### ISSUE TITLE
Download to Remote Server

### ISSUE THREAD

**Issue by ricksee** [inorichi/tachiyomi#1003]
It will probably a niche request, but is it possible to add FTP so we can download manga to a remote server, such as a seedbox for instance. I download a ton of manga and it would help save space if I download them to somewhere else. Then, I can view it from my phone from there.

**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

**Comment by j2ghz** [comment]
Workaround:
Install nginx on the server and use `autoindex on;`
You will then have a website like this https://i.imgur.com/kxc58YI.png
If your manga is correctly placed in the filesystem (e.g. `/somewhere/mangaName/chapterName/001.png`), you can write a very simple extension source for yourself. Making a public one would depend on #1007

**Comment by arkon** [comment]
Don't think this is going to happen.
