### ISSUE TITLE
Error when downloading from Mangahere

### ISSUE THREAD

**Issue by serenajonesthewriter** [inorichi/tachiyomi#1004]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**
This may be related to #997, but I really don't understand any of this. Starting on 9/26/17 all of my library updates are 'queued'. I tried to go to Mangahere directly, but I get the error "java.security.cert.CertPathValidatorException: Trust anchor for..." I get the same error for MangaFox, but not for any of the other English sources.

I'm sorry if I've put this in the wrong place. Please let me know if I should re-posted the problem somewhere else on the site.

Thank you.

By the way, this is the best reader since Mango retired!

**Comment by qwertyuser1983** [comment]
https://github.com/inorichi/tachiyomi/issues/999

I thinks this bug related. :)
