### ISSUE TITLE
Back button opens menu drawer.

### ISSUE THREAD

**Issue by jfields99** [inorichi/tachiyomi#1005]
Currently, back button will take you back one level until you reach your library screen, then it will exit the app. I am suggesting a quality of life feature, where the back button opens the side drawer of menus, and if not available, a level towards a screen where the side drawer is available. Thank you.

**Comment by NoodleMage** [comment]
I will keep this open. But will probably not be implemented because it goes against Android guidelines.

**Comment by arkon** [comment]
No longer relevant.
