### ISSUE TITLE
Page List is empty 

### ISSUE THREAD

**Issue by UVERtainment** [inorichi/tachiyomi#1006]
Hi,

i cant view or download any manga due to this error 'Page List is empty'. (i use kissmanga)

may i know why is that so?

Thank you.

**Comment by NoodleMage** [comment]
**Before reporting a new issue, take a look at the [FAQ](https://github.com/inorichi/tachiyomi/wiki/FAQ)**

##### Q: I'm getting 'page list is empty'
1. Try opening the manga in browser. If there is CAPTCHA, solve it and try again.
2. Change your internet connection ( wifi <--> mobile data or another wifi ), then try again.

If any of the above solves it you are getting a CAPTCHA (or similar) and there is probably nothing that can be done about that. Switch to a different source, use a source less, don't download from the source.

3. Check with other users. If everyone is having this issue, the problem could be that the website changed layout. In that case, open an issue.
