### ISSUE TITLE
SSLHandshakeException when accessing Mangafox

### ISSUE THREAD

**Issue by nokutu** [inorichi/tachiyomi#1008]
I've been getting a Toast message with the exception every time I try to access the Catalog or the Mangas.

I've tested it with version 0.6.3 on my phone and with the master branch version on Android Studio's emulator.

Exception trace: https://pastebin.com/VJHnrfCc

![image](https://user-images.githubusercontent.com/7753959/30988288-47b92c96-a49a-11e7-845a-da1a05c507af.png)

**Comment by inorichi** [comment]
#998
