### ISSUE TITLE
Feature Request: Remember if "Unread" box is checked in chapter list

### ISSUE THREAD

**Issue by katarai** [inorichi/tachiyomi#101]
I'm not sure how relevant it is to others, but I rather enjoy seeing the full chapter list of a manga, regardless of whether I've already read it or not. The grayed out chapter names for chapters I've already completed is more than convenient enough for browsing.

If there was an option to either always show previously read chapters, or to show all chapters by default, that would be amazing.

**Comment by inorichi** [comment]
It's already done. Check debug version.
