### ISSUE TITLE
Mangahere only one page loads

### ISSUE THREAD

**Issue by vampiricwulf** [inorichi/tachiyomi#1012]
Only the first page loads of each chapter.

**Comment by ImposingWaffle** [comment]
I'm having the same issue

**Comment by mrskizzex** [comment]
#997 ths issue was fixed. But then #999 happened and now its fixed but only in dev. Switch to it if you want to use Mangahere.

**Comment by ImposingWaffle** [comment]
I used the patch on #999.

**Comment by inorichi** [comment]
Install the extension at https://github.com/inorichi/tachiyomi/issues/999#issuecomment-333177131

**Comment by vampiricwulf** [comment]
The extension in #999 did not solve the issue.
