### ISSUE TITLE
Enquiry on the downloaded manga status

### ISSUE THREAD

**Issue by blackdevil91** [inorichi/tachiyomi#1013]
Hi,

May iknow is there any downloaded status in my library list. So far, the manga is shown based on which manga we mark as favourites. May i know is there any option or setting to see which manga that i have downloaded so far? i need to resume manga which not downloaded but are in my library.

Thanks

**Comment by j2ghz** [comment]
Duplicate of #826 #895

**Comment by blackdevil91** [comment]
regarding the option under display, i am not able to see any 'download badges'

**Comment by cd0rw0** [comment]
#895  the " download badges" still under in work progress
