### ISSUE TITLE
[Feature Request] Arc Welder fix/workaround

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi#1017]
Hello! I just got around to testing Tachiyomi in Chrome using Arc Welder, and it works excellent! Even with the newer window resize option enabled in ARC.

There is a slight issue with ARC itself that causes all windows when maximized to cut a very small portion of the screen off on the right hand side that doesn't happen when not maximized (even if you spend the time to manually resize the window to that exact maximized size manually). I've tried it on multiple PC's with different APK's, its definitely an ARC issue.

Now this is going to sound ridiculous, by chance would it be possible to add a setting buried somewhere maybe called "Arc Welder Workaround" or something that simply pads the right hand side of the screen by about the same amount as the gap set between the covers when viewing the catalogue?

Even with having to use Chrome/ARC Welder, on Windows tablets/convertible laptops this is still hands down the best way to view manga when compared to all the native Windows apps. I thought if its simple it would be really cool if a workaround for that might be added in so it works perfectly on this platform, even though the issue has nothing to do with this app itself and it would just be working around another piece of softwares issue.

These are 2 pictures showing the right edge when maximized and cut off and then how it should look when just resized manually.

https://i.imgur.com/6I1EQiA.jpg
https://i.imgur.com/j8VmumS.jpg

Thanks!

**Comment by mrskizzex** [comment]
Why do something so workaround like that when there is http://www.cdisplayex.com/ and https://sourceforge.net/projects/hakuneko/ . Moreover i think this is awfully situational and probably only you would use that option which means it's not worth dedicating work for.

**Comment by BaronKrause** [comment]
Ha just tested that new HakuNeko S, it actually seems pretty great, thanks for that. I've used the older version in the past without much luck (only showing partial results for most things) so I had wrote it off.

CDisplayX is pretty much unusable though on modern high res monitors. You either have a blurry screen with normal sized buttons, or disable DPI scaling for that program to get a sharp screen with super tiny buttons. i've been using Pico Viewer lately as it reads CBR and has a webtoon mod that actually works like you would expect.

**Comment by inorichi** [comment]
If this is an issue in ARC Welder, then it has to be fixed there. I hate device specific bugs (looking at Samsung), and I try to fix them if they affects a lot of users. Not only ARC is barely used, but trying to fix something that should be working out of the box is a PITA and not worth looking into. Sorry.
