### ISSUE TITLE
Download Percentage Overflow/Incorrect

### ISSUE THREAD

**Issue by Greenwolf25** [inorichi/tachiyomi#1019]
App Version: 0.6.3
Android ver: 7.0
When reading a non-downloaded chapter and going to the next page the download percentage shows, large negative numbers and not numbers from 0-100.
Source: ReadMangaToday(EN)

![screenshot_20171004-181609](https://user-images.githubusercontent.com/19523350/31207423-031dedd6-a933-11e7-9c77-fbba4eb8f9e8.png)

**Comment by null-dev** [comment]
This is an issue on the server side. The server is not sending the total
image size to the app so the app can't calculate the download percentage
properly.

@inorichi maybe we could have fallback text for these cases so users don't
get confused.
