### ISSUE TITLE
Bug(?): Notifications turn screen on for each manga being updated

### ISSUE THREAD

**Issue by katarai** [inorichi/tachiyomi#102]
**Version:** 0.1.2

**Issue:** Every time the app runs an update cycle, it turns the screen on for each manga it checks. For example, I have 8 manga in my library, so it progresses from 1/8 to 8/8 on the notification bar. Each time the number increases (2/8, 3/8, etc.) as it changes the manga it's checking, it turns the screen of my phone back on.

I'd think it would be best to simply have it turn the screen on when it finds new chapters (since it pops a notification for that, anyway), at the end of its update cycle, but I'm not aware of how simple or difficult that may be to implement.

**Steps to reproduce:**
1) Add multiple manga to library
2) Start an update
3) Turn screen off

**Comment by inorichi** [comment]
I haven't done anything that explicitly wakes the screen. I only update the notification when it completes a manga's update.

My devices don't wake when it's updating. I don't know if there's a fix or it's device specific. I'll try to look at it tomorrow.

**Comment by katarai** [comment]
It could be conflicting with something else on my phone. I tried disabling everything I thought may be causing an issue when I was testing earlier, but I'll give it another go. Hopefully it's just a minor issue on my end.

**Comment by katarai** [comment]
Reinstalled and restarted and it's working normally now. Not sure what the issue was, didn't change anything else. Thanks for looking into it, though.
