### ISSUE TITLE
Allow sorting manga by scanlator group

### ISSUE THREAD

**Issue by harava** [inorichi/tachiyomi#1020]
Hi,

Since some manga have been translated by multiple scanlators, it would be nice to be able to sort chapters by group. Currently, reading through a manga with two different scanlators means you have to constantly skip duplicate chapters.

**Comment by MercerBoi** [comment]
Seconded! This is an awesome idea, would be great if implemented.

**Comment by CarlosEsco** [comment]
@harava @MercerBoi  latest dev now in settings you can click skip mark as read.  Then you can mark the scanlators you dont want read, and read without having to skip duplicates.

**Comment by inorichi** [comment]
Side note: this was already possible if you set sorting mode to "by number" instead of "by source".

**Comment by arkon** [comment]
Merging with #969
