### ISSUE TITLE
Search using Alternative Names

### ISSUE THREAD

**Issue by 2B1Kenobi** [inorichi/tachiyomi#1021]
Some time ago, I searched for Onepunch-Man and the search for Kissmanga only showed ONE's version. Now it correctly shows Murata's version and ONE's version.

I tried to recreate the problem with "Food Wars".
**MangaHere**
![screenshot_20171005-211152](https://user-images.githubusercontent.com/11996112/31229694-2987845a-aa14-11e7-8744-b56798491cc8.jpg)
**MangaFox**
![screenshot_20171005-211216](https://user-images.githubusercontent.com/11996112/31229877-b468ed8e-aa14-11e7-9078-26c8bbc4da35.jpg)
**KissManga**
![screenshot_20171005-211243](https://user-images.githubusercontent.com/11996112/31229991-1c8c446a-aa15-11e7-8d57-98982f2df8fa.jpg)
![screenshot_20171005-211312](https://user-images.githubusercontent.com/11996112/31230000-2279ce88-aa15-11e7-9143-3ac4cd4ba67a.jpg)

Both MangaHere and MangaFox show the correct results, albeit with MangaFox showing a different manga. KissManga on the other hand showed the same lacking metadata as I have experienced before.

I propose making a search through a metadata site for alternative names. And then using those alternative names, perform a search through a source.

**Comment by inorichi** [comment]
That's up to the source. I don't want intermediary services in a search, we would have to make multiple queries, and some sites like Mangafox don't like that.
