### ISSUE TITLE
Top bar/notification bar shows up after leaving app

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#1023]
When reading a manga and i leave the app amd go back to it the top black bar (time, signal notifications) shows up and only goes away with a tap and re-tap. Its faster to back out and tap the last-read button.

**Comment by ShakeBake** [comment]
![screenshot_20171006-102602](https://user-images.githubusercontent.com/29230146/31272113-b17e9688-aa81-11e7-9b62-36a9759cfe1d.png)

**Comment by CarlosEsco** [comment]
version of app?
version of android?
what reader are you using?  (webtoon, vertical etc)
have you tried latest dev build?

**Comment by ShakeBake** [comment]
Always tge latests dev build, android 6.1.1. Using the webtoon viewer but it happens with all the viewers.

**Comment by arkon** [comment]
Sort of related to #2068. I think this is actually an issue with Android, not the app.
