### ISSUE TITLE
"Add to home screen" not working on Oreo

### ISSUE THREAD

**Issue by andreapinardi** [inorichi/tachiyomi#1025]
the function to create shortcuts to specific manga from home doesn't work in Android Oreo. 
I can correctly open the menu in Manga Info, then I can tap on "add to home screen" and choose the shape of the shortcut, but then the activity doesn't switch to the launcher showing the new shortcut. 
At first I thought it was a problem of my launcher but it doesn't work on any launcher I tried (Launcher3, Nova, Google Now)

- Nexus 6P, Oreo 8.0.0

**Comment by NoodleMage** [comment]
Update on this one. It seems that Android O introduced a new Shortcut manager. I already implemented it on my [local branch. 
](https://github.com/NoodleMage/tachiyomi/tree/oreo_fix)
Will need to re-add the features @j2ghz  added to change the shapes on pre Oreo devices. Probably tomorrow.
