### ISSUE TITLE
MangaHere does not download

### ISSUE THREAD

**Issue by vista-narvas** [inorichi/tachiyomi#1028]
version: 0.6.3
build time: sep 11 2017
(from the f-droid strore)
device: jolla (os: sailfish)

sometime ago i wasn't able to download pages from MagaHere
the first page of the chapter loads but everything after does not
if the download starts on the 2nd page nothing loads

refreshing and clearing everything from the advanced menu does not work

older versions also did not work

**Comment by j2ghz** [comment]
Duplicate #999
