### ISSUE TITLE
[Feature Request]  Add Arabic manga sites 

### ISSUE THREAD

**Issue by yshalsager** [inorichi/tachiyomi#1031]
Can you add Arabic manga websites in your app, please?
It'll be great addition for many Arabic users.
Here's some good sites that I know
manga.ae
gmanga.me
mangaforall.com

**Comment by j2ghz** [comment]
Read the contributing guidelines https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md

**Comment by Covide** [comment]
Please add more arbic manga server like(arab maga team) (maga swat)Because they have the best translation and the fastest and many of it and thank you ❤️
