### ISSUE TITLE
[Bug] Notifications sometimes hang indefinitely when updating library in Oreo.

### ISSUE THREAD

**Issue by beepFTW** [inorichi/tachiyomi#1033]
Device: Pixel XL 
OS: Stock Android Oreo (8.0.0)
App: dev build r1246

* Even though it hangs, it still completes the library update. 
* There is no problem with the manga itself, it can be updated manually with no issues. 
* 5th time this happened.

![screenshot_20171012-160850](https://user-images.githubusercontent.com/7910502/31527916-323234f8-af85-11e7-8f85-6be152a18ca2.png)

**Comment by inorichi** [comment]
Did it happen with r1244 too?

Can you try upgrading the importance of the "Library" notification channel? I set it to `LOW` in r1246 because every progress update triggered a sound notification, which is very annoying.

**Comment by beepFTW** [comment]
Yes it did, When I first encountered the sounds popping 3 times every second I though it was hilarious.

But it hasn't hung for a couple of hours now, on either medium or high importance. Will update if/when it happens again.

**Comment by beepFTW** [comment]
Continues to happen, even on high importance.

![screenshot_20171013-112047](https://user-images.githubusercontent.com/7910502/31560445-1d02e12a-b009-11e7-93ce-c430d1ece48f.png)

**Comment by inorichi** [comment]
Looks like they updated again the implementation of the notification manager and they might be dropping an entire series of notifications when too many are posted. I'll have to take a look at the internals to confirm.

**Comment by inorichi** [comment]
By the way, do you have a logcat?

**Comment by beepFTW** [comment]
`10-14 02:07:12.447 W/ActivityManager(1074): Stopping service due to app idle: u0a289 -1m0s661ms eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.data.library.LibraryUpdateService`

Is the error. I'll message you the logcat in discord.

**Comment by inorichi** [comment]
It should work now.

**Comment by beepFTW** [comment]
Works great now. Thanks inorichi.
