### ISSUE TITLE
Unkown Error when loggin ont MyAnimeList

### ISSUE THREAD

**Issue by Basoeckn** [inorichi/tachiyomi#1035]
I cant login to mal anymore, even after updating the app. Other Issues on here boiled down to that, sorry if I missed one where the solution was different

Version: Android 7.1.1
Tachiyomi Version 6.3 (previously on 6.1 unfuntional as well)
Cant acces another device to try from there

**Comment by inorichi** [comment]
Maybe a temporary issue on their end? I just tried and it's working fine.

**Comment by Zyten** [comment]
I can confirm this as well. After several attempts on my device resulting in "Login error", I tried on my PC browser and got "Too many failed login attempts, your IP address has been blocked for several hours." A quick look though the MAL forums tells me that the ban should last 2 hours without any new attempts in-between.

Android Version: 4.4.2
Tachiyomi Version 0.6.3

**Comment by Zyten** [comment]
Just out of curiosity, does your password contain a colon @Basoeckn ? Read through MAL API docs and I believe that is the issue for me. Only found out issue #882 after that 😞. I agree that nothing can be done about it from our end. Sorry for the troubles.

**Comment by Basoeckn** [comment]
After I got it working again a while ago (and forgetting to check my emails, sorry about that), I think it was a problem on MAL's site, as I could not login from the desktop version either a while after I had the issue with the app

**Comment by Zyten** [comment]
Perhaps the issue can be closed @Basoeckn ?
