### ISSUE TITLE
Kissmanga&Mangafox http error 404

### ISSUE THREAD

**Issue by augustfap** [inorichi/tachiyomi#1036]
kissmanga and mangafox blank http error 404, can somebody help me?

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/wiki/Source-problems

**Comment by inorichi** [comment]
You may need to install the mangahere extension (and restart tachiyomi after that). Kissmanga should be working fine, they may have deleted some manga (error 404 means not found).
