### ISSUE TITLE
Can't download or view new chapters from Manga Here

### ISSUE THREAD

**Issue by henryvo62** [inorichi/tachiyomi#1037]
Whenever I try to download from Manga Here I just get an error message. If I view a chapter I have not downloaded from Manga Here the app crashes immediately.

When I try to download the chapter I also get a notification saying 
"unexpected url: //www.mangahere.co/manga/its_not_my_fault_that_im_not_popular/c121/2.html"

It also says it is trying to download the chapter but it does not work and is stuck.

I installed the patch from this https://github.com/inorichi/tachiyomi/issues/999 if that is related.

**Comment by Xenryusho** [comment]
I'm having slightly different and possibly related issues with mangahere (since the last major release, 6.3). When I started a mangahere chapter it loads successfully the first page. Following that, however, it will just stay in the loading state indefinitely for all the following pages.

**Comment by Johndeep** [comment]
With latest F-Droid version 6.3, I also have this strange issue.
Furthermore, it seems all the covers in the overview of Mangahere won't be loaded. Maybe there are some connections between these problems.

**Comment by shimizurei** [comment]
Also having the same issue. I was trying to read Glaucos from mangahere, but it only loaded the first page of the chapter. I switched to the Batoto version and it worked fine. I thought it was just slow to download, but after 20 minutes, nothing had changed. I reinstalled the app using the apk from Github and nothing changed.

**Comment by lynnex** [comment]
I'm having the same issues as Xenryusho and Johndeep.

**Comment by Xenryusho** [comment]
64 release does not fix. Mangahere still unusable.

**Comment by null-dev** [comment]
@Xenryusho Clear your chapter cache in the settings.

**Comment by Xenryusho** [comment]
Worked, thank you.
