### ISSUE TITLE
Correctly Pathed Files Not Being Found

### ISSUE THREAD

**Issue by Bach117** [inorichi/tachiyomi#1038]
Files previously downloaded are not being found even after several reinstalls. They are in the default pathways assigned when they were initially downloaded. Files can be viewed in file storage, so they are definitely still there.

Google Pixel XL

Version 0.6.3

**Comment by inorichi** [comment]
Does it happen for every download, including the ones made within the same installation?

**Comment by Bach117** [comment]
No, it's sporadic. Some things I've never had to redownload and are properly found after reinstallation. Meanwhile, One Peice has been each time. It's deletion is generally what prompts my attempts to reinstall.

**Comment by inorichi** [comment]
What's the source you are using? The titles must match, if the source changes the title of the chapter the folder will be unrecognized next time. The folder should also be renamed when this happens.

**Comment by NoodleMage** [comment]
Any update?

**Comment by NoodleMage** [comment]
No update, closing
