### ISSUE TITLE
Feature request: only update over wifi

### ISSUE THREAD

**Issue by JohnFlowerful** [inorichi/tachiyomi#104]
I believe Tachiyomi refreshes an entire page worth of content to get updates, so it would be a good idea to have an option to limit updates to wifi connections only.

**Comment by NoodleMage** [comment]
<img src="https://cloud.githubusercontent.com/assets/9655378/12764512/81c6ee4a-c9fa-11e5-9515-1e888dc6b694.png" height="600px" />

Isn't this already available?

**Comment by inorichi** [comment]
He means the library update. It should be easy creating a similar class to `SyncOnConnectionAvailable` (from `LibraryUpdateService`) that only triggers on wifi connection.
