### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rCan9** [inorichi/tachiyomi#1041]
There are so many sources. Some are quite quick to update a particular manga but slow (or sometimes never) in updating other mangas. If it could be possible, i would like to request a small feature to combine same mangas from different sources and list it under one name only. It would be great to see chapters just by scrolling side by side for different sources instead of going back and forth between same mangas from different sources. Like, if i add one piece from mangafox and mangasee then it should show only one in the main page. And when i open that, i see 3 tabs: description, mangafox, manga see. Whichever updates first, i could read without having to clutter the favorites page with same mangas from different source.

**Comment by inorichi** [comment]
Similar to #886, answer is still no.
