### ISSUE TITLE
Feature Request: Calendar for chapter

### ISSUE THREAD

**Issue by darkbeast13** [inorichi/tachiyomi#1042]
If possible please add a calendar feature from which we can know when the "new chapter" is gonna be release for the manga in "My Library".
Though we can calculate than on the basis library updates that when the new chapter is gonna be released but sometime there is no new chapter that week or in the next schedule time.
This is just a small request.
If you think this is a good feature please think about it.
P.S : I couldn't find a site getting me detail of the future chapter release date.so don't know even if it is possible.maybe you can find one.
Thanks for the great app 👍

**Comment by CarlosEsco** [comment]
Unless you could find a source for dates i don't think it's really feasible.

**Comment by inorichi** [comment]
Even if there's a site for that, it's not going to be implemented, sorry.
