### ISSUE TITLE
Sharing single picture causes Tachiyomi to crash.

### ISSUE THREAD

**Issue by mrskizzex** [inorichi/tachiyomi#1046]
Version: r1254
Galaxy S5 crDroidAndroid-7.1.2-20171026 LineageOsBased

Long pressing on a picture inside a reader opens a menu, inside that menu there is a share button, pressing on it causes tachiyomi to either crash the reader and go back to chapter view or crash completely and go to launcher.

Tried cleaning all caches and other usual troubleshooting. I tried different manga and it happens in all of them. I can use share menu normally in other apps without any crashes.

**Comment by inorichi** [comment]
Do you have a logcat? Does it make a difference if the chapter is downloaded?

**Comment by mrskizzex** [comment]
https://pastebin.com/UfAT7UTb

Both, downloaded and not downloaded lead to a crash. This logcat is from a downloaded chapter.

**Comment by mrskizzex** [comment]
https://pastebin.com/YCkMYaiD
Another logcat with deepest log level, it turns out if I share not downloaded chapter it works fine. Sorry I said so in previous reply.

**Comment by mrskizzex** [comment]
It works now. Thanks for a quick fix.

**Comment by inorichi** [comment]
I was waiting for the travis build to finish to comment but you were faster :smile: .

Glad it solved the issue.

**Comment by mrskizzex** [comment]
Well, this is awkward. Opening a share menu no longer crash tachiyomi, but it doesn't work either. No matter with what i try to share it with, all apps return something in style of : no file, can't share an empty file, path to file is not valid.

I only checked if the share menu opens but not if it works. Sorry.

**Comment by mrskizzex** [comment]
Logcat of both downloaded and not downloaded share attempt https://pastebin.com/eeUpF3n4
File that is shared if you share a not downloaded chapter https://a.pomf.space/bxchcafnbspp.0
Original filename is e50bcccc626b34a1ba62a45d08cd6774.0
It appears that it's still a valid file because when i changed the extension to jpg it works https://i.imgur.com/QRnaZUD.jpg

**Comment by inorichi** [comment]
Filename is a md5sum of the url plus a ".0" added by the disk cache. It's shared as a`image/*` mime so it's not a problem.

Can you share the logcat of this build? For both downloaded/cached chapters: [app-dev-debug.apk.zip](https://github.com/inorichi/tachiyomi/files/1443319/app-dev-debug.apk.zip)

**Comment by mrskizzex** [comment]
After renaming the file to apk and trying to install it, I cannot because android throws damaged apk error.

**Comment by mrskizzex** [comment]
Logcat of both downloaded and not downloaded share https://pastebin.com/AHqbE7K5

**Comment by inorichi** [comment]
Both the path to the file and the uri to share are correct: 

```
11-04 16:59:46.821 E/ReaderActivity(20885): Uri to share: file:///data/user/0/eu.kanade.tachiyomi.debug/cache/chapter_disk_cache/d4797be73d125c5e1da678a525d80381.0
11-04 16:59:46.832 E/ReaderActivity(20885): Uri compat: content://eu.kanade.tachiyomi.debug.provider/cache_files/chapter_disk_cache/d4797be73d125c5e1da678a525d80381.0
```

I'm starting to think there's something wrong in your ROM, I can't find something wrong in the share code and the paths are definitely correct.

**Comment by mrskizzex** [comment]
I tried downloading stable and it happens there as well. Of course if its downloaded on sdcard it crashes but when its on internal it behaves the same, ie, empty file if downloaded, works fine if cached.

While i don't refute the idea that my rom is causing this (in fact I changed rom from crdroid to viperos yesterday but I didn't check if sharing works so its not relevant) I had not a single instance of not working share in any other app.

This might be one of those bugs that only full wipe and manual restore of everything without restoring data with titanium backup can fix. Unless someone else can test this and input some data if it happens to  them too, you can safely ignore this bug/error  and pin it on rom bug.

**Comment by inorichi** [comment]
Actually the error is there:

`11-04 16:25:19.209 E/FILE    ( 1698): java.lang.IllegalArgumentException: column '_data' does not exist`

In my case, using `setData` does not work, and I have to use `Intent.EXTRA_STREAM`, but maybe using both methods isn't wrong. I'll push a commit.

**Comment by mrskizzex** [comment]
Logcat of new version https://pastebin.com/CJ1QLsCr
Still doesn't work and has a funny side effect of filling gmail recipient with this https://imgur.com/BAgRsZ4

**Comment by inorichi** [comment]
Sorry, I have no clue. I'll keep it open, maybe there's something I'm still missing.

**Comment by inorichi** [comment]
> This might be one of those bugs that only full wipe and manual restore of everything without restoring data with titanium backup can fix. Unless someone else can test this and input some data if it happens to them too, you can safely ignore this bug/error and pin it on rom bug.

Now that I think about it... if you restored the preferences, you may need to set again your downloads directory. With the changes introduced in recent versions of Android you have to explicitly set permissions to folders through the system's directory selector. Try setting again "Custom directory" to the one you are using. It should work after that.

**Comment by mrskizzex** [comment]
Yep, that was it. Everything works correctly now. 

You might want to add an alert for that when you select sdcard as the directory. 
Moreover to actually give permissions to the app you need to "select"  root of the sdcard and then select desired directory. Selecting anything else than root won't give the app proper permissions. 

You should also rollback that change you made to share method because it adds that undesired data to the share in some apps (like gmail).

**Comment by inorichi** [comment]
The system gives you read/write permissions only under the folder you select, but we don't do anything outside the one selected so there shouldn't be a problem.

The problem isn't really SD related, but the SD is one of the exceptions where additional permissions are required and there may be more exceptions in the future. I'd really like to always use the  old `File` approach (all the predefined entries do except "Custom directory"), because using the Storage Access Framework makes disk access really slow (really noticeable when looking up for downloads), but I'm not aware of such a solution, and maybe it's not possible anymore.

I guess this is better explained as an entry in the FAQ, but most people won't read it if so...
