### ISSUE TITLE
Did someone steal your app?

### ISSUE THREAD

**Issue by Chocobubba** [inorichi/tachiyomi#1047]
https://play.google.com/store/apps/details?id=mangareader.mangarock.mangabook&hl=en

This app looks shockingly similar to yours and I'm just curious if they stole it and if so, if you were aware.

**Comment by robkooper** [comment]
The other app that is similar is "Blue Manga" or "Comic: Manga Rock-Manga Online" https://play.google.com/store/apps/details?id=mangareader.mangarock.comicreader&hl=en

**Comment by null-dev** [comment]
How did these even get on the Play Store...

**Comment by ivocarvalho** [comment]
More importantly, how can we report this to Google?

**Comment by null-dev** [comment]
@ivocarvalho At the bottom of the Play Store listing, tap on: "Flag as inappropriate". In the list of options, choose: "Copycat or impersonation" and tap "submit".

The problem is, copying this app may be allowed by this app's license :(.

**Comment by mrskizzex** [comment]
I'm like 99% sure that it's not allowed by apache license.
See point 4 here http://www.apache.org/licenses/LICENSE-2.0

**Comment by null-dev** [comment]
@mrskizzex Nowhere there does it say that binary copies of the app are not allowed. It states:

- You must give anybody who uses the suggests a copy of the Apache license
- If you have modified files, you must indicate you have done so in the **source code**
- You must retain all copyright notices in the **source code** (so if I compile the app, I can remove any copyright notices!)
- If the source code contains a "NOTICE" file, you must follow the instructions in that file and include it in whatever form you are distributing the program in

**Comment by mrskizzex** [comment]
@null-dev Sorry, i kept my reply short and didn't specify what i meant.
I'll be using https://inteist.com/how-to-use-apache-2-0-in-commercial-products-explained-in-simple-terms/ for easier argumentation.
My understanding of that is as follows :
If someone were to copy tachiyomi they can do whatever the fuck they want, charge money, change anything they want as long as they change the name and include clear notice that they are using apache licensed software without proper attribution/recognition.

So i copy tachiyomi, compile it as Generic Manga Reader without changing a thing except the name. I don't have to disclose the source code but i must state somewhere that i used code from tachiyomi and that it's apache licensed.

Those apps failed to do so therefore it is not allowed. That's what i meant.

**Comment by inorichi** [comment]
Yes, they did, and I didn't know until last week, when it was posted on the discord server, but I was expecting it. It's sad, but I won't give them more attention than they should. Not even a GPL3 license would have prevented this, they don't really care. I've already seen some clones of GPL3 projects so... (although it'd help to take down the app from the store). 

The only victims here are the ones who don't know it's a clone of a free app and are using one bloated with ads. That said, those two apps are not even available in my country and I guess they'll be taken down when they get popular.
