### ISSUE TITLE
Blank screen after waking up from landscape mode

### ISSUE THREAD

**Issue by haivp3010** [inorichi/tachiyomi#1049]
**Dev version:** 1264

**Steps to produce:**

1. Open Tachiyomi app.
2. Allow screen rotation and put screen into landscape mode.
3. Lock screen.
4. Unlock screen, the app goes blank with only the title bar left.

This happens for every other main screen, *except for reading screen*.

**Screenshot**
![screenshot_2017-11-03-21-43-37-038_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/7151454/32379512-4e47b2b4-c0e0-11e7-9096-74176bb8856b.png)

**Comment by inorichi** [comment]
It's not an issue in tachiyomi, but in the navigation library [Conductor](https://github.com/bluelinelabs/Conductor/). There's an open issue there and I'm also trying to fix it. By the way, what device are you using? I think this only happens on high end devices (I can only reproduce in a OnePlus 5).

**Comment by haivp3010** [comment]
I am using Redmi Note 4 (Snapdragon 625)

**Comment by haivp3010** [comment]
I tried setting breakpoints at onCreate(), onSaveInstanceState() and onDestroy() and found this wierd scenario:

Without breakpoints when locking device, app flow stopped at "save" and only proceeded to "destroy" when device was unlocked, resulting in a **2+2/3** cycle as in the log below, then app showed a blank screen:

> D/TAG: save
=== UNTIL DEVICE UNLOCK ===
D/TAG: destroy
D/TAG: create
W/PhoneWindow: Previously focused view reported id 2131296456 during save, but can't be found during restore.
D/TAG: save
D/TAG: destroy
D/TAG: create
D/TAG: save
D/TAG: destroy
D/TAG: create

However, **with breakpoints active when locking device and manual continuation at each breakpoint**, a full cycle was executed, and unlocking device then would only trigger activity recreation **once**. In this way, the app resumed just OK.

> D/TAG: save
D/TAG: destroy
D/TAG: create
I/Choreographer: Skipped 116 frames!  The application may be doing too much work on its main thread.
=== UNTIL DEVICE UNLOCK ===
D/TAG: save
D/TAG: destroy
D/TAG: create

I haven't found any clues beyond that yet.

**Comment by inorichi** [comment]
This has been fixed in conductor finally.
