### ISSUE TITLE
Transparently load the next chapter in the view while reading

### ISSUE THREAD

**Issue by icewind1991** [inorichi/tachiyomi#105]
By automatically appending the pages of the next chapter to the list of pages in the reader the chapter boundary becomes transparent and they no longer break the reading flow.

The reader could automatically append the next chapter once you get near to the end of the current chapter and remove the previous chapter once you're a few pages into the next chapter to clean up.

I had a go at this myself and while appending the next chapter worth of pages was easy, getting the reader to properly handle a list of pages that belong to different chapters required to much changes for me to handle (updating the current chapter correctly while scrolling to pages, proper progress bar, etc)

**Comment by inorichi** [comment]
Merged in 2566862
