### ISSUE TITLE
New chapter checking notification lingers on the last manga in library. 

### ISSUE THREAD

**Issue by mrskizzex** [inorichi/tachiyomi#1058]
r1269, android 7.1.2

What I mean by linger is that it stays in the notifications unless I press cancel. 
It only happens to the timer initated check. It dismisses normally when forced.
https://imgur.com/VQAal5p

**Comment by CarlosEsco** [comment]
Are you on oreo?

**Comment by mrskizzex** [comment]
I edited my main post to reflect your questions. I'm on Nougat and it only happens to the timed update.

**Comment by mrskizzex** [comment]
I didn't change anything except installing newer version r1272 and problem disappeared.
