### ISSUE TITLE
Local Manga files in External SD card not being Detected by App

### ISSUE THREAD

**Issue by milomilomilo** [inorichi/tachiyomi#1059]
Hi, I'm having problems with getting my local manga files to show up in tachiyomi from my external sd card. 

Currently, if I add my files to internal storage/Tachiyomi/local, the manga will show up fine in the "Local manga" catalogue. However, if I add my files to sdcard/Tachiyomi/local, tachiyomi will not be able to detect my files and "No results found" will be shown at the bottom. I am using the same files in both instances and I have tried multiple formats such as directories with pictures inside, ZIP and CBZ.

Some additional information:
- I have already granted Tachiyomi permission to access my storage
- The same problem arises when I'm using the dev version of tachiyomi
- The directory for my sdcard is "/storage/0000-0000/Tachiyomi" as shown in the downloads directory

I have actually found another issue that was opened previously which is now closed that have the same issue as me.

https://github.com/inorichi/tachiyomi/issues/791

Unfortunately, I am not familiar at all with coding to understand the solution and nobody in the tachiyomi discord seems to have the same problem as me. So I apologize in advance if I'm breaking any rules here. Thank you.

**Comment by LakotaGray** [comment]
Has this bee resolved for you? With the new implementation of tachi's ability to store anywhere, I'd think it probably has, but wanted to verify

**Comment by milomilomilo** [comment]
Hi, unfortunately not. I still can't see my files from my sd card. It's not showing up for both the dev version and the stable version.

**Comment by inorichi** [comment]
Android version?

**Comment by milomilomilo** [comment]
Android version 7.0, Tachiyomi stable version 0.7.0, Tachiyomi dev version r1379.

**Comment by milomilomilo** [comment]
Hi, this issue has been resolved for me after I flashed a custom rom on my tablet. Thank you!
