### ISSUE TITLE
Custom screen brightness turns screen off

### ISSUE THREAD

**Issue by olo1990pl** [inorichi/tachiyomi#106]
After tapping on the center of the screen when reading manga I checked the box with custom brightness. 
After that I can't read anything, because screen instantly turns off and I need to push power button to unlock the screen. 
Is there an option for set all options to default? Or config file to edit/delete so I don't lose my library? 
I spend more than an hour to add my ongooing mangas. 

Edit: lost library after reinstalling to version from F-droid :-|
Sry for my English and chaotic post.

**Comment by inorichi** [comment]
I've added a switch preference in the settings. My devices don't turn off the screen when it's set at the minimum. Every device does what he wants...

The app from F-droid and my releases have a different sign key, so when you try to install from the other site Android tells you the previous app has to be uninstalled before (thus losing your data).
