### ISSUE TITLE
[Feature request]  Statistics tab

### ISSUE THREAD

**Issue by mrskizzex** [inorichi/tachiyomi#1061]
Low priority but possibly low difficulty to implement as well. 
It would be cool if there would be another tab on the left menu called Statistics.

- You would be able to see total count of various data like : 
- Total manga count
- Total read chapters count
- Manga breakdown by custom cattegories
- Manga breakdown by source
- Stuff about tracking services like average score and the like < kinda redundant with what their websites offer already
- Time spent on reading < possibly detrimental to battery consumption ?
- Pages per minute < possibly detrimental to battery consumption ?
- Maybe some tags pie charts, although that probably is hard to implement due to different tag formatting between sources.

Obligatory : shouldn't be hard to implement so code this tomorrow okay ?
Seriously though, the framework already should be there, only thing needed is some way to show it.

Of course it's just a suggestion. But if you ever feel burned out by harder things (like that search stuff you guys are working on now) maybe try something else for a change and a breather.

**Comment by mrskizzex** [comment]
Stupid github. I searched for statistics but it didn't show any opened issues. When i opened mine, it decided to show it. Gah.

**Comment by wopian** [comment]
Ref: https://github.com/inorichi/tachiyomi/issues/115
