### ISSUE TITLE
[Feature request] Default chapter sorting/filtering

### ISSUE THREAD

**Issue by jasonhpchu** [inorichi/tachiyomi#1062]
Everytime I add a new manga, I tend to change the sort to ascending order (who reads backwards??), and filter to only show unread (new manga, every chapter should be unread to start).  Gets tedious overtime to do this same step everytime.
Perhaps a default setting that I could set in settings, or maybe a global sort/filtering that's applied for all mangas across the board?

Thanks.

**Comment by inorichi** [comment]
#484
