### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi#1063]
after reading 3-5 chapters of some manga the app is getting really slow in loading. this app is in general slow in compairison to other manga app. changing menus or tabs needs loading time, in other apps you dont see or feel the loading from app functions. as for manga chapter load can you make it so that when you read a chapter that it preload all pages at ones? it is kina annoying to wait for the load every page anew.

**Comment by inorichi** [comment]
In loading what? Images in the reader?

You'll need to be more explicit with "changing menus or tabs needs loading time". I don't notice many slowdowns in a >300 manga library with 4 categories with an old Nexus 7 (2013).

**Comment by wopian** [comment]
OPO (2012) has always been instant on changing views with nearly 700 manga. What device do you have & how much free space is left?

**Comment by amboris** [comment]
I am using samsung s5 with 3gig free space and having 60 mbps internet. well this app in compairison with manga reader 2.0 and mangarock is definitve slow (loading images when reading depents on with manga or time cant figue out, loading cover on manga on source when browsing or searching, when you are on search tab and go back to browse mode reload all images at same speed, loading info & chapter info). you allways feel the delay/lagg as every load just load one image/cover at a time.

**Comment by NoodleMage** [comment]
Merging with #1082
