### ISSUE TITLE
[request] platform compairison

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi#1064]
i noticed that some platforms have more chapter than others on some mangas. it would be nice if we could just subscripe for the manga for all platform in one then rather to subscripe it for every platform anew. also would it be nice to see which platform has the most/newest chapters on the manga. 

another feature that would be very nice is the hot/top manga feature/sort from the platform itself since each platform has their own rating it is nice to know whats good/hot when searching for new stuff to read.

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md
