### ISSUE TITLE
"Retry" button on every page when scrolling back to a deleted chapter

### ISSUE THREAD

**Issue by m-vlad** [inorichi/tachiyomi#1066]
If you have Tachiyomi set to delete chapters after reading them and you go to the next chapter, then try to scroll back, you'll see black and retry buttons (which is normal, seeing as the chapter was deleted), but the buttons show up on top of the non-deleted chapters until you exit and reopen the chapter.

**Comment by arkon** [comment]
Can't seem to reproduce in newer versions.
