### ISSUE TITLE
Pixel 2 XL rounded screen edges optimisation for page number.

### ISSUE THREAD

**Issue by TalhaMangarah** [inorichi/tachiyomi#1068]
The page number in the bottom left of the screen gets cut off while reading due to the rounded corners of the Pixel 2 XL screen. I realise this isn't a huge issue but if it's possible to move it a little to the right then that would help to see the numbers a little better.

**Comment by j2ghz** [comment]
Duplicate #1056

**Comment by TalhaMangarah** [comment]
Oh right, sorry about that
