### ISSUE TITLE
Show scanlation group name alongside chapter when using batoto source.

### ISSUE THREAD

**Issue by beepFTW** [inorichi/tachiyomi#107]
This is more of a problem of seeing copies of the same chapter and being unable to differentiate between them. Different groups often use different lingo and it ends up confusing.

You can see this easily when viewing Platinum End on batoto.

**Comment by wopian** [comment]
If this becomes a thing, can it be made optional in the settings?

**Comment by Bloodwork** [comment]
Not sure why would it need to be optional but why not. It's a huge help for series with multiple groups scanlating them. Like Mahoutsukai no Yome's first 10 chapters: http://bato.to/comic/_/comics/mahoutsukai-no-yome-r10801

**Comment by Moravuscz** [comment]
It would also be wonderful if we could filter chapters by scanlation group.
(Not sure if batoto allows empty group, but if so, using uploader's username instead could work)
