### ISSUE TITLE
Number of selected item from User-created Category in Library keep increasing

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi#1073]
Version: 0.6.3
OS: Android 5.1
How to Reproduce:
1) Arrange your item in user-created category
2) Search something in that category
2) Keep selecting items in cycling order

Those items also didn't selected properly. It didn't happened in default category so it's probably you're just missing something for handling user-created categories.

User-created category:
![screenshot_2017-11-22-12-57-01-508_eu kanade tachiyomi](https://user-images.githubusercontent.com/14852623/33112463-f2da4fd6-cf85-11e7-93f7-cc2fddc82a20.png)

Default category:
![screenshot_2017-11-22-13-12-19-400_eu kanade tachiyomi](https://user-images.githubusercontent.com/14852623/33112732-49e98a3e-cf87-11e7-9808-bcd6a14dffdb.png)

EDIT: I do another test to know what's the effect of those selects are and it turns out it become duplicates of same series. Also, whenever you select any of it, the selection square (that blue borders) will points to the first duplicate.
![screenshot_2017-11-24-00-56-38-426_eu kanade tachiyomi](https://user-images.githubusercontent.com/14852623/33185310-484dd3e6-d0b4-11e7-8f3e-eed9f79b23e3.png)

**Comment by atmazzerexe** [comment]
FYI, bug still occurs in 0.6.4

**Comment by atmazzerexe** [comment]
[There you go](https://my.mixtape.moe/uhapxo.mp4). I almost forget how to do it since it's been quite a while lol.

**Comment by atmazzerexe** [comment]
Well, did you notice the numbers of selected items? The numbers just keep increasing. Wasn't the correct behavior is it'll just only selecting one item in the library? I mean, if you do any action to those selections, there'll be duplicates (Or was it the intended behavior?).

Ah, also, the selection box also only showing in one of those selections.

**Comment by wopian** [comment]
I also get these duplication/counting issues with 6.0.1

**Comment by LakotaGray** [comment]
This has been occurring for a number of updates. I noticed but forgot to create issue. But even wirh the increasing number of “selections” I’ve found no adverse or unintended outcomes. Appears to be limited to incorrect count only.

**Comment by LakotaGray** [comment]
I’ve not Experienced the doubling/tripling of tittles like that after the incorrect count selection occurs.
