### ISSUE TITLE
Unknown error while login in to My Anime List in Tachoyomi

### ISSUE THREAD

**Issue by Irohen** [inorichi/tachiyomi#1076]
The title pretty much says it all. I'm using the latest version (0.6.3) but when I try to login to My Anime List to sync it, but it always says "login error" and "unknown issue". Yet I'm sure I am entering the right login infos.

**Comment by j2ghz** [comment]
Could it be #882 ?

**Comment by Irohen** [comment]
No, there is no : in my password.

**Comment by Jayjader** [comment]
I'm getting this same issue on my OnePlus One with CyanogenMod 13. I also don't have a semicolon in my password.

**Comment by AmineI** [comment]
Due to the MAL API fiasco, the MAL implementation isn't the same as before and this can't be exactly reproduced anymore I believe. Is this still happening in the current workaroundish implementation ?

**Comment by arkon** [comment]
Someone had success trying to change their password. Their old password worked when they changed it back too, so it could be an issue with cookies.

**Comment by pratapghanta** [comment]
For me the first time login works for My AnimeList. However from the second time, I keep getting "Unknown Error" (Authentication Error). 

The workaround in my case is to delete the cookies from "Settings > Advanced > Clear Cookies". If I try to login after the cookies are deleted, the login process completes successfully.

**Comment by arkon** [comment]
I believe this was fixed with #2042
