### ISSUE TITLE
Clickable authors / artists / genres fields in info tab not working

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#1077]
I thought #860 by @QuestofIranon was implemented with global search time ago. I don't know if it has not been done yet or if there is a problem.

Thanks!.

**Comment by 444nonymous** [comment]
Related to https://github.com/inorichi/tachiyomi/issues/1079 "Advanced search in globlal search", since "Clickable authors / artists / genres fields in info tab"  could open a global search.

**Comment by NoodleMage** [comment]
Not yet implemented. Makes it duplicate of #860
