### ISSUE TITLE
Advanced search in globlal search

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#1079]
Could it be possible to add the individual catalog icon for advanced search also in global search? So, you could also global search by author. 

I understand that global search by genre is also useful for obscure genres with few mangas, or trying to find mangas using a combination of several genres. IE: Drama + Seinen + Sci-Fi + Psychological. Results: "Akira" and similars.

This also relates to the "Clickable authors / artists / genres fields in info tab" option what could open a global search -> https://github.com/inorichi/tachiyomi/issues/1077

Thanks!.

**Comment by arkon** [comment]
This is dependant on the extensions' search functionality.
