### ISSUE TITLE
Cyanogenmod 12/13 bootloop

### ISSUE THREAD

**Issue by AnotherPony** [inorichi/tachiyomi#1081]
Look, there is a problem with cyanogen mod ROMs right now.
https://issuetracker.google.com/u/2/issues/64434571
Your last update v0.6.4 causes bootloop on my phone.
To fix this problem you need to add `android.enableAapt2=false` into your `gradle.properties` file.
Thanks to your open source code - I build my own app with this string and everything works fine.
Android studio developers promised to fix this bug in next update, but right now it's the only solution.

Fix it or not - your choice. But there is a lot of people who use CM ROMs.

**Comment by Zaneo** [comment]
I feel like this should be a bug report for CM. Nonetheless nice find on the work around.

**Comment by inorichi** [comment]
This should have been fixed with the use of the builds tools v27. Please confirm.

**Comment by AnotherPony** [comment]
@inorichi yup, everything works great on `builds tools 27.0.1`.
Please, use this version for the next update.
