### ISSUE TITLE
Batoto login issue

### ISSUE THREAD

**Issue by SDMU** [inorichi/tachiyomi#1087]
![This is what is being shown when I try to login](https://i.imgur.com/wHRHB9m.jpg)

And yes , I can login to Batoto perfectly well via a browser .

**Comment by dobbleg1000** [comment]
I experienced this as well after I tried to relogin because Batoto was giving me a 503. I can login through a browser as well.

**Comment by Sarkazein** [comment]
I noticed when I went to Batoto in the browser I had to go through a cloudflare ddos protection page first.  I wonder if the app is getting stuck on that...

**Comment by dobbleg1000** [comment]
That could be I remember mangafox(?) having an issue similar to this in the past. What fixed it was going to the page once from a different browser on the device.  That doesn't seem to fix it this time.

**Comment by atmazzerexe** [comment]
Recent DDoS attack makes batoto use their Cloudflare anti-DDoS feature, so please implement cloudflare bypasser on batoto too.

**Comment by Pizz001** [comment]
i have the problems ( or close to it) with saved manga, i have to go in clean the system and research for the manga and add at least back in once from my saved library, then they all seem to work again

**Comment by dobbleg1000** [comment]
Im now 100% sure the issue is cloud flare. I decided to a build myself and was able to resolve the issue by copying "import okhttp3.OkHttpClient" and "override val client: OkHttpClient = network.cloudflareClient" from Kissmanga.kt to Batoto.kt

**Comment by Sarkazein** [comment]
Can confirm, I've done the same upgrade and can access Batoto again.

**Comment by SecT0uch** [comment]
When can we expect to get the fix within the stable release?
