### ISSUE TITLE
Unknown Error when trying to log in to Batoto.

### ISSUE THREAD

**Issue by kevinmreyes** [inorichi/tachiyomi#1090]
Using version  0.6.4. Whenever I try to update, open, or download a chapter from Batoto, I get an error 503. So, I decided to try re-logging into Batoto on the app but every time I try to do so the button just turns red, the login text changes to "Unknown Error" and a small message appears with the error:

"Attempt to invoke virtual method 'java.lang.String
org.jsou.nodes.Element.attr(java.lang.String
)' on a null object reference

**Comment by j2ghz** [comment]
#1087 #1089
