### ISSUE TITLE
Colour of Unread and Downloaded Badges

### ISSUE THREAD

**Issue by Arkonos** [inorichi/tachiyomi#1091]
I find the colours of the Badges not very pleasing. They are too bright and thus draw too much attention, especially compared to the sublte grey text in 0.6.3.
I'm not good with colours, but I made a mockup of a possible alternative.

![badges_colour](https://user-images.githubusercontent.com/3932266/33336228-8b1299d2-d46f-11e7-9cdc-c6a9057d90f6.png)

I left the bottom two rows as is for comparison.
The colours I chose are the blue of the top bar. For the red I chose a colour inbetween that blue and the bright red. (Blue: 54759e, Red: 89423d) I like my changes for the dark theme, they also mostly work for the amoled theme, but are too dark for the light theme. If you want to keep one colour for all three themes, maybe something like a light brownish red (93716f) could work instead.

**Comment by 444nonymous** [comment]
You are using list wiew. Icons are shown over black or white. Easy. Now try grid view and icons have to be shown over colorful covers.

The icons have to be bright and are not really distracting. Color preferences are another thing and not really that important one way or another.
