### ISSUE TITLE
Batoto login issue

### ISSUE THREAD

**Issue by Bdren** [inorichi/tachiyomi#1094]
When trying to login in to batoto or on a device in already logged in I cannot access their content if on a device in already log in o get http error 503 and when I try to log in I get ( attempt to Invoke  virtual method java.Lang.script org.jsoup.nodes.node.stir(java.Lang.string) on a null object reference. I reid on Wi-Fi and LTE

**Comment by dobbleg1000** [comment]
This is fixed on the Dev branch. No ETA for the stable. To switch you can do a backup of the stable and restore it on the Dev to preserve your library and some settings. Make sure you login to Batoto and Tracking before the restore.

**Comment by dobbleg1000** [comment]
See Issue #1084
