### ISSUE TITLE
Can't login or view Batoto and ReadComicOnline on 1 of my tablets (0.6.5)

### ISSUE THREAD

**Issue by Dotsquall** [inorichi/tachiyomi#1095]
I have 2 tablets, my brother uses 1 of them. Today I tried to install ReadComicOnline on the one he uses but I get HTTP error 503 when trying to check it, I also noticed Batoto doesn't work on that tablet, I get Unknown Error when tryng to login.

On the tablet I use everything works just fine.

**Comment by NoodleMage** [comment]
which version?

**Comment by NoodleMage** [comment]
https://github.com/inorichi/tachiyomi/wiki/Source-problems

**Comment by Dotsquall** [comment]
Just went trough the Source Problems page. I checked both Batoto and ReadComicOnline in the tablet browser and no captcha, it worked just fine there. I also restarted my connection and the problem persist.
I also don't think it was an IP ban since I have static IP in my router and all my devices would have been affected.

**Comment by inorichi** [comment]
Advanced > Clear cookies?

**Comment by NoodleMage** [comment]
Did clear cookie work?

**Comment by Dotsquall** [comment]
Sorry for the late answer, I was in place with no connection for some days.

And yes I've tried that, I've tried every option in the options menu and the problem still persists on that tablet.

**Comment by inorichi** [comment]
Please use the extensions repository for catalogue issues.
