### ISSUE TITLE
Options menu in chapter view contains menu entries from library view

### ISSUE THREAD

**Issue by ddmgy** [inorichi/tachiyomi#1096]
Version: 1288 (Issue does not appear in releases before 0.6.5)
OS: Tested on Android 5.0, 6.0.1, and 7.0

When opening a manga, the [chapter options menu](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/res/menu/chapters.xml) also contains the menu entries for the [library options menu](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/res/menu/library.xml).

Below are screenshots showcasing the issue:

> Overflow menu showing Filter, Update library, and Edit categories entries in chapter view.

![screenshot_20171129-150658 2](https://user-images.githubusercontent.com/6520686/33397712-8731547e-d51a-11e7-9d34-67a11a676f9a.png)

> Search icon on toolbar in chapter view.

![screenshot_20171129-151815 1](https://user-images.githubusercontent.com/6520686/33397803-d0b3be16-d51a-11e7-99d3-b9ab52bb8613.png)

-----

Interacting with these entries works, but does not always produce the same behavior as in LibraryController.

- Clicking the Search icon expands the SearchView, as it does in LibraryController, but entering text does not filter the chapter list.

- Clicking Filter does not do anything visually, but it may be opening the secondary drawer (navView) of LibraryController, which is hidden by ChaptersController.

- Clicking Update library does what is expected, it starts updating the library.

- Clicking Edit categories will launch CategoryController, but it will be shown over the LibraryController, as seen below. You can still select, move around, create, rename, and delete categories, but it is all drawn over the list of manga. Navigating up the stack returns to ChaptersController.

> Clicking Edit categories from chapter view menu opens CategoryController over library view.

![screenshot_20171129-151833 1](https://user-images.githubusercontent.com/6520686/33398296-7e0347b6-d51c-11e7-8c2d-4049872bb858.png)

-----

There is [an issue (371)](https://github.com/bluelinelabs/Conductor/issues/371) from October in Conductor that I think shows the same bug.

Also, to show that the menu entries have not always carried over from the parent Controller, below is a screenshot of the same menu in a dev version (I don't remember which one it was) in August this year, which shows only the entries defined in res/menu/chapters.xml.

Edit: I can also confirm that this behavior is not present in a release as recent as 0.6.3. ~~Haven't tried 0.6.4 yet.~~ Also not present in 0.6.4.

![screenshot_20170809-150251 1](https://user-images.githubusercontent.com/6520686/33398736-fb640c44-d51d-11e7-973c-b98cb8d58f67.png)

**Comment by inorichi** [comment]
Thanks for the detailed issue.

It wasn't Conductor's fault but mine. I shouldn't have used the change handler, but the retain mode. The first one should only be used for popups like dialogs.
