### ISSUE TITLE
MAL Score in Info Page

### ISSUE THREAD

**Issue by MaskedPierrot** [inorichi/tachiyomi#1099]
Would it be possible to integrate the overall MAL score for a series in it's `info` page? That way we could know how good(or popular) a series is without having to actually check MAL.

**Comment by Sparh4wk** [comment]
@MaskedPierrot you need to check how popular manga is to read it? thats sad.

**Comment by dobbleg1000** [comment]
The biggest problem with this is the names that are used don't always match the tracking service. Even if you already use the tracking service you are still the one who decides what manga matches,

**Comment by inorichi** [comment]
Nope, sorry. Info will only be affected by what the source gave us. There are many problems to workaround so it's not worth.
