### ISSUE TITLE
Feature Request: Download All for a manga, Mark as read and Download in the recent chapter

### ISSUE THREAD

**Issue by IceKreem** [inorichi/tachiyomi#110]

**Comment by wopian** [comment]
You can already download/mark read on all chapters by long holding a  chapter, pressing the 3 dot menu and tapping select all.

Then to download all click the download icon and to mark all as read press the menu icon again.

**Comment by IceKreem** [comment]
For the 'mark as read' you cannot mark as read in the recent chapters )which was what I was talking about). Additionally, you cannot download all manga but only Mark all manga as read and would have to download them individually (even when all the chapters are selected).

**Comment by inorichi** [comment]
I'm pretty confident the download selected button should work fine. Sometimes the UI doesn't refresh and they don't show up as "queued" until you go back, but they are queued.

**Comment by IceKreem** [comment]
Where is the download selected button? 
![screenshot_20160203-170131](https://cloud.githubusercontent.com/assets/15200832/12789943/d9758c44-ca97-11e5-92d8-e0787901ced5.png)

**Comment by inorichi** [comment]
At the top, the download icon.

**Comment by wopian** [comment]
The first icon at the very top (underscored down arrow) is the download icon.

**Comment by IceKreem** [comment]
Yeah but that doesn't download all of them (well not for me anyway)

**Comment by wopian** [comment]
And by the 3 dot menu, I meant the vertical dots not the horizontal one.

**Comment by IceKreem** [comment]
sorry I know what you mean now, my bad :(

**Comment by inorichi** [comment]
The row menu only applies to that single chapter regardless of the selected ones.

**Comment by IceKreem** [comment]
Yeah that's what I was doing and was wondering why it wasn't working. LOL rookie error ._.
