### ISSUE TITLE
The walmart giftcard

### ISSUE THREAD

**Issue by dar090** [inorichi/tachiyomi#1103]
this stupid link that I can't click out of made me lose my spot in a book so please stop sending or I will never use this website again on readcomicbooksonline.net!!!!!!

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md

**Comment by inorichi** [comment]
I don't even understand what you're talking about. Anyways, closing as invalid because it doesn't follow our guidelines.
