### ISSUE TITLE
Local manga appears in app, but "page list is empty"

### ISSUE THREAD

**Issue by TakaiSaisei** [inorichi/tachiyomi#1105]
I have placed my manga in `Tachiyomi/local` folder and it appeared in app, but I can't read it cause it says that page list is empty. I realized that this was due to maybe some specific folder tree, it looks like `PandoraHearts\01\001` where 01 is volume and 001 is chapter. Numbering for frames in each following chapter starts from 001, so for me it will be really hard to rename all images for storing it in one folder. Maybe you can fix it?

![screenshot_2017-12-03-04-42-02](https://user-images.githubusercontent.com/34200381/33521528-f3228636-d7e4-11e7-80a9-74582a42322e.png)

**Comment by LakotaGray** [comment]
I believe your issue has to do with Volume/chapter labeling. From personal experience, volume labels like that, or the subsequent file tree doesn’t work. Try erasing volume altogerher, and just going PandoraHearts\001\ images
I believe the way Tachi reads the page list is from series titles, the next is chapter followed by images. If you have additional folder, it doesn’t go deeper and just sees empty page list. 
IF volume info is important to you, you can label the chapters as 1.1 , 1.2, 1.3 for vol 1 ch 1, vol 1 ch 2 etc
