### ISSUE TITLE
Crash related to rotation

### ISSUE THREAD

**Issue by gian8989** [inorichi/tachiyomi#1109]
I don't know if this will help to reproduce the crash on other device.

device: Samsung galaxy Tab S 10.5
OS: android 6.0.1

- open app in horizontal
- open last chapter of a manga (tried on mangafox and mangahere)
- rotate in vertical (using sensor)
- go to last page and try to go to next chapter
- press back button
- app crash ("Unfortunately Tachiyomi has stopped") 

I hope it helps.

**Comment by greensad** [comment]
I usually keep the orientation locked to landscape when reading manga and constantly experienced this problem when I was done reading but couldn't figure out why until I tried reading unlocked today. Crash is especially annoying at the end of a 300 page chapter, I'm glad I wasn't the only one experiencing this!

**Comment by inorichi** [comment]
It has been fixed already. There will be an update soon.

**Comment by gian8989** [comment]
Good to know.
I didn't see anything related in issue section so I wanted to report it.

**Comment by greensad** [comment]
You guys work fast! Very impressed with Tachiyomi's update cycle!
