### ISSUE TITLE
Recently read tab

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#111]
Now that I've used Tachiyomi for awhile I often find myself in need of a Recently read tab, that lets me see the latest chapters I've read for each series.

Check out Manga Rock's "Recents" tab or Manga DLR's "Recently read" tab for similiar functionality.

**Comment by IceKreem** [comment]
What version are you on? This feature has been implemented.

**Comment by inorichi** [comment]
I think he means an history of reading.

**Comment by Bloodwork** [comment]
Yes, I meant the history of my own reading instead of the latest updates from sources.
