### ISSUE TITLE
`Could not find manga` during restore only

### ISSUE THREAD

**Issue by jsilvermist** [inorichi/tachiyomi#1113]
I regularly use backup and restore to sync multiple devices, but since the 0.6.6 update I'm getting between 20-40 `Could not find manga` errors per attempt, some seem to work if you try multiple times, while some won't work at all.

Note: The manga's that it says `Could not find manga` about can be found and viewed fine when browsing the `Library` or `Catalog`.

Note 2: The majority of issues seem to be with Mangahere mangas, but not exclusively.

**Comment by NoodleMage** [comment]
It has to do with the tracking. Are you logged in to the tracking services?

**Comment by inorichi** [comment]
But is the manga restored despite the error?

**Comment by jsilvermist** [comment]
After further investigation it would seem that the chapters are synced properly even when the error is thrown for a certain manga.

It's possible that it has to due with a rate limit or something similar, as while initially restoring the library from a clean slate which takes quite a long time, no errors occur (Very small sample size so this could have just been luck though).

When restoring my library over an existing library to update chapters and add new mangas, the log is flooded by this error. It's hard to say how high the percentage of failure is though, as my library consists of ~370 mangas, but only a much smaller number actually has tracking enabled, and with that I'm getting about 30-40 failures on average per restore.

**Comment by jsilvermist** [comment]
One question here though, is should it still be trying to find the manga name if it's already registered? After the initial import, should it still be trying to find the manga in the tracking service for ones that are already registered?

**Comment by arkon** [comment]
Super old and restoring has changed since. Closing.
