### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Nishant21Hada** [inorichi/tachiyomi#1114]
I restored my library using a backup.After it finished,there were some errors like manga not found and a log file opened in chrome.But I accidentally closed it and can't find the file.Where I can find that file so that I can know what manga didn't get restored?

**Comment by NoodleMage** [comment]
Sorry for the late response. 
It should be in the external cache directory (I think "/Android/data/eu.inorichi.tachiyomi/cache"). But the change exist that it's already removed because it's only meant to be there temporary. The file name is: tachiyomi_restore.log
