### ISSUE TITLE
page share not working

### ISSUE THREAD

**Issue by noobfag** [inorichi/tachiyomi#1115]
version 0.6.6
build 6 dec 2017

page share function not working
when tried to share to whatsapp,telegram / other apps, either black screen showed or "sharing failed".

**Comment by NoodleMage** [comment]
Android version? Do you use a ROM?

**Comment by noobfag** [comment]
mine using 5.1.1
i did asked around,few my friends running 6.1 and 7.1.1 also have the same
problem..all of us using stock rom

On 11 Dec 2017 21:55, "Bram van de Kerkhof" <notifications@github.com>
wrote:

Android version? Do you use a ROM?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/inorichi/tachiyomi/issues/1115#issuecomment-350730755>,
or mute the thread
