### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#1116]
Can you please add something like read from last unread chapter to latest updates as well? 

I know this feature is in library when you are at chapter view, but is it possible to add it to latest updates as well?

 cause now I must check manga first if I read all previous chapters so I can read the new one or not..   or maybe there is better way like graphics mark etc.. thanks

**Comment by NoodleMage** [comment]
Duplicate of #963? If I'm wrong please reopen
