### ISSUE TITLE
Problems downloading multiple issues

### ISSUE THREAD

**Issue by nandito104** [inorichi/tachiyomi#1118]
Currently I'm trying to download an entire series and keep getting a "timeout" error. The only workaround I've found is pausing the download and starting it again to fix this.

**Comment by cd0rw0** [comment]
from my experience this is because app being shutdown by android doze.
so to whitelist just turn off "battery optimization"  for tachiyomi in phone setting.

**Comment by NoodleMage** [comment]
Did the solution by @cd0rw0 work? Also next time please include app version and Android version

**Comment by nandito104** [comment]
It worked, thanks. I'll keep that in mind for the future.
