### ISSUE TITLE
Using "Export" After Backup Creates Empty File

### ISSUE THREAD

**Issue by Flat** [inorichi/tachiyomi#1120]
If after creating a backup you tap export and overwrite the default restore made the file will be truncated to 0 bytes. Effectively destroying the backup.

Revision 1301

**Comment by Flat** [comment]
Just retraced my steps, this isn't a bug with tachiyomi and is likely a bug with my file manager. Sorry about that.

**Comment by NoodleMage** [comment]
No problem. Thanks for the update 🥇
