### ISSUE TITLE
ComicVine support ?

### ISSUE THREAD

**Issue by cojoMan** [inorichi/tachiyomi#1125]
As someone who reads mostly western comics with one of the provided catalogues, I find tracking with the 3 supported services at this time lacking. Could it be possible to add a service that tracks western comics, like GoodReads, or comicVine ? Any other would be fine as well.

Thanks !

**Comment by NoodleMage** [comment]
I did a bit of research for you. Correct me if I'm wrong

Comicvine:
Doesn't seem to have tracking functionality (at least not the API).
Goodreads:
Seems to sort by volumes not by series.

I also found leagueofcomicgeeks.com. But they don't seem to have an API and also group by volume. 

If someone is interested or has a better suggestion be my guest but I don't think implementing these services is feasible.

**Comment by cojoMan** [comment]
Seems to be about right - does anyone else want to pitch in ?

**Comment by sahil-mohd** [comment]
[ReadComicOnline](http://readcomiconline.to/) has a similar feel to KissManga. Why not take a look at that?

**Comment by cojoMan** [comment]
That is the catalog, and it is only present in Tachiyomi as such.
I asked about a service for TRACKING, and RCO does not have an api for integration - it's just a depository as far as I can tell.

**Comment by CarlosEsco** [comment]
@cojoMan  probably didnt see my discord yesterday but without an API for tracking this more than likely won't be happening.

**Comment by inorichi** [comment]
Following @NoodleMage's comment and the lack of API, I don't think it's worth investing time into, so I'm closing.
