### ISSUE TITLE
Possible to change image server used when reading from Batoto? 

### ISSUE THREAD

**Issue by kevinmreyes** [inorichi/tachiyomi#1126]
Tachiyomi version 0.6.6.

Been noticing lately that Batoto has been slower than usual when browsing through the app. I was curious so I decided to try it out in my phone's browser as well and saw that it was slow there too. But the browser version of Batoto has the option to change image servers and, upon switching to a different one, the pages loaded much faster than before. 

So is there a way to do this within the Tachiyomi app itself?

**Comment by CarlosEsco** [comment]
can you screenshot the option on the website?

**Comment by inorichi** [comment]
Closing this one.
