### ISSUE TITLE
Updating from F-Droid after installing from repo release

### ISSUE THREAD

**Issue by Enamex** [inorichi/tachiyomi#1129]
Right now I have an oldish (~2 months old) dev version installed as downloaded from this repo release.

I recently began to use F-Droid to replace some of my old apps with its alternatives and wanted to update Tachiyomi through there as well. Only the non-dev version was available. Today I remembered to check the repo and and someone is graciously offering dev builds through a repo on F-Droid.

So the situation again (haven't tried but would expect the same situation with the non-dev version):
1. I have an old dev version installed manually.
2. Have F-Droid and want to install `Tachiyomi (dev)` from J2ghz's F-Droid repo.
3. F-Droid says the installed version has a different signature and cannot be directly updated.

Thank you!

**Comment by cd0rw0** [comment]
Hi 

You can't update f-droid on top of app download frm here for Official and dev version. 
You need to uninstall your current app then install f droid ver.

Btw Dev ver is in F droid for long time maintain by j2ghz.

**Comment by inorichi** [comment]
You'll have to create a backup, uninstall one version and install the other. There's no way to bypass a signature change, it's enforced by Android.
