### ISSUE TITLE
Source Wiemanga can't load any pages properly

### ISSUE THREAD

**Issue by Freakmiko** [inorichi/tachiyomi#1131]
The German source "wiemanga" won't download any pages from any chapter anymore. It'll only show the image below for every page.

To reproduce this, open any manga from the German "wiemanga" source and try to read a chapter.
I suspect they're doing something weird as you can reproduce this in a browser by just copying the link to a chapter and pasting it in a new tab or in another browser (maybe cookie or referrer or something).

Version: Tachiyomi v0.6.6
Tested on two different devices.
![Image of the missing page](https://user-images.githubusercontent.com/2048635/34122766-ce843b1c-e42d-11e7-92ba-d7a536eb8d6f.png)

**Comment by CarlosEsco** [comment]
Weirdly enough even on desktop i get this if i go directly to a page.
for example
https://www.wiemanga.com/chapter/Kalender2013/191001/

**Comment by Nonononoki** [comment]
Can we get another German source?

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md#catalogue-requests

**Comment by CarlosEsco** [comment]
This can be closed.  Download the external extension
1.2.0 

ih app or in the extension repo.

https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk
