### ISSUE TITLE
Mangahere changes it's domain to mangahere.cc

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi#1133]
Just like the title implies. It's so ridiculous when they don't even port the mobile site to the same domain too (It's still m.mangahere.co last time I checked).
Story short, please change every link from mangahere.co to mangahere.cc.
Thank you.

EDIT: Looks like they decided to use those two domain for desktop browser use (mangahere.cc) and mobile browser (mangahere.co)

**Comment by pokhym** [comment]
Did this render your Mangahere catalogue empty?  Cause I can't find any new manga from the mangahere catalogue

**Comment by inorichi** [comment]
The extension is still working so I'm closing this.
