### ISSUE TITLE
reader skips pages when using a bluetooth remote

### ISSUE THREAD

**Issue by zrouda** [inorichi/tachiyomi#1135]
I've tried multiple remotes and they all work well with perfectviewer and other readers, Tachiyomi always skips a page (it used to work fine in a previous version) see video for example of the issue 

https://www.dropbox.com/s/ds2migeh2vsl5t0/VID_20171227_215227.mp4?dl=0

**Comment by inorichi** [comment]
Can you try the latest dev version? I think this has been fixed but I can't test if I don't have that bluetooth remote.
