### ISSUE TITLE
Marking chapter as read ignores deletion options.

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#1136]
App version: 0.6.6
Android: 8.1.0 OPM1.171019.011
Phone: Pixel 2

Manually marking downloaded chapter as read deletes the chapter. For example in case of a new chapter i have read on the pc I have one unread downloaded chapter and one downloaded read. Marking the unread chapter as read deletes the chapter leaving the second newest downloaded.

I have deletion options set so that the last released chapter is kept downloaded, but this deletes the last chapter and leaves previous chapters.

[Video](https://streamable.com/iszwm) showing the issue

**Comment by arkon** [comment]
This should be fixed now.
