### ISSUE TITLE
Visual Reference to Tracking Service in "My Library"

### ISSUE THREAD

**Issue by lordbk** [inorichi/tachiyomi#1147]
Dear All, [feature Request]

i would like to request simple visual reference in "my library" for synced tracking service. 
i did simple MS mock up of my visualization of this request, maybe others can come up with better ideas.
i did this way to make at as simple as as possible without cluttering cover. 
Hope any dev/contributor can consider this request.

Colour Reference ( as per their logo colour)
Blue - MAL
Red - Kitsu
white & Blue - Anilist

<a href="https://ibb.co/nH3RBb"><img src="https://preview.ibb.co/mjTtrb/Screenshot_20180105_100738_1.jpg" alt="Screenshot_20180105_100738_1" border="0"></a>

**Comment by zunjae** [comment]
In general I'd advice against color coding functionality due to UX reasons.

**Comment by wopian** [comment]
I don't see this working for the list view either. 

Would be better to be able to filter your library by trackers (None, AniList, Kitsu and MAL)

**Comment by cd0rw0** [comment]
hi @zunjae  @wopian 
this is just an idea...
List view - I dont see reason why it wont work in list view. it can have 3 dot next to unread badge.
filter by tracker (4 option) will make filter option long. i dont think dev will agree to that.

**Comment by LinkCable** [comment]
Hmm, off the top of my head I would think using the favicons would be good, but would probably get too low res. Another option could be shapes (triangle, circle, square) with the colors, but it'd still be iffy how to communicate to the user which means which.

**Comment by j2ghz** [comment]
What is the use case for this? I can only think of going through all your manga that e.g. doesn't have a binding to MAL, to bind them. For that filters would be much better I think.

**Comment by cd0rw0** [comment]
@j2ghz im not against filter option. what i mean was, filter list will become too long if have 3/4 option as per above suggestion. (AniList, Kitsu and MAL)

**Comment by LinkCable** [comment]
>@j2ghz im not against filter option. what i mean was, filter list will become too long if have 3/4 option as per above suggestion. (AniList, Kitsu and MAL)

I don't think it will get too long, I mean if you look at the filters for various catalogues there are so many genres and it's still fine.

Also we plan to make the filters in your library collapsable by section like the filters in Catalogues, so you could just collapse all until you get to the "tracking" section or something.

**Comment by inorichi** [comment]
I don't see any good reason to have this visual reference in the library.

**Comment by as280093** [comment]
Hey Guys, Is Anyone Working on this Request Because i too faced the issue to find which i am tracking or which not plz guys its over a year
