### ISSUE TITLE
Limit Mangafox simultaneous downloads to 1 (override global value)

### ISSUE THREAD

**Issue by RobotoDroid** [inorichi/tachiyomi#1149]
When attempting to download from Mangafox provider using more than 1 simultaneous threads will result in a huge amount of 503 errors as the website refuses to serve more than 1 request at a time. A solution to this problem would be to limit the downloads from the specific host to 1 thread. This is an issue when downloading many chapters at once for example.

I can see a solution to this problem. Allowing the user to select max simultaneous downloads per source in the "Catalogue" menu by clicking and holding the host.

**Comment by inorichi** [comment]
In fact I think I'm going to remove the possibility to download more than one at once. Most sites don't like that and are the source of many of the issues people have.

**Comment by inorichi** [comment]
7b4ac79
