### ISSUE TITLE
Bug: Batoto images aren't loading

### ISSUE THREAD

**Issue by jake2034** [inorichi/tachiyomi#1151]
I'm using the latest version (0.6.6).

In between chapters, they just stopped loading. This is across multiple titles, and other sources work fine.

**Comment by LinkCable** [comment]
Just note, [Batoto will be closing permanently](https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/) so unless the site domain is transferred and someone creates a mirror I doubt this will be addressed.

**Comment by Gameaday** [comment]
Batoto servers are down,  the issue you have is not with the app.

**Comment by jake2034** [comment]
Damn. Guess I'll have to find a second best.

Thanks guys.
