### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by ScorpiotheVenom** [inorichi/tachiyomi#1153]
For the past three days I have been trying to read any manga chapter on mangaseeonline.us, but every time I click on the chapter to advance from page one to page two but all I keep getting is two blue dots going back and forth and not loading the page. I waited as long as thirty minutes and still got nothing. Has anyone else had this issue and can hopefully provide a solution?

**Comment by CarlosEsco** [comment]
Please edit with following info: 
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md

Further questions i have
Do you have this issue on any other source?  
Are you able to view and read chapters on your web browser on your phone? 


I just went to a random manga on latest dev and had no issue getting into chapter list clicking chapter and starting to read it. So you might want to try these 
https://github.com/inorichi/tachiyomi/wiki/Source-problems

**Comment by ScorpiotheVenom** [comment]
All right I looked up the Source problems and found my answer, it was actually due to my security that I was unable to go to the next page. Thanks for the help CarlosEsco.
