### ISSUE TITLE
Change visuals of Library Filters for better UX

### ISSUE THREAD

**Issue by LinkCable** [inorichi/tachiyomi#1157]
Currently, the Library Filter menu differs visually from the Categories Filter menu, when they should really both use the same design.

Changes include:

- Using the same collapsable headers as Category Filter uses
- Fixing the bug of the collapsable sections to allow them to actually work (mentioned in #1155)
- Changing the sort/order icon to use Up and Down arrows instead of reusing the dropdown arrows  (mentioned in #1155)

![filter_library](https://user-images.githubusercontent.com/620506/34656667-539d3cc8-f3eb-11e7-847f-a374ab514cc0.png)

These changes will also make it easier to fit in filtering by tracking as mentioned in #1147 as you could just collapse to the tracking section.

**Comment by CarlosEsco** [comment]
This is gonna be a little harder then the other one as it requires extensive rewrites.  I will look into more next week

**Comment by LinkCable** [comment]
Thanks for tackling these @CarlosEsco!
