### ISSUE TITLE
Improve Tracking Search results

### ISSUE THREAD

**Issue by LinkCable** [inorichi/tachiyomi#1158]
This one is definitely most up for discussion, but we've had issues (#1102, #422) regarding the results of the MAL search (and likely other trackers) being less-than-ideal for picking the correct manga to sync.

These changes depend on what sort of data we can get from the API, and how much dev time we want to devote, and also what other devs/users think.

1. Show the manga with it's cover page, title, author, and first lines or so of the description to make a more informed decision of what you're picking to sync
2. Just recycle the list view we already use for Catalogues, which at least adds the manga image

![mal](https://user-images.githubusercontent.com/620506/34656850-7391e806-f3ed-11e7-8cad-710158e1416d.png)

Again these are just initial designs and not necessarily final.

**Comment by Flat** [comment]
Anilist and Kitsu provide fields for cover images through their API. According to their documentation MAL does not.

**Comment by LinkCable** [comment]
>According to their documentation MAL[3] does not.

Dang not even the author, stingy.
