### ISSUE TITLE
Download new chapters automatically

### ISSUE THREAD

**Issue by Ligerx** [inorichi/tachiyomi#116]
This is a feature of Mango that I used to have turned on.
Whenever the app checks for new chapters, it will automatically download any new updates.

**Comment by FlinstoneJohn** [comment]
This option would be nice to have. If it were implemented, maybe have it disabled by default, so people who uses mobile data won't get surprised by an automatic download.

**Comment by CelesteGH** [comment]
I so want this one. Frankly it's the last thing I need for Tachiyomi to be perfect ^_^
