### ISSUE TITLE
[Request] Adaptive 2 Page View

### ISSUE THREAD

**Issue by TyranitarTar** [inorichi/tachiyomi#1163]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

The most popular comic reader for windows, Comic Rack (Crunchyroll Viewer also),  has this really nice feature called Adaptive 2 Page View, where it shows 2 pages on the same screen, but if one page is too large, i.e. a double-spread it only shows one. (see provided link for a screenshot to see how this looks)
http://prntscr.com/hxifcb

I imagine that this could be implemented as a setting in the "viewer for this series" selection option in settings.

I would love it if TACHIYOMI could also implement such a feature. 
I know that this is a niche feature that would likely only be used by Tablets and Chrome Books users, but for these demographics I think it would provide a pleasant viewing experience.

**Comment by inorichi** [comment]
Duplicate of #149. Further updates will be there.
