### ISSUE TITLE
batoto-will-be-closing-permanently

### ISSUE THREAD

**Issue by jblgf** [inorichi/tachiyomi#1164]
https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/

**Comment by CarlosEsco** [comment]
Search GitHub this issue was closed already.  There is a way to at minimum add your manga to other sources in my pull request

**Comment by cd0rw0** [comment]
we should keep this open so other dont open new 1.

**Comment by Kovaelin** [comment]
Will this be available for the stable release too?

**Comment by LinkCable** [comment]
Yes, it will be.

**Comment by inorichi** [comment]
Closing this one.
