### ISSUE TITLE
[Request] Chapter settings

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#1166]
Hi,

I have a request, if its possible to change that 3 dots menu on every chapter for something bigger..
I have big fingers and even on 10.1" tablet I have problem pressing them :(

I know its proly not that needed atm.. just reference for future, if its not much of work..

Thanks

**Comment by CarlosEsco** [comment]
3 dot is standard overflow menu for android.  Can you share a screen shot?  It is different in size then your normal phone?

**Comment by Sparh4wk** [comment]
@CarlosEsco  nope, but cause its on right side and there is also a scrolling area so if I touch the 3 dots with big finger, it registering scrolling and not the 3 dots :(

**Comment by wopian** [comment]
This is also an issue with very high DPI settings, where the touch event for scrolling overlaps almost half of the 3-dot menu. 

![](https://thumbs.gfycat.com/NauticalAnguishedCassowary-max-14mb.gif)

**Comment by CarlosEsco** [comment]
![image](https://user-images.githubusercontent.com/2092019/35198942-81fae4a6-fec4-11e7-8a65-029bd41a497a.png)

Would this touch area be better?
