### ISSUE TITLE
Adding more websites

### ISSUE THREAD

**Issue by reddeimon** [inorichi/tachiyomi#1168]
Hello, may i request for adding websites like mangarock.com, mangapark.me and mangaon.net into the catalogues? Thank you.

**Comment by inorichi** [comment]
The readme contains instructions on how to request them.

**Comment by SDMU** [comment]
@reddeimon btw mangarock has its own app

**Comment by jeffrey0922** [comment]
@inorichi how can i add in this website, https://readcomicsonline.ru, to tachiyomi

**Comment by CarlosEsco** [comment]
That site already exists.

**Comment by jeffrey0922** [comment]
@CarlosEsco no its a different one

**Comment by CarlosEsco** [comment]
Install the foolslide extension. And this is wrong repo and a closed ticket

**Comment by jeffrey0922** [comment]
what do you mean by foolslide extension and closed ticket, i only heard about tachiyomi and f droid 2 days ago

**Comment by CarlosEsco** [comment]
Join the discord channel please.

**Comment by jeffrey0922** [comment]
@CarlosEsco im sorry but i dont even know what that is either

**Comment by wopian** [comment]
@jeffrey0922 Discord is a text chat service and Tachiyomi has a server on it to help with support/general questions: https://discord.gg/WrBkRk4).

Carlo is incorrect with the Foolside extension - readcomicsonline.ru is included with the `My Manga Reader CMS` extension. Tap the hamburger menu in top left and select `Extensions` to install it.
