### ISSUE TITLE
[Feature] - Category Specific Filters

### ISSUE THREAD

**Issue by zbhoy** [inorichi/tachiyomi#1169]
Is there a way to get filters specific to the category? 

For example my reading category I want to show all the manga i am reading whether i have unread or downloaded chapters.

My category of comics i am catching up on I want to show only mangas that have downloaded manga

**Comment by cd0rw0** [comment]
Hi 

to show only downloaded mangas 

In my library -> Filters -> select/tick  "downloaded"

you also can select : display -> download badges 
this will display downloaded chapter count.

hope this help.
