### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#117]
instant crash, just a dialog Unfortunately, Tachiyomi has stopped. Worked fine just affter update.

r424

**Comment by j2ghz** [comment]
Titanium backup, uninstall, install, restore data everything works

**Comment by IceKreem** [comment]
I do not have this problem also on r424, perhaps the restore messed something up?

**Comment by j2ghz** [comment]
If it doesn't happen to anyone else we can close it, it could have been caused by something other than tachiyomi

**Comment by Bloodwork** [comment]
No crashes on launch for me on both the stable and devbuild.

**Comment by inorichi** [comment]
It seems it's not related to the app.
