### ISSUE TITLE
Bato.to infinite retry, pages never load

### ISSUE THREAD

**Issue by DinduNuffins** [inorichi/tachiyomi#1173]
No matter how many times I attempt to load the page, it immediately fails and shows the retry button. Updated to 6.7, source content on bato.to won't load under CDN but all other servers load fine. Doesn't work on app as I can't change the image server.

I suppose it's a moot point since it's shutting down soon though.

**Comment by CarlosEsco** [comment]
Not gonna be fixed with batoto closing down

**Comment by DinduNuffins** [comment]
Fair enough to me. Just trying to track down which chapters need to be saved over, I'll live though
