### ISSUE TITLE
.apk isn't allowing install

### ISSUE THREAD

**Issue by dropkicks93** [inorichi/tachiyomi#1174]
Previously I've used 0.6.5, but trying to update to 0.6.7 doesn't work as the "install" button is greyed out. No 3rd party apps are running in the background, no screen overlays, and there is more than enough space on my phone (LG G3).

**Comment by inorichi** [comment]
Did you install 0.6.5 through F-Droid? If so, you won't be able to update with my release due to the signing key being different and you'll have to wait for an update on their end.

**Comment by dropkicks93** [comment]
unknown .apk files are allowed to be installed and I've previously never used the F-Droid versions. It seems that none of the versions, developmental, stable, or F-Droid's are able to be installed.

**Comment by inorichi** [comment]
Which app are you using to install the app? Can you try with the built-in updater in Settings > About > Version?

**Comment by dropkicks93** [comment]
I'm simply running the .apk from my file manager/downloads to install it. I've also sadly uninstalled it and backed up my library earlier so I'm unable to use the built-in updated.

**Comment by dropkicks93** [comment]
Interestingly enough it turns out that all .apk files aren't able to be installed. Going to look at android-specific posts as well while this issue is still open.

**Comment by dropkicks93** [comment]
Well I've found an odd fix. It seems to be a bug in some recent software updates. Locking the screen and unlocking it once or twice will enable the ability to install any .apk files.

Hopefully this post will help with any similar events in the future.

**Comment by melnation-com** [comment]
What software updates? what did u update?

**Comment by Kovaelin** [comment]
When I encountered installation problems in the past (with extensions), all I did was reset my device (I probably had it on for over a month), and that made things work again.

**Comment by paulo27ms** [comment]
I found this to be an issue if you use software that dims the screen.
For example, I use this: https://play.google.com/store/apps/details?id=jp.ne.hardyinfinity.bluelightfilter.free
And it won't let me install or update any app while it's activated.

**Comment by inorichi** [comment]
Closing because he resolved it and doesn't seem related to tachiyomi.
