### ISSUE TITLE
"SyntaxError: parse error (line 1)" When trying to read anything from KissManga

### ISSUE THREAD

**Issue by Cleverbird** [inorichi/tachiyomi#1175]
Since updating to the latest stable build (0.6.7) from 0.6.6 I've been getting the aforementioned error whenever I try to read anything from Kissmanga. Other providers (such as Mangafox) work just fine.

This happens for all manga from Kissmanga, not just the ones in my library. I did manage to pull an update list though.

The Dev build seems to be working without any issues.

**Comment by Cleverbird** [comment]
Reinstalling the app seems to have fixed the issue for me. When in doubt, uninstall and reinstall!

**Comment by CarlosEsco** [comment]
can you close this issue since its resolved
