### ISSUE TITLE
Library updates are not updates

### ISSUE THREAD

**Issue by ArmeF97** [inorichi/tachiyomi#1176]
Version: r1304

![image](https://user-images.githubusercontent.com/6240983/34770093-2b2b6442-f600-11e7-8d40-1f2afa373052.png)

For example, Nanatsu No Tazai. I've already read it. But everyday when I update, trying to see if there is a new chapter to read, in the "today" section, those chapters come up.
Maybe there was some kind of update, so maybe it's reasonable that it's a "today" update.
But I've already read them, could we hide already read chapters from this list?
Same goes for Minamoto-kun, I've already read all chapters, but everyday I see updates from those chapters I've already read

I don't know if I explained my self clear, feel free to ask
Thanks 👍

**Comment by CarlosEsco** [comment]
So you are requesting option to hide read chapters in this list?

**Comment by ArmeF97** [comment]
Well, it's the "what I am going to read list", so why have already read chapters?

**Comment by CarlosEsco** [comment]
Technically it's a what has been update in your library page that's why I was asking

**Comment by CarlosEsco** [comment]
You could technically sort your library by last updated for similar results

**Comment by ArmeF97** [comment]
Ok but that should be a way to exclude already read chapters from updates

**Comment by ArmeF97** [comment]
Also, I don't know if this is related to this bug or not (in that case I should open another) but I always have a weird update from "Girls of the wilds" in the android notification place but it isn't listed in the "library updates" page. Is it related to the thing I am saying before?

**Comment by LinkCable** [comment]
This isn't a bug. The list is for library updates, AKA what in your library has updated. A filter could be added to get rid of chapters you've already read.

**Comment by ArmeF97** [comment]
Then I'd like to have that filter

**Comment by zbhoy** [comment]
Are they manga that have finished? If so put them in a different category and they won't be shown in this view if you only update the default view

**Comment by ArmeF97** [comment]
No that's not the problem @zbhoy 
Nanatsu no Tazai is not finished
I've read... let's say the first 200 chapters to make this example easy to understand
When I update the library I can see that the chapter 190 has been updated. What do I care? I've already read it.

Am I clear now?
