### ISSUE TITLE
[Request] — Download menu

### ISSUE THREAD

**Issue by Pavkazzz** [inorichi/tachiyomi#1179]
Can you add option to download more chapter in download chapters menu, because it's come a real problem, when you have a 500+ chapter manga and Download all unread it's too much. 
For example from next, 5, 10 to next, 5, 10, 30, 50.
![screenshot_20180111-200546_01](https://user-images.githubusercontent.com/3702034/34837151-fbbebb4e-f70a-11e7-93e7-e3f0b27d753f.jpg)

Thanks!

**Comment by Flat** [comment]
Just long tap to start selection, select the ones you want to download and then tap download.

**Comment by Pavkazzz** [comment]
@Flat it's kind of problem to click 50 times on the screen to download the next pack of chapters, on my opinion.

**Comment by melnation-com** [comment]
I always wish it has the same selecting power of MangaRock

**Comment by NoodleMage** [comment]
#1185
