### ISSUE TITLE
Turn on Auto-updates by default

### ISSUE THREAD

**Issue by LinkCable** [inorichi/tachiyomi#1182]
Lately we've had a lot of Discord and reddit discussion where people don't know that a new release has come out that addresses their problems.

To solve that, I suggest that we instead turn on auto-updates by default, and that if a user refuses the auto update they can turn it off in a following dialog. I also propose making it more evident how a user can manually update, as there are no instructions on the About screen of how to do so.

(sorry for the awkward screen size, took screenshots and based off my tablet)

![modal](https://user-images.githubusercontent.com/620506/34858994-93ed3e20-f721-11e7-90ab-626757dff177.png)

Two potential designs to explicitly inform about manual updates:

![check_](https://user-images.githubusercontent.com/620506/34859054-f68ed5f2-f721-11e7-8ca0-84fed8bd07c7.png)

These would save us a lot of support headaches and people's time wondering what's wrong and how to update.

**Comment by Kavboy** [comment]
I think that if auto updates are implemented, than v2 of the about page is better. If not than v1.

**Comment by sharedkestrel** [comment]
I know it's just a mockup, but adding a limiter for the search of updates would be good (like once a day, once every two days, once a week...)

**Comment by Kovaelin** [comment]
Nice mockup. However, I don't see the need to change the default, as long as settings are saved after each update. The option to turn them on is right there in the settings and not at all difficult to find. I think most people that use the dev version also tend to keep it off to see if new builds are stable before updating themselves.

**Comment by LinkCable** [comment]
@Kovaelin We have experienced many people entering our Discord asking how to update and lots of reddit comments regarding how to update, with many not knowing this option even exists.

Also dev has no auto-update option (on purpose). This is only for stable.

**Comment by arkon** [comment]
This is now the case for fresh installs.
