### ISSUE TITLE
Dev branch on F-Droid changes signature sometimes and can't update

### ISSUE THREAD

**Issue by Enamex** [inorichi/tachiyomi#1183]
Currently I have Tachiyomi (dev) Version `0.6.6-1304`.

The 'Versions' tab shows up to `0.6.7-1312` available but it has 'different signature to installed version'.

My current version is installed through F-Droid, of course.

**Comment by j2ghz** [comment]
Use backup, uninstall, install and restore. The signature was changed to match inorichi's.
