### ISSUE TITLE
Unexpected behavior with chapter re-read

### ISSUE THREAD

**Issue by substanceof** [inorichi/tachiyomi#1186]
If i want to re-read previous chapter, return to it from reader, and then try to resume reading, i'll be dropped to last unread chapter. Maybe it worth to put a warning (that progress will not be saved) or something?

**Comment by substanceof** [comment]
I was thinking to create a PR with warning but it's need a discuss

**Comment by LinkCable** [comment]
Is this saying that you re-read a chapter you already read prior, and you expect the play button to pick off from last chapter read, rather than the next unread chapter?

**Comment by substanceof** [comment]
If saying about behavior i was expecting - then yes.

**Comment by inorichi** [comment]
The current expected behavior of the "play" button is to continue from the lowest unread chapter. If you're rereading a series you should mark everything as unread then proceed as usual. I don't think we should change its behavior.
