### ISSUE TITLE
is readcomiconline down for anyone else ?

### ISSUE THREAD

**Issue by cojoMan** [inorichi/tachiyomi#1187]
I haven't been able to get a read on the source since a week and then some now, when I think their server went down. Is anyone else having the same issue, or am I the only one ?
please help !

PS. did the regular stuff, opened browser to check for chaptchas, checked with other types of connections, and other devices. Did not see a similar issue opened thread...

thanks.

**Comment by LinkCable** [comment]
Are you on the latest release (0.6.7)?

**Comment by cojoMan** [comment]
tachiyomi dev 0.6.6-1304, with readcomiconline.to extension up to date ("updated days ago")

0.6.7 does not appear in f-droid, dev or normal(normal version is 0.6.5 in f-droid)... is there a proper way to get the last version ? I thought F-Droid was the right channel.

**Comment by LinkCable** [comment]
F-Droid is having problems building and distributing apps. I recommend backing up, installing the latest release from Github, restoring and turning on auto-updates from Settings-> About.

The issue you are encountering is fixed in 0.6.7

**Comment by LinkCable** [comment]
(or the latest dev, your choice)

**Comment by cojoMan** [comment]
how would I be able to install extensions, same way, pick and choose from github respectively, or is it inside the app ?...

**Comment by inorichi** [comment]
You can keep installing the extensions from F-Droid.

**Comment by cojoMan** [comment]
"...restoring and turning on auto-updates from Settings-> About."

I cannot see the auto-update option in the latest dev version from GitHub - should it be available in the app itself ?...

**Comment by LinkCable** [comment]
Dev does not have auto-update feature.
This is on purpose.

**Comment by cojoMan** [comment]
but normal version would have it ?...

**Comment by LinkCable** [comment]
Yes, Stable has this feature.

**Comment by cojoMan** [comment]
thank you, kind sir !
