### ISSUE TITLE
windows app

### ISSUE THREAD

**Issue by cojoMan** [inorichi/tachiyomi#1188]
Hi guys, I recently got a surface pro tablet, running windows, and the only thing I am missing from my usual samsung android tablet, is Tachiyomi. Is there any way to run it on the surface ? I tried a few emulators, but it's not coming even close to the experience on android. I understand there is no Windows app/program, or a track to build one at this time...

Any advice would also be appreciated, thanks.

**Comment by LumpBloom7** [comment]
Building Windows apps require a different programming language, not to mention a completely different framework to work with.

**Comment by LinkCable** [comment]
This is not relevant to Tachiyomi. If anything bring it up in the discord. The GitHub is for issues regrading the app itself.

There's no way to run Tachiyomi on a Windows machine without an Android emulator.

**Comment by cojoMan** [comment]
my mistake, thanks.

**Comment by LinkCable** [comment]
Sorry to be harsh, we just want this to be a consistent issue tracker that we can reference when developing new features or pull requests.

Thanks for liking the app so much :)

If your question is answered please close the issue thanks!

**Comment by cojoMan** [comment]
no apologies needed, I did not know the protocol, now I do, closing it, and can be deleted.
and yes, LOVING the app.
