### ISSUE TITLE
Name problems with "migration"

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#1189]
Russian catalogs(mangachan) do not take into account that the translation is written in parentheses, because of this manga can not immediately "[migrate](https://github.com/inorichi/tachiyomi/commit/a75457ad88b2f9a1fcae347676d14e10ff6b5af0)", it is necessary to erase the Russian or English name !!!
![](https://i.imgur.com/iKvcHZp.png)
![](https://i.imgur.com/zKLjIhS.png)

**Comment by e-shl** [comment]
@inorichi, do so that the name is taken only before the parentheses

**Comment by CarlosEsco** [comment]
@e-shl and what would you do if a manga had parens in the name?
