### ISSUE TITLE
Bug: New chapter search resets read count

### ISSUE THREAD

**Issue by Soumatan** [inorichi/tachiyomi#119]
This is a problem that happens sometimes. When the App searches for new manga chapter and when it finishes it says that a lot of new chapters has been found. Some of these mangas will not have new chapters and wont appear in the "Recent Update" tab but it will reset the read count and appear that every chapter appears unread. The MAL count stays the same so at least I don't get lost in where I was but it's a bit annoying seeing it happened. This has happened to me since the official version.

![screenshot_2016-02-05-15-30-56](https://cloud.githubusercontent.com/assets/16980590/12856967/f786504c-cc1d-11e5-8cbe-68ddcd8b8266.png)
![screenshot_2016-02-05-15-31-40](https://cloud.githubusercontent.com/assets/16980590/12856974/fcb05676-cc1d-11e5-922c-1be2ed08a8e9.png)
![screenshot_2016-02-05-15-31-43](https://cloud.githubusercontent.com/assets/16980590/12856979/015b257a-cc1e-11e5-874a-f2e0c9e6869c.png)

Also when the app finishes searching for new mangas it would be cool that when I hit the notification in the phone it opens the manga reader in the "Recent Update" tab instead of just opening the app normally.

**Comment by j2ghz** [comment]
Same problem with multiple manga, sometimes resets all chapters, sometimes just last 5-10

r424

**Comment by inorichi** [comment]
Does it happen on all sources or only in Mangafox?

**Comment by j2ghz** [comment]
I use batoto only

**Comment by inorichi** [comment]
The issue *should* be that the url has changed, and then the chapter is added as a new one.

Possible workaround: recognize chapter number and find if previous one with same number has been read.

**Comment by inorichi** [comment]
This may also fix #18

**Comment by inorichi** [comment]
It shouldn't happen now, unless the chapter number is not recognized.

**Comment by zKskita** [comment]
The issue still persists for Mangafox as of v0.1.3. 2-6 series out of 50 in my list randomly has this problem every refresh.

**Comment by j2ghz** [comment]
Fixed in dev, will be in next release
