### ISSUE TITLE
Download badge counts empty temporary folders 

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#1193]
https://gfycat.com/QuerulousHomelyAyeaye

Lookism has all the unread chapters downloaded according to the download badge - but actually only has a few downloaded

r1319

**Comment by wopian** [comment]
Yes, but irrelevant for this. Was part of a download batch from months ago that failed. 

Manga from all sources have this issue.

**Comment by CarlosEsco** [comment]
Interesting you know how to repeat this? I've never had this occur for me I just have download badges for read items cause my delete after read setting was messed up

**Comment by wopian** [comment]
Also can't seem to replicate this - but there are ~10 with wrong counts in that category from various sources.

The folders contain 0 byte `{chapter}_{title}_tmp` files

**Comment by wopian** [comment]
~400 chapters in total from only 3 dates interestingly (Aug, Nov and 2 weeks ago)

Found a way to repeat this. 
- Begin a download
- Clear the download list while in progress (may need to make it error by turning WiFi off?)
- Close Tachiyomi
- Open Tachiyomi
- Download badge has gone up

**Comment by zbhoy** [comment]
I have had this issue also. I have to go into file explorer and delete the folder in order to fix

**Comment by inorichi** [comment]
Isn't it better to show the temp folders? That way you know there are directories that shouldn't be there.

**Comment by wopian** [comment]
> @inorichi Isn't it better to show the temp folders? That way you know there are directories that shouldn't be there.

If they aren't empty.

Scanning through a list of manga you wanted downloaded and seeing `[12] [12]`, then going to read them when offline only to find they're errored chapters with 0 pages downloaded is not.

**Comment by inorichi** [comment]
Sorry but I'm not scanning the contents of the chapters. Blame Google and its crappy and slow SAF/cursor API.

I had to fork a library precisely to avoid many cursor queries, and just scanning them can make the library take 20s (or more, depending on how many chapters were downloaded) to load.

**Comment by wopian** [comment]
Then I will say no to this and ignore temp folders completely (contents of temp folders are unused as they're downloaded from source when opened):

>Isn't it better to show the temp folders? That way you know there are directories that shouldn't be there.

**Comment by zbhoy** [comment]
From a UX perspective it is just very confusing to think there is something downloaded and nothing shows. Maybe even if it is a temp folder then show it so we can delete from in the app

**Comment by mwsasser** [comment]
Any progress on a fix?

**Comment by arkon** [comment]
Badges now ignore tmp folders.
