### ISSUE TITLE
Full Name Error

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1194]
A few examples of full name errors from the latest commit r1321.

![screenshot_2018-01-19-00-25-58-216_eu kanade tachiyomi debug 01](https://user-images.githubusercontent.com/23010526/35115999-eabcd3ee-fcaf-11e7-8c9f-5f7ed37881b9.png)
![screenshot_2018-01-19-00-26-10-651_eu kanade tachiyomi debug 01](https://user-images.githubusercontent.com/23010526/35116009-f2d6ce18-fcaf-11e7-8ceb-19f8c8d33052.png)

**Comment by inorichi** [comment]
I guess we could use the new auto sizing text view https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview.html @LinkCable @QuestofIranon

**Comment by LinkCable** [comment]
I think this is a good solution, see Material recommendations too:
![pzasq](https://user-images.githubusercontent.com/620506/35119272-6f777722-fc62-11e7-8ba5-9279bc19043d.png)

**Comment by QuestofIranon** [comment]
I'll tryout the autosizing text view this evening.
