### ISSUE TITLE
Error in "New Game!" in Dynasty source

### ISSUE THREAD

**Issue by sharedkestrel** [inorichi/tachiyomi#1195]
I'm using the latest dev release (0.6.8-1321) and the latest DynastyScans version (1.2.1) (according to F-Droid, at least). 
When browsing "New Game!" chapters, some displayed the error "Page list is empty", while others worked perfectly fine. I can access the chapters from my browser, with or without WiFi, and clearing cache didn't help. I tried every solution in the source problems page. Just for reference, the chapters that I tried that didn't work were number 68 and 42, while ch. 40 worked like a charm.
I looked a bit at the site, and the URL sintax is the same. The only difference I noticed is that both of the chapters that do not work have this syntax for the image source: `/system/releases/000/018/188/[Doki]%20New%20Game!%20-%20Chapter%2042%20-%20Page%2001.png` , while chapter 40 had `/system/releases/000/016/781/019.png`.

The manga has many other sources, so it's not an urgent matter, but I thought I should report it.

**Comment by CarlosEsco** [comment]
Please close and open in the tachiyomi extensions GitHub page
