### ISSUE TITLE
Readmangatoday search not working

### ISSUE THREAD

**Issue by LordSquiggles** [inorichi/tachiyomi#1199]
The search function for the readmangatoday catalogue always ends up with no results found. The issue is the same on both the 0.6.8 release and the current dev build on both my android 6 phones. Using the latest extension available for readmangatoday on f-droid does nothing as well. There are no problems with browsing and downloading chapters and so far this issue is only apparent in readmangatoday.

**Comment by CarlosEsco** [comment]
@LordSquiggles Should be fixed in latest dev.  If so close the issue
