### ISSUE TITLE
Pages that fail to load can't be forced to retry

### ISSUE THREAD

**Issue by madolinn** [inorichi/tachiyomi#120]
While on my 3G about 1 page every chapter fails to load. Either it times out or it gets a bad packet and corrupts the photo, causing the page to just render as white.

This can currently be solved by either deleting a chapter entirely and redownloading it, or using a more stable connection.

Not a deal-breaker but I'd prefer not to have to find an open WiFi while on the go.

**Comment by madolinn** [comment]
1.3 fixed this, my apologies

**Comment by madolinn** [comment]
Recent update did not fix this issue after all. It's started happening frequently again.

Solution? Add an option for "Retry" regardless of if you think programmatically it succeeded in loading.

**Comment by inorichi** [comment]
Try disabling wifi and 3G while loading some chapter. You should see the retry button. And change the image decoder to Skia. I would say the image is downloaded but it just doesn't render.

In the latest debug version, Rapid decoder also shows the message "Image couldn't be decoded". It's only shown for non-webtoon readers though.

**Comment by madolinn** [comment]
Alright, I will try this next time it comes up.

The retry button does show up sometimes, and it does work, by the way. It just doesn't always show up.

**Comment by inorichi** [comment]
If you are using the debug version, it may be fixed already. I can't reproduce this issue (I always see the retry button when a page fails). Report back if it still fails.

**Comment by madolinn** [comment]
Sorry about that, it seemed to have been fixed in the debug version, but sure enough it came back up last night on me; even on a stable connection (WiFi).

Switching from rapid decoder to Skia gave me an error saying there was errors in the image and it couldn't be loaded.

Opened the website up and manga to the page in a browser, loaded fine. Checked in the downloaded folder on my SD card and the images were indeed corrupt. They couldn't be loaded using an image viewer. Deleting them only redownloaded new corrupted images.

These were all webtoons this time around. Probably the huge in length images get a minor hiccup and then the entire page dies.
