### ISSUE TITLE
[Feature Request] Adding "SEE ALL" in the global search result per source.

### ISSUE THREAD

**Issue by Skcyte** [inorichi/tachiyomi#1201]
As the clickable tag/author is being develop, the sideway scrolling is a bit troublesome when the results are way too many. Adding see all option per source would make the results are easy to browse. Basically it's the same page where in the browse catalogue mode with the filter in it.

**Comment by CarlosEsco** [comment]
Maybe something as simple as clicking the source name relaunches same search on just that source

**Comment by Skcyte** [comment]
That would be fine as well. I'd more concern on tag/author one since you basically can do name search on just one source right.

**Comment by arkon** [comment]
Closed by #3265
