### ISSUE TITLE
[Feature request] E-reader Page-up/down button support

### ISSUE THREAD

**Issue by Nelthorim** [inorichi/tachiyomi#1202]
Simple request: Android e-readers exist, and this app works amazingly in them. However, it would be nice to be able to use the page-up/down buttons available on them to pass the pages in addition of swiping the e-ink screen, which isn't as responsive as it should be.

I'm not sure how hard this would be to implement, but didn't see it suggested here yet, so I'll bring it to your attention.

**Comment by CarlosEsco** [comment]
What ereader do you use?

**Comment by Nelthorim** [comment]
Energy System Pro HD. Most of the other ebook apps work with the side buttons, so I was hoping this one would too :(

**Comment by CarlosEsco** [comment]
Are you using dev or stable?

**Comment by Nelthorim** [comment]
I've tried with both the stable and dev version. Unfortunately, that .apk gives error to install.

If it's useful, I'll attach the output of KeyEvent for those keys.

[keyevent_2018-01-24-205848+0000.txt](https://github.com/inorichi/tachiyomi/files/1661660/keyevent_2018-01-24-205848.0000.txt)
