### ISSUE TITLE
Page list empty error

### ISSUE THREAD

**Issue by MyoKA** [inorichi/tachiyomi#1207]
Can't read or download any issue in kissmanga souce. It just keep showing page list is empty. Same error happens in other source too.
![screenshot_2018-01-22-16-50-17-87](https://user-images.githubusercontent.com/35681664/35216013-8cc91b84-ff94-11e7-9b7a-8b9b8f12e69f.png)

![screenshot_2018-01-22-16-50-49-02](https://user-images.githubusercontent.com/35681664/35216004-85233338-ff94-11e7-9160-8d5894a09fd3.png)

**Comment by CarlosEsco** [comment]
What version of app and have you tried clearing cache and cookies? I just checked kissmanga on latest stable with no issues

**Comment by MyoKA** [comment]
I'm currently using v0.6.8. I have tried clearing cache, but that doesn't solve the error. I don't know much about how this stuff works. So, please help me out. Thanks a lot !!

**Comment by CarlosEsco** [comment]
Can you access the site and chapters on your phone's web browser

**Comment by MyoKA** [comment]
Yes, I can read the chapters on the site. I have no idea what's the problem.
Also, I can update new chapters on the app, but the same error occurs to those new chapters.

**Comment by CarlosEsco** [comment]
clear database also?  I have no issue at all on 0.6.8 picked same manga from kissmanga no issue loading latest boruto chapter

**Comment by CarlosEsco** [comment]
Did you follow these steps?

https://github.com/inorichi/tachiyomi/wiki/Source-problems

**Comment by SDMU** [comment]
I guess it is because sites like mangafox , kissmanga try to prevent downloads by 3rd party devices . They don't earn any money that way . This is one of the reasons why the MangaRock people started their own server .

**Comment by CarlosEsco** [comment]
Thats not the issue here.  This is isolated to you so there is something on your end.  Feel free to go to discord channel as you can get on the fly help and delete this issue since its not a tachi related issue

**Comment by CarlosEsco** [comment]
Again seems to be isolated if your using latest stable with internal source you should have no issue

**Comment by MyoKA** [comment]
It doesn't show 'page list is empty' anymore after I checked into the site from browser and clearing cache.
Thanks so much for your help.l didn't know  about the steps to follow. So, thanks again for the info.
