### ISSUE TITLE
[Feature Request] Replace Batoto with Mangadex

### ISSUE THREAD

**Issue by sthebemita** [inorichi/tachiyomi#1210]
Batoto is completely dead now and the most popular successor seems to be Mangadex. They are updating it frequently, so maybe it's better to wait for it to be more stable (and I don't know how hard it would be to implement this).

**Comment by wopian** [comment]
It's already implemented as a catalog extension which are available by using the F-Droid versions of Tachiyomi 😄 

https://github.com/inorichi/tachiyomi-extensions/pull/163
https://github.com/inorichi/tachiyomi/wiki/FDroid-for-dev-versions

**Comment by sthebemita** [comment]
Thanks! I didn't see it.

**Comment by CarlosEsco** [comment]
can you close this 😄
