### ISSUE TITLE
[Feature Request] Separator for sorting by catalogues

### ISSUE THREAD

**Issue by MaskedPierrot** [inorichi/tachiyomi#1218]
As it is it's a bit confusing when sorting by catalogues because there's nothing to seperate the Manga so there's no real distinction between sources. I think a horizontal line with the title of the source on top of it between each set of Manga from different catalogues would make it much easier to go through. I did a quick and rough edit of what I'm trying to describe.
https://imgur.com/a/RIzYv

It could be collapseable too but for now it just needs to be there.

**Comment by arkon** [comment]
This was removed in favour of searching by source.
