### ISSUE TITLE
Kissmanga almost never loads on certain wifi network

### ISSUE THREAD

**Issue by Ligerx** [inorichi/tachiyomi#122]
When I'm on my school's wifi network, this app almost never loads from Kissmanga.

All other catalogs work fine on my school's network. When I'm using my home wifi or data plan, it loads just fine. One possibility is that Kissmanga is loading extremely slowly and times out. If I try to access Kissmanga from my browser, it loads normally.

Unfortunately I have no idea clue how to help debug the problem further.

I'm running Lollipop 5.1 on an LG G4, using Tachiyomi v0.1.3

**Comment by inorichi** [comment]
It looks unrelated to the app. I want to add some retry functionality in the catalogue, but if it doesn't load, nothing I can do there.

**Comment by Ligerx** [comment]
If it loads in the phone browser but not the app, then it seems like it's something to do with the app to me.

I'm curious why you think it's not related to the app?

**Comment by inorichi** [comment]
The way it loads from the app is different from the browser, because it needs to access through IP, but that shouldn't matter. If it depends on certain wifi networks then I can't do anything. Maybe there's some firewall behind or who knows.
