### ISSUE TITLE
Enlarge the 3-dot icon click space in chapter lists

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi#1220]
I know this has been modified in the dev version already (I have r1335 right now) but the space you have to click the icon is simply far too small. With this change the icon is also now vertical instead of horizontal so there's effectively no change as far as I can see outside of it not looking as bad.
I have a 720x1280 screen and it's pretty evenly split between opening the chapter, jumping to another location with the scroll bar and actually opening the menu when I try.
Please either make the space to click it significantly bigger or add an option to disable the scroll bar.
Thank you.

**Comment by paulo27ms** [comment]
I'm not sure I follow. To the right? That brings up the scroll bar and moves me somewhere else.
I'm asking to make it bigger, like, double its current size added to the left.
It does not work like this for me if this was the final product:

![35238868-d3f150d4-ff7c-11e7-95dc-941544631d67](https://user-images.githubusercontent.com/13546823/35538140-b36c4f62-0544-11e8-9869-d59b3c40182b.png)

I am noticing that it looks quite a bit different on my end though:

![screenshot_2018_01_29_22_33_01](https://user-images.githubusercontent.com/13546823/35538174-cfd6b87c-0544-11e8-91b8-f8b2d21b5edb.png)

**Comment by CarlosEsco** [comment]
Sorry meant left and that's weird.  Is that tablet can you try on phone? Mine is spaced out

**Comment by paulo27ms** [comment]
This is an Android phone. Wiko CINK FIVE, 5'', 4.1.2 Jelly Bean Android, 720p resolution. Not sure what else could be interfering with this.
Landscape mode doesn't change anything. 
I'll have access to a tablet tomorrow and I'll try to install Tachiyomi on it to see.

**Comment by Sparh4wk** [comment]
I think after update in dev version, its ok that way..

**Comment by CarlosEsco** [comment]
@Sparh4wk  It works for you right?  What version of android you using?
@paulo27ms What version of dev

**Comment by CarlosEsco** [comment]
I found issue

**Comment by paulo27ms** [comment]
I see. I'll wait for an update then. Thank you.
