### ISSUE TITLE
Tachiyomi Dev MAL login "failed to connect..."

### ISSUE THREAD

**Issue by melnation-com** [inorichi/tachiyomi#1222]
Is it just me who cant login in myanimelist in tachi?
https://cdn.discordapp.com/attachments/349436576037732355/407573501621567518/Screenshot_2018-01-30-00-27-58.png

Seem I cannot also login in firefox on my phone but I can login add/edit stuff on the browser on my laptop just fine like nothing happened.

Other details, all these are on wi-fi
Tachiyomi version: Tachi dev 0.6.8-1335

Updating/Installing method: Fdroid

Methods tried: Already tried force-stopping, clearing cache, uninstalling~>installing. Logged out from PC browser then logged in phone browser.

Started happening, I think a few days ago before 0.6.8-1335 and I still had 0.6.8-1334

Summary:
Phone login: No
PC/Laptop: Yes

**Comment by CarlosEsco** [comment]
So i was following and discord but this isnt a Tachiyomi issue.  If you cant login in on your phones browser your probably ip banned.  Either research how to update ip address on your phone or switch to/from wifi to mobile and data.  But please close this issue as again its not a Tachiyomi problem
