### ISSUE TITLE
Transperant/dark spalsh screen 

### ISSUE THREAD

**Issue by cd0rw0** [inorichi/tachiyomi#1223]
hi Guys ,

Currently tachiyomi dont have splash screen just blank white screen for few second when we open app.
changing from normal phone screen to bright white screen is kind irritating(specially during night).

if possible, i reqeust to change current blank screen to transparent splash screen.
of course i like to have dark splash screen similar discord android app but sum user doesn't use/like dark option, so is not fair for them.

-this white screen only on older models as older model need few second to load. 
im using S galaxy tab a2016
-this not big issue, but 1 of small quirk that i notice every time i open app.

Thanks

**Comment by inorichi** [comment]
There's no way to have a transparent splash, also it'd look weird.

There's also no way of using a black splash if you're using the dark theme because the activity hasn't loaded yet and I can't do any check.
