### ISSUE TITLE
Cannot load or migrate Batoto manga from backup

### ISSUE THREAD

**Issue by nantsuchatta** [inorichi/tachiyomi#1225]
Batoto is now down, but my manga collection is in backup form. With dev version r1337 I am unable to retrieve the vast majority of my collection from backup as I'd been mainly using Batoto prior. Attempting to restore results in "Restore Completed - 46 errors found", with each of those being 404 errors in the log. How is the backup json formatted? It is not immediately obvious as to how to manually retrieve my position in each series.

**Comment by CarlosEsco** [comment]
So backup won't restore since you can't login to batoto anymore as for the Json I believe the list is list of all read. Or in progress

**Comment by nantsuchatta** [comment]
The JSON chapter list is a list of u, r, and l keys. Example:
```json
"chapters": [
    {
        "u": "/reader#92ad09f4c029cf39",
        "r": 1,
        "l": 10
    },
    {
        "u": "/reader#e051d632efcc0ab5",
        "r": 1
    },
    {
        "u": "/reader#b9f109255dde6553",
        "r": 1
    }
]
```
I can't work out what each of these keys mean. `r` I'm guessing is a flag indicating that a chapter is read, but I don't have any flags saying a chapter is unread. `l` might refer to last page read, I think.

**Comment by CarlosEsco** [comment]
Oh yours is harder.  The first u one is the url for the last chapter read.  Problem is url doesn't say which chapter it did like the same I looked at.

**Comment by nantsuchatta** [comment]
I'm going to hope that I don't have unread chapters before my last read chapter and just take a count then to get my probable latest chapter for each series.

**Comment by paulo27ms** [comment]
You can migrate the manga before backing it up.

**Comment by nantsuchatta** [comment]
@paulo27ms yes, but that doesn't help when the backup is all I have. Optimally the backup system shouldn't depend on the individual services.

**Comment by CarlosEsco** [comment]
closing this because restore from backup will restore any manga even if extension doesnt exist now.
