### ISSUE TITLE
F-droid build seems to fail.

### ISSUE THREAD

**Issue by Lionirdeadman** [inorichi/tachiyomi#1227]
Tachiyomi v6.8 seems to be having issues with F-droid.

Build log from F-droid wiki : 

https://f-droid.org/wiki/page/eu.kanade.tachiyomi/lastbuild_31

**Comment by inorichi** [comment]
It only tried to build once and failed (as usual). There's nothing we can do besides contacting them to trigger another build or fix their issue.

I'm honestly tired of their reliability and won't be the guy to get in touch with them.

The best you can do is install the github release.

**Comment by Lionirdeadman** [comment]
Alrighty, I'll contact them.

I don't mind doing that. If it happens again, you can mention me and I'll do it. I love this app so it's the least I can do.

**Comment by Lionirdeadman** [comment]
It was built. Closing this issue.
