### ISSUE TITLE
[Feature request] Corresponding links to Mangaupdates 

### ISSUE THREAD

**Issue by thankyou-xx** [inorichi/tachiyomi#1229]
For that reason I propose that each manga page would have a corresponding MU page link on it. There, it will be easier to find similar manga and do other stuff.
I wish [this issue](https://github.com/inorichi/tachiyomi/issues/376) would have been implemented instead, but I guess it's too hard to do.

**Comment by CarlosEsco** [comment]
Until Mangaupdates gets an api, this isnt happening and even after this probably isn't.  
There is no way to link a random manga with its mangaupdates entry without searching parsing and hoping for the best as Tachiyomi is not a content provider.
