### ISSUE TITLE
"Girls of the Wild" everyday in Android notifications but it's not in library update

### ISSUE THREAD

**Issue by ArmeF97** [inorichi/tachiyomi#1230]
Tachiyomi version 0.6.7 (edit and version 0.6.8)

Everyday, I manually check for library updates.
See:
![photo_2018-02-04_11-07-54](https://user-images.githubusercontent.com/6240983/35776415-4c9df4a0-099c-11e8-984f-d37147f27df2.jpg)
![photo_2018-02-04_11-07-53](https://user-images.githubusercontent.com/6240983/35776416-50579dbc-099c-11e8-9588-a98b23368249.jpg)

There is always in the notifications this "Girls of the wild", but not in the library update section.
The worse part is that Girls of the Wild is finished, it's completed 😃

**Comment by Skcyte** [comment]
The latest stable version is v.0.6.8
Please update to latest version first. If the f-droid acting up again, please download from the github page.

**Comment by ArmeF97** [comment]
It says that the package is in conflict with my installed version.
But this issue, it's been month or maybe a year that it's there. I decided only today to make an issue, but I doubt it's a problem with this 0.6.7 or that it's fixed in 0.6.8 :(

**Comment by calvinjhchan** [comment]
I've had this issue for a while as well. I am on 0.6.8 already. It may be an issue related to the source of the manga.

**Comment by ArmeF97** [comment]
Today is another day, new version (0.6.8), same problem

**Comment by Skcyte** [comment]
What source and have you check the manga directly?

**Comment by sharedkestrel** [comment]
The same was happening to me months ago with Black Clover from mangafox, even though I read all chapters, it kept marking them as unread with every update.

**Comment by ArmeF97** [comment]
![photo_2018-02-05_21-40-30](https://user-images.githubusercontent.com/6240983/35827673-38fd9d16-0abd-11e8-8767-3c23b5813076.jpg)

@Skcyte , it's from MangaFox. And, I tried checking the manga directly, but there are no updates, nor in the notifications. But everyday (when I manually check) from the "library updates" general place, I get the notification.

**Comment by arkon** [comment]
Closing due to age.
