### ISSUE TITLE
[Feature] Batch migration of manga

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi#1231]
When migrating manga, people with large libraries will end up spending large amounts of time migrating manga to other sources when one goes down. (of course this can be mitigated by using multiple sources, but eh) So I want to be able to  have the option migrate large amounts of manga at once, working similarly to how manga updating works. You select a source, and the app begins searching titles, skipping the titles that aren't available or aren't found. Maybe afterwards it would show something like _"x manga migrated to x successfully. x unsuccessful"_. Thanks a bunch

**Comment by LinkCable** [comment]
I liked this idea, so came up with a quick mock if we want to pursue this. (Ideally the list of manga would use the same style as the source list, this is just me putting screenshots together.)

![migrate next](https://user-images.githubusercontent.com/620506/36159832-be06c992-10ad-11e8-8b41-94f4f3f5e32c.png)

**Comment by scriptmode** [comment]
That will not work well because of a high chance of wrong results. You would need to limit the automatic migration to results with exactly one match, and somehow communicate that to the user.

**Comment by inorichi** [comment]
Sorry but no plans on this.
