### ISSUE TITLE
[Bug] Downloading extensions from Github Repo - Stuck at INSTALLING

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#1234]
When you press install and then canlel or click out of installation box it stays on INSTALLING state and you cant install it again. Ofc its working again, if you go to other section and back to extensions.

I know its minor issue and not something feature breaking.

**Comment by inorichi** [comment]
I was aware of this but sadly I haven't found any solution yet (besides some very ugly hacks I'm not going to add). There's also a notification you can click which will also open the installer, and the operation times out after 2 minutes IIRC.

I don't know if there'll be a fix for this.

**Comment by inorichi** [comment]
It timeouts after 10s when the apk has been downloaded now.
