### ISSUE TITLE
[Feature] Language organization for Extensions

### ISSUE THREAD

**Issue by dobbleg1000** [inorichi/tachiyomi#1235]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**
Nothing too tedious I hope. Just a way to organize the Extensions by Lanuage. Possibly by a collapsable group of some sort. There is already language information associated with it so hopefully this isnt too hard.

**Comment by inorichi** [comment]
They are sorted by package name now, which also sorts by language.
