### ISSUE TITLE
Cannot open file when downloading extensions from GitHub

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#1236]
When installing an extension:
- Tachiyomi closes
- The extension is downloaded

When clicking the download notification, the file is unable to be opened. Reopening Tachiyomi prompts to install the extension again.

r1340 (F-Droid) on 6.0.1

**Comment by secw** [comment]
Same issue here

**Comment by inorichi** [comment]
It should work now.

**Comment by wopian** [comment]
Fixed with r1341
