### ISSUE TITLE
readmanga.me (russian) doesnt load manga pages

### ISSUE THREAD

**Issue by Hulkmaster** [inorichi/tachiyomi#1238]
ver: 0.6.8
device: Nexus 5 D821
OS ver: 6.0.1

steps to reproduce:
1) open any manga from readmanga.me (russian manga site)
2) see "Retry" button (plain manga page behind)

tested with "Tales of demons and Gods", "Fairy Tail", "One punch man"

"Download" option doesnt work either

**Comment by Taumer** [comment]
Already fixed.
Use dev version or install extension from [here](https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk)

**Comment by Hulkmaster** [comment]
great, thx!
