### ISSUE TITLE
Feature Request: add custom manga

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#124]
Ok, so i know this isnt just an easy tweak but i think it'll be amazing if we could manually add a manga from images. For example, i follow a guy that draws web comics and i want to import them into tachiyomi. Doesnt need to have auto updates or anything. Just upload the images and a cover photo. Description is optional.

**Comment by inorichi** [comment]
If you mean #254, it will probably be supported one day. If you want to create a custom parser for a website, you should be be able to do that creating your own parser when I merge #239 (probably on 0.3.0)
