### ISSUE TITLE
smb support

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#1243]
Is it possible to add smb sharing support?

so say i have folders of manga on my windows pc that are shared over a network, tachiyomi could see those folders and read from them as if they were in the local folder.

perfect viewer seems to be able to do this if you want an example.

**Comment by GreyCannibal** [comment]
This can be a new extension ❤️
I'm currently using MiXplorer to browse on my manga on SMB server.

**Comment by arkon** [comment]
Can check out some extensions like Komga.
