### ISSUE TITLE
New sources

### ISSUE THREAD

**Issue by JohnPalace** [inorichi/tachiyomi#1246]
So, no more Bato.to, no more Mangafox and ReadMangaToday isn't working either.
I would recommend adding Mangadex and MagaGo.

**Comment by wopian** [comment]
Mangadex is in the dev version along with many others. 
(https://github.com/inorichi/tachiyomi-extensions/pull/163)

Whenever the next release happens, these catalogues can be installed from the sidebar under `Extensions` (https://github.com/inorichi/tachiyomi/pull/1101)

**Comment by CarlosEsco** [comment]
Both the sources are available as extensions though mangago is currently broken as they started encrypting their images.  Mangafox and readmangatoday work perfectly fine though I know mangafox is redirecting to different url for users outside of the us.  p.s all source request belong in the extensions repository

**Comment by JohnPalace** [comment]
Thank you for your answers.
