### ISSUE TITLE
Batoto login issue, needs fix for new ownership

### ISSUE THREAD

**Issue by onozukas** [inorichi/tachiyomi#1249]
![screenshot_20180211-040627](https://user-images.githubusercontent.com/36393167/36083247-88c10070-0f7e-11e8-9e1d-9c9f9cd14bd4.jpg)

Logging in using new batoto login doesn't work, this is the error I get after using my new login. I'm guessing tachiyomi is still linked to the old domain. If this is being worked on for 6.9 that would be great.

**Comment by CarlosEsco** [comment]
I don't believe there are plans to change batoto over as its just the same as mangapark, so you can use the mangapark extension

**Comment by onozukas** [comment]
I'm using the mangapark extension for f-droid, so I might as well keep using it, I guess I'm still trying to lach on to batoto of days past
