### ISSUE TITLE
Crashes and/or blank screen

### ISSUE THREAD

**Issue by Justtaway** [inorichi/tachiyomi#125]
Basically what title says, I get either crash with image decoder rapid or blank screen (only reloading helps) with image decoder skia whenever I try to read something.
I have Asus Memo Pad FHD 10 (ME302KL), 4.2.2 android version. I downloaded app from F-droid, 0.1.3 version.

**Comment by inorichi** [comment]
Have you tried dev version? Does it happen for every manga?

**Comment by Justtaway** [comment]
How can I get dev version? And yes, I tried several random mangas on different sites and it happens every time.

**Comment by inorichi** [comment]
There's a badge in the readme (main page). The one that says "Debug latest version". You can have both versions installed.

**Comment by Justtaway** [comment]
I'll try and see if I still have this problem.

**Comment by inorichi** [comment]
Ah right, someone had this issue before. I'll try to look for another approach.

**Comment by inorichi** [comment]
140bf8c and a90a4bf
