### ISSUE TITLE
New View Mode

### ISSUE THREAD

**Issue by JohnPalace** [inorichi/tachiyomi#1250]
Currently, we have 4 page-by-page viewing modes and 1 Webtoon mode.
I'm proposing expanding the 1 Webtoon mode into another 4:
1. Continuous (left to right)
2. Continuous (right to left)
3. Continuous (top to bottom)
4. Continuous (bottom to top)

This means that there will be 2 Viewing Menus in the App, one for Page Mode and the other for Reading Direction:
1. [Page by Page] or [Continuous]
2. [Left to Right] or [Right to Left] or [Top to Bottom] or [Bottom to Top]

**Comment by JohnPalace** [comment]
Actually, some changes. For the Page Modes, 3 options would be best: [Single] or [Double] or [Continuous]

**Comment by JohnPalace** [comment]
Also, this checkbox bellow the two menu:
[    ] Add spacing between pages

**Comment by arkon** [comment]
Horizontal webtoon: #2291

Can't see a bottom to top one happening.
