### ISSUE TITLE
Reading from mangahere is not working anymore

### ISSUE THREAD

**Issue by dutiona** [inorichi/tachiyomi#1251]
Hello,

I can't open any chapter from any manga from mangahere.cc. Images are not even displayed anymore in the catalog page (after a refresh in settings > advanced > refresh library metadata).
The website is up and working and doesn't seem to have changed its domain.

App Version : 0.6.8
Running on Android 7.0, Galaxy s7 non edge.

Thanks,
Michaël.

**Comment by CarlosEsco** [comment]
Their website is up but if go into any chapter its not loading on the website either.

**Comment by dutiona** [comment]
I missed that. So the issue is not related to the app :) . Sorry for the bother.
