### ISSUE TITLE
Error when trying to restore backup.

### ISSUE THREAD

**Issue by GumiFlatline** [inorichi/tachiyomi#1252]
Hi, 
As the title says, I'm getting a error message when I try to restore a backup. Here's the log message:

[tachiyomi_restore.log](https://github.com/inorichi/tachiyomi/files/1733381/tachiyomi_restore.log)

**Comment by Skcyte** [comment]
What source your mangas are? Is it from Batoto?

**Comment by NoodleMage** [comment]
Can you upload the backup Json file?

**Comment by GumiFlatline** [comment]
Sure, here you go (just rename the file extension as .json):
[tachiyomi_2018-02-16_15-46.zip](https://github.com/inorichi/tachiyomi/files/1733536/tachiyomi_2018-02-16_15-46.zip)

Also, almost every manga in this backup came from mangadex.

**Comment by Skcyte** [comment]
Tested with freshly installed r1344 and only Mangadex 1.2.4 installed.
No problems occurred only timeout, no chapter found and HTTP error 404.

**Comment by GumiFlatline** [comment]
Mangadex 1.2.4 isn't showing for me on F-Droid or Tachiyomi's native extension installer, but I'm using Tachiyomi version r1344.

**Comment by Skcyte** [comment]
I see. Please uninstall Mangadex 1.2.3 first. Force close Tachiyomi then open it up again, from there install Mangadex 1.2.4 using the built in extension downloader. 

*Just giving you some background. F-droid becomes unreliable now and the devs decided work on reliable alternative.

**Comment by GumiFlatline** [comment]
Funny enough, I had to reinstall Tachiyomi through F-Droid to make Mangadex 1.2.4 appear on native extension installer. Now it's working properly.

But yeah, it's good to know that I don't need F-Droid again. Having it installed just for Tachiyomi was a bit underwhelming.

Anyway, thanks for the help @NoodleMage @Skcyte! I'm closing this issue now.
