### ISSUE TITLE
[Minor Bug] Horizontal Progress bar doesn't show on tablet when reading Right to Left

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi#1253]
Using the dev version r1343 from F-Droid on both my phone and tablet.
On my tablet when a manga is set to read from Right to Left the horizontal progress bar doesn't show up, just the round blue dot that moves. Soon as you change it to read from Left to Right (or any other mode that changes the progress bar direction to be left to right, even webtoon) it shows again, white section for unread, filled in blue section for read and everything. This happens in both rotated orientations.

This doesn't happen on the phone.

Its super minor as the progress dot itself is the most important thing to see, but wanted to report it anyway.

Here are the 2 devices resolutions/OS incase its relavant:
Samsung Galaxy Tab S3:
2048 × 1536
264 ppi
Android 7.0

Nexus 6P
2560 x 1440
580 ppi
Android 8.1

[Edit]
I was able to reproduce this in a Genymotion VM by selecting a Pixel C as a base and changing its resolution to be that of the Samsung Tab S3. Selected 240 ppi as well as it was the closest option.

**Comment by inorichi** [comment]
#544 It's a bug in AOSP that only happens in API 24 (7.0). I tried a few things some time ago (wrapping the seekbar in a framelayout and rotating that one, but none helped). 

And if I don't rotate the view but invert the controls, callbacks are called when setting the initial state and it's even harder to get working.
