### ISSUE TITLE
[Feature Request] Preferred update time

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi#1254]
Basically, I want to make it so the app updates at the time I want, for example, if I set it so it updates once every 6 hours and set it to start updating at midnight, it'll update at 00:00, 06:00, 12:00 and 18:00, obviously it'll only update when it can (if you have restrictions on it) but even if it updates at 06:30, it should still update at 12:00 again.

**Comment by inorichi** [comment]
The JobScheduler doesn't let you wake the app whenever you want so it's not possible.
