### ISSUE TITLE
Can't find any title on MAL

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi#1258]
**App version:** r1347 / Android 4.1.2

After the last dev update, when I try to link some manga to MAL no titles ever show up in the search, I know there's issues with the API where sometimes it doesn't respond and you have to type something for it to search again but in this case nothing ever shows up no matter what I type. I see the loading circle and after that's done I just get an empty list.
I am logged in to MAL, can access it on a browser and can work with the API both on my computer and other apps on my phone.

**Comment by CarlosEsco** [comment]
Have you tried again since opening?  I had same issue when I read this but just tried again and it's working I'm guessing API might have been down.

**Comment by paulo27ms** [comment]
No luck, tried to clear cookies too and nothing. API is working fine for me on other apps.

**Comment by CarlosEsco** [comment]
ok let me try on a emulator for 4.1.2

**Comment by CarlosEsco** [comment]
working on something to fix this
