### ISSUE TITLE
[r1357] Error while trying to restore backup from r1344

### ISSUE THREAD

**Issue by GumiFlatline** [inorichi/tachiyomi#1261]
Hi,
[yeah, me again :v]

As the title says, I'm getting a error while trying to restore a backup from r1344 into r1357. I'm getting the following toast message: 
![screenshot_20180219-104945](https://user-images.githubusercontent.com/32400260/36381503-85dbc232-1564-11e8-892d-288bb4ac08d4.png)

Strange enough, when I tried to update Tachiyomi (r1344) using the dev version available here, on GitHub, I got a message telling me that the package installer couldn't find the app and/or the file was corrupt. Then, I uninstalled r1344 and installed r1357. 

After doing every basic step (updating extensions and login on trackers and such), I tried restoring my backup, but ended up with the error I mentioned earlier.

If it's needed, here's my backup file (rename to .json): 
[tachiyomi_2018-02-19_10-47.zip](https://github.com/inorichi/tachiyomi/files/1736974/tachiyomi_2018-02-19_10-47.zip)

**Comment by CarlosEsco** [comment]
Looking into but side note: why are you backing up and restoring every time you update dev?

**Comment by CarlosEsco** [comment]
Was this a fresh start meaning no manga was in the library during?

**Comment by Skcyte** [comment]
Tested on r1357, Mangadex 1.2.6

There's no problem actually just bunch of time out from Mangadex because their site is super super slow.
None of your problem mentioned above is happening to me.

I'm guessing that there's something happened with the app installation, maybe you should do like use SDMaid. I mean like cleaning all Tachiyomi related remaining files.

**Comment by CarlosEsco** [comment]
Its a tracker specific related issue, i believe.  @Skycte did you try restore to a tracker?

**Comment by CarlosEsco** [comment]
@GumiFlatline What tracker are you using also?  Im not able to repeat the issue

**Comment by Skcyte** [comment]
No I did not.

**Comment by GumiFlatline** [comment]
@CarlosEsco as I've mentioned, I tried to update Tachiyomi but I got a "app not found/file corrupted" error. That's I uninstalled and reinstalled it. Maybe it's because my r1344 came from F-Droid, which probably caused any conflict because of different signatures or such.

Anyway, I'm using Mangadex as source, but as soon as I try to restore my backup, I get the error mentioned earlier.

**Comment by CarlosEsco** [comment]
@GumiFlatline  what tracker are you using.   But yes you cant upgrade from fdroid to github since they had different signing key

**Comment by GumiFlatline** [comment]
I'm using AniList, but I found a workaround for my problem:

I removed every Tachiyomi folder manually and then used SDMaid (since I didn't root my cellphone because of specific problems with Moto Z's Mods). After that, I reinstalled r1344 and restored my backup (because r1357 keeps giving me the same error). And then I updated it to r1357 (no error this time).

**Comment by CarlosEsco** [comment]
ok go ahead and close for now and if someone has the issue again they can reopen.
