### ISSUE TITLE
No indication of installing extension

### ISSUE THREAD

**Issue by yambadr** [inorichi/tachiyomi#1263]
Version: 0.6.8-1357

Clicking install on any extension inside the app doesn't give any indication that the extension is being downloaded.

**Comment by inorichi** [comment]
Works for me.

Android version? Can you provide a video reproducing the issue?

**Comment by yambadr** [comment]
Ah sorry. It turns out that I had a custom DNS running and I totally forgot about it. I disabled it and it worked. Sorry about that.
