### ISSUE TITLE
Can't restore backup from main app to dev

### ISSUE THREAD

**Issue by briggsi** [inorichi/tachiyomi#1265]
Using 0.6.8 and r1347 with extensions for Mangadex, Dynasty, and MerakiScans (both installed from the FDroid repository and via the Dev extensions option, which have different numbered versions).

After making a backup with the main app (with all options checked), I tried restoring it to the dev app in order to use some of the newer features.  It fails without completing the first manga with this error:

![screenshot_20180219-221856](https://user-images.githubusercontent.com/8586304/36407987-1f1f8da8-15c8-11e8-8c1a-da1e1bbf64c1.png)

The first manga it runs into is from Dynasty, and it still happens after removing that one such that the first is from Kissmanga.

Last note while testing, unchecking "History" and "Tracking" from the create backup options, allows the dev version to continue on the backup, but everything from Mangadex and Dynasty return "Source not found" in the log.

**Comment by briggsi** [comment]
And now after uninstalling the dev version, FDroid won't let me download for some reason, so I downloaded r1357 from github.  It has all the extensions still installed, and the backup is currently going but very slowly (as expected from Mangadex right now) with the original backup with "History" and "Tracking".  I'll close since the problem seems to have cleared up.

**Comment by briggsi** [comment]
And now that it's finished doing it, I noticed I was not signed into MAL and all the tracking failed.  Trying to use the backup again proceeded to fail the same way as previously stated.  And after uninstalling and reinstalling r1357, it fails to use the backup whenever I am signed into MAL.

**Comment by CarlosEsco** [comment]
@briggsi 
Try this build let me know 

https://www.dropbox.com/s/bv4u4fikf0ohzid/tackiyomi-restore-fix.apk?dl=0

**Comment by briggsi** [comment]
@CarlosEsco

I'm getting a "package appears to be corrupt" error when installing that .apk.

**Comment by CarlosEsco** [comment]
[app-dev-debug.zip](https://github.com/inorichi/tachiyomi/files/1740700/app-dev-debug.zip)

**Comment by CarlosEsco** [comment]
[app-dev-debug.zip](https://github.com/inorichi/tachiyomi/files/1740904/app-dev-debug.zip)

**Comment by Sparh4wk** [comment]
well I have the same problem, but both on dev.. I have backup like from version 1345-1350 and now I cant restore it to 1353 for some reason. have the same error as OP.

**Comment by Flat** [comment]
There is a fix pending merge. #1269
