### ISSUE TITLE
Not all chapters being pulled down from Mangadex

### ISSUE THREAD

**Issue by karehaqt** [inorichi/tachiyomi#1267]
**App version: 0.6.8**

**Issue/Request: When doing an update on Mangadex, not all chapters are being pulled down. Mangadex spreads their chapters over numerous pages if there are to many so this could be the cause.  An example is B Gata H Kei, there are 100 chapters per page and only 100 are pulled down by the app.**

**Steps to reproduce (if applicable)**

 1. 
 2.
 3.

**Other details:**

**Comment by wopian** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/207

**Comment by karehaqt** [comment]
Aha no problem, didn't see that one so will close mine :+1:
