### ISSUE TITLE
Scaling images not working.

### ISSUE THREAD

**Issue by Justtaway** [inorichi/tachiyomi#127]
I tried all sorts of scaling types, but results are the same:
![This is how it looks](https://cloud.githubusercontent.com/assets/9951646/12922373/3708ad54-cf62-11e5-9445-49d5d58ef2dc.png)

**Comment by inorichi** [comment]
Well, that's because the images are so small. Try using Kissmanga or Batoto. I should increase the maximum allowed scale.

**Comment by Justtaway** [comment]
Actually, I made account for batoto and I get the same result.

**Comment by inorichi** [comment]
Try with the latest debug version again.

**Comment by Justtaway** [comment]
Yeah, it's working perfectly fine now. Thanks.
