### ISSUE TITLE
Failed to connect w/any catalog

### ISSUE THREAD

**Issue by camo43** [inorichi/tachiyomi#1277]
**App version:**

0.6.8
**Issue/Request:**

Tried downloading multiple chapters at once. After that i can't read any manga. From any source on the app. It shows "failed to connect to kissmanga(or manga fox, etc) xxx.xxx.xxx (port 80) from xxx.xxx.xxx (port: xxxxx) after 1000ms

**Other details:**
I have already gone to kissmanga on browser and resolved the captchas, erased cookies, deleted the app and installed it again. Tried to download the .apk file and s
Instaled the app again. Nothing worked.

**Comment by Skcyte** [comment]
There's a chance that your IP is banned. It's already been discussed about this problem, and the decision was to set/remove your multiple download off. The feature was disabled on the latest dev version.

**Comment by camo43** [comment]
I am sorry i did not realize sooner that i was banned. Odd thing is that i
usually dont alter the default config. I was just trying to queue like 15
chapters. But they usually download 1 at a time.

But i just checked now and i am able to read chapters again.

Thank you.

**Comment by camo43** [comment]
Update. It was just a few chapters i am still "unable to connect"

I guess i am blocked

**Comment by inorichi** [comment]
The extension is working correctly. You may have to use a VPN if you're blocked. Nothing we can fix from our side.

**Comment by camo43** [comment]
Thank you for the reply

**Comment by SchuwiUee** [comment]
i still have the same problem even if i use VPN

**Comment by SchuwiUee** [comment]
new user here
