### ISSUE TITLE
Unable to update extensions

### ISSUE THREAD

**Issue by SleepingPanda** [inorichi/tachiyomi#1279]
All versions of Tachiyomi that have the built in extension downloader.

Links to manually install the extensions.

I think it's only an issue with my device and can't be reproduced on others.

My Nexus 6P has issues with updating/downloading apps from the Play Store and its somehow affecting Tachiyomi's extension download feature. Clicking on update does nothing in Tachiyomi. It's not a firewall or app or setting preventing this. May be a bug with my device. I would just like a link to manually download and install the extensions. No fix necessary.

**Comment by wopian** [comment]
All of the extensions can be manually downloaded here:

https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk

**Comment by SleepingPanda** [comment]
Thanks very much!

**Comment by CarlosEsco** [comment]
@sleepingpanda you sure you don't have adblocker enabled

**Comment by SleepingPanda** [comment]
I have a pi-hole server on my network but the problem occurs on multiple networks. No other adblockers.

**Comment by nokusukun** [comment]
1.1.1.1 Also triggers this problem.

**Comment by metroid112** [comment]
Can confirm 1.1.1.1 application does affect the extension download as I brought up in issue #1848
