### ISSUE TITLE
Cant find the extensions on the Fdroid repository.

### ISSUE THREAD

**Issue by traferi** [inorichi/tachiyomi#1280]
I just did one factor reset on my tabled. After installing the Fdroid, and after add the source https://fdroid.j2ghz.com/repo, I could not find any extensions do the repository,  like the source readcomicsonline. I could only find the main app on the repository.

The place to download the extensions changed? I didn't find any information.

Thx.

**Comment by CarlosEsco** [comment]
Go to the extensions page and read the readme
