### ISSUE TITLE
Last updated filter not changing

### ISSUE THREAD

**Issue by wolfhowling** [inorichi/tachiyomi#1284]
**App version:**
0.6.8
**Issue:**
The sort by last updated by default is set to older first when I tap it again to change to newer first it does not work just stays the same, all the other filters work fine.

Update: I think is due to the fact that I did a restore so all of them appear as updated today.

**Comment by inorichi** [comment]
Yep, if you restore a backup that information is lost. It'll be built over time.

I'm not sure if the backup should contain that field, as that's its only use.
