### ISSUE TITLE
[Feature Request] Filter Out Specific Scanlation Groups

### ISSUE THREAD

**Issue by sgern** [inorichi/tachiyomi#1285]
**App version:**
0.6.8-1364
**Issue/Request:**
Filter out Specific Scanlation Groups
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
Would it be possible to, on a manga by manga basis, filter out chapters uploaded by specific groups? For example, if a manga had two groups, one uploading in black-and-white and one uploading in color, someone could filter out the black-and-white group's chapters and only have the color group's chapters show up, or vice-versa.

**Comment by Flat** [comment]
Duplicate #969
