### ISSUE TITLE
Weblate is down

### ISSUE THREAD

**Issue by Ancovens** [inorichi/tachiyomi#1286]
https://weblate.j2ghz.com/ is down

**Comment by Flat** [comment]
This is not a bug with tachiyomi. Please read the text before deleting it. Also see here https://github.com/inorichi/tachiyomi/pull/1274#issuecomment-369942801

**Comment by Ancovens** [comment]
Pls update the wiki link.

**Comment by wopian** [comment]
Its not currently live on the hosted projects yet - could be up to a month until that happens.

**Comment by j2ghz** [comment]
Wiki updated, you can close the issue.
