### ISSUE TITLE
Library Updates Sorting

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1288]
Wanted to know how the sorting works in Library Updates. 

If it's not by time, I would love to see it get implemented. I'm guessing the current sorting is by source?

**Comment by inorichi** [comment]
Do you mean the sorting of entries within a day ?

**Comment by bbtora** [comment]
Yes, it seems to re-do the order of the previous day too. Isn't there a way to just sort it by the time of release?

**Comment by hXtreme** [comment]
The default is to not explicitly sort it and therefore it checks for updates Lexicographically. 

Check out #1772 which sets up things to sort the order deliberately.

If you have a way in which you'd like your manga to sort for updates then let me know, I'll look into it.

**Comment by bbtora** [comment]
This request is not about sorting the updating order. It's simply about sorting the manga in the Library Updates section by the update time. 
As I said before, the order kinds of resets itself in alphabetical order after a day.

**Comment by hXtreme** [comment]
I see. I'll try to take a look at this soon.

**Comment by bbtora** [comment]
A fellow user created this to make the issue clearer: 

![Screenshot_2019-06-25-22-17-53-488-2](https://user-images.githubusercontent.com/23010526/60583424-7f75bd80-9da8-11e9-8e13-6944aeedf79e.png)

**Comment by CarlosEsco** [comment]
So question i have is were these added in 1 library update?  Just the chapter dates are 1, 5, 8?

**Comment by bbtora** [comment]
1, 5, and 8 represent the time of library update. As in 1am, 5pm, and 8pm

**Comment by arkon** [comment]
I believe this was adjusted at some point.

**Comment by bbtora** [comment]
I will take your word for it thanks :)
