### ISSUE TITLE
Various xkcd tooltip/mouseover Rendering Bugs

### ISSUE THREAD

**Issue by PatchSalts** [inorichi/tachiyomi#1294]
**App version:** HTC 10, Android 7.0 (November security patch), F-droid (dev) r1370, xkcd v1.2.3

**Issue/Request:** Various tooltip/mouseover text rendering issues. when words are too long, the text renders offscreen, and some chapters' texts are too big, and others fail to render certain characters.

**Steps to reproduce:**
 1. Open up any affected chapter (so far I've observed issues in chapters 111, 188, 196, 218, 238, 253, and 259).
 2. Scroll to the second page, the one that contains tooltip/mouseover text

**Other details:** The issues are divided into three categories:
1. The ones where the text renders offscreen (occurs when a word is too long to fit the screen, chapters 111, 196).
2. The ones where the text is rendered in a different font and is too big (occurs when the title or tooltip contain the character "#", chapter 188, 218, 238, 253)
3. The ones where the text is missing special characters (when rendering unsupported characters, chapter 259).
I have checked my conclusions with the website on a desktop in a browser, so I think I should be correct in my assessment.

The images I have saved from my observations:
![xkcd - 111 - firefox and witchcraft - the connection_ - 2](https://user-images.githubusercontent.com/9244116/37174235-f10269e4-22e3-11e8-94dd-69fc4b4ac98a.png)
![xkcd - 188 - reload - 2](https://user-images.githubusercontent.com/9244116/37174236-f11fc7d2-22e3-11e8-8d32-f5db78943cc4.png)
![xkcd - 196 - command line fu - 2](https://user-images.githubusercontent.com/9244116/37174237-f12c53bc-22e3-11e8-8d51-c7f20a9b7266.png)
![xkcd - 218 - nintendo surgeon - 2](https://user-images.githubusercontent.com/9244116/37174238-f13d6c38-22e3-11e8-8f87-bd3c698d9f67.png)
![xkcd - 238 - pet peeve 114 - 2](https://user-images.githubusercontent.com/9244116/37174239-f14b5fc8-22e3-11e8-9c44-e5bad63b1f29.png)
![xkcd - 253 - highway engineer pranks - 2](https://user-images.githubusercontent.com/9244116/37174240-f157821c-22e3-11e8-8253-d3e29e24be87.png)
![xkcd - 259 - cliched exchanges - 2](https://user-images.githubusercontent.com/9244116/37174241-f1643d72-22e3-11e8-988f-4d73e74bee8e.png)

**Comment by CarlosEsco** [comment]
Please close and open in the extension repo

**Comment by PatchSalts** [comment]
Oh, oops, thank you.
