### ISSUE TITLE
Make a "default" source

### ISSUE THREAD

**Issue by hortondorton** [inorichi/tachiyomi#1295]
First of all, very, very minor "inconvenience" issue, and I also have to admit I'm a sloppy searcher so I don't know if it has been brought up before, but here goes anyway.

I only use one source for manga (kissmanga) and it would simply be nice if I could skip a click and just go straight to it when I go to the catalog, which for me only consists of kissmanga and local manga. I believe it was possible in earlier versions that the latest source you used "locked" as your default and it was just very convenient.

Thanks for a great app.

**Comment by LakotaGray** [comment]
It doesn’t “lock” it, it only remembers it as the last source used. It’s as easy to click an alt source from sources screen as the last one used. I think it’d be more of a hassle to have to back out of a default each time. Personally I use several sources for most things and would prefer not having to click out of a auto loaded default source.

**Comment by hortondorton** [comment]
Semantics. Doesn't work on my app. And besides, I'm not asking to make it mandatory. Just a minor quality of life convenience for people like me that only use one source and only intend to use one source.

**Comment by inorichi** [comment]
Sorry but we can't implement this with the current UI.
