### ISSUE TITLE
[Feature Request]Sort by Score on "My Library"

### ISSUE THREAD

**Issue by nearbaskara** [inorichi/tachiyomi#1297]
**App version:**
r1370

**Issue/Request:**
I wonder if we can sort our bookmarked manga by score on our tracking sites. 

Why we need this feature: by sorting score, if we recommending manga to our friend or other people, it's easier and very convenient. 

**Steps to reproduce (if applicable)**

 1. Just as the title says.

**Comment by inorichi** [comment]
For now the library doesn't know anything about the tracking feature, and most probably this won't change. I'll consider again if/when it happens.
