### ISSUE TITLE
Extension tab doesn't work

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#1300]
**App version:0.70**

**Issue/Request: can't update or download from extension tab**

**Steps to reproduce (if applicable)**

 1.goto extensions tab
 2.press install/update
 3.it'll show pending but nothing will happen. After a while it'll show retry or go back to update/install

**Other details:the new update look great btw**

**Comment by CarlosEsco** [comment]
If you have an adblocker please disable and try again

**Comment by evo85210** [comment]
Thanks, turning off ad block does the trick.

**Comment by Aphyxia** [comment]
I had the same problem but had to disable the 1.1.1.1 DNS for the extension downloads to work. I'm not really sure why that would be the case but if anyone has that and this problem, here's the solution.
