### ISSUE TITLE
[Feature Request] Add new track for Shikimori

### ISSUE THREAD

**Issue by MrModest** [inorichi/tachiyomi#1303]
**Shikimori** is a Russian analogue of **MyAnimeList**. 
Site: https://shikimori.org/

I would like to add Shikimori support as like it implemented in MAL

The site has an open API:
https://shikimori.org/api/doc/1.0
https://shikimori.org/api/doc

Authentication with OAuth2 (other auth methods are deprecated and will be removed after 2018-07-01) 

P.S. Sorry by my English.
P.P.S. The site is quite popular
![voeooxzqx3](https://user-images.githubusercontent.com/13031058/37291450-b740a9b6-261f-11e8-8c44-555d8fd95985.png)

**Comment by Kuroyuki1** [comment]
Great idea for russian for comm.

_Random russian boy_

**Comment by Misaka0x2730** [comment]
Nice idea.
_Random russian boy._

**Comment by Kuromaru1** [comment]
Good idea.
Random russian boy.

**Comment by Gjmrd** [comment]
It would be very kindly if author will add Shikimori support to app. I had to suggest it earlier

**Comment by supremko** [comment]
Great idea, i think will be good add it.

**Comment by Kuroyuki1** [comment]
Meeeeeeh, and we have nothing

**Comment by AmineI** [comment]
This is available in the latest dev, although I didn't try it.
