### ISSUE TITLE
[Feature Request] Show chapter download size

### ISSUE THREAD

**Issue by Luisdv93** [inorichi/tachiyomi#1305]
I use data frequently but I don't have an unlimited data plan, sometimes when I'm close to my data limit I start wondering how many chapters I could download before running out of data.

I thought it would be nice if a download size for chapters could be implemented, wether is before the download or after they're added to the download queue. I'm sure this would be helpful for those of us with limited data plans.

**Comment by LakotaGray** [comment]
I actually think this would be a nice feature, but so I’ve any idea the space it’d take up in my memory/drive. 

As for the data usage, why not just wait until you’re on WiFi?

**Comment by CarlosEsco** [comment]
Wouldn't be able to show a download size until after they were already downloaded.  So I don't know how helpful that would be. All tachi has is a list of Image urls, and doesn't know quality or size of the images until after they are download from the source

**Comment by MrModest** [comment]
@CarlosEsco, and what about that before the download, read only the headers without downloading, summarize size from every link and show summary size?

**Comment by Flat** [comment]
While we could send http HEAD requests not all servers provide the `Content-Length` header. Additionally sending a bunch of HEAD requests for each image in a chapter may trigger IP bans depending on the limits.

**Comment by MrModest** [comment]
Indeed, I did not think about it at once.

**Comment by inorichi** [comment]
And not only that. In most cases you only have the url of the page containing the image, and we would have to request it, find the url of the image and do another request for the image headers, so it'd take a while to collect the size of the chapter.

So I'm closing this since it's not a feasible feature.

**Comment by MrModest** [comment]
@inorichi And if you show the size of the chapter after start the download? If the size is too large, will the user be able to cancel the download. Downloading a file, we already get its size, why not show it off then?

**Comment by CarlosEsco** [comment]
You would just see the total size after it already downloaded though..  So if you had a data limit it doesnt help you.  You already downloaded it
