### ISSUE TITLE
(Issue) Attemp to invoke virtual method (Can't download Chapters from any source)

### ISSUE THREAD

**Issue by Zahev** [inorichi/tachiyomi#1306]
**App version:**

v0.7.0
**Issue/Request:**

Can't download any chapter (from any source)
Error: Attemp to invoke virtual method 'com.hippo.unifile.Unifile[] com.hippo.unifile.Unifile.listF... 
(the error is too long to read everything)

**Steps to reproduce (if applicable)**

 1. Trying to download anything

**Other details:**
I can still read the chapters, but without downloading them (and I'm really dependent of offline reading)

The Downloads were normals on the afternoon of the 13th of March

![cfbf95964d520df759b5ae9480a3f7a1](https://user-images.githubusercontent.com/37358877/37384436-a17aa4d8-272d-11e8-88fc-f5c5e69d8aee.png)

**Comment by LakotaGray** [comment]
So your os version is what? is it an older one like 4.4.X?

There's a list of things to do/try in the #faq section of the tachi discord server. For quicker and more personalized assistance, join the server.

 But first things to check, do you have an ad-blocker of any sort? if so turn it off. Do you use a vpn at all? try it without it if you do.
Have you gone in Settings --> Advanced --> Cleared 3 sections?

**Comment by Zahev** [comment]
As I stated, my version is the most recent stable version (v0.7.0), and I don't use any adblock or vpn (my cellphone only has tachoyomi, messenger and what's up, it's mostly a clean phone) and I already cleared everything and didn't work out, this issue started from nowhere (and everything was fine some seconds before it stoppped downloading)

**Comment by wopian** [comment]
Lakota meant your Android version (Lollipop/6.0.0 etc)

**Comment by Zahev** [comment]
Android 5.0.1 (Galaxy S4 is the model)

**Comment by Zahev** [comment]
I Fixed the Issue, the problem was that my SD card couldn't get any files Transfered/Deleted, the main issue was that I had the "Developer Option" activated on my android, but after turning it off and restarting the phone, the issue was fixed! (Sorry for the trouble!)
