### ISSUE TITLE
Clear Cached Thumbnails for Catalog Search?

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi#1309]
Just curious if the original thumbnails for searched manga is permanently stored somewhere.

For instance if I search for a manga, add it to my library and then a few days later its cover changes, it will update in my library and search results.

But if you were to remove that manga from your library and go to advanced settings/clear database (removing info from manga not in your library) and search that manga in the catalog again, it will now show as the original thumbnail that appeared when you first searched it. If you click it, inside it will show the new cover, and seemingly update the thumbnail when you back out, but its only temporary until you clear the database again. It's like the new cover metadata takes priority over the original thumbnail cache, but never replaces/updates it (it will even show a custom set cover in the catalog search if you have it already added to your library and set one). So once its cleared, it defaults back to the original cache instead of re checking the source like it would on first search of that title on a fresh install.

Obviously this is not huge, but would it be possible to have an option in the advanced settings to clear the catalog search thumbnail cache along with the rest of the clear options? If you have a Tachiyomi install going long enough, eventually that cover cache will be pretty out of date if your not adding everything to your library.

[Edit]
This was tested with mangadex using the most up to date version of the extension/newest dev version, incase that makes a difference.

**Comment by inorichi** [comment]
Catalogue covers are backed by Glide's internal cache, which uses a LRU cache of 50MB so they aren't "permanently" stored. 

If you want to clear that cache (alongside other caches like the one of the reader), you can always use the "Clear cache" functionality of Android.
