### ISSUE TITLE
Getting 403/503 errors when trying to browse readcomicsonline

### ISSUE THREAD

**Issue by HereticWilson** [inorichi/tachiyomi#1310]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**
R1374
**Issue/Request:**
Source not loading 
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
Tried uninstalling and reinstalling the extension, did not work.

**Comment by CarlosEsco** [comment]
.. please close and open in the extension repository. You even copy and pasted what it you should have done. Also include extensions version when you do

**Comment by HereticWilson** [comment]
Sorry I thought that meant only post there if you wanted to request a new extension not if you had issues with a current extension.
