### ISSUE TITLE
Library does not prioritize downloaded chapters when filtered.

### ISSUE THREAD

**Issue by Chibicon** [inorichi/tachiyomi#1311]
**App version:** 0.7.0

**Issue/Request:** The library will not prioritize downloaded chapters in the chapter list when filtered by downloaded.

**Steps to reproduce (if applicable)**

 1. Download chapter that has multiple releases i.e. Chapter 7 From Group A while skipping Chapter 7 from Group B and Group C.
 2. Download Chapter 8.
 3. Advance From Chapter 7 Group A in the reader.

**Other details:** The reader should skip Chapter 7 from Group B and Group C and go directly to Chapter 8 but it will go through Chapter 7 by both skipped groups regardless of filter before going to Chapter 8.

https://imgur.com/Cl40qLG

**Comment by arkon** [comment]
Skipping filtered chapters was added recently.
