### ISSUE TITLE
[Feature Request] Hide adult sources in extensions.

### ISSUE THREAD

**Issue by Presac** [inorichi/tachiyomi#1312]
Would it be possible to hide every adult extension in the list? With the possibility of kids using the app, I think it would best for those to be hidden by default.

Every extension would probably need some kind of flag to specify them as adult material though.

**Comment by jerycho007** [comment]
It's pointless, I think. If you give your kids a smartphone they are going to find porn on the internet anyway without even trying. You can install the extensions and then hide them in catalogue options, that's a better solution and already implemented for your problem.

**Comment by HereticWilson** [comment]
Would also be a nice thing for people wanting a bit of help resisting the temptation of porn if they're trying to break that habit. That responsibility isn't on the developer's shoulders, though.

**Comment by Presac** [comment]
Both of you got a point, but it's a request none the less.

**Comment by arkon** [comment]
Basic support was added. It'll need to be iterated upon so that it can't be easily toggled by non-authorized users.

Followup issue to properly flag extensions: https://github.com/inorichi/tachiyomi-extensions/issues/4055
