### ISSUE TITLE
F-droid repo "Error getting index file"

### ISSUE THREAD

**Issue by risole** [inorichi/tachiyomi#1313]
**App version:**
1.1-alpha4

**Issue/Request:**
F-droid shows "Error getting index file" when swiping down.

**Steps to reproduce (if applicable)**
 1. download https://f-droid.org/repo/org.fdroid.fdroid_1001004.apk.* from https://f-droid.org/en/packages/org.fdroid.fdroid/
 2. gpg --verify org.fdroid.fdroid_1001004.apk.asc
 3. adb install -r org.fdroid.fdroid_1001004.apk
 4. Success output after adb command returns
 5. Settings->About F-Droid shows Version 1.1-alpha4

**Other details:**
On March 05 I downloaded and installed with "adb install" the FDroid.apk file at https://f-droid.org/FDroid.apk which (IIRC) reported itself when running as version 1.0.3 (although aapt dump seems to have showed it was version 1.0.2). At this time (March 05), I had no problems getting index file, installing, or updating apps. But 10 days later (today), I now see "Error getting index file".

Today both versions reported "Error getting index file" when swiping down. When I found this error today in 1.0.3 (1.0.2?), I did "adb install -r org.fdroid.fdroid_1001004.apk" and it too (1.1-alpha4) reported the same error. I rebooted the phone just in case it would help, but saw the same error after reboot too.

This is a custom ROM (by agentfabulous@Cloud2 built Feb 27, 2018), but it's the same custom ROM I was running on March 05 when I installed FDroid.apk for the first time on this phone.

Phone is the OnePlus One (bacon)
Android version: 8.1.0
Build number: OPM5.171019.014

I usually place a checkmark in the F-Droid setting "Only on Wi-Fi: Only update automatically on unmetered networks like Wi-Fi", but I tried both checking and unchecking this setting today and in both cases, I see the "Error getting index file" (see Screenshot attached). In any case, the phone is connected to both my Wi-Fi and my mobile networks.

![screenshot_20180315-160031](https://user-images.githubusercontent.com/28057740/37488405-e11b7476-286a-11e8-9d58-312854dc0041.png)

The phone seems perfectly functional in every other respect.

**Comment by Lionirdeadman** [comment]
Um, you're at the wrong place to report this.

Report the F-droid issue here : https://gitlab.com/fdroid/fdroidclient/issues

Tachiyomi simply allows F-droid to compile the application, it has no control over F-droid and its application.

**Comment by risole** [comment]
Oh! Sorry about that. I saw https://github.com/inorichi/tachiyomi/issues/823 and it was similar enough to my issue that I didn't look carefully to check it I was reporting in the correct spot. Thanks for passing the link for the correct spot.
