### ISSUE TITLE
[Feature Request] customizable categories on catalogues

### ISSUE THREAD

**Issue by pervertkirito** [inorichi/tachiyomi#1317]
Just like on [My Library], you can do custom list for manga like "unread", "complete", "favorite" etc.

as for now, I have installed more than 21 extension source.
Inside [Catalogues], I would like to request same feature like on [My Library], so I can separate(make list for) aggricator site and scanlator site.

thank you.

**Comment by inorichi** [comment]
Are you really using that many? There's a way to hide individual catalogues.

For now it won't be added, but it'll be considered when we revisit the UX of that screen.
