### ISSUE TITLE
Incompatible SDK API use which may cause crash to your APP

### ISSUE THREAD

**Issue by jay2013** [inorichi/tachiyomi#1319]
**App version:** eu.kanade.tachiyomi_33.apk

**Issue/Request:** Incompatible SDK API use which may cause crash to your APP

**Steps to reproduce (if applicable)**

**Other details:** 
Hi tachiyomi Developers,
I develop a tool to detect incompatible SDK API use in android application. Today I use my tool to check tachiyomi downloaded from F-Droid. My tool report many bugs. Although I believe most of them are real bugs, I cannot be 100% sure because I am not very familiar with Android developing. So
please help to check it, it must be very helpful to your APP.

The attachment below is the bug report that my tool give. please help to double check!
I also really hope to get your feedback.
thank you!

**[Supplementary explanation]**
There are totally two type of bug in the report. The first one is like this: "API called in method not in [list]", the list here are sdk levels, it means your app run under these SDK version can not call API because no such API in these sdk levels.
Type two is like "API called in method no living level", it means your application can never reach this API
use, so if these API uses are not in external library, you can remove it from your own code.

APIs or methods in our report are given in signature format like "<declaringType: returnType methodName(paramTypeList)>".

And finally, the reachable path is actually one possible call stack. it is always start from dummyMainMethod which is created by our tool. So you should read it from bottom to top.

Yes, many of these bugs seem to be in third-library codes. But it do cause problems in your app. Some third-library API say that they can only be run at specific SDK Level by using "@targetapi(Build.VERSION_CODES.N)", however, Application codes tend to ignore this warning.

Donejie He
hedongjie@ict.ac.cn

[eu.kanade.tachiyomi_33.apk.report.txt](https://github.com/inorichi/tachiyomi/files/1834381/eu.kanade.tachiyomi_33.apk.report.txt)

**Comment by null-dev** [comment]
All of these *bugs* are in external libraries, not our application code. I've checked most of them and most of them appear to be handled correctly in those libraries.

Thanks for the report anyways!

**Comment by jay2013** [comment]
yes, maybe they are okay in external libraries, but when you use them in your code, these SDK API use will cause bad effects to your app because these API may be not exist some of the SDK Versions that your APP support. 

In addition, we are trying to help you to reproduce some of them. Please wait for our good news.

**Comment by inorichi** [comment]
Thanks. I've also checked the report and there's nothing to be worried of. All those calls are properly handled by the respective library.
