### ISSUE TITLE
Kissmanga gives a 403 error

### ISSUE THREAD

**Issue by Timecrash** [inorichi/tachiyomi#1322]
**App version:** 0.7.0

**Issue/Request:** Kissmanga gives a HTTP 403 error when trying to access their search page or any bookmarked manga. I guess they must have changed their API.

**Steps to reproduce (if applicable)**

 1. Attempt to select Kissmanga from the Catalog.
 2. Alternately, select a manga saved to the Library that points to Kissmanga.

**Other details:** n/a

**Comment by Timecrash** [comment]
I can't edit issues, however I also noticed they recently added DDoS protection which waits five seconds before accessing the site. I recall this happening with another manga site, I think Batoto, so this might be the cause.

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/258

**Comment by Timecrash** [comment]
Clearing all data from the Advanced menu and loading the site in my browser worked. Thank you!
