### ISSUE TITLE
Most of Sources isn't working

### ISSUE THREAD

**Issue by efmavmim** [inorichi/tachiyomi#1323]
Mangafox, Mangahere, Kissmanga, Mangago etc. not working. And today myreadingmanga is alsa started giving error.

**Comment by LakotaGray** [comment]
Can you open this in the extensions GitHub instead please, this sounds more like an issue with your extensions than an issue with tachiyomi. Make sure you’ve updated all extensions and the latest version of tachiyomi either dev or stable. 

 If you have discord join the tachiyomi discord server and I can assist you live  right now.
