### ISSUE TITLE
Where's multiple downloading

### ISSUE THREAD

**Issue by ooluyid2** [inorichi/tachiyomi#1326]
It was a function before. You could download multiple files at the same time. now it's one.

**Comment by Flat** [comment]
It was removed as it was causing IP bans from several sources.

**Comment by Lionirdeadman** [comment]
What if this feature still existed *BUT* it only downloaded multiple from **Different sources**?

Example :
I download from Example.com and Example.org at the same time.

@NoodleMage

**Comment by LakotaGray** [comment]
You’re free to make the request as a feature request, after verifying there isn’t already an open request for that. However it’s unlikely to be implemented. Just be patient and wait for the download

**Comment by inorichi** [comment]
Simultaneous downloads is gone. Forever.

There were other, less relevant, reasons besides the IP ban. Like the behavior of notifications when using > 1 simultaneous download, a custom and not well tested Rx operator (incompatible with Rx2 btw), and new issues that will come when extending the downloader functionality.
