### ISSUE TITLE
Indonesia Languange

### ISSUE THREAD

**Issue by Muclaz** [inorichi/tachiyomi#1327]
Can you insert new languange for indonesia?  Maybe mangaindo.web.id can support you or mangacanblog for manga indonesia

**Comment by sleey** [comment]
Are u asking about [translation](https://github.com/inorichi/tachiyomi/wiki/Translation) or [extensions](https://github.com/inorichi/tachiyomi-extensions).

**Comment by lontong21** [comment]
He is talking about source for indonesian manga sites
Mangaindo.web.id is available on playstore
https://play.google.com/store/apps/details?id=id.matoa47.mangaindo
Which is copy of tachiyomi with ads but no credits to tachiyomi :-(

**Comment by CarlosEsco** [comment]
please close.  This is not the correct repo for source requests.

**Comment by Muclaz** [comment]
Yeahh I think you can report him ... They use your source but not permition
fisrt





Pada tanggal Kam, 29 Mar 2018 22.05, inorichi <notifications@github.com>
menulis:
