### ISSUE TITLE
Downloads to SD card fail, still works with custom path

### ISSUE THREAD

**Issue by lpchaim** [inorichi/tachiyomi#1329]
**App version:**
0.7.0

**Issue:**
Using the built-in default SD card path results in an error when trying to download chapters. The error notification reads `downloadsDir..` (probably cut off?). Setting a custom path to [SD path]/Android/data/eu.kanade.tachiyomi/files works as a workaround and restores expected functionality.

**Steps to reproduce:**
 1. Set download path to default SD one
 2. Try to download any chapter

**Other details:**
Logcat doesn't seem to contain any info relevant to this issue. Tried to clear app data, with and without restoring a backup, always same results unless I set a custom path.

**Comment by inorichi** [comment]
Android version required.

**Comment by lpchaim** [comment]
Android 7.1.1 here.

**Comment by arkon** [comment]
Old issue, resolving.
