### ISSUE TITLE
Filename / Directory containing % will make Local Catalogues error

### ISSUE THREAD

**Issue by rahadiancs** [inorichi/tachiyomi#1331]
Version: 0.7

Issue: If we put directory / file with % on it's name, the local Catalog will error. On my case I put Ichigo 100% doujinshi on it. After removing the %, it will works as usual.

Steps to reproduce:

 1. Copy directory / zip files containing % on it's name
 2. Browse Local Catalog
 3. Nothing showed, and there's only an empty notification and retry button on the bottom of the screen.

**Comment by inorichi** [comment]
What happens with .rar or folders? If it's specific to .zip I'm afraid it won't be fixed anytime soon, as it's using the built-in zip API.

**Comment by rahadiancs** [comment]
It's not specific to zip because it will trigger the error when you put a folder / directory with %.
