### ISSUE TITLE
Update to 0.7.0 hides the ReadComicOnline comcis

### ISSUE THREAD

**Issue by jotumn** [inorichi/tachiyomi#1333]
**App version:**
0.7.0

**Issue/Request:**
When I updated to 0.7.0, all my comics from ReadComicOnline disappeared (added through the old yaml method). However, when I press the update library button I can see their names displayed in the progress bar so they must exist in the database. I tried to install the extension but that didn't help. Selecting/unselecting any filters also does not do anything.

**Comment by CarlosEsco** [comment]
Yml has not been supported for a very long time. Switch to the internal extension

**Comment by jotumn** [comment]
I did but the problem is that there are invisible titles stuck in the rotation.

**Comment by LakotaGray** [comment]
Did you uninstall all the old extensions before trying to install new ones or internal ones? Are the old ones you have from Fdroid? Just to make sure everything is in proper order, uninstall all your extensions, and then install them again from within the extensions section of 0.7.0

**Comment by jotumn** [comment]
I did not have any old extensions except that YAML file that I downloaded from here (back when it had a link): https://github.com/inorichi/tachiyomi/wiki/YAML-Sources

Uninstalling/Reinstalling the extensions and removing that YAML file does not help the update still shows there are ghost comicbooks.

**Comment by inorichi** [comment]
Fixed on master.
