### ISSUE TITLE
Dead hosts/404 Missing

### ISSUE THREAD

**Issue by DarkWorld25** [inorichi/tachiyomi#1335]
**App version: 0.7.0**

**Issue/Request: Dead sources, 404 and 403 error**

**Steps to reproduce (if applicable)**

 1. Goto Mangafox, Mangahere, or Read omics online
 2. It will either give an 404 error, not found or not resolved

**Other details:**
Should be an easy fix if it's because of domain change or website redesign (relink the HTML divs)

**Comment by CarlosEsco** [comment]
None of those are dead, just verified.

https://github.com/inorichi/tachiyomi/wiki/Source-problems  or go on discord and ask support for help

**Comment by DarkWorld25** [comment]
Really? One of them were showing up as host not found (dead domain) and the other was showing up at 404 error (I just checked). I'll restart my phone to see if it'll help. :/

**Comment by LakotaGray** [comment]
go to your browser and verify sites are still up. Also try switching off wifi/cell data and to the other to ensure you're not having ip issue. But as of this post all of those sites are up and working. Well mangaFox never works for me so can't speak about that one

**Comment by demidude93** [comment]
ReadComicOnline extension seems to have stopped working for me as well. 

Using Tachiyomi 0.7.0 from fdroid repo and installing ReadComicOnline 1.2.1 internally. Trying to load the catalogue or a chapter from my library results in 503 or 403. 

Navigating to the site by browser works fine. No captcha required. I've also tried using the app from different IPs with no luck.

**Comment by LakotaGray** [comment]
@demidude93 For the future, back up your stable version, uninstall the fdroid tachi and install stable from Github to avoid future headaches. But either way update to 0.7.1. It has the fix for KissManga and ReadComicOnline in it

**Comment by demidude93** [comment]
@LakotaGrey Confirmed, ReadComicOnline extension is now working for me again as of tachiyomi 0.7.1

**Comment by inorichi** [comment]
Extensions issue.
