### ISSUE TITLE
[Feature Request]Search with a little error 

### ISSUE THREAD

**Issue by uni3que** [inorichi/tachiyomi#1337]
**App version: 0.7.0**

**Request: Searching with user input error**

 When making a search for a particular manga, Ex. Dragon ball: if the space between dragon and ball is not included (i.e. if like this Dragonball) the search is limited to very few mangas. Requesting the search to allow human error to be included and provide a wide range of search even with space/spelling mistakes; Intelligent search maybe.

**Comment by LakotaGray** [comment]
The issue I see with that is each source uses different ways of searching. So each extension would need to be coded to allow for the various permutations or combinations of potential results. I don’t know how feasible or labor intensive it would be to implement this, if it’s even possible. I kinda think with the cost/benefit of this feature being what it’s likely to be, it’s probably better to make sure you’re spelling things right. Or if you’re uncertain, type in part of the title, like “Dragon” and scroll through looking for the correct title.

**Comment by CarlosEsco** [comment]
Search is just using whatever the sources search is.  To add there is no way to know when to fix spelling or space mistakes. Tachiyomi only sees a string and just passes that to a sources search. What your are requesting would only be possible if tachiyomi had a database or all sources manga stored locally

**Comment by null-dev** [comment]
This is called "fuzzy searching" but since its really hard to implement in SQLite (the database software we store your manga in), I highly doubt this feature will be implemented.

**Comment by inorichi** [comment]
Tachiyomi doesn't know anything about what you're looking for. We don't have a populated db or something we can query.

Even if we were to use an online 3rd party service, it doesn't mean the catalog will have that specific title, so there's nothing we can do.
