### ISSUE TITLE
Don't show / search "UNKNOWN" info fields

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#1339]
If a filed like Artist is Unknown there is no need to perform a seach for that word or even show the whole field.

**Comment by LakotaGray** [comment]
I apologize, but I'm not sure what exactly you're referring to with this.  When/where is this happening that its becoming an issue?

**Comment by wopian** [comment]
Clicking on Author/Artist does a global search for their name @LakotaGray. This results in searching for `Unknown` for obscure and most local manga.

**Comment by arkon** [comment]
Just don't search for that then. ¯\_(ツ)_/¯
