### ISSUE TITLE
Feature Request: downloading single page

### ISSUE THREAD

**Issue by d3l4croix** [inorichi/tachiyomi#134]
when downloading a manga, sometimes i got few missing page. maybe tachiyomi can include function like long tap at missing page and choose refresh page / reload page something like that

**Comment by inorichi** [comment]
Try changing the image decoder. If the image fails to download a retry button should appear. In the debug version Rapid decoder informs when it fails.

**Comment by scriptmode** [comment]
I have the same problem. Changing the image decoder does not help in such cases, at least for me. From my observation, when I go to the actual website of that mangapage, I see often some kind of load-animation before the real page comes up. So probably the downloader get's some result, but fails to realize that it's not the desired one, and thus does not show a reload-button. Probably there is also some Javascript involved. Does the downloader can load stuff in this case?

I observed this on mangafox and mangahere. So it's not a single sites problem.

So, in general I also support a reload-function for single pages. There are all kind of possible failures which influence the download. Having a simple solution for solving them would enhance userfriendlyness. Additionaly, maybe also add a "Goto to URL"-Button, so you can directly go to the selected page in browser.

**Comment by inorichi** [comment]
The retry button should always show now, even when the decoding fails (I have to add this for the webtoon though).
