### ISSUE TITLE
Repeated 403/503 errors trying to load anything off Kissmanga

### ISSUE THREAD

**Issue by QuietusWolfe** [inorichi/tachiyomi#1340]
Ver. 0.7.0

I'm getting constant HTTP 403/503 errors when trying to load anything to do with kissmanga, even loading the catalog.

I've tried all other suggestions/steps from other requests about this (or similar issues) and none of them have worked.

**Comment by Hayate4506** [comment]
Same here, the ReadComicOnline extension also stopped working properly and is sending back the same errors as KissManga (HTTP 403/503).

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/258

**Comment by inorichi** [comment]
It seems Cloudflare [updated the challenge](https://github.com/Anorov/cloudflare-scrape/commit/798f1674706c38c7cab34a629788ed62c6337eac) so we'll have to update our interceptor.

**Comment by inorichi** [comment]
Please keep this open until I release a new version. Otherwise there'll be many more on this topic.

**Comment by QuietusWolfe** [comment]
OK

**Comment by NK-Uchiha** [comment]
When will this be resolved

**Comment by NK-Uchiha** [comment]
@Mattery how to use the dev version, I am new to the tachiyomi

**Comment by QuietusWolfe** [comment]
@NK-Uchiha just scroll down the main pace, under the Download area there's the "dev" link. the file should be labeled tachiyomi-r1382.apk. Just transfer that to your device and install it.

**Comment by NoodleMage** [comment]
or download from: http://tachiyomi.kanade.eu/latest

**Comment by QuietusWolfe** [comment]
The dev version won't overwrite the current release version, which is why you'll have to import a back up of your library.

**Comment by NK-Uchiha** [comment]
@Quietus Wolfe @NoodleMage thanks

**Comment by Herkarl** [comment]
The latest Dev release fixed this for loading manga, but I'm still getting the same error when trying to use the catalog.

**Comment by CarlosEsco** [comment]
if you are still getting issue do the following:

★ 503/403 issue with Kissmanga/ReadComicsOnline Fix-

• In Tachiyomi go to settings advanced  and clear cookies.
• Opened chrome go to website that is causing the issue.
• click a random comic/manga and click a chapter, let it load.
• Open Tachiyomi.
• go to catalouges and click the browse button the source that is having the issue
• it should work, if it does not click the retry button, after a couple retry attempts it should work.

≫ now you can go back to your library and read your chapters/downloads.

**Comment by phanirithvij** [comment]
That didn't work even in the dev version
The issue still isn't resolved

[Screenshot](https://imgur.com/gallery/naQAU)

**Comment by GyaragaX** [comment]
@CarlosEsco I have tried thisp process of cleaning the cookies repeatedly with both the release and Dev version. I normally use Firefox. I have tried loading in both my regular browser and Chrome and returning to see if the catalogue would load. It does not. It works the same in the Dev version as in the release.

**Comment by NK-Uchiha** [comment]
Yes @phanirthvij . It doesn't work
Just use dev it's working

**Comment by inorichi** [comment]
Try again after one or two hours. My guess is that the user agent is temporarily banned because of the previous failed attempts, as I haven't found any difference between the request of the browser and ours. It's missing `deflate` from `Accept-Encoding` and the `Accept` header (and both _should_ be totally irrelevant).

**Comment by inorichi** [comment]
It seems providing `Accept` and `Accept-Language` does help. I've pushed a new commit, an update should be available in the next 10 minutes.

**Comment by GyaragaX** [comment]
@inorichi I can confirm this has indeed fixed the issue. I appreciate the fix.

**Comment by Treekuma** [comment]
Is this fix implemented in just the dev version or in the normal one too?

**Comment by QuietusWolfe** [comment]
@Treekuma since the new version is 0.7.1 I'd say it's been committed to the main version by now.
