### ISSUE TITLE
Disappearing "downloaded" label on chapter lists

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi#1342]
My tablet is running android 5.1.1, after updating to 0.7.1 and r1387 today there is no longer a "downloaded" label on the chapters that have been dowloaded. Neither when looking at the chapter list while in source, nor in library. The chapters do download, and the download badge shows there are downloaded chapters, but it no longer displays which chapters are downloaded.

**Comment by inorichi** [comment]
Thanks. It should be good now.

**Comment by LakotaGray** [comment]
Works perfectly! Thanks for the quick fix!

**Comment by Silentarchangel** [comment]
Sorry, how was this fixed? I tried redownloading 0.7.1 and still have this problem

**Comment by rasc42** [comment]
@Silentarchangel You need to download the dev-version [here](http://tachiyomi.kanade.eu/latest) (Don't worry, it will not overwrite your stable version). And then you need to make a backup of your stable version, and load it in the new one.

**Comment by Nj97** [comment]
Hello, I really need to use the dev-version?
There is not any other way to put the labels back on the stable version?

Thanks in advance.
