### ISSUE TITLE
Local manga don't show/load the cover after format

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#1347]
**App version:**
r1389
**Issue/Request:**
Local manga cover will not load or show the cover after formatting 
**Steps to reproduce (if applicable)**

 1. Add manga from local catalogue
 2. Format phone
 3. Install and import tachiyomi settings (cover wont load/show)
 4. Create new directory in local different from the original name
 5. Move the archive files in the new directory (cover can be seen)
 6. Delete the old directory
 7. Rename the new directory to the old one (cover wont load/show)
 8. Rename the directory back to the new name  (cover can be seen again)
**Other details:**
Might also be an issue with an older version. I created those local directory a few months after local manga was introduced in tachiyomi.

**Comment by arkon** [comment]
Closing in favour of #932
