### ISSUE TITLE
Long tap manga addition isn't correctly added to Default Category

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi#1348]
Version: 0.7.1
OS: Android 5.1
How to Reproduce:
Possibly related to #1073 but with a bit different approach.
[Here's the video](https://my.mixtape.moe/otksbr.mp4).
As you can see, you can't find the first manga in "Default" Library, while the second ones that I added to custom category are successfully added instead.

**Comment by inorichi** [comment]
I can tell it's not related with the other issue.

In my case, I have 4 custom categories, and the setting as `Always ask`. When I long tap the manga from the catalogue, I get the dialog to move to a category. I closed it by clicking outside, went back to the library, and the manga was available in the `Default` category.

**Comment by atmazzerexe** [comment]
Ah, in the above case I clicked the "OK" button to trigger that. Clicking "Cancel" or outside the box will properly add the manga to Default library.
