### ISSUE TITLE
[Feature Request] Additional method for creating/restoring backup

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi#1349]
I can't use the default one because Documents/com.android.documentsui app from MIUI 9@Android 5.1 (File picker responsible for read/write files, indexing, etc. for applications) are bugged. I can't do a backup or restore no matter if that app is enabled or not.

Everytime I tried to backup or restore manga using the default method, Tachiyomi will crashed regardless of the version used. I can somehow restore them by force kill the Documents app and freeze it, which forcing it to use other file manager, but I can't do the same with the backup creation.

What I wanted here is basically another approach to create/restore manga (eg. directly with Root Access and/or by telling Tachiyomi to use alternative File picker/File manager).

**Comment by LakotaGray** [comment]
Can’t you change your default file exploring app to a different one?

**Comment by atmazzerexe** [comment]
already do that for restoring, but i can't do the same thing to creating backup somehow.
the app will just crash.

**Comment by bbtora** [comment]
"Documents" app on the MiUi (for some) is disabled by default so maybe check if that's the case with your device. If it is, simply enable it through app info.

**Comment by atmazzerexe** [comment]
I already know that, as I always tweaked them by enable it/killing it. Please read the above.

**Comment by arkon** [comment]
I haven't heard of any other XIaomi users complaining about this, so I figure MIUI has been fixed?
