### ISSUE TITLE
Categories dialog: Categories not ticked

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#135]
When a manga is in category and you want to remove it, the dialog has no categories checked, even if the manga is in some of them. To remove it you have to   tick and untick desired category.
r456

**Comment by inorichi** [comment]
That could only be possible if all the selected manga is in the exact same categories. You can select from multiple categories at once, and I'm not sure ticking categories only when the selections are from the same category is a good approach, because otherwise nothing is selected and it could confuse the user.

**Comment by j2ghz** [comment]
Tri-state checkbox?

**Comment by inorichi** [comment]
There's no native support for tri-state AFAIK (there should be an implementation somewhere though). Also, I have to create a custom view for material dialogs. For now, it's not a priority.

**Comment by Trudd** [comment]
I suppose my request is close to this request, but seems to be only partially so? Perhaps I'm misunderstanding this request? Or the answer to it?

> You can select from multiple categories at once, and I'm not sure ticking categories only when the selections are from the same category is a good approach, because otherwise nothing is selected and it could confuse the user.

I'm afraid I don't understand the part about "only when the selections are from the same category". If I have a manga in the categories All, Good and Mangafox, I would simply expect to see all those categories checked if I try to change the categories for this manga. No matter from which one of those categories I'm trying to do the change from. If I de-select one it is removed from that category. And if I de-select all, the manga ends up in the default category, same as newly added mangas from a source would do.

**Comment by inorichi** [comment]
I meant I can only select the union of the selected list. With tri-state the categories outside the union could be marked too.
