### ISSUE TITLE
Tachiyomi broken on wifi

### ISSUE THREAD

**Issue by Syzain** [inorichi/tachiyomi#1350]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**
0.7.1
**Issue/Request:**
After disconnecting on wifi tachiyomi stops working(4g still works)
**Steps to reproduce (if applicable)**

 1. disconnect from wifi for whatever reason
 2. that's it, it just breaks on all forms of wifi after that
 3.

**Other details:**
so i've been having this weird issue on tachiyomi where after disconnecting on wifi tachiyomi just seems to stop working, i cant update any chapters at all, i cant browse the sources and of course im unable to read anything.  once i go on 4g it works again but it is slow and im hoping for a fix.  ive reinstalled tachiyomi a few times and it works to the point where i disconnect, after that i got nothing.  ive gone to the sources from their website in case it was a cloudflare issue but still nada

**Comment by CarlosEsco** [comment]
When your on wifi can you actually access the source you are using through chrome? My guess is your WiFi ip is banned

**Comment by Syzain** [comment]
first thing i tried, still nothing

**Comment by Syzain** [comment]
Yes I did? I've said so multiple times in this post

**Comment by LakotaGray** [comment]
This sounds like an issue with your system. The discord server might be a better place for support

**Comment by Syzain** [comment]
Thank you for the help
