### ISSUE TITLE
Parse error 0.7.2

### ISSUE THREAD

**Issue by deebeepea** [inorichi/tachiyomi#1353]
**App version:**
0.7.2
**Issue/Request:**
I can't update my tachiyomi to 0.7.2 cause its say "parse error" I tried downloading it here and it also said the same thing.
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
My phone is Version 6.0 marshmallow btw.
And it's my first time posting here

**Comment by LakotaGray** [comment]
Did you originally install the stable from fdroid?

**Comment by deebeepea** [comment]
No I got it here

**Comment by deebeepea** [comment]
Now its installing fine  but what happened yesterday cause when I tried downloading the update yesterday from here it says "parse error even in the tachiyomi update automatically
