### ISSUE TITLE
Change notification priority for ongoing notifications (i.e. page downloads)

### ISSUE THREAD

**Issue by roseyhead** [inorichi/tachiyomi#1354]
**App version:**
0.72

**Issue/Request:**
I have a Pebble smartwatch and when I download a chapter my watch buzzes every time the page count increments. Ideally these would be low-priority notifications, the kind that aren't sent to notification-watching apps (smartwatch apps, Pushbullet etc.)
I can mute Tachiyomi through my watch so I don't get any notifications but I do want important notifications such as new chapters.

**Steps to reproduce (if applicable)**
 1. Install an app with notification access
 2. Download a chapter

**Comment by arkon** [comment]
Closing this since Pebble is long dead. I think the priority is correct as it is currently from the Android system perspective. Not sure how Pebble handled that.
