### ISSUE TITLE
Data gone

### ISSUE THREAD

**Issue by Idesmi** [inorichi/tachiyomi#1356]
**App version:** 0.7.1

**Issue/Request:** After the update, the application's data are back to default

**Steps to reproduce (if applicable)**

 1.Update from 0.7.0 to 0.7.1 via F-Droid
 2.Open the app
 3.All the settings are back to default and the catalog is empty.

**Comment by inorichi** [comment]
The only changes between those versions are UI related and the cloudflare update. There wasn't any database update nor data manipulation.

I'd wager on these two:

1. You uninstalled before updating.
2. Android fucked up during the update.

**Comment by Idesmi** [comment]
@inorichi I opt for the 2nd. I'd backup, if at least it worked. Closing.

**Comment by inorichi** [comment]
If you still have the logcat by the time you updated, we might get some more information. Otherwise I'm afraid I can't help, but I doubt you'll be able to recover the internal data anyways.

I'm not aware of issues while creating backups though, at least to the external storage (not SD cards).
