### ISSUE TITLE
[Feature Request] Add option to edit MyAnimeList start and finish date from the Tracking view

### ISSUE THREAD

**Issue by zhantyzgz** [inorichi/tachiyomi#1358]
**App version:** 0.7.2

**Issue/Request:** It would be nice if you could edit your personal start and finish date of a manga directly from Tachiyomi, just like you can edit your status and score.

**Other details:** Screenshot of the MyAnimeList edit panel: https://puu.sh/zZLTm/a68c15a79c.png

**Comment by Tixx7** [comment]
**This**

**Comment by arkon** [comment]
Marking as duplicate of #2670
