### ISSUE TITLE
Log in to mangadex and see followed mangas

### ISSUE THREAD

**Issue by nnyeh** [inorichi/tachiyomi#1359]
**App version:** 0.7.1

**Issue/Request:** Would be nice if you could log in to mangadex and you could see your followed mangas

**Other details:** Haven't come across a single mangareader that can do this, so this one would be the first

**Comment by CarlosEsco** [comment]
1.  This is an extension issue so should be closed and opened in that repo.

2.  Login is currently supported for extensions. Even if it was, I doubt it would be implemented cause it would require a complete rewrite of screens and what not to show the followa
