### ISSUE TITLE
Can't open custom directory

### ISSUE THREAD

**Issue by ArbitraryFox** [inorichi/tachiyomi#1361]
**App version:**
0.7.2-1392

**Issue/Request:**
Can't set custom directory. It tries to open root folder and nothing can be changed

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by Flat** [comment]
What custom directory? What can't be changed? You need to be more descriptive in what is happening. The steps are there for a reason.

**Comment by ArbitraryFox** [comment]
Sorry turns out it was my mistake. I froze a system app that gave access to the storage directory.
