### ISSUE TITLE
Collapsing error in Tracking search

### ISSUE THREAD

**Issue by Kavboy** [inorichi/tachiyomi#1363]
App version:
0.7.2

Issue/Request:
When you try to manualy search for a manga in tracking it collapses the found mangas

Steps to reproduce
Search manualy for a manga in the tracking and then press return to collaps the keyboard
(Only happens if search returns multiple mangas)

Other details:
Android 7.0
Tracking Service: Anilist

![grafik](https://user-images.githubusercontent.com/24781933/38612425-f4442526-3d86-11e8-9bd0-d7bfbfc0a0c3.png)

**Comment by inorichi** [comment]
Sadly I tested this screen before releasing 0.7.2 but the title had only one result and I didn't find this issue...

Fixed in 6de36a8
