### ISSUE TITLE
MangaDex sort of not working

### ISSUE THREAD

**Issue by MakinoTheHermit** [inorichi/tachiyomi#1365]
Issue/Request:
When clicking a series in the MangaDex Catalogue, a message saying "com.google.gson.stream.MalformedJsonException: Use
JsonReaser.setLenient(true) to accept malformed JSON at line 1 column 7 path $" appears. If the series is already in my Library Chapters are accessible but if i try refreshing/updating it, the message appears too

**Steps to reproduce (if applicable)**

 1. Go on Catalogue of MangaDex
 2. Click on a Series
 
OR

1. Select a series in Library from MangaDex
2. Swipe down to update series

**Comment by bbtora** [comment]
First of all, this is an issue with the extension and not the app itself so this post doesn't belong here rather than in [https://github.com/inorichi/tachiyomi-extensions](url)

Secondly, this issue has already been posted there and waiting to be resolved.

**Comment by MakinoTheHermit** [comment]
oh, okay yeah sorry, its been a while and didnt know about the extension site. Thank you for informing me.
