### ISSUE TITLE
[Feature Request] Incognito Mode or Ignore Catalogue

### ISSUE THREAD

**Issue by jfields99** [inorichi/tachiyomi#1371]
0.7.2

I would like someway to temporarily disable the Recently Read section, either through an Incognito Mode or through ignoring certain catalogues being read.

Android 6.0

**Comment by arkon** [comment]
I'll leave this for the hentai forks.

**Comment by lmj0011** [comment]
I can see this feature being a great convenience to users with OCD.

Unfortunately I fall in that category...

I like to flip through a few pages or chapters of a manga (not always hentai) to see if I'm going to like it before adding it to my library for later reading. This process usually ends with me marking the chapter(s) as read and then unread to reset its state. This process is can be tedious although it's unnecessary in the first place.
