### ISSUE TITLE
[Bug] Tracking search problem

### ISSUE THREAD

**Issue by deebeepea** [inorichi/tachiyomi#1372]
**App version:**
0.7.2

**Issue/Request:**
Tracking search sometimes small when multiple manga title shows
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
https://drive.google.com/file/d/1AZIZa7Hds7gyc39v6x35qzaEl_e5HUYU/view?usp=drivesdk
I'm not very good at english thats why Im giving short explanation sorry

**Comment by CarlosEsco** [comment]
I believe this is fixed in latest dev already

**Comment by Chibicon** [comment]
It is. Same problem I had in stable last Friday. Can confirm it is fixed in dev.
