### ISSUE TITLE
Tracking glitch when searching for manga

### ISSUE THREAD

**Issue by BloodOath08** [inorichi/tachiyomi#1373]
**App version:**
v0.7.2
**Issue/Request:**
I'm sorry if the title didn't seem very clear. This is a visual glitch that seems to occur frequently, it makes searching a bit frustrating. The  screenshot below is easier than me trying to explain it.
![screenshot_20180418-233729](https://user-images.githubusercontent.com/32828655/38935912-de797eee-4362-11e8-9e6c-8188e243c4b0.png)

**Comment by CarlosEsco** [comment]
already fixed in latest dev.

https://github.com/inorichi/tachiyomi/commit/6de36a88c04363a4669b62fbec0c7b8a3f2b64c3
