### ISSUE TITLE
Remove Local titles from Library Updates

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1374]
As the title says, it would be much better if local manga are not included in the Library Updates section. If we add some folders in the library then the Updates section fills with chapter list.

Also, adding a new manga from a source triggers previous chapters to be also included in the library updates.

**Comment by hXtreme** [comment]
The problem with adding new manga from source should only happen when using long press to add or adding it before chapter information is loaded (because of internet speed).

It that right or do you get it for any other cases as well?

**Comment by bbtora** [comment]
This happens even when the chapter list is loaded before adding the manga.

**Comment by hXtreme** [comment]
Which source does this happen with?

**Comment by bbtora** [comment]
It happens with almost every source. 

Aside from that, this issue was mainly for the local manga titles.

**Comment by arkon** [comment]
I don't think this happens anymore.
