### ISSUE TITLE
Image Decoder?

### ISSUE THREAD

**Issue by LordAlmond** [inorichi/tachiyomi#1375]
Ver 0.7.2
Issue:
![screenshot_2018-04-19-09-11-32](https://user-images.githubusercontent.com/38513518/38965874-bb5e1012-436e-11e8-887f-f71c810a022c.png)
Downloading from MangaFox,
After said manga chapters are dl'd, i cant open/view said chapters.
The following will appear

Even "Open in browser" leads to errors
Heres an example from Dagashi Kashi Chap 124
the link given was [http://a.fanfox.net/store/manga/15186/07-124.0/compressed/i008.jpg?token=25cb3974f93b90c9c2357964fe3e4e5a2c6337be&ttl=1524171600]
Opening said link will result in the webpage saying
![screenshot_2018-04-19-09-14-14](https://user-images.githubusercontent.com/38513518/38965927-09be312e-436f-11e8-89e2-09e04424ce33.png)

On other Issues
![screenshot_2018-04-19-09-13-16](https://user-images.githubusercontent.com/38513518/38965898-df7de5a8-436e-11e8-91c0-62690ed43059.png)
Under Catalogues, When selecting Mangadex, No results found even if i didnt search for a title
Jaimini's Box is working
KissManga is working
Mangahere is working
Mangafox is working

Small note
Recently Vers 0.7.2 will suddenly crash, and all above incidents started only a few days ago,
although said update was released 9?days ago

**Comment by CarlosEsco** [comment]
1st these are extensions issues so shouldn't be opened on this repo. 

2nd if the chapter doesn't open in browser there is something wrong with source so nothing we can do 

3rd.  Mangadex you aren't on latest extensions

**Comment by thomasprat49** [comment]
The bug is also on the tachiyomi app. 

It's seems that mangafox changed it's url for their images. The one in the example fir example is now : http://s.fanfox.net/store/manga/15186/07-124.0/compressed/i008.jpg?token=25cb3974f93b90c9c2357964fe3e4e5a2c6337be&ttl=1524171600

**Comment by CarlosEsco** [comment]
What manga is that

**Comment by thomasprat49** [comment]
It's the Dagashi Kashi Chap 124 page 9, the one from the post of LordAlmond.

**Comment by CarlosEsco** [comment]
Worked fine for me in app

**Comment by CarlosEsco** [comment]
Try clearing your chapter cache and reloading chapter list

**Comment by thomasprat49** [comment]
I've done it but some chapters of manga from mangafox doesn't load whereas other works. It must be a problem from their side. It's ok, I will go see them on another source. Thank you

**Comment by R-N** [comment]
I've been experiencing this too since I updated the app on late March or early April. 

It only happens on downloads. Though, it loads just fine when I read online. It loads quickly with the same connection so I think my connection isnt the problem (it downloads just as quick). Changing the decoder before or after downloading doesn't help. I'm mainly using MangaSee. Just tried MangaRock, same thing happened. Havent tried other sources since most sources are unavailable to me as my ISP block em.

Should I just open a new issue?
