### ISSUE TITLE
Date format used for release.

### ISSUE THREAD

**Issue by dinosw** [inorichi/tachiyomi#1377]
**App version:**
0.7.2
**Issue/Request:**
The release dates are shown in US format only. 
Could you please change this to the international standard? Or add other date formats as options? 
In Europe we use "dd-mm-yyyy". 
The international standard is "yyyy-mm--dd", which is also what the Japanese use. 
I would be happy to use either of the abovementioned date formats =)

**Comment by inorichi** [comment]
Date format depends on the locale being used in your phone. If you forced english as language in the app (`en`), it uses american english dates. This is probably fixed by dividing english into `en-US` and `en-GB`.

**Comment by arkon** [comment]
Surprisingly, `en-CA` uses the ISO format.

**Comment by inorichi** [comment]
968f4a6
