### ISSUE TITLE
Syntax Error: Parse Error (line 1)

### ISSUE THREAD

**Issue by dylanbarnes65** [inorichi/tachiyomi#1378]
**App version:**
0.7.2
**Issue/Request:**
I'm getting an Syntax Error whenever I try to download a new chapter from Kissmanga. Kissmanga is the only one I use so I don't know if it is affecting others. What can I do to remedy this?

**Comment by Vesnyx** [comment]
Is this issue still occurring? If it is, can you move this request into the other repo at  https://github.com/inorichi/tachiyomi-extensions/issues
