### ISSUE TITLE
Import / export between devices

### ISSUE THREAD

**Issue by Pizz001** [inorichi/tachiyomi#138]
Hi, 
i may have missed it ( please point the way if i have) 

as only just started trying this out after using mangawater from when it was first on googleplay

is there a way to import / export my library between my android devices

but so far have found it very nice and runs well on my zenthink c94 tablet 
( going to test it on my S6 later on , heace the request )

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/34

**Comment by inorichi** [comment]
Duplicate. It should be available soon (on dev version).

**Comment by Pizz001** [comment]
Thanks for the answer all :)
