### ISSUE TITLE
[Feature Request] Non-invasive Notification for Extension Updates

### ISSUE THREAD

**Issue by K1LL3RR0N1N** [inorichi/tachiyomi#1382]
Sorry if this is in the wrong section but I thought it fit this side better.

Could a notification be added to the app for when extensions update?
A lot of times, I don't really notice when extensions have issues except I click on the extensions tab accidently or its a major extension I use that's been broken for a while.

I don't think anything that stands out too much is necessary, so there's no need for a message from the app to notify an extension update but like maybe a small circle next to the extension tab on the menu drawer would be nice, just to highlight that something's been updated. This should probably only affect installed extensions.

**Comment by arkon** [comment]
A badge on the extensions item in the nav drawer might be a good solution.

**Comment by Ramon20000** [comment]
As someone who has now 24 titles and over 100 chapters to read due to that i second that motion. A simple exclamation on the sidebar menu would have avoided that.

**Comment by arkon** [comment]
Closing in favour of #2520.
