### ISSUE TITLE
Library update frequency Isn't working

### ISSUE THREAD

**Issue by yoohoox8** [inorichi/tachiyomi#1385]
**App version:**
0.7.2
**Issue/Request:**

I have the Amazon Fire HD 10 2017 Tablet running Fire OS 5.6.1.0 and for some reason the library update frequency isn't working. 

I can update my library manually no problem and there are no restrictions to it. What can I do to fix it?

**Comment by LakotaGray** [comment]
What do you mean by “library update frequency isn’t working”?
-Can’t get settings to apply? 
-it isn’t updating? 
What specifically are you referring to and what is happening that seems to be an issue or error?

**Comment by inorichi** [comment]
Try disabling/enabling the setting. If you're using the F-Droid release, keep in mind google services can't be used and neither their scheduler. If the API of your underlying Android OS is < 21 (Lollipop) you can't also use the JobScheduler, so you're left with the alarms API which works quite bad.

**Comment by yoohoox8** [comment]
Sorry if I wasn't clear. My manga library isn't updating on the automatic schedule I set it to. I can manually updated each time without a problem, but it isn't updating based off the automatic schedule. The version I am using isn't the F-Droid release.

**Comment by SlothCavalry** [comment]
I also recently noticed I had this issue. However attempting to change the frequency crashes to home.

**App version:** 0.7.3

**Android version:** 4.1.1

**Comment by arkon** [comment]
This is pretty old and the underlying implementation has changed since. Open a new issue if still seeing it in newer versions.
