### ISSUE TITLE
Switching to a new SD Card

### ISSUE THREAD

**Issue by karehaqt** [inorichi/tachiyomi#1391]
I'm running out of space on my current SD card and am planning on getting a 256GB card.  How would I go about moving my manga so Tachiyomi sees it all again once I've moved everything to the new card?

**Comment by LakotaGray** [comment]
You’ll direct the pathway in settings to the new card. You’ll also need the move the folders with the names of sources you use, i.e “MangaDex” or MangaHere etc into the new pathway.

**Comment by karehaqt** [comment]
Thanks for the help, did what you advised and everything is back to how it
was on my smaller card 😁

**Comment by LakotaGray** [comment]
Great! Happy to help. If you need anything else or wanna chat with other users, come to the discord server. Can you close the issue now or was there anything else?

**Comment by karehaqt** [comment]
Thanks again, I'll go ahead and close this down now 😁
