### ISSUE TITLE
[Feature request] stretch to fill screen

### ISSUE THREAD

**Issue by TyranitarTar** [inorichi/tachiyomi#1395]
Some of the Comic Viewers on Android have this feature called "stretch to fit screen" where the image is deformed so it fits fully on the screen, so that no screen space is wasted.

I don't know whether this would be difficult to implement, but considering how much screen space isn't being used on 18:9 aspect ratio phones when reading Manga, I think it would be a worthwhile feature to add for some people.

Here's how the feature is used in Perfect Viewer in a side-by-side comparison with Tachiyomi on my Galaxy Note 2:
![tachiyomi vs pf viewer](https://user-images.githubusercontent.com/35216227/39515575-d1bb43d4-4dfa-11e8-893d-82eb3ee2f9d1.png)

**Comment by pervertkirito** [comment]
you mean this?
![](https://i.imgur.com/D0FcQMS.png)

**Comment by CarlosEsco** [comment]
As someone with a long phone why would you want that.  It stretches the images and people

**Comment by TyranitarTar** [comment]
@CarlosEsco I politely ask you to reconsider, I know it feels unnatural to distort the image, but I feel it is a cheap trade-off for the improved readability, here's an example of how the image would look on a 16:9 not stretched versus 18:9 stretched to fill the whole screen

Personally I feel the difference is pretty minuscule, and it is a cheap trade-off for 40% larger letters.

![18-9 vs 16-9](https://user-images.githubusercontent.com/35216227/39520355-9b23942e-4e0a-11e8-9b3f-e0ea5a143527.png)

**Comment by CarlosEsco** [comment]
Why not just use webtoon viewer? Space is then used and you don't get distortion

**Comment by inorichi** [comment]
Try to stretch a landscaped/dual page image. I really doubt it'd provide that "improved readability".

**Comment by TyranitarTar** [comment]
I apologize if I've caused offense by bringing this up, and if Inorichi isn't interested in implementing such a feature, I'm not going to push the issue.

I merely wanted to say that I've seen other comic readers implement such a feature, and that I personally have enjoyed using it.

**Comment by CarlosEsco** [comment]
No offense was taken, I personally just  don't see the benefit

**Comment by inorichi** [comment]
Yeah, me neither. 

Breaking the aspect ratio can (and will) lead to some hideous images. When the aspect ratio difference is small it's not really problematic (I still find it horrible) but you can't expect this difference to be constant.

Furthemore, the value added by this feature is small compared to the amount of changes that would be required in the image library due to the subsampling, and honestly, I don't want to modify it anymore than I already have.

For these two reasons, I'm sorry but I'm not going to implement this.
