### ISSUE TITLE
[Feature Suggestion] Add page flip like Google books or ibooks

### ISSUE THREAD

**Issue by robzombie91** [inorichi/tachiyomi#1397]
1. I absolutely love this app, its the one ive been serching for on the play store but none live up to it plus its free without ads but would absolutly pay or donate for it if it was available.

"Enough ass kissing"

Not sure if this is a reasonable request but i would love to see page flipping like ibooks or google books if it can be done.

**Comment by jogerj** [comment]
I like reading my mangas as is. It's faster, it's easier, it's smoother. I never liked those book flip animations, it just makes them feel even faker. In the case of webtoons, they were meant to be read the way it is and would not translate well most of the time with sideways reading, moreover adding flip animations in between. 

This should go to the bottom list of priorities to do.

**Comment by null-dev** [comment]
I'm actually a huge fan of the book animation thing but I've never bothered to open an issue about it so +1 here.

I think I remember a library implementing this when I tried to write my own reader so I'll dig around a bit. It should be just plug-and-play if I can find it.

**Comment by Flat** [comment]
Most implementations that I've come across use OpenGL which would require a lot of changes if not an entire rewrite of the reader.

**Comment by InFlames03** [comment]
@jogerj Having it as an option shouldn't hurt. I've always been for having/giving more choices.

**Comment by rahadiancs** [comment]
I used to be excited about book flip animation too to the point that I tried to write my own app because there're no comic / manga reader app that did it. I got the basic thing working, someone else already wrote the library to do that, but never actually finished it, because I'm not good enough. Fast forward today, I'm really grateful to have Tachyomi which already does 120% of what I want to achieve back then. I stop caring about page flip animation.

For some people who are new to this, or just see a page flip animation from another app, they must be really excited to have that feature.

It's an okay feature, but got old easily. But if it can be implemented, then why not.

**Comment by coltaku** [comment]
I would also love for this feature to be implemented.

**Comment by null-dev** [comment]
Just a small technical update to this. I actually did try using: https://github.com/briangriffey/book-animation but it ended up being buggy and the animation wasn't exactly as nice as I expected.

I also actually did try using: https://github.com/eschao/android-PageFlip . It was pretty crazy and rendering involved:
1. Switch to main thread.
2. Draw Android view to canvas
3. Convert canvas to bitmap
4. Switch to GL thread.
5. Draw bitmap to GLSurfaceView
6. Apply page flip effect onto GLSurfaceView
7. Repeat steps 1-6 60 times a second...

Obviously, it didn't exactly have the best performance. It was still usable but far from smooth. There are still tons of possible optimizations however so I won't rule this approach out yet.

If you want to see a small MVP (not integrated with Tachiyomi), it's here: https://s3.wasabisys.com/nd-public/github-files/tachiyomi/readie.apk . You can see that although page-flipping is smooth, zooming (yes, that's a real SubsamplingImageView in there!) and view animations (like the ripple when you tap on the button) are quite choppy.

I just saw this in the Github Explore section however, so maybe someone could look at using it?
https://github.com/wajahatkarim3/EasyFlipViewPager . It doesn't have the same awesome 3D effect, but is better than nothing.

**Comment by arkon** [comment]
Don't think this is worth doing.
