### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#14]
Would it be possible to set the apk version? Something like 0.{build number as seen in settings}
I don't know how it is done, but if you don't know/want to I'll look it up and do it.
I wanted to try setting up a FDroid repo that would automatically update to the latest build, but it can't differentiate between the builds since all of them are version 1.0

**Comment by inorichi** [comment]
I will start versioning when I rename the app (yup, I'm going to change it) and add the logo. I will also add it to FDroid and write a proper readme.

The build number right now is just the number of commits. I want to follow a proper versioning, like {major}.{minor}.{bugfix}

I'm wondering if I should drop compatibility with the previous name (even the database is called "mangafeed.db"). I have to do it if I want to get rid of the older name.

I think everything will be done next week.

**Comment by inorichi** [comment]
Closing this. I've submitted a request for adding it to F-Droid.
