### ISSUE TITLE
Add Madokami as a catalog

### ISSUE THREAD

**Issue by notlily** [inorichi/tachiyomi#140]
http://manga.madokami.com/
Requires a login, but offers fast downloads and a wide variety of titles. Would be nice to have.

**Comment by gendouhydeist** [comment]
I agree with this, this site has all manga collection with HQ scans and you don't need to go anywhere.

**Comment by Kotters** [comment]
I also suggest adding madokami as a catalogue

**Comment by ThePreviousOne** [comment]
I can't make find where to make an account
if someone could give me a link I'd be interested to try writing this catalogue

**Comment by null-dev** [comment]
You have to join the IRC (Rizon > #madokami).

Then you message the bot to get an account. The bot's username should be in the channel topic.

**Comment by ThePreviousOne** [comment]
that fine

**Comment by Kotters** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hey anonymous, I want you to have a nice day today, okay?

For better or worse, the core madokami community organizes through
IRC, on the Rizon network, in the #madokami channel. To the end of
making sure people know how to use such glorious technology,
using madokami requires an account only obtainable through a labyrinthine
gauntlet of IRC arcana. Don't worry, it builds character.

To register:

1. Connect to the Rizon IRC network using a real IRC client. I like Hexchat.
2. Register your nick through Rizon's NickServ.
3. Open the #madokami channel. Note the channel topic, it's important.
4. There's an IRC bot in the channel, identified by that important
thing earlier.
5. Direct message that IRC bot with this cryptic incantation:
   "REGISTER <user> <pass>", replacing the <user> and <pass> with, you know,
   the things you might expect.
6. When prompted by the website, enter in those magical things into
   the appropriate dialog box in your web browser.
7. Wow, that was incredibly painful!

If you forget your account for some reason, you can create a new one using a
procedure similar[1] to the above. If you do remember your current password,
you can also use the "CHANGEPASSWORD <user> <old password> <new
password>" spell.

[1]: a word which here means "exactly the same".

To upload anything, make sure you're lurking in the IRC channel so you know
what's going on. Uploading involves an SFTP client. I like FileZilla okay. The
connection information for SFTP is also in the channel topic. Good thing you're
lurking there anyway. Once you're in, note that you can't delete anything
directly. If you need to delete/overwrite files for organization, please ask on
the IRC to make sure nobody will miss those files. Then, move them into the
"Admin Cleanup" directory and they will be deleted later.

Your lazy sysadmin,queue@madokami.al
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iF4EARYIAAYFAldx6koACgkQtA8ZxyKzq2fuTgEA3u8cjlq/TBJm/MxIQDz7i0EF
HvF9km2fd6gpiljNLL0A/RPwMaEafR866Im3usBs2ucESGi97yAnsPei4QSAzaQI
=AHqJ
-----END PGP SIGNATURE-----

**Comment by Kotters** [comment]
It's kinda pseudo invite-only, since it's not broadcast/advertised how to
get in. But this readme is publicly available, if you have the link to it.

**Comment by ThePreviousOne** [comment]
I m good now, thanks

**Comment by Horoneru** [comment]
@gendouhydeist The main devs are waiting to support fully external sources. The catalogs implementation will change soon to support installing catalogs as separate apks. So I guess work on other catalogs will restart when it's done.

**Comment by beepFTW** [comment]
@gendouhydeist Not just that, the current implementation relies on the source having a reader of sorts. There is no reader for Madokami and there is no archive support.

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).

**Comment by PolkovnikCirno** [comment]
@Kotters Where can I find the readme, I should be able to find it right on the IRC right? I really have no idea what I'm doing, does it have to do with hiro's recent acquisition of madokami?
