### ISSUE TITLE
[Bug] Locking the phone (for more than ~30 mins) while reading a chapter disables "next chapter" scrolling

### ISSUE THREAD

**Issue by Cronium** [inorichi/tachiyomi#1401]
**App version:**
0.7.3
**Issue/Request:**
Locking the device (for more than ~30 mins) while reading a chapter disables "next chapter" scrolling.

**Steps to reproduce (if applicable)**

 1. Open something with future chapters.
 2. Lock device for 30 minutes or so. This may vary based on a device. (I suspect it has something to do with memory/garbage clean up)
 3. Try to scroll to next chapter.

**Other details:**
Reproduction isn't consistent.

**Comment by that-one** [comment]
Yeah, also happens to me. I noticed it often happening when I switch to memory intensive apps and back again. I'm pretty sure it has to do something with it being killed and being reopens. Going back to the manga overview and continuing reading fixes this.

**Comment by jogerj** [comment]
Try disabling battery optimization for Tachiyomi, see if it works.

**Comment by CarlosEsco** [comment]
This is a known issue.  Once tachiyomi leaves memory resuming goes back to the reader activity, problem is reader activity doesnt know about the other chapters.

**Comment by inorichi** [comment]
This shouldn't be an issue on 0.8.0.
