### ISSUE TITLE
Nhentai is giving 403 Errors.

### ISSUE THREAD

**Issue by 0klux** [inorichi/tachiyomi#1402]
**App version:**
r1405
Nhentai version: 1.2

**Issue/Request:**
When trying to browse the catalogue or seeing the Latest. Nhentai will give 403 errors. The steps apllied to solve the same problem on Kissmanga/Readcomiconline don not work with nhentai (probably because it's not a cloudfare issue).
But, searching on the catalogue still works and will let you acess the content.  It's still possible to load and download any doujin in the site. The problem seems to only affect the two sections mentioned above.

**Comment by inorichi** [comment]
This is an issue for the extensions repo.
