### ISSUE TITLE
[Issue] Kissmanga's latest category doesn't get updated until hours later

### ISSUE THREAD

**Issue by Setoshit** [inorichi/tachiyomi#1405]
**App version: 0.7.3**
**Android version: Marshmallow**

The issue is as the title says, I can get updates using the update tab but if I use the latest section there will be no new updated mangas found there until later which spans from an hour to 5 hours.

**Comment by CarlosEsco** [comment]
App latest just shows whatever the page on kissmanga shows so its not a tachiyomi issue.  Reason you hey an update for a manga is because tachiyomi is checking the individual manga page.  We can't control when kissmanga updates it's main page

**Comment by arkon** [comment]
This could be an issue with their CloudFlare caching too, but not really something that the app can address.
