### ISSUE TITLE
Tachiyomi has stopped working

### ISSUE THREAD

**Issue by askrisahagen** [inorichi/tachiyomi#1406]
**App version:**
0.7.3
**Issue/Request:**
Tachiyomi has stopped working. Can't even open it. Trying to open it once makes it continually send "Tachiyomi has stopped working" messages no matter how much I press "close app" and won't stop unless I force stop it from my phones settings. 
**Steps to reproduce (if applicable)**
Nothing. I was just reading manga and it happened.
**Other details:**

**Comment by Vesnyx** [comment]
Additional information would be very much appreciated. Could you provide the phone model and version of Android? Is your memory card full?

**Comment by askrisahagen** [comment]
Phone model is HTC Ultra. Android version 8.0.0. 32 GB left of strorage.

**Comment by pervertkirito** [comment]
Are you reading webcomic?
kinda having same trouble if image size too big
webcomic: Trinity Wonder, chapter 56

**Comment by arkon** [comment]
Too old / not enough info.
