### ISSUE TITLE
[Feature Request] Mangadex Latest Filter

### ISSUE THREAD

**Issue by Hitsun** [inorichi/tachiyomi#1407]
**App version: r1397**

**Issue/Request: request**
Is it possible to add Filter feature just like in Browse? I found the "Show None" for R18 stuff very useful in browsing manga experience. Was enjoying it a lot. 

Thanks again! Appreciate the good work!

**Comment by Hitsun** [comment]
1. Understood. Thanks for the heads up!
2. It's there on "Browse" though, but not sort by Latest, just the Non-H. Back before the latest extension update, the "Browse" and "Latest" tab have the same content for me.

**Comment by CarlosEsco** [comment]
Please close this and if you still want to discuss 2 either ping me in discord or open an issue on the extensions repo.
