### ISSUE TITLE
Bookmark a chapter from within the reader

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi#1413]
v0.7.3
Can you add a button to reader to bookmark the current chapter? Instead of exiting the reader then bookmarking.

**Comment by Samk19** [comment]
@arkon 
Kindly add this feature in upcoming builds....
Like following:

Current 
![Uploading Screenshot_2020-03-11-01-09-35-572_eu.kanade.tachiyomi.debug.jpg…]()

After adding bookmark feature
![PicsArt_03-11-01 17 30](https://user-images.githubusercontent.com/36104528/76353164-40840880-6336-11ea-8874-057cfef20abf.jpg)

**Comment by arkon** [comment]
I'm not sure about this quite yet as it might be confused with bookmarking a particular page (which isn't actually possible).

**Comment by Samk19** [comment]
@arkon 
Its chapter bookmarking not page bookmarking

**Comment by arkon** [comment]
Yes, I'm well aware. I'll look into it.

**Comment by Samk19** [comment]
Thankyou.......you r awesome dude 😍😍😍
Love to bookmark my fav chapters like i was doing in mangarock this is one feature i am eagerly awaiting for........again thanks man for your hardwork on tachiyomi.....
