### ISSUE TITLE
Free rotation will not work

### ISSUE THREAD

**Issue by Manchineel3993** [inorichi/tachiyomi#1414]
**App version:**
Version 0.7.1

**Issue/Request:**
Free rotation won't work

**Steps to reproduce (if applicable)**
Setting>reader>royation>free
No mater how I orient my phone the reader won't rotate.

**Other details:**
Phone: Samsung Galaxy S

**Comment by CarlosEsco** [comment]
Is rotation locked on your phone?  (also update to 0.7.3)

**Comment by Manchineel3993** [comment]
okay I am dumb. I did not even know you could lock rotation on your phone nor do I know when that happened. thanks
