### ISSUE TITLE
"Image could not be loaded. Try changing image decoder ..."

### ISSUE THREAD

**Issue by R-N** [inorichi/tachiyomi#1415]
I've been getting "Image could not be loaded. Try changing image decoder ..." when opening chapters I downloaded. I've been experiencing this since I updated the app on late March or early April. 

It only happens on downloaded chapters. Reading online (in app) works just fine, it loads quickly too, with the same connection and within just a few minutes after I downloaded the chapter and deleted it because it cant be loaded. The download was about as quick.

Changing the decoder before or after downloading doesn't help.

I'm mainly using MangaSee. Just tried MangaRock, same thing happened. Havent tried other sources since most sources are unavailable to me as my ISP block em, but if you want me to try a source to test please say so.

Some example of the mangas are Shokugeki no Soma and Boku no Hero Academia.

Redmi Note 4X
Android 7.0 stock
ver. 0.7.3, still persists on 0.7.4

**Comment by metroxx** [comment]
0.7.3
Xiaomi redmi note 4 
Android 7.0
Same. 
But i am using kissmanga and recently mangadex. Randomly tried mangafox too. It seems like it happens with every site. 
I can read it fine in app or in browser. 
I tried to download 5 different new manga uploads. I thought maybe that was it. But then i tried older series too. 
What i tried:
Kissmanga: one piece, fairy tails, amamo megumi wa Suki darake
Mangadex: henjyo, Pashiri na Boku to Koisuru Banchou!
Mangafox: bleach

**Comment by R-N** [comment]
Hey, same phone and android ver. Not sure if it matters though.

Oh, right. I forgot to mention the Tachiyomi ver; it's also 0.7.3.

**Comment by metroxx** [comment]
They always ask for it, so yeah, it could matter.

**Comment by mr-gmz** [comment]
Had the same problem and finally got it fixed
Basically I had to create a backup of my library, clear all the application data and the restore the backup
I assume some got corrupted somewhere and was causing the problem, working like a charm now

**Comment by metroxx** [comment]
I did that. Didn't worked out.

**Comment by robkooper** [comment]
I have the same problem, this is with chapter 3 and 4 of magic app store comic on kissmanga. If I open the comic in the browser it works fine, if I try to view the comic in the app it does not show, just shows the spinning circle as if it is decoding/downloading the image. This is with 0.74.

**Comment by metroxx** [comment]
I tried every stock source site. None of it works or just partially works like in case with Bijin Onna Joushi Takizawa-san every second or third chapter is download without issues. It works when u read it in browser or in app.

**Comment by R-N** [comment]
0.7.4, issue persists.

**Comment by metroxx** [comment]
I noticed something. 
So when u go in the download abd check the manga's folder it has a 0b file without extension with the chapter number. The file couldn't be deleted in the file explorer.  
Also overtime it will download the chapter without the app mentioned it. 
Example "Bijin onna..." i said that every 2or3 chapter worked the rest had this "image couldn't be" but today without redownload the chapters that had this problem worked without problem. I have no idea why. Because i hadn't touched the app since i last commented here.

**Comment by jotapbmpl** [comment]
When i download a chapter and open the message that image can't load still appears. Any one got a solution?

**Comment by R-N** [comment]
Ok so I noticed that it may be an issue with the source, or maybe an extension issue.

Mangasee, Manga Rock, and MangaDex works only with Rapid decoder.
Mangahere works with Image and Skia.
Manga Eden works with Image and Rapid.
None works with Readmangatoday (yes I can read online in the app)

Even if it's an source/extension issue, can we have a per-source image decoder setting feature? 
Many extensions havent been updated since ages, and idk where to report extension issue.

**Comment by metroxx** [comment]
Issues still exists. 
Even with using rapid on mangadex.

**Comment by R-N** [comment]
Nvm, I was wrong. Even with rapid not all manga works on the source I said it worked with, only some.

**Comment by metroxx** [comment]
Still have problem. It's random when or why it happens. I thought it was
because new manga. Then new chapter.
But no. It doesn't matter it just happens.


LuteFlute <notifications@github.com> ezt írta (időpont: 2018. júl. 29., V
15:23):

**Comment by metroxx** [comment]
Actually when it's about downloading stuff it's kinda works like steam. It
creates files and downloads them after it. I noticed it a few time too.
Whenever i got image couldn't be loaded it was solved by itself without
notifying the user that it's downloading right now like it does when we
start it.

Barabbas <notifications@github.com> ezt írta (időpont: 2018. aug. 26., V,
17:21):

**Comment by elfend** [comment]
hello... this problem caused when u downloaded placed on external storage... and this problem occured if ur android enable "mock sd card optimization", so it simply fix t problem with turn it off...
if ure using xiaomi/MIUI please follow this step:
1. enable developer option in setting>about phone>and tap "MIUI Version" 8 times
2. go to dev option, setting>additional setting>developer options
3. and turn of "mock sd card optimization"
4. restart your phone

hope this help...

**Comment by inorichi** [comment]
Since 0.8.0 there's just one decoder that works with pretty much everything. I'd say images are corrupted if they are not loaded now.

**Comment by xurry26** [comment]
No se si me vayan a entender pero tengo un problema con tachiyomi eh ya q al poner ex hentay no me muestra ni los mangas ni nada y ni por mas que le doy a reintentar checar el problema

**Comment by BelDOT** [comment]
Is R-N still around for help?
I need help with a bit and I saw he had answered someone's questions last year.. he seems to have disappeared
