### ISSUE TITLE
Can't remove or delete entries from Local Catalog.

### ISSUE THREAD

**Issue by cj-sv** [inorichi/tachiyomi#1417]
* version r1411
* build May 6, 2018
* Android 6.0.1

I've added local comics to its own folder at sdcard/Tachiyomi/local/comic-name/. After deleting the folders in the SD card, they still appear in the local catalog. 

I've tried clearing cache and cookies, and refreshing library and tracking metadata. 
  
Is there a way to permanently delete or remove local comics?

**Comment by arkon** [comment]
Unfavorite them.
