### ISSUE TITLE
Attempt to invoke virtual method 'com.hipp... error

### ISSUE THREAD

**Issue by MANGA-1614** [inorichi/tachiyomi#1418]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**
Tachiyomi  v0.7.4
**Issue/Request:**
I get an error:

Attempt to invoke virtual method 'com.hipp...

**Steps to reproduce (if applicable)**

 1. Download "Yugami-kun no way Tomodachi..."

 2.

 3.

**Other details:**

This only happened after installing the latest APK.

**Comment by inorichi** [comment]
Do you have enough space left on your device or partition you're downloading to?

There wasn't any change related to downloads from 0.7.3 to 0.7.4 so I don't think the new version is the reason.
