### ISSUE TITLE
[Bug] Mark as Read (Seamless Mode)

### ISSUE THREAD

**Issue by IceKreem** [inorichi/tachiyomi#142]
When Seamless transition is enabled and you go to the next chapter regardless of how much of that chapter you have read (1 page even), if you back out of the reader, it will be marked as read. (that chapter is grayed out and the MAL counter has incremented (if binded ofc).

**Comment by inorichi** [comment]
It should be fixed now.

**Comment by IceKreem** [comment]
Yup fixed awesome :)
