### ISSUE TITLE
'Page List is Empty' with Mangadex

### ISSUE THREAD

**Issue by Jadomonkey** [inorichi/tachiyomi#1421]
Tachiyomi 0.7.4

I'm getting the 'Page list is empty' error on seemingly random chapters. Roughly 4/10 chapters of various series don't load, the rest work. I've followed the steps to help fix the error: clearing data, using different networks, etc. I still have the problems.

Clearing data does change the chapters which are having issues though. Gakuen Babysitters 4, 6, 8 and 9 were erroring, but after clearing cache, the affected chapters are 1,  2, 5, 6, 7, 9. When choosing to download the affected chapters, only chapter 2 errored while the others downloaded fine.

**Comment by CarlosEsco** [comment]
Please close and open on the other repo.  Also make sure you update to latest version of mangadex
