### ISSUE TITLE
[Bug] .txt files in .cbz files break local catalogue

### ISSUE THREAD

**Issue by NicoC72** [inorichi/tachiyomi#1424]
**App version:** dev r1414

**Issue/Request:** .txt files in .cbz files (possibly other formats as well) throws a MALFORMED[1] error for local catalogue

**Steps to reproduce (if applicable)**

 1. Take a known good .cbz file
 2. Add a .txt file into it
 3. Add modified .cbz to a known good local library
 4. Try to load local catalogue

**Comment by arkon** [comment]
Duplicate of #905
