### ISSUE TITLE
[Feature Request:] Option to limit chapter per day (To keep the suspense)

### ISSUE THREAD

**Issue by voldemort13** [inorichi/tachiyomi#1426]
I often read tens of chapters a day and then the manga is over before I even realize. Would it be possible to make a option limit how many chapters you can read per day/week. 
The thing that you can read even 100 chapters a day really makes the reading less memorable because you can zoom right past the cliffhangers and you dont need to wait and wonder what happens next.

Examples
1. Limit that you can only read 2 chapters any manga in 24Hours 
2. Limit per manga so 1 chapter of OnePiece a week but others you can read as much as you like 

And I want to thank you the makers. This is by far the best manga reader I have found.

**Comment by CarlosEsco** [comment]
Just wait for Android p and you can. Set a time limit on your apps

**Comment by voldemort13** [comment]
Oh right I forgot thats a feature. But it will take year a so for android P...

**Comment by CarlosEsco** [comment]
Lol true 😂

**Comment by inorichi** [comment]
This is something only a few users would use so it won't be added.
