### ISSUE TITLE
Custom color filter picture too big in landscape mode.

### ISSUE THREAD

**Issue by aksratamo** [inorichi/tachiyomi#1427]
In landscape mode the custom color mode is very inconvenient to use. The picture will blog the view so that you have only like 2 lines of space where to scroll the options. (marked in red)
Easiest solution would be to just remove the picture in landscape mode

I read in landscape mode and often use the custom screenbrightness option at night. It makes the screen even darker than the phones brightness slider. (oneplus 3)
![screenshot_20180521-110427](https://user-images.githubusercontent.com/5618026/40297568-02765eee-5ce9-11e8-86e4-cc5b39a9b6ef.jpg)

![screenshot_20180521-110413](https://user-images.githubusercontent.com/5618026/40297353-2f184cce-5ce8-11e8-8a54-48a4232dac4c.jpg)

**Comment by jogerj** [comment]
You can still scroll it. 
A solution would be putting the image on the left and dialog options on the right for landscape.
