### ISSUE TITLE
MAL API change

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi#1430]
It seems that MAL API changed with the latest privacy update from European laws and what not, so Tachiyomi and other apps like Pocket MAL are not working properly anymore.

**Comment by dobbleg1000** [comment]
@metroid112 it is due to a security vulnerability on MALs side and is down until further notice (whenever they fix the problem)

**Comment by zztoastie** [comment]
Yep, Kitsu also doesn't work, at least for me, getting an "Unknown Error" when trying to sign in. Hopefully this gets fixed if it can.

**Comment by brassica77** [comment]
Use your email as username for Kitsu.

**Comment by Kovaelin** [comment]
Kitsu doesn't have anything to do with the MAL API. Are you talking about importing lists? Kitsu doesn't even use the API for that either. If you're trying right now, you'll probably just get a pending status.

Everyone should [export their MAL data](https://myanimelist.net/panel.php?go=export) now that the site is [partially back up](https://myanimelist.net/announcement/201806) though. You can use the files for something else, like AniList

**Comment by wopian** [comment]
> Everyone should export their MAL data now that the site is partially back up though. You can use the files for something else, like AniList

Both AniList _and_ Kitsu allow you to import your MAL library by uploading the XML file.

https://anilist.co/settings/import
https://kitsu.io/settings/imports

**Comment by Kovaelin** [comment]
That XML import from Kitsu is definitely new (they've also removed the old import method). Good to know.
