### ISSUE TITLE
Can't track webtoons with AniList

### ISSUE THREAD

**Issue by Azureum** [inorichi/tachiyomi#1434]
**App version:** 0.7.4

**Issue/Request:** Issue

**Steps to reproduce (if applicable)**

 1. Add a webtoon like Tower of God, Lookism, etc. to your library.
 2. Go to the tracking tab
 3. The AniList details will be empty.
 4. Selecting on edit button and then searching returns no results.

**Other details:**
Tracking with AniList for webtoons from webtoons.com is not possible. Here is an example screenshots of a webtoon called Lookism.
![screenshot_20180527-143619](https://user-images.githubusercontent.com/20842882/40584360-9a1cb176-61bc-11e8-9ccf-378979582cdb.jpg)
![screenshot_20180527-143628](https://user-images.githubusercontent.com/20842882/40584365-a3646436-61bc-11e8-9f1d-8fd20459f6c9.jpg)
The corresponding entry is present in the AniList database.
![screenshot_20180527-143720](https://user-images.githubusercontent.com/20842882/40584374-bf43dbdc-61bc-11e8-8752-cb7a99bb5bf6.jpg)

The same issue is present for all webtoons from webtoons.com. For e.g., Tower of God, Noblesse, unOrdinary, Yumi's Cells, etc.

**Comment by ddmgy** [comment]
That's odd, I'm not having any issue tracking any of the webtoons you mentioned.

For example:
![](https://i.imgur.com/44CDj54.png)

Are you able to track anything in AniList, with any extension?

**Comment by RED-404** [comment]
I gave it a shot on r1414 and no joy.![](https://i.imgur.com/xTDb2T2.png)

**Comment by ddmgy** [comment]
Playing around with the search query Tachiyomi uses, I think I've found the problem. Running the query without argument 'format: MANGA' returns the correct result. I'll make the change in Tachiyomi and see if it works when I'm able to access my computer.

**Comment by xKeiro** [comment]
This used to work on the development version but the last few days it can't find webtoons again.

**Comment by Akihisa17** [comment]
This issue still not solve. Not only in Webtoons but in Manhua as well (e.g Soul Land, Soul Land II, Panlong, Spirit Blade Mountain and etc.
