### ISSUE TITLE
please rectify ASAP

### ISSUE THREAD

**Issue by gondolaaa** [inorichi/tachiyomi#1439]
even though my internet speed is okay but i cant read the manga. its only says retry. i uninstall and re-install tachiyomi afew times but still appears retry
source mangago
xiaomi redmi 4x 
![screenshot_2018-05-29-15-26-20-226_eu kanade tachiyomi](https://user-images.githubusercontent.com/39724095/40644295-4cb16932-6355-11e8-8309-1ad77c865a21.png)
![screenshot_2018-05-29-15-26-41-504_eu kanade tachiyomi](https://user-images.githubusercontent.com/39724095/40644296-4d4418ae-6355-11e8-872e-c8a1d1c93a0f.png)

**Comment by einstein95** [comment]
Mangago has changed their obfuscation, see https://github.com/inorichi/tachiyomi-extensions/issues/335
