### ISSUE TITLE
[Bug] Chapters won't open in Forced Landscape

### ISSUE THREAD

**Issue by Soumatan** [inorichi/tachiyomi#144]
This problem is encountered when you have Webtoon Viewer and Forced Landscape on. It will not happen if you have Forced Portrait or other Viewer Mode with  Forced Landscape. You have to Clear Chapter Cache for it to work again. 
![screenshot_2016-02-14-14-21-41](https://cloud.githubusercontent.com/assets/16980590/13035493/0b1548a0-d328-11e5-8ab1-0a9972d719a4.png)
![screenshot_2016-02-14-14-22-06](https://cloud.githubusercontent.com/assets/16980590/13035500/230a27c8-d328-11e5-8536-b82e453ec57c.png)
![screenshot_2016-02-14-14-21-54](https://cloud.githubusercontent.com/assets/16980590/13035501/280d560a-d328-11e5-8937-6cb4da5a5a9d.png)
![screenshot_2016-02-14-14-22-09](https://cloud.githubusercontent.com/assets/16980590/13035503/2c06685a-d328-11e5-8c0c-9636092fe57e.png)
![screenshot_2016-02-14-14-22-13](https://cloud.githubusercontent.com/assets/16980590/13035504/325cf5fc-d328-11e5-9161-4f4ad81b7205.png)
![screenshot_2016-02-14-14-22-22](https://cloud.githubusercontent.com/assets/16980590/13035508/3b085502-d328-11e5-9e39-180fe28b57e9.png)
![screenshot_2016-02-14-14-22-56](https://cloud.githubusercontent.com/assets/16980590/13035509/423e3882-d328-11e5-90dc-1bcfae4a3f54.png)
![screenshot_2016-02-14-14-23-17](https://cloud.githubusercontent.com/assets/16980590/13035510/4afd701e-d328-11e5-803e-d0375dd3e976.png)

**Comment by inorichi** [comment]
Have you tried locking/unlocking the rotation of the system?

**Comment by Soumatan** [comment]
Just did it on my Moto X and it's the same. The phone recognizes the shift even if it's locked or unlocked,  This error seems to be selective to the specific chapter I enter and exit. In other word if I enter chapter 1 and exit with webtoon viewer and forced landscape on I can't access chapter 1 until I either delete the chapter cache or change the viewer or  lock mode. I still  can access chapter 2, 3, ect, until I exit those chapters and try to enter them again.

**Comment by inorichi** [comment]
Can you try opening a chapter already in landscape mode? I don't know what's happening, it seems specific to some devices

**Comment by Soumatan** [comment]
That did the trick. It seems that when the phone is on portrait it will give an error when the chapter has Webtoon and Forced Landscape. If the phone is already in landscape it will not crash.

**Comment by inorichi** [comment]
4876eaa may have fixed this issue. Can you confirm this on latest debug?

**Comment by Soumatan** [comment]
No. It still does the same if the chapter has an image in it.

**Comment by inorichi** [comment]
Can you test again?

**Comment by Soumatan** [comment]
It's fixed! Don't see any more problems with it, thanks.
