### ISSUE TITLE
Mangago not working properly

### ISSUE THREAD

**Issue by happymermaid** [inorichi/tachiyomi#1441]
**App version:** 7.4

**Issue/Request:** chapters in mangago keep displaying the "retry" button even though in other sources the manga chapters work perfectly fine. Download also isn't available only for mangago, please fix I already installed the latest update

**Other details:**

**Comment by CarlosEsco** [comment]
please close extension issues go in the extension repo.
 and this one is already reported
https://github.com/inorichi/tachiyomi-extensions/issues/335
