### ISSUE TITLE
"Attempt to invoke virtual method"

### ISSUE THREAD

**Issue by samnj** [inorichi/tachiyomi#1442]
So I see some people encountered this error before but nothing seems to work. I just found it today so I'm guessing it has to do with today's update. 
I can't download but I can read just fine. Installed and reinstalled via F-droid and there's plenty of space available. 

v0.7.4.1418 dev

It happens if I go to:

 1. Catalogue
 2. Kissmanga (or the readcomiconline extension as well)
 3. Try do download any manga/comic

**Comment by inorichi** [comment]
Install/update the extension.
