### ISSUE TITLE
Download Issue : unexpected url

### ISSUE THREAD

**Issue by ScarletteZia** [inorichi/tachiyomi#1445]
**App version:** V0.7.4

**Issue/Request:**
When I want to download a manga update from Mangago, there's push notifications saying "Unexpected Url : :b/dwfbt.pajgephctael7rm.noa/i/gelpecyickmhrrn_w_irl/n2/fe0e7u1a2ed48/789.." before it I downloaded any mangas without problems, do somebody know why and how to fix it? I really like using Tachiyomi, I wouldn't find any reason for me to not. Anw, I'm using VPN, I thought it was my VPN that had a problem, I already try to reconnect my VPN, but it didn't work. Sorry for my bad english

**Comment by CarlosEsco** [comment]
Please close issue is already open. 

https://github.com/inorichi/tachiyomi-extensions/issues/335
