### ISSUE TITLE
[BUG] Not all manga show up for tracking search in anilist

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#1446]
**App version:** 0.7.4

**Issue/Request:**
Searching for manga doesn't include ones that are not strictly "Manga". 

For example `The Gamer` is korean manga and thus doesn't show up in tracking search even though it exists in anilist database.
https://anilist.co/manga/85155/The-Gamer/

![screenshot_20180530-191843](https://user-images.githubusercontent.com/2827500/40736515-8748f29c-643e-11e8-8cfc-e049d330d9d9.png)

**Comment by CarlosEsco** [comment]
This is fixed in latest dev

**Comment by wopian** [comment]
See #1434 and #1435

**Comment by tippl** [comment]
Oh, it's the lastest commit too. Should have looked there. Thanks.
