### ISSUE TITLE
Mangago works errors

### ISSUE THREAD

**Issue by Kabula** [inorichi/tachiyomi#1447]
**App version:**
0.7.4
**Issue/Request:**
Works from Mangago always result in "RETRY" error button instead of displaying the images.
**Steps to reproduce (if applicable)**
 1. Add works with Mangago source to library
 2. View chapter

**Other details:**
Mangago's site still seems to be fully functional, even though they will not display properly through Tachiyomi.

**Comment by einstein95** [comment]
Known issue: inorichi/tachiyomi-extensions/issues/335

**Comment by CarlosEsco** [comment]
please close this is an extensions issue not a main app issue.
