### ISSUE TITLE
Anilist tracker 400 error

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1448]
**App version:**
v0.7.4 r1418

**Issue/Request:**
Getting "http error 400" while updating chapters in anilist tracker. 

**Steps to reproduce (if applicable)**

 1.go to any manga page
 2.to tracking (should have anilist logged in)
 3.tap on chapters and increase/decrease number. 
4.tap ok. 

**Other details:**

**Comment by bbtora** [comment]
Solved on my end.

**Comment by Soldiercolur** [comment]
I have this as well, how did you fix it?

**Comment by bbtora** [comment]
Re-adding the manga on the tracker solved it for me.
