### ISSUE TITLE
Add MangaTraders as a catalog

### ISSUE THREAD

**Issue by LoLyeah** [inorichi/tachiyomi#145]
http://mangatraders.org/
Had a huge manga catalogs, with high quality images, and fast downloads.
They also provided direct download for registered users.

Series list link: http://mangatraders.org/directory/

**Comment by JohnFlowerful** [comment]
The problem with MangaTraders is that some manga only have volumes, so the app would also need some way to extract, organize and track archives. not too dissimilar to Madokami.

**Comment by phatalx** [comment]
Well you don't necessarily need to add the "volume only" manga to the app, just the online chapters. I made a json file for mangawatcher back in the day but i don't know how this parser works to do the same.

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
