### ISSUE TITLE
AMOLED theme doesn't set navbar to black

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#1452]
**App version:** 0.7.4

**Issue/Request:**

The AMOLED theme doesn't seem to explicitly set the on-screen Android navigation bar to black. This isn't a problem if the ROM has the navbar as the default black, but it might be a different colour in other ROMs, such as it being white in OxygenOS.

**Other details:**

The main and dark themes do theme the navbar appropriately.

**Comment by arkon** [comment]
Oddly, the theme [does seem to set it](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/res/values-v21/themes.xml#L30). Not sure if this issue is seen in other ROMs that also have non-black navbars.

**Comment by and101** [comment]
App version 0.7.4

On the S8+ the navbar is correctly set to AMOLED dark. It may be an issue with Oxygen OS.

**Comment by arkon** [comment]
[Relevant StackOverflow post](https://stackoverflow.com/questions/48785266/oneplus-5t-on-oxygen-os-ignores-the-specified-color-of-the-navigation-bar)

I guess it's possible that OxygenOS might just be specifically checking if it's set to black and then ignoring it in this case. :(

**Comment by arkon** [comment]
Going to close this since it doesn't seem fixable in a nice way.
