### ISSUE TITLE
Extensions update, but not extension issue?

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi#1453]
I debated on where to open this, and decided I’d put it here because it seemed more appropriate. Maybe not an issue, just a heads up...

The last Mangago update, 1.2.2 wouldn’t show up in the extensions section even after the merge. Swipe down wouldn’t refresh it either. Eventually I uninstalled 1.2.1, and swiped. Then it shows latest version was 1.2.2. Maybe an issue with extension section recognizing updates? Just a heads up

**Comment by CarlosEsco** [comment]
Fixed
