### ISSUE TITLE
[Feature request] A way for a source to provide a chapter number.

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#1454]
Some manga don't follow conventional chapter numberings. Mostly seen on webtoons, where when a new season starts the numbering starts up from 1 again which can be an issue in relation to tracking using services such as anilist. My example here would be [The Gamer](https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88) which started Season 4 recently and is currently at chapter 30...

Tachiyomi takes the chapter number from the title, which is usually not an issue for regular manga, but here it breaks and would track the manga as having read only 30 chapters.

Webtoons.com however also provides a total chapter numbers for all entries, which could be saved alongside the chapter and if set override title parsing, so sources that provide a chapter number could be properly tracked.

I would like to start this probably as a discussion of other counting ways which could be implemented, because aggregation websites like kissmanga which take series from webtoons.com don't include a chapter number, and come up with a solution that could be used there too.

**Comment by CarlosEsco** [comment]
So for webtoons.com that can easily be changed in the extension.  However i don't know how you solve this issue if you were using a different extension.  You would be almost guessing as each extension names chapters with seasons differently

**Comment by CarlosEsco** [comment]
This good?

![image](https://user-images.githubusercontent.com/2092019/40889299-33dacad0-6732-11e8-9d41-f2ddff36f508.png)

**Comment by tippl** [comment]
Exactly, this could probably be solved pretty easily in the webtoons example, just like you showed (not sure how the title parsing chooses what number as a chapter number but it might work). But the problem still remains in other extensions and websites.

Which is why i intended this as a discussion on how to better solve it, because manga numbering is hard and sites like kissmanga are not helping it with each series being numbered differently.

I was thinking of the way where sites that have absolute numbering could be additionally parsed for that. For other sites, i can't really think of anything, position in the list is a possibility, but sites often rename ton of chapters, add ton of bonus chapters or straight up duplicate a ton of them...

**Comment by inorichi** [comment]
Position in the list is already saved. Also, when tachiyomi requests the chapter list, the extension can return a chapter number associated. If it's not set it defaults to our number parsing.

I don't think we can do much more on this matter.

**Comment by inorichi** [comment]
Closing because it's already possible.
