### ISSUE TITLE
Kitsu sync not finding manga

### ISSUE THREAD

**Issue by daddydeadpool** [inorichi/tachiyomi#1457]
Version r1418

Kitsu sync can't find the manga "everlasting god of sword" while it does exist on Kitsu.io

**Comment by CarlosEsco** [comment]
This is a kitsu API issue. Right now they manually sync the search and since it's a newer manga it hasn't been added to search. It gets added every few weeks.  Please close and try again next week and it should be there

**Comment by daddydeadpool** [comment]
thank you for the reply issue closed
