### ISSUE TITLE
[Feature Request] Pressing this area takes you to the manga's info or chapter window

### ISSUE THREAD

**Issue by alecjpav** [inorichi/tachiyomi#1460]
![ks7ozdn](https://user-images.githubusercontent.com/28431403/40946778-406f41ee-6814-11e8-8039-bc73b4c04a8e.png)

It already works this way when you press the back button when you're viewing a chapter from my My Library tab, but pressing the back button from the Library Updates tab (which is how I access my manga 90% of the time) just takes you back to the Library Updates menu. 

Just a QoL feature that I would greatly enjoy as I have a large amount of manga bookmarked and scrolling can be a chore. If there already is a way to do this, I haven't found it. As for whether it would take you to the manga's info or chapter window, it honestly doesn't matter much but an option to let us decide in the settings would be great.

Thank you for reading my suggestion.

**Comment by inorichi** [comment]
> but pressing the back button from the Library Updates tab (which is how I access my manga 90% of the time) just takes you back to the Library Updates menu.

Currently that's the expected behavior. When you click a chapter from recent updates it opens the reader, so going back will bring you to recent updates again.

If you want to open the manga from recent updates, tap the cover of the manga instead.
