### ISSUE TITLE
"Page List Empty"

### ISSUE THREAD

**Issue by QuietusWolfe** [inorichi/tachiyomi#1461]
0.7.4

kissmanga is returning a "page list empty" message for any manga I try to select.

Other sources, like Mangafox, load properly.

Extension is up to date. I've restarted the tablet as well, didn't work.

**Comment by einstein95** [comment]
Can confirm.
Kissmanga is returning "The site is closed." for any requests by Tachiyomi.

**Comment by raniesantos** [comment]
Just commenting to get notified

**Comment by nicodemus88** [comment]
Same problem here. Can't load any Manga on kissmanga library.

**Comment by hakapoid** [comment]
Rip Kissmanga issues, hope it gets fixed soon.

**Comment by 07shadow** [comment]
Same problem. Using mangafox until kissmanga issue is resolved.

**Comment by Domiryuu** [comment]
+1

**Comment by Treekuma** [comment]
+1

**Comment by Kaktusboi** [comment]
Ok people, if you want to get notified if there is an answer on the issue, there's a subscribe button on the right. Please use that instead of answering to get a notification, this isn't Facebook. I've been getting Emails all the time from you guys. 
Thanks

**Comment by Evilsj** [comment]
Not working in the latest Dev version either.

**Comment by yoohoox8** [comment]
This also stops it from updating

**Comment by inorichi** [comment]
Install/update the extension or use the latest dev.

**Comment by Panda7227** [comment]
I have the latest build and Kissmanga is updated, and it still isn't
working.

**Comment by Sparh4wk** [comment]
have the same problem.. Im on latest dev with latest extension.

**Comment by Kaktusboi** [comment]
Try uninstalling the kissmanga extension and installing it again, then deleting cookies and cache in the advanced settings.
That worked for me

**Comment by QuietusWolfe** [comment]
@Panda7227 Dev build is a separate branch.

But installing the dev build did fix it, but importing my library is a bit of a pain so I'll wait for the change to be pushed to the main build.

**Comment by adoredpunk** [comment]
there is an update for kissmanga on the extensions category and it ended up working for me
