### ISSUE TITLE
[Feature Request] Back button opens menu drawer option in settings

### ISSUE THREAD

**Issue by GummiWummiBear** [inorichi/tachiyomi#1463]
I have a short thumb and most of the time I can't be bothered stretching across the width of my phone to view the menu drawer without having to readjust my entire phone grip. So instead, I propose that the system back button can also be used to open the menu drawer like with Discord -- toggleable in settings. Most of the time I just close apps with the recents button, so I don't mind not being able to close the app with a simple back button press.

**Comment by arkon** [comment]
Eventual goal is to remove the drawer, so going to close this.
