### ISSUE TITLE
failing on kiss manga

### ISSUE THREAD

**Issue by CuZnDragon** [inorichi/tachiyomi#1466]
**App version:**
0.7.4
**Issue/Request:**
Kissmanga.com no longer able to browse or get updates
**Steps to reproduce (if applicable)**

 1. Go to catalog
 2. Select browse
 3. Gets error of No Results Found

**Other details:**
If I go to sire with browser there is no issue.

**Comment by daddydeadpool** [comment]
known issue with multiple posts.
[https://github.com/inorichi/tachiyomi/issues/1461#issuecomment-394907234](url)

**Comment by zhongfu** [comment]
duplicate of #1461
