### ISSUE TITLE
"One piece" readmanga.me 404 error

### ISSUE THREAD

**Issue by KirRoil** [inorichi/tachiyomi#1467]
**App version:** r1419

**Issue/Request:** one piece from http://readmanga.me/one_piece error 404
![photo_2018-06-06_17-01-05](https://user-images.githubusercontent.com/30603434/41042796-37a7e762-69ab-11e8-9edf-ab44ccfcd5a4.jpg)

**Comment by Taumer** [comment]
Can't confirm. 
Try swipe down in chapter list to refresh it

**Comment by MartinGauna** [comment]
Same happens to me with Witchcraft Works and on the catalog.

**Comment by KirRoil** [comment]
@Taumer не работает, всё то же 404

**Comment by Taumer** [comment]
@KirRoil могу предложить удалить эту мангу из библиотеки, очистить кэш глав и базу данных в настройках приложения, и добавить мангу снова.
En: i suggest removing this manga from library, clearing chapters cache and database in app settings and add manga to lib again

**Comment by Taumer** [comment]
Manga was moved from `/one__piece` to `/one_piece` on site.
I think issue can be closed.
