### ISSUE TITLE
Can't read any chapter on Tachiyomi

### ISSUE THREAD

**Issue by arwa002** [inorichi/tachiyomi#1468]
Version 0.7.4
I was using a previous version and I noticed that I can't read any of my chapters on Tachiyomi. Any chapter, it always says "Retry". I press it several times and it still doesn't load. This has been an issue for almost 2 weeks now and my net's completely fine. Recently, even getting updates by refreshing the updates page doesn't seem to work. So I downloaded the latest version and the problem still persists. Is this a problem with the backup, my device (Lenovo Tab 3 8) or a problem with the app? I have to resort to using Mangago and I dislike that because my selections aren't as organized as one would see in apps like this. Also I don't need to make extra accounts, so that's one pain chcked out of my list. I really want to read my updates and it sucks that I can't because of this issue.
(The update issue was only in the previous version I used, the new one doesn't have that. But the reading problem is still not resolved.)

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by inorichi** [comment]
I guess you were using Kissmanga after the changes on their site. Just install the extension which is updated.

Any way this is most likely a bug in the extension so I'm closing.
