### ISSUE TITLE
Crash on load chapters

### ISSUE THREAD

**Issue by Taumer** [inorichi/tachiyomi#147]
Crash on load chapters for some manga 
For example:
Fairy Tail from Kissmanga http://kissmanga.com/Manga/Fairy-Tail
Kuroko no Basket from Kissmanga http://kissmanga.com/Manga/Kuroko-no-Basket
Nexus 4 Android 6.0.1 (FakeNexus ROM without root and xposed)
App version r469
logcat http://pastebin.com/8nPR6NZf

**Comment by inorichi** [comment]
Thanks. There's an infinite recursion on `ChapterRecognition`, line 116.

@icewind1991 Can you fix this? I prefer not to touch that class since you know how that works better than me.
