### ISSUE TITLE
Kissmanga not working

### ISSUE THREAD

**Issue by Lewskl** [inorichi/tachiyomi#1470]
**App version:** 0.7.4

**Issue:**
When attempting to read manga sourced from Kissmanga, I get an error saying "Page list is empty". Attempting to view the Kissmanga catalogue only returns a "No results found". I'm able to access kissmanga.com normally. A friend of mine has the same issue.
I've tried clearing my chapter cache, database and cookies, then deleting all data from the app and finally reinstalling, all to no avail.

**Comment by CarlosEsco** [comment]
Issue is fixed in latest dev, or download the kissmanga extension in app.

**Comment by Lewskl** [comment]
Seems to work, thanks
