### ISSUE TITLE
Kissmanga not connecting

### ISSUE THREAD

**Issue by reinoj** [inorichi/tachiyomi#1471]
0.7.4

In catalogues, Kissmanga doesn't connect. Also can't read any chapters from my library that use Kissmanga. Probably an issue on their end, since the other options like Mangafox, etc still work.

This shows when clicking browse on the catalogues screen.
![browse_kissmanga](https://user-images.githubusercontent.com/38120663/41072392-114fffec-69c3-11e8-8de9-87806d045cf9.jpg)

This pops up when clicking on a chapter from Kissmanga.
![fail_opening_file_kissmanga](https://user-images.githubusercontent.com/38120663/41072395-12f4071c-69c3-11e8-9e6f-46a82db1f98b.jpg)

**Comment by LakotaGray** [comment]
Download latest dev versions r1419. Update the kiss extension to 1.2.4. If you need more help go to the discord channel and can assist from there. But this issue has been fixed.
