### ISSUE TITLE
[Feature Request] Persistent Notifications on Oreo

### ISSUE THREAD

**Issue by onurduran** [inorichi/tachiyomi#1473]
**App version:**
0.8.4
**Issue/Request:**
It seems Oreo(9) and new Q(10) has a very diffrent notification system.After clearing notifications on notification bar it also removes app badges on some apps while mail , facebook etc works stays just fine.Is it possible to make notification badges persistent like those apps or make it compatible with a 3rd party app tesla unread?

**Comment by arkon** [comment]
As far as I can tell, Tachiyomi acts "normally". The notifications are intentionally non-persistent, since they're not supposed to be permanently there...
