### ISSUE TITLE
The tracking for some manga doesn't show up 

### ISSUE THREAD

**Issue by Xeiniac** [inorichi/tachiyomi#1474]
**App version:** 0.7.4

**Issue/Request:** When you search for the manga in the tracking tab it doesn't show up, I use Kitsu. 
**Examples:**
Everlasting God of Sword; https://kitsu.io/manga/everlasting-god-of-the-sword
World of Immortals; https://kitsu.io/manga/world-of-immortals

**Comment by CarlosEsco** [comment]
Nothing we can do about this. It's an API issue when kitsu syncs their API with their database you will be able to find it. I guess they do it every 2-3 weeks

**Comment by wopian** [comment]
Manga _just_ added to Kitsu won't show up from API-based searches for a couple of weeks, as its using a legacy system (ElasticSearch) that now has to be manually synced with the database.

**Comment by Xeiniac** [comment]
Oh alright, thanks for the replies

**Comment by bbtora** [comment]
Kitsu search has been really slow for me. While some entries gets results, some just don't and the progress circle keeps revolving even though I've been searching a fairly old manga (Vinland Saga).

**Comment by CarlosEsco** [comment]
Why are you commenting on a closed issue. Open a new one

**Comment by bbtora** [comment]
My issue was similar to this one. But anyways I'll create a new issue.
