### ISSUE TITLE
Animated images does not display

### ISSUE THREAD

**Issue by Hulkmaster** [inorichi/tachiyomi#1476]
**App version:**
0.7.4

**Issue/Request:**
Animated images does not display
Either display them, or give option to open it in another program (browser for example)

**Steps to reproduce (if applicable)**

 1. Download animated image (ex. https://2.bp.blogspot.com/-OKjz3zve9kU/Wxvg2tHXtjI/AAAAAAAH5PA/fYLpRFHq8mMk57AQNzE1b7DIkv9lFp-8wCHMYCw/s0/000.gif)

Fushigi Neko no Kyuu-chan
83 chapter (there are plenty actually)

 2. If it was predownloaded = infinite load
 3. If it was not = error with "try in browser"

**Comment by jshap70** [comment]
I believe 3 is the expected behavior, 2 sounds like a bug
