### ISSUE TITLE
[Extension Request] Tsumino

### ISSUE THREAD

**Issue by canthisbemythrowawayaccountplz** [inorichi/tachiyomi#1477]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
0.7.4

Is it easy to add Tsumino to the extension list? There's e-hentai and nhentai but my main isn't there :(

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

Since this is a throwaway account I don't check often I probably won't respond if required.

**Comment by CarlosEsco** [comment]
Wrong GitHub repo please close

**Comment by wopian** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/201
