### ISSUE TITLE
[Feature Request] Completed only filter in Catalogues->Latest 

### ISSUE THREAD

**Issue by Yube** [inorichi/tachiyomi#1478]
Would be nice having a way to only show completed (and maybe ongoing too) series in the "Latest" subsection of Catalogues; similar to what both the Library and normal Catalog have.
Thank you!

**Comment by CarlosEsco** [comment]
Not something that's possible unless the specific source supports it.  Latest is just a view of the sources latest chapter page the provide and usually those don't have filtering or searching

**Comment by inorichi** [comment]
Yep, this is catalog specific. You can request it for a specific extension if their advanced search supports it, but please create it on the extensions repository.
