### ISSUE TITLE
chapters showing on picture apps.

### ISSUE THREAD

**Issue by cein12** [inorichi/tachiyomi#148]
Pictures of manga chapters showing on "timeline" and other picture apps on my device. I have not experienced that with another manga app before, I hope its a early bug, but I still love this manga app overall.

**Comment by wopian** [comment]
What version are you on?

They're not displaying in gallery for me on 0.13 or r472

**Comment by cein12** [comment]
I am using version 0.1.3

**Comment by cein12** [comment]
Can I make a new folder and .nomedia and place it here tachiyomi/downloads/ for solving the issue?

**Comment by Rumple007** [comment]
That worked for me, putting a .nomedia file in the downloads folder

**Comment by inorichi** [comment]
It will be created automatically in the next release dcfda61
