### ISSUE TITLE
[Suggestion] Displaying not installed "stock" extensions along the installed ones

### ISSUE THREAD

**Issue by Jendrej** [inorichi/tachiyomi#1482]
People are having trouble updating the extensions already included in the app, thinking they have the latest version when they don’t. I think displaying them on top of the list would fix it. Especially if they were also labeled "update" if needed, and for that the main app would need to know the version of the extension it already has included to be able to tell if there are updates to install.
At least this is how I would see it.

**Comment by CarlosEsco** [comment]
Not gonna be an issue cause stock one will be removed at some point

**Comment by inorichi** [comment]
Yeah I'm going to remove them one of these days.
