### ISSUE TITLE
Manga has not updated in two weeks

### ISSUE THREAD

**Issue by CurryMasterE** [inorichi/tachiyomi#1483]
**App version:**
0.7.4
*Issue/Request:**
Manga is no longer updating from sources, the sources/hosts have the newer chapters available and there are links available to them through Reddit but the manga on the app does not update or when it does update updates older chapters. 
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
aside from this, you have an amazing app and looking forward to your future iterations

**Comment by CarlosEsco** [comment]
Which source?

**Comment by CarlosEsco** [comment]
Also I recommend you join the Discord Channel. Support can help figure out your issue

**Comment by CurryMasterE** [comment]
Manga Here

**Comment by 2alin** [comment]
Same problem here, Kiss Manga is the one that I use and it's not updating since two weeks ago in the app.

**Comment by inorichi** [comment]
@CurryMasterE Use another source if it gives you problems. Also try to manually refresh the chapter list of one of those manga, it'll show any error on screen.
@2alin Install the Kissmanga extension.
