### ISSUE TITLE
Bookmark button doesn't respond when in landscape mode

### ISSUE THREAD

**Issue by c0ffee12** [inorichi/tachiyomi#1485]
**App version:**
0.7.4
**Issue/Request:**
Bookmark button doesn't respond when in landscape mode
**Steps to reproduce (if applicable)**
Go to details page of manga in landscape mode, try to press bookmark button, doesn't respond

**Other details:**

**Comment by yambadr** [comment]
It works perfectly.
What's your Android version? What device? Which Source and manga?

**Comment by dominiclopez391** [comment]
V4.4.2, on Samsung Galaxy Avant, pretty old model. Happens to all manga,
but I can favorite in portrait mode, so it's debatable whether to look into.

**Comment by inorichi** [comment]
It's working for me too. I'll check later on an emulator with KitKat.

**Comment by ForgetfulJones** [comment]
Landscape-mode bookmark hasn't worked for me for a long time, actually. Same 'fix' that domenic describes works for me.  Motorola wingray xoom, 4.4.4

**Comment by arkon** [comment]
We're dropping 4.x support (#2436), so this won't be relevant anymore.
