### ISSUE TITLE
Library updates often halt at the last manga in library

### ISSUE THREAD

**Issue by yoohoox8** [inorichi/tachiyomi#1487]
**App version:**
0.7.4

**Issue/Request:**
During library updates, it will often halt at the very last manga in the library and not finish the update on my amazon fire hd 10 7th generation. I will usually turn on then off the tablet to stop the update and re do it. This happens mostly with doing a manual library update, but it also doesn't update the library at the frequency I set it to. 

**Other details:**

There are no restrictions to it it updating 
Fire OS 5 is based off of android 5.1.1 Lollipop.
My library is also  relatively at around 150+
All the extensions are updated

**Comment by arkon** [comment]
Similar to #1420
