### ISSUE TITLE
[Feature Request] 19:9 Fullscreen support?

### ISSUE THREAD

**Issue by sharunks007** [inorichi/tachiyomi#1488]
**App version:**
0.7.4
**Request:**
Support for full screen in 19:9 screen ratio (e.g. on OnePlus 6)

**Steps to reproduce (if applicable)**
 1. Open a manga
 2. Go to reading a chapter
 3. Enable full screen

The status bar is still visible in this case even though Full screen is enabled.

**Comment by inorichi** [comment]
I've asked a friend with a OnePlus 6 to test this issue and he says it's working as expected, no status bar on the fullscreen setting. Are you sure this is an issue on Tachiyomi and not something else interfering?

**Comment by inorichi** [comment]
Closing because working as expected.

**Comment by sharunks007** [comment]
Sorry for the delayed response. I was talking about the image / page going around the notch. When the notch is disabled apps draw all the way up. Here there's a black bar at the top. Though, when taking a screenshot it shows that the image is drawn in 19:9
