### ISSUE TITLE
Settings and extensions are forgotten when app is closed.

### ISSUE THREAD

**Issue by Einlander** [inorichi/tachiyomi#1489]
0.7.4

**Issue/Request:**
Tachiyomi will forget your library and remove all of your extensions when you close the app and restart it.

It will also load your backup and say that it was full of errors.

**Comment by inorichi** [comment]
Device? Sounds like a bug somewhere else.

**Comment by AmineI** [comment]
Not enough info, probably a user issue, and inactive for almost a year, it probably should be closed - at least until the user comes back with more info, if he does.
