### ISSUE TITLE
empty library bug

### ISSUE THREAD

**Issue by rachmadaniHaryono** [inorichi/tachiyomi#1490]
**App version:** 0.7.4

**Issue/Request:** Library don't show any manga and category (screenshot included)

**Steps to reproduce (if applicable)**: None

**Other details:**
device:

- device: nexus 7 2013
- os: android 6.0.1

others:

- automatic backup is also not working
- library update is empty
- recently read is working
- manga is still detected when browsing catalog
- opening manga through catalog, recently read section is working
- creating backup will exit the app. it will exit after backup progress loading

temporary fix is to clear app data and restore backup. this is not optimal solution if the backup didn't include the latest change before this bug occur

![](https://cdn.discordapp.com/attachments/349436576037732355/457073525677883392/Screenshot_20180615-144515.png)

**Comment by inorichi** [comment]
I've never seen this issue so I don't know what's causing it.

Any idea on how to reproduce? Is the edit categories screen showing the categories too?

**Comment by rachmadaniHaryono** [comment]
My Best guess maybe something related to harddisk corruption.

There are other issue on other app, where I have to reinstall the android

Other possibilities is blokada. But it is still not working after I uninstall blokada.

Edit categories is still working

I have only several hour till my limited bandwidth valid.if the issue is still exist by then, I will close the issue , and reset tachiyomi.

**Comment by inorichi** [comment]
I guess you have already tried force closing tachiyomi? Can you change the downloads directory on settings? I doubt it has anything to do with the issue but who knows.

**Comment by rachmadaniHaryono** [comment]
- force closing it don't change anything
- changing the download folder don't change anything
- change download folder and download a chapter don't change anything

**Comment by rachmadaniHaryono** [comment]
I will close this as I can't find a way to debug it

I also delete all the download manga and try to restore backup directly,but this bug still exist

I will open it next time I have more info

**Comment by Edst0rm** [comment]
I got a similar situation 2 weeks ago. To fix the problem, I reinstalled the app, but that doesn't say how it broke and I would love to tell you if I knew.

**Comment by DemonicGod** [comment]
I have this exact issue, did anyone find a solution?
