### ISSUE TITLE
chapters showing as unknown

### ISSUE THREAD

**Issue by jsantuele96** [inorichi/tachiyomi#1491]
I have been using tachiyomi for a year now. Recently there has been an issue with updates so I have to save a back-up and reinstall the app. After reinstalling the app, multiple chapters that I have saved for back up are no longer showing up on my library, so I have to find the mangas tha I was following and add it on my library. All other mangas are good but some does not load at all and boku no hero academia does not show any chapter at all even though there are multiple sources.

**Comment by jsantuele96** [comment]
i already have tried to reinstall the extensions, nothing happens

**Comment by arkon** [comment]
Things might've changed in the source between backup/restores.
