### ISSUE TITLE
Tracking not auto updating

### ISSUE THREAD

**Issue by KrisKamweru** [inorichi/tachiyomi#1492]
**App version: 0.7.4**

**Issue/Request: The tracking linked with Kitsu doesn't auto update when a chapter or several chapters are read**

**Steps to reproduce (if applicable)**

 1. Link kitsu tracking to tachiyomi 
 2. Properly set up tracking for the manga, updated with already read chapters
 3. Read and complete a chapter/ several chapters

**Other details:**
By not auto updating, I don't mean it doesn't sync to kitsu. Indeed, if I update the chapters read in the tracking section, that syncs to kitsu just fine. My only issue is that the chapter read section doesn't update with the completion of a chapter 
I'm not entirely sure if this is a feature yet to be implemented, or one implemented that isn't working for me. Either way, I'll help how I can to fix it

**Comment by wopian** [comment]
Sounds like you have `Sync chapters after reading` disabled in your settings. Enable it by going to `Settings > Tracking`

**Comment by KrisKamweru** [comment]
**Sounds like you have Sync chapters after reading disabled in your settings. Enable it by going to Settings > Tracking**

I actually had that on, which is why I was so baffled 
But, for some reason, as happens in a lot of tech issues, it just started working again. I didn't even change anything 😂 😂 😂. I really don't like it when a program just starts working without my knowing why, but if it ain't broke don't fix it 🤷🏿

Thanks though
