### ISSUE TITLE
Download Feature Request: Range Selection

### ISSUE THREAD

**Issue by ashishkharche** [inorichi/tachiyomi#1493]
**App version:**
0.7.4
**Issue/Request:**

[REQUEST]  Can we have the range selection to download manga chapters. 
Eg. Select starting chapter then select ending chapter?
Then all the chapters between those will be downloaded

**Other details:**

I used this feature in other manga app and is very convenient to have. 

![screenshot_2018-06-17-15-27-19-666](https://user-images.githubusercontent.com/33261496/41506845-2d781708-7243-11e8-8411-a2bcec7da61d.jpeg)

**Comment by KrisKamweru** [comment]
I concur

**Comment by arkon** [comment]
Long press range selection was added in https://github.com/inorichi/tachiyomi/commit/2d3bfa9a89e08bb7318a39ba73620ae2820d6181
