### ISSUE TITLE
Kissmanga not working

### ISSUE THREAD

**Issue by aquagrapher** [inorichi/tachiyomi#1496]
Kissmanga is not available on the app. So whatever manga I had downloaded partly can't be downloaded anymore. Also manga that is not downloaded is not accessible.
Others sites are working
**App version:** 7.4 (latest version) but issue existed in prior version also. Didn't change on upgrading

**Issue/Request:** Please try to fix it

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by aquagrapher** [comment]
I have screenshots. Don't know how to post it

**Comment by Asbesbopispa** [comment]
Same here, these are two screenshot
https://imgur.com/a/W8Lj6uh

When I try to restore a backup, here's the error contained in the log with a random manga:
[2018-06-19 12:13:43.968] Akita Imokko! Ebina-chan - Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference

**Comment by CarlosEsco** [comment]
503/403/ “Page list Empty” issues with Kissmanga/ReadComicsOnline Fix:
-Update to latest dev version OR install latest Kissmanga extension
- In Tachiyomi go to settings advanced  and clear cookies
- Opened chrome go to website that is causing the issue
- click a random comic/manga and click a chapter, let it load
- Open Tachiyomi
- go to catalouges and click the browse button the source that is having the issue
-it should work, if it does not click the retry button after a couple retry attempts it should work
-If still isn’t working, close Tachi, swipe away from recents, and restart app

now you can go back to your library and read your chapters/download

**Comment by just22avi** [comment]
KissManga is not working at all. My all Manga were from KissManga i can't read any of them. Please Fix it.

**Comment by CarlosEsco** [comment]
Do what i posted above.

**Comment by temary44** [comment]
Having this issue too, also with app version 7.4. No KissManga extension because when I get the "Do you want to install this application? It does not require any special access" dialogue box, clicking "install" does nothing (am able to use the cancel button just fine though).

Have done @CarlosEsco 's steps multiple times to no avail. I can use the KissManga site just fine on my tablet's browser but Tachiyomi seemingly cannot reach it for whatever reason. 

Android version 6.0.1 in case it's relevant. No VPNs have been used.

**Comment by CarlosEsco** [comment]
@temary44 turn off adblock so the extension installs

**Comment by temary44** [comment]
@CarlosEsco I never installed adblock on my tablet. 
https://imgur.com/a/bTRI3Fa
I have no Tahiyomi app extensions installed so far and my settings allow installation of apps from "unknown sources" yet I cannot press the install button on the image above.

**Comment by Langstrad** [comment]
@temary44 Do you happen to have the twilight app (or something similar) installed maybe. For me somehow it interferes with only the install option and the workaround is to pause it for a bit install the extension and then start it again. Hope this helps.

**Comment by dubl3a** [comment]
I've tried the steps provided by @CarlosEsco but they do not work.  I've gone so far as to reboot my phone.  When I try to Browse or view Latest from Kissmanga, Tachiyomi reports "No Results Found" every time.
