### ISSUE TITLE
Mangago source not working

### ISSUE THREAD

**Issue by rikuo-g** [inorichi/tachiyomi#1499]
App version: Tachiyomi v.0.7.4

Issue/Request: I know this issue has been addressed and resolved before but it reoccurred just now, or maybe a few hours ago. Whenever I try to download a manga, some error code shows up instead of the progress (e.g. htijeet/:7/mwnba---). Other extensions have no such issues.

Steps to reproduce (if applicable)

 1.
 2.
 3.

Other details:

**Comment by einstein95** [comment]
Yes, obfuscation has been changed yet again

**Comment by fatimagrace015** [comment]
Will it be fix again just like last time?😭

**Comment by CarlosEsco** [comment]
Wrong repo close and open in the extensions repo

**Comment by Syaoran96** [comment]
So this is depend on them? i mean it's not our fault right? All we can do is wait right? I just read some old thread about this issue and i dont understand anything :v i thought i cant read manga on mangago site in this app anymore

**Comment by katsudamn21** [comment]
Yes can u guys pls fix them asap

**Comment by LakotaGray** [comment]
Please close issue. There is an open Mangago issue in Tachiyomi-extensions repo #368

**Comment by NoorHooda** [comment]
I'm really sorry to bother you guys , you work so hard and all , I'm just confused , is the problem about the mangago source gonna be fixed ? I know it's because of the url of mangago has changed , but are you guys gonna fix it or is there a way to fix ot ourselves ? Thank you in advance

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/368
