### ISSUE TITLE
App crashes immediately after opening

### ISSUE THREAD

**Issue by janmarasigan** [inorichi/tachiyomi#1502]
**App version:**
0.7.4

**Issue/Request:**
When I open the app from the launcher icon, or by using the app shortcuts, it crashes immediately.
Only error I'm getting from it is "Tachiyomi has stopped / Tachiyomi keeps stopping".

Last thing I did with the app was download all chapters of a certain manga and left it overnight. The following day, I am now unable to use it.

Clearing the cache did not work.

**Steps to reproduce (if applicable)**

**Other details:**
Device: Moto Z Play (Android 8.0.0), not rooted

**Comment by janmarasigan** [comment]
Clearing all app data fixed it, losing a few manga titles I forgot to backup in the process, and I still do not know what caused the issue.

**Comment by alexjpascoe** [comment]
To anyone else having this problem just reinstall Tachiyomi on top of the unresponsive one and you will keep all your data as well as have a qorking app
