### ISSUE TITLE
Excuse me why did mangago.me stopped working?? It's was working just fine few days ago but it's Suddenly stopped opening the manga !!Really this app is my favorite app for all the time so please fix that problem 

### ISSUE THREAD

**Issue by darkness66** [inorichi/tachiyomi#1503]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**

0.7.4

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by LakotaGray** [comment]
This is the wrong repo for extension/source issues. But in Tachiyomi-extensions #368 is an open issue regarding the problem wirh Mangago. Please close issue and use the other to comment.
