### ISSUE TITLE
 [Feature request] Retry tracking sync if failed.

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#1504]
Basically what the title says. If i read the chapter and i'm not online it won't sync with the tracking service next time i'm online. What i would like is for tachiyomi to queue the updates and retry next time i'm online.

Of course it will sync if i read the next chapter, but that is at the very least a week wait and at worst 3 months for quarterly manga like D.gray-man, so it think this would go a long way towards making sure the manga in the tracking service are always in sync.

**Comment by wopian** [comment]
Duplicate of #1497

**Comment by tippl** [comment]
Cool, was searching if there was already an issue like that, but didn't find it.
