### ISSUE TITLE
mangago

### ISSUE THREAD

**Issue by tachinneko** [inorichi/tachiyomi#1506]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
Don't even read the form did you?  This is the wrong repo and the issue is already opened. https://github.com/inorichi/tachiyomi-extensions/issues/368
