### ISSUE TITLE
Error in Mangago

### ISSUE THREAD

**Issue by yasnil** [inorichi/tachiyomi#1507]
Mangago is not working.. Can't open a single manga. When I try to open a chapter it alway says ERROR. The other app is working except for Mangago.

App Version: 7.4(latest version) 

Issue/Request: Pls fix it. I only use Mangago as a reader for manga

Steps to reproduce (if applicable)

 1.
 2.
 3.

Other details:

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/368
