### ISSUE TITLE
[Enhancement] Add custom time display option

### ISSUE THREAD

**Issue by ZaneHannanAU** [inorichi/tachiyomi#1512]
**App version:** r1421
**Request:** Allow custom time display option

Essentially title; allow custom display of time.

Currently time is displayed (for me) as 25/06/2018; however I myself use 2018-06-25 or often Mon, 25 Jun 2018.

It could be a format option following the unix `date` defaulting to `"%x %H:%M"`; and some defaults like ISO8601 (`"%FT%X%z"`) and UTC-alike (`"%a, %d %b %Y %H:%M:%S"`).

... I would pull but I have no idea where I'd find the formatter.

**Comment by asdkant** [comment]
I'd also like this, the US style of date format (`mm/dd/yyyy`) is really bad and I had to switch to UK localization (`dd/mm/yyyy`), but I'd prefer the option of ISO date format if possible (`yyyy-mm-dd`)

**Comment by arkon** [comment]
#2175
