### ISSUE TITLE
[Feature Request] Combine similar titles option

### ISSUE THREAD

**Issue by rediffp** [inorichi/tachiyomi#1513]
My idea about this feature can be explained using Tokyo Ghoul manga as a (safe for work) reference.
I've made categories based on genre of manga. I might be wrong but many people could be doing that.
Tokyo Ghoul has two mangas and the third one is about to come.
There are users (not all of them) who have ocd (I do have one in this regard) and might not want to create new category for just one manga or see multiple instances of Tokyo Ghoul staring them back.
A probable solution is to introduce folders (in an abstract sense) in each category to group such mangas together. Maybe main stories and spin-offs can be grouped in one folder and named accordingly. Dragging one manga atop the other can create a new folder (just an idea).
I have seen this type of feature in launchers where we can drag and drop applications to create folders.

Not Safe for Work reference
This is a real problem when we add hentai mangas from ehentai, nhentai, etc. They have one chapter or volume posing as a complete manga. This happens for many different mangas. This a serious setback for me.

**Comment by arkon** [comment]
Kind of similar to #1803
