### ISSUE TITLE
Image sharing to Discord gives non-image extension

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi#1516]
**App version:**
0.7.4

**Issue/Request:**
When sharing an image from Tachiyomi to Discord, the filename given has a non-image extension (one that isn't jpg, png, gif, etc.). This means that Discord shows it as a standard file upload rather than embedding the image.

**Steps to reproduce (if applicable)**

 1. Open any manga
 2. Press and hold on the image to open the sharing popup
 3. Assuming you have Discord installed, select Discord
 4. Finish sharing, then view your share

**Comment by phanirithvij** [comment]
**App version:**
0.7.4

For me it says
**Unable to pre-process file**

![screenshot_20180628-133113](https://user-images.githubusercontent.com/29627898/42021269-cf0d2fb2-7ad7-11e8-8fbc-1ce68d2df70c.png)
