### ISSUE TITLE
Kissmanga is not working

### ISSUE THREAD

**Issue by Fokkusuteru** [inorichi/tachiyomi#1517]
Since a few weeks now my kissmanga has not been working. This often happens before but there is usually an update a few days later that takes care of it. I have been waiting for an update but it's just not there. 

App version: 0.7.4

Issue/Request: please fix the kissmanga issue as soon as possible

Steps to reproduce : update system? 

Other details: when clicked on browse it shows 'page not available'.

**Comment by CarlosEsco** [comment]
#1496 follow steps i posted there
