### ISSUE TITLE
App crashes immediately after opening

### ISSUE THREAD

**Issue by nivek1989** [inorichi/tachiyomi#1518]
**App version:** 0.7.2

**Issue/Request:** Any attempt at opening the app immediately results in a crash with the message "Tachiyomi has stopped."  Sometimes this message is also shortly followed up with "Tachiyomi keeps stopping."

**Steps to reproduce (if applicable)**

 1.Open Tachiyomi

**Other details:**
I'm running Android 8.0.0 on the Galaxy Note8.
This stopped working with my first attempt to load it this morning.  
I have not attempted any new downloads last night and I'm unsure what I was reading last.  
I cleared cache, but that did not change my results.
I ran adb logchat, but the results appear empty.

**Comment by bbtora** [comment]
Update the app to 0.7.4 and see if the problem persists.

**Comment by nivek1989** [comment]
That did appear to work - I wonder why 0.7.2 suddenly broke for me though.  Oh well, closing.
