### ISSUE TITLE
Webtoon scroll stuttering

### ISSUE THREAD

**Issue by lucmos** [inorichi/tachiyomi#1521]
App version: 0.7.4
Android: 8.1 (xiaomi redmi note 5)

Issue/Request: webtoon stutters while scrolling pages

Without changing page, after a while, the scroll becomes less smooth. I made a video for better understanding: https://goo.gl/sgRhLW (at 1080p it's more evident)

I recently changed phone, I didn't have this problem with the previous one (android 5.1), same version of tachiyomi.

Update: It seems to do it only on very long pages. And the begining of each page goes smoothly

**Comment by RobotoDroid** [comment]
Confirmed issue on my end too, usually happens with webtoons that are "one page long". Basically a massive strip all as one picture.

**Comment by inorichi** [comment]
It happens when there's a lot of RAM allocated. I don't know if the new reader will fix it.

**Comment by RobotoDroid** [comment]
An issue with RAM allocation perhaps?

**Comment by LucaMoschella** [comment]
The new version appears to have lessen the problem, even if it is still annoying.

Now the stuttering occurs only while changing pages.

I am testing with the manga Trinity Wonder, from ReadManga Today (EN), chapter 55. 

With the webtoon viewer, just scroll the pages (at least p.4)

**Comment by arkon** [comment]
#1908
