### ISSUE TITLE
[Feature suggestion/request] Message system

### ISSUE THREAD

**Issue by ratof** [inorichi/tachiyomi#1522]
**App version:** 0.7.4

**Request:** I don't know it this is viable/doable/wanted, but it's a function that I've seen in some websites/apps and I think it is kinda cool. It's basically a system where the reader can leave messages in the pages of the manga, thus interacting with others and it can be very funny sometimes (you can activate/deactivate). As an example: http://www.mangahere.cc/tsukkomi-help.htm

**Comment by inorichi** [comment]
Sorry but tachiyomi isn't a social app.
