### ISSUE TITLE
[Feature suggestion/request] Add "TumangaOnline site"

### ISSUE THREAD

**Issue by ElBallex** [inorichi/tachiyomi#1523]
I'm not sure if is posible, so.. my apologizes if is not.

Well. in **"Tu Manga Online"** they have content that you can't find in other language,  a lot of manwha and manhua that even in english you can't find.
Is the most important site in spanish.

Thanks for your time!!
I'm sorry if i write something wrong <_<

**Comment by sleey** [comment]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

That's 2 first line that u deleted before u create this issues.
