### ISSUE TITLE
Request to remove the image displayed when Custom Brightness is opened

### ISSUE THREAD

**Issue by ashishkharche** [inorichi/tachiyomi#1528]
**App version:**
0.7.4
**Issue/Request:**

Please remove the image which is shown when Brightness Icon is tapped. Especially in landscape mode, that image blocks all the important features. That image itself has no use. Kindly remove it.

**Steps to reproduce (if applicable)**

 1. Remove that image view.

**Other details:**

**Comment by dobbleg1000** [comment]
Removing it is not the way to go. The purpose of the image is to allow you to see how your settings will actually look on the page. I agree that it is indeed broken in landscape but that is just something that needs to be adjusted.

**Comment by inorichi** [comment]
Fixed on the new reader:

![image](https://user-images.githubusercontent.com/3521738/43680575-43dd9402-983e-11e8-9090-02bede7666d9.png)
