### ISSUE TITLE
[Bug] some manga don't restore from backups

### ISSUE THREAD

**Issue by SynderBlack** [inorichi/tachiyomi#1529]
I should note that this is from latest dev (r1425) on 8.1.0 to latest stable (0.7.4) on 4.4.2
I get errors with "null" after it supposedly completes the restoration. 
Haven't figured out why, but only half of the manga are affected.

**Steps to reproduce:**

 1. backup on first device.
 2. restore on second device.
 3. restore shows ~50% of the manga as errors:
  `[timestamp] manga_name - null`
  and rarely some with `timeout` instead of null, though that might be some kind of unrelated issue.

[backup file](https://github.com/inorichi/tachiyomi/files/2156345/tachiyomi_2018-07-02_17-48.json.txt)

**Comment by LakotaGray** [comment]
Before you try using the backup file to load your library, have you gone to extensions and installed all sources used in your library when you created back up? Are they ALL latest versions? And have you gone through the process for the kissmanga/readcomiconline fix outlined in the discord channel?

**Comment by SynderBlack** [comment]
I do admit, at first I didn't have all sources installed but I've since attempted the same with all sources used. Everything is up to date and I've never required the fix since the built-in extension always worked properly.

**Comment by CarlosEsco** [comment]
so 95% of your errors are because MAL is down, the manga is getting restored fine it just errors trying to restore tracking info for it.  

Your other 5% is http 500 error.  So like Lakota said if you do have kissmanga/readcomicsonline you need to do the fix.

**Comment by SynderBlack** [comment]
I think you might've mixed your percentages, since in the log only 5 manga (out of around 50) actually have a "MyAnimeList not logged in" error, But yeah, looking through most of them are KA. Will try the fix.

**Comment by CarlosEsco** [comment]
Are you using multiple sources for same manga? 

I ask cause i see things like this

Horimiya - Could not find manga

but the manga is restored still.

**Comment by SynderBlack** [comment]
Using the fix on the receiving end fixed the issue, forgot to close this.
Yes, I am using for some manga multiple sources but that wasn't a problem with some other manga.
