### ISSUE TITLE
Chapters with multiple TLers/versions with no title differences are counted in their own.

### ISSUE THREAD

**Issue by ZaneHannanAU** [inorichi/tachiyomi#1530]
**App version:** r1425

**Issue/Request:** give some unique id to chapters

**Steps to reproduce (if applicable)**

 1. find a manga with multiple chapters with the same chapter, name and such on the same source
 2. download one of the dupe chapters
 3. reload the chapter page (either back-forth or w/e)

**Other details:**

![example](https://cdn.discordapp.com/attachments/349436576037732355/463494668294815759/Screenshot_2018-07-03-09-00-40-090_eu.kanade.tachiyomi.png)

Only one version has been downloaded but is showing as two.

Possible options would be attaching a `[group 1] [group 2] [group 3]` to the end; a chapter id or the dataurl to the folder name.

This is an issue that I myself have but have just … put up with for the most part; and now I'm posting it on behalf of 208340757856256000 in https://discord.gg/tachiyomi#support

I posted some alternative ideas after https://discordapp.com/channels/349436576037732353/349436576037732355/463495210681368576 such as the dataurl and cid but haven't come up with much of worth rn.

For backwards compatibility perhaps only apply the fix on chapters that would otherwise conflict with a lower chapter id.

Thank you for your time.

(moved from https://github.com/inorichi/tachiyomi-extensions/issues/378 )

**Comment by paulo27ms** [comment]
Already mentioned this on Discord but you can just use a complete timestamp in the folder name.

**Comment by karehaqt** [comment]
Could you advise where the option to add timestamps to folders is in the app please?

**Comment by paulo27ms** [comment]
There's no option, otherwise there'd be no point to this issue.

**Comment by arkon** [comment]
Closing in favour of #1893
