### ISSUE TITLE
I uninstalled and reinstalled but Tachiyomi still gives me (HTTP error 403) for every manga source i have

### ISSUE THREAD

**Issue by Enegit** [inorichi/tachiyomi#1532]
My Library had a lot of manga and i wanted to clear it out a little bit, so removed a bunch of them.
I then used the Advanced option to delete info on manga that isnt in my library, cleared cookies...etc
after that i used "android maid to delete downloaded manga.
After doing that i went to MangaDex and (HTTP error 403) I tried other sources, some opened and some didnt. I Uninstalled Tachiyomi and installed the latest version and now no source opens.
I went to F-droid and unintialled it again and tried to install it from F-droid and it said it doesnt exist.
I deleted everything, uninstalled and reinstalled again and nothing changed.
what shoud I do to fix this? 
am i responsible for the error, or is it just a coincidence that it happened while i was cleaning my Library?

**Comment by inorichi** [comment]
Make sure the extension is up to date.

Cleaning up the database won't harm the library, nor deleting the chapters with an external file manager. At most you only have to restart the app (in order to populate the downloads cache again).

It was most likely a temporary error on mangadex.

**Comment by Enegit** [comment]
I dont think its Tachiyomi's fault
a few days ago when i open some websites it started  asking me to answer a CAPTCHA
when i scroll to the bottom it says this 

("What can I do to prevent this in the future?)
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
Another way to prevent getting this page in the future is to use Privacy Pass. Check out the browser extension in the Chrome Store.")

Im not sure if im the cause of this message or someone else in the house.
Thanks for the reply, I'll just wait and see if things gets resolved on their own or something
