### ISSUE TITLE
[Feature suggestion/request] Seamless transitions between pages.

### ISSUE THREAD

**Issue by eirmd** [inorichi/tachiyomi#1533]
App version: 0.7.4

Issue/Request: Seamless transitions between pages.

Steps to reproduce (if applicable):

While reading and scrolling (landscape mode) example from page 1 to page 2 it suddenly jump/switch page. I hope it can be scroll between 2 pages and not jump directly to next page. Thanks.

**Comment by CarlosEsco** [comment]
Switch to webtoon reader.  The default reader is page to page. Webtoon has what you want

**Comment by eirmd** [comment]
Yes, this is what I want. Thank you very much!
