### ISSUE TITLE
skipping chapters. cant read manga properly because of not in arrange chapters

### ISSUE THREAD

**Issue by loiuekkun** [inorichi/tachiyomi#1534]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version: r1425

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by loiuekkun** [comment]
i used the other version and uninstalled then installed it over two times already even the extensions but its still the same.

**Comment by loiuekkun** [comment]
*not chapter. its pages. pages of every chapters are not arranged. cant read it manga chapter properly.

**Comment by Adowrath** [comment]
Please take time to even just fill out the template correctly. Also, complain this at the source you're using, they're controlling the order.
