### ISSUE TITLE
Why can't download from Mangago.

### ISSUE THREAD

**Issue by lunaackerman2211** [inorichi/tachiyomi#1538]
(a new member here! sorry don't know how to use this)

*App version: 0.7.4

**Issue/Request: download button keep stuttering ???

**Comment by einstein95** [comment]
What do you mean by "download button keep stuttering"? Can you be descriptive in what you see?

**Comment by lunaackerman2211** [comment]
its says "unexpected url...."

**Comment by einstein95** [comment]
What version of the mangago extension are you using
