### ISSUE TITLE
Image is too small

### ISSUE THREAD

**Issue by enriquezmark36** [inorichi/tachiyomi#1539]
**App version:** r1427

**Issue/Request:**
Loading up any page should show a really small, grasshopper readable image. Changing any settings like zoom position, scale type or image decoder doesn't make it larger. It's also not possible to zoom in. Changing to another source doesn't seem to change at all.

Sorry that I cannot find another device with nougat. This was not present on marshmallow and below.
I also tried wiping the app data and tried some random manga.

**Steps to reproduce (if applicable)**

 1. Open up any manga chapter

**Other details:**
My system runs on lineageos 14.1(Nougat) on 480x800 resolution at 240 dpi

When viewing 'Feng Qi Cang Lan' chapter 79.3 from Mangafox (EN)
![screenshot_20180712-175222](https://user-images.githubusercontent.com/7193373/42626361-bbda2c30-85fc-11e8-8061-06b0cb9a5cdf.png)

**Comment by inorichi** [comment]
Can you provide a screenshot of an app I posted [here](https://github.com/inorichi/tachiyomi/issues/689#issuecomment-280943088)?

**Comment by enriquezmark36** [comment]
Okay.
![screenshot_20180713-084829](https://user-images.githubusercontent.com/7193373/42666770-a568382a-8679-11e8-9fac-191a0f056edf.png)

**Comment by enriquezmark36** [comment]
From android 6.0
![screenshot_20180713-094834](https://user-images.githubusercontent.com/7193373/42669113-74dfa3fc-8686-11e8-9dea-9be487262aca.png)

**Comment by enriquezmark36** [comment]
I forced xdpi and ydpi values to be 240 instead of 25.4 so it now works. 

I'am now closing this.

**Comment by inorichi** [comment]
Sorry for the late reply. Yes, those dpi where definitely wrong.

**Comment by enriquezmark36** [comment]
Welp, actually from the code, it is set to always report 25.4 with this formula: 
xdpi = x_resolution * 25.4 / x_width 
but with x_resolution = x_width,

I can only laugh because I don't know why is it like this. hahahahaha.
