### ISSUE TITLE
[BUG] chapter sign as unreaded after update

### ISSUE THREAD

**Issue by Snake87r** [inorichi/tachiyomi#154]
Sometimes the chapter are marked as unreaded when you update the manga
EXAMPLE:
Today I updated and the manga and after that
The God of High school (readed from chapter 1 to chapter 234) and all the chapter from 1 to 248 are marked as unreaded
Golden boy (redeed from chapter 1 to chapter 85) and all the chapter from 1 to 94 are marked as unreaded
Boku no hero Academia (readed from chapter 1 to chapter 70) about 10 chapter from 52 to 61 if i remember correctly are marked as unreaded.
All the manga are rfom mangafox, I don't know if the other source have this problem..

**Comment by inorichi** [comment]
Duplicate. #119
