### ISSUE TITLE
Library auto update and manual update for new manga not working

### ISSUE THREAD

**Issue by Meganekun98** [inorichi/tachiyomi#1540]
App version: 0.7.4

Issue/Request: (issue) After updating the device, a couple of days ago the library auto update stopped working it self at first, then later the manual update also stopped along with the notification of updating(looking for library updates popup also stopped). Also even if they get updated there are no notification showing that the manga is updated, I only got to know by checking recently updated.
Also notification popping up that tachiyomi is running in background from "android system" got frequent after this happened.

Steps to reproduce (if applicable): 

(don't really know the cause but..)
 1. Updating to latest system build from old version
 2. Battery manager of the honor devices(specially adding to launch manager which restrict auto launch)
 3. Fiddling with device notification settings(though I never did, but maybe)

Other details:
Device: Honor 9 lite
OS: android 8.0.0
EMUI: 8.0.0
After reinstalling and restoring back up, removing it from "launch list" from "battery manager", its back to normal
![img_20180714_235246](https://user-images.githubusercontent.com/41239443/42727275-30e30644-87c1-11e8-9af6-29c852925aa2.jpg)
![img_20180714_234846](https://user-images.githubusercontent.com/41239443/42727255-db5c4e06-87c0-11e8-853a-aa356e129d82.jpg)
![img_20180714_234653](https://user-images.githubusercontent.com/41239443/42727259-e62df816-87c0-11e8-8e14-c953886a8e61.jpg)
![img_20180714_234911](https://user-images.githubusercontent.com/41239443/42727251-cf0e0e82-87c0-11e8-96f8-ab97b5761d78.jpg)
(never changed the notification settings before too)

**Comment by Trung0246** [comment]
I got the same problem too, but on dev version (r1427) and updated to 8.0.0 long ago. This bug only happened days ago...

**Comment by rontieu** [comment]
Same problem on r1427 where update doesn't work.

**Comment by inorichi** [comment]
Are all of you using EMUI? It's working fine on AOSP. The library updater received a minor change on r1427 but I'm quite sure that's not the reason.

> Also notification popping up that tachiyomi is running in background from "android system" got frequent after this happened.

This bugs me. From the looks of it, the service never calls the start command.

> Edit: I got 800+ mangas in my library, probably this is the reason?

No.

**Comment by Trung0246** [comment]
Samsung Galaxy S8+, not Huawei :\

**Comment by KoyLyria** [comment]
I reinstall the app but now like 100 of the manga that I've saved, have been deleted from my manga list. Help me pls
I don't know what to do.

**Comment by CarlosEsco** [comment]
Did you make a backup before uninstall?  If not you are out of luck.  If so restore the backup

**Comment by QuentinLB** [comment]
Same problem here on a Lenovo P8 (not EMUI), but it's working fine on my Huawei Honor 7 (EMUI 4.0.3). I've not already try to reinstall and Tachiyomi and it's plugins are all whitelisted in my power and notifications settings. Ask me if you need logs or more detailled specs.

**Comment by QuentinLB** [comment]
Nervermind, it was fixed after a reboot.

**Comment by EbolaMeister** [comment]
Sorry to necro but Ver 0.8.4 and same issue, tried to reboot, clear cache, force stop, reinstall, restore, nothing seems to work. Please help.

**Comment by arkon** [comment]
No idea how this slipped through my issue triaging, but we don't provide support for old versions.

See #2741 for a duplicate issue for the current versions.

**Comment by EbolaMeister** [comment]
Sorry to necro, but i have the same issue, Ver. 0.8.4. On a Redmi 6. The app is unrestricted from Battery Saving issues, tried to reboot, reinstall, force stop, clear cache and cookies, but nothing seems to work.
