### ISSUE TITLE
Reader error because of cache behaviour on large chapters?

### ISSUE THREAD

**Issue by fredgido** [inorichi/tachiyomi#1545]
**App version:**
Latest, r1427 
**Issue/Request:**
Reader error because of cache behaviour on large chapters.
**Steps to reproduce (if applicable)**

 1.Open chapter 84 of one punch-man on mangadex (or any other large, chap 92 by /a/ works too, possibly other larger than 75 * 1024 * 1024 bytes.
 2.Wait a few seconds for the app to try to cache all pages.
 3.Go to next page. Error.
![screenshot_20180725-105340](https://user-images.githubusercontent.com/17598829/43198291-096ae0b2-9006-11e8-84b5-2024f7227a87.png)

**Other details:**
Putting chapter pages to cache was not made to stop when cache is full of pages of same chapter. 
There is a need to check if the oldest entry page number is bigger than the current reading when adding each page. Evem then I don't know what to excpecting you go back and load other and it starts deleting pages that are the oldest one from cache order of entry but are next to the one you are reading.

Rewrite that caches based on page distance would be nice, caching pages of next chapter before you change. Split cache memory in half for old pages and for new pages?

**Comment by inorichi** [comment]
I've been aware of this issue for a long time but I just never tried to fix it. This is addressed in the new reader.
