### ISSUE TITLE
Random numbering of pages downloaded manga

### ISSUE THREAD

**Issue by fpschubert** [inorichi/tachiyomi#1546]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** r1427 and earlier

**Issue/Request:** When you download manga from Mangago, page numbering has issues like random pages.. You cannot understand the flow of the story since the last page is on the middle one or random pages flipping over. Weird thing is, the page number in the apps is the same.

**Steps to reproduce (if applicable)**

 1. Download manga
 2. Tried to read Manga in Tachiyomi and compare it online
 3.

**Other details:**

**Comment by einstein95** [comment]
[Known issue](https://github.com/inorichi/tachiyomi-extensions/issues/377)

**Comment by CarlosEsco** [comment]
And wrong repository
