### ISSUE TITLE
No wifi connection available when I tried to download but able to read online from the app

### ISSUE THREAD

**Issue by SchoolSucks384** [inorichi/tachiyomi#1548]
App version: 0.7.4
Issue: Can't download any chapter from all source
Other details: A few days ago it worked just fine but it suddenly didn't work. For some reason I can actually read any manga from most source but can't download any chapters at all. It says something like "No Wifi Connection available". I actually tried to download using another wifi but it still the same so I'm pretty sure that it's not the wifi.

**Comment by CarlosEsco** [comment]
You try turning off download only on WiFi and see if it works?
