### ISSUE TITLE
Allow to change the cover image of manga from any external sources

### ISSUE THREAD

**Issue by RatchetNine76** [inorichi/tachiyomi#1553]
App version: 0.7.2

Request: change cover image of manga by copying other external sources, other than a page from a 
               chapter

 1.Open in browser. then search the image you want to replace it with from sites like: google, my animelist, mangaupdates, or other manga sites.

I would like to change the cover image of manga because manga sites like Kissmanga have only placeholder image as their cover, like Komi-san wa Komyushou Desu. and that their no volume cover in all of it's chapter so I can't set cover image it.

**Comment by arkon** [comment]
Hold down the manga in your library and choose the edit button (pencil icon).

**Comment by RatchetNine76** [comment]
Oh thanks for that. Didn't know about that feature. I will just close this then.
