### ISSUE TITLE
TachiyomiEH abruptly closing when opening any manga from author search

### ISSUE THREAD

**Issue by kadaikhan** [inorichi/tachiyomi#1556]
App version: 7.4.4

Issue:
I recently change my device (now using galaxy note 8) and after installing and restoring the app my back up I tried to search an artist related works from my gallery but after selecting any work and trying to open any chapter it closes up the app.

I tried to search directly those titles by their name and it doesn't close when I open them up with that method.

**Comment by CarlosEsco** [comment]
Wrong repo tachiyomieh is a fork owned by someone else
