### ISSUE TITLE
[Enhancement] Colorize Images (Gradient Maps)

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi#1558]
**Issue/Request:**
The ability to colorize the black color gradient for black & white manga. It creates an interesting visual effect, similar to playing black and white games on a Gameboy Color.
Ideally, the ability to perform such operations in the viewer would be more practical than attempting to download and manipulate the images externally.

**Example:**
Here is a image colorized with a gradient map https://imgur.com/7MFs1GL
Image editing software, [such as GIMP](https://graphicdesign.stackexchange.com/questions/74910/gimp-change-a-signature-color-from-black-to-blue-preserving-the-tones), can do this. 

**Notes**
This is different from the color filter option. Where as the color filter adds a transparent filter on top of the image, color toning using a gradient map changes the actual color of the image and looks much better.

**Comment by hXtreme** [comment]
I don't see why one would really want this? It shouldn't be a feature that is used frequently enough to be added when, as you've mentioned can be done by hand on Gimp.

**Comment by arkon** [comment]
Way out of scope.
