### ISSUE TITLE
Manga pages are not in order

### ISSUE THREAD

**Issue by grrlss** [inorichi/tachiyomi#1563]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.7.4

**Issue/Request:** So the downloaded manga pages are not in order..

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
Not enough Info and this is more than likely source specific which does not go in this repo.  Finally my guess is this is mangago and that issue is already open on the repository for extensions

**Comment by grrlss** [comment]
Can you add mangakakalot.com in the extensions?

**Comment by einstein95** [comment]
Make a new issue
