### ISSUE TITLE
[Feature Request]  filter options for browsing catalogues

### ISSUE THREAD

**Issue by ForgetfulJones** [inorichi/tachiyomi#1570]
I would like to be able to filter the view of catalogues (in either latest or "browse") by a number of criteria.  Particularly by genres I'd never be interested in, for example.  
For example, I'd like to be able to go into 'latest' and click to either only show or to bar from showing '4-koma'.  Or don't show any mangas that have less than 10 chapters, Or not to show mangas less than 6 months old, etc.  
I'm sure a number of other sorts of criteria would also be useful.

**Comment by CarlosEsco** [comment]
Not possible. A source dictates the filters possible.  Most sources have the possible filters under browse.
