### ISSUE TITLE
[Feature Request] Integrate Google Translate

### ISSUE THREAD

**Issue by jasonhpchu** [inorichi/tachiyomi#1571]
I'm not sure how feasible is it, or how much does Google Translate expose its API for other app to use.
But I was thinking it would be so convenient to read raw manga if tachiyomi can integrate Google Translate similar to its camera image translation.
For example, turn on translation mode, highlight the bubble text, then show Google's translated text.
Thanks.

**Comment by inorichi** [comment]
Not really feasible, sorry.

**Comment by jasonhpchu** [comment]
yea...was poking around, doesn't seem like Google Translate has much API to integrate with other apps.  Can't even "share/send" image to Google Translate app.
Only thing I can do is screenshot Tachiyomi manga page, open Google Translate, then open image.

Thanks though for looking into it.
