### ISSUE TITLE
[Feature-Request] multithread download

### ISSUE THREAD

**Issue by poldi1405** [inorichi/tachiyomi#1573]
**App version:** any

**Issue/Request:** multithread download

**Other details:** Downloading small files throttles the speed, a way of circumventing it is by downloading multiple files at once.

**Comment by einstein95** [comment]
Duplicate of https://github.com/inorichi/tachiyomi/issues/1567

**Comment by GreyCannibal** [comment]
🤣🤣 the issue is serious, not getting over 400kbps

**Comment by CarlosEsco** [comment]
Just download in advance or overnight

**Comment by poldi1405** [comment]
Well unfortunately you can sometimes download for a limited time only (public Wi-Fi on holiday in my case)
