### ISSUE TITLE
Mangadex error 502.

### ISSUE THREAD

**Issue by HentaiGuy** [inorichi/tachiyomi#1574]
App version: 0.7.4

Issue/Request: MangaDex source doesn't work. When I attempt to load any of my bookmarked manga, it only prompts me with 'retry'. 
I have tried to clear cache, cookies and afterwards have accessed a manga from MangaDex website, without success.

**Comment by paulo27ms** [comment]
502 means an issue with MangaDex's servers, probably from overload. Try again later.

**Comment by HentaiGuy** [comment]
I tried 8 hours ago, and I tried now. The manga and the catalogue wont load.
I can read the manga from the website without problems.

**Comment by paulo27ms** [comment]
Have you updated the extension?

**Comment by HentaiGuy** [comment]
There were No update yesterday.
Just checked, and there were an update. 
I did download it, but I get some weird Googlestring error.

**Comment by HentaiGuy** [comment]
As of now, I can see the catalogue and read some of the manga. But some manga pops up with a 'MalformedJsonException'.

**Comment by Ampexi** [comment]
Just updated the extension and I get **"com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $"** whenever I try to open any MangaDex manga I have in my library. Other manga in MangaDex catalogue are working normally.

**Comment by FlaminSarge** [comment]
MangaDex seems to be heavily rate-limiting for certain IP ranges (error code 429). On Wifi I couldn't open any chapters, but on mobile data I could.

**Comment by paulo27ms** [comment]
@HentaiGuy @Ampexi
Update your whole library once (or update the chapter list of the manga by swiping down at the top of the chapter list) and that issue should be fixed and you can read again.

**Comment by CarlosEsco** [comment]
If you have very large mangadex library don't swipe the whole library. You will get banned
