### ISSUE TITLE
Filters don't work if only a list is modified

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#1576]
**App version:** v0.7.4

**Issue/Request:**

If you try to filter a source with some sort of list (e.g. genres), it doesn't actually do anything.

This check seems to fail: https://github.com/inorichi/tachiyomi/blob/7f63e318f1a741df038e466b200fc6d81bcdaa91/app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt#L140

Probably because this is just a reference to the same objects: https://github.com/inorichi/tachiyomi/blob/7f63e318f1a741df038e466b200fc6d81bcdaa91/app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCataloguePresenter.kt#L100

Potential solutions:
- Make a deep copy on create, but is kind of messy
- Make the `Filter` subclasses have a `isDefault()` method to check

**Steps to reproduce (if applicable)**

 1. Open catalogue that has genres as a filter (e.g. MangaDex or Manga Rock)
 2. Try searching
 3. Notice it doesn't actual search by genres
 4. Change another filter
 5. Notice that it does work now

**Comment by inorichi** [comment]
The method `getFilterList` must always return a new copy of the list AND its objects. [This](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt#L459) must be turned into a function.

On 1.x I added a method `isDefaultValue()` but for compatibility reasons it won't be added on the current version.
