### ISSUE TITLE
[Feature request] Ability to decide update-handling per category

### ISSUE THREAD

**Issue by scriptmode** [inorichi/tachiyomi#158]
So, I have several dozen Mangas on hold, to read them later, somewhere in the future. So updating them is a little bit pointless, because I'm not interessted to know about any new chapters there. But still costs time and hit's the mangasite unneccessary. 

So what would be useful is to deactivate a category the global update. And maybe have a button to only update mangas from the open category.

**Comment by inorichi** [comment]
This is an interesting feature, and I already thought about this before. I even added a `flags` column in categories to allow something like this in the future.

**Comment by inorichi** [comment]
It's now possible to update the active category by pulling down 7cc4405. For the time being the global update will still update everything.
