### ISSUE TITLE
[Request][Enhancement] Mouse Scrolling = change pages

### ISSUE THREAD

**Issue by zragon** [inorichi/tachiyomi#1580]
The viewer that only support scrolling is WEBTOON... Others... Not supported

I'm using bluetooth/2.4GHz mouse to navigate through my phone.. If this feature is implement... Man! What ease will it be!

& if u can add a custom mapper for buttons on controller/mouse/keyboard would be more cool too... Thanks in advanced!

**Comment by inorichi** [comment]
I've added support for mouse wheel events on the new reader.

Which key events are you missing? I doubt I'll add custom mappings but I can consider adding a few more keys.

**Comment by zragon** [comment]
Woah nice! 

The only features that i miss is SCROLLING pages  with MOUSE SCROLL when the viewer is set on :

Vertical, Left to Right, Right to Left...

Only webtoon works fine..

I haven't tried the BETA release.. But the one I'm using right now is latest from 'DEV' downloads

**Comment by inorichi** [comment]
Yes, that's what I added.

I was asking for keyboard keys because of this line:

> & if u can add a custom mapper for buttons on controller/mouse/keyboard would be more cool too... Thanks in advanced!

Currently only arrows and page up/page down are used.
