### ISSUE TITLE
Right to Left viewer does not register swiping properly on android 9

### ISSUE THREAD

**Issue by Maelstrom1** [inorichi/tachiyomi#1582]
**App version:**
v0.7.4

**Issue/Request:**
When default viewer is set to "Right to left" swipes only change the pages if you swipe the entire screen instead of a short swipe like left to right or how it worked before the phone was updated to android 9. 

**Other details:**
I own a pixel, so this is the full release of android 9. Restarting the phone or application had no effect, and this issue has been reported by other users in the discord, but an issue has not been made yet.

**Comment by Sarkazein** [comment]
Same issue here on a Pixel XL.

**Comment by inorichi** [comment]
Does it work with the latest beta on #1550?

**Comment by jsilvermist** [comment]
Seems fixed in Beta 4 on #1550 on Pixel 2 XL with Android 9 Pie.

**Comment by jsilvermist** [comment]
Please ignore me previous post, it is NOT fixed in Beta 4.

**Comment by inorichi** [comment]
Did you enable the beta reader in settings?

**Comment by jsilvermist** [comment]
@inorichi Didn't know I had to, but when I do, it IS fixed, sorry for the noise haha!

**Comment by Sarkazein** [comment]
Same for me.  Beta 4 with the new reader is working like a charm so far.

**Comment by UhOhWillow** [comment]
How do I enable the beta reader? For some reason I can't find it. I should be using the latest dev release

**Comment by UhOhWillow** [comment]
How do I install that version? Ive found it and downloaded it but now im confused. Sorry lol

**Comment by yambadr** [comment]
Remove .zip from filename then install.

**Comment by UhOhWillow** [comment]
Thanks!

**Comment by Gazz1e** [comment]
Loving the app, thanks for all your hard work. Sadly I also have the scroll issue on my OnePlus 6 running the final release of Android 9. Worked fine on Android 8.
