### ISSUE TITLE
[Feature] MAL API Workaround

### ISSUE THREAD

**Issue by MCAxiaz** [inorichi/tachiyomi#1583]
**Issue/Request:**

So I went ahead and wrote up a workaround for MAL tracking on [my fork](https://github.com/MCAxiaz/tachiyomi) since it seems like I'll die of old age before its API ever comes back. Not sure if this is something you'd be interested in integrating into the actual build.

**Comment by tmathura** [comment]
Can you merge your fix in?

**Comment by inorichi** [comment]
I forgot about this. Yes, please submit a PR and I'll review. The old API is probably not going to work when it comes back anyways.

**Comment by tmathura** [comment]
MCAxiaz will you merge it please?

**Comment by MCAxiaz** [comment]
created pr [here](https://github.com/inorichi/tachiyomi/pull/1647)

**Comment by viggy96** [comment]
Can we merge this?

**Comment by Soitora** [comment]
This can be closed I think @inorichi
