### ISSUE TITLE
[Request][Enhancement]Return to library after last page

### ISSUE THREAD

**Issue by fieldhouse** [inorichi/tachiyomi#1584]
Currently, when you reach the last page of a manga you can swipe, tap, or click all day and it stays on the last page.  

Returning to the library makes a lot more sense, even if it's after 2 or 3 swipes. Think of it like closing the back cover after you finish reading; you use the same motion as turning pages.

**Comment by metroid112** [comment]
I like this idea, but you gotta specify it's the last page of the last chapter available. Doesn't make sense on the last page of every chapter. I don't know if it should be automatic or a button pop-up after a certain number of actions on the last page of the last chapter.

**Comment by fieldhouse** [comment]
Good catch. Yeah, it'd suck if it was every chapter.

**Comment by inorichi** [comment]
62e7bea this is as far as we'll get. I don't like the reader being closed automatically.
