### ISSUE TITLE
[Feature] Manga Updates (Baka Updates)

### ISSUE THREAD

**Issue by quinnjet** [inorichi/tachiyomi#1588]
I was wondering if it'd be possible to integrate Baka Updates into the Tachiyomi app. MAL and AniList are very useful, but they tend to lack some of the lesser know mangas. I saw that this feature was previously requested about a year ago, but nothing seemed to come to fruition because of an issue with the API, or lack thereof. Maybe something about Baka Updates may have changed in that time. Thank you in advance.

**Comment by Flat** [comment]
Duplicate #624. They still do not have an API.
