### ISSUE TITLE
[feature request] auto-download in default category

### ISSUE THREAD

**Issue by drac0300** [inorichi/tachiyomi#1589]
**App version:**
r1427 (lastest dev on f-droid)

**Issue/Request:**
It is possible to select categories so that the app automatically downloads chapters of manga in selected categories
But in that setting, it is impossible to select the default category
It would be cool if we could also select the default category

**Steps to reproduce (if applicable)**

 1. Go to settings -> downloads
 2. Touch "categories to download" (not sure of the exact formulation : my phone is not set to English)

**Other details:**

**Comment by dhanjit** [comment]
Bumping this, because Default itself is also a category and needs to be included in download category.

**Comment by arkon** [comment]
This is fixed in dev.
