### ISSUE TITLE
Crash in chapters list

### ISSUE THREAD

**Issue by Taumer** [inorichi/tachiyomi#159]
Open random manga
Open chapters list
Scroll down and while the animation is not finished, press the back
logcat http://pastebin.com/cD3Z3fej
Android 6.0.1 without root and xposed
Version r481
Sorry, english is not my native language

**Comment by inorichi** [comment]
I've received a lot of crash reports regarding this issue, but I didn't know how to reproduce it.

Thanks, it should be fixed soon.
