### ISSUE TITLE
Recent updates from KissManga and Manga Rock can't be opened

### ISSUE THREAD

**Issue by reddeimon** [inorichi/tachiyomi#1590]
I notice some of the new manga updates from KissManga and Manga Rock cannot be opened. All it says is;

"Image could not be load. Try changing the image decoder or with one of the options below". 

After a few testing download and checking the file manager, I found the manga chapter is downloaded into single unreadable file. 

Like, when the chapter is downloaded pretty normal during a download, but after the download finishes, the chapter folder become a single unreadable file. 

The apps still can read manga normally if online, but if the manga is downloaded it becomes unreadable. I hope you can fix this soon.

Tachiyomi ver. 0.7.4
Android 7.1.2

**Comment by TheInpiredConjurer** [comment]
I think there's a problem with the image decoder. Try changing the decoder to 'skia'

**Comment by joseph619** [comment]
Go to Settings -> Reader -> Image decoder -> Rapid or Skia. It should work

**Comment by AmineI** [comment]
I believe this is fixed since the last big update of the reader.
