### ISSUE TITLE
Series 'UnOrdinary' not found for tracking

### ISSUE THREAD

**Issue by TheWhiteHunter** [inorichi/tachiyomi#1592]
https://anilist.co/manga/87399/unOrdinary/

Not sure why but this series can't be found for tracking. The only result is 'Kanojo Iro no Kanojo'.

I've getting unOrdinary from the Webtoons extension if that makes any difference

**Comment by Deterio** [comment]
Should be fixed after #1550

**Comment by einstein95** [comment]
Actually fixed since b19a4d297763acc1155f66edee83d347b4be433a

**Comment by CarlosEsco** [comment]
Next release or stable it will be fixed.  It's already fixed in dev
