### ISSUE TITLE
Error 429 during restoring from backup 

### ISSUE THREAD

**Issue by mrskizzex** [inorichi/tachiyomi#1594]
**App version:** r1428
**Issue/Request** Increase delay between requests to source when restoring from backup 
**Steps to reproduce (if applicable)**
Try to restore more than 200-300 Manga at the same time, in the middle of restore it will start failing with 429 too many requests.

**Comment by CarlosEsco** [comment]
Let me guess you have all that on one source?

**Comment by mrskizzex** [comment]
80% is Mangadex ...
Is that a problem ?

ˡᵒˡ

**Comment by CarlosEsco** [comment]
Nothing really we can do unless we made multiple backups or time delayed it even more. But basically you are hammering their server. Do you get the error on a 2nd restore attempt after some already restored?

**Comment by mrskizzex** [comment]
Heh I know I'm hammering the server.
On 2nd restore attempt instead of ~50 fails there is ~250 fails.
I don't know how it's done in your code but i think the easiest way to resolve this would be something like this :
1. User initiates restore like always.
2. Restore proceeds normally without any change to delays.
3. If there are errors, either add them to background restore queue and retry every hour until queue is cleared or 12hours/12 retries happen or which I think its easier to implement, simply create a separate "error" restore file that contains all failed restores and tell the user to retry later (in hour or two).

**Comment by arkon** [comment]
It's probably better to just enter a "dummy" entry (with the title and whatever other data is available from the backup) if a restore fails that the user can manually retry later.

**Comment by mrskizzex** [comment]
Ugh please no. If you had 200+ dummies that you had to manually pick out of 500 manga library it would be pain. 

I would rather go back to manually splitting the backup files.

**Comment by arkon** [comment]
Nothing would prevent you from still manually splitting the backup files to avoid that scenario in your case though.

The dummies would make more sense for people with more ordinary library sizes that might have a handful of them fail (because of rate limiting, or dead sources, or something else).

**Comment by mrskizzex** [comment]
Even so, if you only have a handful of them, why would you want to do this by hand and not just click one more button that would automatically retry all failed ones. 
That's just being mean and adding additional work by having to add logic of adding dummies and then adding a button for searching that particular dummy in the sources. 

And In retry button scenario you would only add one additional temp file that would get smaller and smaller each time you pressed retry.

**Comment by arkon** [comment]
You could. It's just from a UX standpoint, but either way would be better than the current behaviour where the backup just fails at a certain point and doesn't move forward.

A combination of the two would just be skip past ones that fail and write the failed ones into a file (akin to your temp file idea), but without the retry button -- effectively just making another backup file but with only the failed ones you can retry at will later.

**Comment by Sparh4wk** [comment]
I reported same problem.. only way to restore it for me was split backup file in two files and then restore both of them..

**Comment by Flat** [comment]
Rate limiting would be the ideal solution. May try talking to Mangadex to include rate headers in responses.

**Comment by Sparh4wk** [comment]
@Flat 
I had the same problem with kissmanga, so dunno if its way to go.. cause u need to talk with all website owners for it :(

**Comment by Flat** [comment]
There are other options to throttle connections aside from rate headers, they just make it a lot easier and efficient

**Comment by arkon** [comment]
Extensions can now have rate limiting, so hopefully that helps with this.
