### ISSUE TITLE
[Feature Request] Option for downloading 5 chapters at a time in the download queue

### ISSUE THREAD

**Issue by TheInpiredConjurer** [inorichi/tachiyomi#1595]
**App version:** r1428

**Issue/Request:** multiple concurrent downloads

**Steps to reproduce (if applicable)**

 1.Settings
 2.Downloads
 3. Select number of chapters to download at a time

**Other details:**
Currently, the download is limited to only one chapter at a time. Is there a way to increase it, so that it downloads 5 chapters at a time? Of course, someone could customize it to download 4, 3, or 2 downloads at a time, if he/she wishes.

I have a high-speed broadband connection. Hence, waiting for a long time to download a manga, which has over 200 chapters is kinda annoying.

If you make it so that it downloads 5 chapters at concurrently, that would be huge help.

Thanks!

**Comment by pervertkirito** [comment]
This feature was in Tachiyomi long ago... but has been removed...
> It was removed for a reason, it was causing IP bans
https://github.com/inorichi/tachiyomi/issues/1567#issuecomment-410681741

**Comment by toshiro9117** [comment]
I agree to add increase the download chapter at a time...
