### ISSUE TITLE
WhatsApp Status Can't Apearing (WhatStatus.co)

### ISSUE THREAD

**Issue by MyAnime1221** [inorichi/tachiyomi#1597]
Hello Everyone!
    Hope All are Good, Guys I have detected an issue in my WordPress theme. When I upload a new theme on my site [WhatStatus](https://whatstatus.co/), my content doesn't appear after changing the theme. Guys, Please Tell Me What Can I do to solve this issue please help me to fix this error.

**Comment by CarlosEsco** [comment]
This has nothing to do with tachiyomi
