### ISSUE TITLE
Constant crashing 

### ISSUE THREAD

**Issue by AssassinKO** [inorichi/tachiyomi#1598]
The app keeps chrashing when i try to open it and after i try to open it, it starts crashing by itself 
This started happening after i deleted downloaded manga using a third party app

**Comment by inorichi** [comment]
Can you get a logcat? Also which version?

Some people reported installing the same version over (without uninstalling) fixed crashes on startup but I'm not sure it will fix it.

**Comment by AssassinKO** [comment]
Mnnn 
Cant get the log but its the latest version and i installed the same version over it and it fixed the crashing
