### ISSUE TITLE
[Feature Request] Separate library notification categories

### ISSUE THREAD

**Issue by Mrnoname1000** [inorichi/tachiyomi#1602]
**App version:**
0.7.4
**Issue/Request:**
Separate notification categories for library scans and updates.
Currently notifications for library scanning and library updates are lumped into a single category: "Library." I don't care when my library is being scanned for updates, but I want to know as soon as possible if there is an update. Right now I can either silence both or force both to notify me.

**Comment by eji30** [comment]
Very much agree with this. For me, the main purpose is of course when changing notification types (silent, sound, etc). "Library" should not be a single notification category for "searching for library updates" vs "new chapters found".

**Comment by arkon** [comment]
#2050 for more details.
