### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by waptik** [inorichi/tachiyomi#1604]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version: 
Development app-> r1428
Production app ->0.7.4
Issue/Request: unexpected error occurred / downloadsDir ....

**Steps to reproduce (if applicable)**

 1. Open both dev and production apps simultaneously
 2. Go to catalogue
 3. Search for 'yuragi"
4. Select first manga from mangese
5. Download any chapter
4. Error will be displayed on status bar

**Other details:**
Even all manga that received recents updates face same issue. It all started today. 
![screenshot_2018-09-05-17-41-16](https://user-images.githubusercontent.com/1687551/45111642-03cdc480-b135-11e8-8899-04455da6da43.png)
![screenshot_2018-09-05-17-21-08](https://user-images.githubusercontent.com/1687551/45111672-13e5a400-b135-11e8-9921-260968cc5de8.png)

**Comment by arkon** [comment]
Might've run out of storage room?

**Comment by waptik** [comment]
Yeah, that's the problem. Sorry about not closing the issue. I completely
forgot about it.
Closes #1604
