### ISSUE TITLE
Feature Request/Suggestion: Timer for Reader Custom Filter and Brightness

### ISSUE THREAD

**Issue by Brentboi** [inorichi/tachiyomi#1605]
Hi I don't know if anyone has requested this at least looking through for a little I haven't seen it. I would like to suggest a feature that saves a set brightness/color filter and has it turn on and turn off at a certain time. This is just a quality of life feature so it's not necessary honestly. I mostly read in the middle of the night so I tune down the brightness while reading at night, but I occasionally read in the day so it's just a little tedious.

**Comment by metroid112** [comment]
Which Android version do you have? there's a feature for this by Android itself.

**Comment by DarKCroX** [comment]
You know... you can find something similar on Google Play
https://play.google.com/store/apps/details?id=info.papdt.blackblub
