### ISSUE TITLE
Global catalog search ignores extension settings

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi#1606]
**App version:**
r1429
**Issue/Request:**
When searching for R18 manga with the mangadex setting set to not show R18 manga both in the catalog and in the global extension settings, the manga still shows up, but not if you search in the catalog.
**Steps to reproduce (if applicable)**

 1.set Mangadex extension to not show R18 manga
 2.do a global catalog search for "Pool Side no Koi Moyou"
 3.the manga shows up

**Other details:**

**Comment by CarlosEsco** [comment]
fixed in latest mangadex version 1.2.38

https://github.com/inorichi/tachiyomi-extensions/pull/483
