### ISSUE TITLE
New reader next chapter page alignment

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#1609]
Could the text on the page be aligned so that if the chapter names are similar they actually align? Since finished and next are different lengths they don't.

**Comment by inorichi** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/3521738/46665748-03599b00-cbc5-11e8-8a62-cbe62420d4bd.png)

**Comment by j2ghz** [comment]
Yes, thank you

**Comment by inorichi** [comment]
790e090
