### ISSUE TITLE
Can't change media volume since New Reader update, even with volume key navigation disabled

### ISSUE THREAD

**Issue by mashwell** [inorichi/tachiyomi#1611]
**App version:** r1429-r1431

**Issue/Request:** I can't change the Android system media volume in the reader since the 'new reader' update, even when volume key page navigation is disabled.

**Steps to reproduce (if applicable)**

 1. Launch Tachiyomi while having some media play in the background.
 2. Open Settings > Reader and confirm that volume keys navigation is disabled. 
 3. Open manga chapter list. Pressing volume keys will still change the volume as expected.
 4. Read a chapter. Pressing the volume keys will do nothing now. (toggling the nav settings on and off will not change the behavior)

**Other details:**
Tested on Redmi Note 3 running Android 9.0 and Mi 5 running Android 8.0.  
Previous versions (<=r1428) yields expected behavior.

**Comment by INSANEMODE** [comment]
same thing running r1431 on my lg v30 running 8.0.
If you tap the screen once to get the menu to show up, or hold to get the page sharing options to come up, volume will work, but not if you are just looking at a page in fullscreen. 
All navigation options in settings disabled, including volume buttons.

**Comment by FlaminSarge** [comment]
These two cases don't return false if the config is off:
https://github.com/inorichi/tachiyomi/blob/18f89cc341d85dbb734d370077307d33a8454f6f/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt#L265
Pretty sure that's the culprit.

**Comment by inorichi** [comment]
Yeah it's. I'll update it later.

**Comment by inorichi** [comment]
7afd224

**Comment by mashwell** [comment]
Updated to r1433, volume button now works as it should. Thanks!
