### ISSUE TITLE
Series '1 x ½' not visible on AniList tracking

### ISSUE THREAD

**Issue by dr4chen** [inorichi/tachiyomi#1612]
**App version:** v0.7.4 (re-downloaded and re-installed just in case)

**Issue:** Manga [1 x ½](https://anilist.co/manga/103629/1-x-/) is not appearing on the AniList tracking search

**Steps to reproduce (if applicable)**
 1. Open library entry for 1 x ½
 2. Go to 'Tracking' tab.
 3. Press "Edit" and enter the exact copy-and-pasted title from the AniList website into the search box. I didn't have much success for modifications of the title or the listed "synonyms" on the entry page.

The above also failed for a friend of mine who tried to track it himself.

**Other details:** I'm not sure if this is an error on behalf of the app or AniList, so apologies if the latter is the case. I can add that it appears the manga is not a particularly new entry as it has been available since at least early August 2018.

**Comment by CarlosEsco** [comment]
This already fixed in dev version.  So once a new stable is released it will work
