### ISSUE TITLE
[Feature Request] Better surface FAQ in app

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#1613]
**App version:** 

0.7.4

**Issue/Request:**

Certain issues and functionality tend to be asked about frequently and are usually documented in either the GitHub repo wiki or on Discord, which are a bit hard for typical users to find.

We could potentially add a "Help" entry in the navigation drawer that opens a WebView akin to most Google apps, and have a FAQ/help site hosted on GitHub with common issues such as:

- How to set up local manga
- What are extensions
- AdBlock issues for extensions
- etc.

**Comment by hXtreme** [comment]
How about adding an option in the menu that opens up the wiki.

Then we would just have to spend a bit more time to make the wiki page a bit better.

**Comment by hXtreme** [comment]
I have already started writing some guides in the wiki feel free to chime in.

**Comment by arkon** [comment]
Using the wiki might be a better idea than trying to create a separate FAQ site like I was originally thinking. :)
