### ISSUE TITLE
[Request/Issue] E-Hentai Language

### ISSUE THREAD

**Issue by DaemonPhoenix42** [inorichi/tachiyomi#1614]
Forgive me if this is an issue related to the source (aka) website, but even though the index marks it under english, a vast majority of the comics I've looked at fall under japanese or Chinese language and not english.
If that's not considered an issue then I ask the possibility of adding language type to the metadata search filter?

**Comment by CarlosEsco** [comment]
Post this in the tachiyomi extensions repository
