### ISSUE TITLE
Archive chapters

### ISSUE THREAD

**Issue by DaemonPhenex** [inorichi/tachiyomi#1615]
As an extension of #537, It would be nice to have a toggle ability to automatically/manually archive downloaded Volumes/Chapters, I'm not sure how this would effect parsing or preformance but I find this would be effective for exporting to a 3rd party library such as calibre or comicrack on my pc. 
Edit: Seems this was also mentioned in #918. Feel free to consider this a vote in favor and close.

**Comment by arkon** [comment]
Closing in favour of #918
