### ISSUE TITLE
Image isn't displaying correctly

### ISSUE THREAD

**Issue by Nihisil** [inorichi/tachiyomi#1616]
**App version:** 0.7.4 (F-droid)

**Issue/Request:** 

The image isn't displaying correctly.

![photo_2018-09-13_16-47-41](https://user-images.githubusercontent.com/475367/45477720-c12f6c00-b774-11e8-9035-30964ffacb07.jpg)

**Steps to reproduce**

 1. Open this manga http://www.mangago.me/read-manga/tetsunaki_no_kirinji_kabukichou_seiatsu_hen/
 2. Chapter 67, page 2. It looks like on the screenshot.
 3. If you open the same page on the manga source website, it looks fine.
 4. I tried do delete and download chapter again, it didn't help.
 5. There are 3-5 pages like this in the 3-4 latest chapters of this mange (but I didn't read a lot of manga on this device, it could be more).

**Other details:** Device is OnePlus 5t (screen 1080 x 2160).

**Comment by einstein95** [comment]
Wrong place, report bug here https://github.com/inorichi/tachiyomi-extensions/issues

**Comment by Nihisil** [comment]
Why? It doesn't related with manga source. It is related with app image reader.

**Comment by einstein95** [comment]
The mangago extension is the bit that controls parsing the page for images and decrypting and fixing (if necessary) the content. That's the issue that's going on here.

**Comment by Nihisil** [comment]
Got it. Thank you for the support.
