### ISSUE TITLE
[Feature Request] Make Use of Notification Bar Area on Notched Phones

### ISSUE THREAD

**Issue by coltaku** [inorichi/tachiyomi#1621]
Any chance of Tachiyomi getting notification bar area support with Android Pie devices like the Essential Phone? I would love it if my favorite manga app took advantage of all that extra space! I'm hoping that the app will allow the area around the notch to be used when in fullscreen mode. At the very least, when zooming in, it would be get if it could take advantage of the extra screen space.

I realize that if it always used that extra screen area, the notch might cut off things you wouldn't want it to, or possibly even text. Although, personally I think it would be great if both modes could be implemented so that people could choose or even switch between them per page. Both modes being either 'Always use all of screen' or 'Only use extra screen when zooming in'. I think this would be widely appreciated seeing as tons of devices now have notches and more will probably continue to be made.

**Comment by coltaku** [comment]
The Essential Phone got an update that brought back the control of the notch area so this app now takes advantage of that space. Now if I could zoom out of pages while in 'fit height' mode then the viewer would work perfectly on phones with notches.

**Comment by arkon** [comment]
Closed via #2595
