### ISSUE TITLE
{Site Issue} WhatStatus.co Landing Page

### ISSUE THREAD

**Issue by MyAnime1221** [inorichi/tachiyomi#1624]
Is Any Tell Me How can I Make One Page of Website: [WhatStatus.co](https://whatstatus.co/) into PHP. Is this is possible or not. Please Help Me.

**Comment by that-one** [comment]
Does that have _**anything**_ to do with this app?

**Comment by yambadr** [comment]
This has nothing to do with Tachiyomi. Please close.
