### ISSUE TITLE
[Feature] aspect ratio

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#1627]
r1438
Just got a huge note 9 but it stretched the manga out too much in landscape and its too hard to read in portrait. 
Could we get a way to create black bars either side or choose our aspect ratio/max width.

**Comment by CarlosEsco** [comment]
What fitting are you using?

**Comment by ShakeBake** [comment]
Webtoon reader, all fittings are the same for the webtoon reader.
I've always used a pinch grip and volume buttona to scroll. 
Could use vertical reader and set sizing to original, which does shrink the width, but it depends on the source image.
But would be useful to set aspect ratios/widths and sizes. Even on a tablet in some cases. 
I tried reading manga on my tablet once but it was annoying as I'm super short sighted and would have to move the tablet around to fit my field of view. I read most of my manga in bed at night so prefer not to use my glasses.
Having the image 'centred' makes it easier.

**Comment by ShakeBake** [comment]
Or mabye we could show the original width of the image in webtoon viewer? Although it would still depend on the source and be inconsistent.

**Comment by ShakeBake** [comment]
Just found how to change the aspect ratio of the app. For others interested, there's a small rectangle with shrink/enlarge arrows on the last app opened in the multi tasking menu (in the bottom right of the thumbnail of compatible apps). I would assume this works for s8/+, s9/+ as well but not sure.
