### ISSUE TITLE
[Feature Request] Show Errors after Library update

### ISSUE THREAD

**Issue by InvisibleSymbol** [inorichi/tachiyomi#1630]
**Issue/Request:**
When the app finishes updating your Library, and you go to the "Library updates" page, add a banner (for example at the bottom in red with **"Something went wrong [x Errors]"**) which when clicked on shows all errors. _I'm pretty sure 20% of my manga isn't updating cause of a dead source, but to lazy to check it_. Would also help with normal errors like 404, 500 & Co

**Comment by AbsurdlySuspicious** [comment]
Running in "manga is licensed" after some time this title haven't updated is also kinda annoying. Really important feature

**Comment by joseph619** [comment]
Licensed manga isn't Tachi issue, change your source.

**Comment by AbsurdlySuspicious** [comment]
@joseph619 I didn't mean it. I mean that user will not find out that manga doesn't get updates because of error until he tries to update that exact licensed title (not even something from the same source) manually, that's why this feature is a must.

**Comment by arkon** [comment]
Was added in 0.10.0.
