### ISSUE TITLE
The Color Filter for Reading Manga Does Not Work

### ISSUE THREAD

**Issue by KingOfScorchers** [inorichi/tachiyomi#1635]
**App version:**
0.7.4 (stable build)
**Issue/Request:**
For an unknown reason, the color filter doesn't work.
**Steps to reproduce (if applicable)**

 1. Open any manga chapter.
 2. Go to color/brightness settings and enable custom color filter.
 3. Adjust the colors to any value. The color of both the chapter and the image preview doesn't change.

**Other details:**
I am using a Samsung Galaxy s7 running android 8.

**Comment by inorichi** [comment]
You probably have the alpha channel to 0

**Comment by KingOfScorchers** [comment]
Fixed the problem, thanks.
