### ISSUE TITLE
[Feature Request] Favourite Artists Library

### ISSUE THREAD

**Issue by baraa272** [inorichi/tachiyomi#1636]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

0.7.4

**Issue/Request:**

Add a favourite artists category / library feature so it holds your favourite artists names and when click on an artist name 
Make a global search

**Comment by arkon** [comment]
You can search by artists now.
