### ISSUE TITLE
Cannot track some manga if it lay too deep in anilist search result

### ISSUE THREAD

**Issue by daoluong** [inorichi/tachiyomi#1638]
1. 0.7.4
 2. Cannot add Nichijiou to anilist 
 3. try to add Nichijiou to anilist  in tracking tab

**Other details:**

**Comment by Resshi** [comment]
Found it under "Nichijou - My Ordinary Life"

**Comment by daoluong** [comment]
How in the world "My Ordinary Life" come from?

**Comment by CarlosEsco** [comment]
Ask anilist
