### ISSUE TITLE
Page List Is Empty

### ISSUE THREAD

**Issue by MylesYoung22** [inorichi/tachiyomi#1640]
**App version:**
0.7.4

**Issue/Request:**
Page List Is Empty reoccurs when I try to read a downloaded chapter of a manga from mangasee. 

**Other details:**
I have cleared the cookies and cache for Tachiyomi. As well I have made sure the app is up to date and downloaded the latest extension for the app. I also have force closed the Tachiyomi app. After all this it still doesn't work and I am now unable to continue reading.

**Comment by CarlosEsco** [comment]
#1634

**Comment by CarlosEsco** [comment]
verify you are on extension 1.2.2 then try force closing again.

**Comment by MylesYoung22** [comment]
Yes I am on version 1.2.2 and have done what you stated at least 3 times again right now.

**Comment by MylesYoung22** [comment]
I made sure the extension for mangasee was 1.2.2 and tried force closing 3 times.
