### ISSUE TITLE
Anilist tracking issues for some Manga http 400

### ISSUE THREAD

**Issue by phanirithvij** [inorichi/tachiyomi#1644]
**App version:** 0.7.4

**Issue/Request:** Anilist tracking issues http 400 error

**Steps to reproduce (if applicable)**

 1. Open One piece or One Punch Man from any source
 2. Check whether the Anilist tracking works.

**Other details:**
Screenshots

[screenshot_20181004-102833](https://user-images.githubusercontent.com/29627898/46453742-b3439880-c7c0-11e8-94f2-2015c2f62b40.png)

[screenshot_20181004-102819](https://user-images.githubusercontent.com/29627898/46453752-bfc7f100-c7c0-11e8-9f25-3290e896399f.png)

**Comment by phanirithvij** [comment]
This issue might have already been reported but I couldn't find it.

**Comment by CarlosEsco** [comment]
Check again might have been a timing thing. I have no issue when verifying

**Comment by phanirithvij** [comment]
I'm still getting the error but only for One piece and One Punch Man
Other manga are working with the Anilist tracking

**Comment by CarlosEsco** [comment]
Try removing one piece tracking and re adding. To remove edit the tracker an delete the text and select ok

**Comment by phanirithvij** [comment]
I cannot add One Piece to anilist tracking.
I cannot remove it as I never actually added it.
I cannot re add if I haven't added before

## Look at the screenshot It's empty

![Screen](https://res.cloudinary.com/rootworld/image/fetch/c_scale,w_268/https://user-images.githubusercontent.com/29627898/46453742-b3439880-c7c0-11e8-94f2-2015c2f62b40.png)

**Comment by CarlosEsco** [comment]
Oh my bad that was kitsu. Hmm I'm out of ideas right now. I was able to add one piece no issue with anilist

**Comment by phanirithvij** [comment]
[Recorded Video](https://drive.google.com/open?id=1vqh96Hc4L4I2fjBOrx1DYejJWDZTvP9l)

**Comment by arkon** [comment]
Do you have One Piece added to your Anilist manga list already?

**Comment by phanirithvij** [comment]
No Please look at that beautiful screen SHOT :smile: :smile: :smile:

**Comment by phanirithvij** [comment]
Sorry I do

**Comment by arkon** [comment]
🤔

Anyway, try removing it and then doing it from Tachiyomi again.

**Comment by phanirithvij** [comment]
It worked thanks.

So the bug is it cannot update existing Anilist manga.

**Comment by arkon** [comment]
No, because it's always worked for me. Was there wondering weird about your existing entry?

**Comment by phanirithvij** [comment]
Nothing.
It was normal before I removed it

Status:
Reading 

Score:
97

Chapter Progress:
917

Now it's all zeroes and the status is READING

**Comment by lionirdeadman** [comment]
Anilist's been having issues recently with their APIs, I would guess it's most likely that since the code has been left unchanged between the moment it worked and the moment it didn't (now).

**Comment by CarlosEsco** [comment]
Do you still have this issue on 8.0?

**Comment by phanirithvij2000** [comment]
[screenshot_20181010-215032](https://user-images.githubusercontent.com/32328392/46751069-22e0e880-ccd7-11e8-8605-c8041057ab30.png)

![photo_2018-10-10_22-03-46](https://user-images.githubusercontent.com/32328392/46751506-6ab43f80-ccd8-11e8-88ec-2579e0377f0d.jpg)

**Comment by CarlosEsco** [comment]
K will look into later

**Comment by CarlosEsco** [comment]
@Flat  and I are unable to reproduce it.  Does this happen if you add a new manga to anilist, then try to add it to tachi?

**Comment by phanirithvij** [comment]
Even I'm not able to reproduce it.

It's working surprisingly.
If I add a new manga from Anilist and come back here and track.

But One punch man ( which I added the same way but 1year ago ) is still not
working.

I don't know the exact reason.
But I think the issue can be closed.

Thanks for everyone's time.

**Comment by CarlosEsco** [comment]
yea i would just remove the one punch and re add it again.
