### ISSUE TITLE
[Feature Request] Ability to search downloaded manga with tags

### ISSUE THREAD

**Issue by Amazingduf** [inorichi/tachiyomi#1645]
Is it possible to search the downloaded manga folder with tags ? Like trying Comedy and all the manga that I downloaded that have the Comedy tag appear

**Comment by thu2468** [comment]
Would be nice to search/filter genre in library that you added already. Pretty sure it possible as it looks like the app already store genre. So you could make it so that it get all unique genre naming and then make a list out of that.
