### ISSUE TITLE
[Issue] Mangasee Download Error

### ISSUE THREAD

**Issue by GhostPiggy** [inorichi/tachiyomi#1646]
App version: 0.7.4

Issue: When attempting to download from mangasee I get an error and this message: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference

**Steps to reproduce (if applicable)**

 1.Go to One Piece with Mangasee source
 2. Download chapter

Other details: I've attempted deleting the cookies and chapter cache, clearing database, as well as deleting and reinstalling the same stable version.

**Comment by CarlosEsco** [comment]
Download the extension. Then force close tachiyomi in your Android settings
