### ISSUE TITLE
[Feature request] Reader scrolling speed

### ISSUE THREAD

**Issue by lenisko** [inorichi/tachiyomi#1649]
Setting with scrolling speed multiplier on webtoon reader would be great. Sometimes stripes are too long to swipe them like crazy :)

**Comment by Amazingduf** [comment]
Yeah, that would be really helpful, also, please make the scrolling more smooth.

**Comment by hXtreme** [comment]
I was wondering if webtoons could have an auto-scroll feature.

**Comment by arkon** [comment]
Duplicate of #2785, which is clearer.
