### ISSUE TITLE
Tachiyomi doesn't recognize local manga stored on external SD card.

### ISSUE THREAD

**Issue by Atoli** [inorichi/tachiyomi#1651]
**App version:** 0.8.0
**Android Ver:** Kitkat 4.4.2

**Issue/Request:** 

In Android 4.4.2, you cannot access to local manga on SD card.

This works, since it's an internal storage:

Phone\Phone storage\Tachiyomi\Local\

I have tried many types of possible folder location on external SD card but none is recognized by tachiyomi:

Phone\SD card\Tachiyomi\Local
Phone\SD card\18F5-2C11\Tachiyomi\local
Phone\SD card\storage\Tachiyomi\Local

Of course, there are manga chapters inside each location, i also tried with CBZ manga pack files.

**Steps to reproduce (if applicable)**

 1. Get a phone with Android 4.4.2.
 2. Get an external SD card in the phone.
 3. Try to set a local manga folder in the external SD card, Tachiyomi won't recognize it.

**Other details:**

Local manga stored on an external SD card works fine on Android 5.1, but the roms i used were buggy and there are no other custom roms for my device so had to downgrade to 4.4.2.

**Comment by Atoli** [comment]
> Try with Phone\SD card\18F5-2C11\Android\data\eu.kanade.tachiyomi\local

Um...nope, doesn't work.

Tried with:

Phone\SD card\18F5-2C11\Android\data\eu.kanade.tachiyomi\local\Hataraku Saibou\Ch1

No chapter seen in my local manga.

**Comment by enwokoma** [comment]
Is your external storage an emulated storage from the phone storage (internal storage)?

**Comment by shimizurei** [comment]
How are your files stored? I had trouble with this as well. The only thing that worked for me was a folder with each individual chapter zipped.

```text
/sdcard/tachiyomi/local/Kono Oto Tomare/ch1.zip
/sdcard/tachiyomi/local/Kono Oto Tomare/ch2.zip
/sdcard/tachiyomi/local/Kono Oto Tomare/ch3.zip
```

The following formats failed for me:

```
/sdcard/tachiyomi/local/Kono Oto Tomare.zip/ch1
/sdcard/tachiyomi/local/Kono Oto Tomare.zip/page1.jpg
/sdcard/tachiyomi/local/Kono Oto Tomare.zip/Kono Oto Tomare/page1.jpg
/sdcard/tachiyomi/local/Kono Oto Tomare.zip/Kono Oto Tomare/ch1
```

Hope this helps.

**Comment by bbtora** [comment]
@shimizurei Yes, that's how it works.

/sdcard/tachiyomi/local/`manga_title_folder`/`chapter_zip`
or
/sdcard/tachiyomi/local/`manga_title_folder`/`chapter_folder`/`.png`\`.jpg`
