### ISSUE TITLE
Remove metadata section from in between chapters.

### ISSUE THREAD

**Issue by LalitSinghRana** [inorichi/tachiyomi#1653]
With update 8.0, when one goes to next chapter there comes a section which tells about previous chapter and next chapter.

It isn't really needed there and disturb the reading experience.

**Comment by inorichi** [comment]
It might seem not needed, but it has more uses besides showing you chapter titles. It shows a loading progress if the next chapter isn't loaded yet or a retry button if it fails.

Previously if the next chapter couldn't load you'd reach the end of the chapter and didn't have any feedback of what was going on. Furthermore, it's also used to know when to load the previous chapter.

**Comment by Sparh4wk** [comment]
so can you please make it optional?

**Comment by inorichi** [comment]
No :disappointed:

**Comment by Tempest042** [comment]
Love your work but I would greatly appreciate if this feature was made optional.

**Comment by somedood0** [comment]
I would like to add that it is extremely annoying when reading single-page manga or 4koma. It breaks the flow from page to page.

**Comment by LinkSlayer64** [comment]
I would also like this made optional. I had no problems with the previous setup.

**Comment by k0rak0ra** [comment]
I'd also vote for removing the page (since it cant be made optional). Previous setup was fine, this feels like a really annoying and unneeded option.

**Comment by LinkSlayer64** [comment]
I was just thinking for a minute and an idea came to mind - would it be possible to disable/run a faster check/something the in-between page for series where the the next chapter is registered as "downloaded" - from my own issues, it breaks the flow with my downloaded chapters, whereas it's seems to be a feature more geared towards reading on the fly, because you want to make sure the next chapter begins to download.

**Comment by ooluyid2** [comment]
I back the option to disable it.

**Comment by Acoha** [comment]
I also want to this page to be optional, atleast for downloaded manga. I understand why it’s there: to show download progress for the next chapter but it is completely unnecessary for locally stored manga. It is especially annoying on low pages/daily manga. 

I hope you change your mind on this matter.

**Comment by Th3N3rdyGam3r** [comment]
I also agree that it should become optional for both downloaded manga and non-dowbloaded manga since it is rather annoying when reading 1-2 page manga or downloaded manga.

**Comment by rathus** [comment]
Came to post this as well, mostly reading 4-koma and other 1-page comics, and this screen is utterly annoying.  1 Page > Black Screen > 1 Page > Black Screen > 1 Page > Black Screen.   

You mention that it was added to show download progress or errors but in that case it should just skip itself with no transition speed or something when it's not needed then, because right now it's annoying 99% of the time to fix the 1% chance there's a problem.

Reverted to 0.74 for now though.

**Comment by LinkCable** [comment]
Just to expand as to why @inorichi said no, it currently isn't possible to take it out due to the infrastructure of how this new feature of the reader was coded. We're evaluating how to tackle it the next release, be assured your voice has been heard.

**Comment by Tempest042** [comment]
Thankyou

**Comment by Llaurence** [comment]
You can tell the user something has gone wrong with a "snackbar":

https://developer.android.com/training/snackbar/

![snackbar_drive2](https://user-images.githubusercontent.com/40535137/47614314-0fcf6600-da96-11e8-8714-9ff486de5d08.png)

**Comment by ntdtara** [comment]
I don't understand how you can complain about something that is free

**Comment by Niaomh** [comment]
Great app, but I do feel like this feature takes away from the reading experience and can be jarring when I'm trying to really get into something. I hope that some way to disable it will be added.

**Comment by j2ghz** [comment]
I still think this feature should stay, but if it can't be optional and has to be removed, could it at least stay for webtoon as it's much smaller there?

**Comment by themagicalyang** [comment]
Hopefully this won't be removed entirely. There is a fair number of us who actually make some use of that page. It serves as a chapter differentiation marker and also to know like if the next chapter is a special or extra or whatever. Not to mention, it is like a register in the back of your mind saying chapter ended. And your are at this count. I get the request from the comments above but hopefully if at all this is taken up, atleast it will be kept toggleable.

**Comment by metroid112** [comment]
I'm with the 2 comments above. I'd prefer if it was a toggleable thing, for the reasons also said above and plus for myself I actually use it to stop myself from binging past chapters I don't have downloaded since I use Tachi exclusively on downloaded stuff without using data.

**Comment by LilyIsDead** [comment]
I'd like to toggle this feature off for specific series'. There are some manga that have one page chapters, and it's unnecessary to see the next/prev chapter screen between every page.

**Comment by 7sevenseven** [comment]
This page is unuseful to me.I seldom use this page.Instead of it,want to see the next chapter.
The page number can tell someone the end of the chapter.The loading progress can exist in the number 1 page of the next chapter.

**Comment by XenHat** [comment]
Also chiming in to say I've never experienced a situation where that screen was useful to me. It only breaks reading experience, and completely destroys the purpose of vertical mode. Please make it optional on a global basis. I also download most of my tracked manga so there's not much that can go wrong there.

**Comment by CapnCranch** [comment]
For me i dont really mind it. I most use it to know if im loading the next chapter on one page manga. That way i dont accidently have it delete that downloaded chapter. Though being able to turn it off for individual manga and or all together may be nice.

**Comment by UWNG99** [comment]
I come from another thread in which they directed me here. I also think keeping it optional would be a great idea

**Comment by XenHat** [comment]
Yeah, optional of course should anyone need it, but I would definitely turn it off.

**Comment by VenomMage** [comment]
Please don't remove this feature. I find it very useful.

**Comment by CarlosEsco** [comment]
There are no plans Currently to remove.  Unless someone wants to find an alternative way and opens pull request to solve the problem that this page provides a solution for

**Comment by clem193** [comment]
EH branch provided a solution for this problem a year ago already. He made the feature toggle-able.
(there https://github.com/NerdNumber9/TachiyomiEH/commit/8e9087226ff292f3a1f6a0a5ce83ab3dbb60af39 don't know if he modified how it work since that commit tho)
I'm using it since a year already (with ~2 - 3h of read everyday) and there is literaly 0 issues about it, except with weebtoon style reader sometimes you still see a tiny black space between chapters, but that's as far as "issues" goes (And I tried with pre-downloaded chapters, non downloaded chapters, good internet, shitty slow or even dying internet etc...)

**Comment by arkon** [comment]
He's stated in the past that his implementation was very hacky. If there's a clean way of implementing it, I'd be happy to accept a PR from whoever has bandwidth to look at this.

**Comment by joseph619** [comment]
New PR by morcefaster might solve this, I guess?

**Comment by CarlosEsco** [comment]
@joseph619 it only conditionally hides it which it most scenarios should hide it

**Comment by CarlosEsco** [comment]
latest dev has a toggle to only show when its needed.
