### ISSUE TITLE
MAL login error

### ISSUE THREAD

**Issue by hemlok89** [inorichi/tachiyomi#1654]
**App version:** 0.7.4

**Issue/Request:** MAL login issue/KissManga not showing anything

**Steps to reproduce (if applicable)**

 1. Trying to login to Myanimelist produces an unknown error/login failed.
 2. Clicking on browse next to Kissmanga shows no result found
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
There is already an issue open for mal. Their API is down for foreseeable future. As for kissmanga there is a workaround fix it extensions repository. Look for kissmanga issue
