### ISSUE TITLE
Crashes everytime when I try to open a chapter

### ISSUE THREAD

**Issue by ForgetfulJones** [inorichi/tachiyomi#1655]
**App version:**
r1429 through r1448

**Issue/Request:**
On Motorola Xoom wingray 4.4.4 (2.6.39.4/CyanogenMod 11.20150725
Been using release .74. When I attempted to upgrade to .80 today, it crashed upon attempting to open a chapter, downloaded or otherwise.  So I went back to find the earliest one that crashes which is r1429.

**Steps to reproduce (if applicable)**

 1. Just try to open a chapter.

Crashes even on a fresh install with the cache, settings, and library folder wiped.
 
~~edit: attached filtered copy of catlog.~~ (added tombstone instead)
edit 2: I've modeled .80 in both x86 & arm versions of avd/kitkat, and it still crashes in arm.

**Comment by ForgetfulJones** [comment]
Here's a tombstone I created by compiling & running an fdroid-debug version.  
[tachifdroiddebug.zip](https://github.com/inorichi/tachiyomi/files/2480400/tachifdroiddebug.zip)

**Comment by ForgetfulJones** [comment]
Version 1460 still crashing instantly when I try to read any manga.  Here's a new tombstone:
[tachiyomi1460.txt](https://github.com/inorichi/tachiyomi/files/2626409/tachiyomi1460.txt)

**Comment by CarlosEsco** [comment]
@inorichi

**Comment by ForgetfulJones** [comment]
Adding 'armeabi' let tachiyomi run and view properly in AVD/arm, but still crashes on my tablet ([tachiyomi_1460armeabi.txt](https://github.com/inorichi/tachiyomi/files/2627744/tachiyomi_1460armeabi.txt)) in the same place as all along: #00  pc 0000d1a2  /data/app-lib/eu.kanade.tachiyomi.debug-1/libimage.so (plain_init+1).

I had to alter the imported project in that I had to change devDebug to minsdk 19 from 21, if that makes any difference.

when I check the cpu on the tablet, it's definitely listed as ARMv7 Processor rev 0 (v7l)

**Comment by arkon** [comment]
Is this still an issue? Seems pretty device specific.

**Comment by ForgetfulJones** [comment]
Wow, I just happened to look back based on convo on discord.

Yes, it never stopped being an issue, inasmuch as it still doesn't work on my xoom, but I didn't really expect it to be fixed after inorichi lost interest back in nov '18.  I just got a newer tablet and moved on.

Since 4 is being dropped, might as well close it?
