### ISSUE TITLE
[Feature Request] Custom Playlist Creation for Western Comic Crossovers

### ISSUE THREAD

**Issue by the-fab-freak** [inorichi/tachiyomi#1656]
Many Western comics, especially DC and Marvel, have crossover story arcs that contain chapters from multiple series. The ability to make a custom playlist consisting of chapters from multiple series would alleviate the inconvenience of having to back out to the library, find the series the next chapter is in, and then find the appropriate chapter of that series. The ability to import and export these playlists would allow users to create and share custom reading orders as well, ideal for finding and sharing specific writer/artist runs.

**Comment by pervertkirito** [comment]
You can use [Local manga](https://github.com/inorichi/tachiyomi/wiki/Local-manga) for that
