### ISSUE TITLE
Local manga pages from rar archives load very slowly

### ISSUE THREAD

**Issue by Acoha** [inorichi/tachiyomi#1667]
Manga archived into .rar files are loading extremely slowly compared to .zip files now. It is really noticeable in higher resolution pages especially. Zip 2.0 archives load instantly. 

Some more info:
Samsung tab S (SM-T800)
A 1280x1920 page in .rar 4.x takes on average 6 seconds to load.
Negligible speed change on internal memory/sd card

**Comment by inorichi** [comment]
The only available .rar implementation only allows decoding file by file. If possible, I'd recommend you to use .zip because it doesn't have that limitation.

**Comment by Mkilbride** [comment]
Getting something similar here with CBR files. Slow loading. Also, the wiki page for Tachiyomi recommends .rar files for speed, so it's odd to see this here.

**Comment by bbtora** [comment]
@Mkilbride 
> Getting something similar here with CBR files. Slow loading. Also, the wiki page for Tachiyomi recommends .rar files for speed, so it's odd to see this here.

On the Local manga wiki page:
`Supported chapter formats are directories with pictures inside, ZIP/CBZ, RAR/CBR and EPUB. But expect better performance with directories and ZIP/CBZ.`

**Comment by arkon** [comment]
CBR files are just RAR files.

I don't think this will ever be improved, unfortunately.
