### ISSUE TITLE
Covers for manga in Library not showing up 

### ISSUE THREAD

**Issue by Guilty-King** [inorichi/tachiyomi#1673]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0

**Issue/Request:**
Covers for bookmarked manga are blank 

**Steps to reproduce (if applicable)**

 1. Bookmark any manga 
 2. Go to library ( The manga will have cover as of now)
 3.close and reopen app (The cover will disappear)
![screenshot_20181020-021512_tachiyomi](https://user-images.githubusercontent.com/21334098/47243128-c4bab080-d40e-11e8-99e7-5253d2f065b8.jpg)

**Other details:**
I can see covers if I rotate from portrait to landscape 
Tired reinstalling app , refreshing chapters 
Phone: Samsung Galaxy S7 edge
Android 8.0

**Comment by CarlosEsco** [comment]
What source?  I am pretty sure this might be a source issue

**Comment by Guilty-King** [comment]
Got it fixed after updating extension

**Comment by Guilty-King** [comment]
Source Mangadex
I will move the issue to extension github

**Comment by CarlosEsco** [comment]
Update hour extension

**Comment by CarlosEsco** [comment]
Then clear cookies cache db

**Comment by CarlosEsco** [comment]
And swipe refresh in your library

**Comment by CarlosEsco** [comment]
Its working fine
