### ISSUE TITLE
[Feature Request] Fit to xx% width

### ISSUE THREAD

**Issue by fayumot** [inorichi/tachiyomi#1675]
I would like to request another scale type which is fit to xx% of the screen width. This would really make reading webtoons on tablets a lot more easier. Ideally the the percentage is variable but a ~50% and another ~35% option would probably good enough for both portrait and landscape mode viewing.

**Comment by LunarisDream** [comment]
Agree. I was introduced to Tachiyomi to solve my webtoon-viewing woes as other readers do not have a Webtoon viewing mode to stitch together images for vertical viewing. However, Webtoon mode in Tachiyomi defaults to Fit Width with no way to zoom out further, and on tablets it makes the images too large to view comfortably. Being able to zoom out in Webtoon mode would be absolutely fantastic.

**Comment by hXtreme** [comment]
I can try to work on this in near future but I'll need some help with the testing, as of now I can't test for tablets.

**Comment by dobbleg1000** [comment]
If anyone does decide to work on this I would be willing to test.

**Comment by asdkant** [comment]
+1 on willing to test, I also have a tablet (10.1 inch with high DPI) and I ended up using a different app for the vast majority of webtoon-formatted stuff.

**Comment by arkon** [comment]
Added via #2349
