### ISSUE TITLE
App crashing on launch

### ISSUE THREAD

**Issue by MichaelRLee** [inorichi/tachiyomi#1678]
**App version:** 0.8.0

**Issue/Request:** App crashes immediately on launch with "Tachiyomi has stopped" and "Tachiyomi keeps stopping" windows.  Crash first occurred during library update.

**Other details:** OnePlus 5 running Android Oreo

**Comment by inorichi** [comment]
Install the same version over, without uninstalling so that you don't lose your data.

**Comment by MichaelRLee** [comment]
Fixed the issue. Thanks

**Comment by Reraru** [comment]
If your app crashes after installing the Manhuaren extension, uninstall it. My app stopped crashing after I uninstalled it.

**Comment by ohamszy** [comment]
Reinstalling the same version didn't work for me

**Comment by ohamszy** [comment]
So I uninstalled some extensions and it stopped
