### ISSUE TITLE
[Feature] Allow individual item clears in download queue

### ISSUE THREAD

**Issue by squadz3** [inorichi/tachiyomi#1679]
Can you allow us to remove individual items in the download queue instead of just clearing all?

**Comment by Reraru** [comment]
Go to the manga you're downloading and select the chapters that are queued, delete the ones you want to delete it'll stop the download.

**Comment by emkayDauda** [comment]
Yeah, that works. But it'd still be a hassle clearing several chapters from different manga...

**Comment by arkon** [comment]
Added in fb897e37d1a0f68355bccbbfd22a91813906b5b5
