### ISSUE TITLE
[bug] Hide status bar leaves blank space

### ISSUE THREAD

**Issue by jedinat** [inorichi/tachiyomi#168]
I'm on a tablet (Lenovo tab 2 a10), Android 4.4.4

Other apps that hide the status bar have no issue: Perfect Viewer, MangaDLR, everything...

http://i.imgur.com/lZXHxYE.jpg
http://i.imgur.com/IXozxbW.jpg

---
Version: v0.1.3

**Comment by jedinat** [comment]
The issue persists with version 0.1.4

**Comment by inorichi** [comment]
Can you try debug version?

**Comment by jedinat** [comment]
Looks like the issue is gone in the debug version!
