### ISSUE TITLE
Slow Kitsu tracker search

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1680]
**App version:**
0.8.0-1448
**Issue/Request:**
Kitsu search has been really slow for me. While some entries gets results, some just don't and the progress circle keeps revolving even though I've been searching a fairly old manga.
For Examples: **Vinland Saga** or **Gokufushudou**.

**Comment by INSANEMODE** [comment]
huh, i started tracking Gokufushudou in 1438 just fine, but i can confirm it does load forever if i try to search for it in 1448. 

doing a little more drunken testing, it doesn't load if you type "gok" or "goi" or "goa" or "goz".  all other letters work fine or show no results like they are supposed to.

  and if i change one of the previous letters like "kok" it does load. and vinland saga loads if you start typing it in, but loads infinitly once you get to "vinlan" typing "vinland" doesn't work, but if you misspell it after it starts loading infinitly, it will show up. like "vinlane" or "vineland" will make vinland saga show up.

strange stuff.
