### ISSUE TITLE
Local Manga Failed Chapter Images

### ISSUE THREAD

**Issue by RatchetNine76** [inorichi/tachiyomi#1682]
App version: 0.8.0

Issue:
I downlaoded new manga in local source, saved in sd card, I followed the instructions correctly and has done this in 0.7.1 4 times. When I view it in local source, it will have a blank cover and have all failed images, no matter what I changed in image decoder.Please help or fix this problem

**Comment by Flat** [comment]
What is the full path you are using and file types?

**Comment by RatchetNine76** [comment]
nevermind, there were weird error in making zip file. thanks anyway
