### ISSUE TITLE
Every Page is zoomed in on the center

### ISSUE THREAD

**Issue by darksoul2069** [inorichi/tachiyomi#1684]
**App version:** Latest

**Issue/Request:** Zoomed in after every Page

When am using smart fit or fit width and when i swipe to next page, the page starts from middle (zoomed to middle) like i won't see the first top panel of the manga page
I am using fit height as of now but is there a better solution?
Cuz i like fit width more and i want it to start from the top of the page when i swipe to the next page

**Comment by CarlosEsco** [comment]
Dupe #1661
