### ISSUE TITLE
[Feature Request] Passcode Lock

### ISSUE THREAD

**Issue by grravity** [inorichi/tachiyomi#1686]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0

**Issue/Request:**
(Feature Request): Please Implement a passcode lock onto the app. It would be highly appreciated.

**Steps to reproduce (if applicable)**

 1. x
 2. x
 3. x

**Other details:**

**Comment by metroid112** [comment]
There's Android apps that already do this for you, which on a short Google search, I found this popular one called AppLock

**Comment by Z3ROGRAV1TYx** [comment]
I've tried multitudes of these apps, and they are all very incosistent. I find they constantly bug out or sometimes I can get into an app without having to type a passcode. Also it uses access resources which can slow down people who don't have the best hardware. 

 It would be more beneficial and more secure to implement it on the app end, which shouldn't be very difficult to do. (Unless you want to implement total app encryption which isn't really necessary). But a simple swipe/pin lock for the app. Other apps such as EHViewer have this implemented and is a nice extra measure of security and privacy.

**Comment by CarlosEsco** [comment]
I can understand privacy but there is no security issue

**Comment by Z3ROGRAV1TYx** [comment]
Sorry, misword I didn't mean security in that sense. I just meant privacy.

**Comment by arkon** [comment]
This seems out of scope. I can understand it being in the EH version, but it doesn't really fit this app.

**Comment by metroid112** [comment]
Well, you can read some manga you might not want other people to see in this app just like EH.

**Comment by Flat** [comment]
Android has a lock screen. I agree this seems out of scope.

**Comment by Z3ROGRAV1TYx** [comment]
Not trying to be a pain about it.. But I understand if we were talking about something like putting a passcode on Youtube, a Calculator, Spotify, etc. 

But the fact that Tachiyomi has the ability to display nsfw stuff, and there are people who use it out there for that as well, I believe a simple passcode is a worthy use of time. And it's not like everyone has to use it, it will obviously be able to be disabled. But it's there for people who want it to allow them to have peace of mind.

**Comment by inorichi** [comment]
I might include a fingerprint lock for 1.x, but I don't think I'll add pin/passcode.

**Comment by hXtreme** [comment]
I totally agree with @Aminel, multi-user system should be the ideal solution for a shared tablet.

**Comment by Mystique0414** [comment]
Hey guys, I have my concern regarding the fingerprint lock. There are some android phones that does not have a fingerprint detector or something 😅 but I agree with the passcode request, but for/from the requestor of passcode the app has categorized library then if you don't people to be seen the hentai/horror genre you can categorized them in one library or two but arrange them at the end so when you will open your app it will not the first thing to pop out or be seen 😅 just my suggestion 😅😊
