### ISSUE TITLE
[Bug]Failed to decode image

### ISSUE THREAD

**Issue by Pavkazzz** [inorichi/tachiyomi#1687]
**App version:**
0.8.0 and r1454

**Issue:**
Failed to decode image

**Steps to reproduce (if applicable)**
Reproducible on few russian sources: 
Readmanga, mangachan, mangahub, libmanga(mangalib)
Manga name: The World Where I Belong 

 1. Open source
 2. Find manga
 3. Open chapter 6, page 2

**Other details:**
Work from mobile browser

![screenshot_from_app](https://user-images.githubusercontent.com/3702034/47623926-984a1700-db27-11e8-9b67-462a02e5a76f.jpg)
Link for browser:  http://readmanga.me/the_world_where_i_belong/vol1/6?mtr=#page=1

**Comment by arkon** [comment]
Decoders have changed since Nov 2018, so just going to close this.
