### ISSUE TITLE
[Feature Request]: Samsung S Pen support

### ISSUE THREAD

**Issue by Vandyy** [inorichi/tachiyomi#1688]
**App version: 0.8.0

**Issue/Request: Request is to add the ability to navigate using the Samsung S Pen.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
The Note 9 Samsung S Pen has a button that you can customise based on the app in use. Would love to see it implemented that: One click of S Pen button-> Next page, Double Click S Pen Button -> Previous Page. This would allow users to use the S Pen as a manga reading remote.

**Comment by Flat** [comment]
I find it interesting that apps need to specifically support the pen and you can't map the pen to Android actions or buttons. Here is the sdkhttps://developer.samsung.com/galaxy/spen-remote/documentation for adding it. 

Maybe in the next major version.

**Comment by CarlosEsco** [comment]
This was added but supports note 10+
