### ISSUE TITLE
[Feature Request] Prioritization of downloads

### ISSUE THREAD

**Issue by EZarnosky** [inorichi/tachiyomi#1691]
I normally have bunch of chapters in my download queue and inevitably a new chapter comes out that I'd like to get immediately. Is there any chance of adding a feature to allow a person to prioritize what chapters get downloaded first? As a side item it would also be nice to delete a chapter in the download queue rather that the series chapter list.

**Comment by coltaku** [comment]
This would be a much appreciated addition.

**Comment by arkon** [comment]
Added in fb897e37d1a0f68355bccbbfd22a91813906b5b5
