### ISSUE TITLE
Downloaded chapter count not showing in My Library

### ISSUE THREAD

**Issue by EZarnosky** [inorichi/tachiyomi#1692]
On release 0.8.0 it does not show the number of chapters downloaded on the series thumbnail in My Library. I also have the same issue in the dev release r1454.

Running on Android 7.1.1 Lenovo tablet.

**Comment by CarlosEsco** [comment]
Do you have it enabled?

**Comment by CarlosEsco** [comment]
On library page click filter button at top then click show download badge

**Comment by EZarnosky** [comment]
Thanks. I was looking under setings, not filters.
