### ISSUE TITLE
Not deleting chapter after read!

### ISSUE THREAD

**Issue by kowloonkamikaze** [inorichi/tachiyomi#1693]
App version: 0.8.0

Issue:
When reading the new chapters it is not deleting after read even when this option is selected in settings. 

It used to work but now not working, running on Samsung Galaxy Note 8.

**Other details:**
![screenshot_20181101-100751_tachiyomi](https://user-images.githubusercontent.com/44657482/47827431-445a5f00-ddc1-11e8-92e0-9f18b0bf9890.jpg)
![screenshot_20181101-102643_tachiyomi](https://user-images.githubusercontent.com/44657482/47827438-4a504000-ddc1-11e8-83ad-5284ddbc53c8.jpg)

**Comment by einstein95** [comment]
Do the downloaded files exist in the download folder?

**Comment by kowloonkamikaze** [comment]
No, I store in SD card but I've always done this and had no issues before.

**Comment by einstein95** [comment]
So the files that claim to be downloaded do not exist in the folder you specified to download manga into

**Comment by kowloonkamikaze** [comment]
The files exist in the specified download folder as I had new chapter today then double checked it was there but the problem still exists.

**Comment by CarlosEsco** [comment]
Don't think my pull request closed this.  but this problem doesnt exist anymore either
