### ISSUE TITLE
MyAnimeList Login Error

### ISSUE THREAD

**Issue by DeeJack** [inorichi/tachiyomi#1695]
**App version:** 0.8.0

**Issue/Request:** Login error MyAnimeList, it says "Errore sconosciuto" (Unknown error in English).
Username and password are correct

**Steps to reproduce (if applicable)**

 1. Options
 2. monitoring (or something like this)
 3. MyAnimeList login

**Other details:**

![inkedphoto_2018-11-01_21-33-59_li_moment](https://user-images.githubusercontent.com/20882533/47878386-71892a80-de1e-11e8-8f39-3bb0fc07034e.jpg)

**Comment by CarlosEsco** [comment]
Mal api is still down see other open issue
