### ISSUE TITLE
[Bug] Description hidden when there are too many genre tags, scroll is also missing

### ISSUE THREAD

**Issue by haivp3010** [inorichi/tachiyomi#1699]
**App version:** r1454

**Issue/Request:** 
1. The description text is hidden because there are too many tags. Even the title **Description** itself is overlapped.
2. The genre tags area is not scrollable. In the image below, there are still missing genres that cannot be shown/scrolled to.

![image](https://user-images.githubusercontent.com/7151454/47947219-fa04e980-df4a-11e8-8f80-5c212f7fe8b2.png)

The above problems occur only in portrait mode. How about moving the TagGroup view into the NestedScrollView containing the manga summary, so that we can achieve something like this?

![image](https://i.imgur.com/5nstugW.gif)

**Comment by arkon** [comment]
I think the part with the manga info (cover, title, etc.) should just scroll too.

**Comment by arkon** [comment]
UI in this view was changed recently.
