### ISSUE TITLE
[Issue] MangaHasu latest updated manga chapter/s can only load 1 page

### ISSUE THREAD

**Issue by aestopian** [inorichi/tachiyomi#1701]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0
**Issue/Request:**
MangaHasu latest updated chapter/s can only load up to 1 page
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
I've tried reloading the next pages multiple times but it wouldn't, tried downloading still the same result. Please fix it.

Lenovo Tab3 8

**Comment by aestopian** [comment]
Screenshots
![screenshot_20181104-155907](https://user-images.githubusercontent.com/43212375/47961683-b4c7e100-e04a-11e8-9891-162918780b0b.png)
![screenshot_20181104-155839](https://user-images.githubusercontent.com/43212375/47961687-babdc200-e04a-11e8-8513-05e395102589.png)

**Comment by aestopian** [comment]
Tried downloading the dev version hoping the problem will be fixed but it wasn't.

**Comment by einstein95** [comment]
Solved by clearing cache and cookies before opening a chapter. Seems to be an issue with Cloudflare?

**Comment by aestopian** [comment]
Tried but still didn't work, wiping the cache and cookies, uninstalling tachiyomi then install again, uninstalling mangahasu's extension then installing it back again.

**Comment by CarlosEsco** [comment]
Wrong repository
