### ISSUE TITLE
Takchiyomi ripoff

### ISSUE THREAD

**Issue by Mihai-MCW** [inorichi/tachiyomi#1702]
Someone on GooglePlay put up a ripoff of this app called "MangaKa". Not only that it's basically the same app (without extensions I think), but it uses ads to make money with it. The publisher name is Vlipee.

**Comment by einstein95** [comment]
Known about, all that can be done is report the app to Google.

**Comment by Mihai-MCW** [comment]
I hope more people find out about this and report it... I dislike it when people are stealing someone's work and are taking the merits for it.

**Comment by metroid112** [comment]
Not only taking merits, but also placing ads? Seriously...

I'll be reporting the app and I hope Google does something, I'm sure the Apache 2.0 license should be protecting stuff like this.

**Comment by AmineI** [comment]
So how would you report it ? As a "copycat or other impersonation" or "other objection" 🤔 ?

**Comment by DarkChowder** [comment]
Not a lawyer, but from what I understand the license allows it.
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by einstein95** [comment]
They have not included the full license in the app nor have stated all the changes made.

If you can't report the app, then leave a review saying that they have ripped off Tachiyomi and are in breach of the Apache 2.0 license for these reasons. While they can freely profit off Tachi, they can't not admit that the app is 90% Tachiyomi.

**Comment by DarkChowder** [comment]
They need to attribute Tachiyomi somewhere, and include a link to the license in the app, but they don’t need to do anything else, because they are not distributing the source code. https://opensource.stackexchange.com/a/2788

**Comment by Fordi** [comment]
The only recourse would be to release an android app of Tachiyomi without the ads.  Burn their revenue.

**Comment by Mihai-MCW** [comment]
I think this is the place to research how to report it. But from my understanding it must be the owner.

https://support.google.com/googleplay/android-developer/answer/1085703?hl=en

**Comment by inorichi** [comment]
This is not the first time it happens, in fact, there are a few more in the play store. I usually ignore them, except the time when one guy uploaded it as Tachiyomi (same app name, same logo, but with ads).

If you want to report them, feel free to do so. Breaching the Apache 2 license isn't the only way to take it down; access to copyrighted and adult content is usually enough.
