### ISSUE TITLE
Sorting problems when choosing 'Latest Update'

### ISSUE THREAD

**Issue by Xykros** [inorichi/tachiyomi#1705]
App version: 0.8.0
Issue: When I choose to sort manga on 'Latest Update' order, my library gets sorted all over the place.

Steps to reproduce:
 1. Reinstall Tachiyomi
 2. Restore a backup

OR

1.  Go to Settings then Advanced section
2. Choose 'Clear chapter cache', 'Clear cookies', 'Clear database', 'Refresh library metadata', and finally 'Refresh tracking metadata'
3. Refresh Library Updates

Other details:
As the steps above suggest, I was clearing Tachiyomi's data through the app because for some reason, I've already deleted the downloaded folder manually (through file explorer) but the apps still says that I have downloaded chapters for my manga. While doing step 2 (Choose 'Clear chapter cache', 'Clear cookies', 'Clear database', 'Refresh library metadata', and finally 'Refresh tracking metadata') did work, as soon as I refreshed updates, my library went awry.

I tried reinstalling the app and deleting all files associated with Tachiyomi (aside from my backups) then recovering the backup, but it still yields the same result.

I will provide screenshots if necessary.

**Comment by inorichi** [comment]
Backups don't store last update information. That data will be built over time.

**Comment by hXtreme** [comment]
@inorichi can we close this? Or are you planning to add last update information to database for 1.x?

**Comment by Xykros** [comment]
Sorry about that. Will close now.
