### ISSUE TITLE
There's an error in downloading a manga

### ISSUE THREAD

**Issue by incstll** [inorichi/tachiyomi#1706]
App version:
v8.0

Issue/Request:
There's an error in downloading a manga. I'm having trouble in downloading manga, it only starts in 1 (like 1/20) then error occurs.

Android Version: 4.1.2

**Comment by Vesnyx** [comment]
First, is the issue still occurring?

Second, you're gonna have to be a lot more specific then that for us to be able to help. Which source were you using (Kissmanga, Mangadex, etc.)? What manga were you trying to download? Were you having any trouble with other manga from the same site?
