### ISSUE TITLE
[Feature Request] Different reader settings for series

### ISSUE THREAD

**Issue by taksaru** [inorichi/tachiyomi#1707]
**App version:**

latest

**Issue/Request:**

Allow users to set certain series to a vertical reader as many read both webtoons and manga using tachiyomi. An JSON Boolean could probably be used, although that idea is purely based on the structure of backups.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

Even if you don't want to do this keep up the good work your app is amazing

**Comment by sud7535** [comment]
It already exists.


On 7 November 2018 2:44:17 PM Tak Saruwatari <notifications@github.com> wrote:

App version:

latest

Issue/Request:

Allow users to set certain series to a vertical reader as many read both webtoons and manga using tachiyomi. An JSON Boolean could probably be used, although that idea is purely based on the structure of backups.

Steps to reproduce (if applicable)

  1.
  2.
  3.

Other details:

Even if you don't want to do this keep up the good work your app is amazing
