### ISSUE TITLE
[Feature Request] Different Cover source for different manga source

### ISSUE THREAD

**Issue by sud7535** [inorichi/tachiyomi#1708]
App Version: 

0.8.0

Request:

I prefer some sources over other for mangas due to various factors like complete scanlations and lesser watermarks. But these sources do not keep their cover thumbnail updated with latest volume cover page, while the other sources do. Is it possible to add an option to change the source of thumbnail in the library (Just thumbnail or metadata, not the source), so to make library look more neat and fresh?

**Comment by PmMenekosThx** [comment]
If you long press on any page while you're reading you'll get the option to set that page as the cover for that source.

**Comment by sud7535** [comment]
@PmMeNekosThx Didn't know that, Thanks!! Not what I was looking for, but still good.

**Comment by inorichi** [comment]
If you long tap a manga in the library, you have an option in the toolbar to select any image as the cover.
