### ISSUE TITLE
Tracking settings: how do I add an MAL account that was created through G+ or Facebook?

### ISSUE THREAD

**Issue by Flamingpineapplepie** [inorichi/tachiyomi#1718]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
7-8
**Issue/Request:**
Issue
**Steps to reproduce (if applicable)**

 1.open settings and go to tracking
 2.enter user details for Facebook or G+ MAL account 
 3.login error

**Other details:**
Am I doing this wrong? I added a username and password to the account. Must I create a new account?

**Comment by Flat** [comment]
Duplicate #1430

MAL API is down and will not likely be back soon. A work around may be available in the future however don't get your hopes up.

**Comment by arkon** [comment]
As @Flat mentioned, MAL support is actually not working at all right now.

However, your particular issue wouldn't be fixed anyway -- we don't support logging in via the third party social networks.

**Comment by Flamingpineapplepie** [comment]
Epic. Thanks for the info.
