### ISSUE TITLE
Getting Gradle Sync Errors while trying to compile

### ISSUE THREAD

**Issue by dragneelfps** [inorichi/tachiyomi#1721]
**App version: 0.8.0**

**Issue: Getting Gradle Sync Errors while trying to compile**

**Steps to reproduce**

 1. Clone
 2. Try a gradle sync

**Other details:**
I cloned this repo on my pc. But it is failing with this error in Gradle Sync:
`Failed to resolve: firebase-iid`
`Open File`
`Failed to resolve: firebase-common`
`Open File`
`Failed to resolve: play-services-tasks-license`
`Open File`

To fix this I had to move the `jcenter()' to the end of the repository list like this 

`repositories {`
`        google()`
`        jcenter()`
`    }`
`repositories {`
`        google()`
`        maven { url "https://jitpack.io" }`
`        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`
`        jcenter()`
`    }`

Before `jcenter()` was at the top of the list.
Can someone help me on this one? Why is the list in wrong order in the repository if it is giving this error? Or is it just me who is getting this error? If it is just me, then what should I do, other than rearranging the order?

**Comment by wopian** [comment]
There is an open PR for this in #1728
