### ISSUE TITLE
"Loader not implemented" Issue

### ISSUE THREAD

**Issue by ultimateseme** [inorichi/tachiyomi#1723]
App version: 0.8.0

Issue/Request: Everytime I try to open up a chapter, a message pops up saying "loader is not implemented".

**Comment by CarlosEsco** [comment]
Did you restore from a backup uninstall an extension?  If so you need to install the extension for that manga

**Comment by inorichi** [comment]
Yes, it looks like you don't have the extension installed. If the source shows a number on the manga info screen, you're missing the extension.
