### ISSUE TITLE
HTTP error 502

### ISSUE THREAD

**Issue by Mactroiy** [inorichi/tachiyomi#1725]
loDO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository https://github.com/inorichi/tachiyomi-extensions/

For all other requests Please fill out the form below and remove the first 3 lines of this template

App version:
8.0
Issue/Request:
I get an HTTP error 502
Steps to reproduce (if applicable)

1.I opened a chapter from the manga called demon spirt seed, then it shows a white screen and the loading circle for about 15 seconds and then it backs out to the chapter selection page and at the bottom in a white box it says error 502
2. I also tried restoring a backup and after it finshed processing it said there were 9 errors and when i checked the log each of the manga had HTTP error 502 beside them

**Comment by ChrisJAllan** [comment]
Sounds like an extension issue. Say what catalogue the manga are from and put the issue in https://github.com/inorichi/tachiyomi-extensions/

**Comment by Mactroiy** [comment]
Ok thanks
