### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#173]
How can i make the default order for chapters be ascending instead of descending?

---
Version: v0.1.4

**Comment by j2ghz** [comment]
I don't think you can.

**Comment by inorichi** [comment]
It's not possible, and I don't want to overload the settings with every minor configuration. Invert the list once and it will stay like that.

**Comment by shogunreaper** [comment]
overload the settings? Nonsense, more options is always a good thing.

and no it doesn't stay like that, it resets everytime i open the app again.

**Comment by inorichi** [comment]
I don't agree with "the more the better", and I can't keep everybody happy. Filters are stored for each manga since v0.1.3, if you invert the list, the next time you open that manga it will restore the last used order.
