### ISSUE TITLE
Update tracking sites after finishing chapter instead of as a bulk after exiting reader

### ISSUE THREAD

**Issue by dhanjit** [inorichi/tachiyomi#1731]
**App version:** 0.8.0

**Request:** If I read chapter 1, 2, 3 then instead of setting chapter to 3 in the tracker, update it after finishing every chapter.

This is required for maintaining activity records in trackers such as Anilist.

**Comment by dhanjit** [comment]
This can be marked low priority, as the current workaround of exiting reading after chapter 1 only works fine as long as next exit is within 12 hours for anilist.

**Comment by moka491** [comment]
I looked into it. Easily doable by adding a second call to updateTrackLastChapterRead()
in ReaderPresenter::onPageSelected() inside the first if condition. Tested it and it works just fine.

I'll open a PR for it.
