### ISSUE TITLE
[Features Request] Add option to hide empty search results

### ISSUE THREAD

**Issue by Septolum** [inorichi/tachiyomi#1732]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0

**Issue/Request:**
Add an option that hides sources in the search and migration screens when they have no search results

**Steps to reproduce (if applicable)**
 1. Search for a manga that not all sources have
 2. Many with have a big card saying no results found
 3. When you have a lot of extensions installed especially, these cards take up a lot of space on the list, making it hard to find actual results

**Other details:**

**Comment by blackholeearth** [comment]
Maybe all start in condensed . With loading circle. İf mange exist . İnflate that site source other stay condensed or be gone if searc resulted in nothing

**Comment by metroid112** [comment]
I'm totally keen on this. I have a tons of extensions installed in case I search a manga that's not in my usual extensions, and it's a bit hard to scroll when doing a global search.

**Comment by arkon** [comment]
Nevermind, #2066 does fix this but it just hasn't be released in stable.
