### ISSUE TITLE
Long tapping the cover in catalog and selecting no category doesn’t add the manga to the default category

### ISSUE THREAD

**Issue by Jendrej** [inorichi/tachiyomi#1734]
**App version:** r1458

**Issue/Request:** When there are at least 2 custom categories, long tapping the manga cover in catalog does not add it to the default category (as expected) nor to any of the other categories.

**Steps to reproduce (if applicable)**

 1. Have 2 or more custom categories.
 2. Go to a catalog.
 3. Long tap a title.

**Other details:** The cover does get grayed out, but after exiting the catalog and going back, it turns not grayed out again – the title does not get added to the library.

**Comment by arkon** [comment]
Seems to work properly now.
