### ISSUE TITLE
Save chapters as .zip?

### ISSUE THREAD

**Issue by karehaqt** [inorichi/tachiyomi#1735]
Is this possible in the latest version or do I need to start using the beta version?  Or, is it planned/not planned?

**Comment by tidux** [comment]
Saving such files as .cbz instead of .zip would also allow easy export to other reader applications, like for an e-reader.

**Comment by toshiro9117** [comment]
saving chapters to zip saves same little space too...

**Comment by inorichi** [comment]
Duplicate of #918
