### ISSUE TITLE
Broken covers after restoring backup

### ISSUE THREAD

**Issue by ccrowles** [inorichi/tachiyomi#1736]
**App version:**
r1438

**Issue/Request:**
Many covers from my library are missing after restoring a backup on a new device, from various sources, apparently only the most recently updated ones. I've checked and all the other covers from the same catalogues are working, only the ones that are already in my library are broken. 

Other info:
Using a Xiaomi Mi Pad 4, Android 8.1.0

**Comment by Daiichii** [comment]
Recently downloaded Tachiyomi v0.8.0 & restored from a backup from Google Drive with the extension (MyReadingManga) downloaded. Tried refreshing metadata, clearing cache both in Tachiyomi & from phone but cover image are still missing. Also tried refreshing at each manga's Info tab, uninstalled & installed Tachiyomi again & closing/ opening the app. Is there another method to restoring the cover image other than not restoring the backup? TIA.

Using Asus_Z00LD, Android 6.0.1

**Comment by happywillow0** [comment]
While doing some further digging, this is an extension issue and should be specific to the extension in question. This general issue for the main app could be closed I think.
