### ISSUE TITLE
Tachiyomi Dev above versions 1454 has empty My Library and My Updates

### ISSUE THREAD

**Issue by melnation-com** [inorichi/tachiyomi#1738]
As if it was installed brand new on a new phone. I have Tachi dev versions 1454 and 1458 apks, if I install 1458 they're gone, if I install 1454 they're there again, I install 1458 they're gone again, and so on.

I have Android 4.4.4.

**Comment by melnation-com** [comment]
Based on the date when 1455 was released and the date of a commit, I think it has to do something with "Optimize library query", I think it ain't a coincidence I got a problem with My Library and the update was also about a change in the library.

Maybe I'll try that backup thing and restore in 1458, wish me luck!

**Comment by melnation-com** [comment]
OK I tried many things, even using restore with Titanium backup, Oh well, 1454 is fine then, it's newer than the stable one that was released on Oct 9, 2018 anyway,  which I think is 1448 if it was dev version.

**Comment by inorichi** [comment]
@melnation-com can you confirm?
