### ISSUE TITLE
[Features Request] Change source order on global search 

### ISSUE THREAD

**Issue by JosiasElias** [inorichi/tachiyomi#1739]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
r1458 (dev)
**Issue/Request:**
When doing a global search I'd like to set my most used sources on top.
Also, It seems the app searchs all sources at the same time, making the search on these priority sources slower, so if their search could have priority too it'd be nice
**Steps to reproduce (if applicable)**

 1.Do global search
 2.Lots of useless results in the way
 3.

**Other details:**
Feature request #1732 would help with the issue
I really like the condensed idea

**Comment by hXtreme** [comment]
Check out the pull request https://github.com/inorichi/tachiyomi/pull/1772
This should in theory fix your issue.

**Comment by AmineI** [comment]
> Check out the pull request #1772
> This should in theory fix your issue.

Sorry but I fail to see how the PR you mentioned is related, can you explain please :) ?

**Comment by hXtreme** [comment]
@Aminel that PR implements a prioritization mechanism for library updates. The exact mechanism to be used is also super easy to swap out.The one used in the PR is based on last update time and improves update time significantly. To satisfy this issue, one line of change and one ranking function is all that is required.

**Comment by AmineI** [comment]
Yeah, I got that correctly then - your PR helps for library updates, while @JosiasElias asked for global search - like he said "putting his most used sources on top" of the search results

**Comment by hXtreme** [comment]
@aminel if you look at the changes made by the PR in file app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt we would have to make the same corresponding change for the global search result and add one function call it source ranking to app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateRanker.kt (we should probably change the name of this file if we want to use it for things other than updater as well) 

Also, now this is where I made an error in my previous comment which may have made everything a bit confusing, that is, we'll actually have to provide a UI to be able to rank the sources (I mostly don't do ui so I kinda forgot that it exists. Sorry.)
