### ISSUE TITLE
Show number of pages

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#174]
Instead of the green "downloaded" text on the right side put the number of pages each chapter is.

---

Version: v0.1.4

**Comment by IceKreem** [comment]
It shows the page number when its downloading in the download queue. So it would probably make sense to show downloaded and then the number of pages :)

**Comment by shogunreaper** [comment]
or an option, either way if it shows the page number or downloaded it indicates its finished

**Comment by arkon** [comment]
This came up a couple times and it _is_ possible for downloaded stuff, but it feels a bit weird to have it only on some entries.
