### ISSUE TITLE
Backup did not work

### ISSUE THREAD

**Issue by matehuos** [inorichi/tachiyomi#1740]
App version: 0.8.0 stable

 I made a backup using the same version, but the backup is not working. I checked the backup file is just fine. Someone knows what can be?

[tachiyomi.zip](https://github.com/inorichi/tachiyomi/files/2593078/tachiyomi.zip)

**Comment by arkon** [comment]
What did the logs say?

**Comment by matehuos** [comment]
There is the log: [tachiyomi_restore (1).log](https://github.com/inorichi/tachiyomi/files/2593156/tachiyomi_restore.1.log)

**Comment by matehuos** [comment]
I "fixed" it. I was trying to restore without some manga fonts. 
It was my bad after all.
