### ISSUE TITLE
Manga rock not loading (also mangafox)

### ISSUE THREAD

**Issue by gazabi** [inorichi/tachiyomi#1741]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0
**Issue/Request:**
Gets an error when trying to load manga rock, heres a screenshot
[https://i.imgur.com/apfuj6t.jpg](url)

**Steps to reproduce (if applicable)**

 1.Just clicking the manga rock source (or manga from favorites sourced from mangarock gives same error)

**Other details:**

Mangafox has a similar issue with nothing showing up, but not the same error

**Comment by arkon** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/627 (which is already fixed).
