### ISSUE TITLE
Attempt to invoke virtual method com.hippo.unifile.Unifile

### ISSUE THREAD

**Issue by felipevdc1** [inorichi/tachiyomi#1742]
I'm trying to download the most recent chapters of red storm using readmanga today and mangafox, but both of them shows me this message...

**Comment by inorichi** [comment]
You're most probably out of free space.

**Comment by Samega7Cattac** [comment]
I'm having the same issue. 
It's says he's using 266Gb for User data but if I check the size of the folder it's only 5~6Gb of my 256Gb SD card.
U want some screenshots?

**Comment by CarlosEsco** [comment]
Attach screens please.

**Comment by Samega7Cattac** [comment]
and I checked the size of the folder on Windows
![folder_windows](https://user-images.githubusercontent.com/25128554/49905984-e14ff380-fe67-11e8-8cf2-12ba746ff827.png)
But my SD card only have 256GB wtf is happening here?!

**Comment by gigabytedevelopersinc** [comment]
Simple way to put it...
Your drives are corrupted.
A memory cleanup could help!

Warmest Regards,
Team Gigabyte Developers

**Comment by Samega7Cattac** [comment]
Nvm, I tried to use the build in SD card reader and my device died instantly I insert it.

**Comment by metroid112** [comment]
That's quite the corrupted folder, or maybe it's infested with some malware or something?

**Comment by Samega7Cattac** [comment]
The memory was corrupted and the device dead.
This error should only happen when u don't have enough space on the device.

**Comment by izogfif** [comment]
Same issue with manga 
`Otome Game no Hametsu Flag shika nai Akuyaku Reijou ni Tensei shite shimatta...`
(yes, this is the manga title). Page: https://loveheaven.net/manga-otome-game-no-hametsu-flag-shika-nai-akuyaku-reijou-ni-tensei-shite-shimatta-raw.html
I can browse it by clicking the chapter, though. So the link is not dead and the program actually knows how to obtain images from there.
"Destiny Lovers" manga from the same website downloads without problems. I think it might be the issue with the length, or the fact that the folder name ends with three dots.
The issue happens with latest Tachiyomi and latest RawLH extensions, installed on Memu 7.2.2, with the download folder saved as 
`c:\Users\username\Downloads\MEmu Download\tachiomi-download\RawLH (JA)\Otome Game no Hametsu Flag shika nai Akuyaku Reijou ni Tensei shite shimatta... - Raw\`
No issue with the physical Android device on version 0.8.5

**Comment by arkon** [comment]
There's an open issue about folder names that are too long on Android, but afaik dots are fine in Windows and the max subpath length is 255 char.
