### ISSUE TITLE
Feature Request: Add tachiyomi to play store

### ISSUE THREAD

**Issue by rumblpak** [inorichi/tachiyomi#1745]
**App version:** 0.8.0

**Issue/Request:** Add to play store

**Other details:** As a user of a chromebook, opting to use the developer mode to install tachiyomi, significantly reduces the number of apps that I can use. Having a version that is compliant with the play store would mean that I could avoid having to run in developer mode. I understand that there are limitations to what a play store version would have but those could be noted. With the number of manga apps currently in the play store, it is no longer a reason to not upload the app.

**Comment by rumblpak** [comment]
> 
> 
> Impossible because Tachiyomi violates ToS in three ways
> 
> Downloads APKs for the extensions, which isnt acceptable by Google
There is a precedent in other apps such as fbreader to have separate apps act as plugins for the main app
> 
> Hentai extensions violate the 18+ agreement
Don't have 18+ extensions by default in the play store version 
> 
> A lot of the websites used as extensions are extremely grey market
> 
> Unless you remove mangadex (because mangadex has a lot of hentai) and a lot of the extensions, it's not possible to have it on the gplay store, and I don't think that the devs would like maintaining two versions
I would argue that the grey market area is moot since all manga is really grey market. 

It wouldn't really be about maintaining two versions, it would be about having a version that just works for the masses that is available in the play store. It wouldn't be about maintaining two versions, more like having a logical separation for where the play store version feature set ends and extensions pick up.

**Comment by loocool2** [comment]
¯\_(ツ)_/¯ https://github.com/inorichi/tachiyomi/issues/1600 This one of the devs stance on it

**Comment by rumblpak** [comment]
> 
> 
> ¯\_(ツ)_/¯ #1600 This one of the devs stance on it

That's only if the app is acting as a download host, if it were to link the user to a play store app, it would be fine. The concern at the time was that manga apps were being taken down but the store is littered with them right now. Other than the current state of the app including 18+ content, I don't really see a reason why it couldn't go forward as a play store app. That and having the extensions in a non-apk format (which is arguably the most work) and allow for importing of said new extension format, would bypass any play store restriction, like what many iOS apps already do to bypass the insane apple restrictions.

**Comment by lionirdeadman** [comment]
You assume that extension developers would want to use Google to host their APKs. And with your "new format", all their work would have to be redone, the extension be redone.. Just for the possibility to be on the playstore.. That.. Would be a huge waste of time in my opinion.

I don't think price is an issue but it should still be mentioned because this does mean that Tachiyomi devs would pay to host the app.

(On a personal note, I don't like the idea of promoting Tachiyomi on the play store at all.)

**Comment by inorichi** [comment]
Sorry but I'm not going to deal with google play policies, nor dropping the apk system (in fact before the apk extensions arrived, I was using extensions with YAML files and they were very limited, so I won't invest any more time there.

I'm sure it would be taken down sooner or later, and I'm not going to risk a developer account for a fun/hobby project with no profit at all.
