### ISSUE TITLE
Every manga chapter I try to open leads to "page list is empty" while sending me back to the menu screen.

### ISSUE THREAD

**Issue by Pandoyo1** [inorichi/tachiyomi#1749]
**App version:**
0.8.0

**Issue/Request:**
Any chapter I open closes and goes back to the menu screen saying "page list is empty." I've tried opening chapters in all of my favorited manga, but everything has given me "page list is empty."

**Comment by CarlosEsco** [comment]
This is more than likely a source specific look at the extensions repo page verify the issue doesn't exist and then add issue there and provide what source you are using
