### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by bandithedoge** [inorichi/tachiyomi#1751]
Is it possible to import any PDF and have it in the library? I'd like to have some ebooks in the app since I like the interface and I want to have everything in one place.

**Comment by toshiro9117** [comment]
bumb

**Comment by CarlosEsco** [comment]
Bumping doesn't move this up just sends an annoying emails 😉. There are no plans for PDF support currently.

**Comment by inorichi** [comment]
No plans to support PDF.
