### ISSUE TITLE
[Feature Request] Make pages save in app instead of photo gallery

### ISSUE THREAD

**Issue by SethaWetha** [inorichi/tachiyomi#1752]
**App version:** 0.8.0
**Issue/Request:** Make pages save in app instead of photo gallery
**Additional Details:** I went to send a picture I took to someone and I saw my latest downloaded chapters in my photo gallery and got spoilers.

**Comment by CarlosEsco** [comment]
It does save in app. Some phones don't add a .nomedia file.  Just add that to the tachiyomi folder where the downloads are and it will fix it
