### ISSUE TITLE
Manga loading problem

### ISSUE THREAD

**Issue by GentlemanGamer94** [inorichi/tachiyomi#1753]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 8.0

**Issue/Request:** The app will no longer load any manga; gives me an error stating "Value Unknown Query Version at data of type Java.lang.string cannot be converted to JSONarray". Not sure why or how it's happening.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:** manga I'd previously downloaded works fine; just trying to load stuff from the network gives me grief.

**Comment by arkon** [comment]
MangaRock? Update the extension.

**Comment by GentlemanGamer94** [comment]
Just did so, and all works now; and here was ms thinking it was app related (was trying to access through my library, not through a catalogue). Thanks for the help.  :)
