### ISSUE TITLE
Updating manga doesn't update

### ISSUE THREAD

**Issue by peachyfawx** [inorichi/tachiyomi#1754]
**App version:**

0.8.0

**Issue/Request:**

When updating to check for new chapters the app returns nothing(as in no new chapters) . Has been doing this for little over a week now

**Steps to reproduce (if applicable)**

 1. Manually update
 2. Set an auto update
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
What source and please provide screen shots in app vs on website

**Comment by peachyfawx** [comment]
The source is mangafox

Here is the screenshots in an album
Screenshots https://imgur.com/a/3Evnr7P

It's not just mangafox though. Mangahere doesn't update either

**Comment by CarlosEsco** [comment]
Mangafox has known issues open in the GitHub repository. As for mangahere open an issue in GitHub repo and show some screenshots my quick look I didn't notice chapter mismatch
