### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by M2ck** [inorichi/tachiyomi#176]
Build log from F-Droid wiki:

https://f-droid.org/wiki/page/eu.kanade.tachiyomi/lastbuild_5

**Comment by inorichi** [comment]
I've talked with a mod and he said it's *probably* on their end. You will have to wait.

**Comment by inorichi** [comment]
It seems they fixed it.

**Comment by M2ck** [comment]
Yep fixed, update available.
