### ISSUE TITLE
[Request] Better error message when choosing locked entry in AniList tracker

### ISSUE THREAD

**Issue by awangn6600** [inorichi/tachiyomi#1761]
**App version: 0.8.0**

**Request: Better error message if an entry is locked in AniList tracking**

**Steps to reproduce (if applicable)**

 1. Find any locked entry in AniList (for example: https://anilist.co/manga/87399/unOrdinary/)
 2. Find that title in any available source inside Tachiyomi (the example is in Webtoon, so you will need Webtoon plugin), choose it
 3. Go to Tracking tab, tap Edit on the Title box, select matching entry. There will be a HTTP 403 error

**Other details:**
This error message is caused by a locked entry, in which user cannot add it to their list. The lock itself is caused by a user-submitted entry that doesn't meet AniList database entry guidelines.
There is an explanation in AniList, that a locked entry might be deleted by the staff. 
This error message is not helpful for user, maybe change it to "Entry locked. Cannot add to AniList" or something like that.

**Comment by arkon** [comment]
I've never come across a locked entry. If this is still problematic, please open a new issue with a working example.
