### ISSUE TITLE
[Feature request] Tracking volumes instead of chapters

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [inorichi/tachiyomi#1764]
Some manga formats are in volumes instead of chapters. Obviously, the volumes are incredibly of a much smaller value than chapters (e.g. 200+ chapters can be in volumes of only 20+, etc etc).

Now, I've tried finishing a volume and the value in Tracking didn't even update. Hoping this feature will be considered in a future version.

Tachiyomi version: 0.8.0

**Comment by metroid112** [comment]
What manga "format" is in volumes? I know there's a few manga out there that the translations have posted the entire volume as a chapter but besides that I don't know what is this thing you mention.

**Comment by eji30** [comment]
![Saint Seiya](https://i.imgur.com/5N6Klff.jpg)

**Comment by eji30** [comment]
![Saint Seiya volumes](https://i.imgur.com/G2waQ1M.jpg)

**Comment by eji30** [comment]
@metroid112
![Saint Seiya](https://i.imgur.com/59FOlMl.jpg)
![](https://i.imgur.com/IvGmCLL.jpg)

**Comment by metroid112** [comment]
Yeah it's not the manga's format per se (Saint Seiya like 99% of manga, released on a chapter by chapter basis), but rather a thing from the people that uploaded the chapter itself on the site (Translator or aggregator).

If you want to update volumes on MAL, there's already an issue for that at #505

**Comment by eji30** [comment]
@metroid112
I see. Thanks.

**Comment by arkon** [comment]
Duplicate of #505
