### ISSUE TITLE
[Feature Request] Dark mode: set background as black when enabled

### ISSUE THREAD

**Issue by ArmeF97** [inorichi/tachiyomi#1766]
![screenshot_20181211-105029_tachiyomi](https://user-images.githubusercontent.com/6240983/49792490-26bed480-fd33-11e8-82e4-f1d67dae0712.png)
See screenshot above. My request is that when dark mode is enabled, the loading screen must have a black background

**Comment by yambadr** [comment]
Tap the gear icon and change the background
![screenshot_20181211-123912_tachiyomi 2](https://user-images.githubusercontent.com/17810950/49795542-ebc49d00-fd42-11e8-91fb-4a27f40c6b6a.png)

**Comment by ArmeF97** [comment]
Thanks! Shouldn't it be default when in dark mode?

**Comment by null-dev** [comment]
No, because you can actually change it's default value in the application settings: `Settings > Reader > Background color`

**Comment by that-one** [comment]
Though it would be nice if there where three options: Theme, Black, White
The "Theme" option would take a color value from the theme, ofc. Haven't looked into the themes, so I don't know how hard it would be to implement.

**Comment by BarbaBlannk** [comment]
Maybe we can add a way to modify the theme, like in Telegram or even give the users a way to create themes.

**Comment by inorichi** [comment]
Closing since this is already possible.
