### ISSUE TITLE
Can't authorize Anilist

### ISSUE THREAD

**Issue by Luisdv93** [inorichi/tachiyomi#1768]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.0
**Issue/Request:**
Issue
**Steps to reproduce (if applicable)**

 1. Go to Settings > Tracking > Anilist
 2. Press on the authorize button
 3. Get an error but see the app authorized if I visit my settings in the website.

**Other details:**
I'm getting an error when I try to authorize tachiyomi to use my Anilist account, I already tried with 2 different browsers and a VPN without luck, I remember having the same problem before but I can't remember how I managed to fix it. 

I had my account already authorized but I changed the ROM of my phone so I had to reinstall.

**Comment by as280093** [comment]
Have tried clearing your Tachiyomi Data from settings 
Before doing that make a backup of Tachiyomi

**Comment by Luisdv93** [comment]
@as280093 Just tried this and I keep getting the same error. If I access my Anilist account I can see tachiyomi in the list of authorized apps but I'm not getting redirected to the app after the authorization.

1. Click on Anilist
2. Login sucessfully
3. Get to authorize screen and click on authorize button
4. Get the following error:

![image](https://user-images.githubusercontent.com/7731089/50446511-9b753f80-08eb-11e9-9666-aba466a7b53a.png)

And the url is trying to access looks like this: tachiyomi://anilist-auth#access_token=randomToken&token_type=Bearer&expires_in=31536000

**Comment by as280093** [comment]
https://mariusbancila.ro/blog/2015/09/17/fix-err_unknown_url_scheme-on-android-webview-for-telsmsgeoetc-links/

https://stackoverflow.com/questions/35442592/android-custom-url-scheme-refuses-to-work-how-to-navigate-back-to-android-app%C2%A0


it some code editing but dont know much so i think @inorichi so take a look in it

**Comment by as280093** [comment]
@Luisdv93  it could be best to use kitsu for now and backup from kitsu to anilist every week  or month

**Comment by Luisdv93** [comment]
@as280093 Managed to figure out it was the browser, I downloaded firefox and it worked correctly. Seems to be a problem with certain browsers.

**Comment by CarlosEsco** [comment]
Closing since issue was resolved
