### ISSUE TITLE
[Bug] Image Could not be loaded

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#177]
Sometimes i get an error for a page in a chapter saying

> Image could not be loaded.
> Try changing the image decoder

but when i change the decoder all it does is send me back to the first page in the chapter.

I even tried using the debug version but its the same.

---
Version: v0.1.4

**Comment by j2ghz** [comment]
Happens to me too, clearing cache and re-download helps, not always on the first try

**Comment by shogunreaper** [comment]
yeah... but its easier just to delete it and then reopen it so it grabs from the web.

really kind of a hassle, needs an image refresh button or something.
