### ISSUE TITLE
Can't add Working!! tracking, anilist

### ISSUE THREAD

**Issue by SonOfASelkie** [inorichi/tachiyomi#1771]
**App version:** r1461

**Issue/Request:** Working!! tracking not found with anilist

**Steps to reproduce (if applicable)**

 1. Add Working!! to library (not the spinoffs, main one of 252 chapters)
 2. Attempt to add Working!! anilist tracking
 3. Watch the infinite loading wheel

**Other details:**
I've had _no_ issues at all with tracking any other manga, just this one. I've tried shortening the title to see if I could get a couple, didn't work. I've removed and added working from the anilist website, doesn't work. I've force-stopped the app and tried again, nothing. I've removed and readded the manga, nothing.

**Comment by Flat** [comment]
Try searching for Wagnaria
