### ISSUE TITLE
Show List of manga from anilist & kitsu 

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#1774]
**App version:**

**Issue/Request:**
   Request

**Steps to reproduce (if applicable)**

 1. Show all my Manga list from anilist & kitsu in different page
 2. Click on list then search through manga sources
 3. then add to library 

**Other details:**
i have made some images in photoshop 
side panel  : [https://i.imgur.com/D9x4nFE.png](https://i.imgur.com/D9x4nFE.png)
main screen : [https://i.imgur.com/qGWMOE4.png](https://i.imgur.com/qGWMOE4.png)

this will help to view all the list from anilist.co and kitsu.io without adding each one by one to library.  it will help for backup too (partial backup)

![screenshot_2018-12-21-20-44-30-337_eu](https://user-images.githubusercontent.com/25240839/50353380-1cd87500-056e-11e9-9f5d-fee2986ef98d.png)
![screenshot_2018-12-21-20-47-24-964_com1](https://user-images.githubusercontent.com/25240839/50353381-1cd87500-056e-11e9-8cd7-faadbdcaa3db.png)

**Comment by Flat** [comment]
This seems out of the scope of a manga reading application. Tachiyomi is not a kitsu/anilist/mal client.

**Comment by Flat** [comment]
Even if we show the list in the app you will still have to manually track and add each one, adding the additional step of having to back out of the list to search a catalog.

**Comment by wopian** [comment]
Yes, but it removes the need of having to get the name of, then search by pasting/typing the name for hundreds of manga. It's why I still don't have all of what I (was) reading added to Tachiyomi over 2 years later.

**Comment by as280093** [comment]
@CarlosEsco :joy: no need for that this will be the end 
its not posting app only manga reading app 
so only manga content

**Comment by CarlosEsco** [comment]
But why can I not post on the manga page for anilist or kitsu about  the manga I am reading?

**Comment by wopian** [comment]
That would be a separate issue that can be discussed/closed for being out of scope. As it stands this is relevant as it has the potential of making adding multiple manga to Tachiyomi from tracking services so much quicker, as users would no longer need to search for each individual manga in their library.

I don't know if the navigation drawer is the best place for it, but of course they could only be listed if you have an account linked.

**Comment by Z3ROGRAV1TYx** [comment]
I think this would be a nice feature to have

**Comment by as280093** [comment]
so anyone agreed on adding this feature

**Comment by as280093** [comment]
@CarlosEsco :grinning:  whose starting it

**Comment by Flat** [comment]
You

**Comment by as280093** [comment]
@Flat  :stuck_out_tongue_closed_eyes: even if i sart i dont know much coding its like 0.01 about android coding 
i can help in other stuffs if needed like resources etc

**Comment by hXtreme** [comment]
@as280093 I agree with @Flat, this feature doesn't exactly fit in with the manga reader.

I am not sure but, perhaps making an extension might be a better idea.(As of now, I don't know how this can be done using an extension)

**Comment by inorichi** [comment]
Before anyone starts doing this, the drawer is going away and I won't merge new features on the current version.

Once 1.x has some shape it might be considered but don't get your hopes up.

**Comment by AmineI** [comment]
If can see the need to make importing manga from tracking services easier, but I think your "designs" suggestions makes these features too... Prominent ?
Such a feature would be more suited to be in the "tracking" settings, don't you think ? And with less information probably, as it'd be used to quickly add the mangas that aren't in your library yet, not to check/manage your lists. Your pictures makes it looks like a whole manga list manager inside Tachiyomi to me, which would be a bit too much I believe ?

**Comment by arkon** [comment]
I can kind of understand the appeal, but I'd like to avoid having too much feature creep/bloat in this app.

**Comment by wopian** [comment]
It's more of a quality of life fix for those using the tracking tab on the manga views than feature creep.

**Comment by Flat** [comment]
It's also implementing basically a full tracking client which is not in the scope of this app imo.
