### ISSUE TITLE
[Request] Tracking for comics in extensions like readcomiconline.to (Marvel/DC comics)

### ISSUE THREAD

**Issue by eji30** [inorichi/tachiyomi#1776]
Is it possible in a future update where users can track progress when reading Marvel/DC, or other non-Japanese manga?

If it's not possible right now, I submitted this issue anyway for future reference. Thanks.

App version: 8.0

**Comment by hXtreme** [comment]
What do you mean by track progress? Read History should be functioning.
Please clarify.

**Comment by eji30** [comment]
@hXtreme What I mean is MAL/AniList/Kitsu, but for non-Japanese comics.

**Comment by CarlosEsco** [comment]
@eji30 what site?

**Comment by eji30** [comment]
@CarlosEsco I think it's leagueofcomicgeeks.com. I'm not very sure though.

**Comment by wopian** [comment]
Unfortunately League of Comic Geeks doesn't have a (public) API available: https://leagueofcomicgeeks.uservoice.com/forums/213333-feature-requests/suggestions/6893699-api-access

**Comment by CarlosEsco** [comment]
Closing then.  If someone finds a site that has an API then they can reopen it
