### ISSUE TITLE
App crashed now will no install again

### ISSUE THREAD

**Issue by EZarnosky** [inorichi/tachiyomi#1783]
A couple days ago tachiyomi crashed after regular use - I was reading a downloaded chapter. After I started it backup all my settings were gone. Simply enough I imported my backup from the day before and went back to reading.

I happened to notice a little later that any chapters I tried to download for stuck at page 2 and would never fail out. I've tried restarting several times to no success.

I just uninstalled version 0.8.0 and tried to reinstall it, but the installed failed to complete.

I am using a Lenovo TB-8504F running Android 8.1.0.

Any help would be appreciated.

**Comment by Anutrix** [comment]
Try resetting the settings manually.

**Comment by EZarnosky** [comment]
I can't seem to find any under android/data

Any other places to look.

**Comment by EZarnosky** [comment]
I need my tablet for travel, so I just gave up and factory reset it.
