### ISSUE TITLE
[Request] Temporary solution for Myanimelist API

### ISSUE THREAD

**Issue by robbato** [inorichi/tachiyomi#1784]
Can you use this API for Myanimelist?
https://github.com/jikan-me/jikan

**Comment by bbtora** [comment]
There's a workaround for MAL tracking in the dev version. You'll have to wait for it to be implemented in stable release.

**Comment by as280093** [comment]
there is a solution which i use for myanimelist tracking
first download kitsu.io app
then go to library in bottom right corner there near the search there will be a menu icon 
there you will find export data, click on it and link myanimelist to it 

when you add manga via tracker to kitsu.io its automatically gets sync to myanimelist as kitsu and myanimelist are connected.
