### ISSUE TITLE
Can't install tachiyomi r1461

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#1788]
App version: r1461

-V0.8 stable installs and works, so I'll be using that for now.-

Issue: Realised that I haven't updated in a while and f-droid updates have stopped, so tried to install the latest version but recieve a 'app not installed' screen with no choice but to close. 
Tried uninstalling my current version (after backing up), re-downloading the file, installing a random apk file (works fine), restarting and still nothing.

Is there somewhere i can get the older dev versions to test out? 

Note 9
8.1.0
Not rooted

**Comment by that-one** [comment]
Oldest one I have is r1448, hope it helps.
https://drive.google.com/file/d/1hoEbITpjTYEHUzJBpmDtgLun_iSAyzXv/view?usp=drivesdk

**Comment by CarlosEsco** [comment]
Tachiyomi.kanade.eu

**Comment by that-one** [comment]
Oh, didn't know that exists... Welp

**Comment by ShakeBake** [comment]
Weird. Not one verison works apart from the stable version. My old verison was r144x(can't remember the exact build, and installed from f-droid) I have previously downloaded the apk form the site and installed fine. Don't really understand and, bar a wipe, not really sure what to do. I'll try disabling some admin apps and fidle around.

**Comment by ShakeBake** [comment]
Fixed. There was an old version in my samsung secure folder (the encripted folder) which was stopping me from installing the new app for some reason.
