### ISSUE TITLE
[Request] manhwahentai.com support

### ISSUE THREAD

**Issue by Rule71** [inorichi/tachiyomi#1789]
Id like to read the toomics novels but would also like to not visit that aids side which has very bad ads going on with its site ..... Idk how this works and if it is possible, all I ask for is if it's possible please do it, if not then atleast I tried? Either way thanks

**Comment by lionirdeadman** [comment]
There are extensions which can currently help that urge although not the same source of course in the meantime.

It's my understanding this request should probably go in the extensions repository so if someone could use Github's moving issue feature to avoid a duplicate, that'd be nice.
