### ISSUE TITLE
Crashing while reading Manga. (CBZ)

### ISSUE THREAD

**Issue by Mkilbride** [inorichi/tachiyomi#1792]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** Latest

**Issue/Request:** Crashing

**Steps to reproduce (if applicable)**

 1. Open Manga (Local in my case)
 2. Read for abit
 3. Crashes randomly. 

**Other details:**

On a Kindle Fire HD10.  

It ONLY happens with CBZ/CBR. Folders with JPEGS in them work just fine.  RAM usage appears fine, About 800MB still free while reading. It happens randomly.  First, turning pages slows down. Then the screen goes white and drags me back to the main Tachi screen. Then if I go back to my Manga, it resumes near my previous reading point (i.e, before I started reading again, so say I was on page 11, read to page 80, I'll be back on page 11 again)

It's pretty frustrating.

**Comment by arkon** [comment]
Closing due to age and no similar reports. If you're still experiencing it, please open another issue.
