### ISSUE TITLE
[Feature Request] Multi Download

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#1793]
the actual download works one by one download it takes more time for downloading big manga 

can you add multiple download at a time like 4 at a time rather then one by one

**Comment by SynderBlack** [comment]
This used to be a thing, but was removed because multiple requests can get you flagged on certain sources, so while this is slower, it's much safer

**Comment by kkarakk** [comment]
Why couldn't multiple chapters be downloaded from different sources? Download 1 from kiss,2 from rock,3 from park etc etc. Would look normal to each of the sites and better experience

**Comment by as280093** [comment]
@kkarakk no it cant be done like that as some release it early some late and even if itd done what about downloading it again it will be to complex and hard to maintain and use two sources is not a good idea

**Comment by Vesnyx** [comment]
@kkarakk At the moment, this is extremely unlikely to happen. We don't merge the same manga across different sources so saying "it wouldn't be that hard" is blatantly ignoring the complexity of this problem. If you have your own solution that you'd like to implement feel free to, but I highly doubt that something like this will be implemented at any point.

**Comment by SynderBlack** [comment]
Although majorly different from what you're proposing here, an option would be to download from multiple sources, but for different series. So if you're queuing a bunch of different series (from differing sources) at least that would be done faster. 
But this is a pretty off use case so I'm not sure its  worth the trouble to even implement.

**Comment by trinadhthatakula** [comment]
we used to download multiple chapter in older versions, 
if possible can you enable it for some sources downloading in bulk is taking very long time 
I started downloading a manga with 188 chapters its been like nearly 3 hours still 30 chapters are pending
