### ISSUE TITLE
Crashing when opening downloaded manga

### ISSUE THREAD

**Issue by Kev1nL0ve** [inorichi/tachiyomi#1794]
**App version:**
 v 0.8.0

**Issue/Request:**
When a manga is downloaded (automatically when there's an update), it crashes when I click on it to read it. So I have to delete it and download it manually again for it to work. It also crashes when the manga is downloaded in bulk, as in if I don't have the app open on screen, the downloaded stuff will always crash the app.

**Steps to reproduce (if applicable)**

 1. Download manga when app isn't open on screen (can be in background)
 2. Open the downloaded manga
 3. It crashes

**Other details:**
It was working around 3 weeks ago, I stopped reading for a while and now it stopped working.

**Comment by arkon** [comment]
Old issue, can't debug without logs.
