### ISSUE TITLE
[Feature Request] Option to bulk clear recently read

### ISSUE THREAD

**Issue by bsushmith** [inorichi/tachiyomi#1799]
**App version:**
0.8.0
**Issue/Request:**
An option to bulk clear recently read manga in the Recently read section

**Other details:**

**Comment by MrSteve10424** [comment]
Try turning on "Remove after read" in Settings > Downloads > Remove after read

**Comment by bsushmith** [comment]
In the recently read section, there's a history of manga that was opened and read at least one page(i think), not just downloaded. So it would be great if the history can be removed through a simple option like 'clear all recently read'. I don't mind there being a downloaded chapter.
