### ISSUE TITLE
Mangafox doesn't keep track of read chapters (sometimes)

### ISSUE THREAD

**Issue by IceKreem** [inorichi/tachiyomi#18]
This bug is really hard to reproduce but it only happens with mangafox. If you refresh either through the update button or refresh the chapter list of that manga. It will just show the whole list regardless if you already read them. (So it basically says you haven't read anything of this manga). I barely read from MangaFox but it happened with OnePunch-Man (on mangafox).

**Comment by inorichi** [comment]
The app deletes chapters if they aren't found when updating the list. I guess Mangafox is returning a successful response but with some kind of error message (like wait a few seconds and try again) and the parser returns an empty list. An easy solution would be to throw an error if the list is empty, so that nothing is modified, or to catch that message and throw the error there.

**Comment by IceKreem** [comment]
Yeah I guess that would make sense as it doesn't happen when the chapter list is not empty (Not in my experience anyway).

**Comment by inorichi** [comment]
Done. There's a little problem with this. If the source deletes all the chapters (like Batoto does on some mangas) you will end with "zombie" chapters. They will work if you have downloaded them before though.

**Comment by IceKreem** [comment]
Sadly it happened again :(, when I hit update now, the whole list came up as unread for Onepunch-Man :( The thing is as well, there wasn't even an updated chapter that released for this manga.

**Comment by inorichi** [comment]
Did you have to update the list twice and the first one deleted the list?
If not... my only guess is that the chapter URL has changed and they are replaced.

**Comment by IceKreem** [comment]
well they be changing something, right now its not happening but all of sudden, the chapterlist shows all the chapters as unread :/ And it seems specific to OnePunch-Man as previously stated. is there a workaround for it? 

What do you mean did I update it twice? I just opened the app and hit update now and then that happened.

**Comment by inorichi** [comment]
The only workaround I can think of is either improve the method `equals` of the `Chapter` class, or figure out what is returning Mangafox in that case.

So you only updated once. I wanted to know if the first update deleted the chapters and the second added them again, but that isn't the case.

**Comment by IceKreem** [comment]
Yeah only updated once, but as I said it only happens when it wants too haha :P

**Comment by IceKreem** [comment]
Actually it happens to other mangas on Mangafox, Could the URL really be changing for all of them? o.O

**Comment by inorichi** [comment]
It shouldn't happen now, unless the chapter number is not recognized.
