### ISSUE TITLE
[Feature Request] Bring back multithreaded downloads as an option

### ISSUE THREAD

**Issue by MrSteve10424** [inorichi/tachiyomi#1801]
**App version:**
N/A Future Release
**Issue/Request:**
As stated by the title, bringing back the multi threaded downloading as an option would be a better for everyone since some of us can simply use a VPN/proxy to circumvent the IP banning. Or make it customizable for every source if you want to use multithreading. I know that mangarock should techically allow multithreaded downloads since their app does it.

**Comment by as280093** [comment]
@MrSteve10424 
MangaRock allows it but why to take a risk of getting the api change if they see that their server is heavy loaded they will change the api

**Comment by MrSteve10424** [comment]
Basically I was getting tired of waiting for hours on end to download a manga, back when multithreading was available it took less than 20 mins to download 200 or so chapters, now it just takes ages...

**Comment by MrSteve10424** [comment]
@as280093  doubt MangaRock will change their api, and even if they do we can simply modify our extension to work with it.

**Comment by CarlosEsco** [comment]
For now this is not gonna be changed. In 1.x there is a plan to add the option with built in throttling. Download overnight for now.
