### ISSUE TITLE
[Feature Request] Download queue improvements

### ISSUE THREAD

**Issue by MrSteve10424** [inorichi/tachiyomi#1802]
**App version:**
N/A Future Releases
**Issue/Request:**
What about stacking all of the downloads of a manga together instead of scrolling forever?
Also, I want to be able to move the download priority (Move the manga to top to download first) and to batch delete / delete or batch pause/ pause a certain download.

**Comment by CarlosEsco** [comment]
I can't find it on mobile but this is a duplicate
