### ISSUE TITLE
[Tracking] `Started` Field is buggy on AniList Search.

### ISSUE THREAD

**Issue by DitFranXX** [inorichi/tachiyomi#1804]
**App version:** Stable(0.8.0)/Latest(r1462) both.

**Issue/Request:** Started Field shows differently between site on AniList search.
Update: Fixed value of `BuildConfig.BUILD_TIME`

**Steps to reproduce (if applicable)**

 1. Login into AniList account.
 2.  Edit Anlist tracking info on any manga
 3. Search a title and look `Started` Field.

**Other details:**

| App | Site |
| - | - |
| <img src="https://user-images.githubusercontent.com/45893338/51175910-ed175580-18fe-11e9-889d-5e07aadf668e.png" width="300px"/> | ![image](https://user-images.githubusercontent.com/45893338/51175843-c0633e00-18fe-11e9-82a4-eb189085467a.png) |

PS. stable shows 2017-10-31, Latest shows 2018-12-01

**Comment by CarlosEsco** [comment]
The app that is the started publishing date. And on the site I am assuming that's your personal started reading date?

**Comment by DitFranXX** [comment]
No, I started that in 2018.

Also all of mangas are shows same date.
![c](https://user-images.githubusercontent.com/45893338/51181017-61f18c00-190d-11e9-8a3d-7c4800ec7fae.png)

**Comment by CarlosEsco** [comment]
K that new screen helps

**Comment by Flat** [comment]
Likely an error with date parsing here https://github.com/inorichi/tachiyomi/blame/master/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt#L32

The API returns the correct date however months and days are not 0 padded. So yyyyMMdd is possibly yyyymd. May have to check for <10 and pad or use a different parsing scheme.

**Comment by DitFranXX** [comment]
May related here https://github.com/inorichi/tachiyomi/blob/0ee005579b196350158eff8b9bbe5ffd4ac3f735/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt#L249-L252

**Comment by DitFranXX** [comment]
May 2017-10-31 is `BuildConfig.BUILD_TIME` ?

https://github.com/inorichi/tachiyomi/blob/0ee005579b196350158eff8b9bbe5ffd4ac3f735/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt#L32-L37

why `date` parses build time instead of `start_date_fuzzy`?

**Comment by DitFranXX** [comment]
Wrote simple patch for this.
I want to build app self, but my idea can't detect gradle settings. So may not work.
```diff
Index: app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt	(revision 0ee005579b196350158eff8b9bbe5ffd4ac3f735)
+++ app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt	(date 1547578590775)
@@ -12,6 +12,7 @@
 import okhttp3.Request
 import okhttp3.RequestBody
 import rx.Observable
+import java.util.Calendar
 
 
 class AnilistApi(val client: OkHttpClient, interceptor: AnilistInterceptor) {
@@ -246,10 +247,18 @@
     }
 
     fun jsonToALManga(struct: JsonObject): ALManga{
+        val date = try {
+            val date = Calendar.getInstance()
+            date.set(struct["startDate"]["year"].nullInt ?: 0, (struct["startDate"]["month"].nullInt ?: 0) - 1,
+                    struct["startDate"]["day"].nullInt ?: 0)
+            date.timeInMillis
+        } catch (_: Exception) {
+            0L
+        }
+
         return ALManga(struct["id"].asInt, struct["title"]["romaji"].asString, struct["coverImage"]["large"].asString,
                 struct["description"].nullString.orEmpty(), struct["type"].asString, struct["status"].asString,
-                struct["startDate"]["year"].nullString.orEmpty() + struct["startDate"]["month"].nullString.orEmpty()
-                        + struct["startDate"]["day"].nullString.orEmpty(), struct["chapters"].nullInt ?: 0)
+                date, struct["chapters"].nullInt ?: 0)
     }
 
     fun jsonToALUserManga(struct: JsonObject): ALUserManga{
Index: app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt	(revision 0ee005579b196350158eff8b9bbe5ffd4ac3f735)
+++ app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt	(date 1547578452731)
@@ -1,6 +1,5 @@
 package eu.kanade.tachiyomi.data.track.anilist
 
-import eu.kanade.tachiyomi.BuildConfig
 import eu.kanade.tachiyomi.data.database.models.Track
 import eu.kanade.tachiyomi.data.preference.PreferencesHelper
 import eu.kanade.tachiyomi.data.preference.getOrDefault
@@ -17,7 +16,7 @@
         val description: String?,
         val type: String,
         val publishing_status: String,
-        val start_date_fuzzy: String,
+        val start_date_fuzzy: Long,
         val total_chapters: Int) {
 
     fun toTrack() = TrackSearch.create(TrackManager.ANILIST).apply {
@@ -29,14 +28,12 @@
         tracking_url = AnilistApi.mangaUrl(media_id)
         publishing_status = this@ALManga.publishing_status
         publishing_type = type
-        if (!start_date_fuzzy.isNullOrBlank()) {
+        if (start_date_fuzzy != 0L) {
             start_date = try {
-                val inputDf = SimpleDateFormat("yyyyMMdd", Locale.US)
                 val outputDf = SimpleDateFormat("yyyy-MM-dd", Locale.US)
-                val date = inputDf.parse(BuildConfig.BUILD_TIME)
-                outputDf.format(date)
+                outputDf.format(start_date_fuzzy)
             } catch (e: Exception) {
-                start_date_fuzzy.orEmpty()
+                ""
             }
         }
     }
```

**Comment by DitFranXX** [comment]
Update: Patch is work.

![image](https://user-images.githubusercontent.com/45893338/51216046-5da58d00-1966-11e9-840f-80babf3a9588.png)

But, My commit(DitFranXX@acf32bbd83c301e289f944a9fed3128a5211c5ab) seems has some new line ending error. Please someone patch it into master. codes may dirty.
