### ISSUE TITLE
[Feature Request] In-App Tracking

### ISSUE THREAD

**Issue by hanson2001** [inorichi/tachiyomi#1806]
**App version:**
0.8.0

**Issue/Request:** 
A function where the app would be able to automatically remember when a manga is added to My Library. This seems useful during the time when MyAnimeList API is still down and when I forgot to add the date to MAL. This will be integrated into the app rather than Services (MAL, Kistu, AniList).

**Comment by as280093** [comment]
I think you are talking about adding date field in manga details so you can manage of use them later 
for eg

if you added a manga in Tachiyomi library on 02/12/18
and if MyAnimeList API is working after few months rather then taking the date of adding to API, It should take the date added to Tachiyomi, but to do so you have to wait for 1.x to roll out and #1715 
feature to be added.

**Comment by felixalguzman** [comment]
Kitsu is able to sync to MyAnimeList. The option is in [settings](https://kitsu.io/settings/exports).

**Comment by arkon** [comment]
Superseded by #2670
