### ISSUE TITLE
Tachiyomi Sources needs to be UPDATED!!!

### ISSUE THREAD

**Issue by Shinrazune** [inorichi/tachiyomi#1807]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**App version:** 0.8.0

**Issue/Request:** Page List Empty/Source Not working

**Steps to reproduce (if applicable)**

 1.Update Mangahere(source)
 2.Update Mangafox(source)
 3.Total Update

**Other details:**

**Comment by bbtora** [comment]
You can instead try installing their respective extension.
