### ISSUE TITLE
[Request] Found Manga At Top and Merged

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [inorichi/tachiyomi#1809]
So, I think it would be a good idea: when you search for a manga using Catalog>Global Search it puts all found at top. So if I type "One Piece", if any results are found it moves it to the top instead of showing all these "Not found" per extensions and scrolling through them all. 

It also would be better if we can just see the icon and title of found books and then click them and pick a repo of choice. This will eliminate duplicate results from multiple repos and instead merge them to choose there. I think this will provide more seamless searching.

Also sidenotes: I often find myself searching for something on global search and it doesn't come up, but if I go into a specific extension and search for the same thing it actually shows up all of a sudden. Also sometimes some of the repos in global search just show a lingering buffer circle.

**Comment by metroid112** [comment]
I think it's a good idea, even more so when you have installed a lot of extensions, the global search gets pretty big quickly

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi/issues/1732
