### ISSUE TITLE
[Feature Request] First 9 pages should be named 01-09 instead of 1-9

### ISSUE THREAD

**Issue by dbfan1** [inorichi/tachiyomi#181]
When I download a manga chapter, the first 9 pages are named as 1.jpg, 2.jpg...9.jpg. Instead, it should be named as 01.jpg, 02.jpg and so on. The reason behind this feature request is that a few image viewer apps on Android show the first image (1.jpg) and then the tenth image (10.jpg) while it should show the second image (2.jpg) when scrolling continuously. But if they are renamed to 01-09 they show the images in the correct order.

If image 10.jpg is renamed to 010.jpg then again it displays the image in different order as mentioned in the first case. Only the first 9 images should be named as 01-09.

I know that Tachiyomi displays the images in the correct order. I'm talking about QuickPic and Solid File Explorer's (Material version) image viewer.

---
Version: v0.1.4

**Comment by shogunreaper** [comment]
yeah i agree with this.

**Comment by hresad** [comment]
That would still be a problem for chapter that have over 100 pages. Since it's really unlikely for any single chapter to have 1k or more pages, 001 would be the way to go.

**Comment by dbfan1** [comment]
@hresad I haven't come across a manga chapter which has more than 100 pages, which is why I suggested 01 instead of 001.

**Comment by hresad** [comment]
@dbfan1 I'm currently reading Nobunaga no Chef on batoto. The first 7 "chapter" are whole volumes. The first one has 190 pages. 
I've read other manga that come out maybe once or twice a year that can have 100ish pages.
Doesn't happen too often, but still happens.

**Comment by inorichi** [comment]
I'll change this before the next stable release.

**Comment by dbfan1** [comment]
@hresad I'm not saying that there isn't any manga chapter which doesn't have 100 pages. I'm sure they exist, just that I haven't come across one. @inorichi Thanks for accepting this request and make it 001, 002,..., 010, 011 and so on instead of 01 as suggested by @hresad.
