### ISSUE TITLE
Mass Importing

### ISSUE THREAD

**Issue by Valkilor** [inorichi/tachiyomi#1811]
Is there currently a way to import my entire library via a notepad / word / excel file?

I am new to Tachiyomi and would love to be able to do this opposed to manually adding 300-400 mangas.

**Comment by as280093** [comment]
i think you should save your data on kitsu anilist sites so it could be easy to get 
some manga name can have 2 or 3 mangas so its hard but if you have link of that manga then you can create a json file  buy studying the format then restore it for the time being

**Comment by arkon** [comment]
No, and I don't expect there to be a good way to really standardize this sort of workflow due to differences in extensions/sources.
