### ISSUE TITLE
Equivalent for iOS?

### ISSUE THREAD

**Issue by LouWii** [inorichi/tachiyomi#1815]
**App version:** 0.8.0

**Issue/Request:**
Hi there

I really like Tachiyomi, I've been using it on my phone. However, the only tablet I have is an iPad and I'd like to get the same experience on it. I know that Tachiyomi won't be ported to iOS. However, I was wondering if someone knows a similar app for iOS?

Thanks (and sorry for being a bit off subject)

**Comment by CarlosEsco** [comment]
Google manga apps for ios
