### ISSUE TITLE
[Feature Request] Download Queue new features

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#1817]
this current Download Queue has less feature but it could be nice to have the following too.

1) Select All
2) Download Selected
3) Remove selected
4) Pause Selected
5) Invert Selection
6) long Press select 
7) Pause All

this is because i have added 92 manga in download list and 93rd is the one I want to download now and other through wifi when i get home 🏡 but to download 93rd i have remove all by ( clear) then again add 93rd then download then add previous one.

 It could be nice if we can change download sequence too like in my case select 93rd and send on top 🔝 or send on bottom ⬇

**Comment by hXtreme** [comment]
This is a much needed feature! I can't count the number of times I didn't have anything new to read on the train because my download queue had a backlog.

**Comment by eshanrh** [comment]
@hXtreme are you working on this? I'd like to take a shot at implementing it.

**Comment by hXtreme** [comment]
@eshanrh I'm not working on it but if you do start this I'm very willing to help.

Create a branch on your fork for this and let me know about it.

**Comment by eshanrh** [comment]
I did it, it's [here](https://github.com/eshanrh/tachiyomi/tree/downloadQ-features). I'm very new to android development, so any help is greatly appreciated. I'm focusing on just the long-press select and delete selected ideas for now.

**Comment by hXtreme** [comment]
Thanks!

I'm also fairly new to Android development so I highly rely on the Discord for Tachiyomi, everyone's been super helpful there.

**Comment by eshanrh** [comment]
What's your username on discord?

**Comment by hXtreme** [comment]
hpar1

Best,
Harsh

**Comment by eshanrh** [comment]
The download queue itself is a RecyclerView, and in order to make selections on it, an androidX dependency recyclerview-selection is required. 

1.x uses androidx, so these changes should wait until then, unless we want to migrate all dependencies.

**Comment by hXtreme** [comment]
To the best of my understanding 'chapters' also use RecyclerView but they allow you to make selections. You may want to take a look at how that works and try to mimic it.

**Comment by Efreak** [comment]
This would be quite nice. I have a quite large download queue regularly, and occasionally want to move something to the top.

Ideally, this would allow easy selection of multiple items (hit multi-select button, tap two items to select everything in between), have a select-all function, and have buttons to move selected items up, down, and to top/bottom.

A somewhat simpler alternative would be to have a second download option to add items to the top of the download queue instead of the bottom.

**Comment by eshanrh** [comment]
@Efreak I was working on implementing this, but I think this should be a v1 feature.

**Comment by arkon** [comment]
Mostly added in fb897e37d1a0f68355bccbbfd22a91813906b5b5

Please open separate issues if anything is missing.
