### ISSUE TITLE
Manually sync mangas question

### ISSUE THREAD

**Issue by Hyoretsu** [inorichi/tachiyomi#1819]
What is this library_id on tachiyomi.db's manga_sync category? There's a manga I'm reading with a pretty common and really short name, [Sense](https://anilist.co/manga/46269), so many manga show up on search before that one and I can't sync with it. I've already figured out what all the other fields (there's _id, manga_id, sync_id, remote_id, library_id, title, last_chapter_read, total_chapters, status, score and remote_url, in this order) mean, but this one's tricky, I think it has something to do with the API.

_id: simply its number on the file, 178th equals 178
manga_id: found on tachiyomi.db's manga category, in this case it's 101
sync_id: it's 2 on all other items so
remote_id: id that comes after /manga/ on the manga link, in this case it's 46269
remote_url: manga's url on the anime list site

**Comment by inorichi** [comment]
`library_id` is the id generated on the tracking site for your manga. MAL doesn't use it because it only uses the `remote_id`, but the other sites (IIRC) have them and are needed to update the library entry.

If yours is null, link it again and it should be filled.
