### ISSUE TITLE
Mangahere and Mangafox stopeed wotkin

### ISSUE THREAD

**Issue by shadow303** [inorichi/tachiyomi#1820]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by shadow303** [comment]
Clean tachiyomi v0.8 install no extensions present, trying to browse Mangafox either by Latest or Browse gives empty screen.

Mangahere is the same, Mangasee - nothing by Latest view but Browse (and search) is surprisingly working. All three are accessible from Chrome using the same tablet.

**Comment by that-one** [comment]
... have you updated the extensions in tachiyomi?

**Comment by mray271** [comment]
Same issue. Updated the extensions, but I get a http 400 error when trying to update MangaFox

**Comment by arkon** [comment]
Both of these have been broken for months. There's issues open in the extensions repo mentioned at the top of the issue template.
