### ISSUE TITLE
[Feature Request ] Add filter "readed"

### ISSUE THREAD

**Issue by Jokerdrim** [inorichi/tachiyomi#1821]
App version: r1462
This is about library. It would be great if there was also filter "readed" and also oportunity to hide readed manga in library.

**Comment by AmineI** [comment]
Invert sorting by unread should do the trick ?
With that your *read mangas end up at the end of the list.

**Comment by hXtreme** [comment]
https://github.com/inorichi/tachiyomi/issues/1814

Similar issue which would indirectly also solve this one. Please upvote/like/thumbs up it if you find it important/relevant.

**Comment by arkon** [comment]
Marking as duplicate of #1814
