### ISSUE TITLE
Manga Covers don't load

### ISSUE THREAD

**Issue by Mystique0414** [inorichi/tachiyomi#1826]
After backing up my data in Tachiyomi app; version 0.8.0 and updated extensions. I reformat my phone then install again the app also extensions, import my back up data then after that I check my manga in categories The sources MyReadingManga and Tipastic can't load the covers I tried searching it on the categories and it still the same it just shows black covers 😢

**Comment by Mystique0414** [comment]
I don't know if it the extensions issue or the app 😅😢

**Comment by Mystique0414** [comment]
This are the example pictures btw 😅

**Comment by happywillow0** [comment]
While doing some further digging, this is an extension issue and should be specific to the extension in question. This general issue for the main app could be closed I think.
