### ISSUE TITLE
(BUG) Slow download issue for png image files

### ISSUE THREAD

**Issue by masterbats** [inorichi/tachiyomi#1829]
App version: 0.8.0

I notice some strange issue about download speed, i dont know if it is related to extension or not. 
When i download some manga from mangasee, at the beginning the download speed is fast, but after it hit certain chapter the download speed is drop even though the internet speed still the same.
So i go to check on my download folder and find out that the download speed slow down when it try to download png image file. when it download jpg file the download speed is fast even though the download was from the same source.

Thank you

**Comment by masterbats** [comment]
And apparently if i download it through vpn the download speed return to normal. 
I dont know if it has something to do with my country but i already try it with different internet provider and it still the same problem

**Comment by Fahad1998** [comment]
Maybe you should try the latest debug version and check if the problem persists. The debug version uses different package name so you don't have to replace you current tachiyomi app.

**Comment by masterbats** [comment]
thanks for your response
i just tried that and it still the same problem

i also notice another thing, the image load faster if i read it directly without downloading the chapter

well, guess now i just need to settle with vpn or migrate the source to another one

**Comment by Fahad1998** [comment]
Can you name a manga and chapter number that has this problem. I will try to download it myself to see if I also face this problem.

**Comment by Fahad1998** [comment]
And by slow how much slow you mean. Can you give the speed in kbps?

**Comment by masterbats** [comment]
you can try download slime from mangasee
chapter 1 is jpg  image
and compare it to chapter 51 that is png

**Comment by masterbats** [comment]
i cant show you the speed
but supposedly normal download per image usually just take few seconds for one image
but in this png image it can take up to one minute just to load one image

**Comment by Fahad1998** [comment]
You mean tensei shitara slime datta ken?

**Comment by masterbats** [comment]
yes

**Comment by Fahad1998** [comment]
I get same speed for chapter 1 and 51.

**Comment by masterbats** [comment]
well that is strange
guess it really has something to do my isp
and btw you did use mangasee extension right?

**Comment by Fahad1998** [comment]
I compile the master branch and use it. So our tachiyomi verson is different.

**Comment by Fahad1998** [comment]
And I also checked file extension chapter 1 was jpg and chapter 51 was png. Both have file size of about 500kb in average

**Comment by masterbats** [comment]
yes, that is what i mean, even though the file size relatively the same the speed on my device slow down for png file
but strangely the speed return normal if i use vpn

**Comment by Fahad1998** [comment]
Well I can't think of any reason behind this behaviour.

**Comment by masterbats** [comment]
can you give me your email, i will sent to you the video of that behavior and may be you can decide if it has something to di with the aplication itself

**Comment by Fahad1998** [comment]
I am not very knowledgeable about programming. I just started to learn android programming recently. So I am not sure I can understand what the problem is. You can use discord app. Maybe some other users will understand what the problem is.
Discord server:
https://discord.gg/WrBkRk4

**Comment by masterbats** [comment]
ok thanks for your response

**Comment by Fahad1998** [comment]
Which country are you from?

**Comment by masterbats** [comment]
well i also already upload in on youtube so other can also take a look for the issue

https://youtu.be/HekzCHFwll4

**Comment by 0lm** [comment]
same for me, btw. but its for nearly all extensions for me. at beginning, its at good speed. then it is very very slow, like taking 2  sec for 1 page to download. my speed is usually 5 MB / sec. so i wonder why the speed drops quickly. always at the start, like the first few minutes, i download 20 pages in 2 or 3 seconds. but later its always 1 or 2 seconds for only 1 page. 
i am usually downloading from kissmanga. isnt it possible to add a feature that allows you to download multiple pages at once and not 1 by 1 to have a workaround to this problem?

**Comment by arkon** [comment]
Can't see this being an issue with the app. The servers might be rate limiting you.

**Comment by Aarush-Goyal** [comment]
I am also facing similar issues it takes a lot of time to download manga but takes very less time to load while just reading without downloading
