### ISSUE TITLE
[Feature Request] Always show chapters list first.

### ISSUE THREAD

**Issue by Kittyplx** [inorichi/tachiyomi#1831]
App version: 0.8.0

Issue/Request: Always show chapters list first.

Other details: Can we have an option to skip the info page and go directly to the chapter list? And maybe another sub option that makes it go directly to the first chapter. The annoying level adds up when you go through 20-30 info pages in nhentai.

P.s. Add notification in app to tell Rika to add me in friend list.

**Comment by arkon** [comment]
Not quite relevant with the redesigned view.
