### ISSUE TITLE
[BUG] All entries in my library lose their chapters reguarly, but comes back after some minutes

### ISSUE THREAD

**Issue by Silberkinn** [inorichi/tachiyomi#1833]
**App version:**
0.8.0

**Issue/Request:**
Whenever I open Tachiyomi after it hasn't been open for longer (>1 hour), all my manga are empty. I see them all in my categories including their cover, but if I go into chapter view, there are non of those. At the same time, all information about the manga won't show.
When I switch apps or close the screen, after a few minutes, everything goes to normal again, all information is shown, the chapters are back and even downloaded ones don't have to be redownloaded again to view them.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
It seems like the time I have to wait for the chapters to appear got longer in the last two months as my library was growing. Maybe this is related?

**Comment by arkon** [comment]
The comment is irrelevant to the original issue, so ignoring that (and it was addressed in 0.10.0 anyway).

For the original issue, it sounds like you have a large library and a not particularly performant device. The app's likely struggling to do database operations, but I'm not sure if I can really further optimize it for these rare cases.
