### ISSUE TITLE
[BUG] Unusually high load time for manga chapters in Mangadex

### ISSUE THREAD

**Issue by ritvik1512** [inorichi/tachiyomi#1834]
**App version:0.8.0**

**Issue/Request: Unusually high manga loading time for mangadex source. Any manga from Mangadex would take over a minute or so to load a single page even on a high speed connection. This behavior started happening 2-3 days ago**

**Other details: I'm not sure if it directly relates to the extension repository so for the time being I posted it here. Apologies if I was mistaken.**

**Comment by arkon** [comment]
Literally on their front page: https://mangadex.org/thread/56429

**Comment by ritvik1512** [comment]
Oh wow, I was really not aware of this. Thanks so much!

Sorry about the thread then.
