### ISSUE TITLE
Status Bar still shows at times

### ISSUE THREAD

**Issue by MakinoTheHermit** [inorichi/tachiyomi#184]
When Reading a chapter, even though it is set to hide Status Bar, the status bar will stay there if it is brought up. The only way im able to get rid of it is either to turn of the hide status bar setting then turn it on in the chapter or to just leave the chapter and go back on it.

---
Version: v0.1.4

**Comment by j2ghz** [comment]
#81

**Comment by inorichi** [comment]
Duplicate.
