### ISSUE TITLE
e-ink look and feel

### ISSUE THREAD

**Issue by erwanoops** [inorichi/tachiyomi#1840]
**App version:0.8**

**Issue/Request:request**

**Other details: hello could you add a label "readed" some where like next to the release date ? 
i use and android E-ink tablet and the grey/black difference between read and not read is not perceptible

and for the same reason add a custom chose color/contrast on the miniature label (downloaded/to read chapter) 
**

**Comment by CarlosEsco** [comment]
Readed isn't a word.   Just hide the read in the filter option
