### ISSUE TITLE
Can´t Download From Kissmanga But Can Read Fine

### ISSUE THREAD

**Issue by TakuyaSama** [inorichi/tachiyomi#1841]
**App version:** 0.8.0

**Issue/Request:** Can´t download from Kissmanga, a few different mangas and chapters tried with the same result. I attach the screenshot. But i can read it online without any problems.

**Steps to reproduce (if applicable)**

 1. Go to any manga & any chapter.
 2. Try to download the chapter.
 3. You got the error.

**Other details:** LineageOS 15.1 (Android 8.1 Oreo)
![screenshot_20190207-191152_tachiyomi](https://user-images.githubusercontent.com/15946300/52443710-bcee5b80-2b26-11e9-9352-a102cbdcbde2.png)

**Comment by CarlosEsco** [comment]
Wrong repository
