### ISSUE TITLE
Unable to open mangas

### ISSUE THREAD

**Issue by shiloh960** [inorichi/tachiyomi#1843]
App version: 0.8.0

Issue: A number of the mangas in my library I am unable to read.

One of my mangas in which all of the chapters are marked as already read, looking at the chapter list, I selected a chapter and a black screen with a blue loading circle appeared. After a few moments, the screen went back to the chapter list. I tried opening the chapter again, as well as other chapters, but only a black screen flashes momentarily. 

Another manga I have partially read, but on the last page of my current chapter it lists the title of the chapter i just finished, states the next chapter's title, then says "Failed to load pages: Page list is empty." It has a Retry button but it didn't solve anything. Also, on the chapter list page, if I hit the blue Resume button, the blue spreads across the screen and then returns to the button instead of resuming the chapter.

Another manga I touch on a chapter to open it and it shows a black loading screen for a moment before returning to the chapter selection with the message popping up "page list is empty".

I just realized, I think all of the mangas I can't read are from MangaFox and MangaHere. When I go to the catalogues tab and try to browse those two sources, no mangas appear and it says no results found.

I hope I gave you enough information so you can quickly determine the problem. Thanks for all your help.

**Comment by TanielianVB** [comment]
App version: 0.8.2

I'm also unable to browse Mangafox. 

Catalogues > Mangafox > Browse: Gives me: "No results found"
Catalogues > Mangafox > Latest: Gives nothing. Not even an error.

**Comment by CarlosEsco** [comment]
Mangafox and mangahere are broken see issues on the extension repo

**Comment by TanielianVB** [comment]
Ok. Thank you.
