### ISSUE TITLE
Pages are small

### ISSUE THREAD

**Issue by A-1K** [inorichi/tachiyomi#1845]
![white back](https://user-images.githubusercontent.com/15345426/52579141-6e530100-2e47-11e9-9336-aed50a6babdf.jpg)

**App version:** 0.8.0

**Issue/Request:** Pages are small on my Samsung A7

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:** Excess white background and the page is small

**Comment by A-1K** [comment]
@CarlosEsco  Why was this closed?

**Comment by CarlosEsco** [comment]
Change your zoom if you still have issues. Go on the discord channel and get help. If it's still an issue after that then reopen and provide more details like viewer settings and what not
