### ISSUE TITLE
Request cataloge bato.to (new domain from batoto)

### ISSUE THREAD

**Issue by andycarly** [inorichi/tachiyomi#1847]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by bbtora** [comment]
> DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository https://github.com/inorichi/tachiyomi-extensions/

Please read before blindly posting an issue.

**Comment by einstein95** [comment]
Additionally, https://github.com/inorichi/tachiyomi-extensions/issues/728
