### ISSUE TITLE
[Feature Request] Automatically categorize based on Genres

### ISSUE THREAD

**Issue by Kussie** [inorichi/tachiyomi#185]
As a small idea i had while starting the process of migrating some of my manga from MangaWatcher it would be awesome if there was functionality somewhere (When adding manga or in settings somewhere) that would automatically sort manga into categories based on Genre and create those Categories if they don't already exist.

**Comment by inorichi** [comment]
This seems like a lot of work for something that (probably) won't be widely used. Categories are an optional part of the application and its usage depends on each user. Some prefer to categorize by genre, some by status and some by their own pattern.

In my opinion, this is not worth, at least at the current stage of the app.
