### ISSUE TITLE
Kitsu Tracker Search URL alternative

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#1850]
Kitsu search is not working at the moment. It's an issue from the source. https://kitsu.io/feedback/bugs/p/searchbar

The alternative suggested by the devs is to use https://kitsu.io/manga for manga search.

So, is it possible to use the latter URL for searching in the app as it seems more robust than the normal site one?

v0.8.0 r1463

**Comment by CarlosEsco** [comment]
The latter is what we used to use. Then they told everyone to use algolia.

**Comment by onomori** [comment]
Is there gonna be a fix or are we waiting for kitsu to fix their search for now?

**Comment by CarlosEsco** [comment]
Waiting on kitsu

**Comment by wopian** [comment]
Search is restored
