### ISSUE TITLE
Play Button replace to Open Book

### ISSUE THREAD

**Issue by RuthlessRuler** [inorichi/tachiyomi#1852]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1. 0.8
 2. Replace the play button to an Open Book button. Eg. https://fontawesome.com/icons/book-open?style=solid
 3.

**Other details:**

**Comment by arkon** [comment]
I'm not really convinced that one is better than the other.

**Comment by RuthlessRuler** [comment]
Well, it makes sense cause we read manga and play movies. So that icon clearly depicts the Read thing and play button is generally used for videos and etc. For Books and comics, read button just makes sense.
