### ISSUE TITLE
Mangazuki 1.0.3

### ISSUE THREAD

**Issue by pahadiboy** [inorichi/tachiyomi#1855]
App version: 0.8.0

Mangazuki is only showing some 20 mangas/manhwas

**Comment by Jendrej** [comment]
This belongs in [tachiyomi-extensions](/inorichi/tachiyomi-extensions).

**Comment by pahadiboy** [comment]
Jendrej yes I know but I'm new to github and was not able to figure out how to post in tachiyomi-extensions. So posted it here. 
Sorry for the inconvenience
