### ISSUE TITLE
All chapter downloads fail

### ISSUE THREAD

**Issue by CatmanIX** [inorichi/tachiyomi#1858]
**App version:** 0.8.0

**Issue/Request:** Chapters from all sources fail to download

**Steps to reproduce (if applicable)**

 1. Attempt to download chapter (manually or automatically)
 2. Download fails
 3. ?????

**Other details:**
"Attempt to invoke virtual method 'com.hippo.unifile..."

images still load when trying to read chapter assuming internet access is available, only downloads for later reading fail

**Comment by einstein95** [comment]
Did you install the extensions for the sources?

**Comment by CatmanIX** [comment]
> Did you install the extensions for the sources?

**ALL**  downloads fail, from all sources, all installed. Images still load if internet access is available.

**Comment by einstein95** [comment]
For one of the sources, what version of the extension do you have installed

**Comment by CatmanIX** [comment]
i have the latest versions for all english extensions installed, or at least the latest that are available in-app

**Comment by einstein95** [comment]
What is the version for one of the sources you have installed

**Comment by CatmanIX** [comment]
They're all different version numbers, i fail to see how the version of one random source can be helpful?

Manga Rock is my most used source i suppose, it's version is currently 1.0.5, but like i said, everything from every source is failing to download

**Comment by arkon** [comment]
Do you have room on your device?

**Comment by CatmanIX** [comment]
Ah... yeah, that would be it, would be nice if the error message made that clear

It's probably bloat from some series i haven't read in awhile, would be nice to have a way to set it to only download 'x' number of unread chapters then stop downloading new chapters until i've caught up, would be a pretty useful feature to prevent storage bloat, though i should probably just restructure how i use my categories.
