### ISSUE TITLE
Implement the touch and hold shortcut when reading manga differently

### ISSUE THREAD

**Issue by asianboi34** [inorichi/tachiyomi#1860]
**App version:**
Tachiyomi v0.8.0

**Issue/Request:**
Can you make the touch and hold feature when reading a manga an option instead of a shortcut. it makes reading manga annoying when the menu to set as cover pops while reading.

**Comment by inorichi** [comment]
Added as a new setting on 0.8.1. 

Regardless of the setting, if the reader's menu is open it'll be shown anyways.
