### ISSUE TITLE
3 Errors with MangaChan

### ISSUE THREAD

**Issue by D3xron** [inorichi/tachiyomi#1863]
1) When I'm trying to read manhuas, I'm get this error - "length=78; regionStart=9; regionLength= -10"
2) " manga for example "Handsome and Cute", I'm get this error -  "Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Elements.select(java.lang.String)' on a null object reference"
3)When I'm trying to refresh manga he says "No chapters found" but manga still in "ongoing" and "finished"..

**Comment by Taumer** [comment]
1. Wrong repo
2. Tachiyomi doesn't see the difference between manga, manhwa, comics, etc.
3. The problem does not reproduce. All works as intended.

Try to delete the manhua from the library, clear the database and chapters cache, and readd manhua

**Comment by D3xron** [comment]
Thks for response, I tried to do, what you say, but this don't got result
