### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by hardcrafting** [inorichi/tachiyomi#1865]
**App version:**
0.8.0

**Issue/Request:**
App crash when I start it, it suddendly appeared, I don't think it is linked to an update, here is what my phone says to me :

Build fingerprint: 'Xiaomi/chiron/chiron:8.0.0/OPR1.170623.027/V9.5.2.0.ODECNFA:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 5992, tid: 6018, name: onPool-worker-2  >>> eu.kanade.tachiyomi <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40
Cause: null pointer dereference
    x0   0000000000000000  x1   00000074cb118800  x2   0000000000000000  x3   00000000a6bb7c4f
    x4   00000000138c0fe0  x5   000000000000002c  x6   4b20ff3a734a726d  x7   7f7f7f7f7f7f7f7f
    x8   4d9a995399ec328a  x9   4d9a995399ec328a  x10  0000000000000000  x11  000000009b6af610
    x12  000000000000002f  x13  00000074cae73574  x14  00000074cae735d4  x15  00000074cb118800
    x16  00000074caf4c5f8  x17  00000074cdd70350  x18  0000000000000004  x19  000000009b776bf0
    x20  000000009b6aa870  x21  000000009b6af608  x22  0000000000000000  x23  00000074b03fd620
    x24  00000074caf51ba0  x25  000000009b776bf0  x26  0000000000009d5f  x27  000000009b6af608
    x28  0000000000002071  x29  00000074b03fd3b0  x30  00000074cabca550
    sp   00000074b03fd370  pc   00000074cabca554  pstate 0000000060000000

backtrace:
    #00 pc 0000000000265554  /system/lib64/libart.so (_ZN3art6mirror5Class24ResolvedMethodAccessTestILb1ELb1ELNS_10InvokeTypeE0EEEbNS_6ObjPtrIS1_EEPNS_9ArtMethodEjNS4_INS0_8DexCacheEEE+352)
    #01 pc 0000000000298b58  /system/lib64/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE0ELb0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+508)
    #02 pc 000000000028dad8  /system/lib64/libart.so (_ZN3art11interpreter17ExecuteSwitchImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_b+36540)
    #03 pc 000000000025e9b8  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+664)
    #04 pc 00000000004e9b7c  /system/lib64/libart.so (artQuickToInterpreterBridge+1468)
    #05 pc 000000000051781c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #06 pc 000000007181be00  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0xa13000)

**Comment by inorichi** [comment]
Try downloading 0.8.0 again and install it over (no data is lost if you don't uninstall before)

**Comment by hardcrafting** [comment]
Thanks, as I downladed the app on f-droid, I had to download the apk on their website, and it worked again after installing it. :)
