### ISSUE TITLE
Page List Empty with ReadComicOnline

### ISSUE THREAD

**Issue by anonnnnnnnnn** [inorichi/tachiyomi#1866]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**v0.8.0** Android

**Page List Empty with ReadComicOnline**

Whenever I try downloading or reading a comic I get a page list empty error. I have tried reinstalling and even upgrading to 0.8.0 and nothing helps.

 1.
 2.
 3.

**Other details:**

**Comment by inorichi** [comment]
Wrong place.
