### ISSUE TITLE
[Feature request] Add by URL

### ISSUE THREAD

**Issue by ZaneHannanAU** [inorichi/tachiyomi#1867]
Similar to what https://github.com/NerdNumber9/TachiyomiEH has, with its "batch add" URL field.

![Batch Add TachiyomiEH](https://i.imgur.com/Bx8sSe9.png)

This is done on the main but may cause other issues in the meantime.

!["The main"](https://i.imgur.com/MLpdWFj.png)

This would also require some changes to inorichi/tachiyomi-extensions for eg testing a url for support, but otherwise would not cause great issues.

Thank you.

**Comment by inorichi** [comment]
See #799 and #341. This won't be needed in 1.x (next big version) because deep link handling is better than pasting URLs.

**Comment by ZaneHannanAU** [comment]
Thank you.
