### ISSUE TITLE
Error 500 on searching mangadex

### ISSUE THREAD

**Issue by jasdeep1998** [inorichi/tachiyomi#1868]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by metroid112** [comment]
Read the first paragraph of what you just posted.

**Comment by ritvik1512** [comment]
Although the format is definitely incorrect, the issue exists in some form.

Cannot browse through the categories on Mangadex, any search is giving no results

**Comment by metroid112** [comment]
The issue is already being discussed on the extensions repository over here: https://github.com/inorichi/tachiyomi-extensions/issues/875
