### ISSUE TITLE
[Feature Request] Notify about extension updates

### ISSUE THREAD

**Issue by jsilvermist** [inorichi/tachiyomi#1869]
When extensions are broken for sources it can take some time to notice if it's a lesser used source, even though a fix has often already been published with an extension update.

If there was an option to enable a notification regarding updates for currently installed extensions it would prevent the need to keep checking manually.

**Comment by CarlosEsco** [comment]
Will be better handled in 1.x

**Comment by jsilvermist** [comment]
Holy crap that was a fast response lol, thanks!
