### ISSUE TITLE
[Minor Bug] Covers in library mixed up

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#187]
Covers in library sometimes get mixed up (manga gets a cover from another one). It's happened before, usually under heavy load, took a few seconds for them to fix themselves. Because of that, I wasn't able to capture it. But now, combining heavy load and internet loss it stayed that way long enough for me to get a screenshot.
http://i.imgur.com/1uELNle.png http://i.imgur.com/bNsRN24.png

---
Version: r520, r635

**Comment by inorichi** [comment]
It's probably fixed using a placeholder with Glide. I need some loading animation or something like that.

**Comment by j2ghz** [comment]
I spotted it again in r699, I can't reproduce in r704
It seems to me it occurs only when low on RAM?
I use unread filter all the time so there are just a few manga visible in my library, it manifests only when there's a lot. So it's not solved,  but I don't think it's worth looking into it.
