### ISSUE TITLE
Searching doesn't work at all for some of the sources

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [inorichi/tachiyomi#1870]
ReadMangaToday and MangaSee return some entries (but their libraries are sparse so I don't use them) but whenever I search for anything (let's say for example, I want to read Tomo-chan wa Onnanoko).

![](https://i.imgur.com/dNuYVxu.png)

As you can see, the search doesn't return anything, even though I have that manga added to my library and it updates normally, without a hitch. Here's an example with Naruto:

![](https://i.imgur.com/m5D8epP.png)

The only sources, on which searching works are those two previously mentioned and e-hentai. Kissmanga, MangaDex, Mangafox and Mangahere don't work at all, no matter what you search. The issue persists on both the regular release and the device build.

**Comment by AviKav** [comment]
Anonymous searches are temporarily disabled by MangaDex

**Comment by zbigniewzolnierowicz** [comment]
@AviKav Okay, fair enough, but why are the rest of the sources not working then?

**Comment by CarlosEsco** [comment]
Cause those others are broken.  Kissmanga is only one not and you need to do the 503 workaround. Which can be found on discord

**Comment by Kiroc** [comment]
Which discord?

**Comment by CarlosEsco** [comment]
The one on the main github page for tachiyomi
