### ISSUE TITLE
 Search/Filter function no longer works with mangadex extension

### ISSUE THREAD

**Issue by Chaunceys180** [inorichi/tachiyomi#1871]
VERSION 0.8.0

Issue: Search/Filter function no longer works with mangadex extension. 

**Steps to reproduce (if applicable)**

 1. Go to mangadex catalogue
 2. Search for any manga, no results found
 3. Filter for any author, no results 

I think mangadex recently updated their cloudflare service to prevent ddos attacks maybe thatt has something to do with it.

**Comment by AmineI** [comment]
Read the text you erased when creating the issue. This doesn't belong here but in the extensions repo, where it was already reported. (In short : Mangadex disabled it for guests.)
