### ISSUE TITLE
Vertical viewer centers image instead of showing top part first

### ISSUE THREAD

**Issue by sandorex** [inorichi/tachiyomi#1872]
**App version:**
0.8.0
**Issue/Request:**
When using vertical viewer it centers the image if its bigger than size of the screen
**Steps to reproduce (if applicable)**

 1. Set "Viewer for this series" to vertical
 2. Load any manga with tall pictures (webtoon usually)
 3. Go to next page

**Other details:**

**Comment by inorichi** [comment]
Fixed on 0.8.1
