### ISSUE TITLE
[bug] After update notification will randomly announce new chapters for various mangas

### ISSUE THREAD

**Issue by kakek** [inorichi/tachiyomi#188]
Since 0.1.4, the after update notification will randomly announce new chapters for various mangas, for no reasons.

Details :

When launching a manual update, a notification shows the progress of the update. At the end, it displays something like 

"Found new chapter for :
Girls of the wild
gokuto no brynhildr
Maho shoujo of the end
Nanatsu no tazai
noblesse
... "
( I guess it reachs the maximum size of a notification)

manga list will not always be the same.

But when I open the app, there is no new chapters for those mangas. Checking on the website confirms no new chapter.

It will happen almost every update, for various Mangas. As far as I can tell, this is only for Mangafox mangas (I have a mix of mangafox and kissmanga in my library.)
I thought this might be linked to the update that prevent mangafox's manga from randomly reseting read chapters like it did before 0.1.4

Just to be clear, **this only concern the notification !**
In-app, manga are updated fine. Counter for unread chapters works well, for mangafox as well as other sources. So obviously, it's a minor bug. I don't expect it to be fixed soon nad don't mind, just wanted to mention it.

**Comment by IceKreem** [comment]
This happens to me too but only with MangaFox manga(s). I think the developer already knows of the problem.

**Comment by j2ghz** [comment]
There was a similar issue already reported, try to look at it. (Might not be the same issue)
