### ISSUE TITLE
[Issue] Shows manga has downloaded chapters when it doesn't have any

### ISSUE THREAD

**Issue by Nydid** [inorichi/tachiyomi#1882]
**App version:**
0.8.0
**Issue/Request:**
In Library : Some manga show a number (the counter, top of the manga icon) of downloaded chapters but don't actually have any downloaded, this saturates my library to the point where I can't find anything
**Steps to reproduce (if applicable)**
N/A
**Other details:**
KissManga Source
Lots of downloaded manga : ~30GB

**Comment by CarlosEsco** [comment]
Go into the folder for the manga and delete any temp folders or files.  There is an open issue already for this to be done automatically but hasn't been worked on
