### ISSUE TITLE
Syntax error parse (line 1)

### ISSUE THREAD

**Issue by tompalen** [inorichi/tachiyomi#1883]
**App version:**
r1463
**Issue/Request:**
for about a week now i havent been able to read anything or open anything through kiss anime (havent tried another reader though), I cleared cookies and cache and have restarted my phone multiple times, nothin. I made an account here just to report this to u.

**Steps to reproduce (if applicable)**

 1. Resuming manga where I left off.
 2. Clicking any chapter, read or not.
 3. Even downloaded chapters wont read

**Other details:**

**Comment by arkon** [comment]
Update to the latest dev build.

**Comment by tompalen** [comment]
i updated through the F-Droid app (first time user so maybe I messed up?) and my tachiyomi crashes when I try to restore my backup (lost my library). Did I mess something up when updating? Also still getting the same error

**Comment by Fokkusuteru** [comment]
I've got the same issue. Srsly it's annoying. Any idea how to solve this??

**Comment by arkon** [comment]
@tompalen Get the latest version from GitHub instead. The F-Droid version is no longer maintained.

**Comment by tompalen** [comment]
@arkon yep just did that! it's working smoothly but I still lost my library, my backups end in an odd error too. Any ideas on getting my stuff back?

**Comment by arkon** [comment]
@tompalen What do the errors in the logs say?

**Comment by tompalen** [comment]
@arkon "Not a JSON Object: " with a bunch of random symbols. I have two backups and both do the same thing. Could it be because my backup is from the last version before I updated?

**Comment by KadmusPrime** [comment]
I'm having the same problem, happens with both the latest build and the dev build. The error pops up for most of the manga extensions or anything that isn't a translation team/ hentai extension

**Comment by inorichi** [comment]
If you can mail me the backup I can take a look.

**Comment by DitFranXX** [comment]
Syntax error is fixed on #1876 
wait for stable release
