### ISSUE TITLE
Search function not working properly

### ISSUE THREAD

**Issue by leoteesh** [inorichi/tachiyomi#1884]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.0

**Issue/Request:**
Hi is anyone else having trouble using the search function?
When I am searching for a title and I click on any source then go back it goes to a blank screen.
Also mangahasu search is not working for me. It just comes up with a loading sign.
 I have checked the website for this particular manga and it does have it.
Any advice is much appreciated.
Thank you

**Comment by CarlosEsco** [comment]
known issue and is open in the extension repo.  Next time read the text you ignored, before posting
