### ISSUE TITLE
App suddenly closing after a few seconds

### ISSUE THREAD

**Issue by Luisdv93** [inorichi/tachiyomi#1888]
**App version:**
0.8.0

**Issue/Request:**
App suddenly closing after a few seconds.

**Steps to reproduce (if applicable)**

 1. Open the app
 2. Wait a few seconds
 3. App closes completely

**Other details:**
I checked that it doesn't happen on the dev build but I'd like to backup my library before moving to the dev build, but I'm unable to create a backup since the app closes too fast.

**Comment by CarlosEsco** [comment]
Update to .8.1
