### ISSUE TITLE
Automatic updates for debug version

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#189]
Can this be done?

**Comment by j2ghz** [comment]
#170

**Comment by shogunreaper** [comment]
so that's a no?

**Comment by null-dev** [comment]
Nope, he means it's already done! You just need a separate app store called F-Droid to take advantage of it. See here: https://github.com/inorichi/tachiyomi/wiki/FDroid-for-debug-versions

**Comment by shogunreaper** [comment]
i saw the link for fdroid.. i thought that was some type of phone lol.

**Comment by shogunreaper** [comment]
well i installed fdroid and the latest debug version 0.1.4.520

but when i click on Accounts i get the error message "Unfortunately, Tachiyomi has stopped" and then it restarts.

**Comment by j2ghz** [comment]
I am on that version myself and it works. Since it doesn't seem to be related to my repo, you should close this issue and open a new one.

**Comment by shogunreaper** [comment]
yeah it worked before i uninstalled it too.

but after i uninstalled to reinstall the fdroid version now none except the official one will let me add an account.

**Comment by inorichi** [comment]
It's my fault. I'll fix that today.

**Comment by shogunreaper** [comment]
okay, thought i was going crazy.

**Comment by inorichi** [comment]
Someday I may include something for debug releases. For now, use F-Droid and @j2ghz repo
