### ISSUE TITLE
Multiple Scanlator downloads

### ISSUE THREAD

**Issue by kevinhu12345** [inorichi/tachiyomi#1893]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.1

**Issue/Request:**
There is usually download issues when there are multiple scanlators. Most evident with 5Toubun.
Ends up downloading both scanlators sometimes. Doesn't always do this

**Steps to reproduce (if applicable)**

 1. Select chapters from 1 scanlator and download.

**Other details:**
This was also an issue in older versions

**Comment by thousandsofthem** [comment]
I'm not sure what topic-starter means, but, probably, the solution:

When downloading chapters, add group name to chapter's folder name.
I.e. instead of "Ch.15" use "Ch.15. (Foo Scans)"

**Comment by kevinhu12345** [comment]
> I'm not sure what topic-starter means, but, probably, the solution:
> 
> When downloading chapters, add group name to chapter's folder name.
> I.e. instead of "Ch.15" use "Ch.15. (Foo Scans)"

When I try and download just from 1 scanlator, it sometimes downloads the same chapter from all scanlators

**Comment by AmineI** [comment]
I had the same issue for a while, and noticed it looks like it downloads only the correct version but shows both as downloaded, and then opens the same version for both chapters.

Ex : 
- Download GoToubun 44 by LHT on mangadex
-> /r/anonymous version shows as downloaded
-> HOWEVER, when opening r/anonymous's chapter, you'll see LHT's "credits page", because it never downloaded LHT's version.

**Comment by Efreak** [comment]
See also #1338 #1530 #522. I'm currently having this issue with multiple comics on tapastic, and the occasional title elsewhere. The worst is some comics on tapastic that name each page (chapter, in Tachiyomi's view) as the page number of the current chapter, without the chapter number (ie chapter one, one, two, three, chapter two, one, two, three, etc).

**Comment by arkon** [comment]
Closed by #3513
