### ISSUE TITLE
[Feature Request] Discussion Tab on Series View

### ISSUE THREAD

**Issue by KingsleyBawuah** [inorichi/tachiyomi#1895]
**App version:**

**Issue/Request:** 

**Steps to reproduce (if applicable)** When you click on a series there are tabs for info and chapters. I think it'd be cool to add another section called "Discussion" with a thread of anonymous comments so people can talk about the series. 

 1.My library 
 2. Click on a series 
 3. New tab alongside the current "Info" and "Chapters" tabs.

**Other details:**
You can set an alias in your settings if you don't your name on comments will be some Auto generated name.
It'd be nice to be able to reply to certain comments.
Etc etc

**Comment by CarlosEsco** [comment]
Was a previously closed issue and inorichi does not want this feature

**Comment by KingsleyBawuah** [comment]
I see I should of searched before posting! Thanks
