### ISSUE TITLE
Couldn't download manga even with wifi or mobile data 

### ISSUE THREAD

**Issue by ETvsCJ7** [inorichi/tachiyomi#1897]
App version: 0.8.1

Issue/Request: Couldn't download manga or read with wifi connected

Other details: Just recently I got a notifications on new update for tachiyomi. So before I update it, I try downloading some manga chapters, but it shows error. Then I update my app and try it again but it didn't solve the problem. The wifi and mobile data is working fine. Pls fix this issue

**Comment by phanirithvij** [comment]
- What's the error message?
- Any extra details or screenshots?

**Comment by ETvsCJ7** [comment]
It's ok, just fixed it after restarting the phone. Sorry for the inconvenience
