### ISSUE TITLE
Tracking Mangadex/mangaupdates

### ISSUE THREAD

**Issue by MammothJerk** [inorichi/tachiyomi#1898]
**App version:** 8.01

**Issue/Request:** Is it possible to add tracking for the mangadex 
source? as in updating the read/unread field on chapters in manga on the reading list

Same with mangaupdates. Could you update your reading list up to the current chapter read in tachiyomi?

**Comment by CarlosEsco** [comment]
Both are no. Mangaupdates was already shut down by inorichi, mangadex follows is a no cause it's too site specific and they don't have API for  follows
