### ISSUE TITLE
New translations not available

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#1900]
While #1750 was merged, some languages that have been added are missing from the language switcher. Is automation possible?
https://github.com/inorichi/tachiyomi/blob/2c4fd340c88d1bc9501e6e40ae6a8e2c2ea6c760/app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt#L32-L34

**Comment by inorichi** [comment]
Added them. Not sure automation is worth.
