### ISSUE TITLE
[Feature Request] Pages thumbnails as slider

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi#1901]
**App version:** 0.8.1

**Request:**
Add a image preview as slider instead of using slider with just the page number

Something like this :
https://streamable.com/7bid1 (from another app : CDisplayEx)

![1 mp4_snapshot_00 03 510_1](https://user-images.githubusercontent.com/45663409/54532172-8560a380-495d-11e9-8e53-b04e866930f9.png)

**Comment by arkon** [comment]
Similar to #1632
