### ISSUE TITLE
[Feature Request] Migration within Manga info Page

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#1903]
Manga Migration within manga page is easy as its hard to search a specific manga in traditional migration for eg like this:-
![Screenshot_2019-03-18-18-31-06-220_eu kanade](https://user-images.githubusercontent.com/25240839/54533475-46a80900-49b0-11e9-840a-4ad55c7c3983.png)

**Comment by hXtreme** [comment]
I like how you've used Tonikaku Cawaii as the example.

I might try to implement this soon.

**Comment by serjflint** [comment]
Is it possible to view the chapter list of the target before migration? I want to check if the target has all chapter before migration without manually searching in the target catalog

**Comment by CarlosEsco** [comment]
@serjflint  long click on the potential one you want to migrate to

**Comment by serjflint** [comment]
@CarlosEsco Thanks a lot. Really helped me. Too bad it can't be done with the source manga. Still, it is much easier now.

**Comment by Seflyx** [comment]
If you tap the title of the manga, it will perform a global search so this wouldn't be needed since the purpose is same.

**Comment by serjflint** [comment]
@seflyx maybe I should find and read the manual. These features are not intuitive enough for me. But it solves the issue for me.

**Comment by hXtreme** [comment]
Check out the Guides page in the wiki, it's a work in progress but aims to
get all the features documented.

Any help in updating it would be appreciated.

Thanks,
Harsh

**Comment by hXtreme** [comment]
I need some help with implementing it. Thanks in advance!

I've added the UI element (Migrate button) [check branch](https://github.com/hXtreme/tachiyomi/tree/easy-source-migration).

I also tried to add the logic but the logic didn't work properly and the manga didn't migrate (also the way I did it seems a bit of a bodge to me) [Check Gist](https://gist.github.com/hXtreme/8b55917665fe1ae6c8d174e7ae07565a).

**Comment by serjflint** [comment]
> I also tried to add the logic but the logic didn't work properly and the manga didn't migrate (also the way I did it seems a bit of a bodge to me) [Check Gist](https://gist.github.com/hXtreme/8b55917665fe1ae6c8d174e7ae07565a).
@hXtreme, as Seflyx said there is already logic implemented for pressing title of the manga. Can't it be used here?

**Comment by hXtreme** [comment]
That's not the part I'm having difficulty with though. I just need some help understanding why the edit I made doesn't work. If I can understand that then I can work around it.

Also, to use that I would probably have to make a few derived classes and stuff which I'd like to avoid if possible. In my approach I was simply trying to reuse the derived class made for migration.

**Comment by CarlosEsco** [comment]
@hXtreme  add some Log.D there and then post the logs

**Comment by Guiorgy** [comment]
I came to request something similar, but I was thinking about migrating manga by pressing on the source (manga rock in the example above), just like how you can search for manga by pressing on the title/autor/artist.

**Comment by haldi4803** [comment]
Just here to say that this would be an extremely handy feature ;)
