### ISSUE TITLE
0.8.1 app not installed

### ISSUE THREAD

**Issue by limno97** [inorichi/tachiyomi#1906]
Heya, so just trying to install the new update now and when i am, am getting 'app not installed'. Did see someone else on reddit with the same issue

[Screenshot](https://i.imgur.com/0K1qIVe.jpg)

**Comment by ciborge** [comment]
It is a common error away trying to install a non Fdroid version on top of a Fdroid version you will need to backup and uninstall the current version on your phone before installing the new build.

**Comment by limno97** [comment]
ah ok i see, thanks. mind if i ask how do i back it up? not sure as to how..
