### ISSUE TITLE
[Feature Request] Set viewer mode based on catalogue/individual series

### ISSUE THREAD

**Issue by c0ffee12** [inorichi/tachiyomi#1910]
**Issue/Request:**
Having to go into the options and changing the default viewer each time I switch between a webtoon/manga is annoying. Can we have an option to configure the viewer for each individual series or based on the category the series is in?

**Comment by bbtora** [comment]
You can configure the viewer for each individual series.

**Comment by CarlosEsco** [comment]
Yea. Click center of image and change viewer in settings there it's specific to the series
