### ISSUE TITLE
HTTP error 503

### ISSUE THREAD

**Issue by TheWrightStuff1994** [inorichi/tachiyomi#1911]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
r1470

**Issue/Request:**.
HTTP error 503

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by hXtreme** [comment]
Please provide more details on how you get the error. Also, 503 should mean that there is some problem with the server.

**Comment by TheWrightStuff1994** [comment]
I don't know why it is doing this, it started this yesterday like this and I haven't changed anything, installed anything, internet is fine, and I can access the site through my tablets web browser.

**Comment by hXtreme** [comment]
Okay, so when do you get this error?
Like,
Right after you open the app or when you try to update library...

**Comment by TheWrightStuff1994** [comment]
I believe right after I close the app, then open it later and now can't access ReadComicOnline.to

**Comment by hXtreme** [comment]
I just tried out ReadComicOnline in catalogue and seems to work for me.

Can you go to the extension menu and check to see it there are any updates there?

**Comment by TheWrightStuff1994** [comment]
No update for me and I uninstalled and reinstalled it as well

**Comment by hXtreme** [comment]
I see.
I can't seem to recognize the app version you mentioned in the issue can you try installing the latest version from GitHub: [Tachiyomi](https://github.com/inorichi/tachiyomi/releases)

If that doesn't work then probably someone with more understanding of tachiyomi would have to help you.

**Comment by TheWrightStuff1994** [comment]
Tried the regular version and the developer version, and both say the same thing "HTTP error 503"

**Comment by hXtreme** [comment]
Can you post a gif or a video while the error occurs and maybe that may give me some clues.

**Comment by hXtreme** [comment]
Also, is there a way in which you can trigger the error to occur?

**Comment by jbrucifer666** [comment]
The issue is triggered with every attempt to open a comic book issue.

**Comment by Yasuhan** [comment]
Having the same issue, and it happens when trying to update, or just generally open a chapter to read. Here's a small showcase: https://gfycat.com/GoodnaturedObedientBarb

**Comment by hXtreme** [comment]
It would be really nice if @Yasuhan @jbrucifer666 could mention the source that is giving you the problem.

**Comment by Yasuhan** [comment]
It's kissmanga, should've mentioned that.

**Comment by jbrucifer666** [comment]
It is all sources that I've tried mainly read comics online and I'm able to get to the source via mobile browser.

**Comment by hXtreme** [comment]
Seems like this issue should be on [tachiyomi-extensions](https://github.com/inorichi/tachiyomi-extensions/issues/951)

**Comment by CarlosEsco** [comment]
Yep wrong repository

**Comment by Fokkusuteru** [comment]
I've got the same issue on version r1466. Kissmanga isn't working. Shows this error. I downloaded the stable version 0.8.1 but the same error's there as well. How can I fix it??

**Comment by piratecapn** [comment]
I get that same 503 error for two sources:. Readcomiconline and KissManga.  Been happening for a few weeks.  Deleted app and installed 0.8.1 a couple weeks ago, same problem.  Also reinstalled the extensions.

Happens when trying to browse or see latest updates to the catalogue for those sites. Also happens if clicking a comic saved in my library.

**Comment by gaccm7** [comment]
> Tener el mismo problema, y ​​sucede al intentar actualizar, o simplemente abrir un capítulo para leer. Aquí hay una pequeña muestra: https://gfycat.com/GoodnaturedObedientBarb
Hola, a mi me pasa tal como tu video pero con lectormanga, y cuando entro mediante la web de la misma aplicación me dice estamos trabajando.
Como arrglaste tu problema?
Gracias
