### ISSUE TITLE
Create or restore backup is broken on the last release

### ISSUE THREAD

**Issue by IanRawen** [inorichi/tachiyomi#1912]
App version: 0.8.1

Issue: If I try to create a backup, the app crashes and if I try to restore a backup the app gives this error:
%a can't format java.lang.String arguments
And does nothing.
This only happens in 0.8.1

**Comment by nyenye** [comment]
Same over here. Also it wont find any manga.

**Comment by tompalen** [comment]
Same. When I attempt to restore I get 2 errors and i also can't search.

**Comment by DZeroX** [comment]
If you are trying to restore manga from Mangadex, you're probably doing it during hours when their Cloudflare anti-DDoS measures are on. That's out of Tachiyomi's control, so you gotta wait until they are turned off, try to see if you can solve their captcha through your browser and hope Tachiyomi gets through too, or try to improve CloudflareInterceptor somehow.

**Comment by vampiricwulf** [comment]
I get the same issue with Kissmanga. This cloudflare stuff needs addressing somehow. Is there a way to somehow get the internal browser that tachiyomi uses to scrape the pages accessible to the user so they can preload the page and pass the dumb security check?

**Comment by IanRawen** [comment]
> 
> 
> If you are trying to restore manga from Mangadex, you're probably doing it during hours when their Cloudflare anti-DDoS measures are on. That's out of Tachiyomi's control, so you gotta wait until they are turned off, try to see if you can solve their captcha through your browser and hope Tachiyomi gets through too, or try to improve CloudflareInterceptor somehow.

I'm trying to restore from kissmanga, but that's not the issue, because when I try to create a backup the app crashes and when I try to restore I immediately get this error "%a can't format java.lang.String arguments" (0.8.1 version).

**Comment by DZeroX** [comment]
> I get the same issue with Kissmanga. This cloudflare stuff needs addressing somehow. Is there a way to somehow get the internal browser that tachiyomi uses to scrape the pages accessible to the user so they can preload the page and pass the dumb security check?

Unfortunately, not 100%. I heard of cases where people randomly open Chrome, for example, and passing the check there works in Tachiyomi, but I tried it a few times, and didn't work for me.

> I'm trying to restore from kissmanga, but that's not the issue, because when I try to create a backup the app crashes and when I try to restore I immediately get this error "%a can't format java.lang.String arguments" (0.8.1 version).

On the last commit, 1471, there's a modification to CloudflareInterceptor that should be related to that issue. If you really want to, download the [latest dev build](http://tachiyomi.kanade.eu/latest), and give it a try.

**Comment by vampiricwulf** [comment]
Latest dev build seems to be able to connect to Kissmanga while I can't seem to be able to in the stable build.

**Comment by DZeroX** [comment]
> Latest dev build seems to be able to connect to Kissmanga while I can't seem to be able to in the stable build.

Yeah, the last commit (1471) is related specifically to those 503 errors popping up due to Cloudflare.

> Oh, fdroid's release is still on version 8.0. That could be my issue.

Might as well delete that, and reinstall from the releases here directly, since F-Droid releases have been dropped, according to several threads.

**Comment by vampiricwulf** [comment]
>Might as well delete that, and reinstall from the releases here directly, since F-Droid releases have been dropped, according to several threads.

Do we have an update notification in-app now? The only reason why I use f-droid is because I'd rather not have to keep an eye for updates myself.

**Comment by DZeroX** [comment]
> Do we have an update notification in-app now? The only reason why I use f-droid is because I'd rather not have to keep an eye for updates myself.

Yeah, you can enable auto-updating in the app, and install the updates directly from Tachiyomi.

**Comment by IanRawen** [comment]
> 
> > I'm trying to restore from kissmanga, but that's not the issue, because when I try to create a backup the app crashes and when I try to restore I immediately get this error "%a can't format java.lang.String arguments" (0.8.1 version).
> 
> On the last commit, 1471, there's a modification to CloudflareInterceptor that should be related to that issue and the 503 snackbar that shows up sometimes. If you really want to, download the [latest dev build](http://tachiyomi.kanade.eu/latest), and give it a try.

Yeah, I can access Kissmanga in the 1471 commit, but the issue with the backup and restore is still there, I think that some change in the code (from 0.8.0)  in the backup and restore is the cause.

**Comment by DZeroX** [comment]
> Yeah, I can access Kissmanga in the 1471 commit, but the issue with the backup and restore is still there, I think that some change in the code (from 0.8.0) in the backup and restore is the cause.

I don't know, maybe. In my case, I updated 0.8.0 to 0.8.1, made a backup, and restored it on r1471, and it worked fine. My library only has manga sourced from Mangadex, though, in your case, it might have to do with something related to Kissmanga itself.

**Comment by inorichi** [comment]
> I think that some change in the code (from 0.8.0) in the backup and restore is the cause.

There was no change from 0.8.0 to 0.8.1 related to backups, not even dependency updates. I can create a backup just fine with .1 :disappointed: . 

Which android version and OS do you have?

**Comment by inorichi** [comment]
However... it's possible that error is related to the updated translations. Which language is the app in? What happens if you force it to english?

**Comment by IanRawen** [comment]
> 
> 
> However... it's possible that error is related to the updated translations. Which language is the app in? What happens if you force it to english?

Thanks,
This was the problem, in english it works fine, in portuguese (portugal) I have the problem with restore and creating backups.

**Comment by inorichi** [comment]
This issue (`%a can't format java.lang.String arguments)` has been fixed and will be included in the next release.
