### ISSUE TITLE
None of sites show any result when i use search or sort functionver 0.8.0

### ISSUE THREAD

**Issue by alvizam** [inorichi/tachiyomi#1914]
I mostly use mangadex.

**Comment by alvizam** [comment]
And there is no result when i search or sort. I have tried reinstalling but to no avail.

**Comment by MerradOklom** [comment]
MD disabled the search function for guests that's why it doesn't work at the moment. By the way, 0.8.1 is the latest stable release, you can find it here https://github.com/inorichi/tachiyomi/releases

**Comment by CarlosEsco** [comment]
also mangadex you can search on their website if you have a login then copy the id and search in tahciyomi.
For example if the manga you want to add is
https://mangadex.org/title/24671/olympic-circles

then in tachiyomi search
`id:24671`
