### ISSUE TITLE
HTTP error 503 on kissmanga 

### ISSUE THREAD

**Issue by Fokkusuteru** [inorichi/tachiyomi#1915]
This error continuously shows up on kissmanga. When I'm trying to read a chapter or browse through the source. Other sources are working just fine. I downloaded the dev version as well as the stable one but kissmanga doesn't seem to be working for either one. How can I fix it asap?? 

App version: stable: 0.8.1
Dev: r1466

**Steps to reproduce (if applicable)**

I tried to refresh, clear cache and cookies. Also restarted phone but it didn't work. It was working fine yesterday.

**Comment by arkon** [comment]
This is fixed in r1471.

**Comment by Fokkusuteru** [comment]
How do I get it? There isn't an update option for this version in my settings

**Comment by arkon** [comment]
The download link is in this repo's README file.

**Comment by MerradOklom** [comment]
Direct link: https://tachiyomi.kanade.eu/tachiyomi-r1471.apk

**Comment by Fokkusuteru** [comment]
Thnx so much. It's working well and fine now.
