### ISSUE TITLE
r1471 getting "com.squareup.duktape.duktapeexception:referenceerror: identifier atob undefined" in all extensions

### ISSUE THREAD

**Issue by pgabriel26** [inorichi/tachiyomi#1917]
I updated the app earlier today to version r1471 hopping to stop the "http 503 error" from readcomiconline source. After the installation the error was gone and the app was working fine. Just now, I go back to app to continue reading and I'm getting this error:

com.squareup.duktape.duktapeException:referenceerror: identifier 'atob' undefined

Any solutions?

App version: r1471

**Comment by CarlosEsco** [comment]
Already discussed in the extension repo
