### ISSUE TITLE
Http Error 503 on Kissmanga and Readcomicsonlije

### ISSUE THREAD

**Issue by Thalvoz** [inorichi/tachiyomi#1921]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version: 0.8.1**

**Issue/Request: issue**

**Steps to reproduce (if applicable)**

 1. Browse the kissmanga or readcomicsonline catalogues
 2. Or update a series in the library with the said sites as its source
 3. "Http error 503" appears

**Other details:**

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/951
