### ISSUE TITLE
can't restore backup on sailfishOS (Unsupported action)

### ISSUE THREAD

**Issue by vista-narvas** [inorichi/tachiyomi#1922]
**App version:**
8.0, 8.1, r1471

**Issue/Request:**
when i push the button to restore a backup i get a error saying "Unsupported action"

**Steps to reproduce**
 1. push restore backup button
 2. see error

**Other details:**
my phone is a jolla with sailfish os installed
i know sailfish isn't android and not supported
but sailfish does support android apps and **everything** works except the restore backup button
if there is a work around to resorting backups im also happy

this happens immediately after i push the button
![Screenshot_20190322_001](https://user-images.githubusercontent.com/5795144/54824111-393d9800-4caa-11e9-8885-f8bc33457b0e.png)

**Comment by as280093** [comment]
first check if Storage permission is given , if so 
i think the button opens file manager but my guess is sailfishOS it doesn't opens its most properly sailfishOS problem

**Comment by vista-narvas** [comment]
when i make a backup it opens the file android manager and i can pick a location to store the file that works without problems  
so i dont think the problem is with the file manager or Storage permission

**Comment by inorichi** [comment]
Sorry, but they have to support `Intent.ACTION_GET_CONTENT` and a documents provider.
