### ISSUE TITLE
Can't use app in any sense.

### ISSUE THREAD

**Issue by Panda7227** [inorichi/tachiyomi#1923]
**App version:**
0.8.1
0.8.0
0.7.4
0.6.6
R1470
R1462

**Issue/Request:**
Constantly getting HTTP Error 503 when trying to read a series in my library, and no results found when entering a catalog. When I am able to enter a catalog and select a series to read w/o adding to my library, I run into "retry" on every page. The 503 error happens to multiple series and multiple catalogs.

Also, I'm not sure if this is supposed to happen or not, but when I reinstall a previous version I had, it kept my library.

**Other details:**
I have run the app fine on my current phone. It started when installing the new update.

**Comment by bbtora** [comment]
First of all, this is a source related issue so belongs to https://github.com/inorichi/tachiyomi-extensions/issues

Secondly, [https://github.com/inorichi/tachiyomi-extensions/issues/951](url)
