### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by KoyLyria** [inorichi/tachiyomi#1928]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For 
*App version: the last one

*Android version:8.1.0

*Issue/Request: the app doesn't show me the updates even if there are.
I tryied multiple times.

**Other details: when the app is searching updates it VERY VERY slow, like 20 minutes and after that... no results.

Sorry for my bad English.

**Comment by AmineI** [comment]
I suppose you're talking about chapter updates ? Could be extensions or app. 

If it's chapter updates, mention which source(s).

**Comment by KoyLyria** [comment]
Mangago

**Comment by KoyLyria** [comment]
And when I try to add new manga to my list in the searching section appear "http error 503".

**Comment by CarlosEsco** [comment]
Mangago is broken and no plans to fix

**Comment by KoyLyria** [comment]
Okay, thank you

**Comment by KoyLyria** [comment]
Okay, thank you
