### ISSUE TITLE
[Feature Request] Multi-Select bookmarking

### ISSUE THREAD

**Issue by siteod** [inorichi/tachiyomi#1929]
**Issue/Request:**
In chapter/issue panel for a series, after long-pressing on a chapter you can select multiple other chapters, and a menu appears on top right offering options for mark as read, mark as unread, etc. I would like to have a "Bookmark" option added to the top-right menu, to make it easier to select and bookmark an extended number of chapters (for easy access to a particular writer's run on a comic book, for instance). Thank you.
 
**Steps to reproduce (if applicable)**

 1. Long press a chapter/issue
 2. Select multiple additional chapters
 3. Press bookmark button to flag all selected chapters as bookmarked

**Comment by bbtora** [comment]
#1065
