### ISSUE TITLE
No Manga Chapter Seems To Load

### ISSUE THREAD

**Issue by LooP403** [inorichi/tachiyomi#1931]
**App version:**
8.1

**Android version:**
7.1

**Issue/Request:**
Does not seems to connect to any Manga no matter the source.

**Steps to reproduce (if applicable)**

 1. Select a Manga to read, any source
 2. Select a chapter of Manga to read
 3. Feel sad because you can't read Manga for some reason

This issue has been happening for a while now. I've given it about a month and a half to resolve itself but there seems to be no resolve.

**Comment by CarlosEsco** [comment]
Closing cause you provided 0 details on what sources. And this is more than likely a source issue. Please go the sources repository and verify the sources you are trying to use are not broken. Alternatively go on the discord channel for faster help

**Comment by LooP403** [comment]
I provided all possible details. All chapters work on source though, forgot to mention that.

**Comment by CarlosEsco** [comment]
What you just said makes no sense.  your ticket say no source (which again there are 50+) works.  yet  your new comment says all chapters work on source?    Please go to the discord channel and read the #faq then if those dont answer your questions please ask in the #support channel
