### ISSUE TITLE
[Design Discrepancy] Download Queue

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#1932]
Of all the items in the Nav Bar under the group "@+id/group_feature" the option Download queue is treated differently in the following manner:

1. It is not check-able
2. In MainActivity.kt it is treated differently leading to different transition animation and different back button behavior.

While it is the same with settings, it makes a lot more sense to have different behavior for settings as it is a completely different thing than reading/managing manga.

**Comment by inorichi** [comment]
As explained in the PR, this will still use an activity. Feel free to submit another PR to override the default transition with a fade, if it's too ugly.
