### ISSUE TITLE
[Feature Request] Save downloaded chapters as CBZ

### ISSUE THREAD

**Issue by TyranitarTar** [inorichi/tachiyomi#1943]
If this feature isn't too hard to implement, I'd love if this was an option in the app

**Comment by nille02** [comment]
I would Love it too, they are just uncompressed Zip archives.

**Comment by inorichi** [comment]
Duplicate of #918. It won't be possible until 1.x due to compatibility reasons (we can't use Android's Storage Access Framework for compressed files because we need random file access).
