### ISSUE TITLE
Duktape error for Cloudflare protected catalogues (Japscan, Kissmanga, etc.)

### ISSUE THREAD

**Issue by Dirky14** [inorichi/tachiyomi#1945]
Version : latest (0.8.2)
OS : MIUI 10 (Androïd 8.1)

Description of the error : Duktape error when accessing to Japscan and Kissmanga : com.squareup.duktape.DuktapeException : TypeError : undefined not callable.

**Comment by Damo1738** [comment]
I am also getting this error. The error is also getting it with ReadComicsOnline.

**Comment by anhonorableleech** [comment]
Also getting with dev version.

**Comment by 5kyLegend** [comment]
It would be the same for me.

App Version: 0.8.2 (was the same with 0.8.1) AND Latest Dev version
OS: Android 9.0

The error is the very same. I would also like to add that browsing Mangadex works, but searching does not.

**Comment by Nydid** [comment]
Have also had it in 0.8.2, Oreo firmware

**Comment by arkon** [comment]
Probably relevant: https://github.com/Anorov/cloudflare-scrape/pull/206#issuecomment-477774457

**Comment by yasnil03** [comment]
Is it already fixed or not yet?

**Comment by arkon** [comment]
No, relevant updates will be posted here as they come.

**Comment by yasnil03** [comment]
Ok thanks.

**Comment by melboiko** [comment]
Tangential, but it seems even my desktop browser (Firefox 66.0.2) can't defeat the current Cloudflare unless I disable Ublock. Seems like they're ramping up the arms race these days…

**Comment by omu009** [comment]
There is error every single time. I'm sock of this

**Comment by Fokkusuteru** [comment]
Same error on kissmanga. How can I fix this? I've got the latest dev version. Also tried it on the latest stable version

**Comment by Generator** [comment]
Like @melboiko said, i trying to open readcomiconline.to with an ad blocker like µblock, the site hangs on load (Cloudflare load page), after disable filter on readcomiconline.to an enter the page get the cookies, the same filter can be re-enabled and the site will open without issues.

uBlock log (with site bloqued)
```
+0
readcomiconline.to
1
inline-script
https://readcomiconline.to/

+0
/^https?:\/\/([0-9a-z\-]+\.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|gogoanime|igg-games|kimcartoon|memecenter|readcomiconline|toonget|toonova|watchcartoononline)\.[a-z]{2,4}\/(?!([Ee]xternal|[Ii]mages|[Ss]cripts|[Uu]ploads|ac|ajax|assets|combined|content|cov|cover|(img\/bg)|(img\/icon)|inc|jwplayer|player|playlist-cat-rss|static|thumbs|wp-content|wp-includes)\/)(.*)/$first-party,image,domain=~animeland.hu
--
readcomiconline.to
1
image
https://readcomiconline.to/favicon.ico

+0
##+js(setTimeout-defuser.js, callExo)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(setTimeout-defuser.js, .exo)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(setInterval-defuser.js, (), 500)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(set-constant.js, String.fromCharCode, trueFunc)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(addEventListener-defuser.js, /^(?:click|mousedown)$/, _0x)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(abort-on-property-write.js, callExo)
readcomiconline.to
dom
https://readcomiconline.to/

+0
##+js(abort-on-property-read.js, zfgloadednative)
readcomiconline.to
dom
https://readcomiconline.to/

+0
||readcomiconline.to^$csp=script-src 'self' 'unsafe-inline' *.disquscdn.com *.disqus.com
--
readcomiconline.to
1
csp
https://readcomiconline.to/

+0
readcomiconline.to
1
doc
https://readcomiconline.to/

+0
https://readcomiconline.to/

```

**Comment by 5kyLegend** [comment]
Yeah, so...

I "fixed" this issue on KissManga by disabling AdAway, which I had on rooted Android 9.0

The search on MangaDex still doesn't work, but KissManga definitely seems fixed. Does anyone else with the "com.squareup.duktape.DuktapeException" error have some kind of adblocking enabled?

**Comment by decal08** [comment]
> Yeah, so...
>
>I "fixed" this issue on KissManga by disabling AdAway, which I had on rooted Android 9.0
>
>The search on MangaDex still doesn't work, but KissManga definitely seems fixed. Does anyone else with the "com.squareup.duktape.DuktapeException" error have some kind of adblocking enabled?

I turned off Adhell, and it worked! Duktape error was not encountered

**Comment by 5kyLegend** [comment]
> I turned off Adhell, and it worked! Duktape error was not encountered

Glad I could be of help! Thanks to @melboiko who took notice of this, it wasn't tangential at all. Seems like this issue happens when some kind of adblocking is enabled.

**Comment by Maf0** [comment]
Had to make an account just to say my thanks and also contribute my tiny bit:
i was using the Phoenix browser as my standard browser and it has a built in adblock, after reading what was said, i tried messing around with it without any success, so i uninstalled it and without any browser on my phone it simply started working. I even installed it again and it's still working
here's my theory: 
1 as long as you download some browser without adblock and set it as your standard, kiss manga will automatically work
2 no, you have to go as far as uninstalling them
please take what i said with a bit of salt as i am by no means an expert

**Comment by DitFranXX** [comment]
When you encounter this error, please let me know what site cause the error. 
Currently cycle is on Japscan but site itself is unstable so can't test properly.
ps. Kissmanga is not on cycle now so it just works (03/30/2019 00:00 UTC)

**Comment by arkon** [comment]
FWIW, I don't use ad blockers on my phone and the CF checks are still cycling through new (?) versions.

While ad blocking could affect the CF checks, the fix of turning it off is likely coincidence.

**Comment by whateverthe** [comment]
Hello, for information I also encounter this error (duktape) with the site Mangahasu

**Comment by Thalvoz** [comment]
This issue still persists

**Comment by jdanielchg** [comment]
In Mangadex there's a 403 error. I can't see the catalog, read, nor search any manga.

**Comment by inorichi** [comment]
Anyone having a 403. Please install the latest dev, open any manga of the failing site, go to info tab and from the overflow menu tap "Open in web view".

If you are doing a fresh dev install and can't browse the catalog because of the error, restore a backup from your stable version and open the manga from your library.

**Comment by silentTee** [comment]
On version 0.8.2, I'm still experiencing the duktape exception on Android 9, for KissManga. 

I don't have a system wide adblocker so I'm a tad confused.

**Comment by s8adamz** [comment]
Can someone help me please? I just started getting this error today, even though yesterday it was fine. Oh I'm using kissmanga

**Comment by CarlosEsco** [comment]
can you download the latest dev tachiyomi and see if it works

**Comment by s8adamz** [comment]
I'm sorry, I'm gonna seem like an idiot but... what's dev..?

**Comment by as280093** [comment]
> I'm sorry, I'm gonna seem like an idiot but... what's dev..?

dev is a side version rather then stable version which is under development and can have some bugs
dev ap link http://tachiyomi.kanade.eu/latest

**Comment by s8adamz** [comment]
Yes that worked! Thanks so much. So should I only use this version now?

**Comment by as280093** [comment]
yes you can use it as Ducktape error is fixed in it, if problem still occurs comment here

**Comment by yasnil03** [comment]
Why the mangaho source can't open?

**Comment by xXTHANOZXx** [comment]
is com.squareup.duktape.DuktapeException:SyntaxError.invalid return (line1) also related to this issue?

**Comment by joseph-peace** [comment]
Just wanted to confirm that the disabling adblocker doesn't do anything for me, and the dev build r1489 works perfectly with kissmanga.
Nokia 8, Android 9, not modified.

**Comment by Mecaliste** [comment]
Also having the com.squareup.duktape.DuktapeException:SyntaxError.invalid return (line1) issue. Is there anything we can provide for debugging purpose ?

Error happening with readcomiconline.

**Comment by CarlosEsco** [comment]
Update to latest dev?

**Comment by jsilvermist** [comment]
Latest dev fixed this for me too.

**Comment by silentfp** [comment]
Hopefully we get a new release pushed with this. Dev and release builds are installed side-by-side for me, and I can't easily migrate all my stuff to the dev app. Plus, I don't think the dev version will auto update.

**Comment by yasnil03** [comment]
I tried the updated dev some of the catalogues fixed but some are not it always say Http error

**Comment by Zahev** [comment]
> is com.squareup.duktape.DuktapeException:SyntaxError.invalid return (line1) also related to this issue?

Started getting this Error today as well, going to download de dev version until it's fixed

**Comment by Generator** [comment]
[Tachiyomi v0.8.4](https://github.com/inorichi/tachiyomi/releases/tag/v0.8.4) solves the issue with readcomiconline.to

**Comment by Zahev** [comment]
> [Tachiyomi v0.8.4](https://github.com/inorichi/tachiyomi/releases/tag/v0.8.4) solves the issue with readcomiconline.to

It really did! Thank you!

**Comment by Renaicircus** [comment]
Ver 0.8.4 doesnt fix the duktape error for Mangadex

**Comment by jsilvermist** [comment]
@Renaicircus Open the manga you're trying to read, and on the info tab click the menu and select Open in web view. Let it resolve the cloudflare challenge and captcha or whatever is present. Not sure that'll work, but it's working for me.

**Comment by Renaicircus** [comment]
@jsilvermist thank you it works!

**Comment by tjgordon** [comment]
@jsilvermist What if you can't open any manga from mangadex?

**Comment by jsilvermist** [comment]
tjgordon Save this as a .json file and restore it in Tachiyomi to get a MangaDex manga on your library:

{"version":2,"mangas":[{"manga":["/manga/35456/","Girl and Science",2499283573021220255,0,0]}],"categories":[]}



No idea of this'll work, but it's the best idea I've got.

**Comment by jsilvermist** [comment]
@tjgordon So after realizing I was making it too complicated, i just uploaded it to gdrive, so you can just restore this:
https://drive.google.com/file/d/1CTJTlWrTfB6F3IN_DLJdaEEuNWrCDAv_/view?usp=drivesdk

**Comment by tjgordon** [comment]
@jsilvermist Thanks for the help. I haven't tried actually restoring that because I was able to open the browse and latest sections on mangadex today, though I don't think I changed anything since yesterday.

**Comment by jsilvermist** [comment]
@tjgordon CloudFlare is probably on a stricter setting depending on traffic or if a DDoS attack is suspected, when they are you might have to solve a captcha or a challenge that wouldn't normally be present, which may not be present when load is lower as it may be now. (Just my guess)
