### ISSUE TITLE
com.squareup.duktape.DuktapeException : TypeError : undefined not callable.

### ISSUE THREAD

**Issue by Fokkusuteru** [inorichi/tachiyomi#1947]
**App version: r1471*

**Issue/Request: I'm have this error on my kissmanga. It was working fine just in the morning. 

com.squareup.duktape.DuktapeException : TypeError : undefined not callable.

**Steps to reproduce (if applicable)**

I tried clearing cache and cookies. Also closing and restarting app. It didn't work. Please help fic this issue asap.

**Comment by Rublood** [comment]
Duplicate of #1945
