### ISSUE TITLE
com.squareup.ducktape.Dukta peException: ReferenceError: identifier 'atob' undefined

### ISSUE THREAD

**Issue by Fokkusuteru** [inorichi/tachiyomi#1948]
App version: r1471 

Issue/Request: I've getting this error: com.squareup.ducktape.Dukta peException: identifier 'atob' undefined on kissmanga extension. This only strayed around this afternoon. Please help me fix this asap. 

I've tried clearing cache and cookies even restarting the app.

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/980
