### ISSUE TITLE
Error: Malformed UTF-8 data on Mangago

### ISSUE THREAD

**Issue by Fokkusuteru** [inorichi/tachiyomi#1950]
**App version: r1471 **

**Issue/Request: this error has been showing up on Manga go only when I try to open a chapter on certain Manga. When I search a Manga and try to read and when I check from latest Manga, I can't seem to read. But the Manga from the browse that have already been put there I am able to read. Please help me solve this issue as soon as possible. **

**Steps to reproduce (if applicable)**
I tried refreshing, clearing cache and cookies and retarding app as well. 

Other details: the error is
Error: Malformed UTF-8 data

**Comment by Fokkusuteru** [comment]
Umm any solution??

**Comment by CarlosEsco** [comment]
Read the stuff you deleted when you posted and you will see this is the wrong repository. Go there and search if there are open mangago issues.
