### ISSUE TITLE
error 403 for days only with mangadex

### ISSUE THREAD

**Issue by kingwolf13** [inorichi/tachiyomi#1952]
No matter what I try whenever I try to connect through the app to mangadex I get error 403 but only with the app I tried going to the site and completing the captcha I tried switching wifi sources I even tried uninstalling and reinstalling the extension nothing has worked

**Comment by CarlosEsco** [comment]
wrong repo and there is already open issue.

**Comment by kingwolf13** [comment]
Can you show the link for the issue please and thanks

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/871
