### ISSUE TITLE
Trying to download any comic or manga from any extension crashes Tachiyomi  on latest nightly

### ISSUE THREAD

**Issue by 0klux** [inorichi/tachiyomi#1953]
**App version: r1482

**Android version: 4.2.2

**Issue/Request: Trying to download or reading any comic or manga from any extension crashes Tachiyomi  on latest nightly

**Steps to reproduce (if applicable)**

 1. Either try to download new chapters or resuming a paused download
 2. The app will freeze and then close without ever starting any download
 3. Try to read any chapter (the problem only happens when trying to read online, offline chapters works)
 4. The app will freeze at a white screen for a few moments and the go back to the chapter list

**Comment by 0klux** [comment]
After some testing, i found out I can't even acess any extension without the app crashing.

**Comment by inorichi** [comment]
Should be fixed now.
