### ISSUE TITLE
[Bug] Can't load mangafox and mangahere

### ISSUE THREAD

**Issue by RedeyeFR** [inorichi/tachiyomi#1954]
**App version:** 0.8.2

**Android version:** Android 9 (mi a2 lite)

**Issue/Request:** Bug loading mangafox and mangahere

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
I'm not able to retrieve the manga list from those two sites, I've just started to use the app.
It gives me a "no results found, try again"

Hope someon will be able to fix that ;) The app is amazing

**Comment by CarlosEsco** [comment]
Wrong repository
