### ISSUE TITLE
Request add Extensions nettruyen

### ISSUE THREAD

**Issue by Sokiro** [inorichi/tachiyomi#1956]
**App version:**0.8.2

**Android version:**5.1

**Issue/Request:**Please add Extensions nettruyen(www.nettruyen.com/) for sources Tiếng Việt, the other Extensions are die and i can't read Detective Conan  . Thank you very much 👍 tachiyomi very good

**Comment by CarlosEsco** [comment]
smh.  the part you deleted said 

DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository https://github.com/inorichi/tachiyomi-extensions/
