### ISSUE TITLE
Range selection on library

### ISSUE THREAD

**Issue by Bexa2** [inorichi/tachiyomi#1957]
I just migrated all my mangarock favourites to Tachiyomi (1000+) and I'd like to create categories such as Completed, Re-read, On-going, Dropped, etc...

I can filter and show only completed mangas, but I can't not show completed mangas or select them all to move to a category.

Also do I have to mark chapters as read going inside every manga or can I just select N mangas and mark everything as read?
Since I just imported 1000 mangas I have a lot of blue squares telling me that there are new chapters.

**Comment by Bexa2** [comment]
Since I had a list of IDs I ended up using mangadex api to get the data and classified each manga according to the status 

```
{
    "1":"Ongoing", 
    "2":"Completed", 
    "3":"Cancelled", 
    "4":"Hiatus"
}
```

Then to those that were completed or cancelled I added each chapter like so:
```
{
    "u": "/api/chapter/55618",
    "r": 1,
    "l": 1
}
```

Just leaving this here in case someone wants to do something similar and maybe categorizing by status automatically could be added to Tachiyomi as an option/setting, either as categories or as filters on the library.

**Comment by arkon** [comment]
"Select all" was added recently to the library view.

Request for marking as read/unread: https://github.com/inorichi/tachiyomi/issues/1181
