### ISSUE TITLE
Make dev and release use same library/database structure

### ISSUE THREAD

**Issue by buzmeg** [inorichi/tachiyomi#1960]
Maybe I am missing a configuration option (wouldn't be my first time being a complete idiot), but there really needs to be a way for dev and release to use the same configuration.

I would be far more inclined to try out dev if my library didn't open empty, for example.

Anyway, thanks for all the hard work, especially in the face of all this Cloudflare garbage.

**Comment by AmineI** [comment]
I don't believe it'd be good, for various reasons. Especially since dev should be unstable and you could potentially lose all your data there, I think it's better to separate both.

Just backup your data from stable and restore it in Dev

**Comment by Sparh4wk** [comment]
"Just backup your data from stable and restore it in Dev" this is not easily doable, if you have tons of manga.. every single backup and restore will needs to be divine etc... until server sync is integrated, there is no easy way to do this as I know

**Comment by AmineI** [comment]
Right, but as of now it's the only way AFAIK. If your device is rooted you could probably manually copy the data, but I didn't try that.
________________________________

**Comment by null-dev** [comment]
I just skimmed over the Android Q release notes so please correct me if I'm wrong.

Tachiyomi uses SQLite as it's database. SQLite uses a specific API to load it's database. From what I understand, from Android Q onwards, this API will no longer be available for files on your phone's external storage/sdcard/emulated sdcard.

Since the only way to share files between apps is to place them on your phone's external storage/sdcard/emulated sdcard, and the API SQLite needs to access external storage/sdcard/emulated sdcard is being removed, this feature is essentially impossible to implement.

**Comment by AmineI** [comment]
Well I thought he was basically asking for dev/stable to have the same package name, so that dev would directly update on stable.

But then maybe [Content providers](https://developer.android.com/guide/topics/providers/content-providers) would help to share the db, I'll have to read more about that

**Comment by CarlosEsco** [comment]
As other has said. They don't share because if dev breaks something you won't lose your library and can still read

**Comment by arkon** [comment]
@null-dev There's the scoped storage API for Q, but I've yet to really read into it. In theory, users can grant permissions to read from arbitrary folders, but it's a relatively unintuitive UX.

**Comment by buzmeg** [comment]
Sorry, I  guess I wasn't  clear.  I want both dev and stable to access the same "Library" just like they access the same download storage.  I don't  want the apks to be named tge same though.  That would not be a good idea.

Anyway, not a big deal and you folks have  much bigger issues to deal with right now.

Thanks.

**Comment by CarlosEsco** [comment]
to clarify my comment.  if the 2 apps shared the same database (library)  if a commit broke or corrupt your database it would break your stable version as well.

**Comment by buzmeg** [comment]
Understood.  However, from my point of view, the value of being able to try out dev and stay on it or switch back exceeds the risk of losing my library database.  If I'm trying out dev, something is already broken in stable anyway. 

Presumably, as committers who run lots of dev versions, you folks see more corruptions than we do as end users who only occasionally  run dev when something is significantly wrong with stable.

Thanks.
