### ISSUE TITLE
Problem with mangadex extension

### ISSUE THREAD

**Issue by spookypokey** [inorichi/tachiyomi#1961]
**App version: latest non experimental version (8.something)**

**Android version:Android oreo**

**Issue/Request: trying to update a manga from the source mangadex this msg pops up "com.squareup.duktape.DuktapeException:SyntaxError: invalid return(line 1)**

**Steps to reproduce (if applicable)**

 1.from the mangadex extension 
 2.try to update any manga from that extension
 3.this msg pops up

**Comment by Jerrk** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues
