### ISSUE TITLE
Sort by release date of chapter

### ISSUE THREAD

**Issue by NetherKing1357** [inorichi/tachiyomi#1962]
**App version:**
r1489
**Android version:**
8.0.0
**Request:**
Please add an option to sort issues/chapters by release date of chapter. This option (if added) would preferably go in the 'Sorting mode' tab in the hamburger menu of a page of the manga. 

**Benefits:**
Omakes, specials and annuals will be sorted correctly to improve ease of reading

**Comment by Titus30** [comment]
Does readcomiconline extension works

**Comment by 7sevenseven** [comment]
I agree with you.

**Comment by arkon** [comment]
"Latest chapter" sort was added some time ago.

**Comment by bbtora** [comment]
They are talking about chapter list sorting. not library sorting.

**Comment by emlautarom1** [comment]
Please, take a look at #3179
