### ISSUE TITLE
double tap

### ISSUE THREAD

**Issue by 7sevenseven** [inorichi/tachiyomi#1963]
App version: 0.8.2
Android：7.1.2
HI
when I watch the manga,I usually want to if you could configure the zoom percentage in the settings.The smart fit is good,but I can't see the whole  image.In this case the image can't be zooming out. I'd like it if you could configure the zoom percentage in the settings.
Hope local comics can achieve custom zoom

**Comment by Titus30** [comment]
Is read comic online working for you

**Comment by 7sevenseven** [comment]
My English is not very good.
I agree with [https://github.com/inorichi/tachiyomi/issues/476](url)

> Right now, the app zooms the page to a fixed size on double-tap. This probably works fine on tablets but on smartphones the zoom is too large so it's not very useful. I'd like it if you could configure the zoom percentage in the settings.

Double Tap is the most convenient to watch the manga in the smartphone.
![Screenshot_20190413-153047](https://user-images.githubusercontent.com/49519653/56076250-64c32680-5e01-11e9-9669-bc7c1f5f76cd.png)
![Screenshot_20190413-153055](https://user-images.githubusercontent.com/49519653/56076268-95a35b80-5e01-11e9-8b9b-a16e9e7540fc.png)
I need to see the whole image and I also need to zoom in the image.Right now,if I double tap the screen,the image will be like this. The double tap is more convenient than use two fingers.
If you can configure the zoom percentage in the settings,the app will be perfect.

**Comment by DarKCroX** [comment]
> The double tap is more convenient than use two fingers.

you don't really need to use two fingers to zoom in/out
here the trick, you double tap and drag and adjust the scale

tap, tap[don't lift your finger], drag

**Comment by 7sevenseven** [comment]
> > 双击比使用两根手指更方便。
> 
> 你真的不需要用两根手指来放大/缩小
> 这个技巧，你可以双击并拖动并调整音阶
> 
> 点按，点按[不要抬起手指]，拖动

OH,Thank you.
