### ISSUE TITLE
Error while being on some mangas from Mangakakalot

### ISSUE THREAD

**Issue by matheousse** [inorichi/tachiyomi#1964]
**App version:**0.8.2 (latest)

**Android version:**MIUI 10 (Androïd 8)

**Issue/Request:**Java error if we try to access some titles from Mangakakalot (didn't try every catalogue so I can't tell if it's specific to this site)

**Steps to reproduce (if applicable)**

 1. Search a manga from Mangakakalot (only some of them)
 2. See the error

**Other details:**![Screenshot_2019-04-11-17-56-35-419_eu kanade tachiyomi](https://user-images.githubusercontent.com/39730615/55982851-15aeb180-5c9a-11e9-9ffd-5d8e95cf8518.png)

**Comment by CarlosEsco** [comment]
Wrong repo
