### ISSUE TITLE
getting error 400 when trying to read new characters

### ISSUE THREAD

**Issue by jawahar273** [inorichi/tachiyomi#1965]
App version:0.8.3

Android version:7.0

Issue: getting error 400 when trying to read new characters 

**Steps to reproduce (if applicable)**

 1. Update for checking new chapters. 
 2. Click for the new chapters
 3. Wait for error to come. 

**Other details:**

**Comment by CarlosEsco** [comment]
This is more than likely a source issue.  Please check the other repo for an open issue for whatever source you are using.
