### ISSUE TITLE
Search Issues in Dev Version?

### ISSUE THREAD

**Issue by Adim2P** [inorichi/tachiyomi#1966]
Soo stable is broken cause of the error about ducktape or smth. So i had to migrate to dev version for a while I restored my library and all it worked I can read what I did have in my library, but I can't search for new mangas on the catalogue I can browse the sources but I can't search anything? Is this still connected to the ducktape issues or smth?

**Comment by CarlosEsco** [comment]
what source?

**Comment by Adim2P** [comment]
Here's the Source List it could be more but this is what I gathered so far
-Mangadex
-Kissmanga
-Mangago
-Mangasee
-Mangahere

**Comment by Sparh4wk** [comment]
[988](https://github.com/inorichi/tachiyomi-extensions/issues/988)
some of them are broken with no plans to fix them.

**Comment by CarlosEsco** [comment]
well theres your problem.
(i assume you are using global search)

mangadex search only works with id and probably has a 503 error so click the browse button.  (if that doesnt work go to a mangadex manga in your library and go to the info view, then click on in web view.)
mangahere is broken - has been for 3+ months
mangago is broken has been for 6+ months
kissmanga probably has a 503 error so you should click the browse button
mangasee should be giving results.

best results is verify when you go into each catalog and search.
