### ISSUE TITLE
Backup directly to google drive doesn't work.

### ISSUE THREAD

**Issue by whiterblue** [inorichi/tachiyomi#1969]
**App version:** 0.8.2

**Android version:** 6.0.1

**Issue/Request:** Backup option saves the json fine in local storage correctly but when done directly to google drive it saves an empty json file. I noticed it given that the last months worth of backups (2 or 3 irrc) were not restoring properly (because they were empty -.- ). I remember that it worked flawlessly 6 months ago so.
Thanks.

**Steps to reproduce**

 1. Backup manually
 2. Save directly to google drive
 3. Check google drive backup size, see that is 0kb

**Other details:**
Maybe some google drive app update broke it and not tachiyomi?

**Comment by metroid112** [comment]
I just did a backup directly to GDrive and it worked. I'm on Android 9 Tachi 1469

**Comment by whiterblue** [comment]
Ok. After my phone has done some updates and also updating GDrive app, seems it's working again.
Closing as I don't really know if was Tachiyomi or something else the culprit.
Thanks.
