### ISSUE TITLE
Manga's from library sometimes disappear 

### ISSUE THREAD

**Issue by Navsuu** [inorichi/tachiyomi#1970]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/*

**App version:**
0.8.2
**Android version:**
8.0.0
**Issue/Request:**
Some of the mangas I put in library disappears but the downloaded chapters are still in storage.Dont know why this happens.

**Comment by joseph619** [comment]
What manga did you add to the library, and from what source? Also, are you sure you actually added the manga to library, and not just download the chapters?

**Comment by Navsuu** [comment]
> What manga did you add to the library, and from what source? Also, are you sure you actually added the manga to library, and not just download the chapters?

Mostly mangas from mangadex and kissmanga..Im sure i added them in library

**Comment by arkon** [comment]
#3390
