### ISSUE TITLE
App force close upon pressing search?

### ISSUE THREAD

**Issue by Adim2P** [inorichi/tachiyomi#1973]
Tachiyomi 0.8.3

-Crashes when I press the search button on my keyboard after I type, tried clicking the browse on the source it force closes the app, tried clicking latest on source still force closes the app.

**Comment by ReGtrs** [comment]
Also when restoring backups and opening source catalogues the app force closes

**Comment by einstein95** [comment]
The update has been temporarily pulled due to this issue, please either downgrade to 0.8.2 or wait for a new version to be released.

**Comment by inorichi** [comment]
0.8.4 is now available, please test again.
