### ISSUE TITLE
[0.8.4] Desync between library and catalogue

### ISSUE THREAD

**Issue by jsilvermist** [inorichi/tachiyomi#1976]
Since installing 0.8.4 mangas (specifically from MangaRock, others not tested) that are in my library don't show with the overlay in the catalogue that would mean it's in my library, and they can be added a 2nd time.

Additionally they aren't even sharing chapter read status between the 2 instances even though they are both MangaRock.

**Comment by arkon** [comment]
Wrong repo.

Also, from the FAQ on Discord:

> A recent update to the MangaRock extension affects the bookmark status of library entries in the catalogue. You can do a "source migration" from existing MangaRock entries to "new" entries.
>
>This isn't actually necessary unless you care about your entries not being greyed out when looking at the catalogue.
