### ISSUE TITLE
[Request] Mass mark unread

### ISSUE THREAD

**Issue by hafizhmakmur** [inorichi/tachiyomi#1982]
There's already "mark previous as read" to denote what chapters I've read maybe in another reader. But can there be an opposite feature to mass mark as unread? Sometimes, I'd like to reread a manga and lack of this feature hurts. Without this if I'm in the middle of rereading and I stop I'll lose where I've been reading. Thank you very much.

**Comment by arkon** [comment]
You can long press a chapter and select all/mark as unread from that menu, if that helps.

**Comment by hafizhmakmur** [comment]
That helps. How can I not see that? Thanks.
