### ISSUE TITLE
[Bug] Sort by name is flawed

### ISSUE THREAD

**Issue by ArmeF97** [inorichi/tachiyomi#1983]
**App version:** 0.8.2

**Android version:** 9.0

**Issue/Request:** Sort by name is flawed.

![immagine](https://user-images.githubusercontent.com/6240983/56144383-90c9dd80-5fa2-11e9-9757-2c3542835cf5.png)

As you can see, in the second row, the title "Isekai Yakkyoku" is before "Isekai de Kojiin wo..." 
It's because the Y letter (in "Isekai `Y`akkyoku") is uppercase and the d (in "Isekai `d`e Kojiin wo...") is lowercase 

The sorting method is flawed

**Comment by hXtreme** [comment]
I am in two minds on if this should be a bug or intended behavior.

In English `Y` should probably come before `d` but given that we are mostly dealing with Romanji, capitalization shouldn't have much importance (I guess).

Regardless, I'll open a pr and let someone else figure it out.
