### ISSUE TITLE
google recaptcha for some manga providers

### ISSUE THREAD

**Issue by Hulkmaster** [inorichi/tachiyomi#1984]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4

**Android version:**
9

**Issue/Request:**
Some sites had implemented google captcha

**Steps to reproduce (if applicable)**

 1. Open any manga for kissmanga
 2. Try to open manga (maybe several tries will be needed)
 3. At some point "page list is empty" error will be present https://github.com/inorichi/tachiyomi-extensions/issues/1021
 4. Now you have to open browser (not webview! google captcha will say "open supported browser"), open an chapter, and you will have to pass google captcha
 5. You will have to pass captcha once per ~5 chapters

Not sure if that is general tachiyomi issue, or extension specific

**Comment by hXtreme** [comment]
That sounds like something Kissmanga would do.

**Comment by arkon** [comment]
I guess it's _technically_ an issue with the fact that Tachi is scraping and the site doesn't like that? Not sure if it's really addressable though, but at least the workaround works.
