### ISSUE TITLE
App is unusable 

### ISSUE THREAD

**Issue by amboxer21** [inorichi/tachiyomi#1986]
The latest 8.4 broke my app. I cannot open a manga because it crashes and says, " loader not implemented.". I tried to downgrade and restore my backup but the backups complain that the restore point is not a Jon object.

**Comment by loocool2** [comment]
You need to install the extensions you used because preinstalled extensions were removed in 0.8.4

"Loader not implemented": internal sources were removed in 0.8.4.

1: Batoto
2: Mangahere
3: Mangafox
4: Kissmanga
5: Readmanga
6: Mintmanga
7: Mangachan
8: ReadMangaToday
9: Mangasee
10: WieManga

**Comment by kkarakk** [comment]
So can manga not be used anymore from these sources?

**Comment by CarlosEsco** [comment]
No you just need to download those extensions

**Comment by kkarakk** [comment]
it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi

**Comment by kkarakk** [comment]
it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi

**Comment by arkon** [comment]
We will not continue supporting old versions, so updating is advised if you want things to work properly.

**Comment by AmineI** [comment]
> it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi
@kkarakk 

Confusing ? Just go to the extension menu in app and click install on whatever source you use. Honestly that's actually quite nicely designed, you could have to find and download the apk manually, so having an interface is way more than welcome, and I don't believe it's confusing. Care to explain how it would be ?

**Comment by kkarakk** [comment]
Ok to reproduce my issue - i had manga downloaded from kissmanga/mangapark.    
i update the app   
app says "mysterious loading error"(paraphrasing), i come here and see i need to download extensions   
ok fine i search for extensions in app, no extensions for kissmanga/mangapark are shown.   
find i search for these extensions in the extension repository, couldn't find them with a quick glance, decided it was easier to just download the older version of the app so i could get to reading manga instead of troubleshooting the workflow.   

i will update the app when it stops working and figure it out but til then it's too much work to read stuff i already have downloaded.

**Comment by CarlosEsco** [comment]
Extensions are sorted by language then my alphabetical. If you couldn't find then you werent looking hard enough

**Comment by arkon** [comment]
Extensions have been available directly in the app for a long time now.

**Comment by amboxer21** [comment]
> Ok to reproduce my issue - i had manga downloaded from ki*_manga/mangapa*_.
> i update the app
> app says "mysterious loading error"(paraphrasing), i come here and see i need to download extensions
> ok fine i search for extensions in app, no extensions for ki*_manga/mangapa*_ are shown.
> was reassured here that if i download the extensions it would work
> fine i search for these extensions in the extension repository, couldn't find them with a quick glance,
> decided it was easier to just download the older version of the app so i could get to reading manga instead of troubleshooting the workflow.
> 
> i will update the app when it stops working and figure it out but til then it's too much work to read stuff i already have downloaded.

I am with you bro! I had no idea what extensions the manga I was reading use, so I just downloaded all of the listed sources @loocool2 provided in an earlier post. This is not so user friendly.

**Comment by einstein95** [comment]
>ok fine i search for extensions in app, no extensions for ki\*\*manga/mangapa\*\* are shown.

1. You can mention kissmanga/mangapass, they're not banned words
2. If you have an adblocker, disable it for Tachi. It'd stop the app from being able to download extensions.
3. Mangapass unsupported. Also is no longer called Mangapass, having moved to manga360.com, then mangateen.com, then mangaball.com until finally ending up at http://www.mangadeep.com/. Uses wp-manga so it should slot right in.
4. I can very much assure you the extension for kissmanga is there.

**Comment by kkarakk** [comment]
2. was the solution! i had dns66 installed from fdroid. when my phone restarted, it didn't start and was able to download the extensions. thanks for your patience.

**Comment by jiyozy** [comment]
> > it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi
> > @kkarakk
> 
> Confusing ? Just go to the extension menu in app and click install on whatever source you use. Honestly that's actually quite nicely designed, you could have to find and download the apk manually, so having an interface is way more than welcome, and I don't believe it's confusing. Care to explain how it would be ?

ummm.. where can i find the extension menu?

**Comment by MerradOklom** [comment]
> > > it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi
> > > @kkarakk
> > 
> > 
> > Confusing ? Just go to the extension menu in app and click install on whatever source you use. Honestly that's actually quite nicely designed, you could have to find and download the apk manually, so having an interface is way more than welcome, and I don't believe it's confusing. Care to explain how it would be ?
> 
> ummm.. where can i find the extension menu?

![AreUBlind](https://user-images.githubusercontent.com/43864503/68070666-e05dd400-fd4f-11e9-95a8-193cc43d8a30.png)

**Comment by jiyozy** [comment]
> > > > it was too confusing to find those extensions, was easier to downgrade the version of tachiyomi
> > > > @kkarakk
> > > 
> > > 
> > > Confusing ? Just go to the extension menu in app and click install on whatever source you use. Honestly that's actually quite nicely designed, you could have to find and download the apk manually, so having an interface is way more than welcome, and I don't believe it's confusing. Care to explain how it would be ?
> > 
> > 
> > ummm.. where can i find the extension menu?
> 
> ![AreUBlind](https://user-images.githubusercontent.com/43864503/68070666-e05dd400-fd4f-11e9-95a8-193cc43d8a30.png)

![20191102_200911](https://user-images.githubusercontent.com/57288524/68070714-ac64cc00-fdac-11e9-99ba-e680ed74f0af.jpg)

i dont have it???

**Comment by MerradOklom** [comment]
@jiyozy man, uninstall that right now, it's a copy cat/rip off of Tachiyomi (aka not the official app).

**Comment by jiyozy** [comment]
> @jiyozy man, uninstall that right now, it's a copy cat/rip off of Tachiyomi (aka not the official app).

thanks!!!! i just installed tachiyomi!!

**Comment by MerradOklom** [comment]
@jiyozy 
You're welcome. 
You can join the Discord server here if you need some help or just want to chit-chat:
https://discord.gg/tachiyomi
Also check the FAQ and Guides (WIP) at https://tachiyomi.org if you need some help.

**Comment by joseph619** [comment]
Jesus christ
