### ISSUE TITLE
Mangasee timeout issue

### ISSUE THREAD

**Issue by Shinrazune** [inorichi/tachiyomi#1988]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
r1500
**Android version:**
8.1.0
**Issue/Request:**
Mangasee giving me Timeouts
**Steps to reproduce (if applicable)**

 1.Improve Source Connectivity?
 2.Update Very Frequently
 3.Others

**Other details:**

**Comment by DarKCroX** [comment]
Wrong repo 
https://github.com/inorichi/tachiyomi-extensions/issues/1031
