### ISSUE TITLE
Manga Not Updating

### ISSUE THREAD

**Issue by Yoongin** [inorichi/tachiyomi#1990]
App version:
0.8.4
Android version:
Android 9
Issue/Request:
Trying to update manga, but it only updates to a certain manga and stops the update process there.
Steps to reproduce (if applicable)

1.Manually update
2.
Other details:

**Comment by CarlosEsco** [comment]
this is more than likely a source specific issue.  please verify the sources you are using are not having issues in the github extensions repository

**Comment by Yoongin** [comment]
May I ask how to do that

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues

**Comment by Yoongin** [comment]
Very sorry to bother but I still don't understand what to do.

**Comment by CarlosEsco** [comment]
do the sources you use have an open issue?  if so there are probably work arounds or its broken.  If you still have issues go on the discord channel read the faq then ask any questions

**Comment by Yoongin** [comment]
None of my sources currently have issues as far as I can tell. This problem started today as well.
