### ISSUE TITLE
Issue restoring backup; unexpected url

### ISSUE THREAD

**Issue by ennui169** [inorichi/tachiyomi#1992]
**App version:** v0.8.4, 0.8.2 and 0.8.1

**Android version:** 8.0.0

**Issue/Request:** Backup stops partway through.

**Steps to reproduce (if applicable)**

 1. Reinstalled tachiyomi
 2. Backup
 3. Restore Backup
 4. Restored backup from json made before uninstalling. 

**Other details:**
I was unable to update my library past a certain manga today, possibly after updating extensions and tachiyomi. I tried uninstalling and reinstalling, but when I try to restore the backup, it again only installs up a few manga up to the point where it previously stopped updating. A notification pops up stating unexpected url: /manga/zu917722. I tried removing all text in the backup json relating to that url, restoring from the edited backup, and the issue persisted with unexpected url: /manga/ad_tenshi_no_uso. 
Extensions seem to be installed. 

[tachiyomi_2019-04-19_17-56COPY.json.txt](https://github.com/inorichi/tachiyomi/files/3097895/tachiyomi_2019-04-19_17-56COPY.json.txt)

**Comment by fam007e** [comment]
Same thing happened to me... 😞

**Comment by CarlosEsco** [comment]
couple questions:

1.  do you know what source is causing the issue?
2.  was there a log error file when the backup failed?

**Comment by ennui169** [comment]
1) The zu917722 seems to be from mangakakalot but I'm not sure about ad_tenshi_no_uso. Based on the url for that series on the site, it is possible it could also come from mangakakalot. 

2) I do not know how to access log error files.

**Comment by CarlosEsco** [comment]
i think @arkon  broke it :)

can you try editing the file and putting the full url for the manga/chapter and test?  instead of just the /manga/ad_tenshi_no_uso

**Comment by arkon** [comment]
Haha, yes I did. I'll push out an update to Mangakakalot soon.

**Comment by ennui169** [comment]
I've been adding https://mangakakalot.com to the manga url and it's definitely been downloading more series. Seems to work for chapters as well when I take the time to add in the full url. 
Should I just wait for the update before trying to restore the backup again?

**Comment by arkon** [comment]
Alternatively, downgrade to [Mangakakalot 1.2.4](https://github.com/inorichi/tachiyomi-extensions/blob/repo/apk/tachiyomi-en.mangakakalot-v1.2.4.apk) for now.

**Comment by arkon** [comment]
v1.2.6 of the extension should be out soon.
