### ISSUE TITLE
[Feature Request] Alternative category view (preferrably vertical)

### ISSUE THREAD

**Issue by DatboyACE** [inorichi/tachiyomi#1994]
**App version**
v0.8.4

**Android software**
v9.0

I'm starting to build up quite a number of categories, I have a standalone category for each title that's...well....standalone...but for every title that has sequels or spinoffs, they have their own category.... I also have categories that contain series that all correspond with each other, so I DO have categories that have dozens and dozens of titles in them. This is genuinely the best way for me to organize my library.

This is exacerbated by the fact that I also identify in parentheses which SD card the titles in the category belong on. So when the only way to look through the categories is by scrolling horizontally through tabs, it's becoming extremely unpractical. I can't imagine I'm the first person to deal with this issue. 

It would make me ecstatic if we could have an alternative to the way categories are displayed....I'm thinking an option for your library to show categories by default in a vertical display, and then you go from there. Thank you so much for anyone that takes the time to read this or has any input!

**Comment by arkon** [comment]
This may be considered for 1.x, but if you do want this, you can switch to TachiyomiJ2K.
