### ISSUE TITLE
Library Update Stops

### ISSUE THREAD

**Issue by JWA2K** [inorichi/tachiyomi#1995]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version: 0.8.4

**Android version: 9

**Issue/Request: Library Update Stops Partway

**Steps to reproduce (if applicable)**

 1. Manually update Library
 2.
 3.

**Other details:**
Even while in App, the progress still stops

**Comment by arkon** [comment]
Does it always stop at the same point?

**Comment by JWA2K** [comment]
Always at the same point.

**Comment by arkon** [comment]
What manga/source is that?

**Comment by JWA2K** [comment]
BNHA from Kissmanga, I've already tried removing the downloaded database, but then it would stop on a manga from MangaRock, Azur Lane specifically.

**Comment by arkon** [comment]
Old issue, resolving.
