### ISSUE TITLE
Configurable zoom of  the double tap

### ISSUE THREAD

**Issue by 7sevenseven** [inorichi/tachiyomi#1997]
Configurable zoom on double-tap(like 125%,150%,175%,200% or another).
I know tap tap and drag.But I still hope add setting to let us use choose the zoom factor when  we use the double tap.Right now,when I use the double tap,the image will be back to the original size.This function is meaningless now.
Please, this is really important to me.

**Comment by 7sevenseven** [comment]
Why does double clicking make the screen the original size? It's a little bit not suitable for the use of small screen electronic devices. Configurable double-tap scaling is better

**Comment by Pavkazzz** [comment]
Double of https://github.com/inorichi/tachiyomi/issues/476
