### ISSUE TITLE
Can't open any manga after update to latest version

### ISSUE THREAD

**Issue by kkarakk** [inorichi/tachiyomi#1998]
Keep getting loader not implemented toast and manga that were working do not load

**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
Make sure you download the missing extensions. All internal were removed
