### ISSUE TITLE
Option to see latest added chapters.

### ISSUE THREAD

**Issue by beepFTW** [inorichi/tachiyomi#20]
I consider this to be one of the most important features of any Manga reader. Personally I love to find and read new manga that I would not normally read.

And I am LOVING this app. Looks great and has both my favorite sources. Number one being Batoto (although it looks like it is not fully implemented yet.) and second being Kissmanga, great work.

**Comment by inorichi** [comment]
Do you mean a tab in the drawer (below my library, for example) with the recently added chapters? I want to add that, I don't know when I will do it though.

What do you miss from batoto? I'm not sure I will support genre search, if that's what you are missing. I can't do a local filtering (like most apps) unless I add the entire catalog from every source, so the only option is to search online (like from your browser) and it can be quite troublesome to fully support.

**Comment by beepFTW** [comment]
Yes I think that is the perfect location. Hopefully it can be added soon!

As for batoto, I just talking about basic functionality. Every manga shows 0 chapters for me.

Do you mean you plan to implement a feature like adding a url for a manga and it would add it to favorites?

**Comment by inorichi** [comment]
Batoto takes some time to refresh the chapter list. The chapters tab has a pull to refresh, so, swipe down and wait for it to finish. It should work if you are properly logged.

No, I meant filtering mangas with genres (action, adventure, etc...)

**Comment by beepFTW** [comment]
Ah I see now. I would love to see that as well, but I would still prefer to see the latest first though.

The more I play around with the app the more I love it!

**Comment by inorichi** [comment]
The current implementation shows up to 100 chapters. They are obtained using the upload date from the source. Then they are grouped by the date they were fetched (local date).

At first, it will look ugly (lots of chapters from a manga in the same day), but it will improve over time.

Further improvements could be added, like hiding read chapters, configurable number of results, a menu for every chapter (like in the chapters view of a manga), etc...

**Comment by inorichi** [comment]
How about a spinner like the one from the catalog with date filters? Something like: Last week updates, Last 2 weeks updates, Last month updates.

**Comment by beepFTW** [comment]
Sounds great!

**Comment by inorichi** [comment]
Yes, at least for now. What you want needs new methods on all the sources. It could be added, but not a priority right now.

This issue will focus on recent updates from your library, like the one in MangaWatcher.

**Comment by Rumple007** [comment]
What happened to the recent updates drawer?

**Comment by inorichi** [comment]
I hid it for the release version. I was too lazy to add checks for release/debug version. I'm adding it back now.

**Comment by Rumple007** [comment]
Okay, thank you 😊

**Comment by inorichi** [comment]
Recent updates from the library has been implemented already. Latest updates (from sources) will be discussed in #61.
