### ISSUE TITLE
[request] Handle same chapter from multiple groups

### ISSUE THREAD

**Issue by macravin** [inorichi/tachiyomi#2000]
**App version:**
0.8.4
**Android version:**
9
**Issue/Request:**
Some sources (e.g. MangaDex) have multiple copies of the same chapter from various sources. It would be nice if these could be dealt with in some way.

For example, if reading ch1 from any scanlator resulted in going to ch2 when done instead of some other group's ch1.

Better yet, they're could be a filter option to just show one copy of each chapter available (arbitrarily).

I apologise if this is already possible somehow.
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by bbtora** [comment]
#1285 #1020
