### ISSUE TITLE
App Crashes on First Load

### ISSUE THREAD

**Issue by syeare** [inorichi/tachiyomi#2001]
**App Version:**
0.8.4

**System Details:**
Android Oreo 8.0.0; Device Model SM-G930FD
 
**Issue:**
Force stopping

**Other details:**
I have tried pretty much everything. I uninstalled every extension, I completely cleared app data, uninstalled and reinstalled the app. 0.8.0 and 0.8.2 work fine still, but the WebView capability for that demonic reCaptcha is not present. Unfortunately, 0.8.4 just crashes the instant I open it. If I "brute force" it and keep trying to launch it ("Tachiyomi has stopped" >> "Close App" ; "Tachiyomi keeps stopping" >> "Close App"; relaunch Tachiyomi), then it launches. However, trying to open the Extensions activity/page results in an instant crash.

**Comment by syeare** [comment]
Ah, I suppose I forgot to mention that I have tried both the F-Droid version and the apk available here. Clean wipes and installs, but the issue is the same with both of them.

**Comment by syeare** [comment]
One last thing I forgot to mention, I have tried the dev version as well. Same issue.

**Comment by pervertkirito** [comment]
can you provide a logcat?

**Comment by arkon** [comment]
Try uninstalling any extensions you have too?

**Comment by syeare** [comment]
@arkon I did mention I completely uninstalled all extensions.

@pervertkirito How do I produce a logcat? I thought it isn't possible since I can't access app settings to enable any logging/debugging.

**Comment by inorichi** [comment]
https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/

After the "Setting up ADB" section, you only need to issue `adb logcat` and then open tachiyomi. The crash should be among those lines.

**Comment by syeare** [comment]
@inorichi
I did successfully obtain a logcat, but it seems I cannot pinpoint exactly what has happened. Sorry, but I'm not an Android developer and I have less than an elementary understanding of "intents" and what a SurfaceFlinger (lol sounds funny) is. Would you like me to e-mail you the generated logcat?

**Comment by inorichi** [comment]
Yes, that's fine.

**Comment by inorichi** [comment]
> 04-24 00:16:22.642 E/WebViewFactory(20929): Chromium WebView package does not exist
04-24 00:16:22.642 E/WebViewFactory(20929): android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome

This is causing the crash. Can you install WebView from the play store and see what happens?

**Comment by syeare** [comment]
Upon updating my System WebView to the latest version (pushed to the Play Store yesterday on April 24th apparently), I tried updating and launching Tachiyomi and it worked fine. It showed the changelog on launch.

One more question, will you add some sort of method for the Web View to work without Play Services? For example, on LineageOS?

**Comment by inorichi** [comment]
WebView should come preinstalled, even if you're not running play services. Cookies now depend on WebView too, so it's sadly a requirement.

Closing since this has been resolved.
