### ISSUE TITLE
Add Og:Image in Github Settings

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#2004]
Here are some of the images which can be added 
![repository-open-graph-template](https://user-images.githubusercontent.com/25240839/56579660-60abbb80-65ee-11e9-90d1-aa3950f88744.png)
![repository-open-graph-template1](https://user-images.githubusercontent.com/25240839/56579661-61445200-65ee-11e9-9fb9-56bfd05f85d9.png)
![repository-open-graph-template2](https://user-images.githubusercontent.com/25240839/56579663-61445200-65ee-11e9-91f1-845b99c9f0a8.png)
![repository-open-graph-template4](https://user-images.githubusercontent.com/25240839/56579668-61dce880-65ee-11e9-92b0-782cb06a2992.png)
![repository-open-graph-template5](https://user-images.githubusercontent.com/25240839/56579659-60132500-65ee-11e9-9910-60a189feec35.png)

Worst one
![repository-open-graph-template3](https://user-images.githubusercontent.com/25240839/56579666-61dce880-65ee-11e9-811b-68fc81be7558.png)

@CarlosEsco

**Comment by CarlosEsco** [comment]
@inorichi  do you like any of them or want something different?

**Comment by CarlosEsco** [comment]
i like the bottom one but i think the text needs a black outline so it stands out a little more.

**Comment by hXtreme** [comment]
I vote for image no. 5 (counting from 1).
