### ISSUE TITLE
HTTP ERROR 503

### ISSUE THREAD

**Issue by Zocex** [inorichi/tachiyomi#2009]
I have the developer build r1500. i get this error when i read a manga from the source MangaDex. the extension is updated. i had this problem for months now. i was lazy to report it, sorry.

**Comment by CarlosEsco** [comment]
Go on discord and read faq

**Comment by 10zing** [comment]
Same here! Tried opening mangago. It says the same. Please help!

**Comment by arkon** [comment]
MangaGo extension has been broken for months.

**Comment by 10zing** [comment]
When is it going to be fixed 😭

**Comment by Zocex** [comment]
just clear cache. fixed my proplem

**Comment by 10zing** [comment]
Tired it multiple times..still nope!
