### ISSUE TITLE
dmzj always show retry

### ISSUE THREAD

**Issue by RtYkk** [inorichi/tachiyomi#2012]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
r1463
**Android version:**

**Issue/Request:**
It always shows retry when open mangas from dmzj, all mangas. I have reinstalled the app and extention. But useless.
Another people who use the same version and extention can read normally.
Here's the video. Open the link and enter the password you can look at the video.
https://pan.baidu.com/s/1EO0bJ08KhH6ErP1SNeB4kA      password：V98X
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
Wrong repo
