### ISSUE TITLE
tracker search is really wack

### ISSUE THREAD

**Issue by kfdz277** [inorichi/tachiyomi#2015]
**App version:** 0.8.4

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
Please edit and provide more details

**Comment by Skcyte** [comment]
Or just blame said tracker search capability.

**Comment by CarlosEsco** [comment]
Closing for lack of information
