### ISSUE TITLE
Tachiyomi keeps crashing every time I open library

### ISSUE THREAD

**Issue by NieBelek** [inorichi/tachiyomi#2017]
**App version:**
 0.8.0 and 0.8.4
**Android version: **
8
**Issue/Request: **
Tachiyomi keeps crashing every time I open library but clearing cache seems to fix the issue for a single opening. Reinstalling extensions didn't work and trying different versions. It happened after quite a while of using this app. 

EDIT: I forgot to mention that recently I've been playing around with disabling HW overlay and forcing GPU rendering in developer settings.

**Comment by DarKCroX** [comment]
Can you try update your webview?
the issue you face right now probably same with this one
https://github.com/inorichi/tachiyomi/issues/2001#issuecomment-486851653

**Comment by NieBelek** [comment]
> 
> 
> Can you try update your webview?
> the issue you face right now probably same with this one
> [#2001 (comment)](https://github.com/inorichi/tachiyomi/issues/2001#issuecomment-486851653)

Already tried yet couldn't. It was force-disabled for the user.

**Comment by hXtreme** [comment]
You may have to go to developer option on your phone then to select your web view implementation.

![here](https://i.redd.it/zm66x4ai40031.png)

**Comment by arkon** [comment]
Not enough info here. If you manage to get some logs (refer to Google on how to do so), that'd be helpful.
