### ISSUE TITLE
Update trouble. Feature request.

### ISSUE THREAD

**Issue by DaemonPhoenix42** [inorichi/tachiyomi#2019]
0.8.4

7 Nouget

Yeah, not cool. The app didn't seem to check for updates on its own so I downloaded the newest release.
It then refused to install the new version because I still had an earlier version. Decided to uninstall and manually update, now my library seems to be gone.

Rather unfortunate and dont know why auto update wasn't doing anything, nor can I recall the version I was on last but 'if possible' some manual installation protection so to speak would be appreciated. Assuming im not an edge case.

Edit: thankfully after playing around I found that I had previously enabled auto backup, thank god.

**Comment by kiriya-aoi** [comment]
Was your previous install from F-droid? The signature is different between the Github and F-droid versions, which is why it required you to uninstall before installing from here. Definitely would have recommended making a backup before uninstalling, but it's good that you had an auto-backup on hand.

**Comment by arkon** [comment]
F-Droid is being phased out so hopefully this won't be an issue in the future. We might want to consider enabling auto-backups by default to help prevent a complete library loss though. _But_, I think Android Q will delete everything on uninstall anyway.

**Comment by DaemonPhoenix42** [comment]
A yes, took me a sec to come back to this.
I do have F-Droid still and I would not rule out the possibility, thank you for the information and keep up the good work.
