### ISSUE TITLE
[Feature Request] Data Saver

### ISSUE THREAD

**Issue by Code027** [inorichi/tachiyomi#2021]
Is it possible to add a data saver for sources with huge images like Dex to lessen the data usage by changing (or lowering) the image quality as an option?

**Comment by CarlosEsco** [comment]
Unless the site has an option for lower quality images. This is not possible. Tachiyomi reads directly from the site so its going to download the full size image no matter what

**Comment by hXtreme** [comment]
There is [this thing](https://superuser.com/questions/945924/how-do-i-use-the-google-data-compression-proxy-on-firefox) that may be useful but I don't know much about how it works/would it be compatible with cloudflare/if its even working right now.

**Comment by arkon** [comment]
Unreasonably to implement from the app's side.
