### ISSUE TITLE
[Feature Request] Chapter List Pagination

### ISSUE THREAD

**Issue by DitFranXX** [inorichi/tachiyomi#2024]
**App version:** 1.x (I don't think it can be implemented on 0.x)

**Issue/Request:** Support Pagination on Chapter List. (Like on browse manga)

**Other details:** I want to implement a new source that has pagination on chapter list.
I can't find chapter list pagination related functions on 0.x stubs. also on main codes too.
I don't think 0.x supports this. because development of 1.x is on the way. 

ps. This request is extension related, but it is need to implement on tachiyomi (main-app) side. So I posted issue at here.

**Comment by CarlosEsco** [comment]
how many pages?  you could just pull all pages/chapters using the existing methods

**Comment by DitFranXX** [comment]
![image](https://user-images.githubusercontent.com/45893338/57292731-99bf5200-70fd-11e9-8c41-c67f9bee52d4.png)
I just grab any manga on planned source. it's 29 page.
And How can i pull chapters just in a method? I can't find it.   (There's no json nor api iirc.)

**Comment by CarlosEsco** [comment]
wow lot of pages this will cause a lot of http requests to go out but you could override

fetchChapterList
and loop through network calls while the page exists

**Comment by DitFranXX** [comment]
Thanks. I will try it.

I remain this issue as open because that is not a perfect solution. (lots of requests at once seems not good)
Maybe it can be implemented as like on browse manga in catalog, with something... `override fun chapterListNextPageSelector()`

**Comment by inorichi** [comment]
It should be possible, but I think in those cases it'd be better to just use their webpage and handle deeplinks to open the series back in tachiyomi.

**Comment by inorichi** [comment]
Sorry, I misunderstood the request. I automatically thought it was related to search... I'm not sure we can properly support that, as we need to know whether chapters have been removed...

**Comment by inorichi** [comment]
Btw, do they reload the entire page when you change the page? That seems like a waste and I think they might have some JS to only reload that part. In this case it shouldn't be too problematic, but still a lot of connections, sadly.

**Comment by DitFranXX** [comment]
Yeah, They reload whole page.

**Comment by CarlosEsco** [comment]
such a weird way to paginate a page.

**Comment by DitFranXX** [comment]
If I use mobile page, can reduce requests but it still 10 page. (same one)

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
