### ISSUE TITLE
Double tap zoom sometimes flip the page over

### ISSUE THREAD

**Issue by yshui** [inorichi/tachiyomi#2026]
**App version:** 0.8.4

**Android version:** 9.0

**Issue/Request:**

I can *sometimes* flip the page over (upside down) with double tap zoom.

**Steps to reproduce (if applicable)**

 1. Open an affected page
 2. Double tap
 3. Move finger quickly to the top of the screen

**Other details:**

Only some of the pages are affected, this problem seems to be consistently reproducible on those pages, but not at all on other pages.

When this bug happens, the page will zoom a little bit when I double tap but don't let go. Other pages don't do that, page will only start to zoom if I move my finger after double tapping.

**Comment by inorichi** [comment]
I think this only happens on .gif pages. If so, I was aware of it, but sadly it's a bug of a dependency.

**Comment by arkon** [comment]
Rare enough bug that it's not worth fixing.
