### ISSUE TITLE
Webtoon viewer bug

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#203]
When scrolling, sometimes it'll jump to a random page. 

Here's the logcat. Its in 8:24.

https://drive.google.com/file/d/0B59RgF7gPCFkNi1NU1JKS0FCaEk/view?usp=docslist_api

**Comment by inorichi** [comment]
Version?

**Comment by Syborg49** [comment]
The stable release, so 0.1.4

**Comment by inorichi** [comment]
It must be because it loads a previous image and the height is recalculated. The view doesn't know the height of the image, and it's probably resized after a load. Nothing I can do about that.
