### ISSUE TITLE
The progress bar animation causes the app to crash on some android systems

### ISSUE THREAD

**Issue by timchenggu123** [inorichi/tachiyomi#2035]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.0

**Android version:** 5.1.1

**Issue/Request:** progress bar animation in reader activity causes the app to crash

**Steps to reproduce (if applicable)**

 1. Open the app
 2. Try to open any chapter
 3.result in a crash

**Other details:**
The bug is temporarily fixed by commenting out "animation.show()" The animation is a rotationanimation

**Comment by inorichi** [comment]
What is "some Android systems"? I'd need you to be more specific.

Also, can you provide a stacktrace of the crash?
