### ISSUE TITLE
Long press to change category

### ISSUE THREAD

**Issue by Glasses-are-90-me** [inorichi/tachiyomi#2036]
**Issue/Request:** Ask for category when long pressing Blue Button at manga page

**Steps to reproduce (if applicable)**

 1. Go to a manga page (Image Below)
 2. A short press should default to user defined category in settings -> General
 3. A Long press should allow the user to pick what category they want it in

**Other details:**

So for example lets say I want to move Internet explorer to another category and my default category is "To be read", to do that I would have to go out, and long press the manga and select it to move into a category. This is fine if you have just chosen it from my library. but if you were looking for manga from a source you would have to exit out of your search to place it in the correct category.
All I am saying: Long press:
![image](https://user-images.githubusercontent.com/17042136/57777958-6c5e4e00-7766-11e9-99ce-e695b6d731ad.png)
should end with something like this:
![image](https://user-images.githubusercontent.com/17042136/57778741-07a3f300-7768-11e9-820c-41342b86b45e.png)

**Comment by hXtreme** [comment]
Currently you would have to remove and re-add it to the favorites to change categories from that page. This seems like a fairly intuitive solution.
