### ISSUE TITLE
[BUG] Site "shikimori.org" is blocked in Russia

### ISSUE THREAD

**Issue by vadwave** [inorichi/tachiyomi#2037]
App version: 0.8.4

Android version: 5.1

Other details:

The site "shikimori.org" is blocked in Russia because of video content. They transferred everything to the site "shikimori.one" by removing video content from there. It would be desirable to change the tracking from the site "shikimori.org" to the site "shikimori.one", accounts should work fine on it.

https://shikimori.one/forum/site/284085-ban-kto-vinovat-i-chto-delat

**Comment by Taumer** [comment]
#2038

**Comment by Pavkazzz** [comment]
@CarlosEsco Already fixed
