### ISSUE TITLE
[Feature Request]Tracker anime-planet.com

### ISSUE THREAD

**Issue by Fahad1998** [inorichi/tachiyomi#2039]
Any plan to add anime-planet.com tracker?

**Comment by de-odex** [comment]
tag with [Feature Request] please

**Comment by Vesnyx** [comment]
Dupe of my issue here #1785 . I'm currently planning on adding this in once the app hits the 1.0 milestone. I don't know if it'll impact the authentication methods currently used and I'd rather have it done all at once. :)
