### ISSUE TITLE
[Feature Request] Rename Manga

### ISSUE THREAD

**Issue by lewdnasty** [inorichi/tachiyomi#2040]
**App version:**
1.0
**Android version:**
9
**Issue/Request:**
A feature to rename manga/comics for organizing.
**Other details:**
Locally changing the display name for specific comics might help while quickly browsing, especially when using multiple sources to sync a single franchise. An example would be the Avatar comics. One source lists them as "Nickelodeon Avatar", while another lists as "Avatar". Since they're all separate stories but in the same universe, I'd like to list them all alphabetically so they reside together. Same could apply to arcs, a la Jojo. Alphabetically they wouldn't line up, but with a "Jojo - 1", "Jojo - 2" etc etc it could allow for numerical sorting. The category system sort of solves this but also doesn't solve the issue of certain arcs being chronologically out of order.

**Comment by hXtreme** [comment]
An Alias for each manga seems like a reasonable thing.

**Comment by hXtreme** [comment]
Okay, on some research it seems like just adding an Alias field would break backwards compatibility and some extra effort may be required to pull it off.

**Comment by ZaneHannanAU** [comment]
The alternative is editing the available information

**Comment by hXtreme** [comment]
@ZaneHannanAU  how do you expect the edit to take place? From what I had in my mind, it may cause some people to have manga stored in the old way and others in the 'new' way. If that happens then, tachiyomi would have to supply the 'editing' code for every future release ever.

**Comment by ZaneHannanAU** [comment]
Edit the title field, artist field, author field, status field, description textarea and tag/category data

**Comment by hXtreme** [comment]
Those edits would be lost every time meta-data is updated.

Harsh

**Comment by ZaneHannanAU** [comment]
Could be marked as edited or use a mask for edit information

**Comment by hXtreme** [comment]
But then you would have to store the mask information and so you would have to makes changes to the how Manga are stored and that would take us back to the same problem.

**Comment by ZaneHannanAU** [comment]
If we take the lack of a mask as a sign of not being edited, it may work.

**Comment by inorichi** [comment]
If you believe this is a useful feature, propose it for 1.x. I prefer not to update the database unless it's very important.

**Comment by hXtreme** [comment]
@lewdnasty can you update this request Title with [1.x] ?

**Comment by inorichi** [comment]
I'd prefer to use tags. I'll add it for now but I don't know yet if it's going to be implemented.

**Comment by hXtreme** [comment]
@inorichi regardless of if you implement this can you add some meta-data to the database itself? 
So, the database would have a meta-data saying the 'standard' of the database, this might help if in the future we want to update the database; we can increment the standard and use it to decide how to access the database.

**Comment by fieldhouse** [comment]
If we stuck with using tags could a filter string or additional tag be added to tags so they don't show as new categories and instead override the displayed title?
Personally, i'd just be happy with being able to add a text description to help me remember that [`Asobinin wa Kenja ni Tenshoku Dekiru tte Shittemashita?: Yuusha Party wo Tsuihou sareta Lv99 Doukeshi, "Daikenja" ni Naru`](https://myanimelist.net/manga/120354/Asobinin_wa_Kenja_ni_Tenshoku_Dekiru_tte_Shittemashita__Yuusha_Party_wo_Tsuihou_sareta_Lv99_Doukeshi_Daikenja_ni_Naru?q=asobinin%20wa) is the manga I refer to as `2 Shortstacks and a Sage`

**Comment by quangkieu** [comment]
How about if we somehow tight the mange to those tracker site that I saw we already have. Lookup by combo of Title and Author name (First_Last Name or Last_First as source may use different syntax). From those tracker, most likely that you would have the Alias name to display that could be append as special tag `:Alias Name:`. For more correct match, we could use first tracker alias + title + author combo to map to another tracker. 2 or more tracker that have same alias + title + author would nearly unique.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10

**Comment by joseph619** [comment]
It would be nice to edit the metadata of the manga (author, tags, description) and not just the title. And also support backup for the edited manga.
