### ISSUE TITLE
[Improvement] Use Daiz's manga page naming scheme

### ISSUE THREAD

**Issue by AbdulrahmanHadz** [inorichi/tachiyomi#2043]
For 'Save' in the manga reader, the pages that are saved are named _Series Name - **Vol.x Ch.y**_ Can it be changed so that the chapter number is sorted first so that no matter if a series has volume numbers or not, it'll sort in ascending order of chapter. 
![image](https://user-images.githubusercontent.com/35078604/57982376-a1a3be00-7a3c-11e9-91c6-6a5f77e81303.png)
The pages can be saved using this name scheme which makes sure that a series' pages are always sorted by chapter number.
![image](https://user-images.githubusercontent.com/35078604/57982385-c730c780-7a3c-11e9-9741-11a240256ce8.png)

**Comment by inorichi** [comment]
Thanks. I'll consider this scheme for 1.x. I don't want to break compatibility with the existing downloaded chapters.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
