### ISSUE TITLE
ComicRack/comixology-like zooming/scrolling

### ISSUE THREAD

**Issue by HamzahNizami** [inorichi/tachiyomi#2046]
App version: 0.84

Android version: 9

Request: Hi there, I wanted to say I just stumbled across your app, and I think it's amazing. I was wondering if it would be possible to implement certain features in the reader. I was hoping to see something that could allow users to navigate through each "block" of the comic page and also, a feature where if the user pressed and holds (hovers) over a certain a part of the page, this part is zoomed in. I'm finding it quite difficult to explain it haha, so I've attached a video.

Scrolling Feature - 

![ScrollingFeature (1)](https://user-images.githubusercontent.com/32271819/58216190-494b1580-7cf5-11e9-906e-910ae3dce8c3.gif)

[ScrollingFeature.mp4.zip](https://github.com/inorichi/tachiyomi/files/3209737/ScrollingFeature.mp4.zip)

ZoomInFeature - 

![ZoomInfeature](https://user-images.githubusercontent.com/32271819/58216204-6253c680-7cf5-11e9-8bf8-37982e52728a.gif)

[ZoomInfeature.mp4.zip](https://github.com/inorichi/tachiyomi/files/3209738/ZoomInfeature.mp4.zip)

I have no idea if this is even possible, but it sure would be awesome!

Thanks in advance

**Comment by hXtreme** [comment]
Zoom in sounds feasible but scrolling, I believe would require a reasonable amount of image processing and then too it might fail with spreads that have unusual layouts.

**Comment by arkon** [comment]
Can pretty much guarantee this won't be happening unless there's someone interested in implementing it.
