### ISSUE TITLE
[Improvement][1.x] Make viewers into extensions

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2047]
There are a number of issues that request more and more features from the manga viewer. 

#2010, #2046, #1997, #1977, #1894(if we move things to another viewer), #1649, #1558, #2062  

While a lot of them are interesting to have, I believe that not everyone needs them and including all the varied feature would bloat up the source code. Instead if viewers could be installed as extensions then anyone who really wants a particular feature could in theory make a viewer and use it.

**Comment by arkon** [comment]
I'm not sure if there's any benefit to this from an engineering perspective.

**Comment by hXtreme** [comment]
Option 1: We have one viewer with all (say 10) features which could be turned on or off.  
Here, every time a new one if added extensive amounts of testing would be required about 2^10 many tests. These tests would more or less be required because some features can conflict with others and we need to understand how those conflicts are resolved. Which is bad/tedious!

Option 2: We have multiple viewers bundled together (the current option).  
This solves the problem encountered in Option 1 but every time a new viewer is submitted inorichi (he already has a lot of stuff to do) would have to sign off a pull request and everyone would only receive it on app updates.

Option 3: Viewers are made into extensions (and maybe a few default ones are bundled together).  
This option allows viewers to be updated independently and the development of viewers could follow the same principle as the development of tachiyomi-extensions(where inorichi doesn't have to do most of the work).

**Comment by metroid112** [comment]
How would you use different viewers in the app? Change them in the same menu as rotation/orientation settings while reading a chapter?

**Comment by hXtreme** [comment]
Yes, I guess that would be the best way and infact kind of how it is right now with webtoons viewer.

Harsh

________________________________

**Comment by inorichi** [comment]
That'd be a real pain. I prefer to have them internal and add many configurations.
