### ISSUE TITLE
Issues with MAL

### ISSUE THREAD

**Issue by Justtaway** [inorichi/tachiyomi#205]
- [ ] Need to manually edit title, only after that app recognized manga

- [x] If I enter chapter number manually and DON'T click on it, it doesn't update. It also updates fine when scrolling.

---
Version: v0.1.4
OS: 4.2.2
I tried reproducing the bug in r545, but app kept closing after opening manga (not chapter)

**Comment by inorichi** [comment]
I'll review this when I migrate MAL to Kotlin.

**Comment by inorichi** [comment]
The second one is already fixed. I didn't understand the first one. It does an initial search when you click "edit", but if not results are found it will be empty, so you will have to remove some words/characters. Was that the problem?

**Comment by Justtaway** [comment]
Shouldn't it recognize manga automatically when adding? I thought it is, that's why I labeled it as bug. Maybe should've labeled as Feature Request?

**Comment by inorichi** [comment]
How do you "recognize" it without doing a search before? You can end binding it to another one with the same name, or maybe the user doesn't want to track that one. That's why binding is a manual step.

**Comment by Justtaway** [comment]
Got it, thanks for answering.

**Comment by inorichi** [comment]
:+1: Closing then.
