### ISSUE TITLE
[Feature Request] Separate notification categories

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [inorichi/tachiyomi#2050]
**App version:** 0.8.4

**Android version:** 9.0

**Issue/Request:**
Separate the android notification categories when:
1. Scanning for updates
2. When updates **are found** -- this Category is ideally to be added

**Actual use case**:
Setting notification sound for when updates are found, but not _during_ just the search/scan.

**Problem**
When setting notification sound for **Library**, you will hear that sound you set on **both** during the scan, and when updates are found, which is not the ideal scenario when you want to be "notified".

**Steps to view the categories:**

 1. Go to Tachiyomi app settings. When using Nova Launcher, this is done by long pressing Tachiyomi, then select "App info".
 2. Go to notifications
 3. You will now see the 3 categories: Common, Downloader, and Library

Also, please refer to [this screenshot](https://imgur.com/a/dhK1QyM) for the actual image.

**Other details:**
I believe you will tag this as duplicate of [#1602](https://github.com/inorichi/tachiyomi/issues/1602), but I posted anyways since that post doesn't seem noticed at all (no comments, no reactions, no nothing).

**Comment by eji30** [comment]
Up

**Comment by eji30** [comment]
Up

**Comment by arkon** [comment]
@eji30 Stop trying to bump the issue.

**Comment by arkon** [comment]
This should be fixed now.
