### ISSUE TITLE
[BUG] Long pressing bookmark icon moves manga to default category

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2051]
**App version:**
v0.8.4 r1511
**Android version:**
Android 9
**Issue/Request:**
Long pressing the bookmark icon inside the manga info page changes the category to the default one (set inside the settings). 

I assume the original behaviour of the long press is to open the dialog box to choose the category.  

This relates to #2045

**Steps to reproduce (if applicable)**

 1. Open a manga info page present in a different category
 2. Long press the bookmark icon
 3. Manga moves to the default category

**Comment by hXtreme** [comment]
I actually really like that the category dialogue box pops up but if there's enough support for this then I'll open a PR.

**Comment by bbtora** [comment]
I'm reporting a bug, not a feature request.

**Comment by hXtreme** [comment]
Damn it me!

**Comment by hXtreme** [comment]
Thanks! Can you attach a video or something showing the bug?

**Comment by bbtora** [comment]
Sorry I will not be able to provide a video. Please see if you can reproduce the bug through the steps provided.

**Comment by hXtreme** [comment]
Okay, the reason why I was asking for it is because the logic would first move it to default and then once you select the categories it assigns it to the selected categories.

Plus my code is mostly just a copy of some pre-existing code so this bug should also be present there.

**Comment by bbtora** [comment]
Started with showing that "Currently Reading" is the default category. 

![2019_05_26_08_16_56](https://user-images.githubusercontent.com/23010526/58376726-b88f6680-7f8e-11e9-8fcf-b06ee23fdc46.gif)

**Comment by hXtreme** [comment]
Thanks this helps a lot! I'll get right on it.

**Comment by bbtora** [comment]
Looks like the dialog box for selecting category (on long pressing bookmark) only appears when "default category" is set to "always ask" in settings.

**Comment by hXtreme** [comment]
Yes, I've made the changes and in about 20 minutes (if nothing breaks) a PR should be up.

Thanks again, I never knew that there we could set default categories so it went under my radar during testing.
