### ISSUE TITLE
[Bug] Selecting Help gives "Open with <app>" prompt.

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2053]
On selecting Help the "Open with ..." prompt appears. Then regardless of what is selected there it opens it in Web view.

[See](https://youtu.be/Q8BQP4AcyqU)

Expected behavior: Open it in web view without any prompt.

**Comment by inorichi** [comment]
I think that's the expected behavior. The code uses `openInBrowser`, and when you selected chrome it used a chrome tab, not a webview.

**Comment by arkon** [comment]
Yes, I did intentionally choose to make it open in the browser instead of the WebView. Do you think it'd be better to have it in the WebView, which has very little functionality?

**Comment by hXtreme** [comment]
Opening it in web view would seem more integrated.

**Comment by hXtreme** [comment]
@inorichi if you look at the video, the browser looks nothing like chrome.

**Comment by arkon** [comment]
It's a custom tab, it's definitely Chrome.

**Comment by MerradOklom** [comment]
There is a blank space between Settings and Download Queue since Help was added. Maybe this is because of my phone resolution? It is not much of a problem, just reporting. 
![Screenshot_2019-05-26-13-09-00](https://user-images.githubusercontent.com/43864503/58384491-70853980-7fb8-11e9-9063-9c03abb53684.png)

**Comment by arkon** [comment]
@MerradOklom That's always been there.

**Comment by MerradOklom** [comment]
@arkon I see, sorry. Maybe I didn't pay enough attention before.

**Comment by inorichi** [comment]
I prefer the browser. The only reason we use webviews is to share cookies and allow to bypass the cloudflare challenge and captcha.
