### ISSUE TITLE
Chapter closes on Reopening the app via either Home Screen or App Drawer

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#2054]
Originally posted as https://github.com/inorichi/tachiyomi-extensions/issues/1136 by @thesidejoe

---

Versions:
occurs on dev build r1504 (tested on Pixel XL 2016 Android 9)
occurs on dev build r1506 (tested on OnePlus 7 Pro Android 9 Oxygen OS 9.5.3)
occurs on stable build 0.8.4 (tested on OnePlus 7 Pro)
does NOT occur on stable build 0.7.4 (tested on Pixel XL 2016)

From the looks of it the source of the manga does not matter, although was only tested with MangaDex and one Boredom Society manga.

When reading a chapter, if you change to another app by multitasking or if you press the home button and then tap the app icon for Tachiyomi either via the home screen or the app drawer, the chapter closes. If you tapped to read the chapter either from the library or the updates tab, the screen will go back to the chapter list or the updates page respectively. This does not happen if you reopen Tachiyomi through multitasking, thereby avoiding tapping the app icon.

---

Probably related: https://www.reddit.com/r/androiddev/comments/9shz1a/_/

**Comment by SyntaxError1871** [comment]
Same. Getting this behavior on dev version r1512. 

I don't get the open chapter closing if I switch out of the app and select another app through the app drawer function however.

**Comment by hXtreme** [comment]
I think that I've seen this as well. (On version 0.8.4)

**Comment by MCAxiaz** [comment]
@inorichi Do you remember the exact issue changing launch mode to singleTask was supposed solve?

Doesn't seem like there's an easy way of fixing this other than not using singleTask.
https://stackoverflow.com/questions/2417468/android-bug-in-launchmode-singletask-activity-stack-not-preserved
