### ISSUE TITLE
[Feature Request] Add "Volumes" under MAL Tracking.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#2061]
Would it be possible to implement  "Volumes" as an option under the tracker menu for MAL? It's only for ***manual adding***, as I don't think the app can recognise how many chapters constitute a single volume, since each manga is different.

Many people (including myself) like to mention the number of volumes they've read in a manga, so I think this addition would be useful. That is all.

**Comment by bbtora** [comment]
#505
