### ISSUE TITLE
[Request] Repeat Gifs

### ISSUE THREAD

**Issue by sneger** [inorichi/tachiyomi#2064]
Would it be possible to add so gifs repeat themselves in the app? currently they only play once then stop, I think that would be a great addition to the app

**Comment by ZaneHannanAU** [comment]
?
It currently does.
https://helveticascans.com/r/series/wonder-cat-kyuu-chan/

![Example image](https://i.imgsir.com/w0BK.gif)

![It is displayed](https://i.imgsir.com/pbJR.png)

**Comment by ZaneHannanAU** [comment]
And animated on repeat as well

**Comment by ZaneHannanAU** [comment]
It's possible that the site you're on has opted into using *n* loop GIF type, rather than ∞ loop GIF.

**Comment by sneger** [comment]
I'm using the app and browsing Exhentai, I just tested another gif collection and it seems to repeat itself but it's playing way too slow and not the speed it should

**Comment by arkon** [comment]
Sounds like you have a lower range phone. Also, are you using a fork? Tachiyomi doesn't have Exhentai.

**Comment by sneger** [comment]
I'm using a galaxy 8 and yes sorry, I am using TachiyomiEH

**Comment by ZaneHannanAU** [comment]
In that case, bug NerdNumber9/TachiyomiEH about it iirc

**Comment by inorichi** [comment]
Seems this is not a tachiyomi issue. GIFs do repeat themselves.
