### ISSUE TITLE
Refresh Downloaded manga count

### ISSUE THREAD

**Issue by GyanPreet** [inorichi/tachiyomi#2065]
**App version:**
0.8.4
**Android version:**
OxygenOS 9.0.13
**Issue/Request:**
Refresh the download count of downloaded Mangas. 
**Other details:**
if there is a bug deleting the Mangas or you delete them directly from file manager the downloaded badge still shows #n Mangas downloaded and the only way of removing it is by completely deleting the Manga and re adding it to your library.  I don't know how hard is to implement, as I'm not a developer, but it would need to read local files to check if the Manga is actually in the local storage.

**Comment by CarlosEsco** [comment]
@inorichi  this is probably the cache thing i mentioned on discord.

**Comment by ZaneHannanAU** [comment]
If you close and reopen tachi it clears it. I have done it before.

**Comment by GyanPreet** [comment]
Thank you, it was probably that I left it in the background without clearing the process.
