### ISSUE TITLE
[Issue] Status bar is not hidden on rotation

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#2068]
**App version:**
0.8.4 and r1512 (any? even TachiyomeEH and Neko)
**Android version:**
9.0.0 (Honor Play)
**Issue/Request:**
The status bar is not hidden on rotation
**Steps to reproduce (if applicable)**

 1. Open the manga in portrait orientation
 2. Allow free rotation in the system and in the app
 3. Rotate device into the album position

**Other details:**
The status bar hides after triggering menu by tapping in the middle of the screen. I don't know if it is related but my device has a notch and I use fullscreen mode.

**Comment by arkon** [comment]
Can't reproduce on a OnePlus 5T. Did you try with fullscreen mode off?

**Comment by serjflint** [comment]
I was wrong about Android's fullscreen mode. It was on another app. It only appears on the first time after opening the chapter or after opening-n-closing menu by tapping in the portrait mode. Sometimes the status bar becomes transparent or picture rotates in a different direction (upside down). I'll test on OnePlus 3T today. Before it was Honor Play.

**Comment by Flat** [comment]
Can reproduce
![screenturn](https://user-images.githubusercontent.com/2048861/58884684-deafb780-86ae-11e9-894a-66e27e3001ba.gif).
OnePlus 5T

**Comment by serjflint** [comment]
Tested on OnePlus 3T Android 8.0.0. Not even one of the issues mentioned above.

**Comment by arkon** [comment]
Okay I tried a bit more and it happens randomly.

**Comment by serjflint** [comment]
For me flipping is random but status bar appears on every opening of the chapter

**Comment by bsdfun** [comment]
Can reproduce on tablet (lineageos, android 9) and phone (miui, android 10) with stable and dev build (r2076). Status and navbar (buttons) appears randomly when rotate device between landscape and portrait mode.
