### ISSUE TITLE
[Feature Request] Add HBrowse as an extension

### ISSUE THREAD

**Issue by Jzarecta** [inorichi/tachiyomi#2073]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
latest

**Android version:**
latest

**Issue/Request:**
Add hbrowse.net doujins to the extension plugin

**Steps to reproduce (if applicable)**

 1. Go to Cataloges
 2. Select HBrowse
 3. Add it and search on it

**Other details:**
Be able to browse and download their doujins

**Comment by MercerBoi** [comment]
It is literally mentioned in the post template (which you didn't bother to either read, or remove from the post itself) that this is not the place for requesting new extensions...
