### ISSUE TITLE
App Constant Crash when Download Multiple Different Manga

### ISSUE THREAD

**Issue by RatchetNine76** [inorichi/tachiyomi#2074]
App version: 0.8.4

Android version: 9

Issue/Request:App will instantly crash when I download new mangas from mangadex. 

Steps to reproduce (if applicable)

 1.in catalogue, go to any sources (Mine is either mangadex or kissmanga) open latest
 2.open any manga there, bookmark it then download all
 3.go back to latest, then open another different manga and do the same step 2.
 4.repeat until it will instantly crash. (in my case, usually in 3 -4 manga)

Other details: In latest Update page when I refresh, it works fine and that there is no crash. but when I read new mangas that I am interested in, I downloaded those new mangas and then it crashed when it was 3-5 mangas that i bookmarked and download all.

**Comment by hXtreme** [comment]
By bookmark do you mean add to favourites? Or is it bookmarking a chapter?

Also, does your phone have sufficient storage space? Something similar had happened to me when my phone had ran out of space.

**Comment by arkon** [comment]
Can't reproduce.
