### ISSUE TITLE
Tachiyomi not detecting manva released.

### ISSUE THREAD

**Issue by RYNAPU** [inorichi/tachiyomi#2075]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4
**Android version:**
9.0 Pie June 2019 Security Update
**Issue/Request:**
New chapter for manga is released and viewing the manga info view the "open in browser" option shows it but the app won't show it in list of current chapters despite refreshing in manga selection and library update.
**Steps to reproduce (if applicable)**

 1.NA
 2.NA
 3.NA

**Other details:**
Currently happens on Manga Dex and haven't seen issue on other sources.

**Comment by ZaneHannanAU** [comment]
Is the chapter accessible over webview?

If not, then it's a non-issue. Currently we filter out chapters that will only exist in the future.

**Comment by ZaneHannanAU** [comment]
Example:

![On a browser](https://i.imgsir.com/57eN.png)

![The chapter](https://i.imgsir.com/ap70.png)

![In tachiyomi](https://i.imgsir.com/jDM5.png)

![Using the ComiCake reader on the original site reader](https://i.imgsir.com/2b0P.png)

**Comment by ZaneHannanAU** [comment]
Also appears to be an issue in extension catalog. So uh… please read the template.

**Comment by RYNAPU** [comment]
@ZaneHannanAU yes I can view in web view and the chapter has been released and fully viewable, but Tachi doesn't see it.

**Comment by CarlosEsco** [comment]
What manga. And are you sure you are in the correct language for the chapter?

**Comment by ZaneHannanAU** [comment]
@RYNAPU can you link the chapter or manga? Also please provide screenshots as otherwise it will become difficult to see issues that occur.
