### ISSUE TITLE
Adding Request: toonily & mangafull Source

### ISSUE THREAD

**Issue by Varne01** [inorichi/tachiyomi#2076]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4
**Android version:**
7.0
**Issue/Request:**
Request
**Steps to reproduce (if applicable)**
 1.
 2.
 3.

**Other details:**

https://toonily.com/ 
https://mangafull.org

for another manga/manhwa free source

**Comment by MercerBoi** [comment]
Here's a tip: Read the first sentence of your issue, written in bold and block letters.

**Comment by ZaneHannanAU** [comment]
There have been a lot of these sorts of uh requests

People keep on making requests whilst including the header... if they're not English I can understand it but uh

…

```markdown
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**
```
