### ISSUE TITLE
Remove from queue after read

### ISSUE THREAD

**Issue by jasonhpchu** [inorichi/tachiyomi#2077]
r1512

So if you have a chapter in queue (not downloaded), and you go ahead and read that chapter without it downloaded.
With the option to delete chapter after read, it doesn't clear the queued chapter.
Long select the chapter and press delete does remove it from queue.
So my guess is the two delete action isn't running the same function.

Thanks.

**Comment by Jerrk** [comment]
Could also override the queue and download the chapter as it is opened which i think might fix the problem as well.
