### ISSUE TITLE
Source migration stuck on lading

### ISSUE THREAD

**Issue by taksaru** [inorichi/tachiyomi#2078]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.84

**Android version:**
9, oxygen 9.0.4
**Issue/Request:**
Attempting source migration from Mangadex, sources aren't loading after search starts(left searching for 30 secs+
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by taksaru** [comment]
The search also stays loading when using search for all catalogues

**Comment by arkon** [comment]
What extensions do you have installed? Does this stop happening if you try uninstalling some of them?

**Comment by taksaru** [comment]
Issue was with the first version of manga plus extension
