### ISSUE TITLE
[Feature Request] Deleted Chapter Notification

### ISSUE THREAD

**Issue by AiEsper** [inorichi/tachiyomi#2079]
**App version:**
0.8.4

**Android version:**
Android 9.0 Pie

**Feature Request:**
After some internet drama, can you please make a notifcation/warning if there is a deleted chapter or when there is a difference in server and local file
![Screenshot_2019-06-13-12-04-23-316_eu kanade tachiyomi](https://user-images.githubusercontent.com/27928013/59405492-d523ff00-8dd4-11e9-9dc7-1155b82ff017.png)

**Comment by CarlosEsco** [comment]
Not really something feasible currently or really makes sense with current architecture. 
When you got  chapter list its the cached version of last time you went.  If you swipe refresh and the chapters are missing from the website it just removes them from the list so no need for a deleted marking.  If you wanted to keep removed ones then anytime a site renamed a chapter it would show as deleted and your list starts becoming populated with dead chapters.
