### ISSUE TITLE
[feature request] Adding MyAnimeList ratings to the each series.

### ISSUE THREAD

**Issue by CheesyLadd** [inorichi/tachiyomi#2080]
I'd love to have a MAL rating next to the description of manga series. It might not be possible, but it would make our lives a ton easier when browsing for random manga series to read.

**Comment by MercerBoi** [comment]
Sounds good, maybe throw in AniList ratings into the mix as well.

**Comment by eshanrh** [comment]
How would we decide which one to use? Perhaps there should also be an option to toggle between AniList and MAL ratings because the choice is subjective. It's definitely redundant to include both of them

**Comment by arkon** [comment]
This is too difficult to achieve since we don't control the source data.
