### ISSUE TITLE
Tachiyomi Source List empty

### ISSUE THREAD

**Issue by wamwamtan** [inorichi/tachiyomi#2088]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
Stable 0.8.4
Dev r1515

**Android version:**
Android 9

**Issue/Request:**
I usually use the dev version and because of Manga pull issues from r1471, I updated ro r1515 but now all the sources in the app are gone, tried on both Stable and Dev. When I try to reinstall r1471, the sources are there but there are pull issues., possibly from having the sources not updated.

**Comment by arkon** [comment]
Install them from the extensions section.
