### ISSUE TITLE
Add new source: 8muses 

### ISSUE THREAD

**Issue by darkDaiyo** [inorichi/tachiyomi#2090]
https://www.8muses.com/comics

It has all the rare and famous western adult comics which isn't available even on E-hentai. This is a must website for western adult comics.

**Comment by pervertkirito** [comment]
Wrong repo dude, you should post it on https://github.com/inorichi/tachiyomi-extensions/

anyway, someone already request it here https://github.com/inorichi/tachiyomi-extensions/issues/542
