### ISSUE TITLE
[Feature Request] Extend Cache size.

### ISSUE THREAD

**Issue by XavierSchiller** [inorichi/tachiyomi#2091]
App Version: 0.8.4

Android Version: 9.0

Issue/Request: 
1. Extend cache size for manga. Either that or make it variable. This feature is already present in Tachiyomi-EH, so it's implementation isn't impossible.

**Comment by hXtreme** [comment]
I think that those two requests should be feature requests.

**Comment by XavierSchiller** [comment]
Separating it as two.

**Comment by inorichi** [comment]
Do you feel the current value isn't enough? I don't like adding user settings if there isn't a strong reason for it. I've never had issues with the current cache, that's why I'm asking.

**Comment by XavierSchiller** [comment]
Yes, I do feel that the current value isn't enough -- partially because of how much is read and how much people jump between manga at any given point. It isn't uncommon to read another manga while in the middle of another, but I believe that the settings is set low enough that when I do re-visit the original manga once more, they pages have to be re-downloaded before I read them. While this doesn't need to be directly under the settings; Since you can just double it (Although, it is unadvised.) A more prominent solution is to increase the cache size itself. 

This by any means isn't a strong enough reason; However, adding this is QoL addition that can be imported without much effort from the EH variant of the application. 

This can go to 1.X however, since this is a QoL.
