### ISSUE TITLE
Cant load from a curtain source after updating

### ISSUE THREAD

**Issue by velocity-nova** [inorichi/tachiyomi#2092]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
V0.8.4
**Android version:**
9
**Issue/Request:**
Issue
**Steps to reproduce (if applicable)**
I can't load items from (ReadMangaToday) after updating and can't find it in extensions

**Other details:**
I still have them in my library but it now says it's source is now the number (8)

**Comment by CarlosEsco** [comment]
read 1st line when making a ticket

**Comment by arkon** [comment]
Also, it's definitely in the list.
