### ISSUE TITLE
[Feature Request] Download From cache

### ISSUE THREAD

**Issue by XavierSchiller** [inorichi/tachiyomi#2094]
**App version:** 0.8.4

**Android version:** 9.0

**Issue/Request:** 
Download from cache. If a manga already exists within the cache, it makes sense to download it directly from the cache rather than request the same image from whatever source.

**Comment by Seflyx** [comment]
I just made a pull request regarding your request. However it can only use cached image from the same source, so same manga different source still need you to redownload the whole thing since the cache manager user URL hash key as parameter.

**Comment by XavierSchiller** [comment]
No, that's fine. I'm asking for the same source anyway.

**Comment by XavierSchiller** [comment]
I see you've already done what I asked for. I guess I'll keep this issue thread alive till the pull request is accepted?
