### ISSUE TITLE
[Feature Request]more flexible gestures when change pages

### ISSUE THREAD

**Issue by pkszzcq** [inorichi/tachiyomi#2096]
App version:0.8.4
Android version:9.0
Issue/Request:When I turn the page down with a gesture, I have to slide the finger from right to left accurately.But it's easy to make my fingers tired,or sometimes the operation is invalid because I am not sliding enough standard.
If the gesture can be more flexible,including oblique and curved,I think there will be a better reading experience.

**Comment by ZaneHannanAU** [comment]
Currently you can tap or use volume buttons (see settings -> reader for volume buttons).

**Comment by arkon** [comment]
This is standard Android behaviour.
