### ISSUE TITLE
better manga language filter

### ISSUE THREAD

**Issue by Bekon241** [inorichi/tachiyomi#2098]
rev da3ea5

Hi :)
Can u add filter for language choice for manga looking, site with multi-lang have wierd system one site use manga title and "Manga Title(language)" Other Use this only for chapters example manga title is only one time on list but chapter use "bad company"(pl) This is problematic coz if i look manga on site i not find any polish title before i not click manga title and look chapter list with proper writed filter. **Can u upgrade code and use global filter for bouth manga (left side) and chapter (right side) but use program like this... I mark [X] i wont only Polish manga and program filter looking all chapters + manga title and if in txt or title tags (pl) (pol) (polish) just give me all title on (left side) program window but i wont only fillter work globaly for all chapters and title...** Coz if not some site is hard for navigation coz i have 3500 manga titles and i must click 1 by 1 and (look right side) if any match for filter... This is anoing... Thx. Cheers from Poland.

Test:
**Botato** manga list (work good) coz 
**_Manga list_**
"Aishiteru", Uso dadeko
"Aishiteru", Uso dadeko **(italy)**
if i use filter **(italy)** i find good language for all manga on site

but:
same manga on  **MangaDEX** is writed like this:
"Aishiteru", Uso dadeko
**(only without langage code)**
**and i must click title** (then i see on chapter list this)
Vol1 Ch 002 title **(gb)**

then i know only **great britain lang exist** same for all other...

Can You Mr. update code for global language filter?
If i write example **(English)** lang program looks for language code **(english) (en) (eng)** etc. **together in manga list and chapter list and if find language update manga list title then user not need click all manga title 1 by 1** only have great filtered list without other langage code...

Thanks cheers from Poland.

**Comment by arkon** [comment]
Extension-specific issue.
