### ISSUE TITLE
ADD new source: 8Muses 

### ISSUE THREAD

**Issue by darkDaiyo** [inorichi/tachiyomi#2099]
A must website for western adult genre. There is a lack of western adult content/source and 8muses is E-hentai for western artists.
https://www.8muses.com/comics

**Comment by ZaneHannanAU** [comment]
READ THE TEMPLATE.

**Comment by ZaneHannanAU** [comment]
See https://github.com/inorichi/tachiyomi-extensions as mentioned in the template.
