### ISSUE TITLE
Next Chapter issue

### ISSUE THREAD

**Issue by spawnpoint** [inorichi/tachiyomi#210]
This is for **v0.1.4**
There is currently an issue with how the App loads the next chapter when there are multipart chapters, with decimal places.

**Steps to Reproduce**

_Note_: can be done for any manga where some chapters have whole numbers and some have decimal places. 

1. Open OnePunchMan
2. Download Chapters 16, 17.1.
3. Read/Scroll to end of chapter **16** 
4. Try to scroll to **17.1** 
5. This gives a "Next chapter not found". 

This means that I have to go back and click 17.1 manually. 

I'll try to go through the code to see where the issue lies exactly but should be a quick fix for the loadNextChapter() logic

I did do a search on the github rep but couldn't find the issue anywhere else.

**Comment by IceKreem** [comment]
Yeah this also occurs in the latest debug as well, I did the exact same test.

**Comment by inorichi** [comment]
I did that to avoid skipping chapters. It's better than not reading a chapter because you didn't notice IMO.

**Comment by spawnpoint** [comment]
Thanks for the reply.
It's definitely better to get a visual reminder.

**Comment by inorichi** [comment]
Merging to #243
