### ISSUE TITLE
Request : Parallel Downloads

### ISSUE THREAD

**Issue by chrisadipascual** [inorichi/tachiyomi#2102]
**Issue/Request:**
First I'd like to express my gratitude to the developers of the app. This is far by the best manga app out there.

Parallel downloads would be a very nice feature. Imagine having a high speed internet only to be limited by 1 download at a time.

**Comment by bbtora** [comment]
Feature was remove because of IP bans #1567

**Comment by arkon** [comment]
We may want to consider this being a configurable flag for extensions in 1.x.

**Comment by chrisadipascual** [comment]
> We may want to consider this being a configurable flag for extensions in 1.x.

: )
