### ISSUE TITLE
[Request] Save Downloaded chapters as .pdf file format

### ISSUE THREAD

**Issue by EutMeHardPlz** [inorichi/tachiyomi#2103]
App version: 8.0.4-1516

Android version: 9 (pie)

Issue/Request: please add Save Downloaded chapters as .pdf file format, just like in haku neko S manga reader and downloader, they have a option that can download the chapter in .pdf format. If you can do this, please put this feature. Thanks :)

**Comment by bbtora** [comment]
#658
