### ISSUE TITLE
[Feature Request] .nomedia inside manga pictures folder

### ISSUE THREAD

**Issue by LordMrcS** [inorichi/tachiyomi#2104]
rev 1d079dd

Hi, my feature suggestion is an option in the settings for enabling the app to create a .nomedia file inside each and every manga folder. That is important for enabling the album apps of the phones to ignore the manga folders and to not display manga pictures among the camera pictures.

**Comment by LordMrcS** [comment]
Tested: one .nomedia file inside Tachiyomi top level folder did the trick.

**Comment by ikinone** [comment]
As far as I can tell, the .nomedia needs to be in the immediate folder structure to operate correctly

For the given structure of:

/Tachiyomi/Downloads/<sources list>/<manga list>/images

Currently .nomedia is in <sources list> folder, but it actually needs to be alongside the <manga list> folders to operate correctly.

This solution worked for me, so it shouldn't need to be in every single manga folder, but at least in every source folder.

**Comment by hXtreme** [comment]
Could it just be that the specifications on dealing with .nomedia files isn't clear and every phone manufacturer and file explorer could just be interpreting it differently.

For example,
- One just requires nomedia in the top level directory.
- One that needs it in every directory.
- One that needs it in the immediate parent directory....


If that is indeed the case then the only solution is that we put nomedia in every character directory.
