### ISSUE TITLE
manga not labeled as added to library

### ISSUE THREAD

**Issue by SYSKYMAN** [inorichi/tachiyomi#2105]
**App version:**
0.8.4
**Android version:**
4.4.2
**Issue/Request:**

manga not labeled as added to library,

when I browse the source, the manga is not tagged as added to the library. and when I try to add the second time the manga is added twice. Is there a solution to this problem?

![Screenshot_2019-06-30-03-14-11](https://user-images.githubusercontent.com/52362555/60390783-cf256200-9ae6-11e9-9f3d-30c83b0f9a4b.png)

![Screenshot_2019-06-30-03-14-45](https://user-images.githubusercontent.com/52362555/60390787-e9f7d680-9ae6-11e9-897b-14ae9984be6a.png)

**Comment by CarlosEsco** [comment]
This is because of a mangarock change. Remove the old one after adding the new one

**Comment by SYSKYMAN** [comment]
I have 500 names from that source. Maybe it is possible to solve this problem differently, not manually

**Comment by metroid112** [comment]
You can use the migration feature probably to ease the burden.
