### ISSUE TITLE
[Feature Request] QoL improvements

### ISSUE THREAD

**Issue by boreslayer** [inorichi/tachiyomi#2110]
1. Option to "select all" in the My Library Page
 2. Option to lock the app with a fingerprint or password
 3. Option to show more than 2 columns of comics/manga e.g. currently on my phone, it is showing a 2x2 layout.  Will be great to have an option to select a 3x3, 4x4, 5x5 layout.  
4. Option to add comics/manga to "Favourites".  Currently there's a way to do something similar but I would need to create a category first.  
5. Option to select other folders to import other than the /Tachiyomi/local method.  

All in all, Tachiyomi is a very good manga/comic reader.  These are some suggestions that I have to make Tachiyomi better.  Others can feel free to add on to this.  I'll be updating this when I think of more QoL stuff.

**Comment by CarlosEsco** [comment]
2.  There is already a ticket and may be looked at for 1.x
3.  There already is an option in settings. 
4.  If you really need a separate section for favorites then just make the category the one time.

**Comment by boreslayer** [comment]
2.  Great!
3.  Ahh, I manage to find an option for it.  

Thanks!

I hope 1. be available in the next few updates.  Adding/deleting manga/comics is a huge PiTA.  I had to use a bot to get around this.

**Comment by hXtreme** [comment]
Please check to see if the features you're requesting were already
requested, if they do, see how they were resolved. If they aren't resolved
give it a 👍.

Request 1.: Open a feature request (after checking to see that it doesn't
already exist)

Request 2.: Use some app that lets you lock/hide apps.

Request 3.: Already present under general settings.

Request 4.: Use categories.

Request 5.: Open a feature request (after checking to see that it doesn't
already exist)

Best,
Harsh

**Comment by arkon** [comment]
Please open individual issues if any of these are still relevant.
