### ISSUE TITLE
Outdated Kotlin and Couroutines

### ISSUE THREAD

**Issue by eshrh** [inorichi/tachiyomi#2112]
It seems that this app is using kotlin version 1.2.71, and coroutines is using 0.22.2. In order to be compatible with the android gradle plugin, kotlin needs to be at least 1.3.0. Is there a good reason that we are not using the latest 1.3.40?

**Comment by CarlosEsco** [comment]
upgrading kotlin, requires upgrading coroutines.  which requires some code changes since they made some changes to the methods.   So it requires some coding work besides just upgrading version numbers.

**Comment by arkon** [comment]
@CarlosEsco Want to submit a PR with the updates based on Below? ;)

**Comment by CarlosEsco** [comment]
@arkon if i ever get the time to

**Comment by arkon** [comment]
Addressed in #2239
