### ISSUE TITLE
[BUG?] Update Order affects Refresh Metadata / Refresh Tracking Order

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2114]
**App version:**
0.8.4-1518
**Android version:**
9
**Issue/Request:**
Concerns #1772 
Settings -> General -> **Library update order** affects the order of **Refresh library metadata** and **Refresh tracking metadata** options in Advanced.
Tested with both **Alphabetically** and **Last updated** option.

**Other details:**
I don't know if this was intended with the aforementioned commit.

**Comment by CarlosEsco** [comment]
i don't see an issue with it.  Doesn't make sense to update library metadata alphabetically if you set the general library update to last updated

**Comment by bbtora** [comment]
I see. But why wouldn't it make sense if that's the case? It has been in alphabetical order before the commit and it was working perfectly.

**Comment by CarlosEsco** [comment]
If i am using last updated order, why would i want my metadata for something that hasnt updated in a year to go first just because its starts with an A?

**Comment by bbtora** [comment]
Fair enough but it won't matter anyway as refreshing metadata isn't an automatic call but rather a manual trigger which users either don't use much or have no idea exists.

**Comment by hXtreme** [comment]
This was at least the way I had intended it to work and Carlos hits the exact reason behind it.

> why would i want my metadata for something that hasnt updated in a year to go first just because its starts with an A?

**Comment by bbtora** [comment]
Closing this then as it's an intended behaviour.
