### ISSUE TITLE
[BUG] A sequence of action that's oddly allowed

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2115]
App version: v0.8.4

Please check the [Video](https://youtu.be/4PFFLKWd74M) 

Ideally you shouldn't be able to do other things once you're in chapter selection mode.

**Comment by hXtreme** [comment]
[Another similar one but not about chapter selection](https://youtu.be/D-egTY4JZbo)

**Comment by arkon** [comment]
The original issue is fixed.

**Comment by arkon** [comment]
No intention of fixing edge case of multiple global searches in the stack.
