### ISSUE TITLE
tachiyomi timeout

### ISSUE THREAD

**Issue by chewzhihui** [inorichi/tachiyomi#2117]
**App version:**
0.8.4
**Android version:**
9.0
**Issue/Request:**
timeout issue when reading manga halfway
**Steps to reproduce (if applicable)**

 1. reading "Master of Legendary Realms" until chapter 20
 2.flip next page
 3.timeout issue

**Other details:**

**Comment by arkon** [comment]
What source? Does it happen regardless of network?

**Comment by hXtreme** [comment]
Does it load in web view/in the browser?
