### ISSUE TITLE
Provide web interface

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [inorichi/tachiyomi#2118]
Often I want to read manga on a bigger screen when I have access to a PC, while still syncing my progress with Tachiyomi on my phone. Allowing Tachiyomi to host a server providing a web interface with a basic reader would allow for that.

The user would either turn on the server permanently in the app settings or temporarily turn it on for the current session. The device's IP along with a random or pre-determined port would be displayed to the user, which they can connect to using a browser on any device on the local network. The web server would show a simple overview of the library on the device. Like in the android app, clicking a cover would show some details along with a chapter list and a button to continue where they last left off. The reader view itself would also be similar to the app.

**Comment by arkon** [comment]
That's the goal of https://github.com/TachiWeb

**Comment by HoLLy-HaCKeR** [comment]
That is a port, though. I'd much prefer this to integrate with the android application.

**Comment by as280093** [comment]
whats the app for id you want in Android

**Comment by HoLLy-HaCKeR** [comment]
What exactly do you mean? I meant to say that I would prefer a solution built into Tachiyomi itself, so that it can benefit from any updates it gets, while also having access to the same library I normally use.

**Comment by streamheart** [comment]
this is an amazing idea, i always try to read manga on my pc when am at home 27" screen is so much better

**Comment by CarlosEsco** [comment]
this will  never happen in 0.X maybe 1.x but even then tachiweb for 1.x makes more sense

**Comment by metroid112** [comment]
I don't think it should be built into Tachiyomi, maybe a tighter integration with TachiWeb is the way to go

**Comment by Efreak** [comment]
Run a nginx (in termux) or some other webserver on your Android device; you can then connect to it with webdav to mount it on your PC as a local drive. 

You could also check out the following:
- https://github.com/zhreshold/ComicViewer (may require modification, intended for use with archives)
- https://github.com/bpatrik/pigallery2 (supports mobile/swipe, works with directories)

**Comment by CarlosEsco** [comment]
You can just use something like this.
wirless adb and https://github.com/Genymobile/scrcpy

a web interface to access your device is not going to be added  as its really out of the scope what this app is
