### ISSUE TITLE
[Features Request] Share Library

### ISSUE THREAD

**Issue by Mickuchiha** [inorichi/tachiyomi#2122]
Simply put, a feature on the library that compliates all the links/sources from the library itself and allows you to share that information (be it via whatsapp, an e-mail, etc) could be similar as the prompt you get when migrating sources, recieving end opens the (file, probably) and a list with all the source>series appears (just like when migrating sources) end user can add said manga to its personal library or not [add all, could be an option too]

**Comment by hXtreme** [comment]
You could backup the library and share the backup file.
