### ISSUE TITLE
Manga rock library update delay

### ISSUE THREAD

**Issue by windncloud** [inorichi/tachiyomi#2124]
**App version:** 0.8.4

**Android version:** 9

**Issue/Request:** mangarock update delay for manga added to the library, sometimes the delay can take up to 12 hours

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/1199
