### ISSUE TITLE
[Bug] Possible to open left and right side menu at the same time.

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2129]
**App version: 0.8.4**

**Issue/Request: The following screen is possible:**
![Image](https://i.imgur.com/pDz0nrF.png) 

**Steps to reproduce**

 1. Tap on Hamburger icon
 2. Quickly tap on the filter icon
 3. Both menu open at the same time

**Comment by arkon** [comment]
This is an edge case not worth fixing.
