### ISSUE TITLE
Unknown error when trying to connect to batoto

### ISSUE THREAD

**Issue by drac0300** [inorichi/tachiyomi#213]
When I try to connect to batoto, I get this : 
https://framapic.org/8R0dMU3V1CRO/UXkOcfFL1IJ3.png
(Expect I use my actual username ans password) , the error is the same. 
When i tried connecting on bato.to website, I had no problèm... It may come from my side, is there a way i can access the logs ?

---
Version: v0.1.4
Vrtoxin on oneplus X, rooted ans xposed installed

**Comment by inorichi** [comment]
It's weird. It still works for me with the debug version. If the password was wrong you would get an "Invalid login" error. The error is not logged, the best option is trying to login in an emulator with Android Studio.

**Comment by drac0300** [comment]
Oki, maybe it comes form my side then,  i will try downgrading and/or using thé emulator ...

**Comment by drac0300** [comment]
After downgrading it worked, but i think it light have been some problem with xprivacy, and just reinstalling might have done the trick...

**Comment by drac0300** [comment]
It works after upgrading, thank you for helping me !

**Comment by drac0300** [comment]
It works after upgrading, thank you for helping me !
