### ISSUE TITLE
Better ui

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi#2134]
**Android version:**

Hi, I using the android version of the app and I think the app needs a better update system.  I find it hard to see which comics got updated and it's really frustrating. Can you add a tab or a label next to the comics telling the user how many comics got updated and maybe the date that the user did not read? If the user did not read an update, the comic should still display the number of unread updates. Just Like in manga rock. Manga rock has a great ui for downloading things without opening the comics and a great ui for updates.can you try something like that? Thanks!

**Comment by as280093** [comment]
thats why they ask you for money and show advertisement
tachiyomi is not single aource based application so it can't be built as manga rock as redesigning is in progress in future updates (1.x) till then read it in what you have

**Comment by arkon** [comment]
> I find it hard to see which comics got updated and it's really frustrating.

There's a recent updates view in the sidebar and unread badges in the library. Are these not sufficient?

**Comment by Mechanical-sanity** [comment]
Can there also be icons for mangas waiting to be downloaded? I'm downloading a ton of comics at once

**Comment by arkon** [comment]
Existing unread/download badges already fulfill these usecases, along with the downloading notification and indicators on the chapters themselves.
