### ISSUE TITLE
[Feature Request] Extension Descriptions

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi#2135]
Request:
Add description handler for extensions so that we can create descriptions in the extension and the main app will just locate and relay the text. This would be useful to show sources included in the extension. (If this was implemented I hope no one will make an essay long description with nonsense beautification. This is not for essay writing ).

**Comment by as280093** [comment]
coming in 1.x update

**Comment by hXtreme** [comment]
#2133 + [1926](https://github.com/inorichi/tachiyomi/issues/1926#issuecomment-476211212)

Should result in this.
