### ISSUE TITLE
next chapter button skips to the second to last page sometimes

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi#2138]
**App version:** 0.8.4

**Android version:** 8.1 and 9

**Issue/Request:** next chapter button skips to the second to last page of the same chapter sometimes

**Steps to reproduce (if applicable)**

 1. open a chapter.
 2. tap next chapter button repeatedly.

**Other details:** 
[Screenshot 1](https://user-images.githubusercontent.com/17810950/61405127-53465a80-a8d9-11e9-8168-d3ef67247d13.jpeg)
[Screenshot 2](https://user-images.githubusercontent.com/17810950/61405147-5fcab300-a8d9-11e9-932d-0b3f15fa790c.jpeg)

**Comment by arkon** [comment]
I _think_ this was fixed with some other reader-related bugfixes.
