### ISSUE TITLE
[Enhancement] Dev build downloads new update but doesn't auto trigger installation

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2141]
**App version:**
0.8.4 1519
**Android version:**
9
**Issue/Request:**
Stated in the title. 
**Steps to reproduce (if applicable)**

 1. Open settings
 2. Open About
 3. Tap on version number
 4. Press "Yes" when prompted to download new update
 5. APK update is downloaded but installation doesn't start automatically.

**Other Details**
Issue can only be reproduced in build r1519 because of obvious reasons.

**Comment by arkon** [comment]
I'm relatively sure this is how it works for stable too, especially since the dev updates piggy back on the same logic.

**Comment by arkon** [comment]
The only issue I can see with it automatically kicking you into the package installer is if it took a while to download and you were actually doing something.

**Comment by bbtora** [comment]
Well... I don't know how this can be solved or improved then.

**Comment by hXtreme** [comment]
@arkon once the download finishes we get a notification with an option to install.

A. Isn't that just fine?

B. If not, can we not modify whatever is triggering the notification to trigger the installation.

**Comment by arkon** [comment]
I feel like it's fine how it is?
