### ISSUE TITLE
[Feature Request] Option To Cancel "Automatic Next Chapter"

### ISSUE THREAD

**Issue by Henrique245** [inorichi/tachiyomi#2144]
I know this sounds really nitpicky, but could you add an option to cancel the "automatic go to the next chapter" when you reach the last page of a chapter please :)

Ideally i would like if it just stopped at the last page of a chapter and you couldn't go any further. I mean, i would like to have the option, it would be nice.

If this feature is already available, please let me know.

**Comment by hXtreme** [comment]
Could you elaborate on what do you mean by automatic go on the next chapter?

You'd have to either scroll or tap ... to go to the next chapter right?

**Comment by Henrique245** [comment]
hXtreme, it's when you reach the final page of any chapter, you would swipe to the white screen and you would swipe again to go to next chapter. I would just like an option to just reach the end page and you can't go further anymore and you had to do it mannualy.

**Comment by Henrique245** [comment]
hXtreme, it's when you reach the final page of any chapter, you would swipe to the white screen and you would swipe again to go to next chapter. I would just like an option to just reach the end page and you can't go further anymore and you had to do it mannualy.

**Comment by bbtora** [comment]
You can just go back and tap on the next chapter... If that's what you really intend to do.

**Comment by arkon** [comment]
I don't remember if the page between chapters was added after this, but that should serve this use case well.
