### ISSUE TITLE
[Feature request] Group by Source

### ISSUE THREAD

**Issue by shaishaiNg** [inorichi/tachiyomi#2146]
It would be nice to see a feature that could group our manga list according to its source.  Maybe it can be incorporated similar to the sorting, but with headers.  Particularly helpful in seeing what titles are in your particular source, which I find that the sorter via source isn't really helpful with since you cant really see where those titles came from.

example of headers:
![image](https://user-images.githubusercontent.com/50228486/61763322-96d42380-ae07-11e9-8aaf-6007e47e04d2.png)

**Comment by arkon** [comment]
You can search by source now.
