### ISSUE TITLE
[Bug] Anilist not being updated when I complee

### ISSUE THREAD

**Issue by NihonjinEric** [inorichi/tachiyomi#2147]
**App version:** 0.8.4

**Android version:** Android 8.1.0

**Issue/Request:** Whenever I open and complete a chapter from any series, my Anilist does not show that I read that chapter. Even though I have my Anilist synced with the Tachiyomi app.

**Steps to reproduce:**

 1. Download 0.8.4 APK
 2. Sync up Anilist account
 3. Add One Piece to library
 4. Read [a chapter you have yet to read] of One Piece
 5. Open Anilist.co and see if Tachiyomi updated the One Piece progress

**Other details:** I initially thought it was an issue with my 3 point smiley rating system, but even after updating my rating system to a ten-point system and deleting/reinstalling Tachiyomi (v.0.8.4) and re-syncing my Anilist, new chapters still would not show up as completed on Anilist. Also whenever I go into the third tab on a series' page (labeled "TRACKING"), then hit the "EDIT" key, the pop-up just shows a refreshing loading symbol that never goes away.

**Comment by NihonjinEric** [comment]
Typo in the title, "[Bug] Anilist not being updated when I ~~complee~~ [complete a chapter]"

**Comment by bbtora** [comment]
AniList search is currently facing issue and down for the time being.

Can you also make sure if you have set the manga in the tracking tab correctly by tapping on the Anilist logo on the side. It should take you to the manga page in the browser.

**Comment by NihonjinEric** [comment]
If you mean the part I circled here, tapping on it does nothing. 

https://i.imgur.com/XxZ9hPO.jpg

**Comment by bbtora** [comment]
Okay, I see the problem. You have not set the manga in the tracking tab that is why it is not being updated in the site.
You'll have to wait as the AniList search is down and you won't be able to set the manga if the search doesn't yield results.

**Comment by NihonjinEric** [comment]
Is there anywhere I can track the status of this issue involving anilist?

**Comment by bbtora** [comment]
You can join the AniList discord server to get more info regarding this issue.
