### ISSUE TITLE
Reader can't load image from certain url

### ISSUE THREAD

**Issue by rama982** [inorichi/tachiyomi#2148]
**App version:** 0.8.4

**Android version:** 9.0

**Issue/Request:** Reader can't load image from url with this kind of domains :

> `https://i0.wp.com/lhx.googleusercontent.com/xxxx....xxxx/xxx/xxx.jpg`

**Steps to reproduce (if applicable)**

 1. Open chapter contains that url
 2. Image not loaded, showing "retry"

**Other details:**
No issue when opening on webview.

**Comment by bbtora** [comment]
Can you provide the source and the manga/chapter?

**Comment by rama982** [comment]
> Can you provide the source and the manga/chapter?

Yes,
source is Maid Manga (ID), manga "Taishou Otome Otogibanashi", Chapter 38.2 Extra.
only first and last image contains ads which not using that kind of url is loaded.
other chapter not using that kind of url also fine.

**Comment by rama982** [comment]
@arkon close this also

**Comment by rama982** [comment]
Lmao this is my issue
