### ISSUE TITLE
Getting a message about JSON object

### ISSUE THREAD

**Issue by xxbeelzxx** [inorichi/tachiyomi#2151]
![Screenshot_2019-07-27-23-42-21](https://user-images.githubusercontent.com/53379947/61998409-fe6cc600-b0c8-11e9-9431-437602d3d3ba.png)

I get this message everytime I open an old chapter no matter which manga. 

Tachiyomi 0.8.4

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/1336
