### ISSUE TITLE
Feature Request (Or possible bug?): Download from Cache/Temp

### ISSUE THREAD

**Issue by RaguEsa** [inorichi/tachiyomi#2153]
**App version:** 0.8.4

**Android version:** 9

**Issue/Request:** After viewing a manga, and while it is still in cache, hitting to download the chapter/manga should grab it from the cache instead of completely re downloading it from the server.

Another reader, EhViewer, was able to do this as an example. If you went to download something after reading it, it would instantly complete the download and instead just move the images in the cache to the download folder.

There was a feature request about this a little over a month ago, and the person who stated it replied that it was implemented but no one I have talked to knows anything about the feature and has never seen it work, and I wasn't entirely sure if necro-ing issues was something you should do so I just figured I'd remake it. Feel free to remove if I shouldn't have.

**Comment by arkon** [comment]
Is this the same as #2094?

**Comment by RaguEsa** [comment]
Yes

**Comment by arkon** [comment]
The PR is still open.
