### ISSUE TITLE
Cannot access most manga rock titles

### ISSUE THREAD

**Issue by BarnatoZoldyck** [inorichi/tachiyomi#2157]
Tachiyomi: 8.4

Android version: 6.0

Issue/Request: getting the error
 
Failed to load pages : Value (A directory) at (integer) then type
java.lang.String cannot be
converted to JSONObject with a most manga rock titles

Eg: the example below is for Kurogane chapter 6.3

Failed to load pages: Value
https://f01.mrcdn.info/
file/mrfiles/h/6/7/a/FK
9kvif_Lr.mri at 0 of type
java.lang.String cannot be
converted to JSONObject

**Comment by jackred** [comment]
Did you try to refresh the manga (drag screen down to force the refresh)? I had the same error, but after I refreshed once it became ok.

**Comment by BarnatoZoldyck** [comment]
@jackred thank you it worked, i dont know why i did not think of that. I need to rethink my life lol. I really appreciate it thanks a lot

**Comment by BarnatoZoldyck** [comment]
@jackred thank you it worked, i dont know why i did not think of that. I need to rethink my life lol. I really appreciate it thanks a lot
