### ISSUE TITLE
[UI Issue] The white splash screen is very painful to look at.

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2158]
Currently Tachiyomi doesn't have a splash screen which leads to a white screen to flash.

Check the [video](https://youtu.be/FRRP73lOsbg)

It would be great if a splash screen with dark background and Tachiyomi logo was displayed instead.

Similar to #1223 but a theme independent splash screen.

**Comment by markelgaston** [comment]
I totatly agree, it is painful to watch at night and eventually the app would certently need a splash screen too.

Ill work on it.

**Comment by hXtreme** [comment]
@markelgaston have you started working on it/ are about to? If not, I want to try to take a shot at it.

**Comment by markelgaston** [comment]
> @markelgaston have you started working on it/ are about to? If not, I want to try to take a shot at it.

Hi, I have actually already finished it. Im just not familiar on how to use git on android studio and how to do pull requests and stuff, so Im doing a bit of research to make sure i do it correctly hah, but yea, i will do the pull requests soon.

**Comment by RYNAPU** [comment]
When I launch it, the white screen is there for less than a second. Not sure why it's taking so long for yours ?

**Comment by bbtora** [comment]
It also depends on the size of your library and maybe too on the downloads size in the storage.

**Comment by arkon** [comment]
Added via https://github.com/inorichi/tachiyomi/compare/4bc5f1401f57cf208c09e2655536b29e160b6732..8d3166c5febe2fcf9d53084440a9f18650a467dd
