### ISSUE TITLE
Adding custom scrolling 

### ISSUE THREAD

**Issue by sm7297** [inorichi/tachiyomi#216]
1. when i tap the screen it moves  little bit upward with webtoon reader it will be great if i can select the area to move on a single tap like 25% 50% etc.
2. And this option does not working left to right or right to left viewer it directly goes to next page.
3. I have to swipe more than half of the screen to go to other side of the single page need an option to select swipe width to scrolling area

**Comment by inorichi** [comment]
1. Not going to add this to settings, at least for now. You can change it in the code and compile your own apk.
2. ViewPager is designed to always have one page visible, there's no way to partially scroll a page and it's required to create an entire View for this. I won't invest time here.
3. That also depends on ViewPager's implementation. I don't know if there's a way to easily override this.
