### ISSUE TITLE
[Feature Request] Memory of deleted manga

### ISSUE THREAD

**Issue by ennui169** [inorichi/tachiyomi#2160]
**App version:** 8.4

**Android version:**8.0.0

**Issue/Request:** I don't know if something like this already exists, but some way to remember manga that may have been deleted on the website? I feel that sometimes series I remember adding suddenly disappear. If there was a notification of some sort stating manga X was deleted that would be nice. 

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by hXtreme** [comment]
If it was added to the library it should be visible in the library even if the source deletes it (you won't be able to read it though)
