### ISSUE TITLE
Deleted Manga can't be redownloaded again

### ISSUE THREAD

**Issue by snapdragon64k-47** [inorichi/tachiyomi#2163]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** Current

**Android version:** 9.0 Pie

**Issue/Request:**
Manga failed to download/freezed at 100%, I decided to delete it and it was indeed gone in the downloaded section but I tried redownloading but it said manga was already added on queue/dowloaded, even though there were no pending/running downloads and the said manga can't be seen in the download section. I cant do a clean data wipe as I have 300+ downloaded mangas. Reset catalogue didnt work. Please help. Cache cleared. Nothing.
**Steps to reproduce (if applicable)**

 1. Download a chapter.
 2.Delete it fully in the DL section
 3. Redownload. Mine says already added in Q but theres nothing in the queue/downliaded section

**Other details:**

**Comment by snapdragon64k-47** [comment]
i tried downloading a single manga on a blank phone with mangarock. the first set of numbers in folders are the same, the second set of numbers in the files folder changes. os there any way to know where and what to delete in the root folder of mangarork? im rooted.

**Comment by arkon** [comment]
Wait, is this a bug report about the Manga Rock app? If so, this is definitely not the place for that.
