### ISSUE TITLE
[Feature Request] Sort by date in search

### ISSUE THREAD

**Issue by ArmeF97** [inorichi/tachiyomi#2164]
Add an option "sorta by date" in manga search. The date will be the date of the first chapter

**Comment by hXtreme** [comment]
Do you mean by release date?

**Comment by CarlosEsco** [comment]
Yea that's not gonna be possible. Would have to query every manga during a search to get their chapter list which ddos's the website . And then add an ability to know which manga had a chapter with oldest date.

**Comment by hXtreme** [comment]
@CarlosEsco it should be feasible in the library because everything would be stored locally.

**Comment by ArmeF97** [comment]
I thought servers could have this API, so it would be easier

**Comment by CarlosEsco** [comment]
@hXtreme  this ticket wants this to be when you are searching for a manga.  Not library search.  Even if it then you would need some way to access chapter information when all you have is manga info.  

@ArmeF97   there is no server for Tachiyomi.  The searching of a manga depends on what the extensions website you are using and what they provide

**Comment by hXtreme** [comment]
@CarlosEsco thanks for the clarification! Whenever I see manga search I assume it could be anything from global, library or source.

@ArmeF97 you might want to check if whatever source you're using provides a similar feature on their website. If they do, open up an issue on tachiyomi-extensions for the feature.

**Comment by ArmeF97** [comment]
@hXtreme ok, thank you. I assumed tachiyomi first must support this in order to be able to make my feature request on tachiyomi-extensions but I'll do as you said
