### ISSUE TITLE
How to stop the images from showing up in my image picker activity

### ISSUE THREAD

**Issue by Cleman25** [inorichi/tachiyomi#2165]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
R1521
**Android version:**
Android 9
**Issue/Request:**
How do I stop the files from showing up in my File chooser activity?
**Steps to reproduce (if applicable)**

 1. Open twitter to send a message with an image or tweet with an image
 2. Select add image
 3. Scroll down and the images will appear

**Other details:**
Not sure how they got there. Not sure if they're backups or updates but it's clogging up the space and I don't want to accidentally send a manga scan when in trying to send a meme or something

**Comment by hXtreme** [comment]
try adding a .nomedia file to Tachiyomi folder in your phone.

**Comment by CarlosEsco** [comment]
See above. It should auto add but some phones it has issues.
