### ISSUE TITLE
Cant update Library

### ISSUE THREAD

**Issue by dorafumingo** [inorichi/tachiyomi#2167]
**App version:** 8.4 stable or dev ver.1526

**Android version:** 7.0

**Issue** updating the library doesn't do anything (be it auto update or manual refresh) 

**Other details:**
Updating the library just doesn't work, auto update doesn't happen and when manually refreshing by a swipe up, the round arrow is here but disappear when i let off without starting the update (same thing when i press "update library") the updating notification doesn't start and not one manga is updated. It's happening since yesterday. 
Tried stable version and latest dev version same problem
(there's 3 different sources in my library so i don't think it's because of a source)

**Comment by hXtreme** [comment]
Are there new chapters available for manga in your library?

Sometimes when the library only has very few manga, Tachiyomi can be done with checking for updates before you even get to check the notification.

It could also be a network issue or an IP ban.

**Comment by dorafumingo** [comment]
I checked and there's several new chapters, for the ip ban i don't know i can still browse on the sources (mangarock, mangasee, mangadex...) and read new chapters.
It's just the library that does not want to update

**Comment by CarlosEsco** [comment]
Do you have space where you are trying to download to.

**Comment by dorafumingo** [comment]
Yes, i have tried to change it to the sd card but no changes.
It doesn't even find the new chapters, let aloneness trying to download them

**Comment by dorafumingo** [comment]
Finally i deleted everything tachiyomi related, reinstalled the app and used a backup.

Now it works again (even if i tried the stable and dev versions with different version numbers)

The most important thing is that it works, and i didn't loose much with the backup
