### ISSUE TITLE
Pre-check existing tags when adding to library

### ISSUE THREAD

**Issue by Efreak** [inorichi/tachiyomi#2168]
**App version:**
0.8.4, r1519

**Android version:**
Pie, Oreo

**Issue/Request:**
When adding to the library, check the tags (listed below the description) and pre-check any categories that match (exactly matching is acceptable, case insensitive and disregarding dashes would be ideal). This would greatly speed up categorization. 

**Other details:**
It would be even better if there was a way to auto categorize those already added, but that seems like it would be excessive work for something that'll only be used once. A compromise might be to do this when adding an item to the library immediately after removing it, given a setting to prevent it from replacing categories on accidentally removed items.

**Comment by arkon** [comment]
I feel like this is more complicated and potentially confusing than it's worth (it might look like it's already in a category, which is what it'd imply given the existing UI).
