### ISSUE TITLE
[Issue] Myanimelist tracking error

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#2173]
App version: r1521
Android 9.0
Myanimelist is not tracking automatically and after changing the chapter number manually it says Http Error 400. On the previous beta I didn't notice such an issue. 
![Screenshot_20190810_083528_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/4900246/62817059-d6aa4300-bb49-11e9-8ce3-042c2a275782.jpg)

**Comment by hXtreme** [comment]
You may have to login again.
