### ISSUE TITLE
MyAnimeList login not working

### ISSUE THREAD

**Issue by axiel7** [inorichi/tachiyomi#2174]
**App version:** 0.8.4

**Android version:** Q Beta 6

**Issue/Request:** MyAnimeList login not working, returns unknown error

**Steps to reproduce (if applicable)**

 1. Go to Settings/Sync/MyAnimeList
 2. Try to login with your credentials

**Other details:** It was working ok a few days ago

**Comment by axiel7** [comment]
Okay so I deleted the app cache and it's working now. I don't know if I'll have to delete the cache every time it happens because it would be very annoying. For now I'll close this issue.

**Comment by MCAxiaz** [comment]
Current dev build already has some fixes that should address this isssue.
