### ISSUE TITLE
Please... just add a Downloaded tab? Or have local manga scan the download directory?

### ISSUE THREAD

**Issue by Clydefrosch22** [inorichi/tachiyomi#2177]
**App version: 0.8.4

**Android version: 8.0.0

**Issue/Request: Comfortable access to downloaded chapters through a dedicated tab.
Currently, as I understand it, you have to bookmark a comic so it appears in your library to access chapters you downloaded.
This seems like weird and unintuitive behavior.
I downloaded a short comic with 3 chapters, not seeing the need to bookmark it when I'm all but done with it in one trainride anyways, not realizing that, on the train, without an online connection, I wouldn't be able to find my way to the comics anymore.

I later learned about a rather complicated workaround todownload chapters, then move the downloaded chapters from the download directory to the local manga directory.

That works, but you need to know where the chapters get downloaded to and where to put them first. 

I would've settled with simply using the local manga directory as the download directory, but unfortunately, that doesn't work, as the app insists to put one extra folder (in my case 'ReadComicOnline (EN)') infront. It only works when you move the folders inside that.

So yeah, just add a tab that scans whatever folder you chose as the download directory and displays its contents.
Or make the local manga thing scan the download directory and make that work with the one extra layer of folder.

**Comment by hXtreme** [comment]
What's the problem with the Downloaded filter?

**Comment by Clydefrosch22** [comment]
What Downloaded filter are you speaking off?

**Comment by hXtreme** [comment]
Filter https://imgur.com/gallery/wXUwJP7

**Comment by Clydefrosch22** [comment]
Sorry, I updated the initial post (i accidentally hit enter and sent the whole thing right after the headline)

This downloaded filter only works when you already know to bookmark everything and seems to only serve a purpose when you have a long list of comics, some downloaded, some just marked.

I would wish for a menu showing just comics with downloaded chapters.

**Comment by CarlosEsco** [comment]
The download filter is sufficient enough.  It shows only manga/comic that have downloaded chapters

**Comment by Clydefrosch22** [comment]
but it doesn't when you haven't bookmarked the comic.

it only shows bookmarked comics that have chapters downloaded.

**Comment by bbtora** [comment]
What's the problem with bookmarking manga? You can remove it after reading easily too. This process doesn't take much of the user's time.

**Comment by CarlosEsco** [comment]
dont download a manga that isnt bookmarked.  problem solved. It even suggests to add it when you download.  Also 1.x it will have to be in library to download.

**Comment by Clydefrosch22** [comment]
1. it's really unintuitive having to bookmark something to get to your localized files. I'm not sure there's any other of these downloader types that doesn't just include that.
the little popup asking if you want to bookmark the thing (which I assume is a result of a similar feedback to mine) is a nice start, though it's easily overlooked on a tablet and doesn't tell you bookmarking is your only way back without an online connection, but its really just addressing a symptom of a cause that shouldn't even exist.
2. because it's not intutitive, it's easy to forget and i can only imagine how many people download a bunch of chapters for a bunch of things, especially when they first got this, and just never remember one or two series they meant to look into at some point.
3. kind of adjacent to that, it'd also help to remember to get rid of chapters you downloaded, read and unbookmarked without deleting, since other than checking out the folder on the device, there's no way to know whats still downloaded

now i'm not saying this is a top priority, there's probably source updates and compatibility stuff that's more important, but this seems like a pretty basic, to be expected feature for a reader/downloader such as this. not to mention that the functionality seems all but included already through the local manga thing, there's just one layer of folders too much to make it happen.

**Comment by CarlosEsco** [comment]
its not getting added.  its not hard to add the manga to the library before/after or during downloading.

**Comment by arkon** [comment]
At best, forcing it to add it to the library upon downloading instead of suggesting it would be the solution here.

**Comment by Clydefrosch22** [comment]
Except for when you're offline and didn't know that, because it's only explained online in the issues tracker of a github page.

As for hard or not hard, it's also not hard to download comics on your pc and transfer them to a tablet/phone, but people still wanted a dedicated app doing that for them on their device, because that's even more comfortable. 
And I assume it was hard work to get this running and let it keep up with cookies and session ids and whatever else these websites do to stop these downloaders from leaching their content.

To be honest, beyond the part where this has to be worked on, because I absolutely understand that time is valuable and there's lots of things you could invest time in, I'm not quite sure why you'd rather address this in such a roundabout way, instead of making it, well, more easy and elegant, like on most other comparable apps.

Not having time or having more pressing matters, I understand.
'You don't need that' on the other hand, when, and I checked, I'm by far not the first one to run into this, seems weird.


Anyways, that's my thoughts on this, clearly I can't force you to do anything you don't want to, but you should really keep this in mind at least as a potential quality of life improvement in the future. Cause this is going to trip people up over and over and it really doesn't have to.

**Comment by hXtreme** [comment]
If you don't want to add it to library then why not just go to recently read and continue reading.

The defacto workflow is that for anything you care about, you add it to library.

**Comment by Clydefrosch22** [comment]
Recently read also only works if you actually opened a chapter first, it's an extra step you have to keep in mind needlessly.

I understand that this seems to be the workflow everything else is kind of build around.

It's just not that intuitive though. It requires steps you have to read about or figure out by trail and error first. That's bad design.
Functional, of course, it's not like it's unusable, but there's really little reason why any of these workarounds should have to be employed to access content downloaded with this app, or why the local section excludes local chapters.

It's overall a weird decision. Things with downloaded chapters could also just automatically be added to the library too, circumventing these trip ups too, but that was also consciously decided against for some reason, leaving you in a situation where at least some people will download stuff and eventually wonder why it's not anywhere to be found for no good reason until they go online and do research on it.

I'm certainly open to argue wether or not any interface designer should have to pander to their laziest or dumbest or most confused possible user, but I can't think of any reason why this was being decided like this.

**Comment by CarlosEsco** [comment]
Feel free to open a pull request

**Comment by Clydefrosch22** [comment]
So the general argument remains 'You don't need that.'

Fine, you guys do you.

**Comment by arkon** [comment]
It is bad design, but adding a complex system of showing downloaded content regardless of the library system isn't good design either. Ideally we'd rethink how it works (probably for 1.x), but I still maintain that the best solution here is to automatically add something to the library if a download is initiated, rather than prompting.

**Comment by Clydefrosch22** [comment]
How is a downloaded tab bad design in conjunction with a library (=favorites/following/subscribed/watch list) tab?
There's a reason why amazon, netflix, every podcast, e-book, pretty much every content consumption app supporting downloads, has this setup.

Though I agree, automatically adding things to the library would resolve most of my gripes from a general usability point of view.
You'd still have to actively go and clean out the download folder from cases of premature unbookmarking once in a while, but this actually seems less pressing with current devices growing on board memory.

**Comment by CarlosEsco** [comment]
Again if you think it's a good feature. That nobody else before has requested then open a pull request with the change you want. It's an open source project for a reason

**Comment by arkon** [comment]
It's bad design because it introduces additional complexity to the overall system. You'd effectively have to maintain 2 libraries (i.e. databases and their respective DAOs) that conceptually already have a lot of overlap. It is technically feasible, but it's also not particularly nice in terms of maintainability.

That said, it's clear the app is designed with the happy path in mind (i.e. things you read are added to the library). It's frankly weird (but obviously possible) that a user would actively plan to read something and not add it to their library but rather navigate back to it through the full catalogues.

As Carlos mentioned, you are free to submit a PR, but I doubt the owner would want to add something as complex as this at this point to the existing version. Instead, efforts should be put into ensuring the design for 1.x addresses this sort of use case.

**Comment by Clydefrosch22** [comment]
> 
> 
> Again if you think it's a good feature. That nobody else before has requested then open a pull request with the change you want. It's an open source project for a reason

You know as well as everyone else here that, I can't because programming is not on my skillset and I wouldn't have asked if I could've just done it myself.



> 
> 
> It's bad design because it introduces additional complexity to the overall system. You'd effectively have to maintain 2 libraries (i.e. databases and their respective DAOs) that conceptually already have a lot of overlap. It is technically feasible, but it's also not particularly nice in terms of maintainability.
> 

So it's not bad design, it's just more complex than not adding it. Which is kind of tautological.
Then again, considering that local mangas is already there, the basic functionality of accessing local downloads is already there. If chapters weren't saved in 'Manga Source > Manga name > chapter > images' but just 'Manga name > chapter > images' structure, just putting the local manga path as download path would be all it takes to make this work and have quick and easy access to local manga from within the app with basically no additional maintenance required.
Though it still wouldn't solve the fact that you'd have to go out of your way to go online and research how local manga actually works in the first place.

>
>
> That said, it's clear the app is designed with the happy path in mind (i.e. things you read are added to the library). It's frankly weird (but obviously possible) that a user would actively plan to read something and not add it to their library but rather navigate back to it through the full catalogues.
>

Of course no one would want to navigate back through the full catalogues, as that's slow and at times the search function seems buggy (that might be downtime on the websites though) and you need to be online to do so anyways.
But I'd also never intuitively think 'I downloaded the whole thing to my tablet to read later. I better also bookmark it so I can read it online or go back to the download option again/because otherwise, I'd surely not have access to the things I just downloaded anymore'
I wouldn't do that on a pc, I wouldn't do that on netflix, I wouldn't do it in manga rock.

The only reason I'd bookmark something is if it's still ongoing. So i can check it for updates easily. Until it's completed, at which point I'd kick it out.

>
>
>As Carlos mentioned, you are free to submit a PR, but I doubt the owner would want to add something as complex as this at this point to the existing version. Instead, efforts should be put into ensuring the design for 1.x addresses this sort of use case.
>

Now that is a good reason why it's not gonna happen at this point in time at least.

**Comment by arkon** [comment]
> You know as well as everyone else here that, I can't because programming is not on my skillset and I wouldn't have asked if I could've just done it myself.

GitHub is a platform for developers, the default assumption is generally that someone is a developer.

> So it's not bad design, it's just more complex than not adding it.

Design means more than just UX when talking about architecture. Yes, adding anything is more complex than not adding it. The degree of complexity is the important part.

> Then again, considering that local mangas is already there, the basic functionality of accessing local downloads is already there.

Yes, but it's also important to note that local manga can be extremely slow due to limitations with Android and the hardware itself.

I'll open another issue with the idea of forcing the addition to the library for a hopefully more productive discussion about the issue.
