### ISSUE TITLE
[Feature Request] Allow sorting of manga in browse catalog according to last updated instead of just in lexicographioc order

### ISSUE THREAD

**Issue by MuhdNurKamal** [inorichi/tachiyomi#2178]
This is for manga that is not added to library but just in the browse menu of catalogues. When a filter is applied, the manga list is shown in lexicographic order. There is no way to change this. The request is to add a field to sort the manga list output either by last updated or lexicographic or any other useful metrics.

**Comment by hXtreme** [comment]
This is extension specific and should go to tachiyomi-extensions along with the name of the catalogue.

**Comment by CarlosEsco** [comment]
This depends on the source itself. If there is a particular source you want this on and the website itself has the ability then open a ticket in the extension repo
