### ISSUE TITLE
Automatically add manga to library upon downloading

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#2179]
Original issue: #2177 

---

It can be confusing that downloading a manga doesn't automatically add it to the library. It may no longer be accessible but still be downloaded (e.g. if the user loses Internet connectivity, uninstalls the extension, or the manga/chapters are removed from the catalogue site). While the app currently displays a snackbar prompting the user to add it to the library, the user can ignore it.

The original suggestion is to add something like a downloaded tab (similar to Netflix or Prime Video). This would likely involve maintaining another database that tracks those.

**Comment by snapdragon64k-47** [comment]
Sound idea. The favorites and the downloaded parts should have their own sections. Keeping tabs on downloaded and faves can be difficult as both can be available in the library

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
