### ISSUE TITLE
[Feature Request] Option to divide pages in Webtoon mode

### ISSUE THREAD

**Issue by TheUnlocked** [inorichi/tachiyomi#2180]
I like to be able to scroll part-way through a page when reading (like mentioned in #778, which was rejected for technical reasons). Webtoon mode supports that, but when you use Webtoon mode, every page is directly against one another rather than separated. This of course makes sense for Webtoons which are supposed to exist on an infinite canvas, but it works less well for page-based manga. To make the Webtoon viewing mode work better for page-based manga, I propose an option to add a small amount of vertical padding between each page in Webtoon mode.

Here's a comparison image between unnamed-other-manga-reading-app (left) and current Tachiyomi (right) to explain what I mean (don't mind the difference in scanlation):

![image](https://user-images.githubusercontent.com/10186337/63063645-4dc93980-beb2-11e9-8318-e6d4e82bae35.png)

**Comment by hXtreme** [comment]
Is there any particular reason for why any other view doesn't work for you when reading page based manga?

**Comment by TheUnlocked** [comment]
As I said, I like to be able to vertically scroll part-way through a page as I'm reading (makes me need to move my eyes around less), and vertical mode only supports viewing a full page at a time. This isn't the kind of thing which would be a dealbreaker for me, but it would be a nice feature to have.

**Comment by metroid112** [comment]
Webtoon mode should be left as is, since that works perfect for webtoons which need no padding between vertical "pages".

I think the solution would either be adding a new type of viewer "webtoon with padding" or make the padding an option by itself.
