### ISSUE TITLE
Website for and about this app

### ISSUE THREAD

**Issue by Wolffyx** [inorichi/tachiyomi#2181]
Sorry if I am rude, coming with an proposal :smiley: . I want to make an website for this app, I really think that this app needs one  (I like it too much and I decided to make an website ).
The question is : Can i make one? The host will be [Github ](https://pages.github.com/). 
If yes I want to know if you want a specific design or you let me chose it?

**Comment by hXtreme** [comment]
There is already an ongoing effort towards it. It would be great to have more help there.

Please wait I'll provide you with a link in a moment.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomiorg.github.io
