### ISSUE TITLE
[Feature Request] Manga Dex sign in 

### ISSUE THREAD

**Issue by RYNAPU** [inorichi/tachiyomi#2184]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4
**Android version:**
9 Pie
**Issue/Request:**
A option to sign in to Manga Dex to allow for native searching through app since they turned of guest searching

**Other details:**

**Comment by bbtora** [comment]
You can sign in to Mangadex by going into any of the manga in that catalogue > three dots menu > open in webview > sign in through the open Mangadex webpage

For clearer instructions, visit https://tachiyomi.org/#mangadex-no-results
