### ISSUE TITLE
[Feature Request] Support Extension Image decoder(discrambler)

### ISSUE THREAD

**Issue by DitFranXX** [inorichi/tachiyomi#2188]
Some of manga providers using scrambled images for prevent from CCCVs.

I usually used `Okhttp`'s `Interceptor` for decode those images but there's problems.

1. It is unstable w/ CF's Under-Attack mode
    - Because It doesn't returns full image, as `206 Partial Content`. Which causes error.
2. Can't determine what image is need to decode in normal way.
    - It need to append some decode indicator on Url or Header.
3. Can't use variable that need to decode in normal way.
    - Same as second one.

I think it's better to use image decoder on `Glide`'s `onResourceReady` function. which can't access in current extension api.

I don't think that can be implement on `0.x`, and don't know how `1.x` structured is.

This is draft that don't think the structures.
```kotlin
// model side
open class Page(
    val index: Int, 
    val url: String = "", 
    var imageUrl: String? = null,
    val decoderVariable: SomeObject? = null
)
```
```kotlin
// extension side
open fun imageDecoder(bitmap: Bitmap, variable: SomeObject) {
    ...
}
```
```kotlin
// glide side
override fun onResourceReady(resource: Bitmap, ...) {
    val bitmap = if(decoderVariable != null) { 
        imageDecoder(resource, decoderVariable)
    } else {
        resource
    }
    ...
}
```

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
