### ISSUE TITLE
Backup doesn't restore manga status (which chapters were read) only ID

### ISSUE THREAD

**Issue by perkel666** [inorichi/tachiyomi#2193]
Latest version of Tachiyomi

Had to move my stuff to other tabled. Did backup and tried to restore that backup on other device.
It did bring categories, manga etc but it did not bring which chapters were read, all of chapters now look like they were never read.

I have like 1000 manga and now i don't know which chapters on what manga i was. 
Is this normal ?

**Comment by CarlosEsco** [comment]
when you backed up did you click the chapters option?

**Comment by SamB** [comment]
Maybe that option should be on by default?

**Comment by perkel666** [comment]
> 
> 
> when you backed up did you click the chapters option?

I picked up everything which is default option when you do backup.

**Comment by CarlosEsco** [comment]
if you still have the other device redo the backup cause its more than likely user error.

**Comment by pkajan** [comment]
tachiyomi creating only small file with only ids/urls of mangas...
"new" backup has only 2kb, older that i do monthly and backin it up to cloud has 28kb...
maybe its problem with permissions? -> between last "good" update and "new" one only new thing in phone was android update(Android 9, last security update 1. august 2019)
manual backup > all checked/ none checked => backup file is the same

**Comment by perkel666** [comment]
> 
> 
> if you still have the other device redo the backup cause its more than likely user error.

No it is not. Default option has check-marks on everything and i didn't change a thing. It simply did not backup chapters status.

**Comment by CarlosEsco** [comment]
provide your version of android, device, and version of Tachiyomi.

**Comment by pkajan** [comment]
tachiyomi: 0.8.4 (13.4.2019 15:16)
Android: 9 (build 00WW_6_18A_SP02; core version 3.18.120-perf #1 wed jul 24)
device: nokia 5

**Comment by arkon** [comment]
Never actually reproduced this, but should be irrelevant with the v3 backup system currently in Preview.
