### ISSUE TITLE
[Feature request] library & source status

### ISSUE THREAD

**Issue by cantsay-d** [inorichi/tachiyomi#2198]
Thank you for creating this app , I have been struggling with a lot of apps this one is good , my request is if possible could  you add how many manga or manhwa or .... A source or my library has, like 
![demo1](https://user-images.githubusercontent.com/54781963/64084592-93657d80-cd5f-11e9-9632-7a6dcbd1f861.jpg) and this 
![demo2](https://user-images.githubusercontent.com/54781963/64084593-9fe9d600-cd5f-11e9-924d-415e9ae39544.jpg)

Also could you add " select all" on the option when you select something on my library and apply mark as read, I have a lot of manga and I final add all of them phewwww then am expected to open every one of them and select chapters and mark as read, I won't finish even for tomorrow 😥😞

**Comment by arkon** [comment]
This should be split up into different issues.

1. Number of things available in a source

No, this is not technically feasible unless each site exposed that number in an easy fashion. The app does not store the catalogue data itself, and gets it page by page.

2. Number in library

Yes, this could be possible.

3. Select all option / mark as read/unread

Yes, this should be possible.

**Comment by arkon** [comment]
There's separate issues for 2 and 3 somewhere, so closing this one.
