### ISSUE TITLE
Add mangastream as a source/catalog 

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi#220]
As the title suggests, please add more sources like mangastream. The current ones don't include licensed Mangas like one piece and bleach. Kissmanga does but they are very slow on the update. Thanks and keep up the great work!

**Comment by AntiLight** [comment]
I second this. Mangastream is one of the best places to read manga, so I would much prefer it over others

**Comment by na-ji** [comment]
The problem in Mangastream is that chapters are removed after some time. I can add a parser for Mangastream, but before I have a question for @inorichi : does this behavior might break the app ?

**Comment by Thoasty** [comment]
Ah yes I realized that after I posted this. Below is the archive site for mangastream releases. 

www.mangastream.to

If they are associated with mangastream, I do not know but I guess all I want is just more sources. Especially ones that have licensed Mangas. Maybe like Goodmanga. Thanks!

**Comment by inorichi** [comment]
It doesn't break the app but they will be removed from the list when it's refreshed.

**Comment by ikargbo** [comment]
Yes please add Manga stream its really good add batoto too

**Comment by na-ji** [comment]
Waiting for #239 to be merged

**Comment by inorichi** [comment]
I'm not sure how I will merge #239, because I'm moving at least mangahere and mangafox outside the app, and currently it will break the app if you have manga of those in the library, and the other parsers not implemented by me would also disappear.

**Comment by AntiLight** [comment]
What do you mean you are moving mangafox and mangahere out of the app?

**Comment by ikargbo** [comment]
Yh there is no mangafox and mangahere sources there's only kissmanga and batoto

**Comment by na-ji** [comment]
I started making it but never finished because it was not my priority. All mangastream's release are re-uploaded on other websites for now.

**Comment by ywecur** [comment]
@na-ji FWIW I'd really appreciate it 😘. I'm sure many are with me, most mangas are released there first.

**Comment by na-ji** [comment]
So tried to make it as a YamlOnlineSource but it will be hard. The pageListParse must be called multiple time because the site does not show every page when the number of page is to big. [For instance this chapter](https://mangastream.com/r/dragon_ball_super/019/3892/1)

@inorichi : is there a way with YamlOnlineSource that I am not aware of to do that ? Or is it a feature that we need to add ?

**Comment by inorichi** [comment]
It's not easy to handle every particular case with only a key/value map. There's currently no way to parse that page list. I wanted to allow code execution (like Javascript or JSR 223), but I couldn't find a solid approach and tbh I have other priorities. So yeah, YAML has a lot of limitations.

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
