### ISSUE TITLE
[Feature Request] Mark all chapters as read

### ISSUE THREAD

**Issue by SyncStelar** [inorichi/tachiyomi#2200]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.4

**Android version:** Android 7.0 Nougat

**Issue/Request:** After migrating from MangaRock app to Tachiyomi, Tachiyomi lacks the ability to select manga and mark all of it's chapters as read. Currently the fastest way to do so is to open the chapter and tap "Mark as Read" and "Mark previous as Read".

**Other Details:** Perhaps adding a button to the top right panel when a manga is highlighted in "My Library" will do.

**Comment by CarlosEsco** [comment]
The use case for a mark all read button is limited.  I don't see the need for this when there is a working alternative already.

**Comment by SyncStelar** [comment]
You're telling me that I should do the working alternative for over 260 mangas?
This function basically makes it easier for anyone who decides to migrate from another app to this.

Without this function, it'll take me 1300 clicks (260*5. 1 tap to open manga, 2 for : button, 1 for mark as read, and 1 for Mark previous as read).

In comparison, there are others who may have 600-800++ mangas they wanna import.

**Comment by CarlosEsco** [comment]
#1181
