### ISSUE TITLE
[Feature Request] mix sources v2

### ISSUE THREAD

**Issue by rafalohaki** [inorichi/tachiyomi#2201]
I would like to add idea.
If u click a button then select all installed sources(extensions) to search title u want, u can see them all or only those ones with the top 10(example) most chapters.
It would be best feature ever imo.
Thanks

**Comment by arkon** [comment]
I don't really understand what you mean. 

You mean global search should only show the result that has the most chapters?

**Comment by hXtreme** [comment]
If it's actually what @arkon is saying I'd like to argue against it, as there are certain series of manga that I'd search with the same keyword for example take irregular at the magical school. That has numerous different manga for various arcs, none of which should be hidden when searching.
