### ISSUE TITLE
[Feature Request] Add searchbar to extensions.

### ISSUE THREAD

**Issue by edgarMejia** [inorichi/tachiyomi#2202]
Hi there,
Thank you for the excellent work on this application.

My request is:
There are currently 126 extensions, it would be a good idea to add a search bar.
[https://imgur.com/a/Q2PZCkG](https://imgur.com/a/Q2PZCkG)

Thanks.

**Comment by pkajan** [comment]
it will be nice + search based on "source", not only extension name (because some extensions contain multiple sources)
