### ISSUE TITLE
[Feature Request] Comment section 

### ISSUE THREAD

**Issue by Sumanth4321** [inorichi/tachiyomi#2203]
Nice job with the app.
Just a suggestion that it would be nice to have a comment section for different manga.
Thanks.

**Comment by hXtreme** [comment]
Please describe the feature in greater detail.

Comments as in notes(something similar already under discussion) or comments as in forum(not happening/won't happen)?

**Comment by Sumanth4321** [comment]
Like comments submitted from users using the app.

**Comment by hXtreme** [comment]
Submitted where? To the source, something like this is more likely to be
implemented in Neko?

Best,
Harsh

**Comment by arkon** [comment]
I think something similar was suggested before, but basically the answer is no due to the complexity of having to maintain the infrastructure for it.
