### ISSUE TITLE
Question - import data from mangarock json ?

### ISSUE THREAD

**Issue by wankio** [inorichi/tachiyomi#2204]
Hi, i'm new here.

I have a question, can tachiyomi using json from mangarock to import bookmarked manga ?

Thank

**Comment by joseph619** [comment]
Manga Rock does not use .json, so you can't import boomarks. You have to add each manga manually.

**Comment by wankio** [comment]
i'm not sure but
NL4h0CQVJp_2147483647_backup.jsz
NL4h0CQVJp_2147483647_backup

inside 

> {"recents":[{"time":2147483647,"msid":71,"mid":661020,"page":0,"cid":29764302},{"time":2147483647,"msid":42,"mid":305787,"page":15,"cid":29736561},{"time":2147483647,"msid":71,"mid":553939,"page":5,"cid":29686971},{"time":2147483647,"msid":71,"mid":646174,"page":0,"cid":29015592},{"time":2147483647,"msid":42,"mid":305628,"page":25,"cid":29688354},{"time":2147483647,"msid":71,"mid":564362,"page":0,"cid":26900295},{"time":2147483647,"msid":71,"mid":544357,"page":15,"cid":26095087},{"time":2147483647,"msid":71,"mid":547992,"page":7,"cid":26384156},{"time":2147483647,"msid":71,"mid":545542,"page":21,"cid":26184326},{"time":2147483647,"msid":71,"mid":561491,"page":24,"cid":28282410},{"time":2147483647,"msid":44,"mid":325429,"page":14,"cid":29290175},{"time":2147483647,"msid":71,"mid":563841,"page":18,"cid":28574934},{"time":2147483647,"msid":71,"mid":562769,"page":27,"cid":26889833},{"time":2147483647,"msid":71,"mid":544888,"page":10,"cid":26133460},{"time":2147483647,"msid":71,"mid":626603,"page":19,"cid":29248296},{"time":2147483647,"msid":71,"mid":582003,"page":0,"cid":27281102},{"time":2147483647,"msid":22,"mid":505350,"page":4,"cid":28813037},{"time":2147483647,"msid":44,"mid":330139,"page":4,"cid":27694041},{"time":2147483647,"msid":22,"mid":522733,"page":7,"cid":27346409},{"time":2147483647,"msid":22,"mid":581863,"page":1,"cid":27304911},{"time":2147483647,"msid":1,"mid":262378,"page":11,"cid":28579531},{"time":2147483647,"msid":71,"mid":548455,"page":13,"cid":26421164},{"time":2147483647,"msid":71,"mid":548414,"page":17,"cid":28800049},{"time":2147483647,"msid":71,"mid":648020,"page":5,"cid":28852955},{"time":2147483647,"msid":71,"mid":632192,"page":0,"cid":28434470},{"time":2147483647,"msid":71,"mid":631899,"page":9,"cid":29114064},{"time":2147483647,"msid":71,"mid":611135,"page":9,"cid":29114482},{"time":2147483647,"msid":22,"mid":184352,"page":43,"cid":29130600},{"time":2147483647,"msid":71,"mid":624667,"page":4,"cid":28881084},{"time":2147483647,"msid":71,"mid":563422,"page":40,"cid":26894238},{"time":2147483647,"msid":71,"mid":635800,"page":29,"cid":28577069},{"time":2147483647,"msid":71,"mid":617489,"page":16,"cid":29085740},{"time":2147483647,"msid":71,"mid":614992,"page":11,"cid":29113651},{"time":2147483647,"msid":71,"mid":561404,"page":26,"cid":28489474},{"time":2147483647,"msid":71,"mid":605557,"page":22,"cid":27893033},{"time":2147483647,"msid":71,"mid":615452,"page":26,"cid":28341334},{"time":2147483647,"msid":71,"mid":628877,"page":302,"cid":28355605},{"time":2147483647,"msid":71,"mid":618776,"page":0,"cid":28847158},{"time":2147483647,"msid":71,"mid":592376,"page":16,"cid":28855218},{"time":2147483647,"msid":71,"mid":604025,"page":37,"cid":28121629},{"time":2147483647,"msid":71,"mid":546273,"page":27,"cid":29009833},{"time":2147483647,"msid":71,"mid":623211,"page":13,"cid":28575464},{"time":2147483647,"msid":71,"mid":597538,"page":0,"cid":28955955},{"time":2147483647,"msid":71,"mid":564721,"page":18,"cid":28981899},{"time":2147483647,"msid":71,"mid":547205,"page":18,"cid":26320521},{"time":2147483647,"msid":71,"mid":605606,"page":8,"cid":27894506},{"time":2147483647,"msid":71,"mid":561357,"page":0,"cid":26880111},{"time":2147483647,"msid":71,"mid":558513,"page":28,"cid":28774247},{"time":2147483647,"msid":71,"mid":557895,"page":34,"cid":26856070},{"time":2147483647,"msid":71,"mid":559027,"page":1,"cid":26864202}],"favorites":[{"author":"","mid":372759,"msid":42,"manga":"Tô Tịch Kỳ Quái"},{"author":"","mid":305579,"msid":42,"manga":"Hero Waltz"},{"author":"","mid":306150,"msid":42,"manga":"Ashita no Yoichi"},{"author":"BANJO Azusa","mid":488011,"msid":42,"manga":"Hensokukei Quadrangle"},{"author":"",

**Comment by arkon** [comment]
It may be possible, but it won't be natively supported within the app.

**Comment by arkon** [comment]
@wankio How did you get the JSON from Manga Rock?

**Comment by arkon** [comment]
I made a small tool that can convert the JSON you posted into a backup that can be imported into Tachiyomi (with the Manga Rock extension): https://echeung.me/tachirock/

Should help with migrating sources within the app if that's what you wanted.

**Comment by hXtreme** [comment]
@arkon I checked out your tool, maybe you should allow people to upload the manga rock file.

**Comment by arkon** [comment]
I'll invest more time into it if it's actually useful. I still have no idea where the Manga Rock JSON is coming from and whether other users can easily obtain it.

**Comment by hXtreme** [comment]
Fair enough.

Best,
Harsh

**Comment by wankio** [comment]
> 
> 
> I'll invest more time into it if it's actually useful. I still have no idea where the Manga Rock JSON is coming from and whether other users can easily obtain it.

i'm using tool  capture request send from mobile to pc (as software host) - Fiddler and then create backup.

The only problem is mangarock is just middle app like tachiyomi. It named all title from other source as mrs-serie-xxxxxxxx . Sometime i can browse back to those url, and sometime i can't, just blank page (feel like php send request to the app and app redirect into sources like goo.gl,bit.ly,....)

**Comment by arkon** [comment]
Yes, you need the Manga Rock extension installed. The tool is meant to just import them into Tachiyomi so you can then migrate them to another source. Someone else built another tool that does it based on the Android app's database.

**Comment by wankio** [comment]
but manga rock extension already installed. that's why i'm say it have error
https://imgur.com/a/SYWXgq7

**Comment by arkon** [comment]
The Tachiyomi extension, not the actual MangaRock app.

**Comment by wankio** [comment]
yup, it's mangarock inside tachiyomi/extension - installed

**Comment by wankio** [comment]
update : source id is wrong so it caused problem :)

changed from
1554176584893433600
to
1554176584893433663

**Comment by arkon** [comment]
Well glad it worked for you — it's probably only useful for you anyway. 😅

**Comment by wankio** [comment]
mangarock is great in UI/UX and some features but it lack of feature like local backup/add label-category to manga......etc... That's why i'm switched into tachiyomi, at least i can add label/category my completed manga  like imdb :)

**Comment by wankio** [comment]
> 
> 
> Well glad it worked for you — it's probably only useful for you anyway. sweat_smile

oh i'm found this :) https://github.com/waicool20/mr2tachiyomi

i dont even know mangarock shutdown in end of the year cuz piracy, make money from pirate content
