### ISSUE TITLE
[Feature Request] Auto Manga Update Notifications

### ISSUE THREAD

**Issue by kanekihaise777** [inorichi/tachiyomi#2206]
Would it be possible to add like an automatic notification that will appear on top of your phone when new chapters are available? That would also mean that the library must be constantly be checkinh for new chapters whenever you are connected to the internet.

**App 0.84**

**Android version: 8.0.0**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by bbtora** [comment]
You can set the library update frequency by going to Settings ->General -> Library update frequency

Notifications will be sent once the app has checked for new chapters in the library.

**Comment by hXtreme** [comment]
The highest frequency is 1Hour, which should be good enough for the most part.

Furthermore, constantly checking for updates may get you banned on some websites.

**Comment by CarlosEsco** [comment]
once an hour is enough
