### ISSUE TITLE
[ Downloaded file size request ]

### ISSUE THREAD

**Issue by snapdragon64k-47** [inorichi/tachiyomi#2209]
**App version:** Current

**Android version:** 9.0 Pie

**Issue/Request:**

Would be neat to have a choice to download titles in small image sizes, currently it has around near 500KB for every page, somewhat around 150kb to 200kb would be a sweet spot, as sone of us have a huge database to download.

Thanks

**Comment by arkon** [comment]
The app does not control what the sources offer.

**Comment by hXtreme** [comment]
Is the issue pertaining to storage or data usage?

Not much can be done by Tachiyomi for data usage but if it's about storage, Tachiyomi could compress the image to a smaller size(resolution).
