### ISSUE TITLE
Feature Request: Floating Play Button

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#221]
Instead of having the play button on the bottom navbar i think it would look better if it was floating in a circle like the create message icon in the messaging app for android L

**Comment by AntiLight** [comment]
I second this

**Comment by j2ghz** [comment]
I am against. It may look better but there will be problems with content hiding again. There is FAB in the info tab and it's issue is still not solved (still hides genres). What if there are exactly enough chapters that you can't scroll and you want to press the three dots at the end? I think usability should be before looks.

**Comment by AntiLight** [comment]
Well it can auto hide when you scroll down. Also, you can easily get over your problem by pressing that other button on the side. The bottom chapter will go on the top and you'll be able to access the dots.

**Comment by j2ghz** [comment]
Hiding is possible, but then you have to check every time if the button is really there, now I just press the button that's always there, even after scrolling through the chapters. Changing order is possible, but it's more complicated (more steps) than just pressing the three dots.

They may seem like unimportant issues, but what is is the upside of this change? It looks a bit better. I don't think that trade-off should be made.

**Comment by AntiLight** [comment]
I think you're being a little dramatic now

**Comment by j2ghz** [comment]
I think we should stick to arguments, because I don't really see one in favour.

**Comment by AntiLight** [comment]
Design is one of the most important aspects of app development. A Fab is a great addition and improvement to that, making an app almost always look vastly better and thought out. And it is not a bother as long as it is able to hide itself to not be of bother. And to deconstruct your own argument, you won't have to look to see whether it's there if it is optimized to appear only when you swipe up. 
BUT, this argument is not really all that helpful and important. It is the Dev that will judge whether he wants to add it or not, so let's leave this here. 
(One final thought, the way the bottom bar is now, a fab actually does not make all that sense and will look horrible, so it will need son more redesign if he wants to add it. Having a fab above the bottom bar just looks shitty).

**Comment by NoodleMage** [comment]
@AntiLight I did redesign it. See #4965802.

**Comment by AntiLight** [comment]
Well, I personaly really dig that look.
