### ISSUE TITLE
Add other names info to the Mangas' info page

### ISSUE THREAD

**Issue by eksit** [inorichi/tachiyomi#2212]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.4

**Android version:** Android 9

**Issue/Request:**

I would like to see other names in the info page for the mangas. These would be names that the mangas have shown up as in other places. Even well-known mangas like "My Hero Academia" are stored as different names in the different sources. A lot of them don't have "My Hero Academia," but they do have "Boku no Hero Academia." This is invaluable if you have the customary name to search with but only the romanized japanese words are in the title. Tachiyomi is pretty good at finding the same manga with different names when you do a search, but I would still like to see the information.

**Other details:**

This is like what Manga Rock has in their app. It is invaluable to me right now because Manga Rock is shutting down their service and I am having to move my manga to another app. About 10% of my manga are named differently, including some widely known ones. This could also be handy if you want to search for the manga in the Internet.

**Comment by arkon** [comment]
This is highly dependent on the sources. If you know of particular sources that have that information and you want it to be shown in the descriptions, open up issues in the extensions repo.

The main app has no knowledge of the manga contents.
