### ISSUE TITLE
[Feature Request] E-ink Optimization : Bookmark icon for chapters.

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2213]
> The only visual difference of a booked marked chapter was the text turning light blue which doesn't result in a visual change on a e-ink display.

see: #2056

Instead(or on top of) if we could show a small bookmark icon for bookmarked chapters it would translate fairly well on e-ink devices.

**Comment by arkon** [comment]
Added in https://github.com/inorichi/tachiyomi/commit/ce6848b3c0c48b7321e8b21278867e49ab4c6992
