### ISSUE TITLE
Cant search manga

### ISSUE THREAD

**Issue by dwcha** [inorichi/tachiyomi#2216]
Ver 0.8.4
Cant search manga in mangadex
Type it correctly but the result is not found. But the mangas are exist in the source
.
Thankyou

**Comment by Naomi010Sentzke** [comment]
Open any random manga and go to "Open in web view". Now login or register and make sure to click remember me. This will trigger the cookies. Mangadex does not let you search if you are not logged in.

**Comment by dwcha** [comment]
Thankyou for your information
