### ISSUE TITLE
[Bug] Library not sorting by latest update properly

### ISSUE THREAD

**Issue by ThatsSowitty** [inorichi/tachiyomi#2217]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**   0.8.4

**Android version:**   Latest version of 9 on a Samsung Galaxy S10+

**Issue/Request:**   I recently decided to switch over to this app after mangarock posted their plans to shut down soon. Love the app and it's potential and so far it is better than anything but mangarock.

At the moment, I believe I've encountered an error that fully prevents me from switching over completely. No matter what I try, my library won't show me the manga I want to see in order of what has been recently updated. Pressing the right sidebar to be able to add filters to see the latest update manga either shows random manga each time when the arrow is facing down or, by some even weirder reason, only shows all my NSFW stuff when the arrow is facing up. 

The only way I'm currently able to see what has updated or not is by looking at the Library Updates. This is frustrating for me because I follow so many ongoing series that I often need need to look at the previous chapter to figure out where I am in the story. Any assistance in this matter would be much appreciated.

Thank you for all your hard work!

**Steps to reproduce (if applicable)**

 1. Open app, open your library
 2. Press the three verticle lines in the upper right shaped like a pyramid by size with the longest bar on top and shortest on bottom
 3. Attempt to sort by last updated.

**Other details:**

**Comment by CarlosEsco** [comment]
So its kinda named poorly.  Its sorting by the last time the chapter list was updated for the manga not the time of the chapter itself

**Comment by CarlosEsco** [comment]
you would probably want #1666 but dont think its been looked at.

**Comment by MerradOklom** [comment]
Yes, as Carlos said, if you update your library and X manga has a new chapter it will be moved to the top of the list.

**Comment by joseph619** [comment]
@CarlosEsco The current sorting is definitely misleading, it should either be changed or renamed asap.

**Comment by ThatsSowitty** [comment]
Thanks, that is hugely misleading and rather surprising that it hasn't been looked at. Is assume that most would consider that a base feature. I'm new around here and could use some guidance - is there any of "bumping" the post you linked by liking or commenting on it?

**Comment by joseph619** [comment]
You can bump a post by commenting on it, you would get notified by email

**Comment by de-odex** [comment]
@pjsinc Why not open a PR rather than posting a link to a patch?

**Comment by pjsinc** [comment]
@de-odex Because proper solution requires more than that. Changing the menuitem text at least (from "Last updated" to "Last uploaded". But I guess this should be implemented as a new item, since there might be people who actually use that in the way it was implemented. So I don't consider that worthy of being PR but just a hint to someone who has time to write proper solution.

**Comment by joseph619** [comment]
This is caused by Mangadex extension, when a chapter in non-user selected language (ie French chapter despite only English enabled in Extenion menu) is updated. Tachiyomi recognizes that chapter for Last updated despite not showing in library updates.

The app is working fine just as intended. There is no issue with the app.

**Comment by joseph619** [comment]
@CarlosEsco

**Comment by Theo47** [comment]
This also happens to me with mangakakalot.

The top 6 manga when sorted by "last updated" and their "updated" date (as displayed on the info tab for that manga on "my library") are:
Versatile mage: 17/10/2019
Tower of God: 14/10/2019
The legendary moonlight sculptor: 17/10/2019
Tales of demons and gods: 15/10/2019
I became a legend a decade later: 16/10/2019
Hero? I quit a long time ago: 17/10/2019

If I choose to manually update any of those (by pulling down on the chapter tab of that manga), it will go to the top of the list even though there aren't any changes.  The "updated" date on the info tab remains the same as what it was before the manual update.

**Comment by moneybags-cloud** [comment]
> Looking at the code the "Last updated" currently seems to mean "If there are any changes to chapter list then sort by date the chapterlist change was detected"? If you want to change it to mean "Last uploaded" (i.e. the date the latest chapter was uploaded) then the attached very short patch would do the job.
> [last_uploaded.patch.zip](https://github.com/inorichi/tachiyomi/files/3646356/last_uploaded.patch.zip)

How do you apply the patch? Thank you

**Comment by vongdong** [comment]
> 
> 
> > Looking at the code the "Last updated" currently seems to mean "If there are any changes to chapter list then sort by date the chapterlist change was detected"? If you want to change it to mean "Last uploaded" (i.e. the date the latest chapter was uploaded) then the attached very short patch would do the job.
> > [last_uploaded.patch.zip](https://github.com/inorichi/tachiyomi/files/3646356/last_uploaded.patch.zip)
> 
> How do you apply the patch? Thank you

I 2nd that. How do you apply the patch?
