### ISSUE TITLE
UI related issues (wrong colors, ...)

### ISSUE THREAD

**Issue by inorichi** [inorichi/tachiyomi#222]
Starting with r558, a new dark theme has been introduced. It's probably that we messed up something that was working before.

Post here any wrong element on the app (include screenshot if it's not very clear).

Hopefully this issue can be closed after a few weeks without a lot of comments. ;)

Please include [Android API level](https://source.android.com/source/build-numbers.html#platform-code-names-versions-api-levels-and-ndk-releases) and current application version.

**Comment by j2ghz** [comment]
https://cloud.githubusercontent.com/assets/1708197/13859065/cec49ba8-ec81-11e5-9e70-4540d690b934.png
On lower brightness the currently selected item is not very readable.
Also Tachiyomi crashes everytime I try to open a chapter.

**Comment by inorichi** [comment]
Any suggestion for the selected item? Text color maybe?

**Comment by M2ck** [comment]
Yes why not give a try with a lighter color.

I've just noticed looking at the screenshot above, width of navigation drawer is a bit too short.
This is more noticeable if you compare with Google apps like Gmail or Play Store.

**Comment by inorichi** [comment]
I know, apparently we're the only ones following the material design guidelines. It was changed in the support library 23.2.0, but google apps still use a larger drawer. Probably you will be seeing that size from now on.

**Comment by inorichi** [comment]
![drawer](https://cloud.githubusercontent.com/assets/3521738/14407097/12f7f318-febd-11e5-9a11-93f9e5e2cb6a.png)

Better?

**Comment by M2ck** [comment]
Yes!
About accent color, dialogs from Sources (Languages dialog only), Downloads (Simultaneous downloads dialog only), Reader & General tabs do not match with this accent color.

**Comment by inorichi** [comment]
Dialogs not using the material dialogs library do not use accent color. I'll see what I can do.

**Comment by inorichi** [comment]
Probably they fixed it recently. I checked today and all the dialogs are using the accent color

**Comment by M2ck** [comment]
Well done!
Only on your personnal build? Because these changes related with accent color aren't available on latest build.

**Comment by inorichi** [comment]
It may be related to Android version. Which one are you on? I tested with 6.0 and 4.1

**Comment by M2ck** [comment]
I'm on Android LP 5.1.1
Ok I get new accent color for drawer items but only on dark theme, is it expected behavior?
It's a bit confusing, IMO you should implement this for light theme too for have a consistency UI.

**Comment by inorichi** [comment]
It's the expected behavior. it's hard to have consistent colors for both themes. By default the drawer uses `colorPrimary` (toolbar color). Dark theme overrided it to use `colorAccent` because of the lower readability. Maybe I should change the background color for the selected item instead.

BTW, I just changed the accent color for both themes to a different one, it was less readable on light theme.

Pinging @NoodleMage.

**Comment by NoodleMage** [comment]
@inorichi I think we should only change default behavior if it's absolutely necessary. So I disapprove on changing the light theme to use the accent color for the selected item. 

As for changing the selected background. I thought this messes something up. But can't remember what ;). If this is not the case it may be a better solution.

**Comment by inorichi** [comment]
I also think accent on light theme is a bad (and uglier) idea.

Selected background is already using a custom one for dark theme with a custom style, I changed it once already (it was a greyish and even less readable color before), so no problem there.

**Comment by M2ck** [comment]
>Maybe I should change the background color for the selected item instead.

Interesting idea!

>EDIT: So, are your dialogs using accent color or not?

No still with a green color instead of blue.
![screenshot_2016-04-10-16-10-20](https://cloud.githubusercontent.com/assets/6850125/14410773/27c46946-ff37-11e5-8a49-75cf363b2b64.png)

**Comment by inorichi** [comment]
It should be good now.

**Comment by M2ck** [comment]
Yes accent color on dialogs match everywhere now, thanks!

**Comment by M2ck** [comment]
Last small detail, catalogues menu stay with a dark color on the light theme.
![screenshot_2016-04-10-19-10-06](https://cloud.githubusercontent.com/assets/6850125/14411711/4a5d84a6-ff50-11e5-8dd8-bfbca771094d.png)

**Comment by inorichi** [comment]
Done.

**Comment by NoodleMage** [comment]
@inorichi didn't test it. But doesn't this break selector feedback?

**Comment by inorichi** [comment]
Yep, it did. Do you have any workaround/alternative in mind?

**Comment by NoodleMage** [comment]
Nope not that I know off ;(. Will look if I can find something ;)

**Comment by inorichi** [comment]
Fixed. Used a drawable as background with selection state.

**Comment by M2ck** [comment]
Just an idea about this catalogues menu, it would be possible to create category language for avoid to repeat abbreaviation, something like on this screenshot (but with a better look than my mockup ;))
![screenshot_2016-04-10-21-00-08](https://cloud.githubusercontent.com/assets/6850125/14412510/b1300e74-ff64-11e5-979a-edd963e30153.png)

**Comment by inorichi** [comment]
There's no native way to do that AFAIK. It would be nice to have though.

**Comment by M2ck** [comment]
Too bad because I had another idea...if someone find a way to do it: additionnally of the category language, it would have been nice to show a checkmark (✔) in front of source where we have picked mangas for a better visibility of sources selected.

**Comment by inorichi** [comment]
If there are no more bugs with the UI, I'm closing this, as this one is assigned to 0.2.0 and I'm releasing it soon.

Feel free to open a new one for UI features.
