### ISSUE TITLE
[feature request]support for android / fire tv remotes (d-pad, arrow key etc)  

### ISSUE THREAD

**Issue by nahuhh** [inorichi/tachiyomi#2220]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**
Android TV 
Fire TV
**Request:**
Support for android / fire tv remotes (d-pad, arrow key etc)  
**Steps to reproduce (if applicable)**

 1. Use the d-pad on the remote
 2. Can't select titles

**Comment by arkon** [comment]
Closing in favour of #2515
