### ISSUE TITLE
Something cannot be searched in the extension "DMZJ"

### ISSUE THREAD

**Issue by Hydroge** [inorichi/tachiyomi#2222]
Recently, some comics such as ""来自深渊" (Made in Abyss) and "漂流教室" (The Drifting Classroom) cannot be searched in the extension "DMZJ", which is abnormal because the two above were able to be searched in this extension several days before...

**Comment by arkon** [comment]
Wrong repo.

https://github.com/inorichi/tachiyomi-extensions/issues/1059
