### ISSUE TITLE
Feature Request: Recognize MangaDex AniList Link

### ISSUE THREAD

**Issue by KeiznKlei** [inorichi/tachiyomi#2223]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this templat

**Android version:**

**Issue/Request:**
Request
**Other details:**
Just a suggestion to automatically recognize and grab the MyAnimeList and AniList links in MangaDex when opening or grabbing a link for automatic tracking.

**Comment by arkon** [comment]
I understand that this would be nice, but it's a bit too specific to MangaDex. Could potentially be a candidate for Neko.
