### ISSUE TITLE
[Feature Request] Single Manga Global Viewer Mode Override

### ISSUE THREAD

**Issue by Kekwa** [inorichi/tachiyomi#2225]
Really missed this function where you can set individual viewer mode for each manga title overiding the default global viewer mode. For example setting webtunes viewer mode for certain title while maintaining left to right view mode for global. Automatic detection of this might be hassle to do so give option to set this manually. Option button can be add at manga description and during reading menu.

**Comment by bbtora** [comment]
Open any chapter in the webtoon/manga > tap on the page > top right gear icon > viewer for this series

**Comment by Kekwa** [comment]
Oh man... Just found the menu after a month using this app 😅sorry for the trouble.
