### ISSUE TITLE
Manga Back-Up is not working

### ISSUE THREAD

**Issue by shinh28** [inorichi/tachiyomi#2226]
I just got a new tablet and I wanted to back-up my whole library but for some reason the button for manga is disabled. I was able to back up and restore all my settings, libraries, recent reads but all the mangas I was reading was left behind. 
![Screenshot_20190917-011915_Tachiyomi](https://user-images.githubusercontent.com/55431035/65020276-1e12b480-d8ea-11e9-9458-fe81212f0559.jpg)

**Comment by bbtora** [comment]
The manga is option is not disabled, it's checked by default. That means all the manga info will be backed-up no matter what.
Your manga not showing is most likely due to no extensions installed.
Install the extensions and try restoring the backup again.

**Comment by shinh28** [comment]
Thank you so much. It worked after I downloaded all the extensions that I used to have
