### ISSUE TITLE
Please unlock translations on Weblate

### ISSUE THREAD

**Issue by asereze** [inorichi/tachiyomi#2227]
I'm a translator for Tachiyomi on Weblate, and on the 7 of this month, almost two weeks ago, I received an e-mail that notified me about new stings to translate. But, since then, I couldn't do it because the project it's locked. In the project page this message appears: 

"This translation is currently locked for updates." 

And I can't save any change. Could the project please be unlocked?

**Comment by nightflyza** [comment]
The same situation. I would very much like to continue translating tachiyomi into Ukrainian. What happen? ;(

**Comment by monolifed** [comment]
There are no new strings. But some strings became untranslated.

**Comment by arkon** [comment]
I believe it's been unlocked.
