### ISSUE TITLE
[Bug] Cannot Change Download Location

### ISSUE THREAD

**Issue by YautjaTNT** [inorichi/tachiyomi#223]
Samsung Galaxy Tab S, cannot change the download location to my SD Card, when I attempt to do so, the app automatically and without fail crashes.

---
Version: v0.1.4

**Comment by inorichi** [comment]
You have to use a very specific directory if you want to use an external SD card. [Read from here](https://github.com/inorichi/tachiyomi/issues/141#issuecomment-189640668) for a better explanation. In the debug version the app allows you to select that directory with a popup. For the stable you will have to create it.

**Comment by inorichi** [comment]
I guess you solved it

**Comment by YautjaTNT** [comment]
Whoops, it took me a good while to figure it out because my tablet refused to let me create the necessary folders, sorry, forgot to come back and close the issue. 
Thank you for the help, love your app too, certainly the best one I've found.
