### ISSUE TITLE
Change shikimori.org to shikimori.one

### ISSUE THREAD

**Issue by Yaguar666** [inorichi/tachiyomi#2231]
Hi, please change the sync tracking address of shikimori.org to shikimori.one.
The old address was blocked due to new stupid Russian laws and don't work in Russia.

Thank you in advance.

**Comment by MerradOklom** [comment]
It was changed 4 months ago (#2038). Maybe you're facing a different issue.

**Comment by Yaguar666** [comment]
Hm.
I'm using build 0.8.4 and when I go to Settings->Tracking->Shikimori app open shikimori.org instead shikimori.one in default browser and shikimori.org blocked from internet provider.
When I use VPN on default browser I can login to Shikimori, but app can't sync with it.

Later I downloaded beta realise - all work, thx)
