### ISSUE TITLE
[Feature Request] Typed input of tracking chapters

### ISSUE THREAD

**Issue by Sleeping-Donut** [inorichi/tachiyomi#2232]
App Version: 0.8.4

Android Version: 9

Request: allow chapter number to be entered by typing the number for the tracking screen 
At the moment if you are changing the value of the current chapter on the tracker to something much larger or smaller than the current value you have to swipe for a long time on the carousel selector, of numbers could be typed then large changes would be much easier to make.

**Comment by arkon** [comment]
You already can, just tap the "selected" number in the carousel.

**Comment by hXtreme** [comment]
I don't get it, how can I bypass the scrolling?

**Comment by arkon** [comment]
Just tap, don't scroll.

**Comment by hXtreme** [comment]
Wow! That just blew my mind!

Thanks!

**Comment by Sleeping-Donut** [comment]
Would someone be able to add this to the guide. The feature is really useful but I couldn't find it documented anywhere.

**Comment by arkon** [comment]
It's not really reasonable to document everything in guides...

**Comment by hXtreme** [comment]
Maybe have a tips and tricks section in the wiki.

**Comment by metroid112** [comment]
It just felt intuitive to tap the carousel to type in a value, maybe from seeing it in other Android apps
