### ISSUE TITLE
Licensed manga in MangaRock are still accessible

### ISSUE THREAD

**Issue by sharedkestrel** [inorichi/tachiyomi#2235]
I don't know if this can help in any way, but trying to refresh licensed mangas that were previously working on MangaRock yields the error "Value Manga in licensed at data of type java.lang.String cannot be converted to JSONObject", but that's to be expected. The fact is that the chapters previousl parsed are still available to be read and downloaded without issues.  
I don't know if this can help circumvent regional blocks in some way. If this is useless or already know information, feel free to close the issue.

**Comment by CarlosEsco** [comment]
Tachiyomi purposely respects licensed manga from sources
