### ISSUE TITLE
When saving an image from Tachiyomi its saving as a music file instead of image

### ISSUE THREAD

**Issue by four98** [inorichi/tachiyomi#2236]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

For all other requests Please fill out the form below and remove the first 3 lines of this template

App version: 0.7.2

Android version: Android 9 Pie

Issue/Request: when saving a certain manga page from tachiyomi and instead of the file being a .jpg or .png file, its saving as a music file. and the 3 image decoders the 'image' decoder is not working :/ its always been 'rapid' and 'skia'

Other details: it was not an issue when i was using my old android phone but now that i've changed my phone its saving as a music file and i can't download manga from the mangahasu extension and MRM anymore. Please help, i really love your app

**Comment by joseph619** [comment]
Update your app, latest version is 0.8.4
