### ISSUE TITLE
[Feature Request] More information about a extension before installing it.

### ISSUE THREAD

**Issue by KayMk11** [inorichi/tachiyomi#2241]
App version:
0.8.4

Android version:
Android 9

Issue/Request:
Requesting more information about extensions to be available, 
as many extensions add multiple sources, it would be nice to know what extension adds what.

right now in the available extension section, tapping the extension name does nothing, and you only have install button,
you can have tapping the extension name give more info on the extension, and then the install button

**Comment by hXtreme** [comment]
#1926
