### ISSUE TITLE
Restore backups doesn't work on other devices

### ISSUE THREAD

**Issue by eksit** [inorichi/tachiyomi#2242]
**App version:**
0.8.4

**Android version:**
Android 9 (main phone running Tachiyomi)
Android 7.1.1 (test phone)
Bluestacks 4.110.0.1081 on Windows 10

**Issue/Request:**
I wanted to use Tachiyomi on my laptop so I installed Bluestacks, then installed Tachiyomi in Bluestacks. I exported the json file from my Android 9 phone and imported it into the Tachiyomi in Bluestacks. There was only an error count and nothing was added to the library. I installed Tachiyomi into the Android 7.1.1 phone and the same thing happened. Before I did all that, I deleted my library in the Android 9.0 phone and reimported everything successfully. I did it as a way to delete all the downloaded manga files which were taking up too much space on my phone since I could not find a graceful way to handle downloaded files (that's another issue).

If I can't import a backup to a new Tachiyomi on another phone, it is pointless. As it is, I am having to log the manga data in a spreadsheet so I can add them one by one if needed.

**Comment by MerradOklom** [comment]
I think this is something obvious but did you install the extensions before importing the backup?

**Comment by 4ngels** [comment]
Saved my time
