### ISSUE TITLE
[Feature Request] A guide for beginners - simplification of use

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#2244]
**App version: ALL**

**Android version: ALL**

Request:  Add a beginner’s instructions as in the guide for working with the program to the program itself (installing add-ons, migrating manga, reading local manga, and more). And links to the application menu where this can be done. That is, to make using the application easier for beginners.
more or less like this

<img src="https://user-images.githubusercontent.com/35057681/65430654-b0a6dc80-de31-11e9-8c26-477c3c34db52.png " width="120"> <img src="https://user-images.githubusercontent.com/35057681/65430659-b0a6dc80-de31-11e9-9539-7ecc4041c8de.png"  width="120">

**Comment by arkon** [comment]
There's now a "help" link in the sidebar to the website with guides, so that sort of addresses this?

**Comment by e-shl** [comment]
@arkon, this is addressed but I was talking specifically about embedding in the app so that the user sees a message about what needs to be done and doesn't think that the problem is in the app

**Comment by arkon** [comment]
Unless you're just talking about a first install guide, having specific suggestions for different areas would be nice.

I've definitely been trying to surface particular things more, like prompting the user to open WebView in the case of HTTP errors when browsing catalogues.

There's an open issue for directing users to a guide on how to use the local source too.

**Comment by e-shl** [comment]
> Unless you're just talking about a first install guide, having specific suggestions for different areas would be nice.

exactly about that

**Comment by e-shl** [comment]
@arkon up

**Comment by e-shl** [comment]
@arkon  and this is not a problem
> guide on how to use the local source too
and the problem is that the local manga is not supported normally / understandably. There are no settings for the folder where the manga is stored, in my view there should be a built-in explorer for selecting a folder and importing manga files.

**Comment by arkon** [comment]
That's sort of a separate issue, but I can't see that happening, _especially_ with Android 11's scoped storage changes coming. If anything, storage location settings are going to be even more limited in the future.

**Comment by arkon** [comment]
Guide on how to use local source is now directly linked to from the source.

If there's specific suggestions, please open up issues for those.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
