### ISSUE TITLE
Covers not loading in library

### ISSUE THREAD

**Issue by pedopuncher** [inorichi/tachiyomi#2245]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
R1524
**Android version:**
9.0 Pie
**Issue/Request:**
Covers don't load in and failed to update covers
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
I've already tried the solutions on the other threads but nothing seemed to be working.

**Comment by CarlosEsco** [comment]
This is a extension specific issue. Please go to the extensions repository and provide details like which extensions you have manga without covers loading
