### ISSUE TITLE
Feature Request: Toggle notifications for updates per-series 

### ISSUE THREAD

**Issue by u83rmensch** [inorichi/tachiyomi#2246]
**Android version:**
8.0
**Issue/Request:**
In settings add notifications catagory or options and include the following:

- all series notify of updates by default   on/off

In library: long press an entry will include the option to turn notification on/off specifically for that series 

**Other details:**
I tend to have a lot of entries in my library but I'm not really always following all of them or care to be notified of updates to all them. It would be nice to pick and choose which series I get notifications about so I actually care about being notified. 

Additonal options for custom sounds or even icons would be nice. It would be even better if the drop down  could be set to group or individual notification entries and choose for individual notifications to include the library entry cover image. That's all added stuff though, I'd just like to see the app give me the option to pick what series the notifications will go off for and ignore all other updates

**Comment by snapdragon64k-47** [comment]
Notifications are working well, but when tapping on the new chapters in the status bar it goes straight into library updates, but the library updates section is useless, it doesn't show anything, in my case it shows the chapters downloaded yesterday and none of today's notification. Would be great if this gets fixed.

**Comment by arkon** [comment]
Chapter update notifications were updated based on the grouped notifications from the j2k fork.

You can easily go to or swipe away individual manga now, at least.

**Comment by AmineI** [comment]
Something that could solve this could be having a notification "channel" per library category, so in Android's notifications settings you could individually toggle/hide/hide on lockscreen/etc specific manga categories.
