### ISSUE TITLE
Date view on filter

### ISSUE THREAD

**Issue by Ani7112k** [inorichi/tachiyomi#2247]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.4

**Android version:** 9.0

**Issue/Request:** Is it possible to add "Date View" on filter on "my library" in tachiyomi?.

**Comment by arkon** [comment]
Not sure what this is really asking. I think the "Latest chapter" sort or updates tab are already sufficient.
