### ISSUE TITLE
mangarock similar manga feature and tachiyomi export feature

### ISSUE THREAD

**Issue by wankio** [inorichi/tachiyomi#2248]
Mangarock have many sector like :  https://imgur.com/a/SYWXgq7
Featured titles
Featured collections
Featured Authors
....et.c..

Can tachiyomi have those sector in mangarock extension ?

Catalogues - Manga Rock - Browse - Filter by - Featured [xxxx]

Eg : Featured Collections : Will show all manga in https://mangarock.com/collection/mrs-collection-200052413 (PC Version dont have full displayed manga, only mobile have full displayed manga, in this link, it missing **20th century boys**

----

And about tachiyomi export feature. Can it export list of manga in Library with
Categories | Cover | Title | Source Link ?

Thank you for reading :)

----

and i'm just update : https://github.com/inorichi/tachiyomi/issues/2204#issuecomment-535217201

and somehow, blogtruyen extension have problem with manga cover : https://imgur.com/a/BJhu32Y but nothing problem while reading - mangarock can show cover properly

**Comment by joseph619** [comment]
Tachi can't have featured author/manga because Tachi doesn't use a single source like Manga Rock. So it's impossible to have featured entries for 170 sources.

**Comment by wankio** [comment]
so it can export bookmarked manga with cover - title - author/artist/source/link ?

**Comment by joseph619** [comment]
Post about Blogtruyen cover issue in Tachiyomi Extensions. I am not sure what you mean buy exporting, do you mean backup?

**Comment by CarlosEsco** [comment]
it exports urls and reading status of those.  when you import a backup it loads those urls then pings the website to get the other info.  

Also closing cause this is not feasible.
