### ISSUE TITLE
Identify extensions with your language

### ISSUE THREAD

**Issue by HiseTake** [inorichi/tachiyomi#2256]
I searched and found nothing about it. I would like to suggest to developers a better organization of extensions. Add and separate extensions by language and add a search bar or filter by language.

I leave as an example the font screen of the manga bird application. It would help novice users identify the sources of their native language.

Thanks for the great work done in the app. I recommended to many friends.

![Screenshot_20190119-193937](https://user-images.githubusercontent.com/28351961/65839442-a5ddc300-e2db-11e9-9f17-a4fc855d7033.jpg)

**Comment by joseph619** [comment]
This is already being worked on

https://github.com/inorichi/tachiyomi/pull/2210

**Comment by HiseTake** [comment]
Thanks @joseph619 . I had not found anything about it.
