### ISSUE TITLE
Covers won't show up.

### ISSUE THREAD

**Issue by jonasprokopf** [inorichi/tachiyomi#2257]
**App version: 0.84

**Android version: 9

**Issue/Request: For some of the manga I download, the cover won't show up, even if I manually set it from the reader. When I go to the files, there's always a cover.jpg, that Tachiyomi generates, but it still won't show in the library.

**Steps to reproduce (if applicable)**

 1.Uhh, don't know, should I be sharing links to pirated manga that I've been having this issue with here? 

**Other details: -

**Comment by CarlosEsco** [comment]
what extensions are you having issues with

**Comment by jonasprokopf** [comment]
Local Manga that I download from various sources like Bittorrent.

**Comment by joseph619** [comment]
This is a know issue, I have also seen users reporting that they sometimes can't put covers on local manga. Not sure what causes this.

**Comment by arkon** [comment]
Closing in favour of #932
