### ISSUE TITLE
CATALOGUE SEARCH SLOW LOADING

### ISSUE THREAD

**Issue by shinh28** [inorichi/tachiyomi#2259]
![Screenshot_20191001-042844_Tachiyomi](https://user-images.githubusercontent.com/55431035/65955063-8bebcf80-e404-11e9-9e61-e9cba02f3524.jpg)
It started slowing down since a few days ago. I even tried searching for a manga that is surely in one of the sources just to check how long it loads. Is there any bugs that is affecting the app or its just me?

**Comment by MerradOklom** [comment]
Manga Plus Eng breaks the search, use the "All" version instead.

**Comment by CarlosEsco** [comment]
do the above

**Comment by shinh28** [comment]
when i uninstalled manga plus nothing really changed, but when I uninstalled komga that's when it started becoming fast again..

**Comment by arkon** [comment]
Global search breaking from broken sources is fixed in dev.

**Comment by joseph619** [comment]
@shinh28 Make a separate issue that Komg extension is slowing down Global search
