### ISSUE TITLE
KOMGA SLOWING DOWN CATALOGUE SEARCH

### ISSUE THREAD

**Issue by shinh28** [inorichi/tachiyomi#2260]
Just like what the title says, komga slowed down catalogue searching for me. When I still had it installed searching would take longer than usual, but once it was gone, the search became fast again just like the way it did. Just want y'all to know.

**Comment by joseph619** [comment]
Please post this on Tachiyomi Extensions, this repo is only for the main app

https://github.com/inorichi/tachiyomi-extensions/issues
