### ISSUE TITLE
Feature request: videos and/or external links

### ISSUE THREAD

**Issue by Caagr98** [inorichi/tachiyomi#2262]
Not sure whether this goes here or in the main repo, so whatever.

I want to make an extension for the comic [Ava's Demon](https://www.avasdemon.com), but while most pages are just images, some are instead links to videos, the first being [page 61](https://www.avasdemon.com/0061.html) (spoiler warning). As far as I've been able to find, there's currently no support for video playback (only gifs) nor links, so supporting these pages seems impossible.

**Comment by arkon** [comment]
There's no plans on supporting videos.
