### ISSUE TITLE
[Feature Request] Increase text size in the between chapters page and bold chapter number

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi#2264]
Basically self-explanatory, but the size of the text is rather hard to read at its current font size, so having something to adjust it or have it be bigger by default would be nice.

Having a bold chapter number would allow users to be able to keep track of their progress easier since they would be drawn toward the bolded numbers

**Comment by arsonistAnt** [comment]
Wondering if this feature is still relevant? 

I was able to implement this in my fork and decided that increasing the page transition text from 0% (normal), 25% (large), and 50% (extra large) in pixels would be good enough. 

I could make a pull request if this is something we feel like we need.

![implmentation_example](https://user-images.githubusercontent.com/15347566/67050770-35fa7580-f0ee-11e9-80c2-e67071e70eda.png)

**Comment by arkon** [comment]
I don't really think it needs to be configurable, but the large text size one looks okay to me.

**Comment by arsonistAnt** [comment]
Oh okay, then I'll just set the default text size in the view holder to 17.5 SP which is the measurement of the  "Large Text".
