### ISSUE TITLE
Different search results for MAL in app and on webpage

### ISSUE THREAD

**Issue by Weasy666** [inorichi/tachiyomi#2266]
**App version:** r1525
**Android version:** BlueStacks 4.130.1.1002 and the same on Android 9 with LineageOS

**Issue:**
Same as the title. Searching for a Manga on MAL and in App gives different results.

Search in app with `Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu` to sync manga to MAL and you will see this results:
![image](https://user-images.githubusercontent.com/11967542/66233442-ac10dc80-e6eb-11e9-9ee4-71b3e32d51f9.png)

compared to this results when searching on MAL's webpage
![image](https://user-images.githubusercontent.com/11967542/66233807-77e9eb80-e6ec-11e9-80bf-fa11efae737a.png)

**Steps to reproduce (if applicable)**

 1. Find `Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu` in one of your sources
 2. Connect to MAL for sync
 3. Try to add manga to MAL sync (you won't find the Manga, so leave search as is)
 4. go to MAL webpage and log in
 5. set search to look only for Mangas
 6. search for `Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu` 
 7. compare result list with app

**Comment by CarlosEsco** [comment]
website you are searching to include novel.  which tachiyomi does not since its not a novel reader.

**Comment by Weasy666** [comment]
Err….i am not searching for a novel. This is a manga

https://myanimelist.net/manga.php?q=Isekai%20Yururi%20Kikou%3A%20Kosodateshinagara%20Boukensha%20Shimasu

**Comment by CarlosEsco** [comment]
look at the type on that result page

**Comment by Weasy666** [comment]
Hm...but there is actually a manga of this. Ok...so i will try to file this at MAL.

**Comment by SnakeDoc83** [comment]
https://myanimelist.net/manga/112342/Isekai_Yururi_Kikou__Kosodateshinagara_Boukensha_Shimasu is the manga's page at MAL.  It doesn't have a score, members, or anything which probably means it hasn't been officially accepted as an entry yet or something like that.

**Comment by Weasy666** [comment]
Ah...so i have to wait until it got approved. Thank you!
