### ISSUE TITLE
Favorite/Rating System

### ISSUE THREAD

**Issue by darkren88** [inorichi/tachiyomi#2272]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1. to have a Favorite or a rating system of downloaded manga/manhwa button aside from bookmarking. 
 2. to have a 1 search bar for all manga titles for all catalogues, if its possible
 3. to have the ability to rate or favorite each catalogues so we could remember which catalog is the best

**Other details:**

**Comment by jatinAroraGit** [comment]
The current version of application does support searching through all titles of all catalogs. 
I can look into implementing a rating system/favorite system for downloaded manga and catalog

**Comment by metroid112** [comment]
The global search is indeed already a thing yes. 

Maybe instead of keeping a rating of catalogues (I feel it's completely unnecesary) the app could allow to manually sort catalogues keeping the most relevant ones at the top instead of being forced to be sorted alphabetically. 

For the favorite manga thing, wouldn't creating a new category called "Favorite" work? I don't know what you're planning to do with the favorites but that's a way of keeping all those series together.

**Comment by darkren88** [comment]
ive downloaded and bookmark a lot of manga and manhwa but we cant deny that
sometimes we have favorites amongst downloaded. let say a priority amongst
the downloaded. which we can easily access.

**Comment by jatinAroraGit** [comment]
@darkren88 , I have implemented a rating system for the library mangas but when it comes to individual catalogs they are immutable object and thus there is no support ( in database and classes) to implement a favorite/rating system as it will require changing values and storing them in DB. Also, it seems the catalog heavily depends on what the extension is serving. You can create a separate issue for implementing new database changes and maybe have to look into creating an issue related to Catalogs (as suggested in the Readme file )  in https://github.com/inorichi/tachiyomi-extensions repository.

**Comment by jatinAroraGit** [comment]
Will Do a PR soon

**Comment by hXtreme** [comment]
A rating system is very unlikely to be implemented as that would involve changes to the database.

**Comment by arkon** [comment]
Yeah sorry, I really don't want something like this bloating the app's already messy logic. You can use categories as a workaround.
