### ISSUE TITLE
Adding 86e53e0 to make groups hidden

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#2273]
**Request:** https://github.com/inorichi/tachiyomi/commit/86e53e08de948bc89f97e3d7d4becfba6fb7c305 There are more and more extensions, and the search is becoming more difficult - so needed  to hide groups of languages ​​under the spoilers in order to quickly find the desired language.

**Comment by arkon** [comment]
Added in https://github.com/inorichi/tachiyomi/commit/62d3fc65e0a73645439a9632838197a58c2a9f8c
