### ISSUE TITLE
Chapter folders appear in Google Photos

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi#2278]
I'm running Android 9 on a Xiaomi Mi A2, Tachiyomi dev r1531.

Suddenly downloaded chapters folders started appearing in Google Photos, did the way of downloading chapters change?

![](https://i.imgur.com/9WSmsG0.png)

![](https://i.imgur.com/SgnPXFM.png)

Clarification: In previous Tachiyomi versions this never happened. They didn't appear as folders that could be selected. 

Clarification 2: Google Photos last update for me was in October 1st and this issue appeared just today. I'd like to believe its not GPhoto problem

**Comment by happywillow0** [comment]
Google Photos should respect .nomedia file. Have you checked your Tachiyomi folder has one?

 I just double checked my phone and remembered I forgot to put it back in after I did a reset / restore. 

The specifications on how apps and the phone dealing with .nomedia may not be clear but at least for me using Google Photos, a .nomedia file in the top level directory works.

**Comment by metroid112** [comment]
My Tachiyomi Downloads folder does have a .nomedia file. It's the only place where there's a .nomedia file. I suppose it should work since its on the top level directory, and its been working just fine for all the years I've been using Tachiyomi.

**Comment by bbtora** [comment]
#2104
