### ISSUE TITLE
[Feature Request] Enable search for source within Multi-source extension

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2279]
For example, under extensions menu if I look up Manhwa Club, it would return Madara (as Manhwa Club is part of Madara multisource extension).

**Comment by MCAxiaz** [comment]
This will probably require changes in the extensions repo first, since currently there's no way for the app to get their sources without installing them.

**Comment by joseph619** [comment]
I see. Can the app pull the info from the wiki and then link it to the extension search?

**Comment by Efreak** [comment]
You could list the sources in [index.json](https://github.com/inorichi/tachiyomi-extensions/blob/repo/index.json), it shouldn't cause any issues for older versions of Tachiyomi.

**Comment by arkon** [comment]
Closing in favour of #3338
