### ISSUE TITLE
[Feature Request] Reading List

### ISSUE THREAD

**Issue by marquesjpf** [inorichi/tachiyomi#2281]
I'd like the possibility of making some kind of reading list / playlist with individual issues / volumes.  
While I can make a new tab and put there a bunch of mangas, I cannot sort a reading order for individual volumes.

Some story arcs in comics jump from series to series, so having the means to organize a reading list would be helpful.

Example:
[Comic A Issue 1]
[Comic A Issue 1]
[Comic A Issue 1]

**Comment by arkon** [comment]
Duplicate of #2282
