### ISSUE TITLE
[Feature Request] Disable sources for Multi-source extensions upon installation

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2283]
Most sources from muli-source extensions are not used by users, so it's a pain to disable all of them in Catalogues. It would be easier to enable the sources I would use than disable dozens of sources in Mulit-source extension one by one. Thus, requesting to disable sources from Multi-source extensions in Catalogues by default.

**Comment by SnakeDoc83** [comment]
Disabled by default would be a bad idea.  It adds another step for a user to have sources available and would definitely lead to them asking "I installed X, why don't I have any new sources?"  That said, I think it would be useful to have a quicker way to enable/disable all sources from a multi-source extension either on installation of a multi-source extension (and then enable/disable specific sources) or from the catalog screen.

**Comment by joseph619** [comment]
This is only for Multi-source extensions, having them disabled is far more user friendly than having 20 of them enabled, 90% of which users neither use nor want.

**Comment by SnakeDoc83** [comment]
>This is only for Multi-source extensions

I get that.  What I'm saying is that if nothing else in Tachi were changed other than all sources of a multi-source extension being disabled by default on installation, that when a user installs that type of extension they won't see or have any new sources available at that point.  They would have to go and enable the sources they want before using them (adding extra steps by default).  If they're new users they won't know that (or how to) and it would be a different behavior from how other extensions are installed.  Normally you install an extension and the source is immediately available.  That behavior would remain for single-source extensions, but it would be different for multi-source extensions which adds confusion.  So, the user may be left wondering why they don't see new sources.

>90% of which users neither use nor want.

I doubt that's an accurate percentage.

**Comment by joseph619** [comment]
>when a user installs that type of extension they won't see or have any new sources available at that point. They would have to go and enable the sources they want before using them (adding extra steps by default). If they're new users they won't know that (or how to) and it would be a different behavior from how other extensions are installed. Normally you install an extension and the source is immediately available. That behavior would remain for single-source extensions, but it would be different for multi-source extensions which adds confusion. So, the user may be left wondering why they don't see new sources.

Most users already know how to use Catalogues, and Multi-source are equally annoying for both new and old users. The confusion is relatively minor issue compared to disabling unwanted sources and keeping the wanted source enabled. I for example, had to disable like 30 sources from Foolslide and Madara to keep the ones I liked. That harms user experience a lot. 

To fix confusion, we need more intuitive UI and better guides, being forced to disable 30 sources is not something people should be doing when they install an extension.

> 90% of which users neither use nor want.

Perhaps it's exaggerated, but they most definitely don't use vast majority of the sources. I don't like how they clutter my source page as well, but that's another topic.

**Comment by SnakeDoc83** [comment]
>Most users already know how to use Catalogues

You have to consider new user experience as well.

>To fix confusion, we need more intuitive UI 

This goes towards my point.  I'm saying that if there were changes made to how multi-source extensions are installed it would a better idea to make the process interactive or make editing sources a better experience.  In other words, it would be better to have additional features than to simply exchange one issue (all sources enabled) for a different one (no sources enabled).

**Comment by MerradOklom** [comment]
Usually I see users on Discord asking why the extension they installed is not showing up on Catalogue, they don't even know how to enable per language sources. If this is implemented there will be even more people asking the same thing. Maybe this should be optional, something an experienced user could enable in the settings.

**Comment by MCAxiaz** [comment]
Yea the current system isn't great. I only just found out that non-English sources don't even show up unless explicitly enabled the other day. Surprised nobody has brought up this issue until now. 

The way I see it is, due to how multi-language sources work, it's not possible to avoid having the user go into settings to enable specific languages. So if we establish that going into settings is part of the normal catalogue setup process, then I'm in favor of doubling down on only enabling the bare minimum for both multi-source and languages.

So the issue is how do we make it clear to the users that they can enable other sources/languages.

I'm thinking of just sticking a clickable footer item at the end of the list of catalogues/extensions that just says something along the lines of "Can't find an extension? Make sure it's enabled", and when clicked just brings up the settings menu. Can't get much more explicit than that.

**Comment by joseph619** [comment]
I would like it as an option in settings then, which can be toggled on or off.

**Comment by joseph619** [comment]
@MCAxiaz Do you think this could be solved for 0.x? Maybe we could bring this to Inorichi's attention so that it doesn't happen in 1.x as well. Extension/catalogues needs much work honestly, it's neither user friendly nor intuitive.

**Comment by MCAxiaz** [comment]
I can certainly open up a PR with _a_ fix. But it's up to inorichi to accept it or not.
And admittedly this would be a pretty drastic change in behaviour so not sure what's the best way to approach this is. Maybe some kind of poll soliciting feedback on the discord? Idk

**Comment by joseph619** [comment]
I am not really sure if average user on discord is qualified enough to vote on poll. Maybe just the devs (Inorichi, Carlos, Arkon etc) need to be convinced why change is necessary, as they will be the ones reviewing stuff. 

When Tachiyomi was made, multisource extensions were small enough that it didn't matter much. However as it's grown bigger, things have become far too messy over time. The sources section in catalogues is a complete chaos for me.

**Comment by Efreak** [comment]
It might be worthwhile to have it sorted by how recently/frequently a source is used, or by how many favorites come from them. The most common sources in your library are most likely to be the ones you want to use. For sorting in the extension installer list, stats could come from number of times extensions get downloaded from the server. A search could also be introduced there for people who use multiple languages.

Regarding having to turn on non-English sources separately, perhaps the user should be prompted if they try to install an extension for a disabled language (install + enable language, install without enabling, cancel)

**Comment by arkon** [comment]
I'm not convinced that this won't be confusing for a majority of users.
