### ISSUE TITLE
UI Inconsistency/Bugs

### ISSUE THREAD

**Issue by ItsLogic** [inorichi/tachiyomi#2286]
App version: 0.8.5 + r1531

Android version: 9

Issue/Request:various UI inconsistencies/bugs

Backup restore progress indicator:

Steps to reproduce (if applicable)
1. start restoration of backup
2. rotate device landscape then rotate back to portrait 

Other details: Progress indicator does go back to normal after a short amount of time but does look frozen/broken until it does so. See image 1 before the steps and image 2 after the steps:

![Image 1](https://user-images.githubusercontent.com/38233332/67107798-0cf8e400-f1c5-11e9-97d7-4ad3f491b42d.png)
![Image 2](https://user-images.githubusercontent.com/38233332/67107815-15e9b580-f1c5-11e9-96e9-bcd2057371ba.png)

UI inconsistency when searching (filter button is lost):

Steps to reproduce (if applicable)
1. search for manga title
2. select manga title
3. back out to search page

Other details: See image 3 before the steps and image 4 after the steps (top right corner):

![Image 3](https://user-images.githubusercontent.com/38233332/67107817-15e9b580-f1c5-11e9-8be8-b5e3de92ee3a.png)
![Image 4](https://user-images.githubusercontent.com/38233332/67107816-15e9b580-f1c5-11e9-960f-bc58ed65d0db.png)

**Comment by arkon** [comment]
Restore was moved to a notification and the search issue was fixed earlier.
