### ISSUE TITLE
Date display issue in updates

### ISSUE THREAD

**Issue by kiriya-aoi** [inorichi/tachiyomi#2290]
**App version:**
r1531
**Android version:**
8.1
**Issue/Request:**
The libary updates page has issues with the relative date display. Only appears to happen when the page is left open for multiple days.
**Steps to reproduce (if applicable)**

 1. Visit the library updates page in the app.
 2. Do not use your device for anything but staying on this page or reading manga from this page past a date change or two.
 3. Updates should show up with weird relative dates, like days into the future or several days being today. A couple examples are attached.

**Other details:**
![Screenshot (Oct 14, 2019 19_55_30)](https://user-images.githubusercontent.com/34067059/67150359-7be94200-f284-11e9-8465-d487ef5b9be0.png)
![Screenshot (Oct 19, 2019 00_19_55)](https://user-images.githubusercontent.com/34067059/67150360-7be94200-f284-11e9-9a36-c28cc2523783.png)

**Comment by arkon** [comment]
This is a bit of an edge case that's easily avoidable by just re-opening the view. Effort to "fix" it is too high IMO.
