### ISSUE TITLE
Duplication of chapters in the mangas

### ISSUE THREAD

**Issue by swordart16** [inorichi/tachiyomi#2297]
App:v.r1534
Android:5.1
When updating the library, repeated manga chapters appear

**Comment by happywillow0** [comment]
Is it happening to all mangas or a particular extension? It might be an extension issue.

**Comment by swordart16** [comment]
Apparently it is the extension in Spanish [Tumangaonline] where the chapters of some mangas are duplicated
https://ibb.co/pW0dsZj

**Comment by happywillow0** [comment]
There was a request to separate the scanilators because a chapter may be translated by different groups. 
https://github.com/inorichi/tachiyomi-extensions/issues/1671

In the three dot menu, you can choose Sorting Mode, by chapter number, to skip the duplicate chapters while reading.

**Comment by swordart16** [comment]
I already tried but I want it to not appear in the interface of the chapters
https://ibb.co/fpPZTWb

**Comment by joseph619** [comment]
That is not possible to do, you have to change source for that. Mangadex allows multiple groups to upload their scans for the same manga.

**Comment by MerradOklom** [comment]
Hola. Aquí algunos consejos para TuMangaOnline:

1. Habilita la opción Saltar capítulos leídos (Skip read chapters) en Configuración > Lector. Una vez hecho esto puedes marcar los capítulos extras como leídos para saltarlos. 

2. Otra opción es entrar a un manga, estando en Capítulos selecciona los 3 puntos de la parte superior derecha y en "Modo de ordenado" cambialo a "Por número de capítulo". Si lo haces se saltará los capítulos extras, pero debes recordar cambiar el ordenado a tus mangas manualmente porque no es una opción global. 

Por último, la segunda mejor opción después de TuMangaOnline es NineMangaEs ya que roban el contenido de ellos tienen la misma cantidad de mangas. 

Espero haber sido de ayuda.

**Comment by happywillow0** [comment]
I have added a preference in TuMangaOnline to remove duplication / show one chapter.

Once the update is done, you can select the preference in 
Extensions -> TuMangaOnline [Details] -> Chapter List Scanlator Preference
