### ISSUE TITLE
Title search for tracking

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#2298]
**App version:** 0.8.4

**Android version:** 9

**Issue/Request:** Modify / Fix the title search for the tracking feature. Sometimes, if I try to search the title of a manga I'm reading in that moment, I have to scroll to find the manga, it won't appear as first result, and sometimes I can't find the manga in the list the app returned, even tho the site has it in the database (I use both MAL and AniList, this is in the steps below, only happened with MAL, AniList was easier to find, but i don't remember if I had to change the name or used the automatic one that appeared).
If possible, modify that search feature so you can activate, with enableable boxes, that it have to search for the exact name you give, to find the manga that starts with the string you give or make it also possible to use the ID of the site (in the case below in the url, the id would be 116943).

**Steps to reproduce (if applicable)**
(Steps for the actual issue i encountered)
 1. [This is a manga MAL has in the database, as you can see](https://myanimelist.net/manga/116943/Kimi_to_Boku_no_Saigo_no_Senjou_Aruiwa_Sekai_ga_Hajimaru_Seisen)
 2. Try to write the name in the tracking on Tachiyomi for MAL (i use Mangakakalot source, but i suppose the source here doesn't matter)
 3. You can't find the manga to link it and so you can't activate the auto-sync, I tried with the name the app wrote by itself, I used the name with romaji and also the english name, i couldn't find the

**Other details:**

**Comment by CarlosEsco** [comment]
I am unable to find the manga when searching through the website.  When the type is restricted to manga.  Can you send a url where that manga result is there?

**Comment by antocs** [comment]
Do you mean this https://myanimelist.net/manga.php?q=kimi%20no%20boku%20no%20saigo ? Is the first result.

**Comment by MerradOklom** [comment]
This happened to me before, but as you can see the manga you mention is not ranked and has 0 users following, my guess is that it's still on pending state and you can't add it to you mangalist yet.

**Comment by antocs** [comment]
Oh, well but if we put this case aside, it also happens that sometimes you have to scroll down to find the manga.
I remember that for some manga I had to scroll like 10-20 manga below to find it, even tho i have the same name it had there.

**Comment by Llethander** [comment]
This might be, or might not be, related but I have noticed that there are frequently titles that I can find on a site, Mangadex as an example, that just don't populate as results in the Tachiyomi search.

Example: https://mangadex.org/title/42967/a-tale-of-being-eaten-by-a-man-eating-youkai

**Comment by MerradOklom** [comment]
> This might be, or might not be, related but I have noticed that there are frequently titles that I can find on a site, Mangadex as an example, that just don't populate as results in the Tachiyomi search.
> 
> Example: https://mangadex.org/title/42967/a-tale-of-being-eaten-by-a-man-eating-youkai

I searched in Browse and did a global search:
![IMG_201911315_093458](https://user-images.githubusercontent.com/43864503/68588066-5ad0d700-0467-11ea-8ee2-e0fd725bf070.png)
![IMG_201911315_093528](https://user-images.githubusercontent.com/43864503/68588086-67552f80-0467-11ea-9add-390012255649.png)
Or perhaps I misunderstood and you meant to say you couldn't find it in the tracking tab?

**Comment by Llethander** [comment]
Odd...
![Screenshot_2019-11-11-04-47-17-112_eu kanade tachiyomi](https://user-images.githubusercontent.com/10265978/68588472-6d82e600-043e-11ea-8c50-b23b6a4c53bf.jpg)

**Comment by MerradOklom** [comment]
> Odd...
> ![Screenshot_2019-11-11-04-47-17-112_eu kanade tachiyomi](https://user-images.githubusercontent.com/10265978/68588472-6d82e600-043e-11ea-8c50-b23b6a4c53bf.jpg)

Strange indeed. Just to be sure, are you using the latest version of the app (0.8.4 Stable build/r1532 Dev build)? And did you log in to MD using web view?

**Comment by Llethander** [comment]
Ah, that did it. Signing in using web view was the key.

I thought I had done so before but I guess I only did it for Captcha issues.

**Comment by arkon** [comment]
Searching trackers by ID: #1879
