### ISSUE TITLE
Trying to update manually installed apk with F-Droid (different key)

### ISSUE THREAD

**Issue by jassibacha** [inorichi/tachiyomi#230]
When I first found Tachiyomi I manually installed the .apk on my phone & tablet, but now I've got F-Droid installed so I can do automatic updating, however it's giving me an error saying the new version is signed with a different key, and that I must manually uninstall the old version first. That will remove internal data within the app, so wouldn't I lose my current library?

Image at the bottom of this post for the full error.

Apologies if the answer to this is somewhere else, might be worth adding to the FAQ though.

---
Version: r000 or v0.1.3
Galaxy S6

![tacihiyomi-f-droid-error](https://cloud.githubusercontent.com/assets/3331801/14052197/87d47c22-f285-11e5-9b1c-c901eb3b1da7.png)

**Comment by j2ghz** [comment]
You will. You can try using apps like Titanium Backup to backup the data, uninstall app, install app and restore data.
That is expected, because F-Droid builds the apks itself, using its own key, not inorichi's, so the apks have different keys.

**Comment by jassibacha** [comment]
Ah okay good to know,

Is there a specific folder I could just backup manually to my computer or something? I read before that Titanium Backup needs your phone to be rooted. :/

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/195

**Comment by inorichi** [comment]
My releases can't have the same signing key as F-Droid, so you can't switch from one to another without uninstalling first.

I'll close this, but feel free to comment if you need more help. You probably can't backup the data without root. I'll try to merge #212 soon.
