### ISSUE TITLE
Suggestion/Request: faster multiple-source search with downloaded lists

### ISSUE THREAD

**Issue by Efreak** [inorichi/tachiyomi#2301]
The FMD project uses a downloaded list of mangas at each source (available [here](https://github.com/fmd-project-team/FMD-WebsiteDatabases/tree/master/packages)) and relies on this for speeding up searches. When searching multiple sites in Tachiyomi, it can be quite slow--it would be nice if it had an optional local list to search instead, to speed things up.

**Comment by CarlosEsco** [comment]
Wouldn't you need to update the local list often? Also what is the size of this for fmd? If it's a decent size would you want that on your phone taking up space ?

**Comment by wopian** [comment]
Looks to be a ~40mb database per source.
