### ISSUE TITLE
Long app loading time

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#2302]
Tachiyomi r1531

Android 9

Long app loading with white screen

On every cold start the app takes too long too open. Android asks if I want to terminate it. I tried to clean the cache or restore from backup. It didn't help. I am not sure if it is related but I have over 1000 library entries and almost all English extensions-sources. I also tried to open the 0.8.4 version which I didn't touch in a long time (and library is smaller there) and the same issue happened.

**Comment by CarlosEsco** [comment]
If you can you will need to attach logs

**Comment by serjflint** [comment]
Removing half of extensions also didn't help

**Comment by serjflint** [comment]
I will attach the logs if you tell me how

**Comment by ardittristan** [comment]
A bit ago when i changed my downloads location from the default eu.kanade.tachiyomi location on my sd card to a cusom location on my sd card i did notice a severe slowdown in loading. Once i reverted back to the default location it loaded quickly again.

**Comment by serjflint** [comment]
> A bit ago when i changed my downloads location from the default eu.kanade.tachiyomi location on my sd card to a cusom location on my sd card i did notice a severe slowdown in loading. Once i reverted back to the default location it loaded quickly again.

Not my case, I have it in default location and don't have an SD card. 
After several days it still opens up with a white screen but for a reasonable time.
