### ISSUE TITLE
Error while trying to share a chapter page

### ISSUE THREAD

**Issue by IRohit789** [inorichi/tachiyomi#2303]
**App version:** 0.8.4

**Android version:** 5.0

**Issue/Request:** Getting an error "file format not supported" while trying to share a page in manga by long pressing it.

**Steps to reproduce (if applicable)**

 1. Open any manga chapter
 2. Long press on page and click on share option
 3. Then click on whatsapp

**Other details:**

**Comment by arkon** [comment]
What sources/manga/chapters have you tried it with? It's worked fine for me.

**Comment by IRohit789** [comment]
All sources mangas and chapters actually. Though for the same manga from the same source my friend didn't have any problem

**Comment by arkon** [comment]
Sounds like an issue with the particular device.
