### ISSUE TITLE
[Feature Request] Add Error Log for Updating Category

### ISSUE THREAD

**Issue by tdosch616** [inorichi/tachiyomi#2307]
**App version:*0.8.4*

**Android version:*MIUI Global 10.3.8 (Android 9 PKQ1.180729.001)*

**Issue/Request:*ReadMangaToday often Changes its Paths for Example Solo Leveling
https://www.readmng.com/solo-leveling/ was changed to https://www.readmng.com/solo-leveling-1/ and then to https://www.readmng.com/solo-leveling-2/ when i update solo leveling manually i get "http error 404" then go over to cataloges and add the new solo levling (-2). Updating Category doesnt show me that solo leveling is having an Error so is it possible to add an Error Log to updating Category so i can see which Mangas are broken / changed adress. *

**Comment by arkon** [comment]
Added to preview a while back.
