### ISSUE TITLE
[Issue/Request] Fix web view

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#2309]
**App version:** r1531

**Android version:** 9

**Issue/Request:**
Fix/Improve web view, manga pages are crooked and there is no way to scale the page.
Also, buttons (links) on these pages are not pressed.
What prevents to log in and normally use web view.

**Steps to reproduce (if applicable)**

 1. install mangalib or mangatown etc.
 2. open manga in web view
<details>

**BROWSER**
![Screenshot_20191102-101409](https://user-images.githubusercontent.com/35057681/68068921-ecf82180-fd7b-11e9-840b-f4225219ee30.jpg)

**WEB VIEW**
![Screenshot_20191102-101416](https://user-images.githubusercontent.com/35057681/68068922-ecf82180-fd7b-11e9-9883-bf5c712a304e.jpg)

**BROWSER**
![Screenshot_20191102-101437](https://user-images.githubusercontent.com/35057681/68068923-ed90b800-fd7b-11e9-857e-fbfcb449e200.jpg)

**WEB VIEW**
![Screenshot_20191102-101444](https://user-images.githubusercontent.com/35057681/68068924-ed90b800-fd7b-11e9-9493-7c3634efb718.jpg)

</details>

**Comment by Kiolli** [comment]
+

**Comment by arkon** [comment]
It's dependant on whatever WebView you're using on your phone. It also isn't actually meant to be something for you to read in, you could just use your browser to do that.

**Comment by e-shl** [comment]
@arkon then how to use for authorization?  on the sources of which it is necessary to autorezirovat to use all the functions
