### ISSUE TITLE
[Feature Request] Resume reading, page division, remember zoom, extensions browsing

### ISSUE THREAD

**Issue by Dangelman** [inorichi/tachiyomi#2311]
**App version:** 0.8.4

**Android version:** 8.0.0

**Request:**
- Resume reading from where you've interrupted, this is extremely useful for people who are reading manga with numerous chapters and pages per chapters. Just pop-up a notice when selecting a manga that asks you if you want to resume your reading.
- Option to divide automatically pages in two, useful for scans with two pages in one pic. In particular, I'm reading _Pocket Monster Special_ on NineManga and it's annoying to have to zoom each page due to the width being higher than the height.
- Option to remember the amount of zoom, for when you need to zoom to read a manga, but you don't wanna zoom each time you turn a page. Just need to remember it for a session.
- Extensions search tool, I remember I've spent quite a bit of time when looking for MangaFox, and it's frankly annoying. A simple search tool would be nice.

**Comment by MerradOklom** [comment]
Page division: this feature was requested and discussed in this issue #1384

Remember zoom: already requested in this issue #1822

Extension search: this was recently added in the developer version

**Comment by Dangelman** [comment]
> Extension search: this was recently added in the developer version (#2211)
Should I remove it from the post then? Do you know when would it be implemented in the public version?

**Comment by MerradOklom** [comment]
You can download the dev build from here: https://tachiyomi.kanade.eu/latest
It's pretty much stable in my opinion. 
By the way, in the "Recently read" tab you can resume what you read, it also remembers your reading progress.

**Comment by joseph619** [comment]
@Dangelman  Please close this, everything you requested is already being worked on or completed. Also download the Dev version for latest updates, Stable is 6 months behind.

**Comment by Dangelman** [comment]
> everything you requested is already being worked on or completed

That's exaggerated.
