### ISSUE TITLE
Dev Auto-update does not work

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2313]
App version: r1531 

Android version: 9

Dev was just updated yesterday, and it did not trigger Auto-update. I had to manually update it in Settings > About.

**Comment by sharedkestrel** [comment]
It worked for me, on the same Android and Tachiyomi version

**Comment by lmj0011** [comment]
I'm pretty sure you have to download the app through f-droid to get the auto updates. As far as I know, you always have to manually update the dev version.

**Comment by bbtora** [comment]
> I'm pretty sure you have to download the app through f-droid to get the auto updates. As far as I know, you always have to manually update the dev version.

No, auto-update feature has been added in dev version too.

**Comment by CarlosEsco** [comment]
@lmj0011  fdroid hasn't been supported for a while

**Comment by lmj0011** [comment]
@CarlosEsco oh I see, how long has f-droid been unsupported? Looks this info was only recently [added to the website](https://github.com/tachiyomiorg/website/commit/a6d6b1bb26f46019640f3bc1b064760b7ea06b08)

**Comment by arkon** [comment]
> how long has f-droid been unsupported?

It hasn't really been officially supported for quite some time now, although the documentation was pretty outdated for a while.

I haven't really heard of this issue other than this one instance, so just going to close it.
