### ISSUE TITLE
[Feature Request] Have Notifications for updates in user library.

### ISSUE THREAD

**Issue by baddwolff** [inorichi/tachiyomi#2314]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:** Toast Notifications showing updates would be appreciated.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by arkon** [comment]
This already exists if you have Library updates turned on.
