### ISSUE TITLE
[Feature Request] Would be great to add opds support

### ISSUE THREAD

**Issue by ComicLover2112** [inorichi/tachiyomi#2315]
Would it be possible to add opds support for self-hosted comic server such as ubooquity? Will be great for users that already have a large categorized collection to read on their devices. It's hard to find an app to support android 4.x.x now for some old e-ink devices.

**Comment by CarlosEsco** [comment]
There is support for https://github.com/gotson/komga you set the server and what not and install the extension

**Comment by gotson** [comment]
@ComicLover2112 I am the developer of Komga, it does roughly what Ubooquity does, apart from the folder organization. But it has a native Tachiyomi extension (which i developed).

At first i thought about developing an OPDS extension to integrate with Ubooquity, but i encountered some issues:

- the OPDS feed of Ubooquity is invalid XML, meaning standard parsers like Jackson cannot parse it. You have to use a more low-level XML parser, and handle errors manually.
- Ubooquity doesn't have a flat structure for folders, but Tachiyomi expects that. So getting the list of all folders containing books via Ubooquity's OPDS feed would require a lot of http calls to reconstruct this view. Komga offers this natively in one http call.
