### ISSUE TITLE
Add viewing option [webtoon,horizontal,vertical]  for each comic

### ISSUE THREAD

**Issue by ulrych8** [inorichi/tachiyomi#2316]
Could you add the possibility to have different viewing option per comic.
In order to be able to have specific settings remembered.

## WHY :
I use webcomic view for webcomics but I have to go to parameters to change the view when I want to read manga for instance.

Thank you!

**Comment by MerradOklom** [comment]
¿Have you tried this?:
Press the middle of the screen on the comic you're reading, tap the cog button in the top right of the screen and "select viewer for this series".
