### ISSUE TITLE
Backup/Restore is restoring only up to weeks ago

### ISSUE THREAD

**Issue by Noriller** [inorichi/tachiyomi#2319]
**App version: 0.84 (both phones)**

**Android version: Current: 8.1 and New: 9**

**Issue**
I'm trying to pass everything from my current phone (moto g5s) to a new one (motorola one), both apps (and phones) are up to date.

I've just tried backing up the whole current phone and reinstalling on the new so it would use the backed up data, but it gives me old data, weeks old.

Then I backed the current phone on the app (manual backup) and restored on the new phone... yet again it don't fully restore to the current phone actual data.

I've also tried to clean the app on the new phone and then restore, but then if it got out of the restore screen (or turned off) it would freeze and I had to do it again, if I managed to make it go to the end, then again, it didn't fully restore.

**Comment by kagehisa** [comment]
I'm having the same issue here.

**Comment by Noriller** [comment]
I ended up checking it manually to bring the data up to date... 

I love the app anyway and want to thank you all.

**Comment by hXtreme** [comment]
A few things to try:

Ensure that you have all the required extensions installed before restoring backup.(You could potentially be missing some manga because you don't have the extension installed)

When creating backup try saving it in a different location from the usual (so that it's clear which backup is latest).

----
Also what all is missing in the backup? Manga that you recently added? Read/unread status?...

**Comment by Noriller** [comment]
For me it was mostly the read/unread. The new added manga were there... but then again the reading status was an issue.

Since it was just a few weeks old, I ended up having both phones side by side and updating it manually, but it would really be hard to do it in any other way.

**Comment by kagehisa** [comment]
It is the same for me, newly added stuff is there. But the reading history is just not right. Extensions are the same on both sides and the backup json file is the latest one.

**Comment by arkon** [comment]
What sources do the backups contain manga from?

**Comment by CarlosEsco** [comment]
yea my initial guess is extensions moving into different multiple source extensions breaking the restore for those manga

**Comment by kagehisa** [comment]
ComicExtra, MangaKakalot and Manga Rock. The Extensions for those are installed on both devices.

**Comment by RuthlessRuler** [comment]
You may try clearing up you chapter cache and clear database to see if it works. if there are some mangas that are being skipped then you get a log file for it when restoring so the problem should be in the backup file you created as they don't have chapters marked read/missing mangas/manhwas,
Alternatively you can use Lucky Pathcher/Migrate/titanium backup to backup and restore if your device was rooted.

**Comment by kagehisa** [comment]
Ok after migrating everythin from Mangarock to Mangakakalot backup works kinda as intended. I removed the Mangarock extensions from both devices and backup restore is now consistent with the main device. The only exceptions are some Mangas from Mangakakalot which give me an error on ther main device that sates: "Page list is empty". These mangas then cause an error during a restore operation. But I would say this is unrelated to the backup function and is more of a glitch of the Mangakakalot extension. I will see if there are already some open issues in that regard and if not open one. 
Thanks for the help so far!
