### ISSUE TITLE
Unable to log into batoto in latest version 

### ISSUE THREAD

**Issue by Rauvagol** [inorichi/tachiyomi#232]
Tested in fdroid and manually installed version, attempting to log in returns "unknown error", but it works fine when using  v.1.3

---
Version: v0.1.3
Nexus 7 2013, Rooted, Stock ROM

**Comment by inorichi** [comment]
Can you look for a stack trace of the error in a logcat?

**Comment by cylonu87** [comment]
I have the same problem with the release version (0.1.4) .
On android 4.1 and 4.4, it's working.
On android 5.1 and 6, the button become red with the message unknow error. I didn't find an error in the logcat.
I tried the debug latest build r590 on android 6 and it's working.

**Comment by inorichi** [comment]
Oh, right, I forgot I didn't log the error there.

Someone had this issue before (#213), maybe it helps. If it works in the debug version that's a good thing.

PS: I didn't know you were using this app, @cylonu87. I've used yours too and it's very good. Nice work. :)

**Comment by Rauvagol** [comment]
I didn't see an error in logcat, but I have no idea how to use it properly, so that could be coincidence

**Comment by cylonu87** [comment]
I downloaded the source of v0.1.4 and added the log in the code: [log.txt](https://github.com/inorichi/tachiyomi/files/190626/log.txt)

It seems there is a problem with the certificate with okhttp. v0.1.4 was using okhttp 3.1.1 and debug version is using okhttp 3.2. Maybe the new version of okhttp fixed the issue.

@inorichi I check others apps like you probably do

**Comment by inorichi** [comment]
Thanks for looking into it. And yes, I do check the alternatives (and try to get some ideas from them too).

@Rauvagol, you could try installing the debug version for now (you can have both versions installed), or wait until a new release, but it will take some time, because it's less stable than 0.1.4 at the moment.

**Comment by Rauvagol** [comment]
I checked out the debug version, but since there doesn't seem to be a way to import/export my 228 Manga library, I guess I will just read non-batoto stuff for the time being. Thanks for the quick responses though.

**Comment by j2ghz** [comment]
@Rauvagol there seems to be a non-root user friendly solution https://play.google.com/store/apps/details?id=com.koushikdutta.backup&hl=en

**Comment by Rauvagol** [comment]
Maybe it is because I am sleep deprived, but I cannot figure out how to use that to move data between versions

**Comment by beepFTW** [comment]
I don't think there is a way to move data between versions at the moment.

**Comment by j2ghz** [comment]
Tried it and failed, had to use https://sourceforge.net/projects/adbextractor/files/ (definitely not user friendly) but it didn't unpack the backup right (tar unreadable), so theoretically it should work, but it doesn't.

(The idea was to take a backup, unpack it, change app ids to .debug, pack it and restore)

**Comment by Taumer** [comment]
You can try to copy files from
 /data/data/eu.kanade.tachiyomi/databases
to 
 /data/data/eu.kanade.tachiyomi.debug/databases

**Comment by j2ghz** [comment]
You don't need root for that?

**Comment by Taumer** [comment]
Yes,need root. But he rooted alredy

> Nexus 7 2013, Rooted, Stock ROM

**Comment by j2ghz** [comment]
I got it mixed up with another issue, though he didn't have root.

**Comment by Rauvagol** [comment]
Looks like copying the database files to debug folder did the trick, thanks for the help everyone :)
