### ISSUE TITLE
[Feature Request] LHScan As a Source

### ISSUE THREAD

**Issue by Henrique245** [inorichi/tachiyomi#2320]
Personally i prefer LHScans as my source for raw manga and it would be great if it was added to tachiyomi, thanks.

**Comment by MCGitHub15** [comment]
[You should request this on the tachiyomi-extensions repository.](https://github.com/inorichi/tachiyomi-extensions/issues)

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/236
