### ISSUE TITLE
[Feature Request] Favorite Sources

### ISSUE THREAD

**Issue by Noriller** [inorichi/tachiyomi#2322]
**App version: 0.84**

**Android version: 9**

**Request:**
I have tons of sources (I basically download almost everyone) but I have a few that I like to see if there's something new.

Like the Manga Plus one... every now and then they release new mangas and every now and then I go there to check if I'm missing new mangas... same for other few sources I like.

I can either hide everything else or endlessly scroll to find those sources. If I'm searching for manga, then I would either have to un-hide the sources or do something else.

**Other details:**

By having favorite sources, I can check those whenever I want more easily and if I need to search new manga, those would show up first. 

Then after that could be the sources you already have manga saved.

After that all others.

It would help a lot when searching for manga or trying to see if your favorite scanlators started new projects.

Thank you all, love the app.

**Comment by jatinAroraGit** [comment]
If by sources you mean the Catalogs then as mentioned in the readme the feature requests of those have to be created in https://github.com/inorichi/tachiyomi-extensions repository.

**Comment by arkon** [comment]
Yes, this is the correct repo for this issue.

**Comment by jatinAroraGit** [comment]
Hey, 
Just did a PR to add this feature.

**Comment by hXtreme** [comment]
FYI: You can hide sources by clicking on the gear icon in catalogues. So you for sources that you don't use or don't check, simply hide them to de-clutter.
