### ISSUE TITLE
Issue with "download new chapters" feature!

### ISSUE THREAD

**Issue by lonewolf0211** [inorichi/tachiyomi#2325]
**App version:** 0.8.4

**Android version:** 8.1.0

**Issue/Request:**
Recently began having issues auto downloading new chapters. I've had to manually download my manga chapters for the last few weeks. I really enjoyed the download new chapters feature and it's kind of disappointing that it isn't working.

**Steps to reproduce (if applicable)**

1. Go into settings, then select downloads and enable "download new chapters".
 2. Select a category or categories to include in the download.
 3. Wait for new chapters to appear once library updates, then it should download new chapters... But it's doesn't!

**Other details:**
I use multiple extensions: webtoons, mangarock, mangasee, mangahere. And none of them are auto downloading new chapters.

This is the only issue I've ever experienced with Tachiyomi. I love this app and the people behind it. It's the best manga reader I've ever used! 

**Edit:**
Since opening this issue I discovered that using multiple category tags on a manga prevents autodownloads from working. It's hard to explain but the image below should help. I have 3 categories: reading, manga, webtoons. Reading is set to download new chapters but the manga and webtoons inside Reading use multiple tags. When I removed all but one category tag auto downloads began to work for those manga. It's also possible that what I experienced was just a coincidence but who knows.

![Screenshot_20191114-001216](https://user-images.githubusercontent.com/36937946/68828371-6ee92400-0673-11ea-9227-c001c9149e9d.png)

**Comment by hXtreme** [comment]
Considering your edit

Maybe the check for whether to download a manga or not may be as follows:

If download is on for category `c1` AND category `c2` AND ... then Download

When instead the expected behaviour should be:

If download is on for category `c1` OR category `c2` OR ... then Download


----
FYI: I was able to reproduce the issue by following the instructions in the Edit section.

I have category called Download which is set to download and another called All not set to download. So nothing downloads automatically.

**Comment by lonewolf0211** [comment]
> Considering your edit
> 
> Maybe the check for whether to download a manga or not may be as follows:
> 
> If download is on for category `c1` AND category `c2` AND ... then Download
> 
> When instead the expected behaviour should be:
> 
> If download is on for category `c1` OR category `c2` OR ... then Download
> 
> FYI: I was able to reproduce the issue by following the instructions in the Edit section.
> 
> I have category called Download which is set to download and another called All not set to download. So nothing downloads automatically.

The downloads feature does appear to function the way you mentioned. The downloads weren't starting because they hadn't fulfilled the trigger parameters for being downloaded. Like you said, it was looking for both categories to be enabled but only one was. But it would be nice to have this fixed so that chapters download if they are part of either category that has been set to download.

**Comment by hXtreme** [comment]
Probably needs some changes around https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt#L299

**Comment by Quiksmage** [comment]
I found this issue as well in both stable/dev.

**Comment by tulang3587** [comment]
This is still happening on dev r1753.
