### ISSUE TITLE
Error http 403

### ISSUE THREAD

**Issue by charbin92** [inorichi/tachiyomi#2327]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.4

**Android version:** 8.0.0

**Issue/Request:** Recieving HTTP Error 403

**Steps to reproduce (if applicable)**

 1. Open app 
 2. Select Manga from Library
 3. Select Chapter or scroll to update chapter 

**Other details:** Since 11/14/2019 I have been having issues opening and updating any of the chapters. I keep getting error: "http 403" when I try to do either of those. I have checked for updates and uninstalled and then reinstalled the app and still have the same issue.

**Comment by arkon** [comment]
There's an open issue in the extensions repo about Kissmanga. You can attempt to do the captcha in WebView.
