### ISSUE TITLE
[Feature Request] update extension while refreshing library

### ISSUE THREAD

**Issue by SkyNalix** [inorichi/tachiyomi#2330]
###  Why/Project's Benefit/Existing Problem
When you are refreshing your library, if somes mangas are from an extension who has an update
Why not directly ask "Do you want to update this exension?" and then, refresh the manga
Can also ask to update ALL extensions
It will help a lot
Sometimes i'm refreshing my library, and then i saw that i have some extensions who has an update, but i don't know if the manga, from this source was correctly refreshed
so everytime, i have to update them, then refresh library again 

Sorry if my language is not correct :)

**Comment by RuthlessRuler** [comment]
I think instead it would be better to give us a Notification when there in an update to the extension available.

**Comment by arkon** [comment]
Closing in favour of #2520
