### ISSUE TITLE
App is unable to find local manga

### ISSUE THREAD

**Issue by martmists** [inorichi/tachiyomi#2334]
**App version: 0.8.4**

**Android version: OxygenOS Latest Stable (Android 8.1)**

**Issue/Request: App is unable to find manga locally**

**Steps to reproduce (if applicable)**

 1. Download the monogatari manga epub
 2. Try to load it in the app
 3. The app should be unable to find it

**Comment by arkon** [comment]
Where did you put it?

Guide: https://tachiyomi.org/help/guides/reading-local-manga/

**Comment by martmists** [comment]
![Screenshot_20191120-020647](https://user-images.githubusercontent.com/16361449/69200121-7ceae900-0b3a-11ea-9c8f-33e37d112657.jpg)
![Screenshot_20191120-020651](https://user-images.githubusercontent.com/16361449/69200122-7ceae900-0b3a-11ea-879c-6063ea893f79.jpg)

**Comment by arkon** [comment]
Try putting it in /Tachiyomi/local/Bakemonogatari

**Comment by martmists** [comment]
Same result

**Comment by hXtreme** [comment]
Could it just be that the e-pub is not in "proper" format. Try renaming the file extension to zip and then check the internal structure of the e-pub.

**Comment by arkon** [comment]
No response, closing. If you need more help, please ask on Discord.
