### ISSUE TITLE
Zin Translator stories not loading 

### ISSUE THREAD

**Issue by princess15mm** [inorichi/tachiyomi#2335]
**App version:**

**Android version:** Samsung Galaxy 8

**Issue/Request:** Zin Translator not loading most chapters. 

**Steps to reproduce (if applicable)**

 1. Open a chapter of most comics. 
 2. Loads for a while. 
 3. Retry pops up continuously. 

**Other details:**
I have deleted the catalog, updated it, tried other stories and restarted my phone. I have do far only found one story that loaded in the app, but the others will not work in the app but do online.

**Comment by hXtreme** [comment]
@arkon This seems like an extension issue and should be moved to tachiyomi-extensions repo.
