### ISSUE TITLE
Tachiyomi takes way too long to load library

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi#2336]
**App version: 0.8.4**

**Android version: 9**

**Issue/Request: the app takes too long to load. I think it has to do with the fact that I downloaded so many comics, because when I didn't have any downloaded, it immediately became faster. Could you make it so that it doesnt take so long for the app to load?**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by arkon** [comment]
Do you have download badges enabled?
