### ISSUE TITLE
Please add a screenplay function. It's really gonna be helpful to everyone. I like reading a manga and I also like re-reading it. The thing is it pains me to scroll it, I mean I have read it so I just want to skip the talking part but I dont want to scroll it just because it make me feel tired. So I hope you can add some function that can make the page is just keep scrolling without Im touching it to scroll, in other word a screenplay.

### ISSUE THREAD

**Issue by AH6A7** [inorichi/tachiyomi#2337]

**Comment by bbtora** [comment]
Close this immediately.

**Comment by CarlosEsco** [comment]
#2093

**Comment by AH6A7** [comment]
Add the screenplay function

**Comment by AmineI** [comment]
@AH6A7 This is spam. Stop immediately before you get reported. Github is a developer community, and if you didn't understand, Carlos mentioned that your request was already made and is still open. You can either wait for a developer to implement that feature, or go ahead and code that feature yourself for the community. 
Either way spamming won't do anything. You could also buy a Samsung and use [Smart Scrolling](https://www.samsung.com/in/support/mobile-devices/what-is-smart-scroll-feature-in-samsung-galaxy-s4/).
