### ISSUE TITLE
Feature request: editing download queue

### ISSUE THREAD

**Issue by ClearSights** [inorichi/tachiyomi#2338]
**App version:**
0.8.4
**Android version:**
9.0
**Issue/Request:**
Please consider enable users to edit the download queue, like pausing and removing a specific item. 
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
Sometimes the downloading of one item stalls with no progress, hindering the following items to be downloaded. If user isbable to pause or delete this item, the other items may finish downloading very soon.

**Comment by bbtora** [comment]
#809
