### ISSUE TITLE
[Feature Request] Automatically Retry When Download Timeouts

### ISSUE THREAD

**Issue by yakkyDoodle** [inorichi/tachiyomi#2342]
### App Version
0.8.4

### Android Version
MIUI Global 11.0.4 | 9 PKQ1.180904.001

### Issue/Request
Can we have an option in the Downloads settings for the app to automatically retry downloads when they timeout? Getting around download timeouts is to manually retry the download until it works; so it would be nice if the app can automatically do the retries for us.

**Comment by arkon** [comment]
It already retries up to 3 times.

https://github.com/inorichi/tachiyomi/blob/dev/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L397
