### ISSUE TITLE
[Error] Mangakakalot Chapter Retry

### ISSUE THREAD

**Issue by zyzzyvo** [inorichi/tachiyomi#2347]
Good Day. Whenever I try to read the Rebirth of the Urban Immortal Cultivator Ch. 166 - 168, it only shows retry. Please help

**Comment by toshiro9117** [comment]
I tried to install mangakakalot today but i cant find it anymore in the extension

**Comment by arkon** [comment]
@toshiro9117 Use MangaBox

**Comment by arkon** [comment]
If you're still having issues with the latest extension, open an issue in the tachiyomi-extensions repo.

**Comment by gr8falcon** [comment]
It really suck, this is mostly in mangakakalot
