### ISSUE TITLE
Slow downloads regardless of internet speed.

### ISSUE THREAD

**Issue by pluesan** [inorichi/tachiyomi#235]
Ridiculously slow downloading times. It can take up to a minute to download a single page. Tried on wifi, on network, rapid, skia, fiddled with other settings but download speed remains dreadfully slow.

---
Version: 0.1.4
Android M

**Comment by j2ghz** [comment]
Could be slow phone or memory?

**Comment by pluesan** [comment]
Moto X Pure, no bloat, no memory problems.

**Comment by pluesan** [comment]
Nvm. MangaHere just sucks balls, jumped over to Kiss and they were downloading chapters in seconds.
