### ISSUE TITLE
[Feature Request] Desktop version

### ISSUE THREAD

**Issue by Jzarecta** [inorichi/tachiyomi#2352]
Wonder if there is a chance to write or recomend a client for the Linux Desktop particulary KDE (qt5)? Thanks in advance.

**Comment by samanta-widjaja** [comment]
for windows too maybe? Thanks

**Comment by 46620** [comment]
[This](https://github.com/TachiWeb/TachiWeb-Server) right now is the best we have for a desktop client to my knowledge.

**Comment by jerycho007** [comment]
I found this to be working the best for windows but not exactly sure what you are looking for. It's not a port of tachiyomi.
https://sourceforge.net/projects/hakuneko/

**Comment by arkon** [comment]
#2119, kind of. There's no official stuff currently.
