### ISSUE TITLE
Kissmanga doesnt work

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi#2353]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Go to catalogues
2. Open kissmanga

### Expected behavior
It should open the kissmanga browser

### Actual behavior
This error shows: "SSL handshake aborted: ssl=0x7c2d0bea88: I/O error during system call, connection reset by peer"

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
wrong repo
