### ISSUE TITLE
[Issue] Continuous Chapter Reading "Retry" 

### ISSUE THREAD

**Issue by Zolcry** [inorichi/tachiyomi#2354]
### Device information
* Tachiyomi version: r1533 and 0.8.4
* Android version: EMUI 9.1.0.341
![Screenshot_20191202_222524_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/58501451/70116594-2ed0fc00-1689-11ea-8f4e-edd920c22539.jpg)

## Steps to reproduce
1. Read 1-4 chapters in continuity, that is, do not exit in between. 
2. Try to load the next chapter and be greeted by a "could not load chapter" and a retry button.
3. If you exit the reader mode and try to read the chapter, it will still not load. 
4. Can be done on any extension, happened to me in Mangakakalot and Leviathan scans

### Expected behavior
I should be seamlessly going forward to the nezt chapter, with a brief loading time for images in case I am using slow internet. 

### Actual behavior
I get stuck on the last page of the current chapter I am reading and the first page of the chapter doesn't load, instead it shows a connection timeout of sorts. 

### Other details
I can overcome the issue by going and reading a chaoter of another manga and then coming back to read the one with the issue.

**Comment by amorek** [comment]
Not sure if that's the same issue, but I'm getting loads of timeouts. When one page does not load, the retry button never works. If I exit manga and load chapter again it works most of the time.
Quite often the chapter does not load at all, sometimes rebooting helps though.

I'm usually using KissManga extension, but other extensions also have this problem.

**Comment by JDcarmelo** [comment]
> Not sure if that's the same issue, but I'm getting loads of timeouts. When one page does not load, the retry button never works. If I exit manga and load chapter again it works most of the time.
> Quite often the chapter does not load at all, sometimes rebooting helps though.
> 
> I'm usually using KissManga extension, but other extensions also have this problem.

Getting the same problem with Manga Rock and Mangahere i need to turn off and on the wifi to resume reading

**Comment by Zolcry** [comment]
I recently had a software update on my phone and it has pretty much fixed itself.
Most probably was Huawei messing up stuff. 
Will close the issue in 24 hours.
