### ISSUE TITLE
有没有通腾讯动漫和哔哩哔哩动漫

### ISSUE THREAD

**Issue by HiedanoAkyuu** [inorichi/tachiyomi#2355]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps t

**Comment by Doomsdayrs** [comment]
“ Tachiyomi”是漫画应用，不包含动漫资源

**Comment by HiedanoAkyuu** [comment]
> “ Tachiyomi”是漫画应用，不包含动漫资源

抱歉打错了，问的就是有没有腾讯和哔哩哔哩漫画的插件，粗略看了下插件列表，好像没找到

**Comment by CarlosEsco** [comment]
Source requests belong in tachiyomi-extensions repository.
https://github.com/inorichi/tachiyomi-extensions/
