### ISSUE TITLE
[Feature Request] Limit folder name length (filesystem issue)

### ISSUE THREAD

**Issue by patrickhgb** [inorichi/tachiyomi#2357]
### Why/User Benefit/User Problem
When Tachiyomi downloads a Manga and creates folder, sometimes the name can be too long.

This presents a problem when trying to backup the content.

I put an example below.

I have a OnePlus phone which allows me to use OnePlus switch to make a system backup of everything in the phone, which then I can copy and keep safely in my computer. It includes tachiyomi and other app data.

The issue is that, there are a few manga or comic which have really long titles that cause them to be incompatible with Windows/UNIX filesystems. As such, an error message will be displayed below when trying to copy the backup folder over to a computer.

https://i.imgur.com/I1jQweB.png

### What/Requirements

A simple feature should be added wherein tachiyomi will limit the number of characters when making a folder or image

Consider allowing users to toggle on/off feature if it's undesired.

**Comment by arkon** [comment]
Closing in favour of #3373
