### ISSUE TITLE
[Feature Request] Accept URL intent to add book from browser

### ISSUE THREAD

**Issue by dvhh** [inorichi/tachiyomi#2362]
### Why/User Benefit/User Problem
Usually search is better done through browser than the catalogue search function, looking trough the browser also useful to gauge interest for a manga.
Looking for the same manga again through the catalogue search engine is sometime a difficult task if the manga/comic name is generic enough.

### What/Requirements
Would be able to accept a url through share intent from the browser, if url is unsupported, an dialog box would notify of the rejection.
If supported the manga/comic would be added to "My library"

**Comment by arkon** [comment]
This is already somewhat supported by some extensions (MangaDex and NHentai for example).

**Comment by RuthlessRuler** [comment]
https://github.com/inorichi/tachiyomi-extensions should be a better place for this issue as its not a good idea to implement it in the app.

**Comment by dvhh** [comment]
@RuthlessRuler was not aware about implementation details, will migrate the issue.

@arkon, manifest for the application nor the extension ( I might be missing something though ) does not seem to imply support for url intent filter.

**Comment by arkon** [comment]
For MangaDex:

- https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/mangadex/AndroidManifest.xml#L4-L21
- https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangadexUrlActivity.kt
