### ISSUE TITLE
[Feature Request] Ability to Sync Chapters with MangaDex

### ISSUE THREAD

**Issue by RuthlessRuler** [inorichi/tachiyomi#2363]
### Why/User Benefit/User Problem
It would be awesome if all the Bookmarked chapters + reading progress can be updated to Mangadex. IDK if app extension can add the ability/the main app has to add ability.This will allow users to move from Mobile -> Desktop easily.

### What/Requirements
When a manga is bookmarked on tachi, it will automatically get bookmarked on MD and the chapter progress can also be synced.

**Comment by arkon** [comment]
MangaDex doesn't have an open API at this time.
