### ISSUE TITLE
[Bug] last Page Manga Scrolling Problem

### ISSUE THREAD

**Issue by RuthlessRuler** [inorichi/tachiyomi#2364]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9.0

## Steps to reproduce
1. Open the last chapter of RTL/LTR type manga/manhwa.
2. Fast Scroll till the end and the last page is shown. swipe again

### Expected behaviour
"There is no next chapter" Page

### Actual behaviour
Blank. requires additional swipe to end manga with last page shown again.

### Other details
![ScreenRecord-2019-12-13-21-17-14](https://user-images.githubusercontent.com/20885012/70813843-319dc080-1df0-11ea-913d-4570ae2065dd.gif)

P.s: Additionally, swiping after "There is no next chapter" should also close the manga feature should also be implemented.

**Comment by arkon** [comment]
Can't reproduce this. Please reopen it if you're still seeing this in 0.9.2+.
