### ISSUE TITLE
[Feature Request] Selective "new chapter" automatic download

### ISSUE THREAD

**Issue by angeluserrare** [inorichi/tachiyomi#2366]
### Why/User Benefit/User Problem
I have a lot of manga/comics in my library, some are actively read while others are there as a bookmarks for when i'm ready to start reading them. I work in areas with spotty connections and a lot of downtime and I like to try and download manga beforehand if I know there is a new chapter. I know about the automatic download option, but I don't want to waste bandwidth or battery downloading stuff I'm not currently reading and would prefer just the manga/comics that I'm currently reading. 

### What/Requirements
There is an option to automatically download new chapters in tachiyomi, but it's covers all new chapters. I'm requesting it be re-implemented as a individual toggle on each manga's Info page instead of blanket toggle for all manga.

**Comment by hXtreme** [comment]
Actually, you can create categories, once you make a category add all the manga you want downloaded to that category and set the auto downloader to download only from those categories.

**Comment by angeluserrare** [comment]
oh, your right! the category option isn't visible unless the download option is toggled, so I didn't know about it. Thank you.
