### ISSUE TITLE
Extensions not recognized by app/need reinstall after every boot.

### ISSUE THREAD

**Issue by Nexr0n** [inorichi/tachiyomi#2369]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 8 

## Steps to reproduce
1. Install an extension 
2. Close app and take out of running list 
3. Reopen app 

### Expected behavior
Should be able to open manga from the installed extension. 

### Actual behavior
Extension is no longer in the installed list in app but can still be found in the android settings list of installed apps. Must be re-installed. 

### Other details
https://youtu.be/WfA9tfC9BVE

**Comment by Kyuko** [comment]
Have you tried if those things happen in dev?

**Comment by hXtreme** [comment]
Does your phone have some non-standard security feature that runs after the extension is installed?

My phone (pocofone) does and I used to have similar issues but that got resolved about half a year ago after an update rolled out for my phone.

**Comment by Nexr0n** [comment]
> Does your phone have some non-standard security feature that runs after the extension is installed?
> 
> My phone (pocofone) does and I used to have similar issues but that got resolved about half a year ago after an update rolled out for my phone.

I’ve tried disabling every security feature I can and checked to make sure the data wasn't being moved by some sort of memory optimization.

**Comment by Nexr0n** [comment]
> Have you tried if those things happen in dev?

Yes, same issue.

**Comment by arkon** [comment]
Unfortunately seems like a device ROM issue.
