### ISSUE TITLE
Page list empty and challange not found

### ISSUE THREAD

**Issue by Sahrup** [inorichi/tachiyomi#2373]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9
![Screenshot_20191220-115339_Tachiyomi](https://user-images.githubusercontent.com/59082242/71240690-fe00f000-2333-11ea-8593-db3e742fb8e2.jpg)
![Screenshot_20191220-115345_Tachiyomi](https://user-images.githubusercontent.com/59082242/71240691-fe998680-2333-11ea-9c50-f0fb0a3b8f6d.jpg)

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
Sounds like CloudFlare issues - #2344
