### ISSUE TITLE
Invert colors for manga

### ISSUE THREAD

**Issue by stnm12brX2** [inorichi/tachiyomi#2375]
Staring at a mostly white manga page is strenuous so adding a feature that inverts the collor of manga so it becomes mostly black with white lines would be useful. I have no Idea how one would implement this (sorry).

**Comment by hXtreme** [comment]
I've tried this before and the reading experience was fairly terrible. 

You can try it by turning on colour inversion setting in the accessibility settings on your phone.

**Comment by arkon** [comment]
Closing in favour of just using the system accessibility setting.
