### ISSUE TITLE
[Bug] Manga doesn't found after Accidentally reinstall the app

### ISSUE THREAD

**Issue by Shikomori** [inorichi/tachiyomi#2376]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Open the app
2. Type the title on mangarock extension

### Expected behavior
The manga can be found because it's available on the web

### Actual behavior
This happened instead.

### Other details
This happen on another extension such as mangasee and mangahere
[
![Screenshot_2019-12-21-20-14-32-785_eu kanade tachiyomi](https://user-images.githubusercontent.com/59115256/71307901-0f2f2700-2430-11ea-88d5-7b31d49a1f35.jpg)
](url)

**Comment by arkon** [comment]
🦀MangaRock is kil 🦀
