### ISSUE TITLE
[Bug] Extension toonily is no longer found

### ISSUE THREAD

**Issue by kyu931** [inorichi/tachiyomi#2380]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 8.1.0

I can no longer download or watch webtoons from toonily, tried to reinstall it but didn't find the extension

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
It's in Madara now.
