### ISSUE TITLE
Manga not updating from any sources

### ISSUE THREAD

**Issue by martmists** [inorichi/tachiyomi#2381]
### Device information
* Tachiyomi version: 0.8.4
* Android version: OxygenOS OP3T_O2_Beta_26

## Steps to reproduce
1. Add several manga to library
2. Refresh when a new chapter should be out

### Expected behavior
Updates should appear

### Actual behavior
Updates are not appearing

### Other details
Affected sources:
- MangaRock
- MangaDex
- MangaLife
- Webtoon

I don't have any others installed, but this seems like it would be an issue with the app rather than the extensions.

**Comment by arkon** [comment]
Did you try opening them in the WebView to see if there was anything blocking it (e.g. captchas, age checks)?

**Comment by martmists** [comment]
Webviews are fine, only issue is that Webtoon reports "page list is empty" now

**Comment by nicksz95** [comment]
I dont know about others sites but, mangarock is closing down. The company is making a fully license site and its will be fully closed by the end of this year.

**Comment by keinezeit8** [comment]
For me webtoons restarted syncinc after opening web view and going through age verification.
