### ISSUE TITLE
Issue restoring backup

### ISSUE THREAD

**Issue by teo3300** [inorichi/tachiyomi#2387]
**App version:**
0.8.4
**Android version:**
6.0
**Issue/Request:**
Trouble restoring backups
**Steps to reproduce (if applicable)**
I made two backups (just to be sure) using the 0.8.4 version
and re installed the app at the same version.
Both backups gave the same error on ~30 mangas, the error seems like:
<manga name> - Value Manga is licensed at data of type java.lang.String cannot be converted to JSONObject

After restoring the backup, all mangas listed in the log don't appear in the library section as I had never read them

**Comment by SnakeDoc83** [comment]
I'm guessing the source you were using for those ~30 manga was Manga Rock.  Manga Rock has been removing manga from their site; so you can't restore those to Tachi.
