### ISSUE TITLE
[Bug] Manganelo Extension not Working

### ISSUE THREAD

**Issue by aniik8pv2** [inorichi/tachiyomi#2392]
### Device information
* Tachiyomi version: 0.8.4
* Android version: MIUI 11.0.2 running Android 7.0

## Steps to reproduce
1. Update mangas from Manganelo source
2. View any chapter from Manganelo Source manga

### Expected behavior
New chapter updates
Normal chapter open

### Actual behavior
"page list empty" error on screen when opening a chapter

### Other details
Additional details and attachments.

**Comment by joseph619** [comment]
Wrong repo, post on Tachiyomi Extensions
