### ISSUE TITLE
[Bug] Buttons not correctly centered

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi#2398]
### Device information
* Tachiyomi version: r1565
* Android version: 4.4.2

## Steps to reproduce
1. Open manga info/chapter list

### Expected behavior
-------

### Actual behavior
-------

### Other details
In the latest dev builds the blue resume button and the one to add manga to the library are not correctly centered, this only seems to happen in my Android KitKat (4.4.2), I tried in a different phone with Android 6 and they're displayed just fine. It is worth mentioning that the buttons still function properly, so I think this is a visual glitch.
![Screenshot_2019-12-27-18-05-16](https://user-images.githubusercontent.com/43864503/71534716-683f0500-28df-11ea-8c63-439d853730d7.png)
![Screenshot_2019-12-27-18-05-22](https://user-images.githubusercontent.com/43864503/71534719-71c86d00-28df-11ea-8a42-55dd0f2d832f.png)

**Comment by arkon** [comment]
I pushed something that might help with this. Oddly enough, I can't reproduce it in a emulator.

**Comment by hXtreme** [comment]
For testing it may help to change the screen size, idk.

**Comment by MerradOklom** [comment]
> I pushed something that might help with this. Oddly enough, I can't reproduce it in a emulator.
> 
> (Re-open this if it didn't help)

It worked, the last commit fixed it. Thank you!
