### ISSUE TITLE
[Bug] Catalogue List View Collapses after Search

### ISSUE THREAD

**Issue by MCAxiaz** [inorichi/tachiyomi#2401]
### Device information
* Tachiyomi version: 0.8.4, latest dev
* Android version: 28

## Steps to reproduce
![device-2019-12-27-193844](https://user-images.githubusercontent.com/24946428/71538494-cd472a80-28e0-11ea-9492-738766d6056a.gif)

### Expected behavior
List view should not collapse

**Comment by arkon** [comment]
Reproduced in stable 0.8.4.

**Comment by arkon** [comment]
Does this happen with the change in #2396 too?

**Comment by MCAxiaz** [comment]
Yea it's unrelated.

**Comment by CarlosEsco** [comment]
verified pull request works
