### ISSUE TITLE
[Bug] Tachiyomi crashing after opening settings

### ISSUE THREAD

**Issue by joshdabosh** [inorichi/tachiyomi#2404]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 8

## Steps to reproduce
1.  Using stable build from releases
2. Open settings > general, settings > advanced, settings > download

### Expected behavior
Selected menu should show up

### Actual behavior
App exits, no crash log from Android

### Other details
Phone is moto e5

Will be factory resetting soon, also will be trying to reproduce in android studio to see if my phone is the issue.

Tachiyomi has been working well for a while until yesterday.

**Comment by joshdabosh** [comment]
Okay, the dev release solved my problem. Will probably still look into why it's crashing.

**Comment by arkon** [comment]
Did you change any settings recently?

**Comment by joshdabosh** [comment]
No, just restarted my phone and installed dev build.

Stable build still crashes after restarting though.

Crashing started after I spammed the back button a bunch of times (for some reason last night), screen went blank and I lost all read data.

**Comment by joshdabosh** [comment]
Welp no idea, just going to close this now.
