### ISSUE TITLE
New application update

### ISSUE THREAD

**Issue by olo1990pl** [inorichi/tachiyomi#241]
Is it possible to do a small update for F-Droid, so you would have possibility of doing a copy of the database?
Last update on F-Droid was on February 23 and looking at New Features in debug thread on F-Droid it would be great.
I want to change to F-Droid debug, but about 300 manga makes me want to cry (because of different application certificate, I would have to re-add my manga).

**Comment by inorichi** [comment]
I'll release 0.2.0 in ~1 week (if I don't get any issue with backups). I'm currently fixing crashes to make it more stable than 0.1.4

**Comment by olo1990pl** [comment]
Thx for fast reply.
