### ISSUE TITLE
[Feature Request] 能不能添加Webdav进行备份

### ISSUE THREAD

**Issue by ccczrz** [inorichi/tachiyomi#2412]
我看见有许多软件都支持Webdav备份，能不能让这个软件也支持下呢

**Comment by arkon** [comment]
Why WebDAV? It doesn't seem that popular to me.

**Comment by ccczrz** [comment]
> Why WebDAV? It doesn't seem that popular to me.

我倒是感觉Webdav挺不错的

**Comment by WasdeAsde** [comment]
I think WebDAV is very rarely used. When a backup is made, it can still be uploaded using third-party software. So one could also use other network protocols like Samba or NFS. I don't think it makes much sense to add network backups in Tachiyomi. Even if so, I guess that more popular protocols will be used.

**Comment by ccczrz** [comment]
好吧，很抱歉麻烦你了😃
