### ISSUE TITLE
MangaDex library

### ISSUE THREAD

**Issue by Aericio** [inorichi/tachiyomi#2414]
Tachiyomi v0.8.4.
Android v9.

When you try to open the MangaDex library, it shows an error.

`failed to connect to mangadex.org/5.135141.76:443`

My MangaDex library is on version 1.2.73, and there aren't any updates for it.

**Comment by Aericio** [comment]
Sorry, just saw that this is wrong repo.

**Comment by arkon** [comment]
MangaDex is down for maintenance for up to 3 days.
