### ISSUE TITLE
[Feature Request] arabic sources recommendations

### ISSUE THREAD

**Issue by ahmad-elmasry** [inorichi/tachiyomi#2417]
I have some Arabic sources recommendations because the Arabic sources are just 3 in the app and 1 of them have issues with downloading  pages.
This is the first source ( https://mangaarabteam.com/ )
And this is the second ( https://gmanga.me/ )
I hope if you can add those 2 sources @Support-Notify

**Comment by hXtreme** [comment]
duplicate of #2416

**Comment by ahmad-elmasry** [comment]
Well its Divided into 2 things first is an issues ( manga.ae source dosent reload full pages of the chapter )  you can try kengan asura for example .
Second is recommendation, thats why i duplicated .
Well are you going to add those 2 sources or not ? @arkon

**Comment by joseph619** [comment]
Wrong repo, post on Tachiyomi-Extensions

**Comment by ahmad-elmasry** [comment]
Okay @joseph619
