### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ArjixGamer** [inorichi/tachiyomi#2421]
**App version:**
latest Dev
**Android version:**
8.0
**Issue/Request:**
[Feature Request]
**Steps to reproduce (if applicable)**

 1.Go to Download manager
 2.select a chapter
 3.delete it without clearing all the downloading list

**Other details:**
This is just my suggestion but if it has more than 40 in the queue then it will be such a pain to re-queue what was cleared so wouldnt it be beter add individual clearing off the queue?

**Comment by hXtreme** [comment]
Duplicate of #809
