### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by Birsing** [inorichi/tachiyomi#2425]
Mangadex has changed their domain from mangadex.org to mangadex.cc.
Please update the extension accordingly.
The chapters are not being updated.

**Comment by bbtora** [comment]
Won't be updated as .org is coming back. And if the extension changes to .cc you will be unable to read any old chapter

**Comment by DreiPixel** [comment]
At least make a temporary solution.

**Comment by arkon** [comment]
First of all, wrong repo.

Secondly, if you'd like to contribute a fix (that'll handle both new and old domains), then submit a PR.

**Comment by hXtreme** [comment]
A potential workaround, create a new extension for .cc domain. Users who don't want to wait for .org to be back can migrate to new extension and when they restart .org they can migrate back.

---

PS: Initially I was on team "wait for a week" but then I saw the meme on MD discord announcement page saying: "Tachiyomi is dead" which made me switch teams.
