### ISSUE TITLE
[Bug] Mangadex.org - no address associated with hostname

### ISSUE THREAD

**Issue by MartassCZ** [inorichi/tachiyomi#2427]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. First step - open catalogues
2. Second step - click on mangadex

### Expected behavior
Show manga on mangadex
### Actual behavior
Show error - Unable to resolve host "mangadex.org": No address associated with hostname

### Other details
Beacuse of mangadex new hosting service, mangadex change website to mangadex.cc

**Comment by hXtreme** [comment]
Duplicate #2425
