### ISSUE TITLE
Can't seamlessly switch to next chapter if there is a range of chapters

### ISSUE THREAD

**Issue by synthtech** [inorichi/tachiyomi#243]
It seems like only the first number in the range of chapters is getting parsed as the current chapter being read (in this example as Chapter 11). So when the app tries to find the next chapter it fails, possibly because it's looking for Ch.12 when the next chapter should actually be Ch.21-30.

The manga is _Tomo-chan wa Onna no ko!_ in the Batoto catalogue in case you want to reproduce it.

Chapter list | Next chapter not found
--- | --- | ---
![](https://i.imgur.com/lGDeaXE.png) | ![](https://i.imgur.com/oLiKpZR.png)

---
Version: r614
OS: Android 5.1.1

**Comment by inorichi** [comment]
I'm aware of this. Currently the only way to change chapters is with the recognized number, if there's  a range it won't work.

I want to change this, probably in 0.2.1, but I don't know how to do it, to be honest. If I use the source's order I'll probably have to update all the chapters every time there's an update, but I'm foreseeing some (uncommon) issues with this approach. Maybe someone has a better idea.

**Comment by inorichi** [comment]
Fixed already.
