### ISSUE TITLE
Cannot update extension

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#2430]
### Device information
* Tachiyomi version: r1572
* Android version: 9

## Steps to reproduce
1. Open app > Extensions tab > click on any source to update that extension > doesn't work

### Expected behavior
The tap should update the extension

### Actual behavior
The tap should update the extension but it doesn't

**Comment by arkon** [comment]
Need more info on the actual behaviour. Does _anything_ happen?

**Comment by Syborg49** [comment]
@arkon nothing happens. If it's helpful I can put up a video? Would that be helpful?

**Comment by arkon** [comment]
Sure, that might help.

**Comment by Syborg49** [comment]
@arkon Please see the following video

https://drive.google.com/file/d/1V1VCJj-Sux_UHd4hIhnwErSswdyCgVAw/view?usp=drivesdk

**Comment by Notarin** [comment]
I'm expecting this as well, as soon as I click install, it just goes back to the app. I've tried manually installing the app itself, this fails as well.

**Comment by arkon** [comment]
Duplicate of #2107
