### ISSUE TITLE
[Bug] MangaRock won't load chapters pages

### ISSUE THREAD

**Issue by ShakkoRyu** [inorichi/tachiyomi#2443]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 7.0

## Steps to reproduce
1. Enter any manga from mangarock source
2. Try to read any chapter and a message will pop-up saying "page list empty"

### Expected behavior
Enter reading mode and charge the chapter pages

### Actual behavior
A message pop-ups and tells "page list empty"

### Other details
![Screenshot_20200106-001006](https://user-images.githubusercontent.com/59552345/71798873-2fa6d600-3019-11ea-80ee-5f7c372ef9db.png)

**Comment by SnakeDoc83** [comment]
They're shutting down, don't expect that any of your manga on Manga Rock will continue to work.

**Comment by ZeDeedIsDone** [comment]
> They're shutting down, don't expect that any of your manga on Manga Rock will continue to work.

It still works on the mangarock app which I thought was weird since it doesn't seem like a server issue.

**Comment by CarlosEsco** [comment]
their app is accessing a different api.  which we dont have access to
