### ISSUE TITLE
[Feature Request] Preload source migration

### ISSUE THREAD

**Issue by mraleksander** [inorichi/tachiyomi#2444]
### Why/User Benefit/User Problem
The current source migration is slow as hell a lot of waiting for all the sources to be searched for the manga.
So we need a better way to migrate all mangas from a specific source, for instance MangaRock. Which currently shut down.

### What/Requirements
Preload all the searches for all the mangas in specific source, plus delete any results that don't find anything. So in the end you just get a list for you to select.
Additionall features would also be nice such as show number of chapters on the cover (in the search same way it's done while manga is in your libary) and last chapter added and time of added chapter as we dont get the option to check the manga(source) before migration/copying

**Comment by amboris** [comment]
Pls we really need this. Single migration with over 50 manga is super hell. And showing chapter number on cover is the best way which source is best to migrate.

**Comment by CarlosEsco** [comment]
as for chapter count.  im pretty sure you can either click in or long click into the source to verify the chapters

**Comment by mraleksander** [comment]
> as for chapter count. im pretty sure you can either click in or long click into the source to verify the chapters

Yup I found out that but it pretty much doubles the time needed to migrate a single manga so it's no where good, and dosent solve the problem

**Comment by amboris** [comment]
> as for chapter count. im pretty sure you can either click in or long click into the source to verify the chapters

I dont think you understand the problem.
Example: you search for a single mange on 15 sources. As per your methode you need to klick into the info page on every manga source to see which source is the best for the manga (many sources has different chapter count because of lag of update). The source loading takes super long itself to find the manga. Then you need to do the whole process again for all other 49 mangas... You see the ineffizienty here?

**Comment by mbucas** [comment]
To reduce preloading and noise in searches, it would be nice to select a preferred target on which to preload searches, and preferred options of migrations. Then a single validation would do the migration for all found equivalents. You could repeat this "mass migration" process with 2 or 3 targets and get done !
When doing the Manga Rock escape for only a dozen mangas today, I've found that most where on available on the same source.
If nothing is found on the preferred target, then a button to launch search on other sources could replace the current mecanism.

**Comment by CarlosEsco** [comment]
@amboris i do understand the problem  i was giving a work around for chapter count that not everyone knows.

**Comment by mraleksander** [comment]
I wouldn't mind just waiting to do all the searches for all the mangas and (show the chapter number) and then just click it would be pretty fast and even if the initial search takes a couple of minutes I can do other stuff as long as I don't have to babysit it

**Comment by arkon** [comment]
This isn't really relevant anymore considering MR is long dead and the desperate need for mass migrations is usually quite rare. That said, I still see glaring issues with the proposal:

> Preload all the searches for all the mangas in specific source

When? Tachiyomi is effectively just a browser, so I'm not sure if this makes any sense.
