### ISSUE TITLE
[Bug] Wrong date format in chapter list

### ISSUE THREAD

**Issue by mattiadr** [inorichi/tachiyomi#2449]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9
* Device: Samsung Galaxy S8

### Issue description
My phone language is set to `English (United Kingdom)` but the date in the chapter list is displayed as `mm-dd-yy` instead of `dd-mm-yy`.

**Comment by arkon** [comment]
Closing in favour of #1512.

Technically the app just follows whatever Android determines the locale's date format is. That said, everything other than ISO8601 is wrong IMO. :)
