### ISSUE TITLE
[Bug] Mangarock "Page list is empty" 

### ISSUE THREAD

**Issue by Applewubs** [inorichi/tachiyomi#2450]
### Device information
* Tachiyomi version: 0.8.4-1581
* Android version: 10

## Steps to reproduce
1. First step: Open any manga
2. Second step: Open any chapter

### Expected behavior
The manga should open and load without any problem.

### Actual behavior
Tachiyomi will automatically close the manga and load a pop up "page list is empty"
![Screenshot_20200106-093507](https://user-images.githubusercontent.com/59571080/71828494-0d887480-3068-11ea-928c-2afcf10d7792.png)

### Other details
I have the original Mangarock application since I was a beta tester, and when entering the same manga there it loads perfectly, and even loads and updates all the chapters. So the site has nothing wrong since it still has the database of all the data of the mangas there.
![Screenshot_20200106-093545](https://user-images.githubusercontent.com/59571080/71828522-19743680-3068-11ea-8c79-6d1d37a57c12.png)
![Screenshot_20200106-093558](https://user-images.githubusercontent.com/59571080/71828523-19743680-3068-11ea-9f91-764969158992.png)

**Comment by arkon** [comment]
We don't have access to their app API.

**Comment by Barracuda72** [comment]
Why the heck the bug was closed if it's not fixed? Same problem for me, Android 6.0.1. Any manga from MangaRock can't be downloaded / viewed (chapter list updates works thou). This is serious thing and should be dealt with ASAP. Consider reopening the bug.

**Comment by SnakeDoc83** [comment]
@Barracuda72 Manga Rock is dead, they shut down their website and are moving on; you should too.

**Comment by Barracuda72** [comment]
> @Barracuda72 Manga Rock is dead, they shut down their website and are moving on; you should too.

How is this true if:

1) Official app still perfectly works, accorting to @Applewubs 
2) Manga chapters lists still being updated, like, _right now_, some of them containing chapters not yet released anywhere (except original scanlation team website)?

Yeah, sure, they maybe closed down web interface, but that doesn't matter at all.

**Comment by arkon** [comment]
If you can find out their API, let us know.

**Comment by SnakeDoc83** [comment]
>Yeah, sure, they maybe closed down web interface, but that doesn't matter at all.

It entirely does.  Their website displayed manga by making requests to an API and the MR extension was built to make requests to that API as well.  They shut down their website so they have no reason to maintain that API.  Their official app uses a different API and you shouldn't expect that someone will crack how that one works.

**Comment by Barracuda72** [comment]
@SnakeDoc83 , thanks for your replies. Now at least some things make sense. Still, silently closing the bug without proper and thoughtful explanation was a very bad move on the @arkon 's side. I apologize if my comments were somethat rude.

**Comment by arkon** [comment]
I mean, I did reply with "We don't have access to their app API." ...

**Comment by Applewubs** [comment]
Do not become the victim, to be honest, closing the bug without even having a talk about it or without giving a credible explanation was very bad of you, When you develop an app, you make sure you do everything possible to fix a bug, and if it doesn't work then explain why, we are customers, and you are a mod that owes us an explanation.

**Comment by Applewubs** [comment]
And the app actually works even with the 2020  updated manga, I can give you many screenshots. (forgive my bad english)

![Screenshot_20200106-204511](https://user-images.githubusercontent.com/59571080/71864512-941f6f00-30c5-11ea-98ad-0b6d1ab14352.png)
![Screenshot_20200106-204502](https://user-images.githubusercontent.com/59571080/71864513-94b80580-30c5-11ea-8ef5-bae6c65b50b3.png)
![Screenshot_20200106-204435](https://user-images.githubusercontent.com/59571080/71864581-c92bc180-30c5-11ea-9894-64eca7ce318c.png)
![Screenshot_20200106-204425](https://user-images.githubusercontent.com/59571080/71864582-c92bc180-30c5-11ea-9c57-ee3a7abb0040.png)

**Comment by SnakeDoc83** [comment]
This is a free app my guy and you aren't owed anything.

**Comment by joseph619** [comment]
@Applewubs We don't have API for the app, so we can't fix MR.

**Comment by arkon** [comment]
As @SnakeDoc83 explained in more depth, we don't have access to their private API that they use within the app.

What I said was less descriptive, yes, and potentially worded in a way that some people don't understand so I do apologize for that.

Regardless, we won't be doing the work to reverse engineer their app.

Also do note that Manga Rock themselves announced their plans 3 months ago.

**Comment by Applewubs** [comment]
@SnakeDoc83 Although it is free that does not mean that if something does not work and part of the people like it you simply throw it away.

@joseph619 I know, and sorry if I'm very rude, but it really seemed very bad that he / she did that, I just ask for an explanation as someone using the app.

And last but not least, @arkon I know it has to be very difficult to mix codes to make it work again, and thanks for accepting that the phrase was poorly constructed, I also apologize for being angry that way and creating this stir. If you tried your best then thank you, if not, then don't expect us to shut up without nothing more.

**Comment by wopian** [comment]
#2455 [just linking the issues together for the latter discussion here]

**Comment by Soitora** [comment]
@Applewubs Not only is it a **completely free** application, it's also Open-Source, if you're not happy with us not being able to fix something then fix it yourself. We're not getting paid and neither are you, so why should the responsibility to do temporary workarounds lie on our side?

**Comment by CarlosEsco** [comment]
@Applewubs  you are not customers.  You are users.  Customers by definition are paying users.  This a free app maintained by people in their free time to allow people to read from manga websites.  We do not host any content, we only read from existing sites.  If a site decides to go down, change api, remove support for features.

  We are not  obligated or required to fix it or provide workarounds, if a maintainer wants to close an issue they are free to.  If you are not satisfied with that you are welcome to use any other manga app that actually charges you and then you can have a valid complaint.
