### ISSUE TITLE
[Feature Request] Check for bad mangas

### ISSUE THREAD

**Issue by mraleksander** [inorichi/tachiyomi#2453]
### Why/User Benefit/User Problem
Check their libary for mangas that don't have any chapters(licensed mangas only entry with out any chapters) or are no longer accessible (MangaRock)

### What/Requirements
(explain how this feature would behave)
It would list all such mangas maybe in the migration tab as a separate entity

**Comment by arkon** [comment]
Update error log is probably sufficient for fulfilling the issue that this is meant to address.
