### ISSUE TITLE
[Issue] Outdated MangaRock Extension

### ISSUE THREAD

**Issue by kschou95** [inorichi/tachiyomi#2454]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. Get any manga from MangaRock
2. open any chapter

### Actual behavior
Page List is Empty toast

### Other details
everything is up to date

**Comment by SnakeDoc83** [comment]
Wrong repo and Manga Rock is dead, migrate to a different source.
