### ISSUE TITLE
Transitioning to the next chapter shows me an x/x page

### ISSUE THREAD

**Issue by Pentillum** [inorichi/tachiyomi#2461]
**App version:**
r1567

**Android version:**
9

**Issue/Request:**
When transitioning to the next chapter, what appears is an x/x page of the previous chapter (but I learned even if it said x/x it was near always the 2nd page of succeeding chapter), instead of a 1/x page. 

**Steps to reproduce (if applicable)**

 1. Read a chapter
 2. Swipe to proceed to the next chapter
 3. The 2nd page of that chapter is displayed

**Other details:**
What fixes the bug for me is either going back a page, and then going forward; or going back to the chapter select, then tapping the continue reading button.

I tried this across 3 different mangas to check. Images are attached.

Edits: Removed a detail that wasn't necessary, Added image of a page with correct page number.

![tachiyomibugreport](https://user-images.githubusercontent.com/59666465/72012225-3011bd80-3221-11ea-8903-0951cbbe820d.jpg)
![tachiyomibugreport1](https://user-images.githubusercontent.com/59666465/72012226-3011bd80-3221-11ea-9d7c-da92df9414cd.jpg)
![tachiyomibugreport2](https://user-images.githubusercontent.com/59666465/72012227-3011bd80-3221-11ea-8087-9217aa4d1f95.jpg)

-----------------------------------------------------------
Image with correct page number
![correct number](https://user-images.githubusercontent.com/59666465/72016416-605d5a00-3229-11ea-9f7a-c7bd37cd32aa.jpg)

**Comment by arkon** [comment]
Did this happen on earlier versions too?

**Comment by MCAxiaz** [comment]
It broke from this change
https://github.com/inorichi/tachiyomi/commit/5cddb269d6746969481ebf90ef2873d23790275a#diff-5fe950155145bf961f01ef274f8d1a7aL15

It needs the equals override.
