### ISSUE TITLE
[Feature Request] Filter by source on library 

### ISSUE THREAD

**Issue by Bexa2** [inorichi/tachiyomi#2464]
### Why/User Benefit/User Problem
Ease of manga transfer between sources

### What/Requirements
Filter mangas by source on our library, that way I could show all mangarock mangas and migrate them to a different source

**Comment by Bexa2** [comment]
To clarify, right now we can sort by source, we can't show only X source.
https://github.com/inorichi/tachiyomi/issues/984

**Comment by joseph619** [comment]
You can use this fork and use Source Migration directly, this feature is not available on Stable yet

https://tachiyomi.org/help/guides/getting-started/#installing-an-extension

**Comment by arkon** [comment]
Source migration in stable shows you the lists of manga per source too.

**Comment by Bexa2** [comment]
> Source migration in stable shows you the lists of manga per source too.

You're right, how does that work? Does it search on all sources simultaneously or does it search the next on the list when it's done searching one?

I have a lot of sources and although I would like to migrate everything I can to mangadex I have to scroll down many sources, find mangadex and then it stays loading for a while. 

Maybe after we select the source to migrate from we can select the sources to search to migrate to. (just like it's done now but with a middle step to filter sources to migrate to)

**Comment by joseph619** [comment]
This is already available in J2k, maybe we can take this from there

https://github.com/Jays2Kings/tachiyomiJ2K/issues/41
