### ISSUE TITLE
[Bug] Automatic first page skip on transition page

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2465]
### Device information
* Tachiyomi version: 0.8.4-r1587
* Android version: 9

## Steps to reproduce
1. Go to the last page of any manga chapter
2. Go to the next page
3. Transition page appears

### Expected behavior
The screen should stay at the transition page

### Actual behavior
Transition page automatically skips to the second page of the next chapter, skipping the first page.

### Other details
The second page also shows wrong page number at first.

[Video Capture](https://streamable.com/0ms9q)

Potential PR related to issue - #2426

**Comment by arkon** [comment]
Can you try with r1590+?

**Comment by bbtora** [comment]
Yes, it is fixed with latest build.

Sorry I missed a similar issue #2461 was reported. Thanks.
