### ISSUE TITLE
[Minor Bug] Wrong Update Date

### ISSUE THREAD

**Issue by YautjaTNT** [inorichi/tachiyomi#247]
On random manga I have bookmarked, when they get updated the update date is said to be in like 1969, and when that happens I don't get those manga listed in the recent updates feed, or in the notification that tells me my list has updated itself.

![screenshot_2016-04-10-08-30-03](https://cloud.githubusercontent.com/assets/17912883/14411231/d3b04d1a-fef6-11e5-9462-6c8372c67400.png)

Version: r000 or v0.1.4
(other relevant info like OS)

**Comment by inorichi** [comment]
The recents tab needs the upload date. The date is parsed correctly for me with the latest dev version. I haven't tried with stable.

**Comment by YautjaTNT** [comment]
So in other words, to have the recents tab function the upload date needs to be correct, and you have not encountered such an issue on the next version to be?

**Comment by inorichi** [comment]
The problem is I didn't modify the dates parser of Batoto from 0.1.4, it's the same. Do you see in your browser the recently uploaded chapters as "X hours/minutes ago"?

**Comment by YautjaTNT** [comment]
In the recents tab, no just if it was updated today, yesterday etc. On the actual manga page it's just the date

**Comment by inorichi** [comment]
I mean in Batoto's page. So, you don't have relative dates there?

**Comment by YautjaTNT** [comment]
Tad confused, but I don't see any relative dates anywhere on the app.

**Comment by inorichi** [comment]
Not in the app, in http://bato.to/comic/_/comics/tomo-chan-wa-onna-no-ko-r15722

**Comment by YautjaTNT** [comment]
In that case, yes.
