### ISSUE TITLE
[Bug] AMOLED theme not fully black in some places (e.g. catalog view)

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi#2473]
When you open catalog view the lists the catalogs are in should be black.  Similar to the chapter view.  Instead they are the dark list color

**Comment by arkon** [comment]
The same goes for extensions and tracking cards, I believe. I guess the goal is to literally have everything as black?

**Comment by CarlosEsco** [comment]
For AMOLED I woud say yes
