### ISSUE TITLE
"Authentication Error" MAL tracker

### ISSUE THREAD

**Issue by BlackerBlackDynamite** [inorichi/tachiyomi#2474]
**App version:**
r1607

**Android version:**
10

**Issue/Request:**
When trying to log into MAL in the tracker settings it returns an "Authentication Error". Tried clearing cookies to see if that clears it up, same issue.

**Steps to reproduce (if applicable)**

 1. Setting > Tracking
 2. Select MyAnimeList
 3. Attempt to log  

**Other details:**
![Screenshot_20200110-033113](https://user-images.githubusercontent.com/10680870/72138655-3c9a3100-335b-11ea-9efc-174073b85385.jpg)

**Comment by pervertkirito** [comment]
Change your password on mal, and try again.

**Comment by BlackerBlackDynamite** [comment]
> Change your password on mal, and try again.

Tried doing that as well, still the same authentication error. Not having any issues logging into MAL anywhere else, just in Settings > Tracking.

**Comment by MCAxiaz** [comment]
@BlackerBlackDynamite if you're willing to help debug, I could send you an apk that prints out more detailed error messages. If you try logging in again using it, it might provide some useful info to help resolve this issue.

**Comment by BlackerBlackDynamite** [comment]
> @BlackerBlackDynamite if you're willing to help debug, I could send you an apk that prints out more detailed error messages. If you try logging in again using it, it might provide some useful info to help resolve this issue.

Would love to, but I just woke up and decided to try logging in again and it just worked. No authentication error, no issues. All I did was clear the cookies again and try it and it worked.

**Comment by AKSSPARKPrince** [comment]
I'm facing same problem. I tried cleaning cookie but it didn't worked. Clean whole data but still didn't worked.

**Comment by lucfig** [comment]
> I'm facing same problem. I tried cleaning cookie but it didn't worked. Clean whole data but still didn't worked.

Yeah, me too. Started this week for no apparent reason.

**Comment by arkon** [comment]
How'd you guys end up at this nearly year old issue instead of the newer one?

This is fixed in 0.10.6.

**Comment by AKSSPARKPrince** [comment]
I don't know. It was so frustrating. I had to shift to anilist tracking
website.
 I literally tried everything but nothing came through.

I am using
Device: Redmi Note 5 Pro
Android 10 Lineage OS system

I tried cleaning everything I could (cookies, data) but it didn't work.
It was working fine awhile ago when I installed it but then at a point I
saw my tracks are not updating. When I looked upon it, it was that error
showing up while logged in.

**Comment by clsyee** [comment]
I'm having the same issue as well, I can login anywhere else and tried to clear everything with no luck.

**Comment by ghostbear** [comment]
**_Update_** the app, this is fixed in stable 0.10.6 or preview r2866

To update the app go to More -> About -> Check for updates, then press install from the update notification

Or go to https://tachiyomi.org/download/ to manually download the update

**Comment by AKSSPARKPrince** [comment]
Yaaay, thanks for the update. It worked :)
