### ISSUE TITLE
[Feature Request] Ability to deselect trackers in settings

### ISSUE THREAD

**Issue by nataliejean2412** [inorichi/tachiyomi#2475]
Says it on the tin. Once you've authenticated a tracker, there's no (obvious) way to de-authenticate it.

Currently, clicking on a tracker that's already authenticated just causes it to load the respective login page for that service, which just immediately closes. Maybe there could be a long press menu or even a trash can toggle icon up top to allow for item management.

**Comment by pervertkirito** [comment]
click on any tracker service you use, remove your username/password and click login. It will remove your login

**Comment by arkon** [comment]
I agree that this workflow can be improved.

**Comment by MCAxiaz** [comment]
Could change the green logged in checkmark to a sign out button instead.

**Comment by joseph619** [comment]
@pervertkirito That's not intuitive to the average user and very poorly implemented.
