### ISSUE TITLE
[Feature Request] Ignore Errors on Backup Restore

### ISSUE THREAD

**Issue by clarjon1** [inorichi/tachiyomi#2479]
### Why/User Benefit/User Problem
I tried to import my data from the regular version of tachiyomi to the dev version i installed using the backup restore functionality, so I can assist with testing with future cloudflare challenge changes. However, due to the current CF issues, most of my attempted imported data failed

### What/Requirements
An option to "Ignore Errors", a "Yes i know stuff will say it's broken, just import it anyway dammit i'll deal with the fallout myself" mode, if you will.

**Comment by CarlosEsco** [comment]
It already ignores errors though?  it just writes a error log which you can ignore

**Comment by arkon** [comment]
I think he means he wants to be imported anyway.

**Comment by CarlosEsco** [comment]
It's can't though.

**Comment by clarjon1** [comment]
> 
> 
> It's can't though.

That's why I'm asking for a feature to let it do that.

**Comment by CarlosEsco** [comment]
pretty sure you can just not install any extensions then restore.  and you will get what you want

**Comment by clarjon1** [comment]
> 
> 
> pretty sure you can just not install any extensions then restore. and you will get what you want

Kind of.

What actually happens is that during the backup restore process, it processes each manga, by testing to make sure that it can pull the latest data from the source.

If the source is unable to be reached, for example due to issue #2344,  it notes the error, and does NOT import the manga.

All the exact same sources are added, as it's sharing the addons between my release and non-dev versions of the app i have installed.

So I'm currently unable to easily add the exact same mangas to my dev test version due to issue #2344.

Which is why I'm making a feature request for a feature to bypass this check, and allow me to fully restore the backup, knowing that there are unreachable / unverifiable/ erroring mangas.

**Comment by CarlosEsco** [comment]
You attempted to restore after uninstalling your existing extensions?  If there are no extensions it can't attempt to reach out.    You can easily verify this and if its still broken just reinstall the extensions and nothing in your stable is affected

**Comment by clarjon1** [comment]
What? Where did I say I uninstalled anything?

The stable version and dev versions can be installed side by side on the same android device, thus ensuring all the source extensions are installed from the get-go.

When you restore a backup, **tachiyomi checks on the source server to see if each manga it still exists** if something like **cloudflare prevents tachiyomi from talking to the source server** it assumes the manga does not exist and refuses to import it.

**Comment by CarlosEsco** [comment]
So again i am trying to tell you a workaround that i believe will work.  If you don't want to do it sure but i am also saying this feature is not in timeline to be implemented at any time.
So if you want a work around.
1.  Go into the app (stable or dev it doesnt matter) uninstall your extensions
2.  go to dev and try restore the backup
3.  after the restore is done.  reinstall your extensions

**Comment by clarjon1** [comment]
Oh! My apologies! I've not had my coffee yet, so my brain isn't running on full cylinders.

I'll give that a shot, thanks for the workaround!

It still would be useful for the option I feel, as that's a lot of uninstalling and reinstalling. I'd better take a screencap so I don't forget any sources.

**Comment by happywillow0** [comment]
I didn't think the restore function has changed and just tested it on r1636. 

If a source is not installed, it errors out as 'Source not installed: (ID number)'

**Comment by CarlosEsco** [comment]
@happywillow0  ah i see.  By memory i was expecting it to dummy restore it.

**Comment by JxM-92** [comment]
> > pretty sure you can just not install any extensions then restore. and you will get what you want
> 
> Kind of.
> 
> What actually happens is that during the backup restore process, it processes each manga, by testing to make sure that it can pull the latest data from the source.
> 
> If the source is unable to be reached, for example due to issue #2344, it notes the error, and does NOT import the manga.
> 
> All the exact same sources are added, as it's sharing the addons between my release and non-dev versions of the app i have installed.
> 
> So I'm currently unable to easily add the exact same mangas to my dev test version due to issue #2344.
> 
> Which is why I'm making a feature request for a feature to bypass this check, and allow me to fully restore the backup, knowing that there are unreachable / unverifiable/ erroring mangas.

I believe a better way to explain it would be to add a feature that, after processing a backup file, ask the user to try to restore the "not found sources" with another source, it will take time but it could work... that way the restore process will almost always be success...

**Comment by klonamy** [comment]
I encountered another error related to backups.
I tried the mentioned workaround for reimporting and got 1 imported Manga.
It alterneted between an meta error and one i don't rember.

You could repoduce this if your create a backup with Tachiyomi 0.10.5 Stable.
But try to reimport with Tachiyomi 0.10.4 Stable!

Now i am waiting for my back to finish...

**Comment by arkon** [comment]
This is largely irrelevant with the v3 offline backup system currently in the Preview builds.
