### ISSUE TITLE
[Bug] Unable to search in MangaDex

### ISSUE THREAD

**Issue by deception83** [inorichi/tachiyomi#2480]
### Device information
* Tachiyomi version: 0.8.4
* Android version: Android 10

Hi, I noticed that there was a new update for MangaDex changing the domain to .cc. With the new update I am able to browse the catalogue however I am unable to search within them even though I just randomly pick a name from the "browse" catalogue and search for it.

Please help as I am trying to migrate my source from MangaRock to MangaDex and with this issue I am unable to switch.

Thanks.

**Comment by happywillow0** [comment]
Make sure to log in to Mangadex in to enable search. You can log in by opening a manga via webview. Search is not enabled for "guests". See the Tachiyomi.org website for more details.
