### ISSUE TITLE
[Bug] Unable to restore backup on Amazon Fire HD 10 (2019)

### ISSUE THREAD

**Issue by baileymh** [inorichi/tachiyomi#2483]
### Device information
* Tachiyomi version: r1616
* Android version: Fire OS 7.3.1.0 | Android 9.0

## Steps to reproduce
1. Select Restore Backup
2. Choose Application prompt comes up.
3. Select Drive/Files/Dropbox (tried all of them)
4. Select/download .json file (tried multiple backup dates)

### Expected behavior
Open backup and start loading

### Actual behavior
Nothing happens within Tachiyomi. The screen stays on the "Choose Application" prompt. 

### Other details
Tachiyomi has permission to access files

**Comment by baileymh** [comment]
Fixed in latest update! Thank you!

**Comment by arkon** [comment]
I don't think any of the changes made would affect this, but glad to hear it's working again?
