### ISSUE TITLE
[Bug] Page Scrolling bar is off

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#2487]
### Device information
* Tachiyomi version: r1624 is the latest one i've seen it on but i'm pretty sure its been there since the new reader was made.
* Android version: 5 I think? I'm using a kindle fire 10 hd 2017) so its the custom amazon version.

## Steps to reproduce
1. Open manga
2. tap on screen to bring the page scroller up

### Expected behavior
This is what it looked like in older versions before the new reader.
https://i.imgur.com/ew8w6zZ.jpg

### Actual behavior
this is what it looks like now
https://i.imgur.com/MDqoNOj.jpg

**Comment by arkon** [comment]
I'm pretty sure there's an open issue about this but I can't find it right now.

Have you changed your scaling settings at all?

**Comment by shogunreaper** [comment]
no i havent i didnt even know there was scaling settings

**Comment by arkon** [comment]
I mean on the device (not the app), but I assume you haven't

**Comment by shogunreaper** [comment]
Oh no i haven't but like i said its only on the newer versions so i'd have to assume it's something wrong with the app itself.
