### ISSUE TITLE
[Bug] Adding to Library From Catalogue

### ISSUE THREAD

**Issue by MCAxiaz** [inorichi/tachiyomi#2489]
## Device information
- Tachiyomi version: Dev

## Steps to reproduce
1. Have Library setting Default category set to 'Always Ask' and have at least one category.
2. Long tap a manga to add it to library.
3. Press ok without selecting a category.
![library](https://user-images.githubusercontent.com/24946428/72213660-6496ab00-34a7-11ea-9973-cb043cb9e860.gif)

### Expected behavior
Manga added to library under default category.

### Actual behavior
Manga is not added to library.

**Comment by arkon** [comment]
Initially wanted to say this is related to #2192, but I'm not really sure.

Can you verify what version you're doing this in? (i.e. Does it happen in both stable and dev?)

**Comment by MCAxiaz** [comment]
Dev. 

Stable requires you have two categories. If only one it just adds it without showing the dialog.

**Comment by MCAxiaz** [comment]
So I think #2192 might be outdated since the app provides better support for using "default" as a regular category now. So Keeping this kind of behavior makes sense to me.

**Comment by bbtora** [comment]
If one is setting it to 'Always Ask', then it really shouldn't add a manga without selecting any category.

**Comment by MCAxiaz** [comment]
Hm maybe default should be added as an option to the dialog then.
