### ISSUE TITLE
Can't retrieve/refresh chapters from Batoto

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#249]
When trying to add a manga and/or trying to refresh the chapter list from an existing one I receive this error:

![Image](http://i.imgur.com/XCmZeqH.png)

and when I try to re-login into Batoto again I get this : ![unknown error](http://i.imgur.com/B0fNg3H.png)

Version: 0.1.4
OS: 6.0.1 (Galaxy S6) - just today I upgraded from 5.1.1

**Comment by inorichi** [comment]
See #232. It's an error in an external library. Will be fixed in the next release, soon.
