### ISSUE TITLE
[Bug] I'm not able to download or read new chapters

### ISSUE THREAD

**Issue by KuragariGin** [inorichi/tachiyomi#2490]
### Device information
* Tachiyomi version: 0.8.4
* Android version: ?

## Steps to reproduce
1. First step Download a chapter or try to read a new manage 
2. Second step

### Expected behavior
Download starts and you can see the progress or the page would load 

### Actual behavior
Download stuck on page 0 
When trying to read new manga it's stuck on reload

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
For what sources?

**Comment by KuragariGin** [comment]
All sources

**Comment by SnakeDoc83** [comment]
Do you use Manga Rock?

**Comment by xzns** [comment]
Same issue is happening with kissmanga. Getting a challenger not found error.

**Comment by KuragariGin** [comment]
It was for all sources I had Manga:( Dex, Park, Panda, Reader, sail and gasee) Lucky enough for me everything seems to be working again but it was very weird I have to say. Unless I had it downloaded prior it wouldn't load.
