### ISSUE TITLE
Import Bookmarks from Kissmanga or Batoto

### ISSUE THREAD

**Issue by folta01** [inorichi/tachiyomi#250]
Importing bookmarks from websites such as kissmanga or batoto 
Would require a login and password, and could select which bookmarks to add, or add all. 

I have ~600 bookmarked mangas on kissmanga. It would be much easier for me to mass add Manga than individualy

**Comment by charnotx** [comment]
agree with folta01. Account sync and bookmark sync with Kissmanga would be grand! 

Thanks for all your hardwork on this app!

**Comment by dest1234** [comment]
Can you also do readcomiconline.to login because I also have like 600 comics on there.

**Comment by SamB** [comment]
Manga Rock would also be pretty handy to have somehow, for the purpose of migrating off of it nothing else.

(It might be prudent to grab their list of titles at some point?)

**Comment by arkon** [comment]
Closing in favour of #2205
