### ISSUE TITLE
[Bug] Automatic library backup not working consistently

### ISSUE THREAD

**Issue by raniesantos** [inorichi/tachiyomi#2504]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Set frequency of automatic backup.
2. Wait, then check the backup folder.

### Expected behavior
There should be a new json file in the backup folder.

### Actual behavior
No new file is created.

### Other details

**Battery optimization is disabled** for Tachiyomi.

**Already tried reinstalling**. A backup was successfully created once, but over several days no new backups were created. Max backup files is set to **3**.

I talked to another person in the Tachiyomi Discord server who is having the same problem.

- Me: ransan32#0038
- The other person: Soundtrack2Chaos#8296

They said they were using **Tachiyomi EH**, so this bug is something that originated from this repository and got carried over to that fork.

They also found that for some reason, setting the frequency to **6 hours** got the automatic backup to work properly. I am currently testing this, I do not yet have results but I will update this issue as days pass to see if it works.

They told me (and I agree) that the fact that they managed to get it to work is nice, and the 6 hour interval doesn't have any major effect on usage. However it is still unnecessary for the apps to create backups that often, so it would be nice if the other backup intervals would get fixed.

**Comment by raniesantos** [comment]
No backup files were generated while it was set to **6 hours**.

I changed it to **12 hours**, a backup was generated on Jan 17 after that it stopped working again.

**Comment by arkon** [comment]
This _should_ be more reliable in the latest preview versions since migrating to WorkManager.
