### ISSUE TITLE
Download chapters automatically after reading them completely

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi#2506]
### Why/User Benefit/User Problem
should be added because if I am watching the chapter and then I want to save it I have to download a chapter that I already saw. It is a way to save mobile data by not downloading something twice.

### What/Requirements
I would like you to add an option to save the chapters of the series automatically when they are read (Example: I opened the first chapter of a series and read it completely. Upon reaching the end of the chapter it is saved automatically. Only saved when it is read completely. If it is not read completely do not save it.).

**Comment by RuthlessRuler** [comment]
The way to do is just untick the option to remove chapters when marked read. Cause what you want is basically for some mangas, IDK why you want to do it for all mangas tho. (tachi caches the Manga currently being read, so if you press back button and click that chapter the chapter resumes as the images are cached in temp folder of that chap and deletes the folder after the chapter is read. This is quite helpful as it doesn't fill up your storage) So just download a chap before reading and have the Option "Remove after read" to Disabled & "Remove when marked as Read" switched off. 
FYI- the Option are in the setting which can be accessed by clicking the Hamburger Menu -> Settings ->Downloads.

**Comment by arkon** [comment]
Downloading now checks the cache first so that addresses the data portion, so just "download" manually afterwards if you want to "keep" the chapter.
