### ISSUE TITLE
[Question] Explanation for cryptic string

### ISSUE THREAD

**Issue by comradekingu** [inorichi/tachiyomi#2508]
What does
"Update last chapter read in enabled services to %1$d?"
mean?
https://hosted.weblate.org/translate/tachiyomi/strings/nb_NO/?checksum=32a22a3b819e0df4

**Comment by arkon** [comment]
I actually don't think that string is used anymore. It was for confirming tracker updates before.

**Comment by comradekingu** [comment]
It would be great to remove it, as things like that make translation a pain.

**Comment by comradekingu** [comment]
How about putting that file up as "COPYING"?

**Comment by arkon** [comment]
Not sure what you mean?

**Comment by comradekingu** [comment]
Having a file called COPYING at the root, like "LICENSES", is a convention for stating licenses.
The scenario would be this.

User wants to find out what license covers what.
User sees COPYING file
Done

**Comment by arkon** [comment]
That doesn't seem relevant to this issue. Please open another issue.

That said, I'm not sure what the purpose of that is. The project isn't covered by multiple different licenses, unless you're talking about the dependencies?

**Comment by comradekingu** [comment]
I posted that in the wrong issue X)
