### ISSUE TITLE
[Bug] Can't install Tachiyomi r1549 and newer versions

### ISSUE THREAD

**Issue by haljordan0629** [inorichi/tachiyomi#2510]
### Device information
* Tachiyomi version: r1549, r1554...... until the latest r1648
* Android version: 5.0.2

（I want to say: sorry, My English is poor, and I did try my best to tell what happened.）

At first, I was used r1531,  but when I tried to update, I found it didn't work. 
After tried several times, I can install r1531~r1540, but the versions newer than r1540 can't install. 

It always said: App Not Installed.

I really don't know how to fix the problem.

**Comment by RuthlessRuler** [comment]
Backup your Tachi Library(If not), Clear cache and then data of Tachiyomi and then Uninstall the app (Do not have any other copy of the app Which may have similar package name as the app)

Then try to install the latest version to see if it works. You may also try to restart device, remove the app files from your Multiple User Account if you have and try. Try to uninstall the app from Lucky Patcher in case you are rooted. If these do not fix then please add more details, like your device name and exact Android version and mention of any other details you have that can help us in finding the problem.

**Comment by arkon** [comment]
Unfortunately, I'm not sure what's wrong. It seems like no one else is having this particular issue.

The latest versions should still work with Android 5.x.
