### ISSUE TITLE
[Feature Request] Extension sorting and filtering/search

### ISSUE THREAD

**Issue by GreatestFool** [inorichi/tachiyomi#2512]
There's a lot of extensions, some odd one hundred and fifty if I remember correctly. However there's currently no way to search between them, much less alphabetical sorting! Everything is sort of just all over the place, and it's pretty annoying trying to find that _one_ extension when you're forced to read through the entire list to find it.

Please add at least alphabetical sorting, it'd make sorting through them much easier than it is now.

Searching is optional, but would be appreciated and would also be a great help considering how many there are.

**Comment by happywillow0** [comment]
The dev version has added filters by language and a search function to the extensions page. 

Each should also already be alphabetized by language.
