### ISSUE TITLE
[Feature Request] one community

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi#2514]
### Why/User Benefit/User Problem
(explain why this feature should be added)
I dont really know what is happening here, the community seems like to start splitting because many feature request or pull request are ignored or something. People gets fed up because they provide solution and it wont be accepted and then build their own tachiyomi variation... Like TachiyomiJ2k, TachiyomiEH

### What/Requirements
(explain how this feature would behave)
Cant you guys just work together and stop beeing stiff like a old unflexible structure.  Maybe add those people and give them rights to do their things to help this app getting better. We really need to get away from the old ways where everythings to go through some chain of approvement when they are allready build up some trust. It just slows thing extremly down.
Is there no way to reach out to all the variation creator and join together in coop?

Ps: really missing mass scource migration....

**Comment by CarlosEsco** [comment]
People want different things. That's open source. There are plenty of apps with forks
