### ISSUE TITLE
Can't download or update extention

### ISSUE THREAD

**Issue by raginglazor** [inorichi/tachiyomi#2517]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** latest

**Android version:** 9

**Issue/Request:**Can't download or update extention

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

I have a xiaomi a2, since december OTA i can't seem to download or update extention from tachiyomi, december OTA somehow broke chrome donwloading system or something. i know i can download the extention from github

**Comment by arkon** [comment]
There's other open issues similar to this.

I think this generally only happens with Chinese phones.
