### ISSUE TITLE
[Feature Request] Notification for extension update 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2520]
This feature would inform user that an update for installed extension is available. 

Already available on Tachiyomi J2k

https://github.com/Jays2Kings/tachiyomiJ2K/issues/17

**Comment by Philip1327** [comment]
Agree that this is a good feature to implement. I've basically gotten into the habit of every day that I open the app to manually check the extention page before I start reading. This is inconvenient and having this feature would be really nice.

Only thing better would be auto update of extentions which may not be possible.

**Comment by Flat** [comment]
Automatic updating isn't possible without tachiyomi being installed as a system app with root, as apk installation otherwise requires user interaction.

**Comment by Philip1327** [comment]
Figured as much and just unrooted too lol. 

Ignoring auto updating, and focusing on just a notification of updates, I believe should be theoretically possible. 

I would assume that creating a "service" (not sure what they are officially called on Android) that closely resembles the config of "library update frequency" (the existing notification and update checking features for chapters in general settings menu), except set up to monitor the extention library for possible updates, would be the best/easiest approach.

**Comment by joseph619** [comment]
@Flat You can make a commit by borrowing the Notification for Extension update feature from TachiyomiJ2k

**Comment by arkon** [comment]
Jay is already planning on submitting a PR.

**Comment by arkon** [comment]
#2680
