### ISSUE TITLE
[Feature Request] My Library sorting option

### ISSUE THREAD

**Issue by vongdong** [inorichi/tachiyomi#2521]
I've set the sorting of my categories in the My Library to 'Last Updated' and it isn't doing as I expected. It seems to sort by what the app has checked for an update rather than showing what has the most recent updates from first to last. It would be a huge improvement over the 'library update' page as for some reason that page doesn't show some updates unless I manually go to the manga and update it.

Also, making the 'library update' page look like the 'last read' page would be helpful as I find it a bit small.

**Comment by arkon** [comment]
#2217
