### ISSUE TITLE
[Feature Request] Manage chapters in download queue

### ISSUE THREAD

**Issue by elrepeposo** [inorichi/tachiyomi#2526]
### Why/User Benefit/User Problem
Whenever a new chapter of a series that I want to download comes out, if I'm downloading something else, I have to cancel any chapters that I may have been downloading previously, which is a bit frustrating to be honest.

### What/Requirements
One of the fixes I thought of would be to add a feature that lets you move the chapters around in the queue, or maybe change the chapter's priority so it can be put at the top of the queue without needing to cancel the rest of the chapters.

**Comment by arkon** [comment]
Added in fb897e37d1a0f68355bccbbfd22a91813906b5b5
