### ISSUE TITLE
[Feature Request] Option to hide empty categories

### ISSUE THREAD

**Issue by MxFlix** [inorichi/tachiyomi#2528]
### Why/User Benefit/User Problem
It would make navigating categories a lot easier, especially when searching/filtering when there are a lot of categories.

### What/Requirements
Similar to the behavior of the default category, a category would simply not appear on the top bar of My Library, if there are no items to display in that category at the moment. That would include the case where all items that are in the category are currently hidden due to a filter.

**Comment by joseph619** [comment]
If the category is empty, why not delete it?

**Comment by MxFlix** [comment]
Because
a) it might only _appear_ empty because of the current filter or
b) it's made in preparation for it to be not empty soon.

**Comment by arkon** [comment]
Don't think this is going to happen, mostly because:

- The actual tabs don't know anything about the contents, and I'd rather not set up really janky ways of hooking those two together
- It seems a bit confusing that some tabs might disappear depending on search/filters
