### ISSUE TITLE
[Feature Request] Crop image before saving 

### ISSUE THREAD

**Issue by ach-raf** [inorichi/tachiyomi#2530]
### Why/User Benefit/User Problem
I think it would be convenient to crop just a part from the image before saving it to the gallery 

### What/Requirements
When the user clicks save image the whole page shows with croping tools and then you can select the area you want and click save or cancel

**Comment by joseph619** [comment]
I am not sure adding a cropping tool to Tachi would be feasible, as saving image is a rarely used feature. You can simply take sceenshot and crop directly.

**Comment by arkon** [comment]
Agreed, the workflow should be more dependant on existing gallery tools rather than being built into Tachiyomi.
