### ISSUE TITLE
[Bug] Unable to download several manga from various sources

### ISSUE THREAD

**Issue by richylyq** [inorichi/tachiyomi#2531]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9.0

## Steps to reproduce
1. Go to Mangahere (EN) 
2. download Medical Return

### Expected behavior
Successful download of Manga

### Actual behavior
Manga download error.
from download queue, it is stuck at 16/17 for example

### Other details
this happens for several manga from various sources

**Comment by joseph619** [comment]
This is a source issue, also wrong repo

**Comment by richylyq** [comment]
Thanks for the clarification! Looks like we have to just read it online
