### ISSUE TITLE
[Feature Request] Display the number of manga in your library (or categories)

### ISSUE THREAD

**Issue by PsychoChief** [inorichi/tachiyomi#2533]
### Why/User Benefit/User Problem
This is not a super important feature, but it would definitely help those with a large number of manga in their library, and give the ability to learn how many manga there is in their library (and also respective categories) without needing to count them all by hand.

### What/Requirements
Display a number beside the library section in the side that tells the amount of the manga in the library. It would be the same for categories, except the number displayed will only tell the amount of manga in that category.

**Comment by arkon** [comment]
Workaround for this is to select all in your categories to see the sum.

(There's now a select all option in the library so this is easier)
