### ISSUE TITLE
[Feature Request] Downloading from multiple sources at once

### ISSUE THREAD

**Issue by Jacket-Chan** [inorichi/tachiyomi#2534]
### Why/User Benefit/User Problem
This would make downloading much faster, especially when restoring a backup on a new device and having to download many chapters at once. This would only benefit users who have chapters queued for download from multiple sources but would be a useful feature nonetheless. The current issue is that downloading is already slow to prevent IP bans, so any opportunity to speed up this process would be appreciated.

### What/Requirements
The feature would be for different sources to have different download queues to allow them to download simultaneously, speeding up downloads significantly. This could be implemented as an optional setting. I'm aware that in the past multi-threaded downloading was removed due to IP bans, but since these concurrent downloads would be happening on different sources, there should be no issue.

**Comment by arkon** [comment]
This is actually something I've been thinking about. 👍

**Comment by CarlosEsco** [comment]
@arkon good luck that download code is spaghetti

**Comment by txomon** [comment]
Not sure if this can be bundled within the same feature request, but same thing goes for search functionality, it's really cumbersome to wait for 200 sites to finish searching a term.

**Comment by CarlosEsco** [comment]
For search. Disable sources you know aren't gonna have results. That are not aggregators
