### ISSUE TITLE
[Feature Request] add this websites plz

### ISSUE THREAD

**Issue by Manga-Killer** [inorichi/tachiyomi#2535]
hi, please add these websites

https://www.mangaka3rb.com/

https://mangatales.com/

https://bestmanga-soul.blogspot.com/?zx=a2e70445d7475efc

https://www.nakanaide.me/

https://madscientists33.blogspot.com/

and thanks

**Comment by wopian** [comment]
Extension requests should be made in https://github.com/inorichi/tachiyomi-extensions, not here

**Comment by Manga-Killer** [comment]
> 
> 
> Extension requests should be made in https://github.com/inorichi/tachiyomi-extensions, not here

ok, but how?

**Comment by wopian** [comment]
With https://github.com/inorichi/tachiyomi-extensions/issues/new?labels=Source+Request&template=source_request.md&title=%5BSource+Request%5D+Source+Name

**Comment by Manga-Killer** [comment]
ok, thx
