### ISSUE TITLE
[Feature Request] Revert change to "last updated" library sorting and add "latest chapter date" sort option

### ISSUE THREAD

**Issue by FlaminSarge** [inorichi/tachiyomi#2539]
"Last updated" more closely reflects fetch date as ee8a5318 had it, and "latest chapter date" describes exactly what the current behavior is as of a22c79c5. This issue is for making those both available as distinct sort options.

**Comment by CarlosEsco** [comment]
What scenarios would you need last updated where it wouldn't be solved by adding a date added option?

**Comment by FlaminSarge** [comment]
If I manually update a manga whose latest chapter update was a while ago, it ends up somewhere arbitrary in my library; with a single manga this is manageable, but for multiple it'll end up rather annoying. Having both options solves for both the issues described in the commits referenced above.
