### ISSUE TITLE
Local Manga

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#254]
Can you make it possible to import manga from sd card\internal storage?

Ones not downloaded from within this app, i have a ton of manga that i've collected over the years from various sources. Like Mangawatcher, DomDomSoft Manga Downloader and Free Manga Downloader.

I'd like to be able to use those existing files instead of redownloading everything. I used to just use mangawatcher for it but it stopped being able to pull info off servers for things like descriptions and covers. (plus i like to use one app if possible)

**Comment by Kotters** [comment]
I would also like to request this. Tachiyomi is an excellent reader, and I would love to use it with my existing collection.

**Comment by inorichi** [comment]
Added in #648 as a new source browsable in the catalogues.

You have to place your manga in `/sdcard/Tachiyomi/local`. It also works with removable SD cards by following the same folder structure, allowing you to have chapters mixed in both the external and removable storage.

For example, with
`/storage/emulated/0/Tachiyomi/local/some manga/ch1` (aka `/sdcard/Tachiyomi/local/some manga/ch1`)
and
`/storage/18F5-2C11/Tachiyomi/local/some manga/ch2`
you will have one manga with two chapters.

If you add more chapters later you'll have to manually refresh the chapter list, but it should be instant.

Chapters can be directories with the images or a `.zip` or `.cbz` file. Nested directories are not allowed.
