### ISSUE TITLE
[Feature Request] Add option to disable share button on long press menu

### ISSUE THREAD

**Issue by GGG-KILLER** [inorichi/tachiyomi#2541]
### Why/User Benefit/User Problem
I read manga while on bed a lot and have multiple times nearly shared pages of the manga I'm reading through messaging apps, email and etc. with my face while sleeping.
It would be nice to have an option to disable *only* the share option on the long click menu since I still use a (kind of roundabout) way of sharing by saving the page then opening the file on the app I want to use to share the page and would also like to still have the possibility to set a page as a cover for the manga (without needing to enable the long press menu, set the page as a cover and then disable the long press menu again).

### What/Requirements
It would be a setting (possibly under the "disable long press menu" one) that removes/disables the share button on the long press menu

**Comment by arkon** [comment]
I can only assume you almost accidentally sent some questionable stuff.

I can't really see this being added unless there's actually a large number of people who specifically want this.

**Comment by GGG-KILLER** [comment]
well, I could try to do a PR (though I don't know much about Kotlin), I just wanted gauge the acceptance rate

**Comment by arkon** [comment]
I wouldn't be willing to accept it. Maybe there could be better UX for the menus instead.
