### ISSUE TITLE
[Bug] Can't open MangaDex in Web View (from catalogues)

### ISSUE THREAD

**Issue by StillInSearchOfACoolNewUsername** [inorichi/tachiyomi#2543]
### Device information: Samsung Galaxy J6+
* Tachiyomi version: r1680 (last dev version, I have the "check for updates" on)
* Android version: 9

## Steps to reproduce
1. Enter into the Mangadex source from "catalogues" (I think you need to be logged in and not as guest,)
2. Open the source in Web View

### Expected behavior
I would normally enter from time to time into the MangaDex source, in web view, to make sure that I'm still logged in (you now, to make sure it is included when I search for something in "global search), 

### Actual behavior
But, when I tried this now the loading bar stops at 70-75 the way through, and I can see the dark theme of my account on, and the app crashes. The major problem is that afterwards I cannot open the app again and the phone will say "the app is not responding", even if I force stop the app in the settings the problem still remains. The only way to repair the damage is to restart the phone.

### Other details
If I try to open a manga from MangaDex with web view it doesn't give any problems, and the theme remains the white of default ( because when opening a manga in web view it enters as a guest), but opening the source in web view gives me the problems stated before. This problem doesn't happen in any other source, so I assume the problem is either of MangaDex itself or of the fact that I'm logged into my account (MangaDex is the only source I have logged in in the app).

**Comment by arkon** [comment]
Might be related to the recent change for CloudFlare.  Try installing the older version for now?

**Comment by SnakeDoc83** [comment]
That's r1671, isn't it?  OP says he's on r1670.

**Comment by StillInSearchOfACoolNewUsername** [comment]
I confirmed that the problem still persists even after updating to version r1671 this morning.

**Comment by CarlosEsco** [comment]
Am unable to replicate.  Are you on latest mangadex extension?

**Comment by StillInSearchOfACoolNewUsername** [comment]
Yes, I am on the latest mangadex extension.

**Comment by StillInSearchOfACoolNewUsername** [comment]
Still the same issue.
![Screenshot_20200202-200716_Tachiyomi](https://user-images.githubusercontent.com/60304445/73613678-5ea06f80-45f8-11ea-93d8-ec5a8de537a5.jpg)

**Comment by StillInSearchOfACoolNewUsername** [comment]
I'm sorry but I don't know how to get a crash report. I'm not a developer and this issue makes me unable to use the MangaDex extension...

**Comment by StillInSearchOfACoolNewUsername** [comment]
After I close the app (or the system tell me to close it because it's not responding), every time I try to enter the app crashes. The only way is to restart the phone.

**Comment by arkon** [comment]
This might be related to the version of WebView you're using. You can try updating your WebView, if it isn't already?

**Comment by StillInSearchOfACoolNewUsername** [comment]
I have the latest version. I even tried with both the normal and beta version.

**Comment by arkon** [comment]
Unfortunately there's nothing we can do from the app's side. You could potentially look into using a different Webview implementation via developer options on your device, if possible.

**Comment by realicejoanne** [comment]
Got this issue as well. The webview is not working although I have the most updated one. Then the app crashes and I should restart the phone to use Tachiyomi again. I tried disabling Chrome app and now it's working. Try this way if the problem insists.
