### ISSUE TITLE
[Feature Request] Download all manga in selected category

### ISSUE THREAD

**Issue by monomogi** [inorichi/tachiyomi#2544]
### **Why/User Benefit/User Problem**
It will make downloading easier especially if you want to bulk download multiple manga. It takes quite a while if you want to download a bunch of manga, as you have to download each manga individually by clicking on the manga and going to "Chapters".

### **What/Requirements**
Pressing the context menu on a category will bring a drop-down list, and there would be a button like "Download all manga", downloading every manga in that category.

Here's an example of how I imagine it to look like:
![image](https://user-images.githubusercontent.com/60306168/73129605-fdd6cd00-4022-11ea-93d6-ba5900894dc6.png)

**Comment by CarlosEsco** [comment]
#1181
