### ISSUE TITLE
[Bug] NPE in PreferencesHelper (Crash)

### ISSUE THREAD

**Issue by BlueCat300** [inorichi/tachiyomi#2548]
### Device information
* Tachiyomi version: build 1679
* Android version: 9.0

## Steps to reproduce
1. Open any manga in library

### Actual behavior

> FATAL EXCEPTION: main
> Process: eu.kanade.tachiyomi.debug, PID: 18926
> kotlin.KotlinNullPointerException
> 	at eu.kanade.tachiyomi.data.preference.PreferencesHelperKt.getOrDefault(PreferencesHelper.kt:19)
> 	at eu.kanade.tachiyomi.ui.manga.chapter.ChaptersAdapter.<init>(ChaptersAdapter.kt:35)
> 	at eu.kanade.tachiyomi.ui.manga.chapter.ChaptersController.onViewCreated(ChaptersController.kt:76)
> 	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:23)
> 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1019)
> 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
> 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
> 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
> 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
> 	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:456)
> 	at com.bluelinelabs.conductor.ControllerHostedRouter.setBackstack(ControllerHostedRouter.java:107)
> 	at com.bluelinelabs.conductor.Router.setRoot(Router.java:336)
> 	at eu.kanade.tachiyomi.ui.manga.MangaController$MangaDetailAdapter.configureRouter(MangaController.kt:166)
> 	at com.bluelinelabs.conductor.support.RouterPagerAdapter.instantiateItem(RouterPagerAdapter.java:80)
> 	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
> 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
> 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
> 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> 	at android.view.View.measure(View.java:23466)
> 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
> 	at android.view.View.measure(View.java:23466)
> 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
> 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
> 	at 
> 
>  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
>

### Other details
Latest working version build 1675

**Comment by hXtreme** [comment]
Something similar also happens when I try to open the About section under Settings.

**Comment by StillInSearchOfACoolNewUsername** [comment]
Same happens here, now by doing anything. I've heard that they are making some experiments with the new cloudflare. Don't worry too much about it. If you have backups, ( I suggest enabling the auto-backup if you didn't already) try installing the older version, or like in my case, having the stable version ready for situations like this.

**Comment by Soitora** [comment]
A quick fix is to change your prefered time and date format undef General settings. Having it on the default setting (System default) causes the crash. Any other is fine and will make **About** work again.
