### ISSUE TITLE
[Bug] Unable to uninstall tachiyomi

### ISSUE THREAD

**Issue by dungwinux** [inorichi/tachiyomi#2551]
### Device information
* Tachiyomi version: r1611...r1680
* Android version: Android 10

## Steps to reproduce
1. Install Tachiyomi from apk
2. Try to uninstall Tachiyomi from Settings

### Expected behavior
The uninstalling process exits unexpectedly. When trying to uninstall Tachiyomi multiple times, the system will notify that _Package installer keeps stopping_.

![Screenshot_20200130-154246](https://user-images.githubusercontent.com/23451424/73435022-6eab1b80-437a-11ea-8ca7-ac5857ec2459.png)

### Actual behavior
Package installer should have asked _Do you want to uninstall the app_.

### Other details
I've tried to downgrade the app, and I can only uninstall the app with r1610 and previous versions. Starting r1611, the app is no longer uninstallable.

Screen capture: [MNML-January30-035751PM.zip](https://github.com/inorichi/tachiyomi/files/4133063/MNML-January30-035751PM.zip)

**Comment by joseph619** [comment]
Why are you trying to downgrade?

**Comment by dungwinux** [comment]
If I don't go back to older version, I can't uninstall it.

**Comment by arkon** [comment]
What phone are you using?

**Comment by dungwinux** [comment]
Nokia 6.1

**Comment by dungwinux** [comment]
I think I found the problem. The package installer crashed because of this line in `AndroidManifest.xml` :
```
android:hasFragileUserData="true"
```

Below should be the actual behaviour:

![image](https://user-images.githubusercontent.com/23451424/73451253-cad16800-4399-11ea-869e-777e7c96f184.png)

This is probably caused by the system, not the app, so I'm closing the issue.

**Comment by MCAxiaz** [comment]
Interesting bug.

@dungwinux Is that WhatsApp screenshot taken from this https://officialsmartphoneblog.blogspot.com/2019/11/xda-developers-android-10-lets.html
and not actually from your phone? Cause it should crash for WhatsApp as well. 
I also assume you have an SD card as well, cause that seems to be what causes the issue. 

I filed a bug report actually https://issuetracker.google.com/issues/1485738432
Seems like another case of sloppiness from Google 😔

**Comment by dungwinux** [comment]
@MCAxiaz, yes, the photo is from xda, sorry for not clarifying the source. Also, thanks for the info, I'll try to fix it on my phone

**Comment by dungwinux** [comment]
@MCAxiaz It seems that you're right. Removing SD card can solve the issue.
