### ISSUE TITLE
[Bug] MangaKisa : Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by randw0** [inorichi/tachiyomi#2552]
### Device information
* Tachiyomi extension version: MangaKisa 1.2.2
* Tachiyomi version: 0.8.4-1680
* Android version: OneUI 2.0 (Android 10)

## Steps to reproduce
1.  Open MangaKisa Catalogue or manga chapter

### Expected behavior
The catalogue list or manga chapter should load and open

### Actual behavior
java.io.IOException: Failed to bypass Cloudflare!

### Other details
The extension seems to work fine upon first install of Tachiyomi (The full app, not extension), however once the cookies reset it is unable to bypass Cloudflare again.

Tried this with other sources that have Cloudflare DDoS protection (ReadComicOnline, ReadMangaToday) and these seem to work as expected: Cloudflare doesn't fail after cookie reset.

Uninstalling and reinstalling the extension itself doesn't help. Uninstalling and reinstalling the main Tachiyomi app does get the extension to work first time, but the same happens again. This is all after the update that fixed the initial cloudflare bypass bug

**Comment by happywillow0** [comment]
What happens when you open up the source via webview? Does it load properly or does it continue to trigger cloudflare?

**Comment by randw0** [comment]
Opening in webview triggers cloudflare once, the first time after the cookies reset. After that it loads properly, both the catalogue and every manga. In-app it still shows the exception though

**Comment by happywillow0** [comment]
Ok. The current method checks to see if the cookie is set. I'm not sure why that isn't working with your rom / phone. 

One thing I would try which I have been asking other people is to see if you have any other webview implementation options in the developer options in the Android settings app. You can try another one if you have choices.

**Comment by randw0** [comment]
![Screenshot_20200131-072640_Settings](https://user-images.githubusercontent.com/54715630/73532255-1700c480-43fb-11ea-9af8-37917d20668b.jpg)

These are my options for webview.
I downloaded the beta to see if that would make a difference. It didn!t

**Comment by randw0** [comment]
I've been staring at the CloudflareInterceptor class all day today, debugging it to try to identify a Point of Failure.

What I've found is that, in the case of MangaKisa at least, the value of oldCookie that's set [here](https://github.com/inorichi/tachiyomi/blob/032a6adaabce4a369d597d6633f4b1554921d2e7/app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt#L55-L56) always ends up matching the new cookie that's supposed to be returned [here](https://github.com/inorichi/tachiyomi/blob/032a6adaabce4a369d597d6633f4b1554921d2e7/app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt#L91-L93).

I verified this by clearing the cookies, in which case the new cookie also returns a null.

I've tried increasing the wait time to no real avail, so I honestly have no idea what could be going wrong. My current guess is that it's a server side issue, instead of a bug in the code. If that's the case I'd appreciate a confirmation so I know to migrate sources

**Comment by happywillow0** [comment]
Just to check in, it doesn't look like they are running the "I'm under attack" page currently (at least in the US) which would not generate the cf_clearance cookie. 

Are you still getting a http 503 / failed to bypass issue?

**Comment by randw0** [comment]
Yes, still getting the failed to bypass issue.

I didn't know they're able to geocode the cloudflare protection. Seems that for now I'll be able to get around the issue with a VPN, but the caps on free VPN's make that a not ideal solution.

**Comment by happywillow0** [comment]
What location are you connecting from by chance? (I want to see if my vpn is able to connect to it)

And where is it happening? Is it on browse , latest, search, or a specific manga? 
There could be other part of the website that throw a http 503 other than cloudflare.

**Comment by ImRyley** [comment]
I had same problem what fixed it for me was going to Settings, Advanced, and finally Clear Cookies.

**Comment by JDcarmelo** [comment]
I have the same problem but i just turned off wifi then on and it worked again

**Comment by caHooft** [comment]
I have the same issue but for me going to Settings, Advanced, and finally Clear cookies doesnt change anything.

**Comment by polydoo** [comment]
Same problem, disable Chrome and enable WebView, works 👍🏻

**Comment by pervertkirito** [comment]
video https://streamable.com/d776b
Logcat https://pastebin.com/Gqjmxuxm

**Comment by zsinx6** [comment]
@polydoo where to disable Chrome?
