### ISSUE TITLE
 Unified view from all sources or "Browse manga"

### ISSUE THREAD

**Issue by FreddeITsupport98** [inorichi/tachiyomi#2554]
### Why/User Benefit/User Problem
Get all sources some unanimous or unified view to show many from different sources or extensions. As a feed to browse other manga instead users must select source first from categories to view manga. i Suggest look at manga rock definitive apk as inspiration for UI-element and how to combine multiple sources to display in same feed probably. Suggestion may show to the reader if it is possible.

### What/Requirements
This feature might need UI-change and apk will need extension to load in to browse from different sources and let user select which selective sources should display in "browser for manga".

**Comment by CarlosEsco** [comment]
you would end up seeing duplicates right next to each other.  Also if you know what you are wanting anyways you can just global search and show result from all enabled sources

**Comment by FreddeITsupport98** [comment]
Just enable only one source per view if user want more source to be shown they should be warned about duplicative view of manga as matter in fact.  There are extension that has multiple source in it so user may use the extension as viewing point.  Mangarock already does that only restrict one source to view and global search is good but still required to use websites or categories to view.

**Comment by CarlosEsco** [comment]
I don't understand how your terminology.  You click catalogs you click browse then you can browse manga for a source. How is that any different then browsing your enable one source per view

**Comment by arkon** [comment]
This doesn't make sense with how the app manages sources.
