### ISSUE TITLE
[Bug] cannot Download anything

### ISSUE THREAD

**Issue by Dragonsoule** [inorichi/tachiyomi#2555]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. I cannot download manga i want to read
Tryed various resorces and i can read them in the app but not download them

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
The bug says:
downloadsdir   ...y(getMangaDirName(manga)) must not be null

**Comment by arkon** [comment]
Fix you download directory setting.
