### ISSUE TITLE
[Bug] Mangahub Chapters Issue, always says Retry.

### ISSUE THREAD

**Issue by geeyahnofficial** [inorichi/tachiyomi#2557]
### Device information
* Tachiyomi version: 8.4.0
* Android version: Q

## Steps to reproduce
1. Catalogue
2. Manga Hub

### Expected behavior
Whenever you open a manga and open a chapter it will always says retry.

![IMG_20200201_194907](https://user-images.githubusercontent.com/48980299/73591623-ecfaef80-452b-11ea-8bee-ad0a5511b461.jpg)

**Comment by happywillow0** [comment]
Wrong GitHub repo / issue tracker
Also, now a dup https://github.com/inorichi/tachiyomi-extensions/issues/2170
