### ISSUE TITLE
Wireless charging not considered "charging" for updating

### ISSUE THREAD

**Issue by mishugashu** [inorichi/tachiyomi#256]
Version v0.2.0 for Android 5.1.1.

As stated in the title, wireless charging isn't considered charging. It will give the push error message "Sync cancelled" with the description of "Not connected to AC power".

Also, I feel like this error message shouldn't even pop up. I want to update every hour IF I'm charging, and not do anything otherwise. I don't need to know that I'm not charging every hour.

**Comment by NoodleMage** [comment]
Wireless charging will be fixed in my next pull. Will also add an option to make warning message optional. Thanks for the feedback ;)

**Comment by mishugashu** [comment]
Wow, quick response. Keep up the good work, thanks!
