### ISSUE TITLE
[Bug] Failed resolving cloudflare challenge 

### ISSUE THREAD

**Issue by Ayub-Khan** [inorichi/tachiyomi#2560]
### Device information
* Tachiyomi version: 0.8.2
* Android version: ?

## Steps to reproduce
1. First step
Go to catalogues
2. Second step
Try to browse any

### Expected behavior
This should open and show mangas

### Actual behavior
Shows error in the bottom.

For extensions it works fine. 

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
You should at least update to 0.8.4, but dev has more changes for CloudFlare.
