### ISSUE TITLE
Shikimori sync

### ISSUE THREAD

**Issue by nonameyebiwe** [inorichi/tachiyomi#2564]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 8.1.0

## Steps to reproduce
1. Settings/tracking/shikimori
2. shikimori.org

### Expected behavior
Should open shikimori.one. They are was blocked in russia and change domen.

### Actual behavior
Open shikimori.org

### Other details
No more details.

**Comment by arkon** [comment]
This is already fixed in dev. I'd recommend migrating over.

**Comment by nonameyebiwe** [comment]
> I'd recommend migrating over.
How?

**Comment by arkon** [comment]
Install dev, do a backup in 0.8.4, then restore in dev.

**Comment by nonameyebiwe** [comment]
Thanks.
