### ISSUE TITLE
[Bug] Extensions page not updating

### ISSUE THREAD

**Issue by ridho9** [inorichi/tachiyomi#2566]
### Device information
* Tachiyomi version: r169
* Android version: 9

## Steps to reproduce
1. Open extensions page
2. Update (pull down)

### Expected behavior
Extensions that have update or not installed shown.

### Actual behavior
Only installed extensions shown

### Other details
Logcat message when I open the extensions tab
```logcat
02-04 00:04:14.719 27260 27260 E tachiyomi.debu: Invalid ID 0x00000000.
```

**Comment by arkon** [comment]
Did this occur in other versions for you too?

**Comment by ridho9** [comment]
I tried r1685 and r1689 and it works, now after I installed r1690 again it works. Should I just close the issue?

**Comment by e-shl** [comment]
> I tried r1685 and r1689 and it works, now after I installed r1690 again it works

After clearing the application cache, extension disappear again and filter language

**Comment by rama982** [comment]
Can confirm
![Uploading Screenshot_20200204-025715.png…]()

**Comment by MCAxiaz** [comment]
@arkon 
https://github.com/inorichi/tachiyomi/commit/a3e39987d4ca5cd097cda6151dec3abf75238916#diff-eb333bc49012db9000dff7fe93067871R29

Response body is being accessed on main thread.

**Comment by arkon** [comment]
I pushed a change that _might_ fix it, let me know if it does.

I couldn't actually reproduce the issue.
