### ISSUE TITLE
[Bug] can't edit categories

### ISSUE THREAD

**Issue by reiny2000** [inorichi/tachiyomi#2567]
### Device information
* Tachiyomi version: r1690
* Android version: 8

## Steps to reproduce
1. Open Tachiyomi
2. Press the three dots on the upper right corner

### Expected behavior
A drop down menu with a few buttons. Among those an edit categories button

### Actual behavior
The edit categories button is missing

### Other details
It appears I can assign categories, I just can't edit them or create new ones

**Comment by happywillow0** [comment]
The edit categories button has been moved into the settings menu. You can check it out under the 
Settings > Library > Categories
