### ISSUE TITLE
[Feature Request] Practise Language feature

### ISSUE THREAD

**Issue by Zhonecage** [inorichi/tachiyomi#2568]
### Why/User Benefit/User Problem
1. This feature allows readers to read japanese-only colored manga in english by displaying english speach bubbles when tapping on japanese speech bubbles.

2. Allows readers to practise japanese by reading japanese manga and displaying english speech bubbles when tapping on japanese speech bubbles.

### What/Requirements
So far there is only one app that has this feature: Comic Reader Mobi. Unfortunately it's outdated, has long since been discontinued and it's not available anymore.

This feature works as follows: When loading manga, you have to specify a _Primary_ manga and _Secondary_ manga. Both are the exact same manga with same chapters, pages etc but one is in japanese and the other is in english. Both are loaded at the same time in RAM. The _Primary_ manga is your japanese (colored) manga that you see on the screen and read. The _Secondary_ manga is your english translated (non-colored) manga that runs in the background as a layer underneath the _Primary_ manga.

Now, when you tap anywhere on the japanese manga, it opens a so called lense (it's basically a magnifying glass) that you can move around the manga page and show the english, non-colored manga.

Here is a screenshot to show what it looks like on Comic Reader Mobi: https://s19.directupload.net/images/200203/stfgfwn3.jpg

When you switch a page of your _Primary_ manga chapter, then it should automatically switch a page of your _Secondary_ manga as well.

If you need more information, please don't hesitate to ask.

**Comment by Nexr0n** [comment]
since the app is getting manga from third parties that would make it nearly impossible, resolutions could be different, alignments sometimes off, translated manga often has extra pages inserted to advertise the translator's discord or Patreon. the app doesn't process manga, it just displays it from external services, so it's not really in its scope to clean the 2 copies so they line up properly. 
it's a good idea, just not within this apps established framework.

**Comment by CarlosEsco** [comment]
Way out of scope of what this app is wanting to be and is

**Comment by Zhonecage** [comment]
> 
> 
> since the app is getting manga from third parties that would make it nearly impossible, resolutions could be different, alignments sometimes off, translated manga often has extra pages inserted to advertise the translator's discord or Patreon. the app doesn't process manga, it just displays it from external services, so it's not really in its scope to clean the 2 copies so they line up properly.
> it's a good idea, just not within this apps established framework.

Everything you said is accounted for in the Comic Reader Mobi app. It works with different resolutions, alignments, extra pages, external sources... You should try it some time. Also you may not be aware of it but Tachiyomi has actually a local manga function.



> 
> 
> Way out of scope of what this app is wanting to be and is

Honestly this sounds like an excuse not to invest the work into this feature.

**Comment by CarlosEsco** [comment]
@Zhonecage you are welcome to write the feature, debug it and open a pull request
