### ISSUE TITLE
Alternative for desktop which fetches from same sources?

### ISSUE THREAD

**Issue by DaniellMesquita** [inorichi/tachiyomi#2571]

**Comment by wopian** [comment]
[TachiWeb](https://github.com/TachiWeb/TachiWeb-Server/blob/develop/README.md) for linux/macOS/windows or use an Android emulator like BlueStacks or MeMU.

**Comment by wopian** [comment]
[TachiWeb](https://github.com/TachiWeb/TachiWeb-Server/blob/develop/README.md) for linux/macOS/windows or use an Android emulator like BlueStacks or MeMU.

**Comment by CarlosEsco** [comment]
There are also plenty of dowloaders tha download from same source.  Also tachiweb has been put on hold for an eventual tachiyomi 1.x release
