### ISSUE TITLE
[Feature Request]Chapter list bookmark backup option

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2572]
### Why/User Benefit/User Problem
bookmarks backup option should be added.
Help to improve user experience when transferring data from stable to dev edition or reinstalling app.
Must for user who uses bookmark during reading.

### What/Requirements
Done by adding a bookmark option in create backup menu.

**Comment by joseph619** [comment]
Wait, bookmark in Chapter list is not backed up? What the hell.

**Comment by joseph619** [comment]
Mention Chapter list in your post title and description so that it's easier to understand.

**Comment by Samk19** [comment]
@joseph619 
Originally bookmarked chp
![IMG_20200206_104317](https://user-images.githubusercontent.com/36104528/73907810-ae6b8900-48cd-11ea-8c42-ad70e77a3604.jpg)

After restoring
![IMG_20200206_104335](https://user-images.githubusercontent.com/36104528/73907860-de1a9100-48cd-11ea-91ba-6af0edad2bd5.jpg)


Expected result : Chapter should be bookmarked

**Comment by arkon** [comment]
This appears to work fine in the latest versions.
