### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by im-quite-retarded** [inorichi/tachiyomi#2573]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 7

## Steps to reproduce

1. Go to extensions
2. Install Mangadex as a source
3. go to catalogues
4. select Mangadex
5. pick any manga
6. try to open a chapter
7. get retry button

### Expected behavior
The chapter should load

### Actual behavior
All you get is the retry button and retrying does not load the pages

### Other details
Mangadex extension v1.2.79
This only happens when open or download chapter that uploaded before mangadex changing their domain to .cc. There's no problem with recently uploaded chapter

**Comment by CarlosEsco** [comment]
2.  things

1.  wrong repository.  Extensions to here https://github.com/inorichi/tachiyomi-extensions
2.  go to settings -> advanced settings -> clear cache, cookies, database

**Comment by im-quite-retarded** [comment]
clear cache, cookies, database and the problem still persists.

**Comment by im-quite-retarded** [comment]
clear cache, cookies, database and the problem still persists.

**Comment by CarlosEsco** [comment]
go on the discord channel and ask for help there

**Comment by arkon** [comment]
You can try "migrating" them

**Comment by im-quite-retarded** [comment]
> You can try "migrating" them

You mean changing the source ?

**Comment by arkon** [comment]
Yes, but to the same source.

**Comment by im-quite-retarded** [comment]
> Yes, but to the same source.

Doesn't work :(

**Comment by CarlosEsco** [comment]
go on discord ask for help there
