### ISSUE TITLE
Export image and synopsis of series

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi#2574]
**App version:**
0.84
**Android version:**
9
**Issue/Request:**
Export image and synopsis of series
**Steps to reproduce (if applicable)**

 1.Find the series you want to export.
 2.Add in the menu the option to export the cover and the synopsis and genres. You can also save the url of the series as additional information.
 3.Cover can be saved normally and other information can be saved in an xml called info.xml

**Other details:**
This information can be copied into the folder of a series in the local repository so that the information in the series is shown, not just a random image as it is currently done.

**Comment by CarlosEsco** [comment]
random image?

**Comment by wruizcanal** [comment]
Yes. The app take the first image or the first cap of the series. This image is usually the image of the scan or simply an image of the chapter, therefore a good cover cannot be seen. That is why I want to be able to export the cover and the synopsis of the series so that it can be placed inside the series folder and loaded when the local repository series are read.

**Comment by CarlosEsco** [comment]
you can just edit the cover and choose another image

**Comment by arkon** [comment]
This actually thinks that something like a "Copy to local catalogue" feature might be more useful.

**Comment by arkon** [comment]
Closing in favour of #2666.
