### ISSUE TITLE
[Feature Request] Toggle to show cover images in chapters list

### ISSUE THREAD

**Issue by Gin-no-kami** [inorichi/tachiyomi#2577]
While this may only benefit those who use a personal komga database, I believe the change would have to be made to the Chapter List, thus I am putting the feature request here.

**Why/User Benefit/User Problem**
When reading volumes, i.e. not individual chapters, the cover art is not displayed for each volume in the chapter list. By adding the ability to toggle the chapter list to be a grid, which would display the first page of each volume as the cover, users will be able to see all the nice cover art when browsing the volumes of their manga.

**What/Requirements**
Implement a layout similar to the Library display's Grid/List mode for the Chapter List, thus allowing users to toggle between a list view or a grid view displaying the cover art for each "chapter" (or volume)

**Comment by CarlosEsco** [comment]
Too specific of a feature, that like you said is only useful for komanga.

**Comment by arkon** [comment]
I can see the appeal of having a grid view (maybe), but it would definitely result in a lot of extra network calls.

**Comment by Gin-no-kami** [comment]
Any particular reason this was closed? By making this a toggle, which could be set to list view by default, the amount of network calls would not be an issue. Then for users who actually have covers that they would like to see (i.e. are reading whole volumes stored in a Komga server), the "extra network calls" really won't be an issue since it only has to be done once. Here is a mockup of what the UI could look like (please ignore the extra tab as the mockup was made for another fork).
![UI Mockup](https://user-images.githubusercontent.com/15571712/75112843-db31d700-5615-11ea-8dd4-3a774f547d85.png)

**Comment by CarlosEsco** [comment]
It makes little sense to have since everything is chapter based
