### ISSUE TITLE
[Feature Request] Add an option to hide downloaded mangas from gallery apps

### ISSUE THREAD

**Issue by ArKaGarCa** [inorichi/tachiyomi#2581]
### Why/User Benefit/User Problem
As a normal user who downloads most of its manga, I've found quite annoying that whenever I want to look for an image on my phone, there's all the manga I've downloaded in the middle. This happens on any app that allows you to send images, such as most social medias. It is bearable when you have a low amount of chapters downloaded, but if you have a bunch like me (around 500 chaps from different mangas or webcomics), it becomes quite an annoyance.

### What/Requirements
I've seen other apps (such as Ukiku) that rely on a specific extension for their files in case the "Hide from gallery" option is selected. This prevents the normal gallery apps from showing the files, since they can't understand their extension.
It's also posible to compress the folders which contain each chapter's pictures, but I think it would be a bit less effective, since there are galleries that detect compressed files and show the images they contain.

**Comment by joseph619** [comment]
Create a .nomedia file and put it in the downloads folder, problem solved

**Comment by arkon** [comment]
This should already be fixed in dev. What version are you using?

**Comment by ArKaGarCa** [comment]
I'm on 0.8.4, I tend to use the stable version of many apps I use, mainly for compatibility.

**Comment by Soitora** [comment]
As long as you're on Android 5 or above then Dev *shouldn't* be a problem. It's almost year newer.

**Comment by ArKaGarCa** [comment]
Well then, seems I'll have to upgrade to Dev version. Thanks for the help. Any advice on how to export all of my settings and libraries so that I don't have to redo everything?

**Comment by joseph619** [comment]
Ask on Discord, this is not support forum. And you have to restore backup,

**Comment by ArKaGarCa** [comment]
I'll do it then. Thanks everyone for your help.
