### ISSUE TITLE
[Feature Request] Dark / Light theme

### ISSUE THREAD

**Issue by vitaliyrahmanin** [inorichi/tachiyomi#2583]
### Why/User Benefit/User Problem
(explain why this feature should be added)
The dark theme, however, is very convenient, but it is not convenient to switch every day in different lighting conditions. I think implementing faster access to it is very simple for you.
### What/Requirements
(explain how this feature would behave)
Can you make a button with a dark / light theme on the swipe on the left? You can even activate by clicking on the application sign in the menu on the left swipe: this is implemented in the Relay Reddit application.
I will attach screenshots of how it looks in Relay reddit.
I think you can add “quick settings” down the swipe left.
And also automatically with the system in android 10.

I do not know how to add screenshots to the spoiler
![photo_2020-02-11_19-11-54](https://user-images.githubusercontent.com/45261656/74255730-571d4c80-4d03-11ea-8996-8734edbdafc0.jpg)
![photo_2020-02-11_19-11-51](https://user-images.githubusercontent.com/45261656/74255749-5e445a80-4d03-11ea-9c69-34030e3aef6d.jpg)
![photo_2020-02-11_19-11-48](https://user-images.githubusercontent.com/45261656/74255770-61d7e180-4d03-11ea-91c3-e02e4f01797c.jpg)

**Comment by arkon** [comment]
The sidebar is eventually going away.

**Comment by vitaliyrahmanin** [comment]
Ok, but implement some kind of fast switching-on.
Do not constantly take 8 steps to change to a light / dark theme

**Comment by joseph619** [comment]
New update has added System theme, that should solve this issue mostly.

**Comment by Eyap53** [comment]
Linking for reference: #2603
