### ISSUE TITLE
[Feature Request] Add option to switch back to the old sort by last updated

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2584]
### User Problem
The new sort by last updated setting sorts by when a particular manga received an update in it's corresponding source. What I care about is when I received the update for any particular manga, this is because I mostly manually check for updates for my most read manga and every once in a while I'll update my entire library.

In the new sort, my most read manga show up on before manga that I don't check for frequently (even if I just got an update for it while doing a global update).

Meanwhile the old sorting mechanism would show me the items for which I just received an update first.

### What/Requirements
Add a preference under settings to switch between the new sort and the old sorting format.

**Comment by arkon** [comment]
Superseded by #2563

**Comment by hXtreme** [comment]
I'm satisfied with both of them  coexisting in a different way.
