### ISSUE TITLE
Update by chapters

### ISSUE THREAD

**Issue by Honestlyi** [inorichi/tachiyomi#2586]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version: 0.8.4 **

**Android version:**

**Issue/Request: Update by chapters**

**Other details: It's more like a question. Is there a way to set the application to update the last chapter on the top and not by the manga? I have to scroll down to find my updates which is difficult to do since I have around 200 manga so I'm afraid I might not be able to read one of the updated manga.**

**Comment by arkon** [comment]
I'm not entirely sure what you mean. Do you have a more concrete example?

**Comment by Honestlyi** [comment]
![first](https://user-images.githubusercontent.com/57447967/74297784-e7648d00-4d15-11ea-829b-2abe9a0431ca.PNG)
![second](https://user-images.githubusercontent.com/57447967/74297790-e92e5080-4d15-11ea-8f86-0d6cab6b32f3.PNG)

If you look at the chapter numbers, they aren't exactly in order.

**Comment by Honestlyi** [comment]
![third](https://user-images.githubusercontent.com/57447967/74308292-cd3aa700-4d35-11ea-9744-720accb41406.PNG)
Also, when there is an update, it's not on top of the list which makes me concern if I would miss an update.

**Comment by FlaminSarge** [comment]
Unfortunately, the 'Recently Read' list goes strictly by the chapter upload time, so if the uploader decides to upload them out of order, you end up with this issue. However, I do not know what the current behavior is if the upload time is the exact same for two chapters.
@arkon is it possible that we're not sorting by highest chapter number to break ties in those cases?
