### ISSUE TITLE
[Bug] Cover image doesn't update.

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2588]
### Device information
* Tachiyomi version: r1711
* Android version: NA

## Steps to reproduce
1. Open up a manga that has a new cover image
2. Refresh the metadata screen

### Expected behavior
The cover image should update.

### Actual behavior
The cover image stays the same.

### Other details
[Screen recording](https://youtu.be/jHcDXnsMGpM)

**Comment by CarlosEsco** [comment]
problem is tachiyomi sees the same cover url and ignores it.    You would to delete the cover and clear the cover cache for that manga when you refresh.  Then hope the website wasn't down or else it will have no cover then.

**Comment by Battler624** [comment]
Go to refresh library metadata in advance.

**Comment by hXtreme** [comment]
> Go to refresh library metadata in advance.

But that would refresh the entire library, two thousand more files than I want to.

**Comment by CarlosEsco** [comment]
your other option is to remove it from library.  clear database (maybe cache) then re add it

**Comment by hXtreme** [comment]
Why not have the update process be something like the following:

1. Trigger metadata page refresh.
2. temp <-- image, metadata
3. try: 
    a. get image and metadata
    b. store the new data.
4. on error: revert to temp.

This would resolve your previous concern with breaking cover image.

**Comment by CarlosEsco** [comment]
works but 90% of source never change their cover.

**Comment by hXtreme** [comment]
but what I speculate is the most popular source, mangadex does.

**Comment by arkon** [comment]
Addressed by #3101 (I think)
