### ISSUE TITLE
[Bug] MangaDex Search not functioning

### ISSUE THREAD

**Issue by kaosjr** [inorichi/tachiyomi#2589]
### Device information
* Tachiyomi version: r1719 (latest), reproduced in r1713 as well. MangaDex plugin 1.2.79, reproduced in 1.2.78, 1.2.77 nonfunctional (could not test)
* Android version: 9.0 (Pie)

## Steps to reproduce
1. Install the MangaDex plugin.
2. Switch to Collections, then click Browse.
3. Click the search icon in the top left, and try searching for anything. I saw one piece at the top of the browse menu, and tried it to test.

### Expected behavior
Search should find results, as it does with other sources (I tested KissManga, which worked fine)

### Actual behavior
No results found no matter what the search. Using filters also resulted in the same issue.

### Other details
Here's a screenshot of the issue in action.
![Screenshot_20200213-010714](https://user-images.githubusercontent.com/16449077/74418432-346f5e80-4dfd-11ea-838e-f3ad208d7a96.png)

**Comment by kaosjr** [comment]
For due diligence, I thought I'd check on a second device. My Nvidia Shield Tablet running Android 7 and the latest version of the app and extension also has the same issue with search.

**Comment by happywillow0** [comment]
You have to log into Mangadex for search to work

https://tachiyomi.org/help/faq/extensions/#no-results-when-searching
