### ISSUE TITLE
Feature suggestions (and one possible bug)

### ISSUE THREAD

**Issue by Trudd** [inorichi/tachiyomi#259]
This is what I hope this app would work. I'm sure not everyone sees the need for all these features. Sorry for including it all in one big post. This is with the new ver 0.2.0 in mind. By the way I'm very grateful for this app. It saved me from my sinking MangaWatcher ship, and is now my main mangareader. So thank you!

New features:
- Set any category as default "HOME"
- Show already selected categories when changing them (unless multiple manga selected)
- Be able choose if you should add the selected categories to the existing ones already set, remove them, or simply replace any existing with the new.
- Be able to hide categories at the top
- Unselecting all categories on a manga will move it to default
- Able to sort categories by name, artist, author and source
- Change color on number of chapters when chapter has been added recently, and perhaps change it when no new for a long time?
- A bit hard to see selected mangas so can be hard to deselect them (back button works, but it deselects all)
- Add a select/unselect all option
- Extend filter capabilities. For example show only completed, ongoing, genres, artist, author and sources.
- Option to search in all library or current category.
- Ability to rate a manga in your library, and to add your own comments to them.
## 
- Keep search result when changing catalogue (separate search field if necessary). Or simply allow searching all sources at once.
- Show in other catalogues when app think you already have a manga from another catalogue. If allowing to search all sources at the same time it would also solve this problem.
## 
- Improve downloading. Maybe allow a setting in options to retry downloading a  page 1-4 times when downloading chapter or page, so you don't need to manually try so many time?

Changes to existing features:
- More space between Retry and Open in browser buttons when reading. Not having the trashcan so close to the tag icon (or pen). In short more space between just about every selectable option in the app.
## 

Misc:
- Don't really understand the function of the pen icon. Can someone explain it?
- Not sure about the sync option. Would this allow me to read on multiple devices and my settings would sync between them (ie categories and read chapters)? If not could you add an option to upload library to the cloud (in a way that will work as backup as well) to sync between devices, for example to OneDrive or Google Drive?

/Ulf

**Comment by NoodleMage** [comment]
Thanks for the feedback!.

Could you please use multipart  as per [guidelines](https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md) 

##

You can change the cover image with the edit (pen) icon.

**Comment by Trudd** [comment]
Removed the one bug I mentioned in the post and created a separate post for it. I guess the check-marks was intended for bugs only? But let me know if you want me to do anything further to make it easier to handle what I posted. Thanks.

**Comment by j2ghz** [comment]
Put a space after the star for a list (https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md)(https://guides.github.com/features/mastering-markdown/)

**Comment by Trudd** [comment]
Ah, ok got it. :-)

**Comment by j2ghz** [comment]
Please search existing issues for duplicates.

e.g. Category selection: [#135](https://github.com/inorichi/tachiyomi/issues/135)

**Comment by NoodleMage** [comment]
Closing this one. Most of them are implemented and should be added separately
