### ISSUE TITLE
[Bug] Download feature doesn't work anymore

### ISSUE THREAD

**Issue by 5Rjun** [inorichi/tachiyomi#2592]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Open up a manga
2. Try to download it

### Expected behavior
The manga should be downloaded.

### Actual behavior
Fails to download 

### Other details
Here is a screen shot 
![Screenshot_20200215-013855](https://user-images.githubusercontent.com/45569750/74564014-0f612400-4f94-11ea-91b9-44e26f7f2cec.png)

**Comment by arkon** [comment]
See https://tachiyomi.org/help/faq/application/#why-do-i-see-attempt-to-invoke-virtual-method-com-hippo-unifile
