### ISSUE TITLE
[Bug] ReadComicOnline not working

### ISSUE THREAD

**Issue by DustyButters** [inorichi/tachiyomi#2593]
### Device information
* Tachiyomi version: r1477
* Android version: 9

### Expected behavior
Should work

### Actual behavior
Doesn't work

As the description says i have a problem with the ReadComicOnline plugin when i try to open the comics list it gives me a strange error and it doesn't load please help

EDIT
just updated to last version 0.8.4and still have the error but it is different

**Comment by arkon** [comment]
Providing the error would help.

**Comment by DustyButters** [comment]
![Screenshot_20200215_005023_eu kanade tachiyomi](https://user-images.githubusercontent.com/61069455/74577087-d6be4c00-4f8d-11ea-9bb4-4b9c156a7204.jpg)

**Comment by arkon** [comment]
I assumed you were using the dev version judging from the version number. If you were, try updating that (it should be around r1720-ish now).

**Comment by MercerBoi** [comment]
In my case, `java.lang.Exception: Challenge not found` has been changed to `java.io.IOException: Failed to bypass cloudflare`. I have found a number of solutions for this, but none are permanent:

**Method 1**: Simply refresh the chapter list twice. The first time should give you the error, and the second time will refresh as usual, meaning you can resume reading. If this fails...
**Method 2**: Open the comic in webview, wait till the page fully loads, and then go back to the app and see if you can read. If this fails...
**Method 3**: Go to Settings > Advanced and clear cookies. Then shut down the app and repeat **Method 2**.

These are by no means universal solutions, they are just what I have found to be working for me. I get the error after reading about 2 or 3 chapters and these usually fix it. I am on dev build r1722 and using Android 6.0.1, MIUI Global 10.2.

**Comment by DustyButters** [comment]
> In my case, `java.lang.Exception: Challenge not found` has been changed to `java.io.IOException: Failed to bypass cloudflare`. I have found a number of solutions for this, but none are permanent:
> 
> **Method 1**: Simply refresh the chapter list twice. The first time should give you the error, and the second time will refresh as usual, meaning you can resume reading. If this fails...
> **Method 2**: Open the comic in webview, wait till the page fully loads, and then go back to the app and see if you can read. If this fails...
> **Method 3**: Go to Settings > Advanced and clear cookies. Then shut down the app (clear from recents) and repeat **Method 2**.
> 
> These are by no means universal solutions, they are just what I have found to be working for me. I get the error after reading about 2 or 3 chapters and these usually fix it. I am on dev build r1722 and using Android 6.0.1, MIUI Global 10.2.

The fact is that it doesn't even load the comics list that's the problem

**Comment by MercerBoi** [comment]
> The fact is that it doesn't even load the comics list that's the problem

Yes, getting the error means not getting anything else, that's what those methods are for. You don't have a single comic added to your library? Just that would suffice.

**Comment by DustyButters** [comment]
> > The fact is that it doesn't even load the comics list that's the problem
> 
> Yes, getting the error means not getting anything else, that's what those methods are for. You don't have a single comic added to your library? Just that would suffice.

Fixed thanks
