### ISSUE TITLE
[Bug] MangaDex Some of the Cover Images failed to load

### ISSUE THREAD

**Issue by Moralde-Sama** [inorichi/tachiyomi#2594]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 5.1.1

## Steps to reproduce
1. Press the **latest** option of MangaDex from Catalogues
2. Wait for the cover images to load on Grid View

### Expected behavior
All cover images should load

### Actual behavior
Some cover images failed to load.

### Other details
Some of cover images failed to load but you can load 1 of those broken images by
![Screenshot_2020-02-16-13-02-27-79](https://user-images.githubusercontent.com/41711381/74599541-acb87700-50be-11ea-846e-5964cda43e2c.png)

pressing the broken cover images then wait for it to load 
![Screenshot_2020-02-16-13-02-41-40](https://user-images.githubusercontent.com/41711381/74599559-0456e280-50bf-11ea-8548-53d1ae853f23.png)

then go back to the list
![Screenshot_2020-02-16-13-02-45-82](https://user-images.githubusercontent.com/41711381/74599567-30726380-50bf-11ea-9b1a-f0e6cfba051c.png)

**Comment by CarlosEsco** [comment]
Wrong repo, and working as designed. Long story short for hq covers we guess the image url.  It's right about 85% of time.

**Comment by Moralde-Sama** [comment]
I see. I switched to Mangakakalot catalog seems works fine.
