### ISSUE TITLE
Almost none of the English sources' search tool works

### ISSUE THREAD

**Issue by LetThisNameBeAvailable** [inorichi/tachiyomi#2598]
Only a couple of the English manga sources' search tool work like Kissmanga, Manga Eden, Mangahere, Mangakakalot. The rest don't work at all

**Comment by arkon** [comment]
- What version of the app are you using?
- Can you specifically list the sources that don't work?
- Are you searching in individual sources, or global search?

**Comment by ZayedHegazi** [comment]
Same problem, on the latest version (0.8.4 I presume?). The problem happened to me on Mangadex, not only do the covers not appear, but the search doesn't work at all (no results for anything I type)

**Comment by LetThisNameBeAvailable** [comment]
> * What version of the app are you using?
> * Can you specifically list the sources that don't work?
> * Are you searching in individual sources, or global search?

I'm using the latest version, 0.8.4.
The sources that don't work are:
Mangadex
Webtoons (no results)
Mangafox (no results at all?)
Mangago (same thing as above)
Mangazuki

And none of their search engine work in global or individual search

**Comment by CarlosEsco** [comment]
mangadex requires a login. https://tachiyomi.org/help/faq/extensions/#mangadex
mangafox, mangago are not supported anymore.  Mangazuki i believe had an update at one point.  Either way these are extensions issues.  Not main app issue

**Comment by happywillow0** [comment]
Also, version 0.8.4 is unable to work around broken searches. You can upgrade to the dev version or another fork (j2k, ah, etc) which should bypass any search that isn't working therefor not affecting others.
