### ISSUE TITLE
Feature Request: On Catalogue Screen, allow to select multiple Mangas to be added to Library

### ISSUE THREAD

**Issue by namack75** [inorichi/tachiyomi#26]
Just a shortcut to add multiple mangas.
Something like a Long Click/Hold to enter a multi-selection mode (Like ES Manager).

_(BTW, awesome job thus far)_

**Comment by inorichi** [comment]
Multiple selection in the catalogue can be troublesome.

Instead, long click will show a popup where you can add it to library.

**Comment by inorichi** [comment]
Done. 173e863
