### ISSUE TITLE
[Bug] Old covers don't delete after updating manga

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi#2600]
### Device information
* Tachiyomi version: r1733
* Android version: 8.1

## Steps to reproduce
[1]. Do Source migration of any manga or just try refreshing Libary Metadata 

### Expected behavior
I think after getting new cover by doing [1], the old ones should be deleted from data storage. 

### Actual behavior
Old covers don't get deleted and use unnecessary storage. 

### Other details
my English is bad.

**Comment by AmineI** [comment]
Good point. Multiple sources also update the cover each time a new volume is released, so over time and depending on the library size, it could take quite some space.

**Comment by arkon** [comment]
This should be reliable after #3101.
