### ISSUE TITLE
[Feature Request] auto update mangas that you would like for offline use

### ISSUE THREAD

**Issue by Reiayanami24** [inorichi/tachiyomi#2607]
It would be sweet if in tachiyomi, mangas that u've bookmarked can be auto downloaded when manually updated. The function would eliminate the need to manually download the new chapters of whatever manga you wish to keep for offline use.

**Comment by CarlosEsco** [comment]
This is already option. In library setting.

**Comment by Reiayanami24** [comment]
I'm on dev r1722 and no option to specifically auto download new chapters of specified mangas exist in library. 

There is an auto update manga feature but none for auto downloading them. 

For example, let's say you have 100 mangas in your library 25 mangas per folder, 4 folders total.  Let's say you either manually update or auto update manga chapters, it would be nice when a new chapter is found for a certain manga you want to read offline to be able to be detected then auto downloaded

**Comment by CarlosEsco** [comment]
So make a category with the manga you want then settings -> downloads -> download new chapters and select the category you want to have auto download  when new chapters arrive

**Comment by arkon** [comment]
Also FYI you can edit posts.

**Comment by Reiayanami24** [comment]
Thank you!  Sorry I don't usually post in Github so I'm not familiar with how to edit posts on here @_@
