### ISSUE TITLE
Manga.ae problem 

### ISSUE THREAD

**Issue by Amr-4** [inorichi/tachiyomi#2609]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 8.4

**Android version:** 9.1

**Issue/Request:** Fix

**Steps to reproduce (if applicable)**

 1.
![Screenshot_20200219_191622_eu kanade tachiyomi](https://user-images.githubusercontent.com/59889000/74851571-7d1e9e80-534c-11ea-98b4-6b579222a4c4.jpg)

 2. 
![Screenshot_20200219_191605_eu kanade tachiyomi](https://user-images.githubusercontent.com/59889000/74851588-80b22580-534c-11ea-97eb-9107cd06ef94.jpg)

 3. All Mangas appear Like this

**Other details:**
Also the mangas no apear in library updates

Thank you

**Comment by Jerrk** [comment]
read the first 3 lines of ur own post

**Comment by Jerrk** [comment]
and please close this issue when you're done with that
