### ISSUE TITLE
Possible bugg with category menu/list

### ISSUE THREAD

**Issue by Trudd** [inorichi/tachiyomi#261]
I mentioned this bug among a feature request post. Moved it out as a separate post instead. I Hope this helps.

Category menu/list at the top resets to the middle after going to other options such as settings, and the go back. The correct category is still selected though. Ie I have quite a few categories and mostly use this first few. But since it seems to reset the menu to show the middle of the whole list I have to constantly scroll back to the beginning to change categories if I in anyway leave the library.

Version: v0.2.0
Android 5.1.1 (Sony Xperia Z2 tablet)

**Comment by inorichi** [comment]
Is it still happening? I can't reproduce this (or I didn't understand you)

**Comment by Trudd** [comment]
I'll try to explain a bit better. I have quite a few categories that I have created. I have more than can fit at the top. I list a few here since I need them down below when explaining the issue. All, Unsorted, Good, Ok, Boring, Completed, Ongoing, Abandoned, Forget, Mature etc with about an additional 10 categories. This list of categories is what I referd to as the menu in my previous post. Since it doesn't fit on one screen I can scroll left and right to choose the desired category. So far no problems.

The specific example I mentioned with the settings is actually "solved" so it now behaves as I would expect it to (but perhaps not how you intend it to?). I prefer to remain at the category I selected even after going in to any of the apps options. And to have the category menu to remain underlined above the mangas in that category. Selecting the Settings option actually do this right now. However this is the only thing that work like this.

If you go in to any of the mangas i the category "Unsorted" or "Good" and right back again you still remain in the correct category, but the list of categories at the top will move to the rightmost position. Doing the same thing when in the "Boring" and "Abandoned" categories nothing happens and all is good. And finally selecting the "Forget" or any to the right of this category, will result in the list of category to reset to its leftmost position.

If you instead when you are in any of the catergories and select any other option other that the Settings option in the sidebar/main menu, such as Recent updates, Backup or Catalogues the category is change to the first (the All in my case) and the list of categories goes to the rightmost position.

I use an Xperia Z2 tablet recently upgraded from Android 5.2(?) to 6.0.1 (mostly in the upright position just like a book) if this information is needed. I feel I might still not managed to explain it in a simple way but I hope the gist of it got through?

**Comment by inorichi** [comment]
Okay, I got it. It's not a bug, but a feature request to remember the last active category, similar to how the last used source is remembered in the catalogue. This happens because the fragment containing the library tab is recreated from scratch everytime you open it.

I'll try to add this.
