### ISSUE TITLE
App crashing when searching new chapters 

### ISSUE THREAD

**Issue by Beylers** [inorichi/tachiyomi#2611]
App version: r1747

Android version: 7.1.2

Issue: App crashes when checking new chapters from certain sites (kissmanga, read manga today) and not others (manga park). I have the latest updates for all extensions. This started since the commits on Feb 17, 2020. All the dev updates before that date worked fine. I don't know how to get the logs if that's possible, would gladly share them.

**Comment by arkon** [comment]
Would help if you list the manga too.

What language are you using?

**Comment by Beylers** [comment]
> Would help if you list the manga too.

Well it crashes on all Manga from the sites it doesn't work on. On kissmanga for example Black clover and on read manga today okitenemuru. Mangadex, manga park and some others work just fine. Also just now noticed I can't even Browse kissmanga and readmangatoday through the catalogue it crashes before showing any manga. 

> What language are you using?

English 

On my phone everything works just fine and I have the same library on there so it has to do something with my tablet and that update Feb 12.

**Comment by joseph619** [comment]
Uninstiall and reinstall Tachi on your tablet maybe? Seems like an issue with your tablet than the app.

**Comment by Beylers** [comment]
Alright I tried to install and reinstall it but it still crashes. I didn't even import my library yet I just went to catalogue kissmanga browse and it immediately crashes. Is there anyway to get an older Dev Version sadly I deleted all old dev apks. I also installed the stable build and on that one kissmanga works, for a second an Java.lang.exception error showed up on the stable build but after retrying it showed the full kissmanga catalogue.

**Comment by joseph619** [comment]
Here's old dev

https://tachiyomi.kanade.eu/

**Comment by arkon** [comment]
It'd help if you can get logs. There's some guides online for how to do so ("logcat" would be a useful search keyword).

**Comment by Beylers** [comment]
> It'd help if you can get logs. There's some guides online for how to do so ("logcat" would be a useful search keyword).

Yesterday I installed the r1722 version and it worked again. I installed the latest version and it went back to crashing. Just now did the logcat, it's in the attachment.
[logcat.txt](https://github.com/inorichi/tachiyomi/files/4232379/logcat.txt)

**Comment by arkon** [comment]
Appears to be an instance of this issue: https://stackoverflow.com/questions/57414530/illegalstateexception-reasonphrase-cant-be-empty-with-android-webview

Have you tried updating whatever Webview you're using? (Probably either Android Webview or Google Chrome.)

**Comment by Beylers** [comment]
I already had Chrome and android Webview updated. I guess I'll have to stay on r1722 sadly. or is there something else I can try?
