### ISSUE TITLE
Fullscreen on phones with punchhole

### ISSUE THREAD

**Issue by NiceBlue31** [inorichi/tachiyomi#2616]
On webtoons and some manga on S10 theres a large black bar on top. I tried every setting, but nothing worked. I read a lot of content and I'm fearing that screen burn-in might appear soon.
https://i.imgur.com/cyDWPbP.jpg

**Comment by pervertkirito** [comment]
are you on stable build?
full screen should be possible now https://github.com/inorichi/tachiyomi/pull/2595

**Comment by arkon** [comment]
Also, screen burn in only occurs if the display is on for prolonged periods of time with the same content. The black bar wouldn't burn in.

**Comment by NiceBlue31** [comment]
> are you on stable build?
> full screen should be possible now #2595

Yes. Can you tell me what setting should I choose?

**Comment by NiceBlue31** [comment]
> are you on stable build?
> full screen should be possible now #2595

Yes I'm on stable. I tried every setting the black bar continues to appear.

**Comment by fadhlika** [comment]
you need to allow fullscreen for the app on display setting

**Comment by NiceBlue31** [comment]
> you need to allow fullscreen for the app on display setting

Thank you, it worked.
