### ISSUE TITLE
[Bug] Color filter makes overlay buttons invisible

### ISSUE THREAD

**Issue by kiriya-aoi** [inorichi/tachiyomi#2619]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. Tap on a page to open the overlay
2. Tap on the Sun icon for the color filter
3. Set a custom color filter and raise the alpha
4. Raised high enough, overlay items become invisible

### Expected behavior
Overlay should not be affected by color filter

### Actual behavior
Overlay is affected by color filter and becomes invisible with high enough alpha

### Other details
Also appears on r1755

**Comment by arkon** [comment]
I mean, isn't that literally what you would expect from the alpha setting?
