### ISSUE TITLE
[Feature Request] Updates page View options and shortcut

### ISSUE THREAD

**Issue by Kodevex** [inorichi/tachiyomi#2627]
### Why/User Benefit/User Problem
Overall improves the quality of life for the app and user experience. 

### What/Requirements
Allow the user to change viewing size of the icon/font for title updates on the Update page. Also allow them to jump from the Updates page directly into the chapter list for that specific Manga.

**Comment by MerradOklom** [comment]
Are you talking about "Library updates"? If you press the chapter thumbnail it goes to the chapter list.

**Comment by Alykart** [comment]
Strange, maybe you should start to worry about vision and buy a 10-inch tablet for reading manga?

**Comment by Kodevex** [comment]
> Strange, maybe you should start to worry about vision and buy a 10-inch tablet for reading manga?

I use it on a 8.4in tablet. What a trash reply simply because someone might prefer a different size.

**Comment by Alykart** [comment]
> I use it on a 8.4in tablet. What a trash reply simply because someone might prefer a different size.

I do not argue) And 8.4 is also fine =)

**Comment by Alykart** [comment]
Briefly solve your problem by changing the font settings in the android system. Putting a different font.

**Comment by Kodevex** [comment]
> Briefly solve your problem by changing the font settings in the android system. Putting a different font.
> Temporary crutch;)
> https://forums.tomsguide.com/faq/how-do-i-increase-or-decrease-font-size-in-an-android-device.332362/

I originally tried the font size but that didn't effect the font, strangely. The display dpi effects it but also makes everything stupidly larger outside the app.

**Comment by arkon** [comment]
I'll look into it not respecting the system font size setting, but I won't be adding something within the app.

**Comment by arkon** [comment]
I just tried and it does respect the system font size.

**Comment by Kodevex** [comment]
Doesn't on the t705 Tab S.

**Comment by Alykart** [comment]
Reset your device, or get a Root.
