### ISSUE TITLE
[Bug] Tab changing in bottom navbar

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2630]
### Device information
* Tachiyomi version: 0.8.4-1768
* Android version: 9

## Steps to reproduce
1. Go to Library Updates
2. Tap on any manga thumbnail
3. Corresponding manga chapter list opens

### Expected behavior
Bottom navbar should change highlight from Library Updates to Library tab. 

### Actual behavior
The highlight stays on Library Updates.

**Comment by arkon** [comment]
This is actually the intended behavior. To quote @Jays2Kings :

> It is still bound by the root view, going to chapters list doesn't change the icon
> Normally the icons on the bottom should never change
> Because tapping the icon again takes you back to root, which in this case is library updates

It was a bit less obvious before since you couldn't open the drawer from the manga controller view, but it  was technically the same.
