### ISSUE TITLE
[Bug] Color filter

### ISSUE THREAD

**Issue by Hylak** [inorichi/tachiyomi#2631]
### Device information
* Tachiyomi version: r1768 dev
* Android version: 7.1.1

## Steps to reproduce
1. Open a chapter
2. Open color filter menu
3. Pick a filter value (ie 255, 0, 0, 63)
4. Select a very low custom brightness (ie -50)
5. The example image changes to that color
6. Return to the chapter and the chapter isn't colored, just low in brightness

### Expected behavior
Until a few days ago worked as expected, the example image and the actual chapter have the same filter

### Actual behavior
The color filter seems to ignore the color and just lowers the brightness

### Other details
If needed I could upload some images, but it should be easy to test

**Comment by arkon** [comment]
I can't seem to reproduce this. Does it work if you go back to an older version of the app?

**Comment by Hylak** [comment]
Can I do that in the dev version? I only see releases of the stable version.

As I said until like a week ago it worked, I can try a few versions if you tell me how.

**Comment by arkon** [comment]
Yes, you can download them from https://tachiyomi.kanade.eu/

**Comment by Hylak** [comment]
Okay, thanks.

Until r1755 works, on r1757 starts not working.

**Comment by arkon** [comment]
Do you mind including the letter/numbers in the brackets beside those version numbers? I don't have a great way of mapping the versions to commits...

**Comment by Hylak** [comment]
Worked until: 61d2107e
Fails at: 275bd44e

I guess it should be the moving of the filter: https://github.com/inorichi/tachiyomi/commit/beb2d880ea0af17b74da6cd0fdc0e6aaafb75ad9

**Comment by arkon** [comment]
Hmm I still can't reproduce it. What reader settings do you have? Does it happen regardless of what the color filter and brightness are set to?

**Comment by Hylak** [comment]
Default, force portait, bg white, fill screen and automatic. The rest of the options are ON.

The color doesn't seem to matter. In >0 custom brightness I think it works as intended, but if I go way below, like -60 the filter loses color and it's more low brightness with a dim color. 

It doesn't match the result on the example image: https://imgur.com/a/nYBMqkD 
If I lower even more the brightness, the red is almost the same in the chapter and on the example is very red.

**Comment by arkon** [comment]
I still can't actually reproduce this. Does toggling it again make it show up?

**Comment by Hylak** [comment]
Hey, thanks for keep trying,

I tried a lot of combinations and it's always the same. At very low brightness the color filter doesn't work as intended. In the version before changing the filter works whatever filter and brightness parameters I pick.

If you just use the color filter seems to work, the problem it's when you toggle the custom brightness and pick a very low value.

If you need anything just ask and I can try.

**Comment by arkon** [comment]
I was never actually able to reproduce this nor did I get any other similar reports, so I'm going to say your phone was cursed and call it a day. ¯\_(ツ)_/¯
