### ISSUE TITLE
[Bug] Open manga automatically closes

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2634]
### Device information
* Tachiyomi version: r1768
* Android version: ?

## Steps to reproduce
1. Open a manga description
2. Click on anything on the bottom navigation
3. Navigate back to library

### Expected behavior
The manga description should be waiting open.

### Actual behavior
The description screen is closed and you are "kicked" back to library.

### Other details
[YouTube](https://youtu.be/_oMQLEc_L0s) video.

**Comment by arkon** [comment]
This is intentional and follows the Material Design guidelines.

**Comment by arkon** [comment]
Actually, I'll keep this open. I suspect most people won't actually like that behaviour.

**Comment by wopian** [comment]
I thought the guidelines were to keep the state? All of the official examples using bottom navigation explicitly do so.

https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample

Edit: Guidelines state the following:

> On Android: the app navigates to a destination’s top-level screen. Any prior user interactions and temporary screen states are reset, such as scroll position, tab selection, and in-line search.

> On iOS: the destination reflects the user’s prior interaction. If the user previously visited that section of the app, they return to the last screen viewed (with its prior state preserved, if possible). Otherwise, the app navigates to the top-level screen.


But follow it up with:

> Default platform navigation can be overridden when needed to improve the user experience. For example, an Android app that requires frequent switching between sections can preserve each section’s state.

**Comment by CarlosEsco** [comment]
I actually wouldn't want it to keep state

**Comment by hXtreme** [comment]
The app discarding state that was setup by user without user's explicit intent doesn't seems like good design.

If you _really_ don't want to keep state then an alternate solution would be to have all non-top-level  views to occlude the navbar such that the user has to explicitly drop state to navigate to a different section. (I do not like/endorse this solution, but it was the way of doing things in the old navigation system)

**Comment by CarlosEsco** [comment]
when you navigate away from that state  (clicking to go from say a manga to browsing for new manga) the state you left the previous in shouldnt be expected to be kept.

**Comment by hXtreme** [comment]
Facebook definitely keeps the state for one.


So does Google maps (sometimes) and Google search app (switching between discover and collection).


So saying that it shouldn't be expected isn't exactly right.

[FB](https://youtu.be/OMDdL7EgJRE) [Maps](https://youtu.be/E8s-2mDm3PE)

**Comment by CarlosEsco** [comment]
If you want to say it should keep scroll state sure that might be one thing.  Which the fb/maps example does.  But clicking in and leaving the root screen then switching to a different root screen is too much state to keep

**Comment by hXtreme** [comment]
And that's why, Facebook, maps and Google opt for:

> If you really don't want to keep state then an alternate solution would be to have all non-top-level views to occlude the navbar such that the user has to explicitly drop state to navigate to a different section.

For example opening the comments of a post or checking out a restaurant or opening a news article on Google app...


PS: Sorry if this gets posted multiple times, I'm having some issues with GitHub

**Comment by arkon** [comment]
I got [this method of having saved state between tabs](https://gist.github.com/StefMa/5a6d99a8948f0a1b80cfbf5bd4b51c20) working, but it's pretty janky due to it popping/pushing stuff. It also doesn't really save scroll state.

I might just end up hiding the bottom nav when you go into other controllers (e.g. the manga one).

**Comment by arkon** [comment]
Bottom nav is simply hidden when not at a root controller now as of 164da0fd9f0203e811e7528c21adf38d63322836
