### ISSUE TITLE
[Feature Request] UI change request (convert three tabs to two)

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2636]
### Why/User Benefit/User Problem
Concept UI for reference
For simultaneous access of chapters and title detail 

### What/Requirements
UI change requested in future update

New UI would divide the opening page after clicking a title into two parts one would have  title detail and second part would consist the chapters with scrolling option.
Converting current three tabs to two (ie details, chapters, tracker to (detail+chap)& tracker)

Rough layout image attached
![Untitled design](https://user-images.githubusercontent.com/36104528/75489537-6f19ef00-59d8-11ea-986e-4cd71677acca.jpg)

**Comment by CarlosEsco** [comment]
I can understand wanting 1 page for both tabs but this would be a horrible way visually to do it

**Comment by arkon** [comment]
I'll keep it open for the idea in general, but definitely not like that

**Comment by Samk19** [comment]
Can keep it for tablets with bigger layout (option to switch btw the layout would be the best )
![wpid-Photo-2012-05-09-458-PM~2](https://user-images.githubusercontent.com/36104528/75588801-64765d00-5a9f-11ea-82ca-d4f5bd21b175.jpg)
