### ISSUE TITLE
[Bug] Saving page image error

### ISSUE THREAD

**Issue by abubaca4** [inorichi/tachiyomi#2638]
### Device information
* Tachiyomi version: 0.8.4-1781
* Android version: 5.1

## Steps to reproduce
I just try to save page as a image but get the error
![Screenshot_2020-02-28-17-31-45](https://user-images.githubusercontent.com/55701175/75557149-91e7ea00-5a50-11ea-8fe8-ead9a6e70ac0.png)
Share also not work

### Other details
I have some free memory in internal storage (near 1gb)
I not shure that it is not my phone problem, but some versions ago and in stable version it works. /storage/sdcard0/Pictures/Tachiyomi path has 770 permissions.
Chapter saved in sd card.

**Comment by arkon** [comment]
Does this happen for all pages in different manga/from different sources?

**Comment by abubaca4** [comment]
> 
> 
> Does this happen for all pages in different manga/from different sources?

No, only one manga
I find that it's name lenght is 126
I suppose that the best idea is to set limit to filename length and trim name of manga if necessary

**Comment by abubaca4** [comment]
I has an idea
file name limit 255 byte
But for example russian characters stored as utf-8 and take 2 bytes
That is what I read from one linux forum
Can you check it?
<details><summary>Name that cause problem</summary>
Непризнанный школой владыка демонов! – Сильнейший владыка демонов в истории поступает в академию, переродившись своим потомком
</details>
<details><summary>Phone mount comand output</summary>
rootfs / rootfs ro,relatime 0 0

tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
none /acct cgroup rw,relatime,cpuacct 0 0
none /sys/fs/cgroup tmpfs rw,seclabel,relatime,mode=750,gid=1000 0 0
tmpfs /mnt/asec tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/obb tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
none /dev/cpuctl cgroup rw,relatime,cpu 0 0
/dev/block/platform/msm_sdcc.1/by-name/system /system ext4 ro,seclabel,relatime,data=ordered 0 0
/dev/block/platform/msm_sdcc.1/by-name/userdata /data ext4 rw,seclabel,nosuid,nodev,relatime,noauto_da_alloc,data=ordered 0 0
/dev/block/platform/msm_sdcc.1/by-name/cache /cache ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/platform/msm_sdcc.1/by-name/persist /persist ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/platform/msm_sdcc.1/by-name/modem /firmware vfat ro,context=u:object_r:firmware_file:s0,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=cp437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/block/platform/msm_sdcc.1/by-name/sysprop /sysprop ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/platform/msm_sdcc.1/by-name/carrier /carrier ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/fuse /mnt/shell/emulated fuse rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /mnt/shell/emulated/0 fuse rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
DxDrmServerIpc /data/DxDrm/fuse fuse.DxDrmServerIpc rw,nosuid,nodev,relatime,user_id=1013,group_id=1000,allow_other 0 0
/dev/block/vold/179:65 /mnt/media_rw/sdcard1 vfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=cp437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/block/vold/179:65 /mnt/secure/asec vfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=cp437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/fuse /storage/sdcard1 fuse rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
</details>
