### ISSUE TITLE
[Feature Request] Would it be at all possible so have an option to use the old UI layout with the three line menu

### ISSUE THREAD

**Issue by HereticWilson** [inorichi/tachiyomi#2639]
Man I love this app and don't want to hurt anyone's feelings but I just updated the dev version today and I strongly dislike this new UI. I would really love the option to go back tk the three line menu for downloads updates sources etc.

**Comment by arkon** [comment]
No, the technical debt isn't worth it.

Sidebars are also terrible to use in Android 10 and R if you're using gestures.

If it's any consolation, the aim is to eventually have the bottom nav hide on scroll.

**Comment by whiterblue** [comment]
I agree with @HereticWilson on this one. Just updated to last version and feels like a step backward for what it seems just a fix for some android 10 clunkiness. The last UI design had a design that felt already complete. Just my two cents.
