### ISSUE TITLE
Cloudfire issue

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2640]
### Device information
* Tachiyomi version: 0.8.4-
* Android version: 7.1

## Steps to reproduce
1. First step: donwloaded addon of MangaAE
2. clicked on Latest manga but it show cloudfire bypass error java.lang

### Expected behavior
This should happen. the manga should be appear but it show error instead, i cant watch my favorite manga with this issue :( 

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
This should be fixed in the dev builds.

**Comment by mged** [comment]
what do you mean? its not fixed for me

**Comment by arkon** [comment]
It sounds like you're using the stable 0.8.4 build. You can get the dev build via the link in the README or the website.

A stable build with the fix should be coming out within the next few days if you're okay with waiting.
