### ISSUE TITLE
Why there is no good arabic addon?

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2641]
this app is sadly not suitable for arabic users, that quite unfair. the addons you have are either not working or extremly outdated.

there is too many good arabic manga website that are updated and active.

here is the best one you can check it if you think im a laier.

https://gmanga.me/

make a new addon for this website please https://gmanga.me/ it has all manga release very fast and good translate all will like it and it has no cloudfire

**Comment by arkon** [comment]
Wrong repo. It's also dependant on there being developers willing to create and maintain the extensions. The language is generally the largest barrier since none of the main developers can read Arabic.

If you're capable of doing it, I'd encourage you to do so.

**Comment by wopian** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/117
