### ISSUE TITLE
Downloading chapters overwrited

### ISSUE THREAD

**Issue by muniategui** [inorichi/tachiyomi#2646]
**App version:** 8.4

**Android version:** 10 (OxygenOS)

**Issue/Request:** When downloading a manga that has 2 chapters with same name (Example Berserk when done in mangasee) as both have the same name one of them is overwrited (the first one that has been downloaded). In that example as berserk was named chap 1-16 and then chap 1-357 the first 16 chapters where overwritren by the 1-357 chapters despite beeing diferent chapters.

**Steps to reproduce (if applicable)**

 1. Add berserk from mangasee source or any manga from any source that has 2 chapters with same name (usually because they dont have the specific chapter name just the number and some of them are repited but diferent)
 2. Download all the manga
 3. Open the chapters that has the same name and check that are the same.
4. delete them and go to see them online in same source and check they are in fact diferent.

**Other details:**

**Comment by CarlosEsco** [comment]
Update to 8.5
