### ISSUE TITLE
The ability to use the app with out addon

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2647]
is it possibile to use the app with out addon ? or can i merge the addon with the app? i have samsung s2 with custom rom, i know the device is very old, but the app wont run with the addon sperated, 

so is it possibile that i can merge the addon and the app in 1 single apk? or install 2 apks in 1 apk at the same time? isnt this app open soruce :) ? i  guess there is open soruce for the addon of the app, if i can donwload it can i merge the app and the addon and make them 1 app? i want any english addon so i merge it and make the app fully function with out the need to install an addon.

other manga apps or website are either full of ads or not working on my device your app is working but it missing the manga which is caused by the addon,

so what im going to do is

merge the addon with the app, if its possibile.

**Comment by CarlosEsco** [comment]
Not going to happen. The extensions allow for broken sites to be updated with a app update.

**Comment by CarlosEsco** [comment]
You could always build your own version and bring extensions internal yourself

**Comment by mged** [comment]
is that possibile? can i brong the extensions internal myself? 

the question is, if i make it interanl will it install it as an apk or will it work with out installing it?

**Comment by CarlosEsco** [comment]
You would copy the code into the main app then rebuild the app.

**Comment by CarlosEsco** [comment]
You would then just install the one tachiyomi apk

**Comment by mged** [comment]
``` 
CarlosEsco commented 4 hours ago
You would copy the code into the main app then rebuild the app.

@CarlosEsco 
CarlosEsco commented 4 hours ago
You would then just install the one tachiyomi apk```

i do understand this part :), but im asking which `You would copy the code` which code? where can i find it? is it open soruce?

**Comment by CarlosEsco** [comment]
The code is in the extensions repository. You would need to copy each extension you want into the main repository. Make sure they load up then build the app and push the APK to your device

**Comment by mged** [comment]
https://github.com/inorichi/tachiyomi-extensions-lib 
or
https://github.com/inorichi/tachiyomi-extensions

**Comment by CarlosEsco** [comment]
2nd one. Also I'm not gonna walk you through how to do this

**Comment by mged** [comment]
Do not worry, i have done some code like this some months ago, i can do it, but i just asked which one to pick up and merge with the main code :) that is it.

i really do appreciate your time guiding me all the way.
