### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by kuroBi99** [inorichi/tachiyomi#2648]
### Why/User Benefit/User Problem
(It makes the application Great)

### What/Requirements
(It's necessary to make some effort in the downloading option like downloading 4 chapter together(4 connection to download 4 chapter in one time ). Also it will be great if the application allowed to download from range to range by using range option for example from chapter 8-20 being downloaded by just selecting the range .)

**Comment by CarlosEsco** [comment]
Multiple downloads is not supported at this time as it causes potential bans.  Downloading in a range is already possible. Long click the first chapter then long click the last chapter all chapters between will be selected then click download

**Comment by kuroBi99** [comment]
Thanks
