### ISSUE TITLE
Is there a way to force the app to recheck for downloads? 

### ISSUE THREAD

**Issue by HereticWilson** [inorichi/tachiyomi#2649]
I'm using dev version r1807 and I just moved my downloads to an SD card, and changed the download location in settings. I've restarted the app but is there a way to get it to check the new location for the downloads because it isn't recognizing them.

**Comment by arkon** [comment]
Restart your phone, maybe.

**Comment by HereticWilson** [comment]
Nope didn't work

**Comment by HereticWilson** [comment]
Never mind, my phone just screwed up the move. It's displaying them now. Sorry, hope you weren't looking into it.
