### ISSUE TITLE
[Feature Request] Ability to mark all chapters underneath the selected chapter

### ISSUE THREAD

**Issue by Haakon4343** [inorichi/tachiyomi#2650]
### Why/User Benefit/User Problem
It would be nice to be able to mark every chapter under the one that was selected. Now, if you want to mark a huge portion of chapters as read, you would have to either select the ones that are read, or select all and deselect the ones that are not read. This could be a a huge chore if there are several hundred chapters. This would be easier to do if you could select the last chapter you've read, and then have the option to select all characters underneath it. 

### What/Requirements
The button would be added to the same drop down menu as the "mark all" button when selecting chapters. It would mark all the chapters underneath the uppermost selected chapter. After this we could mark the chapters as read or unread as normal.

**Comment by happywillow0** [comment]
Isn't it already there? 

![Screenshot_20200301-131157](https://user-images.githubusercontent.com/45346080/75631152-74d12980-5bbe-11ea-8be9-4a0470500470.png)

**Comment by Haakon4343** [comment]
I was not aware of this. I thought something like that would be in the selection menu
![Screenshot_20200301-191506_Tachiyomi](https://user-images.githubusercontent.com/20688872/75631212-3f91ff00-5bf1-11ea-9360-70a97e5361e6.jpg)
