### ISSUE TITLE
Unable to open pages in Mangasee on Tachiyomi. Even the retry option is not working

### ISSUE THREAD

**Issue by Luffypirates93** [inorichi/tachiyomi#2653]
### Device information
* Tachiyomi version: ?
* Android version: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by bbtora** [comment]
One of Mangasee's image server blew up. It will take a while for Mangasee source to be fixed. In the meantime, try reading on other sources. 

https://mangaseeonline.us/discussion/
