### ISSUE TITLE
[Bug] Massive battery drain from background

### ISSUE THREAD

**Issue by AgileGhost** [inorichi/tachiyomi#2654]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 8.1.0

## Steps to reproduce
Open tachiyomi, then close it so it can run in background

### Expected behavior
The version before didnt use of much battery power in the background and I expected as much with the latest version

### Actual behavior
Heavy use of battery in the background, stopped once I 'forced stopped' it, it used about 80% of my battery in 3 hours with the screen off and the app closed not forced stopped, also made sure there was no other apps that would drain battery while testing. (Using 3000mAH battery, and is still new if you wanted to know) 

Tried this on another device that I had, (some old sony phone) similar results.

Love the app!

**Comment by arkon** [comment]
Does it still happen after it's been force stopped once?

**Comment by History-exe** [comment]
Maybe I have the same problem. But my device performed the battery high use by the web location app after install the tachiyomi.

**Comment by AgileGhost** [comment]
> Does it still happen after it's been force stopped once?

It still happens after force stopping it once. It stops until you reopen it again because it is running in the background again.

**Comment by CiaraMar** [comment]
I've been seeing higher battery usage as well.
Was hard to track down, but only seems to occur during or after usage of this app.

**Comment by lmj0011** [comment]
@AgileGhost 

Since your phone runs on Android Oreo, you should be able to enable battery optimization to prevent this issue https://support.google.com/nexus/answer/7015477

**Comment by joseph619** [comment]
Also update the app (latest is 0.9.2) and give feedback

**Comment by CiaraMar** [comment]
I'd say it's been better since April or May

**Comment by AgileGhost** [comment]
oh, I forgot to close this ages ago XD It seems to be fixed in v0.9.0 and I haven't had a problem since. I'm using the latest version now tho without any problems.
