### ISSUE TITLE
not working with out extension

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2655]
Hello everyone!

guys i explained this already that my device wont work with the app and its addon spilted,

i tried to merge them but failed, its almost impossible if not impossibile to merge them, so i decided to view the older versions and i saw that the older versions was able to read manga with out an addon! that just amazing, the addon is annoying and who would like to install an addon on his app? for me its ok if it work but it does not work,

anyway the older versions mangafox and kissmanga and some other soruces are not working. after reading the soruce code i saw that they are using scraping to get he manga from that soruces, am i wrong? anyway. what i understand so far, the reason that the app is unable to load manga from kissmanga or other soruces is coz the scrape is outdated, i mean the websites changed their desgin or updated their website or any other change happend to them, coz of this the scraping methood is outdated and not working for the website it try to scrape from,

so my question is. if i donwload older version 0.8.2 or any other version that had the manga sources build-in with out installing an addon, then update the scrape method to make it do scrape in correct way, will it be working?

1: donwload an older version soruce code of the app
2: moddify the scrapping
3: when the scrape work, this mean im cabable of runing the app with out an addon.

is this possiible? is it harder than merging the app and the addon?

**Comment by CarlosEsco** [comment]
yes but you then have to maintain the app yourself.  The reason the extensions were moved externally is because a new app version is needed every time a source breaks.

**Comment by mged** [comment]
what yes?

i did not get your answr, ofc i have to handle the app my self, 

but what about my questions? is this process even possibile? will it work by just updating the scraper? i hope to get a good nice from you sir! :heart:

**Comment by arkon** [comment]
> but what about my questions? is this process even possibile?

Yes, considering you can see yourself that older versions were exactly like that.

> will it work by just updating the scraper?

Maybe. You probably don't want to use the older versions as a base since they don't handle Cloudflare well.

Realistically, it'd be easier to just buy a cheap phone than do this.

**Comment by wopian** [comment]
Replacing 0.8.2's parsings in Kissmanga.kt with the current code for parsing Kissmanga in the extension may work. Although it will probably require updating the Cloudflare Client too among other things to get it to work correctly.

https://github.com/inorichi/tachiyomi-extensions/blob/29d1d99e58c072bde2a65e084e865bcde7dd38dc/src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt

https://github.com/inorichi/tachiyomi/blob/v0.8.2/app/src/main/java/eu/kanade/tachiyomi/source/online/english/Kissmanga.kt

**Comment by mged** [comment]
@arkon 

Maybe. You probably don't want to use the older versions as a base since they don't handle Cloudflare well.

i understand that the website with cloudfire will be a bit harder to scrape from, but what about website that does not use cloudfire? there is website with no cloudfire protection. will updating the scrapper to a website that does not use cloudfire make it function? is this a good idea?
i really cant afford buying a new device :C

**Comment by CarlosEsco** [comment]
Chat on discord if you so inclined.  This is not the place to continue the chat

**Comment by arkon** [comment]
> will updating the scrapper to a website that does not use cloudfire make it function?

Again, maybe. There's only really one way to find out, which is for you to try it.

**Comment by mged** [comment]
@wopian

hello there, kissmanga has cloudfire enabled, 
anyway i tried to serach in the soruce codes for the addon called manga3asq, but i cant find it, whty its not open soruce like the other extensions? :C

may u link it to me?
`package eu.kanade.tachiyomi.extension.all.madara;

import java.text.SimpleDateFormat;
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;

@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\u0018\u00002\u00020\u0001B\u0005¢\u0006\u0002\u0010\u0002¨\u0006\u0003"}, d2 = {"Leu/kanade/tachiyomi/extension/all/madara/Manga3asq;", "Leu/kanade/tachiyomi/extension/all/madara/Madara;", "()V", "tachiyomi-all.madara-v1.2.57_release"}, k = 1, mv = {1, 1, 16})
/* compiled from: MadaraFactory.kt */
public final class Manga3asq extends Madara {
    public Manga3asq() {
        super("مانجا العاشق", "https://3asq.org", "ar", (SimpleDateFormat) null, 8, (DefaultConstructorMarker) null);
    }
}`
which is not like this

https://github.com/inorichi/tachiyomi-extensions/blob/29d1d99e58c072bde2a65e084e865bcde7dd38dc/src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt

where i can find the soruce code for manga3asq and hentai manga

**Comment by CarlosEsco** [comment]
@mged  stop commenting on the issue.  Go on discord chat to talk with whomever wants to discuss this
