### ISSUE TITLE
Same error nothing changed

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2656]
you released a new version and said it fixed the issue but its still there, on Mangaae (arabic manga https://mangaae.com )

https://i.ibb.co/Gk5BNWn/Capture.png

**Comment by arkon** [comment]
Wrong repo, read and follow the issue templates please.

**Comment by mged** [comment]
what u mean? there is nothing wrong.

all versions of tachiyomi can not open managaae ( https://mangaae.com ) if this is wrong repo to ask to fix the MAIN app, then shall i ask others website people to fix your code? i dont get X_X

**Comment by arkon** [comment]
This is an extension issue, not an issue with the main app.

**Comment by wopian** [comment]
https://github.com/inorichi/tachiyomi-extensions

**Comment by mged** [comment]
WOPIAN thank you so much for helping me to fix the latest issue i got, it work on mangahere but on others it does not work, may i contacnt u? what is your discord or facebook :)
