### ISSUE TITLE
[Bug] Impossible to read scans on japscan extension

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [inorichi/tachiyomi#2657]
### Device information
* Tachiyomi version: r1810 (d9934ad8) 
* Android version: 10
* Phone : Huawei mate 20 pro

## Steps to reproduce
1. Install japscan extension 
2. go to catalog
3. go to recent 
4. choose a random manga 😅
5. choose a random chapiter
6. wait download load
7. the rety buttom ia visible
8. click on retry many times do you want

### Expected behavior
Images of scan is visible and readible. 

### Actual behavior
Impossible to read scans

I  uninstalled and reinstalled extension but nothing changes. 
I use developpement version of tachiyomi, but i tried with stable version and the same problem is visible... i asked to my friend with an asus phone on last android version and he has the same problem. 

### Other details
i have to check website of japscan and i can watch and read scan.

i tried with mangakawaii extension and i can read scans.

**Comment by arkon** [comment]
There's open issues in the extensions repo. Somebody is looking at it.
