### ISSUE TITLE
[Feature Request] Better download compression/size or data saver mode

### ISSUE THREAD

**Issue by Devsterman12** [inorichi/tachiyomi#2658]
### Why/User Benefit/User Problem
Having an option for low data usage mode or lower image quality via compression would benefit users with limited WiFi or mobiledata

### What/Requirements
It could work by having options similar to the following.
High detail: Raw download from the source but with a larger size.
Low detail: Lower image quality with the benefit of a smaller size.
Hide catalogue images: Turning off catalogue images when browsing and have the name as text.

**Comment by arkon** [comment]
This is impossible at a global level since we don't vend the source data and don't intend to have any sort of proxy server to do so. 

If certain sources have the option, that could be added to their extensions.

**Comment by arkon** [comment]
Can you open a separate issue for the hiding catalogue images suggestion? That could be an option for the list view mode.
