### ISSUE TITLE
[Bug] Questionable Content downloads never show up in Library Updates

### ISSUE THREAD

**Issue by Fry-kun** [inorichi/tachiyomi#2660]
### Device information
* Tachiyomi version: 0.8.4
* Android version: Q

## Steps to reproduce
1. Install Questionable Content extension, sign up for comic (there's just one)
2. wait for auto update - it downloads and leaves a notice that there's a new chapter
3. Go to Library Updates - it doesn't show QC at all

### Expected behavior
Downloaded chapter should show up

### Actual behavior
Didn't show up

### Other details
Not sure where to file extension bugs, maybe that should be made clearer.

**Comment by joseph619** [comment]
You need to add it to My library first. Downloading doesn't add to My library automatically. 

Also update your app.

**Comment by Fry-kun** [comment]
It's already in My Library, I forgot to mention that

I haven't seen update dialog in forever, and don't see any obvious option to update. Why did the app leave the store/fdroid repo?

**Comment by joseph619** [comment]
Because F-Droid is not the official place, Github is. Backup your manga, uninstall app and reinstall from Github again. Then restore backup.

Also, if you need support, go to Discord server. This is not a bug.

**Comment by Fry-kun** [comment]
To clarify, are you saying the extension bug is not a bug?

**Comment by joseph619** [comment]
This is not the Extensions repo

Post here

https://github.com/inorichi/tachiyomi-extensions/issues

**Comment by Fry-kun** [comment]
Thanks, filed
