### ISSUE TITLE
[Feature Request] New Chapter's Download Should Always be put on Queue

### ISSUE THREAD

**Issue by dimaTrinh** [inorichi/tachiyomi#2664]
### Why/User Benefit/User Problem
Right now, there is the option for new manga chapters to be download automatically. I assume that there is a check when the library refreshes to put manga chapters on the download queue. 
However, it seems that if I set the setting for the app to only download a new chapter using WiFi and the library is refreshed using Data, then the manga chapters are not going to be downloaded due to the WiFi setting, but they are also not going to be queued either. Hence, these chapters are never downloaded

### What/Requirements
I think that all new chapters' download should be put on the queue if the user is not on WiFi, and the queue will only start downloading when the user is on WiFi again (or whatever internet setting they set in the app)

**Comment by arkon** [comment]
Isn't that already what happens? (I just tested it.)

**Comment by dimaTrinh** [comment]
> Isn't that already what happens? (I just tested it.)

I don't think that's what happening for me. Could you tell me how you tested it?

**Comment by arkon** [comment]
1. Ensure download over Wi-Fi only setting is turned on
1. Ensure default category as auto downloads enabled
1. Turn off Wi-Fi (i.e. on data)
1. Add a manga to my default category
1. Refresh category
1. Note that it found new chapters and that they're queued
1. Turn on Wi-Fi
1. Note that they start downloading

**Comment by dimaTrinh** [comment]
> 1. Ensure download over Wi-Fi only setting is turned on
> 2. Ensure default category as auto downloads enabled
> 3. Turn off Wi-Fi (i.e. on data)
> 4. Add a manga to my default category
> 5. Refresh category
> 6. Note that it found new chapters and that they're queued
> 7. Turn on Wi-Fi
> 8. Note that they start downloading

Thank you for the response. What is happening for me is that after step 5, sometimes the app seems to show me there are new chapters, sometimes the app does not. In both cases, the new chapters are not queued.

**Comment by CarlosEsco** [comment]
@dimaTrinh  are you clicking into the manga when you favorite it?  If so at that point the chapters aren't "new" they've been seen.  For no. 4 it should be long press to add manga to library.    By doing this the app hasnt "seen" the chapters from the website yet.  so the swipe refresh on 5 will always think they are new chapters

**Comment by arkon** [comment]
Yeah, the time between 4 and 5 is really short and it's more of a workaround for me to test for new chapters. What @CarlosEsco said is correct.
