### ISSUE TITLE
[Feature Request] Update all button for extensions

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2665]
### Why/User Benefit/User Problem
As number of installed extensions increase, it becomes more and more tedious to manually update extensions.

### What/Requirements
Whenever there's more than one extension with updates available a button should appear towards the top of the Extensions page that lets you update all of them in one click.

**Comment by MCAxiaz** [comment]
Doesn't seem very useful if you still need to accept the install prompt + wait for the install to finish one by one. At most you just save a few clicks but it doesn't really help speed the process up.

**Comment by hXtreme** [comment]
installation can happen simultaneously (at least on my phone it does) which speeds up the process.

as for the install prompt, the accept button is always at the same spot on the screen making it much more friendly to use by eliminating the constant need to move from Update button to accept button at a different spot and then move to a completely different spot to hit the next update button.

**Comment by arkon** [comment]
I wouldn't want it to sequentially trigger the prompts automatically in case the user wants to do something else midway through.

It'll also be confusing if some extensions are slow to download.

At best, I'd add something to download them all in parallel, but installing would still be manually done.

**Comment by FrozenSCV** [comment]
I know this is a huge pet peeve of mine when going to install updates to various extensions, surely I'm not the only one. So any way this could be done with a single button press would be hugely benefitial as far as I'm concerned.

**Comment by arkon** [comment]
It's been mentioned in similar issues, but it's impossible without root since it's a security feature of the OS, and we're also not interested in supporting root-specific functionality.

**Comment by hXtreme** [comment]
Just making a clarification, this feature request as I envision it doesn't require root.

All I want is a single button that is equivalent to the following:

for each extension with updates: `this.updateButton.onClick()`

**Comment by arkon** [comment]
No tangible improvements are going to happen to the extension install flow for 0.x.
