### ISSUE TITLE
[Feature Request] Migrate to Local

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2666]
### User Benefit
The ability to easily get an entire manga on local storage. (Either for offline reading or archiving or later moving to self hosted server)

### What/Requirements
Migrating to local should do the following:
1. Create a local manga with same name & other metadata as original.
2. Download all chapters from initial source to the directory corresponding to the new local manga.
3. Copy/Move over (user) selected tracking data to the local version of the manga.

**Note:** This is not the same request as the other similarly named issue.

**Comment by pervertkirito** [comment]
pretty much same as my feature request here #2289

**Comment by hXtreme** [comment]
@pervertkirito I'd disagree as that seem to deal with salvaging orphaned manga.

**Comment by arkon** [comment]
They sound the same to me...
