### ISSUE TITLE
[Bug] NewToki - Failed to bypass CloudFlare

### ISSUE THREAD

**Issue by taynara2** [inorichi/tachiyomi#2669]
### Device information
* Tachiyomi version: 0.8.5 stable
* Android version: 9 (February 5, security patch)

## Steps to reproduce
1. First step
Download NewToki extension
2. Second step
Try to opening NewToki in catalogues (both sites)

### Expected behavior
This should happen.
Open like any other catalogue.
### Actual behavior
This happened instead.
java.io.IOException: Failed to bypass CloudFlare!
![Screenshot_20200305-124449](https://user-images.githubusercontent.com/52222614/75999712-67c77980-5ee1-11ea-9b39-7f731e1b3d94.png)

### Other details
Additional details and attachments.

It opens on WebView.

![Screenshot_20200305-125809](https://user-images.githubusercontent.com/52222614/75999978-c2f96c00-5ee1-11ea-8844-43b200e95762.png)

**Comment by happywillow0** [comment]
Thanks for providing your Tachi and System version numbers. 

Have you tried seeing if you have any updates to Android Webview and Google Chrome in the play store?

**Comment by taynara2** [comment]
Your welcome, if any more info is needed just say so.

Well the Android WebView was always disabled and the Chrome is up to date.

Android WebView (version: 74.0.3729.136)

![Screenshot_20200305-163502](https://user-images.githubusercontent.com/52222614/76018973-c3086480-5eff-11ea-9f4a-6923477c2007.png)

![Screenshot_20200305-163514](https://user-images.githubusercontent.com/52222614/76018988-c996dc00-5eff-11ea-9ee4-c2ec39fce23c.png)

Chrome (version: 80.0.3987.132)

![Screenshot_20200305-163937](https://user-images.githubusercontent.com/52222614/76019449-80935780-5f00-11ea-8804-ebc2af8695d4.png)

![Screenshot_20200305-163944](https://user-images.githubusercontent.com/52222614/76019471-86893880-5f00-11ea-895a-6b7aecd30351.png)


But the option to enable the Android WebView is not available, and I don't know why...

**Comment by taynara2** [comment]
It's working again... Sorry for wasting your time.

![Screenshot_20200306-020515](https://user-images.githubusercontent.com/52222614/76054264-f7efd800-5f4e-11ea-978e-6b9b1ff5bff7.png)
