### ISSUE TITLE
[Feature Request] Display manga title in download queue

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#267]
Adding the manga title alongside the chapter name would make batch downloading manga much easier to keep track of - as most manga don't have titles so you end up being lost in a sea of "Chapter 00 - Read Online"

![](http://i.imgur.com/SW7FYpR.png)

**Comment by ikargbo** [comment]
I think that the manga pages are too close on webtoon viewer mode a small border could be used
