### ISSUE TITLE
[Feature Request] Add Start and End date on MAL support

### ISSUE THREAD

**Issue by ITALIA195** [inorichi/tachiyomi#2670]
### Why/User Benefit/User Problem
Right now in order to set the start/end date of any anime/manga you need to open MAL on a browser and update it manually. It would be awesome to be able to edit the advanced details in the app. 

### What/Requirements
This can be achieved by either adding the 2 fields in the app details or by adding a "advanced settings" button. (I'd prefer the former)

**Comment by wopian** [comment]
Also for Kitsu please :)

**Comment by taynara2** [comment]
Do it for AniList too please!! c:

**Comment by taynara2** [comment]
For AniList too please. c:

**Comment by ITALIA195** [comment]
Also #315 but considering rereading and such it's relatively hard to check if its the first time reading a chapter. I think that those 2 fields should be added and then maybe you could look into add an automatic option.

**Comment by ITALIA195** [comment]
And it's a duplicate of #1358 too... my bad :/
Anyways this means this is actually a functionality a lot of people want.
Would look into contributing myself but I don't really know how to setup an android environment with kotlin.

**Comment by bbtora** [comment]
> For AniList too please. c:

Anilist does it automatically due to their API.

That reminds me, is the app using the new MAL API or still on the workaround code?

**Comment by arkon** [comment]
Workaround. Is the MAL API still in preview?

**Comment by bbtora** [comment]
I'm not sure exactly, might be still in open beta.
This was the last update (Feb 13)
> Public API Release
We are still some months away from a public API release. After considering and incorporating the feedback of the closed/open beta participants, we hope to return to you with news of a better and public API in early 2020.
