### ISSUE TITLE
[Feature Request] Add Algorithms for improving image quality

### ISSUE THREAD

**Issue by emanrdesu** [inorichi/tachiyomi#2673]
### Why/User Benefit/User Problem
Having the option to make blurry images more sharp in quality would be god send. 

### What/Requirements
I know it is possible as I've seen somebody do it before, I just don't remember if they posted a github link for it, but essentially it would make the image qualities sharper and nicer to look at, I wish I could post a screenshot but I saw this year's ago in an anonymous forum.

**Comment by CarlosEsco** [comment]
something like this.
https://github.com/alexjc/neural-enhance

and no this is not an imaging processing app
