### ISSUE TITLE
[Feature Request] Gestures for navigating a nav bar

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#2675]
I beg to add gestures for quickly navigation across sections.
How is it done in google play
![google play](https://user-images.githubusercontent.com/35057681/76139456-d1768d80-6071-11ea-99a2-a2acaa2db479.gif)
and firefox
![firefox](https://user-images.githubusercontent.com/35057681/76139460-da675f00-6071-11ea-98b4-4dc7a7594cc1.gif)

**Comment by CarlosEsco** [comment]
That doesn't have bottom navigation

**Comment by arkon** [comment]
This already applies when the screen has tabs, exactly like the Play Store.
