### ISSUE TITLE
[Enhancement] speed up application start up

### ISSUE THREAD

**Issue by raslmenea** [inorichi/tachiyomi#2678]

**Comment by CarlosEsco** [comment]
This is dependent on your library size

**Comment by raslmenea** [comment]
i don't really have that much of mangas in my library (less than 10) and i don't use sd card and have plenty of free space.

**Comment by arkon** [comment]
How slow is it? What's your device?

**Comment by raslmenea** [comment]
it takes 2 seconds to start the app (dev 1857), while in version 0.8.4 it takes less than a second to start the app.
tested with y9 prime

**Comment by likehelly** [comment]
it takes one second longer? 

is that really an issue.

**Comment by arkon** [comment]
Duplicate of #2676
