### ISSUE TITLE
Resuming chapters downloads read pages

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#268]
When resuming a chapter you've partially read (e.g read up to page 26 of 46) after the chapter cache has been overwritten by other chapters, the app proceeds to download all the pages again from page 1.

For the user, this results in them just starring at the spinner for ages until it finally starts downloading the page you were on...after wasting several dozen MBs downloading pages you'll never see.

Version: r661

**Comment by Bloodwork** [comment]
This one is particulary bad on Bato.to which is slower than other sources by default. Sometimes it takes up to two minutes to resume at the end of a chapter for manga with particulary large scan sizes.
