### ISSUE TITLE
[Bug] Local manga won't display any cover

### ISSUE THREAD

**Issue by Inu90** [inorichi/tachiyomi#2681]
### Device information
* Tachiyomi version: r1865
* Android version: 9 on MIUI 11

## Steps to reproduce
Have tried both long pressing any of the pics from "within" the manga and the edit button on the library list.

### Expected behavior
Cover image changes to selected pic.

### Actual behavior
Cover stays black, both on the library list and info screen.

### Other details
Only began happening after I switched to dev builds, was working fine on stable, on same Android/MIUI version. Have already tried the library metadata refresh to no avail.
Online manga get their covers working as normal.

**Comment by happywillow0** [comment]
Have you tried:
1. Unbookmark the manga / remove it from your library (Optionally move the manga out of the local manga folder.
2. Clear Database in advanced settings
3. Re-add the manga from local manga

This would be a method to fully remove the manga from the internal database so it can be added with a fresh cover.

**Comment by arkon** [comment]
Consolidating to #932
