### ISSUE TITLE
[Feature Request] Show Number of Chapters Available when searching Catalogue

### ISSUE THREAD

**Issue by ss7vegetto** [inorichi/tachiyomi#2688]
### Why/User Benefit/User Problem
When searching for a manga title in the "Catalogue" section(Also the migrate function), it would be very helpful to know how many chapters each source has of the manga.  Having to migrate from one source to another is very cumbersome when you do not know which source is up to date with the manga you want add.  Currently, you would have to tap and hold if you're migrating sources, then go to chapter to check what number chapter they're on and such.

### What/Requirements
Just a number on the thumbnail to show how many total chapters are available for the source would suffice.  Alternatively, if the migration function could match chapter total or latest chapter number versus the release date as potential migration sources to narrow down that would make things even easier.

**Comment by CarlosEsco** [comment]
Not gonna happen. 
for Most sources its 1 network call to get all the manga and N number of calls to get the cover image.
This would required an additional network call per a manga.  SO now you are looking at 2N + 1 network calls.
