### ISSUE TITLE
[Bug] Tachiyomi doesn't recognize local manga

### ISSUE THREAD

**Issue by Bladeusz020** [inorichi/tachiyomi#2691]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 7.0

## Steps to reproduce
1. Created local folder in tachiyomi app
2. Created manga folder and chapter folder with images, for example:
Phone/Internal storage/Tachiyomi/local/Black Clover/ch168

### Expected behavior
The manga should show up in the local catalogue

### Actual behavior

Nothing appears in the local catalogue, the application throws the message "No results found"

### Other details
I tried to add local sources through the SD card but it didn't change anything, the application still doesn't see the added manga. I also tried to use the .zip format but that also changed nothing.

**Comment by CarlosEsco** [comment]
https://tachiyomi.org/help/guides/reading-local-manga/

if you still have issues go on the discord channel

Also updated to latest stable 0.8.6

**Comment by arkon** [comment]
0.8.5 is the latest stable version.

**Comment by CarlosEsco** [comment]
whoops haha
