### ISSUE TITLE
[Bug] Restoring backup crashes app

### ISSUE THREAD

**Issue by kaosjr** [inorichi/tachiyomi#2692]
### Device information
* Tachiyomi version: r1887
* Android version: 7.0

## Steps to reproduce
1. Have a backup file automatically created by tachiyomi
2. Try to restore this backup

### Expected behavior
The restore should succeed and restore the library.

### Actual behavior
After displaying a progress bar with 0/100 completed, the app crashes to the launcher.

### Other details
I've attached the backup file as well.[Here's a Gdrive link.](https://drive.google.com/file/d/1CNnNbx0nbr_H15UB9NiHvKzVgsO8nWmf/view?usp=drivesdk) 
I tried updating from 1830 to 1887, but for whatever reason my library got wiped in the transition. I went to restore an automatic backup and instead the app crashed.
I also tried rolling back to 1830 and restoring but the same bug persisted.
Sources also seem to be semibroken on this version, I'm having trouble loading anything.

**Comment by kaosjr** [comment]
Strangely I also appear to be crashing the app whenever the downloads button is clicked. Dunno why that happens but it might be related?
I also tried uninstalling and reinstalling the app, no behaviour change. I even tried installing r1719 (the first version I used), and it had the same issues.

**Comment by kaosjr** [comment]
Ok, I tried installing the latest stable release (0.8.5), which appears to be built on a much older version, and it successfully restored the backup. Now I'm left scratching my head, since I want to use the dev version but it appears to be very broken...

**Comment by arkon** [comment]
I'd need actual logs to debug this since nobody seems to have encountered the same thing.

Did you try installing the version but then clearing the app's storage/cache via settings first?

**Comment by arkon** [comment]
Do you possibly not have storage permissions granted too?

**Comment by kaosjr** [comment]
Storage permissions are granted. I even tried reinstalling the app outright after clearing storage/cache didn't seem to make a difference, but that didn't help either.
Where can I get these logs?

**Comment by kaosjr** [comment]
Well that's fun. Turns out trying to launch the dev version while the stable release is installed makes the dev version immediately crash. I'm wondering at this point if it might just be my old tablet needing a factory reset one of these days.

**Comment by arkon** [comment]
Google around for guides about "logcat". There should be some apps that do it, or using your PC.

You should be able to have both stable and dev installed without any issues.

**Comment by alittlebitofit** [comment]
Heĺlo, I am trying to restore from my backup `.json` file but it opens up some kind of music player app.

Why does that happen?
And how can I restore?

The ss is of the app that opens up from when I click on `Restore backup`

![Screenshot_2020-04-07-23-25-21](https://user-images.githubusercontent.com/42311431/78703232-5bc44280-78f9-11ea-81f4-25383ba138b9.png)

**Comment by arkon** [comment]
@alittlebitofit Install a proper file manager such as Solid Explorer.

**Comment by kaosjr** [comment]
> Google around for guides about "logcat". There should be some apps that do it, or using your PC.
> 
> You should be able to have both stable and dev installed without any issues.

I ended up factory resetting my tablet and finding out that the SD card I was using was having issues. That explains a lot.
