### ISSUE TITLE
Rebranding a light theme / icons and search bar in a library

### ISSUE THREAD

**Issue by Gena1005** [inorichi/tachiyomi#2697]
### Why/User Benefit/User Problem:
 It's time to think about the new Tachiyomi design.
### What/Requirements:

-  1.Light theme 2.Black-and-white or "Color" icons in the "Settings", "Bottom Navigation Bar" and, if possible, in other sections.  3.A new view of the "Search String" in the starting page

.

#![Screenshot_20200313-011426](https://user-images.githubusercontent.com/62114135/76554337-4d386600-64c8-11ea-97e2-735a5edc0d88.jpg)
![Screenshot_20200313-011445](https://user-images.githubusercontent.com/62114135/76554342-4f9ac000-64c8-11ea-988f-ff3e1f69d87c.jpg)
#

**Comment by CarlosEsco** [comment]
1.  Why did you bold everything
2.  Change the title to what you are requesting
3.  We don't need your background and history.  Just ask what you want  plain and simple
  

  I believe it was

-  a white theme
-  colored icons for the selected bottom navigation page (all different colors is a no go as its against material design 2)
-  a new search page?  or search string?

**Comment by joseph619** [comment]
He wants a search box similar to that of Play store I think

**Comment by Gena1005** [comment]
> 1.Why did you bold everything
 Hello.  There were extra icons of various social services.  networks, that's why I crossed out this part, because I considered them superfluous and distracting from the main topic ...

> Okay

> We don't need your background and history. Just ask what you want plain and simple
I apologize in advance, for the first time in "Github", so I don’t know about all the subtleties and nuances, I’ll take a note and will not go into details in the future :)
-|-|-|-|-|-|-|

> a white theme
Yes, right

> colored icons for the selected bottom navigation page (all different colors is a no go as its against material design 2)
 Not only in the bottom navigation page, but in general in all sections of the application, either "multi-colored" icons, or simply flat "black and white" icons from the "Material Theme".  Of course, in the "Outline" version ...

> a new search page? or search string?
The search bar is located on the start screen in the "Library" section.  Above, dear: " @joseph619" correctly noticed, the same as in the Google Play store :)

**Comment by CarlosEsco** [comment]
Can you edit your original post to match your request

**Comment by Gena1005** [comment]
Of course, I can do it now)

**Comment by CarlosEsco** [comment]
Are you on dev version or stable?  Dev has bottom bar currently

**Comment by Gena1005** [comment]
On the "Dev".  And I will not leave him for the same reason.

**Comment by Soitora** [comment]
Navbar will be added to Stable in due time, pretty much everything on Dev will. It's a matter of implementing some final things to be included in the 0.9.0 release.

**Comment by Gena1005** [comment]
It's nice, now I am calm, knowing that in respected developers, there are desires for the implementation of these innovations, I wish everyone good luck in all endeavors !!!

**Comment by arkon** [comment]
This issue is still really unclear as to what it's asking, but a white theme was added to dev.
