### ISSUE TITLE
[UI Bug] White text Snackbars dark theme

### ISSUE THREAD

**Issue by DarKCroX** [inorichi/tachiyomi#2699]
### Device information
* Tachiyomi version: 1890
* Android version: 10

## Steps to reproduce
1. use dark theme
2. browse any dead source

### Expected behavior
Snackbars text color should be black

### Actual behavior
Snackbars text in white

![Screenshot_20200313-043122](https://user-images.githubusercontent.com/11861402/76566231-4a993900-64e7-11ea-9bca-83ec981cfa23.png)

**Comment by joseph619** [comment]
This is for any snackbar message or just the ones with HTTP errors?

**Comment by DarKCroX** [comment]
any snackbar i guess
![Screenshot_20200313-050532](https://user-images.githubusercontent.com/11861402/76566744-5f2a0100-64e8-11ea-9c22-d6496fbf0f5e.png)

**Comment by arkon** [comment]
Light snackbar in dark themes is normal. Changed it to be black only in AMOLED theme.

**Comment by arkon** [comment]
![](https://cdn.discordapp.com/attachments/349466829212876813/689093226019553301/Screenshot_20200316-204914.png)

Still buggy
