### ISSUE TITLE
Feature Request: view for downloaded chapters

### ISSUE THREAD

**Issue by Iliansic** [inorichi/tachiyomi#27]
Could you please add view option, where we can see all series with currently downloaded chapters, like in Manga Rock, cause it's kinda getting hard to track them all after some time.

**Comment by j2ghz** [comment]
Feature proposal: In the future this could be replaced by configurable and saveable (multiple presets) filters?

Filter: Next chapter downloaded, All remainig chapters downloaded, MAL status finished/publishing
Sort: Date updated, Date last read, Remaining chapters, % Completed
