### ISSUE TITLE
[Bug] Not all chapters from Mangadex are showing.

### ISSUE THREAD

**Issue by kingwolf13** [inorichi/tachiyomi#2700]
On Mangadex's site there are several manga with chapters almost a year back that are not being updated on the app. Such as The Earl's Daughter was Suddenly Employed as the Crown Prince's Fiancée, Martial Peak, and Yong Heng Zhi Zun to name a few. There's no telling how many more there are like this.

**Comment by CarlosEsco** [comment]
Wrong repository

**Comment by CarlosEsco** [comment]
To add to this I have no issue with the first manga I selected from your list martial peak.  Which means you are either
1.  Using the incorrect language of the extension on accident
2.  Some how your chapters are in a weird state that I assume swipe refresh is not fixing.  Remove those manga from your library.  Clear database in advanced settings.  Then search for one of those manga again and you should be good
