### ISSUE TITLE
[Bug] Pages are very slow to load

### ISSUE THREAD

**Issue by Murasakinoe** [inorichi/tachiyomi#2706]
### Device information
* Tachiyomi version: 0.9.81
* Android version: 10

I recently switched over to Tachiyomi from MangaRock and have been loving every second of it. So far, the only issue I've had is with the load times while reading.

While reading, I would have to wait between each page, from anywhere around a couple of seconds to a minute. This occurs on pretty much all the manga I've read, and on all the extensions I use. I didn't really see my network play an issue as regardless of whether I'm using wifi or data (which for me data is much slower) its the same issue. I've tried a couple of fixes but to no avail. Restarting the app, clearing any and all the caches, reinstall, you name it. Although I can definitely say that the image quality is far superior to any source I've used thus far, I would definitely sacrifice a bit of that for a smoother reading experience. 

I couldn't find a direct solution that I haven't tried already, and all the other posted issues with Tachiyomi being "slow" are in regards to library load times which I have no problem of.

**Comment by arkon** [comment]
Generally if the website is slow, the app will be just as slow. Have you tried browsing those websites on your phone too? Is it faster there?

**Comment by MerradOklom** [comment]
Version 0.9.81? Sounds like you're using TachiyomiJ2K, and you should report this in Jay's repository:
https://github.com/Jays2Kings/tachiyomiJ2K
