### ISSUE TITLE
[Feature Request] New Filter Option: "Last Added".

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#2708]
### Why/User Benefit/User Problem
This would allow the users to sort their manga based on **when** they added them.

### What/Requirements
Using this filter would sort all the manga based on which manga was added to library *last*, and before that, and before that, and so on. This could work inversely too, like which manga was added *first*, and what after that, and after that, and so on.

**Comment by arkon** [comment]
Duplicate of #1287
