### ISSUE TITLE
many chapters 'error' when downloading

### ISSUE THREAD

**Issue by aeli2** [inorichi/tachiyomi#271]
Version: 664 

This is related to #264, but now that i try it with the newest version i am getting tons of errors when downloading instead.  When i get to those pages in the reader, it is just white, with no 'error' or 'retry' buttons
On the file manager there are no 0.10kb files, they just dont have those pages

for what its worth, the 0.10kb images when opened in notepad contain this text:

```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

```

http://imgur.com/EiCcmYm
http://imgur.com/PbHUsp6

**Comment by aeli2** [comment]
im noticing this a lot more on webtoons that have very large pages.  perhaps it needs to keep retrying these pages until they succeed?

**Comment by inorichi** [comment]
Are you sure this is related to #264 and not #262? Webtoons have some problems when decoding big images.

I just tried downloading and it works fine, it's already retrying to download pages.

**Comment by inorichi** [comment]
I was able to reproduce incomplete downloads after the changes for #264.

By giving some time before trying again it may complete them now. But they'll fail sometimes (and I'm not going to retry requests infinitely) and you'll have to add them to the queue again.
