### ISSUE TITLE
[UI Bug] Buttons unreadable in Extension view

### ISSUE THREAD

**Issue by StarWolf3000** [inorichi/tachiyomi#2711]
### Device information
* Tachiyomi version: r1913 (1ebcafb2)
* Android version: 6.0

## Steps to reproduce
1. Open "More" from bottom nav.
2. Select "Extensions".

### Expected behavior
Actions for extensions (on the right side of the screen) shouls be readable.

### Actual behavior
Only the upper half of the action (Details, Install) is readable, the lower portion is cut off.

### Other details
![Screenshot_20200315-191631](https://user-images.githubusercontent.com/787808/76707819-bb607100-66f2-11ea-8572-740985f7f57f.png)

**Comment by arkon** [comment]
Is this only in landscape?

**Comment by StarWolf3000** [comment]
Nope. Both in landscape and portrait mode. Also in light theme too and in other languages from my testing (shown is German).

**Comment by arkon** [comment]
Interesting. Is your system font/text or display size increased?

**Comment by StarWolf3000** [comment]
It is not (it's set to Normal). I checked if its readable with setting my System font size smaller, but Tachiyomi doesn't seem affected by the change, everything is the same size as with Normal.

**Comment by arkon** [comment]
Should be fixed via 3f4140900d2b0a437ed6985d98502c1f5b720604. Let me know if it's still happening.
