### ISSUE TITLE
[Feature request]Advanced bookmark

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi#2712]
I think it will be good if bookmarks get colors/and numbers(for 2 users for example).Also the floatting button would play selected bookmark

**Comment by Mitia99** [comment]
![Screenshot_20200315_212821](https://user-images.githubusercontent.com/56766778/76708024-db009500-6704-11ea-8288-73dd5112f3b5.jpg)

**Comment by arkon** [comment]
There's no plans to really improve on the bookmarking system to this extent.
