### ISSUE TITLE
Weblate plural translation

### ISSUE THREAD

**Issue by Lyaiya** [inorichi/tachiyomi#2714]
I translate the language in Weblate, but I found a error at plural translation.
After I translated Chinese plural string in Weblate, it should be <item quantity="other">, not <item quantity="one"> in string.xml (zh-rCN).
Because of the Language Plural Rules #zh, plural only have "other" category and no "one" category.
May be caused by Weblate? Sorry my poor English.

Language Plural Rules #zh: https://unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#zh

**Comment by arkon** [comment]
Seems related to https://github.com/WeblateOrg/weblate/issues/520

I'm not sure if we can fix that from the Weblate UI or not. I could fix them manually in the source files in this repo. @j2ghz Any thoughts?
