### ISSUE TITLE
Downloaded manga bug.

### ISSUE THREAD

**Issue by Battler624** [inorichi/tachiyomi#2715]
I've been having this weird bug, I have about 500 chapters of a manga downloaded but every time I go to a new chapter it takes a long time to load (even tho it's already downloaded) but if I quit the viewer (not the whole app) it immediately loads.

This bug happens frequently but not always, I've been trying to replicate it but so far I've read 5 chapters while writing this without it happening again. So weird.

**Comment by saintbepis** [comment]
Happened to me too, it's not big but it's a bug

**Comment by morcefaster** [comment]
I've had it on manga with as few as 20 chapters too. I'm planning to try to debug it sometime soon since it happens relatively frequently.

I'm using android 8, @Battler624 @saintbepis could you tell me what android version you're on?

**Comment by saintbepis** [comment]
@morcefaster I'm on android 10 using the latest dev build of the app

**Comment by Battler624** [comment]
@morcefaster Android 10, note 9 device exynos.

**Comment by Battler624** [comment]
Happened again, about 15 chapters of reading.

http://imgur.com/gallery/eSpyA1A

**Comment by morcefaster** [comment]
Yeah, it's same bug we're talking about. I'm now trying to reproduce it in an emulator.
