### ISSUE TITLE
[Feature Request]  download or read online with low or high resolution

### ISSUE THREAD

**Issue by dondeepak** [inorichi/tachiyomi#2716]
when internet is slow loading images / downloading chapters takes too much time it becomes more frustrating.if there is option to change downloading/ online reading image resolution  according to users will would be grate

Option to change downloading/ online reading image resolution to low or high will be more use full.
so please consider adding this option

**Comment by CarlosEsco** [comment]
not possible.  Tachiyomi is at the whim of the extension you are using.  If the extension's website has an option for low quality then you could make a request for the extension to support that.  However either way tachiyomi is downloading whatever the website has to offer.
