### ISSUE TITLE
[FeatureRequest] Only show manga which has unread chapters.

### ISSUE THREAD

**Issue by ruudschouten** [inorichi/tachiyomi#272]
I've got around 300 manga in my library and funding ones that I haven't read up to date can be a bit of a hassle. 

Which is why I would like to have an option somewhere to hide manga which has all chapters read.

**Comment by NoodleMage** [comment]
https://github.com/inorichi/tachiyomi/pull/198

**Comment by ruudschouten** [comment]
Oh nice, I searched the issues for anything resembling it but couldn't find anything.
Cheers
