### ISSUE TITLE
[Feature Request] Change button style from outlined to old

### ISSUE THREAD

**Issue by roguesoulboss** [inorichi/tachiyomi#2723]
im sorry i really hate the new icons can we have an option to use the old ones please please

**Comment by arkon** [comment]
No, that's too much technical debt and bloat.

**Comment by roguesoulboss** [comment]
why do you like the outlined icons they are ugly

**Comment by Soitora** [comment]
why do you like the filled icons they are ugly

**Comment by wopian** [comment]
The puzzle piece icon is barely legible (outline too bold) as a puzzle piece outside of large UI scaling

![](https://i.imgur.com/ue18uHi.jpg)

**Comment by arkon** [comment]
I'll reconsider the icons in this/settings/toolbars, but I do intend on at least keeping the outlined icons for the inactive bottom nav icons.

**Comment by morcefaster** [comment]
Could make icon sets configurable as part of a theme, android-style.

**Comment by happywillow0** [comment]
The outline looks a little weird with the little nubs but the extensions icon I think matches pretty well. Potentially some others I came across for your consideration:

![cloud](https://user-images.githubusercontent.com/45346080/76791887-316ae380-6798-11ea-9bb1-ad0c1234366f.PNG)
![link](https://user-images.githubusercontent.com/45346080/76791888-316ae380-6798-11ea-83e2-31c2996ba628.PNG)
![shop](https://user-images.githubusercontent.com/45346080/76791886-30d24d00-6798-11ea-83ad-97b411d70402.PNG) 


I would also like to propose some more icons for for source migration for your consideration: 

![directions](https://user-images.githubusercontent.com/45346080/76792016-7727ac00-6798-11ea-959b-e4da764562bf.PNG)
![find](https://user-images.githubusercontent.com/45346080/76792017-7727ac00-6798-11ea-8c0b-fa94e80f2e0e.PNG)

**Comment by arkon** [comment]
Not really sold on the source migration suggestions since those icons have stronger associations with other concepts IMO.
