### ISSUE TITLE
[Feature Requests] migrate bookmarks

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2729]
**App version: r1926

**Android version: 9.0

**Issue/Request: To transfer  bookmarks when migrating to different sources

**Other details: bookmarks not imported to the new sources....currently need to add bookmarks manually.....kindly automate this process by giving the option to user of whether to import bookmarks or not 

Thankyou

**Comment by Znova99** [comment]
Ya need this feature

**Comment by Znova99** [comment]
@arkon plez if possible kindly implement this feature as soon as possible......all bookmarks lost when migrating to new phone.....plez implement this feature
