### ISSUE TITLE
[bug] no chapter found

### ISSUE THREAD

**Issue by d3l4croix** [inorichi/tachiyomi#273]
version = v0.2.0
my android = 4.4.4
device = xiaomi mi pad

bug description: add few manga from kissmanga to my library, some added fine, some title have 0 chapter. add title with 0 chapter, go to chapter page in my library, swipe down to refresh, chapter will appear.

**Comment by inorichi** [comment]
It's intended. If you go back before the network request finishes, it won't add them. If you open the manga later from the library you will have to trigger the update manually.

I had my reasons to do that and I won't change it soon.
