### ISSUE TITLE
Please add a function which shows the latest chapter number when searching for a manga right on the catalouge global search page.

### ISSUE THREAD

**Issue by assmaster69** [inorichi/tachiyomi#2733]
### Why/User Benefit/User Problem
I always have to check at-least 4-5 sources individually to make sure if they are all on the same release. 
Recently though I came across a source which was offering 38 chapters for a particular manga (Maou no hajimekata) while the rest were stuck at around 25.
Seeing the latest chapter number or number of chapters befohand (whatever the user chooses) will eliminate this time taking ritual.

What/Requirements
Just search for your manga in global search. The search itself will compare the number of chapters or chapter number (whatever the user chooses) and put the source with the highest number on top. If the sources offer same amount of number, then everything goes traditionally (arranging sources in alphabetical order) while showing the number right below the cover art.

**Comment by CarlosEsco** [comment]
#2688
