### ISSUE TITLE
[Feature Request] Raw/Spn Sources

### ISSUE THREAD

**Issue by AceHeike** [inorichi/tachiyomi#2735]
First of all, **congratulations on this great application**.
My request is for three RAW sources that I would be happy to see in the application, mainly for its constant updating and order >> _loveheaven.net_ | _hanascan.com_ | _mangahato.com_
And a source in Spanish >> _es.ninemanga.com_ that is one of the most punctual in publications.

Thanks again for the effort, greetings :)

**Comment by MerradOklom** [comment]
MangaHato and HanaScan are within the FMReader extension. About NineManga, there is already an extension which supports English, Spanish, Portuguese, Italian, French and Russian. If you can't find them you may need to enable them by pressing the gear icon at the top right in Catalogues.

**Comment by happywillow0** [comment]
Also, this is in the wrong place. You want to post future requests in the tachiyomi-extensions github page.
