### ISSUE TITLE
[Bug] Crash "System UI" when you turn on the function: "Security screen" and the disappearance of the icon in the "recent applications menu"

### ISSUE THREAD

**Issue by Gena1005** [inorichi/tachiyomi#2737]
### Device information
* Tachiyomi version: Dev_0.8.5-1957
* Device: Xiaomi Redmi Note 5 | Whyred
* Android version: 10 (Evolution-X_v4.1.69 | March Madness | OFFICIAL • Build Date: 17.03.2020)

## Steps to reproduce
1. Enable the "Security Screen" function in the "Tachiyomi" settings
2.  Just pull the "Notification Bar" anywhere

### Expected behavior
The "notification bar" should open without any problems.  
There should be no crash of the "System Interface"!
### Actual behavior
Each time the "System Interface" is restarted, when the "Notification Panel" is opened, if the function: "Security Screen" is enabled!  (The screen turns off and turns back on after 2-3 seconds)

### Other details
It all started after updating to the latest "Dev" version of "Tachiyomi" (v0.8.5-1957)
### P.S.
Also, the application icon in the "Recent Applications Menu", Launcher: Pixel Launcher Stock has disappeared.  In the "Android Settings" and in the "Application Menu" is displayed normally!
![Screenshot_20200319-092709_Pixel_Launcher](https://user-images.githubusercontent.com/62114135/77029571-a9225380-69ce-11ea-9d16-27f773d6d83d.png)
![Screenshot_20200319-093009_Pixel_Launcher](https://user-images.githubusercontent.com/62114135/77029588-b63f4280-69ce-11ea-9fe4-076bc00e9bbb.png)

**Comment by arkon** [comment]
Do other apps with similar settings (like Firefox Focus) also crash on your ROM?

**Comment by Gena1005** [comment]
> Другие приложения с аналогичными настройками (например, Firefox Focus) также аварийно завершают работу на вашем ПЗУ?
I don’t use the browser "Firefox Focus", but now I’ll specially install it and check and unsubscribe to you.
