### ISSUE TITLE
[Bug] Automatic update check and automatic backup not working.

### ISSUE THREAD

**Issue by assmaster69** [inorichi/tachiyomi#2741]
### Device information
* Tachiyomi version: r1928 -->1936(3f414090)
* Android version: 9 PPR1.180610.011
*Android device: Xiaomi redmi 6

### Expected behavior
Backup file should be automatically created every 6 hours while deleting any old previous file. Maximum automatic backup is set to 1and frequency is set to 6 hours.
/storage/emulated/0/Tachiyomi/automatic

Automatically should check and notify me of any app update.

### Actual behavior
No automatic backup file is ever created nor any automatic update check occurs.

EDIT: Automatic Library update also not working which is set to every 12 hours.
Please tell me if the problem is from my side or the app's. Screenshots of the settings are posted below.

EDIT 2: Automatic update is working now with the app version 1940. Will take some time more to see if automatic app udpate is or not.

EDIT 3: All the issues mentioned are resolved and hereby I'm closing this thread. Thank you.
Thank you so much for your time and efforts.

**Comment by StillInSearchOfACoolNewUsername** [comment]
Same problem here

**Comment by StillInSearchOfACoolNewUsername** [comment]
Didn't notice until just now, when I checked.

**Comment by arkon** [comment]
Did you update from an older version of dev? You might need to reset those settings to trigger the jobs again.

**Comment by assmaster69** [comment]
> Did you update from an older version of dev? You might need to reset those settings to trigger the jobs again.

Yeah, from the immediate previous version. What do you mean 'reset?' If you mean setting it to manual then again to 6 hrs and maximum backup to 1, then I've already done that.
I have also installed Tachiyomi 0.8.5 stable version and it has the same problem but for now it is set on manual.

**Comment by arkon** [comment]
The only thing that might've affected it is a migration in dev, not stable.

Is battery optimization disabled for the app?

**Comment by assmaster69** [comment]
> The only thing that might've affected it is a migration in dev, not stable.
> 
> Is battery optimization disabled for the app?

Yup

**Comment by StillInSearchOfACoolNewUsername** [comment]
After resetting everything, the automatic update works and the backup too apparently.

**Comment by assmaster69** [comment]
> After resetting everything, the automatic update works and the backup too apparently.

Like clearing cash and all the data?

**Comment by pervertkirito** [comment]
> 
> 
> > After resetting everything, the automatic update works and the backup too apparently.
> 
> Like clearing cache and all the data?

![changelog](https://user-images.githubusercontent.com/27921916/77246918-c709e580-6c66-11ea-8cc5-6ce174108df1.png)

**Comment by assmaster69** [comment]
> > > After resetting everything, the automatic update works and the backup too apparently.
> > 
> > 
> > Like clearing cache and all the data?
> 
> ![changelog](https://user-images.githubusercontent.com/27921916/77246918-c709e580-6c66-11ea-8cc5-6ce174108df1.png)

**Comment by assmaster69** [comment]
> > > After resetting everything, the automatic update works and the backup too apparently.
> > 
> > 
> > Like clearing cache and all the data?
>

**Comment by assmaster69** [comment]
> 
> 
> > > After resetting everything, the automatic update works and the backup too apparently.
> > 
> > 
> > Like clearing cache and all the data?
> 
> ![changelog](https://user-images.githubusercontent.com/27921916/77246918-c709e580-6c66-11ea-8cc5-6ce174108df1.png)

![IMG_20200323_094718](https://user-images.githubusercontent.com/62332219/77296363-8a44f980-6d0d-11ea-9f04-f8a2e2287b01.jpg)
![IMG_20200323_094854](https://user-images.githubusercontent.com/62332219/77296364-8a44f980-6d0d-11ea-81dc-385043d5882b.jpg)
![IMG_20200323_094854](https://user-images.githubusercontent.com/62332219/77296370-8dd88080-6d0d-11ea-8495-ecf6a39c8e42.jpg)
![IMG_20200323_094718](https://user-images.githubusercontent.com/62332219/77296371-8dd88080-6d0d-11ea-95c7-40174b31973a.jpg)

**Comment by arkon** [comment]
Do a backup and reinstall the app.

**Comment by assmaster69** [comment]
> 
> 
> Do a backup and reinstall the app.

I've been trying for 2.5+ hours (I'm OCD) but everytime I get this error of these 9 mangas failing to be added into the library. I'm providing you with the backup file please have a look and tell me which site is causing this problem. Also, please put the site's name in the 'error log report' if possible.
![Screenshot_2020-03-24-02-46-59-137_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/62332219/77365145-9d8eae00-6d7b-11ea-9a3f-62dacc73b5c4.jpg)

**Comment by assmaster69** [comment]
> Do a backup and reinstall the app.

Didn't work. Gave it more than 24 hours. No new chapter notifications. No backup file was created. No app version update (1940) was notified.
One thing I noticed was that when I reinstalled the app, the directory was emulated/0/Tachiyomi/automatic/backup when I changed the backup frequency to 6 hours from manual. There is no backup folder under automatic. And when changed the directory manually to the very same path, the backup in the end was gone.

Also then I clicked on 'create backup,' it didn't prompt me to file manager and created a backup file in the destination folder but after changing the directory manually, it always prompts the file manager. 
Just thought it might help you out.
I you want any more info or have any question, please ask and always grateful for your efforts.

**Comment by EbolaMeister** [comment]
I have a similar issue. 
Device: Redmi 6
Issue: Backup creation Works but Auto Library Update and Manual Library Update don't work. The app is not restriced by Data Or Battery, tried to Force Stop, Clear Cache, Clear Cookies, Reboot, Reinstall, nothing seems to work. The titles don't update unless I manually go to each title in my library and refresh the chapters list. The last time it worked was 12 March. The Backup Creation works though, and as soon as I reinstalled the app all my previous data was there as if the app was never gone.

**Comment by likehelly** [comment]
manual update and automatic update doesn't work for me either.

I swipe down on library, and it quickly shows three titles on the notification bar before just going away and not doing anything.

**Comment by arkon** [comment]
I'd need logs to actually debug this issue, at least for manual update issues.

**Comment by EbolaMeister** [comment]
Logs? How do I help? I'm sorry, I'm dumb.

**Comment by arkon** [comment]
Try something like this:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://community.adobe.com/t5/acrobat-reader-mobile/how-to-get-crash-logs-from-your-device-android/td-p/4790938?page=1

You can just attach the logs here.

**Comment by EbolaMeister** [comment]
Does it still work of it doesn't crash though?

**Comment by arkon** [comment]
Only if it's something reproducible like manual updates not doing anything.
