### ISSUE TITLE
[Bug] Read Comics Online Comics Cover Not Appearing.

### ISSUE THREAD

**Issue by jahidrjrm** [inorichi/tachiyomi#2742]
When In select a comics issue
![Screenshot_20200320-220624_Tachiyomi](https://user-images.githubusercontent.com/61206424/77198294-ea228100-6b10-11ea-948c-a43ed302370b.jpg)
![Screenshot_20200320-221900_Tachiyomi](https://user-images.githubusercontent.com/61206424/77198303-ef7fcb80-6b10-11ea-8d43-cc33fe13549f.jpg)
![Screenshot_20200320-220620_Tachiyomi](https://user-images.githubusercontent.com/61206424/77198312-f60e4300-6b10-11ea-85c5-929d89e514a1.jpg)

**Comment by happywillow0** [comment]
What version of Tachiyomi are you running?
What version of the extension are you running?

**Comment by jahidrjrm** [comment]
Latest One.

**Comment by happywillow0** [comment]
What does latest one mean? 
Please confirm and provide the version numbers.

**Comment by jahidrjrm** [comment]
Could you please confirm me where is Read Comics Online? Is it in Foolslide because i did not find any individual extension for readcomicsonline.ru

**Comment by jahidrjrm** [comment]
If that then this should be
Tachiyomi: 0.8.5
Extension:FoolSlide (multiple sources) v1.2.36
