### ISSUE TITLE
[Feature Request] sort by genre feature

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2743]
### Why/User Benefit/User Problem
Helps to categories various mangas present in default library....also help to search mangas more quickly and accurately using their genre

### What/Requirements
Sorting option currently consist of Alphabet,last read,last update,unread,total chap,latest chap jst add a genre option too [on clicking it....various genre options appears (as dropdown/or popup/etc)....then select desired genre and the mangas having that genre will be shown rest will be hidden ]

**Comment by arkon** [comment]
You can already search by genre or tap one in a favorited manga's info page to trigger the search.

(Currently only in dev, will be in stable eventually)

**Comment by Samk19** [comment]
Oh thanks
