### ISSUE TITLE
Sorting by Last Updated not working properly

### ISSUE THREAD

**Issue by Yohan077** [inorichi/tachiyomi#2745]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9.0

I have sorted manga by Last Updated in 'my library' but some manga keeps going on top of list even though they haven't been updated. Like manga updated on 20th March is shown above the one which updated on 21st March. Should I reinstall the app or is this some minor bug?

### Expected behavior
new updates should be on top

### Actual behavior
Some other manga is on top which isn't updated

### Other details
https://imgur.com/a/qarfYJ4
In pic you can see that "The strongest God king" was last updated on 20th March but "Demon king who lost.." and "My wife is..." (Which updated moments ago taking screenshots) are below it.

**Comment by arkon** [comment]
The option isn't named very well, it's actually the last time it was checked. Dev included a different one, called "Latest chapter". It'll reach stable in the next release.

**Comment by arkon** [comment]
Renamed to "Last checked" in dev.
