### ISSUE TITLE
WHY THE HELLLLL IS THISSSS HAPPPENNNNN ALWAYS

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2746]
im done, you guys cant fix a damn simple issue? i give up on this app this what u want?

come on guys :C fix the cloudfire issue its been there from the forever u did not fix it, you keep releasing tons of useless updates but you cant fix the cloudfire bypass issue? that very stupid.

teamX is not working fix it, if you cant im more than happy to give help.

**Comment by TechnoJo4** [comment]
![](https://cdn.discordapp.com/emojis/561942050904211457.png?v=1)

**Comment by CarlosEsco** [comment]
@mged feel free to fix and open a pull request

**Comment by Aqiyak** [comment]
you should join tachiyomi's community

**Comment by arkon** [comment]
He's already in the Discord afaik. Most people don't have issues with CF, but he seems to be having more issues from wherever he's located.

**Comment by Soitora** [comment]
Simple, help or move country to fix the issues ¯\_(ツ)_/¯
