### ISSUE TITLE
teamX is not working cloudflare error

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2749]
Failed to bypass cloudflare please fix this issue :pray: 

the guys in exetnsions failed to fix the issue sadly ;(

**Comment by arkon** [comment]
You do realize "the guys" are the same people?

**Comment by mged** [comment]
if what you are saying is true, then i have to say im sorry.

but even tho please fix it, in the older issues u fixed the cloudflare for other extensions so fast but for this you cant fix it  why? please tell me.
