### ISSUE TITLE
Overscroll glow

### ISSUE THREAD

**Issue by LendLord** [inorichi/tachiyomi#275]
Is it possible to add overscroll glow when you scroll to the bottom of page? Sometimes long pages have white part at the bottom and it take some time to understand that there is nothing more.

**Comment by inorichi** [comment]
Just tested and my phone shows a glow. I think it requires Lollipop.

**Comment by LendLord** [comment]
I have marshmallow 6.0.1 and overscroll glow don't with default viewer and long pages

**Comment by inorichi** [comment]
![screenshot_2016-05-08-16-32-04_eu kanade tachiyomi debug](https://cloud.githubusercontent.com/assets/3521738/15098316/ba0d5a88-153a-11e6-9855-0e5e6f029025.png)

Probably not too visible, but it's there

**Comment by LendLord** [comment]
https://goo.gl/photos/jLm31Spg4HJQdpEPA

**Comment by inorichi** [comment]
Hm... that may be related with the parser. The page indicator should show 4/4 as you scroll down.

**Comment by LendLord** [comment]
No, it's not webtoon viewer, in default viewer page changes when you scroll from right to left.

**Comment by inorichi** [comment]
Ah. Default uses the one you specify as default in the reader settings.

**Comment by LendLord** [comment]
I don't know that=) So there is no overscroll glow in left to right viewer.

**Comment by CarlosEsco** [comment]
closing because overscroll glow isn't needed anymore since their is the transition page as last page
