### ISSUE TITLE
[Feature Request] Press Back Button to open the Side Menu

### ISSUE THREAD

**Issue by ivpiteriv** [inorichi/tachiyomi#2752]
I'd like to suggest a feature I grew to like from the App "Slack" which I find very convenient.
Especially in times where smartphones are as big as tablets were back in the days.

Benefits: 
Convenience and comfort, especially for large screens.
Subtle feature, which would improve the user experience.
No bloat functionality.

Description: 
Press Back Button once to open the Side Menu.
Press Back Button twice to leave the App.

https://imgur.com/a/MJwOUkP

**Comment by arkon** [comment]
The sidebar is already long gone in newer builds.

There's another open issue for double back to exit, so I'll close this issue.

**Comment by ivpiteriv** [comment]
oops, Thanks!
