### ISSUE TITLE
[Feature Request] Fix library button style

### ISSUE THREAD

**Issue by KraXen72** [inorichi/tachiyomi#2754]
### Why/User Benefit/User Problem
If you really want that outlined button style, take a look at what google photos is doing. 
yes:
![image](https://user-images.githubusercontent.com/21956756/77346235-3995c680-6d36-11ea-94c6-fd9de576b08e.png)
![image](https://user-images.githubusercontent.com/21956756/77346253-40243e00-6d36-11ea-90bc-a244f2261844.png)

no: 
![image](https://user-images.githubusercontent.com/21956756/77346488-9c875d80-6d36-11ea-8b91-43fe5132c183.png)

PLEASE this is the only bad thing right now..

### What/Requirements
(explain how this feature would behave)

**Comment by happywillow0** [comment]
I see what you mean with the icon.

On the other hand, as far as I know, the app is using [material.io guideline provided icon](https://material.io/resources/icons/?icon=collections_bookmark&style=outline) which is different from what Google is using.

**Comment by arkon** [comment]
The icon makes more sense when the rest of the app was using outlined icons, which people apparently didn't like.

**Comment by Soitora** [comment]
Are you referring to the bookmark part being filled in with Google variant but it not being so here?

**Comment by roguesoulboss** [comment]
yeah a fix would be using the normal icons like in settings

**Comment by roguesoulboss** [comment]
or if you really want use the google variant with filled bookmark when unselected
