### ISSUE TITLE
[Bug] Write short description here source arabic teamx  Don’t work

### ISSUE THREAD

**Issue by katake3133** [inorichi/tachiyomi#2757]
### Device information  huawi 
* Tachiyomi version: ? 0.8.4
* Android version: ? 8

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by HaraDesu** [comment]
wow, what a useful information you provide i see.

**Comment by arkon** [comment]
1. Wrong repo
1. Update your app
1. Let CloudFlare check pass in webview first
