### ISSUE TITLE
[Bug] KissManga Reporting HTTP Error 403

### ISSUE THREAD

**Issue by LiamCJ** [inorichi/tachiyomi#2758]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 8.1.0

## Steps to reproduce
1. Use the site KissManga.org as a source instead of KissManga.com
2. Fix bug

### Expected behavior
Being able to read titles from kissmanga

### Actual behavior
Recieved HTTP error 403

### Other details
Use of the folllowing site might fix the bug
https://kissmanga.org/

**Comment by arkon** [comment]
They're not the same thing.
