### ISSUE TITLE
[Bug] kissmanga stopped working

### ISSUE THREAD

**Issue by mrsfn** [inorichi/tachiyomi#2760]
### Device information
* Tachiyomi version: latest dev
* Android version: 8.0

## Steps to reproduce
When I try to access the source I get http error 403.

I hope it can be fixed. Tachiyomi is my favourite app.

**Comment by happywillow0** [comment]
1. Wrong Repo
2. 403 means site likely has a CAPTCHA, You will have to solve the captcaha manually in webview. There is no way to automatically bypass this. [See Also, Tachiyomi.org FAQ](https://tachiyomi.org/help/faq/extensions/#http-error-403)
3. Due to the number of people reading manga, site may be having issues. https://github.com/inorichi/tachiyomi-extensions/issues/2496

**Comment by Radio-9** [comment]
It's no longer showing 403, but no titles of manga are loading. Even the web view isn't showing the right website.

**Comment by ZayedHegazi** [comment]
Can confirm

**Comment by JJRII99** [comment]
I'm having the same problem but when I go to kissmanga I'm not getting a CAPTCHA

**Comment by mrsfn** [comment]
Yes, now it says "page list is empty" for me.

**Comment by HarryFry** [comment]
Guys it's cloud flare. If you open the web view and then open in a browser it redirects you after making you want like five seconds. Cloudflare can get enabled if people are slamming the site. Hopefully activity will slow down and the extension will start working again.

**Comment by otonieru** [comment]
Yeah, i can confirm. On both of my devices, kissmanga title are unable to loaded. Will say : empty page list. I can use the open in browser option fine, so this is not captcha related. But the webview option wont work, only show white screen. Hopefully this is only due to traffic.

**Comment by EthoKurza** [comment]
I have the same error, tried to fix it by doing open web view and open in browser but, it didn't work. On web view it just shows a white page.

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2496
