### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by Spopx1999** [inorichi/tachiyomi#2761]
### Device information
* Tachiyomi version: r1940
* Android version: 9

kissmanga is returning a "page list empty" message for any manga I try to select.

Other sources, like Mangafox, load properly.

Extension is up to date. I've restarted the tablet as well, didn't work.

can you fix this problem please

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2496
