### ISSUE TITLE
[Bug] failed to bypass cloudflare can't download manga in any sources/extensions 

### ISSUE THREAD

**Issue by four98** [inorichi/tachiyomi#2762]
* Tachiyomi version: latest 8.5
* Android version: android 9

### Actual behavior
When i download a certain manga it always shows "failed to bypass cloudflare" But it was okay last night and the version is 8.4 so i thought that i should just update the app but this happened instead 

### Other details
Attached is a screenshot
![Screenshot_20200325-162016_Tachiyomi](https://user-images.githubusercontent.com/55613354/77517036-5ce77f80-6eb6-11ea-89d3-b4ec87e3b452.jpg)

**Comment by CarlosEsco** [comment]
What extensions?

**Comment by kiskae491** [comment]
Open it in web view first then start downloading

**Comment by alittlebitofit** [comment]
Hello, I have a slightly different notification when download fails which says "Page list is empty".
I retried dozens of times but still the same error. It happens with other comics too.

And sometimes it times out when I open a chapter.

@kiskae491 How to open it in web view?

**Comment by kiskae491** [comment]
> 
> 

> @kiskae491 How to open it in web view?
<img width="540" alt="Screenshot_20200328-190253_Tachiyomi" src="https://user-images.githubusercontent.com/19674786/77830304-e81b7c00-7127-11ea-90fb-ea67b4a60144.png">

![Screenshot_20200328-190301_Tachiyomi](https://user-images.githubusercontent.com/19674786/77830323-f8cbf200-7127-11ea-8f3c-880c533bf087.png)

**Comment by alittlebitofit** [comment]
![Screenshot_2020-03-31-20-15-14](https://user-images.githubusercontent.com/42311431/78040015-7bed8200-738c-11ea-9b89-62a37ed6228e.png)

It just opens up blank white screen with Refresh and Close options.

**Comment by arkon** [comment]
You need to make sure you've updated your Android Webview (and/or Chrome, if you're using that).

It also looks like you're using an old version of Android, so it might not actually work as intended either.
