### ISSUE TITLE
[Bug] Source ID changed to "4"

### ISSUE THREAD

**Issue by Sundune** [inorichi/tachiyomi#2763]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10 / OxygenOS 10.3

## Steps to reproduce
Unknown

### Expected behavior
Source ID should still be the one of Manga Eden

### Actual behavior
Source ID from every Manga from Manga Eden changed to 4 and opening/updating the mangas doesn't work anymore (Loader not implemented)

### Other details
This problem happend sometime during this weekend. 

Sadly I only noticed it when i updated Tachiyomi to version 0.8.5 and tried to import my backup.
Before i updated I did notice that the source in the source migration menu sayed 4. that was ultimately why I updated in the first place. 

The attached screenshot shows the area in the backup with the Source ID that i mean. 

![notepad++_gR7ln6fEYu](https://user-images.githubusercontent.com/17412304/77529245-880aa880-6e8f-11ea-937a-052174750335.png)

**Comment by CarlosEsco** [comment]
install the manga eden extension
