### ISSUE TITLE
[Bug] Japscan: Image display problem

### ISSUE THREAD

**Issue by dryx01** [inorichi/tachiyomi#2766]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
Select "Darwin's game" (example) with tachiyomi's Japscan extension.
Open a chapter from 45 or after.

### Expected behavior
Good display of chapter, like other on this website.

### Actual behavior
"Gridded" displaying, seems like the rearrangement of pixels doesn't work.
![Screenshot_20200325-111734](https://user-images.githubusercontent.com/6872170/77562088-db94ea80-6ebf-11ea-9fe6-3d19c3153745.jpg)

### Other details
Only few chapters have this issue, not all.

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2219
