### ISSUE TITLE
[Bug] Kissmanga didn't loading

### ISSUE THREAD

**Issue by cmine20** [inorichi/tachiyomi#2769]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9
* Kissmanga vers.: 1.2.13

When I open my tachiyomi in kissmanga it doesn't loading, no library to search, I can't even update my manga it always say that "no result found!" after the update this March 25, 2020 but I try all the solution like going to Browser(default browser, google, etc.) verifying the captcha. Does anyone know how to fix this??

Pst. I apologize for my grammar.

**Comment by Gamingappleh** [comment]
Had a similar problem it seems that kissmanga has started IP Banning people using tachiyomi.

https://www.reddit.com/r/KissManga/comments/fooysi/dont_use_tachiyomi_or_any_related_bridge_apps_on/

**Comment by cmine20** [comment]
Ahm sorry i just resolve my problem right now and I think it might possible to reshuffle your ip address. Just turn on and off the airplane mode then refresh the kissmanga.. i dont know if it gonna work with you guyz. I wish it might help..
