### ISSUE TITLE
I can't update any new chapters for manga.

### ISSUE THREAD

**Issue by genus555** [inorichi/tachiyomi#2775]
### Device information
* Tachiyomi version: 0.8.5
* Android version: S10

## Steps to reproduce
1. Go to "My Library"
2. Scroll down until bubble with refresh signal comes down

### Expected behavior
Usually it'll go through all the manga I have in my library and update them if they have any new chapters.

### Actual behavior
Checks the first two mangas in alphabetical order then suddenly stops

**Comment by seannydmanga** [comment]
Also having the same problem. Scans the first three manga then stops.

**Comment by CarlosEsco** [comment]
What sources do you use?

**Comment by genus555** [comment]
Mangakalot and Kissmanga mostly. Theres still some manga I have that I haven't transferred from manga rock and very rarely I use manga life/onl/plus

**Comment by mrtort** [comment]
Me too if you try to access directly from browser its gonna tell you are banned
I reseted my router an it worked again, but after 1 day i was banned again

**Comment by tamal777** [comment]
kissmanga not working. they are banning ip.

**Comment by arkon** [comment]
For KissManga: https://github.com/inorichi/tachiyomi-extensions/issues/2496

**Comment by genus555** [comment]
Tbh though KissManga is really laggy for me to begin with so I mostly use Mangakalot

**Comment by seannydmanga** [comment]
I don't think it's the sources that are the main issue as I use various like MangaHub, Mangakalot, Chapter Manga e.t.c and whenever I use the pull-down update feature, it scans the first 3-4 then just stops.

**Comment by bunnygitgud** [comment]
Same Problem Here .when i go to catalogues> Mangakakalot > Latest > Seee my mangas already have an update this day 29,March 2020 .then i tried updating my library no manga/latest pop up.

**Comment by Heinfighter** [comment]
Same issue here, manga has updated if i check myself online manually but when I use autocheck(swipe down to show bubble), It goes through all the manga and show updated chapters for around 3 manga. If i go inside that individual manga that hasn't updated by mass autocheck and manually refresh myself(swipe down for bubble inside chapters screen) , it shows the updated chapters.

**Comment by genus555** [comment]
Is there any other way to update other than manually going through every individual manga rn?

**Comment by mirr** [comment]
I also experiencing this after upgrading to 0.8.5. But this is for kissmanga.com, the rest are working. And when I checked the website, it says my ip is blocked. It seems kissmanga or cloudflare is blocking request from tachiyomi or could be the kissmanga guys did this.

**Comment by seannydmanga** [comment]
**I think I have found a solution as I am now able to update my collection via pulldown.** 

Unsure if this will work for you, but I went to Extensions and updated every extension that had an update. Even if some didnt go through, I was able to sync my library and it works like normal again.

Good luck!

**Comment by ARCKNIGHT117** [comment]
I was able to fix it by uninstalling Mangaplus. I noticed it always crashed once it tried to acsess blackclover.

**Comment by genus555** [comment]
Update: I made a backup and downgraded to 0.8.4 then repudiated to 0.8.5 and now updates work
