### ISSUE TITLE
[Feature Request] display lastest chapter in source migration

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#2778]
When doing source migration, were unable to see switch extension have the lastest chapter/when it was updated.
Some mangas on some extensions updates more frequently/faster than others, but which one updates fastest is not always consistent across mangas.

It would be nice if the source migration page can display the lastest chapter number and when it was updated.

**Comment by CarlosEsco** [comment]
This would require a ton more network calls. On per each manga that shows on that screen.  A work around is long pressing into the chapter so you can check a specific sources chapters
