### ISSUE TITLE
[Feature Request] reset setting for extension

### ISSUE THREAD

**Issue by betengQ** [inorichi/tachiyomi#2780]
### Why/User Benefit/User Problem
when the Mangadex settings are set it cannot be reset again and that sometimes affects the latest catalog update in my case Indonesian server instead of the UK server being updated, because the UK server is set up (sorry my english is suck)
### What/Requirements
Reset button in extension details

**Comment by arkon** [comment]
You can just manually set them back to the "normal" settings.
