### ISSUE TITLE
[Bug] Ever since the kissanime IP ban my tachiyomi is constantly crashing even after I uninstalled kissmanga and moved all the mangas to different sources now I can't even refresh for new chapters cause it keeps crashing.

### ISSUE THREAD

**Issue by syndivenom** [inorichi/tachiyomi#2781]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

Ever since the kissanime IP ban my tachiyomi is constantly crashing even after I uninstalled kissmanga and moved all the mangas to different sources now I can't even refresh for new chapters cause it keeps crashing.

**Comment by arkon** [comment]
Does it still happen if you update to 0.8.5?

**Comment by Sajeeb97** [comment]
Just install latest version.Its working for me though.No crashes
