### ISSUE TITLE
[Bug] Library Update

### ISSUE THREAD

**Issue by bunnygitgud** [inorichi/tachiyomi#2782]
### Device information
* Tachiyomi version: 0.8.5
* Android version: android 7

## Steps to reproduce
1. First step
First I tried Updating my Library but no updated manga /Mangakakalot Source/extension

2. Second step
When i try going to >Catalogues>Mangkakalot Latest > I see my Mangas already have Update.
### Expected behavior
This should happen.
It should be show my latest update of mangas cause the extension already have update
### Actual behavior
This happened instead.
No updates when already have in catalogues
### Other details
Additional details and attachments.

**Comment by arkon** [comment]
From Discord FAQ:

2020-03-25
Mangakakalot may be creating new entries for manga again on their site, so your old entries are obselete and can't access the new content. 

To resolve this, migrate the manga to the Mangakakalot extension from the Mangakakalot extension, manually, as batch/auto migration doesn't support it, though you can begin a auto migration and manually go down the list. 
Or you can migrate to a different extension and stay there or back to Mangakakalot.
