### ISSUE TITLE
Add automigrat to latest chapter

### ISSUE THREAD

**Issue by owosenpie** [inorichi/tachiyomi#2789]
### Why/User Benefit/User Problem
Currently you can update to the first source witch is based off scource name alphabetically, and migrate to most chapters which always selects for manga with multiple of the same chapter, adding migrate by latest chapter will allow people to find the manga with the most chapters that was most recently updated not accounting for repeats.
### What/Requirements
When automigrating use the last chapter and updated date info to find the manga with the highest last chapter that was most recently updated.

**Comment by CarlosEsco** [comment]
Confused cause there is no auto migrate for tachiyomi.  Only a couple forks have this option. Open in their repo. Though it will probably be declined because this required double the network requests. So if you see 30 manga it requires 30 more network requests to get the manga chapter info
