### ISSUE TITLE
[Bug] Series with Chaptermanga as source don't update for some reason. Other sources seem to be working

### ISSUE THREAD

**Issue by EbolaMeister** [inorichi/tachiyomi#2790]
### Device information
* Tachiyomi version: 0.8.4
* Android version: Redmi 6 

## Steps to reproduce
I have no idea how to. 

### Expected behavior
Manga should update, whether in Library Updates Or in Manga Chapters List

### Actual behavior
The Library list stops updating as soon as a Chaptermanga Sourced series comes up. On updating one title manually/refreshing chapters list, it momentarily shows a popup
"Attempt to invoke virtual 
method 'java.lang.String
org.jsoup.Nodes.Element.data()' on a null object reference"

**Comment by happywillow0** [comment]
You posted in the wrong issue tracker. This is for bugs for the app itself and not the extensions.

However, chapter manga is dead. The website doesn't load the last time I checked. Migrate your manga to a different website.

Also, uninstall chapter manga.
Also, make a backup of your library.
Also, update Tachiyomi to 0.8.5

**Comment by arkon** [comment]
Chaptermanga was removed a while ago since it's broken.

Does this happen in 0.8.5?

**Comment by EbolaMeister** [comment]
Welp, guess I'm out of touch/loop. Thanks.
