### ISSUE TITLE
[Bug] Kissmanga blocklists my IP after updating my manga in favorites(more than 100)

### ISSUE THREAD

**Issue by derencel20** [inorichi/tachiyomi#2792]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. Scroll up to get updates for your favorites

### Expected behavior
Should load normally.

### Actual behavior
Page list Empty. And my IP is blocked from Kissmanga now(Already refreshed the IP since my ISP gives me dynamic IP, but upon performing the steps above, kissmanga blocklists the IP). I have about 100 manga in favorites under Kissmanga. Kissmanga probably thinks the IP is performing a DDOS attack on the site.

### Other details
One possible solution would be to reduce the update to one query per site.
Get the JSON (with chapter info) from favorites
Get the JSON (with chapter info) from kissmanga
then compare them, the difference would be the update. Tho idk if this is feasible?

**Comment by arkon** [comment]
Not sure what you mean in the "Other details" section, but KissManga actively blocks users that avoids giving them ad revenue.

I'd recommend just switching to a different source.
