### ISSUE TITLE
[Feature Request] Ability to mark a (range) of manga

### ISSUE THREAD

**Issue by kkarakk** [inorichi/tachiyomi#2793]
### Why/User Benefit/User Problem
(explain why this feature should be added)
A lot of manga sites have two versions of a manga so downloading all means you download the manga twice.   
Marking previous as unread doesn't work since sometimes the newer version is BELOW the older version in the numbered list and with some mangas having 100+ chapters, marking them as read individually is tedious
### What/Requirements
In the dropdown menu, under "mark previous as read" another option would exist "mark range/multiple as read" so you could mark a range of items as read/unread as per requirements.    
This would present the list of chapters and pressing and holding and item would mark the item as start of range. Similarly upon scrolling down and  pressing and holding another item would mark that item as the end of the range. 
Everything between the beginning and end of this range would be selected, this would be represented as a tickmark in the checkbox next to the manga chapter's name.

**Comment by arkon** [comment]
This is already in dev.

**Comment by kkarakk** [comment]
Anywhere I can see? what issue number?

**Comment by arkon** [comment]
#1493
