### ISSUE TITLE
[Bug] 1stKiss Extension not showing showing thumbnails sfter adding to MyLibrary

### ISSUE THREAD

**Issue by HunterCha** [inorichi/tachiyomi#2796]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. Clear Cache
2. Clear Database
3. Clear cookies
4. Force close Tachiyomi
5. Open in Webview. Its working fine in webview. And even in Tachiyomi you can read it. Its just not showing thumbnails on My Library

### Expected behavior
Thumbnails should be seen but its just showing a black background.

### Actual behavior
You can only see a black back ground

### Other details
![Screenshot_2020-03-31-11-07-39-70_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/62924394/77988167-3a3de680-734e-11ea-8047-f862e879dde8.jpg)

**Comment by HunterCha** [comment]
It only happens on 1stKiss. Those with thumbnails are from a different extension. But they dont have some of the manhwas's im reading thats why im using 1stKiss.

**Comment by HunterCha** [comment]
Just to add. 1stKiss is from Madara Extension.

**Comment by SnakeDoc83** [comment]
Is your Madara extension up to date?

**Comment by SnakeDoc83** [comment]
Also, wrong repo, extension issues go here: https://github.com/inorichi/tachiyomi-extensions/issues

**Comment by HunterCha** [comment]
> Also, wrong repo, extension issues go here: https://github.com/inorichi/tachiyomi-extensions/issues

Oh thank you for correcting. Ill just post an updated 1 their. 

Yes Madara extrnsion is up to date. I also updated to version 0.8.5
