### ISSUE TITLE
[Feature Request] Requesting to add Hitomi.la

### ISSUE THREAD

**Issue by alwayswannaflyhi** [inorichi/tachiyomi#2798]
Hitomi.la extension
I feel like  Hitomi.la have more quality doujins some are only found in this site
Pls accept my selfish request

**Comment by CarlosEsco** [comment]
There is no hitom.la in tachiyomi you are using Az or eh open an issue with those forks

**Comment by CarlosEsco** [comment]
Duplicate and wrong repository
