### ISSUE TITLE
Duplicate manga in mangakakalot extention

### ISSUE THREAD

**Issue by moopeypoopey** [inorichi/tachiyomi#2799]
Tachiyomi version: 0.8.5 
Android version 8.0.0

I've been looking at the recently updated manga in the mangakakalot extention and I see the same manga I've favorited in my library but the one in my library hasn't gotten an update any idea what to do?

**Comment by juniornff** [comment]
If you have the stand-alone extension version of mangakakalot, you probably should change it with Mangabox extension (it has mangakakalot and other sources)

That happend me with Ajin, since i changed it, i get the new chapters

**Comment by arkon** [comment]
From Discord FAQ:

2020-03-25
Mangakakalot may be creating new entries for manga again on their site, so your old entries are obselete and can't access the new content. 

To resolve this, migrate the manga to the Mangakakalot extension from the Mangakakalot extension, manually, as batch/auto migration doesn't support it, though you can begin a auto migration and manually go down the list. 
Or you can migrate to a different extension and stay there or back to Mangakakalot.
