### ISSUE TITLE
Feature Request : App update from using the app

### ISSUE THREAD

**Issue by Rumple007** [inorichi/tachiyomi#28]

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/14#issuecomment-172258180
https://f-droid.org/
https://f-droid.org/forums/topic/tachiyomi/

**Comment by j2ghz** [comment]
#46 Ready to close?

**Comment by inorichi** [comment]
Let's wait for the app to be available at F-Droid.

**Comment by inorichi** [comment]
Install from F-Droid: https://f-droid.org/repository/browse/?fdid=eu.kanade.tachiyomi
