### ISSUE TITLE
[Feature Request] UI layout selector

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#2802]
### Why/User Benefit/User Problem
New UI looks better, but moves lots of buttons to the top and bottom of the screen, making one handed reachability a problem, since newer phones are quite tall.

### What/Requirements
An option to switch to the older UI layout, where most things are left and right, this would be nice.

**Comment by happywillow0** [comment]
Thank you for your idea. 

There are no plans for adding alternative / old layouts. Adding additional layouts create code complexity that the developers do not wish to have or to maintain.
