### ISSUE TITLE
It's about download system

### ISSUE THREAD

**Issue by lolruler** [inorichi/tachiyomi#2804]
**App version:R1959

**Android version:7.1

**Issue/Request:About download system

It's hard to download every single manga or porn comics by opening/selecting it . I like to suggest that by selecting bunch of mangas by user clicks they download.if recall correctly the old updates of Tachiyomi were easy to download but in new update it's kinda hard coz I have to click the image of the manga then I have to select which part I want to download of that manga though it's really good feature but I like the old system of download which was easy 😅
Thank you 😊

**Comment by arkon** [comment]
I can't remember the download system changing in the past few years.

If you're talking about downloading from the library view, there's an open issue for that.
