### ISSUE TITLE
Unable to restore backups

### ISSUE THREAD

**Issue by LazyAndBeyond** [inorichi/tachiyomi#2805]
**App version:** 0.8.5

**Android version:** 6.0.1

**Issue/Request:** cannot restore backups

**Steps to reproduce (if applicable)**

**Other details:**
Tried to update the app as I no longer received new chapters, the updating from the app didn't work so I created a backup and downloaded new version from site, when I tried to restore backup it gives me errors for all of them and when I tried going to an oled version it has the same error

**Comment by arkon** [comment]
What are the errors? Are the extensions installed and are you logged in to trackers?

**Comment by spicycake** [comment]
For me, I was using KissAnime as the source. I believe that was the cause because KissAnime is not working right now. So when I try to restore the backups, the app receive null when it try to retrieve the info from the API and then result in errors. Just my hypothesis. Attached the log for more info.

[tachiyomi_restore[1].log](https://github.com/inorichi/tachiyomi/files/4413751/tachiyomi_restore.1.log)

**Comment by LazyAndBeyond** [comment]
> For me, I was using KissAnime as the source. I believe that was the cause because KissAnime is not working right now. So when I try to restore the backups, the app receive null when it try to retrieve the info from the API and then result in errors. Just my hypothesis. Attached the log for more info.
> 
> [tachiyomi_restore[1].log](https://github.com/inorichi/tachiyomi/files/4413751/tachiyomi_restore.1.log)

I'm receiving the same errors and KissAnime isn't working as well I guess that's the reason
I also tried using other sources like mangadex and mangakalot but mangadex doesn't have black clover, Dr. Stone and the god of high school chapters? They are just listed and mangakalot takes a huge amount of time to check for updates for mangas like 20m for only the manga that is in them

**Comment by LazyAndBeyond** [comment]
> What are the errors? Are the extensions installed and are you logged in to trackers?

It's the same as @spicycake

**Comment by arkon** [comment]
Refer to the FAQ/support team on Discord for help on migrating/restoring things from KissManga.
