### ISSUE TITLE
[Feature Request] Add Anime-Planet and/or Baka-Updates as a tracking source

### ISSUE THREAD

**Issue by kaononymous** [inorichi/tachiyomi#2806]
### Why/User Benefit/User Problem
Currently it is difficult to find some manga on current sources. MAL refuses to add anything that is not manga e.g. Webtoons which would be nice to track. You can sometimes find it on AniList but not always but the mentioned sources consistently have records of webtoons and manga that other sources do not have. 

### What/Requirements
Basically the same as any other tracking source

**Comment by CarlosEsco** [comment]
These fall into the no api, probably wont add scenario.

**Comment by arkon** [comment]
There's existing issues for both of these.
