### ISSUE TITLE
[Feature Request] Add server change in groups

### ISSUE THREAD

**Issue by Applewubs** [inorichi/tachiyomi#2807]
### Why/User Benefit/User Problem
Many of us moved from server to server (extensions) for various problems or comfort, in these cases we have to move each manga, I think that having a way to put them in groups helps to release the load a little, including of course a small preview of what will happen and which will be changed.

### What/Requirements
Being able to move more than 20 manga to other server (extension).

**Comment by CarlosEsco** [comment]
weird use of server here.  Just use source or extension in future.  I believe you are asking about grouping the manga by source?  Isn't sorting by source already available in the library view?

**Comment by Applewubs** [comment]
> weird use of server here. Just use source or extension in future. I believe you are asking about grouping the manga by source? Isn't sorting by source already available in the library view?

No, I'm talking about migrating groups of manga from one extension to other

**Comment by CarlosEsco** [comment]
This is similar enough #1729
