### ISSUE TITLE
[Feature Request] add "by download" option in display mode

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2809]
### Why/User Benefit/User Problem
Helps in displaying only download chapters in a sorted manner. User who require to view only certain chapters can download and can view those chapters sort in ascending or descending chapter order. 
For eg: if a user wants to read chp 6 then 11 then 18 he can download those chapters and view them alone after the other rather that going through chapters all the chapters in between.

### What/Requirements
A user can download chapters then from top menu can select display option then select by download and the reader then will only show the downloaded chapters in ascending/decending order of chapter number 

1. Selecting display mode (Downloaded)
![PicsArt_04-02-01 18 53](https://user-images.githubusercontent.com/36104528/78180556-96088c80-7480-11ea-9db0-5e9829085277.jpg)

2.result 
![PicsArt_04-02-01 22 57](https://user-images.githubusercontent.com/36104528/78180659-b7697880-7480-11ea-93dd-81609ccb36ee.jpg)

**Comment by CarlosEsco** [comment]
Am i missing something why dont you click the filter button and choose download as one of the options

**Comment by Samk19** [comment]
Oh yea jst tried thanks

**Comment by Samk19** [comment]
Bro issue not resolved.....only works as viewing option when moving from chp 40 to chp44 doesnt skip the chapters in between

For eg: switch off your internet then filter downloaded in the above case chp 40 ,44,47....now start reading chp 40 when chapter ended says internet not available.....(should work like when chp 40 is over should skip chp 41,42, 43 and directly display chp 44)

**Comment by happywillow0** [comment]
Would you ever want to go back and read 41, 42, and 43? Currently, you can mark them as read and turn on skip read chapters.

**Comment by Samk19** [comment]
@arkon wouldn't the above work in the same way as.....also wouldn't implementing list filtering more work for you guys? Wouldn't adding the above in display mode or sorting mode be more effective (less time consuming) for you guys to develop ?

**Comment by arkon** [comment]
Display and sort mode don't have anything to do with the reader either. Even if it did, shoehorning it in there as a hacky workaround isn't something we'd do.

**Comment by Samk19** [comment]
@arkon thats why created another request as you have mentioned.....kindly reverse issue mentioning (mention #2809 in #2810)....i think implement reader to respect filtering better option as we can remove the problem when author releases some extra chapters in between the series...
