### ISSUE TITLE
[Feature Request] reader respecting the chapter list filtering

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2810]
### Why/User Benefit/User Problem
Can be used to filter the chapter list and sort them into read/unread/downloaded/bookmarked and have a smooth experience when reading even when the chapters are not in sequential order.
Two use cases described below.

### What/Requirements
A user can filter chapter into downloaded/read/unread/bookmark then while reading the same chapters in the selected catagory appear on after the another like for Example:
If the source has update two chapters in the middle of the series (chp 152.1, 184 and 165.1 are uploaded today but user already read till 183) if a user wants to read chapters 152.1 and 165.1 and then start for 184 back to back he can do it by filtering the read to show only unread chapters and while reading the reader is respecting the list filtering and shows user 152.1 then 165.1 and finally 184 directly without loading chapters 153, 154.....164....and so on 

Also second use case would if i want only to read my downloaded chapt for eg: chp 2, 6,8 the reader (after implementing filtering list into the reader) will show load 2,6,8 back to back without opening 3,4,5,7...

This will benefit user in three ways 1.reducing usage 2.conserving time 3.loading of each chapter......also will help when there is no internet and the downloaded chapters are not in proper sequence

**Comment by arkon** [comment]
For more context, originally from #2809
