### ISSUE TITLE
[Feature Request] Add Button/Switches to automate Hide marked "Read" chapter from "Updates Pages" 

### ISSUE THREAD

**Issue by Mystery77** [inorichi/tachiyomi#2811]
Sorry if duplicate request, as i cant found it when search it

**App version:**
r1964
**Android version:**
9

### Why/User Benefit/User Problem
Ease-of-Use when finding updated chapter that not read yet. So "Read" Chapter won`t blocked view in update pages

Below is example when read chapter blocked view on updates pages, and much scrolling to find which chapter not read yet..
<a href="https://ibb.co/G2jZnhb"><img src="https://i.ibb.co/k8FL5dW/Whats-App-Image-2020-04-02-at-11-00-18.jpg" alt="Whats-App-Image-2020-04-02-at-11-00-18" border="0"></a>

### What/Requirements
When toggle/button activated it will remove/hide chapter "marked as read" on Update pages.

**Comment by X9VoiD** [comment]
Sorting your library to unread will do the same as you requested. May close the issue now. Update history is called history because it has to show all entries.
