### ISSUE TITLE
[Feature Request] Add % completion or number of read chapters on thumbnail

### ISSUE THREAD

**Issue by ofirrock** [inorichi/tachiyomi#2812]
### Why/User Benefit/User Problem
When looking at the "My Library" page, it would be nice to see on the manga how many chapters has been read out of the total: can be using % or just curr/Total (e.g. 86% or 172/200).
It enables the user to know how long this title is. ("is it long", "is it short" type of question in the user's head)

### What/Requirements
- Grid-View:
The user can see on the thumbnail's right side the number of total read chapter out of the total. (unread chapters number on the left stays the same)
![image](https://user-images.githubusercontent.com/36620567/78281019-b38e3280-7522-11ea-8acc-cf9ea100f84e.png)

- List-View:
The user can see on the list's item to the left of the number of total unread chapters the  number of total read chapter out of the total. (unread chapters on the right stays the same)
![image](https://user-images.githubusercontent.com/36620567/78281401-48912b80-7523-11ea-8397-3053ac900084.png)

ux/ui note - it could be added in a "gray" style so it won't attract the user's eyes as the number of unread chapter on the left / right (respectively).

**Comment by CarlosEsco** [comment]
Sorting by total chapters and having unread badges achieves a similar thing no?

**Comment by ofirrock** [comment]
It does make it easier, but in my opinion to be able to see the number of chapters right away, is more convenient, more informative and differentiate between long-term and short-term titles more easily (of course that long/short-term is subjective to the user).

**Comment by X9VoiD** [comment]
The unread badges already shows how long the rest of a manga would be, and the requested feature provides no further information except for the number of chapter that is read already. Not exactly useful, may close the issue.

**Comment by ofirrock** [comment]
As @X9VoiD says the unread badges already shows how long the rest of a manga would be (at the said time).
But the point of this feature is to give a clear "numerical weight" to the length of a title.
The _commitment of the user_ to a title can varies by seeing these numbers.
This feature gives the user the ability to clearly differentiate between long and short titles, that he committed to.

(maybe I haven't explained myself clearly in the issue's description, I can edit it in the future if necessary)

**Comment by CarlosEsco** [comment]
That only gives a numerical weight to cmqnga that are finished though

**Comment by ofirrock** [comment]
@CarlosEsco I agree, it does give a better indication for titles that ended.
However, I'm still convinced that this feature has value for ongoing titles.
In addition, I think it should be optional, same as the "Download badges".

**Comment by CarlosEsco** [comment]
I feel it's just not useful. It will just cause confusion with people wondering why it says 100% on manga that's ongoing.    filter by unread and sort by total chapters accomplishes most of this

**Comment by ofirrock** [comment]
@CarlosEsco you're right, I didn't think about the possibility that it would confuse people and that's more important.

I'd love if you can consider showing the series length (so far) on the cover. (even if its already read)
If you need me to open another issue (and close this one) on the subject please update.

Thanks for the quick responses.

**Comment by CarlosEsco** [comment]
Yea if you could do that.
