### ISSUE TITLE
[Bug] Page list is empty

### ISSUE THREAD

**Issue by Lazyram01** [inorichi/tachiyomi#2813]
### Device information
* Tachiyomi version: r1964
* Android version: EMUI 9.1.0

## Steps to reproduce
1. Opening any managahere manga created error "page list is empty" 
2. As explained on the tachiyomi website I tried to do captcha but there was none on the managahere site

### Expected behavior
Manga images open

### Actual behavior
"page list is empty"

**Comment by joseph619** [comment]
Wrong repo, and this is already reported.

**Comment by Lazyram01** [comment]
Can I get a link to the already reported issue? Thanks

**Comment by Lazyram01** [comment]
> Wrong repo, and this is already reported.

Can I get the link to the already reported issue? Thanks

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2573

**Comment by Lazyram01** [comment]
Thanj you so much for fixing it so quickly
