### ISSUE TITLE
Add small icons in the Directory filters instead of an empty field.  (An empty box is opposite the words "extensions")

### ISSUE THREAD

**Issue by Gena1005** [inorichi/tachiyomi#2814]
### Why/User Benefit/User Problem
(explain why this feature should be added)
 It will be very convenient when hiding "temporarily" non-working extensions, if you don’t want to delete it, because, anyway, after a while, the parser will be updated, or it will be repaired on the server side, if the problem is in it, but if a person has many extensions installed, then  it’s somewhat problematic to look and see which parser, where and where it is from, the main source of this extension, for example, one extension - can have up to 3-4 sources ... Thinking such tiny cosmetic improvements do not damage user experience using  Vania, on the contrary, make "Tachiyomi" better and better.  This is of course a trifle, but still a very pleasant trifle :)

### What/Requirements
(explain how this feature would behave)
This item is located along the path: Sources / Filter (Icon in the upper right side) /
![Screenshot_20200403-062832_1](https://user-images.githubusercontent.com/62114135/78309308-d21d1980-7574-11ea-9c35-f9d5c1d91c24.jpg)

**Comment by arkon** [comment]
Add what, exactly? The extension icons?
