### ISSUE TITLE
mangahere not working - page list is empty

### ISSUE THREAD

**Issue by MartassCZ** [inorichi/tachiyomi#2818]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.5
**Android version:**
9
**Issue/Request:**
manga on mangahere, cant read it. instead of that, show error "Page list is empty"
**Steps to reproduce (if applicable)**

 1.Open manga  from mangahere
 2.click on manga
 3.try open chapter

**Other details:**

**Comment by CarlosEsco** [comment]
read your post.  

DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository https://github.com/inorichi/tachiyomi-extensions/

and if you go there you would see there is already an issue opened
