### ISSUE TITLE
Tachiyomi extension kissmanga is not working. 

### ISSUE THREAD

**Issue by Bikeam-tech** [inorichi/tachiyomi#2823]
### device oppo A5S
* Tachiyomi version: 0.8.5
* Android version: CPH1909EX_11_A.36

## Steps to reproduce
1. Open Tachiyomi
2. Go to catalogue and open kissmanga

### Expected behavior
It show all manga without any fails or restriction.

### Actual behavior
But it doesn't open as expected and fails to load and says, "no results found".

### Other details
It been going on since 2 weeks. Even the bookmarked manga doesn't load and it says, "page list is empty".

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2496
