### ISSUE TITLE
[Feature Request] There should be easy way to get to menu. 

### ISSUE THREAD

**Issue by Bikeam-tech** [inorichi/tachiyomi#2826]
### Why/User Benefit/User Problem
It always been little hard to go to menu to open extension,catalogue, settings and others. There should be easy way to go there without any effort like just swipe right and the menu part will show. This will help app to be more simple and easy to use.

### What/Requirements
This feature doesn't harm or make difficult for any other user instead it will help them more because just by swiping to right the menu will open. It doesn't require any requirement.
![IMG_20200405_162004](https://user-images.githubusercontent.com/55379619/78472535-58925080-7759-11ea-9383-e5d8f30932a2.jpg)
![Screenshot_2020-04-05-16-18-23-71](https://user-images.githubusercontent.com/55379619/78472546-8c6d7600-7759-11ea-8293-57bb6b1d0e7c.jpg).

Thank you hope this easy feature will be added soon

**Comment by pervertkirito** [comment]
Hamburger menu/navigation drawer is already gone in Dev build
