### ISSUE TITLE
[Feature Request] Short name feature for Tachiyomi AZ

### ISSUE THREAD

**Issue by leoparker157** [inorichi/tachiyomi#2830]
App version : V8.49-AZ
So in NHentai extension have  display manga title feature that display short or full name of Manga , but in tachiyomi AZ , Nhentai has been include so extension not work anymore but it doesn't have that feature so may you add this feature to AZ for convenience ?
### Why/User Benefit/User Problem
Convenience for source migration because Nhentai manga's title so detail that App can't find another version in another Extension .

**Comment by arkon** [comment]
Wrong repo, open it in the AZ repo.
