### ISSUE TITLE
Page sort regression for local source

### ISSUE THREAD

**Issue by raymoo** [inorichi/tachiyomi#2831]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 7.1.2
* Device: Xiaomi Redmi Note 3

## Steps to reproduce
1. Import the attached zip file as a local chapter
2. Open it in the reader and flip through a few pages

## Issue/Request
Previously, local zip files with page numbers for file names worked fine (1.png, 2.png ..., 10.png, 11.png, ...) and were sorted in natural order without leading zeros. After updating to 0.8.5, I found that they are now sorted lexicographically, breaking the expected page order.$

## Other details
Attached zip file has a few images with the page number written. The only contained files are `1.png`, `2.png`, `3.png`, `10.png`, `20.png`, `30.png`.

[order.zip](https://github.com/inorichi/tachiyomi/files/4439233/order.zip)

**Comment by arkon** [comment]
"Previously" as in 0.8.4? This logic hasn't changed since then, I don't think.

**Comment by raymoo** [comment]
I don't remember specifically, but probably 0.8.4 is correct since I install from F-Droid and check updates somewhat frequently.

**Comment by joseph619** [comment]
F-Droid is no longer supported. Uninstall F-Droid version and download from Github to get future update.

**Comment by arkon** [comment]
What @joseph619 said is true, although irrelevant to the issue.

**Comment by joppatza** [comment]
Can confirm, looking at the diff this seems to be the culprit https://github.com/inorichi/tachiyomi/commit/2ebaacfc898a42e87225323281e70518bb36b564#diff-f749ace3f36301931648bbcf94af5ce9R4.

Looks like `naturalOrder` doesn't behave as expected for numbers, as shown by
```kotlin
print(listOf("20.jpg","1.jpg", "10.jpg", "2.jpg").sortedWith(naturalOrder()))
```
which returns `[1.jpg, 10.jpg, 2.jpg, 20.jpg]`. The [docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.comparisons/natural-order.html) suggests comparing by length first, and
```kotlin
print(listOf("20.jpg","1.jpg", "10.jpg", "2.jpg").sortedWith(compareBy<String> { it.length }.then(naturalOrder())))
```
returns `[1.jpg, 2.jpg, 10.jpg, 20.jpg]` as expected.

Latest relevant source would be this I think :
https://github.com/inorichi/tachiyomi/blob/bff927c6eb9c4c9e8c61a01214ca81401816d99b/app/src/main/java/eu/kanade/tachiyomi/util/lang/StringExtensions.kt#L33

**Comment by arkon** [comment]
Geh 😒

Thanks for digging. A PR would be great too, if you want to make one.
