### ISSUE TITLE
[Easy] Reverse order when downloading all chapters

### ISSUE THREAD

**Issue by null-dev** [inorichi/tachiyomi#284]
It would be great if the chapters of a manga would download from smallest to highest when downloading all the chapters of a manga using the menu on the top right and pressing "Download all".

Currently pressing "Download all" downloads the latest chapter first. Making it download the oldest chapter first would allow users to only have to wait for the first chapter to download before beginning to read a new manga.

Thanks for making this awesome app by the way!

**Comment by NoodleMage** [comment]
Thanks for the feedback.

First of all please don't determine if something is easy or not. Maybe the code is written in a certain way which makes it very difficult to implement something that at first glance looks "easy"

As for your issue. If you change the sort order and then select download it will download from oldest to newest.

**Comment by null-dev** [comment]
Well if a simple iteration loop is written in a way that makes this hard, then I would argue that it is bad code.

Anyways, thanks for the clarification, this issue is useless then so I'm closing it.
