### ISSUE TITLE
Error when openig mangas 

### ISSUE THREAD

**Issue by FreakyGamer** [inorichi/tachiyomi#2848]
### Device information
* Tachiyomi version: 0.9.83
* Android version: 9.0
* Device: xiaomi redmi note 8 pro

## Steps to reproduce
1. First step : open mangas in my library
2. Second step : Get an error message " attempt to invoke virtual method java lang string" 

### Expected behavior
There should be the manga name, the cover image and a description 

### Actual behavior
 Neither a description nor a cover image or a name are displayed but the manga can still be read and in the web view it still works 

### Other details
Seems to pass only at mangakakalot. Have already reinstalled the extension.
![Screenshot_2020-04-09-10-24-56-209_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/18227311/78875121-b078d200-7a4d-11ea-9101-6f0d9f01166d.jpg)

**Comment by CarlosEsco** [comment]
This is an extension issue and belongs in the extensions repository.  verify an existing ticket is not open for the extension before opening
