### ISSUE TITLE
Crashes on r687

### ISSUE THREAD

**Issue by inorichi** [inorichi/tachiyomi#285]
Upgrading RxJava to 1.1.2 or 1.1.3 causes crashes somewhere in the app. I don't know if it's my fault or a bug in the library. I can't trace the error, so... can someone using this version that has experienced a crash recently tell me what he was doing and where it crashed?  (it only happens in r687)

**Comment by Rumple007** [comment]
It happened to me when I tried to open a manga from a catalogue

**Comment by inorichi** [comment]
Thanks for the feedback. I'll try to reproduce and fix this locally.
