### ISSUE TITLE
[Bug] Bromite Systemless Webview crashes Tachiyomi when opening in webview

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi#2852]
### Device information
* Tachiyomi version: r1968
* Android version: Pie
* Device: Vivo S1 Pro

## Steps to reproduce
1. Install Bromite Sytemless Webview from the Magisk Manager
2. Attempt to open something in Tachiyomi in webview

### Expected behavior
Open without crashing and load the page using bromite instead of the system webview
### Actual behavior
It crashes tachiyomi

**Comment by arkon** [comment]
We use the standardized Webview APIs. If Bromite doesn't confirm to it for some reason, we can't do much (for such a niche issue).
