### ISSUE TITLE
[Bug] Random Sudden Force Close when Reading, and cant open the tachiyomi again

### ISSUE THREAD

**Issue by Mystery77** [inorichi/tachiyomi#2854]
### Device information
* Tachiyomi version: R1986
* Android version: 9
* Device: LG V30 (H930DS)

## Steps to reproduce
1. Open any manga, any chapter (better with many "next chapter")
2. Read and next chapter, next and next. I dont know when bug will appear, sometimes only after 1 chapter. sometimes many chapter

### Expected behavior
Nothing happens, as it normal reading activity

### Actual behavior
Force Close, Logo Tachiyomi. And cant open tachiyomi app again, except force close it manually from setting.

**Comment by arkon** [comment]
Should be fixed with a combination of 

- https://github.com/inorichi/tachiyomi/commit/0bb6e1cdc2aa6be54e22ff394b99121d4d2062fe
- https://github.com/inorichi/tachiyomi/commit/5d03eef051e6412cff8536441cd343878c53c340
