### ISSUE TITLE
Hardware menu button in reader

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#286]
Pressing hardware menu button in reader should do the same thing as tapping the center of screen (show/hide bottom and top bars)

**Comment by inorichi** [comment]
I don't think so, I use the menu button to switch between apps

**Comment by j2ghz** [comment]
I mean `KEYCODE_MENU`, not `KEYCODE_HOME`

---
tested using http://stackoverflow.com/questions/7789826/adb-shell-input-events

**Comment by inorichi** [comment]
My phone uses menu button to switch apps, but it seems adding this feature doesn't affect the OS behavior (I have to hold the button for the menu to toggle). Since it doesn't break anything, okay.
