### ISSUE TITLE
[Feature Request] Use a three-dot menu (or really anything besides a long tap) to pin or hide sources

### ISSUE THREAD

**Issue by specterflare** [inorichi/tachiyomi#2862]
### Why/User Benefit/User Problem
Long presses often hide functionality from users, as was the case for me with the sources. I only discovered the ability to pin and hide sources because I was long-pressing them to see if I could reorder them.

### What/Requirements
On the far right side of the sources, pass the "Latest" and "Browse" buttons, there would be a three-dot menu. Clicking on it would expand the options "Latest" and "Browse".

**Comment by joseph619** [comment]
You can already hide sources in Browse by clicking Filter and untick any source you don't want to see.

**Comment by specterflare** [comment]
True, but the concept of hiding functionality still applies to pinning them.

**Comment by joseph619** [comment]
Update to latest version of Dev, it's already added. This ticket can be closed.

**Comment by arkon** [comment]
This ticket is about the UX. I'll leave it open.

**Comment by joseph619** [comment]
You're right, he's requesting overflow for the Catalogues, this wasn't requested before.

**Comment by Soitora** [comment]
The only hidden functionality is pinning, which was added U think yesterday.

A solution for that I think would to add a pin button next to sources in the already existing main menu for hiding/displaying sources.
