### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by moopeypoopey** [inorichi/tachiyomi#2868]
Ultmanga source?

---

### Why/User Benefit/User Problem
Dunno where else to ask this but is there an ultmanga catalog?

### What/Requirements
I'm unsure If the mangakakalot source is outdated now that its merged with manga box because manga like one punch man arent loading new chapters, it's just telling me to go to ultmanga.com to read the chapter

**Comment by Matth7878** [comment]
Please respect rules on opening issues.
You did not put a title. Besides it is clearly stated that extensions related issues are not to be opened here but on [https://github.com/inorichi/tachiyomi-extensions](https://github.com/inorichi/tachiyomi-extensions)

For mangakakalot you have to use mangabox extension.
I don't think there is an extension for ultmanga. You have to look on previous link to see if someone has already opened an issue for it before opening one.

I think you should close the issue as it shouldn't be here and as you won't get any other answers here.
