### ISSUE TITLE
[Feature Request] Add option to not enable new sources by default

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2872]
### Why/User Benefit/User Problem
Many users don't like seeing their Catalogues/Sources screen getting new sources every time they update the extensions, especially the multi-source ones like Madara or FMReader which get new sources every week. User would have to disable all the new sources manually one by one, which can be frustrating.

### What/Requirements
Perhaps an option on Catalogues/Sources/Filters screen (inside an Overflow, maybe), with a checkbox/toggle (whichever works/looks better) to not enable new sources by default.

**Comment by arkon** [comment]
I disagree with the proposed UX, but it's easier to manage sources per-extension in preview now.
