### ISSUE TITLE
[Bug] Dev version: Uses NewToki Webtoon default URL instead of new overridden URL

### ISSUE THREAD

**Issue by jinjaabureddo** [inorichi/tachiyomi#2876]
### Device information
* Tachiyomi version: Dev r2028 (e67bb643)
* Android version: 9
* Device: Huawei P20 Pro

## Steps to reproduce
0. Preconditions: Korean > NewToki extension installed
1. Go to More > Extensions > NewToki > Details
2. For NewToki (Webtoon) (KO), click on Override BaseUrl
3. Enter "https://newtoki58.com" and click OK
4. Restart app to apply new settings
5. Go to Sources > Korean > NewToki (Webtoon)
6. Click either on Latest or Browse

### Expected behavior
Should be able to browse webtoon from "https://newtoki58.com"

### Actual behavior
Displayed error with regards to default URL "newtoki47.com"
Exact error: Unable to resolve host "newtoki47.com": No address associated with hostname

### Other details
Screenshots for clearer understanding. Please note that only NewToki (Webtoon) (KO) is affected and not NewToki (KO). Also, since I have both stable and dev versions for comparison, the latest stable version (0.8.5) is able to use the new override base URL without any issue.
![Screenshot_20200415_032530_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/63659537/79266978-f8bf4680-7eca-11ea-9832-94a4ef5e5696.jpg)
![Screenshot_20200415_032603_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/63659537/79267010-04ab0880-7ecb-11ea-8711-da959c1cdfab.jpg)

**Comment by ptoump** [comment]
Confirmed on r2051 too.

**Comment by arkon** [comment]
Can't reproduce. Did you restart the app after setting it?

**Comment by jinjaabureddo** [comment]
yes, restarted many times with same results

**Comment by jinjaabureddo** [comment]
> ~~Can't reproduce. Did you restart the app after setting it?~~
> 
> EDIT: nevermind, I accidentally checked the regular one instead of webtoon.

alright, no prob. glad u manage to simulate it!

**Comment by jinjaabureddo** [comment]
thank you! it works swiftly now ;)
