### ISSUE TITLE
[Bug] Can't add new manga in tracking for Kitsu

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#2878]
### Device information
* Tachiyomi version: r2028
* Android version: 9
* Device: Honor Play 

## Steps to reproduce
1. Select any new manga in the library without tracking on Kitsu
2. Search for corresponding entry in tracking page for Kitsu

### Expected behavior
Thumbnails with search results appear

### Actual behavior
No search results for any query. Just the spin animation. 

### Other details
I have MAL, Anilist, Kitsu and Shikimori tracking. All except Kitsu are working. Fun fact that for already added manga the progress is updated normally. I just can't add new ones. I thought I have problems with access to the host again, but the site still works for me.

**Comment by arkon** [comment]
Kitsu's search is broken on their side.

**Comment by serjflint** [comment]
@arkon Understood. Thank you

**Comment by arun07as** [comment]
@serjflint Just letting you know that kitsu search is working now

**Comment by serjflint** [comment]
@arun07as Thank you
