### ISSUE TITLE
Add readcomiconline.me to the app

### ISSUE THREAD

**Issue by Rumple007** [inorichi/tachiyomi#288]
The site seems to be connected to kissanime so I was wondering if it was possible

**Comment by Soumatan** [comment]
Yeah this would be great. That way I can actually start reading comics. Tho it's readcomiconline.to right now. I think they changed it like kissanime.

**Comment by Neverest** [comment]
Agree, would be nice to have comics too.

**Comment by j2ghz** [comment]
I tried: https://gist.github.com/j2ghz/fe656fc9efe86de6fee6457bc9454170

Couldn't finish (every page gets the image of first page), because I'm getting CAPTCHAs after reading a few chapters while testing. The error `page list is empty` means CAPTCHA in that case.

So even if I finish it, it's possible it will be unusable.

**Comment by Neverest** [comment]
Hmm, since the website is basically a comic version of kissanime.to, would copying the same settings as kissmanga, but changing the relevant info to readcomiconline make it possible to fix it?

**Comment by j2ghz** [comment]
I did, getting the same CAPTCHA error. You can try for yourself, maybe cloudflare marked my IP as suspicious. [Download APK](https://github.com/inorichi/tachiyomi/files/322226/tachiyomi.zip) (it installs separately from release and dev)

**Comment by Rumple007** [comment]
So I just tried it, I tried reading the first chapter of Injustice Gods among us and I managed to read all the pages

**Comment by Rumple007** [comment]
And tried downloading the chapter for online reading and it works

**Comment by Neverest** [comment]
Hehe, you got me  just when I waked up. :)

Gave it a try, and same as Rumple007, it worked fine. Browse some chapters back to back, changed comics, tried webtoon and no problems.

**Comment by j2ghz** [comment]
As @inorichi said, because it can be added with YAML source, he won't be adding it directly. Head over to [wiki](https://github.com/inorichi/tachiyomi/wiki/YAML-Sources) for instructions.
