### ISSUE TITLE
[Feature Request] Parallel Download

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi#2883]
### Why/User Benefit/User Problem
download will proggress much faster if its slow in some site or even if normal it would still get throttled by one site   *(i know got throttle so we dont got banned or that kind)

### What/Requirements
if in download queue we had list from more than 1 site it should start 2 from different site

**Comment by CarlosEsco** [comment]
Feature was removed to prevent people accidentally getting themselves banned.

**Comment by Riztard** [comment]
isnt that only if on the same site?

**Comment by Riztard** [comment]
for example with those sites. if we start both of them and still limit the speed for each site we wouldn't exceed the limited speed for each site, but faster download because download them at the same time
![Untitled](https://user-images.githubusercontent.com/16263232/79629840-ccc7ed80-8176-11ea-8247-b04d51b47514.png)
![Untitled](https://user-images.githubusercontent.com/16263232/79629578-0ac41200-8175-11ea-8519-c61cce9cf30d.png)

**Comment by arkon** [comment]
There's an open issue for that.

**Comment by CarlosEsco** [comment]
Thank you for informing me of how much faster downloading from 2 sites at once could be. I would have never known

**Comment by Riztard** [comment]
ahh my eyes, i didnt see it before.
i thought carlos doesnt understand what i mean before
