### ISSUE TITLE
Dev Build - manga info, amount of chapters.

### ISSUE THREAD

**Issue by Gamingappleh** [inorichi/tachiyomi#2884]
The option or feature return of the amount of chapters in the manga info.(near the author name and status).

- Dev build (r2040) - mentioned as without this feature transfering manga takes a lot longer.

### Why/User Benefit/User Problem
(explain why this feature should be added)

- This would be beneficial as it would give a quick overview of the amount of chapters and allow people transferring to see quickly if the source has the correct number of chapters quickly without having to slide to the right.

### What/Requirements
- Behaves as it did before the removal.

**Comment by arkon** [comment]
It won't be coming back, but those views also aren't finalized.
