### ISSUE TITLE
[Feature Request] Title of single chapter exceeds screen width

### ISSUE THREAD

**Issue by Kavboy** [inorichi/tachiyomi#2891]
### Why/User Benefit/User Problem
Some chapter titles are realy long and the chapter numbers are usually at the end of these titles in most sources. 

Portrait mode of phone
<img src="https://user-images.githubusercontent.com/24781933/79641546-7075c580-8198-11ea-9de9-5c5fc9d9399c.png" alt="Portrait mode of tachiyomi on phone" width="250"/>

Landscape mode of phone
<img src="https://user-images.githubusercontent.com/24781933/79641591-ce0a1200-8198-11ea-8b08-bc27d48d62ba.png" alt="Landscape mode of tachiyomi on phone" height="350"/>

### What/Requirements
The title should be adjusted to the screen, so that the full chapter title is readable with multiple lines if it exceeds the screen width.

**Comment by wopian** [comment]
`android:ellipsize='middle'` should fix this issue for most cases.

**Comment by arkon** [comment]
So I tried doing the middle ellipses and it looks kind of bad. Ideally the titles should be adjusted to have the chapter number first like other sources, or excluding the long manga title itself.

Feel free to submit an issue for the source [in the extensions repo](https://github.com/inorichi/tachiyomi-extensions/issues).
