### ISSUE TITLE
Genre search not triggering when te manga info is opened from updates or history

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#2893]
### Device information
* Tachiyomi version: Version 0.8.5-2064
* Android version: 10
* Device: ASUS_X00TD

## Steps to reproduce
1. Click on updates or history tab
2. Click on the manga thumbnail
3. Click on the genre 

### Expected behavior
Trigger the search fo specified genre in library

### Actual behavior
Nothing happens

**Comment by arkon** [comment]
Not so much a bug, it was just never implemented.
