### ISSUE TITLE
[Bug] Covers not updating like they used to

### ISSUE THREAD

**Issue by SnakeDoc83** [inorichi/tachiyomi#2894]
### Device information
* Tachiyomi version: r2028 and r2064
* Android version: 9
* Device: Samsung Galaxy Tab A

## Steps to reproduce
1. Pull down on the manga info page to refresh cover, but it doesn't.

### Expected behavior
If the source has a new cover, it shows up within a few seconds.

### Actual behavior
The new cover doesn't show up until after restarting Tachi.

### Other details
Someone brought this up in discord yesterday.  They were trying to get a new cover for their manga but they couldn't get it to update by using the pull-refresh method or by clearing their metadata.  They stated that it would only refresh the cover if they removed the manga from their library and then re-added it.  

In trying to reproduce their issue I found that my covers also wouldn't update unless I removed and re-added it or until after I had restarted Tachi.  The initial bug reporter was also on a recent version of dev.  I tested with MangaDex and MangaSee covers and their selectors look fine; so I don't think it's an extension issue.

**Comment by arkon** [comment]
I think this happens in stable too, doesn't it?

**Comment by SnakeDoc83** [comment]
I don't remember it being that way.  I could swear that after pulling down to refresh that the new cover would show up after a few seconds (assuming a new one was available).
