### ISSUE TITLE
[Bug] Update Download Error

### ISSUE THREAD

**Issue by jonathan-alvaro** [inorichi/tachiyomi#2895]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9
* Device: Huawei P20 Pro

## Steps to reproduce
1. Open "Settings" > "About"
2. Tap on Version to Check for Update
3. Download update to 0.8.5

## Issue/Request
Download fails in just a few seconds. This prevents the app from updating automatically.

**Comment by arkon** [comment]
Try getting it from the website instead: https://tachiyomi.org/

**Comment by jonathan-alvaro** [comment]
Ah, it works. For some reason, the problem seems to be connected to my Wi-Fi? The first time I downloaded through the web it returned a forbidden error. But, when I changed to my mobile connection the download completes almost immediately. This might help others in the future so I'll leave it here.
