### ISSUE TITLE
[Feature Request] Link to Tachiyomi.org for Local source 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2896]
### Why/User Benefit/User Problem
Currently, the Browse screen for Local source is empty and users have no idea what it is for or how it works. By linking to local source section in Tachiyomi.org, they would know how to add manga to local source.

### What/Requirements
It should say something like in the Browse screen.

> Local source is empty, visit [https://tachiyomi.org/help/guides/reading-local-manga/](https://tachiyomi.org/help/guides/reading-local-manga/) to learn how to add manga to local source.

**Comment by Soitora** [comment]
Could also be set with an `emptyView` binder
