### ISSUE TITLE
Add french provider

### ISSUE THREAD

**Issue by M2ck** [inorichi/tachiyomi#29]
First of all thank a lot for this great app! For a first release this app is very impressive and promising.

Could you please add a french provider called [japscan](http://www.japscan.com)?
IMO it is the best french provider with lot of choice!

My current manga reader app is not compatible to add this provider so I hope that will be not a problem to you too.

**Comment by inorichi** [comment]
I'm spending most of the time on the core app. I also want to rewrite the base parser, so I don't feel like maintaining another one if I'm going to change it later. I will accept a PR if anyone is up to it.

**Comment by M2ck** [comment]
Well I hope that someone will send a PR, that will be awesome and greatly appreciated! :finger-crossed:

**Comment by M2ck** [comment]
@inorichi regarding [this commit](https://github.com/inorichi/tachiyomi/commit/689f2e7fbf6db323435825f462ce02f435e03848), what's new about this related request, still not possible currently?

**Comment by inorichi** [comment]
It's possible, but I haven't rewrite the parser yet, so still the same reply, sorry. Priority now will be backups, then reader (migration to Kotlin) and I will work on the base parser after that.

**Comment by M2ck** [comment]
Ok thanks for let me know!

**Comment by na-ji** [comment]
I can add a parser for Japscan, but should-I wait for the parser update ?

**Comment by inorichi** [comment]
I would wait for the update. It would break soon :)

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
