### ISSUE TITLE
Import manga from debug version to official version.

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#290]
Can you allow this? I'd like to use the official version but re-adding all the manga and then losing what chapters i've read is such a pain in the ass.

**Comment by inorichi** [comment]
You can already do that with 0.2.1 and debug. Just backup in one place and restore in the other.

**Comment by shogunreaper** [comment]
well i did that and now all my manga is broken

it just gives me a retry button and wants me to redownload everything...

**Comment by inorichi** [comment]
Probably related to a change in 0.2.0:

Downloaded images now use 3 digits for ordering with other apps (#181). This change makes previous downloaded chapters incompatible with 0.2.0

I don't know if there's a tool to rename images to 3 digits

**Comment by shogunreaper** [comment]
why didn't you keep compatibility with both?

**Comment by inorichi** [comment]
Because Tachiyomi is still in beta stage and I don't want to complicate the code with retrocompatibility.

**Comment by shogunreaper** [comment]
and breaking everyone's mangas is better?

**Comment by shogunreaper** [comment]
and this isn't just a simple load up a program and bam it renames everything perfectly

you'd need to know regex to rename all the files unless you want to be doing it for hours by hand.

**Comment by j2ghz** [comment]
how about downloading it again?

**Comment by shogunreaper** [comment]
i have dozens of mangas and limited bandwidth.

**Comment by shogunreaper** [comment]
so you're not going to try and fix this?

**Comment by NoodleMage** [comment]
We are no going to implement/fix this. Inorichi has given you an explanation why. 

I know it can be anoying but it is clearly indicated that the application is still in a beta stadium which means that changes won't be backward compatible.

**Comment by shogunreaper** [comment]
then why not have the app itself change the page numbers?

**Comment by NoodleMage** [comment]
> Because Tachiyomi is still in beta stage and I don't want to complicate the code with retrocompatibility

This ^^

**Comment by j2ghz** [comment]
If it's such a big problem to redownload, then use the old version.

It was clearly stated in the changelog that `This change makes previous downloaded chapters incompatible with 0.2.0`

**Comment by inorichi** [comment]
You can also compile the APK reverting this commit 492a24e. Or connect your device to your PC and use a bulk renaming tool, with a quick search I found this: http://www.bulkrenameutility.co.uk/forum/viewtopic.php?t=358 and this http://www.rlvision.com/flashren/manual/func_zero_padding.html

The later looks simple, but I haven't tried

**Comment by shogunreaper** [comment]
flash renamer worked, thanks.
