### ISSUE TITLE
[Bug] The size and font of the resume and filter FAB changes when it extends/collapses

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#2900]
## Device information
* Tachiyomi version: r2076
* Android version: 10
* Device: ASUS_X00TD

## Issue/Request
The size of the resume FAB changes when it extends/collapses, it looks neater when the size of the FAB is consistent like google messeged and contacts and also the font would look better if it was bold

## Other details
![Screenshot_20200419-140637](https://user-images.githubusercontent.com/46787056/79683523-4ed41700-8248-11ea-9350-84d0bb6ab2ed.png)

https://github.com/imtuann/FloatingActionButtonExpandable

![image](https://github.com/imtuann/FloatingActionButtonExpandable/blob/master/art/FloatingActionButtonExpandable.gif?raw=true)

**Comment by arkon** [comment]
I don't have the extended FAB in Google Messages so I can't speak for that, but I'm pretty sure this is a bug upstream in Material Components.

**Comment by aakash37** [comment]
![ezgif-4-f17e1ebf2a8b](https://user-images.githubusercontent.com/46787056/79695170-e0687680-8292-11ea-9185-c816a7052002.gif)
 The fab on Google message btw I'm running Version 6.0.110 (Xorn_RC03.phone.openbeta_dynamic) of the app

**Comment by Soitora** [comment]
Can confirm, Tachi FAB janks slightly while the GMesseger one  goes smoothly. 

Also while on FAB topic, maybe the text could use a font weight _slightly_ thicker

**Comment by vengiare** [comment]
Weird. I've tested this on Google Contacts and the FAB actually janks slightly.

**Comment by Soitora** [comment]
After doing some testing it seems that the default style has a default `android:minHeight=48dp`, when I set it to match the given layout width/height (in this case I used a manual `56dp`), it acted normally.

https://github.com/inorichi/tachiyomi/blob/415df2357c85d3f742547f99869ff8e84536678c/app/src/main/res/layout/chapters_controller.xml#L52-L57

https://github.com/inorichi/tachiyomi/blob/aedb4749a214e49695d4ef2fae1cb0674814339d/app/src/main/res/layout/source_controller.xml#L29-L35

**Comment by aakash37** [comment]
will it be possible to make the animation in the shape of a pill for the extented fab

currently it looks a little out of the place
![2](https://user-images.githubusercontent.com/46787056/79972474-a32eff00-84b3-11ea-8af4-77141b203e21.png)
![1](https://user-images.githubusercontent.com/46787056/79972489-a75b1c80-84b3-11ea-9b23-e541a6f1fee5.png)

**Comment by arkon** [comment]
Having a pill animate out would be weird since the width would expand faster than the height.
