### ISSUE TITLE
[Bug] Unreachable code

### ISSUE THREAD

**Issue by TacoTheDank** [inorichi/tachiyomi#2903]
These are not in-app bugs, though it could definitely cause some.

There are two pieces of unreachable code (functions) in the project, and one error-causing mismatch (technically four).

Unreachable code:
- PagerViewer.kt, lines [141-158](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt#L141)

- WebtoonViewer.kt, lines [126-144](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt#L126)

Erroring type-mismatch:
- ChaptersPresenter.kt, lines [175-182](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt#L175)

I noticed these while I was doing the lint fixing. Thanks in advance.

**Comment by arkon** [comment]
I took a brief look at it seems to be issues with how Kotlin's doing the checks. The logic is fine (i.e. the code is reachable and the types are technically fine).

**Comment by TacoTheDank** [comment]
Hmmm...
