### ISSUE TITLE
[Feature Request] Mark all as read from My Library

### ISSUE THREAD

**Issue by jmengelle** [inorichi/tachiyomi#2904]
I juste migrate from Manga Rock to Tachiyomi, and i have a few undred manga in my library. 
Problem : all of them shows as unread, and it seems  i can't change that with bulk opération.

So for each manga i have to : 
- open
- scroll to last chapter (a scroll to top/bottom would also be nice here)
- mark as read
- mark previous as read

It would be great to have the ability to mark a whole manga as read from My Library view, and of course to do so on multiple selection.

**Comment by loocool2** [comment]
Already been considered and denied

**Comment by CarlosEsco** [comment]
No. And you can long press any chapter click select all then mark as read.

**Comment by arkon** [comment]
I don't actually disagree with being able to mark as read from the library, but there's another open issue for it.
