### ISSUE TITLE
[Bug] Wrong order of pages when moving forward/backward

### ISSUE THREAD

**Issue by Disasm** [inorichi/tachiyomi#291]
Verson: 0.2.1
Device: GT-N8000
OS: stock Android 4.1.2
Steps to reproduce:
* Go to "Mangahere (EN)" catalog
* Search for "Tamen De Gushi" manga
* Add to the library
* Open manga from the library
* Download "Tamen De Gushi 6", "Tamen De Gushi 7" chapters
* Open chapter 6, scroll up to its end (page 4/4)
* Scroll forward (you will see chapter 7 page 1, with text "8 minutes later")
* Scroll forward chapter 7 up to the beginning of chapter 8 (inclusive).
* Scroll back (you will see chapter 7 page 1, with text "8 minutes later")
* Scroll back (you will see chapter 6 page 1)
* Scroll forward till the end of chapter 6 (page 4/4)
* Scroll forward (you will see chapter 7 page 1, but it really will be page 3 with text "teacher, they are ...")

Is it OK to see page 1 from previous chapter when scrolling backward from the next chapter? Maybe it will be better to see last page from the previous chapter instead of the first page.
It's definitely not OK to see page "n" instead of page 1 when scrolling forward from the end of the previous chapter.

The same behavior have been reproduced on GT-N7100, CyanogenMod 11 (Android 4.4.4), app version 0.2.1.

**Comment by inorichi** [comment]
Thanks for the detailed explanation. Can you confirm if this issue is fixed now?

**Comment by Disasm** [comment]
Sorry, I can't build it for now. I will test it as soon as new version will become available in F-Droid (or if you give me .apk file somehow).

**Comment by j2ghz** [comment]
Download apk: https://teamcity.kanade.eu/viewType.html?buildTypeId=tachiyomi_Build
Download apk direct: http://tachiyomi.kanade.eu/latest/app-debug.apk
Dev F-Droid repo: https://github.com/inorichi/tachiyomi/wiki/FDroid-for-debug-versions
all three are linked in README.md

**Comment by Disasm** [comment]
j2ghz, thank you. My fault.
This issue seems to be fixed now.
