### ISSUE TITLE
[Feature Request] Source migration option inside mangar chapter list

### ISSUE THREAD

**Issue by claudio4** [inorichi/tachiyomi#2910]
### Why/User Benefit/User Problem
this option simplifies the workflow for changing the source the open manga, this especially useful when suddenly the source you are using starts using bad quality scans (or translations) and you go in search of a better source.
### What/Requirements
Add “Migrate source” button on the3-dot menu in the chapters list, touching this button will directly show the migration options for the manga.

**Comment by aakash37** [comment]
Same as #1903
