### ISSUE TITLE
[Bug] Some extensions have thumbs spacing off

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#2917]
### Device information
* Tachiyomi version: dev r2092
* Android version: 8.1.0

### Other details
Some extensions have different thumbs spacing than other extensions (& Library)
![Screenshot_Tachiyomi_20200421-163804~01](https://user-images.githubusercontent.com/63973749/79846225-c349ba00-83f0-11ea-9499-d0413ca5d6ba.png)

Saw these in 3 extensions (I have only 4 total)
Manga Box 1.2.18
MangaDex 1.2.88
NHentai 1.2.19

Looks okay in MangaPlus:
![Screenshot_Tachiyomi_20200421-163951~01](https://user-images.githubusercontent.com/63973749/79846826-7adecc00-83f1-11ea-8b42-83ced059335f.png)

**Comment by Soitora** [comment]
Seems to be caused by this: https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceController.kt#L201-L212

Removing that in local enviroment made padding the normal again.
