### ISSUE TITLE
[Bug] Page list is empty

### ISSUE THREAD

**Issue by erik1844** [inorichi/tachiyomi#2919]
### Device information
* Tachiyomi version: 8.5
* Android version: 7.0
* Device: Samsung Galaxy 6s Edge

## Steps to reproduce
1. First step: Open tachiyomi
2. Second step: Reload to see if there are updates and select manga and proceed to read.

### Expected behavior
This should happen: Opens manga and read it.

### Actual behavior
This happened instead: Open manga of preference and it says page list is empty.

### Other details
I had this problem before and it just fixed itselfe one day and i dont know how, and it wasnt an update.

**Comment by arkon** [comment]
Check if the website even works first.
