### ISSUE TITLE
Mangabox aint working

### ISSUE THREAD

**Issue by Formulq** [inorichi/tachiyomi#2920]
For some reasons, I cant access the chapters of the mangasites in mangabox. It always says timeout when I try to read a chapter. Most or all of the sources from mangabox does this pls fix this

**Comment by Applewubs** [comment]
I tried reading ir online, but the page of the extensión that i read has the 500 internal error thing. I think Is an error from the server

**Comment by arkon** [comment]
Their servers are overloaded. We can't help you with that.
