### ISSUE TITLE
[Feature Request] Write short description here :

### ISSUE THREAD

**Issue by ningenshot** [inorichi/tachiyomi#2921]
Hey developers,
What if the app had a feature to download the chapters of a manga from certain range?

Like:i downloaded 450chapters of one piece and read it.so for some reason i deleted it.now i want to download chapters 451 to 900.how should i do it?
is there a feature to do that?
please think abt it in the next update.

**Comment by arkon** [comment]
It's already in dev.

1. Long press chapter 451
1. Long press chapter 900
1. Press download in bottom menu

**Comment by ningenshot** [comment]
thanks
