### ISSUE TITLE
[Feature Request] Option to open manga chapter info page from recently read section

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi#2923]
### Why/User Benefit/User Problem
While reading if i left in between without adding it to favourite next time when i want to read i want to open chapter info page whatever reason (jump to later chapter, set to favourite etc) right now we can continue from where we left we cant open manga info page

### What/Requirements
Adding small icon similar to ⓘ on recently read manga will take directly to it's info page.

**Comment by arkon** [comment]
Tap the cover.

**Comment by shashank-p** [comment]
> Tap the cover.

I still believe there should be something that notify there is feature like this (small icon on cover)

**Comment by arkon** [comment]
I made the whole card go to the manga instead.

**Comment by shashank-p** [comment]
It's fine then I guess
