### ISSUE TITLE
[Feature Request] Update FilePicker

### ISSUE THREAD

**Issue by TacoTheDank** [inorichi/tachiyomi#2927]
https://github.com/inorichi/tachiyomi/blob/master/app/build.gradle#L221

https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/CHANGELOG.md

Thanks for the dedication to this app. We all appreciate it greatly. It really is the best reader out there. Happy almost-7K stars!

(This would probably have an enhancement tag instead of the feature request tag tbh)

**Comment by arkon** [comment]
Potentially superseded by #2671

**Comment by TacoTheDank** [comment]
Ah, yeah. So the file-picker itself is going to be removed, then. Will anything replace it?
