### ISSUE TITLE
Japscan extansion problem

### ISSUE THREAD

**Issue by ditrimi** [inorichi/tachiyomi#2930]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10
* Device: Galaxy S10
* japscan version : 1.2.20

## Steps to reproduce
1. Install Tachiyomi
2. Install japscan extansion
3. Search a random manga
4. It doesn't lord
5. Button Retry si always here

## Issue/Request
I tried with my phone and my tablet.
I tried 3 mangas

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues?q=is%3Aissue+is%3Aopen+japscan
