### ISSUE TITLE
[Small Bug] Letter Icons don't appear

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#2934]
### Device information
* Tachiyomi version: r2112
* Android version: 8.1.0

![Screenshot_Tachiyomi_20200423-102417](https://user-images.githubusercontent.com/63973749/80052404-31a38f00-854d-11ea-9b2c-0f44cac4b153.png)
![Screenshot_Tachiyomi_20200423-102328](https://user-images.githubusercontent.com/63973749/80052397-2d777180-854d-11ea-9821-ad8fa8a0b485.png)

**Comment by TacoTheDank** [comment]
Knew I might've messed something up, luckily it wasn't anything auper important
