### ISSUE TITLE
[Feature Request] Hidden Default Category

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi#2936]
### Why/User Benefit/User Problem
Most of us have some webtoon or manga which we don't want other people to find out when they accidentally use our phone for such instances we need hidden default category which will contain such manga or webtoons.

### What/Requirements
It should be something like when app opens it should not be visible but it should be displayed while adding favourite dialog. It should be visible only if it's made visible by user from setting (toggle button or fingerprint authentication) by default it should be hidden

**Comment by arkon** [comment]
The UX for this seems to cumbersome and belongs more in the porn-specific forks. There's already the biometric lock for the entire app anyway.

See #1508 for a workaround.
