### ISSUE TITLE
[Bug] Chapter updates takes time

### ISSUE THREAD

**Issue by Ksetrar** [inorichi/tachiyomi#2938]
Device information
* Tachiyomi version: ?
0.8.5
* Android version: ?
8.1.0
* Device: ?
Oppo A5s

The manga gets updates but the chapter/s do not show up, it takes a matter of 20 - 30 mins to show the updated manga chapter

The screen is at night mode, attached video screenshot
https://files.catbox.moe/wa41oq.mp4

**Comment by Ksetrar** [comment]
When we click on latest release we get the latest update series with the newly added chapter right ?

But some, even if the manga gets updated, the chapter do not shows up, but it do shows up later time like 30 mins or 1 hours

**Comment by arkon** [comment]
Did you check if the site actually shows the chapters?

**Comment by Ksetrar** [comment]
No do not check the site but I check the manga in latest release again after sometime and the new chapter showup

**Comment by arkon** [comment]
Can you double check the next time you notice it? It could either be the app caching it (to avoid using a lot of data), or the site itself not working as intended (which has also happened before).

**Comment by Ksetrar** [comment]
I will check it today and I will notify you.

**Comment by Ksetrar** [comment]
This can be closed
The host site has the issue
