### ISSUE TITLE
Filter for manga not linked to myanimelist

### ISSUE THREAD

**Issue by Snake87r** [inorichi/tachiyomi#294]
Like the title said:
add a filter in the manga list with all the manga not linked to MyAnimeList so you can search and link the manga to animelist Faster then before.

**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by inorichi** [comment]
The new tracking tab will show a tick when a manga is linked, that way you will know at first glance if it's linked when you are in the chapters tab.

You still have to open every manga, but a filter for that in the library isn't a good idea. The library doesn't know anything about tracking services (and I don't want to add that overhead).
