### ISSUE TITLE
Bug on reading chapters according to its chapters

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi#2940]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 6.0.1
* Device: Vivo Y53

## Steps to reproduce
1. I would like it if you guys can sort according to the chapters not by the source
2. Also i would like it if you guys make the selecting option not one by one but by multi choosing
3. Please remove the sort by source option to remove confusion to readers when the chapters is not working according to its acsending or descending order

### Expected behavior
Right order to read/organized. Like when i read chapter 1 the next is chapter 2

### Actual behavior
When i read some manga its not going according to its chapter its skipping some of the chapter its not organize. Like it goes from chapter 1 to chapter 4 then to chapter 8

**Comment by arkon** [comment]
There's already a sort by chapter number option, so I'm not really sure what you're asking for.

Sorting by source can be a valid option depending on the source, it's not going to be removed.

**Comment by Ksetrar** [comment]
`When i read some manga its not going according to its chapter its skipping some of the chapter its not organize. Like it goes from chapter 1 to chapter 4 then to chapter 8`
This might be as have already read the chapter or the manga is not downloaded, I faced this once so I replied

**Comment by CarlosEsco** [comment]
as arkon stated the sort is not a bug.  you change the sort order at the top.  another option is use a source that actually sorts their chapters correctly
