### ISSUE TITLE
[Feature Request] requests about convenience 

### ISSUE THREAD

**Issue by bakezo** [inorichi/tachiyomi#2942]
I would like to suggest a couple of features for this app. I am one of the people who migrated from manga rock after it’s death. So far it’s been good, but i had a problem with how inconvenient the update list and library. For example, let’s say a manga decided to update with 7 new chapters, i don’t like how in the update list it shows each update individually. my suggestion is when you click on the update section, it would show the only the name of the manga and when you click on it, it would show the seven new updates, instead of it being one big list. Second is the library, i’d suggest putting the newly updated mangas directly to the top so we don’t have to scroll through 400 other mangas to find it, it takes a lot of time and it’s very annoying. Third, adding a recommended section and adding custom filter when trying to find something to read, it basically allows you to pick more than one type of genre. Lats but not least is the recently read option, for example, i read “tower of god” in mangarock and after it’s death i decided to use your app, being the lazy kid that i am, i decided to immediately go to the last chapter i read. and let’s also say i stopped reading to do some homework. Then, I decide to read again, so i click the resume button, but it didn’t actually resume. it went back to the first chapter because it wasn’t “read”. i really hate that, i would suggest fixing the option to actually do its job, when i click on a different chapter and leave and decide to go back again, it would be nice to use that option to go back to the chapter i clicked. 

---

i think a lot of people would appreciate the suggestions i made since it’s all about convenience, and it would benefit the aesthetic of your app

I hope you read and understand my suggestion because it would benefit me and you guys as well. Mangarock was known for it’s amazing extension list and convenience. You have the extension list, but the app is still far away from being convenient

**Comment by arkon** [comment]
Please follow the issue templates next time and keep it to 1 thing per issue. They make them easier to read and manage.

---

1. This introduces more steps, which I'm not a fan of. Grouped notifications sort of already address that, unless you dismiss them.
2. There's an open issue for that already. You can also sort so updates are on top.
3. Recommendations aren't feasible with how we surface content. MR could do it since they scraped and hosted everything on their own systems.
4. I think there's an issue for that but I'm not sure. Feel free to open a separate one.

**Comment by tomodachikezo** [comment]
Sorry for the multiple issues, I think the recently read feature is my main problem with the app,  I can sort of deal with the other issues, I just don't like the fact that I have to mark every single chapter that Ive already read. I'll go make a bug issue request to make it easier to read. Thanks for the explanation!
