### ISSUE TITLE
[Feature Request] Auto chapter tracking

### ISSUE THREAD

**Issue by Ksetrar** [inorichi/tachiyomi#2943]
### User Benefit
1. Users do not have to add the manga manually in the signed tracking sites.
2. No manual adding of chapter. [Its damn irritating]

### Requirements
1. User must add the manga in the library.
2. The tracking account must be signed in or else there will be no auto adding of manga.
3. Have to read chapter fully or mark as read or else the chapter will not be marked as readed in the tracking sites.

**Comment by pervertkirito** [comment]
1) how to verify that it's the correct manga? MAL for example, have(or none) small number of manwha & manhua in the database. What if it linked to wrong title... this will cause disaster.

2) go to settings > tracking > enable sync chapter after reading. This is self explanatory ig.

**Comment by arkon** [comment]
Yup, the first point about actually having the right manga was the main issue whenever this was brought up in the past. It's still not a non-trivial thing to solve.
