### ISSUE TITLE
[Bug] The number of pages read always appears in blue, no matter whether chapter is bookmarked or not

### ISSUE THREAD

**Issue by specterflare** [inorichi/tachiyomi#2946]
### Device information
* Tachiyomi version: r2112
* Android version: 10
* Device: Pixel 3

## Steps to reproduce
1. Bookmark any chapter you have read part of

### Expected behavior
The pages read the dialogue for that chapter and only that chapter should turn blue.

### Actual behavior
All subsequent pages read will be blue

**Comment by arkon** [comment]
> The pages read the dialogue for that chapter and only that chapter should turn blue.

Either my brain is farting or this sentence actually doesn't make sense. Can you elaborate?

**Comment by arkon** [comment]
Nevermind, I got what you mean. I changed it to grey for the next preview build.
