### ISSUE TITLE
[Bug] Mangadex WebView is broken

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#2947]
### Device information
* Tachiyomi version: r2112
* Android version: 9
* Device: Honor Play
* WebVew: 81.0.4044.111

## Steps to reproduce
1. Open WebView for Mangadex library entry

### Expected behavior
Normal mobile view

### Actual behavior
![Screenshot_20200424_091710_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/4900246/80174742-0d0eec00-860d-11ea-8e6d-d5a47c30e5bc.jpg)

### Other details
Not sure if it an issue with an extension or the WebView itself, so I post it here. Other sources work fine. I tried rebooting and cache cleaning.

**Comment by serjflint** [comment]
Stable is broken, too. Firefox opens it normally.

**Comment by pervertkirito** [comment]
this should probably Webview itself, did you clear cache for webview too?

**Comment by serjflint** [comment]
@pervertkirito how to do it? I cleared the app cache but I don't see an option for the web view specifically.

**Comment by pervertkirito** [comment]
webview is an app and separate from tachiyomi.
Go to android setting, find app called _Android System Webview_ and try clear cache there
![Screenshot_20200424-141518](https://user-images.githubusercontent.com/27921916/80180812-20827d00-8636-11ea-83e4-4381ff6ab6dd.png)

**Comment by serjflint** [comment]
There is no such app in system settings and Play Store says it is disabled with no buttons to enable it.

**Comment by e-shl** [comment]
https://github.com/inorichi/tachiyomi/issues/2309

**Comment by serjflint** [comment]
It was perfectly normal less than 2 weeks ago

**Comment by rama982** [comment]
My webview is perfectly fine.

**Comment by serjflint** [comment]
WebVew 81.0.4044.111. For me it looks like CSS is not loading properly. Don't want clear all data, because restoring backup in over 1k entries is a drag.

**Comment by arkon** [comment]
Webview is indeed a separate app that we don't control.

**Comment by serjflint** [comment]
It was the issue with the ISP and was resolved by itself after some time. Seems like some assets were blocked but could be downloaded using VPN.

**Comment by arkon** [comment]
This was also "fixed" after noticing some assets failed to load in webview when not on the `www` subdomain.
