### ISSUE TITLE
MangaBox Browsing/Latest Error 404

### ISSUE THREAD

**Issue by TooLazyForThis** [inorichi/tachiyomi#2949]
#2642 # Device information
* Tachiyomi version: 0.8.5
* Android version: Android 10
* Device: Galaxy Note 8

## Steps to reproduce
1. Have mangabox extention
2. Open catalogues page
3. Click latest or browse 

### Expected behavior
Popular or most recently updated manga should pop up and be visible.

### Actual behavior
Blank and a bar at the bottom saying "HTTP Error 404"

### Other details
At the time, manga chapters could still be readable.

**Comment by arkon** [comment]
Wrong repo.
