### ISSUE TITLE
Chapter list is always empty until it is refreshed

### ISSUE THREAD

**Issue by poodle13** [inorichi/tachiyomi#2952]
### Device information
* Tachiyomi version: Preview r2112 (6d5b6b2f)
* Android version: 10.0
* Device: Redmi 7A (pine) Rom - Mokee open source

## Issue/Request
The chapter list is always shown as empty even though you have read the chapter just until a few seconds before. And the app caches are cleaned even tried to reinstall the app. And even tried to delete the the manga and then add it again. The issue is not only with one specific manga but all over the app.

## Other details
![Screenshot_20200424-200053](https://user-images.githubusercontent.com/64269147/80223757-593a4a80-8666-11ea-9f89-6259f7b87e25.jpg)

**Comment by CarlosEsco** [comment]
Does this happen on all sources or just one?

**Comment by poodle13** [comment]
> Does this happen on all sources or just one?

Yep to all.

**Comment by arkon** [comment]
I believe this was fixed.
