### ISSUE TITLE
Create pdf or zip file for downloaded chapter

### ISSUE THREAD

**Issue by SanOtaku09** [inorichi/tachiyomi#2956]
Create pdf or zip file for downloaded chapter

### Why/User Benefit/User Problem
By adding this feature users will be able to share chapters.

### What/Requirements
Instead of creating a folder with chapter images create a pdf with chapter images

**Comment by arkon** [comment]
There's an open issue for storing downloaded chapters as compressed archives for the goal is saving space, which is a valid request.

I don't think doing so for the purpose of sharing content is really in scope of this app.

PDFs definitely aren't in scope, considering the app doesn't handle them anyway.

**Comment by arkon** [comment]
(You can easily create ZIPs using file manager apps anyway)
