### ISSUE TITLE
[Bug] Restore Error

### ISSUE THREAD

**Issue by apatel190** [inorichi/tachiyomi#2958]
#2642 # Device information
* Tachiyomi version: 0.8.5
* Android version: 10.0
* Device: Samsung Galaxy A50

## Steps to reproduce
1. Restore with .json file
2. Gives An error
3. (I don't know what else to put)

### Expected behavior
The Restore should restore all mangas

### Actual behavior
It gives an error saying that all mangas haven't been restored successfully

### Other details
I do have 10 different extensions and I am trying to transfer from mangarock to tachiyomi. The .json file is included below as well as the log.
[tachiyomi_restore[1].log](https://github.com/inorichi/tachiyomi/files/4532943/tachiyomi_restore.1.log)

https://drive.google.com/file/d/1bcC67zMfHKUTz9_QA3XRKRa4PlEE_55X/view - .json link as I cannot post it in github

**Comment by arkon** [comment]
You'd get more help on Discord for this sort of thing.

The logs say you don't have the source installed and it looks like the MangaRock ID.

Have you installed Dummy Rock? The guide also states to use the J2K fork to do this so you can use auto migration, which Stable 0.8.5 doesn't have.

**Comment by apatel190** [comment]
I fixed this issu by using J2K fork thanks!
