### ISSUE TITLE
[Bug] "Blank" posters shows random poster from current view

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#296]
When scrolling up, the first poster in top-left lazyloads a poster that was loaded in previously - instead of the correct poster. Scrolling down different amounts changes what the poster will be each time.

This seems to happen most when you scroll down before the posters are shown on initial opening of the category. You're unable to get the correct poster until a restart.

Example:
https://gfycat.com/IllfatedHopefulCobra

Edit: It's not always the top-left poster. Blank poster at the very bottom will show a random poster when it gets out of view.

![](https://i.imgur.com/maekEYG.png)

---

Version: r704
6.0.1 (CM13)

**Comment by wopian** [comment]
Seems to be caused by canceling the updater - those posters (and some others in other categories which start before **B** are missing posters - which the recycler is putting an already loaded poster in.

**Comment by j2ghz** [comment]
#187 related?

**Comment by wopian** [comment]
Probably. But this isn't happening under the conditions you've mentioned. >2.5gb of RAM was free.

**Comment by inorichi** [comment]
How is it now?

**Comment by wopian** [comment]
Fixed in 706 - blank posters remain blank.

However the only way to fix the blank covers is to manually download the posters from the source and edit the poster.

**Comment by wopian** [comment]
Edit: only some posters have that issue - most manga that had blank posters have their proper posters in 706.
