### ISSUE TITLE
[Bug] New debug builds not on index site 

### ISSUE THREAD

**Issue by TacoTheDank** [inorichi/tachiyomi#2960]
Either the builds are messing up somehow during the process, or maybe some key expired, idk. New builds aren't appearing on the https://tachiyomi.kanade.eu/ site. At least 30 new commits have been made since the last build.

**Comment by arkon** [comment]
They're weekly builds now rather than triggering on every push.

**Comment by TacoTheDank** [comment]
Oh... huh, ok. Ant8 reason why this changed?

**Comment by arkon** [comment]
To avoid having a ton on builds since I tend to push often. Helps reduce load on the server that's hosting all of the build too.

**Comment by qiforra** [comment]
When exactly the weekly build is released?
Which day?

**Comment by CarlosEsco** [comment]
Does it matter if you have auto updates enabled
