### ISSUE TITLE
[Bug] Cannot access Mangadex menus to login in webview

### ISSUE THREAD

**Issue by Rzmydz** [inorichi/tachiyomi#2963]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9
* Device: Nubia Red Magic Mars (NX619J) 

## Steps to reproduce
1. open tachiyomi 
2. Navigate to catalogues > mangadex
3. Tap top right menu to access webview
4. Tap top left menu to try and log in

### Expected behavior
Log in menu appears

### Actual behavior
Menu button highlights in orange indicating it has been tapped but no log in menu appears

Before doing anything in webview
![Screenshot_20200426-094246](https://user-images.githubusercontent.com/64363920/80309582-f3ec7380-87a3-11ea-8eef-17fe81132f4c.png)

Tapping menu in webview
![Screenshot_20200426-094251](https://user-images.githubusercontent.com/64363920/80309591-08307080-87a4-11ea-8db2-92f7c7e6f88b.png)

### Other details
Menu and login works fine in browsers, but not webview

**Comment by arkon** [comment]
Have you tried updating your webview app?

**Comment by Rzmydz** [comment]
The webview app is tachiyomi itself, no?

**Comment by CarlosEsco** [comment]
No tachiyomi opens the systems webview

**Comment by arkon** [comment]
Unfortunately I don't have any suggestions beyond that. We can't control whether your webview browser works properly or not.
