### ISSUE TITLE
Tachiyomi - Back up Issue

### ISSUE THREAD

**Issue by MylesYoung22** [inorichi/tachiyomi#2967]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 8.0.0
* Device: Moto E5 Play

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
On my old phone I backed up my tachiyomi so that I could restore the backup to my new phone. The problem I am having right now is that it keeps stopping at like 6% when I restore it. I've tried to clear the cookies on tachiyomi and forced close the app but none of it helps. 

## Other details
I'm not sure what other details are needed but I'd appreciate if someone can get back to me as soon as possible.

**Comment by serjflint** [comment]
There should be a log in case of an error. Try to check your connection, too. There might be sources that are not available with your ISP and cause you an error. In my case I need to use VPN to get kitsu tracking to work.

**Comment by arkon** [comment]
Try again with 0.9.0.
