### ISSUE TITLE
[Bug] KissManga : Unable to navigate the catalogue 

### ISSUE THREAD

**Issue by LightDestory** [inorichi/tachiyomi#2969]
I am sorry for this poor issue style, I am right now in a smartphone. 
I have installed the latest Kissmanga extension but it seems that doesn't work, both latest and popular tabs are empty. 

(I will do a better issue styling as soon as I am I can get a pc)

Regards Lightdestory.

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi-extensions/issues/2496

KissManga tends to block users that are bypassing their ads (e.g. this app). We recommend migrating to different sources.
