### ISSUE TITLE
[Bug] Icons not showing up on Light Blue Theme

### ISSUE THREAD

**Issue by Badaro** [inorichi/tachiyomi#2970]
### Device information
* Tachiyomi version: Preview r2152
* Android version: 10
* Device: Moto One Action

## Steps to reproduce
1. Go to Settings -> General 
2. Ensure you're using "Light Blue" theme
3. Go to your Library
4. Press and hold over a manga or chapter

### Expected behavior
A bar should appear at the bottom of the screen with the action icons (Download/Delete, Boorkmark, Mark as Read/Unread, Mark Previous as Read).

### Actual behavior
The bar appears, but the icons are not visible. If you click on the position of the icon it still performs the expected action.

### Other details
Comparison of "Default" and "Light Blue" themes attached below.

Defaut:

![light-default-theme-correct-icons](https://user-images.githubusercontent.com/807722/80332379-153f7500-8821-11ea-80ad-0aeeb053fe9e.png)

Light Blue:

![light-blue-theme-missing-icons](https://user-images.githubusercontent.com/807722/80332375-12dd1b00-8821-11ea-802f-9c393204e6d4.png)

**Comment by arkon** [comment]
Thanks for the report! This was fixed in https://github.com/inorichi/tachiyomi/commit/27871161718acb2296a5f7136394937698ce4d0e and will be part of the next build.
