### ISSUE TITLE
[Bug] Tracking with MyAnimeList updates the number of times the series has been reread.

### ISSUE THREAD

**Issue by Blenji** [inorichi/tachiyomi#2971]
### Device information
* Tachiyomi version: Dev, preview r2152 (Bug was present prior to updating to latest version)
* Android version: Latest version
* Device: Samsung Note 9

## Steps to reproduce
1. Track manga using MyAnimeList (have not tried other tracking websites)
2. Either read any chapter, or manually set the number of chapters read.

### Expected behavior
Tachiyomi should update your MyAnimeList and track the chapters you read as it happens. 

### Actual behavior
The above happens, but additionally Tachiyomi sets the number of times you've reread the series to the number of chapters you read. 

### Other details
An example is Senryuu Shoujo, which currently has 163 chapters translated into English. I just recently decided to track the number of chapters I've read, but noticed my "Reread" section on MAL had several hundred instances of me rereading manga, when I've never done so. This but artificially inflates the number of chapters you've read on MAL, and as there is no convenient way to check/change which series you've reread, I'm forced to not track any manga at all.

**Comment by arkon** [comment]
@ITALIA195 This likely has to do with the recent start/end date edit page change?

**Comment by ITALIA195** [comment]
Yep, my bad. Typo on [MyAnimeListApi@Line 342](https://github.com/inorichi/tachiyomi/blob/57911c42d176315f96c56511a51b492c819ddebb/app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt#L342) `track.num_read_chapters` should be `track.num_read_times`.
Can you fix that for me or should I open a PR just for that?

**Comment by arkon** [comment]
PR would be nice if you have time. :)
