### ISSUE TITLE
[Bug] downloader false recognize wifi as mobile data

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi#2972]
### Device information
* Tachiyomi version: 0.8.5 
* Android version: 7.1.1 
* Device: Xiaomi mi max 2

## Steps to reproduce
1. I connected to another xiaomi phone Hotspot and mobile data not active 
2. I have download only on wifi checked
3. It won't download at all, but when i remove checked on no 2, it start to download 

### Expected behavior
Download should be working when only on wifi is checked

**Comment by jfcaraujo** [comment]
That only happens on hotspots, probably because they usually also have limited data (since it's using another phone mobile data). So probably not a bug (but I'm just a random guy, not involved in the project)

**Comment by lmj0011** [comment]
As @jfcaraujo mentioned, the hotspot connection is likely [metered](https://developer.android.com/reference/android/net/ConnectivityManager#isActiveNetworkMetered()), which would trigger [this](https://github.com/inorichi/tachiyomi/blob/v0.8.5/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt#L148-L150) true and stop downloads.
