### ISSUE TITLE
[Bug] No updates on Xiaomi

### ISSUE THREAD

**Issue by Daegnor** [inorichi/tachiyomi#2975]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10
* Device: Xiaomi Mi 9T Pro

## Steps to reproduce
1. Start the app
2. Set updates frequency to "Every 6 hours"
3. In Xiaomi's app settings, enable autostart, remove every battery restrictions and grant every permissions

### Expected behavior
The app should check my library's chapters every 6 hours

### Actual behavior
No updates are made, I have to manually update

### Other details
With the same settings in Tachiyomi on my previous phone (Samsung), I didn't have this problem. It might come from my phone's settings directly but I tried everything in my app settings.

**Comment by samanta-widjaja** [comment]
Have you tried to reboot your phone, set it manually and back to auto again. It's works on my xiaomi

**Comment by Skcyte** [comment]
Disabled battery optimization. 
Or disable memory management in developer settings.

**Comment by CarlosEsco** [comment]
You might want to try some of these.  

https://dontkillmyapp.com/xiaomi

**Comment by Daegnor** [comment]
None of these solutions worked, but I might have found where is the problem. When I finish using an app, I'm used to remove it from the "Recents Apps" menu. It didn't change anything on my samsung but it seems that, on Xiaomi, it kills the app, even after disabling battery optimization and MIUI optimizations. When I keep Tachiyomi in my "Recents Apps" menu, I do have my library's updates. Also, Tachiyomi seems to use a Worker and PeriodicWorkRequest to update the library and, from what I've read, this API is quite troublesome on OS such as MIUI.

**Comment by arkon** [comment]
This is an issue with MIUI. I don't think it's feasible for us to find workarounds for it.
