### ISSUE TITLE
[Feature Request] Add a configurable delay for updating each manga in library

### ISSUE THREAD

**Issue by cvalenciaec** [inorichi/tachiyomi#2976]
---

### Why/User Benefit/User Problem
Some sources (TMO, LectorManga) limit access to their servers from Tachiyomi users when running a update task, because they configured HTTP 429 Too Many Request when there is a lot of request to their servers, this causes a temporarily IP ban for users.

### What/Requirements
Enable a configurable parameter to add a delay between updating each manga in seconds, to limit the update request to servers and don't get banned.

**Comment by arkon** [comment]
The individual extensions should implement rate limiting.

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2886
