### ISSUE TITLE
Japscan FR Bug Tachiyomi

### ISSUE THREAD

**Issue by Hart-JV** [inorichi/tachiyomi#2979]
There is a huge bug with Tachiyomi's extension Japscan FR. I can't download also not read chapters coming from japscan FR extension. I tried with the Device version and the funny thing is that I can load/read/download some but still not the one I want to read. 
### **This is what I get on Tachiyomi stable version**
![Screenshot_20200428-014038_Tachiyomi](https://user-images.githubusercontent.com/64443709/80428143-db8a6f00-88f1-11ea-92fa-4211b9bf6834.jpg)

###  **On the Device version**

**1. I can load this one**
![20200428_015109](https://user-images.githubusercontent.com/64443709/80428603-e8f42900-88f2-11ea-8371-af5042c301fa.jpg)

**2. But not this one**
![20200428_015132](https://user-images.githubusercontent.com/64443709/80428615-f01b3700-88f2-11ea-81c2-40104f847b5d.jpg)

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2535

**Comment by Hart-JV** [comment]
Ils there any solution given there? I don't undrerstand all of it
