### ISSUE TITLE
[Feature Request] Integrate with detekt-hint

### ISSUE THREAD

**Issue by Mkohm** [inorichi/tachiyomi#2980]
Hi!

I am working on a tool for detection of violations on design principles in my master thesis (read more about it https://github.com/Mkohm/detekt-hint), and is looking for an open source project where I can integrate my tool for some feedback and testing. Would you welcome such an integration? It would mean a lot, and I hope it can continue to improve the maintainability of this project.

It only requires creating a configuration file and a new GitHub action. Please let me know if it is of any interest, and I will create a PR with the required changes.

**Comment by arkon** [comment]
Sure, although a majority of the commits in this repo don't go through PRs.

You may also be interested in setting it up in [this repo](https://github.com/inorichi/tachiyomi-extensions), but a majority of the PRs aren't that complicated.

**Comment by arkon** [comment]
No response, closing.

Feel free to submit a PR if you still want to do so, but I have no plans to proactively do this at the moment.
