### ISSUE TITLE
[Feature Request] Exclude sources from search but keep them in the manual Browse list

### ISSUE THREAD

**Issue by narfanar** [inorichi/tachiyomi#2984]
### Why/User Benefit/User Problem
Speed up global search for common searches, but keep useful niche sources accessible.

### What/Requirements
When choosing active extensions under `Browse>Extensions`, the selection applies only to global search through `Browse`. The list of sources (with `Latest` and `Browse` buttons for each) would continue to show all installed sources.

Alternatively, provide separate filters for search/sources-list.

**Comment by arkon** [comment]
Did it a bit differently: https://github.com/inorichi/tachiyomi/commit/fe65f4d6f86dd57fbc62d5f90b347e35dc3d9ba4
