### ISSUE TITLE
[UI Bug] Top margin/Header height in "More..." view

### ISSUE THREAD

**Issue by StarWolf3000** [inorichi/tachiyomi#2988]
### Device information
* Tachiyomi version: Preview r2190 (a9d32fea)
* Android version: 6.0
* Device: Acer Iconia Tab 10 B3-A30

## Steps to reproduce
1. Have Preview r2190 installed (latest as of filing report)
2. Open "More..." view

### Expected behavior
Header has same height like all other views.

### Actual behavior
Header in this view takes a lot of screen space, both in portrait and landscape.

### Other details
Pictures with portrait and landscape modes.
![Screenshot_20200429-191449](https://user-images.githubusercontent.com/787808/80626780-41d8d400-8a4f-11ea-8c90-ee1034d69528.png)
![Screenshot_20200429-192136](https://user-images.githubusercontent.com/787808/80626803-49987880-8a4f-11ea-9a6b-ec053e9cdc7e.png)

**Comment by StarWolf3000** [comment]
7b14942 does not seem to fix it, at least not for me, and I already have e2a9c09. The header still takes a lot of space.

**Comment by arkon** [comment]
It's intentional.
