### ISSUE TITLE
[Feature Request] Make Certain Buttons Accessible

### ISSUE THREAD

**Issue by jioleight** [inorichi/tachiyomi#2991]
When selecting a manga chapter the select all should not be in the 3 dot menu. As well as the Mark as read/unread. I'm adding my library from mangarock but since there is no way for the app to sync with it, I'm manually adding the Mangas I've read ang marking the chapters as read. 

### Why/User Benefit/User Problem
User will have less taps/clicks just to mark the chapters read/unread.

### What/Requirements
When user highlight selects a chapter the select all, mark as read/unread will show up on the top not inside a 3dot menu. To save space icons can be used. In case just add a tool tip when user is hold tapping/clicking the icons. 

Hopefully this will be implemented. Thank you.

**Comment by CarlosEsco** [comment]
Yea it is pretty hard to sync with a dead app

**Comment by arkon** [comment]
I'm assuming you're using 0.8.5. This is changed in the more current preview builds.
