### ISSUE TITLE
Use Filters UI for Reader settings sheet

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#2996]
### Why/User Benefit/User Problem
- UI consistency

Some mockups:

Reader settings mockup:
![reader2x](https://user-images.githubusercontent.com/63973749/80780559-04d12680-8ba2-11ea-9d8a-b34992e3c2fb.png)

Custom color settings mockup:
![readercolor1](https://user-images.githubusercontent.com/63973749/80780070-3517c580-8ba0-11ea-8806-7349a92e5cac.png)

Custom color settings mockup (alternative):
![readercolor2](https://user-images.githubusercontent.com/63973749/80780072-38ab4c80-8ba0-11ea-92d1-f28f62993054.png)

**Comment by arkon** [comment]
Closing in favour of #3453
