### ISSUE TITLE
[Feature Request] Notification when a manga has been removed from a source/extension.

### ISSUE THREAD

**Issue by VishalNikam1295** [inorichi/tachiyomi#2997]
---

### Why/User Benefit/User Problem

When a manga has been taken off an extension or a source, there is no way of knowing about it. 
For example, I had added a manga to my library from the MangaSee extension, had it synced with MAL and had planned to read it an a few days. But apparently, it was taken down from the extension/source and when I clicked on a chapter to read it, it showed error 404. When I looked for it in the catalogues, it wasn't listed in MangaSee anymore, so I had to migrate it to some other source.

### What/Requirements

The app should notify the user when a manga in the user's library has been taken down from the corresponding source, and suggest to migrate it.

**Comment by CarlosEsco** [comment]
We do not control or own any sources. We don't keep a database of every sources manga.

**Comment by CarlosEsco** [comment]
To add.  The 404 is all we see.  Which in this instance maybe their site was down temporarily due to covid and MR going away. Would you want us to remove every manga whenever there is a 404?
