### ISSUE TITLE
[Feature Request] Move migration into browse section

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#2998]
In latest build browse screen include extension management.

It is really better to have it there. Yet headers tab at the top make the spacing between source/extension name feel too wide. Space between elements should be reduced.

It should also be considered to add an additional tab for source migration to truly make all related extension operations accessible from the same screen.

**Comment by narfanar** [comment]
While we're on what settings/dialogs are included in the Browse section, the new "Global search uses only pinned sources" setting should also be under Browse somewhere.

**Comment by Matth7878** [comment]
@narfanar maybe browse screen could have a gear icon next to the search one which would be a shortcut to browse settings.

**Comment by vengiare** [comment]
I think this makes the UI cluttered. Having to use the Source Migration is a bit rare. Having it hidden in [••• More] makes more sense.

**Comment by Matth7878** [comment]
Why hiding it. It makes perfect sense to have it in browse so all related actions to sources are in the same place.

Having 3 tabs instead of 2 won't make UI cluttered, there is already 3 tabs for instance when you are in a manga to see info / chapters / tracking and it doesn't feel cluttered.

Besides you could say the same for extensions. It occures more to add / remove an extension but it's not common once you're set. And now you're notified if there is an update so there isn't really a need to have it in browse.
If you place items in more options depending on how much you use them then extensions shouldn't have been moved. :-p

Personally I'm for grouping what belongs together and that's why I'm also in favor to add an icon to go directly to settings related to browse. Right now we only have 2 icons so having a 3rd won't be a problem, there is already 3 icons on some screen without feeling it off / clunky. ;-)

**Comment by vengiare** [comment]
Still, extensions are regularly updated and they have customizable options there that are handy.

Source migration is only used when you really need it and that occurrence is very rare. It shouldn't be a visual nuisance in the Browse section.
