### ISSUE TITLE
[Bug] icons not visible in reader long press menu(light theme) & reset button less visible & no margin between remove button and manga cover

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#3000]
### Device information
* Tachiyomi version: 0.8.5-2210 (standard, e2a9c095, 42)
* Android version: 10 (SDK 29)
* Device: ASUS_X00TD

### Issue

**icons not visible in reader long press menu(light theme)**
![Screenshot_20200501-142214](https://user-images.githubusercontent.com/46787056/80795147-4f11d200-8bb9-11ea-85e1-3f0e714d6aea.png )

**contrast is less between the reset button text and the background in the light blue theme makes it less visible**
![Screenshot_20200501-142019](https://user-images.githubusercontent.com/46787056/80795359-e0814400-8bb9-11ea-81b9-9ab956a8c993.png)

**there is no margin between the remove button and the manga cover in the history tab**
![Screenshot_20200501-142237](https://user-images.githubusercontent.com/46787056/80795512-538aba80-8bba-11ea-95ee-b30b494063a4.png)

**Comment by arkon** [comment]
That last one's a bit weird since the padding sort of makes it look more aligned with the text above when it's not activated.

It'll probably change more in the future so the buttons aren't there.
