### ISSUE TITLE
[Feature Request] Add Favorite for Extensions

### ISSUE THREAD

**Issue by ItzBaka** [inorichi/tachiyomi#3001]
Hay Guys, wanna ask if its possible to add Favo's for Extensions, i know its possbile to hide extension i have downloaded but that would take so much Time, so why not as Favorite so i can have all extensions i use often in one place

Something like that.

![Unbenannt](https://user-images.githubusercontent.com/46606767/80810712-b2edc800-8bc4-11ea-9308-a9aa550be18d.png)

**Comment by arkon** [comment]
That's what pinning is for.
