### ISSUE TITLE
[Bug] v0.9.0 doesnt install on android 6

### ISSUE THREAD

**Issue by cubakcabak** [inorichi/tachiyomi#3003]
### Device information
* Tachiyomi version: 0.9.0
* Android version: 6

### Actual behavior

The installation fails with the message:
" X Application not installed"
And below just the option "cancel"

### Other details
installed from github release

**Comment by TacoTheDank** [comment]
@cubakcabak @arkon This is because the APK has no JAR signature. So just attach a new APK? I don't think it's too late.
![image](https://user-images.githubusercontent.com/32376686/80820452-e1f44180-8ba4-11ea-9c51-0861405c37f7.png)

**Comment by arkon** [comment]
Good catch. Building now.

**Comment by arkon** [comment]
Just updated the APK. @cubakcabak Can you try again?

**Comment by TacoTheDank** [comment]
It should be good now 
![image](https://user-images.githubusercontent.com/32376686/80821071-11577e00-8ba6-11ea-8d47-fee1fa0d8b65.png)
