### ISSUE TITLE
[Feature Request] Rename "display mode" to "show chapter title" and make it a checkbox

### ISSUE THREAD

**Issue by BayonShahidi** [inorichi/tachiyomi#3008]
### Why/User Benefit/User Problem
- less confusing and more clear
- improved ux

### What/Requirements
![Screenshot_20200502-045055_Tachiyomi](https://user-images.githubusercontent.com/7311096/80833576-31348380-8c32-11ea-8d9d-a35e072d541c.jpg)
![Screenshot_20200502-050528_Tachiyomi](https://user-images.githubusercontent.com/7311096/80833763-9ab49200-8c32-11ea-8726-05a1416dab6c.jpg)

**Comment by arkon** [comment]
It already is, update to 0.9.0.

**Comment by arkon** [comment]
Whoops I misunderstood it as not having a dialog.

I'll name them something clearer for a future release.
