### ISSUE TITLE
[Feature Request] Add a "change viewer" setting within each library item (default viewer override for each manga)

### ISSUE THREAD

**Issue by BayonShahidi** [inorichi/tachiyomi#3009]
### Why/User Benefit/User Problem
- Removes frequent cumbersome need to back all the way out to settings>>reader menu and change "default viewer" setting when you have manga in your library suited to different "viewers" that you switch between

### What/Requirements
Press this:
![Screenshot_20200502-052001_Tachiyomi](https://user-images.githubusercontent.com/7311096/80834728-9e491880-8c34-11ea-8a9f-893a05196a3a.jpg)
To change this:
![Screenshot_20200502-045956_Tachiyomi](https://user-images.githubusercontent.com/7311096/80834751-a608bd00-8c34-11ea-9fe5-67123bb07916.jpg)
And remember this setting for only this manga in the library. Other manga have their own setting.
If not set, use default.

.

**Comment by arkon** [comment]
You can already set viewers per manga from the reader settings sheet.

1. Open a chapter
2. Tap the middle of the screen to show the toolbars
3. Tap settings at the top right
4. Change the viewer for that series
