### ISSUE TITLE
Black screen when switching to Tachiyomi from recent apps

### ISSUE THREAD

**Issue by maggotb** [inorichi/tachiyomi#3013]
### Device information
* Tachiyomi version: 0.9.0
* Android version: 7.1.1
* Device: Samsung Galaxy Tab A

## Steps to reproduce
1. Go to recent apps
2. Switch to Tachiyomi

When I switch to Tachiyomi from recent apps there is a brief black loading screen, it didn't happen in previous versions, here is a video https://streamable.com/6pn5tw

**Comment by arkon** [comment]
Do you have the secure screen setting enabled?

**Comment by maggotb** [comment]
No I don't

**Comment by maggotb** [comment]
Update : it sometimes even get stuck on the black screen and I have to go back to library
