### ISSUE TITLE
[Feature Request] Add extension name to Restore log

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3018]
### Why/User Benefit/User Problem
- Useful for people who use lots of extensions.
- Also useful to figure out exactly what failed.

### What/Requirements
[Timestamp]**[Extension name]** Manga name - Error details

**Comment by vengiare** [comment]
By the way this is mostly because timeout errors don't include the extension/source name.

**Comment by RvI101** [comment]
I can take a look at this.

**Comment by arkon** [comment]
Source names are in the file now.
