### ISSUE TITLE
[POLL] Library design

### ISSUE THREAD

**Issue by NoodleMage** [inorichi/tachiyomi#302]
Because we are curious about your opinions I created a poll where you can give your opinion on which library layout you prefer. 
http://www.strawpoll.me/10199836

### Option 1
<img src="https://cloud.githubusercontent.com/assets/9655378/15249214/c1c88bc0-191e-11e6-98b9-75555aee3a8d.png" height="750" />
### Option 2
<img src="https://cloud.githubusercontent.com/assets/9655378/15249203/bda941ec-191e-11e6-8cc8-9bd1e9bb16a1.png" height="750" />
### Option 3
<img src="https://cloud.githubusercontent.com/assets/9655378/15249221/c74311ba-191e-11e6-808c-7734ffdde773.png" height="750" />

### Option 1
<img src="https://cloud.githubusercontent.com/assets/9655378/15249463/ed171610-191f-11e6-81e8-8b677d857ba7.png" height="750" />
### Option 2
<img src="https://cloud.githubusercontent.com/assets/9655378/15249461/ed1678fe-191f-11e6-8975-fc16e2a2a3c5.png" height="750" />
### Option 3
<img src="https://cloud.githubusercontent.com/assets/9655378/15249462/ed169064-191f-11e6-8d79-678489f98bb9.png" height="750" />

**Comment by wopian** [comment]
Option 3 hands down. Looks nicer and doesn't make the cards super long.

Could be made an option in the settings if there's equal support of both.

**Comment by Snake87r** [comment]
I think the best is option 3 but with author name like option 2..maybe and option to enable/disable author name..

**Comment by Bloodwork** [comment]
I think the author's name is nice to have but ultimately irrelevant because you'll find things faster by manga's title and cover rather than the author. 

My vote goes to option 3. While option 1 seems to have better readability, it makes cards unnecessarily long.

**Comment by NoodleMage** [comment]
And the winner with 81% is **option 3**. 

Thanks all who voted and maybe we will do more of these in the future ;). 

@Snake87r  maybe we will someday add the option to show the author of the manga in the poster. But as of now this is not high on the list ;).
