### ISSUE TITLE
[Bug] Incorrect button placement

### ISSUE THREAD

**Issue by specterflare** [inorichi/tachiyomi#3020]
### Device information
* Tachiyomi version: r2223
* Android version: 10
* Device: Pixel 3

## Steps to reproduce
1. Got to any manga's chapter list
2. Click the three-dot menu in the top right
3. Click on either Display Mode or Sorting Mode

### Expected behavior
The buttons to choose an option should precede the text, like below:

![Screenshot_20200501-210233](https://user-images.githubusercontent.com/61708534/80851995-f4956780-8bf2-11ea-9f90-d2c92139a818.png)

### Actual behavior
The button to choose an option comes after the text:

![Screenshot_20200501-210241](https://user-images.githubusercontent.com/61708534/80852024-31615e80-8bf3-11ea-8b58-a7057148cdce.png)

**Comment by arkon** [comment]
This is actually "normal" for Android menus.
