### ISSUE TITLE
[Bug] Android 10's system Gesture navigation triggers the scroll bar of the app

### ISSUE THREAD

**Issue by SS1113** [inorichi/tachiyomi#3021]
### Device information
* Tachiyomi version: 0.9.0
* Android version: Android 10
* Device: Motorola One Power

## Steps to reproduce
Please have the system "Gesture navigation" of Android 10 enabled.

1. Go to: Library tab or Browse > Extensions or Sources tab or Chapters tab
2. Use gesture-back navigation gesture
3. Observe that the scroll bar is trigger instead of going back, this results in content of the above specified tabs jumping around thus making it harder to browse and navigate inside the app.

• Please see the attached video for clarification.

### Expected behavior
The content in the app shouldn't jump around this makes it really harder to use the app while using the system's Gesture navigation

### Actual behavior
Content inside the app jumps around when gesture-back navigation gesture is being used 

### Other details
Additional details and attachments.
![20200502_075804](https://user-images.githubusercontent.com/42088907/80853217-620abd80-8c1e-11ea-997f-bdbb48aafb5b.gif)

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi/commit/d86d861e4b55ecd2407adb656809d7f24bdbd87f
