### ISSUE TITLE
[Feature Request] Display average rating/score in tracking

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#3022]
### Why/User Benefit/User Problem
The same as the issue #1099 but with a different solution.

### What/Requirements
Now as the completion date was added to MAL tracking is it possible to display the average score/rating in the same tracking tab?

**Comment by arkon** [comment]
Dates are still relevant to the core idea of tracking _your_ reading status. I'd rather not venture into becoming a full on tracking app, especially when even the start/end date stuff was only implemented for 1 of 5 trackers.
