### ISSUE TITLE
[Feature Request] Update tracking when marking as read

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi#3025]
### Why/User Benefit/User Problem
Sometimes I read on my laptop in the browser instead of my phone by I still want to track my manga. 

### What/Requirements
Update tracking info to to the latest chapter marked as read (in the order of chapters, not the latest pressed). In the current version I need to open each latest chapter and scroll to the end of it.

**Comment by arkon** [comment]
Duplicate of #389
