### ISSUE TITLE
[Bug] Jumping to the beginning of a page

### ISSUE THREAD

**Issue by vishalanandch** [inorichi/tachiyomi#3028]
### Device information
* Tachiyomi version: 0.9.0
* Android version: 9
* Device: Redmi K20 Pro

## Steps to reproduce
1. Open any Webtoon chapter.
2. Go till middle of any long page while reading in Webtoon mode.
3. Switch apps and then go back to Tachiyomi.

### Expected behavior
It should resume from middle of the long page as it was doing in the old version.

### Actual behavior
Goes to the beginning of the long page.

**Comment by SnakeDoc83** [comment]
Also happens when you turn your screen off and back on.

**Comment by Gamingappleh** [comment]
Just thought to mention also occurs in the weekly preview/dev build.
(seems to go to start of the page/beginning).

**Comment by arkon** [comment]
This actually applies to regular viewers too, such as LTR. It's more obvious when the page is bigger than the viewport (e.g. using fill height).

**Comment by SnakeDoc83** [comment]
If it helps, it seems to have creeped in between r2112 and r2152.
