### ISSUE TITLE
[Bug] Double page spreads appear at the end of chapters/volume rather than their normal position. Uninstall error as well.

### ISSUE THREAD

**Issue by PraY-8d** [inorichi/tachiyomi#3034]
### Device information
* Tachiyomi version: 0.9.0
* Android version: 10
* Device: Nokia 6.1

## Steps to reproduce
1. Read manga from local storage with a double page spread

### Expected behavior
The double page spread should normally be in their usual page location - example: https://iili.io/J5tAGI.png (page49/194) which I've just tested from 0.8.5. 

### Actual behavior
The double page spread are transferred to the last pages of the chapter/volume - example: https://iili.io/J5tIQp.png (page191/194) this screenshot is from 0.9.0. This happened in all volumes of Grand Blue Dreaming. 

### Other details
Files were .cbz format. Only tested on locally stored manga.

There also was a bug in uninstalling 0.9.0 seen here - https://iili.io/J5t73X.png
so I had to factory reset to downgrade to 0.8.5 and test if the bug occurs there. Other apps can be uninstalled normally, Tachiyomi 0.8.5 uninstalls no problem as well. Only 0.9.0 had this problem and it occured as well now even after the factory reset.

**Comment by arkon** [comment]
What are the files named in the CBZ archive?

Regarding the uninstalling crashes, you need to remove your SD card first. It's a bug with Android 10 itself.

**Comment by PraY-8d** [comment]
The file was named "Grand Blue Dreaming v01 (2017) (Digital) (danke-Empire).cbz". I've tried renaming to "Grand Blue Dreaming v01.cbz" and the bug still happens even after clearing cache and storage. I've also tried extracting it and putting the folder in local and it still happens. Using my SD Card as storage for Tachiyomi btw. Thanks.

**Comment by arkon** [comment]
I meant what are the actual filenames of the pages?

**Comment by PraY-8d** [comment]
Grand Blue -c001 (v01) - p048-049 [Digital-HD][danke-empire].jpg

**Comment by arkon** [comment]
What about one of the single pages?

**Comment by PraY-8d** [comment]
The single pages have these - Grand Blue -c001 (v01) - p050 [Digital-HD][danke-empire].jpg

**Comment by TheOmnivert** [comment]
Is the bug in the video and this related

**Comment by TheOmnivert** [comment]
All the pages which are named slightly different,
Like cover pages, ToC pages and double pages are all shifted to the end
![IMG_20200502_192700](https://user-images.githubusercontent.com/64693560/80866181-e1c77500-8c7c-11ea-9f58-ba8a0cce7a93.jpg)
