### ISSUE TITLE
[Bug] Webview closes itself

### ISSUE THREAD

**Issue by ZEXERJK** [inorichi/tachiyomi#3036]
### Device information
* Tachiyomi version: Stable 0.9.1
* Android version: 10
* Device: Samsung S10+

## Steps to reproduce
1. Open manga
2. Try yo go in Webview mode
3. Bug occurs, the app closes Webview by itself

### Expected behavior
Normal behaviour

### Actual behavior
[Video of the bug on imgur](http://imgur.com/a/OfgrP0p) 

### Other details
Latest version of Webview: 81.0.4044.117
Happens only on certain websites, not everyone.
Websites of the video if anyone wants to investigate the source: [LINK](https://lhtranslation.net)

**Comment by Shabaaz22** [comment]
This also happens to me when using the readcomiconline extension, I have posted an issue for it aswell.

**Comment by jfcaraujo** [comment]
Also happens to me when I use readcomicsonline, from what I saw it's due to a pop-up ad that they added

**Comment by arkon** [comment]
Webview crashes should be reported to Google.

**Comment by jfcaraujo** [comment]
From what I saw it seems to have stopped as of 0.10.x
