### ISSUE TITLE
[Bug] Goes back to page 1 when sharing pages

### ISSUE THREAD

**Issue by TheMinester** [inorichi/tachiyomi#3037]
### Device information
* Tachiyomi version: 0.9.1
* Android version: 10
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Open a manga chapter
2. Long press
3. Press the share button
4. Press the phone return arrow

## Issue/Request
When trying to share a page of a manga via the share option in the readers, if you cancel it will go back to the beginning of the chapter.

## Other details
Don't know if it matters but tried this using only manga from the Mangadex extension as source.

**Comment by arkon** [comment]
What viewer are you using?

**Comment by TheMinester** [comment]
> What viewer are you using?

I'm using the default one

**Comment by arkon** [comment]
I can't reproduce this.

**Comment by M9k** [comment]
Hi,
Same bug with the preview version r2252.
Android 10 - Xiaomi Redmi Note 7 - China Dev version.
Default viewer.
Tried with default settings and custom settings, local and download chapters, same bug.

**Comment by kiobu** [comment]
Same issue with Galaxy S8 using the latest stable release.
