### ISSUE TITLE
Problem with the browsing tab

### ISSUE THREAD

**Issue by gdeeriya** [inorichi/tachiyomi#3038]
I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 0.9.1
* Android version: 8.0
* Device: p9 lite

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Should be able to scroll normally and press in extensions normally

### Actual behavior
Can only scroll using the thing on the left and it scrolls depending on the location im pressing, and can not press anything it only scrolls

### Other details
This happened in both the new 0.9.0 version and the new 0.9.1 version

**Comment by arkon** [comment]
Can you do a screen recording (with touches shown)?

**Comment by gdeeriya** [comment]
https://streamable.com/vqroje

**Comment by gdeeriya** [comment]
https://streamable.com/vqroje
