### ISSUE TITLE
[Bug] Tachiyomi update download gets stuck at 99% when downloaded through "Check for updates"

### ISSUE THREAD

**Issue by SS1113** [inorichi/tachiyomi#3044]
### Device information
* Tachiyomi version: 0.9.1 not the latest but hear me out please 
* Android version: Android 10
* Device: Motorola One Power

## Steps to reproduce
1. Click "Check for updates" in Tachiyomi in More > About section
2. Click on download update
3. The download gets stuck at 99% and never completes

### Expected behavior
The download should complete

### Actual behavior
The download gets stuck at 99% everytime I try

### Other details
Additional details and attachments.

![158846787874478](https://user-images.githubusercontent.com/42088907/80896089-26352e00-8cda-11ea-90b8-a5319cd07934.jpg)

**Comment by arkon** [comment]
Unfortunately this seems to happen for some people but we're not sure why.

As a workaround, download it in a browser from https://tachiyomi.org/

**Comment by SS1113** [comment]
If you show me how to get the logs then may be the cause can be identified?

**Comment by arkon** [comment]
You can follow these steps: https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android

It's not crashing though, and I'm not entirely sure what to look for in the logs since it's a system level download manager and not the app's, but you can try getting some logs.

**Comment by SS1113** [comment]
@arkon Does this log contain any sensitive personal information, if so I can send it privately only to you otherwise I'll post it here.

**Comment by arkon** [comment]
It's logs from everything, so I'm not sure. Feel free to send it to me privately.

**Comment by SS1113** [comment]
@arkon I'm new to GitHub, is there a way to send it privately to you or can you give me any E-mail or something...?

**Comment by arkon** [comment]
Yeah, I'm `arkon#4275` on Discord. Ping me if you can't DM me.

**Comment by SS1113** [comment]
@arkon To reproduce the bug I tried to install an older version i.e `0.9.1` but after I tried to download the update from Check for updates in Tachiyomi it downloaded it without any problem this time; the download completed. I've tried to reproduce it several times now but it's no longer reproducible on my device. Seems like a re-install fixed it.

**Comment by arkon** [comment]
This is hopefully more reliable after https://github.com/inorichi/tachiyomi/commit/788ea052fcacbe7a52142058e489e2115fe0095f
