### ISSUE TITLE
Accidentally change reader color filter to blavk

### ISSUE THREAD

**Issue by itaspira** [inorichi/tachiyomi#3047]
I accidentally change the reader color filter to 0% brightness and can't change it back.

**Comment by joseph619** [comment]
Color filter as in? This isn't what your video showed on Discord.

**Comment by itaspira** [comment]
Sorry I am really bad at explaining.

I was seeing the menu that is in the attached image. I used the the j2k to
take the screenshot.

Next thing I know whenever I go into a chapter it is pitch black.

In the video attached I'm trying to show that I bring down the top down
menu of my phone and tweak the brightness but it is all buggy.

Sorry for the bad form.

Best regards,

Itamar

**Comment by arkon** [comment]
There's no attachments. 

Assuming you're using v0.9.0+, tapping in the middle of the screen should still bring up the toolbars visibly.
