### ISSUE TITLE
[Feature Request] Removing of update option from liability 

### ISSUE THREAD

**Issue by Ksetrar** [inorichi/tachiyomi#3048]
Tachiyomi has already a section named "update" where the users check the updated manga.

Sometimes, when scrolling up, I mistakenly activate the update option even if I do not wanted

A sample video -Onedrive
https://1drv.ms/v/s!AqxLXy2e8tMWl2OZ9lkL7mlswa0a?e=CipkFA

**Comment by arkon** [comment]
Not sure what to say other than be careful? People have complained when it's been removed, and it's not going to be a configurable option.
