### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by ArmandBernard** [inorichi/tachiyomi#3049]
Hello. Since 0.9.X I've been getting cropped chapter numbers on my phone. I've attached an image below to show exactly what I mean.

---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: OnePlus 7 Pro

## Steps to reproduce
Open any manga

### Expected behavior
Properly visible chapter number on top bar

### Actual behavior
Cropped chapter number (see image)

### Other details
![Screenshot_20200503-093927](https://user-images.githubusercontent.com/25556936/80909846-5228d180-8d23-11ea-8bfc-55df8e758ee3.jpg)

**Comment by arkon** [comment]
Turn off the cropped borders option.

**Comment by ArmandBernard** [comment]
No, this isn't about the image being cropped. This is about the UI being cropped. Check the top of the screen.
For reference though, I did try to turn off the setting and it didn't fix it.

**Comment by ArmandBernard** [comment]
![Screenshot_20200503-093927](https://user-images.githubusercontent.com/25556936/81049008-4705ab00-8eb5-11ea-83cf-e3a46de2acd6.jpg)

**Comment by arkon** [comment]
Did you change the font or display size settings on your phone?
