### ISSUE TITLE
Creating a backup file not working

### ISSUE THREAD

**Issue by heksagen** [inorichi/tachiyomi#3051]
I have stable tachiyomi and preview tachiyomi but when i tried creating a backup file on stable tachiyomi this happens
![Screenshot_20200502-111311](https://user-images.githubusercontent.com/64727699/80910182-56bfab00-8d60-11ea-903e-e696bedacb71.jpg) I cant click the folder called "....." And why I try creating a folder it fails also when I click "ok" it closes the app itself

### Device information
* Tachiyomi version: 0.9.2
* Android version: 8.0
* Device: Huawei Y6 2018

## Steps to reproduce
1.Go to Settings
2. Go to Backup
3. Create backup

### Expected behavior
Open my file manager to save a backuo file

### Actual behavior
Redirects to a file manager i dont know and it doesnt work
![Screenshot_20200502-111311](https://user-images.githubusercontent.com/64727699/80910384-aeaae180-8d61-11ea-8860-bb51cecf0043.jpg)

### Other details
Additional details and attachments.

**Comment by Skcyte** [comment]
It doesn't happen to preview build? 
I suggest using 3rd party file manager app.

**Comment by arkon** [comment]
Yup, use a better file manager.
