### ISSUE TITLE
Bottom menu takes up too much place

### ISSUE THREAD

**Issue by dinosw** [inorichi/tachiyomi#3053]
The new bottom menu takes up too much of the screen, when using the app in landscape mode. 
Could we please have an option too choose to use the sidebar menu, rather than the bottom menu?

**Comment by arkon** [comment]
It already hides when you scroll or aren't on one of the top level pages.

It's too much extra logic to have to handle both systems, and the sidebar doesn't work well on Android 10+ when using standard gestures.

**Comment by dinosw** [comment]
@arkon it doesn't hide when scrolling down in my library.   
Would it be possible to have it hide when doing so?

**Comment by arkon** [comment]
You need to update to 0.9.2 then.

**Comment by dinosw** [comment]
@arkon thank you. Sorry that I hadn't noticed 0.9.2 myself before posting. 
And thank you for one of the best apps I have ever used c",)
