### ISSUE TITLE
[Feature Request] Don't drop android 5 (sdk21). Please!

### ISSUE THREAD

**Issue by dickyharper** [inorichi/tachiyomi#3054]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Thank you very much for the app and for your hard work.  I hope you won't cut android 5 support anytime soon.  Because as applications move to the material design, the minimum version becomes 6.

### What/Requirements
(explain how this feature would behave)
Please do not drop android 5 support.

**Comment by arkon** [comment]
We'll try our best.

**Comment by dickyharper** [comment]
> We'll try our best.

Thank you again. 
Have a nice day.
Best Regards.
