### ISSUE TITLE
Auto Update for Dev Build

### ISSUE THREAD

**Issue by TheIvoryWolf** [inorichi/tachiyomi#3056]
### Why/User Benefit/User Problem
(explain why this feature should be added)

Since there is no Auto Update or app update notification (not even every 3 days) this would be nice

Minor changes is a notification and can continue to use the app til a major update hits the device

Major changes must be updated

### What/Requirements
(explain how this feature would behave)

Persistent Wifi or data connection for when a update goes live

(If needed, current build of app)

App version: 0.9.2-2252 (standard, 43c11c6a, 45)
Android version: 10 (SDK 29)
Android build ID: ONEPLUS A6013_41_200222
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6T
Device model: ONEPLUS A6013
Device product name: OnePlus6T

**Comment by arkon** [comment]
> Since there is no Auto Update or app update notification (not even every 3 days) 

There should be.

**Comment by arkon** [comment]
To be clear, you _can't turn it off_. There also isn't updates every day anymore, it's roughly once per week.

**Comment by TheIvoryWolf** [comment]
I dont even get them once a month

**Comment by vengiare** [comment]
> I dont even get them once a month

0.8.5 = March 1
0.9.0 = May 1

**Comment by arkon** [comment]
@vengiare That's the stable release, which is different and has no schedule at all.

@TheIvoryWolf The current build you mentioned is from 1 day ago.

**Comment by vengiare** [comment]
oopsie

**Comment by TheIvoryWolf** [comment]
Exactly my point, and yet there is no auto update for the app

**Comment by CarlosEsco** [comment]
There is make sure you enable it.

**Comment by arkon** [comment]
Are you saying you installed it yesterday and there hasn't been an update since? I'm not sure what you're asking.

> Since there is no Auto Update

There is, and it is _always_ enabled. You can't turn it off.

**Comment by TheIvoryWolf** [comment]
If its enabled, where is the notification? Where i the option to download
it now?

Had it since when manga rock closed, December i believe and never received
a notification of any app updates

I have read solo leveling every week til they finished season one

App version: 0.9.2-2252 (standard, 43c11c6a, 45)
Android version: 10 (SDK 29)
Android build ID: ONEPLUS A6013_41_200222
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6T
Device model: ONEPLUS A6013
Device product name: OnePlus6T

**Comment by arkon** [comment]
> If its enabled, where is the notification? Where i the option to download it now?

I'm not sure you understand how it works. It checks once every 3 days. If you installed it 1 day ago, it hasn't reached the next time to check yet. Even then, there's usually only 1 release per week. r2252 is the latest one, so even if it was checking every day (which is the frequency it did before), you wouldn't have gotten a notification.

**Comment by TheIvoryWolf** [comment]
Please refer to my previous statement for the install date, for when i
tapped the build number, 4 days ago mind you, it was in the 17xx

Shall you continue to ride a dead horse?

**Comment by arkon** [comment]
So you're actually trying to say that it's broken? Did you have them enabled before? It was opt-in in the older builds.

**Comment by TheIvoryWolf** [comment]
Never received any form of pop up or notification in notification list of
android since

I would say so its broken since i have never been updated til having to tap
the build ( tedious that one )

Sorry if this one is a bit harsh, but do test your builds before you deploy
them? Both public and dev?

**Comment by arkon** [comment]
Sure, but there's also thousands of other people who haven't had issues with the updater.

**Comment by TheIvoryWolf** [comment]
Great, then this ticket will remain open?

**Comment by CarlosEsco** [comment]
If you had a legitimate issue you should have said so from the beginning. Instead you make it sound like dev doesn't have this feature. Feel free to use mangazone or one of the other apps if you gonna be a douche on an  open source project
