### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by tournier** [inorichi/tachiyomi#3057]
It would be great to have an option to fill the screen in reader mode so that the chapter we're reading completly fill the screen whether or not we have a camera punch hole. 
---

### Why/User Benefit/User Problem
As this type of camera position become more & more common in nowaday's smartphones, i think adding an option to fill the screen like mangarock does would be great. 

### What/Requirements
As of right now, the chapter you're reading cut right under the punch hole camera / tear drop camera, meaning you lose a bit of space on your screen that gets filled with nothing. It may not mean much as an added benefit to introduce an option like that but i think this kind of customization would be great with how diverse the android smartphone's screens are.

**Comment by arkon** [comment]
Turn on the "Show content in cutout area" setting.
