### ISSUE TITLE
[Feature Request] Keep the search active after switching between Library/Browse

### ISSUE THREAD

**Issue by Playermet** [inorichi/tachiyomi#3062]
### Why/User Benefit/User Problem
The user has to start the search and write a search request a second time if nothing was found in Library, and he wants to continue searching in Sources (or vice versa).

### What/Requirements
Tachiyomi should keep the search active and keep the search request when the user switches between Library and Browse.

**Comment by arkon** [comment]
I couldn't find it, but there was an old issue from when the bottom nav was initially implemented where we decided we won't be retaining state when switching sections.

There's another open issue for search history, so that'd be a better alternative for the problem here.
