### ISSUE TITLE
[Bug] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [inorichi/tachiyomi#3063]
...as `oss-licenses` is not FOSS _(ironic right?)_ and `fdroid` flavor does not exclude it.

Ref: https://github.com/inorichi/tachiyomi/commit/ca47446b46e74ac4d366b7baa686cf3772b0ced9

Removing the include blindly will fail
```
> Task :app:kaptFdroidReleaseKotlin
Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
> Task :app:compileFdroidReleaseKotlin
e: /home/strech/fdroiddata/build/eu.kanade.tachiyomi/app/src/main/java/eu/kanade/tachiyomi/ui/more/AboutController.kt: (10, 27): Unresolved reference: gms
e: /home/strech/fdroiddata/build/eu.kanade.tachiyomi/app/src/main/java/eu/kanade/tachiyomi/ui/more/AboutController.kt: (137, 52): Unresolved reference: OssLicensesMenuActivity

> Task :app:compileFdroidReleaseKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by arkon** [comment]
I guess it's finally time to request for it to be taken down? :)

**Comment by licaon-kter** [comment]
Not sure Google might want to take that lib down...

**Comment by CarlosEsco** [comment]
he's saying fdroid hasn't been officially supported in over a year.

**Comment by arkon** [comment]
I could probably replace it with something else, but our official stance has been that we don't support the F-Droid distributions for at least a year now too, so it's not particularly high priority.

I'll look into alternatives though, but it seemed like the easiest way of automatically getting the OSS licenses as a list.

**Comment by licaon-kter** [comment]
@CarlosEsco Y U can't into joke?

I understand the need for such a lib but the use of a closed source (open-source with close source dependencies actually) one to achieve this is rather baffling. :)

**Comment by arkon** [comment]
https://github.com/google/play-services-plugins/blob/master/LICENSE

It's licensed under APL 2.0.

**Comment by licaon-kter** [comment]
That's great, so it should just build with only FOSS deps?
```
> Task :app:checkFdroidReleaseDuplicateClasses

> Task :app:kaptFdroidReleaseKotlin
Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
> Task :app:compileFdroidReleaseKotlin
e: /home/strech/fdroiddata/build/eu.kanade.tachiyomi/app/src/main/java/eu/kanade/tachiyomi/ui/more/AboutController.kt: (10, 27): Unresolved reference: gms
e: /home/strech/fdroiddata/build/eu.kanade.tachiyomi/app/src/main/java/eu/kanade/tachiyomi/ui/more/AboutController.kt: (137, 52): Unresolved reference: OssLicensesMenuActivity

> Task :app:compileFdroidReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFdroidReleaseKotlin'.
> Compilation error. See log for more details
```
...oh, it depends on GMS which is not FOSS...right...

**Comment by opusforlife2** [comment]
@licaon-kter Which alternatives to this library do other apps on F-Droid use?

@arkon Pardon my ignorance, but how does adding this to an open milestone help you keep track of the issue if the issue itself is closed?

Guys, as an F-Droid user, I am perfectly fine with a simple plain text list, no matter if it is ugly, if it comes to that. Most users don't even access such a list in apps. This app is too useful to not be included in F-Droid.

**Comment by arkon** [comment]
I intend on trying [this library](https://github.com/ligi/ThirdPartyLicenseDisplay), but it's pretty low priority.

I think F-Droid tried fixing the build on their end based on their build logs, but I'm not sure what they plan on doing (and we never really do, hence why we haven't officially recommended F-Droid in a long time).

**Comment by opusforlife2** [comment]
Great! That library seems to have been made specifically to address this problem.

**Comment by CarlosEsco** [comment]
@opusforlife2 may I ask why you are using the fdroid version vs the GitHub version?

**Comment by opusforlife2** [comment]
Guarantee of open... sourciness? Sourcicity? It's the same with FairEmail and so many others. It's not that I don't trust the developers, I just prefer the guarantee.

**Comment by CarlosEsco** [comment]
There is no guarantee?

From fdroid site themselves

F-Droid is a non-profit volunteer project. Although every effort is made to ensure that everything in the repository is safe to install, you use it AT YOUR OWN RISK. Wherever possible, applications in the repository are built from source, and that source code is checked for potential security or privacy issues. This checking is far from exhaustive though, and there are no guarantees.

**Comment by licaon-kter** [comment]
There's no guarantee that the actual code is harmless, not the build process. Garbage-in, garbage-out.

**Comment by opusforlife2** [comment]
It's about putting extra barriers between yourself and potential problems. This very issue is an example of what F-Droid does that I can't do manually.

**Comment by relyt29** [comment]
> @opusforlife2 may I ask why you are using the fdroid version vs the GitHub version?

I use the fdroid version for a reason that isn't "guarantee of open sourcey-ness" (though I do think that's a legitimate reason, and they tell you within the fdroid app whether an app has "anti-features") 

My reason is, FDroid is a package management tool where I get all my apps, and I don't want to be manually managing my Tachiyomi installation. I want to be able to update all of my applications at once, in one place, not manually remembering to check the tachiyomi github page on a frequent basis to check whether there's been an update to the application, this is literally the point of package management. Literally this is what auto-update is for.

It seems that Tachiyomi is written in the spirit of OSS, and FDroid is the de-facto OSS package manager for Android applications.

So then is the current expectation for Tachiyomi users that want their app to be kept up to date is to manually check the GitHub page for updates? Is there no auto-update functionality?

**Comment by arkon** [comment]
It does have auto-update functionality, which is why we don't recommend F-droid anymore since their builds are slow (or broken).

**Comment by CarlosEsco** [comment]
@relyt29  if you had downloaded from github previously you would have seen there has been an auto updater for 2+ years in this version.  fdroid version has it stripped out.  There is also an auto updater for the preview version of the app that gets weekly updates

**Comment by relyt29** [comment]
Ok so if I download the github version the app updates itself, got it

**Comment by opusforlife2** [comment]
Any luck with that library, @arkon?

**Comment by arkon** [comment]
It's been replaced for the next stable release.

**Comment by opusforlife2** [comment]
Awesome! Thanks a bunch!

**Comment by arkon** [comment]
FYI, 0.10.2/0.10.3 appear to be available in F-Droid now.

**Comment by opusforlife2** [comment]
Installed. New look is awesome. :)
