### ISSUE TITLE
[Bug] Search results on Anilist doesn't include the right manga

### ISSUE THREAD

**Issue by Andre-Oliveira** [inorichi/tachiyomi#3064]
### Device1 information
* Tachiyomi version: 0.9.2
* Android version: 7.0
* Device: HUAWEI MediaPad M3 Lite 10

### Device2 information
* Tachiyomi version: Preview r2252 (43c11c6a)
* Android version: 8.0
* Device: HUAWI P10 Lite

## Steps to reproduce
1. Copy manga name from anilist website
2. paste manga name in the text input in the app

### Expected behavior
Correct manga should be one of the first results

### Actual behavior
Correct manga doesn't show up

### Other details
[Streamable link for a video of what actually happens](https://streamable.com/gt2qsa)
[imgur gallery with the correct manga appearing as the 2nd result in search](https://imgur.com/a/kXaOg6V)

**Comment by CarlosEsco** [comment]
Not a bug the 2nd entry in the screenshot is of type light novel we ignore anime and light novels as this is a manga reader

**Comment by Andre-Oliveira** [comment]
My bad, completely missed it was not Manga Type
