### ISSUE TITLE
[Bug] Library lagging in relation to items per row shown

### ISSUE THREAD

**Issue by PredatorIWD** [inorichi/tachiyomi#3065]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: ZTE Blade V10 Vita

## Steps to reproduce
Set "Items per row" to anything more than 2. The bigger the number the more it lags.
Doesn't happen on any other page or other categories where I have only a couple of items. In the main category, where the lag happens, I have around 20 items.

The lag may not be as noticable on video as IRL but you can compare it with the smooth transition on the later categories which feel fully responsive. The faster you scroll the more it lags as well.

Also, the scroll bar seems to be broken while scrolling as shown below at the slower swipe at the end of the clip.

### Actual behavior
https://streamable.com/8h28om

**Comment by arkon** [comment]
I updated how the rounded corners are done for the next release, which might help.
