### ISSUE TITLE
[Bug] All chapters of newly added manga showing up in updates tab

### ISSUE THREAD

**Issue by JakeIsMeh** [inorichi/tachiyomi#3066]
### Device information
* Tachiyomi version: v0.9.2 (has been around for a couple versions)
* Android version: Q/10/API29
* Device: Google Pixel 3 XL

## Steps to reproduce
1. Check updates tab.
2. Add a manga with existing chapters that wasn't updated today.
3. Check updates tab.

### Expected behavior
Content of updates tab should not have changed from step 1.

### Actual behavior
Content of updates tab have been updated to show all chapters of newly added manga.

### Other details
Should this be the intended behaviour, I would like to request a toggle to prevent all chapters of newly added manga from showing up in the updates tab, and instead only chapters that were added today.

### Why/User Benefit/User Problem
Should the user decide to add a manga with many chapters the updates tab would still be usable, as instead of a long list of chapters from the newly added manga, which is especially important for those who choose updates as their default tab.

### Pictures
> This manga was added today, but only chapter 21 was uploaded today.
> Source is MangaDex - id:40897
> Should this be rectified/added, only chapter 21 would be there, along with the rest of today's updates.

![Screenshot_20200504-222810](https://user-images.githubusercontent.com/33054273/80978294-72a67800-8e58-11ea-911d-c64016292fe3.png)

**Comment by JakeIsMeh** [comment]
Update: Added a manga this afternoon with fresh chapters today and works as intended. Only the chapters uploaded today showed up in the updates tab. 

Should anyone with privileges see this, please remove the feature label and add the bug label. Thanks in advance.

**Comment by bbtora** [comment]
Duplicate #1759

**Comment by JakeIsMeh** [comment]
Ah apologies, apparently I just didn't search hard enough.  Shall I close this or no?

**Comment by bbtora** [comment]
Yes you can close it.
