### ISSUE TITLE
[Bug]App take too long to refresh library

### ISSUE THREAD

**Issue by Syehino** [inorichi/tachiyomi#3068]
### Device information
* Tachiyomi version: Stable 0.9.2
* Android version: 9
* Device: Huawei Nova 3i

## Steps to reproduce
1. Swiping down in library page to refresh.

## Issue/Request
Refreshing library for new updates takes too long and sometimes new chapters are not updated.

## Other details
It's usually just take around 5 minutes to refresh my library with just 131 manga but for the past week it took more than 30 minutes to finish.

![Screenshot_20200505_050943_eu kanade tachiyomi](https://user-images.githubusercontent.com/32030125/81014023-bb792380-8e8e-11ea-806f-8c1dd69d4cdc.jpg)

**Comment by arkon** [comment]
You're likely hitting dead sources for some entries, which will take longer.
