### ISSUE TITLE
[Bug] Reader pinch-zoom acceleration can yeet manga pages off screen

### ISSUE THREAD

**Issue by geominorai** [inorichi/tachiyomi#3074]
### Device information
* Tachiyomi version: 0.9.2
* Android version: Android 10
* Device: Samsung Galaxy S9+

## Steps to reproduce
1. Enable webtoon view mode.
2. Pinch to zoom in/out quickly, but this also happens occasionally even if not done in quick succession.

### Expected behavior
Pinch-zooming should keep pages on screen.

### Actual behavior
All manga pages can get yeeted partly, or fully into oblivion.

### Other details
[Video](https://i.imgur.com/dY20rqS.mp4)

This is possibly related to the same bug behind #2602.

See also same issue reproduced on J2K fork: Jays2Kings#273

**Comment by arkon** [comment]
You've already reported this in #2602

**Comment by geominorai** [comment]
If it's the same bug then that's great, but this one seems to be webtoon mode not doing a sanity check for valid scroll boundaries in certain conditions.

**Comment by geominorai** [comment]
This can also be very reliably reproduced by double-tapping to zoom out, but the second tap is a bit away from the first tap.

[Video 1](https://i.imgur.com/kLUbA77.mp4)
[Video 2](https://i.imgur.com/R77Ac5v.mp4)

**Comment by arkon** [comment]
Post it in the open duplicate issue, this is just going to get forgotten about.

**Comment by geominorai** [comment]
Will do.
