### ISSUE TITLE
[Feature Request] add chapter count to searches and source migration results.

### ISSUE THREAD

**Issue by foxlore** [inorichi/tachiyomi#3075]
### Why/User Benefit/User Problem
if the chapter counts are on the search results it will be easier to tell which sources are up-to-date. This will also help with source migration. As an addition to this request if the results could also be sorted my number of chapters it would bring the most up-to-date source to the top of the search.

### What/Requirements
When the search results are returned one of the query parameters could be the total chapter count. A badge overlaid on the artwork would display the chapter count.

**Comment by arkon** [comment]
Duplicate of #2867
