### ISSUE TITLE
[Feature Request] Is it possible to make this app work with ARM cpu?

### ISSUE THREAD

**Issue by AlitheD** [inorichi/tachiyomi#3076]
Hello 
I am trying to salvage a use for my microsoft Windows RT surface. Since It has an ARM Cpu, I can not use it anything other than a paper weight.
I wanted to read some manga with it but yeah... You know the drill. There is no app which functions.

I was wondering if we could ever get Tachiyomi to function with these devices?

---

### Why/User Benefit/User Problem
Why? To let people like me use a over praised and let down device which locks me out from doing anything
User Benefit? It would benefit small number of people who are dumb enough to buy such a device(like me)

### What/Requirements
I have literally no idea. I have no knowledge upon softwares / development.. etc.

**Comment by CarlosEsco** [comment]
#2587

**Comment by arkon** [comment]
If you get Android to run on it, then it'd technically work. Android is usually running on ARM processors.
