### ISSUE TITLE
[Bug] App update doesn't work

### ISSUE THREAD

**Issue by Sphinxs** [inorichi/tachiyomi#3078]
### Device information
* Tachiyomi version: v0.9.2
* Android version: 9
* Device: Moto E6

## Steps to reproduce
1. Download the app
2. Update the app through the notification that is shown

### Expected behavior
When I click on the notification about the app update it should update in background and show me a success message

### Actual behavior
When I click on the notification about the app update the download starts and it never finishes, I have wait for 20 minutes using both wifi and mobile network

**Comment by arkon** [comment]
#3044
