### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#3080]
The latest version of the app crash when i donwload a manga
please fix this issue carlos and arkon you noob devs

**Comment by arkon** [comment]
You failed to provide any details. Please reopen if you can provide reproduction steps and/or logs.

**Comment by AbdullahM0hamed** [comment]
> you noob devs
This comment is entirely unwarranted. The app is opensource, and if you think you can do better, feel free to submit a PR.

**Comment by mged** [comment]
which more detail? i simple click donwload then it crash.

abduallah who the hell are u? im talking the devs and its ok if they cant fix it.

get out of my topics man! ... insect.

**Comment by CarlosEsco** [comment]
mged may i recommend https://mangazoneapp.com/
