### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#3083]
Hi, what u mean? im just reporting issues. what is wrong with u? first u was rude and making silly jokes about me and now being impolite? what

**Comment by mged** [comment]
i did nothing in discord and banned me? this just show you dont follow the server rules and was a bad judgemnet. banning others with out even having a reason is a funny thing that show u are powerless against me. lol

**Comment by arkon** [comment]
GitHub is not a casual discussion forum. Please reach out via the proper channels or provide more context.

**Comment by mged** [comment]
how can i contact u then? u banned me from discord

**Comment by CarlosEsco** [comment]
mged we have been vary lenient with your attitude and rudeness and straight name calling, on discord and here.  You might be a smart guy and english is your 2nd language but talking to people how you do is not acceptable.  Now you are just spamming issues.  You are welcome to use the app or use another one.  But do not open any issues anymore
