### ISSUE TITLE
[Bug] Padding not used in Continous vertical mode.

### ISSUE THREAD

**Issue by swistak** [inorichi/tachiyomi#3088]
### Device information
* Tachiyomi version: 0.9.2
* Android version: ?
* Device: Onyx Boox

## Steps to reproduce

1. Choose continous vertical mode.
2. Set padding (available option)

### Expected behavior

Padding should work as in web toon.

### Actual behavior

No padding applied/

**Comment by arkon** [comment]
Seems to work, it just doesn't immediately refresh the visible pages sometimes. You should be able to see it being applied if you scroll up/down a few pages.
