### ISSUE TITLE
[Bug] You need to restart the app for a changed thumbnail to appear

### ISSUE THREAD

**Issue by ferration** [inorichi/tachiyomi#3089]
### Device information
* Tachiyomi version: 0.92
* Android version: 9
* Device: Samsung J5 Pro

## Steps to reproduce
1. Tap and hold on a manga in your library
2. Press the pencil and upload your image

### Expected behavior
Thumbnail updates immediately

### Actual behavior
You need to restart the app for the thumbnail to update.

**Comment by arkon** [comment]
This is fixed for the next release via #3101
