### ISSUE TITLE
[Feature] Clear Cookies on Start or on Refresh

### ISSUE THREAD

**Issue by IceKreem** [inorichi/tachiyomi#309]
I think it would be a good implementation to add tick boxes for the cookies and when they should be cleared

Version: r726

**Comment by inorichi** [comment]
Why would you want to remove them? It's not like you get ads or anything, I decided to store them to allow Kissmanga to work without direct IP access (because Cloudflare).

**Comment by IceKreem** [comment]
well I've noticed after like a 12 hour period it won't work because they expire and when you click on a manga it will say no internet connection and then I would have to clear the cookies, so that the manga would be displayed again. So if I could do that on a refresh, I wouldn't run into this issues as much

**Comment by inorichi** [comment]
I've also noticed the server refuses the clearance cookie before the original expiration date. I've been doing changes lately and it could be fixed. Everything should be handled transparently, if it isn't, then I have to fix that.

**Comment by IceKreem** [comment]
oh right cool I see, I'll keep you updated if I notice the issue :)

**Comment by inorichi** [comment]
I was checking a wrong error code. Should be fixed now.
