### ISSUE TITLE
[Feature Request] Don't reopen webtoon at the top of the page. This feature was in 8.0 

### ISSUE THREAD

**Issue by TuxXo** [inorichi/tachiyomi#3090]
When i read webtoons, i read it in english instead of my native language. And when i don't remember the meaning of something, i minimize Tachiyomi and then use Google translator to translate It. However, when I reopen the webtoon, it goes back to the beginning of the page and like some webtoons, an entire chapter can be in just 4 pages.  That is, i have to look for the page where i stopped reading.

This would basically save time for readers who read in another language. For this, it is enough that the application reopens on the same page and does not go up to the beginning of it. 

By the way, in update 8.0 i didn't have this problem.  Whenever i minimized the application, it opened on the same page and zoomed in on the last position i left it.

Example, i want this when i minimize and reopen Tachiyomi:
![Screenshot_20200506-023828](https://user-images.githubusercontent.com/64885123/81141329-ae1d7100-8f42-11ea-8642-4537f79839c7.png)

And not this: 
![Screenshot_20200506-023629](https://user-images.githubusercontent.com/64885123/81141246-6dbdf300-8f42-11ea-836f-77ba9be6cc79.png)

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi/issues/3028
