### ISSUE TITLE
Switching apps causes wrong positioning

### ISSUE THREAD

**Issue by CHerSun** [inorichi/tachiyomi#3091]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9.1
* Device: Huawei Honor 10

## Steps to reproduce
1. Start reading in webcomics mode ("Tower of God" for me)
2. Switch to another app (WhatsApp)
3. Switch back to continue reading
4. Reading position jumps back randomly. Could go to the top of current chapter. Could go to previous chapter.

## Issue/Request
I'm using Tachiyomi for quite long time, didn't note such behavior previously. Looks like a bug in 0.9.x

## Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi/issues/3028

**Comment by CHerSun** [comment]
Yes, this looks similar, not sure if it's the same. It mentions jumping to the top of image. In my case it jumps to strange positions. Like just now it jumped to previous chapter image 4 out of 5 (judging by index at the bottom).

Should I close this one?

**Comment by CHerSun** [comment]
I've double checked. It indeed looks like jumping to the top of image (sometimes 1 image back - I guess a question if progress tracking), so #3028 is the same
