### ISSUE TITLE
[Bug] Attempting to Multiple Chapters Lands at End Page

### ISSUE THREAD

**Issue by aznchronos** [inorichi/tachiyomi#3092]
### Device information
* Tachiyomi version: 1.0.2
* Android version: 10
* Device: Samsung Note 10+

## Steps to reproduce
1. Download multiple chapters of any manga
2. Read through chapter
3. Proceed to next chapter via swiping right
4. (Next chapter starts at "There's no next chapter")

### Expected behavior
Start the next chapter page 1

### Actual behavior
Starts next chapter end page at "There's no next chapter"

### Other details
Started reading from 2nd last chapter.

Reproducible with any manga under same circumstances, except webtoons.

**Comment by arkon** [comment]
1.0.2? I'm assuming you're using j2k so this isn't the right repo.
