### ISSUE TITLE
[Feature Request] Bagdes enhancement

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi#3095]
### Why/User Benefit/User Problem
Cleaner UI

### What/Requirements
_Badge remove feature
_Langage badge on the right corner
![Screenshot_20200506_123341](https://user-images.githubusercontent.com/56766778/81162921-a12a6d00-8f96-11ea-9298-5fce269459cb.jpg)
![IMG_20200506_122722](https://user-images.githubusercontent.com/56766778/81162928-a38cc700-8f96-11ea-8c9c-34f1b9a6dbd8.jpg)

**Comment by pervertkirito** [comment]
2) you can create new category and move your manga with different language there.

**Comment by arkon** [comment]
The first one is possible, but the second one isn't really. At best it'd be able to show what the source language is, but I'd rather not add that.

**Comment by Mitia99** [comment]
Langage badges are more convenient cause if a make a category all genres
will be mixed.

Le mer. 6 mai 2020 à 13:22, pervertkirito <notifications@github.com> a
écrit :

**Comment by Mitia99** [comment]
> The first one is possible, but the second one isn't really. At best it'd be able to show what the source language is, but I'd rather not add that.

Yes,it's the language from source.
