### ISSUE TITLE
[Bug] Download Auto-Canceled 

### ISSUE THREAD

**Issue by Hikky9** [inorichi/tachiyomi#3096]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 5.1.1
* Device: Samsung J5

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.
download will continue even if its only H.... (Note: My phone is a 3g one with H+ and H data connectio)

### Actual behavior
This happened instead.
While downloading if my data sometimes go H from H+ it will auto cancel and it will not auto resume i did the check the downloads and off the wifi download only so I need to do download it while checking my phone every seconds and on the side note im not just using regular mobile data I use vpn.

### Other details
Additional details and attachments.
If this is somewhat rude and poorly written I sincerely apologize and it is my first time to send an issue anyways I really am thankful for this community and the developer for this wonderful app because it really is nice will looking forward for future updates...

Edit: Ive done a long search about the updates in version 0.8.4 auto-downloadis still intact and when  I update to 0.8.5 when the internet go slow(my data connection sadly) the progressing download chapters are auto-paused and when the good internet is back it will not auto-download which is I need to manually resume it... And what if I downloaded tons of chapters? Sure that is a real hard thing to do manually 

It would be nice to make auto-download on/ off or have a switch pls..

**Comment by arkon** [comment]
Closing in favour of #3098
