### ISSUE TITLE
[Feature Request] Auto-Resume 

### ISSUE THREAD

**Issue by Hikky9** [inorichi/tachiyomi#3098]
### Why/User Benefit/User Problem
Auto-Resume needs to be back and make it as optionable in settings->downloads since if we use data connection and sometimes it get slow it will auto-pause and never auto-resume which is really bugging and needs to be resume manually time to time...When Version 0.8.4 i dont really need to resume it and just leave my phone download the chapters..

### What/Requirements
Auto-download needs to be back and make it as optionable in settings->downloads  to avoid people with slowpoke connections get auto-pause everytime the internet goes slow and it will auto-resume if the internet is back and good to go so we can just leave our phone downloading..

**Comment by CarlosEsco** [comment]
What do you mean auto download needs to be back?  it exists in the app already

**Comment by Hikky9** [comment]
> What do you mean auto download needs to be back? it exists in the app already

When currently downloading if the data become slow( my 3g phone like this H+ -> H) it will auto-pause and i need to resume it manually again hence even if the net is back it will not resume automatically 

0.8.5 Fix: download queue won't autostart if it was previously paused
And thats it.... if the net become slow(not off) even it's still ON it will auto pause and when the net is back it will not auto-resume..

**Comment by CarlosEsco** [comment]
I believe
0.8.5 Fix: download queue won't autostart if it was previously paused
is when you pause manga then add a new downloads to the queue it doesn't start the queue back up since you paused it

**Comment by Hikky9** [comment]
> I believe
> 0.8.5 Fix: download queue won't autostart if it was previously paused
> is when you pause manga then add a new downloads to the queue it doesn't start the queue back up since you paused it

It was the close related one that I can find that might the cause of this little issue here is the pic.
![Screenshot_2020-05-07-02-50-55](https://user-images.githubusercontent.com/64855076/81216648-d625d680-900d-11ea-9037-3ff6b0f64be6.png)
![Screenshot_2020-05-07-02-51-46](https://user-images.githubusercontent.com/64855076/81216652-d7570380-900d-11ea-9de5-faca211fa300.png)

It just pause itself and needs to be manually resumed by clicking the resume button even the internet is good.... hence if i download a lot of chapters i need to observe my phone and resume if its auto-paused

**Comment by CarlosEsco** [comment]
#959
