### ISSUE TITLE
Revert MaterialFastStroll change

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3102]
### Why/User Benefit/User Problem
![Screenshot_TachiyomiJ2K_20200507-125229](https://user-images.githubusercontent.com/63973749/81256103-08f9ba00-9062-11ea-802c-42714473bca3.png)

The fast scroll that J2K uses, fails to provide scrolling precision that the previous one had when browsing a huge library or a manga with lots of chapters.

This is just such a huge downgrade [compared to what the previous scroller provided](https://cdn.discordapp.com/attachments/694092459839455243/707818949441617990/ScreenRecord_20200507_125853.mp4)—and that's without even having to lift your finger.

**Comment by CarlosEsco** [comment]
This is a j2k issue not a tachiyomi issue

**Comment by arkon** [comment]
That's not even what the commit means.
