### ISSUE TITLE
[Bug] Possibly Device Specific

### ISSUE THREAD

**Issue by Thenewfromdiscord** [inorichi/tachiyomi#3103]
The manga in the app seems to be zoomed out, and no matter what I do I can't zoom in. I tried downloading from my cousins phone and his seemed fine. And when I try webtoon or continuous vertical it includes the black borders with it making scrolling a hard task. I have also tried deleting and downloading, it didn't work.

### Device information
* Tachiyomi version: stable 0.9.2
* Android version: 8.1.0
* Device: iris51

## Steps to reproduce
1. Unknown

## Issue/Request
I want it fixed if possible. Thank you.

## Other details
![Screenshot_2020-05-07_02-33-35](https://user-images.githubusercontent.com/64950761/81266117-c8586b80-9076-11ea-9766-3898731107a8.jpg)
![Screenshot_2020-05-07_12-37-43](https://user-images.githubusercontent.com/64950761/81266139-d3ab9700-9076-11ea-92d7-c43ed4fc00f7.jpg)

**Comment by CarlosEsco** [comment]
click the middle of the screen and send a screen of your display options

**Comment by Thenewfromdiscord** [comment]
![Screenshot_2020-05-07_02-34-30](https://user-images.githubusercontent.com/64950761/81292523-5431be00-909e-11ea-9c25-df9c97e0bd18.jpg)
![Screenshot_2020-05-07_12-37-27](https://user-images.githubusercontent.com/64950761/81292564-64e23400-909e-11ea-82a4-f8bfa4fdf557.jpg)
![Screenshot_2020-05-07_12-37-35](https://user-images.githubusercontent.com/64950761/81292572-67448e00-909e-11ea-8c0c-59ef7fb48952.jpg)
![Screenshot_2020-05-07_02-34-16](https://user-images.githubusercontent.com/64950761/81292574-67dd2480-909e-11ea-8807-d24d003d8bab.jpg)
![Screenshot_2020-05-07_02-34-20](https://user-images.githubusercontent.com/64950761/81292576-6875bb00-909e-11ea-93e4-8fed89e0794e.jpg)
![Screenshot_2020-05-07_02-34-07](https://user-images.githubusercontent.com/64950761/81292579-690e5180-909e-11ea-9683-31de4a2535ee.jpg)

**Comment by arkon** [comment]
Your screenshots don't seem consistent with what the initial post shows.

Exactly what settings are you using that it shows up like that?

**Comment by CarlosEsco** [comment]
yea instead of going to settings.  go the manga with that issue then show the reader settings sheet

**Comment by Thenewfromdiscord** [comment]
I have deleted the app and downloaded another one I'm sorry.
