### ISSUE TITLE
[Bug] Position reset on webtoon after standby

### ISSUE THREAD

**Issue by DeeJack** [inorichi/tachiyomi#3104]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10.0.0
* Device: Honor View 10 Lite

## Steps to reproduce
1. Open a webtoon
2. Read a bit
3. Exit from the reader or put the phone on standby

### Expected behavior
The app should remember the position since it happens that an entire chapter consists of only 2 pages (but the pages are really long)

### Actual behavior
It goes back to the start of the page

**Comment by arkon** [comment]
#3028
