### ISSUE TITLE
[Bug] Scroll to bottom

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi#3105]
### Device information
* Tachiyomi version: r2252
* Android version: 9
* Device: Redmi 4X

## Steps to reproduce
1. open library/browse with long list
2. scroll to bottom (with bottom nav unhidden)

### Expected behavior
scroll to bottom

### Actual behavior
only scroll near the bottom

**Comment by arkon** [comment]
Screenshots?

**Comment by Riztard** [comment]
https://imgur.com/a/xwGXV2G

**Comment by arkon** [comment]
Closing in favour of #3143
