### ISSUE TITLE
All the mangas which are browsed from mangakakalot, mangakakalots, manganelo cannot be read in tachiyomi. 

### ISSUE THREAD

**Issue by LinhDoan1904** [inorichi/tachiyomi#3108]
### Device information
* Tachiyomi version: v.0.9.2
* Android version: 9
* Device: Vsmart Live

### Expected behavior
read normally
### Actual behavior
All the images from mangakakalot, manganelot started broken in 15.30pm 5/7/2020. I can not read any mangas from this source on the the app tachiyomi

**Comment by arkon** [comment]
You still didn't read the template instructions. This isn't the right repo, and it's already been reported multiple times.
