### ISSUE TITLE
[Feature Request] Use consistent buttons throughout the app

### ISSUE THREAD

**Issue by specterflare** [inorichi/tachiyomi#3109]
### Why/User Benefit/User Problem
Use a consistent button style throughout the app.

### What/Requirements
History and the Sources tab of Browse use borderless buttons, but the Extensions tab of Browse uses bordered buttons.

**Comment by CarlosEsco** [comment]
screen shots?  I feel its highly dependent on the page on what style button it should be

**Comment by specterflare** [comment]
yeah, hold on.

**Comment by specterflare** [comment]
![Screenshot_20200507-104103](https://user-images.githubusercontent.com/61708534/81308152-751ef280-904f-11ea-867e-eb75df9d89aa.png)
![Screenshot_20200507-104109](https://user-images.githubusercontent.com/61708534/81308154-75b78900-904f-11ea-9dde-d5ababb48026.png)

**Comment by CarlosEsco** [comment]
i see in that scenario i agree.

**Comment by specterflare** [comment]
history also looks like this:
![Screenshot_20200507-104636](https://user-images.githubusercontent.com/61708534/81308738-232a9c80-9050-11ea-9e84-08ea725bd26b.png)
but I'm not sure what would be best there

**Comment by CarlosEsco** [comment]
yea i think they should all be border less tbh.

**Comment by specterflare** [comment]
yeah, i agree

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi/commit/3b45fcdb216cb29ba4f4fc35dc4649efe4d6f2d7
