### ISSUE TITLE
[Feature Request] Option Toggle auto hide bottom nav

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi#3110]
### Why/User Benefit/User Problem
people that frequently use nav or want it like youtube/j2k/mangatoon/mangarock/whatever would be able to easily use without unhide bottom nav each time

### What/Requirements
if disabled, bottom nav wont hide

**Comment by arkon** [comment]
If you're referring to it hiding when you scroll, I'd rather not start adding a lot of configurations for minor things like that.

If you're referring it to not showing up on subviews, that's a definite no since it's hard to deal with the perceived state changes when switching between sections.

**Comment by Riztard** [comment]
the first one :(
