### ISSUE TITLE
I can't find my download 

### ISSUE THREAD

**Issue by mohammedula** [inorichi/tachiyomi#3111]
When I download a chapter I can't find it in the library yet I can find it in the local file in the device 

### Device information
* Tachiyomi version: v0.9.2
* Android version: android 9
* Device: Samsung Galaxy S8

## Steps to reproduce

What ?
(Couldn't understand)

### Expected behavior

Having the downloaded chapter in the library

### Actual behavior

Couldn't find any chapter

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
you have to add the manga to your library aka favorite it
