### ISSUE TITLE
[

### ISSUE THREAD

**Issue by JerloPH** [inorichi/tachiyomi#3114]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 6.0.1
* Device: Samsung J7 Prime

## Issue/Request

I want to request to replace the (Updates) Tab into (Download Queue).. 

For me, its useless and going into (More) to View your downloading chapters is a hassle.

Make it an option to change it at least.

Thanks!

EDIT:  Just wanna add to also include the source migration option in the (Library).

**Comment by arkon** [comment]
Configurable sections is far too much work considering how specific a lot of the routing is.
