### ISSUE TITLE
[Feature Request] Manga Suggestion Feature

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi#3116]
### Why/User Benefit/User Problem

It helps user to find similar manga / webtoon.

### What/Requirements

If tracker enabled for specific manga it should fetch recommended / suggested manga titles from tracker and should be listed as list in another tab when clicked on any title from suggested list it should be redirected to global search with title name.

**Comment by serjflint** [comment]
There is such feature in the Neko fork for Mangadex. Don't know if the devs will implement this for each source.

**Comment by CarlosEsco** [comment]
There are no plans to implement this in the main app at this time
