### ISSUE TITLE
AniList Sync Support

### ISSUE THREAD

**Issue by NotLemon** [inorichi/tachiyomi#312]
Hi,

Would it be possible to look into supporting sync with Anilist?
Our JSON API is fully documented [here](http://anilist-api.readthedocs.io/en/latest/) and not difficult to work with. Other users have successfully managed to create syncing apps.

Any issues/questions let me know.
The developer section can be accessed at [http://anilist.co/settings/developer
](http://anilist.co/settings/developer)

Thanks

**Comment by inorichi** [comment]
OAuth makes it quite hard to work with. Since I won't provide a client url, it would have to use the authorization pin. I played with it for a while with a WebView and tried to copy the pin with [a solution like this](http://stackoverflow.com/questions/3479833/is-it-possible-to-get-the-html-code-from-webview), but I don't like how it grabs the pin (looking a <h2> tag in the HTML). It would also be possible to let the user copy it though, but that's even more steps.

**Comment by joshstar** [comment]
You could use the authorization code grant with an android URI scheme, this will redirect direct to your application with the auth code so you wouldn't need to mess around with scraping web views. 

As for keeping the client secret private it should be stored locally on each users device once they've initially authenticated via oauth. It wouldn't be something you store for everyone in a central or public place.

**Comment by inorichi** [comment]
I mean the `client id` and `client secret` obtained from the developer section of AniList.

According to [this](http://anilist-api.readthedocs.io/en/latest/authentication.html#which-grant-type-to-use): 

> Both the current grant types have a client secret key, you are required to keep this private.

But then, they have to be known (compile time) before oauth, or am I wrong? Of course the refresh token would be stored locally for each device.

**Comment by joshstar** [comment]
Ah right the client secret, you can either put it in your source code, which would be the easiest way and plenty of other AniList API devs do it. Theres a risk someone else could use your details, but even then they won't be able to authenticate a user without the user secret which is stored on device, so its not a huge concern.

If we spot huge crazy spikes in the API logs we usually contact the app dev and issue them new details if someone else is abusing their API keys.

The better way to do it is to store your client keys in a separate (.gitignored) file and read from it on the device, if thats possible with your build setup.

**Comment by inorichi** [comment]
I could exclude the file from the source code, but then the F-Droid build won't be able to use the API, so my only option if I don't want to exclude them is to hardcode the values. I'll do that as you said it shouldn't be a problem.

Thanks for the clarification.

**Comment by inorichi** [comment]
The backend supports AniList in 534912c. It's now a matter of wiring everything with the UI and rewrite the "MAL" tab into something more generic and keeping in mind how to support the multiple score system from AniList in the UI.

**Comment by inorichi** [comment]
@joshstar What's the lifetime of the refresh token? Does it last forever or should I update it besides the access token? I discovered today some implementations expire the token after one usage, and time may be something to consider too.

**Comment by joshstar** [comment]
Refresh tokens last forever and shouldn't ever change in our implementation, access tokens last 1 hour.
