### ISSUE TITLE
Page listing is empty

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#313]
Sometimes when downloading a chapter or more i'tll say page list is empty in the notification and wont download. In addition i cant seem to read the chapter normally either

**Comment by wopian** [comment]
Version, manga source?

**Comment by inorichi** [comment]
Feel free to reopen this issue after providing more info.

**Comment by BlackSynder** [comment]
Screenshots for the error:
![screenshot_20160614-015330](https://cloud.githubusercontent.com/assets/9393241/16025903/0f730036-31d3-11e6-9434-6c9f886adb72.png)
![screenshot_20160614-015347](https://cloud.githubusercontent.com/assets/9393241/16025905/15323046-31d3-11e6-9bbc-6f7703bd763c.png)
It also gives a 'page list is empty' toast when trying to open a chapter.

**Comment by inorichi** [comment]
Version and source used, for example.

**Comment by BlackSynder** [comment]
Using 778 and kissanime

**Comment by inorichi** [comment]
Does it always happen or it's occasional? 
Does it happen on every manga from the source? 
What happens when you update the chapter list?

**Comment by BlackSynder** [comment]
It happens sometimes but some manga I can download normally but it's inconsistant so I cant reliably say "this" manga works or "that" doesn't. Updating doesn't change anything
