### ISSUE TITLE
[Feature Request] Chapter size

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi#3132]
### Why/User Benefit/User Problem
Better mobile data management when downloading chapters

### What/Requirements
Show chapter size in download queue

**Comment by arkon** [comment]
That isn't possible without actually downloading it.

**Comment by Mitia99** [comment]
> That isn't possible without actually downloading it.

I mean while downloading it(in download queue)

**Comment by CarlosEsco** [comment]
The most you can get is the number of image which is provided.  Until you download an image you don't know the size
