### ISSUE TITLE
[Bug] "Set as cover" doesn't take effect until restart

### ISSUE THREAD

**Issue by SalamiTTP** [inorichi/tachiyomi#3134]
### Device information
* Tachiyomi version: Stable 0.9.2
* Android version: Android Nougat (7)
* Device: Samsung S7 Active

## Steps to reproduce
1. Open any chapter for an entry in your library
2. Tap & hold any chapter image until context menu pops up.
3. "Set as cover"
4. Click "OK" in resulting popup
5. See unchanging cover image.

### Expected behavior
The selected image would be cached and then override the existing cover image in the library & details.

### Actual behavior
Confirmation popups appear and function, but does nothing afterwards. The cover image seems to be updated only after the app has been restarted.

**Comment by arkon** [comment]
Addressed by #3101
