### ISSUE TITLE
[Bug] Covers set as blank after checking for updates

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#3139]
### Device information
* Tachiyomi version: Preview r2289
* Android version: 10
* Device: OP-7

## Steps to reproduce
Update Library

### Expected behavior
Library updates and if cover failed to be retrieved or is blank it should not be updated.

### Actual behavior
If you update the library and it fails to retrieve cover you end up with manga without one.

### Other details
I think it's because covers are now updated when checking sources but if there is no cover from the source previous cover should be kept.

Edit : edited to respect template for submitting bugs

**Comment by arkon** [comment]
Addressed by #3101
