### ISSUE TITLE
[Feature Request] Support for "exclude" filters in Library view

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3140]
### Why/User Benefit/User Problem
We have this feature for sources filter sheet:
![Screenshot_Tachiyomi_20200510-190155~01](https://user-images.githubusercontent.com/63973749/81497541-c5b57a80-92f1-11ea-8f94-23145779d29c.png)

This would be a nice addition to the library filters sheet.

**Comment by arkon** [comment]
Duplicate of #1814
