### ISSUE TITLE
MyAnimeList login error

### ISSUE THREAD

**Issue by DavidG72** [inorichi/tachiyomi#3148]
Tach version: 9.2
Android version: 6.0.1
Device: samsung Galaxy tab s 8.4

I tried logging oit and in since I was unable to secure tracking for a book. It would search endlessly. I did this with Anlist and it seemed to work. Now when I want to log in to My AnimeKisa it comes up as an error after load for a bit. Can someone let me know if there is something I can do or is it an update needed on your end.

Thank you

### Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
Try clearing cookies first?

**Comment by DavidG72** [comment]
I will do that. However I tried going to the website and there was no
answer. Google whether it was down and it seems there is an error with
their server. I appreciate your help. I think I will wait and see. I will
let you know if this issue has been resolved.

Thanx again
