### ISSUE TITLE
[Bug] Status bar pops up in reader everytime in Force landscape rotation mode

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3149]
Device information
* Tachiyomi version: 0.9.2/Preview r2289
* Android version: 10
* Device: Galaxy S10+

## Steps to reproduce
1. Change Reader rotation to Force landscape.
2. Open any chapter.

### Expected behavior
Status bar shouldn't pop up (as it doesn't in any other rotation mode).

### Actual behavior
Status bar pops up.

### Other details
Only happens for Force landscape, not Force portrait or Free/lock

**Comment by serjflint** [comment]
Similar to #2068
