### ISSUE TITLE
MAL start date

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#315]
When binding manga, if it has 0 chapters read and 0 volumes read (or maybe if it wasn't in any list) set start date to today.

**Comment by AerosAtar** [comment]
I think this might be better if it updates in a similar way to some of the MAL anime updaters - when chapter's read goes from 0 to 1, mark **Start Date** as _"today()"_ and set **Status** to _"Reading"_.

Personally I have a list of manga that I plan to read (and therefore are in my MAL list), and have added them to my library in the app, but I am not currently reading them (thus the start date would be incorrect if the app updated it as soon as it was bound).

Possibly worth considering doing something similar once you have finished reading the final chapter of a finished series (i.e. those that are not ongoing) - mark the **End Date** as _"today()"_ and set **Status** to _"Completed"_.

**Comment by arkon** [comment]
Superseded by #2670
