### ISSUE TITLE
[Bug] v0.9.2 does not install on android 9

### ISSUE THREAD

**Issue by bsushmith** [inorichi/tachiyomi#3151]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: OnePlus5T

### Actual behavior
The installation fails with the message:
" App not installed"
And below just the option "DONE"

### Other details
downloaded from github release page
Additional details and attachments.
![Screenshot_20200511-064012](https://user-images.githubusercontent.com/6890568/81515613-91be7180-9352-11ea-83a8-a00f68747015.jpg)

**Comment by arkon** [comment]
If you installed an earlier version from F-Droid before, you'll need to do a backup, uninstall, install the new one, then restore.
