### ISSUE TITLE
[Tachiyomi Safe Mode] Tachiyomi version without hentai extension 

### ISSUE THREAD

**Issue by moktaryunani** [inorichi/tachiyomi#3155]
### Why/User Benefit/User Problem
Some manga reader(parent) have children below 18 that using the same application. Parent that wish to hide those hentai extension will benefit from this safe mode version. 

### What/Requirements
Options:
1. Make it as a alternate Tachiyomi version (new alternate apk)

or

2. To enable/disable hentai extension
     - It must be enable within deep settings 
     - put tachiyomi own password/challenge(not phone password) ...

**Comment by arkon** [comment]
Duplicate of #1758

**Comment by DragonWhisperer** [comment]
For me, hentai is the only problem when I want to recommend Tachiyomi.
