### ISSUE TITLE
It stuck for certain time to load Updates

### ISSUE THREAD

**Issue by Bikeam-tech** [inorichi/tachiyomi#3157]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1.0
* Device: OPPO A5s

## Steps to reproduce
1. Open app (Tachiyomi)
2. Then tap to "Updates" 

### Expected behavior
It should show all the manga which recently updated or the updates of all manga without any delay.

### Actual behavior
But it stucks for certain time and says "No Recent Updates"
![Screenshot_2020-05-11-13-25-28-27](https://user-images.githubusercontent.com/55379619/81536939-1da0bf80-938c-11ea-8f60-59def26caa1b.jpg)

### Other details
Later It shows all the updates after some time.

**Comment by arkon** [comment]
That only happens if the app is having issues reading the database, which is either when it's in the middle of restoring, or your phone's corrupted.
