### ISSUE TITLE
[Feature Request] Open tracking source in browser

### ISSUE THREAD

**Issue by ThatGuyAgain42** [inorichi/tachiyomi#3159]
### Why/User Benefit/User Problem
Currently there are a lot of people asking for features related to tracking; A lot of these issues could be fixed quickly if the user is presented the option to quickly go to their service in a browser.
(E.g. if a manga series has multiple entries on the tracking site you can easily go to the site in browser and fix it yourself)

### What/Requirements
How I would implement this:
When a user adds a tracking service, link the title of the service to the corresponding site (or even better directly to the current manga being viewed)
The user will then be prompted to confirm they want to go to the tracking site.

**Comment by CarlosEsco** [comment]
Once you link a manga to a tracker click the logo of the tracker.
