### ISSUE TITLE
[Feature Request] option to hide manga already in library in searches and catalogs

### ISSUE THREAD

**Issue by Bobbyaloplop** [inorichi/tachiyomi#3162]
Hi I don't know if this is better suited to here or extentions. If this is better suited for extentions ill remove and repost there or if it would be a good to post this there as well I will. As don't know if this would be an extension issue or tachiyomi. Thanks for your hard work.

my manga library is in the thousands currently and when I try to find new stuff I have to wade through hundreds of manga I already have in my library so I'd like to suggest the ability hide manga already in library for searches and in catalogs.

Just realized I deleted this part 

Why/User Benefit/User Problem
Faster to find new manga

What/Requirements
Either in tachiyomi settings for global hiding or per extension settings for hiding.

**Comment by Bobbyaloplop** [comment]
I should add that doing this for manga across extensions (hide one piece in mangadex if you have it in mangasee) would be ass to do so don't do that as even if you added it it would have to have input from the user as which are duplicates like source migration.

**Comment by CarlosEsco** [comment]
#2941
