### ISSUE TITLE
[Bug] Website not showing latest manga chapter by default

### ISSUE THREAD

**Issue by Imperius01** [inorichi/tachiyomi#3165]
When I search manga in a site added in my catalogue, it doesn't shows the latest manga chapter. I have to manually refresh the page to get the latest chapter. This is not happening in all sites but in a few sites like MangaDex, ReadM, ReadMangaToday, etc.

**Comment by CarlosEsco** [comment]
i see you deleted all of the template so i have clue what version of the app you are using.  anyways i assume its preview and there was a bug in the last release

https://github.com/inorichi/tachiyomi/issues/3137
