### ISSUE TITLE
[Bug] Library Update Stucks at random manga

### ISSUE THREAD

**Issue by Agayev033** [inorichi/tachiyomi#3166]
### Device information
* Tachiyomi version: Preview up-date
* Android version: 10
* Device: Xiaomi Mi A2 Lite

### Problem
When i want to get new Chapters and try to Update Library. İt Stucks at random manga

### Other details
Problem started after Update.
![Screenshot_20200512-203610](https://user-images.githubusercontent.com/30019351/81721286-b3257780-9490-11ea-873a-62763eb279a0.png)
Sorry for bad English.

**Comment by arkon** [comment]
#3137
