### ISSUE TITLE
One long image manga didn't fit properly to the screen

### ISSUE THREAD

**Issue by Nihisil** [inorichi/tachiyomi#317]
Version: 0.2.1
Source: ReadMangaToday (EN)
Manga: Tower of God
Chapter: Tower of God - 1

When you open the mentioned chapter and scroll to the second page it looks like this: 
![screenshot_20160528-224019](https://cloud.githubusercontent.com/assets/475367/15627889/583002c0-2525-11e6-81c0-ff036cca2432.png)

I think it is because manga has the first normal image and reader set up the screen to work with it width.

Is it possible to refit image to the screen after page changing?

**Comment by inorichi** [comment]
![qemu-system-i386_2016-05-28_16-46-45](https://cloud.githubusercontent.com/assets/3521738/15627926/ce1b72da-24f3-11e6-81e3-d754b9f6e443.png)

Works fine for me with "fit width". Also you probably want to use webtoon viewer for webtoons.

**Comment by Nihisil** [comment]
I see, didn't notice this settings. Thank you
