### ISSUE TITLE
[Bug] Troubling with updating

### ISSUE THREAD

**Issue by Yuuaki** [inorichi/tachiyomi#3171]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9.0
* Device: Asus Zenfone pro m1

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
You didn't provide any details. Did you install it from f-droid before?

**Comment by Yuuaki** [comment]
No
I downloaded from github

**Comment by arkon** [comment]
I think you can use this app to see why it fails to install: https://www.androidpolice.com/2020/03/24/apkmirror-installer-for-android-now-in-public-beta-lets-you-install-app-bundles-and-apks/

**Comment by Yuuaki** [comment]
Eh ?!
Why did it updated with it this app!!!!!

I tried so many times damn 

Btw thanks for recommending this to me 
It's updated
