### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by coff33ninja** [inorichi/tachiyomi#3172]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Favourites auto downloading once added to faviorites
### What/Requirements
(explain how this feature would behave)
It would be great to view the favorites apart from the downloaded items so it will be easier to navigate through the clusters of data. I come from letdown manga rock and the aspect that intrested me was the clean layed out interface between the data.if possible add a option in menu to change layout to say manga rock or a selection between many of the online app readers's layout. To attact more people to utilise this delicate artwork of a software with gui layout aswell as the wide variety of plugins and content. Sorry for bad english.

**Comment by arkon** [comment]
> Favourites auto downloading once added to faviorites

No, since people would complain that they accidentally ate up their data.

> It would be great to view the favorites apart from the downloaded items

Also no, since that's not how the underlying system works. Tachiyomi does not model downloads the same way that MR does.
