### ISSUE TITLE
Migrate non-found backup sources

### ISSUE THREAD

**Issue by JxM-92** [inorichi/tachiyomi#3181]
Hi, I really love this app...

So... My phone broke in Feb this year, so I stopped using the app from back then, now that I have a new phone I installed the app (apparently is updated with new features, I'm shocked! Thanks) and tried to restore using my last backup from feb2020... The problem is that a lot of mangas aren't being restored because it, for some reason, can't find the sources when I actually installed all the English/All sources and should work, this is the log: 
![Screenshot_20200515-024047](https://user-images.githubusercontent.com/645579/82025869-87a0b980-9657-11ea-874f-246e019c1828.png)

Anyways, I'll have to add them manually, so here is my request: to be able to migrate those restored mangas which the source can't be found, that way people won't lose the last read chapter, because, in my case, I don't quite remember where I left on some of those...

Thanks...

**Comment by JxM-92** [comment]
Or at least be able to automatically add them from another source... I guess it's the same but with different wording... 😅

**Comment by CarlosEsco** [comment]
#2479
