### ISSUE TITLE
[Feature Request] Add Plan To Read list and Custom Lists

### ISSUE THREAD

**Issue by DragonWhisperer** [inorichi/tachiyomi#3183]
### Why/User Benefit/User Problem
- I get updates for titles I don't read currently.
- I want to organize my titles by topic or interest.

### What/Requirements
For the first problem, add Plan To Read list instead the single library. titles in this list will not get updates.
For the second problem, add custom lists and let the user choose things like the list color and the Updates-Mode of the list.

**Comment by Flat** [comment]
You can use categories for both of these use cases.

**Comment by DragonWhisperer** [comment]
> You can use categories for both of these use cases.

Oh I see...
Well, just to make this option clearer, I suggest:
- Add the "Reading" and "PTR" categories by default.
- Add "+" button on the top categories list to quickly add a new category.

**Comment by arkon** [comment]
There's no plans to change the default category since that's too opinionated.

Categories also generally aren't modified often enough to warrant having it upfront like that.

**Comment by DragonWhisperer** [comment]
> There's no plans to change the default category since that's too opinionated.
> 
> Categories also generally aren't modified often enough to warrant having it upfront like that.

You're right, maybe "+" button is not a good idea.
But default READING and PTR are pretty basic and widely used, and it also shows the categories advantages to new users (like me).
