### ISSUE TITLE
[Feature Request] tags/genre can be search for manga recommendations

### ISSUE THREAD

**Issue by aoiaoiaoi1** [inorichi/tachiyomi#3185]
---

### Why/User Benefit/User Problem
(explain why this feature should be added)
- So that we will have recommendations for the particular manga/manhua/manhwa/webtoon's genre. It's a good shot tho just like in mangarock.

### What/Requirements
(explain how this feature would behave)
-it will show a lot of manga/manhua/manhwa/webtoon comic everytime you search or click tags in them, and you will encounter about manga/manhua/manhwa/webtoon you'll barely knew about and yeah recommendations.

Thank you!

**Comment by arkon** [comment]
This isn't feasible since the app doesn't know anything about the sources and its contents.
