### ISSUE TITLE
[Feature Request]skip timed-out title

### ISSUE THREAD

**Issue by rafalohaki** [inorichi/tachiyomi#3186]
I suggest to add skipping title when it's time out about 20 seconds in updating.

It's happening randomized. I migrated few titles from other sources and still it's freezing when updating. Now I have 5hours of updating and it's freezed at 20% of titles.
PS. Sry for bad phrases

**Comment by arkon** [comment]
It already does. If you're using preview, it's likely due to this issue: #3137
