### ISSUE TITLE
Failure to load Batoto page list, other catalogues work fine

### ISSUE THREAD

**Issue by otoryuo** [inorichi/tachiyomi#319]
Most of the time, I cannot load chapters from Batoto.  The chapter attempts to load, then gives an error stating that the page list could not be loaded, and states that I should chzck my internet connection. Occasionally I will be able to load batoto chapters, but it's more the exception than the rule.  I've checked, I can access batoto just fine using other manga apps and my browser.  Other sources have no issue.  

What I've tried:

* Resetting my phone - occasionally successful
* Restarting app - almost never helps
* Resetting permissions - helps occasionally
* Uninstalling/reinstalling app - did not help
* Relogging into batoto from the sources menu - most of the time, cannot connect here either

Version:  v0.2.1 (latest)
Android 6.0.1/Cyanogen Dragonfruit, nexus 6

**Comment by NoodleMage** [comment]
@inorichi rewrote the source parser. Could you please check if you have the same problems on the dev version?

**Comment by inorichi** [comment]
Restarting your phone won't solve anything from the app's side (in this case it would be a bug in the OS). 
Permissions aren't required unless you are using downloads, so that's not the issue either.
IIRC, chapters can load even if you are not logged in.

You could try using the "clear chapter cache" from the advanced section in the settings.

**Comment by otoryuo** [comment]
It's started letting me log back in to batoto again, and that seems to let me load chapters.  It looks more like the issue is with being logged out of batoto whenever I change networks.  

Should I close this, and should I open a new issue for being logged out on network change?

**Comment by NoodleMage** [comment]
I tried to recreate your issue. 

I did the following on both the release and the dev version. 

1. I logged in on my home network. Added "shoguki no soma". Downloaded one chapter.
2. Went to my university logged into their network and tried to download another chapter 
Result:
Release: page list cannot be loaded. Had to login again to fix it.
Dev: works perfectly. 

@otoryu I ask again if you can try if it works on the dev version. If not could you please give the exact step to recreate it.

**Comment by otoryuo** [comment]
So far, it happens when I switch networks, and resolves once I relog.  

I'll try dev once I get a chance.  It may be a bit before I have time to get to my desktop and run a backup.

**Comment by inorichi** [comment]
You can have both versions installed. No need to mess with backup and uninstall.

**Comment by jbowwow02** [comment]
I think this has something to do with new cloudflare protection methods. Almost all cloudfare websites I visit require a CAPCHA click (started today).

**Comment by inorichi** [comment]
Try this: 

1. Delete chapter cache (advanced tab)
2. Open a manga and update the chapter list
3. Open **an old chapter** (more than 1 month since the upload)
4. Kill the app
5. Open another old chapter 
6. If chapter didn't load on step 5, update the chapter list and try to open it again.

**Comment by jbowwow02** [comment]
Alright tried it and got a bunch of errors. Other sources refresh fine but batoto sources give a no connection error.

This when trying to open a chapter
![photo_2016-06-01_18-35-24](https://cloud.githubusercontent.com/assets/4137235/15710455/baa225d2-2827-11e6-9bde-a4bdd36e0ce8.jpg).

It also appears that I cannot actually sign in to batoto anymore
![photo_2016-06-01_18-31-20](https://cloud.githubusercontent.com/assets/4137235/15710480/d642e902-2827-11e6-90ab-f47a76230f53.jpg)

**Comment by otoryuo** [comment]
@inorichi It's been working on relog after network changes.  I'll try these steps next time it happens.  No issue on dev version, though I've only had the issue occur twice since I last posted.  

@jbowwow02 That doesn't seem to be the same error.  It shows the "Cannot load page list.  Please check internet connection" message.  I haven't been able to screenshot it yet.

**Comment by inorichi** [comment]
I think it's not because of network changes, but the app being killed (probably after being a while in background). Dev version has persistent cookies, so they are recovered after application restarts. Batoto requires to be logged for old chapters, and that's probably why that happened.

@jbowwow02 yes, that's probably the captcha from cloudflare. Your IP is being flagged for captcha somehow (probably an entire region). There's no workaround for that at the moment.

**Comment by otoryuo** [comment]
@inorichi - I've whitelisted the release version in my memory management app.  I'll report back after a bit.

**Comment by inorichi** [comment]
Is this still an issue?

**Comment by otoryuo** [comment]
As far as I can tell, no.  

Sorry for delayed reply.  I've been on vacation and only had cellular data for a while.
