### ISSUE TITLE
[Bug] Blank covers for manga after restoring backup

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3190]
### Device information
* Tachiyomi version: r2331
* Android version: 10
* Device: Galaxy S10+

## Steps to reproduce
1. Install fresh Preview
2. Restore backup

### Expected behavior
Covers should show for all manga.

### Actual behavior
Blank covers are shown for around half the manga. Refreshing doesn't fix.

### Other details
Covers don't load in either Library or INFO page. Refreshing does nothing.

**Comment by MCAxiaz** [comment]
Which manga are failing? What sources are they from? And can you share the backup file?

**Comment by joseph619** [comment]
It does not appear to be source specific, as my Library is majority Mangadex. I will send you my backup on Discord.

**Comment by arkon** [comment]
This is probably because MangaDex is struggling.

**Comment by MCAxiaz** [comment]
Yea I think it's just mangadex dying. I tried your file, and most of the covers were blank but after I waited out a while they eventually loaded in. I timed a refresh in the info page and it took over 30 sec for the image to load.
