### ISSUE TITLE
[Feature Request] connection between different versions

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi#3196]
---

### Why/User Benefit/User Problem
Some user use more than one fork of tachiyomi as well as the regular stable build. And they may have to constantly transfer mangas or manhuas between them

### What/Requirements
So theres are multiple options in tachiyomi (one for each fork that will be used in this feature) that when enabled, will share libraries with whatever fork you enabled it for. For example, when I add a manga to my library in the tachiyomi preview build, I can also see that same manga in the j2k build, or the stable build.

**Comment by arkon** [comment]
This would only really be plausible if the apps were to share the database(s), but I don't think _any_of them actually share the exact same schema, and managing migrations between them would be a nightmare.

Having such an extreme state of compatibility with forks isn't really in scope for the core app anyway.

**Comment by Mechanical-sanity** [comment]
Well shit. It was at least worth asking
