### ISSUE TITLE
[Feature Request] Last Updated ordering

### ISSUE THREAD

**Issue by JxM-92** [inorichi/tachiyomi#3198]
Hi...
sorry if this have been already requested...
I usually search for mangas across many sources at the same time, and it would be very useful to have a feature that order all the results in last chapter added date, that way the user won't have to check every single result to check which one is the one being updated on time or the first one to upload the chapters... 

thanks...

**Comment by JxM-92** [comment]
> Hi...
> sorry if this have been already requested...
> I usually search for mangas across many sources at the same time, and it would be very useful to have a feature that order all the results in last chapter added date, that way the user won't have to check every single result to check which one is the one being updated on time or the first one to upload the chapters...
> 
> thanks...

I mean order the results by the last added chapter and, those that have the same chapter uploaded, by date... and, if it's possible (I guess is not that simple), compare them to the release date of the last chapter uploaded date...

for example, sometimes some sources take time to upload some chapters, so if Sources A to C has up to chapter 100 and Sources D to E has up to chapter 99, first order them by the last uploaded chapter, and then order Sources A to C in updated date order putting first the fatest one to upload it (the closest one to the release date)...

I know that usually is better to stick with 1 source, but when you read a lot of mangas, there is no source that will have all the mangas you want to read updated to the last chapter released...

thanks...

**Comment by CarlosEsco** [comment]
order them where? in global search?

**Comment by JxM-92** [comment]
> order them where? in global search?

yes, in global search... because I've had the problem that some source suddenly stops uploading on time, or just stops for that title, or is some chapters behind the release...

**Comment by CarlosEsco** [comment]
Not happening. Tachi would need to make another network request per every manga in global search

**Comment by JxM-92** [comment]
> Not happening. Tachi would need to make another network request per every manga in global search

🤔 you're right... I understand... what about limiting the feature to a short amount of sources? like after doing a global search, comparing results on some sources, or only on sources with a short amount of results, like only 3 results max?

**Comment by JxM-92** [comment]
also, some sources have the option to order in last updated date, so maybe you don't need to actually make a request to each title and just catch the info given by the search result of each source... hmm... although sources often don't show the date on search result... 🤔
