### ISSUE TITLE
[Bug]  Webview not sync cookies

### ISSUE THREAD

**Issue by weiang123** [inorichi/tachiyomi#3199]
## Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1
* Device: MEIZU 16th Plus
* Webview: Chrome 81

## Steps to reproduce
0. update webview in google play, clear tachiyomi cookie and cache
1. Go to explore Browse and click on BROWSE beside the source. Then open a manga and click on WebView .
2. chaptch is shown,  and i solve it
3. use the aforementioned **close button** the bar at the top of your screen to go back to your manga. (no back arrow on my device on top left, only have close button)

### Expected behavior
explorer resource

### Actual behavior
still 403

### Other details
[NSFW content removed]

**Comment by arkon** [comment]
Can't reproduce. This sometimes happen if the Cloudflare protection is a high enough protection level where the cookies aren't sufficient enough to bypass it automatically, which there's no workaround for at the moment.
