### ISSUE TITLE
More options to Recent Updates tab

### ISSUE THREAD

**Issue by kiskae491** [inorichi/tachiyomi#320]
It would be nice to refresh mangas, download/delete/mark as read/unread multiple chapters in recent updates tab. Same or similar to opening individual manga as in screenshot.
![screenshot_2016-05-31-22-48-19_eu kanade tachiyomi](https://cloud.githubusercontent.com/assets/19674786/15690160/7fed7bd0-2782-11e6-95b7-e5094ebe20c4.png)
Thank you for your hard work

**Comment by NoodleMage** [comment]
You're welcome. Thanks for the feedback. 
I will try to implement it when I have some time ;)
