### ISSUE TITLE
[Bug] Large single-tap deadzones when tapping-navigation is disabled on webtoon viewer mode 

### ISSUE THREAD

**Issue by geominorai** [inorichi/tachiyomi#3204]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung Galaxy S9+

## Steps to reproduce
1. Enable webtoon or continuous vertical viewer mode
2. Disable tapping navigation
3. Open a manga chapter to read
4. Tap either side where normally tapping would turn pages.

### Expected behavior
The top (title) and bottom (scrollbar) overlay panels should appear or disappear when tapped.

### Actual behavior
Nothing happened.

### Other details
This appears to be an overlooked case as other viewer modes like left-to-right and vertical mode will allow the whole page to be tapped to toggle these panels.

**Comment by CarlosEsco** [comment]
do they?  I was pretty sure only tapping the middle of the screen on viewers brought up the overlay panels

**Comment by geominorai** [comment]
@CarlosEsco Yes, they do when tapping navigation is disabled.

Also my bad, I just found out this bug is specific to J2K and I cannot replicate it on main.  I'll repost the issue there.
