### ISSUE TITLE
[Bug] | Remove after read: Second to the last chapter | not properly working

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi#3205]
### Device information
* Tachiyomi version: 0.9.2-2331
* Android version: 6.0.1
* Device: Samsung J2 Prime Enigma V2 ROM

## Steps to reproduce
1. Set [Remove after read] to Second to the last page. 
2. Read or just skip a downloaded chapter with a read downloaded one before it until its last page. 
* For instance this chapter of great deity in which I was reading:
   ![Screenshot_20200519-191118](https://user-images.githubusercontent.com/51081028/82320443-deb2df80-9a05-11ea-875e-f9d08bc1a090.png)

### Expected behavior
* Chapter 18 (in this instance) will be deleted. 

### Actual behavior
* Chapter 18 (in this instance) will remain downloaded.

### Other details
* But if you try to read 2 or more chpaters the 2nd to the last chapter of the read chapters after the first one will be deleted except the 2nd to the last of the first one you've read. Please refer to the images. 
   ![Screenshot_20200519-191157](https://user-images.githubusercontent.com/51081028/82321495-7d8c0b80-9a07-11ea-91c1-1586d9ee39a1.png)
   ![Screenshot_20200519-191300](https://user-images.githubusercontent.com/51081028/82321564-9dbbca80-9a07-11ea-9cde-8621087d670b.png)
   ![Screenshot_20200519-193436](https://user-images.githubusercontent.com/51081028/82321721-e5daed00-9a07-11ea-9866-8470efe65d13.png)
   ![Screenshot_20200519-193504](https://user-images.githubusercontent.com/51081028/82321891-2c304c00-9a08-11ea-93db-7c51393bbf55.png)
* Did not tried other settings of [Remove after read] if they are having the same issue.

**Comment by SecT0uch** [comment]
I second that

**Comment by SaruDesu** [comment]
Okay, this seem to be caused by the "Skip chapters marked as read" setting, in which causes tachiyomi and also its some other settings to exclude read chapters (as in not consider read chapters as a chapter).
