### ISSUE TITLE
[Bug] Shikimori traking isn't working 

### ISSUE THREAD

**Issue by PuzlOK** [inorichi/tachiyomi#3209]
After reading chapters, it does nothing to write progress to shikimori.org.

**Comment by arkon** [comment]
@Pavkazzz Do you want to take a look at this? I don't use Shikimori.

**Comment by Pavkazzz** [comment]
Ok, take a look

**Comment by Pavkazzz** [comment]
@PuzlOK What parser did you use? Page number recognition can be broken in extension

**Comment by arkon** [comment]
Closing since no response or similar reports.
