### ISSUE TITLE
[Feature Request] Timeout function on stalled update checking on a title

### ISSUE THREAD

**Issue by HereticWilson** [inorichi/tachiyomi#3211]
### Why/User Benefit/User Problem
Recently when the app has gone to update my library, it gets stuck on a title, and will quite literally sit there all day with that title in the notification bar, apparently constantly trying to check for updates. So not only do I never get that title, it freezes less than half way through and I have to refresh each title manually. If there were a way for the app to detect nothing is happening after 5 or 10, minutes and just move on that would be great.

**Comment by bbtora** [comment]
Please state the app version. This was a recent bug which has been fixed in the latest preview build.

**Comment by HereticWilson** [comment]
Yeah go ahead and close this, a while after I posted this I saw there was a new version and now it's working fine
