### ISSUE TITLE
[Bug] Chapters loads and downloads very slow

### ISSUE THREAD

**Issue by deebeepea** [inorichi/tachiyomi#3214]
### Device information
* Tachiyomi version: r2331
* Android version: 5.1
* Device: Lenovo Tab 2 A8-50F

## Steps to reproduce
1. Downloader keep saying "Invalid download location" after downloading a few chapters
2. Chapters downloads slow and Pages loads slow even when the internet connection is fast

### Expected behavior
It should load fast
And downloads smoothly

### Actual behavior
Loads and downloads very slow

### Other details
This happened about 10-15 days ago. I don't know what App version it started to act like this.

**Comment by arkon** [comment]
Do you have enough disk space?

**Comment by deebeepea** [comment]
> Do you have enough disk space?

Yes I have enough disk space and downloads go to sd card

**Comment by reiny2000** [comment]
Same here.
Tachiyomi version: r2331
Android version: 8.0.0
Device: Motorola Moto Z
Started experiencing slow loads and downloads three days ago.

**Comment by arkon** [comment]
Download speed depends on the sources, not the app.

The only potential issue here is "Downloader keep saying "Invalid download location" after downloading a few chapters", but that sounds like your device's storage is failing for some reason.

**Comment by arkon** [comment]
Not enough info; largely depends on source website speed.
