### ISSUE TITLE
Tracking via MyAnimeList isn't possible for oauth accounts

### ISSUE THREAD

**Issue by forever-and-a-day** [inorichi/tachiyomi#3215]
it should be possible to log into MyAnimeList oauth accounts (sign in thought google, fb, etc) by using a webview

**Comment by arkon** [comment]
We'll revisit this if MAL ever actually releases a proper API again.

**Comment by arkon** [comment]
API doc reference: https://myanimelist.net/apiconfig/references/api/v2

Currently still lacking some functionality to match feature parity in the app.

**Comment by soredake** [comment]
Any progress on this?

**Comment by arkon** [comment]
This is possible in 0.10.6+
