### ISSUE TITLE
[Feature Request] Partial Chapter Handler

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi#3217]
### Why/User Problem
There are some manga sites or scanlators who release chapters of a manga/manhwa/manhua/comic partially. Because of this, trackers have been mis reading a partial chapter as a whole chapter thus adding a count in the trackers. 

### What/Requirements
This feature can be created by having a function that handles the chapter numbered x.y as a single collection chapter of chapters numbered x for any y  so that it would update the tracker for that chapter only once.

**Comment by arkon** [comment]
How would it know which one is the last partial chapter?

**Comment by SaruDesu** [comment]
> How would it know which one is the last partial chapter?

If x is updated. For example: There is chapter 1, then the manga updated another chapter which is 1.1 then chapter 2 is updated then chapter 1.2 is updated; In this case, the no. chapters read will only be counting x not y so even if chapter 1.100 is updated then the chapters reead will not be updated in the counter, so the chapter that  will then be counted is the chapter two. This method assumes that y is infinite for every x. Thus not knowing what is the last partial chapter. (I think this method will be only be applicable for tracking).
