### ISSUE TITLE
[UI] Change color of update icon

### ISSUE THREAD

**Issue by scb261** [inorichi/tachiyomi#3218]
When updating the library, the icon in notification almost invisible because of the dark color. Now, when I look at the screenshot on computer, it's more visible, but on phone I'm not always sure that it's here. Especially when there are no other notifications.
 
![Screenshot_2020-05-21-12-37-46](https://user-images.githubusercontent.com/65343233/82546558-f2bf2400-9b60-11ea-9ac0-6fde36f61130.png)

**Comment by CarlosEsco** [comment]
Phone model?

**Comment by scb261** [comment]
Huawei TIT-U02, Android 5.1

**Comment by scb261** [comment]
Not sure why you labeled it bug, I'll clarify just in case. By "I'm not always sure that it's here" I mean that I not always can recognize it because of low contrast, but it still there.

**Comment by CarlosEsco** [comment]
are you  running a custom theme?    I labelled it bug because it shouldn't be black on a dark system ui

**Comment by scb261** [comment]
App theme: Dark
Dark theme variant: Default
App version: 0.9.2

**Comment by CarlosEsco** [comment]
I meant on your system are you running a custom dark theme?

**Comment by arkon** [comment]
Yeah we just use the system's downloading icon. If it's not the right colour, it's probably due to Huawei's ROM.

**Comment by scb261** [comment]
No, I'm not even sure how to change system ui. If you mean rom chip, then no, I didn't change it. 
I have developer options enabled, just now disabled it and restarted phone, but the icon still dark.

**Comment by scb261** [comment]
Is there a way for me to check if it works, or should I wait until next update?

**Comment by arkon** [comment]
You'll need to wait for the next update.

**Comment by scb261** [comment]
Since I downloaded and built the app for another reason, also checked this one. The icon is still black, so I guess the issue should be reopened.

And also I found that not only the update icon, but also the pause icon (when you pause download queue) also black. While others are white (like in the screenshot in the first comment). I guess they have the same reason, but maybe it'll help to debug it.

**Comment by scb261** [comment]
Not sure if the issue should be reopened since it seems to be phone model specific, I'm just gonna say that the bug is still present and add some info about it. My phone has black background for top bar in half of my apps. In other half it depends on app's color scheme, and when such app has light theme - the icon is more visible, here are examples https://imgur.com/a/bo7JkKU where the last one is Tachiyomi with light theme. I tried to search it in phone settings, but couldn't find anything for this.

**Comment by arkon** [comment]
I'm still going to blame your device ROM for that, considering the icon itself is white and I do the same thing as other notification icons for that particular one.

¯\_(ツ)_/¯
