### ISSUE TITLE
While reading any chapter on wifi it should be downloaded

### ISSUE THREAD

**Issue by sm7297** [inorichi/tachiyomi#322]
For example if i read chapter 487 of fairy tail on wifi and clear cache in advanced tab and then there is no wifi i can't read chapter 487 again i need to download it again. Instead if it is downloaded while reading this would make sense so i can read the same chapter when there no wifi and add option for this in downloads menu like download to sd card while reading it would make things easier

**Comment by NoodleMage** [comment]
I don't think I fully understand what you mean. Isn't this the point of clearing cache. It removes the downloads made while reading from the catalog. 

If you want to download something and keep it you can add the manga to the library and download the desired chapters for later reading.

**Comment by inorichi** [comment]
Then don't clear the cache, the chapter is downloaded there. You already have the option to download chapters, use that if you want to keep them forever.

I'm considering a configurable cache size though.

**Comment by sm7297** [comment]
Hmm let me explain it like this previously i use manga watcher in that application whenever i read the manga it stored in the location set in downloads menu which mean after i read in mangawatcher i can read the same chapter in any other application like perfect viewer to read it again.
i checked in my sd card there is no image files the tachiyomi folder of the manga which i read

**Comment by inorichi** [comment]
I see. Then it's a duplicate of #321, which probably won't happen anytime soon because it requires a new design and a full rewrite.
