### ISSUE TITLE
[Bug] Parsing error on Galaxy Tab 3

### ISSUE THREAD

**Issue by AxezCore** [inorichi/tachiyomi#3220]
---

### Device information
* Tachiyomi version: 0.8.5
* Android version: 4.4.2
* Device: Samsung Galaxy Tab 3 (GT-P5210)

## Steps to reproduce
1. Allow unknown sources
2. Clear app cache.

### Expected behavior
Install latest version of Tachiyomi.

### Actual behavior
There was a problem parsing the package.

### Other details
Tried both this version and Jays2kings version, both produce the same error.

I can update the extensions without any issues.

**Comment by MerradOklom** [comment]
Starting with version 0.9.0 the app only support Android 5.0+ (6.0+ for TachiyomiJ2K).
