### ISSUE TITLE
Failed to load, "no chapters found"

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#3223]
I updated yesterday after months (i forget to update since no auto-update), I use the dev/preview branch (r2331), and this happens to me too.
When you try to update, some manga get "failed to update **x** manga", if you open the log it won't show you the source that errors, only the manga list and the error "no chapters found".
[Image 1](https://user-images.githubusercontent.com/22413659/82642316-feb4ef80-9c0d-11ea-87c8-cd2623d47609.png)
[Image 2](https://user-images.githubusercontent.com/22413659/82642352-0a081b00-9c0e-11ea-8860-f68598b907f1.png)
In these images above it shows the notification for the error, as you can see, the manga that error change.
To fix this (it only works once, you have to do this process every time) I cleared the cache and also updated manga covers (this maybe not required, but I do them together, since I noticed the manga with errors had an entry without cover anymore).

_Originally posted by @antocs in https://github.com/inorichi/tachiyomi/issues/3194#issuecomment-632539515_

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi/issues/3226#issuecomment-632720132
