### ISSUE TITLE
REQUEST For Local Source

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3224]
**1st** **Request**

I Would Like To Form A request Wherein The Covers Are Files Without Extension.. Because Some Of the Covers aare Showing In my Gallery... (e.i. Cover.jpg - - - > cover) to avoid Showing Into the Gallery

 **2nd** **Request**

Can Edit the Json File In the App.. 

**3rd** **Request** 

Change the Local Source Location because if my Files are no inside the zip file It Show Into my Gallery and It's So many... It laggy.

**Comment by CarlosEsco** [comment]
Add a .nomedia file to the local manga folder

**Comment by ImPudding-tech** [comment]
Thanks...

**Comment by shashank-p** [comment]
Can't we just programmatically add .nomedia file whenever source folder is created

**Comment by pervertkirito** [comment]
> Can't we just programmatically add .nomedia file whenever source folder is created
https://github.com/inorichi/tachiyomi/blob/ce0090f0cab2619703ff903ad80a188bc62e5214/app/src/main/java/eu/kanade/tachiyomi/util/storage/DiskUtil.kt#L54

Blame custom skin by OEMs for changing how android work.

**Comment by CarlosEsco** [comment]
just checked its only added for downloads.  Since tachiyomi is creating the folder.  A user for local should just have to put one in tachiyomi/local for all local manga to be ignored
