### ISSUE TITLE
Laggy Reader

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3225]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Huawei

## Steps to reproduce
1. I Open Any manga. 
2. If the File is To long or the height of the photo is to long... The Reader is Starting To Lagg.... 

### Expected behavior
Smooth Reader

### Actual behavior
It Became A Robot. 
Its Scroll Like a Printer. 

### Other details
Additional details and attachments.

**Comment by ngomile** [comment]
I've also experienced this with things like manhwa where the image for a single page is very long. My device is a Samsung Galaxy A20 running Android 9 and running Tachiyomi preview version r2331.

**Comment by arkon** [comment]
Closing in favour of #1908.
