### ISSUE TITLE
[Bug] Doesn't finish downloading

### ISSUE THREAD

**Issue by watterson21** [inorichi/tachiyomi#3229]
![Screenshot_2020-05-24-07-54-58-585_eu kanade tachiyomi](https://user-images.githubusercontent.com/65836031/82742949-c8ef4280-9d96-11ea-8a4b-5bd14fc2e55d.jpg)

### Device information
* Tachiyomi version: App version: 0.9.2 (standard, 43c11c6ac, 45)
Android version: 9 (SDK 28)
Device brand: xiaomi
Device manufacturer: Xiaomi
Device model: Redmi Note 7

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by kai000bubbles** [comment]
I have an issue with downloading the v2353 update today it just gets stuck at the end too

**Comment by SomeZer0** [comment]
> I have an issue with downloading the v2353 update today it just gets stuck at the end too

This happened to me too, tried checking for an update again, and it got stuck at the end as well. (Though manually downloading and installing the update worked fine)

**Comment by kai000bubbles** [comment]
> > I have an issue with downloading the v2353 update today it just gets stuck at the end too
> 
> This happened to me too, tried checking for an update again, and it got stuck at the end as well. (Though manually downloading and installing the update worked fine)

How did you manually download the update?

**Comment by SomeZer0** [comment]
> How did you manually download the update?
Tachiyomi.org and click download. It will give you an option for the stable build or the preview.
