### ISSUE TITLE
[Feature Request] Bookmark icon on History page

### ISSUE THREAD

**Issue by DeeJack** [inorichi/tachiyomi#3239]
### Why/User Benefit/User Problem
I have a very bad memory, I always forget if I already bookmarked a manga I was reading or not, so I check it like 10 times every time. Yes, I'm stupid.
But it would be good to have a simple icon that shows if a manga is bookmarked in the history page.

### What/Requirements
A simple bookmark icon that shows in each container, if the manga is bookmarked, in the History page.

**Comment by CarlosEsco** [comment]
You mean favorited?  Also why not favorite everything you are reading and removing the favorite only when when done or dropping the series

**Comment by arkon** [comment]
My question would actually be why does it matter? Does it help to know that information from the history page?

**Comment by DeeJack** [comment]
I already said at the start why I wanted this feature, if you think it's useless for most of the people let's just close.

**Comment by arkon** [comment]
I was getting more at why you need to know if it's bookmarked. Are you trying to figure out what to delete? Or maybe you're trying to make sure everything's bookmarked?

**Comment by DeeJack** [comment]
It's to see if I bookmarked everything I like, since I start many, many series together, then drop one after the other and lose track of which series I liked.
It's pretty useless, no need to waste time working on it.
