### ISSUE TITLE
[Feature Request] Downloadable language files

### ISSUE THREAD

**Issue by AmeerReal** [inorichi/tachiyomi#3240]
### Why/User Benefit/User Problem
Maybe it would decrease the size or something? Even though they're not that big.

### What/Requirements
A download button besides each language to download it and use it as the app's current language. English is downloaded by default. The system's default language may be also downloaded by default?

**Comment by CarlosEsco** [comment]
I don't understand?  All the languages in the app are already built in you aren't downloading any language file

**Comment by CarlosEsco** [comment]
Also if your saying I don't use these other languages I want to be able to download them. They don't take up that much space

**Comment by arkon** [comment]
Yeah, no. Not worth the effort, it barely takes up any space.

**Comment by pervertkirito** [comment]
I think it might be a great idea.
we don't have to wait for every releases for new translation to be updated.

**Comment by arkon** [comment]
Strings are compile-time resources, so it's not going to happen anyway.

**Comment by AmeerReal** [comment]
@arkon 
:|
OK, thank you for at least TAKING A LOOK at what I suggested.
I SURE took some time from you.

**Comment by AmeerReal** [comment]
@pervertkirito 
See?
