### ISSUE TITLE
[Bug] Queuing downloads pauses with error

### ISSUE THREAD

**Issue by Fred5659** [inorichi/tachiyomi#3243]
### Device information
* Tachiyomi version: Latest
* Android version: 9.0
* Device: SM-G965F

## Steps to reproduce
1. Queue A chapter(s)
2. Download pauses with an error (I know I'm providing very little info without any logs, since I don't know how to record one in the first place but this might help :- Mangabat (EN) A Returners Magic Should be special, {you might say there's a problem with the extention not the app itself, then let me tell you one thing it started to spread in all of the extensions whenever I try to download chapter(s) from any source & manga}

## Issue/Request
App version: 0.9.2 (standard, 43c11c6ac, 45)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.G965XXU8DTC5
Device brand: samsung
Device manufacturer: samsung
Device name: SM-G965F
Device model: SM-G965F
Device product name: SM-G965F

After queuing chapters for download it gives an error

**Comment by Fred5659** [comment]
This thing

**Comment by arkon** [comment]
What's the error say?

**Comment by aymanrady** [comment]
I'm not sure how to pull the debug log, but this the notification I'm getting
![Screenshot_20200619-171245_Tachiyomi](https://user-images.githubusercontent.com/2373059/85149313-d0045600-b259-11ea-9432-63bb6fcd6163.jpg)

Device Model: SM-G985F/DS
Android Version: 10
App Version: 0.9.2

**Comment by arkon** [comment]
Not enough info, closing.

Full storage issue was addressed separately by preventing downloads when available storage is low.
