### ISSUE TITLE
[Bug] <Update Library Failed >

### ISSUE THREAD

**Issue by dondeepak** [inorichi/tachiyomi#3244]
### Device information
App version: 0.9.2-2353 (standard, ac8f2923, 45)
Android version: 9 (SDK 28)
Android build ID: PKQ1.181030.001 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1951
Device model: vivo 1951
Device product name: 1951

## 
Update Failed for some manga.
Failed manga opens in webview can be read but every time selected manga failed to update 

### Other details
Additional details and attachments.
![Screenshot_20200527_194200](https://user-images.githubusercontent.com/24863950/83032064-fe27b900-a052-11ea-8298-6859df282ede.jpg)

**Comment by CarlosEsco** [comment]
wrong repository.  You need to open on the tachiyomi extensions repository and you need to provide what source has the error.
