### ISSUE TITLE
Turkısh Manga sites 

### ISSUE THREAD

**Issue by Aliemir12** [inorichi/tachiyomi#3245]
**PLEASE READ THIS**
Can you add the following sites
https://www.webtoonizm.com/
http://meijisub.com/wp/
http://webtoongarden.com/
http://manga-v2.mangavadisi.org/
http://www.heterophobiafansub.com/
https://trwebtoon.com/
http://emirsub.com/
That is all

**Comment by arkon** [comment]
Please follow the template and open 1 issue per site in the correct repo (which this is not).
