### ISSUE TITLE
Error when using certain catalogues

### ISSUE THREAD

**Issue by natemonster321** [inorichi/tachiyomi#325]
When using MangaFox and MangaHere catalogues, attempting to open a chapter of a manga returns an error that says to check my internet connection, even though it works fine.

Version: v0.2.1
Android 6.0.1

**Comment by natemonster321** [comment]
Just tried to use the site for MangaHere, and it turns out the manga I wanted to read was licensed, which is why I couldn't read it in the app

**Comment by NoodleMage** [comment]
> Just tried to use the site for MangaHere, and it turns out the manga I wanted to read was licensed, which is why I couldn't read it in the app

Does this also hold for mangafox? 
If not which manga causes this error?
