### ISSUE TITLE
[New Extension] <Niadd ✅ NineManga ❎>

### ISSUE THREAD

**Issue by PieroSebastianJoestar** [inorichi/tachiyomi#3250]
Me gustaría que añadan los servidores de Niadd a la app.

Si bien, Ninemanga es muy parecido a Niadd, hay mangas que solo suben sus nuevos capítulos en Niadd y no en Ninemanga (Ejemplo: Ueno san wa Bukiyou y NineManga)

Por eso, aveces es muy difícil estar al día con un manga, los fansubs ni siquiera suben sus mangas en otros servidores.

>

**Comment by arkon** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1007

Not sure why you're posting it here.

**Comment by PieroSebastianJoestar** [comment]
> Duplicate of [inorichi/tachiyomi-extensions#1007](https://github.com/inorichi/tachiyomi-extensions/issues/1007)
> 
> Not sure why you're posting it here.

Sorry, the page is in English and I still don't know how it works.

Google translator 👌
