### ISSUE TITLE
[Bug] Delete nth to the last doesn't work sometimes

### ISSUE THREAD

**Issue by scb261** [inorichi/tachiyomi#3252]
### Device information
* Tachiyomi version: Stable 0.9.2
* Android version: 5.1
* Device: Huawei TIT-U02

## Steps to reproduce (way 1, real usecase)
1. Enable remove fifth chapter to the last.
2. Enable download new chapters.
3. Update library.
4. While it's updating, open first found manga with new chapter. You'll see that the chapter is queued.
5. Open the chapter and read it.

## Steps to reproduce (way 2, easier to debug)
1. Enable remove second chapter to the last.
2. Add new manga to the library.
3. Add to download queue first and second chapters of the new manga.
4. When the first one is downloaded, pause the queue (second chapter remains in the queue).
5. Read those two chapters.

### Expected behavior
nth chapter to the last should be removed.

### Actual behavior
nth chapter to the last isn't removed.

**Comment by Rogavactive** [comment]
I did look into this issue and it seemed like when attempting to delete previous nth to last chapter it was supposed to check if that chapter was actually downloaded, but instead was checking current chapter. Will fix this.
