### ISSUE TITLE
[Feature Request] <Similar Manga>

### ISSUE THREAD

**Issue by dondeepak** [inorichi/tachiyomi#3253]
### Why/User Benefit/User Problem
Similar Manga option to see mangas that similar to the manga currently viewing. It's really useful when i read manga i like most and i want to read similar to that manga it will be lot helpfull

### What/Requirements
Button or separate tab like(info,chapter,tracking)  or bottom of the info tab there should be similar manga list 

Please add this function it will be so much help (neko and manga rock it has this feature)

**Comment by arkon** [comment]
Duplicate of #376
