### ISSUE TITLE
[Feature Request] Allow source migration from library

### ISSUE THREAD

**Issue by lzypnda** [inorichi/tachiyomi#3255]
### Device information
* Tachiyomi version: stable 0.9.2
* Android version: 10
* Device: Samsung Galaxy S20 Ultra

## Feature Request
Allow source migration from library.

## Other details
It would be a nice ability to migrate specific manga from the library menu. The library menu is laid out in a larger format and you're able to click into the info section to check the description and number of chapters. Being able to migrate the source from here from one of the drop down menus or from a long press would be amazing. It's not like I need all my manga from one source so I don't need to migrate all of them from one to another, buy some sources stop having updates on specific mangas and being able to go to the migration screen from the library would help with quickly checking if this is the case. 

Just food for thought, would love to hear others opinion on this as well or if someone has a similar issue and has figured out a way around.

**Comment by arkon** [comment]
Already added in manga view in preview, so should be in the next stable release.

**Comment by lzypnda** [comment]
Awesome, thank you for the info arkon!
