### ISSUE TITLE
[Feature Request] Add manga name to "Page list is empty" notification

### ISSUE THREAD

**Issue by IRISHMAN04** [inorichi/tachiyomi#3257]
### Why/User Benefit/User Problem
So that it is easer to tell which chapter has an error

### What/Requirements
Currently the notifcation reads:

#### Chapter 71: The Unleashed
Page list is empty

But it should read:

#### Tensei Shitara Slime Datta Ken
Page list empty for Chapter 71: The Unleashed

Or something along those lines

**Comment by arkon** [comment]
What notification are you referring to?

**Comment by IRISHMAN04** [comment]
This notification shows up when there is an error downloading a page. The title of the notification is just "Page list is empty"

**Comment by arkon** [comment]
Can you post a screenshot the next time you see it?
