### ISSUE TITLE
[Bug] App closes after opening webview in migration

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3267]
### Device information
* Tachiyomi version: 0.9.2-2373
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Browse > Migrate > Select Source and any manga > Long tap any sources > open webview

### Expected behavior
App must not force close when opening webview in the migration.

### Actual behavior
Migrating from the library opens the webview without app closing. Unlike the migrating from browse tab, it forcefully closes.

**Comment by arkon** [comment]
Fixed by https://github.com/inorichi/tachiyomi/commit/77d378ccd1559617af08a8f067d81f5028f5c7e2
