### ISSUE TITLE
Next chapter button causes crash.

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#327]
Steps to reproduce

1. Scroll to the last page of any chapter 

2. Tap next chapter button instead of scrolling

3. Tachiyomi has stopped working. 

Version: 2.1 stable
(OS: 5.1.1)

**Comment by inorichi** [comment]
Works fine for me with the dev release. Can you try with dev?

**Comment by inorichi** [comment]
Does it happen in 0.2.2?

**Comment by Syborg49** [comment]
All good @inorichi
