### ISSUE TITLE
Global Search is not working

### ISSUE THREAD

**Issue by claytmp** [inorichi/tachiyomi#3270]
I'm using the Tachyomi from this site, version 0.9.2 https://tachiyomi.org/ All of my extensions are up to date and I'm using Mangadex (Which I've already made an account for), Mangasee, Toonily, Webtoon and readcomiconline. Individually, all of the sources work fine. Even with the announcement, I can search for manga and update them as if nothing has changed.

However, when I'm using Source Migration, which leads me to Global Search, the page turns out blank. It doesn't give me an error like 'Couldn't find manga', it's just blank. And I can't even make a normal search with it either.

I was hoping you'd know of a way to fix it

**Comment by arkon** [comment]
Did you turn on the only pinned sources setting but didn't pin any sources?

**Comment by claytmp** [comment]
> 
> 
> Did you turn on the only pinned sources setting but didn't pin any sources?

Sorry for the late response, internet issues. Can you elaborate more? If you mean ticking them on from the 'three-line' option setting on the top right, then yes I did

**Comment by scb261** [comment]
More -> Settings -> Browse -> Only include pinned source. Turn it off and try again.

**Comment by claytmp** [comment]
> 
> 
> More -> Settings -> Browse -> Only include pinned sources. Turn it off and try again.

That worked! Thank you very much
