### ISSUE TITLE
[Feature Request] Option to Hide Text in Library

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi#3272]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Cleaner UI with only manga covers without any Text on or below it in library
 
### What/Requirements
(explain how this feature would behave)
Checkbox to hide manga title text in filter from library

**Comment by arkon** [comment]
Going to turn this down since there's occasional issues with covers not showing up properly and I want to avoid having too much feature/options bloat.
