### ISSUE TITLE
[Bug] there is some glitch

### ISSUE THREAD

**Issue by Gjalarhorn** [inorichi/tachiyomi#3273]
---

### Device information
* Tachiyomi version: 0.9.2 
* Android version: 8.1.0 
* Device: oppo a5s

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
I get some glitch when open some manga then go back (by the way I use dark theme) and I think 0.9.2 too slow rather than 0.8.9

**Comment by CarlosEsco** [comment]
either provide visuals or more information on the glitch or i will close for lack of info
