### ISSUE TITLE
[Feature Request] Skip first/last page in chapter

### ISSUE THREAD

**Issue by LLkoffii** [inorichi/tachiyomi#3274]
### Why/User Benefit/User Problem
Many mangas have repetitive intro and/or outro screens each chapter which breaks the flow of reading and wastes bandwidth.

### What/Requirements
For each manga, add a pair of preferences to skip downloading,  or simply not display,  the first and last X pages.

**Comment by arkon** [comment]
This has been requested and rejected in the past, due to inconsistency in sources, confusing UX (most users don't understand or remember settings that they set), and out of respect for scanlators.
