### ISSUE TITLE
[Bug] Can't change the view mode

### ISSUE THREAD

**Issue by jendralcox** [inorichi/tachiyomi#3276]
### Device information
* Tachiyomi version: 1.0.7
* Android version: 10
* Device: Mi 9t Pro

## Steps to reproduce
1. Don't know how to reproduce it, let me explain here.  When reading the manga, we can change the view for vertical, webtoon, or right to left etc right. But in my case (mangahub latest version) there is one manga that can't change the viewer mode. It keeps on "webtoon" style instead of any other view whatever i change it. Just one manga, i tried on any other manga and it works well.

### Expected behavior
Should change to left-right or any other viewing mode.

### Actual behavior
When i chose right to left mode or any mode,  it keeps on webtoon view. 

### Other details
Additional details : sorry for not fluent in english.
Here's some attachment.

![Screenshot_2020-06-05-04-11-07-261_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/66444198/83811891-d08edf80-a6e4-11ea-8a02-2a909314572d.jpg)

Always on webtoon mode

**Comment by arkon** [comment]
Wrong version.

See https://github.com/Jays2Kings/tachiyomiJ2K
