### ISSUE TITLE
[Feature Request] Option to select external directory (sd-card) to store downloads

### ISSUE THREAD

**Issue by Unique-Phenomenon** [inorichi/tachiyomi#3278]
### Why/User Benefit/User Problem
This feature should be added to allow users to change the storage directory from internal storage to external storage. This would provide more convenient storage management for users. It would also provide other benefits such as avoiding the lose of data in case of a sudden data reset of the device, and a much easier way to move data across multiple devices that supports external memory without having to copy the data repeatedly.

### What/Requirements
Option to select internal or external storage directory.

**Comment by scb261** [comment]
It's already implemented. More -> Settings -> Downloads -> Download location. Or do you mean to transfer already downloaded chapters?

**Comment by Unique-Phenomenon** [comment]
I apologize for the disturbance. Apparently I had a quirk with my own sd-card that caused it not to appear when selecting a download location. Though It would be great to transfer already downloaded chapters. Thanks for your help and for this great app.
