### ISSUE TITLE
[Bug] Resume reading not working

### ISSUE THREAD

**Issue by zuriich5** [inorichi/tachiyomi#3280]
### Device information
* Tachiyomi version: stable 0.9.2
* Android version: 9/ colorOS v6.0.1
* Device: Oppo F7

## Steps to reproduce
1. First step. Choose a chapter
2. Second step. Click resume reading

### Expected behavior
Will return to the current chapter and page the user is reading. Ex. Chapter 5 page 15

### Actual behavior
It went to the very first chapter of the manga. Ex. Chapter 1 page 1

### Other details
Additional details and attachments.
Did this plenty of times and it always goes back to the very first chapter of the manga and not the current chapter the user was reading.

**Comment by CarlosEsco** [comment]
It goes to first unread page. Make the other chapters as read

**Comment by zuriich5** [comment]
Thank you for your fast response!
