### ISSUE TITLE
[Feature Request] Social Feature

### ISSUE THREAD

**Issue by borgeskrl** [inorichi/tachiyomi#3283]
I have a lot of friends who are as addicted as me in reading manga, but they use different apps and when I tell them to install Tachiyomi they prefer to stay in their confort zone and keep using other apps. I believe that if a social feature was added then not only my friends but a large part of the manga reading community would install Tachiyomi since talking about manga would be more practical and fun.

This feature would have: account/profile making and editing, the possibility to add other accounts/profiles as friends, a way to see what your friends are reading and when they are reading (such as "X manga chapter was read at 3:30 a.m").

**Comment by arkon** [comment]
We don't have the manpower or financial means to create and maintain a social networking system.

You could try convincing your friends to use trackers like Anilist.
