### ISSUE TITLE
[Feature Request] Auto update of all source and extensions

### ISSUE THREAD

**Issue by williamkitchong** [inorichi/tachiyomi#3284]
[Feature Request] Auto update of all source and extensions

It is simply very time consuming to manually update all the source and extensions.

Is it possible for them to auto update? Or mass update?

Thank you.

**Comment by AbdullahM0hamed** [comment]
Simply not possible at the moment due to the fact that extensions are packaged as APKs. I'm thinking this'll probably happen for 1.x - but I doubt it'll happen before that.

**Comment by arkon** [comment]
There's a couple closed issues about this, but what @AbdullahM0hamed is correct, this isn't allowed in Android when installing APKs.
