### ISSUE TITLE
[Bug] wrong filter menu on the sources tab

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi#3286]
### Device information
* Tachiyomi version: build from 812fcec9f0b8f896e5ed96113b0ba5ebcd957f98
* Android version: 10
* Device: Samsung Galaxy A50

## Steps to reproduce
1. go to Browse tab from the bottom
2. go to sources tab from the top
3. open the `Filters` menu by tapping on the button with 3 lines from the top right of the app

### Expected behavior
Sources Filter menu be shown

### Actual behavior
Extensions Filter menu is shown (it seems)

### Other details
This bug is not present on the current stable build (0.9.2)

**Comment by AriaMoradi** [comment]
I'm not sure if the bug is caused from this exact commit or the ones before it

**Comment by AriaMoradi** [comment]
![Screenshot_20200606-071628_Tachiyomi](https://user-images.githubusercontent.com/8719233/83934942-b2e77600-a7c9-11ea-8db1-af02d6f24764.jpg)
![Screenshot_20200606-072111_Tachiyomi](https://user-images.githubusercontent.com/8719233/83934943-b5e26680-a7c9-11ea-8bbb-84ad281c440e.jpg)

**Comment by arkon** [comment]
...it's not a bug.

**Comment by arkon** [comment]
(I'll update the screen titles though, filter is a bit too generic.)

**Comment by hXtreme** [comment]
@arkon given that you can hide sources from that screen I think it makes a lot of sense to allow users to unhide from the very same screen.

Also, the way to unhide a source right now r2412 is a bit convoluted, first you go to extension then you have to (either remember or) find the extension that contains the source you want to unhide and then "enable" it.

A tangential complaint, on the sources screen Tachiyomi uses the term "hide" while it uses "enable" under extensions.
