### ISSUE TITLE
[Bug] onma (arabic) not working

### ISSUE THREAD

**Issue by alucardlucilfer** [inorichi/tachiyomi#3287]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: POCOPHONE F1

### Source information

Name: CMS (onma) ( مانغا اونلاين = manga online)
Link: https://www.onma.me/
Language(s): Arabic

## Steps to reproduce
1. Open Onma
2. Choose a manga
3. Try to read it

### Expected behavior
Showing manga

### Actual behavior
Source not working 

### Other details
Failed to bypass cloudflare

**Comment by CarlosEsco** [comment]
Wrong repository open In the tachiyomi extensions repo
