### ISSUE TITLE
[Feature Request] Allow zoom out past limit in 'fit width' mode

### ISSUE THREAD

**Issue by philowe94** [inorichi/tachiyomi#3304]
### Why/User Benefit/User Problem
In fit width mode in landscape view, for panels that are taller than the height of the landscape oriented screen, it is currently impossible to view the entire panel without switching to portrait mode. If I could zoom out past the limit, I would not need to rotate the screen, or switch to fit height mode just for default panels. This is preferrable to fit height mode because fit height mode starts out very zoomed out and I would have to zoom in on every page instead of just zooming out occasionally for tall panels.

### What/Requirements
Just allow the image to become smaller than the width while fit width (an all the other options that start at full width zoom) is selected.

**Comment by arkon** [comment]
Closing in favour of #3348
