### ISSUE TITLE
[Feature Request] In app changelog viewer

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi#3307]
### Why/User Benefit
To monitor changes in - app. This also allows users to easily spot bugs, new features and existing features (so that they won't make an feature request on a feature that is already included).

### What/Requirements
Create a handler in the app that gets the changelog in the github repo. This allows not only the latest app to show latest changes but also previous versions to show update changes. An extension changelog handler is also recommended. It is also recommended to have pull links on the changes made.

**Comment by arkon** [comment]
More > About > Changelog

**Comment by arkon** [comment]
> An extension changelog handler is also recommended. It is also recommended to have pull links on the changes made.

Maybe eventually, but it'll require a lot of infrastructure rework to extensions to get that working so not anytime soon.
