### ISSUE TITLE
0.2.2 missing chapters

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#331]
Only the 25th chapter can be seen in Tachiyomi for [Nozomi x Kimio](http://bato.to/comic/_/comics/nozomi-x-kimio-r824) while all the previous chapters are available in my browser. 

Is there anything I can do to fix the issue? I tried cleaning cookies and manually updating but it did not help. 

Version: 0.2.2
Android: 5.0.1
Source: Bato.to

![screenshot_2016-06-06-17-49-55](https://cloud.githubusercontent.com/assets/7024084/15826211/622b5a40-2c0f-11e6-9f36-b648cb0ca63e.png)

**Comment by inorichi** [comment]
Have you updated uninstalling and restoring backup? My guess is you aren't logged in. Try login again.

**Comment by Bloodwork** [comment]
No, I did not delete the app before 0.2.2 install and I'am already logged in. I just tried relogging but it didn't help with the issue.

**Comment by inorichi** [comment]
It shows all the chapters in my case. Do you have the unread filter enabled by any chance?

**Comment by Bloodwork** [comment]
It was indeed the unread filter. Sorry for wasting your time. This issue is resolved.
