### ISSUE TITLE
[Feature Request] Logo proposal.

### ISSUE THREAD

**Issue by HaraDesu** [inorichi/tachiyomi#3311]
Hello!
I am a somewhat a graphic designer. 
I am interested to collaborating with this project by delivering free logo proposal.
If this is interesting for this project, please let me know!

also, i love using tachiyomi.

**Comment by HaraDesu** [comment]
wait, this is the wrong label. sorry.

**Comment by Rogavactive** [comment]
I would like to work on this, but first logo should be approved. This app already has a logo

**Comment by arkon** [comment]
I personally would want to always have the "立" character, and most of the other contributors seem to agree.

**Comment by HaraDesu** [comment]
Cool!, I will make a revision from it!
