### ISSUE TITLE
[Bug] <screen smart select capture problem>

### ISSUE THREAD

**Issue by Jay-sins** [inorichi/tachiyomi#3321]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: galaxy S8

## Steps to reproduce
1. First step; open smart select and choose capture area
2. Second step: choose capture area 
3. third step; capture (take a screenshot of the area u want)

### Expected behavior
u can capture the area u want in the page u r reading

### Actual behavior
when u open the smart select capture, it takes u immediately to the 1st page u opened when u started reading 

![tachi](https://user-images.githubusercontent.com/66893792/84583800-2823fe00-adfd-11ea-9d85-a05fbadbe86f.jpg)

**Comment by arkon** [comment]
I think this is already fixed in the preview builds.

**Comment by Jay-sins** [comment]
> I think this is already fixed in the preview builds.

well I got this problem only after i updated the app :/

**Comment by Jay-sins** [comment]
if it was already fixed? what should i do then? i have the latest update and i got this problem just after updating it lol

**Comment by arkon** [comment]
You'll need to wait until the next stable release, or switch to the preview builds.

Alternatively, just take normal screenshots.

**Comment by Jay-sins** [comment]
> You'll need to wait until the next stable release, or switch to the preview builds.
> 
> Alternatively, just take normal screenshots.

o okay, well that's what i've been doing for a month. hope the next release comes out soon :) 
anyways, thanks for answering
