### ISSUE TITLE
[Bug] Mintmanga and Readmanga doesn't work 

### ISSUE THREAD

**Issue by Tosterr1** [inorichi/tachiyomi#3327]
Mintmanga and Readmanga doesn't work. Is this problem with my device or site?

Device information
* Tachiyomi version: 0.8.5
* Android version: 4.4.2
* Device: Lenovo Tablet 

![Screenshot_2020-06-14-21-19-07](https://user-images.githubusercontent.com/42684479/84600889-3fa6c980-ae85-11ea-96da-07d8b493738e.png)

**Comment by Tosterr1** [comment]
This massage "com.android..." appears when i trying to update any manga from Mint or Read and when i search new manga from site.

**Comment by arkon** [comment]
Android 4.x is going to have issues in general moving forward as the Internet advances, and we don't intend on supporting it.
