### ISSUE TITLE
Long manga titles in 'Download queue' hide page count

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#333]
For titles that wrap to 2+ lines, the pages downloaded/total counter is not visible.

![](https://i.imgur.com/6YmyaxF.png)

Version: r764
OS: 6.0.1

**Comment by Syborg49** [comment]
I'm sorry @wopian, can you tell me the name of the font that you're using?

**Comment by wopian** [comment]
@Syborg49 it's the default Roboto typeface...
