### ISSUE TITLE
[Bug] Mangahasu extension wont load works properly

### ISSUE THREAD

**Issue by kmelon99** [inorichi/tachiyomi#3332]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1.0
* Device: Vivo V7+ Android

## Steps to reproduce
1. Opened Tachiyomi, as usual.
2. Opened a webtoon I was reading with a Mangahasu extension, picking it up from where I left it off.

### Expected behavior
Loading ever slowly, but was expecting it to normally load after about two tries. I was able to do this before updating to the newest version of tachiyomi.

### Actual behavior
Keeps crashing, saying there's a java exception. A notice which says "java.lang.Exception: failed to bypass Cloudfare" keeps popping up.

### Other details
I tried forcibly shutting the app and restarting it. Even rebooting the wifi router. Didn't work. I tried this at noon yesterday, about 12:15 PM, and today, around 5 AM.

**Comment by cievee** [comment]
That happens to me too its getting kinda annoying cuz the only way i can read it is by dowloading the chapter

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi-extensions/issues/3475
