### ISSUE TITLE
[Feature Request] Switch to toggle data saver (compressed download image)

### ISSUE THREAD

**Issue by kasumi9** [inorichi/tachiyomi#3333]
Why/User Benefit/User Problem:

Make a switch to enable data saver for downloading which compressed the image to save up some storage space. I have over 30+ manga which has 100+ chapters each and it takes a massive amount of storage space.

What/Requirement:

It should at least shave up 25% or more of it's original size.

**Comment by CarlosEsco** [comment]
Disclainmer: Tachiyomi is not a content provider. We are not affiliated with or responsible for any source that is slow, down, or missing chapters.


Which also means we don't control quality if a source has the option it's usually and option in the extension
