### ISSUE TITLE
[Feature Request] Add a "delete downloaded chapters only" when selecting multiple titles in the library section

### ISSUE THREAD

**Issue by Saladaladad** [inorichi/tachiyomi#3334]
I want to delete some downloaded content but want to keep the manga itself in my library. I find it really tedious to individually open a title to delete the downloaded chapters.

**Comment by serjflint** [comment]
You can do so in File Explorer for now

**Comment by IIOMNIVERSEII** [comment]
so are we gonna get this option soon .if only I was also learning how to code for android in school instead I got good old java.
