### ISSUE TITLE
[Feature Request] Persian (Farsi) translations

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi#3335]
### Why/User Benefit/User Problem
it's pretty obvious.

### What/Requirements
all strings translated on weblate (already done)

**Comment by AriaMoradi** [comment]
how do I make a pull request from this?

all translations are on weblate as it should: https://hosted.weblate.org/projects/tachiyomi/strings/fa/

**Comment by arkon** [comment]
We do regular PRs already, you don't need to do anything.
