### ISSUE TITLE
[Feature Request] implement an AI image upscaler such as waifu2x

### ISSUE THREAD

**Issue by sillysack69** [inorichi/tachiyomi#3337]
### Why/User Benefit/User Problem
Manga often has low res images and images with a lot of noise which can be significantly improved with AI upscaling and noise removal. Its not a necessary feature but it has its potential uses especially for badly scanlated manga.

### What/Requirements
I am not sure if older phones will be able to support this feature to begin with since the upscaling will take place in real time. It might cause images to load really slowly on old phones. But since now phones are even getting dedicated AI chips, this feature could really take advantage of that. In any case, I don't have much experience with AI upscaling so I can't really expect the devs to implement this anyway. I just thought that this is something to have in mind as a goal for the future.

**Comment by CarlosEsco** [comment]
doubt this would be added.  As this is primary meant as a reader app

**Comment by arkon** [comment]
Yeah, this seems wildly out of scope.

Also, it's not an AI, it's a program that used data trained from a neural network.
