### ISSUE TITLE
[Bug] Loading Manga Error

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi#3339]
### Device information
* Tachiyomi version: r2421
* Android version: 6.0.1
* Device: Vivo y53

### Expected behavior
Load the image/manga immediately

### Actual behavior
This keeps on showing 
![IMG_20200618_043638](https://user-images.githubusercontent.com/64214774/84947840-80b90b00-b11d-11ea-88f5-eed789f005c8.JPG)

### Other details
This has been happening for a long time even though I already updated the manga, close the app, re-download it,  and restart my phone.  Although sometimes the manga load normally on some manga but almost half of my favorites show like the attachment above.

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi-extensions/issues/3475
