### ISSUE TITLE
Posters don't load for some Batoto/RMT/MH manga

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#334]
I think there was a similar issue before, but couldn't find it in search.

Some manga refuse to have their poster loaded - while several from Batoto did load the cover after refreshing the manga page. Only way for the poster to show up for the rest is to open the manga in browser and save the poster and add it manually.

Examples:
- https://bato.to/comic/_/comics/b-gata-h-kei-r500
- https://bato.to/comic/_/bakuman-r63
- http://www.mangahere.co/manga/eureka_seven_ao/
- + Corpse Party franchise from Batoto

![](https://i.imgur.com/OhJoMqi.png)

---

Version: r764
OS: 6.0.1

**Comment by inorichi** [comment]
Let's try with "Corpse Party". Look for a file `e003b094b0cc32dba9461c65125adaa8` in `/sdcard/Android/data/eu.kanade.tachiyomi.debug/cache/cover_disk_cache/` Does it exist and can it be displayed through any image explorer (not corrupt)?

**Comment by j2ghz** [comment]
I reinstalled tachiyomi on saturday and thought it's just taking a lot of time to load the covers for some reason. But I looked in the folder and there are some corrupt images.

**Comment by inorichi** [comment]
Possible workaround: 
1. Open manga
2. Remove and add from favorites (double tap the FAB)
3. Return to the library and force an UI update (like opening the library from the drawer)

**Comment by inorichi** [comment]
It should be fixed from now on

**Comment by wopian** [comment]
Yeah they were corrupt - on the few I tried pre-update (mostly just the CP franchise in OP) it required a mixture of multiple re-adds and forced UI updates.

**Comment by wopian** [comment]
ofc there had to be a catch. This poster image is corrupted, but loads so none of the above methods work/re-download the poster.

http://www.mangahere.co/manga/jitsu_wa_watashi_wa/

![](https://i.imgur.com/7RFSEfJ.png)

**Comment by inorichi** [comment]
I don't understand this... The image in the background is displayed properly, and both come from the same source.

**Comment by shogunreaper** [comment]
i can't get covers to load for kissmanga.

looked in /sdcard/Android/data/eu.kanade.tachiyomi.debug/cache/cover_disk_cache/ but it doesn't appear.

**Comment by wopian** [comment]
@shogunreaper duplicate of #308. Instructions to fix it are in there too.

**Comment by shogunreaper** [comment]
@wopian

i tried doing a pull down to refresh but nothing happened. And Clear database says it will delete what chapters you've read, i don' want to do that.

Also i clicked the little pencil button that says edit the cover picture and was able to change it that way

but then the background to my android screen changed to the manga cover... how do i reverse that?

**Comment by inorichi** [comment]
First, ensure Kissmanga loads in the catalog, so that the cloudflare cookie is up to date.

Then either update pulling down or use the clear database option (it doesn't delete any progress/chapters from manga in your library). If it still doesn't work, remove and add from favorites with the floating action button (tap two times) to force an update.

**Comment by shogunreaper** [comment]
kissmanga info\chapters load but covers don't.

pulling down and clearing the database doesn't work.

removing\adding back didn't do anything.
