### ISSUE TITLE
[Feature Request] manga deeplinking in app

### ISSUE THREAD

**Issue by sanjay887** [inorichi/tachiyomi#3343]
I noticed that ur log uses sources as a no. To open restore manga.
So,
U can deeplink manga link with adding ur app name and source name or code no. in front of manga link so the app can recognise that its your app and open link in app.

Like :- app name/source code/manga url

For example :- tachiyomi/mangadex ( source code no.)/https://www.mangadex.org/manga/33326/

**Comment by AbdullahM0hamed** [comment]
Extensions can do that. The mangadex extension, in particular, already has that functionality.

Clicking your mangadex example link, gives me the option to open it in Tachiyomi: MangaDex
