### ISSUE TITLE
[Bug] Extension Mangachan doesn't work at all

### ISSUE THREAD

**Issue by Dennyx666** [inorichi/tachiyomi#3344]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: s20 Ultra 5G

## Steps to reproduce
1. Enter the tachiyomi app, went to the main page, then to the extensions, then to my extension Mangachan where I usually browse mangas.
2. Open different mangas to preview.

### Expected behavior
The mangas should be displayed and previewed as usual.

### Actual behavior
There is no information on the pages of any of the mangas, no preview and no chapters, just an error message thatI posted before. Furthermore, now its not working at all.

### Other details
This began today on June 18 of the 2020

**Comment by Dennyx666** [comment]
![Screenshot_20200618-212428_Tachiyomi](https://user-images.githubusercontent.com/67130850/85087331-3a11f200-b1ab-11ea-8549-68d2b182ec42.jpg)

**Comment by arkon** [comment]
We don't control the sources.
