### ISSUE TITLE
[Bug] <Tears on manga when using webtoon mode>

### ISSUE THREAD

**Issue by von-wa** [inorichi/tachiyomi#3345]
### Device information
* Tachiyomi version: Preview r2421
* Android version: 8
* Device: samsung galaxy A5 2017

## Steps to reproduce
1. use the webtoon reading mode
2. find any vertical manga (e.g. chapter 52 of "descent of the demonic master" & chapter 51 of "ernak", both from manganelo)

### Expected behavior
smooth transition between pages
### Actual behavior
tear in between the pages

### Other details
example images : https://imgur.com/a/qMNDsd7
i also included the web version of "ernak". most of  "annoying alice" also have this issue
i think the tears is caused by some pages uploaded zoomed in

**Comment by arkon** [comment]
I assume you have the crop borders setting turned on?

**Comment by von-wa** [comment]
oh yeah it solved the issue. mods at subreddit recommended to report to github. thanks for the help
