### ISSUE TITLE
Tachiyomi on android emulator

### ISSUE THREAD

**Issue by SaruDesu422** [inorichi/tachiyomi#3349]
I'm using tachiyomi with bluestacks but the pages are separated with spaces. Am I not suppose to use android emulators or is there a solution for this problem?

**Comment by arkon** [comment]
Are you using the continuous vertical reading mode?

**Comment by SaruDesu422** [comment]
I'm using webtoon reader

**Comment by CarlosEsco** [comment]
I usually recommend a screen mirror like
https://github.com/Genymobile/scrcpy

vs trying to run on an emulator.

**Comment by arkon** [comment]
Probably a duplicate of #2736

**Comment by SaruDesu422** [comment]
i tried using samsung dex but it's quite laggy so i thought it would be better to use android simulator

**Comment by arkon** [comment]
Closing since I think this is the same thing as #2736. `scrcpy` just mirrors your screen, so you can give that a shot -- it's not intensive like DeX.
