### ISSUE TITLE
[Feature Request] Allow to split manga info from chapters list

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#3353]
With latest dev build chapters list has been merged with manga info. Doing so when opening manga you see only 5 chapters by default because manga info take more than half of vertical space.

Besides until know the app was prioritizing chapters list over manga info since it was the default screen. Merging both screen make chapters list secondary to manga info. I feel it's not a good thing : most of the time I don't really care about manga info. I already know it since I am reading it. It's a lot more interesting (at least for me) to see chapters and to be able to quickly check which is the latest chapters, how much unread chapters you have, ... (And I think it was why previously chapters list was the default screen)

Would it be possible to add an option to keep manga info and chapters list split? And if it's turned on then opening manga should take you to chapters list by default. (Or revert the commit if my arguments were good enough 😄)

**Comment by kai000bubbles** [comment]
Yeah i wish could they have an option to change it back but guess we have to live with it and also the colours they changed too i want my red back
