### ISSUE TITLE
[Feature Request] <Add swiping between library and downloads>

### ISSUE THREAD

**Issue by ngomile** [inorichi/tachiyomi#3355]
### Why/User Benefit/User Problem
This would make accessing downloads and the catalogue easier and faster in the Library section as the user would simply have to swipe between them.

### What/Requirements
It would look similar to how the extensions have been neatly organised in the Browse section of the app, the Library heading would be at the top and the sub sections would be Catalogue, Downloads and the third probably Bookmarks or something like that. The unread and completed filters would only work on the Catalogue section (or both still) and the downloaded filter will no longer exist. But sorting and display should work the same in all the sub sections.

**Comment by arkon** [comment]
Not going to happen due to how downloads are checked based on existing library content and the only effective way of doing it being the same thing as the existing filter.
