### ISSUE TITLE
[Bug] Small visual bug when downloading chapters

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#3358]
### Device information
* Tachiyomi version: 0.9.2-2447
* Android version: 10

Video for the visual bug - 

![giphy](https://user-images.githubusercontent.com/23010526/85226085-3a9cc980-b3f3-11ea-9168-1bc59213eaef.gif)

**Comment by serjflint** [comment]
Same here even with long tap on the chapter. Queued status won't appear for long or I need to exit and enter again.
