### ISSUE TITLE
Tachiyomi not connected to the internet CertPathValidatorException

### ISSUE THREAD

**Issue by Omar-AbdulAzeez** [inorichi/tachiyomi#3359]
Anilist tracking just stopped working. Was working earlier today. I noticed it doesn't auto update so I opened the tracking tab and tried to update manually it gave a failed to connect error (SS included). I tried to re log in but now I just can't log in... after I put the email and password and tried to log in it closes the browser without integrating with tachiyomi.
![Screenshot_20200621-182604_Tachiyomi](https://user-images.githubusercontent.com/49833164/85230053-c7448900-b3ed-11ea-82dd-a2b651e5f4ab.jpg)

**Comment by Omar-AbdulAzeez** [comment]
Ok so... I had my suspicions
It seems the app isn't connected to the internet because of a certificate error?? I edited the title as well
![Screenshot_20200621-185712_Tachiyomi](https://user-images.githubusercontent.com/49833164/85230538-31126200-b3f1-11ea-8635-c691eff4bec5.jpg)

**Comment by arkon** [comment]
I wish you had filled out the template fully.

What version of Android are you using?

**Comment by Omar-AbdulAzeez** [comment]
Sorry... I thought it was something to do with anilist at first so I just didn't bother... it's android 9
And it got fixed on its own... I tried restarting the app a couple of times didn't work but at some point I did another restart and it was fixed idk what changed
