### ISSUE TITLE
[Feature Request] Jump to Chapter list when viewing a manga from Library

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3362]
[ This is not a request to revert changes nor to make a toggle to switch to old style. (like SY does) ]

### Why/User Benefit/User Problem
Before, when you view a manga from your library, it always directed to the Chapters tab. Now with the merged Info + Chapters tab, a huge part of the screen (~70%) is always wasted by the Info section. It could instead just jump straight to Chapters list when you're viewing from Library—emulating the previous behaviour.

**Comment by arkon** [comment]
Duplicate of #3353

**Comment by vengiare** [comment]
This is a different request than #3353. I'm not asking to split Info and Chapters list. I thought i clarified that already.

**Comment by vengiare** [comment]
@arkon Hope you kindly re-read the suggestion.

**Comment by arkon** [comment]
I know. That's the only thing I'd consider for #3353 anyway.

**Comment by vengiare** [comment]
Then it should make this not a duplicate then.
