### ISSUE TITLE
[Feature Request] minimize about section & grey out chapter count

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#3368]
### Why/User Benefit/User Problem
The new vertical split is nice, no need for switching between tabs, but it feels cramped. 
(Same issue as #3362 , but proposing different solution)
Also the chapter count is a bit too eye catching, clicked it by accident once or twice thinking it's a chapter.

### What/Requirements
I'm proposing the about section including the about header should be hidden behind show more by default, this will make things visually less cramped. And showing the title and cover is visually nice, so I don't really want to scroll pass it by default. Oh and the chapter tab at the top is completely unnecessary?
and the chapter count should be greyed out (less eye catching) or maybe removed, or hidden in show more?

**Comment by arkon** [comment]
Added a "Jump to chapters on open" setting.
