### ISSUE TITLE
[Bug] Remove after read settings not working properly after r2447 update

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi#3371]
### Device information
* Tachiyomi version: r2447
* Android version: 6.0.1
* Device: Samsung J2 Prime Enigma V2 ROM

### Steps to reproduce 
Update to `r2447` then read a downloaded manga chapter with any settings under  `Remove after read` configured (such as `Remove when marked as read`) . 

### Expected behavior
The downloaded chapter must be deleted after read or marked as read based on the setting. 

### Actual behavior
The downloaded chapter remains. 

### Other details
This problem may have been caused by the recent `merge of the manga info and chapter view` 4605e147296697ebf5a1318bac6b49519a48aa99.
I also would like to say that black font on aquamarine is kinda... you know...

**Comment by arkon** [comment]
Potentially related to f642f23366ef352c7d107c8fd90a049033391504

Did you verify if the chapter is actually deleted or not in the filesystem, i.e. is it just the app that has a visual bug not updating the status, or is it actually not deleting?

> I also would like to say that black font on aquamarine is kinda... you know...

I have no idea what you're talking about.

**Comment by Dago17** [comment]
I've been looking at the error and I don't see anything strange.
@SaruDesu Can you specify the option you have in "Remove after read" (Disable, Last read chapter, ..)?

**Comment by arkon** [comment]
Potentially fixed in 75d1913aafa587ca74e12231558d14044ad99bfc

Closing for now, can reopen if we see it again in the next preview.
