### ISSUE TITLE
[Bug] Errors when updating categories

### ISSUE THREAD

**Issue by ArzuHrpt** [inorichi/tachiyomi#3376]
* Tachiyomi version:App version: 0.9.2-2447 (standard, 65091c05, 45)
* Android version: 10 (SDK 29)
* Device: Samsung SM-N960F

1. Check for manga updates or wait for app the check for it itself in time
2. See updated manga notifications if there is any

### Expected behavior
Checking for manga updates at designated times without any failures

### Actual behavior
At every update check i get a notification saying some of the manga i saved gave an error while checking.

### Other 
I checked the extension to see if the problem is stemming from there but sources keep changing, different and multiple sources every time and not all manga from said sources, just some random ones. All of my extensions and my app is up to date and, this started to happen after the last update. Thank you.

**Comment by arkon** [comment]
Either read the error log messages from the notification and take action on those, or turn off the setting and blissfully ignore any errors.

**Comment by arkon** [comment]
Actually TODO for me: make just tapping the notification open the error log.
