### ISSUE TITLE
[Feature Request] inbuilt DNS over HTTPS support

### ISSUE THREAD

**Issue by rama982** [inorichi/tachiyomi#3377]
### Why/User Benefit/User Problem
For unblocking blocked extensions site by ISPs

Is this good idea?

**Comment by arkon** [comment]
Android 9+ supports this natively if your configured DNS supports it AFAIK. I haven't seen it implemented in individual apps, other than full on browsers.

**Comment by rama982** [comment]
I just got this idea after seeing this commit
https://github.com/topjohnwu/Magisk/commit/f3e82b9ef1ea5db109f73faffce7af481462fed2

**Comment by arkon** [comment]
Pretty neat, we could probably have it as an option, assuming it doesn't cause issues. I have had issues with Tachi not working when the 1.1.1.1 app is enabled though, but those don't work the same way.
