### ISSUE TITLE
Issues with Edit categories when you select manga from multiple categories

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3382]
### Device information
* Tachiyomi version: Stable 0.9.2
* Android version: 9
* Device: Nokia TA-1053

## Steps to reproduce
1. Select manga from multiple categories (Categories "x", "y", "z" for example)
2. Add it to another category (Category "b" for example)

### Expected behavior
Add manga to the category you want while  retaining previous categories of those manga.

### Actual behavior
Those manga get added to the category you want (Category "b") but it will be removed from its previous categories (manga you selected from "x", "y" and "z" will no longer be in those categories)

**Comment by arkon** [comment]
That sounds like the expected behaviour to me. The selection you make is the final result.

**Comment by vengiare** [comment]
No, I want to copy manga from multiple categories to another category, not move them.

**Comment by arkon** [comment]
You can make a case for either UX flow, and the existing one makes more sense IMO. You can still move individual items or items from distinct categories if needed, but I won't be changing this unless there's a good alternative UX that covers what's proposed as well as existing behaviour.

**Comment by CarlosEsco** [comment]
That's not the feature. It's edit categories. Not add more categories.

**Comment by vengiare** [comment]
> That's not the feature. It's edit categories. Not add more categories.

I believe you misunderstood the issue.

> You can make a case for either UX flow, and the existing one makes more sense IMO.
It's weird that it gives different behaviour when you select manga from a single category compared to when you select manga from multiple categories"

> You can still move individual items or items from distinct categories if needed, but I won't be changing this unless there's a good alternative UX that covers what's proposed as well as existing behaviour.

Dunno, probably have a tri-state checkbox with the "partially checked" state for the categories that only have "some" manga selected.

**Comment by CarlosEsco** [comment]
I know the issue.

You have manga 1 with sports
And manga 2 with action

And you want them to be sports, reading and action, reading

But as I said. You are editing categories in the dialog not adding new categories.  Key difference is editing it encompassing adding and removing of categories and adding only adding new categories on top

**Comment by vengiare** [comment]
I'm not trying to "add" categories. The "reading" category you speak of already exists, if that makes sense to you.

**Comment by arkon** [comment]
> Dunno, probably have a tri-state checkbox with the "partially checked" state for the categories that only have "some" manga selected.

Maybe, although the dialog library we're using doesn't allow that currently. I can leave this open, but I don't think it'll change anytime soon.

**Comment by vengiare** [comment]
On second thought, I don't think this can be solved since selection in library is weird (it selects manga across categories)

I'll probably think of an alternative way to manage manga later.

**Comment by CarlosEsco** [comment]
I know this closed. But you are adding categories adding a category to a manga. Not adding a new category. You are confusing add a new category with add a category to a manga .  Which brings back to what I said its an edit categories on manga not add categories on manga dialog
