### ISSUE TITLE
[Feature Request] Synchronization between devices

### ISSUE THREAD

**Issue by kakardo** [inorichi/tachiyomi#3385]
### Why/User Benefit/User Problem
One big reason is for us that have a smartphone and a tablet, but also for us that has a work phone. It would be really handy if I read something on a device and the other devices got updated with the information. 

As it is right know, a user needs to decide what to read on which device, or memorize what has been read.

### What/Requirements
(explain how this feature would behave)

1. Simplest implementation
A chapter gets marked as read/unread on Device A. When Device B is opened, if the manga is followed on the currently used device, it updates what has been read and what is unread.

2. Less simple implementation
(Has features as in point 1). The app synchronizes which mangas are followed and not between devices.

3. Advanced implementation
(Has features as in point 1 & 2). It synchronizes setting between devices. Perhaps downloads chapters if user has set it to do such a thing.

**Comment by arkon** [comment]
#912
