### ISSUE TITLE
[Bug] App crashes in webtoon-mode with large files

### ISSUE THREAD

**Issue by blaxcky** [inorichi/tachiyomi#3386]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 7.0
* Device: Huawei Mediapad M3, (also Samsung Galaxy Tab S2)

## Bug
The following problem pop up every time I read local upscaled webtoons (upscaling results in better quality so I don't want to give up on it) with tachiyomi and is also reproducible:

It seems tachiyomi has a problem with large files or high resolution in webtoon-mode. After a while reading and scrolling tachiyomi crashes. The app tries to load the next picture and then crashes and goes back to the chapter list (or restarts) or on my other tablet sometimes the app was completely closed. It's really annoying because the progress will not be saved either. 

The same thing happens when I use the "fast page jump" function at the botton of the screen and I wipe back and forth with my finger.
I have tested it with some other webtoon ("The Gamer") which I downloaded with Tachiyomi (no upscaling, normal size and resolution). Neither one of the problems occur.

**Comment by blaxcky** [comment]
Maybe it helps, so I uploaded a cbz file for testing.

http://www.mediafire.com/file/85rgvl2581b8cyh/upcale.cbz/file

**Comment by arkon** [comment]
Closing in favour of #1908
