### ISSUE TITLE
[Bug] Tachiyomi version 0.9.2 application cannot be installed on Android version 4.4.2

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi#3387]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 4.4.2
* Device: OPPO A11w

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by jobobby04** [comment]
9.x only supports 5.0.0 and over
