### ISSUE TITLE
[Bug] something wrong with download chapters and library update

### ISSUE THREAD

**Issue by Fozzy1309** [inorichi/tachiyomi#3389]
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung note 9

## Steps to reproduce
1. Categories were created and manga, webtoons and h*ntai were added. Note: they are have individual category and none of them is in 2 different category and a few of them was manually download because it's not working (as shown in the clip).

2. Manually update using the refresh button on the updates tab (auto update was also being tried and the same problem occured).

3. Wait...

4. Update process ended but my stuff is still hadn't being downloaded.

5. (Not in the clip) the download queue was checked and it's empty

#  Behaviour sumary:
Manga, webtoons and h*ntai should be downloaded automatically on my phone but instead, nothing happended.

Another note: it's working fine if only the default category exists (tested by reinstalling the app after cleaning all the data)

- This is the clip:
[]()https://youtu.be/XMYhpyDLi6k

**Comment by scb261** [comment]
The option _Download new chapters_ works only for **new** chapters, not for unread. Since after updating library in your video there wasn't notification with list of new chapters, I suppose there wasn't any of them. I guess it worked after reinstalling because those chapters weren't in database of the fresh app and therefore the app considered them as new.

**Comment by CarlosEsco** [comment]
If you want it to download all chapters the easiest solution is remove those manga from the library clear your db.  then add them again by long press.  do NOT click into the manga.  then do a library update.  Tachi will see them all as new chapters and download all the chapters.

**Comment by scb261** [comment]
@CarlosEsco isn't it easier to go to the Chapter tab, then click on three dots, click Download, click Unread/All/etc.? I see only one situation where your suggestion is easier - there are many mangas that are displayed together on a source's main page or on the same search page. If not, you need to search each manga individually and my suggestion is easier.

**Comment by CarlosEsco** [comment]
@scb261 yes that would the easiest solution and the most obvious but some people don't like to do that so i always give this as another solution.
