### ISSUE TITLE
[Feature Request] Automatically remove html from all text in app

### ISSUE THREAD

**Issue by Jaykoerner** [inorichi/tachiyomi#3393]
A common issue with many sources is that they commonly have html tags left over after scrapping, I assume this can be fixed by the extension developer but I can not find a single instance where it's inclusion is helpful, and believe using a regex to automatically filtering out anything between angle brackets that starts with the "words" p,h1(h2...etc),span, hr, any other common html tags and to get the closing brackets anything that starts with a backslash( / )would be helpful.

Hope this is isn't a duplicate I didn't see it as a request. Thanks for listening

![Screenshot_20200627-125918_Tachiyomi](https://user-images.githubusercontent.com/6897487/85928874-0ce1d580-b876-11ea-8efe-9ce2afc80f09.jpg)

**Comment by CarlosEsco** [comment]
Don't think this is something that needs to be added as html here means the extensions should be fixed.  Open an issue in the extensions repo for this source.

**Comment by Jaykoerner** [comment]
I get your point that it's a extension issue, my point is that in no case I can think of will it ever be beneficial to have html passed through to text fields, as such it makes sense to do a Passover of all text in the app to get rid of it regardless of misconfigured extensions, just my thoughts and just making sure that viewpoint was gotten across, thanks for the reply
