### ISSUE TITLE
[Bug] Fails to download over Wifi if 'Only download over Wifi' is enabled

### ISSUE THREAD

**Issue by Hew-ux** [inorichi/tachiyomi#3395]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Lenovo M10 tablet plus

## Steps to reproduce
1. Connect to your Wifi network.
2. Turn on 'Only download over Wifi' in the settings.
3. Attempt to download any manga.

### Expected behavior
It downloads over the Wifi connection.

### Actual behavior
A non-dismissable notification appears: 'No Wifi connection available'. The item gets stuck at 'Queued' and never downloads. Video showing the download working with the option off and failing with the option on: https://m.imgur.com/a/4TSYduW

###Workarounds
Turn off 'Only download over Wifi', force stop Tachiyomi and try again. It will download successfully.

### Other details
Same error occurs on my old Samsung tablet (Android 4.4) but not on my phone (Android 6). This makes me believe that this error only occurs on devices that can only connect to the internet via Wifi and nothing else.

**Comment by Albnu14** [comment]
I have this same problem, but i thought it was becuase my wifi connection is metered, so i disabled 'only download over wifi'.
Just to be sure , is your wifi connection metered ?

**Comment by Hew-ux** [comment]
Yes, I have it set to metered. Turning it off allows downloading even when the 'Only download over Wifi' option is enabled. In that case, it could be labelled as 'Only download over unmetered Wifi' to avoid confusion.

The error message specifically saying there is no Wifi connection available could also be changed in a similar fashion when this setting is enabled.

**Comment by Albnu14** [comment]
Yup, changing to 'only download over unmetered wifi' seems good to me, 
And maybe developers can add something to the error message to make it clear to the user
