### ISSUE TITLE
[Feature Request] <Ability to mark a manga as favourite in the tracking section>

### ISSUE THREAD

**Issue by crusaside** [inorichi/tachiyomi#3397]
Why/User Benefit/User Problem
self explanatory. users will be able to mark their favourite manga as favourite in MyAnimeList tracking. personally logging in to MAL in browser and then searching manga and marking them favourite is just a looooooooot of work.

What/Requirements
a button in the tracking section of a manga to mark it favourite in MAL.

thank you!

**Comment by pervertkirito** [comment]
you can tap on the icon, it will open browser.

**Comment by crusaside** [comment]
> you can tap on the icon, it will open browser.

good idea. i didn't notice. but it's still a hassle tho

**Comment by crusaside** [comment]
oh no only 10 favs are allowed on mal. my bad.
