### ISSUE TITLE
[Bug] download queue suddenly missing

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi#3398]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 7.1.1
* Device: xiaomi mi max 2

## Steps to reproduce
I have more than a hundred chapter in download queue. While I read downloaded chapter through another image app. I back to tachiyomi to see download progress. It's not responding. When I reopened it, all my queue is gone. It's happening twice already. Help please

**Comment by arkon** [comment]
MIUI is probably aggressively killing the app.

See https://dontkillmyapp.com/xiaomi
