### ISSUE TITLE
Backup and restore.

### ISSUE THREAD

**Issue by beepFTW** [inorichi/tachiyomi#34]
Let's be honest we are on Android and a lot of us like to fiddle with our devices. So there is always a chance of losing recent data even with nandroid backups. An option to backup bookmarks, read progression, and user settings would be great!

There also may be times where we would want to move between dev and normal version as well. Thanks for reading.

**Comment by wopian** [comment]
:+1:

**Comment by inorichi** [comment]
Yup, I know. I'll work on it ASAP.

**Comment by namack75** [comment]
+1

**Comment by Bloodwork** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by beepFTW** [comment]
Would this be better implemented through an online account sync like Manga Rock or to sdcard like MangaDLR? Online account sync seems like alot of unnecessary work..

**Comment by cyalins** [comment]
I think they mean local backup; hosting a server to sync with seems like it'd be too much

**Comment by wopian** [comment]
Local backup >>>>>> online backup

**Comment by beepFTW** [comment]
The more I think about it, the more I agree. Local backup is much more practical. 😏

**Comment by inorichi** [comment]
I've got local backup working. It should be available soon, once I improve the test suite and the UI (it's just two buttons).

**Comment by beepFTW** [comment]
Can't wait! Can the you update the release version to go with it? I'd like to easily make the transition to dev.

**Comment by inorichi** [comment]
I'll release 0.1.3 soon, but backup won't be included until 0.2.0 (which should be the next version). I want to test backup in dev version for at least a week.

**Comment by ArathoN** [comment]
Wonderful I'll gladly test it and report anu bugs when you'll release the dev version. For now I'm backing the app with titanium backup after huge changes and before updating the app.

**Comment by inorichi** [comment]
It took longer than expected... 

My advice is: be careful using this yet, I have added tests and it worked fine for me, but something unexpected may happen.

**Comment by inorichi** [comment]
I forgot to mention a copy of the backup is saved in the external cache directory, which usually is `/sdcard/data/eu.kanade.tachiyomi<.debug>/cache`, in case the applications shown when saving the backup are useless. Copy it elsewhere if you don't use any app, because it will be deleted if you uninstall/delete app's data.

**Comment by IceKreem** [comment]
Would also like to mention it worked fine for me too, but I'll keep an eye on it ;)

**Comment by Bloodwork** [comment]
I can't root my intel atom tablet unfortunately. Still waiting for backup feature in the main build.

**Comment by namack75** [comment]
just to confirm, does the device need to be rooted?

**Comment by inorichi** [comment]
Not if you use the backup feature of the application.

**Comment by inorichi** [comment]
If anyone has any problem with this feature, please create a new issue. Before deleting the application's data, make sure the backup file is not empty.

**Comment by momoshiromejias** [comment]
can i ask if there is a sync option for yahoomail account for example, cause when i create backup in drive and when i used the backup, there`s an error

**Comment by afat123** [comment]
can i ask if tachiyomi can add a japanese manga extension website that is called kisslove . net?(i dont know if links can be posted here or not, so im gonna put spaces on the dot so it wont become a link just incase)(kisslove . net is rawwqq . com(iirc)((if you use pc and loading images failed it stated something and then it says "rawqq")))
it was removed from tachiyomi version 0.9.2

**Comment by arkon** [comment]
@afat123 Check the spreadsheet here: https://tachiyomi.org/extensions/

**Comment by afat123** [comment]
> 
> 
> @afat123 Check the spreadsheet here: https://tachiyomi.org/extensions/

i checked it, and it doesnt exist(the kisslove manga extension)
theres a few(or maybe more) manga that the available extension dont have/have no update to it for a long time...

is there a possibility it will be re added in the future?

**Comment by wopian** [comment]
@afat123 This is the wrong place for this discussion, but that site is in the FMReader extension as the spreadsheet states.

**Comment by afat123** [comment]
> 
> 
> @afat123 This is the wrong place for this discussion, but that site is in the FMReader extension as the spreadsheet states.

thanks so much for the infooooooo
