### ISSUE TITLE
[Bug] <Mangahasu keeps saying For Input string: """ can you please fix this bug. Thank you for everything>

### ISSUE THREAD

**Issue by yumeinmoon** [inorichi/tachiyomi#3402]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung M30s

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Should be able to read the manga

### Actual behavior
Instead it keeps saying For Input String: """"

### Other details
Extension name: Mangahasu

**Comment by arkon** [comment]
> If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions
