### ISSUE TITLE
[Bug] Manga I added in my library keeps dissapearing

### ISSUE THREAD

**Issue by AkoSiJam** [inorichi/tachiyomi#3404]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Huawei Y9 prime 2019 

## Steps to reproduce
1. Add manga to library
2. Wait

### Expected behavior
Manga stays in library.

### Actual behavior
It gets removed

### Other details
I just noticed it recently but a lot of the manga I saved got removed(even the ones I just read recently).

**Comment by Flat** [comment]
Duplicate #3390
