### ISSUE TITLE
[Feature Request] Add ability to disable chapter end pages/ transition pages

### ISSUE THREAD

**Issue by Jaykoerner** [inorichi/tachiyomi#3405]
Some novels have(nothing but) single page chapters(basically it's for 4 koma template manga, but while rare others exist) making the chapter transitions a real pain, the ability to disable them would make reading of such novels more enjoyable. It would probably also be helpful for the usability of such a feature for the app to be able to read a few chapters ahead in such a case, but even if only in download it would be helpful.

**Comment by CarlosEsco** [comment]
What version of tachiyomi are you using?  if its not .9+ then you upgrade there already is an option that conditionally disables the page.  Though it might not work correctly for 1 page manga

**Comment by arkon** [comment]
#3079 for single page issue

**Comment by Jaykoerner** [comment]
Whoops it there now, didn't see it last time I checked, yeah I see what your talking about it might not work for 1 page manga correctly though, maybe 1 out of 20 chapters I see the transition, but yeah closing the issue since the features there.
