### ISSUE TITLE
[Feature Request] <Show content in cutout area for J2K fork >

### ISSUE THREAD

**Issue by ADMOrange0115** [inorichi/tachiyomi#3407]
Good day dev! I hope you all are safe, I have just one request and and its about the an option to put "Show content in cutout area" for J2K fork. I noticed only the J2K for didn't have this option while browsing at every available fork of Tachiyomi and of course also the main apk. The J2K fork UI really stands out. I hope the show content for phones in that have cutouts will be available for the next update. 😁

**Comment by joseph619** [comment]
This repo is for the main app only, not J2K. Post on J2K repo.
