### ISSUE TITLE
[Feature Request] Add ability to group together multiple sources for the same manga

### ISSUE THREAD

**Issue by SheepGravy** [inorichi/tachiyomi#3408]
As a regular user of Tachiyomi, I've often encountered situations where I'd have to use multiple sources for the same manga. My suggestion is to add a feature that lets you manually group together copies of the same manga from different sources, and (possibly automatically) compare their image quality and loading speed. This will be especially helpful for people with slower internet who'd otherwise need to check each source to see which one loads faster, and also people downloading manga who'd otherwise check which source has the best quality.

My idea for how it would work:
In the library, when having selected multiple manga add option to 'merge to one manga'
When this option is picked, the user will be prompted to select which title to use for the manga out of the different titles from different sources and which cover to use
Next, Tachiyomi will download a couple of pages from each source and automatically check 
(1) How fast the pages are loading from each source
(2) How does the image quality compare (a simple resolution comparison might suffice)
It will present its findings by creating a simple table and displaying the data in ascending order for the speed and descending order for quality. 
The user can now pick a default source by tapping on any one from the table. 
If the user wishes to redo the source-comparison, it can be accessed through the upper right corner of the manga's page
To add more sources to an existing manga group, a [+] sign will be present next to the 'Source:' tag present in the description

**Comment by evo85210** [comment]
I believe this has been requested before, but has been turned down due to technical difficulties.

**Comment by CarlosEsco** [comment]
#886
