### ISSUE TITLE
Add handler for supported website URIs

### ISSUE THREAD

**Issue by jsilvermist** [inorichi/tachiyomi#341]
Add a handler for website URIs to add the ability to open Tachiyomi directly to the specified manga when clicking a link to a manga on a supported source.

[Android Developer - Handling App Links](https://developer.android.com/training/app-links/index.html)

Example: When clicking on the link:
`http://m.mangahere.co/manga/the_gamer/`
OR
`http://www.mangahere.co/manga/the_gamer/`
Tachiyomi would also be an option for opening the link instead of Chrome, and would open directly to the source and manga where it could be read or added to the library.

**Comment by VirusEcks** [comment]
+1 for this feature

**Comment by inorichi** [comment]
This requires changes to the manifest, so external sources couldn't use this, and only a few sites could include it. 

As I'm trying to externalize them all I can, this seems not worth it.

**Comment by karakot** [comment]
Are you not planning to implement this at all or is this a "too soon" feature

**Comment by Syborg49** [comment]
@karakot This is a trade-off between flexible or hardcoded sources. Given the choice I'll gladly take the first one.

**Comment by Sleeping-Donut** [comment]
hasn't this been implemented now with the extensions handling deep links? Should this be closed?
