### ISSUE TITLE
[Bug] Unable to read manga.

### ISSUE THREAD

**Issue by LollipopFt** [inorichi/tachiyomi#3410]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung Galaxy A51

## Steps to reproduce
1. Open any manga.

### Expected behavior
Manga page should load and be readable.

### Actual behavior
Manga page cannot load.
![Screenshot_20200701-141832_Tachiyomi](https://user-images.githubusercontent.com/62802897/86209839-fd2ffd00-bba5-11ea-8076-90c375789da4.jpg)
Brings me back to this page with the above message.

**Comment by loocool2** [comment]
MangaSee's domain has changed. This is not a app  issue, and the extension will be fixed eventually

**Comment by LollipopFt** [comment]
> MangaSee's domain has changed. This is not a app  issue, and the extension will be fixed eventually

When will it be fixed? Just want to know.

**Comment by LollipopFt** [comment]
Thank you!
