### ISSUE TITLE
[Feature Request] <Recommendations from MAL>

### ISSUE THREAD

**Issue by crusaside** [inorichi/tachiyomi#3413]
### Why/User Benefit/User Problem
we can see similar manga with just a touch of a button

### What/Requirements
exactly like TachiyomiSY has, a "see recommendations" button on being tapped, shows a list of similar manga from MAL. then on clicking a title from recommended list, automatic global search should be initiated from all extensions

**Comment by CarlosEsco** [comment]
#376
