### ISSUE TITLE
[Bug] Chapter returning to first page after attempting screenshot

### ISSUE THREAD

**Issue by JRowly** [inorichi/tachiyomi#3415]
Device information
Tachiyomi version: 0.9.2
Android version: 9
Device: Samsung Galaxy S8
Steps to reproduce
Go into any chapter of any manga to any page besides the first
Take a screenshot, either with the Samsung toolbar or regularly
Expected behavior
Chapter page should remain the same

Actual behavior
Chapter returns to first page

Other details
N/A

**Comment by arkon** [comment]
This is already fixed for the next release.
