### ISSUE TITLE
Mangadex Latest Tab not working

### ISSUE THREAD

**Issue by AoiSuwabe** [inorichi/tachiyomi#3417]
Hello!

Since a couple of days ago the latest tab is not working for Mangadex. Shows HTTP Error 500. I checked the website and it works, and I'm logged in there. I've tried NineManga just to know if it was an issue with my app and it works perfectly fine.

Please check it, it's my main source for Manga.

**Comment by CarlosEsco** [comment]
https://mangadex.org/updates/1/. Can you access this?

**Comment by CarlosEsco** [comment]
Also wrong repo

**Comment by AoiSuwabe** [comment]
No, I can't access it. But I can access the MangaDex webview from Tachiyomi.
