### ISSUE TITLE
[Feature Request] add button to  search all other sources manga info page

### ISSUE THREAD

**Issue by Jaykoerner** [inorichi/tachiyomi#3418]
The feature is basically just a reuse of source migration with a dedicated button on each manga to search all extensions for the title.

Reason this feature should exist,

• to more easily find manga on other sources without having favorite or copy and past the title
• to allow users to use one sources search in place of another (example some sources do not allow subtractive genre filtering, and you may want to use 1 source to find manga but another to read it)
• to allow users to more easily find other sources that may have a heater chapter count then the 1 Currently being red from

A good location for placement of said button is the link bar as shown below

![Screenshot_20200703-070626_Tachiyomi](https://user-images.githubusercontent.com/6897487/86467812-b94f0c00-bcfb-11ea-8623-239d682b7641.jpg)

**Comment by CarlosEsco** [comment]
Press the title.  It global searches the manga

**Comment by Jaykoerner** [comment]
That it does, hmm thanks for the info
