### ISSUE TITLE
[Feature Request] Regularly check for better source/ warn if no new chapters are released

### ISSUE THREAD

**Issue by keinezeit8** [inorichi/tachiyomi#3419]
This request was originally posted [here](
https://github.com/Jays2Kings/tachiyomiJ2K/issues/492#issue-638343326).

### Why/User Benefit/User Problem
Quite often a publishing group drops a series, which is later picked up by another group. When following many series' it is hard to notice once one doesn't update anymore, and has to be migrated.

### What/Requirements
A setting, that allows the user to choose how often a source should be checked against all other installed sources for newer chapters.

A lighter version will just alert the user that no new chapters have been released, and the user has to look for a better source himself.

It would also be nice if the average upload speed of a series is calculated and once no new chapters appear, the search is carried out.

release date of new chapters:

1. '1. Jan, 2. Feb, 28. Feb, 3.Apr
2. -> update ~ once a month
3. -> ~2 months after last chapter a new source is searched

This could be done over all chapters or just the most recent x (floating average)

I don't know how to manage series that are not published by anyone for a long time. (Only one attempt or repeated attempts at finding better sources)

**Comment by arkon** [comment]
Sounds roughly like #2419
