### ISSUE TITLE
[Bug] Tachiyomi relies on connectivity status when initiating extension update/download

### ISSUE THREAD

**Issue by gumadozucia** [inorichi/tachiyomi#3420]
As an owner of a Chinese tablet, I have blocked its access to connectivitycheck.*.com on my network, because living it open leads to multiple telemetry connections and drains battery faster. This causes the device to report wifi status as "Connected (no Internet access)" despite internet being available. 

Tachiomi doesn't initiate extension updates/downloads unless the device reports that internet is fully connected. All other Tachiyomi features including downloads and update checks work correctly, it's only extension updates that rely on connectivity check. 

### Device information
* Tachiyomi version: v0.9.2
* Android version: 10
* Device: MatePad T8

## Steps to reproduce
1. Block device connectivity status checks for privacy/performance/battery preservation
2. Initiate extension download or update

### Expected behavior
Tachiyomi tries to connect to update server and if it's successful downloads the update/extension.

### Actual behavior
Tachiyomi is stuck on a pending status.

**Comment by arkon** [comment]
All of the background jobs (library update, app updates check, extension updates check) rely on the same standard AndroidX WorkManager system. There's no plans to work around issues arisen from blocking that core functionality.
