### ISSUE TITLE
[Bug] Use Device Auth to gain access crashes

### ISSUE THREAD

**Issue by kennethtran93** [inorichi/tachiyomi#3425]
### Device information
* Tachiyomi version: Preview r2493
* Android version:  9
* Device: Samsung Galaxy S8
App version: 0.9.2-2493 (standard, 16fc58bd, 45)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.G950WVLS7CTC1
Device brand: samsung
Device manufacturer: samsung
Device name: dreamqltecan
Device model: SM-G950W
Device product name: dreamqltevl

## Steps to reproduce
1. Open app
2. Press 'use password' on biometric request. 

### Expected behavior
Show keyboard to type in password to gain access. 

### Actual behavior
Crashed and restarted. On restart, using biometric successfully returns to previous page /exits app. 

### Other details
On some occasions, after swiping away the app from the recent screen and reopening the app about a second later, it goes to the library without confirming biometric/password. 

I don't think this happened before the last update... Though I'm not sure how the last update may have changed it either.

**Comment by arkon** [comment]
```diff
- implementation 'androidx.biometric:biometric:1.0.1'
+ implementation 'androidx.biometric:biometric:1.1.0-alpha01'
```

I guess due to this update. I would need the crash logs though.

**Comment by kennethtran93** [comment]
I've enabled Send crash reports, restarted the app a couple of times until I got the biometric prompt again, then clicked use password.  This time, instead of restarting it to re-request biometric, it just crashed and went back to android launcher.

Unsure if anything got sent to you guys.  Let me know where to find the crash logs if any.

**Comment by arkon** [comment]
It may flow in eventually, but you can also get them manually and post it here using [these instructions](https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android).

**Comment by kennethtran93** [comment]
[bugreport-2020-07-07-15-28-01.zip](https://github.com/inorichi/tachiyomi/files/4887476/bugreport-2020-07-07-15-28-01.zip)

If it helps...

**Comment by kennethtran93** [comment]
https://issuetracker.google.com/issues/159983244 may be a relevant issue based on what I read in my generated bug report.

**Comment by arkon** [comment]
Yes, that looks like it. Thanks for saving me the effort for Googling it too. :D

**Comment by kennethtran93** [comment]
From one dev (non-android but still a dev) to another.

**Comment by kennethtran93** [comment]
Any chance the biometric library could be reverted back to pre-alpha for the time being?

**Comment by arkon** [comment]
Maybe if I need to do a stable release, but otherwise I'll just wait for an update to the library. There's been a fix submitted already.
