### ISSUE TITLE
Retry failed downloads/A page is missing in dictionary

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#343]
Currently when a chapter is being downloaded, if a page fails to download it throws a "A page is missing in dictionary" error as a notification. 

The rest of the chapter is then seemingly abandoned and the next chapter starts downloading - which when batch downloading many chapters causes a large portion of partially downloaded chapters left when the batch download is "complete". 

Pausing and restarting from the Download queue successfully downloads the missing pages and removes it from the download queue - so simply retrying a page download a couple of times if it fails before carrying on would solve this. 

Edit: Page 9 of this manga seems to mostly always be failing for the ~100 chapters I've downloaded so far. (MangaHere source)

![](http://i.imgur.com/JVXPhIg.png)

**Comment by inorichi** [comment]
It does retry:

```
.retryWhen {
    it.zipWith(Observable.range(1, 3)) { errors, retries -> retries }
        .flatMap { retries -> Observable.timer((retries * 2).toLong(), TimeUnit.SECONDS) }
}
```

3 times, waiting 2, 4, 6 seconds respectively before retrying

**Comment by wopian** [comment]
What about retrying once all chapters have been downloaded and these errored chapters are left in the download queue?

**Comment by inorichi** [comment]
Automatically restarting seems very problematic. The wait time can be increased, sure, but it won't solve the issue (though it can get better results).

**Comment by shogunreaper** [comment]
i think its just an interface problem.. i've seen it happen before and when i pause all downloads and then restart those chapters are removed from the queue. (though the pages still failed)

> It does retry:

it does? Does it try to redownload the failed pages while its downloading later ones at the same time? Or does it wait those 2,4,6 seconds before moving on to the next page?

i still end up with chapters with a lot of broken pages though. Would be nice if you could add a way to retry failed pages manually outside of the chapters itself. It's a bit annoying to be reading a manga and come across a failed page and then have to turn my wifi back on and wait for it to download again.

**Comment by inorichi** [comment]
It waits before moving to the next page. 682a2c7 may fix chapters being incorrectly downloaded.

**Comment by inorichi** [comment]
No further measures will be taken here. It will wait 2, 4, 8 seconds now, but that won't be enough sometimes. Chapters shouldn't disappear now from the queue if they are partially downloaded (corrupt images should be removed properly).

**Comment by shogunreaper** [comment]
so we have to manually redownload the page every time it fails?

**Comment by inorichi** [comment]
Chapter is kept in the queue (unless the application is killed, but that is another issue which is already open). Use the start button from the download queue and it will try to download it again.
