### ISSUE TITLE
[Feature Request] <Image Quality Setting>

### ISSUE THREAD

**Issue by kacipz** [inorichi/tachiyomi#3430]
the benefits of image quality settings are to maximize user comfort in network usage and phone storage usage.  because not all users have strong network quality and large memory capacity.  This image quality settings is intended to reduce the size of images downloaded or used for reading online.  Until the latest version there is not yet image quality setting feature available, the downloaded images are still in the best quality (same as the original file) so all users use alot of data and storage usage for their mobile phones.
in some cases that occur on mobile phones with low storage quality, there are some errors that often occur during the process of loading large images.  such as "loading image takes too long time", "image cannot be loaded", "application is slowing down", "image is corrupt", "application is not responding", and so on.

**Comment by arkon** [comment]
Storage: #918
Data usage: depends on the source. The app can't magically use less data to hit a website.
