### ISSUE TITLE
[Bug] String must not be empty // Index:1, Size:1

### ISSUE THREAD

**Issue by Momonga98** [inorichi/tachiyomi#3433]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Redmi Note 8 Pro

## Steps to reproduce
1. LectorManga has not worked for months. Yesterday I tried TuMangaOnline and it worked, I was reading for a while and I downloaded some chapters.
2. The app downloaded about 15 chapters and at some point the cell phone was restarted.  After turning on the cell phone, I went to the download section to continue the process.  That's when I started to get that problem and it wasn't just the downloads, when I wanted to read a new manga the same error appeared.

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
LectorManga and TuMangaOnline now show the same error.  I have tried uninstalling the app and extensions and reinstalling it but it didn't work.  
Sometimes it shows error Index: 1, Size: 1.
It also didn't work using VPN.

![Screenshot_2020-07-08-19-42-59-807_eu kanade tachiyomi](https://user-images.githubusercontent.com/68036646/86980967-4efef700-c153-11ea-8327-dcc826a2e30d.jpg)

![Screenshot_2020-07-08-19-41-59-863_eu kanade tachiyomi](https://user-images.githubusercontent.com/68036646/86980985-5cb47c80-c153-11ea-93de-926dd1c03fca.jpg)

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2714
