### ISSUE TITLE
[Bug] <WebView not working in Viz>

### ISSUE THREAD

**Issue by kashinkoji** [inorichi/tachiyomi#3436]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1
* Device: 10.Or E

## Steps to reproduce
1. Open Viz Media Extention
2. Select WebView option

### Expected behavior
The Website should open

### Actual behavior
The app crashes and reopens

**Comment by arkon** [comment]
Appears to be fixed in preview.
