### ISSUE TITLE
[Bug] Date header in updates tab shows "Today" for yesterday updates

### ISSUE THREAD

**Issue by stirante** [inorichi/tachiyomi#3437]
The date header, which separates chapters in Updates tab shows "Today" for updates, that happened yesterday.

![image](https://user-images.githubusercontent.com/2420740/87033909-553eb300-c1e7-11ea-8ccd-4553be95e967.png)

### Device information
* Tachiyomi version: r2108
* Android version: 10
* Device: Pocophone F1

## Steps to reproduce
I couldn't find exact steps to reproduce, but It always happens few hours after midnight, when there are new chapters. After refreshing library manually, the headers are correct.

## Possible cause
I think it might be something about time zones (since depending on the date, I have +1 or +2 hours) or just a caching issue.

## Possible fix
I tried to find the code responsible for this behaviour, if it's indeed because of time zones and I think, it could be fixed by changing [`toDateKey`](https://github.com/inorichi/tachiyomi/blob/dev/app/src/main/java/eu/kanade/tachiyomi/util/lang/DateExtensions.kt#L23) extension, so it uses the same method as [`DateUtils.getRelativeTimeSpanString`](https://android.googlesource.com/platform/libcore/+/refs/heads/master/luni/src/main/java/libcore/icu/RelativeDateTimeFormatter.java#361) from android source code to get the day number.

**Comment by scb261** [comment]
#2290 seems to be the same bug where arkon said that it won't be fixed
