### ISSUE TITLE
[Bug] Screen goes complete black

### ISSUE THREAD

**Issue by AndreaS4D** [inorichi/tachiyomi#3439]
### Device information
* Tachiyomi version: 0.9.2 
* Android version: Android 10
* Device: Xiaomi Mi A3

## Steps to reproduce
I don't know how to reproduce it because I'm not sure why it happens, my only guess is that happens when I'm reading something and I change to WhatsApp (for example) without going back to the library before. But it isn't always like that, sometime it happens, sometimes it doesnt.
1. First step
2. Second step

### Expected behavior
When I open any chapter, I should be able to see the image.

### Actual behavior
My complete screen goes all black as if was turned-off

### Other details
I made a quick video on YouTube to explain it because in my screenshots the bug wasn't visible. 
https://youtu.be/HPk3qM1NMUM
The app works fine for a couple of days or hours, by then it happens what you can see on the video. I don't know if it's fixable, or if its my device? I have another phone (Moto E4 Plus Android 7) in which the apps works well. My guess in here is that the Xiaomi Mi A3 has an Amoled Screen (which means the black colour is really intense) and maybe that's what causes the bug? I have also tried turning off the dark mode and restart my phone, but it doesn't change anything. 
I was using TachiJ2K all this time so I moved to the regular version of Tachiyomi and the same happened, so I run out of options. Whenever this happens I just have to make a backup and reinstall or clear all the app data to fix it for some time, but eventually the black screen appears again.
Sorry if what I said in the video or wrote in here wasn't very clear, english is not my mother tongue.

**Comment by arkon** [comment]
Do you have a color filter or custom brightness set in the reader?
