### ISSUE TITLE
Problems Loading Chapters from Kissmanga Catalog

### ISSUE THREAD

**Issue by basilg3** [inorichi/tachiyomi#344]
First, I'd like to say that this app has hardly ever given me much trouble before now, and has been a very trustworthy manga reader.

On to the issue at hand... Whenever I try to load anything from the Kissmanga catalog (or even searching the catalog itself) I recieve an error message that reads "SyntaxError: unterminated statement (line 1)". All of the manga chapters I have from this catalog produce this error message when they are selected for reading. I've tried clearing cache, cookies, checking internet connection, and anything else that may fix the issue, but to no avail. 

Is there anything that can be done about this? Thank you.

Version: r771 or v0.2.2.771

**Comment by SirXCalibur** [comment]
I've just got this problem as well. I just recently try Android N beta then this happen. Not sure if that is the source of issue. What kind of OS do you use?

**Comment by inorichi** [comment]
Cloudflare is updating their auth system lately. I don't know how often they do. It's possible this happens again in a few days.
