### ISSUE TITLE
[Bug] chapter list loading takes 1-2 minutes when I have ridiculous amounts of downloaded manga

### ISSUE THREAD

**Issue by orangpelupa** [inorichi/tachiyomi#3441]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 5.0.0
* Device: asus fonepad 8 

## Steps to reproduce
1. Have ridiculous amounts of downloaded manga (1000+ title, each with hundreds of chapters) 
2. Close tachiyomi 
3. Open tachiyomi and go to the library 
4. Open a manga
5. Go to chapter tab 

### Expected behavior
Chapter list appear 

### Actual behavior
Chapter list appear after 1-2 minutes. 

### Other details
If I changed the download directory to a different folder that's free of files, the library list will appear instantly. 

If I changed it back to my download folder with ridiculous amounts of manga downloaded, slow chapter list loading 
Additional details and attachments.

**Comment by orangpelupa** [comment]
Maybe it's due to the sheer amounts of files, so it takes that long to list the chapters? 

Because AFAIK tachiyomi did not cache the "downloaded" status. It recheck the files directly every launch.

**Comment by MCAxiaz** [comment]
Yea, the entire cache is built at once on the first access. Even if you're just opening a single manga, every single download across all manga gets checked and added to the cache.

**Comment by pervertkirito** [comment]
are you use custom location?
#2676

**Comment by orangpelupa** [comment]
> are you use custom location?
> #2676

Yes, custom location on SD card

**Comment by CarlosEsco** [comment]
Move it off SD card and try.

**Comment by orangpelupa** [comment]
> Move it off SD card and try.

Unfortunately my internal storage is only 8GB, while my downloaded manga is more than 32GB haha. So I can't do that

**Comment by CarlosEsco** [comment]
Well then you are out of luck. Sdcard support is 2nd party at best on Android and the best you can do is upgrade to another faster sdcard

**Comment by orangpelupa** [comment]
> Well then you are out of luck. Sdcard support is 2nd party at best on Android and the best you can do is upgrade to another faster sdcard

Its already fast v30 SD card. Android SD card speed is just abysmal haha.

So I guess, this issue won't be fixed, as it's bit a bug but by design. Need tachiyomi revamped it's caching methods / logic, I think.

Should I close this and put a feature request? Or just left this open?

**Comment by arkon** [comment]
> Android SD card speed is just abysmal haha.

Pretty much, especially if you deviate from the the "standard" locations. You could try moving it to whatever the standard folder is supposed to be for some potentially marginal improvement.

The caching logic on load could likely be improved, but it isn't high priority currently.

**Comment by orangpelupa** [comment]
> > Android SD card speed is just abysmal haha.
> 
> Pretty much, especially if you deviate from the the "standard" locations. You could try moving it to whatever the standard folder is supposed to be for some potentially marginal improvement.
> 
> The caching logic on load could likely be improved, but it isn't high priority currently.

Thank you! Will try it after dinner, and I'll report back the result

**Comment by orangpelupa** [comment]
Moved to standard location, yes it loads faster. It's now less than a minute.

Not really solved, but gonna close this as it's not a bug. 

Thank you
