### ISSUE TITLE
[Bug] Incorrect date and time in the Sardinian and Chuvash localities.

### ISSUE THREAD

**Issue by Voylo** [inorichi/tachiyomi#3446]
### Device information
* Tachiyomi version: 0.9.2 (sc), r2493 (sc, cv) 
* Android version: 9
* Device: Redmi 8A

## Steps to reproduce
1. First step 
To put the Chuvash or the Sardinian language
2. Second step
Go to the "History" or "Updates", or "More" > "About" section
![IMG_20200711_002129](https://user-images.githubusercontent.com/68130021/87205641-967eb200-c310-11ea-9995-77e88bef3d39.jpg)

### Expected behavior
For Chuvash:
2 days ago — "2 кун каялла", Today — "Паян", Yesterday — "Ӗнер"; Jul 7, 2020 — 2020, утӑ, 11; 7/11/2020 —2020,07,11 (or 2020.07.11)

### Actual behavior
For Chuvash:
2 days ago — "-2 d", Today — "Today", Yesterday — "Yesterday"; Jul 7, 2020 — 2020 M07 11; 7/11/2020 —2020-07-11

**Comment by corrado4eyes** [comment]
Maybe related to [this](https://github.com/inorichi/tachiyomi/issues/3437)

**Comment by arkon** [comment]
> May be related to [this](https://github.com/inorichi/tachiyomi/issues/3437)

Nope, this is a localization issue. Potentially an AOSP bug since those strings just call a platform API to get the strings.

**Comment by Voylo** [comment]
> > May be related to [this](https://github.com/inorichi/tachiyomi/issues/3437)
> 
> Nope, this is a localization issue. Potentially an AOSP bug since those strings just call a platform API to get the strings.

Can't this be changed?

**Comment by arkon** [comment]
Yeah so we just use `android.text.format.DateUtils#getRelativeTimeSpanString`, so this is an issue with AOSP.

Not going to work around it in Tachiyomi since it only affects 2 less common locales.
