### ISSUE TITLE
[Feature Request] Reading Folder

### ISSUE THREAD

**Issue by Per0x** [inorichi/tachiyomi#3447]
In addition to the "download folder" feature, it would be very convenient to have the possibility to specify a second folder for reading only.

Let me explain. To avoid having to download mangas on my phone because there is not enough space, when I download them, they are automatically sent to a folder in the cloud with Nextcloud and then deleted from the original folder on the phone. 
But once deleted, the app doesn't find the files anymore (normal because they have been suppressed), so if we could specify a second folder not for downloads but for reading wich point to the cloud folder this time, we would have an proper access of the content on the cloud.

**Comment by arkon** [comment]
Basically the same as #2418.

You can also just use something like https://komga.org/

**Comment by Per0x** [comment]
#2418 is a bug issue, not a feature issue. The problem he describes is related to Nextcloud, not Tachiyomi.
I will check Komga, but it's a whole media server, not just a cloud access.

**Comment by arkon** [comment]
It's the same idea of being able to mount/point to a remote directory.

Regardless, I don't really think any sort of remote directory support will ever be added considering how non-trivial it is.

**Comment by Per0x** [comment]
The method I propose to have two distinct folders, one for downloads and one for reading would also work with Google Drive app, etc.

**Comment by arkon** [comment]
> The method I propose to have two distinct folders, one for downloads and one for reading

The idea of having multiple download directories (which is what a "reading" directory would be) adds too much unnecessary complexity that's bound to just confuse people, not to mention the overhead of having to manage the contents between directories. Wouldn't it make more sense to just mount a remote directory as the single download directory to meet your usecase anyway?

> Being able to mount a remote directory is managed by the cloud app

Yes, except accessing cloud storage with any of those apps doesn't transparently allow apps to access them as if they're just part of the regular filesystem. That's the core issue presented in #2418.

**Comment by Per0x** [comment]
> Wouldn't it make more sense to just mount a remote directory as the single download directory to meet your usecase anyway?

Yes totally, except that in practice, it works very badly and 90% of the files return in failure with that direct access. 
A specialized app has to manage the queues and sendings for it to work good. It's true that it's not user friendly to have multiple access folders in the app, but I don't really see other simple solutions at first glance.

However, since you were telling me about Komga, I saw that there was the extension in Tachiyomi so it looks interesting.
