### ISSUE TITLE
[Feature Request] <Ability to filter more than just one category>

### ISSUE THREAD

**Issue by AkoSiJam** [inorichi/tachiyomi#3449]
---

### Why/User Benefit/User Problem
It will make finding certain types of manga easier. 

### What/Requirements
It will filter manga with the tags you selected(ex. You chose shounen and action, it will show you the mangas with those tags.

**Comment by arkon** [comment]
Not sure what you mean, library search already does all categories.

**Comment by AkoSiJam** [comment]
I mean the filter button when browsing. It only allows you to filter 1 category.

**Comment by arkon** [comment]
Duplicate of #2698

**Comment by CarlosEsco** [comment]
I assumed this was when browsing a source. But there highly dependant on a source allowing it this will stay closed.
