### ISSUE TITLE
[Bug] Manga source name became series of numbers

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3450]
### Device information
* Tachiyomi version: 0.9.2-2493
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Uninstall extension when manga is still in library

### Expected behavior
Source name must retain even if it was uninstalled

### Actual behavior
Source in library and migrate tab became random numbers

**Comment by CarlosEsco** [comment]
Not a bug. If you uninstall the extension why do you expect the manga to keep info about a source. At this point it's also unusable
