### ISSUE TITLE
[Feature Request] <need more filter genre on library>

### ISSUE THREAD

**Issue by Andi234Pisces** [inorichi/tachiyomi#3452]
![Screenshot_20200712-030450](https://user-images.githubusercontent.com/7387311/87231893-63f6b700-c3ed-11ea-8661-84f55aaec39a.png)

---

### Why/User Benefit/User Problem
(so user can easy arange each genre he want to read, download or delete)

### What/Requirements
(the genre to be added on filter in library)

**Comment by CarlosEsco** [comment]
Type the genre in the search bar
