### ISSUE TITLE
[Bug] <When reload the pages/manga, the downloaded manga were deleted>

### ISSUE THREAD

**Issue by Naetaaa** [inorichi/tachiyomi#3456]
### Device information
* Tachiyomi version: v0.92
* Android version: ? 10
* Device: ? RealMe 5 Pro

## Steps to reproduce
1. Opened already downloaded manga in library
2. Reloaded for new update chapters

### Expected behavior
When reloaded, the new chapter shown up, while still having the downloaded manga in library

### Actual behavior
When reloaded, the new chapter shown up, but the downloaded manga were deleted

### Other details
Although in library the manga chapters were deleted, when I search for manga in the android system, there are still there, only not shown in the library. More detail, in android system under the file of Tachiyomi, the manga is still there, but not in the app.

![Screenshot_2020-07-12-15-42-36-08](https://user-images.githubusercontent.com/68180542/87241512-7eb14600-c456-11ea-906a-97c629dc2d75.jpg)

![Screenshot_2020-07-12-15-42-37-99](https://user-images.githubusercontent.com/68180542/87241520-938dd980-c456-11ea-846c-da8d1d002d3c.jpg)

I reloaded the page specificly in Mangaowl

**Comment by arkon** [comment]
This happens if the chapters list changes, which you can see it did.

The app tries to rename downloads on the next release if the detected chapter numbers match up.
