### ISSUE TITLE
[Bug] "Date Added" Option Sorts Alphabetically Instead.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#3458]
### Device information
* Tachiyomi version: Dev r2511
* Android version: 6.0.1
* Device: Redmi Note 3.

## Steps to reproduce
1. Open the library.
2. Open sorting menu, sort by "date added".

### Expected behavior
This sorts all the manga by when they were last/first added.

### Actual behavior
The sorting is the same as the alphabetical one.

### Other details
None.

**Comment by CarlosEsco** [comment]
It's can't sort by date added if you haven't added a new ones. The date you added was never stored before.
