### ISSUE TITLE
[Bug] Persistent no result found while browsing manga from extension

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3460]
### Device information
* Tachiyomi version: 0.9.2-2511
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Browse from extension (e.g. mangasee)
2. Scroll down non stop
3. After scrolling, pick some manga (do some actions like tapping manga name to global search)
4. Go back mangas of extension (in my case, sometimes it doesn't load the next set of manga when scrolling down and will show no result found)

### Expected behavior
Load next set when clicking retry. 

### Actual behavior
After no result found message. Nothing happens when clicking retry. The message will be there and I cannot load the next set of manga. When I browse again in the extension, the no result found was there and clicking retry will remove the message

**Comment by CarlosEsco** [comment]
Are you sure your extension is up to date

**Comment by Mymiano** [comment]
yes, I always update my extensions when there is an update. It also happen in other extension (not loading next set when I open a manga). I always go back to list of extension to browse again

**Comment by CarlosEsco** [comment]
This is likely an extension issue.  If you want immediate help go on the discord channel and ask in support.
