### ISSUE TITLE
[Bug] <mangapark java.lang.exception: challenge not found>

### ISSUE THREAD

**Issue by anonncannon** [inorichi/tachiyomi#3464]
---

### Device information
* Tachiyomi version: 0.8.4
* Android version: 8.0.0
* Device: ASUS_Z01HD

## Steps to reproduce
1. opened manga in webview for mangapark + completed captcha
2. tried to open mangapark catalogue

### Expected behavior
should be able to use catalogue

### Actual behavior
recieved java.lang.exception: challenge not found

### Other details
tried this multiple times. I also don't get asked for the captcha anymore

**Comment by arkon** [comment]
As the issue template suggested, update to the latest version of the app before reporting issues.
