### ISSUE TITLE
[Bug] <Chapter counter does not work>

### ISSUE THREAD

**Issue by Hell13Cat** [inorichi/tachiyomi#3466]
### Device information
* Tachiyomi version: Prewiev r2493
* Android version: 9.0
* Device: Xiaomi Redmi 8A

## Steps to reproduce
1. Open any manga

### Expected behavior
Show the number of chapters in the right place

### Actual behavior
Always shows "1"

### Other details
![Screenshot_2020-07-13-12-32-56-733_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/46496367/87289765-ba571900-c505-11ea-9c6a-eb841a9eed65.jpg)
![Screenshot_2020-07-13-12-33-02-131_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/46496367/87289794-c4791780-c505-11ea-8bf4-923073205d63.jpg)

**Comment by arkon** [comment]
Russian translations for this are fixed in #3421
