### ISSUE TITLE
[Feature Request] Tracking icon should show if currently tracking

### ISSUE THREAD

**Issue by Osyx** [inorichi/tachiyomi#3470]
### Why/User Benefit/User Problem
The new tracking icon should show if the current manga is connected to a service. Currently you have to click on the icon and get to the view in order to know if it currently is syncing or not.

### What/Requirements
Maybe something like this
![image](https://user-images.githubusercontent.com/9387558/87322920-585ed980-c52e-11ea-808e-ba2478966fc3.png)
Which could relate to #3351.
And when not tracking, maybe something like this:
![image](https://user-images.githubusercontent.com/9387558/87323990-c952c100-c52f-11ea-93de-520bef6a6339.png)

Ugly as heck, but you get the point.

**Comment by arkon** [comment]
Done via a443dc3040f5e736ce632a5d00cbca77832ca46d
