### ISSUE TITLE
[Bug] <Search keyword gone after open the results>

### ISSUE THREAD

**Issue by Comdark** [inorichi/tachiyomi#3473]
### Device information
App version: 0.9.2-2511 (standard, e33cacf6, 45)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido

#Description
In previous version of preview, in the Library menu, the search mechanism/search term will stay/persist in result screen after i opened one of the results. I like this style.
But now, when i open 1 result then go back/hit back button, the search term is gone and i have to search/typing keyword again which is consuming time.

## Steps to reproduce
1. in the Library menu, Enter keyword in search
2. After showing results, open one of the results
3. Go back/hit back button
4. The search is gone/reset.

### Expected behavior
The search should be stay/persist in results screen after i opened one of the results.

### Actual behavior
The search gone/reset after i opened one of the results

### Other details
 This is the screen record, sorry i dont know how to attach video in here : 
[Screen record to produce the problem](https://cdn.discordapp.com/attachments/562903556944822288/732519391773720667/20200714_143707.mp4)

**Comment by M9k** [comment]
Hi,
I have the same problem, it work like you described only on the library, contrariwise on the "browse" it works like before.

App version: 0.9.2-2511
Android version: 10
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: lavander
Device model: Redmi Note 7
Device product name: lavander
ROM: MIUI 12 chinese dev weekly 20.7.9
