### ISSUE TITLE
[Bug] Sources in Portuguese(BR) isn't working

### ISSUE THREAD

**Issue by thwoner** [inorichi/tachiyomi#3481]
--

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* MIUI version: 11.0.6
* Device: Xiaomi Redmi Note 7

## Steps to reproduce
1. Download a source in Portuguese(BR)
2. Try to found a source

### Expected behavior
I expected to find the chapters in the installed sources

### Actual behavior
No fonts were showing up, even when I installed a font like MangaDex which also has an extension in Portuguese(BR) this presents problems to open the chapters.

### Other details
I made all possible updates to the sources in Portuguese but they still don't work

**Comment by arkon** [comment]
Enable Portuguese from the filter menu at the top right of Sources.
