### ISSUE TITLE
[Feature Request] problem indicator on library page

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#3482]
### Why/User Benefit/User Problem
It's nice that we get a log of updates that fail, but opening the log and check can be quite cumbersome, especially if multiple failed. Or in cases of missing sources, it's not even logged. 
In some cases I'd have the same manga on multiple sources, I'd have to memorize the name and source from the log, switch back and find it.

### What/Requirements
If the manga is missing sources, or update failed, have some kind of indicator, like a badge or border color I  the library page to allow for faster checking of the problem.

**Comment by evo85210** [comment]
Another idea, ability to just remove all for mangas that lost it's source?

**Comment by arkon** [comment]
I'll at least include source name and entries for things where the source isn't found, but I don't think I'll be adding explicit badges or anything.

An easy way to find orphaned manga is going to source migration and seeing whatever's under sources that are just numbers.
