### ISSUE TITLE
[Bug] Webtoonxyz not updating chapters

### ISSUE THREAD

**Issue by Sajeeb97** [inorichi/tachiyomi#3483]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1
* Device: Xiaomi note 3 pro

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
New chapters should update when pull down

### Actual behavior
This happened instead.

### Other details

![Screenshot_Tachiyomi_20200717-152938](https://user-images.githubusercontent.com/62636945/87771995-a4509d80-c810-11ea-86ab-1e3306ad0216.png)
When I pull down the manga it doesnt load new chapters.Instead it shows no chapter found whereas I can see there are new chapters on the webview.
Source-Webtoonxyz
Extension-Madara letest version

**Comment by scb261** [comment]
Wrong repository, see github.com/inorichi/tachiyomi-extensions
