### ISSUE TITLE
[Feature Request] Download all manga in a category

### ISSUE THREAD

**Issue by Frontear** [inorichi/tachiyomi#3485]
### Why/User Benefit/User Problem
Currently users have the option to create categories for a variety of reasons. One of these reasons could be to have the absolute most favorited manga/comics, which are essential to download for offline reading. As it is now, this isn't easy, since it requires manually going through every single one to download.

### What/Requirements
Allow us to select a category, then Download All.

**Comment by arkon** [comment]
In the preview version (or the next stable release):

1. Navigate to category tab
2. Long press one
3. Select all from top right
4. Press download in action menu at bottom
