### ISSUE TITLE
Webpage sent 405 code

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#349]
Just updated to **2.2.1-1** and I'm getting this error whenever I try to download and or just read online.

See it here: https://my.mixtape.moe/eabewp.mp4

**Comment by inorichi** [comment]
Have you tried updating the chapter list?

**Comment by pitman10** [comment]
I've Uninstalled the app (did this before I saw your response)  -> Installed 2.21 -> Restored from backup (Wish it saved setting as well) -> Installed 2.2.1-1 and now it works.

**Comment by inorichi** [comment]
No, it doesn't save settings, only the database. You will see an error saying "user is not logged" when you try to refresh the list from batoto (I'm guessing it's from batoto).
