### ISSUE TITLE
[Bug] Header in manga section becomes white in dark mode

### ISSUE THREAD

**Issue by bailinhuang** [inorichi/tachiyomi#3497]
Device information
* Tachiyomi version: 0.9.2
* Android version: EMUI 10
* Device: Huawei Mate 20

## Steps to reproduce
(on dark mode) 
1. Go to a manga on the chapters section. 
2. Hold chapter. 

## Issue/Request
The header were the manga name appears becomes white in dark mode. 

## Other details
Additional details and  @attachments.
![Screenshot_20200721_004901_eu kanade tachiyomi](https://user-images.githubusercontent.com/24628727/88022416-760ede80-caec-11ea-99f9-8506aa7933dd.jpg)

**Comment by arkon** [comment]
Does this happen elsewhere in the app too? Is this just an EMUI theming issue?

**Comment by bailinhuang** [comment]
Ok, weird. I cannot reproduce it anymore. Might have been an edge case or an EMUI issue.

**Comment by arkon** [comment]
Reopen an issue if you can reproduce it consistently.
