### ISSUE TITLE
[Bug] Automatic updates aren't working 

### ISSUE THREAD

**Issue by EdwardUV** [inorichi/tachiyomi#3501]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Huawei P20

## Steps to reproduce
No steps as far as I'm aware. I'm not certain what caused this so i do not know how to reproduce it. 

### Expected behavior
Library should be updating every 3 hours. 

### Actual behavior
Library isn't updating automatically, I've tried 6 and 3 hour intervals. Manual updating of the library still works fine. 

### Other details
Switched from an older Huawei P9 Lite to this phone and used the restore feature. It all worked mostly fine with the exeption of one manga with an extension that I believe got removed since it didn't show up in the old phone either. Automatic updates still work on the old phone. This phone isn't new either, I got it from another person but it's in good shape as far as i can tell and it came with a clean factory reset.

**Comment by arkon** [comment]
See https://dontkillmyapp.com/huawei

**Comment by Mymiano** [comment]
This more like android problem than tachiyomi. Add exception to battery saver to prevent it from killing app. Latest android had a feature that kills apps when idle to not consume resources.
