### ISSUE TITLE
Javalang. Failed bypass cloudflare

### ISSUE THREAD

**Issue by zandine** [inorichi/tachiyomi#3502]
### Device information
* Tachiyomi version:  0.9.2
* Android version:  10
* Device: realme 5 pro

## Steps to reproduce
What do you mean by this?

## Issue/Request
always failed to bypass cloudflare it said when i want to read

## Other detail
I have tried it with vpn too and didnt work

**Comment by arkon** [comment]
> What do you mean by this?

What can we do to see the same issue? 

What source is having the issue? Did you try checking in webview?

**Comment by zandine** [comment]
Mangapark and i already use webview still cant

**Comment by arkon** [comment]
Can you try in the preview build?

**Comment by arkon** [comment]
Sort of duplicate of #3511
