### ISSUE TITLE
[Feature Request] Edit Manga Title/Name in Library

### ISSUE THREAD

**Issue by oozora10** [inorichi/tachiyomi#3503]
**Why/User Benefit/User Problem**
different source sometime use different name for the same manga. it make it faster to check if that manga have been updated in other source if you have many manga in library without the need to use migrate or search which is time consuming also when it is not in library you must remeber every name which is unfriendly and because you have many manga in library when same manga have different name/title you forget it is one and the same.

**What/Requirements**
Add an option to edit manga title/name when touch hold so it keep original source name in manga info or add another tile for custom name while keeping the original name for that source if not edited in manga info.

**Comment by arkon** [comment]
#2190
