### ISSUE TITLE
[Bug] Tracking button visable when you dont have it enabled

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi#3507]
### Device information
* Tachiyomi version: r2543
* Android version: android 9
* Device: Oneplus 5t

## Steps to reproduce
1. Disable all tracking options if you have them enabled
2. Open a manga

### Expected behavior
The tracking button is not visable like it was with the tracking tab

### Actual behavior
It is visable even though tracking itself is disabled

**Comment by bbtora** [comment]
I think it should be visible and a message should be there to ask to set up tracker login in settings.
Or else, users may not even be aware in their first use.
