### ISSUE TITLE
Mangadex DNS login problem

### ISSUE THREAD

**Issue by SanOtaku09** [inorichi/tachiyomi#3508]
I am currently using tachiyomi weekly builds
And there a dns over https option
I use it because its fast but

I have problem login manga dex extension 
I have to login everything I open tachiyomi even if I marked *remember me for a year * the next time I open the app manga dex is logged out

**Comment by arkon** [comment]
DoH doesn't affect cookies. Are you manually clearing cookies?

**Comment by SanOtaku09** [comment]
Yes

**Comment by arkon** [comment]
You should stop clearing cookies if you want your session to be persisted.
