### ISSUE TITLE
Successful download doesn't clear queue

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#351]
http://mangafox.me/manga/yakushoku_distpiari_gesellshaft_blue/
I selected Download... > Download all. Download was successful, but the last chapter stayed in queue, but there was No Downloads background at the same time.
![screenshot_20160614-090523](https://cloud.githubusercontent.com/assets/1708197/16056633/aa7cfaac-3276-11e6-87c7-ea14eb82cbd9.png)
![screenshot_20160614-090527](https://cloud.githubusercontent.com/assets/1708197/16056632/aa7cc1cc-3276-11e6-8c24-592dfc34031d.png)

Version: r778

**Comment by inorichi** [comment]
It's just an UI bug, the queue is cleared.
