### ISSUE TITLE
[Bug] Tachiyomi resets page to start page and cannot advance chapters when app loses focus using splitscreen/multitask view

### ISSUE THREAD

**Issue by phauszzie** [inorichi/tachiyomi#3512]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9.0
* Device: Note 9

## Steps to reproduce
a. page reset
1. Open Tachiyomi in split screen with another app like youtube
2. Start reading any manga and read past page 1
3. Click in the other splitscreen app 
4. Click back into Tachiyomi

b. chapter advance
1. Open Tachiyomi in split screen with another app like youtube
2. Start reading any manga and read past page 1
3. Hold finger on other app to focus that app
4. Swipe through chapter in Tachiyomi with another finger to end of chapter and Tachiyomi will not advance to the next chapter even if it exists

### Expected behavior
In Tachiyomi 8.4.0 and below (not sure about 8.5.0), Tachiyomi would maintain the current page that is being read instead of resetting to the starting page.  For example if a chapter is on page 6, Tachiyomi will still be at page 6 after losing focus and coming back.   Also Tachiyomi 8.4.0 would be able to advance chapters correctly in unfocused split screen view.

### Actual behavior
If a chapter is on page 6, Tachiyomi will reset to the start page (usually pg 1) after losing focus and coming back.
Tachiyomi plays the "no more pages" animation on the in between chapter page instead of advancing chapters.  

### Other details
This was working correctly pre Tachiyomi 9.0.0

**Comment by arkon** [comment]
This is fixed for the next stable release.
