### ISSUE TITLE
[Feature Request] Adding default background image / having upload custom background option

### ISSUE THREAD

**Issue by moe-attack** [inorichi/tachiyomi#3515]
#3406 # Why/User Benefit/User Problem
- Having a background image will that suits the theme of the application / echo with the app icon can be very beneficial.
- A nice and unique background image give users more sense of belonging.
- Having the option for users to upload their own background image will increase consumer customization to the application, and make them feel more relaxed when using the app.

An example is Whatsapp, for illustration purpose.
However, users might not spend too much time in the screens with wallpaper, so I believe this feature is good to have to improve the branding of the app, but not necessary.

### What/Requirements
- Add a default background wallpaper for 'Library', 'History', and 'Browse' screen.
- Adding a 'wallpaper' row in 'Setting' -> 'General' for user to choose their custom wallpaper that shows in 'Library', 'History', and 'Browse' screen.

**Comment by arkon** [comment]
This is technically possible to add, but I don't think I would. It doesn't really seem useful enough and introduces complexity around theming/ensuring things are legible.

I know some people do some wacky stuff with modifying the app to do stuff like this though.
