### ISSUE TITLE
[Feature Request] Hide The Chapter that already Read or  Marked As Read In Updates Section

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3516]
### Why/User Benefit/User Problem
Because of Alot of Manga Updates Going on... 
I think That YOU Need to Add This Feature...

### What/Requirements
If The Chapter is Already Read in The Update Section... (MARK AS READ) 
IS THERE POSIBILITY THAT IF YOU MARK AS READ THE CHAPTER 
IT IS ALSO HIDE IN THE UPDATES SECTION....

![Screenshot_20200725_191440_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/65703094/88455809-30b32e00-ceab-11ea-9958-c11330f78a65.jpg)

If this Is Already in the Feature..

Please help...

**Comment by CarlosEsco** [comment]
#3365
