### ISSUE TITLE
[Feature Request] Allow toggling smooth scrolling in Webtoon mode

### ISSUE THREAD

**Issue by Vadigor** [inorichi/tachiyomi#3517]
**Current behaviour**: webtoon view will always use smooth scroll, "Page transitions" option is not available in webtoon view.

**Requested behaviour**: allow toggling of instant/smooth scrolling in webtoon view, similar to disabling/enabling page transitions in regular view.

**Suggested adjustment**: adjust implementation of scrollUp and scrollDown in WebtoonViewer to use scrollBy instead of smoothScrollBy depending on setting of "Page transitions". Allow said setting to be configured in webtoon view.

FWIW: I've made this change to the WebtoonViewer in my own version of the app and it seems to work fine. But I still haven't figured out how the settings really work in this app so probably won't be able to submit this change myself. 😅

**Comment by arkon** [comment]
Was already implemented in https://github.com/inorichi/tachiyomi/commit/b363b9fc1a5f3cd574bf0829d90b50319b83aeee

**Comment by Vadigor** [comment]
Ooh, thanks for this @arkon! And appreciate the link, useful to figure out how the config works. :)
