### ISSUE TITLE
Import favorites from AnilabX

### ISSUE THREAD

**Issue by VanTuz5** [inorichi/tachiyomi#3518]
This application, like yours, allows you to read manga online, but some of the sources that are available in your application for free are opened there for donation. When I found out about your application, I decided to completely switch to it, but transferring all my favorites will take a long time. So I would like to ask for a function to import favorites from that program into yours.

**Comment by arkon** [comment]
This isn't something that'd be considered for the app itself. People can write tools that work with the backup restore system though, similar to what was done for MangaRock.
