### ISSUE TITLE
Manga in multiple directories

### ISSUE THREAD

**Issue by kh0p** [inorichi/tachiyomi#352]
It's suggestion and issue I'm having: because of limited permissions (read, execute) on my `extCard` I can't pick up my directory with Manga there as download folder, so I need to use my directory on `emulated` storage (internal storage), and that's pretty uncomfortable because of lack of space in there. 

After reading I'm usually moving files from internal storage to extCard, but Tachiyomi is only looking up for manga in _Downloads directory_, so I don't have access to old ones. It would be nice if the app would support having multiple Manga directories. :four_leaf_clover:

**Comment by NoodleMage** [comment]
Duplicate #270 

> **Can you make it possible to store manga on both internal storage and external sd card?**
> At the moment, no. You could try using symlinks

**Comment by inorichi** [comment]
Can't you use the predefined folder of `extCard`? The options above "Custom directory" are for that. Those directories should be writable by the app.
