### ISSUE TITLE
[Feature Request] Searchable Settings

### ISSUE THREAD

**Issue by mpm11011** [inorichi/tachiyomi#3520]
### Why/User Benefit/User Problem
Tachiyomi has a large number of settings. It would be nice to search for a setting by name and load it's respective controller directly to that setting. That would help users find a setting that they know a keyword for, but not where it lives, which would improve speed and ease of use.

### What/Requirements
Similarly to Windows 10 settings or Android settings, you search for a setting by keyword, get a list of results, click a result, and it loads the correct page and autoscrolls right to that setting.

### Roadblocks
I can include a search icon on the SettingsMainController; clicking the icon opens up a search bar, just like LibrarySearchController or GlobalSearchController. 

[Mockups](https://imgur.com/a/Ivw62pP)

However, I see two problems from here. First, the settings names are stored in the strings.xml, so searching for a string, with a string, is not all that helpful on its own. You need to tie the string to an actual Preference object, which leads to problem number 2: The SettingsController subclasses load their Preference objects in a JSON-like collection, but the Preferences have no information as to which controller they belong to. You need to go from Preference objects in your search results to the correct SettingsController subclass to load. 

I am completely new to Kotlin but I would be happy to contribute to the effort.

**Comment by arkon** [comment]
> The SettingsController subclasses load their Preference objects in a JSON-like collection,

The "JSON"-ness is just syntactic sugar. They're still regular old `Preference` objects.

> but the Preferences have no information as to which controller they belong to.

This is indeed an issue.

I know there's library like [SearchPreference](https://github.com/ByteHamster/SearchPreference), but those are based on XML preferences, but Tachiyomi defines them programmatically. My initial thought would be to do some codegen on build to create mappings of preference title strings -> the controller class and the search functionality would do a lookup based on that.

**Comment by mpm11011** [comment]
I had considered using reflection on the controllers to do that lookup , but I'm not sure that would work since the preferences are set up in the setupPreferenceScreen function, they're not properties or members of the class itself.

**Comment by lmj0011** [comment]
>I can include a search icon on the SettingsMainController; clicking the icon opens up a search bar, just like LibrarySearchController or GlobalSearchController.

@mpm11011 
If you want to go ahead and start a PR, I can look into what arkon is suggesting. I too think this is a good thing to have implemented

>My initial thought would be to do some codegen on build to create mappings of preference title strings -> the controller class and the search functionality would do a lookup based on that.

**Comment by mpm11011** [comment]
I'll start a PR, but fair warning that my code doesn't provide much of a foundation to build on. The only thing it can do right now is display the mockups I posted earlier. But I guess we'll see where it goes.
