### ISSUE TITLE
[Feature Request] Downloading all library

### ISSUE THREAD

**Issue by RickAsley** [inorichi/tachiyomi#3523]
### Why/User Benefit/User Problem
(explain why this feature should be added)
I added a big list of mangas to my library and categories and wanted to download them all so i can have them in the go, but currently i have to open each one and go to chapters and download all and do that for them one by one
### What/Requirements
(explain how this feature would behave)
when selecting multiple items in the library list at the top there should be a button next to select all that is download all

Thanks

**Comment by CarlosEsco** [comment]
Already exists in preview and will be in next stable
