### ISSUE TITLE
[Feature Request] Jump To Top Button

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3526]
I've been Thinking lately.. I think that It is Good to Add The Jump to Top button.. 

### Why/User Benefit/User Problem
Sometimes We Scroll down to see the Bottom Of the Chapter.. And Scroll back...
Or It is Just me...

**Comment by vengiare** [comment]
Isn't there a fastscroller already for fast navigation?

**Comment by ImPudding-tech** [comment]
Ok thanks!
