### ISSUE TITLE
[Feature Request] Different Save location

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3530]
When Saving A Photo.. 
Separate the Saving Location Per Manga... 
If You Save A Picture From Food wars
. It will go to the Food Wars Folder..

**Comment by scb261** [comment]
If I understood you correctly, each manga already has its own folder

**Comment by scb261** [comment]
Oh, you probably using save from long tap dialog. I guess this option is for cases when you want exactly this page, I don't think many people use it. Right way to download chapters is on manga page. Open manga -> click on download button -> choose what chapters you want. Or long press a chapter and click on download button

**Comment by arkon** [comment]
The filename already includes the manga name.
