### ISSUE TITLE
[Bug] Japanese sources are only available when app language is set to Japanese

### ISSUE THREAD

**Issue by kondanta** [inorichi/tachiyomi#3531]
Note: I don't know whether this is a bug or not but its behavior is unexpected for me. Thus the bug report.

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Samsung J2 Prime

## Steps to reproduce
1. Enable FMReader while app's language is English(US)
2. Go to Browse tab
3. Select Sources

### Expected behavior
I should see English sources as well as the Japanese ones.

### Actual behavior
I can only see English sources. When I change app's language to Japanese, I can see both English and Japanese sources.

### Other details
Additional details and attachments.
![](https://i.imgur.com/xypRz0v.jpg)

![](https://imgur.com/s1QpCCs.jpg)

**Comment by arkon** [comment]
Enable Japanese in the filter menu from the top right.

**Comment by kondanta** [comment]
Thanks, it worked.
