### ISSUE TITLE
[Bug] Download won't start

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi#3532]
### Device information
* Tachiyomi version: r2569
* Android version: 6.0.1
* Device: VIVO Y53

### Expected behavior
Downloads will automatically start

### Actual behavior
Download won't start even if I've toggle resume multiple times. This happens in any extension I have. It just won't start.

### Other details
My wifi connection doesn't seem to be the problem, my storage has space, and the app is up to date.

**Comment by arkon** [comment]
Does it work with r2543?

Old versions: https://tachiyomi.kanade.eu/

**Comment by cievee** [comment]
No it doesnt work too, before i updated to r2569 the download works fine

**Comment by arkon** [comment]
What were you using before?

**Comment by cievee** [comment]
I think its r2493

**Comment by arkon** [comment]
Can you verify that you have the issue starting with r2511?

**Comment by arkon** [comment]
Duplicate of #3564, I think.
