### ISSUE TITLE
[Feature Request] Extension search update for Multiextension

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#3534]
### Why/User Benefit/User Problem
It would make possible to search an extension if it is part of a multiextension, since this isn't supported now.

### What/Requirements
When searching for a source to install, if part of a multiextension, it would point to it/them telling the user that there is a source with similar/equal name in it.
Example: Search "mangak", it would point for MangaBox since **mangak**akalot is in it.

**Comment by arkon** [comment]
#3338
