### ISSUE TITLE
[Feature Request] Zoom in instead of cropping

### ISSUE THREAD

**Issue by scb261** [inorichi/tachiyomi#3535]
### Why/User Benefit/User Problem
Cropping doesn't work ideally and sometimes crops more than needed. In most cases it's just few letters, but sometimes pages are cropped almost entirely, here is example: [with](https://imgur.com/fCQUvKQ) and [without](https://imgur.com/9KM8mou) cropping (it's the same page). Ar first I thought that the source have the same pages and I just skipped them, but then I encountered them more on different sources. It's troublesome to disable and enable cropping each time, would be easier just zoom out or move page a little bit.

I'll also mention that it's not rare to see pages that have white borders but aren't cropped (probably some noise that human eye can't see), so changing threshold wouldn't help much. Would be better to improve detecting borders, but I'm not sure that someone will do it.

### What/Requirements
Option in setting for scaling instead of cropping. I'm not sure about webtoon and continuous vertical, but for LTR, RTL and vertical this should be possible. Can be inconvenient for users who scroll by dragging, so it should be an option.

**Comment by CarlosEsco** [comment]
Just turn off cropped borders.  It's looking for black outlines like a normal manga page. Since these are yellow it's failing.

**Comment by arkon** [comment]
Zooming wouldn't really be any different if the border detection is still the same, wouldn't it?

**Comment by vengiare** [comment]
I think the idea is you can zoom out when border detection fails, but this will only make sense if the scaling is Fit width or something.

**Comment by scb261** [comment]
> Just turn off cropped borders. It's looking for black outlines like a normal manga page. Since these are yellow it's failing.

But then I need to turn in on because text is too small, so each time turn it on/off

> I think the idea is you can zoom out when border detection fails, but this will only make sense if the scaling is Fit width or something.

Yes, exactly. In my case it's fit screen

**Comment by scb261** [comment]
Maybe just add option to Scale type for this

**Comment by vengiare** [comment]
"Zoom to content"-like scaling type, huh. It's a weird option, I think.

**Comment by scb261** [comment]
> It's a weird option, I think.

It removes unnecessary white borders so it's easier to read small text while whole page still visible on screen, just like the crop borders option. But it's easier to handle wrong cropping by simple zooming out instead of going to setting, searching the cropping option and disabling it and repeat to enable it again.

**Comment by vengiare** [comment]
Yeah, I know. I literally said that, but shorter.

> I think the idea is you can zoom out when border detection fails

**Comment by arkon** [comment]
So I'm basically just going to say this isn't going to happen since it's non-trivial.

There are some other open issues for improving the actual cropping though like #3290
