### ISSUE TITLE
Migrate sometimes bugged (preview)

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#3536]
### Device information
* Tachiyomi version: Preview r2569
* Android version: 10
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Search the manga I show in the attachments, it is found in both Mangadex and Mangakaklot
2. Try to migrate from Mangakakalot, it doesnt find the one on Mangadex (same the other way around).

## Issue/Request
Migrate sometimes is bugged and won't find the manga in other sources even if they are there.

## Other details
![Screenshot_20200729-022404_Tachiyomi](https://user-images.githubusercontent.com/22413659/88742973-dd0f4180-d143-11ea-9811-3a60d40b86b6.jpg)
![Screenshot_20200729-022411_Tachiyomi](https://user-images.githubusercontent.com/22413659/88742982-e1d3f580-d143-11ea-8297-39031482a9d5.jpg)

**Comment by scb261** [comment]
It's because of the word **bizarre**. You can edit search when migrating (at least in 0.9.2)
