### ISSUE TITLE
[Bug] Manga Search Across Extensions won't work

### ISSUE THREAD

**Issue by baileywailey** [inorichi/tachiyomi#3538]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Galaxy S10+

## Steps to reproduce
1. Open app to browse tab
2. Tap search bar and search for any manga

### Expected behavior
The manga will be listed from each extension that you have downloaded

### Actual behavior
The app doesn't load anything and displays a blank page with the search on the top.

### Other details
Additional details and attachents
![Screenshot_20200730-093048_Tachiyomi](https://user-images.githubusercontent.com/68994495/88928973-76734c00-d247-11ea-8e00-96a2fc9448b9.jpg)

**Comment by arkon** [comment]
You probably turned on the setting to only search pinned sources but didn't pin any sources.

Either turn off the setting or pin some sources.

**Comment by baileywailey** [comment]
That was it! Thank you so so much!

**Comment by joseph619** [comment]
Maybe an error message could help here to warn users about the issue?

**Comment by baileywailey** [comment]
I feel it would be helpful or even a patch note about it. I don't recall opening that setting, but that's not to say I didn't.

**Comment by arkon** [comment]
> Maybe an error message could help here to warn users about the issue?

Already addressed for the next release.
