### ISSUE TITLE
[Bug] <work up this morning to my whole library gone>

### ISSUE THREAD

**Issue by food8888** [inorichi/tachiyomi#3539]
---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Samsung A8

## Steps to reproduce
1. Opened the app
2. Library and updates gone

### Expected behavior
There should have been library when I open the app

### Actual behavior
No library 

### Other details
I dont know what happened, I installed the update for the app yesterday and it was fine, when I woke up this morning my entire library was empty, I tried uninstalling and reinstalling the app but that didnt work. It still had all my manga extensions and I can still read but the library is still gone.

**Comment by StevenPss** [comment]
Which version of the app were you using before the update to **0.9.2**? and did you try to reproduce this issue from a different device?

**Comment by arkon** [comment]
Sounds like something wiped or corrupted the database. Unfortunately not much we can do for that, but we have heard of that sometimes happening for people on lower end devices or having cleaner apps aggressively destroying app data.
