### ISSUE TITLE
[Feature Request] <Compress Downloaded chapters>

### ISSUE THREAD

**Issue by firestone211** [inorichi/tachiyomi#3543]
I don't know why but a page of manga that is around takes 256KB of data only around 75KB are for the actual .PNG file itself. And since there are around ~30 .PNG files in a chapter with 10 chapters you can compress ~73MB of files from taking up ~84MB to ~74MB. 

TLDR: Compressing chapters or entire mangas to ZIP can drastically save storage

So somewhere on the menu(where you can delete chapters, refresh tracking, mark all as read, etc.) You can add another option to compress and uncompress the manga or maybe the individual chapters. Currently you can do this by compressing the manga manually using a file manager in Android, store it some where, then uncompress it back into the folder. Using this method the chapters can be read offline, but the icons greenshow that it is not downloaded when it is downloaded and stay blue. To fix this you jyst need to force close the app then reopen it to fix the issue.

**Comment by scb261** [comment]
#918 is the same
