### ISSUE TITLE
[Feature Request] <To edit the manga >

### ISSUE THREAD

**Issue by Vvale69** [inorichi/tachiyomi#3546]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Why/User Benefit/User Problem
(To add or remove duplicated or missing chapters./For the user to read without switching sources./Problem is some chapters are duplicated or missing to some sources like MANGA DEX most are duplicated and most are missing

### What/Requirements
(To just remove or add A chapter to an existing manga/comic)

**Comment by CarlosEsco** [comment]
Not happening the whole idea is the entries match the website.  Use a different source, or use local manga if you want to customize chapters
