### ISSUE TITLE
[Feature Request] Locking the menu when scrolling

### ISSUE THREAD

**Issue by Amazingduf** [inorichi/tachiyomi#3547]
Hello, thank you for your hard work

so when I'm reading webtoon or in continuous vertical mode, while scrolling through the pages, I find myself placing my finger on the screen all the time which always prompt the menu (because I long tap the screen), it always keeps happening and the menu keeps popping out (this set as cover, download, share menu)

so can you change this long tap menu gesture or make a feature to lock/unlock the menu when scrolling on webtoon mode ? something like that

thank you

**Comment by scb261** [comment]
More -> Setting -> Reader -> Long tap dialog

**Comment by Amazingduf** [comment]
> More -> Setting -> Reader -> Long tap dialog

thank you
