### ISSUE TITLE
[Feature Request] Option to revert webtoon tap navigation to left/right tap

### ISSUE THREAD

**Issue by TigerUppercut** [inorichi/tachiyomi#3551]
The recent update has changed the webtoon tap navigation to top/bottom tapping to progress pages, where before it was left/right tapping. Can an option be added to change back to the left/right tap navigation? It is very useful for tablet usage, as you can navigate with the hands that are already holding the tablet on the left and right sides, and the new method makes navigating webtoons very cumbersome.

Thanks!

**Comment by BearCooper** [comment]
Yes please. It's very awkward on a tablet.

**Comment by Code027** [comment]
Also would like it to revert back. I usually tap on the lower half of my screen to access what is now the middle tap and now the pages progresses.
