### ISSUE TITLE
[Feature Request] Remember state for manga description (expand/collapse) after exiting view 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3554]
Requested by Diskkk#2694 on Discord. Posted under Feature Request since unsure if it's a bug or intended behaviour.

### Why/User Benefit/User Problem
Currently when expanding manga description by clicking More chip, it resets to being minimized after exiting info screen.

### What/Requirements
App will remember the expand/collapse state of manga description for all manga in Library.

**Comment by arkon** [comment]
It's automatically expanded if opened via Browse and automatically collapsed if opened via the Library/Updates/History.

The reasoning is that you likely wouldn't need to read the full about content if you've already favourited something.
