### ISSUE TITLE
[Feature Request] <Light Novels reading or downloading sources>

### ISSUE THREAD

**Issue by UNRIVALLEDKING** [inorichi/tachiyomi#3557]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.1)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Why/User Benefit/User Problem
I want to read light novels but can find any best source. So, please add light novel reading or downloading sources too

### What/Requirements
Please add light novels reading and download feature.

**Comment by CarlosEsco** [comment]
Light novels are not planned to be supported. This is an image reader not a text one

**Comment by arkon** [comment]
Novels and manga are not related enough to be in this app.
