### ISSUE TITLE
[Bug] Selected table cells in manga view are not distinctly visible when using AMOLED theme on AMOLED device

### ISSUE THREAD

**Issue by buitim** [inorichi/tachiyomi#3558]
### Device information
* Tachiyomi version: Preview r2601 (0d15cbe3)
* Android version: Android 10 - MIUI 12.1
* Device: Xiaomi Mi 9T

## Steps to reproduce
1. Open app
2. Change to AMOLED black theme
3. Select manga
4. Tap and hold on a table view / recyclerview cell to bring up select options.
5. Tap a few of the cells
6. Check if selected cells are distinctly visible from the cells that are not selected.

### Expected behavior
Selected cells are distinctly visible

### Actual behavior
On an AMOLED display, it is very hard to make out which cells are selected.

![image](https://user-images.githubusercontent.com/29244321/89115658-c452a480-d43f-11ea-848c-8af99aabdbda.png)

### Other details
Selected cells are visible on a non-AMOLED screen. I quickly tested this by opening the above screenshot on two different AMOLED devices and on my desktop with a non-AMOLED display.

**Comment by arkon** [comment]
Are you using a custom theme on your device (e.g. through the Xiaomi theming store thing)?

**Comment by hXtreme** [comment]
Couldn't reproduce on Pixel 3.

**Comment by buitim** [comment]
@arkon i am not but you reminded me of something that MIUI does in version 12. By default, when dark mode is enabled, it tries to darken all apps for you. I went into settings, disabled dark mode for Tachiyomi, and now it works beautifully. Apologies for the trouble and thanks for the help y'all.
