### ISSUE TITLE
[Bug] Download won't start

### ISSUE THREAD

**Issue by imKenjo18** [inorichi/tachiyomi#3559]
---

### Device information
* Tachiyomi version: 0.10.1
* Android version: 8.1
* Device: vivo 1811

## Steps to reproduce
1. Find any manga
2. Download a chapter or more

### Expected behavior
It should download normally.

### Actual behavior
Right away it says download complete and a download error.

### Other details
![Screenshot_20200802_130815](https://user-images.githubusercontent.com/69100133/89116094-b98d2380-d4c2-11ea-8a45-85a82daf9017.jpg)

**Comment by imKenjo18** [comment]
Turns out it works if I use the default Download path but not on my sd card

**Comment by scb261** [comment]
You shouldn't close it, it is bug. I'm also having it after update. At first I thought that mangadex is still down, but now I also cannot download from other sources
