### ISSUE TITLE
Error after clear database

### ISSUE THREAD

**Issue by Gilfar** [inorichi/tachiyomi#356]
1. Check a manga so it loads chapters.
2. Go to Settings > Advanced and Clear database
3. Go back and select the same manga
4. You get error during Put operation

If the Catalogue view is refreshed everything works.
Most likely if not refreshed it is using the old database.

**Comment by inorichi** [comment]
Makes sense, because those don't exist anymore. A quick fix would be to recreate the activities' stack when clearing.
