### ISSUE TITLE
[Feature Request] Webnovels support

### ISSUE THREAD

**Issue by natintosh** [inorichi/tachiyomi#3560]
I acknowledge those clauses 

---

### Why/User Benefit/User Problem
I think it would be nice if I can read my favourite Webnovels with Tachiyomi... Or could you d a spin off from Tachiyomi for Webnovels. I think it would the great

### What/Requirements
- Add plugins for Webnovels
- Add support for Webnovels

**Comment by scb261** [comment]
#3557
