### ISSUE TITLE
[Bug] Source with different languages

### ISSUE THREAD

**Issue by psychopomp9** [inorichi/tachiyomi#3562]
### Device information
* Tachiyomi version: 0.10.1
* Android version: 9
* Device: Redmi Y2

### Expected behavior
Sources which have more than one language should only be active for selected language (as per previous version)
Which is app Language.

### Actual behavior
Active for all languages

### Other details
In last version of Tachiyomi, sources are shown only for the application language, but now it's showing every single language and it's enabled rather than disabled so I've to disable them one by one! It might because of the application version update

**Comment by arkon** [comment]
> but now it's showing every single language and it's enabled rather than disabled so I've to disable them one by one!

No it's not, I just verified with a fresh install. You must've toggled them at some point.
