### ISSUE TITLE
[Bug] Overlapped Android's gestures Pill bar and Tachiyomi's chapter progress number indicator 

### ISSUE THREAD

**Issue by FrostedIce339** [inorichi/tachiyomi#3563]
### Device information
* Tachiyomi version: Version 0.10.1
* Android version: Android 10
* Device: Motorola One Power

## Steps to reproduce
Please have the gesture navigation enabled

1. Open a manga chapter
2. Click on the "Custom filter" icon at the top right corner
3. Observe at bottom of the screen that the 'pill bar' of Android 10 System Gestures Navigation is overlapping with the Tachiyomi's chapter progress numbers indicator like `2/30` (please see the screenshot¹ for clarification)

### Expected behavior
This should happen.

### Actual behavior
The pill bar of Android 10 shouldn't overlap with Tachiyomi's chapter progress numbers like `2/30`
  

### Other details
Additional details and attachments.

![Screenshot_20200802_121933](https://user-images.githubusercontent.com/69083746/89117503-e38f1780-d4bb-11ea-8a17-544e29d6b4b0.jpg)

___

Furthermore I also see that the pop-up that let's us know what Reading mode we are in seems to be also overlapping, for example Vertical pop-up appears that appears when the Reading mode is set to Vertical with the chapter progress number indicator.

## Steps to reproduce

1. Open a manga chapter
2. Observe at the bottom of the display of overlapped toast message and Tachiyomi's chapter progress number indicator.

Let me know if I should open a new issue for this. 

![Screenshot_20200802_122029](https://user-images.githubusercontent.com/69083746/89117599-ad05cc80-d4bc-11ea-96a7-e3dfc47cbc1a.jpg)

___

Here's another glitch: 

![Screenshot_20200802-141622](https://user-images.githubusercontent.com/69083746/89119295-e6453900-d4ca-11ea-822b-3b903cd235bf.png)

___

**Screenshot¹:**
![Screenshot_20200802_123454](https://user-images.githubusercontent.com/69083746/89117606-c3ac2380-d4bc-11ea-9b7a-235a1fe4a712.jpg)

**Comment by arkon** [comment]
Not really bugs.

1. A side effect of the navbar being translucent when a sheet is opened.
2. Snackbars can cover content temporarily; i.e. it's intentional.
