### ISSUE TITLE
[Bug] Download won't start when SD card is chosen

### ISSUE THREAD

**Issue by scb261** [inorichi/tachiyomi#3564]
### Device information
* Tachiyomi version: 0.10.1
* Android version: 5.1
* Device: Huawei TIT-U02

## Steps to reproduce
1. Select SD card as download location.
2. Choose any manga and try to download it.

### Expected behavior
Download starts.

### Actual behavior
Download won't start and 2 notifications are shown: unexpected error and download complete.

### Other details
Same issue were opened, but closed by the author #3559. Here is video if it helps https://youtu.be/JGb2SDRRuXg

**Comment by arkon** [comment]
Please provide logcats.

**Comment by scb261** [comment]
I hope I did it right [logcat_08-02-2020_17-09-20.txt](https://github.com/inorichi/tachiyomi/files/5012267/logcat_08-02-2020_17-09-20.txt)

**Comment by arkon** [comment]
That doesn't seem to include anything about Tachiyomi.

**Comment by scb261** [comment]
Ok, I think I got it now [logcat_08-02-2020_17-33-17.txt](https://github.com/inorichi/tachiyomi/files/5012298/logcat_08-02-2020_17-33-17.txt)

**Comment by toshiro9117** [comment]
i got the same problem too when i updated tachiyomi to version 0.10.1

**Comment by arkon** [comment]
Logs weren't useful, but I reproduced it on an old phone that has an SD card slot.

It seems like if you choose the default SD card location from the setting, it works fine. It fails if you choose a custom location. Can you guys confirm?

**Comment by scb261** [comment]
If you mean second option in Download location, then it works fine (but is it really SD card?). If root of SD card - bug is still there

**Comment by arkon** [comment]
Interesting, no.

My test device shows something like `/storage/extSdCard/Android/data/eu.kanade.tachiyomi/files`.

Regardless, since I reproduced it I can work on fixing it.

**Comment by scb261** [comment]
Am I correct that stable version won't have fix for the bug any time soon? I guess I'll switch to preview when it will be fixed.

Also, I see that you added fix for "Download complete" notification in case of an error, it also appears when you cancel download and nothing was downloaded.

**Comment by arkon** [comment]
> Am I correct that stable version won't have fix for the bug any time soon? I guess I'll switch to preview when it will be fixed.

I'll release something within the next day or two with other bug fixes.

**Comment by scb261** [comment]
I just misunderstood the milestone. Thanks
