### ISSUE TITLE
[Feature Request] Option to not have downloading complete notification

### ISSUE THREAD

**Issue by taksaru** [inorichi/tachiyomi#3566]
### Device information
* Tachiyomi version: 0.10.1
* Android version: 10
* Device: OnePlus6T

## Steps to reproduce
1. Download Manga

## Issue/Request
When a download completes a notification remains saying so. Can we get an option to turn this off? 

## Other details
Additional details and attachments.

**Comment by pervertkirito** [comment]
more > settings > general > manage notifications

**Comment by taksaru** [comment]
D'oh sorry
