### ISSUE TITLE
[Bug] Sort by "Date Added" not working in descending order.

### ISSUE THREAD

**Issue by neiloweeen** [inorichi/tachiyomi#3567]
### Device information
* Tachiyomi version: 0.10.1
* Android version: 6
* Device: Redmi 3s Prime

## Steps to reproduce
1. Open library
2. Open sort menu
3. Tap on "sort by date added"
4. Try to change ascending order to descending order.

### Expected behavior
Newly added manga should appear first.

### Actual behavior
No change. Oldest added manga persist at the top.

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
It only applies to things added after the update.
