### ISSUE TITLE
[Bug] <Library crash update>

### ISSUE THREAD

**Issue by MrKJReyes** [inorichi/tachiyomi#3570]
### Device information
* Tachiyomi version: 10.1
* Android version: 5.1.1
* Device: Oppo A37

## Steps to reproduce
1. Open Tachiyomi application
2. Click update library
3. Check notification then every manga should update alphabetically.

### Expected behavior
Updating the manga

### Actual behavior
Closing the app and still crushing when I uninstalled it and install it. 

### Other details
When I restore my data it's still crashing and when I open the browse and click mangafreak (Extension that I installed), the application are closing or crashing.

**Comment by arkon** [comment]
Provide logcats, otherwise there's no way I can tell why it's crashing.

Refer to this guide: https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android

**Comment by MrKJReyes** [comment]
And also I can't restore every manga and manhwa that I downloaded.

**Comment by arkon** [comment]
As I commented before, you must provide logs.

**Comment by MrKJReyes** [comment]
It seems like mangafreak is the one who causing the problem.

**Comment by arkon** [comment]
Please comment on the issue with actual logs and I'll reopen it. This is unactionable otherwise.

You most likely do not have a valid Webview provider on your device and it's failing the Cloudflare bypass.
