### ISSUE TITLE
[Bug] <Write short description here>

### ISSUE THREAD

**Issue by Gladius-007** [inorichi/tachiyomi#3572]
### Device information
* Tachiyomi version: 0.10.1
* Android version: 10
* Device: Resmi k20 pro

## Steps to reproduce
1. N/a

### Expected behavior
All the chapters of the manhwa should be visible.

### Actual behavior
It's showing 0 chapters.

### Other details
![Screenshot_2020-08-02-22-54-20-692_eu kanade tachiyomi](https://user-images.githubusercontent.com/69119040/89128593-588e3b80-d514-11ea-8331-ce75620bcfbc.jpg)

**Comment by scb261** [comment]
Seems to be the same as #3552, already fixed, wait for next release within day or two
