### ISSUE TITLE
[BUG] Frequent broken/corrupted images

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#3573]
### Device information
* Tachiyomi version: 0.10.1-2601 (standard, 0d15cbe3, 47)
* Android version: 10 (SDK 29)
* Device: Pixel 3

## Steps to reproduce
1. Open a chapter for reading.
2. Either some of the images are corrupted or try again with a new chapter.

## Issue/Request
Corrupted images load frequently (about once or twice in every 30 chapters).

## Possible resolutions
1. Add integrity checks when loading images and automatically re-download image on failure (probably requires source to provide file hash or checksum)
2. Add a reload button in manga viewer to allow user to manually re-download the image.

## Other details
I mostly use Mangadex and have thus noticed it mostly with chapters from mangadex. These chapters load perfectly fine when using the website.

_(please wait I'll attach example images)_

**Comment by hXtreme** [comment]
The following images were saved using the in-app save image option.

![Orenchi ni Kita Onna Kishi to_ Inakagurashi suru Koto ni Natta Ken - Ch 49 - Disagreement - 11](https://user-images.githubusercontent.com/22425371/89131143-3d2d2b80-d528-11ea-8c92-da70805bab09.jpg)

![Orenchi ni Kita Onna Kishi to_ Inakagurashi suru Koto ni Natta Ken - Ch 49 - Disagreement - 12](https://user-images.githubusercontent.com/22425371/89131146-3f8f8580-d528-11ea-9ad1-1e84216bbff4.jpg)

**Comment by arkon** [comment]
Do you see it in other sources? Seems like you're just hitting bad MD@Home nodes.

**Comment by scb261** [comment]
I also had this once before on 0.9.2, but it was only one image. Don't remember what source it was

**Comment by hXtreme** [comment]
I might've encountered it once with Bokuben on MangaPlus (can't be super sure if it was this problem because it happened over a month ago but I do recall that I had to go read a chapter from the website because of some issue).

@arkon you could be right though that I might just be hitting bad MD@home nodes but I guess a reload button should then resolve it right (shouldn't be too likely that I got a bad node multiple times in a row)

**Comment by hXtreme** [comment]
Clearing chapter cache doesn't work, I get the exact same corrupted image if I reopen the chapter after clearing the cache.

**Comment by vengiare** [comment]
I've only encountered something like this probably only two or three times in a manga cover—which I usually just pull down to refresh, to fix it. (0.9.2)

Weird that you're getting the same corrupted image after clearing cache tho.

**Comment by hXtreme** [comment]
@vengiare I've also had problems with cover image but as you said, refreshing it (once or twice) resolves it.

Next time I encounter this problem I'll try clearing cache from phone settings.

**Comment by joseph619** [comment]
One user got a corrupted image

Source - Mangadex
Manga - The villainess reverses the hourglass
Chapter -  42
Page - 14

**Comment by Celestialcelery** [comment]
I cleared chapter cache and app cache. I refreshed as well, but problem persists. Only for mangadex source.

**Comment by hXtreme** [comment]
@Celestialcelery for now the work around is to close the app, go into the settings on your phone > app > Tachiyomi > Clear cache.

**Comment by Celestialcelery** [comment]
@hXtreme yes, that's what I did. the chapter still showed up as half loaded/grayed out. Normally happens on the last page transitioning to the credit page.

**Comment by scb261** [comment]
Seems to be MD problem on their side. If you removed chapter, cleared cache and it didn't help, then go to extension settings and change image server, it helped one user on discord.

**Comment by scb261** [comment]
Users keep asking about this problem on discord and it's MangaDex all the time, so I guess the issue can be closed. For anyone finding this issue in future: 
1. Remove chapter with the problem if it was downloaded.
1. Clear cache: *More > Settings > Advanced > Clear chapter cache*.
1. Change image server: *Browse > Extensions > Mangadex > gear button beside your language > Image server*.

**Comment by hXtreme** [comment]
@scb261 clearing cache from within the app doesn't work for go. Can you update the instructions to ask users to clear the cache from their phone's settings.

**Comment by hXtreme** [comment]
(Closing as it seems like it's a Mangadex issue)

**Comment by scb261** [comment]
Users on discord didn't have problem after clearing cache in the app and changing image server. Also looking at the conservation above it doesn't look like clearing cache from phone settings helps
