### ISSUE TITLE
[Bug] The app crashed

### ISSUE THREAD

**Issue by lilmochi98** [inorichi/tachiyomi#3576]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extension

---

### Device information
* Tachiyomi version: v.0.10.2
* Android version: 6.0
* Device: Moto g3

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
open the app and make it work

### Actual behavior
the app does not open freezes in the logo

### Other details
This has never happened to me but today I updated the app and now the app doesn't work for me

**Comment by jobobby04** [comment]
Uninstall the KuManga extension in your phones settings, it updated and is now causing issues

**Comment by lilmochi98** [comment]
yes it was that Thank you
