### ISSUE TITLE
[Bug] <Filter Options Keep Disappearing>

### ISSUE THREAD

**Issue by CarlyBurnsAll** [inorichi/tachiyomi#3577]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 0.10.2
* Android version: 10
* Device: Samsung Galaxy Note 9

## Steps to reproduce
Happens randomly and filter menu is gone more often than being there.

### Expected behavior
Each extensions filter menus should show up when pressing an extension.

### Actual behavior
If a filter option is avaliable when entering an extension, backing out and clicking the same extension or any other extension removes the filter menu.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
You are only clicking the text of the extension and not mistakenly clicking the latest button correct?

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi-extensions/issues/3993

**Comment by CarlyBurnsAll** [comment]
Thank you for the help. My apologies over tbe confusion.
