### ISSUE TITLE
[Feature Request] <Webtoon old tab navigation >

### ISSUE THREAD

**Issue by iAdoly** [inorichi/tachiyomi#3578]
### Why/User Benefit/User Problem
(explain why this feature should be added)
 Make it more Comfortable to navigate with larger display. 
### What/Requirements
(explain how this feature would behave)
Just get it back from older versions.

**Comment by scb261** [comment]
Do you mean ta**p** as in #3551?

**Comment by CarlosEsco** [comment]
Reopen if the above is not what you wanted
