### ISSUE TITLE
[Localization/Weblate] Remove Tagalog localization

### ISSUE THREAD

**Issue by mr26th** [inorichi/tachiyomi#3579]
## Issue/Request
**Note: I have omitted the other details needed (like Android version and steps to reproduce stuff) since I believe that this issue does not need that.)**

Hello devs!

I 'm the one who is translating the app into the Filipino language. I initially added Tagalog since I didn't know at that time that Weblate supports Filipino. Since Tagalog is basically the same as Filipino, I went ahead and add that, only to found out that the latter is supported.

Since then, I only translate the strings into Filipino. Tagalog is there but I haven't touch ever since. I initially thought to delete Tagalog by myself but I have found no ways for me to do it, so I guess it might be a developer/admin-level task.

I have found a way involving VCS, but I'm a foreigner to that.

I'm sorry if this is not the place for this matter.

**Comment by arkon** [comment]
Thanks, I'll remove it from the app.

I've also asked @j2ghz to remove Tagalog from Weblate.
