### ISSUE TITLE
Feature Request: Route / Proxy

### ISSUE THREAD

**Issue by VirusEcks** [inorichi/tachiyomi#358]
as lot of isp offer custom free website / domain for their users
can you add a route or api that can be used to forward / route / proxy the requests that the app requires so that all data is through that host/web address/ etc, using java or php to be added to that webhost or address.

it would be good for me not to be charged for the downloads or manga i browse while not on wifi

thanks for the great app

**Comment by inorichi** [comment]
There are already plenty of options to route your traffic in the store. I don't see any need to implement this
