### ISSUE TITLE
[Bug] <library update nofications doesn't get removed after finishing>

### ISSUE THREAD

**Issue by sohilsayed** [inorichi/tachiyomi#3581]
### Device information
* Tachiyomi version : latest dev app
* Android version: 8
* Device: sony xa1 ultra

## Steps to reproduce
1. START updating the library
2. The app update all titles

### Expected behavior
The library update nofication gets removed

### Actual behavior
The library update nofication doesn't get removed and shows that it's still updating last title in the list

**Comment by arkon** [comment]
I can't reproduce this.
