### ISSUE TITLE
[Feature Request] Filter to see manga without source (extension uninstalled)

### ISSUE THREAD

**Issue by scb261** [inorichi/tachiyomi#3582]
### Why/User Benefit/User Problem 
When user uninstall an extension, he can forget about manga from it. Would be good to have a way to see such manga. (Also helps when SY changes internal sources to delegated and you need to see manga that doesn't have source now since source id changed, but I think this feature should be on main app too, so I'm creating the issue here)

### What/Requirements
I don't think it should be an option in filter, maybe just search by keyword 'unknown status' just like by source name

**Comment by arkon** [comment]
You can view it from the migration list.

**Comment by scb261** [comment]
Oh, you right, didn't see it. But sure if my suggestion still should be implemented

**Comment by arkon** [comment]
I still don't see it being a valid usecase.

If the motivation is to see what's been orphaned by a lost source, the list in migration serves that purpose well. 

If the motivation is to just filter the library by a particular lost source, you can search for the ID number already as you mentioned on Discord.
