### ISSUE TITLE
[Feature Request] Add an option to disable both top and bottom toolbars from collapsing when scrolled

### ISSUE THREAD

**Issue by calvinize** [inorichi/tachiyomi#3583]
### Why/User Benefit/User Problem
Sometimes it's kind of annoying to have the toolbars collapsing when I'm just going through my library and suddenly wanted to search for a manga, filter my library, or browse for more manga in the Browse tab.

### What/Requirements
A toggle in the Settings page so those who would like to disable the feature can do so.

**Comment by arkon** [comment]
#3392 for bottom.

I'd say no to the top one, you can just scroll up a bit.

**Comment by calvinize** [comment]
Umm according to that I have to change the items per row to something larger than 3, but changing it to 5 or even 6 the bottom toolbar still collapses on scroll.

**Comment by arkon** [comment]
It's an open issue so it hasn't been addressed.

**Comment by calvinize** [comment]
Ah I see. I thought you were saying that I had to follow the instructions in that thread. My bad.

Cool then hopefully it will be addressed soon.
