### ISSUE TITLE
[Bug] Adding to library

### ISSUE THREAD

**Issue by qoro** [inorichi/tachiyomi#3585]
Just found a design flaw in 
App version: 0.10.2 (standard, cdbefd919, 48)
Android version: 10 (SDK 29)
Android build ID: 00WW_4_15F
Device brand: Nokia
Device manufacturer: HMD Global
Device name: PL2_sprout
Device model: Nokia 6.1
Device product name: Plate2_00WW

I clicked on download but I didn't have the manga added to any library and when it asked me to add it in the bottom I could not click on add because of the resume button. I had to scroll down a little so I could see the 'add' option and click on it with my other finger. 
It's not really a bad issue, just a small detail.
![Screenshot_20200803-213936](https://user-images.githubusercontent.com/68406310/89221710-cf930500-d5e4-11ea-9cbf-8628b6957b66.png)
![Screenshot_20200803-213951](https://user-images.githubusercontent.com/68406310/89221712-d0c43200-d5e4-11ea-9792-a4f8cf10472b.png)

**Comment by arkon** [comment]
Was fixed in 0.10.3.
