### ISSUE TITLE
[Bug] Fullscreen is overlayed

### ISSUE THREAD

**Issue by diggtrap** [inorichi/tachiyomi#3586]
### Device information
* Tachiyomi version: v0.10.3
* Android version: 8.1.0
* Device: Moto G5 Plus

## Steps to reproduce
1. Open any manga chapter, make sure "Fullscreen" option is enabled
2. Tap screen to access chapter options

## Issue/Request
Android taskbar won't minimize while app is in reader mode as it did before, making it hard to navigate. 

## Other details
![Screenshot_20200803-170252](https://user-images.githubusercontent.com/38831894/89223103-9474df80-d5ac-11ea-90e1-415f0b581fdb.png)

**Comment by kaosjr** [comment]
Can confirm that this issue also occurs on an NVIDIA SHIELD Tablet K1 
![Screenshot_20200804-021943](https://user-images.githubusercontent.com/16449077/89280430-771c3180-d5fd-11ea-98c1-d1956ccbfe89.png)
