### ISSUE TITLE
Better changelog

### ISSUE THREAD

**Issue by Rstment25** [inorichi/tachiyomi#3588]
## Like instead of showing us this 
![Screenshot_20200803-214244](https://user-images.githubusercontent.com/32986283/89221702-06acea80-d5d4-11ea-8a76-e473ebea7a24.jpg)

## How about you keep this
![IMG_20200803_215944](https://user-images.githubusercontent.com/32986283/89222082-aff3e080-d5d4-11ea-856b-96a52ceb45e0.jpg)

## And add this 

![Screenshot_20200803-215246](https://user-images.githubusercontent.com/32986283/89222105-b84c1b80-d5d4-11ea-8c2c-54470761b30a.jpg)

Changelog in the last picture is fully scrowable and pleasant to use. I see you tried in 10.0 and 10.2 to implement something similar but what you changed to in 10.3 is horrific...

Not only is the button itself ( What's new ) completely useles but the UI decision is trash as well. 

![Screenshot_20200803-221806](https://user-images.githubusercontent.com/32986283/89223561-475a3300-d5d7-11ea-99ba-9f665409dc83.jpg)

You're forcing the dialog upon users, forcing them to close it just to be able to use the app! 

That is the bane of all the Chinese crapware out there. How many times did you open up some Chinese app then had tons of shet blasted at you? Not knowing where to start, completely drowning in that shet? Same shet is happing here. 

You open up the app and get shet you didn't ask for right in your face. It gets in the way of using the app, it annoys the living fuck out of the user - an unnecessary step forcing them to close something they didn't even ask for and even if they press the button it doesn't work and only adds more unnecessary steps with the slow ass browsers loading up full blown github page only to then have to muck out of that back in the app. 

Ya know, that's who knows how many steps involved just to be able to see the changes...

Please move to the less annoying and more neat bottom of the page toast like notification with scrowable dialog like what you'll see below.

https://mega.nz/file/CEwByboI#CLj0zKOu49OV4SsglBsSSgpas129YMff84EBKGBoHlY

You had it right in the first few tries, hopefully this sets you on the right path again. 

Thanks!

**Comment by arkon** [comment]
> Not only is the button itself ( What's new ) completely useles but the UI decision is trash as well.

It redirects you to the changelog.

> You're forcing the dialog upon users, forcing them to close it just to be able to use the app!

Because people miss the snackbar and people clearly aren't reading.

> That is the bane of all the Chinese crapware out there. How many times did you open up some Chinese app then had tons of shet blasted at you? Not knowing where to start, completely drowning in that shet? Same shet is happing here.
>
> You open up the app and get shet you didn't ask for right in your face. It gets in the way of using the app, it annoys the living fuck out of the user - an unnecessary step forcing them to close something they didn't even ask for and even if they press the button it doesn't work and only adds more unnecessary steps with the slow ass browsers loading up full blown github page only to then have to muck out of that back in the app.

The credibility of this issue fell apart at this point.

**Comment by Rstment25** [comment]
Idk... What fell apart? 

You do realise that any extra crap thrown on top of all the other activities is nothing but bloat?

You have close the dialog itself, on machines that are prolly dinosaur age which means fps jitter, slow down and annoyance. Then add the browser startup time, freeze on that it the device is weak while extra ram that tachiyomi is holding in the background doesn't help either. You then wait for your potato phone to load github only to have to exit all of that and get back in the app. It might not look like such a hassle but the whole thing could take anywhere from 20/30 seconds to much longer. 

How's all of that better than adding few bits of data containing all the changes while using bottom notification in order not to fall into Chinese CRAPWARE territory?

I understand if it may have offended you , but no the argument is pretty sound. The work you're doing is amazing but I hope you'll find it in you to accept critism where its due. 

Thank you!
