### ISSUE TITLE
[Bug] App freezes/crashes

### ISSUE THREAD

**Issue by Rave1996** [inorichi/tachiyomi#3590]
### Device information
* Tachiyomi version: v0.10.3 0c07e05
* Android version: 10 (QKQ1.190828.002) / MIUI Global 11.0.9 | Stable
* Device: Xiaomi Pocophone F1

## Steps to reproduce
1. Open the app and wait a few seconds.

### Expected behavior
Show main screen.

### Actual behavior
App freezes on splash screen.

### Other details
Sometimes:
- Doesn't even load the splash screen
- Randomly crash
Already tried cleaning up the cache, still happens
Error started with 0.10.1 (didn't tried 0.10.0)

**Comment by arkon** [comment]
Uninstall the Kumanga extension if you have it.

**Comment by Rave1996** [comment]
It perfectly works now, thank you.
