### ISSUE TITLE
[Bug] Reader view hides top/bottom bars under navbars when page is tapped

### ISSUE THREAD

**Issue by kaosjr** [inorichi/tachiyomi#3592]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 7.1
* Device: NVIDIA SHIELD Tablet K1

## Steps to reproduce
1. Open any manga chapter.
2. Click in the middle of the screen to bring up the chapter scroll bar and Android navbars.
3. The Android navbars cover the chapter scroll bar and the title text at the top of the screen.

## Issue/Request
In 0.9 versions, the bars correctly positioned themselves so that they were not covered by the navbars. Please make sure that this happens on 0.10 versions as well.

## Other details
Screenshot of this behaviour:
![Screenshot_20200804-021943](https://user-images.githubusercontent.com/16449077/89277392-a29d1d00-d5f9-11ea-9099-7dc4af2f144c.png)
This happens on any chapter and only started happening after I updated from my previous stable version to the latest (0.10.3).

**Comment by scb261** [comment]
Duplicate of #3586

**Comment by kaosjr** [comment]
Which was closed for seemingly no reason. This is a real bug and it shouldn't be closed like that.

**Comment by kaosjr** [comment]
Which was closed for seemingly no reason. This is a real bug and it shouldn't be closed for seemingly no reason.

**Comment by Seishirou101** [comment]
It was closed because ecec1bd fixes it.

**Comment by kaosjr** [comment]
Ah, ok.
