### ISSUE TITLE
[Bug] Migrate fails

### ISSUE THREAD

**Issue by jsilvermist** [inorichi/tachiyomi#3595]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 10
* Device: Pixel 2 XL

## Steps to reproduce
1. Select a manga
2. In the top right menu click Migrate
3. Select a new source and click Migrate

### Expected behavior
The manga should remove the old source from the library and add the new one with read chapters.

### Actual behavior
The old manga is removed from the library but the new one is not added, nor does it have any chapters marked as read.

### Other details
First time this happened it did migrate read chapters but not add the new source to my library after removing the old one, but since then it won't even mark the chapters as read on the new source anymore.

**Comment by arkon** [comment]
I can't reproduce this. Can anyone else reproduce it?

**Comment by jsilvermist** [comment]
It's strange but it doesn't seem to be happening anymore. It happened before when migrating MangaHere to Mangakakalot, and Mangakakalot to MangaHub, but it seems to be working now.

I'm wondering if it could have been related to packet loss on my network connection? That's the only thing that I can think of that could have changed.
