### ISSUE TITLE
[Feature Request] Show Or Merge/Remove Duplicate Manga in Library

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi#3596]
Currently there is no option in tachiyomi to know duplicate Mangas in library, so pls Add an option to show Merge/Remove duplicate manga in library

**Comment by Soitora** [comment]
A question to this would be; what are you doing in the first place that creates duplicates?

**Comment by CarlosEsco** [comment]
for merging #886

for showing.  just type the title you suspect is duplicate.  This would be a rarely used option and is not worth adding
