### ISSUE TITLE
[Feature Request] Sort Manga By Source In Library

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi#3597]
Add an Option to Sort Manga by source in library

**Comment by scb261** [comment]
You can search by source name

**Comment by sam7028** [comment]
i know that we can search by source name,but there are many sources available,so it will be difficult to search each and every source to know what manga have been added to library if the feature is added it will be much easier to know.

**Comment by scb261** [comment]
I don't understand why you want to sort library by source. If you interested in particular source - you can search by its name. If you want to see last manga added to library - use sorting by date added.
