### ISSUE TITLE
[Feature Request] <Don't show "No results found" extensions when searching in Browse tab>

### ISSUE THREAD

**Issue by tmyl8** [inorichi/tachiyomi#3598]
When searching for a manga in the browse tab, extensions that have no result show the message "No results found". This takes up space for no good reason and if you use a lot of extensions but only a few of them have the manga you are looking for then you will need to scroll through all the sources that have the no results message.

![Example](https://user-images.githubusercontent.com/47001660/89357918-bb6d0780-d6b9-11ea-8e73-98c8f058f865.jpg)

In previous versions when searching for manga, any extensions that didn't have a result simply didn't show up on the search. Is it possible to add this back in the settings so that extensions that don't contain the results don't show up?

**Comment by vengiare** [comment]
I think the "No results found" is still a good feature so that you can go a the source and then tweak your search query.

I hope this doesn't get removed completely. Ideal solution would be to put sources with results on top. Quick solution would be a toggle.

**Comment by joseph619** [comment]
Grouping sources with results at the top would be ideal. This way both conditions can be satisfied

**Comment by Soitora** [comment]
Like @joseph619 wrote, grouping positive results is something we could look into adding. We're however not removing the notice of none found, it was like that before but for good reasons it was changed.

**Comment by tmyl8** [comment]
Hi, all these suggestions sound good to me!

I've noticed that this post is closed, I assume something was modified code wise? (apologies if I'm wrong as I'm new to Github). 

Do I need to download anything to get the new code to work or will it be implemented in the new update?

**Comment by scb261** [comment]
@tmyl8 yes, they modified code, sources with results will appear at top, wait for next release

**Comment by tmyl8** [comment]
Thanks all!
