### ISSUE TITLE
Downloader won't start until Access permissions accepted (Android 6)

### ISSUE THREAD

**Issue by namack75** [inorichi/tachiyomi#36]
Noticed that when I selected chapters to be added to the download queue, they wont start.
The downloader will only start when I go to settings and 'change' the download directory and get permission prompted.

**Comment by IceKreem** [comment]
Basically What you need to do is, you need to go into settings > Downloads and then change the Downloads Directory /sdcard/andThenCreateOrChangeDirectory here. Save it and close the app and the download will work :) This is a work around because the default folder chosen doesn't exist.

**Comment by inorichi** [comment]
It should be fixed already.

**Comment by Ligerx** [comment]
I ran into a similar problem on v0.1.3 (just released).
I'm running Lollipop, and I can't use the app to create new folders or download on my external SD.

If this sounds like a separate problem, then I'll create another issue. Thanks!

**Comment by inorichi** [comment]
Try to use the external cache dir as downloads dir.

The dir is: `/sdcard/Android/data/eu.kanade.tachiyomi/`, if you use debug version it ends with `eu.kanade.tachiyomi.debug`. Try to create a downloads folder there and let me know what happens.

**Comment by Ligerx** [comment]
The `eu.kanade.tachiyomi` folder did not exist, so I created it myself. (didn't get any permission errors doing this)

However, when I tried downloading a chapter, it stalls at 0% in the download queue.

**Comment by inorichi** [comment]
Are you on wifi network? By default it only downloads when wifi is available. If it's not that, I don't have any idea, the commit that fixed this is for Marshmallow and higher. 

That folder should be writable by the app, and the downloads start when there's a connection available. I would try looking for similar problems with your device and OS version.

**Comment by Ligerx** [comment]
Okay so maybe I was having internet problems before, but the external cache dir works for downloads now. I believe the `/sdcard/Android/data/eu.kanade.tachiyomi/` directory is actually internal storage.

However I'm still having problems with downloading to my external SD card. If I'm interpreting my research correctly, then Lollipop needs to explicitly ask for permission (similar to Marshmallow). I also just formatted my sd card (through my phone) and that didn't fix anything.

[Link1](https://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop)  [Link2](https://android.stackexchange.com/questions/96500/how-to-allow-apps-to-delete-sd-card-content)  [Link3](https://metactrl.com/docs/sdcard-on-lollipop/)

**Comment by inorichi** [comment]
Only in Marshmallow a popup is displayed to ask for permissions. Lollipop doesn't have/need that. Try the latest debug with these changes a81f6c3. I don't have external SD card so I can't test this.
