### ISSUE TITLE
[Filter] <the filter in the extension for finding a certain theme>

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#3600]
### Why/User Benefit/User Problem
Because it'll be easy for me to find horror and fantasy mangas. So please bring back this feature. 

### What/Requirements
You already know how it works. It's the filter when browsing in a certain extension to find mangas with the tags that I want.

**Comment by jobobby04** [comment]
It's still there, click the source name instead of the latest button

**Comment by MxxS07** [comment]
Thanks! I thought It was removed.
