### ISSUE TITLE
Optional switching between the new and old interface info manga.

### ISSUE THREAD

**Issue by KazumaYamaguchi** [inorichi/tachiyomi#3609]
### Why
Many users (friends) They reported that the change in the viewing tab of the list of chapters and in the info of the manga In the version 0.10.3 it was very abrupt, and the list of chapters just below the manga information made the interface of that part very polluted, because there were many things together.

### User Benefit.
Many users have already gotten used to the [Old](https://imguh.com/image/L2AQC), And the [new look](https://imguh.com/image/2020-08-06-00-32-57-img.L2tpW). and adding a way to transition between the new and the old look would be another way of customization.

### User Problem.
As I mentioned at the beginning, the page was very polluted and disorganized, making it difficult to locate the options a little, in addition to giving relief to users with OCD and this made it very difficult to adapt to the new version, giving a feeling that it was very strange.

### What/Requirements
The option to switch between the new and the old model could be available in the settings, more precisely in the "General" part.
Making the user be able to decide whether the display mode will be scrolled from top to bottom or scrolling left or right.

**Comment by Soitora** [comment]
No, but you're free to use the option under:

- **More » Settings » Library » "Jump to chapters on open"**

This makes it so that you open manga scrolled down to the chapters list instead.

**Comment by CarlosEsco** [comment]
No. Too difficult to maintain
