### ISSUE TITLE
Constant Crash on Catalogues search and download

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#361]
Searching in the catalogues causes the application to crash after showing the second set of autocomplete. Sometimes downloading many chapters causes the app to crash.

Version: r0.2.2-1
(other relevant info like OS)

Phone: Xiaomi Redmi 1s
Android version: 4.4.4 

sending crash report is already enabled

**Comment by inorichi** [comment]
Can you try the current dev version (r803)? Does it always crash when adding the second page?

I'm aware of an issue in the downloads view while scrolling, but I still don't know how to fix that issue.

**Comment by inorichi** [comment]
Also with r805 it shouldn't crash on the download queue anymore.

**Comment by uenoshita** [comment]
Tried using r805 still experiencing some crashes when search but now it's more random. I sometimes switching sources would also cause a crash. I'd send you the log files if you can tell me the path. It's not in /storage/sdcard0/Android/data/eu.kanade.tachiyomi.debug/ or /storage/sdcard1/Android/data/eu.kanade.tachiyomi.debug/ .

**Comment by inorichi** [comment]
The RAM is not the issue here. And I already have a log of the crash, don't have to worry about that. The crash happens in the android framework, so I have to try workarounds to avoid the crash.

Can you try again with r815? Most probably it happens because you are scrolling while a new page is added, if you scroll slowly it's possible to avoid the crash (when you see the loading progress at the bottom try not to scroll at all and see if it helps).

**Comment by uenoshita** [comment]
Updated to the r815. Tried to do the ff to cause a crash:

A.

1. Search
2. Delete what I typed.
3. Switch sources
4. Crash

B.
1. Search
2. delete some characters (typo)
3. Type new letter
4. Crash

**Comment by inorichi** [comment]
Sorry but the only way to fix this is by trial and error. I've removed the bottom progress bar in [the apk from the branch `issue-361`](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/588:id/app-debug.apk). I think this can fix one of those scenarios. Can you try it?

**Comment by uenoshita** [comment]
Still crashes. Although now it does when pressing enter. Also please note that I'm not scrolling or anything at all just searching on search bar. The only thing I'm touching is the search bar and the on screen keypad. I'm thinking it might have to do with the auto complete/auto populate when coming into the catalogues page.

**Comment by inorichi** [comment]
It can be the keyboard being closed and forcing a layout measurement. [Here's my last try for today](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/589:id/app-debug.apk?guest=1). I'll have to investigate more with the details you provided.

**Comment by uenoshita** [comment]
That seems to have fixed it for the search/auto complete issue. Will try with the download issue later. might have something to do with intermittent mobile data since I was able to download the whole 3 gatsu lion from kiss manga without issue with the stable branch earlier.

**Comment by inorichi** [comment]
The one from the downloads I fixed is when a chapter is going to be removed from the queue, if you are scrolling a lot downwards while it's removed, it crashes. In the current dev release it shouldn't happen.

Or did it happen while you weren't in the downloads view? (just downloading chapters in background)

**Comment by uenoshita** [comment]
I think it happens on the chapter views when choosing to "download all" chapters. Suddenly the app would crash after a few minutes of downloading so what I did was choose download 10 chapters instead after a crash. It's really random so I'm not really sure about the details of the crash.

**Comment by inorichi** [comment]
Okay, please create a new issue for that crash if you experience it again.

**Comment by uenoshita** [comment]
ok thanks
