### ISSUE TITLE
[Bug] Dialog Add manga to library doesn't disappear after few seconds

### ISSUE THREAD

**Issue by staudond** [inorichi/tachiyomi#3614]
### Device information
* Tachiyomi version:  v0.10.3
* Android version: 10
* Device: Redmi Note 8 Pro

## Steps to reproduce
1. Download a chapter from manga not in your library
2. Dialog "Add manga to library?" will pop up

### Expected behavior
This dialog should disappear after few seconds.

### Actual behavior
Dialog stays, and is present when you are searching any source, open any manga and it is even present if you open settings, download queue or categories menu.  It is present even in library view, updates, history and browse section hidden under the bottom bar.

### Other details
It doesn't even disappear after you add the manga to library manualy. Only way for it to disapper is click on add, restart the app or  remove manga from library with downloaded chapters and it will disapper when dialog "Delete downloaded chapters?" pop up. "Delete downloaded chapters?" dialog disappears normally after few seconds.

**Comment by CarlosEsco** [comment]
can you attach a video or gif of this occurring

**Comment by staudond** [comment]
here is a video [google drive](https://drive.google.com/file/d/157QnwxjHfK2A3cFWbo-BVxuDvaNHy--W/view?usp=sharing)
