### ISSUE TITLE
[Bug] downloaded images are s

### ISSUE THREAD

**Issue by Zethzune** [inorichi/tachiyomi#3615]
---

### Device information
* Tachiyomi version: 0.10.3
* Android version: 7.1.2
* Device: Redmi 5A 

## Steps to reproduce
1. Download chapters with long strip pages or chapters with over 20 pages(estimate)

### Expected behavior
Smooth reading access to the downloaded chapters

### Actual behavior
Blank or black chapters pages

### Other details
I suspect that it was download failure but the app recognise that it was download complete. 
I tried comparing one long chapter in nhentai extension - since it's common that it have more than 30 chapter pages - and mangakakalot and mangadex extension's manhwa with the downloaded chapters in the directory. 
The chapters in the directory has missing or broken pages but the app recognise that it was completely downloaded

**Comment by armangido** [comment]
Can provide an source/link that has this page, I will look into it.

**Comment by arkon** [comment]
Not enough info.
