### ISSUE TITLE
[Feature Request] Only One Instance Of Pinned Sources 

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#3616]
### Why/User Benefit/User Problem 
If you pin a source, it should just appear at the top, and not both at the top and then again at the source list. This makes browsing the source list more convenient if the list is long.

### What/Requirements
Suppose I have MangaDex, MangaHub, MangaLife and MangaSee. If I pin MangaSee, it disappears from my source list (where the other sources are) and appears only under the "Pinned" section, so basically it doesn't appear twice. I suppose this is just a "Quality of Life" feature rather than anything important, but it would be appreciated.

**Comment by arkon** [comment]
I don't really see how it's more convenient. If anything, I'd find it more convenient to still see a complete list while scrolling through them.

**Comment by MercerBoi** [comment]
Bruh.

**Comment by MercerBoi** [comment]
How about making it an optional feature? 

(Unless it's difficult to implement and/or clutters the code, in which case I'll understand and stop pestering about this further.) 

I'm only arguing since it's still a pretty subjective matter.
