### ISSUE TITLE
[Bug] <App doesn't open>

### ISSUE THREAD

**Issue by Prephis** [inorichi/tachiyomi#3618]
#3406 # Device information
* Tachiyomi version: 0.10.3
* Android version: 10
* Device: Google Pixel 4XL

## Steps to reproduce
1. First step - open app.
2. Second step - app doesn't load.

### Expected behavior
The app should open up.

### Actual behavior
App doesn't load further than the logo.

### Other details
I'm attaching a picture of my screen while the app loads, it also lags my phone when I try to close it if I don't close it before switching to another app.

![Screenshot_20200806-225401](https://user-images.githubusercontent.com/61310350/89534212-eed5a080-d837-11ea-9fdf-01fbde9ffdc0.png)

**Comment by arkon** [comment]
Uninstall the Kumanga extension if you have it.

**Comment by Prephis** [comment]
How do I do that if I can't get into the app?

**Comment by MerradOklom** [comment]
Uninstall it as you would uninstall any other app (Phone Settings > Applications).

**Comment by lmj0011** [comment]
> Uninstall it as you would uninstall any other app (Phone Settings > Applications).

https://tachiyomi.org/help/faq/#how-do-i-uninstall-an-extension

**Comment by CarlosEsco** [comment]
@lmj0011  that guide is useless if he can't open the app.  He needs to go through the actual phone settings as if it was a normal application uninstall

**Comment by Prephis** [comment]
That worked, thank you so much, I didn't know you could uninstall them that way.
