### ISSUE TITLE
Screen too bright

### ISSUE THREAD

**Issue by jibust** [inorichi/tachiyomi#362]
Please allow forma an evento lower brightness that what is currently offered.

Version: 0.2.2-1
(other relevant info like OS)

**Comment by inorichi** [comment]
By default it uses the system's brightness. If your minimum brightness isn't enough I can't do anything.

**Comment by j2ghz** [comment]
You can try third party app like https://play.google.com/store/apps/details?id=com.vitocassisi.luxlite&hl=en

**Comment by inorichi** [comment]
Actually it's possible to have a "lower brightness" than the allowed by the system. Adding a semitransparent overlay on top of the reader can simulate that.

**Comment by Neverest** [comment]
What about a bluelight filter option?

**Comment by wopian** [comment]
There are plenty of apps for that @Neverest

**Comment by inorichi** [comment]
Adding a black layer on top of the reader is easy to implement. Supporting filters might be a pain, and if there are already apps capable of doing that it's not worth to complicate Tachiyomi even more.

Regarding this change, I've tried to hide the dialog while the progress bar is being dragged (to preview the brightness) but I couldn't do it. Maybe another day I achieve it.
