### ISSUE TITLE
[Feature Request] Bring back the red "downloaded" badges 

### ISSUE THREAD

**Issue by 29-29** [inorichi/tachiyomi#3621]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Because I miss it, and I think red looks more suitable for the "downloaded" badges

### What/Requirements
(explain how this feature would behave)
Maybe give the user an option to change the color of the badges (downloaded and unread) between red, green, or the user's choice.

**Comment by CarlosEsco** [comment]
#3610
