### ISSUE TITLE
[Bug] no action to search by a tag on the latest tab 

### ISSUE THREAD

**Issue by 130bernardo130** [inorichi/tachiyomi#3625]
### Device information
* Tachiyomi version: Tachiyomi version: 0.10.3
* Android version: 10
* Device: all devices

## Steps to reproduce
1. First step
click in the latest, every extention works
2. Second step
click in any manga
3. Third step
click in any tag that you want.

### Expected behavior
the app should search using the tag

### Actual behavior
the app pretends to search the tag

### Other details
no other details needed. its a easy reproducible bug.

**Comment by arkon** [comment]
Source search only functions when you browse the source directly, not via latest.

**Comment by Shadow573** [comment]
Why are we not able to search in the new update? Makes it hard to find anything
