### ISSUE TITLE
[Bug] impossible to see and use top and bottom bar

### ISSUE THREAD

**Issue by SkyNalix** [inorichi/tachiyomi#3626]
### Device information
* Tachiyomi version: stable 0.10.3
* Android version: 7.0
* Device: Huawei GR5 2017

## Steps to reproduce
1. open any chapter of any manga
2. click on the middle of the screen so the top and bottom bar appear

### Actual behavior
![image](https://user-images.githubusercontent.com/56894341/89575818-a6fe4b80-d82e-11ea-9fda-2db0807c20be.png)

**Comment by scb261** [comment]
Already fixed, wait for next release
