### ISSUE TITLE
[Feature Request] Add a dark mode button on the homepage

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi#3629]
Tachiyomi version: 0.10.3

with the addition of a dark mode button on the homepage it will make it easier for users to switch from light to dark mode and vice versa.
![Screenshot_2020-08-07-14-18-24-1](https://user-images.githubusercontent.com/3974476/89620552-59f69580-d87f-11ea-8780-b01e42d7fbc3.png)

**Comment by CarlosEsco** [comment]
No plans to add a dark mode button.

**Comment by willyreza** [comment]
Why?

**Comment by CarlosEsco** [comment]
Cause it's a useless feature that wouldn't be used at that often.  Most people set a theme and forget it.  You also can switch to follow system. And let your system auto control when it's light vs dark

**Comment by willyreza** [comment]
Ok
