### ISSUE TITLE
[Source Request] <3asq> <Gmanga>

### ISSUE THREAD

**Issue by el3rg** [inorichi/tachiyomi#3631]
[Source Request]
Name:3asq
Link:https://3asq.org/
Language:Arabic العربية
-------------------------------------------
Name:Gmanga
Link:https://gmanga.me/
Language:Arabic العربية

**Comment by edgarMejia** [comment]
This source is already in **Madara** extension.
See: https://tachiyomi.org/extensions-spreadsheet.
Please close this.
