### ISSUE TITLE
[Bug] <Write short description here> No search or filter button when I open an extension

### ISSUE THREAD

**Issue by KillerQueen86** [inorichi/tachiyomi#3632]
---

### Device information
* Tachiyomi version: 0.10.3
* Android version: 10
* Device: Samsung A70

## Steps to reproduce
1. First step
Update to Tachiyomi ver. 0.10.3

2. Second step
Go to browse and click latest of any extensions

### Expected behavior

There should be a search and filter button

### Actual behavior

The search and filter button are missing

### Other details
Additional details and attachments.
![20200807_230559.jpg](https://user-images.githubusercontent.com/69375772/89701348-11cd8680-d904-11ea-8e97-d8e4b8f9eecb.jpg)

**Comment by pervertkirito** [comment]
its not a bug. Read changelog.
