### ISSUE TITLE
[Feature Request] Add smb function please

### ISSUE THREAD

**Issue by Heavyarms04** [inorichi/tachiyomi#3633]
It would be nice if we could access smb folders, whether they are on a computer or from a NAS device, since the people we usually collect manga would stop suffering for space, and I must say tachiyomi is the most robust manga viewer that exists no matter the size of the file this is layers to show it in a fast and soft way

Perdón por la mala redacción al inglés, no manejo bien el idioma
Sorry about the mis-writing in English, I don't handle the language well

**Comment by arkon** [comment]
Related: #2418

Otherwise, try using something like Komga.
