### ISSUE TITLE
[Bug] <ReadManhwa> <Not showing nsfw content>

### ISSUE THREAD

**Issue by hunter643** [inorichi/tachiyomi#3634]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 9
* Device: Samsung j7 Core

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Shows NSFW contents on the top.

### Actual behavior
No NSFW

### Other details
![117236704_237223167352481_3716333985696455739_n](https://user-images.githubusercontent.com/69393812/89714272-05aefb00-d9d0-11ea-9fd0-7e66fc063fdd.jpg)

**Comment by arkon** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4050
