### ISSUE TITLE
[feature request] just a simple clock on the next chapter screen... 

### ISSUE THREAD

**Issue by 007Hughy** [inorichi/tachiyomi#3635]
Just a thought but a simple clock on the next chapter screen would be nice if your one of the people that will read till the sun comes up with out noticing the time... Been there a few times.

A toggel in the settings under Reader would be the best way for people to turn it on or off...

**Comment by arkon** [comment]
What if it just showed the status/navigation bars instead, similar to when there's no more chapters to read?

**Comment by 007Hughy** [comment]
What ever wold be easiest to implement would be fine with me so long as the time is displayed, but it probably should be an option that the user has to turn on as some people may not like having the status/navigation bars shown on that screen...

**Comment by arkon** [comment]
That said, couldn't you just toggle the status bar yourself to check the time?

**Comment by 007Hughy** [comment]
True the thought just never came to mind... anyway thanks for considering the Idea :)
