### ISSUE TITLE
[Bug] <Mangafreak> <Failed to bypass/failed to update manga>

### ISSUE THREAD

**Issue by hunter643** [inorichi/tachiyomi#3636]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 9
* Device: Samsung j7 Core

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Update manga

### Actual behavior
Failed to update/failed to bypass cloudflare

### Other details
![20200809_083008.jpg](https://user-images.githubusercontent.com/69393812/89722378-83e4bf00-da1b-11ea-8265-62e14e4c7c3f.jpg)

**Comment by scb261** [comment]
Open in webview first to bypass it
