### ISSUE TITLE
seamless chapter when using filter

### ISSUE THREAD

**Issue by sm7297** [inorichi/tachiyomi#364]
when using filter for unread chapter in any manga  if unread chapter are different in numbers like after 30 chapter the next unread chapter 45 when getting at the end of the chapter 30 if scroll more it will load 31 instead of 45 

Version: r778 or v0.0.0
android kitkat 4.4.2

**Comment by inorichi** [comment]
The reader doesn't apply the view filters. The next chapter of 30 will always be 31, and the previous one 29, regardless of its read status. 

Who would want to jump from 30 to 45 while reading? In the unlikely case the user wants to do that, he will close the reader and open chapter 45.
