### ISSUE TITLE
[Bug] add bar show evrlery after add... 

### ISSUE THREAD

**Issue by VeganCzech** [inorichi/tachiyomi#3640]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 9
* Device: Huawei P30 lite 

Always when adding manga I see the bottom panel add manga which does not disappear. It helps to close the app and reopen it. 
I add manga and downstairs I have a bar where it writes add manga even if it is added. I can see it even in the system settings of this bar I add manga and downstairs I have a bar where it writes add manga even if it is added. I see it even in the system settings of this bar. 
![Screenshot_20200810_122358_eu kanade tachiyomi](https://user-images.githubusercontent.com/63636174/89773957-36dd1780-db05-11ea-9d8b-a138e62a0e1e.jpg)
![Screenshot_20200810_122711_eu kanade tachiyomi](https://user-images.githubusercontent.com/63636174/89773962-38a6db00-db05-11ea-8ae1-5fa0585f00b6.jpg)
![Screenshot_20200810_122404_eu kanade tachiyomi](https://user-images.githubusercontent.com/63636174/89773963-393f7180-db05-11ea-8402-35cca49196c9.jpg)

**Comment by CarlosEsco** [comment]
#3614
