### ISSUE TITLE
[Bug] Download complete notification keeps appearing

### ISSUE THREAD

**Issue by hunter643** [inorichi/tachiyomi#3642]
### Device information
* Tachiyomi version: 0.10.3
* Android version: 9
* Device: Samsung j7 Core

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
![20200810_224859.jpg](https://user-images.githubusercontent.com/69393812/89796324-15f3e100-db5c-11ea-8227-d036a5e44add.jpg)

**Comment by lmj0011** [comment]
Not a bug

See: https://discord.com/channels/349436576037732353/349436576037732355/741015250601508935
