### ISSUE TITLE
[Bug] Unable to go back to a previous chapter after opening a new one.

### ISSUE THREAD

**Issue by kleverly** [inorichi/tachiyomi#3643]
---

### Device information
* Tachiyomi version: Stable 0.10.3
* Android version: J530FXXS7CTF1
* Device: Samsung Galaxy J5 (2017) SM-J530F

## Steps to reproduce
1. I open a new chapter from the _Updates_ section.
2. I go back to the previous page from page 1, as to go to the previous chapter.

### Expected behavior
I should be able to see the last page of the previous chapter, right?

### Actual behavior
The message "There's no previous chapter" appears, as that last chapter was also the first one.

### Other details
I tried with three different extensions (Mangadex, MANGA Plus and Webtoon) and had the same result. This seems to happen mainly (but not only) with newest chapters. If I try it with the last chapter of Chainsawman, either by opening it from Updates or by going inside the manga and choosing the last chapter, it gives me this problem. But If I do it, idk, with Comic Girls, it doesn't happen.
As you can see in the screenshot, the selected chapter is the last one (#80), but it says there are no previous chapters. Of course, if I try to open the previous chapter directly, it works.
![7d116e89-eab1-4685-b853-fdb94c031430](https://user-images.githubusercontent.com/69477928/89814241-1f248400-db43-11ea-850f-26885e7c03e4.jpg)

**Comment by CarlosEsco** [comment]
do you have skip read enabled in the reader settings?

**Comment by kleverly** [comment]
Yes, that was it. Thank you for your help and sorry for wasting your time with such a thing.
