### ISSUE TITLE
Delete download chapters

### ISSUE THREAD

**Issue by Mano5JP** [inorichi/tachiyomi#3647]
## Why/User Benefit/User Problem
(so, as of now it removes/delete read chapters which was downloaded. 

So i am using Samsung Note 10+ and has installed galaxy labs

Though all downloaded chapters been deleted after been read. File guardian(galaxy lab keeps it. ) 

## What/Requirements
(maybe if it could delete from there as well if its feasible)

For a reference that the copies of file that its size. 

![Screenshot_20200810-225357_File Guardian](https://user-images.githubusercontent.com/64928088/89824868-467b5100-db43-11ea-8c54-57c5ee8368ed.jpg)

**Comment by arkon** [comment]
> File guardian(galaxy lab keeps it. )

I have no idea what that is, but it sounds like an issue for that. Tachiyomi just deletes files normally.

**Comment by Mano5JP** [comment]
I found out that i could restrict file guardian to not store file. 

That solved a problem, i guess 

Thx @arkon
Maybe wasn't really tachi issues 
Cheers.
