### ISSUE TITLE
[Feature Request] Add dark mode button on the homepage 

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi#3653]
Tachiyomi version: 0.10.4
![images (1)](https://user-images.githubusercontent.com/3974476/89883940-5ed98300-dbb8-11ea-8823-58d7760e91b1.png)

Please, with the addition of a dark mode button on the homepage it will make it easier for users to switch from light to dark mode and vice versa. Thanks :)

**Comment by scb261** [comment]
#3629
