### ISSUE TITLE
[Feature Request] Custom Brightness For whole App Not For the Reader

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3654]
---

## Why/User Benefit/User Problem
Some Of Us Readinh Manga During Night. 
And I think that We Need Custom Brightness Not only For The Reader But In the Whole App.. 
Because Sometimes When I finished Reading The Manga with The Lowest Brightness And If You  Go To the Categories Section... It Returns To the Normal Brightness....

IF IT IS ALREADY IN THE app.. HELP!!!

**Comment by scb261** [comment]
#3453 
> Colour filter options outside of reader

I guess this idea also applies to brightness.

For now you could use another app to change brightness not only for Tachiyomi but for all your apps. You can google it 'blue light filter for android' or something like this

**Comment by CarlosEsco** [comment]
why wouldn't you just set the brightness for your whole device lower also?  That is like complaining when you stop reading and loading chrome its too bright
