### ISSUE TITLE
[Bug] Library only shows downloaded

### ISSUE THREAD

**Issue by skpeter02** [inorichi/tachiyomi#3655]
---

## Device information
* Tachiyomi version: 10.4
* Android version: 10
* Device: xiaomi  pocophone f1

## Steps to reproduce
1. Go to library
2. -

### Expected behavior
Show every manga/manhua I've added to my library with every chapter available 

### Actual behavior
Strictly shows only downloaded manga/manhua.

## Other details
Checkmark is grayed out. When looking up a new series every chapter is missing from the list. No longer updates the series I've added to the library

**Comment by vengiare** [comment]
More > Turn off "Downloaded only"

**Comment by skpeter02** [comment]
i said that the option was grayed out. ergo I CANT
