### ISSUE TITLE
[Feature Request] Allow filtering by label or tags within library

### ISSUE THREAD

**Issue by Indipax** [inorichi/tachiyomi#3658]
## Why/User Benefit/User Problem
This will allow you to find similar mangas in your own library, grouping them together by their genres making it easy to search for mangas by label or tag if you have a lot. 

## What/Requirements
Currently, you are able to filter in catalogues by tag or label (ex. Shounen, shoujo, action, drama, etc) but these tags aren't able to be used in your own library. I propose that the library filters displays any current labels your mangas have (via their source), and use this as a way to filter or sort mangas in your library.

**Comment by arkon** [comment]
> but these tags aren't able to be used in your own library

Yes you can, either search manually or tap one from the manga info screen.
