### ISSUE TITLE
Change tracking guide wording

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3659]
![Screenshot_20200812-042412~01](https://user-images.githubusercontent.com/63973749/90011302-f253a680-dcd3-11ea-9618-80a4aff1e168.png)

Small nitpick: tracking tab no longer exist. Don't really know how to word it tho, "tracking menu" maybe.

**Comment by shashank-p** [comment]
To use Tracker you need to login before from Setting -> Tracking tab once you logged in Tracking button is visible in Manga Info Page beside library button

**Comment by scb261** [comment]
@shashank-p screenshot is from Settings -> Tracking. The issue is that tracking (and chapter list) were moved from tabs to manga info screen and there is no tabs now, but screenshot tells users that tracking still in the tab
