### ISSUE TITLE
[Feature Request] In app sharing feature

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi#3661]
An in app sharing feature

## Why/User Benefit/User Problem
Sharing the manga page website link is useful, but an in app sharing feature is even more useful than that, because usually when I want to share with a friend, they have Tachiyomi installed too and sending them directly to the manga page in the app will take out the effort of manually installing the extention and finding the manga by searching in the extention. 

## What/Requirements
possible implementation: 
Use a custom URI, put in the extention id/package and link in the URI

**Comment by CarlosEsco** [comment]
Not possible without major app changes . Also You would need the extension installed. It makes more sense to add deep linking to more sources so sharing the url can be opened up in app
