### ISSUE TITLE
[Feature Request] Bypass cloudflare 

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#3666]
## Why/User Benefit/User Problem
It's kinda annoying to open the manga on web and bypass cloudflare everytime I download new manga.

## What/Requirements
Please add a feature to automatically bypass cloudflare.

**Comment by arkon** [comment]
It already does. There's only so much it can do depending on the protection level.

**Comment by MxxS07** [comment]
Where can turn find that feature?

**Comment by arkon** [comment]
It happens in the background.

**Comment by MxxS07** [comment]
![Screenshot_20200813_202744](https://user-images.githubusercontent.com/60882025/90134340-99ebda00-dda3-11ea-8a64-f8ee2ba91581.png)
OK. BTW, what does this option do? Is it connected to bypassing?

**Comment by arkon** [comment]
No. Please read https://en.wikipedia.org/wiki/DNS_over_HTTPS
