### ISSUE TITLE
[Bug] <Seach in any extension is not working>

### ISSUE THREAD

**Issue by jinshelgeorge** [inorichi/tachiyomi#3668]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 8
* Device: Honor 7A

## Steps to reproduce
1. Open any extension (for example mangasee)
2. Search any manga

### Expected behavior
The manga which i searched should appear on the screen. 

### Actual behavior
It keeps on loading and actually not using the internet. 

## Other details
Actually i observed when i search any manga it is not using or sucking the Internet ( Internet speed- 0K/s) like it should be doing and keeps on loading. But when i open the webview it immediately boosts the internet then i close the webview, then the manga i searched loads up because of the boost. 
![Screenshot_20200813-210845.jpg](https://user-images.githubusercontent.com/69640734/90155765-52684c80-dda9-11ea-90ff-89d4a008652a.jpg)

**Comment by Shadow573** [comment]
The ability to search in any extension is gone and the only option are there is sort and go to the browser but not the search icon which make it impossible to search any manga.

**Comment by arkon** [comment]
Read #3600

**Comment by Shadow573** [comment]
Akron thank you

**Comment by Shadow573** [comment]
arkon 
Thank you
