### ISSUE TITLE
[Bug] download queue from chapter updates are "paused". Need to manually start the download 

### ISSUE THREAD

**Issue by orangpelupa** [inorichi/tachiyomi#3670]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 8.1
* Device: Mediapad M3

## Steps to reproduce
1. Check for new chapters (drag library down / scroll way past up) 
2. Wait until it found new chapters to download 

## Issue/Request
New chapters are added to download queue but they are paused. I need to manually start the queue. 

## Other details
Did not happen before the UI revamp.

**Comment by arkon** [comment]
Judging from the way you said "UI revamp", I assume you updated from 0.8.x.

See #3098

**Comment by orangpelupa** [comment]
> Judging from the way you said "UI revamp", I assume you updated from 0.8.x.
> 
> See #3098

It seems to be a different issue. It was about downloads not auto resuming.

But my issue was tachiyomi did not auto start download when new chapters are found. I don't even know tachiyomi have auto resume haha.

**Comment by arkon** [comment]
It's referring to the resumption of downloads.

**Comment by arkon** [comment]
#3098 / #959
