### ISSUE TITLE
[Feature Request] Scroll position to last read chapter

### ISSUE THREAD

**Issue by pig-cop** [inorichi/tachiyomi#3672]
When I enter a long manga that I'm still reading usually I don't filter out the read chapters because I want to reopen the last chapter to jog my memory if it's passed some time.
So the chapter list scroll position is always on top showing the first chapter or the last one, depending on my sort order.

What do you think if there was an option to automatically center the scroll position to the last read chapter?

Sure I know there's the Start/Resume button, I'm using it all the time and it's quite cool but this can be even cooler, just to visually be aware of what chapter is the current one directly from the list.

**Comment by lmj0011** [comment]
Assuming you download chapters before reading, this is work around to keep last read at the top:

- enable "Remove when marked as read" preference

- change your "Remove after read" preference to "Second to last chapter"

- change your manga's chapter settings filter to "Downloaded" and sort to "By source" and ascending (ie. blue arrow pointing down)

**Comment by Matth7878** [comment]
@pig-cop FYI I just opened an issue for a feature request which I think could also answer to your use case : #3677 Filter unread and last read chapters

**Comment by pig-cop** [comment]
@lmj0011 That's an interesting function, I never used it and for manga downloaded with Tachiyomi it sure gets the job done, but I'm using the local source for most of the longest manga I read (I locally store the official digital editions).

@Matth7878 Your feature request does indeed address in different way the same scenario and it's a better solution.

After thinking about it I realized that my suggestion make no sense if the header of the manga (cover, title, etc.) scrolls up as part of the chapter list like it does now, it would be confusing and an unwanted behaviour.

**Comment by scb261** [comment]
I like this one better, since then I won't need to change filter to read older chapters (I mean more than 10 chapters ago). Maybe add *Jump to* to 3-dot menu on manga page and replace current switch option in settings *Jump to chapters on open* with option *On open*:
* Show manga info
* Jump to start of chapter list
* Jump to last read chapter

**Comment by pig-cop** [comment]
@scb261 That's maybe even better, simply a button to jump to last read without involving filters. I agree with you.

**Comment by arkon** [comment]
So J2K used to have a similar feature where it'd automatically scroll to the first unread (none of the apps do anything related to a truly "last read" concept) and people actually complained about fwiw.

**Comment by pig-cop** [comment]
Yeah I really see how it could be really annoying if it was automatic.
If it was something like this?

https://i.imgur.com/ehGvAp8.jpg

**Comment by lmj0011** [comment]
> Yeah I really see how it could be really annoying if it was automatic.
> If it was something like this?
> 
> https://i.imgur.com/ehGvAp8.jpg

If that button is intended to _only_ jump to the "last read" chapter, you may want to lose the arrow, because it makes it seem like it's going to do some sorting.

--

Also, what if the "last read" chapter is not in the list due to filtering? Should the button only be visible if certain filters are not set?

**Comment by scb261** [comment]
> Also, what if the "last read" chapter is not in the list due to filtering? Should the button only be visible if certain filters are not set?

I think it's better to jump to first unread if you take into account how app works under the hood. If there is unread chapters, then show first unread in center of screen. If none - show message about it or jump to start/end depending on current sort or both.

**Comment by pig-cop** [comment]
> If that button is intended to _only_ jump to the "last read" chapter, you may want to lose the arrow, because it makes it seem like it's going to do some sorting.
> 
Yeah you're actually right.

**Comment by lmj0011** [comment]
> **I think it's better to jump to first unread** if you take into account how app works under the hood. If there is unread chapters, then show first unread in center of screen. If none - show message about it or jump to start/end depending on current sort or both.

filtering by "unread" and have ascending sort order set will get you that behavior. Doesn't this work for local sourced manga also?

**Comment by pig-cop** [comment]
> filtering by "unread" and have ascending sort order set will get you that behavior.
> ^ Doesn't this work for local sourced manga also?

It does but you cannot read one or two chapters behind, because they're filtered out.

**Comment by scb261** [comment]
> filtering by "unread" and have ascending sort order set will get you that behavior.

I want to:
1. Have unfiltered list, so I could scroll to older chapters without changing filter each time
1. See current chapter in list when opening manga page, so I could see if there is any duplicats or missing chapters. And as the author said, it's just cool (not exactly cool, but nice) to see current chapter in list before reading.

Current jump option doesn't allow both of those at the same time and I described possible modification of it above. Actually I was thinking about opening the same issue before and now I see that I'm not the only one who wants it.

> Doesn't this work for local sourced manga also?

Not sure how local manga is related here, it should work the same for it.

**Comment by lmj0011** [comment]
> I want to:
> 
> Have **unfiltered list**, so I could scroll to older chapters without changing filter each time
> See current chapter in list when opening manga page, so I could see if there is any duplicats or missing chapters. And as the author said, it's just cool (not exactly cool, but nice) to see current chapter in list before reading.

Ok, this answers my question

>Also, what if the "last read" chapter is not in the list due to filtering? Should the button only be visible if certain filters are not set?

In this case, it would make sense to only show a "Jump to last read" button, if there's no filters set.


>Not sure how local manga is related here, it should work the same for it.

pig-cop [mentioned it](https://github.com/inorichi/tachiyomi/issues/3672#issuecomment-674387441) earlier 

> @lmj0011 That's an interesting function, I never used it and for manga downloaded with Tachiyomi it sure gets the job done, but **I'm using the local source** for most of the longest manga I read (I locally store the official digital editions).

**Comment by CarlosEsco** [comment]
A work around is to download stuff and filter by download.  Then delete chapters older than the last read.  You would need to disable delete after read in setting

**Comment by vengiare** [comment]
> Sure I know there's the Start/Resume button, I'm using it all the time and it's quite cool but this can be even cooler, just to visually be aware of what chapter is the current one directly from the list.

J2K achieves this by having a loooong button that says "Start reading Ch.X / Continue reading Ch.X". I have no idea how one would fit that in the FAB, maybe "Resume (Ch.X)" or something.

**Comment by arkon** [comment]
I'm personally against adding this, at least in the way that it's proposed. Filtering/sorting can help you get 99% of the way there.

**Comment by pig-cop** [comment]
And what about just letting the user go back to read chapters even when the read chapters are filtered?

Now if I filter out the read chapters I get what I'm interested in: seeing the last chapter I'm in on top.
But when I enter the chapter if I go back to read a bit of the previous chapter it just says "There's no previous chapter" as if it doesn't exist, if you think about it it doesn't makes much sense even if I'm aware there's some technical reason I guess.
