### ISSUE TITLE
[Feature Request] split downloads

### ISSUE THREAD

**Issue by joelocandol** [inorichi/tachiyomi#3676]
---

## Why/User Benefit/User Problem
(explain why this feature should be added)

With programs or apps like IDM (on windows) or Download Navi (on Android) the user has the possibility to split their downloads in parts to secure the stability of his connection and the total use of their download speed

## What/Requirements

The app must offer the user an option to choice how many parts will the download splits

**Comment by CarlosEsco** [comment]
This is already done behind the scenes.  And downloaders are downloading a large file not a single image. The images are threaded up 2-4 images are downloaded at once
