### ISSUE TITLE
[Bug] Tachiyomi deleted all my downloads after a very long restore process (~1 hour)

### ISSUE THREAD

**Issue by orangpelupa** [inorichi/tachiyomi#3679]
* Tachiyomi version: 0.10.4
* Android version: 8.1
* Device: Mediapad M3

## Steps to reproduce
1. Set download folder to android/data on memory card. For me its the one above "custom location".
2. Download and install previous extensions.
3. Restore backup

### Expected behavior
Backup restored and it automatically detects downloaded manga. As i;ve done countless time.

### Actual behavior
Backup took a long time to finish (~1 hour) and completes just fine (0 error), but all downloaded manga are gone.

## Other details
Currently looking where tachiyomi keeps its log file.

Its nowhere on /storage/emulated/0/Android/data/eu.kanade.tachiyomi/ and its subfolders

**Comment by arkon** [comment]
Unactionable without consistent reproduction steps.

**Comment by orangpelupa** [comment]
Is this bug related? 

Today tachiyomi suddenly mark a bunch of chapter as not downloaded despite its already downloaded, and when it redownloads, it redownloads to the same folder (but with tmp suffix)

This folder already exist and contains proper downloaded files 
heroz scanlation & Group 01000001_Ch.160 - I Was Always Myself 

But suddenly tachiyomi mark the chapters as not downloaded. After I  tell it to download them. It downloads to
Heroz Scanlations & Group 01000001_Ch.160 - I Was Always Myself_tmp

And renamed it to 
Heroz Scanlations & Group 01000001_Ch.160 - I Was Always Myself

After download completed. 

So there's now folder dupes 

heroz scanlation & Group 01000001_Ch.160 - I Was Always Myself
Heroz Scanlations & Group 01000001_Ch.160 - I Was Always Myself

With no way of knowing the dupe and deleting the dupe than by manually exploring the folder. 

Maybe a bug with how mangadex Metadata can be edited post release?

**Comment by scb261** [comment]
@orangpelupa as you noticed, your issue happens when source changes name of a chapter. There is request to have tool that would clean orphaned downloads: #1767 #2445. There are mentions of download badge that used as indicator for such chapters, but it was "fixed", so only way to find it now is using file manager. Or you can try some forks that have option to clean orphaned chapters.

As for original issue, it's probably unrelated, it sounds like downloads were gone even from file manager.

**Comment by orangpelupa** [comment]
I just tried it again, and yep it deletes all my downloaded manga again. 

And I stupidly forgot to copy the downloads before testing hahaha.

**Comment by scb261** [comment]
~~I didn't notice at first that the author and one with renamed chapters is the same person~~

So, I reread original issue and I think I figured it out, restore process is not related here. Second option that contains `Android/data` is folder inside system folder that directly conected to the app. So when you remove app, Android also removes that folder with downloads in it. I don't think that this is considered bug, but maybe at least add some note to this option, maybe just hide path and instead show text "Inside of the app".

Not sure if it's needed, but here is my steps to reproduce:
1. Choose **second** option in *Download location*.
2. Downoad any chapter.
3. Verify with file manager that downloaded chapter is there.
4. Remove app or clear its data with app manager.
5. Go to file manager. You will see that app's folder is gone along with downloads in it.

**Comment by arkon** [comment]
Yeah, uninstalling the app deletes files in the app folder. This is avoided in Android 10+.
