### ISSUE TITLE
[Bug] Search not working at all on any source 

### ISSUE THREAD

**Issue by KrisLau** [inorichi/tachiyomi#3680]
---

## Device information
* Tachiyomi version: J2K 1.0.7
* Android version: 10 (Oxygen OS 10.0.12)
* Device: OnePlus 7T

## Steps to reproduce
1. Search for any manga under browse tab or in a source.
2. No search results.
3. OR try clicking on a manga title in your library and still no search results.

### Expected behavior
Manga matching the search query appears

### Actual behavior
No search results

## Other details
None.

**Comment by AbdullahM0hamed** [comment]
This issue should go [here](https://github.com/Jays2Kings/tachiyomi) instead.
