### ISSUE TITLE
[Bug?] After updating Android System Webview, Tachiyomi keeps stopped working

### ISSUE THREAD

**Issue by Harunyaanuwu** [inorichi/tachiyomi#3682]
## Device information
* Tachiyomi version: 10.4
* Android version: 6.0.1
* Device: Asus

## Steps to reproduce
1. Updated the ASW  to version 84.0.4147.125-414712550

## Issue/Request
MyReadingManga worked yesterday but stopped this afternoon so I tried updating my ASW.
Tachiyomi then keeps stopped working.

Tried to:
* Clear cache
* Restart or reboot phone

## Other details
I don't have a backup made by the app and I tried copying the files back then on older version to 8.(?) but the app didn't get to read them so I would need to try solutions before clearing the data or reinstalling the app.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
