### ISSUE TITLE
[Bug] Downloader notification reappearing

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3686]
## Device information
* Tachiyomi version:  0.10.4-2658
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Run global update
2. When there is updated manga, download it manually while update is ongoing (download finish and downloader notification appear
3. Wait until update is finish 
4. Download completed notification appeared

### Expected behavior
No download completed notification if there is no new downloaded manga after update

### Actual behavior
Downloader notification appear when there is no current downloaded manga.

**Comment by lmj0011** [comment]
@Mymiano see https://github.com/inorichi/tachiyomi/issues/3642
