### ISSUE TITLE
[Feature Request] Multiple downloading

### ISSUE THREAD

**Issue by Harunyaanuwu** [inorichi/tachiyomi#3687]
## Why/User Benefit/User Problem
I don't know if it is some kind of bug but whenever I download couple of chapters, there would be 2 chapters downloading at the same time. There wasn't this option at Settings>Downloads and I think this is a good thing for people having fast internet.

## What/Requirements
There would be an additional option in Settings>Downloads>(Multiple Downloads)
Instead of a chapter at a time, you will be able to download 2,3,4 or even more.

Note: There might be some issues though like sometimes it skips a chapter and you will need to resume it again

**Comment by scb261** [comment]
It's intended behaviour, it downloads more than one chapter at time if they are from different sources (5 max iirc)
There is request to have option to disable it #3472
