### ISSUE TITLE
[Feature Request] Categories and Personalization of Library

### ISSUE THREAD

**Issue by Harunyaanuwu** [inorichi/tachiyomi#3689]
## Why/User Benefit/User Problem
It's a bit difficult if you like to organize your library. For example, the categories can only be by the top right on the bottom of the search and sorting button. It would be nice if there would be folder-like has the same size of mangas and manhwas that would be under of categories so you can organize them by author, volumes (especially mangas from MyReadingManga), etc.
I think it's also good to personalize the background and color of bar and the font

## What/Requirements
There would be:
* Add button that would be under in a category to collage or organized your library more specifically. Like a folder that contains mangas and manhwa
* You can name/rename and add a photo as cover for every folder
* In More>Settings>General>Theme, you will be able to pick a color of choice for background when in Dark mode or not
* Time setting when to On/Off Dark mode and another color of choice to suit the background's and bars' color
* Or a On/Off of Dark mode button whenever/wherever you are (in library, browsing or looking what to read in a source extension, or while reading)

**Comment by arkon** [comment]
Effectively the same idea as #1803. Feel free to add your ideas about folders/etc. there.
