### ISSUE TITLE
[Feature Request/Bug] Wrong chapters

### ISSUE THREAD

**Issue by Harunyaanuwu** [inorichi/tachiyomi#3690]
## Why/User Benefit/User Problem
There are some mangas and manhwas containing shuffled and missing chapters. It can be sorted by but when reading, it will skip the chapter. I noticed while reading, I feel lost on the story and  exited the chapter noticed I skipped the continuation where I should be.

**Comment by scb261** [comment]
Use source that doesn't have missing chapters
> Disclaimer: Tachiyomi is not a content provider. We are not affiliated with or responsible for any source that is slow, down, or missing chapters.
