### ISSUE TITLE
[Feature Request] Add option to select all chapters between two selected chapters

### ISSUE THREAD

**Issue by BikramKumar6928** [inorichi/tachiyomi#3692]
## Why/User Benefit/User Problem
This feature can be used to select multiple consecutive chapters and perform actions like delete downloaded, mark as read, download chapters and other actions.

## What/Requirements
When 2 or more chapters have been selected, a third option along with" invert selection" and "select all" should appear with name "select interval". After selecting, there can be options like downloading selected (already present), deleting downloaded, marking as read(already present), etc.

**Comment by arkon** [comment]
Long press one chapter, then long press another.
