### ISSUE TITLE
[Bug] Trust anchor for certification path not found

### ISSUE THREAD

**Issue by AmbiTyga** [inorichi/tachiyomi#3698]
## Device information
* Tachiyomi version: 0.10.4
* Android version: Oreo
* Device: Samsung M30s

## Steps to reproduce
1. Go to any comic
2. Tap a chapter

### Expected behavior
The chapter should have shown.

### Actual behavior
A notification came with message ** Trust anchor for certification path not found**

**Comment by arkon** [comment]
What source?

**Comment by AmbiTyga** [comment]
I am not getting what you meant by source?

**Comment by scb261** [comment]
What extension do you use

**Comment by AmbiTyga** [comment]
Mangakisa and mangalife

**Comment by scb261** [comment]
Mangakisa is no longer accessible, they shut down their site, migtate to another source. Does the error also happen in mangalife?

**Comment by AmbiTyga** [comment]
I just changed my server, it seems like the problem was mangakisa not in mangalife, thank you for the help.
