### ISSUE TITLE
Problem with thumbnails at favorites

### ISSUE THREAD

**Issue by ZellFk** [inorichi/tachiyomi#370]
Hi, wanted to say tachiyomi's pretty great, but after the latest updates (after 2.2 and onwards) sometimes I have an issue of losing the image from some of the mangas added in my library (tried clearing the cache and database, but the problem still happens)

https://abload.de/img/screenshot_20160627-2uhum6.png

Version: v0.2.2-1
(Android 6.0)

**Comment by inorichi** [comment]
This issue was discussed and fixed here #334.

If you use clear cache from Android (not the one in the app's settings) it will redownload them. If you don't want to clear the entire cache, you can follow [these steps](https://github.com/inorichi/tachiyomi/issues/334#issuecomment-224048875)
