### ISSUE TITLE
[Feature Request] Download from Cached chapters instead of redundant download from the servers.

### ISSUE THREAD

**Issue by akza07** [inorichi/tachiyomi#3712]
## Why/User Benefit/User Problem
Being able to check a Manga out and realizing it's a good Manga after reading a few chapters, then going back to download them adds more load on server and additional internet/data usage to the user. Some people doesn't have enough bandwidth or have tight data restrictions.

## What/Requirements
When downloading chapters, if it's available in Cache, copy those local files instead of pulling from Servers. And may be an option to save the chapters automatically if they want to save chapters as they read.
Like... In Settings > Downloads > Save chapters as you read
Browse Cached chapters and save what user wants to keep or something similar.

Apologies for lack of clarity, still learning English.

**Comment by scb261** [comment]
It already downloads from cache when available. And I don't think that option *Save chapters as you read* is actually needed, there is request to download next chapter if you interested #3295

**Comment by CarlosEsco** [comment]
As stated it already tries to copy it from the cache.

https://github.com/inorichi/tachiyomi/blob/64bdfabbd850254184a0e603fcc5370427f1c8e3/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L352

**Comment by akza07** [comment]
Oh, Ok. I guess App removed the Manga I read from Cache before I could download.
