### ISSUE TITLE
[Bug] downloaded chapter deleted when change read statua

### ISSUE THREAD

**Issue by llreizh** [inorichi/tachiyomi#3714]
## Device information
* Tachiyomi version: 0.10.4
* Android version: pie
* Device: zb602kl

## Steps to reproduce
1. Highlight downloaded chapter
2. Change status from read to unread
3. Downloaded chapter deleted

### Expected behavior
Status change to unread

### Actual behavior
Chapter deleted

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
I assume you have the setting enabled for it to do that......

**Comment by llreizh** [comment]
Found it. Thank you
