### ISSUE TITLE
General Blurriness of Images when reading on some Phones

### ISSUE THREAD

**Issue by z3r0r4** [inorichi/tachiyomi#3716]
## Device information
* Tachiyomi version: v0.10.4
* Android version: 7.1.1
* Device: Elephone U

## Steps to reproduce
1. Open just about any Manga and view a panel

## Issue
The Images are blurry and fuzzy when zoomed out, which makes manga unreadable.
Zooming in closer changes this blurriness

![IMG-20200825-WA0002](https://user-images.githubusercontent.com/38572382/91230057-247cf380-e72b-11ea-8d91-ddea87f91984.jpg)

![IMG-20200825-WA0003](https://user-images.githubusercontent.com/38572382/91230062-28a91100-e72b-11ea-8118-d8a29ac2d80b.jpg)

**Comment by arkon** [comment]
The source is serving you low quality images then. Use a different source if needed.

**Comment by z3r0r4** [comment]
Sadly this is the case for every Source available @arkon 

The comparison between normal and zoomed in also shows that the blurriness is different depending on the zoom level

**Comment by arkon** [comment]
I don't think there's anything I can do about this unless it was a wider spread issue. It may be device dependant.

**Comment by z3r0r4** [comment]
it surly is device dependent since the same manga reads on my s10 just fine.

Any hints or ideas what could be causing it would be greatly appreciated anyways.

**Comment by arkon** [comment]
You could potentially flash a different ROM on it, although I doubt there's decent ROM support for a random offbrand device like that.

**Comment by z3r0r4** [comment]
There actually are, might be an idea to try.

Thank you
