### ISSUE TITLE
[Feature Request] BETTER WAY TO RECORD A TRACK

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3717]
I Think That You need a another option like this  Feature Where in It is easier to Record Tracking Count. 
---
Because What If I am Already In the Chapter 300.. And I Need to Scroll down Until I Reach 300.. 

I Think ypu need to Change The Tracking Count Into something like. This..
![PicsArt_08-26-09.41.48.jpg](https://user-images.githubusercontent.com/65703094/91245580-6421fa80-e780-11ea-93a0-997e07bbab2b.jpg)

So it is Easier to Record a Track..

**Comment by arkon** [comment]
Tap the number to edit it.

**Comment by ImPudding-tech** [comment]
Oh.....  I DIDNT KNOW THAT.. 🤣🤣🤣


THANKS
