### ISSUE TITLE
[Feature Request] Option to remove downloaded manga not in library

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3718]
## Why/User Benefit/User Problem
Reduce space consumes by manga that cannot read or will not read by the user. Sometimes when manga sources updated that removes chapter or changes it, it will stay in the downloads or when migrating and forgot to delete chapters. Currently it is hassle to clean one by one and checking if it is in library.

## What/Requirements
Make an option to clean unneeded downloaded manga. Make it separated/optional solely for cleaning downloads (different from `Clear chapter cache` and `Clear database`. If manga is in library, check if chapters is same as the updated fetch, if not, delete chapters. When manga is not in library, remove the dir and files of it.

**Comment by scb261** [comment]
#1767 #2445
