### ISSUE TITLE
[Feature Request] Have resume button in history actually resume

### ISSUE THREAD

**Issue by vongdong** [inorichi/tachiyomi#3719]
Can you please make the resume button in the history section actually resume from the last page rather than just say 'there's no next chapter' if its the latest or only chapter. It's a little annoying if i want to go back and re-read, I need to go into the title's page and select the chapter again.

**Comment by vengiare** [comment]
That's a silly suggestion. If you're re-reading a chapter then go to the manga page and select it. 

Resuming means picking where you left off, it shouldn't show a chapter you already read. Current behaviour is just accurate.

**Comment by vongdong** [comment]
How's that silly? What if I already read the latest chapter and want to go back and re-read from a certain part of it?

**Comment by arkon** [comment]
I wouldn't call it silly, but it wouldn't make sense for a resume button to restart something.

You can currently just tap the history item to open the full manga chapters list and open up any chapter from there.
