### ISSUE TITLE
BUG: crash fail from menu

### ISSUE THREAD

**Issue by VirusEcks** [inorichi/tachiyomi#372]
when pressing the options button at top of the page while reading i'm getting this: 
menu disappears and appears fast repeatedly and only way to stop is pressing back at the right moment

Version: r800
phone:sm-n910c android:6.0.1 rooted

**Comment by inorichi** [comment]
What is your OS? I know why that happens, but it shouldn't. I think the OS is at fault here.

**Comment by VirusEcks** [comment]
stock android v6.0.1

**Comment by inorichi** [comment]
http://stackoverflow.com/questions/2562248/how-to-keep-onitemselected-from-firing-off-on-a-newly-instantiated-spinner

Reason and a lot of solutions, I went with the one that disables the animation, but it seems it doesn't work on all the devices.

**Comment by NoodleMage** [comment]
@len I fixed this in my anilist commit with a custom widget [here](https://github.com/NoodleMage/tachiyomi/blob/backend_anilist/app/src/main/java/eu/kanade/tachiyomi/widget/SaneSpinner.kt) (inspired by [this](http://stackoverflow.com/questions/2562248/how-to-keep-onitemselected-from-firing-off-on-a-newly-instantiated-spinner/30555475#30555475)) Maybe that solves the problem?

**Comment by inorichi** [comment]
@NoodleMage wrong user :). I don't think it will work in his case. We are setting the listener after setting the initial value and it's still fired.

I think I'll go with a simple boolean flag, it's easier and we won't need to subclass `Spinner`.

**Comment by inorichi** [comment]
@VirusEcks Does it work with r801?

**Comment by VirusEcks** [comment]
yes for r801 the menu works fine
👍
