### ISSUE TITLE
[Feature Request] <comment section>

### ISSUE THREAD

**Issue by Wip-Sama** [inorichi/tachiyomi#3721]
## Why/User Benefit/User Problem
In every website the comment section is a very important part for the reading experience. 
The lack of this function can be hard to surpass for someon who is obsessed whit it... 

## What/Requirements
I think that adding a button on the end of every chapter that show you the comment sections will be a very good option for this features, obviously to enable this feature the extension need to be compatible with the site comment format.

**Comment by arkon** [comment]
#2203, kind of.

No plans to add this since it'd be wildly different for different websites and it's not worth maintaining in extensions.
