### ISSUE TITLE
"HTTP Error 600"

### ISSUE THREAD

**Issue by UrYaoiWaifu** [inorichi/tachiyomi#3726]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 10
* Device: LG Stylo 5

### Expected behavior
I was trying to download chapters from a manga, it should have downloaded them

### Actual behavior
It kept saying 'HTTP Error 600' and the chapters wouldn't download

## Other details
It would also say the same thing when I would try to read a chapter.)
It would say that the downloads are paused, but when I click resume it says HTTP Erro 600
![Screenshot_20200827-231654](https://user-images.githubusercontent.com/70361871/91524108-a7cd4f00-e8bb-11ea-84bb-82efbd79e55b.png)
This is what would pop up.
![Screenshot_20200827-231659](https://user-images.githubusercontent.com/70361871/91524169-cf241c00-e8bb-11ea-9783-440d468654d3.png)

**Comment by Zaneo** [comment]
Mangadex? If so, their servers are rebooting right now so don't expect to be able to access Mangadex for the next 24 hours. Try visiting their site, chapters don't load either.

**Comment by UrYaoiWaifu** [comment]
> Mangadex? If so, their servers are rebooting right now so don't expect to be able to access Mangadex for the next 24 hours. Try visiting their site, chapters don't load either.

Oh, i'm sorry for not knowing. I should have looked into it before repoting. Thanks for telling me!^^

**Comment by rubenz** [comment]
I am still having this problem too. When I openned from browser it is working but when openning from tachiyomi i got this error 600. Hope it can be fixed

**Comment by Zaneo** [comment]
![IMG_20200828_175536](https://user-images.githubusercontent.com/295949/91541738-bff2ac00-e957-11ea-8609-716f7a8caaa5.jpg)
It's a cache issue with mangadex, every different series, or client may experience different results until it stabilizes.

**Comment by rubenz** [comment]
If using regular browser (not from tachiyomi app). I tried random series all are working. If using tachiyomi always page not found or error 600.

![Screenshot_20200828-161216_Samsung Internet](https://user-images.githubusercontent.com/70370181/91544108-7307d900-e949-11ea-9e6b-8b1a2f86a5a7.jpg)

**Comment by az4521** [comment]
mangadex are blocking tachiyomi for now. they will unblock it in a few hours. wait until then or use a different source.

open your issue in the correct repository next time. inorichi/tachiyomi-extensions
