### ISSUE TITLE
[Feature Request] End to Endless Scroll

### ISSUE THREAD

**Issue by Ketchup1138** [inorichi/tachiyomi#3728]
## Why/User Benefit/User Problem
(explain why this feature should be added)
Why: It's hard to go back and find older manga

## What/Requirements
(explain how this feature would behave)

Can you add number to scroll like websites

![S00828-101034.jpg](https://user-images.githubusercontent.com/64573339/91532066-0b806800-e90e-11ea-9f36-af1c8b772fa1.jpg)

**Comment by arkon** [comment]
#407

**Comment by Ketchup1138** [comment]
sorry
