### ISSUE TITLE
[Feature Request] Anilist Custome List Tracker

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3729]
It is Posible yo Add the Custome List In The Anilist Tracker...

![Screenshot_20200828_181244_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/65703094/91550013-76579080-e95a-11ea-9443-fdc6f832c76b.jpg)

Not Only The Status

 But Also the Custome List

**Comment by arkon** [comment]
Considering that's not a concept available to the other trackers, no.
