### ISSUE TITLE
[Feature Request] feature where you can set how many you can download at a time

### ISSUE THREAD

**Issue by Supergene1** [inorichi/tachiyomi#3731]
---
 Sometime some chapter error and failed to download so you place it in the bottom to continue what your downloading or just redownload it. But if you can set your maximum download atleast if one particular chapter failed, the downloading will atleast not stop.

**Comment by CrepeTF** [comment]
You can't download multiple chapters at the same time from the same source so you don't get IP banned by source.

**Comment by CarlosEsco** [comment]
for reasons state above this is not being added
