### ISSUE TITLE
[Feature Request] Missing chapter indicators

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi#3732]
## Why/User Benefit/User Problem
Many sources have chapter gaps which users might not notice right away, causing possible problems and confusion for people who don't pay as much attention

## What/Requirements
An optional indicator that'd show around above the About section that'd indicate that there's possible chapters missing

From my understanding Tachiyomi can tell chapter numbers to some extent, obviously sources it can't tell chapters apart or even manga which use weird naming like 1.1, 1.2, etc. Would be exempt from this.
Taking the idea from MD's missing chapters feature, it's not perfect but gives you a quick look into missing chapters in 95% of manga.

**Comment by vongdong** [comment]
This feature feels a bit unnecessary given what's already there and using your brain a little bit. Just sort chapters by number and there's already an indicator for how many chapters are there so do a bit of maths and you'll see if there's a bunch of missing chapters or there's a few extras.
