### ISSUE TITLE
[Bug] file corruption

### ISSUE THREAD

**Issue by Celestialcelery** [inorichi/tachiyomi#3734]
## Device information
* Tachiyomi version: 0.10.4 stable
* Android version: 10
* Device: note 10+

## Steps to reproduce
1. Open "the villainess reverses the hourglass"
2. Go to chapter 42, page 14

### Expected behavior
Chapter should load and open normally 

### Actual behavior
Half the chapter did not load and was gray. 

## Other details
Additional details and attachments.
![Screenshot_20200830-080214_Tachiyomi](https://user-images.githubusercontent.com/70473823/91658788-5bd80100-ea99-11ea-85c4-c6433211f4ff.jpg)

**Comment by scb261** [comment]
#3573
