### ISSUE TITLE
 ERROR MANGALIB "Latest"

### ISSUE THREAD

**Issue by keke0202** [inorichi/tachiyomi#3737]
Hey. The last button on the Mangalib source doesn't work for me. 
Writes: "Attemp to invoke virtual method java.lang.String org.jsoup.nodes.Element.attr (java.lang.String) on ​​a null object reference".
We reinstalled the program, uninstalled Mangalib and installed it again, nothing helped. Is there anything you can do about this?
https://cdn1.savepice.ru/uploads/2020/8/31/909d5f78bf7b61457ec3169f8fcab49c-full.jpg

Thank you in advance.

**Comment by scb261** [comment]
Wrong repo, it should be in https://github.com/inorichi/tachiyomi-extensions
