### ISSUE TITLE
[Bug] download

### ISSUE THREAD

**Issue by momoshiromejias** [inorichi/tachiyomi#3739]
## Device information
* Tachiyomi version: 10.4
* Android version: 8.1.0
* Device: android

I downloaded a manga in mangahere, i haven't open it for weeks, when i click it the manga load and no longer seen as downloaded and i have to download it again yet when i see in tachiyomi mangahere folder the downloaded chapters are still there

**Comment by scb261** [comment]
Most probably source renamed chapters, compare the names in file manager and Tachiyomi

**Comment by momoshiromejias** [comment]
Yes, I tried Downloading 1 chapter and name file change, ia there a way to solve it sir? Like rening the name file to restore it, im ignorant regardi g this issues! Ty for your time sir

**Comment by momoshiromejias** [comment]
Yes, I tried Downloading 1 chapter and name file change, ia there a way to solve it sir? Like rening the name file to restore it, im ignorant regardi g this issues! Ty for your time sir

**Comment by scb261** [comment]
Right now you can't solve it inside Tachiyomi (there are 2 issues about it already #1767 #2445). You can either delete old chapters and redownload them, or rename chapters folders (not so easy if there is too much of them). You can also move it to local folder https://tachiyomi.org/help/guides/reading-local-manga/#reading-local-manga

**Comment by momoshiromejias** [comment]
> Right now you can't solve it inside Tachiyomi (there are 2 issues about it already #1767 #2445). You can either delete old chapters and redownload them, or rename chapters folders (not so easy if there is too much of them). You can also move it to local folder https://tachiyomi.org/help/guides/reading-local-manga/#reading-local-manga

Can i ask sir if i for example put it in local would there be a need to download it again or it would direcly show as downloaded?

**Comment by scb261** [comment]
Browse > Sources > Local source. There won't be *Downloaded* mark for each chapter, but they still will be available without Internet. Better discuss it on https://discord.gg/tachiyomi in #support channel.

**Comment by momoshiromejias** [comment]
THANK YOU SIR!!!
