### ISSUE TITLE
Browse Filter Missing

### ISSUE THREAD

**Issue by gasukadingin** [inorichi/tachiyomi#3740]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 10
* Device: Pocophone F1

## Steps to reproduce
1. Browse
2. Manganelo (other source is the same)
3. Latest
4. No Filter like the old version tachiyomi

## Issue/Request
No Filter when open all source like the old version of Tachiyomi

**Comment by scb261** [comment]
![image](https://user-images.githubusercontent.com/65343233/91738685-80c39580-ebb9-11ea-8924-f5dbfe1daf35.png)

**Comment by gasukadingin** [comment]
Thanks a lot. 🙏🙏
