### ISSUE TITLE
[Feature Request] Dual Screen/Foldable screen support 

### ISSUE THREAD

**Issue by Dalmahr** [inorichi/tachiyomi#3742]
---

Users will be able to see more than one page at once
Useful for users who have large screens like tablets in landscape mode, dual screen phones, folding phones. More of these types of devices are starting to come around. Microsoft has a SDK for their dual screen device. Unsure if others have similar. I know LG makes a dual screen device. Samsung.. And I think Xaomi have folding screens. 

On tablets in landscape mode or foldable screens you'd see 2 pages side by side. On dual screen phones you'd have one page on each screen.

**Comment by CarlosEsco** [comment]
falls under #149
