### ISSUE TITLE
Image Path Error

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi#3744]
## Device information
* Tachiyomi version: Preview r2671
* Android version: 10
* Device: Oneplus 8Pro

## Steps to reproduce
1. First step 
2. Second step

### Expected behavior
Just open OH漫画 (One漫画) and start reading

### Actual behavior
It does not open and it shows an error

## Other details
Additional details and attachments.
![Screenshot_20200902-130222](https://user-images.githubusercontent.com/59502042/91946792-001daa00-ed1d-11ea-8240-00adecf2a207.jpg)

**Comment by EricFoodTab** [comment]
Opened the site in webview,everything seem fine. so maybe there's a problem with the extension

**Comment by arkon** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4292
