### ISSUE TITLE
[Bug] My library is gone...

### ISSUE THREAD

**Issue by DemonicGod** [inorichi/tachiyomi#3746]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 10
* Device: Motorola g7 power

### Expected behavior
Library with manga is shown

### Actual behavior
"Your library is empty"

## Other details
![Screenshot_20200903-024308](https://user-images.githubusercontent.com/70672509/92057499-3f84de80-ed8f-11ea-8ae8-0494af4f23d4.png)

**Comment by arkon** [comment]
There's no useful information here. 

- I'm assuming it disappeared?
- Do you see anything in updates or history?
- Did this happen after an app or phone update?
- Do you use sketchy cleaner apps that either you installed or came with the phone?

**Comment by DemonicGod** [comment]
1 what information do you need? I'll provide what I can, however, I don't really know anything.

2 Yes, it just disappeared, it was working earlier the same day.

3 History and updates at empty as well.

4 No nothing was updated as far as I can see.

5 Well, I have a theme app that comes with a cleaner, but the cleaner has run before without affecting tachiyomi, plus the cleaner didn't run that day.

**Comment by arkon** [comment]
Were your settings lost too? Did you accidentally clear the app data at some point?

Unfortunately I can't really do anything without reproducible steps other than suggesting you to enable automatic backups in the future if you haven't already.
