### ISSUE TITLE
Portuguese (pt-PT) UI Translation

### ISSUE THREAD

**Issue by MrAmnesiac** [inorichi/tachiyomi#375]
I don't really understand github yet, but after seeing the Spanish translation I realized I could help too, maybe. So I translated it to Portuguese (Portugal).
`
:<resources>
    <string name="app_name">Tachiyomi</string>

    <string name="name">Nome</string>

    
    <string name="label_settings">Definições</string>
    <string name="label_download_queue">Fila de Transferências</string>
    <string name="label_library">A minha biblioteca</string>
    <string name="label_recent_manga">Lidos recentemente</string>
    <string name="label_recent_updates">Atualizações</string>
    <string name="label_catalogues">Catálogos</string>
    <string name="label_categories">Categorias</string>
    <string name="label_selected">Selecionado: %1$d</string>
    <string name="label_backup">Cópia de segurança</string>

    
    <string name="action_settings">Definições</string>
    <string name="action_filter">Filtro</string>
    <string name="action_filter_downloaded">Transferido</string>
    <string name="action_filter_unread">Não lido</string>
    <string name="action_filter_empty">Eliminar filtros</string>
    <string name="action_search">Procurar</string>
    <string name="action_select_all">Selecionar tudo</string>
    <string name="action_mark_as_read">Marcar como lido</string>
    <string name="action_mark_as_unread">Marcar como não lido</string>
    <string name="action_mark_previous_as_read">Marcar anteriores como lidos</string>
    <string name="action_download">Transferir</string>
    <string name="action_delete">Eliminar</string>
    <string name="action_update">Atualizar</string>
    <string name="action_update_library">Atualizar biblioteca</string>
    <string name="action_edit">Editar</string>
    <string name="action_add_category">Adicionar categoria</string>
    <string name="action_edit_categories">Editar categoria</string>
    <string name="action_rename_category">Renomear categoria</string>
    <string name="action_move_category">Mover para categorias</string>
    <string name="action_edit_cover">Alterar imagem de capa</string>
    <string name="action_sort_up">Ordem ascendente</string>
    <string name="action_sort_down">Ordem descendente</string>
    <string name="action_show_unread">Não lido</string>
    <string name="action_show_downloaded">Transferido</string>
    <string name="action_next_unread">Próximo não lido</string>
    <string name="action_start">Começar</string>
    <string name="action_stop">Parar</string>
    <string name="action_pause">Pausa</string>
    <string name="action_clear">Limpar</string>
    <string name="action_previous_chapter">Capítulo anterior</string>
    <string name="action_next_chapter">Capítulo seguinte</string>
    <string name="action_retry">Tentar novamente</string>
    <string name="action_remove">Remover</string>
    <string name="action_resume">Resumir</string>
    <string name="action_open_in_browser">Abrir no navegador de internet</string>
    <string name="action_display_mode">Mudar modo de visualização</string>
    <string name="action_cancel">Cancelar</string>
    <string name="action_sort">Ordenar</string>
    <string name="action_install">Instalar</string>

    
    <string name="deleting">A eliminar…</string>
    <string name="loading">A carregar…</string>

    
      
    <string name="pref_category_general">Geral</string>
    <string name="pref_category_reader">Leitor</string>
    <string name="pref_category_downloads">Transferências</string>
    <string name="pref_category_sources">Fontes</string>
    <string name="pref_category_sync">Sincronização</string>
    <string name="pref_category_advanced">Avançado</string>
    <string name="pref_category_about">Sobre</string>

      
    <string name="pref_library_columns">Número de manga por fila</string>
    <string name="portrait">Retrato</string>
    <string name="landscape">Paisagem</string>
    <string name="default_columns">Por defeito</string>
    <string name="pref_library_update_interval">Frequência de atualização da biblioteca</string>
    <string name="update_never">Manual</string>
    <string name="update_1hour">Hora à hora</string>
    <string name="update_2hour">A cada 2 horas</string>
    <string name="update_3hour">A cada 3 horas</string>
    <string name="update_6hour">A cada 6 horas</string>
    <string name="update_12hour">A cada 12 horas</string>
    <string name="update_24hour">Diariamente</string>
    <string name="update_48hour">A cada 2 dias</string>
    <string name="pref_library_update_restriction">Restrições sobre a atualização da biblioteca</string>
    <string name="pref_library_update_restriction_summary">Atualizar apenas quando se cumprem as condições</string>
    <string name="wifi">Wi-Fi</string>
    <string name="charging">A carregar</string>
    <string name="pref_update_only_non_completed">Atualizar apenas manga em curso</string>
    <string name="pref_auto_update_manga_sync">Sincronizar capítulos após leitura</string>
    <string name="pref_ask_update_manga_sync">Confirmar antes de atualização</string>
    <string name="pref_theme">Tema da aplicação</string>
    <string name="light_theme">Tema principal</string>
    <string name="dark_theme">Tema escuro</string>

      
    <string name="pref_fullscreen">Ocultar barra de estado</string>
    <string name="pref_lock_orientation">Bloquear orientação</string>
    <string name="pref_enable_transitions">Permitir transições</string>
    <string name="pref_show_page_number">Mostrar número de página</string>
    <string name="pref_custom_brightness">Usar brilho personalizado</string>
    <string name="pref_keep_screen_on">Manter ecrã ligado</string>
    <string name="pref_reader_navigation">Navegação</string>
    <string name="pref_read_with_volume_keys">Teclas de Volume</string>
    <string name="pref_read_with_tapping">Toque</string>
    <string name="pref_reader_theme">Cor de fundo</string>
    <string name="white_background">Branco</string>
    <string name="black_background">Preto</string>
    <string name="pref_viewer_type">Visualizador por defeito</string>
    <string name="default_viewer">Por defeito</string>
    <string name="left_to_right_viewer">Esquerda para Direita</string>
    <string name="right_to_left_viewer">Direita para Esquerda</string>
    <string name="vertical_viewer">Vertical</string>
    <string name="webtoon_viewer">Webtoon</string>
    <string name="pref_image_decoder">Descodificador de imagem</string>
    <string name="rapid_decoder">Rapid</string>
    <string name="skia_decoder">Skia</string>
    <string name="pref_image_scale_type">Tipo de escala</string>
    <string name="scale_type_fit_screen">Ajustar ao ecrã</string>
    <string name="scale_type_stretch">Esticar</string>
    <string name="scale_type_fit_width">Ajustar à largura</string>
    <string name="scale_type_fit_height">Ajustar à altura</string>
    <string name="scale_type_original_size">Tamanho original</string>
    <string name="scale_type_smart_fit">Ajuste inteligente</string>
    <string name="pref_zoom_start">Posição de zoom inicial</string>
    <string name="zoom_start_automatic">Automático</string>
    <string name="zoom_start_left">Esquerda</string>
    <string name="zoom_start_right">Direita</string>
    <string name="zoom_start_center">Centro</string>
    <string name="pref_rotation_type">Rotação</string>
    <string name="rotation_free">Livre</string>
    <string name="rotation_lock">Bloqueado</string>
    <string name="rotation_force_portrait">Forçar retrato</string>
    <string name="rotation_force_landscape">Forçar paisagem</string>

      
    <string name="pref_download_directory">Pasta de Transferências</string>
    <string name="pref_download_slots">Transferências em simultâneo</string>
    <string name="pref_download_only_over_wifi">Transferir apenas através Wi-Fi</string>
    <string name="pref_remove_after_marked_as_read">Eliminar ao marcar como lido</string>
    <string name="pref_remove_after_read">Eliminar depois de ler</string>
    <string name="cat_remove_after_read">Eliminar depois de ler</string>
    <string name="current_chapter">Capítulo atual</string>
    <string name="previous_chapter">Capítulo anterior</string>
    <string name="custom_dir">Pasta personalizada</string>

      
    <string name="languages">Idiomas</string>
    <string name="languages_summary">Seleciona em que idiomas mostras as fontes</string>
    <string name="accounts">Contas</string>

      
    <string name="services">Serviços</string>

      
    <string name="pref_clear_chapter_cache">Limpar a cache dos capítulos</string>
    <string name="used_cache">Usado: %1$s</string>
    <string name="cache_deleted">Cache limpa. %1$d ficheiros foram eliminados</string>
    <string name="cache_delete_error">Ocorreu um erro ao eliminar a cache</string>
    <string name="pref_clear_cookies">Limpar cookies</string>
    <string name="cookies_cleared">Cookies limpas</string>
    <string name="pref_clear_database">Limpar redundância da base de dados</string>
    <string name="pref_clear_database_summary">Eliminar manga não presente na biblioteca</string>
    <string name="clear_database_confirmation">Capítulos lidos e progresso em manga que não está na biblioteca será perdido. Deseja continuar?</string>
    <string name="clear_database_completed">Entradas eliminar</string>
    <string name="pref_show_warning_message">Mostrar avisos</string>
    <string name="pref_show_warning_message_summary">Mostrar mensagens de avisos durante a sincronização</string>
    <string name="pref_reencode">Recodificar imagens</string>
    <string name="pref_reencode_summary">Permitir recodificação se as imagens não poderem ser descodificadas. Para melhores resultados utilize Skia</string>

      
    <string name="version">Versão</string>
    <string name="build_time">Hora da compilação</string>
    <string name="pref_enable_automatic_updates">Procurar por atualizações</string>
    <string name="pref_enable_automatic_updates_summary">Procurar por atualizações automaticamente</string>
    
    <string name="pref_enable_acra">Enviar relatórios de erro</string>
    <string name="pref_acra_summary">Ajuda a corrigir qualquer erro. Não serão enviados dados sensíveis</string>

    
    <string name="login_title">Iniciar sessão para %1$s</string>
    <string name="username">Nome de utilizador</string>
    <string name="password">Password</string>
    <string name="show_password">Mostrar password</string>
    <string name="login">Iniciar sessão</string>
    <string name="login_success">Inicio de sessão bem sucedido</string>
    <string name="invalid_login">Inicio de sessão falhado</string>
    <string name="unknown_error">Erro desconhecido</string>

    
    <string name="library_search_hint">Titulo ou autor…</string>
    <string name="updating_category">A atualizar categoria</string>
    <string name="confirm_delete_manga">Eliminar manga selecionada?</string>

    
    <string name="source_requires_login">Esta fonte necessita que inicies a sessão</string>
    <string name="select_source">Selecionar a fonte</string>

    
    <string name="manga_detail_tab">Info</string>
    <string name="description">Descrição</string>
    <string name="ongoing">Em curso</string>
    <string name="unknown">Desconhecido</string>
    <string name="licensed">Licenciado</string>
    <string name="add_to_library">Adicionar à biblioteca</string>
    <string name="remove_from_library">Remover da biblioteca</string>
    <string name="manga_info_author_label">Autor</string>
    <string name="manga_info_artist_label">Artistas</string>
    <string name="manga_info_chapters_label">Capítulos</string>
    <string name="manga_info_status_label">Estado</string>
    <string name="manga_info_source_label">Fonte</string>
    <string name="manga_info_genres_label">Géneros</string>

    
    <string name="manga_chapters_tab">Capítulos</string>
    <string name="manga_chapter_no_title">Sem titulo</string>
    <string name="display_mode_chapter">Capítulo %1$s</string>
    <string name="chapter_downloaded">Transferido</string>
    <string name="chapter_queued">Em fila</string>
    <string name="chapter_downloading">A Transferir</string>
    <string name="chapter_downloading_progress">A Transferir (%1$d/%2$d)</string>
    <string name="chapter_error">Erro</string>
    <string name="fetch_chapters_error">Erro ao obter capítulos</string>
    <string name="show_title">Mostrar titulo</string>
    <string name="show_chapter_number">Mostrar número de capítulo</string>
    <string name="sorting_mode">Modo de organização</string>
    <string name="sort_by_source">Por fonte</string>
    <string name="sort_by_number">Por número de capítulo</string>
    <string name="manga_download">Transferir</string>
    <string name="download_1">Transferir próximo capítulo</string>
    <string name="download_5">Transferir próximos 5 capítulos</string>
    <string name="download_10">Transferir próximos 10 capítulos</string>
    <string name="download_all">Transferir tudo</string>
    <string name="download_unread">Transferir não lidos</string>
    <string name="confirm_delete_chapters">Tem a certeza que deseja eliminar os capítulos selecionados?</string>

    
    <string name="reading">A ler</string>
    <string name="completed">Completo</string>
    <string name="dropped">Abandonado</string>
    <string name="on_hold">Em espera</string>
    <string name="plan_to_read">Planeada a leitura</string>
    <string name="score">Avaliação</string>
    <string name="title_hint">Titulo…</string>
    <string name="status">Estado</string>
    <string name="chapters">Capítulos</string>

    
    <string name="dialog_remove_recently_description">Isto irá remover a data de leitura deste capítulo. Continuar?</string>
    <string name="dialog_remove_recently_reset">Repor todos os capítulos deste manga</string>

    
    <string name="downloading">A transferir…</string>
    <string name="download_progress">Transferido %1$d%%</string>
    <string name="chapter_progress">Página: %1$d</string>
    <string name="chapter_subtitle">Capítulo %1$s</string>
    <string name="no_next_chapter">Capítulo seguinte não encontrado</string>
    <string name="no_previous_chapter">Capítulo anterior não encontrado</string>
    <string name="decode_image_error">Imagem não pode ser carregada.\nPor favor tente alterar o descodificador de imagem ou selecione uma das seguintes opções</string>
    <string name="confirm_update_manga_sync">Atualizar último capítulo lido a %1$d nos serviços ativos?</string>
    <string name="viewer_for_this_series">Visualizador para esta serie</string>

    
    <string name="backup">Cópia de segurança</string>
    <string name="restore">Restaurar</string>
    <string name="backup_please_wait">Cópia de segurança em curso. Por favor aguarde…</string>
    <string name="backup_completed">Cópia de segurança restaurada com sucesso</string>
    <string name="restore_please_wait">Restaurando cópia de segurança. Por favor aguarde…</string>

    
    <string name="recent_manga_source">%1$s - Ch.%2$s</string>

    
    <string name="download_queue_error">Ocorreu um erro ao transferir capítulos. Poderá tentar novamente na secção das transferências</string>

    
    <string name="notification_update_progress">Progresso da atualização: %1$d/%2$d</string>
    <string name="notification_update_completed">Atualização completa</string>
    <string name="notification_update_error">Ocorreu um erro inesperado ao atualizar a biblioteca</string>
    <string name="notification_no_new_chapters">Sem novos capítulos encontrados</string>
    <string name="notification_new_chapters">Novos capítulos encontrados para:</string>
    <string name="notification_manga_update_failed">Falha ao atualizar ao manga:</string>
    <string name="notification_first_add_to_library">Por favor adicione a manga à sua biblioteca antes de fazer isto</string>
    <string name="notification_not_connected_to_ac_title">Sincronização cancelada</string>
    <string name="notification_not_connected_to_ac_body">O dispositivo não está ligado ao carregador</string>
    <string name="notification_no_connection_title">Sincronização cancelada</string>
    <string name="notification_no_connection_body">Ligação indisponível</string>

    
    <string name="file_select_cover">Selecionar imagem de capa</string>
    <string name="file_select_backup">Selecionar ficheiro de cópia de segurança</string>

    
    <string name="update_check_title">Nova atualização disponível!</string>
    <string name="update_check_confirm">Transferido</string>
    <string name="update_check_ignore">Ignorar</string>
    <string name="update_check_no_new_updates">Sem atualizações disponíveis</string>
    <string name="update_check_download_started">Transferência iniciada</string>
    <string name="update_check_look_for_updates">À procura de atualizações</string>

    
    <string name="update_check_notification_file_download">Transferir atualização</string>
    <string name="update_check_notification_download_in_progress">Transferência em curso</string>
    <string name="update_check_notification_download_complete">Transferência completa</string>
    <string name="update_check_notification_download_error">Erro na transferência</string>
    <string name="update_check_notification_update_available">Atualização disponível</string>

    
    <string name="description_backdrop">Imagem de capa de manga</string>
    <string name="description_cover">Imagem de capa de manga</string>

    
    <string name="information_no_downloads">Sem transferências</string>
    <string name="information_no_recent">Sem capítulos recentes</string>
    <string name="information_no_recent_manga">Sem manga lida recentemente</string>
    <string name="information_empty_library">Biblioteca vazia</string>

    
    <string name="download_notifier_title_error">Erro</string>
    <string name="download_notifier_unkown_error">Erro inesperado ao transferir capítulo</string>
    <string name="download_notifier_page_error">Página em falta na pasta</string>
    <string name="download_notifier_page_ready_error">Página não carregada</string>
    <string name="download_notifier_text_only_wifi">Sem ligação de Wi-Fi disponível</string>

</resources>`
It was pretty straight forward and I did my best, so I think it's error free, but it's just text on a notepad, it felt kinda prone to error.

**Comment by inorichi** [comment]
Thanks, I included it here 864f001

**Comment by Lurian** [comment]
I found really nice the translation to portuguese, but something is bugging me for a while:
<string name="default_viewer">Por defeito</string>
<string name="default_columns">Por defeito</string>

At least in Brazillian Portuguese I would translate "default" into "padrão" or "norma". "defeito" means "fault" for me. 
<string name="default_viewer">Por Padrão</string>
<string name="default_columns">Por Padrão</string>
Does "defeito" means "default" in European Portuguese @MrAmnesiac

**Comment by MrAmnesiac** [comment]
Yes @Lurian , it's the most common way of saying it here Portugal. Default also means failure in certain contexts.

Also, @inorichi, I'm also here to "update" the translation:
```xml
<resources>
    <string name="app_name">Tachiyomi</string>

    <string name="name">Nome</string>

    <!-- Activities and fragments labels (toolbar title) -->
    <string name="label_settings">Definições</string>
    <string name="label_download_queue">Fila de Transferências</string>
    <string name="label_library">A minha biblioteca</string>
    <string name="label_recent_manga">Lidos recentemente</string>
    <string name="label_recent_updates">Atualizações</string>
    <string name="label_catalogues">Catálogos</string>
    <string name="label_categories">Categorias</string>
    <string name="label_selected">Selecionado: %1$d</string>
    <string name="label_backup">Cópia de segurança</string>

    <!-- Actions -->
    <string name="action_settings">Definições</string>
    <string name="action_filter">Filtro</string>
    <string name="action_filter_downloaded">Transferido</string>
    <string name="action_filter_unread">Não Lido</string>
    <string name="action_filter_read">Lido</string>
    <string name="action_filter_empty">Remover filtro</string>
    <string name="action_search">Procurar</string>
    <string name="action_select_all">Selecionar tudo</string>
    <string name="action_mark_as_read">Marcar como lido</string>
    <string name="action_mark_as_unread">Marcar como não lido</string>
    <string name="action_mark_previous_as_read">Marcar anteriores como lidos</string>
    <string name="action_download">Transferir</string>
    <string name="action_delete">Eliminar</string>
    <string name="action_update">Atualizar</string>
    <string name="action_update_library">Atualizar biblioteca</string>
    <string name="action_edit">Editar</string>
    <string name="action_add_category">Adicionar categoria</string>
    <string name="action_edit_categories">Editar categorias</string>
    <string name="action_rename_category">Renomear categoria</string>
    <string name="action_move_category">Mover para categorias</string>
    <string name="action_edit_cover">Alterar imagem de capa</string>
    <string name="action_sort_up">Ordem ascendente</string>
    <string name="action_sort_down">Ordem descendente</string>
    <string name="action_show_unread">Não lido</string>
    <string name="action_show_downloaded">Transferido</string>
    <string name="action_next_unread">Próximo não lido</string>
    <string name="action_start">Começar</string>
    <string name="action_stop">Parar</string>
    <string name="action_pause">Pausa</string>
    <string name="action_clear">Limpar</string>
    <string name="action_previous_chapter">Capítulo anterior</string>
    <string name="action_next_chapter">Capítulo seguinte</string>
    <string name="action_retry">Tentar novamente</string>
    <string name="action_remove">Remover</string>
    <string name="action_resume">Resumir</string>
    <string name="action_open_in_browser">Abrir no navegador de internet</string>
    <string name="action_display_mode">Mudar modo de visualização</string>
    <string name="action_set_filter">Definir filtro</string>
    <string name="action_cancel">Cancelar</string>
    <string name="action_sort">Ordenar</string>
    <string name="action_install">Instalar</string>

    <!-- Operations -->
    <string name="deleting">A eliminar…</string>
    <string name="loading">A carregar…</string>

    <!-- Preferences -->
    <!-- Subsections -->
    <string name="pref_category_general">Geral</string>
    <string name="pref_category_reader">Leitor</string>
    <string name="pref_category_downloads">Transferências</string>
    <string name="pref_category_sources">Fontes</string>
    <string name="pref_category_sync">Sincronização</string>
    <string name="pref_category_advanced">Avançado</string>
    <string name="pref_category_about">Sobre</string>

    <!-- General section -->
    <string name="pref_library_columns">Número de manga por fila</string>
    <string name="portrait">Retrato</string>
    <string name="landscape">Paisagem</string>
    <string name="default_columns">Por defeito</string>
    <string name="pref_library_update_interval">Frequência de atualização da biblioteca</string>
    <string name="update_never">Manual</string>
    <string name="update_1hour">Hora à hora</string>
    <string name="update_2hour">A cada 2 horas</string>
    <string name="update_3hour">A cada 3 horas</string>
    <string name="update_6hour">A cada 6 horas</string>
    <string name="update_12hour">A cada 12 horas</string>
    <string name="update_24hour">Diariamente</string>
    <string name="update_48hour">A cada 2 dias</string>
    <string name="pref_library_update_categories">Categorias a incluir na actualizização global</string>
    <string name="all">Tudo</string>
    <string name="pref_library_update_restriction">Restrições sobre a atualização da biblioteca</string>
    <string name="pref_library_update_restriction_summary">Atualizar apenas quando se cumprem as condições</string>
    <string name="wifi">Wi-Fi</string>
    <string name="charging">A carregar</string>
    <string name="pref_update_only_non_completed">Atualizar apenas manga em curso</string>
    <string name="pref_auto_update_manga_sync">Sincronizar capítulos após leitura</string>
    <string name="pref_ask_update_manga_sync">Confirmar antes da atualização</string>
    <string name="pref_theme">Tema da aplicação</string>
    <string name="light_theme">Tema principal</string>
    <string name="dark_theme">Tema escuro</string>

    <!-- Reader section -->
    <string name="pref_fullscreen">Ocultar barra de estado</string>
    <string name="pref_lock_orientation">Bloquear orientação</string>
    <string name="pref_enable_transitions">Permitir transições</string>
    <string name="pref_show_page_number">Mostrar número de página</string>
    <string name="pref_custom_brightness">Usar brilho personalizado</string>
    <string name="pref_keep_screen_on">Manter ecrã ligado</string>
    <string name="pref_reader_navigation">Navegação</string>
    <string name="pref_read_with_volume_keys">Teclas de Volume</string>
    <string name="pref_read_with_tapping">Toque</string>
    <string name="pref_reader_theme">Cor de fundo</string>
    <string name="white_background">Branco</string>
    <string name="black_background">Preto</string>
    <string name="pref_viewer_type">Visualizador por defeito</string>
    <string name="default_viewer">Por defeito</string>
    <string name="left_to_right_viewer">Esquerda para Direita</string>
    <string name="right_to_left_viewer">Direita para Esquerda</string>
    <string name="vertical_viewer">Vertical</string>
    <string name="webtoon_viewer">Webtoon</string>
    <string name="pref_image_decoder">Descodificador de imagem</string>
    <string name="rapid_decoder">Rapid</string>
    <string name="skia_decoder">Skia</string>
    <string name="pref_image_scale_type">Tipo de escala</string>
    <string name="scale_type_fit_screen">Ajustar ao ecrã</string>
    <string name="scale_type_stretch">Esticar</string>
    <string name="scale_type_fit_width">Ajustar à largura</string>
    <string name="scale_type_fit_height">Ajustar à altura</string>
    <string name="scale_type_original_size">Tamanho original</string>
    <string name="scale_type_smart_fit">Ajuste inteligente</string>
    <string name="pref_zoom_start">Posição de zoom inicial</string>
    <string name="zoom_start_automatic">Automático</string>
    <string name="zoom_start_left">Esquerda</string>
    <string name="zoom_start_right">Direita</string>
    <string name="zoom_start_center">Centro</string>
    <string name="pref_rotation_type">Rotação</string>
    <string name="rotation_free">Livre</string>
    <string name="rotation_lock">Bloqueado</string>
    <string name="rotation_force_portrait">Forçar retrato</string>
    <string name="rotation_force_landscape">Forçar paisagem</string>

    <!-- Downloads section -->
    <string name="pref_download_directory">Pasta de Transferências</string>
    <string name="pref_download_slots">Transferências em simultâneo</string>
    <string name="pref_download_only_over_wifi">Transferir apenas através Wi-Fi</string>
    <string name="pref_remove_after_marked_as_read">Eliminar ao marcar como lido</string>
    <string name="pref_remove_after_read">Eliminar depois de ler</string>
    <string name="custom_dir">Pasta personalizada</string>
    <string name="disabled">Desativado</string>
    <string name="last_read_chapter">Último capítulo</string>
    <string name="second_to_last">Últimos dois capítulos</string>
    <string name="third_to_last">Últimos três capítulos</string>
    <string name="fourth_to_last">Últimos quatro capítulos</string>
    <string name="fifth_to_last">Últimos cinco capítulos</string>

    <!-- Sync section -->
    <string name="services">Serviços</string>

    <!-- Advanced section -->
    <string name="pref_clear_chapter_cache">Limpar a cache dos capítulos</string>
    <string name="used_cache">Usado: %1$s</string>
    <string name="cache_deleted">Cache limpa. %1$d ficheiros foram eliminados</string>
    <string name="cache_delete_error">Ocorreu um erro ao eliminar a cache</string>
    <string name="pref_clear_cookies">Limpar cookies</string>
    <string name="cookies_cleared">Cookies limpas</string>
    <string name="pref_clear_database">Limpar redundância da base de dados</string>
    <string name="pref_clear_database_summary">Eliminar manga não presente na biblioteca</string>
    <string name="clear_database_confirmation">Capítulos lidos e progresso em manga que não está na biblioteca será perdido. Deseja continuar?</string>
    <string name="clear_database_completed">Eliminar entradas</string>
    <string name="pref_show_warning_message">Mostrar avisos</string>
    <string name="pref_show_warning_message_summary">Mostrar mensagens de avisos durante a sincronização</string>
    <string name="pref_reencode">Recodificar imagens</string>
    <string name="pref_reencode_summary">Permitir recodificação se as imagens não puderam ser descodificadas. Para melhores resultados utilize Skia</string>

    <!-- About section -->
    <string name="version">Versão</string>
    <string name="build_time">Hora da compilação</string>
    <string name="pref_enable_automatic_updates">Procurar por atualizações</string>
    <string name="pref_enable_automatic_updates_summary">Procurar por atualizações automaticamente</string>
    <!-- ACRA -->
    <string name="pref_enable_acra">Enviar relatórios de erro</string>
    <string name="pref_acra_summary">Ajuda a corrigir qualquer erro. Não serão enviados dados sensíveis</string>

    <!-- Login dialog -->
    <string name="login_title">Iniciar sessão para %1$s</string>
    <string name="username">Nome de utilizador</string>
    <string name="password">Palavra-passe</string>
    <string name="show_password">Mostrar palavra-passe</string>
    <string name="login">Iniciar sessão</string>
    <string name="login_success">Início de sessão bem sucedido</string>
    <string name="invalid_login">Início de sessão falhado</string>
    <string name="unknown_error">Erro desconhecido</string>

    <!-- Library fragment -->
    <string name="library_search_hint">Título ou autor…</string>
    <string name="updating_category">A atualizar categoria</string>
    <string name="confirm_delete_manga">Eliminar manga selecionada?</string>

    <!-- Catalogue fragment -->
    <string name="source_requires_login">Esta fonte necessita que inicies a sessão</string>
    <string name="select_source">Selecionar a fonte</string>
    <string name="no_valid_sources">Por favor habilite pelo menos uma fonte valida</string>

    <!-- Manga info fragment -->
    <string name="manga_detail_tab">Informações</string>
    <string name="description">Descrição</string>
    <string name="ongoing">Em curso</string>
    <string name="unknown">Desconhecido</string>
    <string name="licensed">Licenciado</string>
    <string name="add_to_library">Adicionar à biblioteca</string>
    <string name="remove_from_library">Remover da biblioteca</string>
    <string name="manga_info_author_label">Autor</string>
    <string name="manga_info_artist_label">Artistas</string>
    <string name="manga_info_chapters_label">Capítulos</string>
    <string name="manga_info_status_label">Estado</string>
    <string name="manga_info_source_label">Fonte</string>
    <string name="manga_info_genres_label">Géneros</string>

    <!-- Manga chapter fragment -->
    <string name="manga_chapters_tab">Capítulos</string>
    <string name="manga_chapter_no_title">Sem título</string>
    <string name="display_mode_chapter">Capítulo %1$s</string>
    <string name="chapter_downloaded">Transferido</string>
    <string name="chapter_queued">Em fila</string>
    <string name="chapter_downloading">A Transferir</string>
    <string name="chapter_downloading_progress">A Transferir (%1$d/%2$d)</string>
    <string name="chapter_error">Erro</string>
    <string name="fetch_chapters_error">Erro ao obter capítulos</string>
    <string name="show_title">Mostrar título</string>
    <string name="show_chapter_number">Mostrar número de capítulo</string>
    <string name="sorting_mode">Modo de organização</string>
    <string name="sort_by_source">Por fonte</string>
    <string name="sort_by_number">Por número de capítulo</string>
    <string name="manga_download">Transferir</string>
    <string name="download_1">Transferir próximo capítulo</string>
    <string name="download_5">Transferir próximos 5 capítulos</string>
    <string name="download_10">Transferir próximos 10 capítulos</string>
    <string name="download_all">Transferir tudo</string>
    <string name="download_unread">Transferir não lidos</string>
    <string name="confirm_delete_chapters">Eliminar os capítulos selecionados?</string>

    <!-- MyAnimeList fragment -->
    <string name="reading">A ler</string>
    <string name="completed">Completo</string>
    <string name="dropped">Abandonado</string>
    <string name="on_hold">Em espera</string>
    <string name="plan_to_read">Planeada a leitura</string>
    <string name="score">Avaliação</string>
    <string name="title_hint">Título…</string>
    <string name="status">Estado</string>
    <string name="chapters">Capítulos</string>

    <!-- Dialog remove recently view -->
    <string name="dialog_remove_recently_description">Esta ação irá remover a data de leitura deste capítulo. Continuar?</string>
    <string name="dialog_remove_recently_reset">Repor todos os capítulos desta manga</string>

    <!-- Reader activity -->
    <string name="downloading">A transferir…</string>
    <string name="download_progress">Transferido %1$d%%</string>
    <string name="chapter_progress">Página: %1$d</string>
    <string name="chapter_subtitle">Capítulo %1$s</string>
    <string name="no_next_chapter">Capítulo seguinte não encontrado</string>
    <string name="no_previous_chapter">Capítulo anterior não encontrado</string>
    <string name="decode_image_error">Imagem não pôde ser carregada.\nPor favor tente alterar o descodificador de imagem ou selecione uma das seguintes opções</string>
    <string name="confirm_update_manga_sync">Atualizar último capítulo lido a %1$d nos serviços ativos?</string>
    <string name="viewer_for_this_series">Visualizador para esta série</string>

    <!-- Backup fragment -->
    <string name="backup">Cópia de segurança</string>
    <string name="restore">Restaurar</string>
    <string name="backup_please_wait">Cópia de segurança em curso. Por favor aguarde…</string>
    <string name="backup_completed">Cópia de segurança restaurada com sucesso</string>
    <string name="restore_please_wait">A restaurar cópia de segurança. Por favor aguarde…</string>

    <!-- Recent manga fragment -->
    <string name="recent_manga_source">%1$s - Cap.%2$s</string>

    <!-- Downloads activity and service -->
    <string name="download_queue_error">Ocorreu um erro ao transferir capítulos. Poderá tentar novamente na secção das transferências</string>

    <!-- Library update service notifications -->
    <string name="notification_update_progress">Progresso da atualização: %1$d/%2$d</string>
    <string name="notification_update_completed">Atualização completa</string>
    <string name="notification_update_error">Ocorreu um erro inesperado ao atualizar a biblioteca</string>
    <string name="notification_no_new_chapters">Sem novos capítulos encontrados</string>
    <string name="notification_new_chapters">Novos capítulos encontrados para:</string>
    <string name="notification_manga_update_failed">Falha ao atualizar a manga:</string>
    <string name="notification_first_add_to_library">Por favor adicione a manga à sua biblioteca antes de fazer isto</string>
    <string name="notification_not_connected_to_ac_title">Sincronização cancelada</string>
    <string name="notification_not_connected_to_ac_body">O dispositivo não está ligado ao carregador</string>
    <string name="notification_no_connection_title">Sincronização cancelada</string>
    <string name="notification_no_connection_body">Ligação indisponível</string>

    <!-- File Picker Titles -->
    <string name="file_select_cover">Selecionar imagem de capa</string>
    <string name="file_select_backup">Selecionar ficheiro de cópia de segurança</string>

    <!--UpdateCheck-->
    <string name="update_check_title">Nova atualização disponível!</string>
    <string name="update_check_confirm">Transferido</string>
    <string name="update_check_ignore">Ignorar</string>
    <string name="update_check_no_new_updates">Sem atualizações disponíveis</string>
    <string name="update_check_download_started">Transferência iniciada</string>
    <string name="update_check_look_for_updates">À procura de atualizações</string>

    <!--UpdateCheck Notifications-->
    <string name="update_check_notification_file_download">Transferir atualização</string>
    <string name="update_check_notification_download_in_progress">Transferência em curso</string>
    <string name="update_check_notification_download_complete">Transferência completa</string>
    <string name="update_check_notification_download_error">Erro na transferência</string>
    <string name="update_check_notification_update_available">Atualização disponível</string>

    <!--Content Description-->
    <string name="description_backdrop">Imagem de capa da manga</string>
    <string name="description_cover">Imagem de capa da manga</string>

    <!-- Information Text -->
    <string name="information_no_downloads">Sem transferências</string>
    <string name="information_no_recent">Sem capítulos recentes</string>
    <string name="information_no_recent_manga">Sem manga lida recentemente</string>
    <string name="information_empty_library">Biblioteca vazia</string>

    <!-- Download Notification -->
    <string name="download_notifier_title_error">Erro</string>
    <string name="download_notifier_unkown_error">Erro inesperado ao transferir capítulo</string>
    <string name="download_notifier_page_error">Página em falta na pasta</string>
    <string name="download_notifier_page_ready_error">Página não carregada</string>
    <string name="download_notifier_text_only_wifi">Sem ligação de Wi-Fi disponível</string>

</resources>
````

**Comment by inorichi** [comment]
Please submit a pull request. https://github.com/inorichi/tachiyomi/blob/master/app/src/main/res/values-pt/strings.xml

Click the edit icon and make your changes there.
