### ISSUE TITLE
[Feature Request] Bring back the ability to have only the version with the most chapters display

### ISSUE THREAD

**Issue by OkamiSenpaii** [inorichi/tachiyomi#3754]
---Bring back the ability to have only version with the most chapters display

## Why/User Benefit/User Problem
Helps organize versions from sources that have multiple, especially when the version at the top of the current list isn't the one that is updated anymore (quality of life in a way)

## What/Requirements
Same as it did in the previous versions, when a source has multiple versions for a manga it will only display the version with the most chapters/ most updated.

**Comment by arkon** [comment]
> Same as it did in the previous versions, when a source has multiple versions for a manga it will only display the version with the most chapters/ most updated.

This was never the case. If anything, this sounds like a source website issue.

**Comment by OkamiSenpaii** [comment]
It was in the settings of the app

**Comment by arkon** [comment]
Are you referring to source migration in J2K?

**Comment by joseph619** [comment]
I think he is talking about sort by Total chapters no longer working (for sources with dupes such as Mangadex and Mangapark)

**Comment by OkamiSenpaii** [comment]
Sorry if I'm making this confusing, I don't have the old version of the app anymore to make this more concise. But it would make sources with multiple dupes (version fox, version rock, version duck for example on manga park) and only display the version with the most chapters. I remember it specifically in the app's settings.

**Comment by arkon** [comment]
It's still in MangaPark's extension settings

**Comment by OkamiSenpaii** [comment]
shit, lol I swear I looked everywhere in the settings for it. Thank you sorry for the waste of time.
