### ISSUE TITLE
[Bug] extension install failed because of apk has been deleted during installation

### ISSUE THREAD

**Issue by rhjdvsgsgks** [inorichi/tachiyomi#3759]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 9
* Device: any device can be reproduced

## Steps to reproduce
1. use a 3rd part apk installer with install in background support
2. install extension in tachiyomi
3. cause of "background install", apk installer will return to tachiyomi during the installation
4. tachiyomi noticed return from apk installer, think installation is done, delete the apk
5. installation failed cause by apk has been deleted during installation

### Expected behavior
tachiyomi delete the apk when extension has been successfully installed

### Actual behavior
tachiyomi delete the apk when focus back to himself

## Other details
nope

**Comment by arkon** [comment]
This deviates from the intended and standardized Android workflow, so it's not something we'd intend on working around to support.
