### ISSUE TITLE
[Bug] <Manga description beside cover in a library no longer shows last updated and start date>

### ISSUE THREAD

**Issue by crusaside** [inorichi/tachiyomi#3761]
### Device information

Tachiyomi version: preview r2682
Android version: 10, realme UI 1.0
Device: realme 3 Pro

### Steps to reproduce

1.First step - click any title in your library
2.Second step - look at the information beside manga cover

### Expected behavior
The area beside cover earlier used to showthe start date and last updated date as well, in addition to the ones that are now shown( mentioned below).   please add that back if it's intended.

### Actual behavior

Now it only shows manga name, author, whether ongoing or completed, and extension source. 

## Other details

It helps us to know whether we should begin reading a manga by looking at the credibility of the source and the frequency of updating chapters. Thanks!

**Comment by arkon** [comment]
This is intentional as seeing the topmost chapter in the list gives the same information.
