### ISSUE TITLE
[Feature Request] An Extension README Dialogues with Markdown? 

### ISSUE THREAD

**Issue by DitFranXX** [inorichi/tachiyomi#3763]
Maybe this goes to 1.x proposal or like.
Related to : #1926 #2420 (Only opened issue)

Sorry that I'm write this at dawn.... Maybe it's too simple. If you think this issue is duplicated with related issues. Please close this.

## Why/User Benefit/User Problem
I want to share an extension explanation and change log to users who uses my extension.

## What/Requirements
I just thought this features when I see the [Magisk Manager](https://github.com/topjohnwu/Magisk)'s module READMEs.
It was Markdown. uses `io.noties.markwon` packages.

It looks like this. (from [this site](https://android.gadgethacks.com/how-to/magisk-101-install-magisk-modules-from-repo-third-party-sources-0179675/). I don;t have rooted phone right now.)
![image](https://user-images.githubusercontent.com/45893338/92332586-f21fae80-f0b9-11ea-867a-c51d2c8e64e6.png)

**Comment by arkon** [comment]
Throwing this into the 1.x suggestion bucket: https://github.com/tachiyomiorg/android-app/issues/10
