### ISSUE TITLE
[Feature Request] 2 Page Spread

### ISSUE THREAD

**Issue by dyan458** [inorichi/tachiyomi#3764]
## Why/User Benefit/User Problem
(explain why this feature should be added)

For those 2 page spread long arts in manga like Berserker, Chainsaw Man to view all art not just half 

## What/Requirements
(explain how this feature would behave)

It behaves like a book reader when it shows 2 pages instead of 1. You would be able to view spread pages easily without cuts on page end.

**Comment by kiriya-aoi** [comment]
https://github.com/inorichi/tachiyomi/issues/149
