### ISSUE TITLE
Question : re backs ups can they be merged

### ISSUE THREAD

**Issue by Pizz001** [inorichi/tachiyomi#377]
Just a question about importing backs up , 
i have 2 units using the app 1 is my phone and the 2nd one is my tablet , is it possible to merge the back up files when you import them
as i have different manga on the 2 units or will it just replace the files by over writing them ?

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by wopian** [comment]
Importing a backup will just add it to what you already have.

Don't know if it'll overwrite chapters read if both backup files contain the same manga.

**Comment by inorichi** [comment]
It merges manga and the read progress, but I can't say it's 100% reliable.
