### ISSUE TITLE
Preload

### ISSUE THREAD

**Issue by DraldAzrael** [inorichi/tachiyomi#3775]
please add feature (preload next chapter) while reading online

**Comment by scb261** [comment]
According to #2367 it's already preloading when you reach last 3 pages, but it actually preloads only chapter's metadata (like number of pages) when chapter transition is enabled, not pages itself. So maybe it should be labeled as bug

**Comment by lmj0011** [comment]
If you're normally reading while connected to wi-fi then see https://github.com/inorichi/tachiyomi/issues/3295
