### ISSUE TITLE
[Feature Request] Ability to select left, right, or middle for page number indicator

### ISSUE THREAD

**Issue by torga13** [inorichi/tachiyomi#3776]
I'm hoping that this can be addressed in a future Tachiyomi release.  

If using Tachiyomi on a phone with vanilla Android gesture navigation, the page number indicator is displayed slightly behind the navigation pill. I suppose another fix is to raise the page number indicator's height. But choosing right/left justification would be nice. 

Attached is a screenshot showing the issue. 
![Screenshot_20200909-213820](https://user-images.githubusercontent.com/71097616/92786931-865d7000-f35d-11ea-902a-c3715c3f8d58.png)

**Comment by arkon** [comment]
The pill normally shouldn't even be visible if you're using fullscreen mode.
