### ISSUE TITLE
[Bug] Downloads finish but _tmp suffix isn't removed

### ISSUE THREAD

**Issue by stevenx37** [inorichi/tachiyomi#3778]
## Device information
* Tachiyomi version: Preview r2682
* Android version: 11
* Device: Pixel 4a

## Steps to reproduce
1. Download a chapter
2. Open the chapter after downloader marks it as 'Downloaded'

### Expected behavior
Chapter loads from storage

### Actual behavior
Chapter starts loading the pages from network

## Other details
Few manga are affected and not all chapters of the mangas in question are affected.
So far it has happened with both Guya (English) and Mangadex extensions.
I've already tried clearing the chapter cache, app cache, cookies, and database. Refreshing the chapter list won't fix it. Happens on both Wifi/LTE. The issue always affects the same chapters and never the ones that are ok.
[Video 1 (Mega.nz)](https://mega.nz/file/VZBlWCII#3jlSRskjkRQ6K3-B8FyLvJOF4ewUHBs1ZVywvmj0lNM)
[Video 2 (Mega.nz)](https://mega.nz/file/pcZAmChY#pDL47Q3Tojo2C-pm5vFxfms4Trq_C2jOdh4qYdR1nnU)
[Screenshot (Guya)](https://user-images.githubusercontent.com/15038615/92908024-d850d500-f3f3-11ea-9d8f-eee77b4d3e5d.png)
[Screenshot (Mangadex)](https://user-images.githubusercontent.com/15038615/92907769-9cb60b00-f3f3-11ea-9721-fbdc3daa7090.png)
Android 11 might've broken something since the app was fine before updating.

**Comment by stevenx37** [comment]
Also noticed my file manager can't rename the _tmp folders but can rename the unaffected ones.

**Comment by stevenx37** [comment]
Okay definitely Android 11. Folder names with an apostrophe cannot be renamed by Tachiyomi or by any app (including the stock file manager). I'm not sure if a workaround can be implemented so I'll close this for now.

**Comment by stevenx37** [comment]
Any folders created inside the folder with an apostrophe cannot be renamed either.

@arkon or anyone else. For a workaround, I was thinking: the downloader does a one-time check to see if system can rename folders with apostrophes by creating an empty folder with an apostrophe and renaming it. If it fails, future downloads with the downloader should create a new folder (without _tmp), move the _tmp contents over, and delete the _tmp folder.

**Comment by CarlosEsco** [comment]
easier solution is just to add ' as reserved character and replace it with _ like the other non FAT32 compliant characters

**Comment by thenickdude** [comment]
This seems to be fixed in the Android 11 October security update. After manually deleting the old _tmp folders from previous attempts, I was able to download chapters with apostrophes in their names successfully.

**Comment by stevenx37** [comment]
Yep you're right, october ota fixed it.
