### ISSUE TITLE
[Feature Request] Request to add color inversion function

### ISSUE THREAD

**Issue by arithxp** [inorichi/tachiyomi#3785]
## Why/User Benefit/User Problem
(explain why this feature should be added)
I mainly read novels, but I would like to have a color inversion mode so that I can see them at night.

## What/Requirements
(explain how this feature would behave)
Color inversion mode

original image
![Screenshot_20200912-230848_Tachiyomi](https://user-images.githubusercontent.com/6009737/92997336-7e642280-f54d-11ea-9ae3-a3d52ae3428a.jpg)
color inversion image
![Screenshot_20200912-230848_Tachiyomi_color_inversion](https://user-images.githubusercontent.com/6009737/92997354-920f8900-f54d-11ea-8a20-780ae0e4ac8a.png)

Please add the color inversion function.
Thanks for reading.

**Comment by arkon** [comment]
You can just use the Android accessibility feature, which is also usually available as a quick settings toggle.

**Comment by arithxp** [comment]
> You can just use the Android accessibility feature, which is also usually available as a quick settings toggle.

Samsung Note 10 cannot be added to Quick Settings.

Therefore, when I read a novel, I have to press Settings-Accessibility-Improve visibility-Invert color.
Turn it off when I'm not reading a novel.
 
It is very uncomfortable. I am wondering why it is passive to add this function.
