### ISSUE TITLE
[Bug] Downloading in the library not working

### ISSUE THREAD

**Issue by Skarrum** [inorichi/tachiyomi#3786]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 10
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Select your desired manga in the library
2. Hit the download icon on the bottom left between the mark read and category icon.
![Screenshot_20200912-102743_Tachiyomi](https://user-images.githubusercontent.com/55517360/92998992-082ad600-f4e3-11ea-93fc-31aa00cb5506.jpg)

### Expected behavior
Manga should be downloaded.

### Actual behavior
Most of the time nothing happens.

## Other details
I've tried this in several categories, and using different sources just in case but it didn't help. Very occasionally it will work, but it seems almost random which manga will and won't download.
I've been tinkering around with it, so I'll add any new information I find.

Apologies I was misunderstanding the button. I assumed it meant download all, and not download unread. Meaning this is more of a feature request than a bug.

**Comment by scb261** [comment]
It downloads only unread chapters, can you confirm if it's the issue?

**Comment by Skarrum** [comment]
> It downloads only unread chapters, can you confirm if it's the issue?

Yeah, I had just figured that out. My bad.
