### ISSUE TITLE
[Mal] <invalid index 0, Size is 0>

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi#3790]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 6.0.1
* Device: Sony xz2

## Other details

So when i wanna chose chapter that's what happened! Every time!

**Comment by arkon** [comment]
What source?

**Comment by scb261** [comment]
It's myanimelist, try relogin

**Comment by shipoxx** [comment]
> It's myanimelist, try relogin

Thanks, it's work!
