### ISSUE TITLE
[Bug] <http error 429>

### ISSUE THREAD

**Issue by Zextokar** [inorichi/tachiyomi#3793]
Device information
Tachiyomi version: 0.10.4
Android version: 7
Device: alcatel
Steps to reproduce
First step
Second step
Issue/Request
al actualizar el directorio algunos mangas me dan error

Other details
![WhatsApp Image 2020-09-13 at 17 40 02](https://user-images.githubusercontent.com/70647980/93028258-ee73b680-f5e8-11ea-8dce-91e9ffce59b9.jpeg)

**Comment by arkon** [comment]
The site is throttling you because you're hitting it too much. Try again in smaller batches later.
