### ISSUE TITLE
[Bug] Preview build failed to check for new updates: "Chain validation failed"

### ISSUE THREAD

**Issue by taksumaki** [inorichi/tachiyomi#3795]
## Device information
* Tachiyomi version: Preview r2688
* Android version: 9.0
* Device: Redmi Note 6 Pro

## Steps to reproduce
1. First step
Press the button to check for updates.

2. Second step
Wait for the error message to appear.

### Expected behavior
---
Tell me a message if Tachiyomi is out of date and having to download the new version to always keep Tachiyomi in its latest version.

### Actual behavior
---
I only get an error Toast that says the following: Chain Validation Failed.

## Other details
Attached is a screenshot of how the error message looks and click to make it appear.
---
![IMG_20200913_160939](https://user-images.githubusercontent.com/56084970/93029936-49eb7780-f5dc-11ea-95be-225cebfb9333.jpg)

**Comment by arkon** [comment]
Looks like the certificate for kanade.eu expired a few hours ago.

> Expired: Sunday, September 13, 2020 at 16:19:58 Eastern Daylight Time

I'll ping @inorichi about it.

**Comment by arkon** [comment]
For those who may end up here before it's fixed, you can find the latest versions here: https://tachiyomi.kanade.eu/ (you'll need to ignore the certificate error)

Alternatively, see https://github.com/tachiyomiorg/android-app-preview/releases (the eventual replacement).
