### ISSUE TITLE
.yml file location

### ISSUE THREAD

**Issue by ChaotikZ** [inorichi/tachiyomi#380]
According to the tutorial provided in the YAML-Sources page, the .yml files (in this case, readcomiconline.yml) should be placed in **/sdcard/Tachiyomi/parsers/[site].yml**, but what about devices that use a different kind of path for the sdcard?

For example, my phone sdcard path is **/storage/0403-0201**, while the internal storage is **storage/emulated/0**, what am I supposed to do in this situation?

_Version: r805
Android 6.0.1 / Moto G 2014_

**Comment by inorichi** [comment]
It's the primary external storage directory, and that should be `/storage/emulated/0` in your case.

**Comment by ChaotikZ** [comment]
Ah, thanks for answering to quickly. Yeah, they finally showed up in the catalog after I moved the folder to that location.

I believe someone already reported this, but **readcomiconline.yml** is not working (a _page list empty_ error comes up) so I'll wait for the fix.

**Comment by inorichi** [comment]
Make sure you are using the last revision of that one, and the dev release (in 0.2.2 it won't work). It's working for me.

**Comment by j2ghz** [comment]
@ChaotikZ That error means they [readcomiconline] want you to solve a CAPTCHA. I don't think there will be a fix for that.

**Comment by inorichi** [comment]
I remember unflagging my IP by resolving it on my PC.

**Comment by ChaotikZ** [comment]
>I remember unflagging my IP by resolving it on my PC.

...aaaand it's working! Thanks for the tip, ino.

**Comment by travionfrancis** [comment]
How did you do it?

**Comment by ChaotikZ** [comment]
@travionfrancis
Go to http://readcomiconline.to, choose the comic, solve the captcha (I did all this on my phone browser), go back to Tachiyomi, and it should work.
