### ISSUE TITLE
[Bug] Blank Library/Update/History & Freezing When Entering Settings - Library

### ISSUE THREAD

**Issue by Schezuk** [inorichi/tachiyomi#3806]
## Device information
* Tachiyomi version: TachiyomiAZ 8.6.0
* Android version: 9

## Steps to reproduce
Open App.

### Expected behavior
The library should have shown up in less than 10 seconds, which is the case when I have a little bit fewer mangas in the library.

### Actual behavior
The library is blank. Update and History say there is nothing.
About 8 or 10 minutes later everything in the library contents suddenly appears and so is the case in Update and History.
If you switch to other apps and switch back, either nothing changes or the app reloads itself.

## Steps to reproduce
Open App and enter Settings - Library.

### Expected behavior
Settings appear.

### Actual behavior
The app will freeze. About 8 or 10 minutes later settings suddenly appear.
If you switch to Library after that, the library contents will appear in less than 10 seconds.

## Other details
There are 35,000 mangas in my library now. But this problem didn't appear when there were 30,000 of them. 
Is there some threshold that Tachiyomi cannot afford?

PS: Can you offer a debug option to import/export SQL to and from the SQLite database? 
That would be faster to backup and recover mangas without time-consuming recovery from the source, especially when it hides something regularly.

**Comment by arkon** [comment]
https://github.com/az4521/TachiyomiAZ

**Comment by Schezuk** [comment]
> https://github.com/az4521/TachiyomiAZ

Hey I believe it is not a TachiyomiAZ-specific problem.
