### ISSUE TITLE
Local mode.

### ISSUE THREAD

**Issue by Neta2603** [inorichi/tachiyomi#3808]
## Device information
* Tachiyomi version: 0.10.1
* Android version: 6.0
* Device: Nabi tablet fisherprice ( a bullshit).

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
I wanna learn what is the correct folder structure for pdf archive on local mode?

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/reading-local-manga/#reading-local-manga

PDFs aren't supported.
