### ISSUE TITLE
[Feature Request] Download compressed images

### ISSUE THREAD

**Issue by aozurei** [inorichi/tachiyomi#3809]
Please add feature to download the compressed image such as the mangadex's data saver feature. 
It would be helpful to download the compressed size image of full volume manga or manhwa. It will make less storage needed so the phone storage won't be full in a long time.

![20200916_105437](https://user-images.githubusercontent.com/71364698/93290742-98328d80-f80b-11ea-856f-384f813c8386.jpg)

I don't know whether the extension or the app that should be upgraded with this feature but this feature would be helpful. Maybe the app can auto compress the image as we download it. 

Sorry for my broken english

**Comment by jobobby04** [comment]
The mangadex extension already supports data saver

**Comment by aozurei** [comment]
Really? Is it auto or should i choose it manually?

**Comment by jobobby04** [comment]
Its in the extension's settings menu

**Comment by aozurei** [comment]
Ah yes, found it, thank you 😊
