### ISSUE TITLE
Possible bug : using minimizing or vpn services like opera max

### ISSUE THREAD

**Issue by VirusEcks** [inorichi/tachiyomi#381]
using opera max breaks the image load
after image starts loading it stops and you have to retry a lot for it to load correctly 

Version: r816
Samsung note 4 - android 6 stock

**Comment by inorichi** [comment]
The connection should be unstable. Once an exception is thrown (timeouts, server response...) the download has to start again from the beginning. 

I will investigate if there's a better network client configuration (like changing the default timeouts), but I'm closing this issue as it's not related to using a VPN.
