### ISSUE TITLE
Clear History

### ISSUE THREAD

**Issue by historiatachi** [inorichi/tachiyomi#3812]
Still no "Clear History" on the new update. Kinda disappointed..

**Comment by scb261** [comment]
You've already been told to not open duplicates for the same feature #1799 #3639

**Comment by historiatachi** [comment]
> You've already been told to not open duplicates for the same feature #1799 #3639

I did?

**Comment by CarlosEsco** [comment]
Yes you did

https://github.com/inorichi/tachiyomi/issues/3639#issuecomment-671278232

**Comment by arkon** [comment]
Submit a pull request if you want this ASAP. This is not a high priority item to me.
