### ISSUE TITLE
[Feature Request] <download feature : select and delete one or multiple or pause one or multiple ones +some stuff just read> here>

### ISSUE THREAD

**Issue by ALPHAwolfhi** [inorichi/tachiyomi#3813]
## Why/User Benefit/User Problem

because it's can give you the ability to do what you want with the download menu just like the ADM(It's a download mangere)

## What/Requirements

select chapter in the download menu (long press) option shows up [pause] [delete] my be add some Feature from other user if they ask

![Screenshot_20200916-204000](https://user-images.githubusercontent.com/71354209/93386331-719e4200-f85f-11ea-909b-0ae13f1e7f47.png)

**Comment by scb261** [comment]
#2860 - select multiple to cancel or reorder specific chapters.
#3688 - select multiple to pause/resume specific chapters.
