### ISSUE TITLE
[Bug] no seach bar

### ISSUE THREAD

**Issue by sexytama** [inorichi/tachiyomi#3814]
When i go to the extension look for manga there is no search bar
![Screenshot_20200917-051035_Tachiyomi](https://user-images.githubusercontent.com/71410405/93393197-a5e82180-f8a4-11ea-92d8-635c86259992.jpg)

**Comment by joseph619** [comment]
Tap on source name/icon instead of Latest

**Comment by sexytama** [comment]
> Tap on source name/icon instead of Latest
Thank You  it work
