### ISSUE TITLE
Sakha (Yakut) language

### ISSUE THREAD

**Issue by Baibal3** [inorichi/tachiyomi#3818]
Why Sakha(Yakut) language was not added?😐
![Screenshot_20200917-231240_Tachiyomi](https://user-images.githubusercontent.com/70212113/93484811-53a70f00-f93d-11ea-8d58-b0253746830d.jpg)
![Screenshot_20200917-231243_Tachiyomi](https://user-images.githubusercontent.com/70212113/93484983-851fda80-f93d-11ea-8d25-eb36fb5b2673.jpg)
![Screenshot_20200917-231458_Chrome](https://user-images.githubusercontent.com/70212113/93485011-8c46e880-f93d-11ea-828c-2081fe88cabc.jpg)

**Comment by arkon** [comment]
#3818
