### ISSUE TITLE
Crash on incomplete downloaded pages

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#382]
Crash on incomplete downloaded pages. Basically the image is downloaded partway but was stopped due to closing the app or intermittent connections and would cause the app to crash when reaching the page. The work around I've been doing is deleting the whole chapter or deleting the incomplete page with another app. 

Version: r0.2.2-1
Phone: Xiaomi Redmi 1s
Android version: 4.4.4

**Comment by inorichi** [comment]
I think it won't crash anymore (in dev).

**Comment by uenoshita** [comment]
Have been using version r820 and haven't experienced the crash anymore.
