### ISSUE TITLE
[Feature Request] Multiple migrate

### ISSUE THREAD

**Issue by VuNguyenLong** [inorichi/tachiyomi#3823]
## Why/User Benefit/User Problem
If some source went down, i would like to move all manga that related to that source to another. But it become such a time consumed task to move manga one by one cause the number of manga (about 100 and no one would be happy to move them).

## What/Requirements
I would like to see if is there any way to solve this problem. But some how, select all of them then move to another source is more convenient.

**Comment by scb261** [comment]
Duplicate of #1729
