### ISSUE TITLE
[Feature Request] <Write short description here>

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#3824]
## Why/User Benefit/User Problem
On latest beta manga view has been changed and now in library / tracking / webview are more visible : 

![Screenshot_20200920-091436](https://user-images.githubusercontent.com/3684177/93705946-01731300-fb22-11ea-8f21-8e4e84b12b16.jpg)

Still it feels there is a lost of wasted space. It would be good and fit well to add category shortcut instead of having it in 3 dots menu.

## What/Requirements
Add a button between library and tracking to edit categories.
Categories are related somewhat to library.  Same for tracking but it is also related to internet and it is more logical to have it near webview.

**Comment by joseph619** [comment]
You need to open a new ticket, make sure to fill in stuff correctly next time

**Comment by Matth7878** [comment]
Do not know if anybody would read this but not should have a delay... I instantly picked up I forgot about title and corrected it as soon as I published but it was too late...
It would be nice to allow a 5 minutes delay before bot taking action.
