### ISSUE TITLE
[Feature Request] Add category button in manga view

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#3825]
## Why/User Benefit/User Problem

On latest beta manga view has been changed and now in library / tracking / webview are more visible :

![Screenshot_20200920-091436](https://user-images.githubusercontent.com/3684177/93706202-3d0edc80-fb24-11ea-8478-e9d942e49c7a.jpg)

Still it feels there is a lost of wasted space. It would be good and fit well to add category shortcut instead of having it in 3 dots menu.

## What/Requirements

Add a button between library and tracking to edit categories.
Categories are related somewhat to library. Same for tracking but it is also related to internet and it is more logical to have it near webview.

**Comment by scb261** [comment]
You can long tap "In library"

**Comment by Matth7878** [comment]
@scb261 ha didn't knew that.
It's hardly discoverable, so I think it would be better to have it as a button and not in 3 dots menu. Still it's nice to know there is some kind of shortcut. 🙂

**Comment by arkon** [comment]
I'm actually a bit iffy on this after trying it since:

- It isn't _that_ commonly used
- It increases the likelihood of pushing text to 2 lines in some buttons, which looks bad

**Comment by arkon** [comment]
Despite the thumbs down reaction, it still visually looks really bad. Not going to do this.

**Comment by Pxeexe** [comment]
Sorry boy i just confused


вс, 18 окт. 2020 г., 19:28 arkon <notifications@github.com>:
