### ISSUE TITLE
[Bug] Random crashes when reading local mangas

### ISSUE THREAD

**Issue by jorel221** [inorichi/tachiyomi#3828]
---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 7.1.1
* Device: Samsung Galaxy J5 2016 J510MN

## Steps to reproduce
1. Start reading any local manga
2. Continue reading, scroll fast.

### Expected behavior
Continuous reading without crashes.

### Actual behavior
Crashes at random times.

## Other details
I've tested almost every version of tachiyomi including the forks, all versions that were released after 0.7.4 have this problem. Sometimes it crashes after a few minutes, sometimes it takes more time, it never crashed reading from online sources, though. Also the pages transition isn't smooth, it doesn't pre load the next pages. The version 0.7.4 is the last version without this issues, it's also the last version with image decoder option (Image, Rapid, Skia), so I think the problem is the new decoder. I'm using 0.7.4 to read local mangas but I really miss one feature wich is the chapter transition, at the end of every chapter. Can you consider making a special version with Rapid or Skia as image decoder?

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by jorel221** [comment]
[bugreport.zip](https://github.com/inorichi/tachiyomi/files/5264404/bugreport.zip)

**Comment by arkon** [comment]
That seems to be a system dump rather than crash logs.

**Comment by jorel221** [comment]
Sorry, I tried with adb this time.
[j5problem.txt](https://github.com/inorichi/tachiyomi/files/5267791/j5problem.txt)

**Comment by blaxcky** [comment]
Any new info about this problem? I have the exact same problem, it's reproducible.

**Comment by arkon** [comment]
@blaxcky Please provide crash logs.

**Comment by jorel221** [comment]
Hi, I tried to get the  crash logs using adb, is it okay?
Here:
[j5problem.txt](https://github.com/inorichi/tachiyomi/files/5580386/j5problem.txt)

**Comment by arkon** [comment]
I was hoping to get logs from someone else too.

**Comment by jorel221** [comment]
Ah, got it. Btw I've installed a custom rom (Viper OS, android 9) and the apps stopped crashing. But the reading in webtoon mode still isn't as fluid as in 0.7.4. I don't know if this occurs because it's a low end phone or incompatibility with the new image decoder, sometimes when it's changing to the next page it shows the backgroud color (black or white) until the next page is ready. It's for less than a second but it's still annoying. It'd be great if you could make a new version with any of the old decoders (rapid or skia),

**Comment by jorel221** [comment]
Another thing, I've tried slicing the webtoon's pages in many different heights: 200, 300, 500, 700, 1000, 1300, 2400... Also tried to compress the image into many types (jpg png, webp) but nothing solved this bug.

**Comment by arkon** [comment]
You can open another issue for that, but I doubt it'd get addressed. It's probably the view recycling rather than the image decoding, and it's not worth addressing at this point since I'd rather invest the time into other things like the app rewrite.

**Comment by jorel221** [comment]
Thanks! I will do that.
