### ISSUE TITLE
[Bug] < manga search error>

### ISSUE THREAD

**Issue by Zextokar** [inorichi/tachiyomi#3831]
## Device information
* Tachiyomi version: 0.10.5 creo 
* Android version: 7
* Device: alcatel

## Steps to reproduce
1. First step
2. Second step

### Expected behavior

It should not give an error when updating that I think

### Actual behavior
I get an error when updating my directory even if I change the extension or migrate the manga nothing works not even mimanganu does this happen

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
What error do you get?

**Comment by Zextokar** [comment]
http error 429

**Comment by CarlosEsco** [comment]
429 is you are being rate limited.  My guess is you are slamming the website.  How many manga and are they all on one source?

**Comment by Zextokar** [comment]
there are 10 sleeves per directory and I have 3 directories

**Comment by CarlosEsco** [comment]
sleeves? directories?  10 manga per a category with 3 categories?

**Comment by Zextokar** [comment]
Yes

**Comment by CarlosEsco** [comment]
What source are these manga on?

**Comment by Zextokar** [comment]
son de tumangaonline y lectortmo

**Comment by scb261** [comment]
Did the error happen as soon as you changed extension, or was it after some time of usage? You have about 30 manga in your library, right? How often do you update your library? How many chapters did you download recently?

**Comment by Zextokar** [comment]
the error occurs at the time after changing the extension, if I have around 30 sleeves, I update it every 2 or 3 days I don't download them I read them online

**Comment by scb261** [comment]
Your first issue was about tumangaonline, so I guess you're using only lectortmo now? Can you check update log and say what source gives 429 error now? Or just post screenshot of update log.

**Comment by Zextokar** [comment]
![WhatsApp Image 2020-09-22 at 16 59 37](https://user-images.githubusercontent.com/70647980/93931317-063bf080-fcf5-11ea-9b99-9e7883e832c3.jpeg)

**Comment by CarlosEsco** [comment]
my guess you are ip banned by lectormanga.  try using a different network to see if it works

**Comment by Zextokar** [comment]
I have already been banned from the IP before but the problem remains the same after they banned me

**Comment by CarlosEsco** [comment]
if they banned you we cant control that.  Thats not a tachi issue at that point.
