### ISSUE TITLE
[Feature Request] <An option to lower image resolution>

### ISSUE THREAD

**Issue by kuroBi99** [inorichi/tachiyomi#3839]
---

## Why/User Benefit/User Problem
(Adding an option to lower image resolution can reduce the image loading time dramatically, thus users who have limited data/Users who have slow internet will benefit from this feature )

## What/Requirements
(I believe This should be in form of an option that's activated by the user manually in settings, it would be best if the option come in the form of ORIGINAL SIZE/FHD/HD/SD so that users can select their preferred mode )

**Comment by scb261** [comment]
> Adding an option to lower image resolution can reduce the image loading time dramatically, thus users who have limited data/Users who have slow internet will benefit from this feature

It's impossible unless a site supports it. And if it does, it either already have been added to extension's settings, or should be requested on extensions repository.

There is also unfinished PR #1526 to compress images when downloading, but it will only save storage space and not mobile data. And it will not reduce loading time.
