### ISSUE TITLE
[Bug] Failed to load downloaded chapter

### ISSUE THREAD

**Issue by LuthfiKun** [inorichi/tachiyomi#3840]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 11
* Device: Pixel 3

## Steps to reproduce
1. Go to Musume no Tomodachi on MangaDex
2. Download the chapter(s) translated by Daphie's
3. Open the downloaded chapter(s)

### Expected behavior
It should loads the downloaded chapter(s) from the internal storage.

### Actual behavior
It's trying to fetch the chapter(s) directly from the internet.

## Other details
[Here's video](https://youtu.be/Zc7VUqgC26E)

Looking at the download directory, the folder name still have _tmp suffix on it even though on the app says the chapter's already downloaded. Deleting the _tmp suffix by renaming the folder gives access denied error. After some more digging around, this seems to happen with any chapter with (') regardless whether it's on the chapter or group name. Maybe it's something to do with Android 11 since I just updated to it this morning and don't have the same issue with Android 10 before.

**Comment by scb261** [comment]
#3778 is the same issue but closed by the author. He said it's android 11 issue and he can't rename it even with stock file manager

**Comment by LuthfiKun** [comment]
> #3778 is the same issue but closed by the author. He said it's android 11 issue and he can't rename it even with stock file manager

Ah I was searching only on open issues. I'll close this one too then.
