### ISSUE TITLE
[Feature Request] Update Global search layout to match Library and Browse 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3841]
## Why/User Benefit/User Problem
Currently, Global search doesn't show the full title of the manga as it should in Comfortable grid, or the rounded thumbnails in Library and Browse.

## What/Requirements
Update Global search thumbnail layout to match that of Library and Browse; display the fulll title in Comfortable grid and rounded thumbnails.

**Comment by ghostbear** [comment]
If I understood this correctly, does this fix the issue? 
<img src="https://user-images.githubusercontent.com/6576096/95013118-5e042100-063e-11eb-919c-43fbf56c768a.png" data-canonical-src="https://user-images.githubusercontent.com/6576096/95013118-5e042100-063e-11eb-919c-43fbf56c768a.png" width="300" />

**Comment by joseph619** [comment]
Yeah something like that.  Might also want to remove the card background for consistency (Browse removed it recently)
