### ISSUE TITLE
[Feature Request] Being able to reach read chapters when unread filter is on

### ISSUE THREAD

**Issue by pig-cop** [inorichi/tachiyomi#3844]
This was discussed before but this time I have a different suggestion.
What about letting the user go back to read chapters even when the read chapters are filtered out?

As it is now if I enable the unread filter I get what I want: seeing on top the last chapter I'm in.
But when I enter the chapter if I go back some pages to read a bit of the previous chapter it just says "There's no previous chapter" as if it doesn't exist.
If you think about it it doesn't makes much sense even if I'm aware there's some technical reason for it I guess.

**Comment by scb261** [comment]
More > Settings > Reader > Skip filtered chapters / Skip chapters marked read

**Comment by pig-cop** [comment]
Oh my god, now I feel stupid.
Been using Tahiyomi for years and never noticed there was an option for this, absolute gold.
Thank you @scb261 !!!

**Comment by CarlosEsco** [comment]
skip filtered was added more recently.  skip read has been there for a good while
