### ISSUE TITLE
[Feature Request] <In-app source report>

### ISSUE THREAD

**Issue by kuroBi99** [inorichi/tachiyomi#3845]
---
## Why/User Benefit/User Problem
(A feature to report sources inside the app with a brief description, it can have restrictions making only those who has latest update be able to fill in report. This feature will contribute to the overall stability of the app and assuring a faster fix for nonfunctioning not working sources by a faster report from users who are not a member in github or users who don't have github account.)

## What/Requirements
(I imagine it to work by long pressing the source extension and be an option to choose, then after choosing the option of report a window will open to describe the nature of the problem)

**Comment by arkon** [comment]
We're not really willing to spin up the infrastructure for a reporting system, especially one that'd prevent spam. Requiring people to sign up and do it on GitHub is good for reducing spam.
