### ISSUE TITLE
[Feature Request] Discord Comment toggleable

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#3846]
## Why/User Benefit/User Problem
It's annoying every time you try to directly share the page of a manga on discord, instead of downloading first, you need to delete the automatic comment.
![20200925_165920](https://user-images.githubusercontent.com/22413659/94283025-cd985300-ff50-11ea-8ecc-27c440ad35ff.jpg)

## What/Requirements
Either delete or make the feature toggleable in options.

**Comment by CarlosEsco** [comment]
I see no reason why it should be removed as it provided information on where the image can be found

**Comment by arkon** [comment]
Not worth making this a setting since it takes 1 second to remove it yourself.

**Comment by bb010g** [comment]
When sharing to apps like Telegram, there's no opportunity to edit the text before it's been sent. You'd have to edit the post after it's been sent to replicate the Discord workaround.

**Comment by 9ary** [comment]
> Not worth making this a setting since it takes 1 second to remove it yourself.

Most of the time I don't want the comment to be attached. Having to remove it every time is a pain, while adding an option to Tachiyomi is trivial. The benefits outweigh the cost by a long shot.

> When sharing to apps like Telegram, there's no opportunity to edit the text before it's been sent. You'd have to edit the post after it's been sent to replicate the Discord workaround.

+1, I also use Telegram and this is very annoying. The chances of getting *them* to do anything about it are slim considering the dev for the Android app is a prick who doesn't accept any bug reports and wouldn't even release the source code if his employer didn't force him to.

**Comment by CarlosEsco** [comment]
@9ary  i'm locking this, but what are you even talking about?  Telegram source code is open source https://github.com/DrKLO/Telegram
