### ISSUE TITLE
[Bug] "# chapters" bar in Manga info functions the same as the "Filter" chip

### ISSUE THREAD

**Issue by Doomsdayrs** [inorichi/tachiyomi#3847]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: OP6

## Steps to reproduce
1. Go to manga info for a manga
2. Click the space next to the filter button

### Expected behavior
Nothing

### Actual behavior
Opened up filter menu

## Other details
[Video](https://cdn.discordapp.com/attachments/349436576037732355/759150352305225820/ScreenRecord-20200925-163141.mp4)

**Comment by arkon** [comment]
It's intentional so it's easier to open.
