### ISSUE TITLE
[Bug] Manga Chapter Filter improper overlay of navigation buttons

### ISSUE THREAD

**Issue by Doomsdayrs** [inorichi/tachiyomi#3848]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: OP6

## Steps to reproduce
1. Open up manga info
2. Click filter
3. Notice space below filters slide

### Expected behavior
Filters slide should either cover up nav button or not make nav buttons invisible

### Actual behavior
Nav buttons are invisible, but can still be pressed, with an obnoxious wasted space

## Other details
[Video](https://cdn.discordapp.com/attachments/349436576037732355/759154092538462218/ScreenRecord-20200925-164648.mp4)

**Comment by h4rz** [comment]
Assign this issue to me. I can fix it. I have worked on a similar issue.

**Comment by arkon** [comment]
@h4rz Go for it.

**Comment by h4rz** [comment]
@arkon, Fixed! Check it once - #3874

**Comment by h4rz** [comment]
Well, it took me a few days when I had first encountered this issue. 😅
