### ISSUE TITLE
[Bug] Downloads stuck in queue state

### ISSUE THREAD

**Issue by rlewkowicz** [inorichi/tachiyomi#3850]
## Device information
* Tachiyomi version: v0.10.5
* Android version: Nougat 
* Device: Bluestacks on Windows

## Steps to reproduce
1. Use any source, I use mangadex
2. Find a manga, I use Kanojo, Okarishimasu
3. Download all
4. Let it start downloading, after it's finished one or so, close the app. 
5. Open the app. All downloads are now stuck in a queue state with no way to recover

### Expected behavior
One would hope it would resume, or at least give me an option to manually resume or clear failed state

### Actual behavior
Nothing happens. It just is stuck in queued state

**Comment by arkon** [comment]
Can you not resume from the download queue?

**Comment by rlewkowicz** [comment]
Where is that located? An android download queue or a native queue to the application?

**Comment by rlewkowicz** [comment]
It's under more, I'm a dunce, apologies

**Comment by arkon** [comment]
You can also tap the download notification, if that's still there.
