### ISSUE TITLE
[Bug] Content cut off at the bottom for filter sheet slightly

### ISSUE THREAD

**Issue by CrepeTF** [inorichi/tachiyomi#3854]
When looking through genres on source filter sheet, you see the stuff is cut off I guess.

![Screenshot_20200927-203626__01](https://user-images.githubusercontent.com/70870719/94374144-31ae4900-0102-11eb-91c0-a0c18f99fa0e.jpg)

---

## Device information
* Tachiyomi version: Preview r2734
* Android version: 10
* Device: OnePlus 6t

## Steps to reproduce
1. Open source filter sheet
2. Have eyes

### Expected behavior
Content is there

### Actual behavior
It isn't there

## Other details
Fuck sizurpp

**Comment by arkon** [comment]
Not very good steps to reproduce...

**Comment by TheUnlocked** [comment]
I believe they're referring to the tiny gap in the bottom if you expand the filter sheet and scroll such that something is half-way across the navigation bar.

What it should look like:
![image](https://user-images.githubusercontent.com/10186337/94893970-40b43480-043d-11eb-9945-25e9f1131ed5.png)

What it actually looks like:
![image](https://user-images.githubusercontent.com/10186337/94894097-87099380-043d-11eb-877d-9ef9dfc8da29.png)

I've made a fix and will PR shortly.

**Comment by CrepeTF** [comment]
Absolute legend
