### ISSUE TITLE
[Feature Request] add a pin tab for currently read manga 

### ISSUE THREAD

**Issue by losav0** [inorichi/tachiyomi#3856]
---

## Why/User Benefit/User Problem
this feature should be added so users dont have to scroll far down to their history or their list.

## What/Requirements
this would be put somewhere in the recents tab

**Comment by scb261** [comment]
Do you know about categories? https://tachiyomi.org/help/guides/categories/

**Comment by CarlosEsco** [comment]
yea just add the manga to a currently reading category
