### ISSUE TITLE
[Feature Request] Extensions root install

### ISSUE THREAD

**Issue by ruffi123456789** [inorichi/tachiyomi#3859]
## Why/User Benefit/User Problem
Always updating extensions takes time and can't be done in background. Implementing this would then afterwards save some accumulated time (probably not much if you're not updating often/don't have many extensions, etc...)

## What/Requirements
I would just make an toggle in Settings to enable/disable installing .apks with superuser commands, so it can be installed in the background without having to interrupt the user experience (for example: SAI, Titanium backup and probably many more).
Afterwards you could even add something to automatically update extensions (every app launch/once a day/once a week/etc)

Isn't really important all in all but would be a nice touch for those with rooted devices

**Comment by CarlosEsco** [comment]
No plans to add this as it is a niche feature.
