### ISSUE TITLE
Can't Download manga

### ISSUE THREAD

**Issue by Smjonos** [inorichi/tachiyomi#386]
I hope this is the right place for that sort of thing. I am having an issue with the app. I can't downloald manga in order to store them on my phone. The first time I did fine, the app downoaded quite a few chapters. However, now it doesn't download at all, the selected chapters go to the download queue but the process does not start.

I use the latest version, 0.2.2.
My phone is Samsung Galaxy S2, with Android version 4.1.2.

**Comment by Smjonos** [comment]
I tried again. This time I got an Error: Failed to create directory (I think that error came up and the first time).

**Comment by inorichi** [comment]
If you are using an external SD card as downloads directory, you have to use the predefined folder which points to your SD (probably the third entry)

**Comment by Smjonos** [comment]
It works now. Thank you.
