### ISSUE TITLE
Bato.To is gone

### ISSUE THREAD

**Issue by mbryant95** [inorichi/tachiyomi#3861]
## Device information
* Tachiyomi version: 10.5
* Android version: 10
* Device: Galaxy 

## Issue/Request
The extension i use the most is Bato.To but it disappeared overnight after their website did some maintenance. I'm sort of depressed because most of those manga I could only read through Bato.To. Everything is up to date but Bato.To is gone. I do see what its supposed to be when I go to migrate tab. The title is just a series of numbers. I really hope you can fix this because now I'm on a permanent cliff hangar until this is resolved. On another note mangahasu stopped working and keeps saying "http error". 

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
1. Wrong repository
2. Already reported https://github.com/inorichi/tachiyomi-extensions/issues/4455
