### ISSUE TITLE
[Feature Request] Add option to prevent going to the next chapter

### ISSUE THREAD

**Issue by guestname** [inorichi/tachiyomi#3864]
## Why/User Benefit/User Problem

I think it would be good if we have an option that prevents us from going to the next chapter even if we try to scroll past the last page. It maybe useful, for instance, if we're planning to read the next chapter later but don't want to accidentally see some spoiler. Or we want to count more carefully how many chapters we're reading.

## What/Requirements

Just a single option in the reading settings that, if we mark it, prevents us from going to the next chapter when scrolling past the last page in the current one. Should be unmarked as default.

**Comment by scb261** [comment]
Chapter transition may be good solution for you. It should be enabled by default, but just in case: *More > Settings > Reader > Always show chapter transition*

**Comment by arkon** [comment]
Yeah, use the transitions. Otherwise this is too niche to justify the effort/complexity.
