### ISSUE TITLE
Next chapter/next page button on top status bar should follow the Default viewer settings

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#387]
Next chapter/next page button on top status bar should follow the Default viewer settings.

e.g. 
Left to Right => Left button goes to previous, page right goes to the next page
Right to Left => Right button goes to previous, left page goes to the next page

Optional:
Vertical and webtoon should have buttons that point up and down so that the arrows are consistent with the settings.

Version: r0.2.2-1
Phone: Xiaomi Redmi 1s
Android version: 4.4.4

**Comment by inorichi** [comment]
It already does that, check dev version.
