### ISSUE TITLE
[Feature Request] Hide 'Last used' source in Browse if it's the same as pinned

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3875]
## Why/User Benefit/User Problem
Having both Last used and Pinned if it's the same source just shows duplicate, which reduces the number of other visible source on screen.  

## What/Requirements
Hide Last used if it's the same as pinned source in Browse.

**Comment by arkon** [comment]
I'm not sure if this makes sense if someone has a bunch of things pinned.

**Comment by joseph619** [comment]
Alternatively, it could show Last used and not the pinned one. This way it would be at the top and not waste space with duplicate.

**Comment by arkon** [comment]
I feel like this is a silly exercise in trying to eliminate a "duplicate" for the sake of "simplicity". There're both there for good reasons.

**Comment by joseph619** [comment]
Well Last used itself is mostly redundant now due to pinned sources appearing at the top, this tried to address that without removing Last used entirely.
