### ISSUE TITLE
[Bug]The image looks a little fuzzy.

### ISSUE THREAD

**Issue by zxhdmx** [inorichi/tachiyomi#3876]
I made a comparison between tachiyomi and the website

Left: tachiyomi   right: Web page 

web link:[365manga reminiscence adonis](https://365manga.com/manga/reminiscence-adonis/chapter-0/)
![](https://i.imgur.com/7c6IrXM.jpg)

up:tachiyomi   down:web page

web link:[1stkissmanga lady baby](https://1stkissmanga.com/manga/lady-baby/chapter-0/)
![](https://i.imgur.com/mXttE4C.jpg)

**Comment by CrepeTF** [comment]
Tried turning on 32-bit colour?

**Comment by arkon** [comment]
The app just uses a library to display images. It subsamples things to keep it relatively memory efficient, which may cause this as it isn't the same as however your browsers are rendering it.

It's generally fine, so it won't be fixed.
