### ISSUE TITLE
Method to bookmark/follow manga titles in batoto/kissmanga

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#388]
I've seen the import batoto bookmarks feature requested but is there a way to bookmark/follow a manga in app? so that I could sync my follow on the app and on the site I use.

Version: r0.2.2-1
Phone: Xiaomi Redmi 1s
Android version: 4.4.4

**Comment by inorichi** [comment]
Sorry but that kind of syncing is outside of the scope of this app.
