### ISSUE TITLE
Multiple language

### ISSUE THREAD

**Issue by Victoiire** [inorichi/tachiyomi#3883]
Hi

I would like to reccomend a function where you can choose not only one language in general settings.

I think this feature shoul be added because there's a lot of people who can read more then one language, for example I can read spanish, japanese and english. It would be so great if we can read from multiple sources not only in english, that way there will be more options from sources and more people can be atracted to this app.

This will work this way:
1-. Put 1 o more language you want to read, selecting only one like principal and the others like subordinates. Meaning the principal language will be the main on the app, like if you choose spanish, the app in general will be in spanish.
2-. Then the app will show you all the sources in those languages they selected including the general.

This way people who feel more comfortable with there primary language can be able to keep it in the main app but at the same time can acces to practice or read other language.

Thank you for your time.

**Comment by arkon** [comment]
Use the language filter menus in the Sources and Extensions screens.
