### ISSUE TITLE
[Feature Request] Adding a 18+ toggle button in MoreController to hide the adult content

### ISSUE THREAD

**Issue by FareesHussain** [inorichi/tachiyomi#3887]
#### I suggest categorizing adult extension and other extensions to be displayed Different.

> According to the 18+ toggle button (yet to be implemented in the MoreController) 
and this 18+ toggle button will be off as default when the app is installed.

**Comment by arkon** [comment]
Parental controls are currently incomplete, but you can toggle this within the Preview versions of the app. I don't intend on surfacing this in the top-level More menu.
