### ISSUE TITLE
[Bug] Manga Cruzers Extension not working

### ISSUE THREAD

**Issue by FareesHussain** [inorichi/tachiyomi#3888]
### Manga Cruzers app extension is not working
 > The base URL of the Manga Curzers extension i.e, https://ww2.mangacruzers.com/ is not available
<p align="center">
<img src="https://user-images.githubusercontent.com/54740946/95001684-e3a9b180-05e9-11eb-9e4c-ea3103809b08.png" width="32%"/>
<img src="https://user-images.githubusercontent.com/54740946/95001712-34210f00-05ea-11eb-95ff-35455ac30692.png" width="32%"/>
</p>

**Comment by arkon** [comment]
Wrong repo.
