### ISSUE TITLE
[Feature Request] Show language for last used and pinned sources

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3889]
## Why/User Benefit/User Problem
![Screenshot_20201004-052937](https://user-images.githubusercontent.com/63973749/95002076-c3d2b780-0602-11eb-9f99-4e3cf0c4701f.png)
You have no way of telling which is which

## What/Requirements
Add language next to source name, or in a separate line.

**Comment by joseph619** [comment]
If accepted, would prefer if this is shown for Non English sources only, vast majority of users only use English sources and they don't need to see the language code for all sources.

**Comment by TheUnlocked** [comment]
> If accepted, would prefer if this is shown for Non English sources only, vast majority of users only use English sources and they don't need to see the language code for all sources.

Or just hide it if all pinned sources have the same language.

**Comment by joseph619** [comment]
Not just pinned, any enabled english source.

**Comment by arkon** [comment]
Added to everything in ed41604f5667cc63778282c69d90d71d070422fb

Can be tweaked later if needed.
