### ISSUE TITLE
[Bug] <Failed to connect to raw.githubusercontent.com/127.0.0.1:443>

### ISSUE THREAD

**Issue by sombresu** [inorichi/tachiyomi#3890]
## Device information
- Tachiyomi version: 0.10.5
- Android version: Oreo

## Steps to reproduce
1. Open Tachiomi
2. Browse extensions

### Expected behavior
Showing lists of extension to install

### Actual behavior
Failed to connect to raw.githubusercontent.com/127.0.0.1:443

**Comment by arkon** [comment]
Nothing we can do on our end since it's just a simple request to GitHub.
