### ISSUE TITLE
[Feature Request] Mute/Hidden category.

### ISSUE THREAD

**Issue by ram-evre** [inorichi/tachiyomi#3893]
## Why/User Benefit/User Problem
There were a few times where i wanted to hide the manga i was reading for personal reasons(embarrassed to show etc) or atleast turn off update notifications just for a single category/manga to not get tempted to read a chapter which i wanted to avoid reading for a while.
So a hide/mute option would help.

## What/Requirements
The category which has been muted or hidden won't get any updates or update notifications unless the user manually reloads the category or when the person opens that category.
The hidden categories should not be shown and can be opened with a seperate method (long pressing on unhidden categories or something)

**Comment by scb261** [comment]
You can choose all categories except this one in *Categories to include in global update* and *Categories to include in download*

**Comment by ram-evre** [comment]
> You can choose all categories except this one in _Categories to include in global update_ and _Categories to include in download_

Thanks for the reply, I didn't know that.
Also I pressed the submit button without completing the whole issue, so I updated it now.

**Comment by arkon** [comment]
Closing, assuming what @scb261 mentioned is sufficient.

**Comment by ram-evre** [comment]
> Closing, assuming what @scb261 mentioned is sufficient.

Okay (^._.^)ﾉ. The update notifications thing can be done by global updates, but the "hide a category" (hide from the library view) feature can be handy. 
So consider it if you see it fit, TQ.

**Comment by arkon** [comment]
There's some other similar issues like https://github.com/inorichi/tachiyomi/issues/1508
