### ISSUE TITLE
[Bug] <Recent Chapter History>

### ISSUE THREAD

**Issue by Toastypoptart** [inorichi/tachiyomi#3896]
## Device information
* Tachiyomi version: Preview r2763 (4cbe4997)
* Android version: 10
* Device: Samsung Galaxy S10 plus

## Steps to reproduce
1. Exits out of Manga I was reading
2. In History tab

### Expected behavior
Should say chapter 42 (most recent chapter) that I just read.

### Actual behavior
Says chapter 41 that I've read last time.

## Other details
On version r2763 of Tachiyomi my history tab doesn't update to the most recent chapter that I've read unless I click off the tab and click back on (example: clicks on browse and then clicks on history) or close the app and reopen it.

**Comment by WildOrangutan** [comment]
I will try to solve this mystery! 😊
