### ISSUE TITLE
[Bug] My tachiyomi keeps on breaking when im restoring my backup my previous device broke but thankfully i saved backups of my mangas so now i have a new device and i installed tachiyomi i can't restore my backup because tachiyomi keeps on bugging in blackscreen whenever i tap the backup

### ISSUE THREAD

**Issue by ChrizzTian** [inorichi/tachiyomi#3897]
## Device information
* Tachiyomi version: stable 0.10.5
* Android version: 8.1.0
* Device: OPPO A5S

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen: The conformation of restoring the backup

### Actual behavior
This happened instead: The black screen appears and stays like that until i go to the home of the device

## Other details
This is what it looks like of the several hours i waited
![Screenshot_2020-10-05-07-43-22-81](https://user-images.githubusercontent.com/72364633/95031109-b1ca4500-06e6-11eb-9a3a-d786215dfd26.jpg)

**Comment by arkon** [comment]
Try using a different file manager app.

**Comment by Pxeexe** [comment]
Fuck you

вс, 18 окт. 2020 г., 19:25 arkon <notifications@github.com>:
