### ISSUE TITLE
[Bug] failure to update

### ISSUE THREAD

**Issue by Kooevil** [inorichi/tachiyomi#3908]
---

## Device information
* Tachiyomi version: 0.8.4
* Android version: 8.1.0
* Device: ASUS_X00DA

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Should continue to download

### Actual behavior
Failure to download halfway through.

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
Download latest version of the app https://tachiyomi.org/download

**Comment by arkon** [comment]
As mentioned in the acknowledgement section of the issue template, you must update to the latest version. We do not support old versions.
