### ISSUE TITLE
[Feature Request] <Beta version>

### ISSUE THREAD

**Issue by Yota321** [inorichi/tachiyomi#3909]
## user suggestion 
I think in the beta version the finger print scanner color #45A69B looks a bit bad (in my opinion)previous one looked better.

**Comment by arkon** [comment]
That isn't controlled by the app.

**Comment by Yota321** [comment]
> That isn't controlled by the app.

I was thinking about this!

[Screenshot_2020_1007_180244.png](https://user-images.githubusercontent.com/62050293/95331235-530ff180-08c7-11eb-9a45-ebf36c2170b4.png)

Old one⬇️
[Screenshot_2020_1007_180528.png](https://user-images.githubusercontent.com/62050293/95331481-b1d56b00-08c7-11eb-8bfa-d8fdc195edf7.png)


And this is taciyami's  own figureprint I am not using any application for this .

**Comment by arkon** [comment]
Yes, we just use Google's library for it.
