### ISSUE TITLE
[Bug] No previous/next chapter (repeat of #2296)

### ISSUE THREAD

**Issue by deeplyarnab** [inorichi/tachiyomi#3911]
A repeat of  #2296 with the latest beta.

## Device information
* Tachiyomi version: Preview r2763
* Android version: 10

Vid link
https://pixeldrain.com/u/8jwkWmrx

Sent the vid to my friend (hence the title) and he had the same issues on the stable version on some sources.
In the prev beta, this used to work and only "updates" tab was broken in the same way, now both of them are.

**Comment by scb261** [comment]
*More > Settings > Reader > Skip chapters marked read*
