### ISSUE TITLE
[Возможность ставить пароль на приложение (Password)] <Ability to set a password for application>

### ISSUE THREAD

**Issue by PythonLog** [inorichi/tachiyomi#3914]
Why/User Benefit
Password protection of the application will protect the library from unauthorized people.
|                                                                                                                                               |
 What/Requirements
In the menu item "Security" you can add a new item "Set password" or "Set PIN-code".

**Comment by arkon** [comment]
The app already supports biometric methods. We don't plan on supporting non-biometric methods as there aren't simple/standard ways of doing it.
