### ISSUE TITLE
[Bug] Timeout and Recents

### ISSUE THREAD

**Issue by shivakanou** [inorichi/tachiyomi#3917]
## Device information
* Tachiyomi version: 1.0.9
* Android version: 9
* Device: Samsung Galaxy S8

## Steps to reproduce Timeout
1. Select any manga
2. Open the chapter list
3. Start downloading chapters
4. You'll get a timeout error

## Steps to reproduce Recents
1. Read any manga
2. Go to Recents tab
3. Click on any manga (in my case Hajime no Ippo, Gokushufudou or One Piece)

### Expected behavior Timeout
This shouldn't happen. I should just start downloading chapters and they would complete.

### Actual behavior Timeout
Very often I receive a Timeout error or a "incomplete url" when downloading files.

### Expected behavior Recents
I should click the chapter and get redirected to where I stopped.

### Actual behavior Recents
I get redirected to the first unread chapter, not the first unread after the one I just read.

## Other details
I recently erased all notifications from my phone. As soon as the timeout error happens again, I'll attach.

**Comment by scb261** [comment]
This repository is for main app, not forks, see https://github.com/Jays2Kings/tachiyomiJ2K . And timeout issue is probably because of your connection or the source you're using has a problem
