### ISSUE TITLE
[Feature Request] Faster source scanning.

### ISSUE THREAD

**Issue by Nipper4369** [inorichi/tachiyomi#3919]
#3683  Why/User Benefit/User Problem
Faster source Scanning. 
Reason being as if a source hangs or is broken you have to wait for it to timeout to move on to the next. This slows down the scan alot. What I would like to ask is have it able to multi thread its scanning as in. 

## What/Requirements
Example. 

Limit set to 2 or 3 by default up to say 10 if set manually.
Maybe have 2 types one for being on Cell network and one for being on wifi so the wifi one can be set higher.

Search for any manga via browse or migrate.
It would search the set amount of locations at once. If one hangs it still has the others to keep the process moving forward and not having it hang waiting for it to time out.

**Comment by scb261** [comment]
Right now it does search in several sources simultaneously, 5 to be exact. I don't think that there is actually a reason to make it configurable. As I already said on discord, just filter out sources that you aren't using. Or you can also enable *Only include pinned sources* in settings.
https://github.com/inorichi/tachiyomi/blob/a249373bf50c0701c6f8d0f1b9e692dc633cd5ab/app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchPresenter.kt#L178

**Comment by Nipper4369** [comment]
Well then my rquest would be to have a way for the user increasing it. I used to think it was based on my tablet but even this new one had the slow ups that my old one had. I already filter out the bad sources.

**Comment by arkon** [comment]
Yup, it's been "multi-threaded" for as long as I can remember. There's no plans to improve this in 0.x, but in general it's not a simple problem to solve as source speed depends more on the user's connection than how the app handles it.
