### ISSUE TITLE
[Feature Request] <Add an option to limit downloads to one at the time>

### ISSUE THREAD

**Issue by Kuroruisu** [inorichi/tachiyomi#3930]
## Why/User Benefit/User Problem
(I have a very limited data plan and i make a list of things to download , sometimes i just want to download the first thing on the list right now and it starts downloading more than one at the time and wastes my megas)

## What/Requirements
(It would limit downloads to one at the time giving priority to the first one on the download list)

**Comment by scb261** [comment]
Duplicate of #3472
