### ISSUE TITLE
[Feature Request] Duplicated Chapter detection

### ISSUE THREAD

**Issue by jopejoe1** [inorichi/tachiyomi#3932]
## Why/User Benefit/User Problem
If using mangadex as source the same chapter get released by 2 groups it makes the same chapter appear after each other when reading.

## What/Requirements
Should skip over chapter if it is the same as the previous.

**Comment by scb261** [comment]
Set chapter sort to sort *By chapter number*, the reader will skip duplicates with this setting. You can also block group on the site, or mark chapters as read and enable *Skip chapters marked read*

**Comment by jopejoe1** [comment]
Thanks for the answer. Is there anyway to set sorting as default?
