### ISSUE TITLE
[Feature Request] <Please, an option to compress the mangas and not download them in HD, to save space and data..>

### ISSUE THREAD

**Issue by zola71** [inorichi/tachiyomi#3940]
Opinion to compress the images of the mangas.

I know that if an image is compressed, the image loses quality, I don't mind sacrificing quality for storage space.

## Why/User Benefit/User Problem
There are mangas and comics that are very heavy, and take up more than 1GB of storage space, they also take many hours to download. Such an option would save a lot of storage space and time, because 1 manga that normally weighs 1GB, could be lowered to weigh much less.

## What/Requirements
I don't know about programming, but isn't there a way to add an option to force the application to display and download image with very low quality, with the percentage (%) of quality you want?

Example: 

A option that says: 
Show and download all images with 
15,
20, 
30, 
40,
50,
60
70,
80,
90,%... or whatever you want the quality to be, and that any user can choose the percentage (%) of quality that the user wants. Obviously I know that if you do that, the images lose a lot of quality, I don't care, that's just what I want to do.

I don't know if that is possible, but you can do something like that, I will be infinitely grateful. Please, this application is perfect, it is the best for reading mangas, but that would be the only option I need to be happy.

**Comment by arkon** [comment]
#918, sort of.

At best there's the option of compressing images as archives and/or lowering the quality on save, but initial download quality is dependent on the source websites, so overall data usage and download time would be the same.

**Comment by arkon** [comment]
MangaDex offers a data saver option, FWIW.
