### ISSUE TITLE
[Bug] Anilist tracking won't load

Adding tracking to a manga does not work anymore. Specifically  Anilist, the window for searching opens up but no matter how long I waited nothing showed up. 



### ISSUE THREAD

**Issue by Wiz1991** [inorichi/tachiyomi#3945]
![Screenshot_20201016-084019_Tachiyomi.jpg](https://user-images.githubusercontent.com/45233935/96221875-36d51a00-0f83-11eb-8626-530659bc5e6e.jpg)
This is how it looks, its stuck here. I should mention that anilist is working and i can access it, i can also change the status on manga that ive added already.

**Comment by arkon** [comment]
Why did you remove everything from the template? Please fill out the required information.

**Comment by arkon** [comment]
No response, closing.
