### ISSUE TITLE
[Feature Request] Too little lateral spacing for expanded FAB content

### ISSUE THREAD

**Issue by CrepeTF** [inorichi/tachiyomi#3949]
The spacing to the left and right of the content in the FAB is just too small!
Flat is justice but not in this case, it makes the FAB look cramped and claustrophobic - save FAB-tan.

The FAB background should also be a dark gray with blue icon and text since it fits with the modern material ux better.

---

## Why/User Benefit/User Problem
It looks better #SaveFABTan

## What/Requirements
Exactly how it looks now - but thiccer, and dark gray background with blue icon and text.

Current look:
![Screenshot_20201018-002015](https://user-images.githubusercontent.com/70870719/96355285-e15e5180-10d7-11eb-8576-112288f75ae4.jpg)

How it should look:
![Screenshot_20201018-002050](https://user-images.githubusercontent.com/70870719/96355288-e9b68c80-10d7-11eb-9633-9ff07e3c6b06.jpg)

**Comment by arkon** [comment]
It was changed by Google to conform with the specs. If anything it actually isn't supposed to be this tall when expanded.

**Comment by arkon** [comment]
Also grey background is too difficult to see.

**Comment by vengiare** [comment]
> https://user-images.githubusercontent.com/70870719/96355288-e9b68c80-10d7-11eb-9633-9ff07e3c6b06.jpg

Too much spacing at the left, has to be centered in the circle like when it's collapsed

**Comment by vengiare** [comment]
Wait, this was never about the FAB height

**Comment by arkon** [comment]
I'm following the spec, not your opinions.

**Comment by vengiare** [comment]
![unnamed.png](https://user-images.githubusercontent.com/63973749/97059873-56dc8d00-15c4-11eb-968e-83e1043793c3.png)

yeah which spec

**Comment by arkon** [comment]
https://github.com/material-components/material-components-android/commit/14c70f0b117795b6894648efbc7c1052e9105846
