### ISSUE TITLE
[Bug] <Tachiyomi crashes on my pocophone f1>

### ISSUE THREAD

**Issue by x-6699** [inorichi/tachiyomi#3961]
#3406  Device information
* Tachiyomi version: v0.10.5
* Android version: Android 10/ MIUI v11.0.9
* Device: Pocophone F1

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by x-6699** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint:
'Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V12.0.2.0.QEJMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2020-10-29 15:33:32+0800
pid: 23904, tid: 23958, name: RxIoScheduler-3 >>> eu.kanade.tachiyomi <<<
uid: 10359
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x432f55d8b69cb5
    x0 c3fee68dd6978160 x1 0000000000000015 x2 0000006fb43f9e64 x3
0000006fb43f9e89
    x4 0000006fa9d34a30 x5 0000000000000000 x6 000000000000005d x7
000000000000005d
    x8 0000000000000000 x9 0000000000000025 x10 0000006fb43f9e64 x11
0000006fa9d33272
    x12 0000000000000005 x13 0000000000000001 x14 0000000000000000 x15
0000000000000000
    x16 0000006fa9d33178 x17 00000070ae27d5c0 x18 0000006fad2d8000 x19
0000000000000015
    x20 c3fee68dd6978160 x21 0000006fb43fc020 x22 e4432f55d8b69cb5 x23
0000006fb43fc020
    x24 0000000000000011 x25 0000006fb4617100 x26 000000701a3cf4c0 x27
000000701a3cf4c0
    x28 0000006fa9b9ff24 x29 0000006fb43f9f70
    sp 0000006fb43f9d50 lr 0000006fa9baaf1c pc 00432f55d8b69cb5

backtrace:
    NOTE: Function names and BuildId information is missing for some frames
due
    NOTE: to unreadable libraries. For unwinds of apps, only shared
libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 00432f55d8b69cb5 <unknown>
      #01 pc 0000000000029f18
/mnt/expand/807a8d62-504f-45c8-96cf-6dd37d5b0c08/app/eu.kanade.tachiyomi-QiwvJtUdciwvefE7Sq4xQg==/lib/arm64/libsqlite3x.so

**Comment by arkon** [comment]
Need more logs than that.

**Comment by arkon** [comment]
No usable information, closing.
