### ISSUE TITLE
[Bug] AniList tracker broken

### ISSUE THREAD

**Issue by imokirby** [inorichi/tachiyomi#3964]
## Device information
* Tachiyomi version: stable v0.10.5
* Android version: 10
* Device: Samsung Galaxy A30

## Steps to reproduce
1. Select a manga
2. Add or update AniList tracker

### Expected behavior
* should add or update the relevant listing on my AL profile

### Actual behavior
* if you try to update a manga that already has AL tracking, there is a HTTP Error 400
![Screenshot_20201023-164302_Tachiyomi](https://user-images.githubusercontent.com/73327724/96960997-72f21700-154f-11eb-9850-120c7e855f20.jpg)

* if you try to add AL tracking to a new manga, it will load forever
![Screenshot_20201023-164956_Tachiyomi](https://user-images.githubusercontent.com/73327724/96961376-3c68cc00-1550-11eb-8733-15f1e3e80cf7.jpg)

## Other details
* I have confirmed that the AniList website itself is working fine
* Seems to be the same bug as #3945

**Comment by scb261** [comment]
Works for me, can you try to relogin?

**Comment by imokirby** [comment]
Ah, that worked. I feel really dumb now.
