### ISSUE TITLE
Page corrupted

### ISSUE THREAD

**Issue by ZackCelestial** [inorichi/tachiyomi#3965]
- I have updated 
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Phone Samsung A51

## Steps to reproduce
1. First step
2. Second step

## Issue
Page Corrupted

## Other details
Manga Azur Lane Comic Anthology from Mangadex Volume 7 Chapter 6 page 9 and 10 was corrupted and the page just show half image.

**Comment by scb261** [comment]
https://github.com/inorichi/tachiyomi/issues/3573#issuecomment-701621703
