### ISSUE TITLE
[Feature Request] Make list view font size bigger again

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3967]
## Why/User Benefit/User Problem
Stable
![Screenshot_20201025-030127~01](https://user-images.githubusercontent.com/63973749/97091525-01a98580-166f-11eb-8953-7cda32c91685.png)

Preview
![Screenshot_20201025-030221~01](https://user-images.githubusercontent.com/63973749/97091516-f6eef080-166e-11eb-8198-7389c37ebcdc.png)

Font size for list view now matches source/extension's, which doesn't look good in it especially since the icons used beside list view are considerably bigger than the icons used in source/extension list.

That font size would probably only look good if the list has a second line like Updates list, but I'm pretty sure that's never happening.

**Comment by joseph619** [comment]
It looks better with smaller font, I prefer the new change

**Comment by vengiare** [comment]
Try to compare it to text in settings, it's way off.

**Comment by vengiare** [comment]
It's even more apparent how bad it looks when you use a smaller text scaling

Stable
![Screenshot_20201025-050216.png](https://user-images.githubusercontent.com/63973749/97093578-c499bf00-167f-11eb-9d3d-9c1df9c0b8bc.png)

Preview
![Screenshot_20201025-050312.png](https://user-images.githubusercontent.com/63973749/97093584-d2e7db00-167f-11eb-8160-20136a1474ae.png)

And as I mentioned, it doesn't match font size used in other parts of the app, unlike before.
(Compare screenshots above to this)
![Screenshot_20201025-050317.png](https://user-images.githubusercontent.com/63973749/97093597-ebf08c00-167f-11eb-8258-6de216e90ea8.png)
