### ISSUE TITLE
Switching to next downloaded chapter says next chapter not found

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#397]
Sometimes while switching to the next chapter the app says chapter not found. I've got  the the next chapters downloaded but still gets this error when reading.

Version: r822
Phone: Xiaomi Redmi 1s
Android version: 4.4.4

**Comment by null-dev** [comment]
This is probably because the chapter number for the chapters you are trying to read is a non-whole number.

**Comment by inorichi** [comment]
By default it doesn't use the number anymore. But if you were using the app before that change and you didn't update the chapter list for every manga (global update doesn't update manga marked as completed by default), then the order isn't saved (every field is 0) and you can't navigate from the reader.
