### ISSUE TITLE
[Bug] <Write short description here>

### ISSUE THREAD

**Issue by sexyasianboi** [inorichi/tachiyomi#3974]
Device information
Tachiyomi version: 10.5
Android version: 10
Device: moto g7 power

Steps to reproduce
First step i went to open it it acts like it was working and then it crashes and wont open at all
Second step i have rebooted my device thinking it might fix it but it didnt fix it
Expected behavior
This should happen.
it should have opened and allowed me to read my mangas

Actual behavior
This happened instead.
it wont open and just crashes everytime i try to open it
manga app crash bug.zip

Other details
[manga app crash bug.zip](https://github.com/inorichi/tachiyomi/files/5435805/manga.app.crash.bug.zip)
ower

**Comment by sexyasianboi** [comment]
ok wiilll re sumbit again

**Comment by arkon** [comment]
@sexyasianboi See https://github.com/inorichi/tachiyomi/issues/3973#issuecomment-716200605
