### ISSUE TITLE
[Bug] <app crashes wont open 3 time submited starting to get mad >

### ISSUE THREAD

**Issue by sexyasianboi** [inorichi/tachiyomi#3975]
Device information
Tachiyomi version: 10.5
Android version: 10
Device: moto g7 power

Steps to reproduce
First step i went to open it it acts like it was working and then it crashes and wont open at all
Second step i have rebooted my device thinking it might fix it but it didnt fix it
Expected behavior
This should happen.
it should have opened and allowed me to read my mangas

Actual behavior
This happened instead.
it wont open and just crashes everytime i try to open it
manga app crash bug.zip

Other details
[manga app crash bug.zip](https://github.com/inorichi/tachiyomi/files/5435813/manga.app.crash.bug.zip)

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi/issues/3973#issuecomment-716200605

**Comment by sexyasianboi** [comment]
> See [#3973 (comment)](https://github.com/inorichi/tachiyomi/issues/3973#issuecomment-716200605)

saw it but have no idea what it means

**Comment by arkon** [comment]
> Make sure you have Webview installed/enabled/updated.

This should be understandable for non-developers.

**Comment by sexyasianboi** [comment]
> > Make sure you have Webview installed/enabled/updated.
> 
> This should be understandable for non-developers.

it is installed enabled and updated 
as far as i know yet it still crashes

**Comment by arkon** [comment]
I don't know why your phone has a 32-bit version of Webview. If you can't update it to a proper 64-bit version, then there's no way to fix it on our end.

**Comment by sexyasianboi** [comment]
> I don't know why your phone has a 32-bit version of Webview. If you can't update it to a proper 64-bit version, then there's no way to fix it on our end.

ill check and see if i can get it updated to a 64-bit one
