### ISSUE TITLE
[Bug] Webtoon / Manwha / Manhua black bar per page loading on reading

### ISSUE THREAD

**Issue by koetjeengdjalanan** [inorichi/tachiyomi#3976]
There is black bars when I am reading related type of content.

![Screenshot_2020-10-27-00-34-06-55](https://user-images.githubusercontent.com/48125544/97207689-dfd60d00-17ec-11eb-92fc-0cdc3bfc368b.png)

I really confused and annoyed to read like this. Any solution to unify per. Page so the black bars gone? 
*note : this is the worse scenario, but I think you guys got the idea of the issue

**Comment by scb261** [comment]
Change reading mode from *Vertical continuous* to *Webtoon*

**Comment by koetjeengdjalanan** [comment]
> Change reading mode from _Vertical continuous_ to _Webtoon_

Thank you kind sir.
