### ISSUE TITLE
Issue while browsing fast on "next chapter" 

### ISSUE THREAD

**Issue by jscti** [inorichi/tachiyomi#398]
Hi

When I don't know what chapter I last read, I often have to click "next chapter" fast in order to see the chapter front page.. but the more I click  "next chapter" the longer the waiting loader is displayed. After some time I abandon and close/reopen the reader.
It seems like for each chapter I begin to watch (first page), tachiyomi queue the loading of each chapter's page, even previous chapters.. 
=> Wouldn't it better to reset the queue each time the new chapter get displayed ?

Sorry If I'm completely wrong about this ;)
 
Version: v0.2.2-1
Phone: Nexus 4
Android version: 6.0.1

**Comment by inorichi** [comment]
I think this doesn't happen in v0.2.3

**Comment by jscti** [comment]
I confirm, it's no longer an issue. Thanks
