### ISSUE TITLE
[Feature Request] Intelligent sources search

### ISSUE THREAD

**Issue by Hapique** [inorichi/tachiyomi#3987]
## Why/User Benefit/User Problem
I have a lot of sources installed and searching them all in `Browse`> `Sources` takes a lot of time. I think it would be great to have another way to search them other than alphabetically.
I think it would be nice if the app kept track of previous searches and gave a rank to each source that would change the sources search order. The rank would be kept between searches and if source has result(s) during a search it would rank up or else rank down.

## What/Requirements
I think a switch in `Settings` > `Browse` to enable/disable this feature would do.

**Comment by ranztorz** [comment]
Or atleast something like a profile search, where you put sites into category. Selecting and un-selecting a bunch of extensions is a total pain, especially since there are a lot of type of sites for specific genre.

**Comment by CrepeTF** [comment]
If you pin your sources, when Global Searching it searches in those pinned sources first

**Comment by CaptainHalflife** [comment]
Can someone add a feature to search amoung all installed source. We can only search for extension and from that no way to select the source. Its even more disturbing when you have a bunch of multisource like me.

**Comment by arkon** [comment]
> Can someone add a feature to search amoung all installed source.

You already can, just search from the Sources tab.

**Comment by CaptainHalflife** [comment]
> > Can someone add a feature to search amoung all installed source.
> 
> You already can, just search from the Sources tab

My bad that's not what i meant. I want a search bar to search the source itself. If there is already 1 that mean i really blind @nd that wouldn't suprise me.

**Comment by CrepeTF** [comment]
You mean like this?
![Screenshot_20201113-142218](https://user-images.githubusercontent.com/70870719/99082186-b7575c80-25bb-11eb-9837-a03c49d6de6e.jpg)

**Comment by CaptainHalflife** [comment]
No to search the source itself not in the source.

**Comment by CaptainHalflife** [comment]
to search the name of the source because i have a lot

**Comment by CrepeTF** [comment]
You mean like this spreadsheet?
https://tachiyomi.org/extensions-spreadsheet

**Comment by CrepeTF** [comment]
If you mean to instead of looking through all your sources to select 1 source just pin it

**Comment by CaptainHalflife** [comment]
Here my problem i am reading a scan on a source but now they drop the manga. An another group now continue to translate it, so i want to search amoung all my sources that new translater team without having to scroll through all my list

Its a minor problem but i encounyer it many times already ^^'

**Comment by CrepeTF** [comment]
Just global search for the series/ press the title of the series

**Comment by CaptainHalflife** [comment]
It takes times to load all that my poor internet canct keep up and     it search 1 by 1

**Comment by CrepeTF** [comment]
Then search on Google, how would tachi be able to tell what's a scan group and what's an aggregate website?
And what if there are multiple scan groups scanlating the series?

**Comment by joseph619** [comment]
In future, scanlator extensions will be tagged as such. However that has nothing to do with intelligence source search, nor it is possible what you are requesting.

**Comment by arkon** [comment]
> In future, scanlator extensions will be tagged as such.

No they won't. Please do not spread fake news.

**Comment by joseph619** [comment]
My bad, I misunderstood the extension tagging system in 1.x then.

**Comment by arkon** [comment]
I have to agree with CrepeTF here, it's unrealistic to make the app into some sort of search engine.

For the other thing, it shouldn't be hard to search through your sources list since it's already sorted alphabetically.
