### ISSUE TITLE
[Feature Request] Add Novel And eBooks Support and Sources

### ISSUE THREAD

**Issue by alfaazian** [inorichi/tachiyomi#3990]
## Why/User Benefit/User Problem
The Number of users will increase and readers will also have more options to read from.

## What/Requirements
It will let user manage Novels/eBooks like they do with their Mangas/Comics. It will probabaly need Tachiyomi to support pdf/epub formats.

**Comment by joseph619** [comment]
Duplicated of #685, also declined
