### ISSUE TITLE
[Feature Request] Download Only new Chapters in Category XZ but not Y

### ISSUE THREAD

**Issue by neodata83** [inorichi/tachiyomi#3991]
Hello everyone.

Dont know if this was posted before cant find anything.

## Why/User Benefit/User Problem
I Would like to have an option to say that download only new chapters in category A and C but not in B. Because for some mangas i like to keep the chapters  and others dont matter.

## What/Requirements

May bee in the category settings a checkbox "download new chapters if available" or under the Download new chapters option a second one with categories for selection.

**Comment by Seishirou101** [comment]
You can already choose which categories to download.
