### ISSUE TITLE
[Bug] downloaded chapters missing

### ISSUE THREAD

**Issue by Yorugami06** [inorichi/tachiyomi#3992]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 5.0
* Device: Oppo A37f

## Steps to reproduce
1. Download chapters
2. Close app after download complete
3. Open app
4. Downloaded chapters go missing

### Expected behavior
Should show downloaded chapters

### Actual behavior
Downloaded chapters go missing in app and file manager. 

## Other details
Tried in mangakakalot,managanelo mangairo mangahasu. Downloaded  image of chapters is corrupted after download when i checked before it go missing.

**Comment by scb261** [comment]
It's probably some file cleaner or Google Photos, can you check if you have one and disable it?

**Comment by Yorugami06** [comment]
> It's probably some file cleaner or Google Photos, can you check if you have one and disable it?

I don't have a file cleaner, also i just checked it but when I set the download location to Internal Storage it works fine. But when I set it to sd card problem happens
