### ISSUE TITLE
[Bug] Bangumi track Login

### ISSUE THREAD

**Issue by deqxj00** [inorichi/tachiyomi#3994]
I acknowledge that:
- I have updated to the latest version of the app dev r2804 

Cannot login bangumi from dev version r2804 r2796 r2790
webview work fine  but call back to tachiyomi ,tracker bangumi not show √
last work version is dev r2774

**Comment by arkon** [comment]
This is admittedly a bit hard to fix because I can't seem to create an account properly.

Is there any chance that you can create a new account and DM me the login info on Discord?

**Comment by deqxj00** [comment]
01 select this
<img width="471" alt="01" src="https://user-images.githubusercontent.com/6488246/97807487-2370c100-1c9c-11eb-8ea6-f830076e697e.png">

02
<img width="454" alt="02" src="https://user-images.githubusercontent.com/6488246/97807494-2f5c8300-1c9c-11eb-8371-1cd12e27995a.png">

03
<img width="451" alt="03" src="https://user-images.githubusercontent.com/6488246/97807505-384d5480-1c9c-11eb-843b-db5d9bd81660.png">

04
if 03 active button show this mean waiting 
<img width="434" alt="04" src="https://user-images.githubusercontent.com/6488246/97807518-469b7080-1c9c-11eb-96d5-34f702d6aea6.png">

please try bgm.tv or bangumi.tv to reg

**Comment by arkon** [comment]
I did do that, but the verification code isn't accepted.

**Comment by deqxj00** [comment]
I signup a bgm.tv account by 10minutemail 
try this?
email:lvsudloebchpgsmsdx@tsyefn.com
pasword:qwerqwer

**Comment by arkon** [comment]
Thanks. I'm not sure why the verification didn't work, it gave me an error saying that the system was down.

That account worked though, and it _should_ be fixed for the next preview build. Sorry for the inconvenience.
