### ISSUE TITLE
[Bug] Code Adam on webtoon - no chapters

### ISSUE THREAD

**Issue by Akazotik** [inorichi/tachiyomi#3999]
Source: Webtoon
Manga: Code Adam
Tachiyomi ver.: r2804
Android ver.: 10
Bug: No chapters, but in web view i see that it update. Today release 54 chapter, but in tachi i see 53 and it says no chapters.

![Screenshot_2020-11-02-18-43-26-239_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/97888149-da704980-1d3b-11eb-80b6-cf39adac0cee.jpg)![Screenshot_2020-11-02-18-44-39-863_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/97888153-dc3a0d00-1d3b-11eb-97c3-3409c4830140.jpg)

**Comment by Riztard** [comment]
https://github.com/inorichi/tachiyomi-extensions
read thing before deleting instruction
