### ISSUE TITLE
Manga Scaling

### ISSUE THREAD

**Issue by MakinoTheHermit** [inorichi/tachiyomi#40]
It would be nice to have some sort of scaling when reading manga, like scaling to width so that when i enter a chapter in landscape, i dont have to zoom in every page so that i can read the text.

**Comment by j2ghz** [comment]
I would prefer that to be configurable. I would like it to automatically fit to the smaller of the two dimensions (now it fits the larger), so there are no black bars and I have to scroll only in one direction.

**Comment by MakinoTheHermit** [comment]
Yea, thats how i would like it to be too. Was not specific/clear enough. Thank you for giving a more clear explanation.

**Comment by inorichi** [comment]
Closing this, already implemented.
