### ISSUE TITLE
Restoring a backup doesn't work

### ISSUE THREAD

**Issue by ruudschouten** [inorichi/tachiyomi#400]
Version: r825

When I try to restore a backup which is made from the same version, the restore dialog doesn't show up, and nothing really happens.
I inspected the json file, and it looks alright. I added an attachment as a .txt, if you want to look at it.
I tested it in 2.2.1, and restoring does work there.

[tachiyomi-2016-07-21.txt](https://github.com/inorichi/tachiyomi/files/376583/tachiyomi-2016-07-21.txt)

**Comment by inorichi** [comment]
Thanks, I'll look at it tomorrow. Hopefully it's easily fixed and I can release 0.2.3
