### ISSUE TITLE
[Bug] <After reading delete chapter not working correctly>

### ISSUE THREAD

**Issue by ColinTheBugFinder** [inorichi/tachiyomi#4000]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 9.1
* Device: Huawei Y9 2019

## Steps to reproduce
I don't know how to reproduce it, it would act on its own

### Expected behavior
After reading last read chapter(all the options)
It would delete automatically

### Actual behavior
After reading the last chapter (all the options)
It would sometimes skip deleting the already read chapter 

![Screenshot_20201103_011022_eu kanade tachiyomi](https://user-images.githubusercontent.com/73845522/97897573-a31c8f80-1d71-11eb-9f40-58b395e4af7c.jpg)
![Screenshot_20201103_011145_eu kanade tachiyomi](https://user-images.githubusercontent.com/73845522/97897592-a7e14380-1d71-11eb-9fd4-8b9f7a4e0666.jpg)

## Other details
Can you fix this minor issue

**Comment by scb261** [comment]
Can close the issue, here is what the author said on discord
> Ohh
Wait
Yahh I think I skipped that chapter when it's not yet finished downloading
My bad
