### ISSUE TITLE
[Feature Request] Add the option to zoom in and out by long tapping

### ISSUE THREAD

**Issue by vosian** [inorichi/tachiyomi#4001]
## Why/User Benefit/User Problem
It would facilitate controlling the zoom level with one hand, compared to double tapping, it offers better control over the exact zoom level we end up having, basically the same level of control as pinching.

## What/Requirements
As long tap is currently mapped to a menu, there would need to be a toggle for this (and maybe then the menu would have to be moved to another button in the gui, which makes me fear this won't be added).
The way this would behave is that after a set time of tab-holding (could be unchanged from the current menu fuction) would trigger this function, then, while still holding, we would move the finger up to zoom in, and down to zoom out, how much the zoom level changes depends on how far we move from the initial tap position.

I don't know if it even works with current android versions, but **mango**, a manga app that's been abandoned for several years, had this option, assuming it still runs it could help showcase this function.

**Comment by scb261** [comment]
You can double tap without releasing the second tap. Then move finger down to zoom in, or up to zoom out.

**Comment by CarlosEsco** [comment]
see above

**Comment by vosian** [comment]
I wasn't aware of that option, thank you.
