### ISSUE TITLE
[Feature Request] Show ALL downloaded mangas

### ISSUE THREAD

**Issue by CarterSnich** [inorichi/tachiyomi#4002]
## Why/User Benefit/User Problem
Please add a tab or category of al downloaded titles, as well of those mangas that aren't been added to library.

Why? User benefit?
It easier to track all of downloaded titles, most efficient way.

User problem?
Sometimes, the user may forgot to click the Add to library. Also, the Downloaded Only switch in the settings only shows titles that are downloaded and added to library.

## What/Requirements
Just add a tab/category or filtering on Library page.

Thank you!

**Comment by arkon** [comment]
#2177, kind of.

Tl;dr the app doesn't work in a way that'd allow that to work nicely if it isn't already in your library. The best workaround for now is for you to move things to the Local source if needed.
