### ISSUE TITLE
[Bug] Not a single extension is loading pages or cover art for me

### ISSUE THREAD

**Issue by ethan061903** [inorichi/tachiyomi#4004]
## Device information
* Tachiyomi version: 0.10.5 (and other forks because I was trying to fix it myself in any way possible)
* Android version: 10
* Device: Xiaomi mi 9t

## Steps to reproduce
1. Open up a manga

2. Open up a chapter

3. Slowly wither away as you stated at the loading animation for the page that never loads

### Expected behavior
To actually load the pages and cover art

### Actual behavior
It never loads...

## Other details
I've tried every possible option to fix it such as clearing cache and force stopping, uninstalling and reinstalling, trying forks, uninstalling and reinstalling extensions, vpn, EVERYTHING

Please don't close this issue because it's not just a single extension not working, it's all of them...

**Comment by ethan061903** [comment]
Please give it a look and not dismiss it as a wrong category to report the bug

**Comment by arkon** [comment]
Not sure how to help with the provided info. Have you tried a different phone

**Comment by ethan061903** [comment]
OH MY GOD I JUST HAD TO RESTART MY ROUTER

**Comment by ethan061903** [comment]
Btw I did try on a different phone and it worked so yeah

**Comment by ethan061903** [comment]
Also the way I found out to restart the router is that it started working when I was in mobile data and broke when I was on wifi (leaving this here to let people know in case this happens to them)
