### ISSUE TITLE
[Bug] Language Setting cause Browse limitations.

### ISSUE THREAD

**Issue by skyhong2002** [inorichi/tachiyomi#4005]
## Device information
* Tachiyomi version: Stable 0.10.5
* Android version: 11
* Device: Google Pixel 4a (4G)

## Steps to reproduce
1. First step

Set device language to Chinese (in my case), and download Extensions which supports Chinese.
Then tap "Extension info" and activate all to language.

2. Second step

Set device language back to English.

### Expected behavior
Browse sources should list all the language I activated.
When I global search for manga, each sources should appear.

### Actual behavior
This happened instead.
It only shows English reasults.

## Other details
Additional details and attachments.
It happens to:
E-Hentai (supports many languages)
NHentai (supports chinese, english, japanese, and others)
Jimmamtiantang (only chinese)
Hanhuaren (only chinese)
etc.

**Comment by arkon** [comment]
Enable the languages from the source screen at the top right.

**Comment by skyhong2002** [comment]
Wow, I didn't noticed that until now, thanks a lot!
