### ISSUE TITLE
[Bug] Whole chapter page was corrupted

### ISSUE THREAD

**Issue by ZackCelestial** [inorichi/tachiyomi#4006]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Smartphone 

Azur Lane Comic Anthology (Mangadex) Volume 7 Chapter 6 whole chapter page was gone and can't read.

**Comment by scb261** [comment]
https://github.com/inorichi/tachiyomi/issues/3573#issuecomment-701621703

**Comment by CarlosEsco** [comment]
see above
