### ISSUE TITLE
Issue with readcomiconline YAML source

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#401]
I'm not sure if this is the right place for YAML source issues but here it goes:

I'm having issues with comics - "Sunstone", "Switch" and "Death Vigil". Odly enough they are all by the same author. The problem is that nothing shows up - no covers, description or anything. And it says there are no chapters while in browser from the same device everything is alright.  

r820
Android 5.0.2

This is what I get in the app:

![screenshot_2016-07-21-22-39-41](https://cloud.githubusercontent.com/assets/7024084/17036253/31a5a490-4f94-11e6-8d6b-702fb6ef64b5.png)

This is in the browser on the same device:

![screenshot_2016-07-21-22-44-20](https://cloud.githubusercontent.com/assets/7024084/17036409/d83fec70-4f94-11e6-806e-e4227c228af9.png)

![screenshot_2016-07-21-22-44-34](https://cloud.githubusercontent.com/assets/7024084/17036412/dbcdafb2-4f94-11e6-96e2-a4f1f8b81a47.png)

**Comment by j2ghz** [comment]
I don't know why I don't get notified about comments on my gists :(

**Comment by j2ghz** [comment]
It loads this page: http://readcomiconline.to/Search/Comic?keyword=sunstone , which is supposed to list search results, but instead, because there's just one comic with sunstone in name, it goes directly to the comic.

**Comment by j2ghz** [comment]
@Bloodwork temporary fix: search for `sun` instead, it finds 4 comics, select sunstone

**Comment by Bloodwork** [comment]
Nice! Thank you for the help. I got them all by searching` sun` for Sunstone, `death` for Death Vigil and `sw` for switch.

**Comment by Bloodwork** [comment]
Will there be a fix for the `a page list empty` error in the future? It's interesting that this site has the chaptcha issue but Kissmanga doesn't. Or is it a YAML specific issue?

**Comment by j2ghz** [comment]
It's site specific, I don't know what cloudflare uses to determine it's time to ask for CAPTCHA, but there are several levels of severity https://support.cloudflare.com/hc/en-us/articles/200170096-How-do-I-turn-the-CloudFlare-captcha-challenge-page-off- . I guess they set it more severe than other sites. It may be possible to show the CAPTCHA to you and have you solve it. I don't know whether it's planned.

**Comment by Bloodwork** [comment]
I see. It's not a huge issue but I hope @inorichi will implement captcha solving functionality in the future if it's technically possible.

**Comment by inorichi** [comment]
It would have to open a browser tab, but no plans for it yet. Closing as it was "fixed". When POST requests are properly implemented in the parser it shouldn't happen anymore.
