### ISSUE TITLE
Mangasee extension Title cover

### ISSUE THREAD

**Issue by Akarui39** [inorichi/tachiyomi#4011]
## Device information
* Tachiyomi version: 10.5
* Android version: 10
* Device: redmi note 8 pro

## Steps to reproduce
1. Install mangasee extension
2. Check latest updates

### Expected behavior
Title cover should be shown.

### Actual behavior
Title cover appers as corrupted.

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
Wrong repository. Try *More > Settings > Advanced > Clear database* and *Refresh library manga covers*. If won't help, open the issue in https://github.com/inorichi/tachiyomi-extensions
