### ISSUE TITLE
Mangawt http error 403

### ISSUE THREAD

**Issue by kadiranul** [inorichi/tachiyomi#4012]
Mangawt is has a error pls edit :3 
Source : https://mangawt.com (turkish)

**Comment by scb261** [comment]
1. Wrong repository, next time use https://github.com/inorichi/tachiyomi-extensions for source issues
2. It was 403 for me and it works fine after [solving captcha in webview](https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-a-captcha)
