### ISSUE TITLE
[Feature Request]  new extension.

### ISSUE THREAD

**Issue by Bikeam-tech** [inorichi/tachiyomi#4014]
there is a new site for kissmanga which is 
www.kissmanga.org
so, if it is possible please add this site as an extension.

## Why/User Benefit/User Problem
it is much better than the old kissmanga. As it's the most loved site for manga lovers.
 
Thank you.

**Comment by CarlosEsco** [comment]
please read the text you deleted.  this repo is not for extensions requests and we have no plans to add kissmanga back
