### ISSUE TITLE
[Feature Request] options to change timeout for loading content

### ISSUE THREAD

**Issue by Jaykoerner** [inorichi/tachiyomi#4018]
## Why/User Benefit/User Problem
Allows loading of all content on slower sources, allows a more pleasant search experience with proper thumbnails even if they load slowly

Will also be useful as a work around to make sources slowing the loading for tachiyomi users usable till the extension is updated to either bypass the check or updated to interact with a change in the site

## What/Requirements

A option added to settings for either then main app or the individual extensions settings to change the default timeout

**Comment by arkon** [comment]
Slower sources already have longer timeouts set in the extensions when needed.

The only reason it may not work for someone is if they have crazy slow Internet, but you should ideally just find a site that works better for your location in that case.

If you're finding certain sources take too long to load, you can request for them to be updated in https://github.com/inorichi/tachiyomi-extensions
