### ISSUE TITLE
Library retaining categories after deletion

### ISSUE THREAD

**Issue by QuestofIranon** [inorichi/tachiyomi#402]
Found this while doing the list mode, if a category is deleted any categories after it are just copied over it. So if there are 2 categories and you delete the first, the second category still exists, but without a tag, and the first category becomes the second category. If you delete the last remaining category the deleted category will still have focus when the user returns to the main library screen as well. You can still scroll to the last deleted category as well but it doesn't get focus, so it'll just return to the default list.

This is only until the user goes to a different area like Catalog and library refresh doesn't fix it.

I'll attempt to fix it, I haven't looked into it too much yet though.

Version: r825

**Comment by inorichi** [comment]
Is this still an issue?
