### ISSUE TITLE
App crashes when setting default sort for all manga in library

### ISSUE THREAD

**Issue by arun07as** [inorichi/tachiyomi#4020]
## Device information
* App version: 0.10.5-2807 (standard, 8aa6486b, 51)
* Android version: 9 (SDK 28)
* Android build ID: LLD-AL10 9.1.0.173(C675E9R1P4)
* Device brand: HONOR
* Device manufacturer: HUAWEI
* Device name: HWLLD-H
* Device model: LLD-AL10
* Device product name: LLD-AL10

## Steps to reproduce
1. Take any manga in library
2. Take the option to change the sorting order of the manga
![Screenshot_20201108_131942_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460230-6b29a800-21c8-11eb-860f-038eac058ddf.jpg)
3. Change the sort ( Mine was originally by source, changed it to by chapter number )
![Screenshot_20201108_131955_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460234-78469700-21c8-11eb-9aa5-e9b86592ae32.jpg)
4. Click on the 3 dots. It will show a drop-down giving you the option Set as default. Choose set as default
![Screenshot_20201108_132002_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460237-85638600-21c8-11eb-91f0-a078366dd483.jpg)
5. A popup appears with a check box "Also apply to all manga in my library". Tick it and press ok.
![Screenshot_20201108_132008_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460241-901e1b00-21c8-11eb-9f6b-ccc47d57ccda.jpg)
![Screenshot_20201108_132108_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460244-990eec80-21c8-11eb-8f0d-68e0f58e54f0.jpg)
6. Try to do some action. In my case, I went back to library and tapped on any manga ( or just click on the 3 dots at the top of the manga details screen ). App freezes for some time and then I get a system system alert saying Tachiyomi isn't responding
![Screenshot_20201108_132304_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/17740186/98460249-aa57f900-21c8-11eb-8fb2-fb9937f3de65.jpg)

## Issue/Request
App crashes when setting default sort for all manga in library.

When I close and reopen the app, it works fine, but the default sort has not changed for all other manga. For example, the sort changed for "Trash of the Count's family" which is the manga I changed it for, but sort didn't get updated for other manga in my library ( I checked around 5 manga. Too lazy to check them all ). They are still on sort by source.

## Other details
I have 3 categories ( including default ) and over 1000 manga in library. I tried out this set as default for the first time around 1 week ago. Had this issue back then as well

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by arkon** [comment]
No logs provided, closing.

**Comment by fuwizu** [comment]
i had the same crash,
i have the log here
[](https://pastelink.net/2k7be)

**Comment by arkon** [comment]
@fuwizu report SY crashes in the SY repo.
