### ISSUE TITLE
My library is empty but the mangas are bookmarked

### ISSUE THREAD

**Issue by EdNa1392** [inorichi/tachiyomi#4022]
## Device information
* Tachiyomi version: 10.5
* Android version: 8.1.0
* Device: Moto G5s plus

## Steps to reproduce
1. First step
It's start from when i update the webtoon resource after that i get my library update from my smartphone notification. After i click that, tachiyomi app was opened but my library is empty.

2. Second step
Restarted the app and my smartphone, bookmarked and unbookmarked mangas and delete the unused resource

### Expected behavior
My library come back

### Actual behavior
All is empty (library, history, updates), i can't even do the backup.

## Other details
Additional details and attachments.
![Screenshot_20201109-033407](https://user-images.githubusercontent.com/74154104/98482824-f2196780-223e-11eb-897e-ef0ab7aacf35.png)
![Screenshot_20201109-032202](https://user-images.githubusercontent.com/74154104/98482828-f6de1b80-223e-11eb-8608-85d8491d9f89.png)
![Screenshot_20201109-031815](https://user-images.githubusercontent.com/74154104/98482832-03fb0a80-223f-11eb-8bb0-480a8e44f2b7.png)
![Screenshot_20201109-031931](https://user-images.githubusercontent.com/74154104/98482834-08272800-223f-11eb-9329-0772f6220945.png)
![Screenshot_20201109-030500](https://user-images.githubusercontent.com/74154104/98482835-08bfbe80-223f-11eb-9ca4-9a558cd7dd41.png)

**Comment by arkon** [comment]
I have no idea how, but based on the backup error message, your database is stuck in a broken state.

This has never come up before AFAIK, so I'm not sure if there's any way to really help you in this scenario unfortunately.
