### ISSUE TITLE
Goodreads tracker integration

### ISSUE THREAD

**Issue by cmxgv** [inorichi/tachiyomi#4023]
Is it possible to add whatever is read from tachiyomi to goodreads list to keep track of all the comics/graphic novels/manga read ?
Alternatively , is it possible to dump out a csv to be added to goodreads ?

**Comment by arkon** [comment]
Goodreads does have an API, but I'm not entirely sure if it fits the tracker system's needs or not: https://www.goodreads.com/api

If someone's interested, they can look into this more.

**Comment by ghostbear** [comment]
> Goodreads does have an API, but I'm not entirely sure if it fits the tracker system's needs or not: https://www.goodreads.com/api
> 
> If someone's interested, they can look into this more.

It seems that Goodreads is planning to retire its API

Source: [Goodreads plans to retire API access, disables existing API keys](https://joealcorn.co.uk/blog/2020/goodreads-retiring-API)

**Comment by arkon** [comment]
RIP Goodreads.
