### ISSUE TITLE
Covers still don't show up after update. 

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#403]
Updated to 0.2.3 and some covers still don't show up:  http://i.imgur.com/hTVei2T.jpeg

Only thing that gets the covers back is removing a manga from my library and looking for it again in the catalog,  at least my "read"  progress is being kept which is pretty nice.

**Comment by pitman10** [comment]
Seems like removing/adding without going into the library does bring back the cover as well.

**Comment by pitman10** [comment]
https://gfycat.com/BlissfulNecessaryArrowcrab

**Comment by inorichi** [comment]
The issue that caused it is fixed, but it won't help with already broken covers. One of the workarounds is to remove/add to library like you said, and another one is to clear the application's cache (from Android, not in the settings of Tachiyomi).
