### ISSUE TITLE
[Feature Request] <Add sort by author and sort by artist>

### ISSUE THREAD

**Issue by PhantomO2** [inorichi/tachiyomi#4030]
Please, In the library section of the tachiyomi add options to sort by artist and sort by author.

How it will help users:-
I don't know about others but I have a lot of downloaded "doujinshi". So, the sort by "artist" really help while reading "doujinshi" created by a particular artist. Otherwise I usually have to "remember" and "type" the name of the "artist" in the "search section" to find a particular artist the has created "doujinshi". If the "doujinshies" are already sorted by the artist then I can just look at the artstyle and can see all the "doujinshi" bunched up together by that particular artist and other artists as well.

**Comment by arkon** [comment]
Long press the artist or author to copy the text.
