### ISSUE TITLE
Source Mangasusu had change his domain

### ISSUE THREAD

**Issue by Gungperd** [inorichi/tachiyomi#4032]
![Screenshot_2020-11-13-18-11-03-399_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/72451318/99063628-b9331700-25df-11eb-871e-beca0a767344.jpg)

Mangasusu change his domain from .site to .bid

**Comment by scb261** [comment]
Wrong repo, see https://github.com/inorichi/tachiyomi-extensions/issues
