### ISSUE TITLE
[Feature Request] Panel Detection for Guided View

### ISSUE THREAD

**Issue by IneonInoodle** [inorichi/tachiyomi#4033]
Many of the new comic readers have guided view which jumps from panel to panel. Could be very useful for manga

Many comic readers they must manually set this up for each comic, but I found this comic reader which supports this feature on generic CBR and CBZ. 

It works very well (it takes a bit of time to scan the pages first) - similar to text recognition ai maybe. But Im not 100% how the algorithim works.

As a side note this app also has a cool manual panel select mode where you draw a box by click and drag and on release zooms in to that box size. 

Here is a link to the app I am talking about https://play.google.com/store/apps/details?id=es.dexx.solutions.comicreader.comictime&showAllReviews=true

## Why/User Benefit/User Problem

This feature would set this reader truly appart from others, and is proven to work well in the app.  Doesnt work in all cases but most managa have clear box pannels so it would work with them. 

## What/Requirements

When guided view was set for a manga, it would detect the panels and swipe to go through them one by one

**Comment by loocool2** [comment]
denied already as per https://github.com/inorichi/tachiyomi/issues/414
