### ISSUE TITLE
[Bug] <Mangafreak is not loading any manga and updating chapters saved in my library>

### ISSUE THREAD

**Issue by hedrickdocks** [inorichi/tachiyomi#4035]
---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 7.1.1
* Device: OppoA71

## Steps to reproduce
1. First step, update extension server of Mangafreak
2. Second step, enhance the connection between Mangafreak and tachiyomi

### Expected behavior
This should happen. Manga from Mangafreak shoul be loading and updating chapters without any problem

### Actual behavior
This happened instead. Mangafreak is not loading and updating any manga and sayong "java.lang.exception: Failed to bypass Cloudflare"

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
1. Wrong repository, see https://github.com/inorichi/tachiyomi-extensions
2. Open the site in [webview](https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-a-captcha) to bypass cloudflare

**Comment by hedrickdocks** [comment]
> 1. Wrong repository, see https://github.com/inorichi/tachiyomi-extensions
> 2. Open the site in [webview](https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-a-captcha) to bypass cloudflare

it's still not working even if i open in WebView
