### ISSUE TITLE
[Catalogue] Raw mangas

### ISSUE THREAD

**Issue by choolastre** [inorichi/tachiyomi#404]
Do you think you can add any raw manga catalogue? It will be the only app to have it. Sources for raw manga: http://raw.senmanga.com/ (best), http://online.mangaraw.net/, http://mangahead.com/Manga-Raw-Scan,
Thanks.

Version:  v0.2.3 android

**Comment by ThePreviousOne** [comment]
Im Starting Work on that now, but so you know MiMangaNu has senmanga raws

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).

**Comment by kavin-90** [comment]
what is know is` raw.senmanga.com` has DDL but only for register user but on `beta.senmanga.com`
