### ISSUE TITLE
[Feature Request] migrate tracking

### ISSUE THREAD

**Issue by Slowxzy** [inorichi/tachiyomi#4043]
---

## Device information
* Tachiyomi version: Stable 0.10.5
* Android version: 10
* Device: Samsung a70

## Steps to reproduce
1. add tracking to any manga
2. try migrating to other source 

### Expected behavior
it should migrate the checked boxes 

### Actual behavior
it removes the original source from the library but it doesn't remove the tracking 

## Other details
 can you also remove the marked read on the original source

**Comment by Slowxzy** [comment]
sorry for posting it twice

**Comment by arkon** [comment]
> can you also remove the marked read on the original source

So are you talking about the trackers or just the chapter read status? And why?

**Comment by Slowxzy** [comment]
I am actually talking about the both. for why I asked this... cuz it annoys me and that's all.

**Comment by arkon** [comment]
Why? If you really want it to, you can clear the states in Settings > Advanced > Clear database.
