### ISSUE TITLE
[Bug] Splash & Biometric screens in light theme even though app is in dark theme

### ISSUE THREAD

**Issue by ChrRubin** [inorichi/tachiyomi#4044]
## Device information
* Tachiyomi version: Preview r2815
* Android version: 6.0.1
* Device: Huawei RIO-L01

## Steps to reproduce
1. Launch app

Unfortunately I don't have other devices to try to reproduce this issue. The splash and biometric unlock screens used to be in dark theme before today, and this just happened to me after restarting my phone.

### Expected behavior
Both splash and biometric unlock screens should be in dark theme if it is selected in settings.

### Actual behavior
Both splash and biometric unlock screens are in light theme instead.

## Other details
I used to be on an older preview version (r2804 if i recall correctly) when this happened. I've tried force closing the app, updating to latest preview, and reinstalling with the latest preview version to no avail. Even after reinstalling (which reset the app theme back to light), changing to dark theme still kept these screens on light theme.

Honestly I was starting to think that I might have hallucinated the splash and biometric screens having a dark theme, but seeing #2540 at least confirmed to me there was a dark themed splash screen.

If this happens to just be an issue with just my specific device, then so be it. I can live with a little bit of light theme. I was just extremely confused when this issue started happening to me.

**Comment by arkon** [comment]
The splash screen follows your device light/dark theme

**Comment by ChrRubin** [comment]
Isn't device light/dark theme introduced in Android 10? So devices that don't support this feature will just default back to the light theme splash screen?

**Comment by arkon** [comment]
It was introduced in Android 9 as a developer option and Android 10 to regular users.

And yes, it'd default to the light splash screen. Always has, and always will.

**Comment by ChrRubin** [comment]
OK then. I was just extremely confused since it used to use the dark theme splash screen + biometric unlock before today.

Thanks for the clarification though.
