### ISSUE TITLE
[Bug] Manhwatop java.lang.Exception:failed to bypass claudflare

### ISSUE THREAD

**Issue by lilmai2x** [inorichi/tachiyomi#4045]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 6

Hello first time sharing issue here can someone help me please 😊

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475
