### ISSUE TITLE
[bug] app won't download missing pages in already downloaded chapter.

### ISSUE THREAD

**Issue by zimakkkk** [inorichi/tachiyomi#4046]
* Tachiyomi version: 0.10.5
* Android version: 8.0.0
* Device: sony xperia xz

## Steps to reproduce
1. download a chapter. 
2. delete files from phone directory. 

## Issue/Request
after fully downloading a chapter if perhaps a picture is corrupted and you need to delete it the app doesn't detect the deletion and the change in the difference between the number of downloaded pics in the download folder and the number of actual pages in the chapter. there is no way to download the missing pages unless you move the downloaded chapter out of the folder and start a fresh download and moving the already downloaded pages to the chap_temp file. 
I'm not sure if this is a bug or it's just not implemented yet.(if the later i want this to be a request post.)

**Comment by arkon** [comment]
Force close the app and reopen it. It generally doesn't check the disk except on launch since it's slow.

**Comment by zimakkkk** [comment]
> Force close the app and reopen it. It generally doesn't check the disk except on launch since it's slow.

nope. it still says the wrong number if pages and won't download anything

**Comment by Jacekun** [comment]
Happens the same to me sometimes. My work around is:
1. pause the download,
2. stop Tachiyomi App,
3. delete the corrupted pages,
4. Open Tachi and resume.

**Comment by zimakkkk** [comment]
> Happens the same to me sometimes. My work around is:
> 
> 1. pause the download,
> 2. stop Tachiyomi App,
> 3. delete the corrupted pages,
> 4. Open Tachi and resume.
> 
> EDIT: This is hard to reproduce in a few tries, so _programmatically_ adding a workaround is possibly hard.

@Jacekun 
it's easy to reproduce. cause my problem is after the download is finished until the "folder" of the downloaded chapter isn't deleted the app still says that the chapter is downloaded even when i have deleted every image in that folder. and when every image in that chapter's folder is gone when you open the chapter in the app it just says that there is no page in chapter and won't download anything either.

**Comment by arkon** [comment]
Wait, you're leaving the folder? This is intended behaviour.  There's no way for the app to know if the pages have completely changed, e.g. everything was shifted by 1 on the site.

You'd need to delete the folder and redownload it.

**Comment by zimakkkk** [comment]
> Wait, you're leaving the folder? This is intended behaviour. There's no way for the app to know if the pages have completely changed, e.g. everything was shifted by 1 on the site.
> 
> You'd need to delete the folder and redownload it.

oh well Allright.
