### ISSUE TITLE
[Bug] <cannot download. Tried both 10.5 and canary>

### ISSUE THREAD

**Issue by mecoromeo** [inorichi/tachiyomi#4054]
## Device information
* Tachiyomi version: 10.5 and 10.5.2827
* Android version: 11
* Device: Poco F1

## Steps to reproduce
1. Try downloading manga
2. It would either get "error" (no error message, just that). Then checking downloads, it'd be there and stuck there. Even if you cancel and redownload it'd download fast).

FYI You can see the images using a file manager as _tmp, but can't remove the tmp, even if you move the images it won't get recognized

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
Does the chapter name contains an apostrophe?

**Comment by mecoromeo** [comment]
None sir. Just shows human high-light film_Chapter_tmp

**Comment by scb261** [comment]
There was a bug with apostrophe #3778, but it was fixed in Android update. If you can't remove/rename the folder with file manager, then I guess it's a similar bug on Android side

**Comment by mecoromeo** [comment]
I'm on November A11 awaken rom. I couldn't find a fix when redownloading and i actually tried deleting TMP file and redownload the manga but issue persists.

Although i found a workaround by moving the tmp files to "local" . Guess that's what I'll do for now

**Comment by arkon** [comment]
Unless someone else can reproduce this in a different Android 11 ROM, this is likely an issue with your ROM.
