### ISSUE TITLE
[Feature Request] Tags and Description automatically load to manga added to library

### ISSUE THREAD

**Issue by RussianToilette** [inorichi/tachiyomi#4056]
## Why
In the current system, clicking on the cover of a manga (not to read it, just to get to the tags, description etc. screen) will load in its tags and description, which otherwise stay unloaded. This is the only way to load these in, as updating the library will still not do this. What this means is that for people who go through adding a bunch of manga to their library quickly without pressing the covers (via hold-clicking in the extension page) cannot search by tags unless they go through each and every manga in their library, loading them all in manually. (and yes I am mainly talking about myself, but I can't be the only one)

## Requirements
EITHER have a setting where manga added in to the library automatically have their tags loaded in, OR just make this also happen whenever you update your library.

**Comment by arkon** [comment]
The automatically refresh metadata setting already does this.
