### ISSUE TITLE
[Feature Request] Share link/text to global search in app

### ISSUE THREAD

**Issue by VorAndVik** [inorichi/tachiyomi#4058]
## Why/User Benefit/User Problem
Convenience in finding manga. 
There will be no need to copy/paste titles.

## What/Requirements
Add the application to the pop-up window with messengers.
If share a link, she looks for a suitable extension and searches for it.
If share the title, it conduct a normal search.

**Comment by arkon** [comment]
Extensions handle links directly if implemented.

Sharing doesn't really make sense to invoke a search, but maybe this could be added: https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999

**Comment by VorAndVik** [comment]
> Extensions handle links directly if implemented.
> 
> Sharing doesn't really make sense to invoke a search, but maybe this could be added: https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999

I found several similar requests. Is there a chance for implementation?

**Comment by arkon** [comment]
Chance for what implementation?

**Comment by VorAndVik** [comment]
Open links to manga in the app if the required extension is installed.

**Comment by arkon** [comment]
They do:

> Extensions handle links directly if implemented.

You need to request it per-extension if you want more.

**Comment by VorAndVik** [comment]
> They do:
> 
> > Extensions handle links directly if implemented.
> 
> You need to request it per-extension if you want more.

Thanks. I did not know this.

**Comment by paulo27ms** [comment]
> Extensions handle links directly if implemented.
> 
> Sharing doesn't really make sense to invoke a search, but maybe this could be added: https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999

I feel like might not appeal to everyone as it might be seen as Tachiyomi bloating stuff outside of the app. Personally sharing to search makes perfect sense to me as that's how some apps also handle converting URLs quickly and without navigating a lot of menus (like Youtube download apps or web to PDF apps, for example).
