### ISSUE TITLE
Feature Request: "In Library" Indicator in catalogue view

### ISSUE THREAD

**Issue by YuukiMinoru** [inorichi/tachiyomi#406]
it would be useful to be able to tell if a manga is currently included in the library while looking at the catalogue manga list.

A bookmark icon in the corner of the cover would be nice.

**Comment by null-dev** [comment]
You should be able to tell, manga in your library should be whitened over a bit on the catalogue.

**Comment by NoodleMage** [comment]
Like @null-dev said. The cover is transparent when manga is in library.

**Comment by ruudschouten** [comment]
I think he meant that if the title is already in your library from a different catalogue

**Comment by YuukiMinoru** [comment]
ah. In that case the problem only arises when covers fail to load.

I thought the whiter tint was for manga's that had been read, not just for ones that were in the library.
