### ISSUE TITLE
[Feature Request] <cancel queue >

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#4061]
## Why/User Benefit/User Problem
Whenever I end up downloading a wrong manga, I have to cancel all the mangas in my download queue and download them again. And sometimes, I have to cancel the chapters of that wrong manga one by one. But it's such a bother. 

## What/Requirements
I want a feature that will allow me to cancel download queue in a certain manga .

**Comment by scb261** [comment]
Not sure if this should be part of #2860 or a separate issue

As workaround for now you can go to the manga info page, select queued chapters and tap remove button. But you need to select at least one downloaded chapter as well for the button to appear

**Comment by MxxS07** [comment]
> Not sure if this should be part of #2860 or a separate issue
> 
> As workaround for now you can go to the manga info page, select queued chapters and tap remove button. But you need to select at least one downloaded chapter as well for the button to appear

Oh. I didn't think it would work, but it did. Thanks.
