### ISSUE TITLE
[Feature Request] <Add Offline Option>

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi#4063]
## Why/User Benefit/User Problem
So that users do not spend unnecessary mobile data.

## What/Requirements
When you are watching a series on LectorManga or TuMangaOnline there are times when there are several versions of the same chapter. Users download the chapters from wifi to save mobile data and select which version of the chapters they want.

The problem arises when looking at the chapters later. When you read chapter 01 that you downloaded and you finish it, the next chapter is chapter 01 of another version that you did not download since you decided to see the previous version. The app begins to download the chapter to be able to show it and consumes mobile data.

What I want is a quick way to specify that I want to work offline so that it only shows what it downloads. Maybe a button on the display that can be easily turned on and off.

Thank you

**Comment by scb261** [comment]
More > Downloaded only
