### ISSUE TITLE
[Bug] <chapters with missing pages unavailable offline>

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#4064]
## Device information
* Tachiyomi version: v 0.10.5
* Android version: 6.0.1
* Device: vivo 1606

### Expected behavior
I just want to read those chapters with missing pages offline and just leave the missing pages as error. 

### Actual behavior
When I download manga, sometimes there are missing pages in a chapter. So it is impossible to read that chapter offline even though I already downloaded some of its pages. For example, the download queue shows that 16/17 pages of the chapter are already downloaded. But I can't read those pages offline because there's a missing chapter that is impossible to download.

**Comment by Jacekun** [comment]
This is a "quickfix" to that:
Check what the title and source is of that manga. On your Tachiyomi downloads folder, open the specified source and the manga title. Rename the folder with incomplete pages, by removing the **_tmp** at the end of the folder name.

**Comment by MxxS07** [comment]
> This is a "quickfix" to that:
> Check what the title and source is of that manga. On your Tachiyomi downloads folder, open the specified source and the manga title. Rename the folder with incomplete pages, by removing the **_tmp** at the end of the folder name.

Thank you. This method can help me a lot. But I'd still like it if this bug can be fixed by the next update.

**Comment by Izumichi** [comment]
> > This is a "quickfix" to that:
> > Check what the title and source is of that manga. On your Tachiyomi downloads folder, open the specified source and the manga title. Rename the folder with incomplete pages, by removing the **_tmp** at the end of the folder name.
> 
> Thank you. This method can help me a lot. But I'd still like it if this bug can be fixed by the next update.

Agreed.

**Comment by Jacekun** [comment]
> Thank you. This method can help me a lot. But I'd still like it if this bug can be fixed by the next update.

I think this is an intended behavior. I mean, what's the reason to read incomplete pages of chapters? I don't see this as a "bug".

**Comment by CarlosEsco** [comment]
Yea this isn't a bug.  Unless you can provide an actual reason that you would need to read partial chapters offline.  I just don't see the usecase

**Comment by MxxS07** [comment]
The issue is I can't download a chapter whenever there's a missing page. The download queue would stop and the chapter would not be downloaded. The missing chapter is usually just 1 out of 30 or more. Imagine downloading a manga and the whole manga is already downloaded except one chapter because there's a missing page. Would you find a new source with no missing page and download the manga again?

**Comment by Jacekun** [comment]
> The issue is I can't download a chapter whenever there's a missing page. The download queue would stop and the chapter would not be downloaded. The missing chapter is usually just 1 out of 30 or more. Imagine downloading a manga and the whole manga is already downloaded except one chapter because there's a missing page. Would you find a new source with no missing page and download the manga again?

That's the good thing about Tachiyomi. You aren't limited to one source. If I were you, I'd just find a source with complete pages for that one chapter. Easier and quicker to solve.
