### ISSUE TITLE
navbar bugged after latest update

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#4065]
## Device information
* Tachiyomi version: Preview r2827
* Android version: 10
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Hold down a manga in the library to select it.

## Issue/Request
The navbar has a bugged positioning, shouldn't it be at the bottom?

## Other details
![Screenshot_20201127-090833_Tachiyomi](https://user-images.githubusercontent.com/22413659/100426035-8b92a700-3090-11eb-8f34-14e647919ce3.jpg)

**Comment by arkon** [comment]
Reverted the edge to edge stuff for now, which this was related to.

For future reference, this was caused by the status bar not being accounted for when forcing the action toolbar to the bottom.
