### ISSUE TITLE
[Bug] Enabling 32-bit causes some pages randomly to load in inverted color

### ISSUE THREAD

**Issue by darshanio** [inorichi/tachiyomi#4067]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10, MIUI 12
* Device: Redmi K20 Pro

## Steps to reproduce
1. Enable 32-Bit color from settings
2. Randomly pages will appear in inverted color in a few manga (like from Mangahere extension open Tokyo Kushu, ch 01, page 06; screenshots attached)

### Expected behavior
![Screenshot_2020-11-28-23-05-33-119_eu kanade tachiyomi](https://user-images.githubusercontent.com/13926954/100522274-7f613380-31cf-11eb-8bd0-0807817c669a.jpg)

### Actual behavior
![Screenshot_2020-11-28-23-05-58-046_eu kanade tachiyomi](https://user-images.githubusercontent.com/13926954/100522297-999b1180-31cf-11eb-81c2-b2ecf95c9641.jpg)

**Comment by arkon** [comment]
Doesn't happen on my device. There may be something buggy with your device/ROM's rendering engine.
