### ISSUE TITLE
[Feature Request] add multi-threaded or multi-task downloading of comics to the software

### ISSUE THREAD

**Issue by hanxin1997** [inorichi/tachiyomi#4071]
## Why/User Benefit/User Problem
 can download comics at the same time faster

## What/Requirements
add multi-threaded or multi-task downloading of comics to the software

**Comment by scb261** [comment]
Was rejected before because source will ban you for this. There is multi-threading for up to 5 different sources though

**Comment by hanxin1997** [comment]
> 
> 
> Was rejected before because source will ban you for this [#1567 (comment)](https://github.com/inorichi/tachiyomi/issues/1567#issuecomment-410681741). There is multi-threading for up to 5 different sources though

Some sources are not restricted, and it is hoped that users can choose to download multiple tasks at the same time.

**Comment by arkon** [comment]
Not happening in 0.x since it'd be too difficult to add in. It'll be considered for 1.x.
