### ISSUE TITLE
[Bug] Shift up

### ISSUE THREAD

**Issue by Ranennder** [inorichi/tachiyomi#4075]
## Device information
* Tachiyomi version:  0.10.5-2850
* Android version: 10
* Device: OnePlus 7 PRO

## Issue/Request
There was a shift up after the swipe down. Because of this, it is not very convenient to choose a title and all the time I think that a new Chapter has appeared. Please, fix it 
## Other details
YT video as attachments.

https://www.youtube.com/watch?v=BJF8YMh7EGQ&ab_channel=%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B0%D0%9F%D0%B5%D1%81%D1%82%D1%80%D0%BE%D0%B2

**Comment by arkon** [comment]
Should be fixed in the next preview as edge to edge was reverted.
