### ISSUE TITLE
[Bug] Global Search order

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi#4076]
## Device information
* Tachiyomi version: prev r2850
* Android version: 10
* Device: Xiaomi redmi 8

## Steps to reproduce
1. browse
2. use global search

### Expected behavior
source which found manga should be on top (with loading if can), source which not found to bottom 

### Actual behavior
loading source on top, source which found manga and not found in bottom

## Other details
https://cdn.discordapp.com/attachments/694092459839455243/782929528644435988/Screenrecorder-2020-11-30-18-18-30-829.mp4

**Comment by arkon** [comment]
Reverted back to the existing behaviour.
