### ISSUE TITLE
[Feature Request] <filter for mangas that are not downloaded yet>

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#4081]
## Why/User Benefit/User Problem
To filter out the mangas and chapters that you will download. 

## What/Requirements
There should be not dowloaded filter on the library and in the manga chapters.

**Comment by CrepeTF** [comment]
Just press downloaded filter twice

**Comment by MxxS07** [comment]
> Just press downloaded filter twice
Is this supposed to be a joke? 'Cause it's not funny.

**Comment by MxxS07** [comment]
> > Just press downloaded filter twice
> Is this supposed to be a joke? 'Cause it's not funny.


Ejjw

**Comment by jobobby04** [comment]
There is a exclusion mode on filters by clicking it twice...

**Comment by AbdullahM0hamed** [comment]
Idk what you mean man, @CrepeTF has clearly reached the peak of comedy

**Comment by MxxS07** [comment]
> > > Just press downloaded filter twice
> > Is this supposed to be a joke? 'Cause it's not funny.
> 
> 
> Ejjw

@jobobby04 Really? It doesn't work for me though.

**Comment by jobobby04** [comment]
Its definitely in the latest release, check for updates

**Comment by jobobby04** [comment]
Nevermind, its only in the preview builds, just checked

**Comment by MxxS07** [comment]
@jobobby04 My tachiyomi is already up to date.

**Comment by az4521** [comment]
TachiyomiAZ has this feature :^)

**Comment by arkon** [comment]
Will be in the next stable release.
