### ISSUE TITLE
[Feature Request] <prioritize source with most chapters>

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#4083]
## Why/User Benefit/User Problem
To find a reliable source with most chapters easily. 

## What/Requirements
Put the source with the most chapters during global search.

**Comment by arkon** [comment]
See #2867

**Comment by MxxS07** [comment]
> See #2867

So, is this feature going to added in the next release?

**Comment by CarlosEsco** [comment]
It's a duplicate of an open issue.  Which is why this was closed
