### ISSUE TITLE
[Feature Request] Re-update manga if error

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#4085]
## Why/User Benefit/User Problem
When a manga gets an error for whatever reason, you can't know if it has new updates till it gets updated again, either going manually in its page (pain) or with another list update (pain again, the more if you have a big list).

## What/Requirements
Add a new menu with the latest list update errors, which lists all the manga that got one (from the error.txt).
Here, we can either tap "update all" to check all those manga that got an error, or just select some, if we wanna exclude some manga with an error we can't resolve.
After it checks up, they get removed from the list, leaving the list empty or the ones excluded.

**Comment by arkon** [comment]
Settings > Library > Show updates errors notifications

**Comment by antocs** [comment]
That's not what I was requesting, I got this idea right cause I have it enabled.
I get many errors sometimes, which means many manga in an automatic update don't get checked for new chapters.
So instead of checking manually every title, that would be an user-friendly way to check them agaim fast.

**Comment by arkon** [comment]
See #3226 for rationale against adding this.
