### ISSUE TITLE
[Bug] Hentaivn extension can't search manga

### ISSUE THREAD

**Issue by Sehai1** [inorichi/tachiyomi#4087]
## Device information
* Tachiyomi version: stable 0.10.5
* Android version: 10
* Device: xiaomi

### Expected behavior
When i search a manga or manga by tag. Extension can find

### Actual behavior
Could not find anything
![Screenshot_2020-12-03-17-48-46-097_eu kanade tachiyomi](https://user-images.githubusercontent.com/64726925/100999919-d3816480-358f-11eb-9b48-d1f08ca793f4.jpg)

**Comment by scb261** [comment]
Wrong repo, see https://github.com/inorichi/tachiyomi-extensions
