### ISSUE TITLE
[Feature Request] <download new chapters from mangas that I've started reading>

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi#4088]
## Why/User Benefit/User Problem
I know that an option to download new chapters already exists. But downloading new chapters even from the mangas that I haven't started reading yet will only get my storage full. With this option, the new chapters from the mangas that I've started reading will automatically download every library update. 

## What/Requirements
Add a new option to download new chapters only from mangas that I've started reading.

**Comment by arkon** [comment]
Categories are meant for this sort of thing.
