### ISSUE TITLE
Catalog: Dynasty Scans

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#409]
Would it be possible to add http://dynasty-scans.com/ as a catalog ?

**Comment by ThePreviousOne** [comment]
I am starting one now. but I don't have an account so I am curious, should I/ do I need one?

**Comment by Bloodwork** [comment]
All manga there can be read without an account so I don't think you need one.

**Comment by ThePreviousOne** [comment]
Done https://github.com/inorichi/tachiyomi/pull/424

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).

**Comment by frazse** [comment]
Am I blind or has this Source been removed from the repo or something?

**Comment by wopian** [comment]
@frazse https://github.com/inorichi/tachiyomi-extensions/pull/75
