### ISSUE TITLE
[Feature Request] A method of downloading

### ISSUE THREAD

**Issue by Turbo-Future** [inorichi/tachiyomi#4096]
**Tachiyomi Version**
Stable 0.10.5

----------------------------------------------------------------------------------------------------------------------------------------------

Can you guys make it so that when you download a manga, for example like Vagabond, instead of making it so that every time the manga downloads the source folder as well, can you add an option to remove this?  What I mean is like this: 

Normal Downlad:
**/Tachiyomi/downloads/Source name/Vagabond/Chp 1/pg1.jpg**

What I mean:
**/Tachiyomi/downloads/Vagabond/Chp 1/pg1.jpg**

I'm asking because it makes reading from local source easier. My download location is set to **/Tachiyomi/local**  so every time I download, the source folder gets in the way. It recognizes the manga however it shows "No Pages Found". So I have to get rid of the source folder, and then move the manga folder.  Kinda troubling

Thank you 

![](https://cdn.discordapp.com/attachments/725334951184302170/785358799258124318/Screenshot_2020-12-07-08-10-51.png)

**Comment by arkon** [comment]
No, it's there for technical reasons.
