### ISSUE TITLE
Catalog / Feature Request - ReadComicOnline

### ISSUE THREAD

**Issue by gedling** [inorichi/tachiyomi#410]
I know this is a manga app but would it be possible to add comics from ReadComicOnline.to? Only asking because it seems to use identical formatting to KissManga which means that scraping would be relatively easy? Thank you for producing and maintaining such an amazing app!

Version: 0.2.3 Android

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/wiki/YAML-Sources

**Comment by gedling** [comment]
Huh. TIL. Thank you!
