### ISSUE TITLE
[Bug] MyAnimeList login not working

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi#4100]
## Device information
* Tachiyomi version: all (stable + preview)

## Steps to reproduce
1. Attempt to login
2. Get error

## Other details
TBD

**Comment by kennethtran93** [comment]
Looks like MAL implemented 2FA, so perhaps a browser login should be implemented as a fallback? I was able to login to MALClient when they put in the webview browser login.

**Comment by arkon** [comment]
Yup, seems like it's failing due to the lack of a reCAPTCHA field.

**Comment by arkon** [comment]
Fix will be part of the next stable / preview releases.
