### ISSUE TITLE
[Sources Request] <Please add this Sources for Arabic Sources>

### ISSUE THREAD

**Issue by Daredroi** [inorichi/tachiyomi#4101]
1 - gmanga
https://gmanga.org

2 - manhwa.ae
https://www.manhwa.ae

3 -  mangaka3rb
https://www.mangaka3rb.com

4 - sa3i9a
https://sa3i9a.org

5 - manga.ae
https://www.manga.ae

6 - mangarabian
http://mangarabian.com

**Comment by CarlosEsco** [comment]
you didnt read any of what was posted in the template.
1. Search before opening an issue to verify there is not an open issue or the source already exists.
2.  1 source request per an issue opened
