### ISSUE TITLE
[Feature Request] A way to save app data

### ISSUE THREAD

**Issue by FairlyWicked** [inorichi/tachiyomi#4102]
## Why/User Benefit/User Problem
It would be nice if there was a way to save what manga I have bookmarked. I recently had to switch phones and lost all of my bookmarks. I had a lot of different manga bookmarked and unfortunately cannot remember them all. 

## What/Requirements
I would be able to see my bookmarks on other devices

**Comment by jobobby04** [comment]
Already exists https://tachiyomi.org/help/guides/creating-backups

**Comment by FairlyWicked** [comment]
Oops my bad. I'm so sorry
