### ISSUE TITLE
[Feature Request] using Fingerprint gestures to navigate. 

### ISSUE THREAD

**Issue by NeeHimo** [inorichi/tachiyomi#4107]
## Why/User Benefit/User Problem
(explain why this feature should be added)
 I always use  my thumb while reading and I started to feel pain but I want to continue reading although it hurts too much but I just cant stop reading so thought "What if we can use our fingerprint scanner as a navigation button?" 
## What/Requirements
(explain how this feature would behave)
If you find this request interesting please read this article. [How to add fingerprint gestures](https://developer.android.com/training/gestures)

Thank you! :))

**Comment by CrepeTF** [comment]
#1832
