### ISSUE TITLE
[Feature Request] Ask If Read This Chapter. (Updates Section) 

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#4108]
When accidentally Pressed The Wrong Chapter in Update Section... It will ask if "Would you Like to Read this chapter Or Continue... 
---

## Why/User Benefit/User Problem
It will Prevent us From Accidentaly Skip a Chapter... 

## What/Requirements
(explain how this feature would behave)

**Comment by CarlosEsco** [comment]
What scenario would you be clicking a chapter and not realize you didnt click the correct unread one?

**Comment by ImPudding-tech** [comment]
Or Instead Of Separating "Chapters"
I think it is easier if..
All chapters can be found in one series Is Merge... 
(e.g. Chapter 67, 68, and 69 Update Found In this Series) or 
(e.g. 7 New chapters Found In this Series)
And This Examples Are Placed Below the Series Title
![Screenshot_20201215_181855](https://user-images.githubusercontent.com/65703094/102203528-aaec5980-3f03-11eb-8781-ca5567e7290c.jpg)

**Comment by scb261** [comment]
Your second suggestion already has an issue for it #2774
