### ISSUE TITLE
Feature Request: Downloads Tab

### ISSUE THREAD

**Issue by Yauten** [inorichi/tachiyomi#412]
As you guys added a recently read tab, I think it'd be nice if you added a downloads tab, as I constantly find manga I do not remember downloading, download, which would help located these, and also as I use tachiyomi on multiple devices it'd really help with sorting manga that I have downloaded on one device, and not the other.

**Comment by j2ghz** [comment]
Downloaded filter in library?

**Comment by YautjaTNT** [comment]
Some of the like, yes, something. Something that shows downloads whether or not you have them bookmarked.

**Comment by j2ghz** [comment]
I think it won't be done, since AFAIK only bookmarked downloads are tracked. https://github.com/inorichi/tachiyomi/issues/385#issuecomment-231552608

**Comment by inorichi** [comment]
The app doesn't know which manga has downloaded chapters. It just converts the title to a string and check if the folder exists. Doing that for every single manga in the database can be slow.

It could list the downloads folder, but you won't be able to start reading from there, only delete the folder.

**Comment by Kamui-Solo** [comment]
Then maybe it would be good if we will automatically add to bookmarks manga which we downloaded? Very often I download some chapters for reading later, but forgetting to add this manga to bookmarks, and then I need find this manga in catalogue again for reading, but if there's no internet connection I can't do that.

**Comment by Efreak** [comment]
Perhaps you could solve this by listing the directory, and in each directory add a file like the per-chapter index.json. Tbh, this would be nice anyways, as it would allow copying files across devices without redownloading them

This could be even more useful if it was one of the [existing metadata formats](http://wiki.mobileread.com/wiki/CBR_and_CBZ#Metadata) for cbz files (json that gets stored in a zip header/comment, or an XML file in the archive). Using a [ComicInfo.xml](http://wiki.mobileread.com/wiki/ComicRack#Metadata) file with an extra tag would be amazing, as it would allow simply zipping the entire folder and renaming to .cbz to read it with FBReader, easily store it in Calibre, etc.

**Comment by Kamui-Solo** [comment]
I think "bookmark" manga is something like mark it favorite, but not currently reading. I can read manga and download some chapters, but I don't like it so much for adding to bookmarks. So download tab or something like this is musthave.
Moreover I've tested more manga readers for this function, and almost all of them has downloaded section. For example OpenManga, Manga Rock, Zingbox, Manga Bird, Manga Watcher X (need to add in library for downloading).
But tachiyomi has best reading modes, especially permanga reader type. So I hope for your app.

**Comment by arkon** [comment]
See https://github.com/inorichi/tachiyomi/issues/3355#issuecomment-647184494

We can keep this in mind when architecting 1.x, maybe.
