### ISSUE TITLE
[Feature Request] <Volume buttons to turn pages Set distance>

### ISSUE THREAD

**Issue by ChoBitsZ7** [inorichi/tachiyomi#4124]
Hello
I hope to add it to the reading setting. The volume button is turning pages (setting the page turning distance)
Reading mode (Webtoon mode) (vertical continuous)
Thank you

**Comment by arkon** [comment]
#2161 / #2785, probably.

**Comment by ChoBitsZ7** [comment]
> 您好，
> 我希望將其添加到閱讀設置中。音量按鈕正在翻頁（設置頁面翻頁距離）
> 閱讀模式（Webtoon模式）（垂直連續）
> 謝謝
