### ISSUE TITLE
[Bug] Thumbnails don't load in browse if not set

### ISSUE THREAD

**Issue by crisalis2** [inorichi/tachiyomi#4127]
## Device information
- Tachiyomi version: ~~r2807~~ 0.10.6
- Android version: 10

## Source information
- Name: Madokami
- Extension version: 1.2.4

## Steps to reproduce
1. Go to the Madokami source.
2. Notice thumbnails don't load.

### Expected behavior
Thumbnails load.

### Actual behavior
Thumbnails don't load.

## Other details
If you access a particular title (where chapters are listed), the thumbnail will load. Only thumbnails of titles whose list of chapters you access will load.

@tesu I guess.

**Comment by arkon** [comment]
I'll look more into this. I did change something with how things are loaded, so there's probably a bug.
