### ISSUE TITLE
[Bug] no tracking button in manga page

### ISSUE THREAD

**Issue by svetchkill** [inorichi/tachiyomi#4129]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: samsung s9

## Other details
The tracking button in 0.10.5 was next to "add to library" button but now it's gone. Was it removed? I notice the change in 0.10.6, i thought it was a bug and would be fixed in 0.10.7 but it's still the same.

![20201214_093220](https://user-images.githubusercontent.com/74079735/102033912-46d87100-3def-11eb-8723-b74a1dc7c40c.jpg)

**Comment by CrepeTF** [comment]
Relogin to your tracking service

**Comment by svetchkill** [comment]
I did. I even logged out and log in again to make sure. Clean app cache and everything.

**Comment by arkon** [comment]
Can you actually confirm that there's at least 1 tracker that shows as logged in in settings?

**Comment by svetchkill** [comment]
You mean this?
![20201214_095325](https://user-images.githubusercontent.com/74079735/102035122-3d043d00-3df2-11eb-9a68-80e37021ac14.jpg)

**Comment by arkon** [comment]
Thanks, it's probably an issue with the MAL fix that hadn't been reported yet.

I'll take a look at this at some point this week.

**Comment by svetchkill** [comment]
well uh.. good news, it fixed itself after 2nd clean install, i dont know what happened there lol
sorry for taking your time
