### ISSUE TITLE
Cover art just missing 

### ISSUE THREAD

**Issue by keccakec** [inorichi/tachiyomi#413]
There aren't really any steps to reproduce. I got on today, and, since the other day have lost the cover art for all manga I have in my library, with the exception being my most recent one. 

Version: v0.2.3
OS: Android 6.0

**Comment by keccakec** [comment]
It's probably also worth mentioning that the art is missing in catalogue (only for the original source), as well.

**Comment by inorichi** [comment]
Were they broken before 0.2.3 or its a fresh install from that version? Does it happen in every source or a specific one?

**Comment by keccakec** [comment]
It is a fresh install on a new device that I got the library for by recovering from a backup. It is also only the ones in my library that are missing pictures in the catalog. 

When I recovered, all pictures were there. Then I added a few more manga. Those manga still have pictures, and it appears only the original recovered manga don't. 

I'll try backing up and recovering again and seeing if that fixes it.

**Comment by keccakec** [comment]
I have no idea how to edit on mobile, so apologies for cluttering the post with edits, but this is a fresh install, then recovery: http://imgur.com/xKDnnMg

I haven't checked, yet, and likely won't get a chance until I get on my computer again tomorrow, but is there a way to edit the sources in the json? If so, I'll switch them all to another source to check if that's the issue.

**Comment by keccakec** [comment]
I just noticed that the manga that previously had images no longer do after the fresh install into recovery. 

Again, sorry for not knowing how to edit on mobile.

**Comment by inorichi** [comment]
Is the source kissmanga? The image library doesn't resolve the cloudflare challenge, you have to trigger some request in the source, like opening the catalog in kissmanga or refreshing the chapter list for some manga. They should load after that.

**Comment by keccakec** [comment]
Hmm, it doesn't appear to load the images even then. I did just notice that view was yet to be approved in xprivacy for tachiyomi, so that could have something to do with it somehow (Though I did another recovery after and the pictures were still missing). 

I also never mentioned I am using a rooted device, but I doubt that would result in such a weird bug. 

I don't mind switching the sources too much if it's a problem specifically with kissanime. It seems from it only affecting the old kissanime manga in the library/catalogue that it is a problem with requests from their website not reaching my app. I have been meaning to use batoto for a while anyway.

**Comment by jsilvermist** [comment]
Same thing happening for me,  mostly with mangahere,  but also others. 

I did a backup on latest stable version to restore in the latest dev version since I was going to use it for now,  as mangahere catalog doesn't have any images on stable but does on dev for Mangas I DON'T have in my library,  but nothing I restored from the backup will load the cover art now,  though anything Not in the library will show an image,  nothing in my library does,  even on catalog page.

**Comment by inorichi** [comment]
Try one of the following:

* Clearing the cache of Tachiyomi (from Android, not the app)
* Removing and adding to favorites
* Refresh the manga details from the info tab (if the url to the thumbnail has changed it won't be able to display it)

**Comment by jsilvermist** [comment]
Clearing the cache:
On 0.2.3 stable with images showing in my library but not in the catalog,  this broke all the images that used to be working and they won't come back now. 
On 0.2.3 dev build 842 with images showing in the catalog but not the library, this did nothing at all. 

Removing and adding to favourites, no change.
Removing, closing the app, reopening and readding to favourites, no change.

Going to info tab and pulling to refresh does restore the image, but is not a convenient method as I have over 200 mangas in my collection.

**Comment by inorichi** [comment]
Yeah I agree it's not a convenient method, but it's not an issue with the cache. The thumbnail url changed and then tachiyomi can't download the cover again (it was working in the stable version because the cover was already downloaded).

So the setting to add would be a "Update library manga details" or something like that.

**Comment by inorichi** [comment]
#462 will fix this.
