### ISSUE TITLE
MAL tracking BROKEN

### ISSUE THREAD

**Issue by gaemonton** [inorichi/tachiyomi#4130]
## Device information
App version: 0.10.7 (standard, c87ba62, 53)
Android version: 10 (SDK 29)
Device name: m30s
Device model: SM-M307F

## Steps to reproduce
1. MAL tracker is not updating shows HTTP 400 error

## Issue/Request
Please resolve this ASAP

## Other details
Additional details and attachments.
Mostly due to update from MAL website as it added 2FA.

**Comment by arkon** [comment]
Try clearing your cookies (Settings > Advanced) and re-logging into MAL.

**Comment by gaemonton** [comment]
Tried it. Other MAL client are also broken. See MAL update comments.

**Comment by arkon** [comment]
> Tried it. Other MAL client are also broken.

I'm well aware of the changes, v0.10.6 was meant to fix it. 2FA is irrelevant; I need more tangible info from users to fix it properly.

> See MAL update comments.

Did you forget to include a link to whatever you're referring to?

**Comment by gaemonton** [comment]
> > Tried it. Other MAL client are also broken.
> 
> I'm well aware of the changes, v0.10.6 was meant to fix it. 2FA is irrelevant; I need more tangible info from users to fix it properly.
> 
> > See MAL update comments.
> 
> Did you forget to include a link to whatever you're referring to?
https://myanimelist.net/forum/?topicid=1880551
People are saying recaptcha is messing it... 
I can't login now..

**Comment by arkon** [comment]
What'd you do to solve your issue?

**Comment by arkon** [comment]
Link from deleted comment for future reference: https://myanimelist.net/forum/?topicid=1880551

**Comment by gaemonton** [comment]
Restarted Phone just worked!!

**Comment by gaemonton** [comment]
Recaptcha was causing some issue for some people tho on MAL.
