### ISSUE TITLE
[Feature Request] Option to delete update history

### ISSUE THREAD

**Issue by Ahsan40** [inorichi/tachiyomi#4133]
![Screenshot_2020-12-14-19-43-36-357_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/30434801/102088165-bc226100-3e44-11eb-9551-4ccf86932811.jpg)

## Why/User Benefit/User Problem
It's a privacy feature. User can delete reading history, but what's the point if it still on the update list. It will increase the user privacy.

## What/Requirements
After long press there are few option become visible (Mark all, Download etc.), this feature should have added there.
![Screenshot_2020-12-14-19-47-54-888_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/30434801/102088565-4bc80f80-3e45-11eb-80b1-1d7fea968818.jpg)

**Comment by arkon** [comment]
This list only contains updates of things that are already in your library. If it's already in your library, the privacy justification isn't really valid.

If you're trying to hide some smut from other people who use your phone (and the biometric lock is insufficient for whatever reason), you can consider using third party app locking tools.
