### ISSUE TITLE
[Feature Request] Separate security option of hiding app content and blocking screenshots

### ISSUE THREAD

**Issue by xShirohi** [inorichi/tachiyomi#4135]
---

## Why/User Benefit/User Problem
I would like to hide the app contents when switching apps for privacy reasons in public but would like to keep the feature of being able to screenshot so that I can share images with friends.

## What/Requirements
Split the secure screen option into 2 options so that you can individually choose between blocking app content and preventing screenshots.

**Comment by arkon** [comment]
Not possible, this is a standard Android feature.
