### ISSUE TITLE
Http 404 error: on adding manga to MyAnimeList Tracker

### ISSUE THREAD

**Issue by centipede13** [inorichi/tachiyomi#4139]
---

## Device information
* Tachiyomi version:  0.10.7 (standard, c87ba62, 53)
* Android version: 10 (SDK 29)
* Android build ID: QKQ1.190828.002 test-keys
* Device brand: Xiaomi
* Device manufacturer: Xiaomi
* Device name: beryllium
* Device model: POCO F1
* Device product name: beryllium

## Steps to reproduce
1. Open any new manga 
2. Click on tracking
3. Select Manga Name(I use myAnimeList)
4. Click Ok

## Issue/Request
When I try to add new manga to tracker set to MyAnimeList "Http 404" error shows up.

## Other details
![Screenshot_2020-12-15-18-22-20-057_eu kanade tachiyomi](https://user-images.githubusercontent.com/24701563/102217280-5bf1f480-3f02-11eb-9993-8ece24e2854f.jpg)
![Screenshot_2020-12-15-18-22-23-067_eu kanade tachiyomi](https://user-images.githubusercontent.com/24701563/102217285-5e544e80-3f02-11eb-9f05-e8c03bb4cd81.jpg)
![Screenshot_2020-12-15-18-22-32-328_eu kanade tachiyomi](https://user-images.githubusercontent.com/24701563/102217287-5eece500-3f02-11eb-8814-cb89e035c82c.jpg)

**Comment by scb261** [comment]
Try to relogin into MAL, and after you enter login and password, click on profile

**Comment by arkon** [comment]
404 isn't the same as 400.

And yes, you may need to retry logging in a few times since it's a bit problematic right now.

I'll eventually replace this with a more reliable version in #4140.

**Comment by willyreza** [comment]
Mine is also broken

**Comment by Bikeam-tech** [comment]
> 404 isn't the same as 400.
> 
> And yes, you may need to retry logging in a few times since it's a bit problematic right now.
> 
> I'll eventually replace this with a more reliable version in #4140.

I have tried and no matter how many times I refresh and re-login, it still shows an error. so it needs to be fixed as soon as possible.

**Comment by willyreza** [comment]
> > 404 isn't the same as 400.
> > 
> > And yes, you may need to retry logging in a few times since it's a bit problematic right now.
> > 
> > I'll eventually replace this with a more reliable version in #4140.
> 
> I have tried and no matter how many times I refresh and re-login, it still shows an error. so it needs to be fixed as soon as possible. 

Mine too error

**Comment by centipede13** [comment]
> Try to relogin into MAL, and after you enter login and password, click on profile

I am already logged in and I also tried what you said but the error still persists and others are also facing the same issue.

**Comment by CarlosEsco** [comment]
Clear your cookies in advanced settings, then re login in tracker settings.

**Comment by CrepeTF** [comment]
If that doesn't work also try changing your password

**Comment by Bikeam-tech** [comment]
Thanks a lot for your help. your 1st tips worked perfectly.

**Comment by centipede13** [comment]
> Clear your cookies in advanced settings, then re login in tracker settings.

Thanks, this worked for me

**Comment by willyreza** [comment]
> > > 404 isn't the same as 400.
> > > 
> > > And yes, you may need to retry logging in a few times since it's a bit problematic right now.
> > > 
> > > I'll eventually replace this with a more reliable version in #4140.
> > 
> > I have tried and no matter how many times I refresh and re-login, it still shows an error. so it needs to be fixed as soon as possible. 
> 
> Mine too error

    Not work for me😭

**Comment by willyreza** [comment]
Not work for me😭

**Comment by CarlosEsco** [comment]
@willyreza  you did what i said above?

**Comment by CrepeTF** [comment]
@willyreza keep relogging, apparently that worked for someone
