### ISSUE TITLE
Add MangaTraders.org as a source

### ISSUE THREAD

**Issue by AceT72** [inorichi/tachiyomi#415]
Not necessarily an issue but mangatraders has the digitally coloured one piece comics available and it would be very convenient to have it on a mobile device due to one piece's immense popularity. It uses a very similar format to mangasee.co so I don't think this would be too difficult.

**Comment by JohnFlowerful** [comment]
Batoto has digital coloured One Piece too.

**Comment by AceT72** [comment]
While that may be true, batoto is also missing a plethora of chapters which leaves the reader kinda disjointed and desiring more, while mangatraders has every chapter available with no holes in between.

**Comment by inorichi** [comment]
There's already one request for this site in #145. Closing.
