### ISSUE TITLE
Request: Port the app to Universal Windows Platform

### ISSUE THREAD

**Issue by notnsane** [inorichi/tachiyomi#416]
I'm not sure if Microsoft would approve an app like this on the Microsoft Store, but if not, you guys can upload the .appx here on github and we can sideload the app using the Desktop App Installer: https://www.microsoft.com/en-us/store/p/app-installer/9nblggh4nns1

I know it's not an easy process, it would take months probably, but it would be really good for the FOSS community, to start providing some apps outside of the MS Store just like F-Droid does.
An app like this would be awesome for all Windows 10 desktops, and also could be potentially available to Windows Phones, laptops, Xbox, HoloLens and other products.

If you need help on where to start, ask me, I've been doing a bit of research on MS tools and "ecosystem" lately and I just published a small test app on the Windows Store without any coding at all (again, jsut a small test app), and for free if you use BizSpark.

**Comment by null-dev** [comment]
Probably not happening, this would require almost a complete rewrite of the
app (UWP uses a completely different programming language...).

**Comment by j2ghz** [comment]
For a while I've been thinking whether to start such a project (new app, not a port) (no ads, MAL sync and FOSS manga reader). Reasons why I haven't:

1. I haven't seen any interest (of people to use it and of people to help with development)
2. https://github.com/inorichi/tachiyomi/issues/383#issuecomment-233035553, which makes any other potential app other than tachiyomi unusable for me, and I won't make an app I won't use.

**Comment by null-dev** [comment]
Actually if you are looking for desktop manga reader that syncs with Tachiyomi: https://github.com/TachiWeb/TachiWeb-Server (shameless self-advertising).

Live demo: http://64.137.238.70:4567/

It's actually reasonably stable and is already on-par with some of Tachiyomi's features.

**Comment by inorichi** [comment]
What a great job you have done there! It looks very good! :+1:

Regarding porting this app to another framework, I won't do that, it would be a complete rewrite. Lately I don't even have time to work on Tachiyomi... Also, you can run Tachiyomi in Chrome with ARC Welder. The font of the covers looks bad (at least when I tried it some months ago), but everything else works fine.

Finally, UWP is still a Windows only solution. I would rather have a multiplatform app, and TachiWeb is a clear winner here.

**Comment by notnsane** [comment]
Thanks for all the comments! I've been trying to use Tachiyomi on Windows with an Android emulator but the tap and drag somehow stops working after a couple seconds, haven't found out why. 

I'll try using either TachiWeb-Server or try some of the other FOSS apps out there. Thanks again!

**Comment by inorichi** [comment]
I would try with ARC Welder. The font issue could be easily fixed (removing the font from the apk or compiling it without the font).

**Comment by Naomi010Sentzke** [comment]
Windows 10 might have native android app support in futre
https://www.theverge.com/2019/6/24/18715222/microsoft-surface-dual-screens-foldable-android-apps-rumors
I wonder if you guys will also test future releases on Windows 10 devices when it gets native android app support.

**Comment by narfanar** [comment]
ARC Welder works fine so far.

The process to get sources installed is annoying, though :/
