### ISSUE TITLE
can't download to sd card anymore

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#418]
I can't seem to download manga to my sd card anymore, it was working fine now it just adds them to the queue but doesn't start the downloads.

directory on sd card is storage/sdcard1/tachiyomi/downloads

also able to download to internal storage fine.

Version: r842 (also happens on 0.2.3)
android 5.1

**Comment by inorichi** [comment]
OS update?

You will have to use one of the predefined directories, like /storage/<sd card>/Android/data/...tachiyomi/files

**Comment by shogunreaper** [comment]
i don't have an update?

and like i said it was working before... i downloaded hundreds of chapters.

and i was also able to get it to start downloading a chapter but it got stuck after 8 pages.

the only predefined directories i have is

/storage/emulated/0/tachiyomi/downloads
/storage/emulated/0/android/data/eu.kanade.tachiyomi/debug/files

neither point to my sd card.

My device is rooted now if that matters.

**Comment by shogunreaper** [comment]
???

**Comment by inorichi** [comment]
Have you tried using a custom directory which points to the directory I mentioned?

**Comment by shogunreaper** [comment]
well i tried that but it didn't work either.

though after i restarted my tablet it seemed to work in my original directory again.
