### ISSUE TITLE
Catalog request   MangaGo

### ISSUE THREAD

**Issue by mrtort** [inorichi/tachiyomi#419]
First of all, i just love the app! Keep the great job
I dont know what complication creates the adding of sources, but i would love if you add Mangago.

I am moving from my previous reader to this one.

Version: v0.2.3
Android 5.1.1

**Comment by ThePreviousOne** [comment]
Here is a debug build of https://github.com/inorichi/tachiyomi/pull/424

[tachiyomi.zip](https://github.com/inorichi/tachiyomi/files/435995/tachiyomi.zip)

I imagine ther will be a ne release build in the next few weeks (pure speculation of course) but if you like you can use this until then

It will install alongside the release build

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
