### ISSUE TITLE
Auto download, delete

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#42]
Settings:
* [ ] How many next chapters to download upon reading a chapter
* [ ] Delete chapter when set as read

Menu in Library > Chapter list
* [ ] Download next 1/5/10/all chapters

**Comment by BlackSynder** [comment]
So is this happening? Would be amazing if it is. If you turn off downloaded and turn on unread, the second you finish a chapter, it dissapears and its hard to keep track of whats downloaded.

**Comment by jassibacha** [comment]
The "Download Next 1 / 5 / 10 / All" is an extremely useful thing to add, I didn't realize how much I used it until now.
