### ISSUE TITLE
Italian catalogs request

### ISSUE THREAD

**Issue by P4Ks** [inorichi/tachiyomi#420]
Hello, i've just discovered this great manga app and it's hands down the best Android manga reader so far (thanks reddit for the tip).
I'm here also to request to add also italian catalogs to the app. Usually other manga app have MangaEden, Itascan or NineManga as catalog sources.

Thanks!

Version:  v0.2.3
MIUI7 on Xiaomi Mi4C

**Comment by ThePreviousOne** [comment]
https://github.com/inorichi/tachiyomi/pull/445
I finished NineManga and am Currently working on MangaEden

out of curiosity which of these sites do you prefer if any?

**Comment by P4Ks** [comment]
Great!! imho at the moment the most complete source catalog is MangaEden and second place Itascan.
there is also a button to donate something?

good work!

**Comment by ThePreviousOne** [comment]
@inorichi I (think I ) completed this source but it tries to check the browser before loading which causes timeout you can implement it if you want but I wont

[Itascans.kt.zip](https://github.com/inorichi/tachiyomi/files/536016/Itascans.kt.zip)

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
