### ISSUE TITLE
Weird/incorrect download notification.

### ISSUE THREAD

**Issue by null-dev** [inorichi/tachiyomi#421]
Just noticed that the download notification goes negative (and apparently, I am downloading a negative amount of zero chapters)!

Screenshot of notification in question:
![1471568399270 1](https://cloud.githubusercontent.com/assets/9571936/17795685/65965cae-6588-11e6-87bb-1e74c0d67620.jpg)

**Version:** 0.2.3

__Other stuff that you probably won't need:__
**OS:** Android 6.0.1 Marshmallow (OxygenOS 3.2.4)
**Device:** Oneplus 3
**Basic specs:** 6GB RAM, Qualcomm Snapdragon 820
**Network status at time of bug discovery:** WIFI

**Comment by inorichi** [comment]
That's weird. Did it happen with 1 or more simultaneous downloads?

**Comment by null-dev** [comment]
A lot of downloads... I can't remember the exact amount but it was
definitely more than 100.

>

**Comment by inorichi** [comment]
Sorry I meant the setting.

**Comment by null-dev** [comment]
Oh, it was set to 3 simultaneous downloads.

>

**Comment by NoodleMage** [comment]
The queue size isn't [initialized](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt#L137). 

That's also why the amount of downloads is [negative](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt#L101). 

Bit hard to debug but will look into it when I have some time ;).
