### ISSUE TITLE
Why do i need to edit title to sync?

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#422]
Why can't it just grab the title automatically from the site it's using?

if for some reason its wrong then it can be edited manually.

i also get "Could not find manga" errors on some titles when trying to sync(Fairy tail and shingeji no kyojin to name 2) even though it provided me with the names fine.

**Comment by inorichi** [comment]
It was discussed and maybe it will be added as an optional feature. Not everybody wants to have everything linked or bind to an incorrect manga.

That error is shown if you have deleted the manga in your MAL. Try binding it again.

**Comment by shogunreaper** [comment]
an option to would be nice.

**Comment by Efreak** [comment]
I've had a few manga that couldn't be found on mal as well. I fixed it by editing the name and removing enough words from it until it showed up in the list. Try setting the name to `kyojin`, for example, and it should show all mangas with kyojin in the title

**Comment by rachmadaniHaryono** [comment]
Maybe option to use myanimelist url or manga id?
