### ISSUE TITLE
Manga wont download

### ISSUE THREAD

**Issue by xXShiina** [inorichi/tachiyomi#423]
I have a problem where the manga's that I want to download wont download. I have the download location set to my SD card, so if there's a need for the app to have permission for it to download to the SD card then please tell me how to enable that option.

A little more about my problem is that, When I select something to download it just displays that its "downloading" but the progress bar goes nowhere, Even after waiting some time.

I only use WiFi to download things on my phone, So I know that that is not an issue.

I use F-Droid to download this app and to keep it up to date.

App Version: v0.2.3
Phone: Samsung Galaxy S4
Android Version: 5.0.1
Carrier: Verizon

**Comment by kiskae491** [comment]
As far as I know any app that declares the WRITE_EXTERNAL_STORAGE permission is implicitly
granted this permission on android 5 and up and but I don't think Tachiyomi does it. Root your phone and apply sd fix or just download mangas to internal storage

**Comment by inorichi** [comment]
[Read this.](https://github.com/inorichi/tachiyomi/issues/386#issuecomment-231578473)

If you are using an external SD card with Android >= KitKat, you can only use one directory, even if the manifest declares `WRITE_EXTERNAL_STORAGE`. 

Writing to any folder should be possible, but it would require using the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html) which is annoying to work with. 

Selecting as downloads directory `<your sd card>/Android/data/<package id of tachiyomi>/files` will work (it should appear when you click the setting).
