### ISSUE TITLE
Multilingual Catalogues

### ISSUE THREAD

**Issue by ThePreviousOne** [inorichi/tachiyomi#427]
I want add a few catalogues like ninemanga that have multiple languages

Ideally I would create one source that could be used for all lang's
(for ninemanga this would mean baseUrl = "http://${lang.code}.ninemanga.com" )

The 'Problem' is, I don't know how to start

**Comment by inorichi** [comment]
Create a common `abstract class` for the source with the language (and the base url if the codes doesn't match for all the available languages), and the implementations of that abstract class will only implement the language (and the base url if it was needed).

**Comment by inorichi** [comment]
Closing this issue since it's support, not a feature/bug. You can still write here if you didn't understand something.
