### ISSUE TITLE
Status bar tint issue

### ISSUE THREAD

**Issue by M2ck** [inorichi/tachiyomi#43]
Colors from status and tool bars are a bit too different.
By the way could you tint navigation bar?
![screenshot_2016-01-20-17-32-06](https://cloud.githubusercontent.com/assets/6850125/12455526/597e8eec-bf9c-11e5-8404-cefee33e8aec.png)

**Comment by inorichi** [comment]
I wanted to release a fix so fast that I forgot to remove that color. BTW, which one do you like, that one or the one from the debug builds?

**Comment by Rumple007** [comment]
If you don't mind me saying the new one looks better

**Comment by M2ck** [comment]
Yes the new one is really nice, I would like to have it on my navigation bar too :)

**Comment by inorichi** [comment]
It looks like this in the chapters tab, I'm not sure if it's a good idea.
![navigationbar](https://cloud.githubusercontent.com/assets/3521738/12461363/c7b1cf52-bfb8-11e5-80f9-32f1672735b7.png)

**Comment by M2ck** [comment]
You should give the same darkness from status bar on the navigation bar, see an example below with Solid Explorer app
![screenshot_2016-01-20-21-12-21](https://cloud.githubusercontent.com/assets/6850125/12461755/d3d27622-bfba-11e5-8e79-652245ffdf4c.png)

**Comment by inorichi** [comment]
Okay, done.

**Comment by M2ck** [comment]
Thanks!
