### ISSUE TITLE
Duplicate entry in chapter update notification

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#430]
Doing a batch update of all manga resulted in Horimiya being listed twice - there was also only one new chapter too.

Source: Batoto
Build: 844
Version: 6.0.1

![](http://i.imgur.com/7lPn1Z7.png)

**Comment by inorichi** [comment]
Is Horimiya in the library from more than one source?

**Comment by wopian** [comment]
Oh shit. I've reached the point where I don't realise I already have the manga downloaded and partially read in another source. :blush:
