### ISSUE TITLE
"Night Mode" colour temperature option

### ISSUE THREAD

**Issue by voodoobs** [inorichi/tachiyomi#432]
I'd like to see an optional filter that colours the screen. You currently have something similar implemented in that adjusting the brightness below 0% introduces a black filter. What I'd like is a separate option to choose a "permanent"/"always on" colour filter regardless of brightness level.

I specifically put "night mode" in the title because I was thinking of a toggle that made reader mode turn to a warmer colour filter (red or orange) to aid in reading in dark/dimly lit areas, but i recall using a reader a long time ago that gave the user a choice from preset colours if this becomes something other people like and want a different colour other than red/orange.

**Comment by wopian** [comment]
Imo this is something better suited as a system-wide app instead of implemented within individual apps.

https://play.google.com/store/search?q=CF.lumen&c=apps&hl=en
