### ISSUE TITLE
Please add readcomiconline.to to the official build.

### ISSUE THREAD

**Issue by Tdanny** [inorichi/tachiyomi#439]
This unofficial Version of tachiyomi
has readcomconline.to added to his Sources

It works perfectly fine and it woud be really good
to add it to the official sources.

 *LINK*
https://github.com/inorichi/tachiyomi/files/322226/tachiyomi.zip
Version: unofficial
(Android)

**Comment by inorichi** [comment]
Read this. https://github.com/inorichi/tachiyomi/wiki/YAML-Sources
