### ISSUE TITLE
Downloads Error out / Takes forever to download

### ISSUE THREAD

**Issue by xXShiina** [inorichi/tachiyomi#440]
Sometimes the manga that I try to download with this app doesn't download. It errors out when I try downloading manga, usually saying just "error" when I go check the manga to see if it downloaded. 

Another thing is that it literally takes hours to download a manga, Sometimes it will take basically an entire day just to download one manga, if it downloads at all. I know that my internet connection isn't the problem because everything else works fine on my phone if I check. I'm only using WiFi to download and not my data. 

App Version: v0.2.3
Phone: Samsung Galaxy S4
Android Version: 5.0.1
Carrier: Verizon

**Comment by xXShiina** [comment]
I have tried a new way of downloading that I found when looking for similar problems as mine, One of the solutions was in the FAQ I think.

Before I had it on 3 simultaneous downloads, I have now limited it to only 1 download at a time. I'll see if this makes a difference.

**Comment by inorichi** [comment]
I would always use just 1 download at a time, not because the app can't handle it, but because of the source site you are downloading from. They could filter you if the traffic is too high.

I don't think Tachiyomi is at fault here btw, have you tried from different sites?

**Comment by xXShiina** [comment]
I only have one site available, Batoto, That's under the sources tab. I don't see any other options for site to download from.
![tachiyomi sources 1](https://cloud.githubusercontent.com/assets/18011651/18189956/a3b9c9ce-7084-11e6-90cb-e6472cbdecd1.png)
![tachiyomi sources 2](https://cloud.githubusercontent.com/assets/18011651/18189957/a3b9ecec-7084-11e6-9a2c-fb20679c0e37.png)

**Comment by wopian** [comment]
The sources section in settings only shows sources you need to sign in to use.

Going to the `Catalogue` page and tapping the header where it says `Batoto (EN)` will show all the sources you have available.

![](https://i.imgur.com/b904iNZ.jpg)

**Comment by xXShiina** [comment]
Oh I didn't know that was there. I'll check this out.

Thank you.

**Comment by IamHeinous** [comment]
I think the download issue is not with the app but with the site it is downloading from. I tried kissmanga Vs mangasee. Kissmanga.com errors out but mangasee doesn't.

**Comment by inorichi** [comment]
Closing as this doesn't look like a bug in the app.
