### ISSUE TITLE
[Feature] Discard Errored Out Downloads

### ISSUE THREAD

**Issue by xXShiina** [inorichi/tachiyomi#443]
I don't think that this is a current feature yet, but if it is and then I must of missed it. My request is that when downloads error out they stay in the manga that it had an error in, Could a feature please be implemented so that instead of having to manually select all the error files in a manga could something be implemented to clear out all the errors at one time. Or maybe an auto error delete?

I might be missing it but I don't see an option to mass clear out errors when they occur.

App Version: v0.2.3
Phone: Samsung Galaxy S4
Android Version: 5.0.1
Android OS: Lollipop 
Carrier: Verizon

The photos below are only the most recent that I have that has had an error, But there's been many times that I've had to go though manga's manually selecting them to delete them.

![tachiyomi 1](https://cloud.githubusercontent.com/assets/18011651/18155441/54cee558-6fd3-11e6-98d0-cc98ac369168.png)
![tachiyomi 2](https://cloud.githubusercontent.com/assets/18011651/18155442/54d9ec28-6fd3-11e6-8fdb-236acbf4df5a.png)
![tachiyomi 3](https://cloud.githubusercontent.com/assets/18011651/18155443/54dadcfa-6fd3-11e6-8ed0-86dbc4db694c.png)
![tachiyomi 4](https://cloud.githubusercontent.com/assets/18011651/18155445/54e4fa6e-6fd3-11e6-82df-abbf076f3c2a.png)

**Comment by inorichi** [comment]
The point of the error is to tell the user that those downloads failed. Clearing them would delete the entire folder.

From the download queue you can restart the downloads and they will continue where they failed.

**Comment by xXShiina** [comment]
Alright, I didn't know that.

Thanks for your reply.
