### ISSUE TITLE
Hide Individual Sources

### ISSUE THREAD

**Issue by ThePreviousOne** [inorichi/tachiyomi#447]
I'm starting this Issue because I don't think a pull request is the place to discuss a new feature

I imagine the simplest way of doing this would be something along the lines of adding a new entry to pref_sources, a list of some sort.

What I want to do is much more work and I probably can't even handle it (I detest UI) but I'm going to try.
I want to make the Spinner swipe-able, in that a user can remove a catalog from the spinner directly.

**Comment by null-dev** [comment]
I would avoid making the spinner swipeable, I don't think anyone will ever think of swiping stuff out of a spinner.

Maybe long-pressing the spinner or adding this option to the "Sources" screen would be a better option.

**Comment by inorichi** [comment]
I prefer using the sources screen.

I think the languages should show its list of sources and you can enable/disable them. The preference should store a list of disabled languages and sources, so that by default they are enabled.

I'm not sure how to do this in a single setting (we could use one for languages and one for individual sources but I think that's not the best approach)

**Comment by inorichi** [comment]
![qemu-system-i386_2016-09-04_20-00-30](https://cloud.githubusercontent.com/assets/3521738/18232924/5759bd70-72da-11e6-8486-04c11481ae13.png)

I've implemented this dialog (it doesn't store anything yet). It shows only the sources for the active languages (enabled in the setting above this one).

Thoughts?

**Comment by ThePreviousOne** [comment]
I think this would get bloated with a large list
I don't like when popups scroll it feels wrong

I was thinking something more like 
![screenshot_20160904-131632](https://cloud.githubusercontent.com/assets/13936351/18233221/853fc47a-72a6-11e6-9835-f04fd80225c6.png)

I apologize I had to wip this up in Krita I Cannot do UI dev.

**Comment by ThePreviousOne** [comment]
With this you could even get rid of the language selection

**Comment by inorichi** [comment]
That's what I thought at first, but if the list of languages grow, there's a bigger scroll.

**Comment by inorichi** [comment]
Furthermore, languages is something you change once (I think I'll add it to a setup screen when the app is first installed). The list of active catalogues will be updated more than once.

**Comment by ThePreviousOne** [comment]
Still I'd prefer this to a popup

**Comment by NoodleMage** [comment]
I prefer the look and feel of @inorichi's example in combination with a welcome screen like  https://github.com/PaoloRotolo/AppIntro.

**Comment by ThePreviousOne** [comment]
Well either way I can't write it so I guess I don't care

**Comment by NoodleMage** [comment]
You may still care even if you can't code it ;). Your opinion and input are appreciated and @j2ghz seems to agree with you (according to the emoticon) ;). Just giving my opinion as well xD.

**Comment by ThePreviousOne** [comment]
Ok I'll revise that then. I don't care that much (I was going to get Really Passionate about it)

**Comment by inorichi** [comment]
> I don't know what you're imagining I was simply suggesting adding a checkbox before the dropdown

I was referring to your suggestion of merging the language and source selection. If the full list of languages is shown there (even the ones you don't care about, most people will use at most 2-3 languages), you would have to scroll more content, even if all of the sections (languages) are collapsed.

**Comment by ThePreviousOne** [comment]
@NoodleMage Also I don't understand what Your purposing it sounds as though you are purposing that they be set only on first open. That'ed fine it it weren't not a one time thing, that would screw over anyone who's already installed the app but if its not then how do you change them them after  the first time? ... my way?

@inorichi how may languages do you intend to support I can only really think of seven fits perfectly on a phone screen

**Comment by inorichi** [comment]
I don't intend to support anymore than the ones I implement, but I'm accepting PRs. Just keeping in mind the language list can grow.

> you are purposing that they be set only on first open

No. It's just for the initial configuration. You can always change them from the settings.

**Comment by ThePreviousOne** [comment]
> You can always change them from the settings.
Yes but how, isn't that what this is about

I paid someone $20 to do the HideableSpinner for me because I want it (for myself at least)
but thats extra, so is the Initial config (relative to this issue at least) am I wrong?

**Comment by wopian** [comment]
I prefer [ThePreviousOne](https://github.com/inorichi/tachiyomi/issues/447#issuecomment-244621951)'s over a modal that would end up being scroll-able very soon (big ew) + [PaoloRotolo/AppIntro](https://github.com/PaoloRotolo/AppIntro)

>That's what I thought at first, but if the list of languages grow, there's a bigger scroll.

Just installed MangaRock to see what they've done to show their 26 manga sources. It takes exactly 3 scrolls to reach the bottom, which isn't all that bad (a little over 2 with Tachiyomi's Sources layout & padding)

On the on-boarding process you could show the available languages and the user tick the languages they want. Then show the list of sources by language. Likewise on the source settings page, languages that are not selected would not have their sources shown which would reduce the amount of scrolling required. Although I somewhat prefer how MangaRock has done it by just showing all the languages and sources - just not the design :wink:

**Comment by wopian** [comment]
E.g something like this:

Although the German sources would be above the English ones and it'd have either a toggle or checkbox instead of the tick thing from the current source page.

![](http://i.imgur.com/LSUkxsM.png)

**Comment by inorichi** [comment]
Current/unfinished design:

![qemu-system-i386_2016-09-10_12-19-51](https://cloud.githubusercontent.com/assets/3521738/18409813/233b7e7c-7751-11e6-9558-f9aa4b4dc639.png)

For now there will be another screen for the selection (blame Batoto).  I have to figure out how to manage selection and a catalog that requires login, but that's for another issue.

**Comment by ThePreviousOne** [comment]
just a thought but could you, for batoto remove the checkbox and make that te account "thingy"

if (notLoggedIn) batoto = false   ...   kind of thing

**Comment by inorichi** [comment]
See the last comment in the PR.
