### ISSUE TITLE
Global search (from all sources)

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#45]
like MW and MR has, search in all available sources

**Comment by Bloodwork** [comment]
I concur. MangaDLR also has this feature and it has saved me a lot of time.

**Comment by j2ghz** [comment]
Could be further enhanced by parsing the number of last chapter and showing that to make it easier to choose a source with the latest chapters

**Comment by inorichi** [comment]
Tachiyomi doesn't have all the catalogue from every source in a file. I think it would be a very slow operation.

**Comment by j2ghz** [comment]
That is true, but certainly faster than me doing the same thing manually. I meant it not as a replacement of regular search, but maybe hidden in the three dot menu after opening search

**Comment by weedy** [comment]
In MR, after you search from your desired source you get an option to search more sources at the end of the results list. 
You generally only bother hitting that when the list has few matches.
It's not an instant search global search either. 

I don't see how we could do worse. And this is THE feature that made me switch to MR and keeps me from switching to Tachiyomi permanently.

**Comment by Bloodwork** [comment]
I've been recently looking for a lot of older manga that is not present in all sources. This feature would have saved me a lot of time, I've been jumping sources so many times now to the point I'm frustrated that there is no global search. 

It would definitely be faster than source switching and typing the name of the manga again  and again even if it takes some time for the search.

**Comment by Mistero5050** [comment]
Very useful
