### ISSUE TITLE
Can you add readcomics.tv to the app

### ISSUE THREAD

**Issue by TheWrightStuff1994** [inorichi/tachiyomi#451]
I will very much like to have the site readcomics.tv to the app because it has more comics then readcomiconline.to but that site has more comics than readcomics.tv so please add it or somebody give me the .yml file for the site so i can add the site and you don't have to add the site to the app and reconfigure the entire app just because of me.

**Comment by j2ghz** [comment]
https://gist.github.com/j2ghz/f30ef1a707292e096ad95637f0b99c79
I also added it to the [YAML Sources](https://github.com/inorichi/tachiyomi/wiki/YAML-Sources) wiki page.

**Comment by TheWrightStuff1994** [comment]
Thanks man! MUCH appreciation!

**Comment by opheliakc** [comment]
Hey, sorry how can I use these yml files? I'd like to have it too

**Comment by j2ghz** [comment]
@opheliakc [YAML Sources](https://github.com/inorichi/tachiyomi/wiki/YAML-Sources) wiki page

**Comment by inorichi** [comment]
Closing as it's implemented in YAML.
