### ISSUE TITLE
Webtoon mode doesn't retain last read page

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#453]
Webtoon does note what number it is but when I click a chapter I started to read, it just goes back to the start. Is this a known issue? Doesn't look too bad to fix but I can understand why it isn't if it's known.

**Comment by wopian** [comment]
#71. Adding this functionality [requires](https://github.com/inorichi/tachiyomi/issues/84#issuecomment-176204009) making a custom view for the webtoon viewer so will likely not be fixed in a long time.

**Comment by inorichi** [comment]
I tried in the past to restore it with no success. There were some bugs with the scroll in the RecyclerView (and with a ListView was even worse) and I eventually gave up.
