### ISSUE TITLE
Download single page while reading

### ISSUE THREAD

**Issue by carks32** [inorichi/tachiyomi#457]
A lot of times I'm reading something and found just one page amusing and try to download it but it looks like you can't do it on tachiyomi while reading. Is there any way or is it totally not possible?

**Comment by inorichi** [comment]
Can you ellaborate? I don't understand the issue.

**Comment by wopian** [comment]
I believe he wants to save/download a single page which would be viewable in your gallery app.

**Comment by carks32** [comment]
What wopian said. Sorry, I wasn't clear.
