### ISSUE TITLE
Fdroid release

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#46]
I'm trying to speed up release on fdroid by providing a merge request, but I ran into some issues. If anyone wants to help: https://gitlab.com/fdroid/fdroiddata/merge_requests/1156
Edit: I filled out most of the fields just to test whether it builds, If there are any mistakes please say so

**Comment by inorichi** [comment]
I guess I have to remove those repositories and add some dependencies as a library

**Comment by inorichi** [comment]
I've removed one of those already. [Icepick](https://github.com/frankiesardo/icepick) is going to be a pain. It uses clojure, I think we have to add clojure support in our gradle in order to compile it.

**Comment by mvdan** [comment]
No need to compile your libs from source. We allow jcenter, mavenCentral and oss.sonatype. Also jitpack, which should work with any libs in github repos that aren't in any of those repositories.

**Comment by inorichi** [comment]
ERROR: Found unknown maven repo 'https://clojars.org/repo/' at build.gradle
    ERROR: Found unknown maven repo 'http://dl.bintray.com/amulyakhare/maven' at build.gradle
    ERROR: Found unknown maven repo 'https://github.com/suckgamony/RapidDecoder/raw/master/repository' at build.gradle

These are throwing errors, and Icepick is only available at [clojars repo](https://github.com/inorichi/tachiyomi/blob/master/build.gradle#L22).

The last two could be included as lib easily.

**Comment by mvdan** [comment]
The idea is to only allow maven repos that host open source libs only. Seems like clojars is just that. Do they require you to upload the source code for each version, though?

**Comment by mvdan** [comment]
If clojure libs are generally only pushed to clojars, allowing its use in F-Droid seems like the best option given that the site is free software and seemingly only allows free software libs.

**Comment by inorichi** [comment]
If it can be whitelisted in F-Droid it would help a lot. I don't know if they require you to upload the source code for each version. [Here's a comparison](https://github.com/clojars/clojars-web/wiki/About#how-does-clojars-compare-to-central) I've found against central.

**Comment by mvdan** [comment]
Sounds good. Will whitelist in a second.

**Comment by inorichi** [comment]
I've removed those repositories. It should compile now.

**Comment by mvdan** [comment]
Looks good now, thanks! We only need a tagged release we can build now.

**Comment by inorichi** [comment]
Thanks to you :D. I just released a new version.

**Comment by mvdan** [comment]
Merged on our end. Should be available within a day.

**Comment by inorichi** [comment]
Already available https://f-droid.org/repository/browse/?fdid=eu.kanade.tachiyomi
