### ISSUE TITLE
Filter categories to update in auto update.

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#461]
The auto library updater currently just updates your entire library. For me this means updating >700 manga - many of which are in categories i'm not reading (i.e Plan to Read/Completed), which takes a huge amount of time, wastes bandwidth for client and site and causes needless battery drain. Thus I just manually update 3 categories every day.

Version: r861

**Comment by IceKreem** [comment]
I agree it would be cool to implement an option for what caterog(y)ies need updating and also have an "whole library" option as well.

**Comment by wopian** [comment]
Whole library update would be implied when no categories are selected

**Comment by Kreemy** [comment]
Haha thats what I meant ;)

**Comment by null-dev** [comment]
Why are we updating completed manga anyways?

Maybe add an option to not update completed manga?

**Comment by wopian** [comment]
>Maybe add an option to not update completed manga?

This is already an option. Kinda a bad example with that category name but until the manga details is updated its still marked as `ongoing` and would get updated.

**Comment by malakigerald19** [comment]
I think this feature is already implemented? Go to the specific category and pull to refresh/update it and it will just updating the mangas in that category

**Comment by wopian** [comment]
@malakigerald19 nope. That's a manual update and you have to do it for each and every category and wait until each one has finished before updating the next category.

This issue is for automated updates of specific categories instead of updating everything.

**Comment by inorichi** [comment]
I've almost finished it. I'll try to publish this tomorrow.

The setting affects both the automatic and manual (from the library's menu) update.

If you think a shorter title fits better the description, please tell me.

![qemu-system-i386_2016-09-14_00-15-40](https://cloud.githubusercontent.com/assets/3521738/18493501/35274400-7a11-11e6-9c2c-1c504e7f97ce.png)

**Comment by inorichi** [comment]
91829b0
