### ISSUE TITLE
Ability to batch update manga details

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#462]
The only way to update the manga details (i.e poster, status and genres) is to open each manga and switch to the info tab and refresh.

Ideally this could be part of the normal update or it could be in the (advanced) settings.

Version: r861

**Comment by wopian** [comment]
@inorichi, this will only update ongoing manga when the setting in General is on. This should be something that is updating everything.

**Comment by inorichi** [comment]
Fixed.
