### ISSUE TITLE
Data use while set to Wifi-Only

### ISSUE THREAD

**Issue by ethaksus** [inorichi/tachiyomi#467]
Version: v0.2.3
Handset: OnePlus 3
OS: Oxygen OS 3.2.4

I have configured Tachiyomi as follows:

General > Library Update restrictions:
* [x] Wi-Fi
* [ ] Charging

Downloads > Only download over Wi-Fi:
* On

However, I noticed today that tachiyomi had used approx. 5MB of foreground network data (which is a significant amount on a 100MB limit). Background data restriction in Android was not applied until after I discovered this usage. I believe this is a bug, unless there is a third setting required in order to entirely stop the application from using data while operating. 

I believed that these two were enough for the app to consider itself "offline" if a wifi connection was not detected. If this is an error, it may needlessly consume data for users and result in unexpected costs.

**Comment by inorichi** [comment]
That setting only affects the automatic library update.

It won't prevent you from browsing a catalog or reading a chapter you haven't downloaded (there's a checkbox for downloads too).

**Comment by inorichi** [comment]
If network usage is so bad you shouldn't open the catalog or read something not downloaded. To avoid further network usage, use some third party app (or your system if it allows that) to disable usage on mobile.

The automatic library update has been updated to use a better restrictions API (`GcmNetworkService`), but I doubt it was a bug.
