### ISSUE TITLE
Odd behaviour with single-page chapter mangas

### ISSUE THREAD

**Issue by ethaksus** [inorichi/tachiyomi#468]
Version: v0.2.3
Handset: OnePlus 3
OS: Oxygen OS 3.2.4

When reading single-page-per-chapter mangas (such as Tomo-chan wa Onnanoko!):
* Swiping forward or backward does not work to change pages/chapters (tapping edges of screen work however).
* Only previous chapter is updated for read progress to MAL.

> Chapter 4 is read, and upon exiting, MAL is updated to Chapter 3.
> Opening Chapter 4 again and exiting will then update MAL to Chapter 4.

**Comment by wopian** [comment]
This has been fixed in the latest dev release :smile:
