### ISSUE TITLE
Aesthetic improvements

### ISSUE THREAD

**Issue by M2ck** [inorichi/tachiyomi#47]
Please could you implement these following aesthetic requests:
- Replace checkboxes by switches (only in Settings, it would be odd in Chapters tab for example)
- Put icons near tab names in navigation drawer, you can choose them via this library: [Iconics Library](https://play.google.com/store/apps/details?id=com.mikepenz.iconics.sample)
- Implement a header in navigation drawer, something like this library: [MaterialDrawer Sample](https://play.google.com/store/apps/details?id=com.mikepenz.materialdrawer.app)

**Comment by inorichi** [comment]
I've changed the checkboxes.

Can you pick the icons? :)

About the drawer, I'm actually using that library, but there's no picture to display, so I didn't add the header.

**Comment by Rumple007** [comment]
The switches look better than the check boxes😊

**Comment by M2ck** [comment]
@inorichi about the drawer you could improve via a header that allows choose a source. 
With this way Catalogues tab could be removed and It should be much more user-friendly that the current implementation (but I guess it's easier said than done!)
See screenshot above with Palabre app for example 
![screenshot_2016-01-21-17-25-13](https://cloud.githubusercontent.com/assets/6850125/12486951/3d6b99c4-c065-11e5-9344-e1b345a46651.png)
@Rumple007 indeed switches...and tinted navigation bar look great! ^^

**Comment by inorichi** [comment]
Trying a gradient instead of the semi-transparent black box.

![screenshot_2016-01-24-19-49-18](https://cloud.githubusercontent.com/assets/3521738/12538186/ce8af448-c2d3-11e5-9e89-b251aa1a1694.png)

Which one do you prefer?

**Comment by j2ghz** [comment]
gradient

**Comment by M2ck** [comment]
Gradient too

**Comment by Rumple007** [comment]
Gradient

**Comment by JohnFlowerful** [comment]
Not trying to be a stick in the mud... but I prefer the black boxes.

Also, can you make the general settings text more concise? Portrait viewing on a Note 4 yields this:
![general settings](http://puu.sh/mMlDK/c0df63bedc.png)

**Comment by cyalins** [comment]
Made a pull request to fix the 'incomplete' spelling error, but I'm not sure if the settings can be made any shorter without losing their meaning. On Marshmallow and Lollipop, the On/Off slider is smaller, so it doesn't cut off any of the text.

**Comment by JohnFlowerful** [comment]
One could make it a multi line description with something like 'Update incomplete' then explain what the option does underneath.
Same goes for the 'Automatically update latest' option: 'Update services', then describe underneath.
And lastly, 'Confirm updates' should do.

**Comment by inorichi** [comment]
Everything asked has been implemented already. Closing this one.
