### ISSUE TITLE
[Catalogue] Adding request: Chinese sources

### ISSUE THREAD

**Issue by lilyke** [inorichi/tachiyomi#471]
Would it be possible to add some Chinese sources such as DM5 http://www.dm5.com/  and manhua dmzj http://manhua.dmzj.com/huanghunyuhui/

Version: v0.2.4
Android 6.0.2

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
