### ISSUE TITLE
Feature Request: Manga Update Notifications 

### ISSUE THREAD

**Issue by xXShiina** [inorichi/tachiyomi#474]
This is a feature request, I don't think that Tachiyomi has this feature. 

My request is to add a popup notification on the notification bar of the device, Like for a cell phone it would appear on the top of the phone where all the notifications are. The feature is that when a manga updates (Adds a new chapter) it will have a notification that will appear on the notification bar on the device. I'm asking for individual manga update notifications.  

In these pictures you can see what I am asking for. There is a notification for Youtube, and Webtoon those apps have the notification that I'm requesting.

Version: 0.2.3
Build Time: July 25, 2016, 0107 Hours
Samsung Galaxy S7 Edge
Marshmallow OS
Android 6.0
Verizon Wireless
![samsung screenshot for tachiyomi](https://cloud.githubusercontent.com/assets/18011651/18704575/18027652-7fb0-11e6-9a31-5a6981f8d4d3.png)
![tachiyomi feature request 1](https://cloud.githubusercontent.com/assets/18011651/18704573/17ffbb1a-7fb0-11e6-9f91-258b09c5f169.png)
![tachiyomi feature request 2](https://cloud.githubusercontent.com/assets/18011651/18704574/17ffdc12-7fb0-11e6-8daa-b0152475ae9f.png)

**Comment by inorichi** [comment]
Sorry but we can't have push notifications. The only way to know if there's a new chapter, is updating the chapter list.
