### ISSUE TITLE
Mangas not downloading 

### ISSUE THREAD

**Issue by xXShiina** [inorichi/tachiyomi#475]
I seem to be having a problem when I'm downloading. The download freezes and won't download anything more or after. 

I'm trying this with Batoto, MangaHere, and MangaFox. But sometimes my downloads still hang and wont download. 

Below are the screenshots of a manga that was downloading but then stopped, As well as my settings for downloads. Also, as pictured there is no download queue and nothing that I wanted to download after the download stopped has downloaded, There's not even an indicator saying that it failed or any notification saying the manga that I want to download anymore.

Version: 0.2.3
Build Time: July 25, 2016, 0107 Hours
Samsung Galaxy S7 Edge
Marshmallow OS
Android 6.0
Verizon Wireless

![tachiyomi download settings](https://cloud.githubusercontent.com/assets/18011651/18704802/11448fca-7fb1-11e6-8f27-cf6c215fab67.png)
![tachiyomi no download queue](https://cloud.githubusercontent.com/assets/18011651/18704801/114448b2-7fb1-11e6-8e8c-65b24c146cf6.png)
![tachiyomi not downloading](https://cloud.githubusercontent.com/assets/18011651/18704803/114b30d2-7fb1-11e6-888c-018195d6b0e0.png)

**Comment by inorichi** [comment]
Does the chapter list mark that one as downloaded? Maybe it's just a bug in the notification not being closed/updated.

**Comment by NoodleMage** [comment]
This is probably fixed in #485. If a page missing from index (or something like that) was thrown it would stop updating the download progress.

If this problem still occurs please reopen ;)
