### ISSUE TITLE
Search on kissmanga doesnt work with newer dev releases

### ISSUE THREAD

**Issue by bestrandomnameever** [inorichi/tachiyomi#480]
When I tried to filter by name in the kissmanga catalogue, it no longer worked. When I try to filter by genre it does work but takes extermely long compared to eg. mangafox.

I tried this on 2 different devices which each run a different version of the app : r876 & r863. Both are dev versions so I tried again with the latest release where it did work.

**Comment by inorichi** [comment]
Seems to be related to genre search, it should work now.
