### ISSUE TITLE
Set global chapter sort order & display mode

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#484]
At the moment it defaults to how the source lists the chapters - which fairly often has chapters in the wrong order on some sources. Additionally the chapter display mode would benefit from this too.

It's much less tedious to switch everything to using the chapter number with a global setting than manually overriding it for everything. :(

Version: 882

**Comment by vengiare** [comment]
Wanted to comment on *a certain PR related to this issue* (#3622) but the guy has me blocked from commenting, for some reason. Comment is as follows:

Does this also apply to filters? If yes, that would be weird cause filters should be unchecked by default. (but the opposite is also weird cause people would think "Set as default" also applies to filters)

> To set default "Chapter Settings" for all Manga in your Library, you must long-press the "Set as Default" button and then tick the "Apply to all in Library" checkbox first, before tapping "Set as Default"

Weird set of actions. I don't think this is intuitive.
