### ISSUE TITLE
[Bug] Pictures don't display on mangas after restore

### ISSUE THREAD

**Issue by Kreemy** [inorichi/tachiyomi#486]
When restoring only some pictures restore. Would it be possible for it to force all pictures to be loaded after restore?

Of course I could manually refresh each individual one (currently doing) but that can be tedious when you have over a certain quantity in manga.

Version: r884

**Comment by inorichi** [comment]
The app is trying to download them again, but it's getting 404 errors (the cover url was updated).

The solution is #462, and I just had an idea of how to implement it. Hopefully it's done within a few days.
