### ISSUE TITLE
[Catalogue] Adding request: heymanga

### ISSUE THREAD

**Issue by Charuru** [inorichi/tachiyomi#487]
Please add heymanga.me

More information on reddit thread:

https://www.reddit.com/r/manga/comments/56h794/mobile_app_that_supports_heymanga

**Comment by Bloodwork** [comment]
I support the implementation for this source seeing that the site provides exclusive content that can't be found anywhere else.

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
