### ISSUE TITLE
Long press on screen to save page

### ISSUE THREAD

**Issue by MrAmnesiac** [inorichi/tachiyomi#488]
While reading, long pressing the screen would allow us to save that individual page, saving it to a configurable location. 
I've been craving this for a while now because some pages have specially good jokes or puns, or whatever and I want just that page, but all I can do is take a screenshot, which is not very good, specially if what I want to save is bigger than the screen I'm using.

What are your thoughts? 
Thank you.

**Comment by NoodleMage** [comment]
Already working on this ;) #481 and duplicate of #457

**Comment by MrAmnesiac** [comment]
Thank you, and sorry!
