### ISSUE TITLE
After update, all manga switched from mangafox to mangahere

### ISSUE THREAD

**Issue by Coraz97** [inorichi/tachiyomi#489]
After updating tachiyomi from r887 to r889 via F-Droid, all the bookmarked manga in my library have switched source from mangafox to mangahere.
Also, even after restoring a backup prior to the update, all chapters keep being taken from mangahere. As a result, downloaded chapters no longer show up, and I had to switch manually the source for all the manga.

Version: r887 > r889

**Comment by inorichi** [comment]
Sorry about that, the order didn't match and I messed up...
