### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by NoodleMage** [inorichi/tachiyomi#49]
Please add comments to your code. 
I get that you understand your own code. But when you want to make something open source comment it!.

I am trying to understand your code but without comments I have to check every subclass /query, this takes way to much time and I hate headaches :).

For example you have the query called from the function geLibrarymangas():
```sql
          "SELECT M.*, COALESCE(MC.%10$s, 0) AS %12$s " +
            "FROM (" +
                "SELECT %1$s.*, COALESCE(C.unread, 0) AS %6$s " +
                "FROM %1$s " +
                "LEFT JOIN (" +
                    "SELECT %5$s, COUNT(*) AS unread " +
                    "FROM %2$s " +
                    "WHERE %7$s = 0 " +
                    "GROUP BY %5$s" +
                ") AS C " +
                "ON %4$s = C.%5$s " +
                "WHERE %8$s = 1 " +
                "GROUP BY %4$s " +
                "ORDER BY %9$s" +
            ") AS M " +
            "LEFT JOIN (SELECT * FROM %3$s) AS MC ON MC.%11$s = M.%4$s",
```
How hard is it to just write what it is doing in natural language. 
Now I have to check what the value's mean what you want to do with your SQL, which takes time, which I could spend on improving the code. 

If you don't feel like spending time on commenting I understand. But I like your manga reader and want to help improve it. But with the current state of the code it will take too much time before I or someone else can understand it.

**Comment by inorichi** [comment]
I totally get your point. I also hate when I have to review code and there isn't a single comment, but in the end I'm one of those... I'll try to comment more code from now on.

I also hate that query, but I wanted to keep using the tables classes and it ended like that.

Anyways, I'm willing to explain anything I can to anyone who wants to contribute. I've a Slack team, send me an email to `admin` at `kanade` dot `eu` and I will send you an invite.
