### ISSUE TITLE
UI/notification change request

### ISSUE THREAD

**Issue by Efreak** [inorichi/tachiyomi#490]
Version: 0.2.3

In the notifications, please identify that the notification is from tachiyomi. The having several different manga apps installed makes a list of updated/failed manga somewhat useless without opening the notification (and therefore the app), when all I want to do is dismiss the notification and remember that manga X is done downloading in app Y.

There's two ways to do it, and I'd prefer the first (which should probably be easier anyways), though either or both could be done.
- prefix notification titles with Tachiyomi (IE, *Tachiyomi: update completed*)
- add the tachiyomi icon behind the current notification icon.
  - Google currently shows a cloud icon for weather notifications, but when you open the notification list, you see the Google logo with the cloud icon/badge in front. This would also work.
- doing both would probably be better, but the first way is trivial and doesn't require finding an icon that looks good at tiny size.

**Comment by wopian** [comment]
I think a better solution would be putting the intent into the smaller icon and replace the large icon with the app's icon would be the best solution.

Similar to how the stock screenshot notification works.

edit: also calendar notification

![](http://i.imgur.com/UwmWeRKl.png)

**Comment by inorichi** [comment]
Added this:
![qemu-system-i386_2016-10-13_19-51-38](https://cloud.githubusercontent.com/assets/3521738/19360366/88e86ed2-917e-11e6-9dff-d494bbd51073.png)

The small icon is shown from the one used in the status bar. I can revert the small one to the refresh icon.

**Comment by inorichi** [comment]
Already implemented. Also reverted the small icon to the refresh one.
