### ISSUE TITLE
Duplicate chapters are still opened by the reader despite whether they're marked as read or hidden.

### ISSUE THREAD

**Issue by milkb0t** [inorichi/tachiyomi#491]
Advancing to the next chapter within the reader will bring up the next chapter in order, regardless of whether it's marked as read or hidden with filters.

Version: dev

**Comment by wopian** [comment]
what build are you using? Found in Settings->About.

**Comment by milkb0t** [comment]
r883, but it also didn't work in v0.2.3

**Comment by wopian** [comment]
This was possibly fixed with r887's changes. It's definately not opening duplicate chapters on r894.

**Comment by inorichi** [comment]
Use sorting by chapter number (overflow menu in the chapters view). There isn't a 100% reliable way to detect the chapter number, that's why it's not the default sorting.
