### ISSUE TITLE
Page list is empty

### ISSUE THREAD

**Issue by camo43** [inorichi/tachiyomi#494]
Hello. I am new to the app. So i am not sure if this is some rookie mistake.

While reading Pokemon Adventures i tried downloading multiple chapters at a time. After i tried to download the chapters, all i got was a menssage "page list is empty".

Now i see this message everytime i try to read a pokemon chapter. Even if it was one i have already read before.

I already tried erasing cache and data. Last i dod was reinstall the app.

Thanks for your help.

Version: or v0.2.3
(Android 6.0.1)

**Comment by inorichi** [comment]
Either an issue in the parser or you are trying to read licensed content (from mangafox most probably).

**Comment by camo43** [comment]
How can i resolve both of those issues?

Thanks for the response. Beste regards

**Comment by psychowood** [comment]
I don't know if it is your case, but with KissManga I get that error if I try to increase the number of concurrent downloads in settings.

**Comment by camo43** [comment]
I have not changed that setting myself. I checked it and it is currently at
1.

The oddest thing here is that even the chapters i had already read (1
through 22) display the same message.

Thanks for the support. I really like that manga.

**Comment by psychowood** [comment]
Which source are you using?

**Comment by camo43** [comment]
Kissmanga

**Comment by inorichi** [comment]
Doesn't seem to be an error in the parser.

Try to read it from your browser (if you can't read it there, there's nothing to do), or use a different source.

Closing. I will reopen if it's definitely an issue in the parser.

**Comment by camo43** [comment]
I juat tried and i can read it on my browser.

http://kissmanga.com/Manga/Pokemon-Adventures/23?id=42538

I tried again on the app. Same message appears.

Thanks. I will await and see if it get's resolved.

**Comment by inorichi** [comment]
Try the setting clear cookies, also a router restart may help (if you have a dynamic IP). Did you have to resolve a captcha in your browser?

**Comment by camo43** [comment]
Just cleared cache and cookies. Restarted the router. Same problem. If this
helps. I get the same error when i am trying to read the manga using data.

I did not have to resolve captchas.

**Comment by camo43** [comment]
Hello.

I just installed v0.3.1 and the same thing has happened.

I could see that the same error message is appearing whenever i try to read
anything from kissmanga.

I tried reading randomangas using mangafox and it seems to work just fine.

This also happens whilr i use mobile data.

I have no idea what to do now.

Thanks for your attention.

**Comment by inorichi** [comment]
I didn't introduce any change regarding this issue.

I need the response you are getting from the site. If you can setup Wireshark to capture your phone packets, [read the latest comments of this issue](https://github.com/inorichi/tachiyomi/issues/478). It may not be easy to configure though.

[This StackOverflow question may help too.](http://stackoverflow.com/questions/27887719/capture-packets-in-android)

**Comment by camo43** [comment]
This morning i could not yet read any manga from kissmanga. But i tried a
couple of hours ago and now i al able to freely read kissmanga.

I did not make any more changes.

Wierd right?

But thank you for your patience.

Best regards.

**Comment by xrishox** [comment]
I'm having the exact same issue. Kiss manga and manga here. It will download some and then start throwing that error and none will download after that

**Comment by xrishox** [comment]
I just loaded kiss manga on the same device in a browser and it gave me an are you a human check box captcha. I ticked it and it's working now if anyone comes across this in the future. Weird that it threw the same error for mangahere as well.

**Comment by soulsynapse** [comment]
Thanks, fixed the problem for me

**Comment by shadowviper7Z** [comment]
I was reading manga normally and same isdue has occured for a number of my manga chapters

**Comment by camo43** [comment]
Good evening.

I also have that problem since a couple of hours ago

Thanks.

**Comment by wazir6363** [comment]
Have you fixed?

**Comment by Anutrix** [comment]
Does the issue still exist? I can't seem to reproduce it.

**Comment by CarlosEsco** [comment]
Stop commenting on closed issues. This is not an issue
