### ISSUE TITLE
"Unfortunately Tachiyomi has stopped working"

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#497]
I can't finish reading the latest chapter of Hare-kon.

Video with the issue: https://gfycat.com/CompetentHotEquine

Link to the chapter: http://bato.to/reader#0e472e9b2af293d0

Crashes on page 16 which is a double spread: http://img.bato.to/comics/2016/10/19/h/read5806ec72dc43a/img000016.png

Version: r909
Android 6.0.1

**Comment by inorichi** [comment]
I need the stack trace. Do you have enabled the send reports setting? I can't find anything relevant.

**Comment by Bloodwork** [comment]
The option for sending crash reports is enabled.

**Comment by Bloodwork** [comment]
I just reinstalled the app and restored from backup but it's still the same.

**Comment by inorichi** [comment]
Then somehow I'm losing crashes. Can you force the crash again?

**Comment by Bloodwork** [comment]
I crashed it 3 times in a row just now.

**Comment by inorichi** [comment]
I didn't receive anything (I just forced two from the emulator and it works). Weird.

Can you retrieve the trace with `adb logcat`?

**Comment by Bloodwork** [comment]
I just tried it on my phone (crash is on tablet) with a fresh install and it worked fine. Seems to be device specific? 

I currently don't have logcat on my PC and it's almost 1AM here. I'll set it up and get back to you tomorrow.

**Comment by inorichi** [comment]
It's an `OutOfMemoryError` in native code. r911 should improve it, but OOM are still a possibility.

**Comment by Bloodwork** [comment]
This totally slipped my mind. Yes, r911 has fixed the problem for me. No more crashes. Thank you.

**Comment by inorichi** [comment]
And now rapid tries to use RGB_565, consuming half the memory.
