### ISSUE TITLE
request: adding readcomics.tv to the list of sources

### ISSUE THREAD

**Issue by Nightlydisc** [inorichi/tachiyomi#498]
I just recently discovered the site readcomics.tv, and while it's structure is similar to all the manga sites in tachiyomi, it does something the manga sites do not: offer western comics.

In my opinion tachiyomi has already cemented itself as best manga app, so why not adding the title as best comic app on top of that?

I don't know how difficult it is to implement that into the app, but i would be very grateful if it would happen with the next update. It would make reading Scott Pilgrim much more convenient!

**Comment by inorichi** [comment]
There's already one request for this, #451 

Also read the wiki, section YAML sources. You can add a similar source for western comics.
