### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by JohnFlowerful** [inorichi/tachiyomi#50]
Is there an IRC channel or any plans for one?

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/49#issuecomment-173932569

**Comment by inorichi** [comment]
There isn't a channel, it could be created. In the case it's, I hope it doesn't turn into a flood of questions.

**Comment by wopian** [comment]
test

**Comment by wopian** [comment]
test

**Comment by JohnFlowerful** [comment]
My thought is to avoid what happened to [Manga Watcher's issue tracker](https://bitbucket.org/_vadia/manga-watcher-public/issues?status=new&status=open). Instead of having a torrent of people using Google Translate to ask questions and whatever else here, have an IRC channel where they can ask and be informed by the app's users.

I don't know about you guys, but my first point of contact is through a projects IRC channel rather than posting potential rubbish on GitHub.

**Comment by xoryo** [comment]
@inorichi why don't you create an irc channel on freenode. You can do it like most project.
- Support channel -> for questions
- Private dev channel -> for contributors

**Comment by dulleh** [comment]
Slack is pretty good for this stuff - especially if you're already using it for other things (which is more likely than some alternatives since it's quite popular).

**Comment by inorichi** [comment]
Closing this old issue. Sorry but I don't plan to use IRC (nothing you don't know already). For support there's my email in my profile, and many also know my reddit account.

**Comment by rachmadaniHaryono** [comment]
Or maybe you can use gitter.im for people who want to chat and don't have reddit account 

https://gitter.im/
