### ISSUE TITLE
Duplicate chapters

### ISSUE THREAD

**Issue by aznricegrowa** [inorichi/tachiyomi#500]
Two issues:
1. Updating causes duplicate entries in the chapter list. Downloading these chapters causes both to download
2. Installing fixes the syncing issue but i cant delete one of the duplicate entries 

Apologies if im doing something wrong. Thanks. 

Version: v0.3.1

**Comment by inorichi** [comment]
You mean updating the app? The entire chapter list is duplicated?

**Comment by aznricegrowa** [comment]
When the app updates the library and finds new chapters, it duplicates the chapter in the chapter list (ie I have two chapter 840s in my MangaSee's One Piece). I've since reinstalled and its fixed the issue going fwd but is there a way to remove all of the duplicate chapters from the past? I have to scroll through chapter 840 twice. Downloading the chapter downloads it for both chapter 840s. Deleting the chapter deletes it for both chapter 840s but leaves the listing duplicated
![tmp_7679-screenshot_20161021-0958042022135456](https://cloud.githubusercontent.com/assets/22960658/19601220/58774b3a-9776-11e6-8c36-fcebc28decda.png)

**Comment by IamHeinous** [comment]
Yes this is true. new chapters are now duplicated. I also see it in mine.  V3.1 marshmallow android

**Comment by inorichi** [comment]
Same site?

**Comment by Gilfar** [comment]
There was a problem with parsing Mangasee for some time in old version.
You can fix it in a couple steps but you lose reading progress:
1. Remove manga from library
2. Settings > Advanced > Clear database
2. Readd manga

**Comment by inorichi** [comment]
Seems to be only related to Mangasee, and it was updated recently. Closing.
