### ISSUE TITLE
Image becomes black and white on zoom

### ISSUE THREAD

**Issue by jotumn** [inorichi/tachiyomi#501]
Whenever I zoom an image in the 0.3.1 version (skipped the 0.3.0, didn't have this problem in 0.2.3), it becomes black and white at some level of zoom. Zooming out a bit makes the colors appear again.

**Comment by inorichi** [comment]
I added a limit on the number of image tiles to avoid a lot of memory usage (and crashes), however it shouldn't turn them black/white.

Does it happen too often? Can you give me an example?

**Comment by jotumn** [comment]
It happens every time on every image from readcomiconline.to, for example, http://readcomiconline.to/Comic/Green-Arrow-2011/Issue-47?id=12998. And not immediately - I zoom in or move the view a bit, and then I can see how the tiles are becoming b/w one by one every 200ms or so. This might be due to the high image resolution. I've checked it briefly with some manga covers from mangafox and they stay in color.

I used yaml from here: https://github.com/inorichi/tachiyomi/wiki/YAML-Sources

**Comment by inorichi** [comment]
Thanks, I'll investigate it ASAP.

**Comment by inorichi** [comment]
r911 should fix this, but it will still happen with bigger images. The image decoder can't handle regions with those jpgs.

**Comment by jotumn** [comment]
Is there any way for me to test it? I tried downloading the apk marked as "dev latest build" on the project front page but when I try to install it, it says "Parse error" "There was a problem while parsing the package." 

Also I noticed that it says 0.3.1-r910 but still.

**Comment by inorichi** [comment]
r911 should be available now, but I never had that error, does it happen before or after installing?

**Comment by jotumn** [comment]
Right after i tap "install" in the package properties window. Same thing with r911. Maybe it's because I have Android 4.2 or some kind of debug mode needs to be enabled on the phone?

**Comment by touzainanboku** [comment]
Do you perhaps have the F-Droid version installed? I think you have to uninstall that first.

**Comment by inorichi** [comment]
It's probably multidex not working properly.

**Comment by jotumn** [comment]
No, I have the normal 0.3.1 release. I uninstalled it just now to be sure but it still gives the same error.

**Comment by jotumn** [comment]
All right, nevermind. It was the ES file explorer all along. I tried to install apk from the network folder.

Unfortunately, the fix didn't help. It still makes tiles b/w on zoom.

**Comment by inorichi** [comment]
You can try using the other image decoder. The change I did will probably not work in old phones, because it doesn't allow images bigger than 2048x2048 and then it needs tiling.

**Comment by jotumn** [comment]
Well, skia image decoder does exactly the opposite thing :)
By default, full image is b/w and when I zoom it in, it becomes colored tile by tile.

Also skia has some issues with the resulting image, producing some weird dithering:

rapid1:
![rapid1](https://cloud.githubusercontent.com/assets/16961866/19618432/5538e0d8-985b-11e6-9655-a06a5f73e903.png)

rapid2:
![rapid2](https://cloud.githubusercontent.com/assets/16961866/19618430/54c02fd0-985b-11e6-9286-a0b8f23873f6.png)

skia1:
![skia1](https://cloud.githubusercontent.com/assets/16961866/19618431/54c34e90-985b-11e6-8d12-e4d91cadfe27.png)

skia2:
![skia2](https://cloud.githubusercontent.com/assets/16961866/19618429/54bf0844-985b-11e6-9f13-032ba6371072.png)

**Comment by gedling** [comment]
Using full color images from ReadComicOnline on 0.3.1. With rapid, all the images are entirely black and white. With skia the top half is black and white, the bottom is color. Using a OnePlus 3 so relatively powerful phone...

**Comment by inorichi** [comment]
0.3.1 still uses the 2048px limit, so it won't matter.

**Comment by gedling** [comment]
Resolved. Had a little trouble getting the parsers working on the debug version but working great now. Thanks for being so quick and on top of this!

**Comment by inorichi** [comment]
@jotumn can you update to the latest dev build? It should now work in older phones too.

**Comment by jotumn** [comment]
Thank you, r914 fixes everything for me with rapid image decoder. Skia is still as before - b/w in zoomed out, colors with dithering artifacts appear on zoom in.

**Comment by inorichi** [comment]
Another crash introduced in r914 has been fixed. I'd recommend to update.

**Comment by inorichi** [comment]
This is fixed with the new image decoder.

**Comment by jotumn** [comment]
Rapid was fine for me with the r914 fix but the new decoder is working as intended, too. I guess this issue can be closed. I've also never experienced the crashes before or after the fix.
