### ISSUE TITLE
Sync between devices

### ISSUE THREAD

**Issue by radry** [inorichi/tachiyomi#502]
It would be good to have a "sync between devices" feature. It could use the already existing MAL sync, so the necessary data is already available. Thus implementation is quick and easy.

How it would work:
Read/sync the MAL data (the app already does this)
Use the chapter count from MAL to mark the chapters as read.
This should be done automatically each time the chapter list is opened or refreshed.

Why would we need this? 
Obviously so we can read on different devices and not worry about read status.

Version:  v0.3.1

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/383#issuecomment-233035553

**Comment by inorichi** [comment]
Sync with MAL would be very limited. You have to add the manga to the library and bind it in both places, and trust the recognized chapter number for it to work (it's not 100% accurate and a few russian sites can't even parse the chapter number, so it wouldn't work for them).

Maybe one day sync is properly implemented, with a Google Drive file or a self-hosted backend (like Tachiweb), but not like this.

**Comment by radry** [comment]
It's better than nothing and easy to implement until you can think of something better. I don't want any additional services where I have to sign up.
