### ISSUE TITLE
It's closing the chapter not the app itself

### ISSUE THREAD

**Issue by IamHeinous** [inorichi/tachiyomi#503]
Version: v.  3.1
Android Mrashmallow

Hi I am experiencing an error for Kissmanga Prison School chapter 195. Page 8 or 9.  It only happens only those pages and I cannot progress on that specific page.  Next chapters are OK.  All other chapters and other pages are OK. 
I have downloaded it a bunch of times and do real-time download but it keeps force closing On both page 8 and 9. Replicated on two devices. Asus zenfone 2 and Samsung Galaxy s4. 

Update : it downloaded the page 8 and 9. I can see them but when I zoom them it force closes. On either page.

**Comment by inorichi** [comment]
It's an out of memory error (mostly fixed in the dev version). Try using Skia. I'll release a new version when I stabilize a few things.

**Comment by inorichi** [comment]
Update and use the new decoder.
