### ISSUE TITLE
Updating volume

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi#505]
Volume updating is a must. It's not a really big bother but updating volume manually is no different than updating the chapters too. And even on completed manga when you set them as completed volume count stays at zero

**Comment by opheliakc** [comment]
Also 2 manga I came across and plan to read (akira and black jack) is divided by volumes and not chapters so it would be helpful for that too.

**Comment by inorichi** [comment]
In the case volume updating is implemented, it will have to be changed manually.

**Comment by erikolson97** [comment]
What does this mean, even if the feature is implemented it will have to be changed manually?  I also am interested in this feature.

Also just fyi I believe https://github.com/inorichi/tachiyomi/issues/1117 is another duplicate.

**Comment by MercerBoi** [comment]
Wow, I wasn't aware there were multiple requests for Volumes already.

@inorichi, updating it manually is not a problem at all. I (and the rest of the users) would really appreciate it if you added it in the next build.

**Comment by george-emerald** [comment]
@inorichi, is there an ETA on this? It's been almost three years and it should be a pretty easy implementation. I don't mind having to do it manually, though it would be great if it could at least recognize volume files, which is the common format for manual downloads from sites and trackers that end up in the local manga catalogue.

**Comment by Flat** [comment]
![2019-06-23-10:16:15](https://user-images.githubusercontent.com/2048861/59977512-fd171d80-959f-11e9-8030-b8e72f109ab8.png)

See the label that says 1.x? That means this feature is targeted for the rewrite aka version 1.x. no ETAs are available.

**Comment by george-emerald** [comment]
Does this feature require a rewrite of the entire application? I wouldn't know the answer to that question, but it doesn't seem like pulling just one more entry from the Anilist API would require a complete rewrite to me. And why is there no ETA for the rewrite, has it not even been started yet?

**Comment by bbtora** [comment]
No it doesn't require a rewrite. The app itself is in a planned rewrite phase and the feature is included in that. 

> And why is there no ETA for the rewrite, has it not even been started yet?
It will be done when it's done. If you are still not satisfied, look for the 1.x branch on this repo.

**Comment by george-emerald** [comment]
Does that mean no feature will be implemented until the rewrite is done?

Unfortunately, I can't read the branch since the only programming I've been taught so far is basic python. I'd love to contribute when I'm done with my compsci bachelor, though. I'm not dissatisfied, the app is amazing and I'm very thankful to everyone who spent their free time to contribute to it. It's just been sitting here for 3 years and it seemed like something that could be done readily to me.

**Comment by arkon** [comment]
ETAs generally don't make sense for small projects that's primarily maintained by one or two people in their spare time.

**Comment by Flat** [comment]
This app is developed mainly by one person, in their free time. All contributors also work for free, in their free time. The current version is limited to bug-fixes pending the rewrite as adding features at this point is wasted effort. Yes it might've been added previous to the start of the re-write but at this point it would require too many changes to accurately track volumes. Just adding a field to manually set volumes wouldn't be that difficult but it doesn't really provide any use unless you completely do not use anilist outside of tachiyomi.

**Comment by george-emerald** [comment]
Adding volume, notes and started/read dates fields would be wondrous for me since I wouldn't have to use the site on my mobile browser. But of course, this is just my personal inconvenience, I'm not expecting you to spend your free time to fix it right now, I didn't mean to be rude.

**Comment by george-emerald** [comment]
Will tracking volumes be implemented on the rewrite? Having the option to track volumes on local manga would be amazing.

**Comment by MercerBoi** [comment]
Yeah it'll be there on the rewrite/ 1.x, as it has been labelled by the main dev. 

Though I do wish it comes out for the current releases first, since 1.x is like a utopian app with no release date in sight.

**Comment by inorichi** [comment]
Sorry but 0.x is currently in maintenance mode. Only bugfixes and minor improvements will be considered.

I know 1.x is like a utopian app but trust me I haven't given up yet, however I don't have enough time/motivation at the moment. Furthermore, I'm also waiting a bit for the tooling to improve because I'm using alpha components and those need a few fixes too, and for some new designs. So... it's not dead yet.

**Comment by MercerBoi** [comment]
Inorichi, it's just a wish, no worries at all! We all love you and your app, keep up the good work! <3

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
