### ISSUE TITLE
Can't have more than one chapter with the same chapter number downloaded at the same time.

### ISSUE THREAD

**Issue by StanleyCranel** [inorichi/tachiyomi#506]
The series "Seitokai Yakuindomo" that KissManga hosts have multiple chapters with the same chapter number, even though they really aren't the same. There would be, for example, two different chapter 6s and the app would only allow me to have one of them downloaded at a time.

**Comment by inorichi** [comment]
It's intended. There are no plans to change that. Folders would conflict, so you can download only one (at least you can select which one).
