### ISSUE TITLE
Error creating folder when downloading

### ISSUE THREAD

**Issue by GDXN** [inorichi/tachiyomi#511]
When a folder or file ends in " ." (space+one ore more points) result in a forbidden name as android ignores the trailing points and no folder or file can end in space, then in the case of a chapter ending in " ." the program tries to create the folder and fails as it don't remove the space before the trailing point/s. Instead of removing the space there is a alternative and simpler solution as is to append something to the name like the download website, time, release number...
 
I can point to a chapter example if toy want.

this affects all tested versions.

**Comment by inorichi** [comment]
I have to rewrite the entire download manager. A quick fix for this is to not allow dots or trim them. In order to keep compatibility I guess I'll do the second one.

**Comment by GDXN** [comment]
The fix is not in the dots, is in the spaces.

for android "name.", "name.." and "name..." are the same as "name" and they are valid.
but "name .." is folded to "name " that is an invalid name.

This regex if my skill didn't go rusty is a solution:

`str.replaceAll( "^([ ]*)(.*[^ .])([ .]*)$","$2");
`
This removes all leading spaces and tailing spaces and points from a string.

**Comment by inorichi** [comment]
Kotlin's `.trim('.', ' ')` strips both spaces and dots.

I'll fix this alongside the rewrite of the download manager, which will also allow to write to any folder in the SD card.
