### ISSUE TITLE
Unknown error on MAL login

### ISSUE THREAD

**Issue by reconman** [inorichi/tachiyomi#513]
I tried adding a new series to my library and that's when I noticed you couldn't log in into MAL anymore with Tachiyomi.

Whenever I enter my credentials I get an Unknown Error message.

Version: v0.2.3
Android 5

**Comment by inorichi** [comment]
They changed their API to https recently. It's possible they dropped support for non secure requests. You have installed an old version that still uses http. Try again after upgrading.

**Comment by reconman** [comment]
Had to update Tachiyomi manually since the problem with F-Droid still persists.

That fixed the problem, thanks!

**Comment by mahoromax** [comment]
I experience the same behaviour using 0.8.0 from Oct. 9th (according to the app).
