### ISSUE TITLE
"Image" image decoder displays chapter incorrectly 

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#514]
App 0.3.2, Android 6.0.1

This is how every page in the entire chapter looks:
http://i.imgur.com/MX2PhqR.png

With Rapid/Skia the chapter looks fine. 

Manga is 'Amano Megumi wa Suki Darake!' ch. 11,  source is Batoto.

**Comment by inorichi** [comment]
Fixed upstream and it should be available in the next release.
