### ISSUE TITLE
Play Services dependency (and F-Droid)

### ISSUE THREAD

**Issue by paronos** [inorichi/tachiyomi#515]
I noticed that since v0.3.0 Tachiyomi does not build anymore on F-droid a result of play services dependence https://gitlab.com/fdroid/fdroiddata/issues/539.
If I'm not mistaken the only play services dependence is com.google.android.gms:play-services-gcm:9.4.0 used by the auto updater (GcmNetworkManager).

To allow Tachiyomi to run on devices without play services (amazon, chinese phones, etc.) and the download from F-Droid it may be possible to re-implement the auto updater without using GcmNetworkManager. It is possible to use JobScheduler on API 21+ (GcmNetworkManager also uses this internally on API 21+), and AlarmManager on previous APIs https://speakerdeck.com/vrallev/scheduling-background-job-on-android-at-the-right-time.

Another option is to use the [android-job](https://evernote.github.io/android-job/) library that works even if the play services are not installed on the device (perhaps it would still be necessary to add a build without the auto update to fix the F-Droid issue).

**Comment by inorichi** [comment]
2856d9d 

Gcm dependency can be removed in F-Droid's build script.
