### ISSUE TITLE
Mangasee Chapters Not Working

### ISSUE THREAD

**Issue by basilg3** [inorichi/tachiyomi#516]
Hello, I'm using the current version of the app and ran into a bit of an issue. No manga chapters I have gotten from the MangaSee catalog are working. When clicked on, they display the following error message: 

"Attempt to invoke virtual method 'java.lang.String.org.jsoup.nodes.Element.attr(Java.lang.String)' on a null object reference"

This issue can't be from the MangaSee website itself, as it works fine if I open the site from browser. Can you do anything about this? Thank you.

**Comment by ThePreviousOne** [comment]
The "Current Version" Being?

**Comment by basilg3** [comment]
In settings it says Version r931

**Comment by GHOSTBEAR** [comment]
MangaSee have changed their url from mangasee.co to mangaseeonline.net

**Comment by basilg3** [comment]
Ah I see. Okay, so is this an easy fix then?

**Comment by GHOSTBEAR** [comment]
Don't think this to hard but will require a little more job that just changing one line of code

**Comment by opheliakc** [comment]
Yeah that happened for me too. I just uninstalled the app like the dumbass I am

**Comment by inorichi** [comment]
Closing as another one was created. Please use the same issue if it's not closed.
