### ISSUE TITLE
Source name selection sticks when its not supposed to, ends up crashing.

### ISSUE THREAD

**Issue by beepFTW** [inorichi/tachiyomi#52]
To reproduce;

Go to Catalogs → select a source → touch search icon → open sidebar with search activity still active → go to My Library.

If you do this more than twice, you'll have no more room for the new "select a source" option and the app crashes. Here are some downsized screenshots:

![xlha6p5](https://cloud.githubusercontent.com/assets/7910502/12532395/e7a70db6-c1c7-11e5-9015-d97c78305c36.png) ![rl4l47s](https://cloud.githubusercontent.com/assets/7910502/12532400/ee5fe7ae-c1c7-11e5-8a90-4eb53f4b59dc.png)

**Comment by inorichi** [comment]
Nice catch. :)
