### ISSUE TITLE
Problems with chapters with the same name

### ISSUE THREAD

**Issue by psychowood** [inorichi/tachiyomi#522]
There are some sources that use the same title for different chapters (e.g. [Project ARMS on MangaHere](http://www.mangahere.co/manga/project_arms/?no_warning=1) where numbering restarts from 1 for each volume, and the volume number is not part of the chapter title).

- Reading without downloading the chapter works and follows the correct order (keeping source sorting)
- Downloading a chapter with the same title of another one overwrites the files of another chapter (since the directory name is the same) and marks every chapter with the same title as downloaded
- "Download next XXX chapters" seems to always sort by name instead of using the selected criteria (e.g. source, in this case): if I select the 3rd "Chapter 5" in the list (actually the 25th, with 10 chapters per volume), and I want to download the next 3 chapters, the app downloads the first three "Chapter 6" instead of the following "Chapter 6,7,8".
- Mark previous as read is not working, either
- Display by Chapter Number shows "Chapter -1" for every chapter

Version: r934

**Comment by inorichi** [comment]
I don't think I'll remove the chapter name restriction. The case you linked can be fixed by adding the grey text (volume) as part of the title.

I could mix the chapter id with the folder, but in the case the chapter is readded (it happens from time to time), it would have another id and won't be marked as downloaded.

**Comment by psychowood** [comment]
I'm trying to add that text. Any idea on why changing chapter.name in `MangaHere.kt -> chapterFromElement` is not changing the displayed name (even if the chapter.name is correct)?

**Comment by psychowood** [comment]
What about channel numbering, when the name is duplicated, since volume number is ignored?
Since chapter number should be absolute, the only idea that came to my mind is adding a very large offset identifying the volume, when present.

>     /**
     * Chapter containing multiple zeros
     */
    @Test fun multipleZerosCase() {
        createChapter("Vol.001 Ch.003: Kaguya Doesn't Know Much")
        ChapterRecognition.parseChapterNumber(chapter, manga)
        assertThat(chapter.chapter_number).isEqualTo(1000003f)
>
        createChapter("Vol.002 Ch.003: Kaguya Doesn't Know Much again")
        ChapterRecognition.parseChapterNumber(chapter, manga)
        assertThat(chapter.chapter_number).isEqualTo(2000003f)
    }

but I'm not really sure about where chapter_number is used, besides comparison and sorting...

**Comment by inorichi** [comment]
That would break progress updates with MAL.

**Comment by psychowood** [comment]
Then the only other way would probably be incrementing chapter_number by counting globally from the source chapter list, otherwise the progress update with MAL would be broken anyways.

**Comment by inorichi** [comment]
Chapters not recognized are set to `-1` so that it doesn't update anything. There's already a counter for the source chapter list `source_order`

> Reading without downloading the chapter works and follows the correct order (keeping source sorting)

That works because the sorting mode is source order. It won't work with chapter number order.

> Downloading a chapter with the same title of another one overwrites the files of another chapter (since the directory name is the same) and marks every chapter with the same title as downloaded

That's expected. The mapping chapter/folder works like that to keep them across reinstalls.

> "Download next XXX chapters" seems to always sort by name instead of using the selected criteria (e.g. source, in this case): if I select the 3rd "Chapter 5" in the list (actually the 25th, with 10 chapters per volume), and I want to download the next 3 chapters, the app downloads the first three "Chapter 6" instead of the following "Chapter 6,7,8".

That can be changed. IIRC it's implemented in `ChaptersPresenter`.

> Mark previous as read is not working, either

Can be changed too.
    
> Display by Chapter Number shows "Chapter -1" for every chapter

That's expected (chapter not recognized).
