### ISSUE TITLE
Download notification stays forever stuck download

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#527]
When downloading I've noticed that the download notification kept showing (http://i.imgur.com/CXQ5khQ.png)  despite finishing all the downloads and it did show that it failed to download 2 chapters. 
At least the notification can be cleared easily.

**Comment by inorichi** [comment]
App version?

**Comment by pitman10** [comment]
0.3.2

**Comment by NoodleMage** [comment]
This is probably because the manga with errors stay in the queue but it isn't recognized as downloaded. (thus 37/39 in your case). If this still occurs after the download manager rewrite I will try to fix it.

**Comment by inorichi** [comment]
Just made a commit to always remove the downloader notification (except the error notification) when it stops.
