### ISSUE TITLE
Crashing from Settings menu

### ISSUE THREAD

**Issue by lynnex** [inorichi/tachiyomi#528]
Errors only when accessing:
Settings > Reader
Settings > Sync
Settings > About

Brief white screen before being taken back to home (My library)
No error message or dialogue box
Factory reset tablet. Uninstalled and reinstalled each version down to 2.0 - same results.

Current Installed Version: v0.3.2
Android 5.1 Lollipop (Ellipsis 10 Tablet)

**Comment by inorichi** [comment]
Does r953 make any difference?

**Comment by lynnex** [comment]
No same results

**Comment by inorichi** [comment]
Update again. If this one doesn't fix it, I'm out of options. The crash is not caused by the app but the system.

**Comment by inorichi** [comment]
I don't have any crash in the dev version regarding this. Either you downloaded 0.2.3 (the stable release) or the report was lost. Can you try r955 (not 0.2.3)?

**Comment by lynnex** [comment]
Is r955 the latest stable version (3.2)? That is what I have installed, but am experiencing the same issue. I will uninstall/reinstall again and report back.

**Comment by inorichi** [comment]
No. It's the dev build, the one that says "dev, latest build" in the main page. [Here's the link](http://tachiyomi.kanade.eu/latest/app-debug.apk)

**Comment by inorichi** [comment]
Can you confirm if the issue persists?

**Comment by lynnex** [comment]
Yes, it is still happening.

**Comment by inorichi** [comment]
[This was r953](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/773:id/app-standard-debug.apk?guest=1). This version should have fixed the crash (test all the screens that crashed before just in case).

**Comment by lynnex** [comment]
Installed r953. Still experiencing the same issue.

**Comment by lynnex** [comment]
I recorded my screen if it will help.
https://vid.me/bGVy

**Comment by inorichi** [comment]
It should be working now.
