### ISSUE TITLE
a page is missing in directory

### ISSUE THREAD

**Issue by cein12** [inorichi/tachiyomi#530]
I get the above message when I try to download chapters for "Noblesse" from mangafox. I think the "moving animation" on last page causes this issue but I am not sure.

I am using HTC One M9
Android 6

**Comment by inorichi** [comment]
App version?

**Comment by cein12** [comment]
Version 0.3.1

**Comment by inorichi** [comment]
Well, it happens when the image can't be downloaded. In most cases, the server is at fault (never had any problem with Batoto or Kissmanga). Also, if you are using the advanced setting reencode images, disable it. In 0.3.2 it was removed.

**Comment by inorichi** [comment]
Closing as it doesn't seem to be related with the app.
