### ISSUE TITLE
MyAnimeList login fails with unknown error

### ISSUE THREAD

**Issue by lpchaim** [inorichi/tachiyomi#531]
Upon trying to add my account to Settings->Sync->MyAnimeList the button reads "Loading..." upon my clicking it for less than one second before changing to "Unknown error" with red background. For all subsequent tries without closing the dialog, it behaves the same way. Likewise for closing and reopening it.
No further information is given as far as I can tell, tried looking into logcat but nothing caught my eye. If there's anything else I can provide or help with, I'll be happy to do so.
EDIT: Forgot to say I'm unable to test with other devices right now, sorry.

Device: Moto G (2014, XT1069 model).
OS: Android 7.1, Cyanogenmod 14.1, built-in root.
Version: v0.2.3

**Comment by inorichi** [comment]
#513

**Comment by lpchaim** [comment]
Damn, I'm sorry. I was looking for MyAnimeList as opposed to MAL. My mistake.
