### ISSUE TITLE
Chapter page save Error

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#533]
Some manga's giving error while saving chapter pages (e.g My Hero Academia and Prison School). Mostly Batoto titles observed but not all. Other sources like Kissmanga and Mangasee titles are saving fine.

Version: r955 or v0.0.0

**Comment by inorichi** [comment]
I introduced some changes to the downloader, but this is most likely a network issue. If you are using multiple simultaneous downloads, try again with only 1. Not all sites allow a lot of simultaneous requests.

**Comment by bbtora** [comment]
Thanks for your help!
