### ISSUE TITLE
Latest update issue 

### ISSUE THREAD

**Issue by TheWrightStuff1994** [inorichi/tachiyomi#534]
Can you add Readcomiconline.to to the apps latest update section.

**Comment by GitHubAdi** [comment]
I use mi manga nu for readcomiconline.to (for walking dead for example) And tachiyomi for mangasee. Could be really nice to have both catalog available on the same app.

**Comment by beepFTW** [comment]
It is already available. Check out YAML sources in the wiki.

**Comment by wopian** [comment]
Link for the lazy ;)

https://github.com/inorichi/tachiyomi/wiki/YAML-Sources

**Comment by TheWrightStuff1994** [comment]
I mean in the section on the right of app under Catalogue name "Latest Updates" it only has KissManga to have updates but I would like to have Readcomiconline.to on there.

**Comment by wopian** [comment]
Click the "Kissmanga" in the header and the dropdown will open with all the available sources.

**Comment by beepFTW** [comment]
We know.  Although if you can get the build environment set up, you can easily add Readcomiconline to the existing source list. Also since Readcomiconline is basically Kissmanga. You can copy paste the same methods to get latest updates to work.

**Comment by inorichi** [comment]
The YAML parser is now deprecated. You can request this catalogue with the new extensions system [here](https://github.com/inorichi/tachiyomi-extensions/issues)
