### ISSUE TITLE
CBT Support for Offline Viewing

### ISSUE THREAD

**Issue by zQueal** [inorichi/tachiyomi#537]
I usually get my Manga via my PC, then transfer to my phone for offline enjoyment. Downloading via Tachiyomi is great--but it would be nice to be able to archive my manga in CB(T/Z/G) and import them to Tachiyomi for viewing.

Any chance on this becoming a feature?

**Comment by paronos** [comment]
If I have not misunderstood this issue, CBZ (and CBR) reading is now supported.
CBT (TAR) and CBG (TARGZIP) are not supported, but are these format really used? (same thing for CB7 (7Z), CBA (ACE) and CBB (TARBZIP2))

**Comment by zQueal** [comment]
> but are these format really used

Depends on the devices, but usually, yes. Both CBZ and CBR are based on compression whereas CBT, CBG, and alike are containers only so these formats are particularly useful on older hardware because during opening no decompression has to take place. The file sizes are bigger, but it's a pretty good tradeoff if you ask me.

**Comment by inorichi** [comment]
ZIP can be created without compression, and you are most probably going to get better performance with ZIP since it's pretty well supported by the java API (it keeps the file/headers open while needed etc).

For the time being, only zip and rar containers will be supported.
