### ISSUE TITLE
Remove manga name from chapter listing

### ISSUE THREAD

**Issue by myuc** [inorichi/tachiyomi#54]
Is it possible to remove the manga name from chapter listing? Some manga has a long name which prevents the chapter number from bring seen.

See this for an example 
![2016-01-24 06 07 43](https://cloud.githubusercontent.com/assets/16784734/12534845/26c88ebe-c2a6-11e5-9b69-5cb5dc87d78b.jpg)

**Comment by Rumple007** [comment]
Or maybe it could e set to two lines instead of one?

**Comment by icewind1991** [comment]
https://github.com/inorichi/tachiyomi/issues/57 changes the way chapter titles are elipsized to keep the chapter number visible

**Comment by myuc** [comment]
Issue is still present. Compare the portrait vs landscape view.

![2016-01-24 17 16 43](https://cloud.githubusercontent.com/assets/16784734/12537758/ea71fd9a-c301-11e5-8c67-dad8ff24c10b.jpg)
![2016-01-24 17 16 21](https://cloud.githubusercontent.com/assets/16784734/12537757/ea711894-c301-11e5-8bae-60f7852b0a89.jpg)

![2016-01-24 17 27 43](https://cloud.githubusercontent.com/assets/16784734/12537789/132c6b2a-c303-11e5-9c92-be0c0fe81bd5.jpg)
![2016-01-24 17 27 31](https://cloud.githubusercontent.com/assets/16784734/12537790/133c5a4e-c303-11e5-8331-86d5916d2d79.jpg)

**Comment by inorichi** [comment]
A new flag in `chapter_flags` could switch between the chapter name and the value of `chapter_number`.

It can be added in the options menu of the tab. I will try it later.

**Comment by inorichi** [comment]
Does it work fine now?

**Comment by IceKreem** [comment]
Yep work's fine for me :)
