### ISSUE TITLE
Mark previous as read does not work anymore

### ISSUE THREAD

**Issue by akumamg** [inorichi/tachiyomi#541]
I dont know when buy Mark previous as read doest work anymore.
I have to select chapters and mark them as read.

**Comment by Kamui-Solo** [comment]
I approve it, this function doesn't works anymore.

**Comment by psychowood** [comment]
Which manga are you testing it with?

**Comment by akumamg** [comment]
I tested on few like To Love ru, etc.

**Comment by Taumer** [comment]
Partially confirm. This function works right if chapter number was parsed correctly
For example:
Naruto from Kissmanga
[Screen 1](https://cloud.githubusercontent.com/assets/5036757/20486911/886c13b6-b012-11e6-9d87-a7f2cf992c51.jpg)
[Screen 2](https://cloud.githubusercontent.com/assets/5036757/20486951/a6aec828-b012-11e6-8da2-4044cbc323f6.jpg) (Show chapter number)
If we will use "Mark previous as read" on first chapter (Naruto Side Story 001) it will have no effect.
If we will use it on second chapter (Naruto 700 Special Gaiden) it will mark readed chapters with number < 700
[Screen 3](https://cloud.githubusercontent.com/assets/5036757/20486868/608e1542-b012-11e6-8870-db750551d935.jpg)

**Comment by j2ghz** [comment]
I, as a user, would expect mark all previous as read to mark all the chapter that are shown as previous in the list (over or under selected chapter, depending on sort direction), not based on chapter number. More so now, when source ordering is used.

**Comment by Kamui-Solo** [comment]
I agree with **j2ghz**
