### ISSUE TITLE
Can't open saved Images

### ISSUE THREAD

**Issue by Kreemy** [inorichi/tachiyomi#542]
When saving a picture, it does not save with the extension and therefore the picture could not opened. Luckily, by manually adding .jpeg I could open it but because of this the share and open function does not work on the image.

Version: r961

**Comment by Kreemy** [comment]
![screenshot_20161122-210024](https://cloud.githubusercontent.com/assets/15200832/20541859/ce341bac-b0f6-11e6-8860-9f5c64e295b4.png)

Even though you can share and open the pictures. In the file explorer it still not saving the extension.

**Comment by inorichi** [comment]
In my emulator it's working. If the extension is not found it defaults to jpg. Have you deleted those pictures and tried again?

**Comment by Kreemy** [comment]
Works now too, I think downloaded the APK when the build was failing on Github . Either way its working :)
