### ISSUE TITLE
Wrong order of pages

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#546]
Some pages of downloaded chapters are shown at the last. Happened with all the Berserk chapters I downloaded from Mangasee.

Edit :
I think the download manager is at fault. As the pages it couldn't download at the first try and gives error. Then at the second try it downloads the remaining pages, and hence shows at the order we're reading.

Edit :
Checked the downloaded chapters in file explorer. Labelled correctly. So I guess reader shows the pages in order of downloaded first or at the ascending order of download time.

Version: r966

**Comment by bbtora** [comment]
I think the download manager is at fault. As the pages it couldn't download at the first try and gives error. Then at the second try it downloads the pages, and hence shows at the order we're reading.

**Comment by inorichi** [comment]
Ok, thanks for the report, I thought they were ordered by name. I'll fix this ASAP.
