### ISSUE TITLE
Chapter page save error reopen

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#547]
This is in reference to [#533](https://github.com/inorichi/tachiyomi/issues/533). I managed to somehow capture the screen at the time of the error this time. 

![screenshot_2016-11-25-00-27-35](https://cloud.githubusercontent.com/assets/23010526/20608321/be4ff43e-b2a6-11e6-9123-ad7e992bf7d1.png)

Edit :
Version: r967 -> r969

**Comment by inorichi** [comment]
I misunderstood the other issue, I thought you were talking about downloading errors.

This is caused by invalid characters as filename, `:` is an invalid character.

I'll fix this in a few minutes.

**Comment by bbtora** [comment]
Oh ok. Thanks a lot. And sorry for the lewd pic 😅
