### ISSUE TITLE
Manga Metadata isn't updating

### ISSUE THREAD

**Issue by poww10s** [inorichi/tachiyomi#548]
When looking for manga on Batoto, the only manga in the catalogue that show metadata are the ones on the main list, if you filter or search it they won't display metadata or update the page correctly, you can still add to library but it acts buggy. This also rarely applies to other sites in the catalogs.

Version: v0.3.2
Android 6.0
Nexus 6p

**Comment by inorichi** [comment]
I haven't experienced anything weird. Are you using the list view (without covers)?

**Comment by poww10s** [comment]
No this is with covers, I'm starting to think this may have been on batoto's end? It seemed to have fixed itself yesterday, but I'm just waiting a day or two to see if it consistently remains. This was also happened with descriptions if I wasn't clear.

**Comment by inorichi** [comment]
This doesn't seem like a bug, probably the parser failed at some point (maybe network issues). 

Closing.
