### ISSUE TITLE
Number of simultaneous downloads being ignored.

### ISSUE THREAD

**Issue by myuc** [inorichi/tachiyomi#55]
All queued items are downloaded at the same time.
![2016-01-24 06 30 28](https://cloud.githubusercontent.com/assets/16784734/12534863/2524bb72-c2a7-11e5-8edf-9088804ca13d.jpg)

**Comment by j2ghz** [comment]
It seems to me that the setting sets the number of actual simultaneously downloaded files, not the number of simultaneously downloaded chapters

**Comment by inorichi** [comment]
It's intended to limit the active downloads. I remember it was working fine yesterday.

Anyways, 5942198 should have fixed it (and I hope it doesn't happen again).

**Comment by inorichi** [comment]
Closing. It was fixed on the commit mentioned before.
