### ISSUE TITLE
Automatic updating is constant

### ISSUE THREAD

**Issue by WolfgangAxel** [inorichi/tachiyomi#552]
Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.3.2 (Nov 20 2016 build)
Samsung Galaxy S3, Android 6.0.1

If I have automatic library updating turned on at any interval, a few seconds after the library updates, it will initiate the update again. It only stops this loop if the update is cancelled from the notification area, or turning the update interval to manual. Force doing the app did not fix the issue. I don't have another device handy to try to replicate the results on.

It's strange, because this just started today, but I've been using this version since it came out 5 days ago.

**Comment by inorichi** [comment]
I think they are being scheduled one after another instead of updated. It's already fixed in the dev build.

I just noticed F-Droid users are running a dev build (expect some crashes).
