### ISSUE TITLE
Function : Sorting in Titles and chapters

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#555]
Sorting needs more options in my opinion.

I can think of sorting the Manga Titles in the form of: Alphabetical (the default one currently), last updated (both asc and desc), manga chapters unread (both asc and desc, my personal preference).

For the in-title chapter list, we only got by chapter no. and source (?), a sort by date (both asc and desc) would be much appreciated too. 

I haven't got any other sorting ideas for now but i'll look forward to edit in future for that. Options by other users will be appreciated too.

Version: r973

**Comment by rachmadaniHaryono** [comment]
similar with #374 ? @NoodleMage is also working on #536

**Comment by NoodleMage** [comment]
Implemented in #536

**Comment by inorichi** [comment]
I'll add the unread sorting.
