### ISSUE TITLE
Multiple downloads

### ISSUE THREAD

**Issue by SeraphineX** [inorichi/tachiyomi#556]
For the lack of a better title, what I basically mean is after I press the option to download 5 or 10 chapters I can't press those options again because it won't add the next 5 or 10 chapters to the queue. Sometimes I want to donwload 20/30/40 chapters and I have to press the "download the next 10 chapters" and start selecting manually to download the rest.

It'd be nice if there was an option to "Download the Next 'X' chapters" or at least make the download 5/10 buttons work consecutively.

**Comment by psychowood** [comment]
It would probably enough to change in "Download the Next 'X' **not downloaded** chapters". Also a custom option could help (dialog to ask for X value).

**Comment by inorichi** [comment]
It should work consecutively now.
