### ISSUE TITLE
Batoto source doesn't work

### ISSUE THREAD

**Issue by opheliakc** [inorichi/tachiyomi#557]
When I choose batoto as source the mangas I enter says source is kissmanga and I believe that is true because when I search a manga that's in batoto it doesn't show in the app.

Galaxy s3, latest build, sorry doesn't know the version name. Just installed couple hours ago.

My batoto account works, I can read in browser.

**Comment by bbtora** [comment]
Pretty sure you haven't logged in to your batoto account from settings>source.

**Comment by opheliakc** [comment]
No I am logged in.

**Comment by inorichi** [comment]
It's working for me. Try Settings > Advanced > Clear cookies

**Comment by opheliakc** [comment]
It seems t be fixed now. Thanks again
