### ISSUE TITLE
[request] Language selection

### ISSUE THREAD

**Issue by Snake87r** [inorichi/tachiyomi#558]
Add a language selection for the app,
Usually I have my tablet in my native language, but i prefer some app (like tachyiomi) in english, so if it's possible add an option called "Select language", with Automatic option setted by default, and list all the available translation so every user choose the preferred language for the app..

Version: r982

**Comment by inorichi** [comment]
Changing the locale in runtime is a real mess from what I've seen. I don't think this will be implemented.

You could try to remove the translation for your language, [here's a tutorial](http://forum.xda-developers.com/showthread.php?t=1890521) I found, but I haven't tried it, so it may not work.

I also wanted the english translation in my tablet, so I ended up changing the system's language to english.
