### ISSUE TITLE
Refresh button to reload image/Reload button not working

### ISSUE THREAD

**Issue by myuc** [inorichi/tachiyomi#56]
I have noticed that on some instance if the image cannot be download, there will be a reload button in the center of the page that could not be clicked. I have to go to "setting-> advanced-> clear chapter cache" to clear it before it will try to redownload the image.

Additionally, I have noticed that sometimes, the page doesn't get downloaded correctly and all I see is a black/white screen depending on what the background colour is set. Again. Clearing chapter cache would solve the problem but its a crumblesome fix as the reader would start download from the first page of the chapter. i.e. If say page 40/70 has the issue and i clear chapter cache, I would need to wait for the reader to re-download page 1-39 which I have already read before the "correct" page 40 would be downloaded. 

Sidenote: Aizoban also has the same problem sometimes but it has a refresh button which allows me to just reload that particular page. Can a refresh button (hidden in the menu etc) be easily implemented?

**Comment by inorichi** [comment]
The reload button works fine for me. When you see a black screen, try changing the image decoder, or go 2 pages back and forth. Both options will force the image to be reloaded.

fad7b75 may fix the retry button not being clickable.

I would like to avoid placing it in the menu.

**Comment by inorichi** [comment]
Also, if a chapter has a size bigger than the cache (75 MiB), it will delete the first images, and they won't be able to be reloaded. I have to think how to workaround that, but for big chapters the best option is to download them.

**Comment by inorichi** [comment]
Does the retry button work now?

**Comment by inorichi** [comment]
Closing. Feel free to open it again if the refresh button does not work.
