### ISSUE TITLE
Unwanted save image popup when scrolling in webtoon mode

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi#561]
This is happens when you try to scroll to the next page while the image is still loading. The problem might be easier to be seen when you have slower connections.

![screenshot_2016-12-05-00-13-54-619_eu kanade tachiyomi](https://cloud.githubusercontent.com/assets/14852623/20868345/11e74e84-ba8c-11e6-87e7-1dbd36462d75.png)

Version: v0.4.0
Android Version: 5.1 (Lollipop)
Image Decoder: The default Image, but I've tried using Rapid and the problem are more apparent especially in case when the 1st and 3rd are already loaded while the 2nd are still loading

**Comment by pitman10** [comment]
I use one finger zoom a lot and since the update it always triggers that pop up,  mildy annoying b7t can live with it until a fix is made,  perhaps the app can recognize the action of moving a page/zooming and ignore propting the pop up?

**Comment by inorichi** [comment]
I've noticed this as well, but it's hard to reproduce. I think touch gestures are colliding with each other and making the listener think it was a long tap. I'll see what I can do.
