### ISSUE TITLE
Image saving options while double-tap zooming and no resetting cover picture

### ISSUE THREAD

**Issue by opheliakc** [inorichi/tachiyomi#562]
When I double click and zoom around the save image option appears (unwantedly). mostly I accidentaly change cover image and can't reset it. 
And I don't want the double tap zoom thingy too. If possible please add  a option to turn it off. Or just disable the image saving while you're just zooming

**Comment by inorichi** [comment]
A way to reset the cover is to readd to library. Just click the bookmark icon twice.

I agree that option should have a confirmation dialog.
