### ISSUE TITLE
Issue: downloads not sorting after changing destination to SD card

### ISSUE THREAD

**Issue by maurus56** [inorichi/tachiyomi#564]
I backed up my library and did a clean install of v0.4 . After fixing again the settings, I restored the library and everything worked like always until I changed the destination of the downloads. When modified to the SD card the library updates become clean and the sorting by downloaded stops working. But when opening a manga with downloaded chapters, they appear as so and work fine.
I repeated the process several times and it keeps happening.
Take into consideration that I moved the complete folder from the internal to the SD and then all the other things.

(First time writing a issue)

Version: v0.4.0
Moto X pure
Android 6.0

**Comment by inorichi** [comment]
Have you tried downloading a chapter with the new version? In the changelog I specified compatibility isn't guaranteed.

**Comment by maurus56** [comment]
After testing out the available options for the download path, it seem that the problem occurs when using a user defined path. Since publishing the issue I tried every options to reproduce the problem and it seem that it has to do with this option. Downloading works fine.

To sum it: seems than when using a user specified downloading path the "downloads" sorting method stops working.

Hope the info is useful.

**Comment by inorichi** [comment]
Can you try creating with the directory selector a new different directory in your SD card, and download something there?

I would say this happens because you are providing an existing directory yourself and Android somehow can't take persistable read/write permissions in that folder. If this is the case, there's (most probably) nothing I can do.

**Comment by maurus56** [comment]
Effectively as you said:
-clean install
-assigned path in a folder created with the app on the main SD directory
No problem with the sorting through this method.
Thanks for the help.
