### ISSUE TITLE
'Library updates' taking too long to load

### ISSUE THREAD

**Issue by nosocjo** [inorichi/tachiyomi#567]
Yesterday I updated to the latest version and since then the library updates window gets like this for like 15 seconds.

![screenshot_2016-12-06-20-23-34](https://cloud.githubusercontent.com/assets/24418278/20940192/2b3bd190-bbf2-11e6-9193-a4eca2a8d378.png)

Then it shows the latest updates as it should.
What I did was unistall previous version (installed through F-Droid), install the new version from the .apk I got from GitHub and restored the backup I previously had.

Version: v0.4.0
Huawei P9 lite rooted
Android 6.0

**Comment by inorichi** [comment]
Do you have many downloads and are you by chance using a custom directory?

**Comment by nosocjo** [comment]
I'm using a custom directory (extsdcard/Tachiyomi), but I was already using it before the update.
I only have 1 downloaded manga (329,4 MB), which is less than usual.

**Comment by inorichi** [comment]
This view needs pagination or a hard limit. Can you do a little test by changing the downloads directory to the first predefined one (only the setting, no need to move around folders)?

**Comment by nosocjo** [comment]
Okay, working fine now. 
I've tried moving the downloaded files to the default external folder option and it works. Must be some kind of problem with custom folders.
Anyway, thanks for the quick response and keep up the good work.

**Comment by inorichi** [comment]
I think I'm going to add another entry to select a custom directory like before, without the storage access framework. It won't work with any directory in external SD cards, but it's a lot faster.

**Comment by nurupo** [comment]
Can reproduce using a custom external directory extsdcard/manga. The directory is empty though, no downloads at all, and it takes about 5 seconds for the Library Updates screen to display the entries. Using v0.4.0.

The fact that there is such long delay when the download directory is totally empty kind of makes me wonder if your assumption that the delay is caused by using an extrernal directory is correct.

**Comment by nosocjo** [comment]
I'm pretty sure it's caused by using a custom directory, in my case it doesn't matter whether it's internal or external

**Comment by Madidas** [comment]
I would like to also add that this same behaviour happens opening My library from custom directory in SD-card. Fresh install (0.4.0) and restored library from backup. Also redownloaded all manga (~8.0Gb) again after I noticed this issue. And device is bonestock Moto E (2015) with Android 6.0.

**Comment by inorichi** [comment]
I'm aware of the reason. Any directory selected through the Android filepicker (using the Storage Access Framework, aka SAF) will cause a performance loss.

Current workaround is to use one of the predefined directories. I'll try to optimize the calls in this view and also allow the custom directory to be selected without using SAF (with no support for writing to any directory in an external SD card, but faster).

**Comment by inorichi** [comment]
It should work a lot better now. I would appreciate if any of you can test it with the latest dev build and a custom directory and many downloads.

**Comment by nurupo** [comment]
Installed http://tachiyomi.kanade.eu/latest/app-debug.apk, but apparently it installed a second Tachiyomi, instead of updating the existing one, so it has no library and other stuff.

**Comment by inorichi** [comment]
They are separate apps. But you can use the backup/restore functionality from one to the other.

**Comment by nurupo** [comment]
Didn't know about backup and restore functionality before.

>test it with the latest dev build and a custom directory and many downloads.

Set custom download directory to /`storage/extSdcard/Manga` (which is shown as `content://com.android.externalstorage.documents/tree/0000-0000%3AManga/document/0000-0000%3AManga`) again. The directory itself is empty, I don't have any manga downloaded and I don't download it for offline viewing. When switching to the Library updates screen, I still get the same behavior I was getting the last time of Library updates screen taking about 5 seconds before it displays anything, so nothing has changed for me.

If I select the app-specific directory on the external card, the one predefined, `/storage/extSdCard/Android/data/eu.kanade.tachiyomi.debug/files`, Library updates screen shows entries almost immediately, but so does the stable 0.4.0 version too.

**Comment by inorichi** [comment]
Thanks for the detailed answer. It wasn't working well when the directory didn't exist. It should work as expected now.

**Comment by nurupo** [comment]
Yep, that improved things a lot, the entries on Library updates screen show up almost immediately now, thanks!

**Comment by inorichi** [comment]
Didn't notice the beginning of your previous comment.

> After restoring, how do I make Tachiyomi re-download all the manga covers?

There's an option for that in `Settings > Advanced > Refresh library metadata`.


Back to this issue, it's already fixed so I probably won't need to add the other directory selector. It's possible this issue also happens in the library when enabling the downloaded filter. I'll try to optimize that one too.
