### ISSUE TITLE
Add GIF support

### ISSUE THREAD

**Issue by ywecur** [inorichi/tachiyomi#569]
It's something that's included in some mangas. It would be nice to not have to open the browser for those pages.

**Comment by inorichi** [comment]
You mean the animation or the format not supported?

I need examples in either case.

**Comment by ywecur** [comment]
With the rapid image decoder, animation is not supported but the first frame is shown

![](http://i.imgur.com/n49g5mi.jpg)

With the other decoders nothing appears

![](http://i.imgur.com/NTXRmLw.jpg)

**Comment by inorichi** [comment]
Well, the image library used doesn't support animated gifs, and the decoders not displaying the image isn't something I can fix. If rapid works, use it.

**Comment by ywecur** [comment]
@inorichi Rapid doesn't work, it only displays the first frame. This is even worse in my opinion because you don't even know that the image is supposed to be a gif when seeing it.

**Comment by inorichi** [comment]
[Subsampling Scale Image View](https://github.com/davemorrissey/subsampling-scale-image-view) doesn't support animated gif, and I'm not going to modify it to support them or write a new one. If you find a better alternative that handles subsampling on zooming, gestures and animated gif, please tell me. Otherwise I don't see this being supported.

**Comment by libjared** [comment]
This is an old issue, but Hitoribocchi ch54 page 6 has a GIF. It looks like something the scanlators added to celebrate the anime adaptation. A system to detect the GIF and switch to a different decoder would have saved some confusion.

**Comment by cyanlink** [comment]
@inorichi @libjared Indeed an old feature request... But infact Ehviewer did well on handling GIF and other Formats correctly, According to https://github.com/seven332/EhViewer , The dev uses GIFLIB to implement this, though I can't hash out the whole code for now.

**Comment by NerdNumber9** [comment]
BTW, I've recently added GIF support on my fork. It's kind of hacky as it replaces the subsampling image view with a WebView and then loads the gif in the WebView. It seems to work just fine though.

@inorichi If you want, I can make a PR.

**Comment by bbtora** [comment]
This issue is being addressed in #1550
