### ISSUE TITLE
WiFi and Kissmanga come up "Page list is empty"

### ISSUE THREAD

**Issue by EichiXIII** [inorichi/tachiyomi#572]
I tried looking for this to be mentioned but I couldn't find anything about it. The problem is whenever I try downloading/viewing new chapters from Kissmanga it just comes up as "Page list is empty". This only happens when I am connected to WiFi though. If I connect through 4g I can view and download new chapters with no problem. It might be unrelated but ever since this started, which is a few days after updating to 0.4.0, I deleted everything and downloaded the chapters I wanted again but some manga still show up as "downloaded" when using the downloaded filter despite having no chapters currently downloaded. I even went through all the files making sure it was all empty. One manga currently doing this is Yuki ni Tsubasa which I had never downloaded a chapter of yet. The first attempt to download from that manga was during the time when I started getting the "Page list is empty" message.  

I did try clearing the chapter cache, cookies and database as well as refreshing the metadata but nothing has made any difference.

Version: v0.4.0
Galaxy S5 
Android v6.0.1

**Comment by psychowood** [comment]
Sounds like an IP ban from KM. Perhaps you did download too many chapters at once. Have you tried rebooting the router (hopefully you don't have a static address)?

**Comment by EichiXIII** [comment]
I tried using a VPN in case my IP was being blocked but still had the same problem. I can also read it just fine on WiFi if I open it in the browser.

**Comment by inorichi** [comment]
Does it say anything if you refresh the chapter list (pull down)?

I need to see the exact response the app is getting. Can you get a network dump with Wireshark or tcpdump? This may not be easy to setup, so I could try to prepare an apk that dumps network responses.

**Comment by EichiXIII** [comment]
Nothing at all comes up if I refresh the chapter list. It just updates it if there is anything new. 

I can try but I don't really know how to do it.  Might be able to figure it out though.

**Comment by inorichi** [comment]
That's enough, thanks. Cloudflare flagged your IP and is "asking if you are human". Have you tried opening kissmanga (and try to open some chapter too) WITH your phone/tablet (it has to be the same device) and wifi?

You should see a confirmation box, after that it should work. This usually happens when they detect a lot of traffic.

**Comment by EichiXIII** [comment]
Yep. I don't get any confirmation box. It just opens the chapters up with no problem.

**Comment by inorichi** [comment]
Sadly this is the only way to fix this issue. I'm glad you could solve it.

I've made a few changes to notify the error code received, it's better than a "page list empty".

**Comment by blackman91** [comment]
I have the same issue on the latest dev version, I opened kissmanga on pc but I get no confirmation dialogue.

**Comment by kamicartier** [comment]
I am also running into this problem on latest version, despite visiting kissmanga on my browser

**Comment by Baolle** [comment]
I have the same issue too. No confirmation box when visiting kissmanga on my browser.

**Comment by EichiXIII** [comment]
I started getting it again too and this time even when I do the "Are You A Human?" verification it doesn't resolve it. I can get through it fine on the browser on PC but when I try to start downloading chapters on the app it immediately goes back to "Page List Empty". I can then refresh my PC browser and redo the verification but it is just an endless cycle.

**Comment by blackman91** [comment]
This issue needs to be reopened, this bug appears to be affecting a lot of people.

**Comment by psychowood** [comment]
It is tracked at #696
