### ISSUE TITLE
Release v0.4.0 hasn't made it to F-Droid.

### ISSUE THREAD

**Issue by mishugashu** [inorichi/tachiyomi#578]
It's been 11 days. Is it supposed to be autobuilding?

Might be related to #515?

**Comment by inorichi** [comment]
Build log can be found [here](https://f-droid.org/wiki/page/eu.kanade.tachiyomi/lastbuild_16)

Reason:

```
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.1].
```

They have to accept that license (I don't know if there's any reason for not accepting version 25.0.1).

**Comment by inorichi** [comment]
They have an issue [here](https://gitlab.com/fdroid/fdroiddata/issues/561)

Closing as it's not our fault.

**Comment by paronos** [comment]
v0.4.0 is on fdroid
