### ISSUE TITLE
[Catalogue] Adding request: French sources

### ISSUE THREAD

**Issue by Eeveel** [inorichi/tachiyomi#579]
Hi,
Can you add some French sources? 
Here some French sources:
scan-manga.com
japscan.com
manga-sanctuary.com
mangaKawaii.com
mangapedia.fr
mymanga.io

Thakns for your hard work! :)

**Comment by inorichi** [comment]
Tachiyomi won't include any new catalogues in its core, and the current ones will be removed in a future (not soon) release.

The app is now able to load pluggable catalogues installed as a separate apk, and there's [a new repository](https://github.com/inorichi/tachiyomi-extensions) for this purpose.

Every catalog request/issue should be created there, so feel free to post your request [here](https://github.com/inorichi/tachiyomi-extensions/issues).
