### ISSUE TITLE
Three Dot Mark Previous As Read

### ISSUE THREAD

**Issue by Kiure** [inorichi/tachiyomi#580]
Been using since 0.2.1, just been a lurker and busy with life. 

Currently, when you select a manga and tap the three dots for more options. Mark previous as read does not mark the current one and only the previous one.

I was hoping to change that it does mark the current one read too.

For example, when bookmark a new manga, and you've read up to the latest chapter you want to mark it as read. Tapping the three dots and mark previous as read then another two taps is just unnecessary.

**Comment by wopian** [comment]
"Mark Previous" means it will mark everything before the current chapter. Marking the selected chapter as read too when tapping that option is an unexpected behaviour for the user.

If you want to mark all the chapters as read (i.e your example), you can long hold any chapter → ⋮ → select all → ⋮ → mark as unread
