### ISSUE TITLE
Downloads stop because of an error for another chapter

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#582]
Using 0.4.0, android 6.0.1

https://my.mixtape.moe/couxzh.mp4

As seen in the above downloads have been stopped because of an error for a chapter that isn't being downloaded at all and I have to manually resume the downloads and I have to do it several times until all the chapters in the queue are downloaded.

**Comment by inorichi** [comment]
It stopped because it reached the end. Those downloads failed in the process and manual interaction is required, you are seeing the error of the last download because it's being overwritten.

Nothing to fix here

**Comment by pitman10** [comment]
Does it even retry to resume downloading by itself? 

Perhaps it could try 1-3 times to resume downloads by itself before notifying you that downloads has failed or juat make that message more cleae that all downloads have failed and that manual interaction is required?

**Comment by inorichi** [comment]
There's a retry logic for pages, but not for chapters (retrieving the page list). I may add one or two retries after some time for chapters, but it can still happen.
