### ISSUE TITLE
App is ignoring system Font Size setting 

### ISSUE THREAD

**Issue by GHOSTBEAR** [inorichi/tachiyomi#587]
Did update to lastest version and noticed that font size got bigger. I have my phone Font Size set to "small."  And it seem like Tachiyomi don't care about this setting and treat it like Font Size is set to "normal."

[Picture in v. 0.4.0](http://i.imgur.com/c2fQ6xul.png?1)
[Picture in v. 0.4.1](http://i.imgur.com/A8GZTAEl.png)
Ignore that I have a screen filter on

## 
Version: v0.4.1
Phone: Sony Xperia Aqua M4
OS: Android 6.0.1

**Comment by inorichi** [comment]
Must be a side effect of #563

**Comment by inorichi** [comment]
Working fine in my phone, not sure about other devices.

**Comment by GHOSTBEAR** [comment]
Okay, do you know how long till dev build is available with the fix? Or is it already available to download.

**Comment by inorichi** [comment]
Usually around 5 minutes since the commit. It's already there.

**Comment by GHOSTBEAR** [comment]
Did download latest dev build. Seem to be working now. Thanks for fix it 😄
