### ISSUE TITLE
Colors tone change when using Image decoder

### ISSUE THREAD

**Issue by nshishov** [inorichi/tachiyomi#589]
Version: r1003
Android 6.0 on Huawei M3

Hi!

When I use "Image" decoder colors tone changes (look at the screenshot), no problems with Skia or Rapid decoders.

PNG files looks fine, very likely it affects only JPG.

![screenshot_2016-12-17-14-38-10 1](https://cloud.githubusercontent.com/assets/20397468/21325745/7719cc64-c630-11e6-8ab4-96f56ad5bd00.jpg)

**Comment by jshap70** [comment]
If you tap the screen to bring up the viewer's header and footer, and click the sun/moon icon in the top right, can you check that you don't have any of the settings tweaked in this menu?

**Comment by inorichi** [comment]
I noticed this as well, but I thought it was the image. It may be related to decoding the images with RGB565, but all the decoders are using that format.

Anyways the decoder implementations aren't part of the app and I can't fix them, so I would suggest you to create this issue [in the repository of the creator of this library.](https://github.com/seven332/Image)

**Comment by nshishov** [comment]
@jshap70 
Of course all this settings are turned off.

@inorichi 
Have you tried to use another version of the library?
I suppose EhViewer uses the same library and it doesn't have this problem.
https://github.com/seven332/EhViewer/blob/master/app/build.gradle

**Comment by inorichi** [comment]
No, but I can't go back too many versions because the bitmap decoder was added in 0.2.5. Previously it only supported bitmaps with data in the native heap and Tachiyomi/Subsampling can't work with those as far as I remember.

**Comment by nshishov** [comment]
@inorichi 
Ok, thanks.

**Comment by nshishov** [comment]
@seven332 commited change to the library that should fix the problem https://github.com/seven332/Image/commit/7a1b4cb6d9cae58c57faef073972752adf56295d

Can you please make new build using latest library version?

**Comment by inorichi** [comment]
Done.

**Comment by nshishov** [comment]
Thanks!
It works now.
