### ISSUE TITLE
When Opening a manga from recent updates, it sometimes creates a new instance

### ISSUE THREAD

**Issue by IceKreem** [inorichi/tachiyomi#59]
I have a category set up (Reading, Plan to Read and Completed). Sometimes When a manga is opened from the recent updates, it will create another instance of the manga which is in the default category.

**Comment by inorichi** [comment]
Oh, I know what's happening. The cursor for a manga and a chapter has the same id and the manga's id is being mapped as the chapter's id.

The same is happening with #58.

**Comment by inorichi** [comment]
I would recommend to remove all the duplicated instances from the library and clear the database (from the advanced tab).

**Comment by IceKreem** [comment]
Yeah I have done that :+1:
