### ISSUE TITLE
Share/Cover/Save Long Tap menu issues opening

### ISSUE THREAD

**Issue by QuDu43bChhiONNVlgkoy** [inorichi/tachiyomi#598]
I have issues opening the long tap menu where you can share/cover/save an image from the chapter. The issue being is it very rarely shows up when I long tap. Seemingly it randomly assigns itself to a small part of my screen. Opening the menu, closing it, and holding the exact same place isn't a guarantee I can open it again.

I have tested this on two devices, listed below. I am having issues on my S7. I am having no issues on my Galaxy Tab E tablet. I have reset my phone to see if it would fix it, it didn't.

Version: v0.4.1
Samsung S7
Android 6.0.1
No mods.

Version: v0.4.1
Samsung Galaxy Tab E
Android 6.0.1
No mods.

**Comment by inorichi** [comment]
Most likely related to [this commit](https://github.com/davemorrissey/subsampling-scale-image-view/pull/211/files) not included in my fork. Though those changes conflicts with the ones @iBaer made for better scrolling.

I've wanted to rebase my fork against the latest version (3.6.0) for some weeks, I'll try to do it soon. @iBaer is it fine if we first try with this new method?

**Comment by inorichi** [comment]
Can you try with the latest dev build?

**Comment by QuDu43bChhiONNVlgkoy** [comment]
Apologises for the late response. I was waiting for the new update to come out on fdroid and decided to just back up and install the app manually.

Still having the same problem. With v0.4.1 (and to extension v0.4.2) I found that it's consistently in the bottom right hand corner somewhere, linked below.

http://i.imgur.com/0zEfEjq.png

**Comment by inorichi** [comment]
The release (v0.4.2) doesn't include any fix. I meant [this](http://tachiyomi.kanade.eu/latest/app-debug.apk) version. It's installed separately, so no need to backup and uninstall the other first.

**Comment by QuDu43bChhiONNVlgkoy** [comment]
Downloaded the debug version, seems to work fine.
