### ISSUE TITLE
Unknown error on MAL login with a wrong account

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#599]
On r1017, trying to log into MAL gives me unknown error. (I just uninstalled the f droid version, and after restoring backup I tried logging in, resulting in this error)

**Comment by inorichi** [comment]
I'm now showing the error message. Update and tell me what it says.

**Comment by BlackSynder** [comment]
I should specify that I've logged in with a correct account and it worked. Still gives an unknown error when the account is wrong though.

**Comment by inorichi** [comment]
Okay, not a bug then. It now shows additional information in a toast.
