### ISSUE TITLE
Can't search in YAML parser

### ISSUE THREAD

**Issue by TheFrajem** [inorichi/tachiyomi#600]
I added the parser for readcomiconline.to to the last stable version (0.4.1 as I write) and it works. I can see the full list of the comics, and I can read them perfectly. Two things don't work.
Searching. When I write the first letter of the search, everything disappears, as if it searched "b" and there were no comics with b in the title (it's the same if I write the whole word).
Loading backup. I already used the site with an old test version (named Tachiyomi test), now if I backup my list with the old version and load it up with the new one, i can see all the comics and the reading progress, but I can't read them. when i click on a chapter it shows a quick "unsuccessful code 404" popup and nothing happens. I don't know if this problem has anything to do with the parser, anyway.
Thanks!

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by j2ghz** [comment]
https://gist.github.com/j2ghz/fe656fc9efe86de6fee6457bc9454170#gistcomment-1946839

**Comment by inorichi** [comment]
The YAML parser is not going to be updated anymore. It'll be better when extensions are implemented.
