### ISSUE TITLE
scroll bar + downloads tab

### ISSUE THREAD

**Issue by Jkccl9** [inorichi/tachiyomi#605]
Please can i request some features

A scroll bar in the manga listings with marked intervals if possible, ie if there are 600 chapters I can't easily find 455 without scrolling down. 

Also please can there be a separate downloaded tab so then it is easier to mass delete downloaded manga 

One last thing can you add a link to github or a contact email in the settings

Sorry if I posted something wrong,  I'm doing on a phone and I've never used github :) 

Thanks 

Version: v0.4.1
Marshmallow

**Comment by inorichi** [comment]
I think this could be added when that page is rewritten with a new library, probably in a few weeks.

**Comment by Jkccl9** [comment]
Thanks, no rush I'll be waiting :D

**Comment by inorichi** [comment]
5c4139b  added the scrollbar
