### ISSUE TITLE
Readmangatoday error 400 on my tablet but not my phone

### ISSUE THREAD

**Issue by rumitg2** [inorichi/tachiyomi#608]
On my tablet every few days manga from readmangatoday stops working and returns an error 400 code. I have never had this issue on my phone for over 3 months since I started using it but every few days I have to reset my account to keep viewing.  Any idea what this could be?

Version:  v0.4.1
Android 6.0 EMUI 4.1

**Comment by NixAshtear** [comment]
Something similar for me. I'm getting error 400 on all readmanga.today titles right now, just started happening today though. I can still reach their website to view titles so the site isn't offline or anything. Their site says they just fixed a problem with another app not showing their manga so perhaps they changed something that is interfering with a lot of the manga readers

**Comment by Presac** [comment]
I had the same problem. Got fixed after I used "Clear chapter cache", "Clear cookies", "Clear database" and "Refresh library metadata". I don't know which of them solved the problem, as I did everything at once.

**Comment by Presac** [comment]
Did you happen to check one at a time, or all at once? Would be good to know which of them solved it.

**Comment by NixAshtear** [comment]
Just did them all, if it happens again I'll test it and let you know

**Comment by inorichi** [comment]
The only related issues I can think of are "clear cookies" and "clear database". I'm closing this since it seems it doesn't happen anymore. Probably a change in the site was causing this issue.
