### ISSUE TITLE
[Catalogue] raw.senmanga.com

### ISSUE THREAD

**Issue by calvinize** [inorichi/tachiyomi#609]
Hi there, first off, I would like to thank you for creating this awesome app. It's definitely the best manga reader for Android I've ever used!

That being said, I would really appreciate it if you could add at least one source for reading raw (untranslated) manga. I suppose the most popular one is http://raw.senmanga.com/ but something else would be fine really.

Thank you very much.

Version: 0.4.1

**Comment by inorichi** [comment]
Duplicate of #404. Also, soon every catalog request will be closed here, once I achieve catalogs as extensions. I'll create another repo for that.
