### ISSUE TITLE
Latest Updates Tab/Drawer

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#61]
One of the best features in Manga Rock is the Latest Updates tab which I frequently check for new manga that I'm not yet aware of. Most of my ongoing reading material was found through that feature. MangaDLR too has this feature under the Latest tab. 

It would be incredible if you could implement a similiar feature for Tachiyomi. At that point I would have no reason to fire up Manga Rock or MangaDLR ever again.

**Comment by Bloodwork** [comment]
Now that 0.2.0 is out are there any plans for this feature?

**Comment by inorichi** [comment]
Not yet. There are other priorities right now.

**Comment by Bloodwork** [comment]
No problem! Keep up the great job you and the team are doing.
