### ISSUE TITLE
"My library" always empty, even after downloading manga

### ISSUE THREAD

**Issue by yankee14** [inorichi/tachiyomi#617]
EDIT:
I didn't realize that you have to click and hold on a manga in the catalogue and select "Add to library." In my opinion, this kinda violates the principle-of-least-surprise, and its kind of a strange default behaviour. If I've already downloaded one or more chapters of a manga, or an entire manga, I think it should show up in the library without having to be added manually. But I totally understand if others don't agree. 
***
The latest update caused all previously and newly downloaded manga to disappear from "My library." Cannot locate downloaded manga anywhere within the program. The catalogue sources still list manga properly, and it allows me to download them, but they do not appear within the program.

I have tried uninstalling and reinstalling Tachiyomi, clearing the chapter cache and database, and deleting the ./Tachiyomi/downloads directory in between reinstalls.

- Tachiyomi Version 0.4.1, Build time 18 Dec., 2016 17:54, installed via F-Droid
- Device Model: LG G2 LS980 (Sprint), Rom: CyanogenMod version 12.1-20161016-NIGHTLY-ls980

I do not have the ability to test this on another device.

Steps to reproduce:
- Install Tachiyomi (from F-Droid)
- Download any manga from any catalogue source.
- Observe that they don't appear in the library, yet they do exist on the filesystem.

EDIT: The chapters I've already downloaded have the tag "DOWNLOADED" when viewed in the catalogue, though they don't appear in the library. Clicking on already downloaded chapters opens the chapter in the viewer, as expected.

**Comment by inorichi** [comment]
There's a button when you open a manga (in the info tab) for bookmarking, the long tap is an additional way to bookmark more than one of them without having to open the details screen for each one.

Downloading and bookmarking are different features of the app. Downloading a chapter doesn't mean your manga is bookmarked, though I agree the user should at least be notified.

There was a discussion for this in #448 and a recent PR #618.
