### ISSUE TITLE
Mangafox search not showing

### ISSUE THREAD

**Issue by reddeimon** [inorichi/tachiyomi#619]
Mangafox has updated recently that it will show the cover of manga instead the name list like always. So the Tachiyomi Mangafox search cannot show any result. Hope you can fix this soon

![screenshot_2016-12-30-22-27-53](https://cloud.githubusercontent.com/assets/13470103/21566597/56d48770-cedf-11e6-83a0-d472ca1aa594.png)

![screenshot_2016-12-30-22-29-46](https://cloud.githubusercontent.com/assets/13470103/21566620/8fda5e50-cedf-11e6-92e1-bbccd10ddbb9.png)

Version: or v0.4.1
Andoid  Lollipop

**Comment by inorichi** [comment]
This was fixed in #604, either use the dev release or wait for 0.4.2
