### ISSUE TITLE
Library Updates Tab opening slowly

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#623]
Just as the title says, the Library Updates tab is opening very slowly. Is it because there are many downloaded chapters in the phone? It wasn't much happening before. Can you look into it?
Other tabs are opening just fine if you were wondering so don't know what's the problem with that specific one.
Version: r1038

**Comment by inorichi** [comment]
Yes, it's because of the downloads. I've already optimized the downloads discovery, so we have to add a paginator here. It's always retrieving all the updates from the last 30 days, and with big libraries it can have a lot of results. It should retrieve around 100 objects per page.

**Comment by inorichi** [comment]
I was able to improve the downloads discovery even more. Can you tell me how it plays with your library? Hopefully I don't have to add pagination.

**Comment by inorichi** [comment]
Ping.

**Comment by bbtora** [comment]
Oh sorry, really hadn't checked your reply there. And thanks it's working faster than before. 
Yes it might be because of the custom directory but I later on changed that to predefined one.

**Comment by inorichi** [comment]
Is the difference when using the predefined and the custom noticeable or almost the same?

**Comment by bbtora** [comment]
It's noticable. But I really don't know what really solved this issue. Whether it was the directory change or our tweaks or my erasing database not in the library.

Also, can we get a quick instructions on how to add and read local files?

**Comment by inorichi** [comment]
I wrote instructions for local manga in [this issue](https://github.com/inorichi/tachiyomi/issues/254#issuecomment-275941848). I'll add it to the wiki later.

I'm closing the issue since it should be fast now.
