### ISSUE TITLE
[FEATURE REQUEST] Download will Auto Add Title to My Library

### ISSUE THREAD

**Issue by Rait0** [inorichi/tachiyomi#638]
The first time I used this awesome app, I struggled on finding where my downloaded manga can be found. I realized that I should bookmark the manga first so I can open them, view manga details and the chapters including those I've downloaded offline.
I guess it would be a great help if it automatically add the titles to My Library /bookmarks those titles that we are downloading. Because it's only logical that we'd view them on our library sooner or later after downloading. You can also just create a "downloaded" tab but I think just the automatic bookmark when we download will do the job.

Version: v0.4.2
Android 6.0

**Comment by NoodleMage** [comment]
#448
