### ISSUE TITLE
Can't find downloaded titles

### ISSUE THREAD

**Issue by soulsynapse** [inorichi/tachiyomi#641]
I downloaded some manga and forgot which one I downloaded, now I can't find any history or location or anything for where it is

You'd think it'd be automatically downloaded to 'my library' cuz you know, it's part of your library. You downloaded it.

How can I delete what I downloaded?

**Comment by soulsynapse** [comment]
nvm I found it in recently read

that said though, every single other manga reader does this.. seems really silly for this one to not

**Comment by inorichi** [comment]
#618
