### ISSUE TITLE
Option in Deleting Manga

### ISSUE THREAD

**Issue by Rait0** [inorichi/tachiyomi#642]
I don't know if there's any other workaround in deleting manga besides manually deleting them using a file manager or going to manga details and delete chapters. I've also tried the advanced option that says delete manga or chapters that are not in my library but it does not seem to delete anything from my storage. 

So what I am trying to request is an option when deleting manga the application will ask if it will delete downloaded files or chapters as well. Thank you :)

Version: v0.4.2
Android 6.0

**Comment by rachmadaniHaryono** [comment]
There is also features to delete manga after you read it. Go to 'settings'->  'download'   ->   'remove after read' section. There you can set the option of how manga will be deleted

**Comment by Rait0** [comment]
Yeah I've seen that but I don't usually delete right after I read a good manga. In this case I've downloaded a lot of manga and I don't have plans on reading some of them, I've also got duplicates of manga from different sources which I wanted to compare image and translation quality before going to actually reading them. Deleting them along with their files from the library would be really helpful.

**Comment by inorichi** [comment]
If you hold any chapter in the chapter list it will enable selection mode, then you can use the select all button and then delete. I guess we could show a dialog for deleting all the chapters if the manga is unbookmarked (and only if the manga directory exists).

>  I've also tried the advanced option that says delete manga or chapters that are not in my library but it does not seem to delete anything from my storage

That's expected, it's only for cleaning up the database.

**Comment by pitman10** [comment]
Despite having 'remove after read' and selected all chapters and 'deleted' them I could see it was still taking space on my phone https://imgur.com/a/qilem 

and it's not the only one, had to manually remove with a filemanager a couple of other manga folders that stuck around even after reading them all.

**Comment by inorichi** [comment]
Now it asks you to delete downloaded chapters (if any).
