### ISSUE TITLE
[ISSUE] Kissmanga Filter isn't working

### ISSUE THREAD

**Issue by Rait0** [inorichi/tachiyomi#643]
I've tried checking almost all the manga filter of kissmanga but it just doesn't work. Here on my screenshot I filtered for genderbender but it only showed their manga list a-z. Same happens using other filters.
I've checked kissmanga and their web filter works fine.
http://m.imgur.com/3E2HUW4

Version: v0.4.2
Android 6.0

**Comment by inorichi** [comment]
It's fixed upstream.
