### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by kerosyn** [inorichi/tachiyomi#646]
Version: v0.4.2
Android: 6.0.1

Adding Chromecast support could be another thing that sets this app apart from other manga apps. Functionally-wise it wouldn't be much different from casting the full screen but it could be optimized for using a seperate screen.

Allowing the user to customize the Chromecast viewing without modifying regular mobile viewing. Allow the user to keep there phone vertical, while the TV is fit-to-width landscape. Give the option to start/pause/stop slideshow.

Not a hugely important feature request, just something I thought might be interesting.

**Comment by inorichi** [comment]
I don't have a chromecast to work with nor the enough motivation to implement it. I'll keep it open if anyone wants to work on this, as long as it's a relatively small amount of code to maintain (I don't know how it works at all).

**Comment by arkon** [comment]
Going to go ahead and say this is never going to happen...
