### ISSUE TITLE
I lose all my manga covers  3 times a week

### ISSUE THREAD

**Issue by Sinaaaa** [inorichi/tachiyomi#647]
I have a Huawei p9. I often lose all my manga covers, then I use the "refresh library metadata" setting & it's back to normal for a very short while, at most 2 days. Tachiyomi only needs the "storage" permission & it has it. My phone is super stable, nothing else is malfunctioning, I'm not rooted & I'm running stock firmware.

Version: v0.4.1
(Nougat 7.0)

**Comment by inorichi** [comment]
Free space on the SD card/internal storage? (usually labeled as `/sdcard`)

Tachiyomi doesn't delete the files there unless you unbookmark the manga, but the system may decide to delete the files if you are running out of memory.

**Comment by Sinaaaa** [comment]
I have 10 gigabyte+  free, both on internal & sd.

**Comment by inorichi** [comment]
Do you remove/extract the SD often? Have you ever experienced a crash when using the `Clear cache` setting in `Advanced`?

**Comment by Sinaaaa** [comment]
I only removed the SD once since the Nougat update. Clicked "clear chapter  cache" & no crash happened.

**Comment by inorichi** [comment]
I have over 150 and I don't have any issue. Does the directory I said before exists? If so, how many files does it have?

**Comment by Sinaaaa** [comment]
34 files, but I just did a refresh metadata today.

**Comment by inorichi** [comment]
And which site are you using? The covers being redownloaded means they were deleted or modified. If they are blank until you refresh the metadata, it means its thumbnail url has changed and it's not found (do the covers change?).

**Comment by Sinaaaa** [comment]
Mangahere & Mangafox mostly. Usually no change to the covers.

**Comment by Beylers** [comment]
Happens to me too on Mangahere and Kissmanga sources.
