### ISSUE TITLE
Bit of a problem with MAL search and short titled manga

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#65]
Series with short names like Rin or Magi are impossible to find in the integrated search feature. While the Magi has the affix "The Labyrinth of Magic" in MAL, Rin has nothing like it and currently it is impossible to find and update it through the app.

Rin on MAL: http://myanimelist.net/manga/46894/Rin 

A long list of a bunch of stuff that is not Rin:
![screenshot_2016-01-25-00-04-08](https://cloud.githubusercontent.com/assets/7024084/12539291/eb27a852-c2f7-11e5-9645-5d461cf10349.png)

**Comment by inorichi** [comment]
There's nothing I can do there. Those are the results returned by MAL's API. Try looking for the alternative name in the browser and try with that.

**Comment by Bloodwork** [comment]
Unfortunately there is no alternative name. Maybe it is possible to make the list longer than it is currently to include more results?

**Comment by inorichi** [comment]
http://myanimelist.net/modules.php?go=api#animemangasearch

I don't know if it's possible.

**Comment by inorichi** [comment]
There's a way. I could show the list of the user (with a checkbox or something) and it could be selected there. I don't know how to design the dialog to do this in a friendly way though.

**Comment by inorichi** [comment]
Install from F-Droid: https://f-droid.org/repository/browse/?fdid=eu.kanade.tachiyomi

**Comment by inorichi** [comment]
As of 8ca0814 you can search a manga from your list like this: `my:rin`

**Comment by reconman** [comment]
Can you please add some tooltip or any sort of hint so users don't have to look up this feature on github?  

For example you could display a text like "Use my:<title> to search for titles in your MAL profile"  below the search textfield all the time or when the search field is empty. When the search textfield is empty there is plenty of space in the white rectangle dedicated to the search results.

**Comment by nearbaskara** [comment]
omg it helps me :lol 
would be better if you put that <my:<<manga>>> instruction on the app tho.

**Comment by AmineI** [comment]
Just to be sure, regardless of the current MAL API status, was this feature removed ? It's still in the FAQ but I couldn't get it to work nor find the current code of the feature (a quick "getList" search  in the repo returns nothing else than the function 
itself available from MAL's workaround that was just merged, but I could have missed it somehow so I'd prefer to ask)
