### ISSUE TITLE
Deleting one sync service

### ISSUE THREAD

**Issue by Kavboy** [inorichi/tachiyomi#653]
If possible add the option to cancel the use of one sync service. I only wanted to test anilist and mal together for a sort period of time and now i can't remove mal from the sync list.

Version: v0.4.2
Android 7

**Comment by inorichi** [comment]
Use a wrong password and it'll unlog. Not the best thing we can do but it works.

**Comment by Kavboy** [comment]
Ok it worked this way, is there no way to make this with a loggout button or does the api from mal doesn't provide such a function?

**Comment by inorichi** [comment]
Anilist uses a different login procedure, so I think I'll allow to unlogin with a long tap. Either that or a settings icon where the green tick is placed, but then I would have to remove the tick.

**Comment by Kavboy** [comment]
Personally I would prefer an icon because a long tap, is in my opinion not the way that users know how to interact with a loggout function. But it's your choice in the end. I'm fine with both solutions.

**Comment by arkon** [comment]
Logout flow as added recently.
