### ISSUE TITLE
special character issue

### ISSUE THREAD

**Issue by 0x72D0** [inorichi/tachiyomi#654]
when I was trying to open the chapter Tower of God - 108 -, the chapter didn't open and tachiyomi display an error message.

I think the cause of this issue is the special character at the end of the name of the chapter.

OS: Android 5.0.1
catalogue: ReadMangaToday

![screenshot_2017-01-24-21-05-01](https://cloud.githubusercontent.com/assets/16087328/22302692/e6d880f6-e2fd-11e6-8603-5dbfa7e8291b.png)

**Comment by inorichi** [comment]
It's on their end. The chapter isn't available here http://www.readmanga.today/tower-of-god/108%E2%80%93
