### ISSUE TITLE
Unable to load covers for manga saved in library

### ISSUE THREAD

**Issue by kvsjxd** [inorichi/tachiyomi#657]
Version: 0.4.2
OS: LineageOS 14.1 (Android 7.1.1)
Device: Samsung Galaxy S5 (SM-G900W8) (klte/kltecan)

I updated my library with covers and new chapters information and closed the app. Whenever I launch the app next time, it always fails to load the saved covers from cache. So, I have to update library each time I launch the app.

**Comment by inorichi** [comment]
#647
