### ISSUE TITLE
Feature request - Export downloaded manga title to a PDF file

### ISSUE THREAD

**Issue by kvsjxd** [inorichi/tachiyomi#658]
Please develop a feature to export a downloaded manga title (.JPG files) to a PDF/EPUB file for easy storage. Just like creating a physical notebook by stapling some pages together.

**Comment by inorichi** [comment]
Why would you want that? I could understand it if you wanted a cbr/zip, but pdf?

**Comment by kvsjxd** [comment]
zip format would be handy too :+1:

**Comment by j2ghz** [comment]
Why not do it at a PC? Manga downloaders exist and cbz to pdf converters do as well.

**Comment by kvsjxd** [comment]
Then I will have to depend on PC for this additional task, if an app does all comics related stuff them it would be easier to manage :)

**Comment by inorichi** [comment]
For the record, we are not going to support PDF in the reader, so you would have to use another app for reading them.

**Comment by kvsjxd** [comment]
Alright how about cbr format then?

**Comment by inorichi** [comment]
It's planned, but support will start with cbz (zip). We'll try with rar later.

**Comment by kvsjxd** [comment]
Thanks for the info! :+1:
