### ISSUE TITLE
MAL sync finds non-existant entries.

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#659]
v0.4.2

Was looking into syncing this title (Obaa-chan to Game) to MAL and it finds the title (http://i.imgur.com/CluX9QL.png) and when I try to add it I get 'http 400' / 'http 403'  errors, when checking MAL the entry for this manga does not exists.

**Comment by inorichi** [comment]
It's actually there, but pending approval: https://myanimelist.net/manga/102217

If you try to add it in MAL you'll see that message.

**Comment by inorichi** [comment]
This shouldn't happen too often, and even if I show that message as error it still won't work. I'll leave it like this for now.
