### ISSUE TITLE
Hummingbird sync support

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#66]
Add [Hummingbird](https://github.com/hummingbird-me/hummingbird) support, 2nd biggest anime tracker after MAL.

Manga API is currently not really documented anywhere in V1 and V2, plus both are soon to be deprecated when Hummingbird V3 and API V16 rolls out later in February with oAuth. 

V16 API has  elasticsearch, so things like #65 won't be an issue, and its output follows the [JSON API](http://jsonapi.org/) spec.

**Comment by Bloodwork** [comment]
That would be great!

**Comment by Codex-** [comment]
Definitely keen for this, might try add it in a fork I'm not beaten to it...

**Comment by inorichi** [comment]
The database is already prepared for multiple sync services. The auto-updater is also able to update multiple services when a chapter is read.

I don't know how easy would be to maintain a [generic interface](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/mangasync/base/MangaSyncService.java) for all of them. That one was made in a few minutes.

The MyAnimeListFragment could be renamed to SyncFragment or something like that, and it would show the binding of enabled services.

I'm also considering to move everything related to sync to a new settings tab (automatically update in enabled services settings, the login for them and a way to enable or disable them).

**Comment by Rumple007** [comment]
Yes, thats a good idea

**Comment by Codex-** [comment]
Looks like a good foundation for addition.

There is a v2 api currently in the works but for now you could sync library changes with the v1 api (i'm pretty sure it works, haven't tested it personally)
https://github.com/hummingbird-me/hummingbird/wiki/API-v1-Methods

**Comment by wopian** [comment]
@Codex-, V2 isn't in the works, the master branch is frozen and all development is taking place on the `the-future` (HB V3 and API v16)

**Comment by Codex-** [comment]
oh yeah you're right, I forgot v3 was under works.

**Comment by TheWhiteHunter** [comment]
I use anilist personally so if that could be looked at for future support as well, that would be cool :) 

In the meanwhile, Flynx is a quick way to update your list on other sites while reading.

**Comment by BlackSynder** [comment]
is this still being considered? i prefer hummingbird over MAL because it looks prettier (both on the net and the fan made apps) i dont really mind moving back to MAL but it would be great to to have this.

**Comment by JohnFlowerful** [comment]
Hummingbird doesn't have the silly rules MAL has with its DB either.

**Comment by inorichi** [comment]
There's no API for manga AFAIK. Ping me when v3 is out.

**Comment by mishugashu** [comment]
I don't know if this information will help or not:

https://forums.hummingbird.me/t/manga-related-api/24670/7

**Comment by wopian** [comment]
@mishugashu nope, that's the internal API.

It's far better to wait for V3 of HB to release and it's V16 (i.e V2016) API than to bodge together a temporary solution that will break the second V3 is released.

**Comment by wopian** [comment]
Hummingbird is now Kitsu, see #574
