### ISSUE TITLE
No content Provider

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#661]
Added local files as per the previous reference but getting "no content provider" in the local manga catalogue. 

Version: r1085

**Comment by wopian** [comment]
What's your folder structure like?

**Comment by bbtora** [comment]
The directory structure is like this :
sdcard 
-> Tachiyomi 
-> downloads | local
-> local -> manga_name -> chapter_no

**Comment by inorichi** [comment]
Chapters structure? Zip/cbz? Content of the zip?

**Comment by bbtora** [comment]
ZIP file and contains obviously pics. 180 png pics to be precise.

**Comment by inorichi** [comment]
It seems the content provider isn't installed. You may have to reinstall. How did you install the update?

**Comment by bbtora** [comment]
Just over the existing app. So I might have to reinstall it after all? I'll give it a try and report back.

**Comment by bbtora** [comment]
Reinstalled the app but didn't solve the problem.

**Comment by inorichi** [comment]
Just tried with the apk from the build server and it works for me™. 

I need more information, Android OS, any mod, root, the app you used to install tachiyomi (firefox, a file manager, etc...)

**Comment by bbtora** [comment]
Android OS : Marshmallow 6.0.1
no mod/root
APK was installed through the download manager.

**Comment by inorichi** [comment]
Are you storing them in a removable SD card? If so, can you try moving them to the external partition? When is the error shown, when trying to open a chapter or when opening the catalogue?  Maybe in 6.0 or MIUI the Storage Access Framework is required, but it works in Nougat with no extra permissions.

**Comment by bbtora** [comment]
No, I'm storing them in the internal storage. And error is being shown when opening the catalogue.

**Comment by inorichi** [comment]
Try using a folder for the chapter instead of zip/cbr. Move the current zips to another folder outside `local` so that the catalogue may survive the exception. This will help to know if the error has to do with the OS permissions or the `ZipContentProvider`.

**Comment by bbtora** [comment]
I have this current directory route : sdcard/tachiyomi/local/manga_name/chapter_no/pages.png

Still doesn't work.

**Comment by inorichi** [comment]
I'm also using MIUI 8, but on Lollipop, and it's working here. Weird because the downloads have a similar path (replacing `local` with `downloads`) and they are working.

I have no clue.

**Comment by bbtora** [comment]
Okay, I may have taken the first step to solving it but I gotta need help now.

What I did was just remove the `manga_name` folder and just kept `chapter_no` folder with pics inside `local` so the catalogue is showing the manga title as "ch60" and didn't found any chapters inside it...

**Comment by bbtora** [comment]
So the directory I have right now is sdcard/tachiyomi/local/ch60/pics

**Comment by NoodleMage** [comment]
I got the same error on my emulator (7.0) . Tried to debug it (didn't have much time). But it seems to give the error because [this](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt#L159) returns an empty string for the url. Directory was Tachiyomi/Local/name/chapter_21.zip

**Comment by bbtora** [comment]
Mine seems to work now with : `sdcard/tachiyomi/manga_name/chapter.zip`

I don't know why but having `local → manga_title folder → chapter_no folder → pics` is giving errors.

**Comment by bbtora** [comment]
Mine broke again. Was testing something but now I can't seem to recreate the scenario.

**Comment by inorichi** [comment]
I was able to reproduce with the given steps. Thanks.

**Comment by bbtora** [comment]
Thank you so much it's finally working! You don't know how much happy am right now after trying so much 😄
