### ISSUE TITLE
Configurable local manga storage path

### ISSUE THREAD

**Issue by Gilfar** [inorichi/tachiyomi#662]
I propose to make this configurable akin to Download directory as ContextCompat.getExternalFilesDirs(context, null) doesn't return SD card for my ROM meaning I'm stuck with internal storage only. 

Also maybe tie Download directory and Local manga directory under one base path if no one objects.

**Comment by inorichi** [comment]
Additionals directories can be easily added with the current implementation. Merging downloads with local is complicated and I'm totally against it.

**Comment by inorichi** [comment]
A few more directories are detected now. Is it still unrecognized by your ROM?

**Comment by Gilfar** [comment]
The problem is it's a dodgy original chinese rom that doesn't set SECONDARY_STORAGE, so all hope is lost for automatic sdcard detection, I think. I could edit ramdisk, however I do not feel like doing it only for tachiyomi

**Comment by meelahi** [comment]
Local could be merged with library directly instead of downloads or even be completely separate. I'd be happy if it's not part of Catalogues that's all.

**Comment by LakotaGray** [comment]
Can this be closed now?

**Comment by arkon** [comment]
Closing this since it's mostly usable nowadays. It'll also be a huge pain with Android 11's storage model.
