### ISSUE TITLE
Add search by author name in manga tracking tab

### ISSUE THREAD

**Issue by Iliansic** [inorichi/tachiyomi#663]
Could you please add additional search options for tracking tab like author name?

Currently there is an issue when the name of the manga is too short like [RiN](https://myanimelist.net/manga/46894/RiN?q=rin), or commonly used like [Happiness ](https://myanimelist.net/manga/85173/Happiness?q=happiness) gives a quite a long list of manga-titles. And the most frustrating thing is that the required manga doesn't fit in presented list.

It would make the search much easier if we could look by the authors name as well.

**Comment by 444nonymous** [comment]
+1

**Comment by vezelas** [comment]
would also really like this feature +1

**Comment by Studywolf20** [comment]
+1

**Comment by sbstratos79** [comment]
+1 But are we ever going to get this feature? :(

**Comment by arkon** [comment]
Doesn't this just depend on what the tracking service returns from their search?
