### ISSUE TITLE
Local Manga Sorting

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#665]
Sorting in the chapter list seems a sort of mess. Will it be better to change `vol` to `ch` ?

![screenshot_2017-01-31-20-15-15-375_eu kanade tachiyomi debug](https://cloud.githubusercontent.com/assets/23010526/22470378/1590059e-e7f5-11e6-9a4a-e8f7804ef72e.png)

Version: r1086

**Comment by wopian** [comment]
Pretty sure the sorting only finds the chapter number and doesn't deal with volumes.

What does the list show when you change the `display mode` in the menu to `show chapter number`? Should probably be Chapter 0 on all of them I believe.

**Comment by bbtora** [comment]
Yes, it shows `chapter - 1~` . So should I go and rename `vol` to `ch` in thr chapter name? But other manga title like this one shows it correctly (even though it's from kissmanga catalogue)
![screenshot_2017-01-31-20-50-49-862_eu kanade tachiyomi debug](https://cloud.githubusercontent.com/assets/23010526/22471045/379777ba-e7f7-11e6-975e-017fca13d2f1.png)

**Comment by inorichi** [comment]
The number after a volume is ignored because we only rely on the chapter number. That screenshot is working because by default the ordering follows the original source. But the local source can't have that.

**Comment by bbtora** [comment]
So what should be the solution for that?

**Comment by inorichi** [comment]
Remove "vol" before the number.

**Comment by bbtora** [comment]
Ok. Sort working now.  But does the keyword `vol` or `v01` trigger that issue?

**Comment by NoodleMage** [comment]
It's not realy an issue. It's intended behavior. Things like vol ,v, s, season get filtered out to prevent wrong chapter recognition.
