### ISSUE TITLE
KissManga Issue (Manga are not showing up)

### ISSUE THREAD

**Issue by ahhhno** [inorichi/tachiyomi#666]
Certain manga titles that are on the Kissmanga website don't show up in tachiyomi's search.

![jhjhn](https://cloud.githubusercontent.com/assets/25474090/22496940/eddc35be-e81b-11e6-8af2-4b2293b61102.PNG)
![screenshot_2017-02-01-01-12-28-1](https://cloud.githubusercontent.com/assets/25474090/22496978/2d71ccfc-e81c-11e6-96e0-f195f24202ed.png)

Version: v0.4.2
Android Version: 6.0.1

**Comment by cylonu87** [comment]
Your first screenshot is from "http://www.kissmanga.io", not from "http://kissmanga.com"

**Comment by inorichi** [comment]
Closing since it's working as expected.
