### ISSUE TITLE
Image file extension

### ISSUE THREAD

**Issue by paronos** [inorichi/tachiyomi#669]
Not really an issue, but something I noticed while seeing the last commit:
- `DiskUtil.kt:43`. "image/jpg" is probably a non standard mime type.
- `Downloader.kt:408`. `MimeTypeMap.getSingleton().getExtensionFromMimeType(mime)` does not seem to support it: with `mime="image/jpg"` it returns `null`, with `mime="image/jpeg"` it returns `jpeg`.

Since the default extension is `.jpg` there are no problems (besides that sometime the less common extension `.jpeg` is used instead of `.jpg`).

**Comment by inorichi** [comment]
Hm, right.

So, can we just do this? 
```kotlin
else if (bytes[0] == 0xFF.toByte() && bytes[1] == 0xD8.toByte() && bytes[2] == 0xFF.toByte()) {
    return "image/jpeg"
}
``` 

Or should we also check the fourth byte:

```kotlin
&& (bytes[3] == 0xE0 || bytes[3] == 0xE1 || bytes[3] == 0xEE)
```

**Comment by paronos** [comment]
Checking the fourth byte is probably enough, but I really don't know why bytes 7 to 11 are also checked (when the fourth byte is 0xE1). If this further check is removed the the ByteArray can be of size 8 (instead of 11).

If we do want to to avoid `.jpeg` files we can also do (in `Downloader.kt`) something like
```kotlin
val ext = MimeTypeMap.getSingleton().getExtensionFromMimeType(mime)
return if(ext == null || ext == "jpeg") "jpg" else ext
```

**Comment by inorichi** [comment]
Added a commit where I've omitted the fourth byte since it doesn't have to always be `0xE0` or `0xE1`.

I used as reference [this](http://stackoverflow.com/a/23360709/3263582):

> Making sure the next byte is 0xFF is of course an extra precaution, to filter out false positives.

And [this](http://stackoverflow.com/questions/5413022/is-the-2nd-and-3rd-byte-of-a-jpeg-image-always-the-app0-or-app1-marker).

Since this method will be barely used, I believe we don't need to be very exhaustive and it's fine like this.

What do you think?

**Comment by paronos** [comment]
From what I read from the links it seems that even jpeg without the third byte = 0xFF are possible (created by some cameras). If false positives are not a great problem the check could even be limited to the first two bytes (and we could also add `image/bmp` - first two byte = "BM").

**Comment by inorichi** [comment]
It should be fine. I doubt it will ever load a bmp. As for the 0xFF, I'll keep it for less false positives.
