### ISSUE TITLE
[REQUEST]Add ReadComicOnline.to

### ISSUE THREAD

**Issue by goldenguy43** [inorichi/tachiyomi#671]
It would be nice if you could add ReadComicOnline which is a site from the same guy as kissmanga that has a large collection of Western Comic Books and the app could also focus on other sites that have comic books that you can read online.

**Comment by inorichi** [comment]
It's available as a [YAML source](https://github.com/inorichi/tachiyomi/wiki/YAML-Sources) (it will be deprecated soon but it works), and catalog requests now belong to [this repository](https://github.com/inorichi/tachiyomi-extensions)
