### ISSUE TITLE
ePUB Support

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#676]
[Currently][0] only zip/cbz is supported in the local catalogue.

ePUB is widely used in DRM-free comics and uses considerably less space than the various pdf/rar/zip formats - so a large portion of my local manga collection is currently in ePUB.

[0]:https://github.com/inorichi/tachiyomi/pull/648

**Comment by inorichi** [comment]
Never worked with epub, but AFAIK it's a zip.

**Comment by wopian** [comment]
It's not a zip, but is an archive format. Its XML based iirc.

**Comment by Arasthel** [comment]
[It's a zip.](http://www.idpf.org/epub/301/spec/epub-overview.html)

Its contents are a spine file which defines the 'book' structure and the chapters, which are usually HTML files. Of course, that HTML can have embedded images. If you want to read epub files you should probably do it using an epub reader. Adding a whole new parser for epub comics is an overkill.

**Comment by wopian** [comment]
>If you want to read epub files you should probably do it using an epub reader

Which wouldn't have tracking functionality.

**Comment by inorichi** [comment]
Well, it should be fairly easy to support by reading the contents of the zip. I don't know how they are structured, so send me some chapter to give it a try.

**Comment by wopian** [comment]
Uploaded 2 samples of each type to slack.

https://tachiyomi.slack.com/files/wopian/F41362ZGA/chapter_1.epub
https://tachiyomi.slack.com/files/wopian/F4135RMNW/chapter_2.epub

**Comment by inorichi** [comment]
It can load epub now, but I'd recommend using a zip/cbz. Parsing the document and all its pages can be slow. I could have just looked for all the images in the directories, but I wasn't sure of the naming scheme (leading to unordered pages).

I've only tried with the first epub provided, it may fail with epubs created with different tools.
