### ISSUE TITLE
Cover image randomly missing in mangafox/mangahere

### ISSUE THREAD

**Issue by devastgh** [inorichi/tachiyomi#679]
As title says, when i click on latest updates on either of those sources, some cover images do not appear. The issue exists on both live 4.2 and dev build as well. Live version is much worse sometimes 10-15 out of 20 manga covers missing. Dev build is better, much less missing covers, but the issue still pesists. If i go into the manga and do a refresh it will load the cover image, and going back it will correctly display it in the latest updates view. It also happens in the Catalogues view.
edit: I can't reproduce this with sources mangasee,kissmanga and readmanga.today.

Version: 4.2 and r1100

**Comment by inorichi** [comment]
It happens when a manga is initialized and they change the url. Using `Settings > Advanced > Clear database` will fix it for non-library manga, and `Settings > Advanced > Refresh library metadata` for manga in your library.

**Comment by devastgh** [comment]
I wasn't aware that non-library manga metadata gets initialized/cached, and as you said: clear database fixed the issue for now.
Thanks.

**Comment by serjflint** [comment]
> It happens when a manga is initialized and they change the url. Using `Settings > Advanced > Clear database` will fix it for non-library manga, and `Settings > Advanced > Refresh library metadata` for manga in your library.

This answer helps with missing covers on Mangadex and supposedly on any source.
