### ISSUE TITLE
Letter Filter Local Manga

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#680]
Just like #665 . Looks like letter `T` is filtered so it's not showing in the chapter list. File name is `Twin Spica 01` but showing only `01` in chapter list.

Version : r1100

**Comment by paronos** [comment]
The manga name (i.e. the parent folder name) is removed from the chapter names.
So, if the file `Twin Spica 01` is in a directory named `Twin Spica`, this is the intended behaviour.

**Comment by inorichi** [comment]
Closing since it's working as expected.
