### ISSUE TITLE
Mark as read when removed

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#681]
There is the opossite setting "remove when marked as read". But most download apps (like podcast ones) use also "mark as read when removed" (they too have delete after played). This way you can filter "show only unread" and it will show downloaded and new episodes to download. The old read / deleted ones will be hidden.

Right now you have to delete them and then manually select them again and mark as read to hide them.

**Comment by 444nonymous** [comment]
Could you please add this feature?

If you use other app to read the mangas or just collect and rar them, "mark as read when removed" makes a lot of sense. The way its now, you have to delete the files and then manually mark as read.

If you have to select tens of chapters is very tedious. On the other hand it makes sense that if you are deleting the chapter is because you have already read it.

It's just an useful option to have.

Thanks

**Comment by NoodleMage** [comment]
> , you have to delete the files and then manually mark as read.
Why not just mark them as read? They will be removed if you do that (if options is enabled). 

If you want to safe some space and remove multiple chapters you had downloaded you don't necessarily read them.

**Comment by 444nonymous** [comment]
Deleting when mark as read does not work for previous chapters. You have to manually select all files and mark as read. The mark as read after deletion makes sense too. Podcast apps have both for a reason.

**Comment by NoodleMage** [comment]
You will still have to select all manga you want to delete and click delete. 

If you mean delete with something like Solid Explorer the app won't keep track of downloaded manga in the database as of now.

**Comment by NoodleMage** [comment]
Closing because not a feature that should be implemented
