### ISSUE TITLE
Deleting categories hides manga until switch from and to library

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#686]

**Comment by jshap70** [comment]
Hi, can you checkout [this guide on submitting issues](https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md) and provide a bit more information? I'm not really sure what "switch from and to library" means

**Comment by j2ghz** [comment]
The one I wrote :D I sent the issue from gitskarios, for some reason the description vanished.

1. Have a library with some manga in a category, some in Default
2. Delete the category
3. There will be only manga from default category, the ones that were in the deleted one are not there
4. Switch to catalogue, latest updates,...
5. Switch back to library
6. All manga will be there

Version: r1105
