### ISSUE TITLE
Problems When Searching for Manga in the MangaSee Catalog

### ISSUE THREAD

**Issue by basilg3** [inorichi/tachiyomi#692]
Though the advanced search options work fine with every other catalog, the MangaSee catalog presents a bit of a strange issue. When the catalog is selected, the manga from the website appear in alphabetical order, but only about 80 or so titles are listed and shown. When one attempts to scroll past these 80 titles, the alphabetical list simply repeats itself, limiting the amount of manga one can select from this catalog.

Attempting to search for a specific manga not in the list has no effect either; the same 80 are shown. Using the advanced search options to select a genre is also ineffective, displaying the same 80 titles regardless of which filter is picked. Opening MangaSee from a browser reveals that everything is in place on the website, meaning there's an issue somewhere in the app.

Can this be fixed? Thank you.

Version: 0.5.0

**Comment by Caera89** [comment]
Aye the search function on Mangasee stopped working maybe a week ago for me too, hope it can be fixed as Mangesee has been the best overall source for the stuff I've read so far.
Great app also btw.

**Comment by BobKaLonger** [comment]
I also have been having this issue for a little over a week. In my case, only 20 series with either a number or a special character as the first character in the title are shown, and loop if you attempt to scroll. Filters or advanced search change nothing. I absolutely adore this app and Mangasee is the source for probably 80-90% of the stuff I read.

On the bright side, if I already have a series saved in my library from Mangasee, I receive updates to those series and can download and view (enjoy) them just fine. So at least I can keep up with my weekly favorites! Hope this helps.

V0.5.0
