### ISSUE TITLE
Nox : Batoto sign in issue

### ISSUE THREAD

**Issue by Mentolik** [inorichi/tachiyomi#695]
Greetings, 

decided to leave a short message about my current issue, since I couldn't find anything about it on google, the known issues, FAQ or the changelog.

My current issue is that I wanted to make a profile save-file over the Android Emulator Nox, on my PC. Reason being that my tablet is rather old and slow. 

In any case, I can't progress - since the "login" button for Batoto doesn't advance after typing in the password. Since it doesn't recognize ENTER as ENTER. For whatever reason. 
Tried to deactivate the hardware keyboard in the settings of the android and even installed the gboard, since it was supposed to help with that issue. Nothing really worked.  

I suppose this is a rather niche issue, still - in case you care. 

Thank you, for your time - and this otherwise great app.

**Comment by inorichi** [comment]
I don't know how Nox works, in fact I just learnt about its existence. Can't you use the mouse to click the login button?

**Comment by inorichi** [comment]
Closing this one.
