### ISSUE TITLE
Scrolling when reading manga gets choppy sometimes

### ISSUE THREAD

**Issue by ruudschouten** [inorichi/tachiyomi#697]
Version: r0.50.0-1113
Android: 7.0
Device: OnePlus3 

First, let me try to explain what I mean with the scrolling getting choppy; when I'm reading and I scroll downwards the scrolling just stops. I can move my finger all I want but nothing happens. When I let go of the screen and slide again it usually works again.

The screen orientation I use is Forced Landscape, and Fit to Width.

I've checked a few versions to see on which version this happens, and so far it happens on the following versions:

0.5.0
0.5.0-1113
0.5.0-1109
0.4.2-1108

On 0.4.2 the scrolling works just fine, and there is no choppiness.

I can add a recording of the scrolling if you'd like. Just let me know.

**Comment by inorichi** [comment]
#231 regression after updating subsampling to 3.6.0. I asked @iBaer if we should try the changes of 3.6.0 before (they were conflicting) but he didn't reply and that's what I did. I'll see if I can restore the old behavior.

**Comment by inorichi** [comment]
The previous version was causing #598. The problem is I don't have a Galaxy S6 or S7 (or any other with a 2K display) to find and test a solution for both.
