### ISSUE TITLE
Batoto External Links Error

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#699]
All the Batoto sources, when used "Open in Browser" for extra info opens up to wrong info link.

Version: r1113

**Comment by inorichi** [comment]
Can you ellaborate? Link it opens, etc

**Comment by bbtora** [comment]
Here are some screencaps

![screenshot_2017-03-06-00-07-35-360_eu kanade tachiyomi debug 01](https://cloud.githubusercontent.com/assets/23010526/23590166/329e0ffc-0201-11e7-9e95-8723bd2d2ef3.png)

![screenshot_2017-03-06-00-07-46-198_com android chrome 01](https://cloud.githubusercontent.com/assets/23010526/23590168/48b211f8-0201-11e7-9519-678c3c6b6ce8.png)

**Comment by wopian** [comment]
What happens when you open it in your browser (⋮ in top right)

**Comment by inorichi** [comment]
It's technically not wrong. That's the url used to initialize the manga metadata, which is used instead of the page because it's a lot faster, but you can click the image and it will open the page you are looking for. Changing this would require an additional method in the source API.

**Comment by bbtora** [comment]
Hmm yeah. Fair enough I guess. Thanks for clearing that up. I thought something was wrong with the link.
