### ISSUE TITLE
Sort by last updated

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#70]
I'd love to see an option to sort your library by what manga was last updated instead of alphabetical order. Maybe even a badge or a banner on manga that were updated but not viewed yet.

**Comment by Bloodwork** [comment]
I too enjoyed this feature in Manga Rock's library (favorites).

**Comment by BlackSynder** [comment]
i personally moved from zingbox but yeah

**Comment by poopybunghole** [comment]
Is there also a way to sort the catalogue screen with new releases?  I like to find new manga that way.  Or just a new releases screen in general?  That's the default main screen in most manga reading sites.

**Comment by inorichi** [comment]
Moving to #374
