### ISSUE TITLE
Category-specific auto download

### ISSUE THREAD

**Issue by sbstratos79** [inorichi/tachiyomi#700]
An option for auto downloading new chapters from user defined categories would be very useful. I have created 3 categories : Reading, Plan to read, and Read. I want Tachiyomi to auto download new chapters of the manga only in the "Reading" category.

Version: v0.5.0

**Comment by ArmandBernard** [comment]
This is actually a great idea. I +1 this.

**Comment by NoodleMage** [comment]
Forgot to upload my local changes from backup pull and had some free time so wrote some code to do this today. Wanted this option myself ;) 
Won't have any time tonight to do last tests so will probably commit tomorrow evening.
