### ISSUE TITLE
Add "Select" and "Inverse select" to chapter browse page

### ISSUE THREAD

**Issue by meelahi** [inorichi/tachiyomi#706]
The three dot button on chapter browse page could have two new options called "Select" and "Inverse select".
![screenshot_2017-03-11-05-57-55](https://cloud.githubusercontent.com/assets/20714252/23822760/650e473a-0621-11e7-915f-6dafae67e6e1.png)

Both options are batch selection of a lot of chapters. 
- "Select" would prompt user to select All/Read/Unread/Recent five etc. 
- "Inverse select" would select all chapter previously not selected and vice-versa.

The options are specially helpful after adding a new manga to library. After selection user can mark chapters read-unread/download selected/delete downloaded chapter.

**Comment by CarlosEsco** [comment]
This already sort of exists if you long press the a chapter, then click 3 dot menu.

You have select all, mark as read and mark as unread.

**Comment by arkon** [comment]
There's already select all / select inverse in dev.
