### ISSUE TITLE
[feature] Double tap: vertical and horizontal adjustment of the image

### ISSUE THREAD

**Issue by LucaMoschella** [inorichi/tachiyomi#707]
Usually, I use the double tap when there is a situation like this (I think this is the most common scenario)

![photo_2017-03-13_20-40-30](https://cloud.githubusercontent.com/assets/11019190/23872202/ae76350a-082d-11e7-87cc-3cd19e32dabb.jpg)

As it is, if I double tap:
![photo_2017-03-13_20-40-39](https://cloud.githubusercontent.com/assets/11019190/23872227/bf5c26e0-082d-11e7-8075-440bee0e71da.jpg)

...In this way I'm totally lost in the page, I have to manually set the zoom.

In my opinion, the double tap should switch between the horizontal and vertical fit of the image.
That is, it should zoom like this:
![photo_2017-03-13_20-40-35](https://cloud.githubusercontent.com/assets/11019190/23872304/058cdd26-082e-11e7-85a8-c781883334da.jpg)

Cutting off from the screen only the black bands, and not portions of the image.

Similar requests;  #476 and #228 
Implementing this feature should be simpler than the configurable double tap.

**Comment by inorichi** [comment]
That's exactly what the "smart fit" does. I didn't implement the double tap zoom, it's from a third party library. Also you have to consider not everybody uses fit to screen so for example double tapping with a fit height would just do nothing.

**Comment by LucaMoschella** [comment]
Sorry, I totally missed that option.

Thanks!

**Comment by Battler624** [comment]
I honestly want a revive of this, I dont enjoy the smart fit or atleast I want the smart fit to engage only on double-tap.
