### ISSUE TITLE
Local manga does not work

### ISSUE THREAD

**Issue by jotumn** [inorichi/tachiyomi#708]
I've put some CBR and CBZ files into /sdcard/Tachiyomi/local/MyManga
And when I select the local manga catalogue, I see the following error message:
"length=48; regionStart=46; regionLength=-34"
and Retry button near it.

Example of a file name: "wildcats v1 002 (1992) 28p [image].cbz" (maybe the square bracket symbols break something)

Version: v0.5.0

**Comment by inorichi** [comment]
Can you get a screenshot with the error? I haven't had any issue with local manga. If you think the square brackets are at fault, try removing them and report back.

**Comment by jotumn** [comment]
All right, after some testing I've isolated the problem. It wasn't because of the file name but because of the file contents. One particular archive contained a folder with JPG files and the folder was named something like "MyComics #1". I did some testing with other files and the problem is with this "#" symbol. Upon tapping this file I get this error:
![111](https://cloud.githubusercontent.com/assets/16961866/24560211/db56e604-1652-11e7-9ab4-71d273a0e556.png)

**Comment by inorichi** [comment]
Ok, thanks. I'll see what I can do.

I requested the screenshot to know where the error actually happens, and that one helps. :)

**Comment by inorichi** [comment]
The error shown in the image is fixed, however zip won't be able to load files containing a '#', but that issue is not in our code, but the `JarURLConnection` (Java) implementation.

If you use plain folders it'll work, and rar probably too.
