### ISSUE TITLE
Webtoon viewer issues

### ISSUE THREAD

**Issue by Bloodwork** [inorichi/tachiyomi#71]
I know that this is still an experimental feature but I consume a rather sizeable amount of webtoons so I'd like to see this feature improved.

The viewer itself is fine for the most part besides these issues:

- [x] 1. Reading in webtoon viewer doesn't correctly update chapter progress 

- [ ] 2. Can't switch chapters by swiping

- [x] 3. Frequently pages are loaded a bit late

- [x] 4. Huge spaces between pages cutting heads and speech bubbles in half (pages should be stiched together)

- [ ] 5. The reader always return to the very first page rather than the page that it was on prior to being closed

- [x] 6.  After rotating from portrait to landscape the chapter goes back to page 1 (changing orientation resets current page)

**Comment by inorichi** [comment]
1. Always scroll to the very bottom, the last image must be at least partially visible.
3. That's an issue of the image library. I think you will have to deal with that for a long time.
4. They are supposed to be together. What's the height of those images?

**Comment by Bloodwork** [comment]
Here are both of the images:

1. http://img.bato.to/comics/2015/05/23/k/read5560e4751c071/img000012.jpg
2. http://img.bato.to/comics/2015/05/23/k/read5560e4751c071/img000013.jpg

They are both 690x2000px

**Comment by wopian** [comment]
The gap doesn't happen on 0.1.2 with the Skia decoder.

http://i.imgur.com/VjYLRQm.jpg

**Comment by Bloodwork** [comment]
The gaps are still there for me no matter which decoder is selected.  I'm also using 0.1.2

![screenshot_2016-02-11-21-48-18](https://cloud.githubusercontent.com/assets/7024084/12562360/69f72878-c3ad-11e5-9917-21b83fa423c9.png)

**Comment by j2ghz** [comment]
r378, the same images of the same manga, Rapid and Skia both look ok

**Comment by inorichi** [comment]
It looks like it's a device related issue.

Anyways, the webtoon reader is using a RecyclerView and I don't know a better alternative that does not require you to write a custom View from scratch. Any help here would be appreciated.

**Comment by Bloodwork** [comment]
Yea, it's device specific. No gaps on my phone.

If it helps anything - the gaps are on my Lenovo Tab S8-50 tablet (Android 5.0 with 1920x1080px screen resolution).

**Comment by Bloodwork** [comment]
Another observation - viewing the same manga in landscape mode makes the gaps even bigger. Something around 1000px between pages.

**Comment by inorichi** [comment]
I made some changes. I need fix confirmation for points 3 and 4.

**Comment by Bloodwork** [comment]
Both point 3 and 4 are fixed in the latest dev build. Gaps are gone and images are loaded in time. Incredible work, inorichi! Thank you.

**Comment by inorichi** [comment]
It's far from perfect, but f19889c "should" avoid crashes

**Comment by Bloodwork** [comment]
Added point 6 from #93

**Comment by inorichi** [comment]
Nothing I can do for the first point. As said before, make sure you are seeing the last page before closing/switching chapter

**Comment by inorichi** [comment]
Point 2 is not needed anymore with the seamless feature.

**Comment by inorichi** [comment]
Closing old issues, create a new one if something is wrong. Point 5 probably won't be supported.
