### ISSUE TITLE
F-Droid builds have been failing since v4.2

### ISSUE THREAD

**Issue by mosterdt** [inorichi/tachiyomi#712]
It seems that the [latest F-Droid builds](https://f-droid.org/wiki/page/eu.kanade.tachiyomi#0.5.0) have been failing starting with version 4.2. Any idea what's going wrong?

**Comment by j2ghz** [comment]
The errors are:
```
> Failed to install the following SDK components:
  [Solver for ConstraintLayout 1.0.0, ConstraintLayout for Android 1.0.0]
  The SDK directory (/home/vagrant/android-sdk) is not writeable,
  please update the directory permissions.

> Failed to install the following SDK components:
  [Solver for ConstraintLayout 1.0.0-beta4, ConstraintLayout for Android 1.0.0-beta4]
  The SDK directory (/home/vagrant/android-sdk) is not writeable,
  please update the directory permissions.
```
I guess that should be reported to the F-Droid team?

**Comment by mosterdt** [comment]
After searching around it looks like this will be solved in the upcoming F-Droid buildserver update.
The merge request that solves the issue: https://gitlab.com/fdroid/fdroidserver/merge_requests/225
Another app with the same problem: https://gitlab.com/fdroid/rfp/issues/69 (see comments at the bottom)

As this is not an issue with tachiyomi itself, I'm closing my issue. Thanks for making this awesome app!
