### ISSUE TITLE
Page list is empty

### ISSUE THREAD

**Issue by shadowviper7Z** [inorichi/tachiyomi#713]
So while using tachiyomi normally on my next chapter i got page list is empty and then i tried a diffrent manga and page list empty i though app gliched so o extied then re tunred and fail, i can read it on the main source so its not that and cleared cookies and such but i can not read previous chapters i read already as well

**Comment by iBaer** [comment]
What source are you using? I get the same error but only on Kissmanga.

**Comment by ramattos** [comment]
I get the same error since today, only on Kissmanga. Reading the manga on their website on my phone works just fine, how ever.

**Comment by shadowviper7Z** [comment]
So far ive tried kissmanga and manga here and bleh mothing, i was reading them just find idk what happend

**Comment by Lionirdeadman** [comment]
https://github.com/inorichi/tachiyomi/commit/3be9881997fe8358d725a651710ae55ec382935e fixes that issue if I'm not wrong, it's just that 5.0 isn't up to date. Please correct me if I'm wrong.

**Comment by lawbarb** [comment]
This is already discussed in issue #696.

**Comment by inorichi** [comment]
Fixed in v0.5.1.
