### ISSUE TITLE
Kissmanga error

### ISSUE THREAD

**Issue by diksm8** [inorichi/tachiyomi#714]
Kissmanga returning "Page list is empty", this manga worked just a couple  of days ago. Worksh other sources.

Version: v0.4.1
Android N

**Comment by diksm8** [comment]
Issue remains with 0.5.1

**Comment by choolastre** [comment]
Settings→Advanced→Clear Chapter Cache.

**Comment by TheWhiteHunter** [comment]
I'm on 0.5.1 and clearing chapter cache did not work. Still getting "page list is empty" for KissManga.

**Comment by GreyAsteroid** [comment]
There are two issues that this could be, if it's the issue that 0.5.1 fixes then clearing chapter cache should fix it, another thing to try that I can personally say works is backing up settings, clearing app data, then restoring settings. 

If it's the issue of KissManga flagging your IP, you need to open kissmanga.com in your browser, load up any chapter and solve a captcha. (On their forums they've said it may help to make an account too). To help prevent this from happening in the future, you can make sure "Simultaneous downloads" is set to 1

**Comment by phieti** [comment]
i have same problem for past few days. Cleaning cache and updating to latest version didnt helped. Gonna try reinstall

**Comment by phieti** [comment]
Yes reinstalling did helped.

**Comment by diksm8** [comment]
Works now, solved itself, thanks for all the help.
