### ISSUE TITLE
Manga info always shows only the first line of manga description

### ISSUE THREAD

**Issue by paronos** [inorichi/tachiyomi#716]
![portrait](https://cloud.githubusercontent.com/assets/23290139/24106121/413a596c-0d87-11e7-812c-816d591a754b.png)
![landscape](https://cloud.githubusercontent.com/assets/23290139/24106141/4b8daf90-0d87-11e7-9bd0-bbc39d8af548.png)

Version: r1124
Android 4.1

**Comment by rachmadaniHaryono** [comment]
can you try it once again with latest version https://github.com/inorichi/tachiyomi/releases/tag/v0.5.1

**Comment by rachmadaniHaryono** [comment]
also confirmed on android 6.0.1, source mangahere

**Comment by inorichi** [comment]
Stupid mistake by copypasting...
