### ISSUE TITLE
Disable ACRA at build time

### ISSUE THREAD

**Issue by psychowood** [inorichi/tachiyomi#717]
Hi,
I'm going to push an sdk15 build in my forked repo and I'd like to disable ACRA (Automatic Crash Reporting) to prevent "fake" reports sent to you (there will be a few :) ), can I add (or provide me indications to do a PR) a flag somewhere to disable error reporting (e.g a buildConfigField in build.gradle)?

Thanks

**Comment by inorichi** [comment]
Sure. You can set the field to false in the dev flavor and add a check in `App.kt`
