### ISSUE TITLE
App not installed 5.1 error

### ISSUE THREAD

**Issue by KettleBlack07** [inorichi/tachiyomi#718]
I am trying to get 5.1 installed and this message keeps popping up. I have tried to uninstall 4.1.0 and install 5.1. Only the one that will install is the one from f-droid.org. I just want to be fix the "page list not found"

**Comment by inorichi** [comment]
What are you using to install the app? Try using a different browser or app. Sometimes one of those can't install other apps with certain permissions.

**Comment by lifeweaver** [comment]
@KettleBlack07  I  had the same problem, I had to uninstall the old version, 0.4.1, before it would install, I had the old version installed via F-Droid.

**Comment by inorichi** [comment]
The latest version is already available in F-Droid.
