### ISSUE TITLE
F-Droid Version Behind

### ISSUE THREAD

**Issue by KazuyDarklight** [inorichi/tachiyomi#720]
While the stable version here on the site is 0.5.1, the F-Droid app shows the latest version as 0.4.1 even after attempting to force an update.

**Comment by j2ghz** [comment]
#712

**Comment by inorichi** [comment]
It'll eventually update. I don't have any control over F-Droid builds, so you will have to wait until they finally support some Google libraries (specifically Constraint Layout).
