### ISSUE TITLE
Page empty error on KissManga catalogue @5.1

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#721]
Hello, 

As of today morning the page empty error that caused a lot of trouble returned. I've tried this on the dev version as well and it results the same. I've included a gif below to show the error in action. Please let me know what relevant information I can provide to resolve this. Thanks

https://giphy.com/gifs/xUPGcdoeMnsiz3IzHq

Version: v5.1
(Android lollipop 5.1)

**Comment by cylonu87** [comment]
If you open kissmanga in a browser, you'll see this message:

KissManga closed to upgrade the servers. It should be done within few hours.

**Comment by ssuperkid5** [comment]
No, your reply is incorrect. Normally when I get this error it is asking to confirm I'm a human with a captcha and I do it through a browser, but I've been having this page empty error specifically for KissManga for the past 2-3 days. I've checked KissManga multiple times, going to a random chapter and it loads properly in-browser, yet it doesn't work on Tachiyomi. I tried dev and stable as well.

**Comment by cylonu87** [comment]
When I wrote my answer, kissmanga was down. It's up now.

**Comment by Syborg49** [comment]
@cylonu87 My bad it's working ok now. Closing the ticket. Thanks
