### ISSUE TITLE
Mark previous read / group selection

### ISSUE THREAD

**Issue by AdvancedNeanderthal** [inorichi/tachiyomi#723]
I know there's the multiselect and inverse selection which is fine for a lot of cases, but say you're at chapter 100 out of 200. In such a case, there's no getting around having to tap on 100 chapters in order to mark them read.

A "mark previous read" option would simply mark all chapters before the selected as read.

or

Group selection could work as it does in several android file managers. For example; long press ch4, long press ch8, now ch4-8 are selected.

Version: 0.5.1

**Comment by wopian** [comment]
"Mark previous as read" already exists. Tap ... in the chapter list

![](https://i.imgur.com/Mi9jpHZl.png)

**Comment by AdvancedNeanderthal** [comment]
Ah! Thanks. I was looking for it in the multi-select screen I guess. X_X
