### ISSUE TITLE
Cutoff Descriptions

### ISSUE THREAD

**Issue by Redalertz** [inorichi/tachiyomi#725]
With the latest update manga descriptions were greatly shortened and then followed by a ... so you are unable to read the whole description.

![5untfz3](https://cloud.githubusercontent.com/assets/26729571/24386489/e939b0ac-133d-11e7-820a-404307dc2dbc.png)

Version: 0.5.1

Verizon 
LGG5
Android 7.0

**Comment by NoodleMage** [comment]
#716

**Comment by Redalertz** [comment]
My apologies I looked to see if this question had been asked. Did not
realize it had been. Anyways, awesome app keep up the good work.
