### ISSUE TITLE
When downloaded, everything goes to gallery.

### ISSUE THREAD

**Issue by PuppyLover101** [inorichi/tachiyomi#726]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

Can we have it stored in the app instead of the gallery? My "collections" in the gallery app is cluttered with it

**Comment by inorichi** [comment]
You have to open `Settings > Downloads` at least once in order to create a `.nomedia` file in the downloads directory.
