### ISSUE TITLE
Page List Empty Error MangaHere

### ISSUE THREAD

**Issue by ahhhno** [inorichi/tachiyomi#729]
Whenever I try to read any popular manga (One Piece, Shokugeki no Soma, etc)on mangahere I get an error saying "page list empty". This has been happening to me for a while now and the manga is readable on mangazone.

Version: 0.5.1
Andriod Marshmallow 6.0.1

**Comment by DarKCroX** [comment]
Try clear cache.
Settings > Advanced > Clear chapter cache

**Comment by metroxx** [comment]
Same error but with every site.
Version: 0.5.1
Android 4.2
Clearing cache didn't work.

**Comment by ahhhno** [comment]
Tried that even uninstalled and reinstalled Ii still have the error

**Comment by metroxx** [comment]
Forgot to add: retrying it 10-20 times helped kinda. With every retry it downloaded another page/chapter.

**Comment by inorichi** [comment]
Did you try reading those directly in the website? If the content is licensed in your country it may not be available to read.

**Comment by inorichi** [comment]
bc9417e
