### ISSUE TITLE
Adding .yml files to Tachiyomi/parsers/(website).yml not working on LineageOS

### ISSUE THREAD

**Issue by chronisaurous** [inorichi/tachiyomi#731]
Hi! I used to use Tachiyomi on my Galaxy S5 running stock OS. The 3 .yml files I found here for comic books worked just fine after I put them in my phones root folder in root/Tachiyomi/parsers/.yml.

But yesterday I flashed LineageOS and now I can't get any additional websites to work. I've tried putting the Tachiyomi file in both root folder and on my SD card, but neither will work. I've uninstalled and tried again 3 times too.

Any help would be appreciated! I was half way through the walking dead :(

Thank you!

**Comment by inorichi** [comment]
I guess you are running Android 6.0 or higher (reading the issue template and providing the requested information would be nice). If so, make sure you give the app disk permissions or it won't be able to read those files.

**Comment by chronisaurous** [comment]
![screenshot_20170402-141855](https://cloud.githubusercontent.com/assets/26843132/24584382/9e777c40-17af-11e7-87af-33eeab52eb11.png)

Hey, thanks for the reply. Sorry, I'm running android 7.1 and the latest version of Tachiyomi. I have attached a screenshot of my permissions, I'm pretty sure I have all the right permissions.

**Comment by inorichi** [comment]
It's another screen with a toggle like in https://inthecheesefactory.com/uploads/source/blog/mpermission/permissionsrevoke.jpg . There should be a single permission "Storage" that must be enabled. You also need to restart the app after enabling it.

The permission is also requested the first time you open any manga.

**Comment by inorichi** [comment]
Did it help?
