### ISSUE TITLE
New sources

### ISSUE THREAD

**Issue by meradoou** [inorichi/tachiyomi#736]
Hello,
Is possible to get new source for French ? Like http://lirescan.net/ or http://lel-scan.com/ ?
Thank you

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md#catalogue-requests

**Comment by NoodleMage** [comment]
new catalog requests must go here: https://github.com/inorichi/tachiyomi-extensions
