### ISSUE TITLE
Manga description displays in one continuous line

### ISSUE THREAD

**Issue by maurus56** [inorichi/tachiyomi#739]
[Bug]
With the new version I'm getting this problem. Reinstalled the app but it's still there.
The issue applies to any manga from all sources.
Don't really know how to contribute, I'll do my best to answer any question you throw.
![screenshot_20170406-162558](https://cloud.githubusercontent.com/assets/20258911/24774257/425f4818-1ae6-11e7-954c-b8708ada3d93.png)

Version: 0.5.1

**Comment by inorichi** [comment]
#716. Yes we're aware and it's already fixed. A new release will come soon.
