### ISSUE TITLE
Broken catalogue covers manga fox and manga here 

### ISSUE THREAD

**Issue by Sinnesfrid** [inorichi/tachiyomi#741]
In the catalogues for mangafox and mangahere so is every cover that I haven't manually updated displayed as broken.

Is there anyway to fix them and make the catalogues function with clear covers again?

Version: r000 or v0.5.1

**Comment by wopian** [comment]
You can refresh the metadata, which should fix your covers.

Settings > Advanced > Refresh library metadata

**Comment by inorichi** [comment]
Or clear database, in the same screen, for non bookmarked manga.

**Comment by Sinnesfrid** [comment]
Thank you
