### ISSUE TITLE
HTTP 422 errors when syncing with Kitsu.io

### ISSUE THREAD

**Issue by bossanovaorca** [inorichi/tachiyomi#743]
Version: v0.5.1

I am getting HTTP 422 errors when trying to sync progress with Kitsu.io. I can edit the titles to point to different (incorrect) manga which will update Kitsu to show that I am reading a new series, but when I try to point to the correct manga title, I will get a 422. Deleting and re-adding a title also results in 422s. Not sure how to troubleshoot this and I can provide more details if needed

edit: I guess I should add this has only started happening since the beginning of this week. Not sure if it's on Kitsu's end at all but I haven't been able to troubleshoot

**Comment by emyarod** [comment]
Was also running into this problem. Thanks for the quick fix @inorichi, looking forward to the next release!

**Comment by matthewdias** [comment]
I'm still seeing this issue on 0.5.2

**Comment by matthewdias** [comment]
Clearing cache fixed it.
