### ISSUE TITLE
New chapter widget?

### ISSUE THREAD

**Issue by roseyhead** [inorichi/tachiyomi#746]
With my anime for example I use Seriesguide which gives me a scrollable widget of all my unwatched episodes with new episodes added to the top as they come out, then I mark them as Watched in the app which removes them from the list. I'd love something similar for manga that lets me see at a glance what chapters I haven't read yet and what chapters have just come out and so on.

**Comment by arkon** [comment]
Seems like too much effort for something that probably wouldn't get much usage, unfortunately.

Widgets were more popular a few years ago, but usage seems to have dropped off over time.
