### ISSUE TITLE
Page list empty

### ISSUE THREAD

**Issue by FTWOblivion** [inorichi/tachiyomi#749]
Basically every source and every manga is coming up as page lost empty

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by wopian** [comment]
Version? (`Settings > About`)

**Comment by FTWOblivion** [comment]
Version: 0.4.2

Thanks for quick reply, sorry for my late reply. I just turned on automatic updates, hopefully that will fix it for me automatically...?

Sent from Tony's Mobile Device


________________________________

**Comment by inorichi** [comment]
Update the app. Click the version in that settings screen to look for a new update. Or wait for the automatic check to trigger (~12 hours IIRC)
