### ISSUE TITLE
Feature request: got few request

### ISSUE THREAD

**Issue by d3l4croix** [inorichi/tachiyomi#75]
I'm not an IT person so forgive me if I'm doing mistake somewhere

List of feature (basically from mangawatcher )
1)  disk space usage information: how much disk space used by a manga title for downloaded chapter

2) backup and restore: function to backup library and restore them after phone reset or change device. Maybe restore downloaded manga chapter from mangawatcher folder to tachiyomi

3) auto update tachiyomi app

4) cloud sync

5) show unread chapter count on page cover in library

6) change book size in library

That's for now. Thanks much for the great app

**Comment by j2ghz** [comment]
1. https://play.google.com/store/apps/details?id=com.google.android.diskusage&hl=en
2. #34 
3. https://github.com/inorichi/tachiyomi/wiki/FAQ
4. Create separate issue for that
5. It is there. Version?
6. Settings > General > Library manga per row

**Comment by d3l4croix** [comment]
Oh ok, for number 5,it didn't appear but after I change library size, then it appear

For disk space, this is what I mean
http://imgur.com/m0nFXl3

Thanks, I will remind myself to read FAQ before opening new thread.

**Comment by j2ghz** [comment]
Close this and make separate issues for 4 and 1 then

**Comment by inorichi** [comment]
1. #27 
4. No cloud. Maybe a file in google drive or dropbox, but it's not going to happen soon.
