### ISSUE TITLE
Any way to only read the chapters that have been filtered?

### ISSUE THREAD

**Issue by Nogooduser** [inorichi/tachiyomi#750]
I couldn't come up with a better title so I'll try and clarify this the best way I can.

This issue came up while I read reading Jojo Part 5 on Tachiyomi. If you look at the [bato.to page](http://bato.to/comic/_/comics/jojos-bizarre-adventure-part-5-vento-aureo-r6270) for this series you'll notice there's 2 releases for each chapter: one that's colorized and one that's black and white.

On the app there's no way to filter releases by group like you can on bato.to so when I finish reading one chapter of one version (in this case I'm reading the colored version) I have to then skip the next chapter(s) until I get to the one I want. 

Now this isn't exactly something that ruins my experience a lot or anything, however it does become really problematic when you're reading manga offline. 

I have all the colored chapters downloaded, but if I have no internet connection, once I finish one chapter the app will tell me there's no next chapter (since there's no internet connection so it can't find the black and white chapter that comes after in the list) and so I'm forced to go back, move up the list to skip the chapters I don't want to see, and press on the next colored chapter.

I figured sorting the list by "downloaded" would fix this issue, however all the filter does is shrink the list itself, it doesn't actually remove the chapters that were filtered out, so in the end the problem persists, and that's what I'm asking to possibly be fixed.

Essentially, when the list turns from [this](https://i.imgur.com/Ks4gPdN.png) into [this](https://i.imgur.com/IifEjNW.png) I want to **only** be reading the chapters I downloaded, I don't want the app to try and load the chapters that were filtered out.

I know this is a very specific thing and that in most cases there's only one release of a manga, but it would be really helpful if the filters worked this way for those situations when that isn't the case and you want to only be reading the version you downloaded.

I hope that was clear enough. Thank you for your attention!

**Comment by inorichi** [comment]
Yeah, I know it's quite annoying.

In the meantime, you can download the chapters and copy them to the local manga folder (instructions in the wiki). Then add the manga to the library as local.

A "simple" fix for this is to prefer downloaded chapters when using sorting by chapter number. When this sorting mode is selected, the app only loads one chapter with the same number, but it does not have any preference of which one to select ATM.

**Comment by Nogooduser** [comment]
Moving the files to a local folder definitely seems like the less cumbersome solution. I didn't actually remember to try and do that.

Hopefully this problem can be fixed at some point in the future.

**Comment by arkon** [comment]
Added in https://github.com/inorichi/tachiyomi/commit/a3b660a2c95e4d6b86cf39fafee62cee9541d711
