### ISSUE TITLE
Choppy vertical scrolling in webtoon mode when scrolling up.

### ISSUE THREAD

**Issue by littlemuyer** [inorichi/tachiyomi#751]
Version: v0.5.1
OS: android 6.01

In webtoon mode, when I try to go up the pages seem to force a jump down for each page I try to go up ( not always but mostly 99% ). This happens for all the mangas I try and only can go up if I scroll up very quickly.

Going down is OK and also the performance is clearly not the issue here (no lag).

Anybody having the same problem ?

I think to remember this started with the version v0.4.0 or v0.4.1

**edit
This is a different problem from the [#697](https://github.com/inorichi/tachiyomi/issues/697)

**Comment by inorichi** [comment]
v0.5.2 improves this a bit, but it still happens when scrolling very fast. I know the reason, but not a solution (yet), it's the loading progress showing/hiding. The views change dimensions and the jumps happen.
