### ISSUE TITLE
Folder named with a '!' disallows manga from working

### ISSUE THREAD

**Issue by XeVile** [inorichi/tachiyomi#752]
Having local manga folder named with a '!' in it such as 'Binbougami Ga!' stops the application from displaying any image. Instead of that a Retry button appears on all pages.

For now renaming the folder to exclude '!' works.

Version: 0.5.1
Android 7.1.1

**Comment by gfieldGG** [comment]
Happens for me only with trailing '!' and '.'
Anywhere else in the name seems fine. 
'#' in file (not folder) name breaks it too

**Comment by ivanershov51** [comment]
@XeVile, @gfieldGG, could you please test this bug again on the latest version of Tachiyomi? I can't reproduce this on v0.7.4+ (commit 515289134ef9d79097f235a3a8b94e81b77615fa), but I remember encountering it in earlier versions.

**Comment by gfieldGG** [comment]
Just tested a folder ending with a '!' using version r1425 and the issue still exists.
Under _Catalogues > Local Manga_ (and when added to the library) the manga in question doesn't have a thumbnail and the pages are just "retry" buttons.

**Comment by inorichi** [comment]
Is this still an issue? It works fine for me with the latest version.
