### ISSUE TITLE
Cant add catalogue for extracomic.com, readcomicbooksonline.net and readcomics.website using yml parsers

### ISSUE THREAD

**Issue by strugler** [inorichi/tachiyomi#754]
I have been using tachiyomi for a while with the readcomics.tv yml parser. The site was taken down and i tried adding two new catalogues using the same method but it doesnt work. It shows the catalogue name but it doesnt pull nay titles or information

Please help!

The first site comicextra.com below is the yml file i created:

id: comicextra
name: comicextra
host: http://www.comicextra.com/
lang: en
client: cloudflare

popular:
    url: http://www.comicextra.com/popular-comic
    manga_css: .manga-box h3 a
    next_url_css: .general-nav :last-child

search:
    url: http://www.comicextra.com/comic-search?key=$query
    manga_css: .manga-box h3 a
    next_url_css: .general-nav :last-child[href]

manga:
    parts:
        info: .manga-details table
    author:
        select: tr:nth-child(5) > td:nth-child(2)
        from: info
    artist:
        select: tr:nth-child(5) > td:nth-child(2)
        from: info
    status:
        select: tr:nth-child(4) > td:nth-child(2)
        from: info
        complete: Completed
        ongoing: Ongoing
        capture: (.*?),
    summary:
        select: .pdesc
    genres:
        select: tr:nth-child(6) > td:nth-child(2)
        from: info
    cover:
        select: .manga-image img

chapters:
    chapter_css: ul.basic-list li
    title: a
    date:
        select: span
        format: M/d/yyy
        day0: [Today, ago]
        day1: [Yesterday]

pages:
    pages_css: '#asset_2 > select > option'
    image_css: '#main_img'

**Comment by strugler** [comment]
for readcomicbooksonline the following is the yml i used:


id: readcomicbooksonline
name: readcomicbooksonline
host: http://readcomicbooksonline.net/
lang: en
client: cloudflare

popular:
    url: http://readcomicbooksonline.net/catalogue
    manga_css: .manga-box h3 a
    next_url_css: .general-nav :last-child


search:
    url: http://readcomicbooksonline.net/search/node/
    manga_css: .manga-box h3 a
    next_url_css: .general-nav :last-child[href]

manga:
    parts:
        info: .manga-details table
    author:
        select: tr:nth-child(5) > td:nth-child(2)
        from: info
    artist:
        select: tr:nth-child(5) > td:nth-child(2)
        from: info
    status:
        select: tr:nth-child(4) > td:nth-child(2)
        from: info
        complete: Completed
        ongoing: Ongoing
        capture: (.*?),
    summary:
        select: .pdesc
    genres:
        select: tr:nth-child(6) > td:nth-child(2)
        from: info
    cover:
        select: .manga-image img

chapters:
    chapter_css: ul.basic-list li
    title: a
    date:
        select: span
        format: M/d/yyy
        day0: [Today, ago]
        day1: [Yesterday]

pages:
    pages_css: '#asset_2 > select > option'
    image_css: '#main_img'

**Comment by strugler** [comment]
As for readcomics.website i dont know how to do it since i cant see the serach and popular urls.

Please help me as i use tachiyomi exclusively for comics.

Thank you very much!

**Comment by j2ghz** [comment]
1. For making yml sources you need working knowledge of HTML, CSS and mainly CSS Selectors

1. yml sources are being replaced by apk sources at https://github.com/inorichi/tachiyomi-extensions, so no one will probably be making yml sources anymore

**Comment by strugler** [comment]
Thank you j2ghz for your reply. I have two questions if you dont mind:

1- Can you help me with at least one of them. I have good html knowledge but basic css. I tried to find a tutorial to follow so that i can create at least one for readcomicbooksonline but no luck. I know its being replaced soon but would you be able to help for a minimal fee?

2- when you say yml being replaced does this means even the ones that are still working now will stop working? 

3- Is writing extensions for new websites as catalogues easier than using yml? what i mean is what is the reason for going the extension way rather that support for yml?

Thank you so much

**Comment by j2ghz** [comment]
1. I don't mind giving you a few tips for free:

Use https://try.jsoup.org/ to test the selectors
Use Chrome DevTools (F12) to inspect the page
e.g.
```yml
popular:
url: http://www.comicextra.com/popular-comic
manga_css: .manga-box h3 a
```
instead of `.manga-box` it should be `.cartoon-box` as seen in https://i.imgur.com/7G9NU34.png

2. If and when support for yml sources will be removed is not known. I meant it as there is an alternative available now, that is superior in every way.
3. You need to know Kotlin (or Java) and spend a little bit of time understanding how sources work in Tachiyomi. The reason is there are sites that were impossible to do using yml, because of minute differences in structure. Now it should be possible to add almost any site.

**Comment by strugler** [comment]
Thank you so much that makes a lot of sense. Im gonna take a crack at it later today and see if i can get it to work. I might bother you again if i get stuck.

**Comment by strugler** [comment]
Ok more trouble. The following is how my yml looks, It freezes tachiyomi as soon as i choose the catalogue. Can you see where things are messed up?  Again thank you very much


id: comicextra
name: comicextra test4
host: http://www.comicextra.com/
lang: en
client: cloudflare

popular:
    url: http://www.comicextra.com/popular-comic
    manga_css: .cartoon-box h3 a
    next_url_css: .general-nav :last-child


search:
    url: http://www.comicextra.com/comic-search?key=$query
    manga_css: .cartoon-box h3 a
    next_url_css: .general-nav :last-child[href]

manga:
    parts:
        info: .main-content

    author:
        select: p:eq(6) a
        from: movie-meta-info
    artist:
        select: p:eq(6) a
        from: movie-meta-info
    status:
        select: p:eq(3) a
        from: movie-meta-info
        complete: Completed
        ongoing: Ongoing
        capture: (.*?),
    summary:
        select: .film-content.content
    genres:
        select: p:eq(7) a
        from: movie-meta-info
    
    cover:
        select: .movie-l-img img

chapters:
    chapter_css: tr:has(td a)
    title: a
    date:
        select: td:eq(1)
        format: M/d/yyy
        day0: [Today, ago]
        day1: [Yesterday]

pages:
    image_regex: lstImages.push\("(.+?)"

**Comment by strugler** [comment]
Can anybody help and tell me what i did wrong there?

Thank you

**Comment by j2ghz** [comment]
Bad: http://i.imgur.com/okl1SUR.png
Good: http://i.imgur.com/a0EHry3.png

**Comment by strugler** [comment]
Ok thanks for that.
Now i can see the list of comics but with no pictures nor images, and whenenever i try to open a comic i get page list empty :(

So i guess my file is way more messed up that i originally thought

**Comment by j2ghz** [comment]
I've shown you how to do it, but I won't do the work for you. If you have any specific problem/question ask away. Page list is empty means that after opening the manga page and loading list of chapters, no chapters were found. Probably wrong selector for chapter. Missing covers means probably wrong cover selector.

**Comment by inorichi** [comment]
I'm closing this issue since YAML is deprecated and new requests must be placed in the extensions repository.
