### ISSUE TITLE
New backup/restore system, more info please.

### ISSUE THREAD

**Issue by choolastre** [inorichi/tachiyomi#756]
Can you please post information about the new backup system introduced in 0.5.2? Are the backup files now stored in the cloud? If so, where? Do we still have the option save them locally? Are the previous backup file .json still working if you use restore option in 0.5.2?

All this questions are related to the new featured in the changelog: "New backup system. Smaller file size but requires a network connection to restore."

Thank you.

**Comment by null-dev** [comment]
The backup files are still stored locally. It's just now, they won't contain the manga information in them (genres, description, author).

When you restore the manga, Tachiyomi needs to fetch this information again. That's why it needs a network connection.

**Comment by Studywolf20** [comment]
Somebody please can tell me how use the new shortcut feature (Round)?????  Thank you

**Comment by null-dev** [comment]
@Studywolf20 If you mean the launcher shortcuts, they only work if your launcher supports them. If you are running anything lower than Android 7.0, your launcher will probably not support them.

If you launcher does support launcher shortcuts however, just press and hold on the Tachiyomi icon and release to show them.

**Comment by inorichi** [comment]
As @null-dev said, they are still stored locally, as always. You can manually save it in some cloud service with the "share" button after the backup is created.

Backups are also backwards compatible. I would have mentioned it if they weren't. But of course you can't restore a backup created with this new implementation (0.5.2) in older versions.

I'll keep the issue open for a few days so that anyone with similar doubts can easily reach this thread.

**Comment by paronos** [comment]
What happens if a manga has been removed from the source (or the source does not exist anymore)? Genres, description and author will be blank but it will still appear in the library with its completed chapters?

**Comment by NoodleMage** [comment]
Every error will be added to the log which can open after the restore.

In case manga information can'tbe retrieved the manga will not be added. 

In case of sites like botato the manga will be added but the chapter can only be fetched / restored after you're logged in.

**Comment by pervertkirito** [comment]
is there a way i can restore backup from 5.2 to 5.0?

on my phone, i run tachiyomi 5.2 and my laptop using tachiyomi 5.0.

I can't use 5.2 on laptop because i can't restore backup, if I try to restore, it will crash.

if you wonder how i run tachiyomi on windows, i use google apps called ARC Welder

**Comment by Thanatos97** [comment]
Can't restore backup.Any type of software needed?
