### ISSUE TITLE
Webtoon viewer after unlocking instead of last page getting 1st page

### ISSUE THREAD

**Issue by Studywolf20** [inorichi/tachiyomi#757]
I read Manga with webtoon viewer and in landscape mode.
I guess there's a bug in webtoon last page retained feature.
While reading if I shut/lock my screen with power button and quickly unlock it there isn't any problem I get the page where I stopped and locked my screen but instead of quickly unlocking my screen if I wait for may be 10/15 sec instead of getting page at which I lock my screen I get the first page of that chapter.

Android :- 7.0
Tachiyomi :- 0.5.2

**Comment by inorichi** [comment]
Page is restored fine after process death on 0.8.0
