### ISSUE TITLE
Yaml parser: how to use the url_replace and url_replacement?

### ISSUE THREAD

**Issue by hlogic** [inorichi/tachiyomi#759]
I am trying to define the scrapping rules for some given sites. And i am facing an issue of having a list of options each pointing to a given page number (and not to a page link) as following:

```
<select>
<option value="1">1</option>
.
<option value="n">n</option>
</select>
```
normally i would go with `pages_css: select option` but in my current case i will need to build the link based on the current page link. i suspect that it has to do with `url_replace:` & `url_replacement:` but i can't figure out how to use/pass them correctly.

The logic i am hoping to accomplish is:
Using current URL, Replace its end with value of each of option value.

Thank you.

**Comment by j2ghz** [comment]
What you are probably looking for is: https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/online/YamlHttpSource.kt#L194
So `replace` is regex and replacement is string that contains `$value` that will be replaced by whatever your select captured.

**Comment by hlogic** [comment]
Thank you @j2ghz but how can incorporate the current URL in that regex?

I tried passing using:
`url_replace: '\d+$'`
`url_replacement: '$value'`
To instruct the App to replace the end of URL numeric end with the value. but no success.

My url looks like `domain.com/comic-info/.../01` where the last numeric part represents the page.

**Comment by inorichi** [comment]
This is what the mangafox implementation had:
```yaml
url_replace: \d+\.html
url_replacement: $value.html
```

Maybe the `$` end of line is causing issues.

Anyways I would avoid writing this with the limited yaml and create an [extension](https://github.com/inorichi/tachiyomi-extensions) instead.

**Comment by hlogic** [comment]
@inorichi the end of the url, doesn't contain the `.html` extension, just the page number.

I would love to use the new extension way, however since i am not a Java developer i am afraid i can't -at least at the moment-.

Using Regex is tricky especially when i can't view the result of the replacement so i can adjust the Regex.
Anyway i will try a different Regex variances may be one will catch, and will get back with the result.

**Comment by j2ghz** [comment]
`domain.com/comic-info/comic1/chapter1/01` this is the url of the first page I presume
`domain.com/comic-info/comic1/chapter1/` so this would be where the manga info and page list is
Does this work? http://www.regexr.com/3fp76

**Comment by inorichi** [comment]
Closing this. Feel free to request your catalogue in the extensions repository.
