### ISSUE TITLE
Warn about missing sources

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#762]
Extension sources make it easy to add and remove sources. When you remove a source now, any manga you have from the source will not be shown until you add it again.
It would be good to show a warning which manga are affected and which sources are missing.

Enhancement:
* Instead of a warning show dialog that can be used to delete the affected manga or "Remind me later"

**Comment by inorichi** [comment]
For the record, if a source is missing, we can't tell which one is. We only know the id, a 64 bits number not useful for the user.

So this can only act as a way to tell the user he needs to install more sources.

**Comment by j2ghz** [comment]
Is the id not a string? Or are you hashing the id?

But still, such warning is better than nothing.

**Comment by null-dev** [comment]
The I'd is a long.

**Comment by j2ghz** [comment]
With #1101 and https://github.com/inorichi/tachiyomi/issues/1151#issuecomment-355854003 this should be changed. New proposal:
When a manga's extension does not exist, as much info as possible should be shown, the rest replaced by warnings. Not sure what the design limitations on this are.

**Comment by inorichi** [comment]
Closing since manga is not hidden anymore.

On 1.x we could create another index (always keeping the history) to map source ids to names. It'd be hard to script it on the current version because the source api requires tachiyomi to run.
