### ISSUE TITLE
Sort by popularity not working

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#763]
Selecting "Catalogues" shows mangas sorted by popularity by default.

The moment you select a genre or do a search, mangas are sorted alphabetically. This way it's much harder to find good manga by genre.

IE: Seinen in Kissmanga
It shows -> http://kissmanga.com/Genre/Seinen
But it's better -> http://kissmanga.com/Genre/Seinen/MostPopular

You could also create a "sort by" option if you want to. In Kissmanga you have "Sort by alphabet| Sort by popularity | Latest update | New manga". You could update or replace the "Latest updates" option wih an "advanced search" option. Maybe leaving the "catalogue" tab with only genre selection sorted by popularity by default. (just an idea, you will find a better solution) ;)

IE: Seinen in Kissmanga
Alpahbet -> http://kissmanga.com/Genre/Seinen
Popularity -> http://kissmanga.com/Genre/Seinen/MostPopular
Latest update -> http://kissmanga.com/Genre/Seinen/LatestUpdate
New manga -> http://kissmanga.com/Genre/Seinen/Newest

Thanks.

**Comment by inorichi** [comment]
It's a limitation of Kissmanga, [this](http://kissmanga.com/AdvanceSearch) is the form we use to search and filter. As you can see, there's no way to sort results.

The links you provided only allow to select one genre and no query at all.

Unless there's a hidden option to filter the results, it's not possible.

**Comment by 444nonymous** [comment]
I did not know about that limitation in advanced search. Is it a limitation for listing individual genres too?
(could you use http://kissmanga.com/Genre/Seinen/MostPopular instead using AdvanceSearch)

Even if it only works for individual genre selections, the default display should be "by Popularity" and not "by alphabet", like it works by default when no genre is selected.

Thanks.

**Comment by arkon** [comment]
Extension-specific issue.
