### ISSUE TITLE
Chapter number messed up

### ISSUE THREAD

**Issue by AiEsper** [inorichi/tachiyomi#765]
Instead of showing the last chapter, it shows the total of all chapters, so the manga that has a special chapter is also counted . So manga like arifureta, is counted has 13 chapter and it only has 11 chapter
~sorry bad english

**Comment by inorichi** [comment]
It was designed like that. Trusting the recognized number can lead to wrong results, but it's possible.

We can find the max chapter number and if it's below 0 we fallback to the chapter count.
Or in code `chapters.maxBy { it.chapter_number }.takeIf { it > 0 } ?: chapters.size`

 What do you guys think?

**Comment by j2ghz** [comment]
> It's a good idea to show number of last chapter, but having a fallback takes it all away, because then you can't be sure which value the number represents. I guess the aim is to be able to decide which source to take manga from without opening it, then you probably want the one with latest chapter, but if the number could represent number of chapters or last chapter number, it doesn't tell you anything.
>1. Show last chapter number, if not available show `/`,`-1` or nothing
>1. Show last chapter number, if not available show number of chapters, but differentiated by e.g. changing background color
>1. Show last chapter number and number of chapter, like `13/11`, `13:11`
>I guess 2 is not really intuitive.

... is what I wrote then I realized we are talking about library, not catalogue, since catalogue doesn't show chapter counts. Library show number of unread chapters and I think that should definitely be kept as-is. I don't see any reason I'd want to know last chapter number when looking at library. Number of unread chapters is much more important information.

**Comment by inorichi** [comment]
I'm talking about the "chapters" count shown in the info tab of manga.

**Comment by j2ghz** [comment]
Oh, I see. Then your solution is good. Maybe make the label `Last chapter` then.

**Comment by AiEsper** [comment]
Yeah, please make the Last Chapter thibg
FYI many manga app fail in this, if the lastest chapter isnt a number(ex. 46 SPECIAL 1) it will show 1.0(ZingBox) or 0(BuluManga)
