### ISSUE TITLE
New backup system doesn't store status of synched manga

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#767]
What I mean is, if I restore the backup file to a completely new tachiyomi it won't restore the status of manga with the synced service. For example if I restore the manga "prison school" KissManga catalogue, it'll show how many chapters I've read but won't show the status is in like "competed, reading"

Version: r1144
Android 7.1.1 (Logcat can be provided)

**Comment by NoodleMage** [comment]
You have to refresh the sync manually. The backup only restores the sync id information.

**Comment by inorichi** [comment]
We should save them (I thought they were). When the reader syncs the progress it will unset the score and reset the status. We can't have that.

**Comment by Syborg49** [comment]
Closed as of commit #8df3080

**Comment by inorichi** [comment]
That commit doesn't fix this issue.

**Comment by Syborg49** [comment]
Oh ok, one thing though, the bookmarks aren't saved either. So if you could do that while doing this that'd be much appreciated.
