### ISSUE TITLE
Crash when trying to restore backup. *update: can't save backup

### ISSUE THREAD

**Issue by pervertkirito** [inorichi/tachiyomi#768]
I can't restore my backup.
logcat: https://pastebin.com/VHN0PQ91

Tachiyomi v0.5.0 work without any problem.

Version: Tachiyomi v0.5.2
App Runtime for Chrome (Beta) 54.5021.629.0

**Comment by inorichi** [comment]
8df3080 introduces a change that could fix this issue. It's available in the dev channel, can you confirm if it works?

**Comment by pervertkirito** [comment]
Tachiyomi 0.5.2-1147 work great 👍 
Thanks!

**Comment by pervertkirito** [comment]
Oh no, new problem!
In v0.5.2-1147, when I click "Create backup", it suppose to "save as" window not "open" window

![new](https://cloud.githubusercontent.com/assets/27921916/25408803/d978b5bc-2a41-11e7-94a5-d121411c0e08.png)
![old](https://cloud.githubusercontent.com/assets/27921916/25408804/d97ccabc-2a41-11e7-885a-b86968f5aecb.png)

**Comment by inorichi** [comment]
Not sure why that happened, but we were using `ACTION_CREATE_DOCUMENT` which is clearly an action to create a file, not open one. It might be something else missing (not that I'm aware of), but it looks like a wrong implementation of ARC Welder. Anyways I've upgraded the system document creation to Lollipop (ARC seems to use Kit Kat), so it may work now.

**Comment by pervertkirito** [comment]
using version r1158 right now, and nothing change.
I use Tachiyomi on desktop just for download new chapter and transfer to my phone...
Thanks anyway.

**Comment by pervertkirito** [comment]
just found out last working was r1131
no longer work after pull #650

**Comment by pervertkirito** [comment]
this logcat from before new backup update
[logcat from 0.5.1-r1131](https://pastebin.com/bg8EnPrR)
