### ISSUE TITLE
'HTTP error 400' when trying to add a specific manga to MAL

### ISSUE THREAD

**Issue by Akeboshiwind** [inorichi/tachiyomi#771]
Steps to reproduce:
1. Add 'Dusk Howler' to Library (Note: I've tried with all the English sources)
2. Go to tracking tab in manga
3. Click 'Edit' on the MAL card
4. Select 'Dusk Howler' from the list
5. See error 'HTTP error 400' in toast message

I can't seem to find it on [MAL](https://myanimelist.net/manga.php?letter=D&show=1600), but it could just be under another name (not that I can find another English alphabet name).
Even so, it probably shouldn't be showing up in the list in the app.

Version: v0.5.2

**Comment by inorichi** [comment]
https://github.com/inorichi/tachiyomi/issues/659

**Comment by Akeboshiwind** [comment]
Ahh, I see. Interesting issue.
I'll close this then.
