### ISSUE TITLE
Add more YAML sources

### ISSUE THREAD

**Issue by vilaroo** [inorichi/tachiyomi#772]
Can you add sources YAML for:
http://www.comicextra.com/ ?

First time using github, sorry if i posted in the wrong place

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md#catalogue-requests

**Comment by inorichi** [comment]
YAML is deprecated. I'll edit the wiki now.
