### ISSUE TITLE
Backup/Restore progress UI doesn't get updated with the actual progess of a backup/restore procedure

### ISSUE THREAD

**Issue by nurupo** [inorichi/tachiyomi#781]
After selecting "Create backup" and specifying where to store it, the "<spinning wheel> Creating backup" doesn't seem to go away. I have been waiting for 6 minutes now for it to create a backup.

Anyway, I'm about to factory reset my device, so I really need to make a backup of Tachiyomi. Any way I can make a backup?

Version: v5.2.0
Android 6.0.1

**Comment by NoodleMage** [comment]
Could you check if the file isn't already stored in the folder you selected?

Also could you give me your logcat / enable crash report?(in the case of crash report I would like to know your device type as well).

**Comment by nurupo** [comment]
There are already backup files in that directory, but they have different file names. The default backup file name includes date and time with the precision to the minute.

I have factory reset my device already, so I will see if I still can reproduce this again.

**Comment by nurupo** [comment]
The backups that never completed did create backup files. Just tried using these backup files to restore -- restoring is always at 0%, 0/100. Tried using a successfully completed backup from March -- also stuck at 0%, 0/100.

The March's backup was made using v5.0.0, so I will downgrade Tachiyomi to that version, try to restore from the backup and then update back to v5.2.0.

**Comment by nurupo** [comment]
Oh, nevermind. Apparently despite it saying 0%, 0/100, v5.2.0 did restore from the March's backup. It also has successfully restored off the never completed backup I took today. I just canceled the restoration, navigated into the library and everything is there. I guess the actual issue here is that backup and restoration progress bar UI is not being updated with the actual progress of backup and restoration process.

**Comment by nurupo** [comment]
I just noticed that the restored library is once item short. I had two "One-punch man" mangas, from different sources, but it has restored only one of them.

**Comment by NoodleMage** [comment]
Did you check the log?. This can happen because the source of one of the manga is no longer supported. 

The UI should update even for older backups, but it was probably fixed in 8df3080, which is not yet implemented in v0.5.2. Or does it still not work on dev version?

**Comment by nurupo** [comment]
>The UI should update even for older backups, but it was probably fixed in 8df3080, which is not yet implemented in v0.5.2. Or does it still not work on dev version?

Installed the dev version, added a single manga, tried to create a backup -- "<circle> Creating backup" UI doesn't seem to ever go away, had to close the app.

After closing the app, I see that the backup file was created and the contents of the file look okay to me, it seems to be a valid json and lists the manga and the read chapters.

Opened dev Tachiyomi again, removed the manga from the library, and tried to restore from the backup -- the restoration progress UI never quits, sitting at 0% and 0/100. Pressed "STOP", navigated back into the library and saw the manga from the backup appearing there.

So yeah, it's still reproducible.

>Did you check the log? This can happen because the source of one of the manga is no longer supported.

Sorry, no idea how to check the log. Can't use `adb` since I don't have Android SDK installed, and the numerous logcat programs from Play Store won't work because Android doesn't allow applications reading other applications' logs starting Jelly Bean and my device is not rooted.

**Comment by nurupo** [comment]
I just found something. The progress UI for the backup restoration procedure, which always displayed 0% and 0/100 for me, starts displaying the actual progress if you re-initialize the activity, e.g. if you press the Home android button to get Tachiyomi off screen and then go back to the Tachiyomi. Same trick doesn't work with the backup creating progress UI.

**Comment by NoodleMage** [comment]
Thank you for the extensive review. 

The log is created during restore and shown after restore completion. Which you obviously don't get (stupid on my part). Will maybe add an option to view restore log from settings or something like that. 

@inorichi is rewriting the preference and UI (see branches) so maybe we're lucky and it's fixed after these are merged. If not I will try to fix it.

**Comment by inorichi** [comment]
The log must be  available in `{main_storage}/Android/data/eu.kanade.tachiyomi/cache`. Add `.debug` to the package name if you are using the dev build.

With conductor it should be easier to synchronize the backup progress with the UI. I already rewrote everything there except the backup, will get to it soon.

**Comment by nurupo** [comment]
Just repeated the procedure in dev Tachiyomi: add manga, create backup, delete manga, restore from backup -- no restoration log.

However, I have restoration log from when I restored my actual library from a backup in the stable Tachiyomi:

>[2017-05-06 15:16:57.486] Onepunch-Man - HTTP error 404

which makes sense, as the manga seems to have been removed from that particular catalog.

**Comment by inorichi** [comment]
It should be fixed in master. The local broadcast was registered in `onStart` and unregistered in `onPause` (I don't know how this happened). The dialog could pause the fragment and no more events were received.
