### ISSUE TITLE
Error while downloading chapters without an error message

### ISSUE THREAD

**Issue by reconman** [inorichi/tachiyomi#782]
I use the autodownload feature to download new chapters. In most cases I will see a notification saying something like "Downloading 18/19" which does not change.

When you click on the notification it will show the download manager with a play button to resume the download and no error message. When you go to the chapter overview for the Manga it will just display "Error" as status. (instead of Queued, Downloading, Downloaded, ...).

Normally you can see error messages in the downloading notification but in this case the only error you can see is in the chapter list in the chapter status field.

To fully download the chapter after the error happened you need to resume the download in the download manager once or in most cases twice.

It would be nice to fix the error stopping the download but to do that the error message must be shown anywhere.

Is there some kind of log in the file system where I could find out why the download stops?

Version: r1145
Android 6.0

**Comment by blureshadow** [comment]
I have this too

**Comment by blureshadow** [comment]
It's error 503. I get that notification. Source being mangafox

**Comment by levintruenoae86** [comment]
I have this same issue, but with MangaHere....from what I've been reading, it's a discrepancy between page index and actual pages.  This issue has been present for the last four revisions, and seems to be due to URL changes on MangaHere and MangaFox.

**Comment by CarlosEsco** [comment]
closing as this is dated
