### ISSUE TITLE
Kitsu 400 error

### ISSUE THREAD

**Issue by matthewdias** [inorichi/tachiyomi#783]
Trying to load library entries yields a 400. I'm pretty sure this is because the max page limit for library entries was recently set to 500, and the app is asking for 10000.

**Comment by matthewdias** [comment]
Really only need a limit of 1 since because we're filtering by id there should only be 1 result.

**Comment by wopian** [comment]
Tbh, doesn't need to explicitly state the limit here in the first place - since it'll never be more than 1

**Comment by inorichi** [comment]
Limit removed in 89b293f
