### ISSUE TITLE
Feature request: option to manually set manga covers

### ISSUE THREAD

**Issue by PorchettaMan** [inorichi/tachiyomi#79]
With the exception of Batoto, the various manga sources often use wrong or very low quality covers. It's a purely aesthetic thing, but it would be nice to have an option to manually select manga covers from local storage, like MangaWatcher allows to.

**Comment by Bloodwork** [comment]
I noticed this too. Kissmanga has terrible covers even though it's the next best HQ source after Bato.to.

**Comment by NoodleMage** [comment]
http://mcd.iosphe.re/. Maybe we can look at this API.Even if it looks a bit outdated for some manga :).

**Comment by inorichi** [comment]
I forgot to close this. It's already available.
