### ISSUE TITLE
[Feature request] additional sort option, and auto-update

### ISSUE THREAD

**Issue by eji30** [inorichi/tachiyomi#793]
1. Sort by total chapters in my library - this would be helpful in planning to read completed manga. For example, I would first want to read a manga that is the shortest among my list, then the next, and so on. For short lists, the text (unread chapters) above the manga is helpful, but it won't be if I happen to have a very long list in the future.

2. Auto-update - right now I update Tachiyomi through F-droid. In my opinion, apps that are not found in play store should have the auto-update feature as a standard. Some apps found in the play store also have this like Facebook, Instagram, etc. Would be great if my favorite manga app has this too. Thanks!
![screenshot_20170514-073503](https://cloud.githubusercontent.com/assets/17059824/26030050/df99a8e4-3878-11e7-860c-d79b44432382.png)

Version: v0.5.2

**Comment by j2ghz** [comment]
Two separate issues should be split into tow separate issues.

2. Auto-update is already included, but is disabled in F-Droid versions.

**Comment by eji30** [comment]
I'm sorry but if I may ask, where can I download a non-F-Droid version?

**Comment by j2ghz** [comment]
![](http://i.imgur.com/NS7FS8Q.png)
https://github.com/inorichi/tachiyomi/releases

**Comment by Syborg49** [comment]
Just wanted to piggyback on this thread, is there any way to update the lastest dev build without installing fdroid?

**Comment by eji30** [comment]
Oh I'm very sorry, that's because of the unfamiliarity of GitHub. Thanks very much!!
Now my only issue left is #1.

**Comment by j2ghz** [comment]
@eji30 Leave this issue as auto update, and make a new issue for the sort
@Syborg49 Update? Yes. Auto-update? No.

**Comment by Syborg49** [comment]
Thanks @j2ghz. Hopefully sometime in the future.

**Comment by eji30** [comment]
@j2ghz  Done, link is now in [https://github.com/inorichi/tachiyomi/issues/796](url). Thanks again!
