### ISSUE TITLE
download ahead

### ISSUE THREAD

**Issue by m-vlad** [inorichi/tachiyomi#794]
It would be nice to have a download ahead setting so if you want to read a manga that has lots of chapters you don't have to manually download chapters. You could set it to download 10 chapters ahead.

**Comment by masgritz** [comment]
Tachiyomi already had this feature implemented for a while. Just go to the series you want to download and click the three dots menu on the top right (next to the series name, not the chapter name), then select download - out of the options available, "Download next 10 chapters" is one of them.

**Comment by blureshadow** [comment]
Not what I meant. That's a download feature, quit I'm talking about is a download ahead. Automated.

**Comment by masgritz** [comment]
Oh, my bad. I was under  the impression that the "Download next 10 chapters" feature would download ahead the next 10 releases, instead of the 10 previous releases.

**Comment by masgritz** [comment]
OK, now I found the feature you need. Go to Settings > Downloads, then select "Download new chapters". It automatically downloads every new release for the series in your Favorites list. Hope it helps!

**Comment by arkon** [comment]
Closing this in favour of #2367
