### ISSUE TITLE
Crash when update tracking for Anilist

### ISSUE THREAD

**Issue by DarKCroX** [inorichi/tachiyomi#797]
I read manga offline. 
Only update tracking when I have internet access.

updating Kitsu I get "Unknown status"
crash for Anilist

[Logcat here](https://pastebin.com/qbxi7NCG)

Version: r1156
OS: Android 5.1.1

**Comment by inorichi** [comment]
Have you by chance restored a backup with the new system?

**Comment by DarKCroX** [comment]
what do you mean by the new system?
my library backup from v0.5.2 to dev build r1156

**Comment by inorichi** [comment]
I meant the new implementation of backups. Can you pull down the screen in the tracking tab? It will update the local data with the latest from Anilist.

**Comment by DarKCroX** [comment]
It's working, thanks.
but do i have to do this 1 by 1 with every titles?

**Comment by inorichi** [comment]
I'll soon add an option to mass update them and include the status and score fields in the backup (issue #767). Until then, you'll need to do it one by one.

**Comment by inorichi** [comment]
Implemented in 67678cd
