### ISSUE TITLE
Direct URL import?

### ISSUE THREAD

**Issue by null-dev** [inorichi/tachiyomi#799]
Possibly we could add direct URL import for sources?

A possible method of doing this:
1. Loop through all sources checking if the link starts with a source's `baseUrl`.
2. If it does, strip off the `baseUrl` from the link.
3. Create a new manga and set it's url to the new link.
4. Check if a manga already exists in the library with this url and source.
5. Call `fetchMangaDetails` and `fetchChapterList` to get the manga metadata/chapters.
6. Ensure that at least the `title` field is filled out after doing this. If no exceptions were thrown, and the `title` field is not blank/null, the link was successfully imported!

**Comment by inorichi** [comment]
I would prefer an activity on each extension that handles the URL and redirects it to Tachiyomi, so you can easily go from the browser to Tachiyomi. I'm not sure how it should be handled if the site is multi language though.

**Comment by inorichi** [comment]
This won't be needed on 1.x, because extensions can define deeplinks that can be redirected to tachiyomi.
