### ISSUE TITLE
App bar transition issues

### ISSUE THREAD

**Issue by GreyAsteroid** [inorichi/tachiyomi#801]
The animation used for expanded app bar transitions is not present in the library. 

Steps to reproduce:

- Add a manga to your library with only the default category
- Select the manga
- See the lack of animation for the app bar transition

One weird quirk is that when going back to your library from the manga view you sometimes don't even trigger the transition leaving you with the expanded app bar and only the default category. 

![screenshot_20170517-165052](https://cloud.githubusercontent.com/assets/4615298/26178188/84786840-3b22-11e7-853d-a349b6e83987.png)

Another weird quirk shows up when you have a lot of manga added to the library. 

![screenshot_20170517-163333](https://cloud.githubusercontent.com/assets/4615298/26178384/6265984e-3b23-11e7-9ebf-5d7d2014942f.png)

After opening the app an empty library with the expanded app bar will show up for about half a second before the app bar makes the animation-less transition and all the manga show up.

Another thing to note is that after making the animation-less transition if you go to the catalogue (where the animation works) the first manga you select will not trigger the entire transition.

![screenshot_20170517-171452](https://cloud.githubusercontent.com/assets/4615298/26178592/7bbe62e8-3b24-11e7-8a4c-ec9ea77b0af4.png)

Similarly, if you go to the catalogue and select a manga (which normally triggers the transition and the animation correctly) then go to your library, the first manga you select will properly transition with the animation.

Version: r1161
OS: Lineage 14.1 Android 7.1.2

**Comment by inorichi** [comment]
I don't know how to fix this (yet). I may have to leave the tabs always visible when there's only one category. Both the activity and the library controller are configuring the visibility of the tabs and they are clashing with each other.

**Comment by inorichi** [comment]
It should work fine now. I hope there are no more side effects.
