### ISSUE TITLE
Sync after reading doesn't update tracking tab

### ISSUE THREAD

**Issue by wopian** [inorichi/tachiyomi#803]
Currently when `sync after reading` is enabled the following behaviour happens:

1. Read chapter 10
2. Exit chapter (Tachiyomi updates trackers to ch 10)
3. Swipe to tracking tab (displays ch 9)
4. Change rating (Tachiyomi sets tracker back to ch 9)

1155 on 6.0.1

**Comment by inorichi** [comment]
It's working fine here. Whenever the tracker is updated, the database stores the new changes, and when the database is updated, the tracking tab is automatically refreshed.

The only case issue I can think of is that the database throws an exception and then the tab isn't updated, but that's very unlikely 😓

**Comment by inorichi** [comment]
Does this still happen? Are you totally sure Tachiyomi is updating the tracker to ch 10?

**Comment by wopian** [comment]
Ah yeah, it doesn't update until it's received a response, so if it takes a while (for whatever reason - like poor 3G) it will still show the previous chapter. After some time it'll change to the updated value.


So can be closed as a non-issue, or an icon next to the chapter number to indicate it's still syncing.

**Comment by IamHeinous** [comment]
Please put a button to manually update/sync MAL AND other tracking services

**Comment by CarlosEsco** [comment]
closing this as non issue for now since its so old
