### ISSUE TITLE
Backup problem

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#806]
Version: r1164

I think its not an issue of tachiyomi, but just wanna ask if someone was able to run it on some kind android emulator.

I can run it on nox, memu, virtual box android, remix os etc.. but all of these have one common problem. Backup cant be done. Every single time when I wanna backup, it tells me that "Couldnt create backup file".

Second  problem is with tracking.. that gives me Error 400, every single time.. even if the manga is found (it gives that error every single time, when I select found manga name)

Both of these works fine on my phone, so its only problem on emulators.. I know you dont have time etc to solving these thing, but just wanted to ask, if someone have a clue, why these thing doesnt work on emulators.

Have like 700 mangas with read progress in xml file and I wanna add it to tachiyomi on PC, and then backup it for my tablet cause on phone/tablet it will be more painfull. 

Thanks for any suggestions and sry for bad english

**Comment by j2ghz** [comment]
I haven't tried it, but:
@pervertkirito: https://github.com/inorichi/tachiyomi/issues/804#issuecomment-302870969
@null-dev: https://github.com/TachiWeb

**Comment by Sparh4wk** [comment]
thanks for info, but already tryed that ...
first solution arc welder, when backup is pressed it want to open so *.ai file.
second solution seems to have different json format and missing new catalogues..

btw, thanks for great work on this manga reader, its superb :)
