### ISSUE TITLE
Status bar not hiding. 

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#81]
http://i.imgur.com/uIsgvNv.png.

**Comment by inorichi** [comment]
I can't reproduce. Does it hide if you open the menu and reenable the option?

**Comment by j2ghz** [comment]
It sometimes happens to me after I switch to another resource demanding app for a longer time, then switch back
I thought it was because of Xposed statusbar modifcations, but maybe it isn't?

**Comment by ivocarvalho** [comment]
This happens to me too from time to time. Can't really find a pattern.
When that happens e get out to the manga library and open it again and the status bar will be hidden.

**Comment by Syborg49** [comment]
Logcat. 

https://drive.google.com/file/d/0B59RgF7gPCFkMWp5Yl9PYXU3UG8/view?usp=docslist_api

**Comment by inorichi** [comment]
Reopen this if it's not fixed, but it should be.

**Comment by Syborg49** [comment]
On latest debug, status bar still not hiding, 

Logcat: https://drive.google.com/file/d/0B59RgF7gPCFkRjJWeTJacEVJN2s/view?usp=docslist_api

**Comment by inorichi** [comment]
I see. Both reports warn about a memory leak I have to fix. That should be the root cause.

**Comment by shogunreaper** [comment]
happening to me too.

it goes away when i first open the chapter, but after touching the screen at all it comes back on.

**Comment by inorichi** [comment]
Did this happen recently? I made some changes while rewriting the reader in Kotlin. It may be fixed now.

**Comment by Syborg49** [comment]
Issue fixed, thanks inorichi
