### ISSUE TITLE
MAL search by name problem

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#810]
Version: r1171

Hi, Im adding my 700+ database to tachiyomi, and when its possible Im adding MAL tracking as well.. but I have problem with adding mangas like "Days" cause there is a lot of mangas on MAL that includes a word Days, yet the one Im looking for its not listed in results. is it possible to add search by manga ID on MAL or something which can help us found the right manga?

second problem is with mangas like Mahou Tsukai no Yome, if I searching on MAL website, its ok, but in tachiyomi, its not found unless I fix it to Mahoutsukai no Yome.

**Comment by Akeboshiwind** [comment]
It might be interesting to sort the results by [likeness](https://en.wikipedia.org/wiki/String_metric) to the search string.

**Comment by inorichi** [comment]
From the FAQ:

Q: I can't find a manga in MAL's search results.
A: You can search a manga from your MAL list like this: my: <manga>.


Sorting results won't help because the limitation/issue is on MAL search engine.

**Comment by Sparh4wk** [comment]
@inorichi is there a way to do something like this with anilist? switched from MAL, cause of lack of support of manhwas etc.. thanks.
