### ISSUE TITLE
Manga Panels Appearing On Gallery.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#812]
I have downloaded quite a few manga from this app before, but none of the manga images ever appeared on my gallery, and that was good, it made uploading photos on social media easier and making the relevant pictures more accessible. However, I recently downloaded Gunnm, but this time all the images are appearing whenever I open the gallery, so whenever I try to upload a photo on a social media, I have to go through a plethora of manga panels to find my pic! Why did this happen? This is the first time this is happening. Please look into it.

Here's a screenshot of the problem - http://i.imgur.com/DKsKPtt.png

Version: 0.5.2
Xiaomi Redmi Note 3 
Android Version : 6.0.1

**Comment by CarlosEsco** [comment]
What is the folder path in gallery that those are showing in?

**Comment by MercerBoi** [comment]
The same folder path where all the other manga that I downloaded from Tachiyomi is.

My SD card > Android > data > eu.kanade.tachiyomi > files > Kissmanga (EN)

Screenshot for clarification - http://i.imgur.com/OMnvvuT.png

**Comment by inorichi** [comment]
1. Install the dev release alongside your current 0.5.2. 
2. Go to `Settings > Downloads`. 
3. Change the downloads directory to match the one used by 0.5.2. 
4. Everything should have disappeared from gallery.
5. Uninstall the dev release.

**Comment by MercerBoi** [comment]
I did exactly as you said, but the problem persists. I guess my only option is to read it completely and then deleting it.

**Comment by inorichi** [comment]
There should be a `.nomedia` file created in that directory. Delete it then try again with the previous steps.

**Comment by MercerBoi** [comment]
Deleted the hidden .nomedia file and followed the previous steps again, once more, there is no change in the result :disappointed: .

**Comment by inorichi** [comment]
The `.nomedia` file is there, and by doing those steps, we run the media scanner on the downloads directory to update everything from there. If the images are you seeing are inside the directory with the nomedia, I doubt we can do anything else, that file is our only interaction with the gallery.

**Comment by FujoshiEnthusiast** [comment]
I just downloaded this tachiyomi app, and it's really cool. I have downloaded two manga but I was a bit shocked that it appears in my gallery, honestly I really don't like that. I'm just a newbie when it comes to this so please somebody help me.😅

**Comment by hXtreme** [comment]
Try adding an .nomedia file to Tachiyomi folder.


Best,
Harsh

**Comment by FujoshiEnthusiast** [comment]
Thank you for that, it worked.😅
