### ISSUE TITLE
Categories  

### ISSUE THREAD

**Issue by cd0rw0** [inorichi/tachiyomi#813]
Currently to update or to check current categories,

(Action - Result )
> 1. touch ribbon/tag/bookmark icon  - removed from library
> 2. touch ribbon/tag/bookmark again  - added to library 
> 3. category menu  - tag new categories/ check on current categories, 

i assume this to make removal of manga from library easier. but this making extra action/touch just to check current categorizes.
and also 1 touch removal make easy for accidental removal. ( yap i have removed few manga like this)
in my opinion, we update categories more frequently then remove manga from library.  

so my suggestions is, 

part 1: adding "categories" to main page
<a href="https://imagez.to/i/H23VOAeq.jpg"><img src="https://imagez.to/t/H23VOAeq.jpg"></a>

with this, checking on currently tagged categories done without any actions.  
this will big help for people who frequently update categories and have multiple categorizes tagged for 1 manga.
this also can be make actionable by - touching any part of  categories open categories menu.
 
Part 2 : ribbon/tag/bookmark icon

Ribbon icon have 2 action - 1 touch and touch & hold
by default 1 touch maintain current - remove manga from library 
touch & hold - open categories menu

but have option to change/swap 
(i will definitely will not use 1 touch to remove manga from library, scared of accidental removal) 

also can have additional option added in 3dot menu on top for removal from library by add "remove from library"

as i said above, both my suggestion are based on assumption that alot people update categories more frequently then remove manga from library. 

Hope you look into above suggestions.

Thank you

updated 28/05
-update icon name

**Comment by wopian** [comment]
Pressing the tag icon (middle) will give you a checklist of categories it's in

**Comment by cd0rw0** [comment]
cant understand which 1 you referring too

**Comment by inorichi** [comment]
A long tap in the floating action button is unnoticeable. It can be added in the toolbar instead.
As for showing the categories alongside the manga metadata, I don't like it.

**Comment by arkon** [comment]
A separate button for managing categories was added recently.
