### ISSUE TITLE
Kitsu tracking returning HTTP 400 errors

### ISSUE THREAD

**Issue by emyarod** [inorichi/tachiyomi#814]
When trying to add a new title and sync it with Kitsu, Tachiyomi will return a HTTP 400 error

Steps to reproduce:

1. Enter your credentials in Settings > Tracking > Services > Kitsu
2. Go to the "Tracking" tab of any work.
3. Edit title and select corresponding title in Kitsu database.

![gif](https://cloud.githubusercontent.com/assets/8265238/26523608/5f2a893c-42e9-11e7-8139-a26f2c7cfdda.gif)

Version: v0.5.2
(other relevant info like OS)
Phone: Google Pixel XL
Android: stock 7.1.2

**Comment by pervertkirito** [comment]
same issue #783 
fixed in dev build
