### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by reddeimon** [inorichi/tachiyomi#816]
Some manga such as Kyou no Cerberus and Witchcraft Works will "Mark as Unread" after some time even after "Mark as read" or downloaded multiple times.

Version: v0.5.2
(Android 5.2)

**Comment by NoodleMage** [comment]
This is probably because the source re uploaded a new version.  Could you give the catalogue of this manga?

**Comment by reddeimon** [comment]
Mangafox, but some of "Mark as Unread" manga already ends like 3 years ago
such as The World God Only Knows or rarely updated like 4 months such as
Witchcraft Works. The weird part is usually chapter with extra chapter with
".5" at the end remain untouched

**Comment by inorichi** [comment]
If they change the url of the chapter, it's not easy to detect if the chapter is read or not. We rely on the chapter number for that, but if the recognition fails, so does the marking as read. There's hardly any solution for this.

**Comment by reddeimon** [comment]
Thank you for the reply, keep up the good work
