### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by reddeimon** [inorichi/tachiyomi#817]
1. App is easily frozen if trying to download large amount of chapters

2. If download more than 1 chapter in a time the download easily get error

Version: v0.5.2
(Android 5.2)

**Comment by NoodleMage** [comment]
> App is easily frozen if trying to download large amount of chapters


Large amount? How many chapters and which phone?

> If download more than 1 chapter in a time the download easily get 

Which catalogue/manga?

**Comment by reddeimon** [comment]
1. I download about 200+ chapters using my Zenfone Go

2. Mangafox, anytime the simultaneous is 2 or 3 the download progress of a
chapter easily get frozen before it ends and then proceeds to other
download. But everytime the download of each chapter will get frozen

**Comment by inorichi** [comment]
1. Queued 500 chapters with no freeze at all. You're using a custom directory right?

2. Then use 1 simultaneous download. Mangafox might not like you doing that, it's not an issue with Tachiyomi itself.

**Comment by reddeimon** [comment]
Thank you for the reply, keep up the good work

**Comment by inorichi** [comment]
Maybe I can speed up the freeze you are having. Can you confirm if you are using a custom directory for downloads?

**Comment by reddeimon** [comment]
Yes, i am using custom directory. I redirect the download path to SD card

**Comment by drac0300** [comment]
I also have this problem (the app being unresponsive under large downloads), and I believe it is due to the I/O on the SD card since I don't remember it happening on internal memory. I think it is just my SD card being slow though. It is in my case not limited to tachiyomi, large DLS  using aria2 also slow down the system
