### ISSUE TITLE
Page list empty 

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#818]
Version: r1172

heve this problem at kissmanga.. tested 2 mangas there... app will found new chapter, but cant read any.. even old one.

**Comment by inorichi** [comment]
If other chapters are working, it should a problem with kissmanga itself (have you tried to read in your browser?). With no examples I can work with, there's nothing to do.

**Comment by Sparh4wk** [comment]
in browser it works fine. but not even single manga from kissmanga works in app..
for example http://kissmanga.com/Manga/Normal-Class-8

**Comment by inorichi** [comment]
They're working for me. If you can provide me a network log I'll be able to know what's going on, otherwise I can't do anything.

**Comment by Sparh4wk** [comment]
ok.. now I know where is the problem.. I downloaded latest dev version and then all catalogues from fdroid... I uninstalled kissmanga catalogue from fdroid and now everything is ok... prolly someone should clean old ones from that repo.. and btw dunno if its just me, but on fdroid there is latest dev version 1167 even if there already 1172 out there. thanks for help and sry for wrong issue report.

**Comment by inorichi** [comment]
No worries, after all those catalogues are outdated and it's our fault. I'm going to update them shortly.
The fdroid repo is maintained by @j2ghz, I can't help you there.

**Comment by Sparh4wk** [comment]
sry, my knowledge of github is not that great. so dunno how to contact him.. :(

**Comment by j2ghz** [comment]
It works now, https://github.com/j2ghz/FDroid-Data/issues/1. There are no DMs no github, so the only way is @mention on issue.
