### ISSUE TITLE
Minor bug with search and filter button in catalogues

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#819]
Version: r1172

what to do:

1. go to Catalogues
2. press search button
3. find something, for example "Overlord"
4. Click on it and click Tracking 
5. Im using MAL so click Edit, found manga and click OK
6. Press back arrow 2x 

Now you are at catalogues, yet search and filter button is not there.

**Comment by inorichi** [comment]
https://issuetracker.google.com/issues/37657375 probably related. It's easy to reproduce with the library search too.
