### ISSUE TITLE
F-droid dev repo "Error getting index file"

### ISSUE THREAD

**Issue by Arkonos** [inorichi/tachiyomi#823]
After resetting my phone and reinstalling f-droid, I get the following error whenever /repo or /archive wants to update:
"Error getting index file".
I can access both XML files with the same phone.
Writing http://... instead of https://... changes the error to:
"Error parsing index".
Removing the Tachiyomi dev version that was restored via titanium backup did not help.
Installing 0.5.2 via the F-Droid repository works.

My phone's time is reasonable accurate.

Android: 7.1.2
LinageOS 14.1-20170516-NIGHTLY-hammerhead
Android security patch level: 5 May 2017
Kernel version: 3.4.0-g4edc8ca

**Comment by Sparh4wk** [comment]
+1 have the same problem couple of days now.. but I think its better to report this to repo owner.  @j2ghz

**Comment by Arkonos** [comment]
Please do so if you can, I don't see a way how to raise an issue on his fork nor contact him directly.

**Comment by cd0rw0** [comment]
hi guys 

fdroid maintain by @j2ghz  , & this issue reported in here  gitup https://github.com/j2ghz/FDroid-Data/issues/1
look  like this is  issue with new fdroid . so @j2ghz  reported in fdroid.

**Comment by j2ghz** [comment]
It's fixed. https://gitlab.com/fdroid/fdroidclient/issues/1040#note_30975303
