### ISSUE TITLE
[Feature Request] Settings backup

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#824]
Version: r1173

Can you please add settings to backup? I mean all setting, like reader, tracking, sources etc...
I think it will be great feature, cause I needed reinstall app for like 10 times in last week and its realy boring to set all up again and again  :)

**Comment by inorichi** [comment]
#795. Sorry but you'll need to manually set them.

**Comment by Sparh4wk** [comment]
@inorichi I dont need login info to be stored, but other things like reading style, image fit etc.. or this cant be done either? :(
