### ISSUE TITLE
Images not loading correctly

### ISSUE THREAD

**Issue by Isanagi** [inorichi/tachiyomi#825]
Version: v0.5.2
Android 8.0 beta preview, Nexus 6P

Probably an 8.0 related issue but images are corrupted and cannot be viewed properly. 
![screebshots](https://cloud.githubusercontent.com/assets/29097003/26631774/3037a568-45fc-11e7-9b89-304e26895dd5.png)

**Comment by NoodleMage** [comment]
#802
