### ISSUE TITLE
Backup/Restore problem

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#827]
Version: r1174

Dunno whats wrong but few days Im trying to backup database on one device and restore it on second.
I have tablet and phone. When I backup database on one device, then delete tachiyomi on second device, and clean install it, then setup my batoto and mal account, I have problem with some mangas that doesnt have any chapter read, even if they are marked even in backup file.

I tested it now like 5 times, and every single time I have problem with those mangas

Ao no Exorcist - in backup latest read chapter is 53
Kekkon Yubiwa Monogatari - in backup latest read chapter is 16.5
Omae o Otaku ni Shiteyaru kara, Ore o Riajuu ni Shitekure! - in backup latest read chapter is 10.5
Rosario to Vampire Season II - in backup latest read chapter is 63

Maybe there are more of them, but dunno.. about week ago I tested this, and I think there was more of them... Sometimes there is problem, that even those c

hapters arent in the backup file, but not this time.

P.S: Dunno why, but I cant add database file here, even if I packed it as zip, so its here as json https://file.io/2LWFBX

UPDATE:

I just manually set those missing chapters as read, then rerun backup, and found these differences:

Old one = O (doesnt work)  New one = N (working)

```
O:       "chapters": [
        {
          "u": "/manga/ao_no_exorcist/v13/c053/",
          "r": 1
        },
N:       "chapters": [
        {
          "u": "/manga/ao_no_exorcist/v13/c053/1.html",
          "r": 1
        },

O:      "chapters": [
        {
          "u": "/manga/kekkon_yubiwa_monogatari/c016.5/",
          "r": 1
        },
N:      "chapters": [
        {
          "u": "/manga/kekkon_yubiwa_monogatari/c016.5/1.html",
          "r": 1
        },

O:       "chapters": [
        {
          "u": "/manga/omae_o_otaku_ni_shiteyaru_kara_ore_o_riajuu_ni_shitekure/c010.5/1.html",
          "r": 1
        },

N:      "chapters": [
        {
          "u": "/manga/omae_o_otaku_ni_shiteyaru_kara_ore_o_riajuu_ni_shitekure/c010.5/",
          "r": 1
        },

O:      "chapters": [
        {
          "u": "/manga/rosario_to_vampire_season_ii/v13/c063/",
          "r": 1
        },

N:       "chapters": [
        {
          "u": "/manga/rosario_to_vampire_season_ii/v13/c063/1.html",
          "r": 1
        },
```

Its weird, cause there is 0 differences in versions etc.. even catalogs are the same :(

**Comment by NoodleMage** [comment]
Which catalogue? 

The backup restores read data with the URL of chapters because the ID of chapters are not known to the backup. The way it looks in your example is that the url changed and that causes the backup to be unable to restore. Does the new one work?

**Comment by Sparh4wk** [comment]
Catalogue: Mangafox
All worked but not this one:

```
O:       "chapters": [
        {
          "u": "/manga/omae_o_otaku_ni_shiteyaru_kara_ore_o_riajuu_ni_shitekure/c010.5/1.html",
          "r": 1
        },

N:      "chapters": [
        {
          "u": "/manga/omae_o_otaku_ni_shiteyaru_kara_ore_o_riajuu_ni_shitekure/c010.5/",
          "r": 1
        },
```

But its weird:

Old one address was ok, yet it wasnt imported.
New one is exported wrong = without 1.html and its not imported as well.

The right format on mangafox should always ends with 1.html cause all mangas on mangafox works that way.. dunno why tachiyomi saves without it to backup :( maybe catalogue problem?

**Comment by NoodleMage** [comment]
[This](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/backup/serializer/ChapterTypeAdapter.kt#L24 ) is where the url is set. As you can see it just takes the data from the object which it fetched from the database. So weird indeed :).

If you can create a method to reproduce it, I will look at it this weekend.

**Comment by Sparh4wk** [comment]
well Im not at programming etc, so if someone have skill I provided my database in OP. Thats all I can do for now :( but thanks anyway.

**Comment by Sparh4wk** [comment]
ok

just test this on new device that I purchased today Galaxy Tab s2, and again, 3 other manga wasnt restored, even if they are backed up, and I can see chapters in backup files with 1.html = the right one..

Can someone please test restore this json file? it contains only 3 mangas from mangafox

Black Bird
Sankarea 
Xblade

maybe someone can find the reason why its not working :(
[test2.txt](https://github.com/inorichi/tachiyomi/files/1048062/test2.txt)

Just rename it to json.
For anyone who is interested, I uploading my database with like 227 mangas... for testing purpose.
[test.txt](https://github.com/inorichi/tachiyomi/files/1048065/test.txt)

**Comment by NoodleMage** [comment]
I understand. It's just easier for me if I can reproduce it, that's why I asked. 

Thank you for these files. I will look at it tomorrow and see what I can find.

**Comment by NoodleMage** [comment]
Update: I tested test1.txt, works for manga specified. Created my own backup from it. Works. 
Manually added the manga and then restored it, works.
I tested test2.txt works for manga specified + adds other.

So sadly I can't recreate with the files provided, which means I can't fix it.

**Comment by Sparh4wk** [comment]
damn.... is there a way to make a logfile from import or something like that?

**Comment by NoodleMage** [comment]
After restore a log file is created here. /storage/emulated/0/Android/data/eu.kanade.tachiyomi/cache/tachiyomi_restore.log. Not that it gets overwritten after new restore

**Comment by Sparh4wk** [comment]
well its empty, so Im doomed :)
will try to moove all my mangas away from mangafox, cause it seems, thats the only catalog, that have this problem.. yet it will be hard work to do so.

**Comment by Sparh4wk** [comment]
ok, closing this.. solved via chaning all mangafox manga to another source :)
