### ISSUE TITLE
Auto resume download queue when launching app

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#828]
Tachiyomi saves the downloading queue  but it does not start it automatically.

It would better if it did or have an option to do it. That way you could even set Tasker (app) to launch Tachiyomi and start downloading the queue at night.

Most podcast apps have this feature, schedule to download at night (new and queued podcasts), when the phone is not being used and the internet bandwidth is better.

**Comment by CarlosEsco** [comment]
Arkon can correct me if am wrong but there are no plans to add this feature
