### ISSUE TITLE
Play button/resume button issue. 

### ISSUE THREAD

**Issue by myuc** [inorichi/tachiyomi#83]
Pressing the resume button on a new manga that has not been read before leads to a black screen instead of loading the first chapter.

**Comment by inorichi** [comment]
Probably a network issue on their end. I can't reproduce. Also post the version you're in, it may help.

**Comment by myuc** [comment]
Ah your right. It was a network issue. I hit back when it didn't load, clicked on the chapter and it loaded and assumed there was an issue.

**Comment by inorichi** [comment]
I'm doing some changes to be more user friendly. Showing a black screen is not right.
