### ISSUE TITLE
can you add Arabic language  

### ISSUE THREAD

**Issue by Hemosama** [inorichi/tachiyomi#832]
hi 

i love your work and i hope it comes with Arabic language 

i can help with translation 

but i don't no anything about programming :(

**Comment by NoodleMage** [comment]
We don't have a global translate page (yet), so you have to translate [this](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/res/values/strings.xml) file manually.

You can clone the project and create a folder values-ar  in res (same as for example values-pt) containing this stings.xml file with translated values. After this you can commit and create a pull.

If this sounds to difficult you can also let me know on this issue after you translated it. And I will help you do it.

**Comment by drac0300** [comment]
Note that there is an application called  'stringlate' on f-droid that helps you edit the strings.xml file

**Comment by NoodleMage** [comment]
#844
