### ISSUE TITLE
Kissmanga say "No Result Found" in catalog menu

### ISSUE THREAD

**Issue by dreiki** [inorichi/tachiyomi#835]
So i've download the app, and go to catalog menu. I select every source and the Kissmanga and mangafox give me the message below the screen "No Result Found". I know that mangafox is blocked in my country so this error is reasonable, but the kissmanga website not blocked and operated correctly in my browser, and some other manga app. 

Version: v0.5.2
CM 13 Marshmallow

**Comment by ShakeBake** [comment]
Try going to advanced settings and clear database and refresh library metadata. This worked for me. But be careful, clearing the database will delete all downloaded manga not in your library.

**Comment by Jezza** [comment]
I don't think it's a DB issue, as I have had the same problem with mangafox. 
A simple restart of the app fixed it. Might be related.
