### ISSUE TITLE
Local manga on sdcard

### ISSUE THREAD

**Issue by protoniogg** [inorichi/tachiyomi#837]
Tachiyomi doesn't display manga ( CBZ format ) placed in external sdcard. The path is correct ( externalsd/Tachiyomi/local) infact I can see the cover of the manga but there aren't chapters inside, I tried to put same files in the tablet memory and that works. I'm using shield tablet k1 with android 7.0

Version: 0.5.2

**Comment by inorichi** [comment]
Have you manually refreshed the chapter list?

**Comment by protoniogg** [comment]
Yes, I have; but maybe the app need same permission to read the sdcard (maybe because of Android 7), I talking about permissions because other application ask me to grant them while tachiyomi not. In this moment I have put the file in external Memory/tachiyomi/local but in order to read It I have to copy them to the internal memory

**Comment by inorichi** [comment]
We ask the permission when opening any manga. Anyways you can always check if the permission is granted or not. Open the app info and under the section "Permissions" there should be an "Storage" permission turned on.

**Comment by protoniogg** [comment]
Yes, it's turned on

**Comment by ProjectPatatoe** [comment]
I'm unable to view the cbz files on /storage/0000-0000/Tachiyomi/local/somemanga/blah1.cbz, they show up in the list but every image has a "retry" on it. After extracting, it works and I am able to read it.

In fact in internal storage I am also unable to view cbz files but they also show up on list.

LG G4 android 6.0
Tachiyomi Version 0.6.7

**Comment by B4rabbas** [comment]
Hi, I got the same issue

**Comment by arkon** [comment]
This is a pretty old issue. If it's still an issue, open a new one with more up to date device/app info.
