### ISSUE TITLE
Tracking doesn't work

### ISSUE THREAD

**Issue by baskervald** [inorichi/tachiyomi#838]
Version: v0.5.2
Device: Nexus 5x
OS: PureNexus 7.1.2-20170509-OFFICIAL

Tracking refuses to work no matter the settings. I'm logged in with Kitsu, Anilist, and MyAnimeList. These are my settings:

![screenshot_20170611-191818](https://user-images.githubusercontent.com/8798637/27015454-f82527a2-4edb-11e7-94ca-ff7cc048249c.png)

All fields in the tracking page for a manga are blank, as shown below:

![screenshot_20170611-191841](https://user-images.githubusercontent.com/8798637/27015466-1e2b9f62-4edc-11e7-8743-b604e9f45d4c.png)

For example, despite the fact that I'm well into History's Mightiest Disciple Kenichi, it's not even listed on any of the three tracking sites:

![screenshot_20170611-191837](https://user-images.githubusercontent.com/8798637/27015475-4c14f86a-4edc-11e7-8a20-ee7cd3d5eb8e.png)

My profiles: [kitsu](https://kitsu.io/users/transitracer), [anilist](https://anilist.co/user/transitracer), [myanimelist](https://myanimelist.net/profile/transitracer)

**Comment by baskervald** [comment]
My apologies. This was an error on my part, since I didn't realize you have to set the name for it to start tracking.

I am getting an http 400 error on kitsu.io, however.

**Comment by wopian** [comment]
>I am getting an http 400 error on kitsu.io, however.

This will be fixed in the next release. Got fixed in dev build last month 😃 (#783)
