### ISSUE TITLE
Lost covers in Mangafox and "No Results Found"

### ISSUE THREAD

**Issue by ReGtrs** [inorichi/tachiyomi#839]
(1) I've had these issue only in Mangafox that somehow the manga covers aren't showing (except for those in my library). My temporary fix for this is wiping the app's data for the covers to show up again.

(2) Sometimes when searching (in the same source), it shows "no results found".

Version: 0.5.2
OS: 4.4.2

**Comment by inorichi** [comment]
1. Settings > Advanced > Clear database will solve that issue.

2. Mangafox has a limit of 1 query every 5 seconds. Just wait a bit and try again.
