### ISSUE TITLE
App keeps returning to page 1 on webtoon viewer

### ISSUE THREAD

**Issue by Red91** [inorichi/tachiyomi#84]
Cannot continue back to the last read page. Instead the app always returns the reader to the very first page rather than the page that it was on prior to being closed or switched to another manga.

**Comment by inorichi** [comment]
Webtoon viewer?

**Comment by Red91** [comment]
Yes. Is this an expected behavior due to you previously saying Webtoon viewer was not as stable?

**Comment by inorichi** [comment]
Yes, it's not supported. I would like to have a custom view for the webtoon viewer but I'm not skilled enough and it would take a lot of time.

**Comment by Red91** [comment]
It's totally fine. Not really a major problem since the app does state the page number I was recently on so I can always just scroll back to that page manually as soon as it takes me to page 1

**Comment by inorichi** [comment]
Moving issue to #71
