### ISSUE TITLE
About the big amount of WakeLock calls

### ISSUE THREAD

**Issue by Johndeep** [inorichi/tachiyomi#843]
It seems to be an issue about the **LibraryUpdateService:WakeLock**, which can be seen and measured by i.e. "WakeLock Detector".
The configuration of Tachiyomi is "Daily update" and I have roughly about 40 Mangas, after about just one day measuring (i.e. by looking up the CPU-WakeLock after unplugging after some time), I think over +25000 wakeups are a little bit much. Last time I looked it up after about 3 days measuring data, it was at about +95000 wakeups.

My question is, is it normal to wake up that much or are there some unnecessary calls?

Version: v0.5.2 from F-Droid on LineageOS 14.1.

**Comment by inorichi** [comment]
I can only tell you the calls are not wrong. You can see it for yourself [here](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt#L154).

The wakelock is acquired when the service is created, then released when destroyed, no other usages. Maybe the service is being created and destroyed multiple times (for unknown reasons), but it's unlikely.

**Comment by Johndeep** [comment]
Hmm, oh, sorry for not very clear, but of course I know this call is necessary, the main problem on this is the huge amount of callings. I mean, if you update, wouldn't a "handful" per day be sufficient?
But maybe this could also be a problem of the PowerManager itself..

Well, nothing you can do then.

**Comment by inorichi** [comment]
I don't know where that "huge amount of callings" come from. The update service is alive while it's updating (when the progress notification is shown), and that service has an `onCreate` and `onDestroy` method, which is called before starting to update, and after the update is finished, respectively.

So, when you manually click the update library button or the daily update is triggered, exactly 1 wake lock is created and acquired, and cleaned up when the update finishes.

Perhaps do you mean something else with "25000 wakeups"? If the update takes for example 10 minutes, the wake lock is alive all that time.

**Comment by Johndeep** [comment]
Well, I'm certain this "25000 wakeups" are referring to Tachiyomi, because there are also other Apps like K-9 Mail, which has a similar issue about the mail pushing, which already exceeds over +400000 calls in total in only 10 hours (the striking ones are called "ImapFolderPush" instead).

Even though I closed this issue already, after some lookups, I'm now a bit more certain, that this is a problem with the Doze Mode of Android 6 and 7 at least. In recent blogs and posts about this there are several mentioning about how "only high-priority GCM (google cloud messaging) notifications can wake a phone from doze".
Furthermore, this huge amount of calling seems to only be happening, if the phone itself is probably in Doze state, which could correlate with the wakeup calls, maybe? Because as long as I didn't let the phone go into Doze mode (in my understanding, the Doze mode is activated after the phone is idle for about one hour), there are no abnormal barrage of callings.

I'm aware that I'm only speculating without solid proof, but this is what I observe and on which I make (probably wrong) insights.

**Comment by null-dev** [comment]
@Johndeep So I installed this "Wakelock Detector" app, started a library refresh and closed my phone. The detector showed x45246 a minute later after I opened the phone screen. I'm guessing this number means how much CPU time or just how long in general services have been running for after the phone screen is closed (in ms).

There is also no way my phone could have entered doze mode immediately after I closed the screen. For that, you need an app like ForceDoze.

**Comment by Johndeep** [comment]
@null-dev If that's the case, then I'm simply wrong about Doze.

But now you gave me a crucial information which I didn't tested yet, any app always raise the amount of calling **after** the screen is turned off (how is irrelevant), **while** something in this app is currently running and wants to keep it open.

So then, this could be failed attempts to "wake up" the system (this many it seems). In general, **every time** the app is "trying" to do something while the screen is off seems to retry as many times it takes to complete the task. Tachiyomi seems to do this for updating, even thought the "request for lock" command is only called once in the app itself. So the detector still shows the attempts, which is indeed proportional to the time in milliseconds. Which is why I now suspect the power management of android for screwing around.

But thank you for still staying with me (even if the issue is closed and it is probably not really related to Tachiyomi itself) to track down this unwanted behaviour. At least I know now this is related to the underlying "screen off" mechanism or most probably rather to the power management of android.

One thing I still want to know, can anyone reproduce this problem prior to Android 6, before the "better power saving attempts due deep sleep etc." of Android 6 and 7?

**Comment by wopian** [comment]
I have 353 wakelocks from the past year almost on 6.0.1

**Comment by Johndeep** [comment]
@wopian That's impressive how you could retain the counting for a year, and yeah, undoubtedly Marshmallow isn't affected by this wakelock issue. I can confirm this.

So some changes in the "battery life optimization" between Marshmallow and Nougat were happening, some regression I say.. I hope this will be fixed in Nougat and not first in Android O.. unfortunately this issue is almost "invisible" for many without access to some CPU wakelock scanner. The most obvious you can notice at all are the faster battery drain, followed by clueless searches..

Sorry if I post this here, but I noticed this whole issue first with Tachiyomi.. and I just wanted to wrap up this issue properly.

**Comment by wopian** [comment]
>That's impressive how you could retain the counting for a year, and yeah, undoubtedly Marshmallow isn't affected by this wakelock issue. I can confirm this.

Nah, its just Amplify recording all wakelocks (4.3m in total 🙀)
