### ISSUE TITLE
hello problem with android studio

### ISSUE THREAD

**Issue by moamen1** [inorichi/tachiyomi#845]
hello i tried to edit app on android studio 

i am very new to proframing and every thing 

i have this error

Error:(15, 1) A problem occurred evaluating project ':app'.
> Cannot run program "git": CreateProcess error=2, The system cannot find the file specified

**Comment by moamen1** [comment]
can i chat with you for business

**Comment by inorichi** [comment]
In the `build.gradle` inside `app`, there are some calls that require git to be installed. Read the comments there, and either install git or change the call as explained in the comment.

**Comment by moamen1** [comment]
OK thanks can you email me for work with you hazem.elraad1@gmail.com

**Comment by moamen1** [comment]
OK thanks can you email me for work with you hazem.elraad1@gmail.com
