### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by walkingshit** [inorichi/tachiyomi#847]
Version: v0.5.2

getting this error only with kissanime. all other sources are working correctly. this only started to happen today and it worked perfectly yesterday.
i tried clearing database, refreshing library metadata. neither of them worked.
pls give me a solution.

**Comment by 0xelectron** [comment]
Works fine here. Can you provide logcat?

**Comment by wallkingshit** [comment]
where can i find logcat?

**Comment by 0xelectron** [comment]
Well, you can use to apps like matlog to generate a logcat or you can get through adb. Are you still facing the issue? have you tried manually accessing the website?

**Comment by wallkingshit** [comment]
yes still facing it and the site works fine on the browser. i will try matlog and let you know.

**Comment by inorichi** [comment]
Have you tried opening kissmanga from your phone's browser?

**Comment by wallkingshit** [comment]
yes i have tried opening kissmanga from phones browser and it works on the browser and i tried to kissmanga in the app while kissmanga is open on the browser it still shows the error. wanted to install the log checker but it requires me to root the device which i cant do. i guess i will just have to live with other sources.

**Comment by 0xelectron** [comment]
@wallkingshit you don't need rooted device. You just need to unable USB debugging and plug your device to computer(adb drivers should be installed) and accept the the request. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by walkingshit** [comment]
@0xelectron ok i installed the adb. now what request should i accept? because i didnt get any here is a photo of the adb installer 
![pic](https://user-images.githubusercontent.com/17717752/27227811-cbf8e9a4-52c6-11e7-8fc4-25d87d15d0e9.PNG)

**Comment by brillean** [comment]
I've also had this issue (HTTP error 403 on everything from KissManga) since version 0.5.2 & continuing through version 0.6.1.  I do have root, but logcat doesn't seem to show anything useful to me, although I'm not sure what to look for.

**Comment by walkingshit** [comment]
@brillean my issue was fixed after 1 or 2 weeks on its own. i think its an internet issue where its unable to fetch cookies. not sure though. you can maybe post your logcat and see what the developers say.
