### ISSUE TITLE
LocalManga enable bug

### ISSUE THREAD

**Issue by Pavkazzz** [inorichi/tachiyomi#848]
Local Manga sources enable only if english is turn on in "Sources"

Version: all

**Comment by Pavkazzz** [comment]
Step to reproduce: 
1) Enable 1 sources, except english
2) Put manga folder in /sdcard/Tachiyomi/local
3) In Catagues doesn't create source with local manga

**Comment by inorichi** [comment]
Thanks. Local source was implemented as an english source, it'll be changed.
