### ISSUE TITLE
One more zoom type

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#85]
I was just thinking there could be one more zoom type
* If width > height  -> fit height
* If height > width -> fit width

Good for not having to pan regular pages while zooming double pages enough to read.

**Comment by inorichi** [comment]
What should it be called? Smart fit?

**Comment by j2ghz** [comment]
Sound good. I don't think there is a name that would be this short and more descriptive

**Comment by j2ghz** [comment]
@inorichi It's great, except it starts in the middle, it should start on the right side for RTL and left for LTR

**Comment by inorichi** [comment]
Maybe configurable, because the resolution for the vertical is unclear.
