### ISSUE TITLE
Recent updates doesnt work after tap on new chapters found ribbon

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#850]
Version: r1177

I think its not working as intended... if Im at my library view or any other section of techiyomi, and then tap on new chapters ribbon, it doesnt redirect me on recent updates... only when I have tachiyomi closed, it will open recent updates.. dunno if its just me or there is something wrong with it.

**Comment by inorichi** [comment]
I have to change a flag, will fix later today.
