### ISSUE TITLE
New back system seems to be hanging when used to back up with dropbox since 5.2 release

### ISSUE THREAD

**Issue by Pizz001** [inorichi/tachiyomi#851]
Hi , since installing the new update (5.2) 
 i've now started to have problems with backing up to my dropbox folder where i had no problems before which never happened with any of the others 
i use dropbox as i back up from my main reading tablet a c94 10" zenithink tablet running ( 4.2.2) as i share it with my samsung edge 7 phone 
i've set up the path : /mnt/sdcard/android/data/com.dropbox.android/files/u92587971/scratch/main back up ( i've add this just incase there's a problem with it and it's a basic mistake on my part  )

each time i've tried to use the backup it's just been spinning  , even lastnight as a test i left it updating over night and after 8hrs it was still spinning and i had to hard reboot my tablet 

if anymore info's needs please just ask as more then happy to help .

Version: r 5.2 or v0.0.0
(other relevant info like OS)

**Comment by inorichi** [comment]
Can you try rotating the screen?

**Comment by Pizz001** [comment]
yes it will let me to do that , 
and oddly it works and makes the bacp and stores it in the right place when in landscape mode 
but still jams up in portrait and hangs with just a spinning box
 but thanks for the workaround and fast reply as its a great app :)

**Comment by inorichi** [comment]
It's a known issue (#781) and fixed in the next update.

**Comment by Pizz001** [comment]
sorry missed it when looking

**Comment by Pizz001** [comment]
sorry about that i missed it when having a look thru the posting
but thanks once again
