### ISSUE TITLE
[Feature Requests] Multiple Sources, Range Selection

### ISSUE THREAD

**Issue by Rave96** [inorichi/tachiyomi#852]
Hi, first of all thank you for the great app :D 
Glad to toss mangarock away. 

So some nice features I'd like to see, are searching on multiple sources at the same time, so if one manga isn't found on one source, that it shows other sources where it is aswell. (search function for tags etc. won't work for that, I know)

Second feature I'd like to see is a range selection when you are viewing chapters. For example if you want to mark chapter 1-150 as read you have to select every chapter on its own atm. With that feature you'd just have to set the starting chapter and the end chapter and everything inbetween gets marked as read aswell.

Third would be changing the grid size, because id like to have the images a bit smaller and see 3 manga per line for example.

And a question that I have would be, why do you have to be logged in for batoto chapters? When using mangarock, you don't have to be logged in or anything.

Would be cool to see some of it in the app :)

**Comment by j2ghz** [comment]
1. #849 
1. You can use Mark previous as read

**Comment by Rave96** [comment]
oh cool, thanks for the info :) 
I editted the post and added a third feature, do you have any info on that? 

> Third would be changing the grid size, because id like to have the images a bit smaller and see 3 manga per line for example.

**Comment by j2ghz** [comment]
Do you mean Settings > General > Library manga per row?

**Comment by Rave96** [comment]
oh wow, yes! 
So many good features in this reader!!!
Thanks a lot :)
