### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi#854]
I need to change the design but layout didn't show me the half of the design with red error
i need one update the project and he help me very mush or he solve that problem and thinks

**Comment by inorichi** [comment]
What are you trying to do? What error?

**Comment by nevaend** [comment]
when i open the project he gives me 15 Warning

Warning:no entries written for string/pref_ask_update_manga_sync_key (0x7f090181)
Warning:string 'backup_completed' has no default translation.
Warning:string 'backup_please_wait' has no default translation.
Warning:string 'font_roboto_medium' has no default translation.
Warning:string 'pref_ask_update_manga_sync_key' has no default translation.
Warning:string 'pref_category_sync' has no default translation.
Warning:string 'restore' has no default translation.
Warning:string 'restore_please_wait' has no default translation.
Warning:string 'title_hint' has no default translation.
Warning:no entries written for string/backup_completed (0x7f090061)
Warning:no entries written for string/backup_please_wait (0x7f090062)
Warning:no entries written for string/restore (0x7f090115)
Warning:no entries written for string/restore_please_wait (0x7f090116)
Warning:no entries written for string/pref_category_sync (0x7f090162)
Warning:no entries written for string/title_hint (0x7f090163)

so what i do

**Comment by inorichi** [comment]
Warnings are not errors. Ignore them.

**Comment by nevaend** [comment]
thinks, how i can get the project in palette in layout and add them in anew project
