### ISSUE TITLE
Image Sharpener

### ISSUE THREAD

**Issue by basilg3** [inorichi/tachiyomi#855]
Though this feature is not absolutely necessary, I believe that many manga scans could benefit greatly from a feature that would simply sharpen the display of a given manga chapter. Perhaps this feature could be acessed via the settings gear at the top right of the page, and be located under the "Image Decoder" option. I would imagine that a feature like this would come equipped with a "slider" that would determine the intensity of the sharpening effect, similar to how the Custom Color Filters have intensity "sliders" of their own. Of course, I understand if this feature is not feasible or possible, but it's something that I hope can be looked into. Thank you.

Version: r1179

**Comment by drac0300** [comment]
+1
, reading blurry japanese can be pretty hard when you are a beginner ><. 
I don’t know if it’s possible performance-wise, but you could take inspiration from how it’s done in imagemagick 
http://www.imagemagick.org/Usage/convolve/#unsharpen
https://en.wikipedia.org/wiki/Unsharp_masking
Thank you for the hard work !

**Comment by fighuass** [comment]
I think Lanczos3 support or something like that would suffice, too.

**Comment by arkon** [comment]
Would prefer not to bloat the app with extra image processing stuff. I'd recommend finding a better source.
