### ISSUE TITLE
Temp files in PC

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#856]
I decided to back up the downloaded chapters from the app to the pc but all I see are the temp folders and files in the pc whereas they are showing correctly in mobile file explorer.
edit : If I copy the folder in some other directory in mobile then it's showing correctly in pc. 
Version: r1174

**Comment by inorichi** [comment]
Examples of folders working/not working? It's weird, but what can I do from the app's side?

**Comment by bbtora** [comment]
Maybe it's an issue from the mobile side. I'll close the issue for now as I don't think it's the app's fault.
