### ISSUE TITLE
Total pages

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#857]
Can you make it so it will show the total number of pages for each chapter on unread chapters in the chapter list?

the placement could be the same as it is for the current page number when you are in the middle of reading a chapter.

**Comment by inorichi** [comment]
The page count is unknown until the chapter is opened. Also I'm not sure I want to save that field in database.

**Comment by shogunreaper** [comment]
why is that? it simply needs to add up the amount of images.

**Comment by CarlosEsco** [comment]
Its not that simple.  From manga page without any slow down to app it would need to open each folder for each chapter and count the number of images

**Comment by shogunreaper** [comment]
or it could save the amount of images it downloads at the time it downloads them.

**Comment by CarlosEsco** [comment]
yes but he just said he doesn't want to save the number to db.

**Comment by shogunreaper** [comment]
no he said "i'm not sure"

**Comment by inorichi** [comment]
Well it's not that I don't want to add a new column, but it's an overhead to be considered.

Let me elaborate on the other part. The number of pages is unknown until a chapter is opened or downloaded. I just can't make N requests to query the page count. However, the "current page" is only shown when it's greater than 0, so the chapter had to be opened at least once (except when restoring a backup, where it'll be unknown again), and that's when I can save the count.

**Comment by shogunreaper** [comment]
do you know how mangawatcher did it maybe you could copy that way.

**Comment by CarlosEsco** [comment]
shogun its not that simple to just copy how another app did it.  The apps are setup the same at all.

**Comment by shogunreaper** [comment]
well i don't mean copy the code just the method of how its done.

**Comment by CarlosEsco** [comment]
mangawatcher wasnt open source, and however they did it i'm sure we do not know.  They kept all hemanga on their own server.   instead of downloading directly from the website on the app like this app is doing.

**Comment by shogunreaper** [comment]
Not sure what you mean I used mangawatcher for years and it always downloaded the chapters to my tablet.

**Comment by CarlosEsco** [comment]
Yes what im saying is manga watcher had a backend server that scraped the websites and saved the images.  When you picked a manga to read it was reading the manga off their own server.  It is why manga would be missing when searching a website until he updated the app again or updated the backend server cache.

**Comment by inorichi** [comment]
They probably did what I said before. If the chapter was downloaded or opened at least once, the count is saved and can be shown.

No website shows the page count from the chapter list (or at least 90% of them). With a manga like Hajime no Ippo I would have to make more than 1000 network requests, and that's an IP ban for sure.

IIRC manga watcher scrapped directly from the website like we do. The only difference is that they provided a local file with the entire catalogue of the website, but that's not relevant for this case.

**Comment by CarlosEsco** [comment]
local makes sense, as to why catalog would get stale.  I must have missed it when I decompiled app before. When they added the web app version I was pretty sure they started making requests directly to the app

**Comment by shogunreaper** [comment]
> No website shows the page count from the chapter list (or at least 90% of them). With a manga like Hajime no Ippo I would have to make more than 1000 network requests, and that's an IP ban for sure.

yes i believe that the page count was only shown if you had the chapter downloaded already.

which is what i'm asking, i don't read manga online i always download it first.
