### ISSUE TITLE
[Feature Request] Chapter Sizes.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#858]
It would be great if we could see the size of the manga chapters before downloading them, this would help me know how much I can download before my data gets exhausted. Thank you.

v0.5.2

**Comment by inorichi** [comment]
No, you can't. Reasons discussed yesterday in the previous issue.

**Comment by MercerBoi** [comment]
Could you link me to the issue? I can't seem to find it.

**Comment by NoodleMage** [comment]
#857. It has to do with sending a request for every page. Which means if we implement your idea you probably also will be IP banned

**Comment by MercerBoi** [comment]
Ah I see. Too bad then. Thanks for the quick response though.
