### ISSUE TITLE
 Clickable author and genre fields in info tab

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#860]
New feature. it will help find mangas by the same author or genre. It can open a search in catalogs.

**Comment by QuestofIranon** [comment]
I could work on this if there is interest.

**Comment by sbstratos79** [comment]
+1 This seems like a very useful feature.

**Comment by QuestofIranon** [comment]
I've been playing around with this, but I was unsure if I should base any changes against #849 or the master branch?

Right now I have a semi-working solution against [NoodleMage/tachiyomi:global_search](https://github.com/NoodleMage/tachiyomi/tree/global_search) though.

**Comment by sbstratos79** [comment]
@QuestofIranon Can you not somehow integrate the clickable-author-name feature you are working on with NoodleMage's global search? Like if the user taps on the author name, it opens the global search with the search query as the author name.

**Comment by QuestofIranon** [comment]
@sbstratos79 I have it integrated with global search (need to clean up the code and change some other things when I get time though), just wanted to check if I should do a pull request against @NoodleMage's changes or if I should wait until those updates are merged into the master.

**Comment by NoodleMage** [comment]
@QuestofIranon Thanks for contributing!, 

Will probably finish pull this weekend (if nothing comes up). I don't know if the pull is visible in the main repo if you pull on my pull request. So I thinks it's easier for us to review if you wait for merge with master.

**Comment by 444nonymous** [comment]
I wonder if it's possible to implement some short genre description too.

Like the ones in -> http://www.anime-planet.com/manga/tags

**Comment by altaf933** [comment]
**Genres** having many tags so I just find out view which can be add into column with it's decent look . Check out this [repository.](https://github.com/2dxgujun/AndroidTagGroup)

**Comment by QuestofIranon** [comment]
Sorry I've been busier than I thought the past few weeks, I'll be working on this over the week/ next weekend.

**Comment by 444nonymous** [comment]
Global Search by @NoodleMage has been merged https://github.com/inorichi/tachiyomi/pull/849

@QuestofIranon  Maybe you could implement "Clickable author and genre fields" now.

**Comment by QuestofIranon** [comment]
@NoodleMage is this still needed? I had began work on it a while back and had it semi-working, but I'll probably just start over with the new search feature.

Also, I think #1127 could be added as well by long-click to copy?

**Comment by NoodleMage** [comment]
@QuestofIranon New quality of life features like this are always nice to see implemented. So if you have the time, be my guest ;).
