### ISSUE TITLE
"Page list is empty" on full volume .cbz files

### ISSUE THREAD

**Issue by dr4chen** [inorichi/tachiyomi#861]
I've been using Tachiyomi to view online manga for quite some time now with no issues whatsoever, however recently I've acquired some manga of my own and would like to read them through the app.

In learning how to set-up local manga through the app, I've noticed that most of what's mentioned in regards to the actual manga data refers to their individual chapters. I haven't been able to tell, but does this mean that files that are the entire volume will not be compatible with the Tachiyomi hierarchy and, thus, cause this "page list is empty" error? 

The "_You can also place your chapters or manga_" excerpt in the wiki led me to believe "manga" implied greater collections than individual chapters, but if I was mistaken, you can just stop reading here (though full volume support would be much appreciated!)

For clarification of my process if this is indeed unintentional and full volumes should be viewable:

I have been placing the manga in the Internal storage/Tachiyomi/local directory, with a sub-folder created with the manga's name for the following file path:

**Internal storage/Tachiyomi/local/manga/vol 1/manga_vol1.zip** (with .cbz inside)

I've also tried dumping it in the base manga directory:

**Internal storage/Tachiyomi/local/manga/manga_vol1.zip** (with .cbz inside)

And, unless I misunderstood the whole ZIP/CBZ instruction, I've also tried the same without the zip archive:

**Internal storage/Tachiyomi/local/manga/vol 1/manga_vol1.cbz**
and
**Internal storage/Tachiyomi/local/manga/manga_vol1.cbz**

Naturally, only one of these are right (unless I'm still missing something), but as I'm not very experienced in this sort of thing, I wanted to cover my bases. Each method reproduced the same "Page list is empty" issue.

Finally, I've cleared the cache several times, though I'm not sure if it should have any effect or not, and nothing changed. Also, unlike issue #837, my chapters are visible (as I guess they just assume the directory name), yet not accessible to read. Tachiyomi also has storage permissions.

The version of Tachiyomi I am using is 0.5.2

Thanks for your time, and thanks for all your work on the app!

**Comment by j2ghz** [comment]
The correct one should be `Internal storage/Tachiyomi/local/manga/manga_vol1.cbz`
How does your cbz look on the inside?

**Comment by dr4chen** [comment]
Oh, cool. I wasn't even aware that these were archives! 

I cracked one open and noticed that it's just filled with image files (.jpg specifically) with no other file type. I assume, then, it's missing some sort of meta file to let Tachiyomi know what it's supposed to do?

Anyway, I placed a few of the loose image files in `Internal storage/Tachiyomi/local/manga/` and it works, albeit in a very barebones (no divisions) and tedious to implement fashion. 

Just to check again now that you've given me the proper format, I also tried the .cbz again but to no avail. Does this mean my specific files just wont work?

**Comment by inorichi** [comment]
> Oh, cool. I wasn't even aware that these were archives!

cbz is just a zip with the extension renamed. You can rename it to .zip and it'll work too.

> I assume, then, it's missing some sort of meta file to let Tachiyomi know what it's supposed to do?

No, there's no need for metadata files.

> Does this mean my specific files just wont work?

They should, although there are a few cases where special characters will break the parser. How are the files named?

**Comment by dr4chen** [comment]
Gotcha. That clears the whole CBZ/ZIP deal up for me.

For this particular instance, I'm trying to add the first volume of Fairy Tail. 

Name of directory: `Internal storage/Tachiyomi/local/Fairy Tail/Volume 1`
Name of .cbz archive: `fairytail_vol1.cbz`
Name structure of pages within: `fairytail_vol1_001.jpg` → `fairytail_vol1_210.jpg`

My guess is that maybe the underscore or name repetition is the issue? I have a bulk renaming utility and can remove anything strings and repackage the volumes if need be.

**Comment by inorichi** [comment]
Place `fairytail_vol1.cbz` inside `Internal storage/Tachiyomi/local/Fairy Tail`. The `Volume 1` directory shouldn't be there.

Underscores do work, so there's no need to rename files.

Remember to refresh the chapter list, by pulling down the chapters screen, after moving the cbz.

**Comment by dr4chen** [comment]
Ah, now I feel a bit silly. I thought I had tested (and failed) that path above when j2ghz provided the correct directory. It works now! Tried it for another series as well and the same applies. Thanks (you both) for your help!
