### ISSUE TITLE
Random page list empty

### ISSUE THREAD

**Issue by TheOnlyZii** [inorichi/tachiyomi#862]
Hi

So I have this problem "page list empty"  showing up on random chapters across all sources. 

Like for example I tried to read the "karate shokoushi" ch 97 and 100 on stable I got "page list empty" error while when I changed to dev build its working fine
After that I was using the dev build for sometime and on a random ch I happens again, but this time the stable build loads it just fine

any ideas what caused it? 
Thanks

Version: stable v0.5.2
(Android 6.01)

**Comment by inorichi** [comment]
It has to do with the catalogue used. Maybe the dev release contains a fix for that catalogue.
