### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi#863]
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\manga\track\TrackPresenter.kt
Warning:(33, 26) Parameter 'error' is never used, could be renamed to _
Warning:(83, 49) Parameter 'v' is never used, could be renamed to _
Warning:(182, 43) Parameter 'which1' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\ReaderSettingsDialog.kt
Warning:(596, 31) Parameter 'dialog' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\widget\FABAnimationUpDown.kt
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\ReaderCustomFilterDialog.kt
Warning:(181, 39) Parameter 'dialog' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\viewer\webtoon\WebtoonAdapter.kt
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\setting\AnilistLoginActivity.kt
Warning:(242, 34) Parameter 'materialDialog' is never used, could be renamed to _
Warning:(170, 35) Parameter 'view' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\download\DownloadPresenter.kt
Warning:(182, 34) Parameter 'dialog1' is never used, could be renamed to _
Warning:(383, 49) Parameter 'v' is never used, could be renamed to _
Warning:(39, 35) Parameter 'savedState' is never used
Warning:(170, 41) Parameter 'page' is never used, could be renamed to _
Warning:(86, 43) Parameter 'v' is never used, could be renamed to _
Warning:(41, 56) Parameter 'v' is never used, could be renamed to _
Warning:(156, 25) Parameter 'chapter' is never used, could be renamed to _
Warning:(317, 28) Parameter 'error' is never used, could be renamed to _
Warning:(12, 66) Parameter 'attrs' is never used
Warning:(36, 78) Parameter 'view' is never used, could be renamed to _
Warning:(242, 50) Parameter 'view' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\ReaderActivity.kt
Warning:(70, 41) Parameter 'result' is never used, could be renamed to _
Warning:(596, 39) Parameter 'which' is never used, could be renamed to _
Warning:(181, 47) Parameter 'which' is never used, could be renamed to _
Warning:(383, 52) Parameter 'event' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\viewer\pager\PageView.kt
Warning:(78, 55) Parameter 'v' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\widget\preference\LoginDialogPreference.kt
Warning:(114, 56) Parameter 'v' is never used, could be renamed to _
Warning:(88, 51) Parameter 'v' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\reader\ReaderPresenter.kt
Warning:(73, 34) Parameter 'v' is never used, could be renamed to _
Warning:(102, 41) Parameter 'result' is never used, could be renamed to _
Warning:(109, 58) Parameter 'v' is never used, could be renamed to _
Warning:(242, 59) Parameter 'charSequence' is never used, could be renamed to _
Warning:(25, 48) Parameter 'v' is never used, could be renamed to _
Warning:(154, 22) Parameter 'view' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\ui\catalogue\CataloguePresenter.kt
Warning:(133, 17) Name shadowed: date
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\source\online\english\Readmangatoday.kt
Warning:(87, 13) Name shadowed: url
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\source\online\english\Mangasee.kt
Warning:(85, 26) Unnecessary non-null assertion (!!) on a non-null receiver of type Filter.Sort.Selection
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\source\LocalSource.kt
Warning:(79, 26) Unnecessary non-null assertion (!!) on a non-null receiver of type Filter.Sort.Selection
Warning:(311, 24) Parameter 'pages' is never used, could be renamed to _
Warning:(295, 29) Parameter 'pages' is never used, could be renamed to _
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\data\download\Downloader.kt
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\data\download\DownloadService.kt
Warning:(88, 13) Variable 'information' is never used
E:\tachiyomi-master\app\src\main\java\eu\kanade\tachiyomi\data\backup\BackupCreateService.kt
Warning:(125, 22) Parameter 'error' is never used, could be renamed to _

i can,t convert the project into apk

**Comment by QuestofIranon** [comment]
Those warnings should be ignorable.

**Comment by nevaend** [comment]
warnings i can't ignoble them,
he gives me error when i need to convert project into apk,
what i should do to remove this error

**Comment by null-dev** [comment]
What are the errors then? Those are warnings. Warnings are warnings.
Warnings are NOT errors. Maybe post a screenshot or something.

P.S. Hint: Warnings are yellow, errors are red in android studio.

**Comment by nevaend** [comment]
he gives me the first  message by yellow (warnings)

**Comment by null-dev** [comment]
Can you look for an APK inside "E:\tachiyomi-master\app\build\outputs"?

**Comment by nevaend** [comment]
i can't find it

**Comment by nevaend** [comment]
thx
