### ISSUE TITLE
Latest dev builds don't install

### ISSUE THREAD

**Issue by Beanow** [inorichi/tachiyomi#866]
The versions listed there

- 0.5.2-1179
- 0.5.2-1178

Android 7.1.1 on the OnePlus 3.

Coming from the repo in https://github.com/inorichi/tachiyomi/wiki/FDroid-for-dev-versions
`https://fdroid.j2ghz.com/repo` do not install with below error.

This prevents usage of extensions because the latest non-dev build still has this bug https://github.com/inorichi/tachiyomi-extensions/issues/37

![screenshot_20170627-150235](https://user-images.githubusercontent.com/497556/27588964-24d2f8ea-5b4a-11e7-818d-611e44fe64bb.png)

**Comment by j2ghz** [comment]
I have reinstalled 0.5.2-1179 right now and it worked. The latest version is https://fdroid.j2ghz.com/repo/tachiyomi-r1179-b3113.apk, can you try downloading it directly?

**Comment by Beanow** [comment]
Trying the direct install gave a better error message. Supposedly there was a duplicate app installed, but not for my user not sure how that ended up there but I had to uninstall for all users first to get this to work. Probably one of the debug builds did it.
