### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by catzs** [inorichi/tachiyomi#869]
Version: v0.5.2 
OS: Android N
Device: Motorola 5G+

Attempt to download all available Manga for one series. A number of pages for one chapter will download, but then it will stop and skip to the next chapter.

**Comment by inorichi** [comment]
Use a single simultaneous download, it'll help with downloads. There's already a retry strategy implemented for pages, but with multiple slots the chances to get a failed HTTP response are higher.
