### ISSUE TITLE
HTTP error 404

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi#870]
i add a new sources of Arabic manga but when i open the application it;s gives me that error and don't open any thing  ( http error 404 )

**Comment by j2ghz** [comment]
Issues about extension should not be here, but at https://github.com/inorichi/tachiyomi-extensions

**Comment by nevaend** [comment]
i know it's my  problem by editing the catalog
 but can you see it and tell me what's the wrong i do
tachiyomi/app/src/main/java/eu/kanade/tachiyomi/source/online/Arabic/GManga or Mangaforall

[download the project](https://mega.nz/#!i1kQHKZQ)
