### ISSUE TITLE
Error on bato.to

### ISSUE THREAD

**Issue by lightningdrake99** [inorichi/tachiyomi#872]
[Image](https://imgur.com/gallery/aaYhI) only happens on bato.to, no extensions installed. Also gets http error 405 when trying to view something from batoto. The problem appeared just recently (like a few hours ago maybe).

I assume batoto updated their reader or something, I have no idea other than that.

Version: v0.5.2
Android 7 on Samsung Galaxy Tab A 10" and LG G5

**Comment by beepFTW** [comment]
Getting this as well. Although the $baseUrls seems to still be correct. Too bad I'm away from home to research at the moment.

**Comment by ddmgy** [comment]
I was also having issues loading Batoto in Tachiyomi, so I've opened a pull request [here](https://github.com/inorichi/tachiyomi/pull/873) to fix it. Some of the links (to manga and to chapters) changed from http to https.

If you can build Tachiyomi from master, you'll be good to go.

**Comment by lightningdrake99** [comment]
Yep, changing all but the thumbnail url to https seems to fix the problems.
