### ISSUE TITLE
Bato.to error 'java.lang.String'

### ISSUE THREAD

**Issue by wisiwi** [inorichi/tachiyomi#874]
Having error when try load bato.to catalog. 
Full error - 
Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String}' on a null object reference
Having this issue on Tachiyomi v0.52
Device 
Asus zenpan 10
Xiaomi note 3 pro phone. 

Screenshot - http://i.want.tf/to/that/174j9.jpg

**Comment by j2ghz** [comment]
Duplicate #872
