### ISSUE TITLE
Java error when accessing Batoto catalogue or updating Batoto manga

### ISSUE THREAD

**Issue by LordZounds** [inorichi/tachiyomi#875]
Seems similar to #478 

This started a couple days ago for me. When I try to access the Batoto catalogue or update a manga from Batoto, I get this error:
"Attempted to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference"

I'm getting this on two different devices.

Version: v0.5.2
Device 1
Android 6.0.1, Running Cyanogen 13, Rooted and using Xposed
Device 2
Microsoft Surface running AMIDuOS Android emulator, running Android 5.1.1, not Rooted

**Comment by j2ghz** [comment]
Duplicate #872

**Comment by LordZounds** [comment]
Sorry, I looked but didn't see that. Thank you!
