### ISSUE TITLE
Batoto issue, "Attempt to invoke virtual method"

### ISSUE THREAD

**Issue by aolappa** [inorichi/tachiyomi#876]
I've tried updating and reinstalling the app but it still gives me this error when I try to refresh or update individual manga.

After reinstalling, chapters don't even show up now.

Here is a screenshot of the error: http://i.imgur.com/2geIXqV.png

Version: 0.5.2
OS: Android 7.0

**Comment by aolappa** [comment]
Note: Found out that apparently this error is only happening with Batoto directories.

**Comment by nightsky9S** [comment]
Same for updating any catalogue (screen stays blank)!

Version: 0.5.2
OS: Android 7.1.1

**Comment by wopian** [comment]
This was recently fixed (https://github.com/inorichi/tachiyomi/pull/873) and is available in the dev build

**Comment by ssuperkid5** [comment]
I use F-Droid to update to the dev version and I've reinstall and refreshed for updates multiple times. Is the build on F-Droid behind the one released here?

**Comment by nightsky9S** [comment]
Indeed, latest build works great!

**Comment by ssuperkid5** [comment]
I use F-Droid to update my Tachiyomi app and have refreshed the repository and uninstalled and reinstalled the app multiple times. Is the version in the repo normally behind the one released here?

**Comment by nightsky9S** [comment]
I've just downloaded the latest apk from GitHub, I'm not using fdroid
anyway

ssuperkid5 <notifications@github.com> schrieb am Mo., 3. Juli 2017, 08:25:

**Comment by inorichi** [comment]
Keeping this issue open until a new release arrives (to avoid too many of them).

Batoto announced in their twitter they were being DDoSed, maybe that's the reason they changed the links to https (also why the parser broke).

**Comment by j2ghz** [comment]
@xChickens I was doing maintenance on the server this weekend, and not everything is up yet. It should be done soon.

**Comment by Drfate13** [comment]
Is the batoto issue still unsolved?
Android 6.0
Version 0.5.2

**Comment by nightsky9S** [comment]
Use the latest version, not the stable!

Drfate13 <notifications@github.com> schrieb am Mo., 3. Juli 2017, 21:24:

**Comment by Arkonos** [comment]
V. 0.5.2-1181 is available via F-Droid.
Oddly enough I have 5 seemingly identical entries for this version.

**Comment by j2ghz** [comment]
@Arkonos That's from testing, just use the last one.

**Comment by 2b00** [comment]
Thank you for all the work that goes into this app. It's made following and managing the series I follow easy and convenient. I really appreciate it.

I also am still having the Batoto issue. I downloaded the latest developer build having ran into the problem with Batoto on the stable 0.5.2 build, but it seems the issue is present within both builds. Is this a matter of waiting until the issue is resolved on Batoto's end or maybe in the next update?

Thanks

**Comment by j2ghz** [comment]
@2b00 Are you using version r1184? It should be working there

**Comment by 2b00** [comment]
Sorry but I couldn't tell you. How would I check this? I just downloaded what was available on the main page and it doesn't seem like there are any available updates through the app.

**Comment by j2ghz** [comment]
@2b00 Settings > About

**Comment by 2b00** [comment]
I reinstalled the dev build. Works now, thanks for the assistance.
