### ISSUE TITLE
Problem with FlexibleAdapter??

### ISSUE THREAD

**Issue by ThePreviousOne** [inorichi/tachiyomi#879]
I am trying to write an extension and I am getting a few errors thot seem to be not related to my code

W/FlexibleAdapter: addItems Position is negative! adding items to the end
E/CatalogueController: onLoadMore
I/FlexibleAdapter: Running version 5.0.0-rc1 built on 2017.01.14

leading to this

07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity: java.lang.Exception: Page list is empty
07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.ui.reader.ChapterLoader$loadChapter$2.call(ChapterLoader.kt:66)
07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.ui.reader.ChapterLoader$loadChapter$2.call(ChapterLoader.kt:18)
07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
07-04 01:50:18.439 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.onNext(OperatorOnErrorResumeNextViaFunction.java:118)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:25)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
07-04 01:50:18.440 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.setProducer(OperatorOnErrorResumeNextViaFunction.java:130)
07-04 01:50:18.443 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
07-04 01:50:18.443 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Subscriber.setProducer(Subscriber.java:205)
07-04 01:50:18.443 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:45)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:13)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
07-04 01:50:18.444 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at java.lang.Thread.run(Thread.java:818)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.ArrayList.class
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:98)
07-04 01:50:18.445 11194-11194/eu.kanade.tachiyomi.debug E/ReaderActivity: 	... 51 more

Version: r1179 or v0.0.0
(other relevant info like OS)

**Comment by ThePreviousOne** [comment]
my problem occurres after chapters are loaded as pageListParse tries to run I have debugged it and the cause doesn't appear to be my code. It's getting stuck somehow between fetchPageList and pageListParse

**Comment by ThePreviousOne** [comment]
Also, and this is why I think it has to do with FlexibleAdapter, on any of the sources I have added ( I haven't checked others ) if there is only one chapter, chapter count is -1

**Comment by inorichi** [comment]
At that point flexible adapter doesn't have anything to do. The negative `addItems` is fine, and the other one may mean there are no more pages.

Anyways when you open the chapter flexible adapter isn't used at all. It looks like your fetch page list method is returning an empty list.

**Comment by ThePreviousOne** [comment]
I know that's not it because I have log statements all over the place. I can tell its not even making it to my code

**Comment by null-dev** [comment]
Can we see your code?

**Comment by ThePreviousOne** [comment]
https://github.com/ThePreviousOne/tachiyomi/tree/dev

**Comment by ThePreviousOne** [comment]
Nevermind I got it was in another class I overlooked
