### ISSUE TITLE
stream manga from computer

### ISSUE THREAD

**Issue by jevcleem** [inorichi/tachiyomi#88]
I think support for streaming downloaded manga from your computer to your device would be awesome. Perfect viewer allows for this using ftp but it is really slow. ComicCafe uses its own server, so it is fast but has a clunky UI.
In searching the web I found the following comic servers with available API's but no client app on android:
[http://vaemendis.net/ubooquity/](http://vaemendis.net/ubooquity/)
[https://github.com/beville/ComicStreamer](https://github.com/beville/ComicStreamer)

**Comment by inorichi** [comment]
It's too early for that, and I'm not sure I would implement it, because I prefer to keep the app simple.

**Comment by j2ghz** [comment]
If you implement it as a source the only thing that would be different is configurable address (could be implemented the same way as batoto's login). But I agree it's too early

**Comment by Kussie** [comment]
I'd kill for this, would help greatly for those hard to find mangas from rarer sources and save me from having to download and copy them to my sd card and use manga watcher still.  Local sources (Via SD Card or similiar) would finally allow the full replacement of MangaWatcher in my books

**Comment by drac0300** [comment]
This would be so good, combined with flexget !

**Comment by phanirithvij** [comment]
I don't think its too soon now @inorichi 
It's been 3 years nearly.
Please add a new type of extensions_category made just for UI changes and another category just for miscellaneous like this.
Now there are extensions by languages and websites.

**Comment by gotson** [comment]
definitely interested in support for Ubooquity, especially since [Kuboo](https://github.com/sethchhim/Kuboo) is now in archive mode.

**Comment by gotson** [comment]
I have sent a PR for an extension that will work with my new comics server: [Komga](https://github.com/gotson/komga).

**If people are interested to test it, i am happy to get some feedbacks!**

I started Komga as there is simply no existing project that would fit this need:

- Comicstreamer is not maintained anymore
- Ubooquity is closed source, has no API, and has problems with its [OPDS implementation](https://ubooquity.userecho.com/communities/1/topics/377-opds-xml-special-characters), making it difficult to integrate
- [ComiXed](https://github.com/mcpierce/comixed) supports OPDS but no API, and OPDS is not very efficient IMHO

**Comment by arkon** [comment]
There's been a few extensions created that target this sort of functionality, and they seem fairly decent.
