### ISSUE TITLE
[0.5.2-1181] FC upon selecting weekly backup frequency.

### ISSUE THREAD

**Issue by Arkonos** [inorichi/tachiyomi#880]
FC upon selecting weekly backup frequency.

Steps to reproduce:
Settings -> Backup -> Backup frequency -> Weekly
100% for me, no other frequency shows the same behaviour.
Once after such crash, the app would FC immediately on start until I cleared my data, but I can't reproduce this.
Pretty sure the same thing happened with 0.5.2-1179 already.

Version: 0.5.2-1181 (F-Droid)
Phone: Nexus 5 (hammerhead)
Android 7.1.2
LinageOS version 14.1-20170704-NIGHTLY-hammerhead
Kernel:3.4.0-g79d000a

**Comment by NoodleMage** [comment]
Can reproduce. Will look at it when I have some time.

**Comment by NoodleMage** [comment]
^^ thanks
