### ISSUE TITLE
MyAnimeList login fails if their is a colon in the password

### ISSUE THREAD

**Issue by franckoni** [inorichi/tachiyomi#882]
It seems that trying to link a MAL account having a “:” in the password lead to a login failure. 
To reproduce it follow these steps:
1. Change your password in MAL and add an “:” in it. I tried with “sgYu87:aze”

2. Then go to Settings → Tracking → MyAnimeList and try to connect. I got a “Login fail” that pop up and a red button with “Unknown error” on it.![sans titre3](https://user-images.githubusercontent.com/23405326/27919950-67f25b0e-6273-11e7-85b2-61486d18908c.png)

3. Then try this again while removing the “:” (for my case “sgYu87aze”). During the login process everything work fine and I succeed to link.

I tried it with other symbols character “!@#$%^&*()-_+=~`[]{}|\;<>,.?/” but “:” is the only one failing.
**BE CAREFUL** if you fail to login too many times MAL will ban your IP address for 12h.

Device 1: Nox App Player 3.8.2.0
Device 2: Samsung S7, OS: Android 7.0 
Version: 0.5.2

EDIT 07/16/2017:
The new v0.6.1 do not fix the bug

**Comment by jshap70** [comment]
i hope you've changed your mal password btw

**Comment by franckoni** [comment]
I change it don't worry

**Comment by haganbmj** [comment]
Looks like it's just an issue with the way credentials are passed in okhttp3. I'll have a look tomorrow to see if I can get my feet wet in this project. 

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Credentials.java

**Comment by inorichi** [comment]
This is not specific to Tachiyomi. You can also reproduce the issue with `curl` from the command line:

`curl -u <user>:<pass> https://myanimelist.net/api/account/verify_credentials.xml `

It returns "Invalid credentials" if the password contains a colon. It's an issue on their end, they probably split by colons without a limit. There's nothing I can do from the client side.
