### ISSUE TITLE
Batoto: Reloading chapter list does not work

### ISSUE THREAD

**Issue by BearBlaster** [inorichi/tachiyomi#884]
Reloading chapter list returns "Did not find balanced maker at href^=https://bato.to/reader". Other sources seem fine.

Version: v0.6.0
Android version 7.1.2
Nexus 6P

**Comment by KevWasHere** [comment]
Experiencing the same thing. Catalogues works now from latest update but the chapter list cannot refresh.

Android 5.0.1
Galaxy S4

**Comment by inorichi** [comment]
Ok, fixed now. Forget v0.6.0 ever existed.

I didn't expect JSoup syntax to change with a minor release. It's my fault for not testing it properly.
