### ISSUE TITLE
Combine sources?

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#886]
Just wondering if it's possible to combine sources, since titles from different sources update at different rates, sometimes source A will update faster than source B and vice-versa.

So instead of choosing a source then searching for a title, I simply type in a title, it'll search all the sources, and combine results with same titles?

Not sure if this is possible/hard to code for, since different sources names the titles slightly differently.

**Comment by evo85210** [comment]
Just to elaborate a bit more, what I'm trying to say is basically a global search, but the function is also extended into the reading list
For example
Source A has chapter 1 -12
And source B have 1-13
When  finish reading chapter 12 from source A, it'll notice that source B have the new chapter, so it'll automatically load that chapter from source B

**Comment by j2ghz** [comment]
The main problem would be to recognize which chapter in one source is which in the other, and also having extra chapters. I don't think it will be possible to make it good enough to be useful.

**Comment by evo85210** [comment]
Yea that'd be the biggest problem, there's also the problem of sorting, since popularity and rating may be different on different sources.

Im just throwing out an idea, you never know, there are some really smart people around, they might just be able to figure it out somehow .

**Comment by inorichi** [comment]
Nope, sorry. Global search will be implemented (there's an open pull request already), but merging titles with multiple catalogues won't be possible without breaking the whole app. The effort required to make this possible is not worth.
