### ISSUE TITLE
More intuitive page transition (landscape vs portrait)

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi#887]
So I changed over to Android from iOS, and I used to use mangastorm, which is a great app, but not available on Android.

So far I find tachiyomi just about more superior in every aspect, except page transitions.

Tachiyomi have fixed transition zones/method (tape right or flick left for next page) regardless of the orientation of the phone.

In mangastorm, I flick left for next page in portrait mode, but when in landscape, I flick up, since I'd be scrolling down to read a page that's zoomed in.

I find mangastorm's page transition to be more intuitive, just wondering if it's possible to add something like this?

**Comment by inorichi** [comment]
You can use the vertical viewer for flicking in that direction.

**Comment by wopian** [comment]
@inorichi allowing different default viewer settings for each orientation. E.g setting `Right to left` on portrait and `Vertical` when reading in landscape. Instead of one setting that's used for both

**Comment by inorichi** [comment]
I don't see a per orientation viewer preference. None of the other Android readers I'm aware of has this feature, and it's not very UX friendly IMO.

People usually read in one orientation. Maybe with double pages they rotate to landscape, but after that page, they go back to portrait. Also, tap zones can avoid the nuisance of wrong flick directions.

**Comment by arkon** [comment]
This sounds like very confusing UX if I'm understanding it correctly.
