### ISSUE TITLE
Error when trying to use Batoto as catalogue source

### ISSUE THREAD

**Issue by SmugLoli** [inorichi/tachiyomi#888]
I successfully logged in to Batoto in the settings. I can search for manga in Batoto but when I click one there are no chapters available after refreshing and I get an error message saying:

**"did not find balanced maker at href^=https://bato.to/reader"**

My bad if this has been covered before : )

_Version: v0.6.1 (latest)
OS: Android 5.0.1
Device: Samsung I9505 S4_

**Comment by inorichi** [comment]
It looks like you're using 0.6.0

**Comment by SmugLoli** [comment]
Fudge, huge blunder of mine. Thanks : )
