### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by IamHeinous** [inorichi/tachiyomi#889]
Version: 6
(other relevant info like OS)
Android Mrashmallow 
Zenfone 2

If you go to library updates. Please add a download button next to the menu. Inside menu should be mark as read unread and mark as read. If it is already downloaded the download button will turn to a trash icon to delete downloaded Manga if pressed.

**Comment by wopian** [comment]
You can download the chapter within the 3-dot menu, or by long tapping chapters and pressing the download chapter button

**Comment by inorichi** [comment]
1. Long tap a chapter to enter selection mode
2. Select any additional desired chapter
3. Click the download icon in the toolbar
