### ISSUE TITLE
Bookmarking 

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi#89]
As the title suggests, bookmarking option would be great.

**Comment by Bloodwork** [comment]
Bookmarking of what? Pages?

**Comment by Syborg49** [comment]
No. Bookmarking of chapters. Like Mangawatcher.

**Comment by Bloodwork** [comment]
I'm not sure why would I want to bookmark a chapter but I'm sure you have your own needs. 

I quite like the page bookmarking feature Crunchyroll app has. Makes it easy to pull up best quotes and scenes from the manga I read.

**Comment by Syborg49** [comment]
Isn't this possible @inorichi?

**Comment by inorichi** [comment]
No plans for this at the moment.

**Comment by Syborg49** [comment]
@Noodlemage is this possible? I'd love this so much. If you guys can include this, it'll be great. Thanks again for all the hard work.

**Comment by ThePreviousOne** [comment]
@Syborg49 Maybe give a use case as to why chapter bookmarking is helpful

**Comment by Syborg49** [comment]
Well I wanted this because when I was reading a fairly big (150+) Manga (Feng Shen Ji) I really wanted to remember some chapter because there was some memorable moments in it so I bookmarked it on mangawatcher. That way I could quickly access those chapters. That's the only reason i can think of @thepreviousone

**Comment by NoodleMage** [comment]
@Syborg49 

Little sneak peek ;)
![image](https://cloud.githubusercontent.com/assets/9655378/19455069/e6dd1f34-94bb-11e6-948a-205859ff7bbf.PNG)
