### ISSUE TITLE
A more free way to download and delete manga in library

### ISSUE THREAD

**Issue by Jendrej** [inorichi/tachiyomi#890]
Version: v0.6.1
Android 4.4

I would make it the way it was in the previous app I was using: make the download button in the 3 dots menu allow you to select the chapters you want to download on a list (to allow skipping downloading duplicate chapters), and add a select button with the options there are now: all, unread chapters etc. The same thing with deleting, also to be added to the 3 dot menu. I don't like how I can't delete all read chapters at once and have to remove each one manually.

**Comment by j2ghz** [comment]
Long press on chapter, select the chapters you want, tap download

**Comment by NoodleMage** [comment]
Long press one -> press select all -> delete

**Comment by Jendrej** [comment]
Hm. It's not intuitive, but whatever.

**Comment by NoodleMage** [comment]
I don't understand your idea. If you think it's more intuitive and you can explain it better, maybe people will prefer it. Only wanted to tell it's possible.

**Comment by wopian** [comment]
In the downloads settings, you can select "delete when marked as read" which would automate what you're trying to do

**Comment by Jendrej** [comment]
I know about this option, but it's not what I wanted. But nevermind, I just didn't notice that you can long press chapters on the list.
