### ISSUE TITLE
Does tachiyomi work on Amazon Fire tablets?

### ISSUE THREAD

**Issue by tachiyomayne** [inorichi/tachiyomi#891]
Tried to ctrl-f through previous issues and didn't see an answer in the wiki. I'm not sure if this is obvious one way or the other since these devices use Fire OS, but you can also access traditional Androids apps on it through various means. Appreciate the help.

**Comment by ThePreviousOne** [comment]
yes
https://f-droid.org/packages/eu.kanade.tachiyomi/

**Comment by tachiyomayne** [comment]
Thank you!

**Comment by Jendrej** [comment]
The version on F-droid is not the latest version though. I'm not sure why can't you just grab the apk from here if you are able to install F-droid, but I also don't know how do those devices work and what are the limitations.

**Comment by j2ghz** [comment]
It is the latest stable version. For all available download methods see table at the top of the [Readme](https://github.com/inorichi/tachiyomi/blob/master/README.md)

**Comment by Jendrej** [comment]
No it's not. The latest stable version shown in the table you're talking about is 0.6.1. The newest one on F-Droid is 0.5.2.

**Comment by j2ghz** [comment]
It seems F-Droid hasn't picked up the update:
https://f-droid.org/wiki/page/eu.kanade.tachiyomi
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/eu.kanade.tachiyomi.txt

**Comment by CarlosEsco** [comment]
@tachiyomayne  i agree with above.  Download from github and install the apk.  It has auto updates built in the app so you are always on latest version no need to worry about F-Droid not updating.

**Comment by tachiyomayne** [comment]
I installed and backed up my Tachi library today. I've ran into an issue where I can't sign into my Batoto account, though. I'm using the latest stable version and am able to sign in via the website. When attempting to sign in through the app, it just says unknown error.
