### ISSUE TITLE
BUG: Permissions not remembered at all.

### ISSUE THREAD

**Issue by Madidas** [inorichi/tachiyomi#892]
Tachiyomi keeps asking permissions (storage, photos and media) every time I open any manga in My Library. It looks like it does not remember that it has already given permissions to read that stuff. Under program info in Android settings it shows right permission to been given to it.

I need to try it with a clean install still. Though it did this with the latest dev build before v0.6.0.

Version: v0.6.1
Motorola Model E (2nd Generation) with 4G LTE
Android 6.0
With 1 December 2016 Security patch
Kernel 3.10.49-ga495b15

**Comment by ThePreviousOne** [comment]
are you running a custom rom?

**Comment by Madidas** [comment]
Nope. Not on custom ROM. Latest stock that Motorola has to offer in this phone.

**Comment by Kanjiex** [comment]
I have the exact same problem on my ZTE Trek 2 after updating to 0.6.1. It asks for storage permission each time I open any manga even though all permissions were granted. Already tried a clean install, clean data & cache, did not help.

I also have Tachiyomi on my Moto G4 plus which does not have this bug.

**Comment by Kishi** [comment]
I'm having the same problem and it's really annoying. Version 0.6.1 on a Moto G4 plus.

**Comment by Kishi** [comment]
Found some kind of solution, just deny the permission and it will restart the app. Deny it a couple of times then approve it and it will stay that way.
