### ISSUE TITLE
Bug: tapastic source does not load, crashes app

### ISSUE THREAD

**Issue by raiskream** [inorichi/tachiyomi#893]
V 0.6.1

_Sent from my HTC One A9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThePreviousOne** [comment]
I'll check it out but this should likely be filed against https://github.com/inorichi/tachiyomi-extensions

**Comment by raiskream** [comment]
Oops! Will add there. 

_Sent from my HTC One A9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by inorichi** [comment]
This should be fixed in the next release. For now, it works with the dev build.
