### ISSUE TITLE
Source Exhausted Prematurely

### ISSUE THREAD

**Issue by SmokedBeef** [inorichi/tachiyomi#898]
Everytime i wen to "Catalogues" section with Mangasee as my source, it won't showed any manga (usually it showed, i forgot when this problem even start). It just showed "source exhausted prematurely". Strangely, i still can download chapters for my bookmarked manga, weird.

Other source working just fine tho, i just prefer this site, since most other source is blocked by my ISP.
Here i attach the screenshot.

![screenshot_2017-07-15-22-24-11](https://user-images.githubusercontent.com/20703867/28240528-b4352d5c-69ad-11e7-8b6d-c00a1bbdae77.png)

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: v0.6.1
Android 5.1.1

**Comment by NoodleMage** [comment]
Is this fixed?

**Comment by SmokedBeef** [comment]
Yes, it's fixed long time ago, in previous version i guess.

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 30, 2017 at 1:56 AM, Bram van de Kerkhof<notifications@github.com> wrote:   
Is this fixed?
