### ISSUE TITLE
Follow up on #862

### ISSUE THREAD

**Issue by TheOnlyZii** [inorichi/tachiyomi#899]
this is a follow up from [#862](862) since i have more less better understanding of the real issue

This "page list empty" nag oftenly occur when you have an unstable connection, so what i think happened in the app is that when you're loading the chapter for the 1st time and it returns negative="Page list Empty" even though the chapter itself is there, and it will keep giving you a "page list empty" even though your connection got better because you failed to load it the 1st time until the library fetch new info.

Some of the quick fix i used to counter this issue so far is : 
-when you cant read a ch strangely enough you can just download that 1 ch you cannot view
-or use another version of the app (which havent failed loading the ch) ie: dev build, or using a dual apps feature

Version: v0.6.1

**Comment by inorichi** [comment]
You can also try clearing the chapter cache when it happens. Please let me know if that helps when you reproduce it next time.

**Comment by TheOnlyZii** [comment]
strangely enough clearing cache didn't help much when it occurs.
the easiest workaround so far was just to download instead of viewing it directly (sometimes the download will just stuck "On Queue" if that happens just pause and resume until it works)
