### ISSUE TITLE
Suggestion for new features

### ISSUE THREAD

**Issue by prifs** [inorichi/tachiyomi#901]
1. Any downloaded chapters' images don't show up on galley/picture apps. 

2. Any manga that you download a chapter is automatically added to your library. I think this will make it more user-friendly. I've downloaded a few chapters from some new manga to read and I've forgot to add them to my library, I wish that I don't have to come back to the manga just to add them when I've  already downloaded chapters from them.

3. Make the automatic default viewing right to left. Just a small issue but since 90%+ of the content are read from right to left, it would be nice if the default is like that.

4. Firstly, I don't know if this is a feature already, I've tried to mess with the settings but can't find it so I'll assume it's not yet a feature.  When there's a doublespread (that's the term I think, when a panel takes two whole page) page in a manga I would love it if when I doubleclick the page the doublespread page would fit exactly into the screen instead of zooming onto the particular panel/place that I've double tapped into. I can't remember where I saw this feature, I think it was in MangaStorm in iOS.

Before double click: [https://imgur.com/9NN6KeM](https://imgur.com/9NN6KeM)
After: [https://imgur.com/hGxrg5X](https://imgur.com/hGxrg5X)

5. An option to auto download the next chapter of the current chapter I'm reading at the moment.

6. Option to download every next chapter of the current chapter I've just read. I think this is better than filtering to unread chapters, selecting all then downloading them.

**Comment by j2ghz** [comment]
1. #812 
2. #638 #448 
3. I guess that's true.
4. Double tap is already reserved for zoom, and it's not very intuitive to change behavior based on the size of the page
5. Next chapter is automatically preloaded, if that's what you mean
6. 3 dot menu > Downlad > Download next X chapter(s)

**Comment by prifs** [comment]
1 & 2. Thanks for pointing out the thread.

4. I guess that is true, though it's a shame. MangaStorm, I think, have this feature and the zoom feature would be available through pinch gesture. It's one of the things I missed in iOS.

5. Thanks, didn't know that.

6. The feature downloads only the next, next 5 or next 10 chapters. There's also download all or download unread but if I'm continuing to read from the laptop to android then downloading all unread or all is not what I need. The feature would be say that I've read Death Note from chapter 1 - 40 on a laptop, then in tachiyomi I would want to download 41 - Final chapter. Since I haven't read this in tachiyomi, I can't select  download all unread since it'll also download chapter 1 - 40. Want I would to be able to do in Tachiyomi is read chapter 40 directly, then after that I can select download all next chapters, which would download chapter 41 to the Final Chapter. I'm sorry if this is too demanding for a simple feature. It's also a feature I've missed in MangaStorm

**Comment by CarlosEsco** [comment]
for number 6 long press chapter 40 then select all the chapters you read and mark as read.  then do dl unread

**Comment by prifs** [comment]
But this seems non user friendly. Let's say I read in laptop then discovered tachiyomi or I used to read in Zingbox got fed up  with the app then discovered Tachiyomi. And the chapter I'm on is chapter 100, and I want to download until 210 (Assuming this is the final chapter). Then I would have to click for 100 times before I can mark them read, or just straight download 101-210 by clicking every single one. As I've said, I'm sorry if this is too demanding, especially if there is a feauture of sort. It's one one the feature I've missed in MangaStorm iOS.

**Comment by CarlosEsco** [comment]
its not demanding but the use pattern for 95% of users is read through app since it keeps track of chapters marking them read.

**Comment by CarlosEsco** [comment]
actually I'm dumb forgot a feature.  so find chapter you want to read say 101 click the three dot button and click mark previous as read and all 1-100 will be marked read

**Comment by prifs** [comment]
My fucking Go-!!! I did not see that! Thank you! For some reason I wasn't able to see that feature for a long time. Thank you!

**Comment by j2ghz** [comment]
@prifs You can close this issue and make a new one for number 3.

**Comment by inorichi** [comment]
I've seen other readers also defaulting to left to right. I don't think it needs to be changed, since changing the default viewer is just two steps away and needs to be configured only once.

The rest of the points have been already solved (thanks for helping), so I'm closing this.
