### ISSUE TITLE
New uploaded comics from yaml source not showing

### ISSUE THREAD

**Issue by vilaroo** [inorichi/tachiyomi#902]
I've added the source readcomicsonline with the yaml file, awesome app by the way, but it only shows comics since that day or before, new uploaded comics won't show.

Version: v0.6.1
S6 with xtrestolite rom

**Comment by vilaroo** [comment]
Marshmallow rom

**Comment by j2ghz** [comment]
https://gist.github.com/j2ghz/fe656fc9efe86de6fee6457bc9454170#gistcomment-2011151

**Comment by inorichi** [comment]
YAML is deprecated. I think there's an extension already.
