### ISSUE TITLE
Library update chapters check too slow after update

### ISSUE THREAD

**Issue by mrtort** [inorichi/tachiyomi#903]
I had version 0.6.1 working fine with android 6.1 but after my phone updated now the app take forever to serch for new chapter on my library
I tried delete the app and reinstall but got the same performance
Am i doing something wrong, most of my list is from mangahere

Thx in advance 
Great app!

Version: v0.6.1
Samsung s6 edge android 7.0

**Comment by inorichi** [comment]
It has to do with the site. Nothing we can do.
