### ISSUE TITLE
[Bug Report] Webtoon viewer image crop fault

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#904]
Images do no seem to be being cropped while in webtoon viewer. If i switch to any other type it crops and looks fine but not on the webtoon viewer.

Version: r1184

**Comment by 444nonymous** [comment]
I noticed that too. Crop never worked for webtoon in any build since it was introduced.

**Comment by ShakeBake** [comment]
Is it difficult to implement for that type of viewer?

**Comment by j2ghz** [comment]
https://github.com/inorichi/tachiyomi/issues/219#issuecomment-279184489

**Comment by 444nonymous** [comment]
@ShakeBake I don't use Tachiyomi to read manga for that reason. I only read in webtoon.

Use Challenger Viewer (is free with no ads, like tachiyomi) and crops in webtoon (in several levels).

Add the tachiyomi folder in Challenger Viewer and it automatically loads and sorts all mangas.

https://challengerviewer.wordpress.com/

**Comment by ShakeBake** [comment]
I do sometimes use perfect viewer for that but I LOVE tachiyomi. It flows really well and is easy to read from. I also haven't been able to find a continuous viewer (webtoon viewer) that is as well implemented as here. I want to help improve it and eventually use it as my one stop shop for manga.

**Comment by 444nonymous** [comment]
I've tried all paid and free android readers. Challenger Viewer is much better than Perfect Wiewer.

It has continuous and smooth webtoon viewer with many render and crop options.
