### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by namnguyendeveloper** [inorichi/tachiyomi#906]
The source: http://truyentranhlh.com just return json data instead of html page when searching for manga. How can I parse it?

**Comment by j2ghz** [comment]
Instead of inheriting from `ParsedHttpSource` you can try `HttpSource`
https://github.com/inorichi/tachiyomi/tree/master/app/src/main/java/eu/kanade/tachiyomi/source

**Comment by inorichi** [comment]
Exactly that. It's going to be a bit harder but not impossible.

**Comment by namnguyendeveloper** [comment]
Done! Thanks so much
