### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by namnguyendeveloper** [inorichi/tachiyomi#908]
1. Open catalogues page
2. Search anything
3. Select any result
4. Press back twice
Search icon is disappered!
I don't know how to fix it :(

![screenshot_20170723-173700](https://user-images.githubusercontent.com/24988688/28498740-f36d46fe-6fce-11e7-8a1f-058602debd25.png)
![screenshot_20170723-173712](https://user-images.githubusercontent.com/24988688/28498741-fc21bd84-6fce-11e7-8e93-6095512941eb.png)
![screenshot_20170723-173726](https://user-images.githubusercontent.com/24988688/28498742-0693ce4c-6fcf-11e7-8298-27c570890879.png)
![screenshot_20170723-173736](https://user-images.githubusercontent.com/24988688/28498743-0cf41918-6fcf-11e7-9bd7-bd50e759449c.png)

**Comment by j2ghz** [comment]
Search and the two other icons that should be there are replaced by 3dot menu, tapping on it doesn't do anything.

**Comment by namnguyendeveloper** [comment]
If you press home button and then back to app, and problem solved 😂

**Comment by inorichi** [comment]
It's a bug in the support library from Google. I don't have the link to the issue right now, but it was introduced in v24 IIRC. Hopefully they'll fix it in v26.

**Comment by inorichi** [comment]
This is the issue: https://issuetracker.google.com/issues/37657375 

Sadly, it wasn't fixed in v26, but someone posted a workaround so I'll probably do that.

**Comment by inorichi** [comment]
I just added a workaround for the library search. I didn't update the catalogue one to not interfere with @NoodleMage 's PR. It'll be fixed later or added in that PR.
