### ISSUE TITLE
Import bookmarks from MangaRock into Tachiyomi

### ISSUE THREAD

**Issue by RoastyMcToasty** [inorichi/tachiyomi#909]
So I've had MangaRock for a few years and have accumulated about 200 bookmarks on, I recently heard about Tachiyomi and liked it more than MangaRock after installing and using it. I can't find a way to import bookmarks from MangaRock though and having to do each one individually would take a long time. I DON't know for sure if it's possible since MangaRock keeps backups etc. saved on their servers but if it is possible then it'd be a really good feature, aside from bookmarking from other sources.

If it's already available and I just haven't found it then please tell me, it'd save me a lot of time...

**Comment by inorichi** [comment]
Sorry, it's not possible.
