### ISSUE TITLE
Feature Request: Ability to download manga while not in app

### ISSUE THREAD

**Issue by catzs** [inorichi/tachiyomi#910]
When downloading manga, especially long manga series, it becomes extremely burdensome when one is confident to stay within Tachiyomi. If the option to continue downloading while the app was closed were present, this issue would be nonexistent. It is possible because numerous apps allow background downloading of various types of files

**Comment by inorichi** [comment]
Tachiyomi downloads in a background service, it keeps downloading when you switch to another app. However, if the app is killed by either you or the system, it'll stop and there's no solution for that.
