### ISSUE TITLE
[Feature Request] Add more reader defaults

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#913]
It would be useful to be able to set other options as default and change them depending on the content (mainly crop amd orientation). E.g. Set rotation and crop as a default and when needed (webtoons or whatever) change it to the desired setting and have those settings stick for that manga. In the same way that the default viewer' is set up.My main issue is switching between vertical webtoons and back to my default manga reading landscape position.

**Comment by ShakeBake** [comment]
My main issue is switching between vertical webtoons and back to my default manga reading landscape position.

**Comment by ShakeBake** [comment]
Just crop and orientation would be cool. For some reason free orientation doesn't work for me.

**Comment by inorichi** [comment]
#452
