### ISSUE TITLE
Chapters not showing for Wakabayashi Toshiya’s 4-koma Collection on Batoto

### ISSUE THREAD

**Issue by hhiru** [inorichi/tachiyomi#915]
Version: v0.6.1
OS: Fire OS 5.4.0.0 (Based on Android)

This is the manga: https://bato.to/comic/_/comics/wakabayashi-toshiya%e2%80%99s-4-koma-collection-r9820 When looking into the chapters tab on the app the list is empty. I noticed this problem with other Batoto titles

**Comment by inorichi** [comment]
I can see 44 chapters with no issues.
