### ISSUE TITLE
bug: app closes when attempting to create a backup

### ISSUE THREAD

**Issue by Wi150nZ** [inorichi/tachiyomi#921]
when creating a backup, the application closes (it doesn't crash)

current app version: 0.6.1
phone: nexus 5x (lineage 14.1-20170529 nightly build w/ root)
here is the logcat output: https://pastebin.com/gESFqkEc

**Comment by NoodleMage** [comment]
You should enable write permission. https://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/

**Comment by Wi150nZ** [comment]
I checked my permissions for the app and made sure that it was update, but the app still closes

**Comment by inorichi** [comment]
Can you try if it crashes with the latest dev build?

**Comment by Wi150nZ** [comment]
@inorichi I tried the lastest dev build and I still experienced the same problem. However this issue when away when I flashed a new ROM on the phone, so I guess the problem lies somewhere with Lineage rather than the app.

**Comment by inorichi** [comment]
We use the built-in document creator. For some reason it wasn't installed/found in your ROM. I don't know if that app is supposed to be optional, but for now nothing will be changed.

If the issue is present in other devices/ROMs, I'll look for a workaround.
