### ISSUE TITLE
Attempt to invoke virtual method, only with mangago

### ISSUE THREAD

**Issue by maneleleina01** [inorichi/tachiyomi#924]
Whenever i open any manga in the source mangago the message that is stated in the sceenshot appear, i can't read online and can't download too
Version: r1188

![screenshot_2017-08-09-16-59-44](https://user-images.githubusercontent.com/30871928/29131702-9b622204-7d25-11e7-8b5a-d676358743ba.png)

**Comment by inorichi** [comment]
Mangago is an extension and it should be reported, so this issue must be reported in that repository.

**Comment by maneleleina01** [comment]
How do i do it please?

**Comment by inorichi** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues

There's one issue open already though.
