### ISSUE TITLE
Chapter Naming Scheme

### ISSUE THREAD

**Issue by DamSenViet** [inorichi/tachiyomi#925]
Could we have the option to have the chapters renamed by chapter order instead of it taking the chapter name directly from the source? There are certain naming schemes from sources that are inconsistent. E.g. using 0 then 100 for chapter numbers as opposed to 000 then 001 (digit inconsistencies vs same digit numbering). It'd be nice to have it use chapter number instead of the direct source like how it's implemented in the display mode.

**Comment by 444nonymous** [comment]
I agree. Related to https://github.com/inorichi/tachiyomi/issues/918#issuecomment-321201396

**Comment by inorichi** [comment]
The displayed number in display mode isn't reliable, and I don't like inconsistencies.

Also I don't see where this would be useful.

**Comment by DamSenViet** [comment]
Lets say that my primary reason for using this app is for bulk downloading manga for storing purposes and not just to read it (which it really is). When I transfer it over to a PC, its typical that the PC uses the naming scheme to sort the folders. If I cut and paste the files from my phone to my PC there's the possibility that the order will be thrown off (hence why sort by name may be more reliable in this use case). If the naming/numbering schemes are inconsistent as I mentioned, it throws off the sorting order and then I have to go look for the correct chapter manually (or rename the chapters manually).

I wish these sites would implement a consistent numbering and naming system so that it was convenient for their readers but I digress. Different use case, different benefits.

I completely understand that it isn't easy to implement considering you would have to figure out the numeric order for chapters that are extras like omakes/tanks and account for the occasional missing chapter(s).

**Comment by arkon** [comment]
Closing in favour of #2043
