### ISSUE TITLE
Sharing option isn't working 

### ISSUE THREAD

**Issue by bgilc** [inorichi/tachiyomi#928]
Tachiyomi v0.6.1

Steps to reproduce:

1. Open some manga (tried only local manga) in Tachiyomi.
2. Press and hold your finger on screen. A window will be displayed with "share" option.
3.  Choose "share" and then select one of available options (gdrive, one drive, send to pictures, gmail etc).

Result:
Nothing happens.

**Comment by UnrealPowerz** [comment]
Doesn't seem to be a problem in the latest dev build.

**Comment by OrbitalBlanc** [comment]
Well for me it's the same with latest dev build.

**Comment by wopian** [comment]
On 1184, it's an unknown file format for everything - Drive receives `f93c97ab500bc4a72a877cdfbf8eea37.0`

**Comment by OrbitalBlanc** [comment]
I would like to note that I'm talking about a local manga not a online source.

**Comment by wopian** [comment]
Sharing local manga is working fine for me on 1184
