### ISSUE TITLE
Bug : In webtoon viewer, changing orientation reset current page

### ISSUE THREAD

**Issue by kakek** [inorichi/tachiyomi#93]
I use webtoone viewer.
When I rotate my phone in the middle of a chapter, to view a page in landscape, the chapter goes back to page 1.
This doesn't happen with other viewers.

Also, I take the occasion to tell you this app is amazing. So close to perfect in so little time. Thanks so much for your work, and also for making it open source. I'm currently trying to understand how it works,  but it seems my coding skills are lacking. If it doesn't take you to much time, maybe you could slip a few comments in the code, to help noobs like me ?

**Comment by j2ghz** [comment]
#49

**Comment by Bloodwork** [comment]
We already have a thread for all Webtoon issues. #71
