### ISSUE TITLE
[Feature Request] Contact

### ISSUE THREAD

**Issue by HunterKurza** [inorichi/tachiyomi#931]
Any chance of adding an inapp way of allowing us to contact you?

**Comment by j2ghz** [comment]
What are the benefits of doing so?

**Comment by HunterKurza** [comment]
@j2ghz An easier way to contact the devs. Github is more for development requests and development in general.

**Comment by j2ghz** [comment]
Do you mean something like link to the discord server #944 in Settings > About? That is planned if the server is a success. Or something else?

**Comment by HunterKurza** [comment]
I mean that should be done as well but I do think there should be a way to specifically contact the devs as well

**Comment by inorichi** [comment]
I'll add a link to the discord channel, but that's it.

**Comment by inorichi** [comment]
Link added.
