### ISSUE TITLE
App Icon Update

### ISSUE THREAD

**Issue by EddJack** [inorichi/tachiyomi#934]
![tachiyomi](https://user-images.githubusercontent.com/30783525/29311609-74da827a-8167-11e7-929e-357f609254d7.png)
Circular version of the app icon for anyone who wants it

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by Efreak** [comment]
I don't know that Tachiyomi especially needs a new icon, however I do think the *debug version* (which I get thru fdroid) could use a new icon and/or app name, to differentiate it from the stable version.

**Comment by inorichi** [comment]
We have an adaptive (circular) icon already so... closing.
