### ISSUE TITLE
[Feature Request] 1-Finger Zoom

### ISSUE THREAD

**Issue by HunterKurza** [inorichi/tachiyomi#935]
Any chance if having one finger zoom implemented similar to how Manga Watcher does it?

**Comment by inorichi** [comment]
I don't know how Manga Watcher does it, but I'm not going to change anything there. One finger zoom is already possible with a tap followed by dragging upwards or downwards.

**Comment by HunterKurza** [comment]
@inorichi They basically have it set up so you can hold ghe screen for a split second and then drag up or down to zoom in or out respectivly.
