### ISSUE TITLE
Select All Above/Below

### ISSUE THREAD

**Issue by jasonhpchu** [inorichi/tachiyomi#939]
Version: r1199

When you long press select a chapter, the three dots should add an option to let me select all above/below the currently selected chapter.

I'm new coming in from another manga reader, trying to add in my progress.
But if you got a massively long manga, and you're in the middle of it, it becomes impossible to tell tachiyomi that you've read up to 300 of say a 600 chapters manga.

Thanks!

**Comment by inorichi** [comment]
> But if you got a massively long manga, and you're in the middle of it, it becomes impossible to tell tachiyomi that you've read up to 300 of say a 600 chapters manga.

`Mark previous as read` is there for that reason.

**Comment by jasonhpchu** [comment]
*facepalm*
Sorry about that.  Was so fixated on long press selecting it that I didn't notice the three dots next to each chapter.
Thanks.
