### ISSUE TITLE
[Feature Request] MAL Updater

### ISSUE THREAD

**Issue by jfields99** [inorichi/tachiyomi#942]
Automatic or manual MyAnimeList updater, to update on MAL what manga you're reading, how far you've read, and what date you start / finished it.

**Comment by cd0rw0** [comment]
hi,

ist this already in tachiyomi ?

U login your MAL id in setting>MAL
and open any manga go to "tracking" tap and update manga info.
done.
after this your MAL account will auto update for that manga.

**Comment by jfields99** [comment]
Oh wow, I was over a year out of date. Thanks!
