### ISSUE TITLE
"All" Manga Tab

### ISSUE THREAD

**Issue by cd0rw0** [inorichi/tachiyomi#943]
All Manga

it would be convenient if all saved manga in 1 fixed place by default regardless of their categories.
this would help user 
- search saved manga ( currently after key in search, we need to changed categories 1 by 1)
- identify duplicate manga from different source

Thanks

**Comment by CarlosEsco** [comment]
I like this idea.  I dont use categories but can see how its useful will look into.

**Comment by ShakeBake** [comment]
Cant we already do this? Make a default catagory called all and automatically add all subsribed manga to that as default. Then you can use multiple tags to both move the manga to a desired catagory and still keep it in the 'all' catagory.

**Comment by cd0rw0** [comment]
since its manual & bound to human error.

**Comment by CarlosEsco** [comment]
Yea my plan was to rewrite so every manga was always in default, and you could "move" into other category but default would always have all.

**Comment by inorichi** [comment]
It's easier to have a switch (probably in the overflow menu of the toolbar) and then a few changes to the library presenter to fetch the data with or without categories.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
