### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by HunterKurza** [inorichi/tachiyomi#944]
Would you like me to set up a Discord server to be able to better communicate with your users?

**Comment by j2ghz** [comment]
Duplicate of #50 I guess

**Comment by inorichi** [comment]
I don't mind if you do. I never used it so I don't know if I would join.

**Comment by ReGtrs** [comment]
That would be a good idea since I'm an active user in discord.

**Comment by j2ghz** [comment]
I went ahead and created it: https://discord.gg/WrBkRk4
My idea is that the primary function should be as a user-moderated support place. So I created @support role that anyone can mention, the main channel is #support. Should also other channels for miscellaneous discussions be created?
What do you think?

**Comment by HunterKurza** [comment]
@j2ghz Yeah, I use Discord every day. Add me at HunterKurza#9665 and Ill help you set everything on the server up

**Comment by j2ghz** [comment]
@HunterKurza Click the [![Discord](https://img.shields.io/discord/349436576037732353.svg)](https://discord.gg/WrBkRk4), it's a link to the invite.

**Comment by HunterKurza** [comment]
I dont see it?

**Comment by j2ghz** [comment]
@HunterKurza Click this: [![Discord](https://img.shields.io/discord/349436576037732353.svg)](https://discord.gg/WrBkRk4)

**Comment by Enamex** [comment]
It might not be very non-dev friendly (OK, it isn't meant for that use at all) but we could have one on Gitter as well.
