### ISSUE TITLE
Reopening app from launcher closes manga reader.

### ISSUE THREAD

**Issue by tippl** [inorichi/tachiyomi#947]
**Description**
When opening Tachiyomi from launcher and it is already open in a manga reader, the manga reader is closed and list of chapters is shown.

**Steps to reproduce**
1. Open a manga and select a chapter
2. Close the app using the home button
3. Open Tachiyomi again from the app launcher

**What happens**
The app opens in the chapter list view instead of the manga reader.
If the reader has been opened by the "continue reading" button the circular animation is reversed to show reader closing as the app opens.

**Expected behavior**
The app opens in manga reader at the page it was left at, as it does when relaunched from the recents menu.

**Notes**
From what I remember, this has worked before updating to Android 8, so this may be a regression.
However I tried testing this using the Android virtual machine on api levels 25 (7.1.1) and 26 (8.0.0), and the issue appeared on both, so i am not that sure about my previous statement.

Version: v0.6.1
Android: 8.0.0
Phone: Nexus 5X
[Video](https://streamable.com/u7axs) showing issue.

**Comment by tippl** [comment]
I ran a bisect on this, here is the [log](https://pastebin.com/raw/TmkGgvwb).

**Comment by askhavok** [comment]
This has always happened to me, PureNexus 7.1.2
