### ISSUE TITLE
YMAL extention for readcomics.website

### ISSUE THREAD

**Issue by somevik** [inorichi/tachiyomi#948]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by j2ghz** [comment]
@somevik What about it?

**Comment by somevik** [comment]
readcomics.tv Yml file is not working i tried changing the url in that yml file and i found that it doesnt  work that way so need Ymal file for this comic site plzzz.... readcomics.website

**Comment by j2ghz** [comment]
YAML sources are deprecated, see https://github.com/inorichi/tachiyomi/wiki/YAML-Sources

Also:
> Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting
