### ISSUE TITLE
The App Icon doesn't look like it's following material design.

### ISSUE THREAD

**Issue by Waynekosimoto** [inorichi/tachiyomi#950]
I've never been on this repo and I just found out that @EddJack made a circular icon but, it too isn't following the material design guidelines. Since I have experience on making icons for Android apps, I wanted to share my redesign. I made them in two colors, blue and red. Circular and traditional.

![red](https://user-images.githubusercontent.com/12769365/29695008-aa5f77ca-8905-11e7-87a0-e7915a799445.png)
![blue](https://user-images.githubusercontent.com/12769365/29695012-ad76a7d0-8905-11e7-97f9-d67761ce915a.png)
![red c](https://user-images.githubusercontent.com/12769365/29694822-aa729bd0-8904-11e7-9378-ec6498c66b3e.png)
![blue c](https://user-images.githubusercontent.com/12769365/29694825-add52b58-8904-11e7-8dce-e231b8de1dc9.png)

If the dev wants to implement this I'm fine with it. They're in a 512 x 512 format so that they can be downscaled into xhdpi xxhdpi, etc.

**Comment by rouji4256** [comment]
I like the design though I would prefer if they were flat icons instead of the 3D pop effect.

Favourite one is the 2nd one!

**Comment by 444nonymous** [comment]
I like these ones with 3D effect more. The round one looks more symmetrical and balanced.

**Comment by Waynekosimoto** [comment]
@CarlosEsco These are built with code and a grand majority of apps haven't moved to this new "standard". Free Form icons are still allowed (that's why the icon tab in the material design guidelines still have the free form style) but they will __eventually__  be treated as 2nd class citizens on Android.

**Comment by CarlosEsco** [comment]
@Waynekosimoto agreed they are built with code but they are 2 different drawables with different dimensions then the standard icons so my suggestion was to convert this to the new format.  So they could be integrated in.

**Comment by Waynekosimoto** [comment]
@CarlosEsco I didn't ask what they are. I didn't realize that Android Oreo was pushing for this so quickly, I'll adapt them.

**Comment by Jendrej** [comment]
Uh, but what’s wrong with the current icon? I like it. The ones you made look blank compared to the current one.

**Comment by fighuass** [comment]
+1, but I'd choose the 2D over the 3D one.

**Comment by inorichi** [comment]
Sorry, no plans to update the icon for the current version. Maybe 1.x will have something different, but I will ask LinkCable when it's the time for that release.
