### ISSUE TITLE
Backup/Restore bug with tracking

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi#951]
Version: latest dev version

Hi, 

I think I found a bug with tracking when restoring from backup.
Dunno if this one "works" in MAL or not, but Im using anilist.

Reproduction:

1. add manga to anilist.. it set your Tracking status as reading.
2. if you read manga, it tracking your progress, thats good.
3. make backup
4. restore to new device (clean one, without db)
5. status will disappear from tracking information = no reading status = even if you continue reading new chapters, it doesn't add anything to "chapters" in tracking

EDIT: if you manually change "chaters" count in tracking without reading status = app will crash 

![inyrilx](https://user-images.githubusercontent.com/7014826/29702567-2520fea4-8972-11e7-8e98-5814cb5389bd.png)

**Comment by inorichi** [comment]
In Settings > Advanced you can refresh tracking data. Status and score isn't stored in the backup yet.
