### ISSUE TITLE
Java Error when loading a manga with Batoto

### ISSUE THREAD

**Issue by Asbesbopispa** [inorichi/tachiyomi#953]
Here's a screenshot: http://i.imgur.com/MKBkOyK.png

I remember this issue was solved by updating some time ago but the Dev version has the same error.

Version: 0.6.1
Android 6.0

**Comment by Drfate13** [comment]
Same here

**Comment by Asbesbopispa** [comment]
Can I close the issue?

**Comment by j2ghz** [comment]
No, since this is the first report, and it's not fixed yet. Valid reports are closed by whoever commits the fix.
(Closed on pull request mean rejected, merged would mean accepted)

**Comment by Asbesbopispa** [comment]
Ok, thank you.

**Comment by dtrazzi** [comment]
Getting it here as well.

**Comment by dekza456** [comment]
So, Is this problem solved and where I can download the Fixed App version?

**Comment by j2ghz** [comment]
It *should* be fixed, you can download the dev version to test it.

**Comment by Leverpastej** [comment]
Same for me too and I run version r1200, build 20 Aug 2017 15:47

**Comment by j2ghz** [comment]
The latest version is r1202.
http://i.imgur.com/KL0xqkz.png

**Comment by Asbesbopispa** [comment]
It works with r1202 http://i.imgur.com/LESTAMR.png

I can search without problems and update the chapter list.

**Comment by replis** [comment]
I had the same issue. Now, with the r1202 it has been fixed. Thank you.

**Comment by Llethander** [comment]
Checking for updates using v0.6.1 finds nothing, is a fix going to be pushed to the app or should I just install the Dev build and start re-following the manga I have bookmarked?

**Comment by Asbesbopispa** [comment]
You can backup your manga in tachiyomi; do it, install the Dev version and restore it, then wait for the next stable.

**Comment by Llethander** [comment]
Oh, that's awesome. I didn't even realize it was possible to backup. Thanks!

**Comment by Acoha** [comment]
The bug seems to have been fixed on batoto. I'm on version .61 and it's now working correctly.

**Comment by Asbesbopispa** [comment]
I confirm, just tried it.
