### ISSUE TITLE
No results (images, titles, anything) when searching Batoto or viewing the catalog homepage

### ISSUE THREAD

**Issue by Enamex** [inorichi/tachiyomi#957]
Version: r1200.
Android 4.2

Batoto's catalog home screen and search results screen stopped showing any titles (no text, no images, nothing) The notification bar that shows at the bottom of the app does show with the 'retry' button, but there's no error message.

Note that:
bato.to is not down;
I'm logged in;
I can read manga on Batoto that I'd bookmarked before (online; not downloaded).

**Comment by j2ghz** [comment]
Could be duplicate of #953 
Also latest version is r1202 so please try that. http://i.imgur.com/KL0xqkz.png

**Comment by Enamex** [comment]
I'd downloaded the latest just 8 hours before submitting this :'D

It _might_ be #953 but I'm not getting a Java error. It just doesn't load (and shows the 'retry' button in the same place as it would if it were an error with a message).

**Comment by Enamex** [comment]
This's fixed at or before r1204 👍 .
