### ISSUE TITLE
Set previous chapters as read

### ISSUE THREAD

**Issue by ArathoN** [inorichi/tachiyomi#96]
In mangawatcher there was an option to set the previous chapters as read automatically after setting a chapter as read. This would be really useful for long mangas like One Piece where you'll have to select a lot of chapter to set them as read/unread.

**Comment by j2ghz** [comment]
Already exists on debug, not sure if on release too

**Comment by ArathoN** [comment]
yeah you are right, never thought to check what lies behind these 3 dots, I always used the other "general" menù (not the one relative to the single chapter).
