### ISSUE TITLE
Issue with reader

### ISSUE THREAD

**Issue by Rinto-kun** [inorichi/tachiyomi#962]
Page slider has the same color as the UI after updating to Nougat v7.0 (Samsung ver.)
![screenshot_20170820-130842](https://user-images.githubusercontent.com/17642766/29869023-dff3c2b4-8d89-11e7-8287-9a8b3447143a.png)

**Comment by inorichi** [comment]
#544.

**Comment by inorichi** [comment]
There is a "hack" around it in the mentioned issue but I don't like it. That said, shouldn't most of the devices with Nougat be running API 25?

**Comment by Rinto-kun** [comment]
Mine was just updated two weeks ago so I don't know.
