### ISSUE TITLE
Random/Surprise-me Feature

### ISSUE THREAD

**Issue by vkk1903** [inorichi/tachiyomi#964]
Implementing a feature which brings Random Manga. This feature will be available after selecting a catalogue. 

Category wise Random will be more logical and useful. 

'Random' button can be accommodated in Filter drawer.

Clicking on 'Random' button will choose any random Manga from list of Manga that would have appeared after clicking 'Search' button. 

eg. One select Action and Comedy categories from Filter Drawer , Then tap Search . It will bring a list of many Manga - Let's say Manga 1 , 2 , 3 , and 4 
But if Random button is tapped it will show Manga 2 directly without showing search result.

**Comment by ayuhsya** [comment]
@j2ghz Is this a reasonable feature? Would like to take this up.

**Comment by j2ghz** [comment]
If you want to be certain it's a feature that would be accepted you have to ask the owner @inorichi or the collaborator @NoodleMage (as opposed to contributors which have 0 permissions)

It seems reasonable, but there are technical limitations (you have to load all results to be able to choose one randomly) and for sources that have "Order by > Random" it'd be duplicate functionality. So I'm not sure.

**Comment by ayuhsya** [comment]
Ah, I understand.
Loading **all** the results was my concern too. Otherwise, the result will not really be random.

**Comment by inorichi** [comment]
There's no simple way to implement this unless we have an entire copy of the catalogues (which we don't have). As @j2ghz said, it's only possible if the sources implement some random order.
