### ISSUE TITLE
Hide chapters

### ISSUE THREAD

**Issue by askhavok** [inorichi/tachiyomi#967]
[Screenshot](http://i.imgur.com/l71TbyW.png)

Se how chapter 37 and 32 have two versions? It would be convenient to be able to hide one of them for a more seamless read.

**Comment by CarlosEsco** [comment]
Just click those marked as read

**Comment by ShakeBake** [comment]
For the webtoon reader at least, even when it's marked as read it still reads through them. But I just click the Next button on the quick bar when that happens.

**Comment by askhavok** [comment]
This is true, I thought it fixed it at first but it didn't do anything of the sort.
