### ISSUE TITLE
Wrong Last Chapter

### ISSUE THREAD

**Issue by vkk1903** [inorichi/tachiyomi#968]
Know Example of Error - 

Magi on KissManga Catalogue . 
Visible Chapter count on Manga Info Page : 98005
Actual Count : 363

This error is not found on any other instance currently. But possiblity of other wrong count is there. 

Tachiyomi - v 0.6.1-1209 ( Dev Version )

**Comment by j2ghz** [comment]
There is a chapter between 98 and 99: `Magi 098005` which is parsed to chapter number 98005, which would make it the latest chapter. It's also called last chapter, not chapter count.
