### ISSUE TITLE
Bug: Chapters not oppening

### ISSUE THREAD

**Issue by Soumatan** [inorichi/tachiyomi#97]
Downloaded the latest debug and encounter that chapters will crash upon upening. When I open one chapter it start to open the image (and sometimes show the image) but then the app either crashes or  just says "Unfortunately, Tachiyomi has stopped" and everything else continues working except actually opening the chapter. It does this even if the chapter is downloaded  and with different sources.

I'm using Moto x  2nd gen with android version 5.1

**Comment by inorichi** [comment]
Try disabling the lock rotation option or image decoder

**Comment by Soumatan** [comment]
Changing the Image decoder to Skia fixed it. Rapid is the one that is damaged then, tho isn't rapid the better one of the two?

**Comment by inorichi** [comment]
Does it also happen on the stable version? Some chapters will be better with Skia and others with Rapid. Read [here](https://github.com/inorichi/tachiyomi/blob/master/libs/SubsamplingScaleImageView/src/com/davemorrissey/labs/subscaleview/decoder/RapidImageDecoder.java) for an explanation. It's from an example of the Subsampling library. I don't know any more than that.

**Comment by Soumatan** [comment]
No, it does not happen on the stable. I update my debug app daily so it was probably in one of the update in the last 24-30 hours that did that to rapid decoder.

**Comment by inorichi** [comment]
Yeah, I know. [This is the commit.](https://github.com/inorichi/tachiyomi/commit/bcefc176c169d42117b9236833178c9a607cb147) I will test it for a while, if it's too unstable I will revert the commit.
