### ISSUE TITLE
Back Button Twice, Search Button Disappears

### ISSUE THREAD

**Issue by mafudadagronslaya** [inorichi/tachiyomi#971]
Ver. 0.6.2
Android Version 7.1.1

If you go to Catalogues > choose any source > Search Button > search for anything > tap on any manga > tap back button twice, the Search Button that is supposed to be on the top ribbon has disappeared.

I haven't tested this on another device yet. Seems easy enough to replicate and check, though.

**Comment by j2ghz** [comment]
Duplicate #908

**Comment by mafudadagronslaya** [comment]
Shoot, my bad.
