### ISSUE TITLE
Problem displaying chapters after update

### ISSUE THREAD

**Issue by redlee13** [inorichi/tachiyomi#973]
After I updated the app to version 0.6.2 yesterday, I noticed my chapters are not being displayed as downloaded, the app does not recognize the old downloaded chapters. 

I downloaded chapter 15 again to display the problem. 

![in the explorer](https://user-images.githubusercontent.com/13471815/30247591-abf17642-9620-11e7-97d7-ea6c3a930ccc.png)

![in the app](https://user-images.githubusercontent.com/13471815/30247634-6a653410-9621-11e7-8cf4-af2f8c1d7b3f.png)

**Comment by inorichi** [comment]
I guess you're using Mangafox. The parser was edited to include chapter titles, so now your folders don't match the titles and chapters can't be found. You'll have to either redownload everything from that source, or move them to the local manga folder and read it as a local manga.

**Comment by inorichi** [comment]
"Resolved" on discord.
