### ISSUE TITLE
[Feature Request]Sync between pc and android phone/ bookmarks

### ISSUE THREAD

**Issue by TheMiziko** [inorichi/tachiyomi#975]
I would love to be able to either sync my watched chapters on some kind of account to browse my manga on pc via  android emulator, or way to sync my watched chapters on website like mangasee or other available sources for manga  with account creation and bookmarks so that I would know where I finished reading :)

**Comment by j2ghz** [comment]
Duplicate: #912

**Comment by TheMiziko** [comment]
@j2ghz Oh, thank you for the info ! I browsed all the requests beforehand to make sure Something like this would not happend , but it seems I still missed it in swarm of other issues and posts :D 

Hope you will consider it somewhere in future !
