### ISSUE TITLE
Tachiyomi for IOS?

### ISSUE THREAD

**Issue by GurRman** [inorichi/tachiyomi#979]
Do you plan to release Tachiyomi for IOS?

**Comment by j2ghz** [comment]
Same case as #416, there would be nothing in common between those two apps, so probably no

**Comment by AmineI** [comment]
Just passing by, I have absolutely no interest in an iOS app but wanted to let you know that frameworks like Xamarin (I believe) as used in [MALClient](https://github.com/Drutol/MALClient/) allows a single codebase to be used for iOS, Android and UWP clients. But I think it would actually still require a rewrite of the app, so not happening as well.

**Comment by CarlosEsco** [comment]
It would xamarin is c#

**Comment by GiuseppeLaurenza** [comment]
Any novelty on this topic?

**Comment by arkon** [comment]
No.

**Comment by MercerBoi** [comment]
No.

**Comment by xiamaz** [comment]
Kotlin Native does exist: https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html

This would only require a reimplementation of the UI/UX, which would still be able to leverage the extension architecture and possibly unify adding support for a large number of websites.

**Comment by CarlosEsco** [comment]
Don't you have to jailbreak still to install apps outside the app store?

**Comment by c0sm05** [comment]
You could use Cydia Impactor for sideloading iPAs (basically the apk of iOS) to non-jailbroken devices but you would still have to port the app to iOS though, which is the main problem of this issue http://www.cydiaimpactor.com/

**Comment by CarlosEsco** [comment]
@c0sm05  i know that it needs ported, i contribute to the app.  I was asking cause as you see its a pretty big hassle to side load an app to iOS

**Comment by GiuseppeLaurenza** [comment]
I think you can publish the app on "https://www.tweakboxapp.com <https://www.tweakboxapp.com/>”, it is an alternative store that works without jailbreak.

**Comment by joseph619** [comment]
So Tweakbox is like FDroid of iOS? But we don't maintain FDroid releases anymore, who is going to maintain Tweakbox?

**Comment by arkon** [comment]
It'll be hard convincing any of the contributors to port this to iOS. If it's something that somebody else wants to take on that'd be nice.

v1.x should have more reusable modules that aren't as Android-specific, so that might be useful.

**Comment by joseph619** [comment]
Given that we already abandoned FDroid, you're right nobody will be interested in porting this, let alone maintain

**Comment by tcyrus** [comment]
[Kotlin Native Tutorial](https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/01_Introduction)

**Comment by vinaysb** [comment]
Is anyone working on this using kotlin/native?

**Comment by joseph619** [comment]
Nobody is working on this, and nobody will.
