### ISSUE TITLE
Feature Request: Batch select download

### ISSUE THREAD

**Issue by kevinhy01** [inorichi/tachiyomi#980]
This would be pretty great especially if you're in the middle of a series or something. I apologize if it's already in, but I've found no way to do it. It's a feature from mangarock that's so convenient (e.g selecting chapter 15 and 45 downloads everything from 15-45).

**Comment by CarlosEsco** [comment]
long press the 1st chapter
then press on each chapter you want to download
then click download button

**Comment by NoodleMage** [comment]
You can also click download in the dot menu to the right. Next you can select download 5 > 10 > unread > all

**Comment by kevinhy01** [comment]
I mean something different. Currently if I want to downlod say, 600-750 there's no convenient way to but clicking every single chapter, which is tedious as hell. It'd be nice to be able to press 600 and 750 and everything in between would be selected. Stuff like Tomo-chan is ridiculously long since it's 1 chapter a piece, so there's not quick way to select chapters unless it's a completely new series.

**Comment by inorichi** [comment]
If you have read up to chapter 600, click the 3 dot menu in that chapter and select "Mark prevous as read". Then in the "Download" button select "Download unread".

I don't think we need to add more options when it can be achieved with a few steps.
