### ISSUE TITLE
Request: Local manga naming

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi#981]
Hello! I noticed that on local manga if a chapter is called lets say "Awesomeness Chapter 1" and is placed inside a folder called "Awesomeness" that the chapter list will no longer show the full name and just start at the first non space character after the name (in this case "Chapter 1") to save on needlessly wasted space, which is really cool!

Is it possible to have it omit specific characters along with the spaces? Like if the manga was called "Awesomeness - Chapter 1" it will now show as "- Chapter 1". Not a big deal at all! But if it was something simple like adding "-" (and maybe "_" as well if it isn't already) along with spaces as characters to skip before starting the chapter name from the file name then it might be worth it since its a really common naming scheme.

Thanks!

**Comment by inorichi** [comment]
Yes, it seems reasonable.

**Comment by ayuhsya** [comment]
@BaronKrause @inorichi Hello! I'm trying to resolve this. Can you point me towards some downloadable manga with such filenames - `Awesomeness - Chapter 1` so that I can test it? Thank you.

**Comment by j2ghz** [comment]
@ayuhsya Just get whatever manga and then rename the folder or archive

**Comment by BaronKrause** [comment]
You can't blame him for trying to gain access to the super amazing "Awesomeness - Chapter 1".
