### ISSUE TITLE
[Feature Request] Sort by Source 

### ISSUE THREAD

**Issue by cd0rw0** [inorichi/tachiyomi#984]
Hi,

currently to identified manga source in library we have to open 1 by 1.
option to sort by source will resolve this.

TQ

**Comment by ddmgy** [comment]
This is something I have also wanted before, so I have opened a pull request to add an option to sort by source.

**Comment by cd0rw0** [comment]
@ddmgy  thanks for #985

**Comment by NoodleMage** [comment]
Please don't close before pull is merged
