### ISSUE TITLE
Choose Latest Updates as start screen

### ISSUE THREAD

**Issue by Izuni** [inorichi/tachiyomi#987]
**Please read https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md before posting**

**Comment by Izuni** [comment]
I think it would be nice to have "Latest Updates" as a start screen option similar to MangaRock. I personally enjoy browsing recent manga updates to find new titles to read.

**Comment by Izuni** [comment]
![screenshot_20170920-025457](https://user-images.githubusercontent.com/32124011/30632857-2d26cfec-9daf-11e7-9bc8-818006ad18f6.png)
This is how it looks like for MangaRock but it became inconvenient for me anyways after the recent redesign.

**Comment by NoodleMage** [comment]
Not applicable with new design
