### ISSUE TITLE
Pages wont load ocasionaly

### ISSUE THREAD

**Issue by ShakeBake** [inorichi/tachiyomi#989]
Sometimes (about once every 10 or 20 chapters) when reading a manga a random page will appear blank without a retry button. I solve this by backing out and continuing the chapter, in effect reloading the bonked page. Another perhaps related bug occurs when reading 4-koma single page manga. Every several pages/chapters the next one won't load and I have to tap the next chapter button to force continuation.It happens almost every couple of pages for the 4-koma. Changing orientation fixes it for a few pages then it stops again.

I've also noticed that while reading normal length chapter when it happens, scrolling forwards 5-10 pages and then back, the image is fine amd properly loaded. I've tried changing the image processor but no change. 

A useful feature would be a permanent retry symbol that will force reload the currently viewed page regardless of if its been downloaded or not.
Using webtoon reader in landscape.

**Comment by ShakeBake** [comment]
It happens almost every couple of pages for the 4-koma. Changing orientation fixes it for a few pages then it stops again.

**Comment by ShakeBake** [comment]
Same thing happens with the 4-koma with other viewers but using the volume keys gets past the issue as it is in effect a next button.

**Comment by ayuhsya** [comment]
This seems similar to #990. I think a retry button on the action bar can solve both the issues.

**Comment by ayuhsya** [comment]
Or a button to directly open in the browser might be better. 🤔

**Comment by CarlosEsco** [comment]
closing this for now as this very old and there has been lots of changes since

**Comment by scb261** [comment]
Probably the same as #2614. Just linking issues together
