### ISSUE TITLE
Downloading multiple chapters: app pulls them in the wrong order

### ISSUE THREAD

**Issue by roseyhead** [inorichi/tachiyomi#99]
For example, I'm downloading One Punch Man. Already read chapters 1-49 so I mark them all as read, set to show unread, select all and hit Download. It starts downloading from chapter 86 and works backwards from there until it finishes at 50. Might be nice if it started at the oldest chapter and went forward from there so you can read while it downloads.

(If you reverse the chapter list so it shows old chapters at the top and new chapters at the bottom it adds them to the download queue in this order.)

**Comment by voodoobs** [comment]
I'd like to see this implemented as well.
The only way to get it to download in order of lowest chapter first is to download the chapters one by one, which can be quite time consuming.

**Comment by inorichi** [comment]
For now, invert list, select all, download.

**Comment by voodoobs** [comment]
Oh, wow.
I didn't even think of that. Thanks -- this became almost a non-issue for me then.

**Comment by j2ghz** [comment]
* [ ] The download next / next 5 / next 10 / unread / all chapters ignores sort and always downloads higher number chapters first
