### ISSUE TITLE
re-download single page/page corrupted

### ISSUE THREAD

**Issue by DarKCroX** [inorichi/tachiyomi#990]
reason: image corrupted sometime
![ss](https://user-images.githubusercontent.com/11861402/30731113-f8360dd4-9f9d-11e7-8970-d4b29d05d008.png)

**Comment by askhavok** [comment]
Have you tried checking if its the source your using and not the download?

**Comment by DarKCroX** [comment]
Source: mangahere
Because the image is corrupted, I usually just delete the chapter, and read online... so I don't think the problem at the source.
