### ISSUE TITLE
When selecting a file for backup an option doesn't come for my files.

### ISSUE THREAD

**Issue by NfernoFire** [inorichi/tachiyomi#994]
basically what the title says. When I tap restore backup, no option comes to select it from my files 
![screenshot_2017-09-25-23-37-34](https://user-images.githubusercontent.com/21341806/30829932-c45ff404-a1ee-11e7-8b51-ea6e6d4677d2.png)
I am using the dev version of tachiyomi if that helps from F.droid and am running Android version 4.4.2

**Comment by NoodleMage** [comment]
You're version of Android probably doesn't have an file explorer. Install something like solid explorer or anything that is not ES explorer. Sadly we can't do anything about this without (imo ugly) workarounds.

**Comment by kyapako** [comment]
Ok no problem. I thought it was a problem with the app. Looks like I'll need to upgrade my phone lol.

**Comment by NfernoFire** [comment]
Ok thank you. I thought it was a problem with the app itself. Looks like I'll need a new phone lol.
