### ISSUE TITLE
Notifications don't appear

### ISSUE THREAD

**Issue by dobbleg1000** [inorichi/tachiyomi#995]
I have Android 8.0. I am on the current Dev build. Updating my library no longer gives me any progress notifications and on completion doesn't say what it found.

**Comment by inorichi** [comment]
You probably blocked notifications for Tachiyomi.

They work fine in the emulator.

**Comment by dobbleg1000** [comment]
I already checked the Android settings and the app settings. They stopped when I updated a few days ago.

**Comment by dobbleg1000** [comment]
I switched off the dev branch and they work again.

**Comment by beepFTW** [comment]
I have this issue as well. I see that Android Oreo now requires the use of notification channels. 

https://stackoverflow.com/questions/43093260/notification-not-showing-in-android-8-oreo

Here is the app after I update library and refresh metadata.

![screenshot_20171006-183856resized](https://user-images.githubusercontent.com/7910502/31312323-c5c24eca-ab74-11e7-9eef-c7a6c1e719bd.png)
