### ISSUE TITLE
"unexpected url" push notification when attempting to download a chapter

### ISSUE THREAD

**Issue by jfields99** [inorichi/tachiyomi#996]
When I attempt to download a chapter from the mangahere source, it will error out and send me a push notification saying "unexpected url" and the chapter will not load.

Version: 0.6.3
Android 5.1.1

**Comment by baskervald** [comment]
I'm having this issue as well, with the addition of mangahere series only loading the first image of each chapter.

Version: r1224
Android 7.1.2

**Comment by mrskizzex** [comment]
Chiming in to say : Me too.

Version: 0.6.3
Android 7.1.2

**Comment by LakotaGray** [comment]
Same here. Issue occurs on 2 separate tablets with different manufacturer and android versions
