### ISSUE TITLE
Mangafox fails to load manga, blank error pops up for 1 sec

### ISSUE THREAD

**Issue by LopinRD** [inorichi/tachiyomi#998]
1.6.3 and latest build, both of them tested. I have all my mangas in mangafox. 

For some reason it loads the first page then fails, i get instant blank page with the retry button. Cant download since they get stuck and when trying to open the chapter again i get dumped back to the chapter list and i get a small blank popup message for 0.5 seconds, its empty, no message in it but something is going on. Sometimes the chapters load, sometimes they dont, spamming retry makes it work sometimes.

**Comment by Mistero5050** [comment]
![screenshot_20170928-091011](https://user-images.githubusercontent.com/6240983/30953676-3ba2f684-a42d-11e7-814b-a01f96427016.png)
I Aldo add this. Mangafox problem

**Comment by Basha0** [comment]
Same Problem, hope we can get a fix here

**Comment by NoodleMage** [comment]
Mangafox seems to be working again. Please let me know if it's the same for anyone else (thumbs up down). 

Please try a few times before saying it isn't working ;)

**Comment by cd0rw0** [comment]
1st try - working.

**Comment by Mistero5050** [comment]
Working
